### ISSUE TITLE
Catalog search should include results for harvest source url

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1009]
## User Story

As a catalog user, I want harvest source results to appear when searching for source URLs so that I can quickly find the harvest source in the catalog when all I have is a URL.

## Details
Searching for `https://meta.geo.census.gov/data/existing/decennial/GEO/GPMB/TIGERline/Tiger2019/cnecta/tl_2019_us_cnecta.shp.iso.xml` yields no results.

## Acceptance Criteria
- [ ] Searching for a URL will match against harvest source url

**Comment by adborden** [comment]
We'll take another look at this after we upgrade to a recent CKAN version.

**Comment by jbrown-xentity** [comment]
Would be nice to maintain that link in future harvester versions, tagging @btylerburton and @rshewitt for future discussion.
Closing this for now, as we don't intend to implement this in CKAN harvester.
