### ISSUE TITLE
dashboard logs CodeIgniter errors

### ISSUE THREAD

**Issue by pburkholder** [GSA/data.gov#1010]
## User Story

In order to make code-level errors visible to operators on cloud.gov, we want pod-dashboard to write CodeIgniter logs to stdout.

## Acceptance Criteria

* [ ] GIVEN I run the dashboard using docker-compose \
  WHEN CodeIgniter logs an error, it's visible in stdout
* [ ] GIVEN I run the dashboard in cloud.gov \
  WHEN CodeIgniter logs an error, it's visible in logs.fr.cloud.gov
* [ ] GIVEN I run the dashboard using php-fpm \
  WHEN CodeIgniter logs an error, it's visible in php-fpm logs on the host where the error occurred

---
Background: 

  * Currently the only logs for CodeIngiter apps in BSP are the Apache/Nginx logs. Logs from the apps themselves, namely, those written from `log_message` are not kept as the `config[log_threshold]` is set to 0 (zero) in BSP, and even if it were enabled, it would be written to a local log file. This means you don't get any code-level errors, like: 

          ERROR - 2019-10-01 12:21:29 --> Severity: Warning  --> fgetcsv() expects parameter 1 to be resource, boolean given /home/vcap/app/htdocs/application/helpers/csv_helper.php 44
          ERROR - 2019-10-01 12:21:29 --> Severity: Warning  --> Invalid argument supplied for foreach() /home/vcap/app/htdocs/application/helpers/csv_helper.php 48
          ERROR - 2019-10-01 12:21:29 --> Severity: Notice  --> Undefined variable: row_new /home/vcap/app/htdocs/application/helpers/csv_helper.php 52

  * Most PHP web apps will treat STDOUT as what gets passed to the web server and back to the client, which is why the log_message and write_log functions of CodeIgniter write to a specific path in application/logs. 

If we want these logs:
* update `system/libraries/log.php` for`log_message` to write to STDOUT, then
*  use the fpm.d tricks at https://github.com/cloudfoundry/php-buildpack/issues/256#issuecomment-372144456 and/or cloudfoundry/php-buildpack#202 to set FPM_CATCH_WORKERS_OUTPUT to yes.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
