### ISSUE TITLE
CI drives periodic runs of pod-dashboard tasks on cloud.gov

### ISSUE THREAD

**Issue by pburkholder** [GSA/data.gov#1011]
## User Story

In order to migrate the production deployment of the pod-dashboard to cloud.gov, we want to trigger periodic runs of pod-dashboard tasks using our CI system

**Acceptance Criteria:**

* [x] GIVEN I start a timer \
  WHEN 24 hours has passed \
  THEN I see that the cronjobs have run to completion since the timer started

## Details

There are two cronjobs: 
* `index.php campaign status cfo-act download` (takes about 5m)
* `index.php campaign status cfo-act full-scan` (takes a lot longer)

Cloud.gov doesn't have built-in [support for scheduling](https://network.pivotal.io/products/p-scheduler-for-pcf), so we can pursue a couple of other options for running the daily jobs. The one that got buy-in on Oct 2, 2019 was to use `cf run-task` from our CI/CD to launch a task instance.

This seemed easier to manage and track than using a scheduler internal to cloud.gov, or a janky cron job.

---
Background:
  * Cloud.gov doesn't have built-in [support for scheduling](https://network.pivotal.io/products/p-scheduler-for-pcf), so we can pursue a couple of other options for running the daily jobs. 
    * One option -- run a [worker process](https://docs.cloudfoundry.org/devguide/multiple-processes.html) that mostly sleeps, but checks every 30m if it's "trigger time" to run the daily tasks, as in [this example from cf-ex-drupal-8](https://github.com/18F/cf-ex-drupal8/blob/master/cronish.sh).
    * Whether it's triggered could be determined by whether a `cronish` table in the database has not had any updates in 24 hours.
    * For demo purposes, the code currently has a `cronish` app that just does the `download` job and then sleeps for 23h.
    * This `worker` process keeps running regardless of the stability of the `web` process, but uses the same droplet build.

**Comment by mogul** [comment]
The PR referenced above works fine. However, the crawls are taking longer than a fixed 300 second maximum to run, so they get killed and are marked `FAILED`. A couple options:

- Ensure all crawls can pick up where the last one left off, and run the task more frequently than just once per 24 hours.
  - This is my preference, as it also guards against running out of memory, etc. 
- Keep Peter's way of doing this, where there's a separate long-running worker process in the app for the crawls that is just `sleep`'ing most of the time. 
  - Although this works, it "feels" ugly, and it also means we'd have to be dedicating quota space to that crawler all the time.
