### ISSUE TITLE
Google Authenticator two factor authentication

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1026]
## User Story

As a Data.gov Operator, I want Google Authenticator configured for Jumpbox access so that access to Jumpbox is controlled by two explicit factors for two factor authentication (2FA).

## Details
This is stated in the SSP but not implemented.

## Acceptance Criteria
- [ ] All jumpbox operator accounts are configured with google-authenticator

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
