### ISSUE TITLE
Move test secrets to environment variables

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1028]
## User Story

As a developer, I want test secrets read from environment so that the secrets don't appear to be a leakage of credentials and cause false positives for scanning tools and bug bounty reports.

## Details
Two test secrets, could be read from environment instead.
https://github.com/GSA/datagov-deploy/blob/5fb6ab1545f11cfe9d11dea3daaa88c70797d265/ansible/.kitchen.yml

https://github.com/GSA/datagov-deploy/blob/5ec3c9c402fae4577b22816365d8134cb0fb0ad9/ansible/roles/software/ckan/inventory/molecule/resources/prepare.yml

## Acceptance Criteria
- [ ] No test secrets exist in source code.
- [ ] CI secrets are added to appropriate systems, with documentation.
- [ ] Clear, automated instructions to create test secrets for development exist.

**Comment by nickumia-reisys** [comment]
No more Ansible (and, by extension, ansible management of secrets),
- https://github.com/GSA/data.gov/issues/3710

All of our current secrets are managed by dedicated data structures on cloud.gov and by environment variables in application containers.
