### ISSUE TITLE
Harvesting and Data.json Backup

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#103]
## for Fetch and Harvest investigate
- [ ] High Availability 
- [x] Process persistance  (cron gather and fetch process dont respond after some idle time)

**Comment by kvuppala** [comment]
@JJediny on High Availability, what are we looking to consider?

**Comment by JJediny** [comment]
@kvuppala the need/ability to manage multiple harvesters with a queue. If we now find that a dedicated local redis with a large instance is sufficient for the foreseeable future lets close this one and rekindle if/when we start seeing the performance threshold

**Comment by kvuppala** [comment]
@JJediny with local redis, so far harvesting process is going smooth and would be sufficient.  I will close this for now, and open a new one if there is any need in future.
