### ISSUE TITLE
Configure Jenkins authentication with SAML/Login.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1031]
## User Story

As a Data.gov Operator, I want to access Jenkins through SAML/Login.gov so that our CI solution meets all the controls outlined in our SSP by leveraging a third-party service and reduces the number of controls we have to implement ourselves.

## Details
Jenkins has the [saml](https://plugins.jenkins.io/saml) plugin enabled, but it is not configured.

We currently don't use SAML within the sandbox environment, so we don't know exactly what challenges exit here, if any. We might go with user/password authentication for sandbox environments.

## Acceptance Criteria
- [x] Only authorized Data.gov team members can log in to Jenkins through Login.gov multi-factor authentication.
- [x] [datagov-deploy-jenkins](https://github.com/GSA/datagov-deploy-jenkins) is updated for automated configuration, if possible. Otherwise, documentation exists on how to configure it.

**Comment by adborden** [comment]
Some resources:
- [Data.gov MAX.gov Community page](https://community.max.gov/pages/viewpage.action?pageId=1109066197)
- [MAX.gov implementation guide](https://community.max.gov/display/MAXAUTH/Technical+Information)
- [MAX.gov Idp metadata](https://login.test.max.gov/idp/shibboleth)

I sent an email to the MAX.gov asking to clarify next steps. @FuhuXia and I plugged in some parameters into the saml configuration, but some configuration is needed on the MAX.gov side.

**Comment by adborden** [comment]
MAX.gov says they are using Jenkins themselves and will look into sharing their configuration and providing next steps.

**Comment by adborden** [comment]
Pinged MAX.gov folks.

**Comment by mogul** [comment]
@hkdctol volunteered to ping harder.

**Comment by mogul** [comment]
@hkdctol when you're back: Any word?

**Comment by adborden** [comment]
MAX got back to us. They are using CAS, not SAML, and with a modified plugin. I've sent them our SP metadata and config with a best guess for values I'm not sure about.

**Comment by adborden** [comment]
Uploaded SP metadata to our [MAX.gov Community page](https://community.max.gov/pages/viewpage.action?pageId=1109066197).

**Comment by mogul** [comment]
@adborden at this point is this issue blocked on action from the max.gov team?

**Comment by adborden** [comment]
That was the case, but I just saw an email this morning saying they update the metadata on their end, so it's back in our court.

**Comment by adborden** [comment]
I had to update the metadata, waiting on MAX again :(

**Comment by mogul** [comment]
This is stalled waiting for max.gov. However, since we're stopping work on this epic for a while, we're just going to icebox the issue and bring it up again at the point where we're relying on their response to unblock us restarting the work.

**Comment by adborden** [comment]
With Login.gov in the works, I'm curious if this will be less painful to implement. It's still a bit annoying but I started documenting this https://github.com/GSA/datagov-deploy-jenkins/pull/14

If SAML continues to be a thorn, I think using GitHub authentication would satisfy compliance requirements.

**Comment by mogul** [comment]
We're picking this up for a bit because when we have login.gov integration, the MFA support will be enough to enable use of Jenkins to drive the FCS environment.

**Comment by adborden** [comment]
https://jenkins-saml.sandbox.datagov.us is available and working with a manual configuration. I'm now polishing some PRs to automate this, although there are a few road bumps I can see:

**Ansible plugin install:** Once SAML is enabled, the admin user can no longer be used by Ansible to configure Jenkins. This really only has an effect on the plugins install, which are already installed. As a work around, you can run the playbook with `-e jenkins_plugins=[]` to effectively skip the plugins install.

**Build trigger:** I think our build trigger won't work with SAML because the crumb issuer (CSRF token issuer) is behind the SAML auth. Maybe there's another way to specify an API key. I'll test this.

**Storing encrypted keystore in Ansible is awkward:** The keystore is already encrypted, but I'm still encrypting it with the Ansible Vault. This makes the vault password rotation a little more complicated.

**Storing Jenkins secrets in configuration-as-code:** Jenkins has an encryption key stored in its data directory (we manage it as Jenkins data, not configuration). It encrypts any secrets, like passwords and credentials and stores the encrypted data in the XML configuration. This is what is specified in the configuration-as-code plugin, which means we can't generate secrets ourselves, we need Jenkins to do it (to do the encryption part), which effectively make credentials and saml configuration a manual step.

Tasks remaining:

- [x] Test application CI can still trigger jobs
- [x] Resolve the crumb issuer/crsf token issue with ansible jenkins_plugin install
- [x] Look into script for ansible vault key rotation

**Comment by adborden** [comment]
I updated with wiki on [ansible vault password rotation](https://github.com/GSA/datagov-deploy/wiki/Keypair-Rotation) to include the saml-key.jks. Next time we rotate the password would be a good time to explore a script.
