### ISSUE TITLE
post BSP migraton issues to be addressed

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#104]
## for Inventory
- [x] Datapusher issue on csv upload
- [x] crons configuration to resolve EOF SSL error, causing the application to give 500 error

## for Catalog
- [x] Emails are taking a lot of time to process, optimize to send one email per harvest job instead of multiple emails for each admin/editor/subscriber to receive emails
- [x] harvesting is switched to local REDIS queue to resolve the gather / fetch process getting into idle state.
- [x] crons configuration to resolve EOF SSL error, causing the CSW end point to give error
- [x] enable all the regular cron job on the catalog, DO NOT enable the job for hard delete of deleted datasets 
- [x] PostGres RDS database tuning (ckan datasets view metric cron is slow to process)
- [x] usasearch feed and topics export csv in cron [tracked here as well #44 )
- [x] QA cron / broken link report configuration and rerun the link check for all resources on catalog

## for CRM and Dashboard
- [x] adding local users on crm after MAX authentication, so set application specific roles
- [x] datashboard cron email issue

**Comment by vasili4** [comment]
Datapusher is working now after pull request https://github.com/GSA/catalog-deploy/pull/120
