### ISSUE TITLE
Create a list of pages and content URLs for use in a content audit

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1045]
## User Story

As a content editor, I want a spreadsheet containing links to content pages on www.data.gov and digital.gov so that I can track my audit in a single place with quick access to the actual content resources.

## Details
Spreadsheet columns:
- title
- URL
- date created (if available)
- author (if available)

## Acceptance Criteria
- [ ] Spreadsheet exists in google drive

**Comment by adborden** [comment]
@mogul and I discussed adding a plugin to do the work is probably the simplest solution

https://wordpress.org/plugins/export-all-urls/
https://www.wpbeginner.com/beginners-guide/what-is-a-wordpress-sitemap-how-to-create-a-sitemap-in-wordpress/

**Comment by ydave-reisys** [comment]
Uploaded document to google drive. https://drive.google.com/open?id=1JZmWGnFLEKmcDsllkLoiH15gLwR_s6O3

**Comment by adborden** [comment]
@crysacarter can you take a look at this and see if it'll work for you?
https://docs.google.com/spreadsheets/d/1ZohmuI28lsO5HMG5h7NqkEpkynJ6w-3xPdW3RZyYXr0/edit#gid=1850827333
