### ISSUE TITLE
Inventory: integration tests for local development environment

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1046]
## User Story

As a Data.gov developer, I want an integration test suite so that I can easily add automated tests that target Inventory components.

## Details
We've done these kinds of tests with [BATS](https://github.com/bats-core/bats-core). [Dashboard](https://github.com/GSA/project-open-data-dashboard/tree/develop/tests) has an example. We've also implemented [test containers](https://github.com/GSA/catalog-app/blob/develop/Dockerfile.test) who's only job is to run a test against the app container.

## Acceptance Criteria
- [x] It is easy to add tests to the existing automated test suite
- [x] Automated integration tests can be run by a single command
- [ ] Automated integration tests are running in CI

**Comment by mogul** [comment]
@adborden can you tag the in-progress PR here?

**Comment by adborden** [comment]
Done ^
