### ISSUE TITLE
Update Inventory Ansible role to install from a single requirements.txt

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1047]
## User Story

As a Data.gov developer, I want the Inventory role to install application dependencies from a single requirements.txt so that the code I'm using for my local development is the same that is being deployed into other environments.

## Details
The single requirements lock file should be committed to the Inventory application repo so it is under version control and can be inspected for dependency vulnerability analysis.

## Acceptance Criteria
- [x] requirements.txt and a lock file exist in the Inventory application repo
- [x] Ansible role pulls the Inventory repo based on an Ansible variable for the git-ish version e.g. `inventory_app_version`
- [x] GH and Snyk security notifications are enabled in the Inventory repo

**Comment by adborden** [comment]
https://github.com/GSA/inventory-app contains the requirements.txt

**Comment by adborden** [comment]
@ydave-reisys can you test this in the sandbox before we call this done?

**Comment by adborden** [comment]
After testing on sandbox, we identified a few more fixes that need to happen ^

**Comment by mogul** [comment]
@adborden is this still in `In Progress`? Or is it already `Done`?

**Comment by adborden** [comment]
Ready for Deploy

**Comment by adborden** [comment]
Oops, nm the PR has yet to be merged https://github.com/GSA/inventory-app/pull/9

**Comment by mogul** [comment]
Needs a documentation tweak, then should be ready to go
