### ISSUE TITLE
Bump python to 3.7

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1049]
## User Story

As a Data.gov Developer, I want our Python 3 projects bumped to 3.7 so that I can keep my projects up to date with the latest security features and keep close to stable, supported versions.

## Details
[Python 3.8.0 was just released](https://pythoninsider.blogspot.com/2019/10/python-380-is-now-available.html), so we should bump to 3.7.

## Acceptance Criteria
- [ ] Projects using Python 3 are updated

**Comment by nickumia-reisys** [comment]
Superseded by https://github.com/GSA/data.gov/issues/3876
