### ISSUE TITLE
data.gov mailed a "set password" link to a new user; it shouldn't

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1055]
### Description of steps to reproduce the issue.

Follow the process to set up a new admin [as described in the form that the onboarding checklist links to](https://docs.google.com/forms/d/e/1FAIpQLSetStmwqrbMWDz_WIlh1trjhP0PFCjKXHzshsJveYmtIvlG2Q/viewform).

## Expected behavior

You can log in to data.gov using max.gov for SSO with no further steps.

## Actual behavior

1. data.gov sends you a "[Data.gov] Login Details" mail with a password set hash (this one's already used):  \
![image](https://user-images.githubusercontent.com/47762/66956526-63c1ba80-f019-11e9-8e40-eeeb9df0e441.png)
1. You click the link and are presented with a "set password" dialog, which you fill out
1. You are presented with an unadorned error message from WordPress saying that you did not provide the right password. 
1. The same message appears if you clear your data.gov and max.gov cookies and try logging in.
1. To resolve the issue, an administrator must remove your account and have you log in again as if for the first time.

**Comment by mogul** [comment]
(This happened when provisioning my data.gov WordPress account.)

**Comment by nickumia-reisys** [comment]
Wordpress no longer exists.  Data.gov is on cloud.gov now,
- https://github.com/GSA/data.gov/issues/3555
- https://github.com/GSA/data.gov/issues/3554
- https://github.com/GSA/data.gov/issues/2788
- https://github.com/GSA/data.gov/issues/3541
- https://github.com/GSA/data.gov/issues/3891
