### ISSUE TITLE
Audit state of GSA-owned WP plugins

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1060]
## User Story

As an operator, I want to understand which of the WordPress plugins we use are unmaintained so that I can assess the risk of continuing to use them.

## Details
`datagov-wp-boilerplate` depends on about 15 GSA-owned WordPress plugins, and also includes copies of third-party packages in `lib` which are not being updated. At least one of the GSA-owned plugins is archived (eg not getting updates). We need to review them all to figure out what kind of risk we're carrying based on the state of these plugins and decide how we want to deal with that.

## Acceptance Criteria
- [ ] We have a clear list of which plugins are unmaintained/out of date
- [ ] We have a plan for how to deal with that list (eg we write another story)

**Comment by adborden** [comment]
If we [migrated WordPress](https://github.com/GSA/datagov-deploy/issues/992), we could avoid doing this work.

**Comment by nickumia-reisys** [comment]
Wordpress no longer exists.  Data.gov is on cloud.gov now,
- https://github.com/GSA/data.gov/issues/3555
- https://github.com/GSA/data.gov/issues/3554
- https://github.com/GSA/data.gov/issues/2788
- https://github.com/GSA/data.gov/issues/3541
- https://github.com/GSA/data.gov/issues/3891
