### ISSUE TITLE
Bionic inventory CKAN requests hang

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1068]
After putting Bionic into production for Inventory, some requests hang indefinitely. This manifests as uptrends alerts because some requests will timeout.

What we know so far...
- The behavior is somewhat intermittent. Sometimes it works, sometimes not.
- This did not seem to be an issue for staging, only production.
- This looks similar to what @adborden was seeing on Catalog when testing bionic.
- strace does not show a clear culprit.
- The hang seems to happen within CKAN's plugin initialization phase.
- We've verified connections to database (inventory and datastore), solr, and s3.

## How to reproduce

1. `sudo -u www-data /usr/lib/ckan/bin/paster --plugin=ckan serve /etc/ckan/production.ini`
1. `curl -v -L -k localhost:5000/api/action/status_show`

## Expected behavior

Request returns 200, JSON response of the server status

## Actual behavior

Request hangs, timeouts after ~5 minutes.

**Comment by adborden** [comment]
We could try disabling all the plugins, and re-enable them one by one.

**Comment by mogul** [comment]
I think what we're seeing is happening at the end of the plugin-initialization process. And again: Why do we only see this behavior on these two particular hosts, when the same plugins work on the staging hosts?

**Comment by adborden** [comment]
I think I'm seeing this behavior on staging Trusty now.

**Comment by adborden** [comment]
@FuhuXia has spent some time on this and hasn't been able to reproduce it in any environment. We are going to go ahead with the deploy, checking along the way in case it comes back.

**Comment by adborden** [comment]
Seeing this issue on production again.

**Comment by FuhuXia** [comment]
When one Bionic hangs, it also brings down other Trusty instances. Trusty instance will take forever to load `/dataset` and eventually gives 500 error. The log shows it is related to postgres QueuePool limit.

![Screenshot 2020-03-24 17 06 32](https://user-images.githubusercontent.com/1392461/77478262-103b7000-6df4-11ea-8ee9-770879119cab.png)

**Comment by adborden** [comment]
Closing as a duplicate of https://github.com/GSA/datagov-deploy/issues/1375, we're at least talking about these as if they're the same issue.
