### ISSUE TITLE
Bump dependencies for catalog-app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1070]
- https://github.com/GSA/catalog-app/network/alerts
- https://app.snyk.io/org/data.gov/project/ad0e236f-051e-4456-b32c-24e911ed9bde/

**Comment by adborden** [comment]
I have a branch somewhere that includes some changes to the migrations that are needed for sql alchemy...

**Comment by adborden** [comment]
Did some cherry-picking on [datagov-catalog/bump-sqlalchemy](https://github.com/GSA/ckan/compare/datagov...datagov-catalog/bump-sqlalchemy).

**Comment by adborden** [comment]
This was a PR for inventory https://github.com/GSA/ckan/pull/66

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3416
