### ISSUE TITLE
Update CKAN extensions for updated DCAT-US schema

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1071]
## User Story

As an agency user, I want the DCAT-US CKAN extensions updated to refer to the schema at [resources.data.gov](https://resources.data.gov/schemas/dcat-us/v1.1/) so that the data.json files I publish continue to work correctly.

## Details

Schema moved from project-open-data.cio.gov to https://resources.data.gov/schemas/dcat-us/v1.1/. Extensions need to be updated to make sure they continue to work correctly.

- [x] [GSA/usmetadata](https://github.com/GSA/usmetadata)
- [x] [GSA/ckanext-datajson](https://github.com/GSA/ckanext-datajson)
- [x] [GSA/ckanext-geodatagov](https://github.com/GSA/ckanext-geodatagov)
- [x] [GSA/ckanext-spatial](https://github.com/GSA/ckanext-spatial)

## Acceptance Criteria
- [x] Grepping for project-open-data yields no documentation results within [catalog](https://github.com/GSA/catalog-app) and [inventory](https://github.com/GSA/inventory-app) virtualenvs (DCAT-US schema still relies on project-open-data link and is not in the scope of this ticket).

**Comment by mogul** [comment]
After Aaron showed me where the venv was landing (:doh:) I was able grep and see that these are the repos implicated:

- GSA/usmetadata
- GSA/ckanext-datajson
- GSA/ckanext-geodatagov
- GSA/ckanext-spatial

**Comment by adborden** [comment]
@mogul you might find that things break, just open an issue to track. This is a stub: https://github.com/GSA/datagov-deploy/issues/1693

**Comment by jbrown-xentity** [comment]
Tested changes to a [sample data.json file](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/tests/datajson-samples/arm.data.json) and attempted reharvest on local development, got the following errors:
```
ckanext.harvest.logic.action.create: INFO: Harvest job saved 35caacd2-b804-4c6b-a7ea-aff098ea91ba
test_datajsonharvester: INFO: GATHERING http://127.0.0.1:8998/arm
harvester: DEBUG: In <Plugin DataJsonHarvester 'datajson_harvest'> gather_stage (http://127.0.0.1:8998/arm)
harvester: INFO: GET mock at: /arm
harvester: INFO: return json file arm.data.json
harvester: INFO: mock respond {
  "conformsTo": "https://resources.data.gov/schemas/dcat-us/v1.1",
  "describedBy": "htt
ckanext.harvest.model: INFO: Error reading json schema value. The given value is https://resources.data.gov/schemas/dcat-us/v1.1.
test_datajsonharvester: INFO: job.gather_errors=[<HarvestGatherError id=b4cf3781-7316-435e-996f-ae2491379068 harvest_job_id=35caacd2-b804-4c6b-a7ea-aff098ea91ba message=Error reading json schema value. The given value is https://resources.data.gov/schemas/dcat-us/v1.1. created=2020-06-25 22:02:47.309657>]
test_datajsonharvester: INFO: obj_ids=[]
```

The following were the changes made:

```
"conformsTo": "https://resources.data.gov/schemas/dcat-us/v1.1",
"describedBy": "https://resources.data.gov/schemas/dcat-us/v1.1/schema/catalog.json",
"@context": "https://resources.data.gov/schemas/dcat-us/v1.1/schema/catalog.jsonld",
```

Will need to re-evaluate if significant code changes are needed or future redirects are needed long term for this harvest type.

**Comment by adborden** [comment]
Chatted with @jbrown-xentity today, we decided we wouldn't touch any sample files or code related to parsing DCAT-US and only update documentation references.
