### ISSUE TITLE
[research: 20h] Best way to bump dependencies for inventory-app?

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1075]
- https://github.com/GSA/inventory-app/network/alerts
- https://app.snyk.io/org/data.gov/project/a390fc87-5f86-4437-93c9-8b7d879210b3/

**Comment by adborden** [comment]
#1070 might be identical in the work that needs to happen here, please keep in coordination with that ticket.

**Comment by adborden** [comment]
In order to bump the dependencies, like SQLAlchemy, some changes to the migrations were needed. This branch [datagov-catalog/bump-sqlalchemy](https://github.com/GSA/ckan/compare/datagov...datagov-catalog/bump-sqlalchemy) is for catalog, but I think is relevant to inventory, too. It should be rebased onto `inventory` as a starting point.

**Comment by adborden** [comment]
derp, there is also a PR https://github.com/GSA/ckan/pull/66

**Comment by mogul** [comment]
Outcome of 20h of attention here: 

- We think the path forward is to opt-out of all the issues associated with CKAN 2.3 and go straight to CKAN 2.8.
- We don't think there's a ton of value to finishing the work-in-progress on mod-security; that work won't be valuable after we move to cloud.gov.

**Comment by jbrown-xentity** [comment]
Completed by merging 
- https://github.com/GSA/inventory-app/pull/12/
- https://github.com/GSA/ckan/pull/67
