### ISSUE TITLE
Upgrade to Ansible 2.7

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1080]
## User Story

As a Data.gov developer, I want to use Ansible 2.7 so that I can take advantage of newer features, while maximizing compatibility with the third-party Ansible roles that we consume.

## Details
Ansible 2.9.0 was just [released](https://github.com/ansible/ansible/releases/tag/v2.9.0), so Ansible 2.6 will move to unsupported. Time to update to 2.7

## Acceptance Criteria
- [x] datagov-deploy is updated to 2.7
- [x] Ansible roles that we maintain are updated for 2.7

**Comment by mogul** [comment]
Aaron took care of this in a PR referenced above and just checked to confirm that all of our roles are using Ansible 2.7 in their testing.
