### ISSUE TITLE
Open license guidance should include note to use specific version of licenses in URLs

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1081]
## User Story

As a dataset owner, I want up to date guidance on how to use the metadata fields so that I am following best practices without having to know what the best practices are.

## Details
https://resources.data.gov/open-licenses/ lists usage notes for the `license` field. It should include the [latest guidance from the dataset-search project](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/datasetsearch-announce/v1E8Gg4_ilE/M0qQ-cGfAwAJ) to use URLs to specific versions of licenses, e.g.

```
license: "https://creativecommons.org/publicdomain/zero/1.0/"
```

## Acceptance Criteria
- [ ] open-licenses page is updated
- [ ] we announce the new guidance to agency users

**Comment by hkdctol** [comment]
This will be addressed in metadata schema update effort

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/DCAT-US/DCAT-US-Schema-v3.0/issues
