### ISSUE TITLE
Support agencies in keeping their data up to date

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1082]
## User Story

As a data user, I want agencies to keep datasets up to date so that I can access the latest and most accurate information available from the US Government.

## Details
Not all datasets receive updates, some are just historical datasets. How can we support agencies in keeping datasets up to date?

## Acceptance Criteria
- [ ] Create a plan on how we might answer these questions
  - How we might identify out of date datasets proactively?
  - What prevents agencies from keeping data up to date?

**Comment by jbrown-xentity** [comment]
This is an epic, something very high level. Business process and goal focus. Tagging @hkdctol and @tdlowden for analysis if this is still relevant, and what the priority is.

**Comment by hkdctol** [comment]
I don't think we have to have it open as an epic at this point in time
