### ISSUE TITLE
Split harvest-gather onto its own hosts

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1089]
## User Story

As a Data.gov operator, I want gather hosts separate from fetch or other tasks so that I can tune resources for the gather job specifically and avoid spending human time babysitting large jobs like NASA's harvest.

## Details
NASA's data.json is large (~70MB, 24k datasets). We run this job manually because it often runs out of memory during the gather phase. I've clocked it at about 5G, so within the resources of an 8G host. Since other services, like the 5 fetch workers and the fgdc2iso service are also running, the memory available to the gather process isn't enough. Splitting out the gather process to its own host means it won't be competing for resources.

As a work-around I've been manually stopping services so that the gather room can complete, then restoring the other services to normal.

## Acceptance Criteria
- [ ] New Ansible inventory groups are created to reflect the different harvester roles (main, misc, qa, etc)
- [ ] Ansible playbooks are updated with new inventory groups

**Comment by adborden** [comment]
Another datapoint, Department of Commerce ~200MB data.json and 40k datasets consumed 6289060KiB during the gather stage.

**Comment by nickumia-reisys** [comment]
Being on cloud.gov now, `catalog-gather` is it's own app and it does not interfere with other processes.  There are issues with harvester restarts, and other harvesting stuff (but that's out-of-scope for this issue),
- https://github.com/GSA/catalog.data.gov/blob/main/manifest.yml#L82
  ![image](https://user-images.githubusercontent.com/85196563/216687286-d50f3c79-48cd-40ab-b53a-b85e7571c1f9.png)
- https://github.com/GSA/data.gov/issues/4187
- https://github.com/GSA/data.gov/issues/1342
