### ISSUE TITLE
Update TLS configuration on data.gov, catalog.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1091]
From FY19 pen test: moderate.

> The site offers week SEED and 128 and 256 bit CBC ciphers.

Need to update the [CloudFront distributions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html#secure-connections-supported-ciphers).

**Comment by mogul** [comment]
@adborden do we have to go through BSP to get our Cloudfront configuration changed? Or do we have access to make this change ourselves?

**Comment by adborden** [comment]
No, we can do this ourselves. The CloudFront distros are in the `gsaoppprod` AWS account.

**Comment by jbrown-xentity** [comment]
CloudFront configuration updated to use TLS 1.2 for catalog and wordpress
