### ISSUE TITLE
CRM app should bootstrap its own DB schema

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1098]
## User Story

In order to remove manual effort and make deployment of the CRM app more self-contained, operators want the CRM app to populate the DB with its initial schema as a CodeIgniter migration.

## Details

Right now you can't just start up the CRM app in an environment, whether local or production... The operator is responsible for doing an initial population of the DB schema *before* running the built-in schema migration logic. That shouldn't be necessary... This story concerns putting the initial .sql schema load into a [CodeIgniter migration](https://codeigniter.com/user_guide/libraries/migration.html). (It might optionally also auto-run migrations, an option in CodeIgniter we haven't enabled.) 

## Acceptance Criteria
- [ ]  GIVEN I run `git clone git@github.com:GSA/open311-simple-crm.git` \
  AND I run `cd open311-simple-crm.git` \
  AND I run `docker-compose up` \
  (AND I do **NOT** run `cat db/fms-endpoint-initial.sql | docker container exec -i $(docker-compose ps -q db) mysql -uroot -pmysql-dev-password crm`) \
  AND I run `docker-compose exec app php index.php migrate` \
  WHEN I run `curl -v localhost:8000` \
  THEN I get a `200` response \
  AND I see the source for the front page of the CRM app does not contain errors

**Comment by hkdctol** [comment]
Closing since we shut down CRM
