### ISSUE TITLE
Setup Jekyll based static websites

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#11]
Options:
- S3 or EC2

**Comment by JJediny** [comment]
https://github.com/JJediny/jekyll-hook

Is an NGINX server with a Nodejs webhook that rebuilds the site (optionally to s3) and drops the cache. At a minimum we could use 1 ec2 instance to handle multiple webhooks from multiple Github repos/sites. We would have to orchestrate the Route53/ELB/S3 through Ansible or Cloudformation

**Comment by FuhuXia** [comment]
We end up with using jekyll-rebuilder, apache proxy, and s3cmd with IAM roles for the jekyll build webhook and S3 options. One ec2 box can be used for multiple jekyll apps. Web files are build locally and pushed to S3 for publishing. Currently we have sdg-indicators and data-federation two apps. New app can be added into https://github.com/GSA/catalog-deploy/blob/master/ansible/jekyll.yml#L11-L29. Re-run ansible playbook and new app will be ready.

ansible instruction is here.
https://github.com/GSA/catalog-deploy/blob/master/ansible/roles/software/jekyll/README.md
