### ISSUE TITLE
Provision config for dashboard to run in CI environment

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1100]
## User Story

In order to enable functional deployment of the dashboard application in the CI environment, operators want the needed DB and S3 resources provisioned in AWS and the configuration captured in the Ansible inventory vars+vault.

## Acceptance Criteria
- [ ] GIVEN I run `ssh jump.ci.datagov.us` \
  AND I run `git checkout git@github.com:GSA/datagov-deploy.git` \
  [...and I debug anything that prevents that checkout from succeeding...] \
  AND I run `cd datagov-deploy/ansible &&  ansible-playbook dashboard-web.yml --tags=provision,deploy -i inventories/ci` \
  WHEN I run `curl -v https://dashboard.ci.datagov.us/` \
  THEN I see a `200` response \
  AND I see the HTML returned does not include any errors about configuration/setup

**Comment by mogul** [comment]
This was done as part of the PHP 7.3.0 upgrade to enable testing in the CI environment.

**Comment by adborden** [comment]
Confirmed.
