### ISSUE TITLE
Wordpress nightly triggering CPU alarms

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1102]
We see both cloudwatch alarms (ALARM: "DataGov-Prod-Wordpress-WordpressWeb1CPUAlarm-40HMX2ET0Z6" in US East (N. Virginia)) and NewRelic CPU load alarms.

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by adborden** [comment]
Unassigning @jbrown-xentity since he won't be able to do much investigation without GSA credentials.

**Comment by mogul** [comment]
Closing as we haven't seen this recently; can always reopen in future!
