### ISSUE TITLE
catalog-harvester1p logrotate complains that fetch-consumer.log.1 already exists

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1106]
```
/etc/cron.daily/logrotate:
error: destination /var/log/fetch-consumer.log.1 already exists, renaming to /var/log/fetch-consumer.log.1-2019111206.backup
```

We should check the configuration isn't somehow duplicated on this host.

## How to reproduce

1. Run the logrotate cron job

## Expected behavior

Logs are rotated correctly, without creating any `.backup` files.

## Actual behavior

Error notification is sent

**Comment by adborden** [comment]
The issue seems to be that supervisor does its own log rotation http://supervisord.org/logging.html#child-process-logs

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
