### ISSUE TITLE
Upgrade WordPress version

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1115]
## User Story

In order to keep www.data.gov easy to update and secure, the team wants www.data.gov to be running the most recent supported version of WordPress (5.4.1 as of this writing).

## Acceptance Criteria

- [x] GIVEN I am logged into WordPress as an admin \
 WHEN I look at the version information in the lower-right of the dashboard \
 THEN I see that the version is 5.4.1 or higher

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
We believe this will only improve our security posture with no changes to overall architecture/deployment.

## Sketch

- [x] Read the release notes for intermediate versions
- [x] Update the composer file and work from there...

**Comment by adborden** [comment]
WordPress 5.4.0 was [released](https://wordpress.org/news/2020/03/adderley/).

**Comment by hkdctol** [comment]
Email from GSA Security today encouraging update to 5.4.2

**Comment by pjsharpe07** [comment]
While logged into to wordpress on data.gov...

![image](https://user-images.githubusercontent.com/38019872/89559325-bfd91380-d7d2-11ea-8b4d-0c3b34576d69.png)
