### ISSUE TITLE
Plan for in-person hack session

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1122]
## User Story

As a Data.gov team member, I want an agenda for the in-person hack session so that we can make the most of the time in person together.

## Details
We're going to be together in person, how should we use the time?

## Acceptance Criteria
- [ ] Document exists describing the agenda

**Comment by hkdctol** [comment]
We have morning of Wednesday 12/18 for in person meeting with Data.gov PMO and REI teams.

Options:
Roadmap - higher level discussion of priorities. We have a lot of tech debt and tickets, but what's next re: infrastructure move, cloud.gov, GCP, modernize Data.gov CKAN, and relationship to work on the other contract

Hackathon - curated list of issues that we can co-work 

Other?

We can do either another time as well, virtually--what would be best option for in person meeting opportunity?

**Comment by mogul** [comment]
Hyon, Bret, and Aaron will wrap this up today
