### ISSUE TITLE
Stop-gap script or tool to automate the process of resolving stuck harvest jobs

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1123]
## User Story

As a Data.gov operator, I want an automated tool or script so that I can safely unstick harvest jobs without running raw SQL in the production database.

## Acceptance Criteria
- [ ] a script or tool is created under version control

## Details
Harvest jobs get stuck all the time and we have no tools to unstick them. The harvest retry logic has been disabled for ? historical reasons.

Each day we get a harvest report that lists the harvest jobs in the queue. When this queue grows large enough, we manually unstick it.

The [manual process](https://github.com/GSA/datagov-deploy/wiki/Stuck-Harvest-Fix) involves querying the harvest jobs, checking the status, and then manually resetting them with some SQL UPDATEs.

_Note: this story is not meant to fix the root cause, only address the manual and error prone process of having to touch the database._

**Comment by adborden** [comment]
@FuhuXia @kvuppala do you have more background on the harvest job retry customizations?

**Comment by kvuppala** [comment]
@FuhuXia for sure, assigned to him.

**Comment by mogul** [comment]
@adborden is going to schedule a meeting to investigate why the upstream retry logic isn't enough and we had to write our own retry logic, and how to address that.

**Comment by adborden** [comment]
@jbrown-xentity @FuhuXia and I chatted about this today. [ckanext-geodatagov](https://github.com/GSA/ckanext-geodatagov/blob/d82eb45067f9b8335b6d767499f218431fb6c215/ckanext/geodatagov/commands.py#L657) contains a `harvest-job-cleanup` command that searches for stale jobs (over 6 hours with no progress), identifies them and attempts to unstuck them. There's several corner cases it addresses. This also notifies us via email with the jobs it has identified.

We're not ready to re-enable these jobs unless we add some tests since this job currently doesn't have any automated tests.

That said, we think that the latest fixes to ckanext-harvest and ckanext-datajson addresses some of the common stuck jobs we've seen recently. Therefore, we're going to punt on this issue. We still have the daily harvest report which will tell us if we indeed fixed some of the commonly stuck issues or if we need to revisit.
