### ISSUE TITLE
Update logo for National Endowment for the Humanitites

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1124]
Update logo for [NEH](https://catalog.data.gov/organization/neh-gov). Looks like they used to host the logo on their site, but the link is now broken. Maybe we can find an updated URL, otherwise the image is here.

![newlogo](https://user-images.githubusercontent.com/509703/68907114-7227f280-06fb-11ea-92a6-26c6836b2d9e.png)

**Comment by kvuppala** [comment]
Update the page with the logo @ https://www.neh.gov/sites/default/files/styles/medium/public/2019-08/NEH-Preferred-Seal820.jpg
