### ISSUE TITLE
Clean up stale GitHub branches

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1125]
There is a lot of stale branches on GH. We should go through them, open issues for any work in progress we want to finish and then delete the stale branches.

**Comment by mogul** [comment]
Aaron's opened draft PRs for most of the branches that look like they still have work worth delivering, and closed others. He'll finish going through the rest of the branches and making PRs before we call this done; we'll then take the PRs in our normal prioritization flow.

**Comment by adborden** [comment]
Just removed another dozen branches from datagov-deploy. I think we're all set here.
