### ISSUE TITLE
Connect dataset support requests with the URL to the dataset

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1127]
## User Story

As a customer support specialist, I want support requests about datasets to include the URL to the dataset in question so that I don't need an extra correspondence to request the dataset URL and remove ambiguity.

## Details
Since we disabled CRM, requests coming in through the Contact Us form are disconnected from the dataset URL where the support request originated.

As a quick fix we could include an optional field in the Contact Us form but long term we want the URL to be captured automatically.

## Acceptance Criteria
- [ ] Email notifications for dataset questions include a URL to the dataset if applicable.
- [ ] If a quick fix is implemented, this story is documented as part of the CRM research project.

**Comment by jbrown-xentity** [comment]
This is already fixed, and the new iteration being worked on will contain the same feature. Closing.
