### ISSUE TITLE
Improve jumpbox creation in BSP

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1131]
## User Story

As a data.gov operator, I want FCS to provision jumpboxes into a known subnet that is already configured with firewall rules allowing SSH so that when a new jumpbox is provisioned a one-off firewall change request is not necessary.

## Acceptance Criteria
- [ ] Jumpboxes can be provisioned without a firewall change request.

**Comment by adborden** [comment]
Keeping track of jumpboxes:
- ip-10-177-107-8

**Comment by adborden** [comment]
Tracking in a Google Doc https://docs.google.com/document/d/19PwTE6rFay5fghAYcNjKCkeLM4OfZG7TqZ4lAL9hZpA/edit

**Comment by mogul** [comment]
There's been a contractor change on the BSP side that makes the friction here higher than we really want to take on right now given the small improvement... Going to `Icebox` this for the future.

**Comment by hkdctol** [comment]
Closing tickets related to BSP
