### ISSUE TITLE
Update WordPress to 5.2.4

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1134]
[WordPress 5.2.4](https://wordpress.org/news/2019/11/wordpress-5-2-4-update/) contains a security fix.

**Comment by mogul** [comment]
Looks like [we already did this](https://github.com/GSA/datagov-wp-boilerplate/pull/28) and it got [merged into develop and then master](https://github.com/GSA/datagov-wp-boilerplate/commits/master) prior to our most recent release on 11/13. Are we seeing an alert on this since then?

**Comment by mogul** [comment]
Confirmed this is in prod, so this was a false alarm.
