### ISSUE TITLE
Resolve Pen Test findings for WordPress

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1139]
Issues are in the datagov-incident-response repo, captured in [a milestone](https://github.com/GSA/datagov-incident-response/milestone/1).

**Comment by mogul** [comment]
We're planning to move the issues implicated in that milestone to the datagov-deploy repo and set a deadline/milestone here so we don't lose track of this one.

**Comment by mogul** [comment]
@mogul will follow up on moving those issues over to the main repo so we can close this issue.

**Comment by adborden** [comment]
#1256 #1255 #1254 #1253 were created. @mogul I'm going to close this out. Please open if there's anything left to do here.
