### ISSUE TITLE
Where should these ckanext-archiver commands live?

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1141]
This needs to live somewhere, probably the catalog [Runbook](https://github.com/GSA/datagov-deploy/wiki/Runbook), but if so it should also be turned into a script and added to datagov-deploy.

I found this in https://docs.google.com/document/d/1w__Mm3XpL_HeCOaZVKQyRFjgpMCfW1IdzLiZzzQL-5I/edit

> Here is a list of commands to queue archiver and qa into redis
> 
> Queues a specific package into priority queue
>     $ paster --plugin=ckanext-archiver archiver update [name/id] --queue=priority -c /etc/ckan/production.ini
>
> This command will queue 1000 datasets at a time and put queued datasets into an archiver_checklist table. Run this command if you want to queue ALL datasets.
>     $ paster --plugin=ckanext-archiver archiver update-max --queue=bulk -c /etc/ckan/production.ini

**Comment by adborden** [comment]
@FuhuXia are you familiar with these commands? When would we need to run them?

**Comment by FuhuXia** [comment]
We have ckanext-archiver extension installed but we dont use it directly, so not sure about the purpose of this command. We use ckanext-archiver as a dependency for the Broken Link Report function. Those reports were generated on regular basis by a cron job on harvester instance.

**Comment by adborden** [comment]
Thanks, yeah, we have not gotten around to re-enabling the archiver jobs but would like to.

**Comment by nickumia-reisys** [comment]
This is superseded (and more so, historical context) by/for,
- https://github.com/GSA/data.gov/issues/3986
