### ISSUE TITLE
Re-enable the CKAN QA jobs

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1144]
## User Story
As a Data.gov admin, I want the CKAN QA jobs running so that I am aware of issues with datasets and can get them addressed.

As an Agency data contact, I want a broken links report so that I know when I need to update links or metadata for my Agency's datasets.

## Details
I'm not 100% sure what the QA jobs do and I'm not sure if they already send reports directly to Agency POCs or not. The intention of the story is to re-enable the jobs. If any follow up work is required, we should address in a follow-up issue.

## Acceptance Criteria
- [ ] Jobs are running successfully in supervisor
- [ ] CKAN broken link reports are emailed regularly
- [ ] Any follow-up work on how to improve the reports are captured as issues

**Comment by adborden** [comment]
Not sure if there are additional commands that need to be added https://github.com/GSA/datagov-deploy/issues/1141

**Comment by nickumia-reisys** [comment]
This is superseded by,
- https://github.com/GSA/data.gov/issues/3986
