### ISSUE TITLE
21st Century IDEA Act compliance 

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1145]
## User Story

As Data.gov PMO, will need to comply with the 21st Century IDEA Act

.
## Details
To be completed, in line with commitments in GSA internal report. Each area of work may become its own epic.

https://docs.google.com/document/d/11uKuCeK1GUNDJ7GZhRscq0yyCRUpqgWPDFkzDfBxGCE/edit

## Acceptance Criteria
All areas being tracked by GSA are accepted as "green" for Data.gov.

**Comment by adborden** [comment]
Added a link to our previous notes.

**Comment by adborden** [comment]
Added to [December 2019 Compliance](https://github.com/GSA/datagov-deploy/milestone/21) milestone.

**Comment by adborden** [comment]
Are there any deadlines on this? I feel like it's a year out or something.

**Comment by hkdctol** [comment]
It's 2 years out but I'll work on the spec on this

**Comment by hkdctol** [comment]
Closing this. Each component (such as accessibility, user-centric, etc.) will become its own epic.
