### ISSUE TITLE
Understand metrics-count

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1146]
Where should these instructions live? Is the command still needed? [metric-count](https://github.com/GSA/metric-count) repo is archived.

From https://docs.google.com/document/d/1w__Mm3XpL_HeCOaZVKQyRFjgpMCfW1IdzLiZzzQL-5I/edit#

> ### Metrics Page / Full History Page Update Process
> Two repositories responsible for Metrics Page: 
> - https://github.com/GSA/data.gov
> - https://github.com/GSA/metric-count
> 
> Metric Count is a cron job that is responsible for downloading dataset counts for federal and non-federal organizations from CKAN once a day. There are 4 main files that are responsible for downloading
> - metric-count/Classes/MetricsCounterFed.class.php
> - metric-count/Classes/MetricsCounterNonFed.class.php
> - metric-count/Classes/MetricsCounterFullHistory.class.php
> - metric-count/Classes/MetricsCounterFullHistoryNonFed.class.php
> 
> The two template files you have to manage are:
> - roots-nextdatagov/templates/content-agency-participation.php
> - roots-nextdatagov/templates/content-metrics-per-month-full.php

**Comment by jbrown-xentity** [comment]
We haven't needed them in 5 years, closing.
