### ISSUE TITLE
Unable to create new organization for SSA in inventory.data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1147]
SSA would like to use inventory.data.gov to manage metadata. SSA has not previously used inventory.

## How to reproduce

Sign in to inventory.data.gov as admin and try to add new organization, Social Security Administration

## Expected behavior

As there is no SSA organization in UI admin view of all organization, and no results when searching for SSA or terms search as "social" or "security," would expect to be able to create new organization.

## Actual behavior

Error message that unable to create organization because it already exists in database.

**Comment by hkdctol** [comment]
This has been resolved and user accounts have been added to SSA organization in inventory.

**Comment by adborden** [comment]
@FuhuXia identified that the SSA organization had been deleted, but not purged from the database. To resolve, he updated the database directly to update the state.

Opened https://github.com/GSA/datagov-deploy/issues/1171 to track for a real fix.
