### ISSUE TITLE
Upload current data.json for SSA to inventory.data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1148]
## User Story

As a new user of inventory.data.gov from SSA, want to start managing metadata from inventory.data.gov

## Details
Upload the current SSA data.json available at https://www.ssa.gov/data.json to newly created SSA organization in inventory.

## Acceptance Criteria
Review by SSA open data lead that SSA in inventory.data.gov is populated with the datasets from public SSA data.json, with identical number of datasets.

Dependency: First resolve #1147

**Comment by adborden** [comment]
Instructions are in the [runbook](https://github.com/GSA/datagov-deploy/wiki/inventory.data.gov#importing-from-datajson) to use [ckanpyimport](https://github.com/GSA/ckanpyimport).

**Comment by adborden** [comment]
Ran into a few bugs while testing on staging. Forgot this also takes some time ~2 hours for ~1k datasets.

**Comment by adborden** [comment]
I think this is done. There are more [datasets](https://inventory.data.gov/organization/social-security-administration) than I expected (~1200), but looking at their identifiers, they are all unique. 

After downloading the data.json from Inventory, running this command prints duplicates (none).

    $ cat ~/downloads/data.json  | jq -r '.dataset[].identifier'  | sort | uniq -d

Updated the instructions in the [Inventory Runbook](https://github.com/GSA/datagov-deploy/wiki/inventory.data.gov#importing-from-datajson).
