### ISSUE TITLE
Alert operators when cloud.gov apps log problems that require investigation

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1150]
## User Story

In order to know when operator attention is needed, operators should be notified when apps running in cloud.gov log a condition indicating a problem that needs attention

### Acceptance Criteria
- [ ] TBD

## Details

cloud.gov doesn't support sending mail from the shell, which had been the method for sharing the results of crawl jobs on BSP,  e.g: `php index.php crawl | tee /var/log/dashboard-cron.log | mail -s 'LabsData - Dashboard' default_email`. However, the the worker or task pattern for the crawl will result in labels from crawls with a worker id, e.g.: `[APP/PROC/WORKER/0] OUT Attempting to request http://www.sba.gov/data.json`.

We need to make sure that humans are notified when there are problems.

**Comment by adborden** [comment]
I feel like there is a philosophical question here about whose responsibility it is to store the logs. As the title suggests, the operator needs to be notified that the job failed and an action is required. However, the notification doesn't need to include the details of the error (or the logs). Maybe the operator must go to the app to pull the logs there (e.g. the app stores it somewhere S3 or DB, etc). Or maybe the job logs are ingested by your log drain just as any other application logs, and the operator would look there for details on the error.

I think the important thing is that the notification is generated and it has enough information (job id or timestamp) for the operator to take action and know where to look.

**Comment by mogul** [comment]
Good point, and I'll modify the story accordingly. Separating the concerns may also make it easier to generate the alert (eg we can have an endpoint that gets polled with the last status rather than trying to figure out mail).
