### ISSUE TITLE
pod-dashboard respects cloud.gov route paths

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1151]
## User Story

In order to enable proxying of labs.data.gov/dashboard to pod-dashboard running on cloud.gov, we need to ensure that pod-dashboard respects the base URL it sees in the cloud.gov environment.

## Acceptance Criteria
- [ ] GIVEN I `cf push --route-path /dashboard` in the pod-dashboard directory \
  WHEN I visit `<the-route>/dashboard` \
  THEN the dashboard generates relative links \
  AND the dashboard behaves as expected.

## Details
  * There may be issues with link writing and the value of `config["base_url"]`. It may be sufficient to unset `config["base_url]` and let CodeIgniter determine URLs internally, and have CloudFoundry rewrite for you. Or, you may want to emulate what's in the Ansible code with:
      ```php
      if (isset($_SERVER['REQUEST_URI']) && 0 === stripos($_SERVER['REQUEST_URI'], '/dashboard')){
          $config['base_url'] .= '/dashboard';
          $cookie_path_prefix = 'dashboard';
      }
      ```

**Comment by adborden** [comment]
If it simplifies things, we can also host the app at its own domain. the /dashboard has caused some confusion with the scanning team. I also think it deserves its own domain fwiw.

**Comment by mogul** [comment]
I view that as a separate concern, more of an IA issue... On the technical
side, the app should not care what the base URL is, or at least take it in
as a parameter. So take this as just one more step in making the dashboard
more 12-factor-y.

**Comment by adborden** [comment]
Ah, right I understand now. Yes, I'm a fan of providing the complete base url as configuration.

**Comment by mogul** [comment]
[Example of a place where the app assumes and tries to do too much](https://github.com/GSA/project-open-data-dashboard/blob/develop/application/views/footer.php#L42-L53)

**Comment by mogul** [comment]
Planning to deploy the dashboard as dashboard.data.gov, so this is no longer necessary.
