### ISSUE TITLE
Generate pod-dashboard image using PHP buildpack

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1158]
## User Story

In order to reduce the potential for drift between dev, test, and deploy of pod-dashboard, data.gov operators want to be able to build a buildpack-generated Docker image of the application and develop with it.

### Acceptance Criteria
- [ ] GIVEN I checkout the pod-dashboard repo \
  WHEN I run `make build; make up; make test` \
  THEN I see the application code is run through a buildpack \
  AND I see a Docker image tagged `project_open_dashboard_app:latest` is generated \
  AND I see the application run successfully \
  AND I see that tests run and pass

## Details

We don't want to maintain another "platform" (Dockerfile + config in docker-compose) for building, developing, and testing our application when we already have Ansible and cloud.gov targets for deployment. We want the minimal configuration we maintain for cloud.gov and the safety/security of buildpacks to apply across our development cycle. By building a Docker image using the PHP buildpack (either via `cflocal` or buildpacks.io's `pack`), we reduce the surface area that we're maintaining, and potentially even enable deployment of the same Docker image via Ansible in the BSP environment.

See branch `use-buildpack-locally` for some early work in this direction.

**Comment by nickumia-reisys** [comment]
Superseded by
- https://github.com/GSA/data.gov/issues/3502
