### ISSUE TITLE
Correct logo for NEH organization not displaying on dataset pages

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1161]
NEH organization in catalog was recently updated with a new logo.

## How to reproduce

View logo on NEH organization in catalog, which has the correct logo. Click on any dataset and logo displayed is the old one.

## Expected behavior

Entering the URL for the correct logo should result in the logo displaying on each dataset page.

## Actual behavior

Dataset pages have the old logo.
<img width="640" alt="NEH org" src="https://user-images.githubusercontent.com/3236989/69756876-84595600-1129-11ea-94b9-60d445483426.png">
<img width="640" alt="NEH dataset" src="https://user-images.githubusercontent.com/3236989/69756890-8ae7cd80-1129-11ea-8d2d-6e2f4c7e627e.png">

**Comment by FuhuXia** [comment]
Fixed. This [URL](https://catalog.data.gov/dataset/neh-state-council-activity-1998-2015) should show new logo after the fix is deployed.
