### ISSUE TITLE
Bump simplesamlphp to 1.18

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1169]
SimpleSAMLPHP should be bumped. Please follow the [release notes](https://simplesamlphp.org/docs/1.18/simplesamlphp-changelog#section_1) for upgrade instructions.

- [x] https://github.com/GSA/project-open-data-dashboard ([Pull Request](https://github.com/GSA/project-open-data-dashboard/commit/f96640dd9911d445b4ae4b7a8d03d05144f0ede4))
- [ ] ~https://github.com/GSA/open311-simple-crm~

**Comment by adborden** [comment]
This just showed up in the GH [security alerts](https://github.com/GSA/project-open-data-dashboard/network/alerts) (low severity).

**Comment by pjsharpe07** [comment]
Since dashboard was merged in November and simple-crm is being removed, is there any work that needs to be done? Can this be moved to the done? @mogul  @adborden

**Comment by mogul** [comment]
I think when we created this we thought that the minor version bump implied some sort if incompatibility that might impact our integration of the package, but having reviewed the release notes it doesn't look like that's the case. So yeah, let's call this done!
