### ISSUE TITLE
When an organization is deleted, cannot create a new organization with the same name

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1171]
https://github.com/GSA/datagov-deploy/issues/1147

## How to reproduce

1. Create an org SSA
1. Delete the org SSA
1. Run purge commands
1. Create a new org SSA

## Expected behavior

New SSA can be created.

## Actual behavior

Error, org already exists in the database.

**Comment by adborden** [comment]
@FuhuXia looked into this and found that the error messaging is improved in CKAN 2.8.3, so upgrading would improve the situation.

https://gsa-tts.slack.com/archives/C2N85536E/p1575465463010300?thread_ts=1574781922.080700&cid=C2N85536E

**Comment by FuhuXia** [comment]
Solution for admin once seeing the error message:
1. Copy the machine name of the organization and paste into this url `/organization/edit/<machine-name>`
You are going to rename the existing machine name to something else so there is no conflict to use it for the new organization you are adding.
2. Click **Edit** next to the URL field and append `-deleted` to the existing name. Click the button at bottom to Update Organization
3. Now you can proceed to add the new organization with desired name

**Comment by mogul** [comment]
Sounds like this may be addressed upstream in newer CKAN versions... Going to icebox this.

**Comment by adborden** [comment]
Just filling in some detail... It looks like CKAN 2.8 supports [organization_purge](https://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.delete.organization_purge) from the API. and https://github.com/ckan/ckan/pull/5127 allows this to be done from the UI.

**Comment by jbrown-xentity** [comment]
This is all defunct, and there is a work around. Closing.
