### ISSUE TITLE
Move contact us to third-party CRM SaaS

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1172]
## User Story

As a Data.gov Operator, I want the "contact us" form routed to a third-party CRM SaaS so that I can link to the CRM from a static site.

## Details
As part of moving www.data.gov to a static site, we need to find a solution for each of our forms. The Contact Us form should be moved to the CRM SaaS.

## Acceptance Criteria
- [ ] Contact Us forms are updated with a link to the CRM SaaS.
- [ ] Flamingo plugin can be removed from WordPress (it doesn't have to be removed, but we are able to remove it if we wanted).

**Comment by adborden** [comment]
While not a CRM, we had a demo with [Touchpoints](https://touchpoints.digital.gov/) today and it looks like it will meet our needs for a contact form. A true CRM would help facilitate our responses and conversations with any inbound requests, but not essential if it helps us to get off of WordPress.

**Comment by adborden** [comment]
Just got a clarification: Touchpoints supports notification emails, but it will require us to log into Touch points to see the request. In that way a true CRM would be a better option.

**Comment by hkdctol** [comment]
Just noting that what we've heard is that the TTS-approved solution for CRM is Salesforce with an initial implementation in a few months. I've joined the relevant Slack channel to track.

**Comment by nickumia-reisys** [comment]
Using touchpoints now,
- https://github.com/GSA/data.gov/issues/3488
