### ISSUE TITLE
Dashboard returns 502 gateway error during deploy

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1173]
Sometimes when we deploy Dashboard, Uptrends alert on a 502. We are running the plays one host at a time, so there _should_ be at least one host available to continue serving requests, but it's possible that one of the plays leave the host unavailable, causing downtime. We should better manage this "critical" section so that the dashboard is still available during this time.

Since the PHP applications are all very similar, it's possible this affects all the PHP app deploys.

## How to reproduce

1. `ansible-playbook dashboard-web.yml`
1. Open https://labs.data.gov/dashboard and keep refreshing during deploy

## Expected behavior

Dashboard remains available, serving requests.

## Actual behavior

Intermittent 502 gateway errors.

**Comment by nickumia-reisys** [comment]
Dashboard has new errors on cloud.gov, but this error was for FCS specifically (which doesn't exist anymore)
- https://github.com/GSA/data.gov/issues/3710
- https://github.com/GSA/data.gov/issues/3961
