### ISSUE TITLE
Content + Layout updates to strategy.data.gov for release of Year-1 Action Plan

### ISSUE THREAD

**Issue by philipashlock** [GSA/data.gov#1176]
The Year-1 Action Plan for the Federal Data Strategy is being finalized and cleared thru OMB with a plan to publish soon. This also comes with some additional content and layout update proposals from OMB which have been provided in Word Documents. 

New content is available here: https://drive.google.com/file/d/0B0AXBa2us_9bd0Ixd1dhbmNDWGNpTFozY0YtcFkyMndJQlI4/view?ts=5d9cc248

**Comment by mogul** [comment]
@philipashlock we're doing some sprint planning... Can you confirm today or tomorrow that you're still planning to work on this, and that you think you can get it to conclusion in the next couple weeks?

**Comment by mogul** [comment]
@philipashlock we're marking this `Done` as there are no more related issues and a release was made... Let us know if that's not the case!
