### ISSUE TITLE
multiple harvest_object_id in action/package_show

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1182]
Two harvest_object_ids show up in `extras` field  in action/package_show. Most of time they have different values, one being current one being old from past harvest job. 

## How to reproduce

1. Open URL in browser
https://catalog.data.gov/api/3/action/package_show?id=ce4914a4-0986-473d-8674-499c39e23bc2
Here are some sample ids to use:

https://catalog.data.gov/api/3/action/package_show?id=49c853cd-1816-45f5-ba78-31ba02232d2c
https://catalog.data.gov/api/3/action/package_show?id=80979892-c24f-4a74-bc0c-19e6314aedcf

## Expected behavior

In `extras` field, there should be one entry with key `harvest_object_id`  and its value should be the latest harvest object id. 

## Actual behavior

There are two entries with key `harvest_object_id`, and their values are different.

**Comment by FuhuXia** [comment]
API version 2 is not affected by this bug. Only one harvest_object_id in URL:
https://catalog.data.gov/api/2/rest/dataset/[dataset-name-or-id]

**Comment by adborden** [comment]
Ah, I remember seeing this when we were debugging the duplicates issue. I believe that in most cases the last Id was used, so it didn't cause any problems as far as I could tell. @FuhuXia do you think this needs to be addressed? I'm thinking we icebox this until after we get on the latest ckanext-harvester version.

**Comment by FuhuXia** [comment]
Sure, we can icebox it. Anyone running ckan-php-manager tagging task such https://github.com/GSA/datagov-deploy/issues/913 should be aware of this issue, because it will cause a false warning for dataset integrity check.

**Comment by jbrown-xentity** [comment]
I believe this is no longer an issue; closing.
