### ISSUE TITLE
Add Infrastructure-as-Code Documentation

### ISSUE THREAD

**Issue by robproper** [GSA/data.gov#119]
Add documentation to describe use of:

0. Move generic process documentation from /terraform/Readme to /InfratsructureAsCode.md
1. Jenkins - Jenkinsfile, pipeline and provisioner Groovy scripts
2. Terraform - Specifically, how to use terraform/bin/manage-stack.sh
3. CloudFormation - Specifically, how to use cloud-formation/bin/manage-stack.sh

**Comment by robproper** [comment]
@neilhunt1 
Added Jenkins documentation:
https://github.com/GSA/catalog-deploy/blob/master-demo/jenkins/README.md

This should complete issue 119. If you agree, please close the issues

**Comment by neilhunt1** [comment]
You hit the important points, LGTM, thanks
