### ISSUE TITLE
Do we need to migrate content from the data.gov wiki?

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1190]
There's some content on the [data.gov wiki](https://github.com/GSA/data.gov/wiki) that looks geared towards Inventory users. Is it still relevant, should we migrate it?

**Comment by mogul** [comment]
@hkdctol do you have any insight on this? Should this issue be part of epic #976?

**Comment by jbrown-xentity** [comment]
This is too generic to take on as a ticket, closing.
