### ISSUE TITLE
Dashboard writes to curl_header in non-concurrent-friendly way

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1191]
As far as I can tell, Dashboard prepares some curl request by [writing to `./archive/curl_header`](https://github.com/GSA/project-open-data-dashboard/blob/31f39fefade7a5ef550bce6f4a93240627bd92e1/application/helpers/api_helper.php#L94). If two requests come in at the same time and trigger this, they will end up overwriting each other, causing undefined behavior.

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by adborden** [comment]
Instead, the dashboard should open a temporary file for writing on each request (or just write to an in memory file per request).

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
