### ISSUE TITLE
[Offboard] peter.burkholder@gsa.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1195]
Peter was never fully onboarded, but we will go through the checklist to be thorough.

These tasks are performed by an Admin unless noted as an action for the outgoing team member.

- [x] Team member should move all Data.gov related documents to team drives
- [x] Team member should document any work in progress and schedule a hand-off for any remaining tasks
- [x] Remove team member from Data.gov GitHub teams
  - [data-gov-admins](https://github.com/orgs/GSA/teams/data-gov-admin/members)
  - [data-gov-support](https://github.com/orgs/GSA/teams/data-gov-support/members)
  - [data-gov-ckan-multi-partners](https://github.com/orgs/GSA/teams/data-gov-ckan-multi-partners)
- [x] Remove team member from AWS OPP account
- [x] Remove team member from [AWS sandbox access](https://github.com/GSA/datagov-infrastructure-live/tree/master/iam#new-users)
- [x] Remove team member from [jumpbox operators](https://github.com/GSA/datagov-deploy/blob/develop/ansible/group_vars/all/vault.yml)
- [x] Remove team member from Data.gov email lists
  - [Data.gov support list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagov)
  - [Data.gov team list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagovhelp)
- [x] Remove team member from [Data.gov calendar](https://calendar.google.com/calendar/r/settings/calendar/Z3NhLmdvdl9zcjZ0NG52YjRhOTNjNnNzdHRxYXAzbjZtMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) and events
- [x] Remove team member from Uptrends via [email](https://docs.google.com/spreadsheets/d/1Z9Zpr1mpx-65i_fH2VTbVofPtidpLZs5cnkO0Jz53Vc/edit#gid=0)
- [x] Remove team member from [New Relic](https://newrelic.com)
- [x] Remove team member from [Docker Hub](https://cloud.docker.com/orgs/datagov/teams)
- [x] Remove team member from [Data.gov system accounts](https://github.com/GSA/datagov-account-management) following [Account Mangement Procedures](https://docs.google.com/document/d/1ipn-RX2Py1-jAAI_dbc6OdrK1j4Z8jKaya9C8RPyDa4/edit)
- [x] Remove team member from TTS Bug Bounty access [#bug-bounty-partners](https://gsa-tts.slack.com/messages/C5JQCD9PH)
- [x] Remove team member from [Snyk](https://app.snyk.io/org/data.gov/manage/members)

**Comment by adborden** [comment]
@kvuppala will run through the steps and delegate to @hkdctol and @adborden if necessary.

**Comment by kvuppala** [comment]
@adborden Still lot more check and confirm, I have ensured on few areas where I have access to see user list.

**Comment by adborden** [comment]
Rotation of the Ansible Vault key to be handled in https://github.com/GSA/datagov-deploy/issues/652
