### ISSUE TITLE
Dashboard crawls exit 0 when they cannot connect to the database

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1197]
On CI sandbox, running the dashboard crawl jobs exit 0, even though the database is configured. This will make it impossible to detect an error if the jobs are in fact failing.

## How to reproduce

1. From the dashboard...
1. Edit /var/www/dashboard/current/.env
1. Give bogus database credentials
1. `/usr/bin/php /var/www/dashboard/current/index.php campaign status cfo-act download`

## Expected behavior

Error is printed, exit code is non-zero.

## Actual behavior

No output, exit code is 0.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
