### ISSUE TITLE
DOI needs a harvest clear

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1198]
placeholder, documentation in the [wiki](https://github.com/GSA/datagov-deploy/wiki/Harvest-Cleanup).

**Comment by adborden** [comment]
@jbrown-xentity can you fill in the details, is it specifically [this section](https://github.com/GSA/datagov-deploy/wiki/Harvest-Cleanup#multiple-harvest-sources) that needs to be run?

**Comment by jbrown-xentity** [comment]
Actually, no. The following DB command can be run to "stop" the current harvest (aka mark the hung harvest objects as errors) and allow the harvest job to be marked as completed.

**Comment by jbrown-xentity** [comment]
`UPDATE harvest_object
SET state='ERROR'
WHERE (state = 'IMPORT' OR state='FETCH' OR state='WAITING')
AND harvest_job_id = 'id-of-job'; `

Apparently the job at some point in the last few days released itself, so I'll be marking this as resolved.
