### ISSUE TITLE
Harvest report contains broken URL in footer

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1202]
Harvest report contains the URL `https://admin-https://catalog.data.gov/harvest/usaid-json/job/56c7e482-2e9c-4e7b-a603-d44b57bc142e`

## How to reproduce

1. Add yourself to the harvest job report emails for GSA
1. Run the GSA harvest job
1. Open the report email

## Expected behavior

Footer links to Catalog admin.

## Actual behavior

Footer contains broken link `https://admin-https://catalog.data.gov/harvest/usaid-json/job/56c7e482-2e9c-4e7b-a603-d44b57bc142e`

**Comment by nickumia-reisys** [comment]
All links in current harvester emails are valid.

![image](https://user-images.githubusercontent.com/85196563/216736358-c8c4d4c4-7673-456b-a28a-77048778c260.png)

![image](https://user-images.githubusercontent.com/85196563/216736378-22e380a6-83b1-4e40-af3a-10e1c6fc008b.png)
