### ISSUE TITLE
Prevent operator login on jumpbox using ubuntu user

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1203]
Jumpbox has system users created for each operator, so logging into the host through the `ubuntu` ssh user is undesired.

From the jumpbox, Ansible accesses hosts (including the jumpbox itself) as the ubuntu user which is configured by https://github.com/GSA/datagov-deploy-common.

Updating ubuntu's [authorized_keys](http://man.he.net/man5/authorized_keys) to include a `from="${jumpbox_ips}"` restriction is probably the most straight forward solution. This would prevent an operator from logging into jumpbox from any IP other than jumpbox itself, and the same restriction would apply to all other hosts as well.

Otherwise, restricting operator key access to ubuntu user on jumpbox makes it more difficult to run jumpbox playbooks on the jumpbox itself.

## How to reproduce

From the GSA VPN:
1. `ssh -l ubuntu -i ${operator_key} datagov-jump2d.dev-ocsit.bsp.gsa.gov`

## Expected behavior

Access is denied (except by root SSH key)

## Actual behavior

ubuntu user is allowed access via the operator's key

**Comment by adborden** [comment]
~see https://github.com/GSA/datagov-deploy/issues/1662#issuecomment-628311529 for a potential fix.~

**Comment by adborden** [comment]
I just realized the proposed fix of removing operator keys from the ubuntu user means that it's no longer possible to run the jumpbox playbook from the jumpbox itself. Instead, I'm proposing updating authorized_keys to include the `from=""` restriction, which seems a little more elegant as it applies to all hosts (jumpbox and non-jumpbox) without exception.

**Comment by jbrown-xentity** [comment]
Directly related to #1837, evaluating at the same time...

**Comment by jbrown-xentity** [comment]
Was able to confirm can lock down user access to various servers using the `from="10.0.101.49"` syntax at the front of each key in the authorized_keys file. Will need to create variable for the jumpbox on each system (sandbox, staging, prod) and lock down access to only from the jumpbox for all ubuntu users. This way will still have access to all servers from the jumpbox, but cannot access ubuntu user via SSH directly, you must login as your username.
