### ISSUE TITLE
Detangle dashboard controllers

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1204]
## User Story

In order to enable easier maintenance of the dashboard code, data.gov operators want CodeIgniter controllers to be single-pupose

## Details
Some of the key controller classes in the dashboard handle very complex route patterns, and collect together unrelated operations. These should be refactored into separate controllers to make debugging and maintenance easier.

## Acceptance Criteria
- [ ]

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
