### ISSUE TITLE
Main labs.data.gov page returning 403 error

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1205]
https://labs.data.gov is unavailable

## How to reproduce

Go to https://labs.data.gov

## Expected behavior

Usually returns a page with links to data.json validator and a few other tools

## Actual behavior

403 error
<img width="1440" alt="labs" src="https://user-images.githubusercontent.com/3236989/70547402-ce393780-1b3e-11ea-8ec5-577eb84b2676.png">

**Comment by mogul** [comment]
We unblocked one user by giving them a URL directly to the tool they needed on the dashboard, but anyone else who normally goes through this page to reach their destination is likely getting derailed. 

Aaron thinks resolving this is just a matter of adding `labs.data.gov` to the whitelisted domains for Wordpress.

**Comment by adborden** [comment]
Merged, but not deployed.
