### ISSUE TITLE
Broken link checking for static sites

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1206]
## User Story

As a content editor, I want links on any Data.gov static sites checked regularly in CI so that I can be notified when a link needs to be updated and provide working links.

## Details
Our static sites use [htmlproofer](https://github.com/gjtorikian/html-proofer) which supports checking links on the site. However, sometimes we disable this functionality, and in some cases we run it on a schedule (so we only notice when someone is making a change, which could be much later than the link became broken).

Static sites:
- https://github.com/GSA/resources.data.gov
- https://github.com/GSA/data-strategy
- https://github.com/GSA/sdg-indicators-usa
- https://github.com/GSA/us-data-federation

## Acceptance Criteria
- [ ] Explicit task exists for the link checking (e.g. via make)
- [ ] Link checking is enforced on the master branch
- [ ] Link checking is part of a weekly CI task

**Comment by nickumia-reisys** [comment]
This was implemented before this PR, but the most recent work that consolidated this feature,
- https://github.com/GSA/data.gov/issues/4143
