### ISSUE TITLE
CKAN API access to staging environment

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1223]
## User Story

As a an Agency developer, I want API access to a test environment so that I can test and develop against the CKAN API without worrying about screwing something up.

## Acceptance Criteria
- [ ] Access to the staging or test environment API is not restricted to VPN access.

**Comment by mogul** [comment]
We have an idea for a workaround (setting the agency up in an isolated organization in inventory in production) that doesn't require opening access to a staging environment.
