### ISSUE TITLE
Pre-populate dashboard with agency IDs

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1224]
In order to document and make it easy to expand the set of agencies that the dashboard crawls, we want the set of agency IDs in the production database to be captured in a DB migration in the code repository.

**Acceptance Criteria**

- [x] GIVEN I have a dashboard deployment configured to use an empty database \
  WHEN I run `php public/index.php migrate` \
  THEN the database has a table `offices` \
  AND the `offices` table has > 100 rows

**Details**

There's a [known issue](https://github.com/GSA/project-open-data-dashboard/blob/develop/README.md#known-issues) about the production database having been seeded with agency IDs from an API that no longer exists. That DB is now our authoritative source for agency IDs, and it shouldn't be. We want to memorialize that list as part of our codebase's DB bootstrapping code so that it's always available (for testing, etc.). We expect that having that list will also make it easier to expand coverage as desired for https://github.com/GSA/datagov-deploy/issues/1193 .

**Comment by adborden** [comment]
Not sure if this is a separate story but want to mention it here. Since
that API was deprecated years ago there might have been some drift in
agencies and components. Should we make our Ids/URLs not tied to something
that changes?

**Comment by mogul** [comment]
I don't know. Ideally there'd be something else we can treat as canonical
to replace the API. If not, then maybe we can just convert the PK to a
UUID, and leave the existing ID as a legacy field useful in rough matching
in future...?

**Comment by mogul** [comment]
> Ideally there'd be something else we can treat as canonical
to replace the API.

@philipashlock do you know of anything available or in progress that we can refer to for agency/component layout?

**Comment by mogul** [comment]
If Phil responds, I'll make a separate story for decoupling URLs from the office IDs. Meanwhile the merged PR above addresses this story.

**Comment by mogul** [comment]
(Technically this is not `Done` yet since the code hasn't reached production, but the change only affects non-production environments so I've moved it over anyway.)

**Comment by philipashlock** [comment]
@mogul here's the new Federal Agency Directory API - https://github.com/usagov/USAGov-Platform-API-Documentation/wiki

e.g. https://usagov.platform.gsa.gov/usaapi/api/v1/usagov/directory_records.json

And for general reference, my master doc on the broader effort to establish more of a consolidated canonical registry of agency IDs can be found at https://docs.google.com/document/d/1vsusqxsgHqFhzaHSOXrTJ7sF3IN7LGZVFNNM3m66i4w/edit#
