### ISSUE TITLE
Add list views to https://www.data.gov/open-gov/

### ISSUE THREAD

**Issue by crysacarter** [GSA/data.gov#1227]
https://www.data.gov/open-gov/

above map representation - "list views" 

Files attached. 
[citycountyopensites.xlsx](https://github.com/GSA/datagov-deploy/files/3962349/citycountyopensites.xlsx)

[stateopensites.xlsx](https://github.com/GSA/datagov-deploy/files/3962350/stateopensites.xlsx)

[internationalopensites.xlsx](https://github.com/GSA/datagov-deploy/files/3962351/internationalopensites.xlsx)

@hkdctol

**Comment by mogul** [comment]
@crysacarter There are links that pop up those list views already. What are you after here... Updating the content of the lists? Having a separate way to download the XLSX/CSV?
