### ISSUE TITLE
Catalog playbook does not start pycsw service if it is stopped

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1228]
Seeing the smoke test fail for CSW service when running the catalog playbook. This is because the smoke test runs before the pycsw playbook. The CSW smoke tests should be moved into the pycsw playbook.

## How to reproduce

1. From one of the catalog-web hosts:
1. `sudo supervisorctl stop pycsw-collection`
1. Run the catalog-web.yml playbook from jumpbox

       $ ansible-playbook catalog-web.yml

## Expected behavior

Playbook installs and starts pycsw, smoke test passes.

## Actual behavior

Playbook fails on CSW smoke test.

**Comment by nickumia-reisys** [comment]
Apart from the fact ansible is no more, we also don't have a `pycsw` service anymore
- https://github.com/GSA/data.gov/issues/3710
- https://github.com/GSA/data.gov/issues/3182
