### ISSUE TITLE
New Relic alerts for supervisor programs

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1229]
## User Story

As a Data.gov operator, I want to be notified when a long-lived supervisor process is not running so that I can take action when a critical service is stopped.

## Details
Long-lived processes in supervisor, like pycsw web services don't alert when they are stopped.

## Acceptance Criteria
- [ ] Production processes alert to slack as alert
- [ ] Staging processes alert to email as warning
- [ ] Alert links to runbook

**Comment by nickumia-reisys** [comment]
No more supervisor.  All relevant cloud.gov alerts are configured in NR or there are issues about them,
- https://github.com/GSA/data.gov/issues/3956
- https://github.com/GSA/data.gov/issues/4014
- https://github.com/GSA/data.gov/issues/3349
- https://github.com/GSA/data.gov/issues/3833
