### ISSUE TITLE
data.gov main site should update to a USWDS theme

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1238]
## User Story

In order to make maintenance easy and match other federal websites, the data.gov WordPress site (or the Federalist equivalent to come) should use a theme based on the US Web Design Standards.

## Details

The theme in use for our current WordPress site is not based on USWDS, so we don't benefit from the consistency and maintenance updates happening there. Presuming we stay with WordPress for a while, we can make our lives easier my making use of [an existing USWDS-based WordPress theme and corresponding plugin](https://designsystem.digital.gov/whats-new/updates/2018/02/20/wordpress-theme-benjamin/). (If we move to Federalist, we'd hopefully land on a similar method there.)

## Acceptance Criteria
- [ ] The theme used by data.gov automatically incorporates any improvements that come from new releases of the USWDS.

**Comment by hkdctol** [comment]
Moving this into Wordpress to Static Site epic.

**Comment by hkdctol** [comment]
Will keep this issue, but I think we need other tickets for making sure the rest of Data.gov follows USWDS.

**Comment by hkdctol** [comment]
Going to close this as duplicative -- we have it covered in #3019 and related issues
