### ISSUE TITLE
SDG search page is not readable in high contrast mode

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1242]
SDG search page is not readable in high contrast mode. The text remains black against a black background.

- [ ] This was reported by a user on datagov@, please update the user once we have a resolution.

## How to reproduce

1. https://sdg.data.gov/search/?food
1. In the top right, click the high-contrast mode button (black circle with yellow "A").

## Expected behavior

Text is readable.

## Actual behavior

Text is not readable. Text remains black against the black background.

**Comment by adborden** [comment]
Not sure if this is an issue with us or the upstream theme. Would like to get the theme updated in case the issue is fixed https://github.com/GSA/datagov-deploy/issues/1243

**Comment by jbrown-xentity** [comment]
This is resolved currently, closing.
