### ISSUE TITLE
Update SDG theme

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1243]
## User Story

As a Data.gov developer, I want SDG updated with the latest version of the [open-sdg theme](https://github.com/open-sdg/open-sdg) so that I know I have the latest features and bug fixes..

## Acceptance Criteria
- [ ] SDG is running open-sdg 0.10 or higher

**Comment by jbrown-xentity** [comment]
SDG update is in progress, going to close but tagging @btylerburton in case there is anything relevant here.

**Comment by btylerburton** [comment]
This is done. 🎉 

https://github.com/GSA/sdg-indicators-usa/pull/1115
