### ISSUE TITLE
New harvester for DOT atlas data

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1244]
## User Story

Department of Transportation wants a test of a new harvester for certain atlas data (currently a WAF source on catalog.data.gov) before changing the source in production.

## Details
Test https://maps.dot.gov/NTADmetadata/ as a harvest source on staging
Check results. 
Delete the current source http://maps.bts.dot.gov/webservices/NTADmetadata and replace with new source.

## Acceptance Criteria
- [x] Completed harvest of new source on staging without errors
- [x] Confirm review of the emailed harvest report with our DOT contact
- [ ] Completed harvest of new source on production.

**Comment by hkdctol** [comment]
Awaiting feedback from DOT contact on harvest results

**Comment by hkdctol** [comment]
the agency contact just confirmed harvest of new source on staging was successful according to the harvest report, so we can replace old source with the new in production.

**Comment by ydave-reisys** [comment]
Made changes to the production. Attaching report and screenshot for the same.

**Comment by ydave-reisys** [comment]
[https://app.zenhub.com/files/42135842/bf85bb97-b218-48f8-88b1-ed480191b4d2/download](https://app.zenhub.com/files/42135842/bf85bb97-b218-48f8-88b1-ed480191b4d2/download)

**Comment by ydave-reisys** [comment]
<img width="1440" alt="Screen Shot 2020-02-03 at 11 13 25 AM" src="https://user-images.githubusercontent.com/3017376/73670157-baa9d900-4676-11ea-9c1d-acbe53c6138f.png">
