### ISSUE TITLE
After attempting to upload an organization logo, cannot edit the organization logo

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1247]
@hkdctol reported that when trying to update the logo for [BLS](https://inventory.data.gov/organization/edit/us-department-of-labor-bureau-of-labor-statistics), she first uploaded a PNG, which didn't work (CKAN does not host organization logos, you must link externally). But then, we could no longer update the image URL.

<img width="1440" alt="Screen Shot 2019-12-20 at 4 04 28 PM" src="https://user-images.githubusercontent.com/509703/71299552-b897ef00-2342-11ea-9b05-274a10c45785.png">

## How to reproduce

1. On Inventory, go to [BLS admin](https://inventory.data.gov/organization/edit/us-department-of-labor-bureau-of-labor-statistics)
1. Update image URL to PNG file
1. Click update organization
1. Edit the organization again

## Expected behavior

Image URL field is editable so we can update its URL.

## Actual behavior

Image URL field is no longer editable.

**Comment by adborden** [comment]
I'm going to update the image URL through the API as a work around.

Interestingly, it looks like the logo was successfully uploaded to S3. Maybe image_display_url and image_url were somehow swapped?

```
$ curl -H "Authorization: $CKAN_API_KEY" 'https://inventory.data.gov/api/action/organization_show?id=us-department-of-labor-bureau-of-labor-statistics' | jq '{image_url: .result.image_url, image_display_url: .result.image_display_url}'
{
  "image_url": "2019-12-20-165544.185738BLSemblem2016.png",
  "image_display_url": "https://inventory.data.gov/uploads/group/2019-12-20-165544.185738BLSemblem2016.png"
}
```

**Comment by adborden** [comment]
My attempt at the API didn't work. Instead, I found a hidden "remove" button in the input. I un-hid the button, clicked it. Then I was able to specify the new URL.

**Comment by jbrown-xentity** [comment]
I think this was a one-off bug, closing.
