### ISSUE TITLE
Update organization image_url succeeds, but url is unchanged

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1248]
In trying to work around https://github.com/GSA/datagov-deploy/issues/1247, I tried to edit the image_url of BLS using the API. Despite a successful response, the URL was unchanged.

I tried with `organization_update` and `organization_patch` but got the same behavior. However, if I tried to update the `description`, it worked, even in the same request where image_url and image_display_url were specified.

## How to reproduce

1. Create bls.json file with content:
    ```
    {
      "image_display_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Bureau_of_Labor_Statistics_logo.svg/200px-Bureau_of_Labor_Statistics_logo.svg.png",
      "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Bureau_of_Labor_Statistics_logo.svg/200px-Bureau_of_Labor_Statistics_logo.svg.png",
      "id": "ce1a425c-039b-4e19-821c-e8710fb16cf7"
    }
    ```
1. `curl -v -H "Authorization: $CKAN_API_KEY" --data @bls.json 'https://inventory.data.gov/api/action/organization_patch'`

## Expected behavior

Response shows updated image_url and image_display_url. Going to https://inventory.data.gov/organization/us-department-of-labor-bureau-of-labor-statistics shows the updated fields.

## Actual behavior

Response shows the original image_url and image_display_url. Going to https://inventory.data.gov/organization/us-department-of-labor-bureau-of-labor-statistics shows the old values.

**Comment by jbrown-xentity** [comment]
This is something we never do or deal with, closing.
