### ISSUE TITLE
Resolve content-sniffing problem

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1253]
[details](https://docs.google.com/document/d/1_25KPRLpFC2r_2cJXoa91sUT_2llvf-qpbEX5-2pQog/edit#heading=h.3pl1zeqv3zo3)

(migrated from https://github.com/GSA/datagov-incident-response/issues/57)

**Comment by ydave-reisys** [comment]
<img width="1440" alt="Screen Shot 2020-01-24 at 3 01 33 PM" src="https://user-images.githubusercontent.com/3017376/73115318-52c6f600-3ef2-11ea-9b84-9bb40e5fe1d8.png">
