### ISSUE TITLE
Resolve secure pages with mixed content 

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1254]
[details](https://docs.google.com/document/d/1_25KPRLpFC2r_2cJXoa91sUT_2llvf-qpbEX5-2pQog/edit#heading=h.3n9ptwkrh18o)

(migrated from https://github.com/GSA/datagov-incident-response/issues/58)

**Comment by ydave-reisys** [comment]
<img width="1440" alt="Screen Shot 2020-01-24 at 9 45 25 PM" src="https://user-images.githubusercontent.com/3017376/73115357-daad0000-3ef2-11ea-9ee4-5c108ef89b5e.png">
