### ISSUE TITLE
Resolve XSS filter misconfiguration

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1255]
[details](https://docs.google.com/document/d/1_25KPRLpFC2r_2cJXoa91sUT_2llvf-qpbEX5-2pQog/edit#heading=h.w7m9co7bbwh4)

(migrated from https://github.com/GSA/datagov-incident-response/issues/56)

**Comment by ydave-reisys** [comment]
<img width="1440" alt="Screen Shot 2020-01-24 at 3 01 50 PM" src="https://user-images.githubusercontent.com/3017376/73115331-8bff6600-3ef2-11ea-813a-2f9be3c885a3.png">
