### ISSUE TITLE
ckanext-datagovtheme styles and assets should not depend on www.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1257]
## User Story

As a Data.gov developer, I want everything ckanext-datagovtheme needs to run included so that I don't get strange behavior when a remote dependency is unavailable and causes things to load in an undefined way.

## Details

ckanext-datagovtheme depends on www.data.gov for a few things.
- [background images](https://github.com/GSA/ckanext-datagovtheme/blob/ca23c1e61e7ad432a2d3e2eb88f10ac84a88982e/ckanext/datagovtheme/fanstatic_library/styles/datagovtheme.css#L268)
- [dynamic menu of catgories](https://github.com/GSA/datagov-deploy/blob/1e5bca48f32dcfd0335829aa8972e32b46283a29/ansible/roles/software/ckan/catalog/ckan-app/templates/etc/ckan/production.ini.j2#L221) (really a dependency of ckanext-geodatagov, which is a hard dependency of ckanex-tdatagovtheme)

## Acceptance Criteria
- [ ]

**Comment by jbrown-xentity** [comment]
The dynamic menu could be added into datagovtheme, and just get it directly from GitHub, right? Or would that be bad practice, since we would be relying on GitHub for production?

**Comment by adborden** [comment]
Right, we don't want to depend on any external service, www.data.gov or github.com, at runtime unless absolutely necessary. For the most part, these are static assets that don't change very often, so they could be committed directly to ckanext-datagovtheme. Another option is to fetch them at build time, but committing them directly makes the most sense in this case.
