### ISSUE TITLE
[spike] test CKAN performance when using IaaS solr from cloud.gov CKAN app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1278]
## User Story

As the data.gov team, we want to test the behavior of CKAN when the Solr instance is not "close" (network boundary or latency-wise) so that we can be confident that we have flexibility in where and how we operate our Solr service after moving inventory and catalog to cloud.gov.

## Acceptance Criteria
- [ ] We have comparable New Relic ApDex metrics for our existing and expected architecture
- [ ] We have stories covering how we'll manage authentication between CKAN and Solr

**Comment by adborden** [comment]
As part of this, we'll want some kind of estimate about CKAN memory usage so we have a sense of what to budget on the agreement.

**Comment by mogul** [comment]
Closing as we are now expecting Solr to be deployed in the same AWS region as the applications running on cloud.gov.
