### ISSUE TITLE
When the dashboard crawl scans an unresolvable DNS, the crawl dies

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1280]
When scanning all agencies, www.energysavers.gov shows up but is not resolvable in DNS. This causes the crawl to die.

```
Adding 48030

Attempting to download http://www.energysavers.gov/digitalstrategy.json to /var/www/dashboard/shared/archive/digitalstrategy/2020-01-09/48030.json
Could not read from http://www.energysavers.gov/digitalstrategy.json

ERROR: An Error Was Encountered

        Not valid data.json URL.
```

I think this is related to one of our SSRF "fixes", likely in `campaign->filter_remote_url`. We'll want to make sure this doesn't regress the [SSRF issues](https://github.com/GSA/datagov-incident-response/issues?q=is%3Aissue+ssrf+is%3Aclosed).

## How to reproduce

1. `/usr/bin/php /var/www/dashboard/current/public/index.php campaign status all download`

## Expected behavior

Crawl logs the error and continues.

## Actual behavior

Crawl dies.

**Comment by mogul** [comment]
> I think this is related to one of our SSRF "fixes", likely in `campaign->filter_remote_url`. 

You absolutely nailed this one, @adborden. [The fix](https://github.com/GSA/project-open-data-dashboard/pull/240) is here. There's no way it'll break SSRF protections because by definition a URL that the server can't resolve also can't be used for SSRF!
