### ISSUE TITLE
aureport not functioning as expected

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1283]
Current environment not showing complete logs. The component that is not working is `aureport`, probably has to do with `auditd`.

## How to reproduce

1. Description of steps to reproduce the issue.
Follow [Security Audit process](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities#au-6-log-auditing). The second step produces logs with no data (notes from 1-1-1970 to 1-1-1970).

## Expected behavior

Should give log output with overview of connection and security information from the previous week.

## Actual behavior

Gave no logs or output of any actual statistics.

**Comment by adborden** [comment]
Should be fixed in https://github.com/GSA/datagov-deploy-common/commit/95d1db93301676846d04ea7b08897d2892ca0c2e and will go out in the next release.

**Comment by adborden** [comment]
@jbrown-xentity can you confirm this is resolved?

**Comment by jbrown-xentity** [comment]
This issue is resolved. We still have continuing triage with aureport building out of control requests and causing inventory to crash, still not sure why inventory specifically (log size seems in line with other applications). I believe that is a separate issue though, we can close this one.

**Comment by adborden** [comment]
Thanks, closing.
