### ISSUE TITLE
Create a test organization in Inventory for agencies to test with the API

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1292]
## User Story

As an Agency developer, I want a test organization in inventory.data.gov so that I can test API actions without accidentally effecting my agency's production datasets.

## Details
We currently don't have an environment for third-parties to test against, this is a simple work-around.

## Acceptance Criteria
- [x] Agencies can request access to the test organization, and write changes via the API.

**Comment by pjsharpe07** [comment]
Our test organization has been created and the api has been tested. See below:

![image](https://user-images.githubusercontent.com/38019872/83555785-0dcc5500-a4cc-11ea-98aa-80a352cafa63.png)

**Comment by mogul** [comment]
Thanks for leaving the screenshot! Very handy for being able to demo during the review while you were out. @adborden is going to follow up with the people who asked for this originally.
