### ISSUE TITLE
Deploy fgdc2iso app on cloud.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1299]
## User Story

In order to reduce the operation and maintenance burden of [fgdc2iso](https://github.com/GSA/catalog-fgdc2iso), the data.gov team wants the fgdc2iso application deployed on cloud.gov.
As a Data.gov developer, I want [fgdc2iso](https://github.com/GSA/catalog-fgdc2iso) deployed to cloud.gov so that I can deploy fgdc2iso independent of FCS and the catalog harvesters.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I commit a change to the `main` branch in the `GSA/catalog-fgdc2iso` repository \
  AND I browse to [the CircleCI dashboard](https://app.circleci.com/pipelines/github/GSA/catalog-fgdc2iso)
  THEN I see a deployment pipeline kick off \
  AND the pipeline completes successfully \
  AND the change is visible at `https://fgdc2iso-data-gov.app.internal` (NOTE internal domain; likely have to `cf ssh -L ...` to actually see it)
- [x] If any manual preparation of the target space was necessary, then an issue exists about automating that setup in future.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
We are deploying from the `main` branch to the `gsa-datagov/production` space only. Other branches and spaces are considered out of scope here. Note cronjobs are also out of scope for now.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
None. This work is being done in an environment completely separate from the existing deployment, and only open source and open data are involved.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- [x] Rename the `master` branch if necessary
- [x] Bring any existing cloud-gov branch up to date
- [x] Create any necessary services in the target space with `cf create-service`
- [x] Create a manifest.yml capturing any settings or bindings
- [x] Practice a hand-driven deployment
- [x] Ensure environment settings are configured based on `$VCAP_SERVICES`
- [x] Make sure the health check is correct and passing
- [x] Make sure the curl command works from root of repo: https://<route>/fgdc2iso -d @test/fixtures/tl_2009_us_uac00_url.shp.xml. Should only work with public route (not .internal)
- [x] The README.md should have instructions for hand-deployment
- [x] Add CircleCI or GitHub Action config for deployment to the `production` space

**Comment by pjsharpe07** [comment]
I'm working through the hand-driven deployment and capturing some notes about the current state:

- [x] find a way to use the saxon-license.lic (currently stored in the ansible vault)
- [x] setup and configure internal routes correctly (manifest vs cf cli vs another method)

Thinking ahead for gh actions, currently pusher to `master` create and tag a new version of the war file. I doubt we want to perform this process for each new deployment of cloud.gov. Consider how/when to separate these two processes (creation & use/deployment).

**Comment by pjsharpe07** [comment]
Current issues trying to resolve/mitigate for hand-driven deployment:

- [x] our current method for creating the saxon-license (push json to a cups secret then grab json and write to file via .profile) causes encoding errors
- [x] unable to use the temporary directory to read the saxon-license. Any environment variables created in the .profile don't seem to persist

**Comment by pjsharpe07** [comment]
Some tentative next steps beyond what's missing in the sketch:

- [x] add `process` to manifest.yml. Currently runs both a `web` and `task`. Task doesn't seem to be utilized
- [x] further refine manifest.yml (disk space, memory, etc).
- [x] make and utilize a temporary directory for saxon license or create new issue

**Comment by jbrown-xentity** [comment]
Made new issue for saxon license random directory: https://github.com/GSA/datagov-deploy/issues/2841
