### ISSUE TITLE
Data.gov stack Authentication method/model

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#13]

**Comment by JJediny** [comment]
Data.gov will use MAX.gov Authentication as a Service (AaaS), which is a custom SAML service:
- [ ] Configure current CKAN SAML extension (on Catalog) to work with MAX test sandbox service
- [ ] Install CKAN SAML extension on Inventory
- [ ] Install Max.gov provided WP plugin 
- [ ] Extend/configure WP plugin for other PHP apps

**Comment by kvuppala** [comment]
MAX has been integrated for all data.gov applications
