### ISSUE TITLE
Data.gov access to cloud.gov accounts

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1301]
## User Story

As a member of Data.gov PMO, I want access to cloud.gov so that work can proceed on moving Data.gov applications to cloud.gov.

## Details

There is currently no MOU covering Data.gov use of Cloud.gov. We need to enter into a MOU in order to get necessary accounts to being cloud.gov migration tasks. A MOU request has been made and funding identified, but draft MOU needs to be finalized, funding applied, and MOU signed.

## Acceptance Criteria
- [x] Completed, signed MOU covering one year use of cloud.gov for Data.gov
- [x] Issuance of cloud.gov accounts

**Comment by hkdctol** [comment]
Blocked pending clarification of budget numbers with Stephanie.

**Comment by hkdctol** [comment]
Resolved budget question issue; now awaiting creation of IX and circulation of MOU for signature.

**Comment by hkdctol** [comment]
We have a signed MOU as of 2/10/2020.

**Comment by mogul** [comment]
Account invitations were sent and permissions were set.
