### ISSUE TITLE
Data.gov access to GCP

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1302]
## User Story

As a Data.gov PMO member, I want to get access to GCP under new TTS cloud contract.

## Details

A call order for Data.gov's use of GCP has been issued under the new TTS cloud contract. An initial meeting/working session is required to get access from reseller.

## Acceptance Criteria
- [x] Data.gov team's GCP account(s) are established under the new TTS cloud contract.
- [x] Data.gov team members access GCP

**Comment by hkdctol** [comment]
TTS Acquisition is scheduling a meeting/training with vendor to start access to GCP.

**Comment by hkdctol** [comment]
Initial meeting, government only, scheduled for 2/12.

**Comment by mogul** [comment]
We have invitation mails to set up our GCP organization now.

**Comment by mogul** [comment]
I've confirmed my access but @adborden is out so this is blocked until he returns.

**Comment by mogul** [comment]
(Aaron, look for mail with subject line `Join my project on Google Developers Console` on February 25th.)

**Comment by adborden** [comment]
:heavy_check_mark: I've accepted.
