### ISSUE TITLE
CloudFront refers to non-existent /errors/500.html

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1312]
I think that requests that would result in a 500 end up returning a 404 page, since the /errors/500.html does not exist.

## How to reproduce

1. https://catalog.data.gov/errors/500.html

## Expected behavior

A 500, Server Error page is displayed

## Actual behavior

A 404 Not Found error page is displayed

**Comment by adborden** [comment]
@FuhuXia are you familiar with why we configure these custom 500 pages? Are they supposed to be served from CKAN?

**Comment by FuhuXia** [comment]
A custom 500.html is need so user dont see a plain apache error page. it can be served from ckan or cloudfront (if possible). The 500.html itself will be cached, so where it resides doest not matter much performance-wise.  But the origin 500 response should not be cached.

**Comment by adborden** [comment]
Just ran into it by chance. It should be served via filestore.data.gov, similar to wordpress. I'm adding it to [datagov-filestore-landing](https://github.com/GSA/datagov-filestore-landing/pull/3/files#diff-28cd7814fb44f09190f831ac4c723782) so it is under version control. Once that is shipped, I will update the CloudFront configuration, which should fix this issue.

**Comment by mogul** [comment]
James is doing a deploy and then Aaron will make an update in Cloudfront.

**Comment by adborden** [comment]
The fix is to add a new origin to filestore.data.gov in CloudFront that matches the `/errors/*` pattern. This is similar to how the WordPress CloudFront issue is configured.

**Comment by adborden** [comment]
Added a new origin for filestore.data.gov to the catalog CloudFront distribution:
<img width="1012" alt="Screen Shot 2020-02-07 at 10 46 55 AM" src="https://user-images.githubusercontent.com/509703/74056741-65800700-4997-11ea-9f9c-b5c02dcc9fcb.png">

Added the the errors behavior so any requests to `catalog.data.gov/errors/500.html` will be served from the filestore.data.gov origin:
![screencapture-console-aws-amazon-cloudfront-home-2020-02-07-13_10_54](https://user-images.githubusercontent.com/509703/74066134-615de480-49ab-11ea-892c-01fc2df1bb1d.png)

Error page: https://catalog.data.gov/errors/500.html
