### ISSUE TITLE
dashboardweb1d keeps going offline

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1314]
https://alerts.newrelic.com/accounts/1601367/incidents/105281829/violations

We've seen this several times, have BSP reboot the instance, but it keeps getting into this situation.

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by adborden** [comment]
My hunch is that it's the dashboard crawl, maybe the staging instances are under powered or some performance tuning is necessary.

**Comment by adborden** [comment]
From our sync today: Let's open a ticket with BSP to update the memory for dashboard instances to match production. BSP should also update the CloudFormation stack so that this isn't a one-time change but integrated into their automation.

**Comment by nickumia-reisys** [comment]
Woah! Pre-Nick Era.  No idea if it was fixed, but the system no longer exists.
