### ISSUE TITLE
Cron emails sometimes generate a warning about IPv6 being disabled

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1315]
https://groups.google.com/a/gsa.gov/forum/#!topic/datagovhelp/ZRX5z52-atQ

```
send-mail: warning: inet_protocols: disabling IPv6 name/address support: Address family not supported by protocol
postdrop: warning: inet_protocols: disabling IPv6 name/address support: Address family not supported by protocol
```

I believe we've only seen this on bionic hosts.

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by adborden** [comment]
AFAIK, IPv6 is supposed to be disabled. Not sure if this is a bug in the reboot-notifier script.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
