### ISSUE TITLE
Rotate TLS certificate for data.gov domains

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1318]
## User Story

As a Data.gov operator, I want a new data.gov TLS certificate so that I can continue providing the data.gov service securely, without interruption in service.

## Details
Current certificate expires Monday, March 30, 2020 at 5:00:00 AM.

Instructions are on the [wiki](https://github.com/GSA/datagov-deploy/wiki/TLS-SSL-Certificates) and requires us generating a certificate request and submitting it to GSA through Service Now.

## Acceptance Criteria
- [ ] When I go to https://catalog.data.gov/dataset and I click the lock icon to see certificate details, the expiration date is a year out in 2021

**Comment by adborden** [comment]
60 days out.

**Comment by adborden** [comment]
@mogul how should we assign a milestone to this?

**Comment by mogul** [comment]
@adborden at our last retro we said we would assign issues to the last monthly milestone before it's actually due, and committed to starting issues at least two sprints before the date of the milestone to which they're assigned.

**Comment by adborden** [comment]
:+1: so since this is due March 30th, we should put it in the February milestone, and start it sometime in one of the February sprints?

**Comment by mogul** [comment]
I think we'd put it in the March milestone and make sure we're starting it by March 1st.

**Comment by mogul** [comment]
The external site certificate is ready, and the two internal certificate requests are in flight. We can install certificates for the Cloudfront distribution  (catalog, wordpress), but not for other services that are only fronted by the load-balancer (dashboard, etc). Those go through BSP.

**Comment by FuhuXia** [comment]
Catalog and Wordpress have new certificates installed on Cloudfront. New expiration date is 2021-04-23, that is 407 days from today.

**Comment by FuhuXia** [comment]
Internal host certificates were added to prod and staging in the PR listed above. External site certificate was requested to be added into BSP following same steps as https://github.com/GSA/datagov-deploy/issues/574#issuecomment-598251495.

**Comment by FuhuXia** [comment]
BSP has completed external site certificate installation.
