### ISSUE TITLE
Operator accounts get locked out for password expiration

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1320]
Even though jumpbox configures [accounts not to expire](https://github.com/GSA/datagov-deploy-jumpbox/blob/master/tasks/main.yml#L34) with locked passwords, the password expiration is still set (by the [hardening playbook](https://github.com/GSA/ansible-os-ubuntu-16/blob/669c2f9b7192602942cdd8f38d6b432baf8b4905/tasks/section5.yml#L286)?). After 90 days of account creation, the account will be locked.

Work around is to log into the jumpbox as `ubuntu` user (or ask a team member) and run chage on your account `sudo chage -M -1 -I -1 <username>`

## How to reproduce

1. Create a new account via jumpbox_operators
1. `sudo chage -l <account>`

## Expected behavior
Password does not expire

## Actual behavior
Password will expire in 90 days.

**Comment by adborden** [comment]
I should add that passwords are locked, so making passwords never expire should not be relevant because you cannot log in with a password.

**Comment by jbrown-xentity** [comment]
A team member was locked out again today. Not sure if this is just a lingering issue, or if something is not working with the fix.

**Comment by adborden** [comment]
Looks like a wave of folks were just locked out of mgmt.

**Comment by adborden** [comment]
Here's an example of chage for a locked account:
```
ubuntu@datagovjump1m:~$ sudo chage -l adborden
Last password change                                    : Jan 06, 2021
Password expires                                        : Apr 06, 2021
Password inactive                                       : May 06, 2021
Account expires                                         : never
Minimum number of days between password change          : 7
Maximum number of days between password change          : 90
Number of days of warning before password expires       : 7
```

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
