### ISSUE TITLE
DOJ Harvest Stuck

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1325]
DOJ harvest on January 16 did not get the expected data results. Specifically [Informal Enforcement Actions](https://catalog.data.gov/dataset/informal-enforcement-actions-fef8d) collection did not have the expected 10 referenced datasets.

## How to reproduce

1. View link above, note missing datasets. 

## Expected behavior

See the [POD data](http://www.justice.gov/data.json) for reference on what data should be.

## Actual behavior

Data missing

**Comment by adborden** [comment]
Did you spot errors in the logs related to this harvest?

**Comment by jbrown-xentity** [comment]
Nothing specific related to this issue, no.
