### ISSUE TITLE
Inventory package_search API does not include private datasets

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1327]
As a member of `department-of-labor` organization, https://inventory.data.gov/api/action/package_search?fq=organization:department-of-labor should show 17 datasets, however it shows none. All the datasets are set as private and are not included in `package_search` which severely limits the usefulness of the API.

Note: this is fixed in CKAN 2.6, `package_search` was [updated to show private datasets](https://github.com/ckan/ckan/pull/3191) by default to organization members and adds the `include_private` parameter to disable. Inventory is currently based on CKAN 2.5.

**Work-around:**  the `organization_show` API can be used with `include_datasets` to show private datasets. The datasets are included under the `.result.packages` properties. This can be used to get the `id` or `name` of each package, and full details from the `package_show` API. e.g.

    $ curl -v -H "Authorization: $CKAN_API_KEY" 'https://inventory.data.gov/api/action/organization_show?id=department-of-labor&include_datasets=true'  | jq '.result.packages'

## How to reproduce

1. Add yourself as a sysadmin or department-of-labor organization member.
1. `curl -v -H "Authorization: $CKAN_API_KEY" 'https://inventory.data.gov/api/action/package_search?fq=organization:department-of-labor'`

## Expected behavior

API shows all DOL datasets, including private ones to organization user.

## Actual behavior

API shows no datasets.

**Comment by mogul** [comment]
We expect to address through ongoing work to upgrade to CKAN 2.8+
