### ISSUE TITLE
Support FGDC creating and validating test harvest sources

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1334]
## User Story

As a FGDC, I want Data.gov support in creating test harvest sources in Catalog (in production) so that I can validate the new XSLT/harvest changes against various metadata test cases.

## Details
FGDC will provide us with a new XSLT and with WAF harvest links to add to catalog.data.gov and facilitate manual test harvesting.

## Acceptance Criteria
- [x] FGDC confirms they are unblocked and can view the harvest results.

**Comment by adborden** [comment]
First request,

@jbrown-xentity can we confirm that for harvest you need separate folders for each type of Metadata (ISO 19139, CSDGM or JSON)?  If yes, we'll take the action to get those directories activated and move the files in:
https://apps.usgs.gov/FGDC-Test/WAF_CSDGM/
https://apps.usgs.gov/FGDC-Test/WAF_ISO_19139/
https://apps.usgs.gov/FGDC-Test/WAF_JSON

**Comment by jbrown-xentity** [comment]
The JSON is a single file, and it needs to live outside of the xml WAF harvest. The other 2 I'm not sure, but it would probably be a good idea. Most of DOI's harvest sources are set to auto detect, I don't know if it does that on an individual level or at the entire harvest level...

**Comment by adborden** [comment]
@jbrown-xentity you should be on the email thread in case you want to reach out directly. Splitting the up the resources it the current plan.

**Comment by jbrown-xentity** [comment]
@adborden sent. Will wait on next steps. Do we have an xslt file from them to implement on sandbox for testing?

**Comment by adborden** [comment]
Not yet. I think the work for this story is mostly about providing support via email to FGDC to setup the harvest sources.

If/when they provide the XSLT... well, this is something I have never had to do myself, so this is new territory :grin: 

1. First, they can submit a PR to the [application repo](https://github.com/GSA/catalog-fgdc2iso) (or we can do it for them).
1. Build a new war archive of the application.
1. Commit the new war archive in [datagov-deploy](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/catalog/harvest/files/var/lib/tomcat6/webapps/fgdc2iso.war). :nauseated_face: 
1. Run the catalog.yml playbook to deploy the harvesters (which includes fgdc2iso).

... And consider implementing https://github.com/GSA/datagov-deploy/issues/865 to improve the process ^ by building the war artifact in CI, and then pulling the artifact from GH instead of committing it to datgov-deploy.

**Comment by adborden** [comment]
@FuhuXia has probably done a version of this  :point_up:

**Comment by jbrown-xentity** [comment]
Add the following users to sandbox for access:
- Lynda Wayne
- Jim Irvine
- Robin Hoban: 
- Lorna Schmid: lorna@usgs.gov

**Comment by mogul** [comment]
Still blocked waiting on XSLT

**Comment by jbrown-xentity** [comment]
Requested update. Current status is the "test WAF" on FGDC side is misconfigured, the JSON files are not setup properly (currently in XML format?). We now have the XSLT file, along with relevant documentation...
[csdgm_iso_transform.zip](https://github.com/GSA/datagov-deploy/files/4307367/csdgm_iso_transform.zip)

**Comment by mogul** [comment]
Still waiting on the other side.

**Comment by jbrown-xentity** [comment]
There are a number of outstanding issues on this ticket. Refactoring into multiple tickets. This will be the work to setup the test harvest source into production.

**Comment by mogul** [comment]
Waiting on harvests to proceed here.

**Comment by jbrown-xentity** [comment]
Harvests are complete, with associated errors. Will send to FGDC and await analysis. Closing.
For reference, harvest sources:
- https://admin-catalog.data.gov/harvest/admin/csdgm-test-waf
- https://admin-catalog.data.gov/harvest/admin/iso-test-waf
- https://admin-catalog.data.gov/harvest/admin/json-test-waf

All datasets in these harvest sources that were harvested correctly appear in the FGDC organization: https://admin-catalog.data.gov/organization/fgdc-gov
