### ISSUE TITLE
jenkins_build script needs to be shared across repos

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1340]
## User Story

As a Data.gov developer, I want the jenkins_build script shareable across repos so that I can easily reuse the script in app deploys without copy/pasting code.

## Details
https://github.com/GSA/datagov-deploy/pull/1218/files#diff-c18e084e19ebd649b735f139b17094b9 is a script to trigger a job on a Jenkins instance.

## Acceptance Criteria
- [ ] I can use the jenkins_build script from catalog-app

**Comment by nickumia-reisys** [comment]
No more Jenkins,
- https://github.com/GSA/data.gov/issues/3710

We handle the need for duplicate files as best as we can.  For example,
- We use templates to reduce duplication of our CI pipeline
  - https://github.com/GSA/data.gov/issues/4121
- We put files in one repo and then call it in other repos
