### ISSUE TITLE
Robust applications in sandbox*

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1341]
As a Data.gov developer, I want applications in the sandbox environments to be fully setup with as much feature parity as staging and production as possible so that when I deploy to sandbox, I have high confidence that applications will deploy to BSP environments.

## Details

Currently, not all applications are working in sandbox. Maybe they need some database initialization, maybe they need an S3 bucket, maybe they need a configuration change.

**Comment by hkdctol** [comment]
This epic has been entered into GitHub projects https://github.com/orgs/GSA/projects/11/views/4

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
