### ISSUE TITLE
Develop approach to collections issue for migration to CKAN 2.8

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1347]
## User Story
As Data.gov PMO, I want to develop an approach to addressing the collections issue in catalog.data.gov for the migration to CKAN 2.8.

## Details
Data.gov has a unique implementation of collections currently, and we need to have a clear approach to addressing collections for the move to CKAN 2.8

## Acceptance Criteria
- [ ] Approach agreed to by Data.gov PMO that incorporates input from stakeholders (other agencies)
- [ ] Next steps outlined in issues in this repository ready to be worked.

**Comment by mogul** [comment]
(Closed this epic as redundant with #514, and reparented the issues over to it.)
