### ISSUE TITLE
List the available alternatives on collections issue

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1348]
## User Story

As Data.gov PMO, I want to review available alternatives in handling collections and answer questions on how the alternatives would handle the relevant harvest sources.

## Details

- Ckanext-geodatagov has the collections harvest feature: https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/harvesters/waf_collection.py

- Ckanext-scheming allows custom fields to be added to the schema.

## Acceptance Criteria
- [ ] Complete list of alternatives with applicable information on the required harvest sources/types.

**Comment by jbrown-xentity** [comment]
This is clearly focused on CKAN handling of collections; going to close for now.
