### ISSUE TITLE
Conduct User Centered Design on Collections Issue

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1349]
## User Story

As Data.gov PMO, I want to incorporate user needs in determining the approach to collections so that the adopted solution meets user needs.

## Details

- Consult agencies using collections. (waf collections by organization) (organizations containing a collection) (curl -v 'https://catalog.data.gov/api/action/package_search?fq=collection_package_id:*&facet.field=\["organization"\]&facet.mincount=1&rows=0'  | jq -r '.result.search_facets.organization.items[] | [.name,.count,.display_name] | join (",")' > collection_members_by_organization.csv)

- Get stakeholder views on dataset count issue

## Acceptance Criteria
- [ ] Data.gov PMO agreement that we have gathered adequate input from agencies on each of the options considered for next steps in collections.

**Comment by jbrown-xentity** [comment]
@hkdctol I feel like some of this was done. Let's either close this, or take this on with new catalog redesign.

**Comment by hkdctol** [comment]
I think we can close
