### ISSUE TITLE
Data.gov access to login.gov

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1358]
## User Story

As a member of data.gov PMO, I want access to login.gov so that migration of data.gov applications away from max.gov can proceed.

## Details

GSA has rescinded its ATO for use of max.gov as the Identity Provider (IdP) for GSA applications. data.gov applications will need to make use of a GSA-approved IdP in order to get their ATOs renewed. login.gov seems like the obvious choice, given it has a GSA ATO, supports PIV cards for multi-factor authentication, has a good UX, and is operated by a neighboring team. Based on our experience with cloud.gov, in order to make use of login.gov, it's likely we'll have to have an internal MOU in place.

## Acceptance Criteria
- [x] Completed, signed MOU covering one year use of login.gov for Data.gov
- [ ] Provision of access from data.gov applications to login.gov and any necessary accounts for managing that access

**Comment by mogul** [comment]
Amos said:
> no promises, yet. but, if there truly is a use-case where you’d be 100% AAL3 via PIV/CAC then we may be able to offer it at a lower rate since it would likely mean higher volume (auths per user) and reduced cost for us (no SMS, for example). we can definitely discuss further

**Comment by mogul** [comment]
I guess the next step here is to set up a meeting.

**Comment by hkdctol** [comment]
Met with login.gov team this afternoon. There is an existing MOU that we can use, so no further paperwork required at the moment. They have set up sandbox access and @mogul will be able to add access.

**Comment by mogul** [comment]
Per [these instructions](https://developers.login.gov/testing/) I filled out the form to ask for access to the sandbox today.

**Comment by mogul** [comment]
cc @starsinmypockets

**Comment by mogul** [comment]
I got access to the login.gov developer dashboard and created a team there... @starsinmypockets @adborden @FuhuXia, you should have invitations in your inbox. Try to log in and create a login.gov development account when prompted (note this is not the same as the production login.gov account).  Once that's done fill out [this form](https://dashboard.int.identitysandbox.gov/service_providers/new) to register catalog for access.

**Comment by adborden** [comment]
FYI, I did not get an email, but I was able to go to the identity
sandbox link, create an account, and once in, I did see that I was part
of the data.gov team.


--
Aaron D Borden
Human and hacker

**Comment by porta-antiporta** [comment]
@mogul FYI, the ability to require a user to authenticate with only a PIV/CAC is now available on login.gov. https://developers.login.gov/oidc/
> http://idmanagement.gov/ns/assurance/aal/3?hspd12=true
This specifies that a user has been authenticated with an HSPD12 credential (requires PIV/CAC)

**Comment by mogul** [comment]
@woodt Should this be going on a board somewhere? Or do we feel like this is done now?

**Comment by mogul** [comment]
We've long since switched to using login.gov for data.gov applications... Closing this one.
