### ISSUE TITLE
Ensure dashboard schema upgrades happen atomically

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1359]
## User Story

In order to ensure the dashboard's database is never in an "in-between" state, we want schema updates to happen within a database transaction.

## Details
We've twice seen a deployment of the dashboard app result in a database where schema changes have already been applied, but the "version" table was not updated to reflect that at the end of the process. This results in an application outage, because every request will then attempt to make the same schema version changes and fail because they're already there. Using a transaction will ensure the database cannot be left in that "in-between" state, and will give us better ability to understand the root cause if this happens again.

## Acceptance Criteria
- [x] GIVEN a database with an out-of-date schema \
  WHEN I run a migration that changes the schema in a specific way and then deliberately fails \
  THEN the database remains at the out-of-date schema version \
  AND the schema changes are rolled back
  AND page-loads give a 5xx error

**Comment by mogul** [comment]
> This results in an application outage, because every request will then attempt to make the same schema version changes and fail because they're already there. Using a transaction will ensure the database cannot be left in that "in-between" state, and will give us better ability to understand the root cause if this happens again.

I thought this was going to be a relatively straightforward change but... surprise! Unlike _good_ databases, [MySQL doesn't support transactions around DDL statements.](https://hashrocket.com/blog/posts/mysql-has-transactions-sorta) This means that so long as we're using MySQL, it's not actually possible to implement atomic migrations in a generalizable way.

(In fact it's likely this property that resulted in the problems we've seen: Not all statements in a previous attempt at applying the migration completed successfully, so CodeIgniter didn't update the version. Nevertheless _any_ DDL statements that did run were left in place!)

Several disciplined coding practices are required to avoid any potential problems:
* **Every individual DDL statement should be in its own CodeIgniter migration, and each  migration should include DDL that implements the `down()` method.**
* Every `CREATE TABLE/DROP TABLE` DDL statement in a migration should use `IF NOT EXISTS/IF EXISTS` to ensure table creation/dropping is idempotent.

On this last point: There's no MySQL equivalent to `ALTER TABLE ADD COLUMN c **IF NOT EXISTS**` or `ALTER TABLE DROP COLUMN c **IF EXISTS**`. There is [a relatively usable workaround for this gap](https://stackoverflow.com/a/49676339) using stored procedures and prepared statement. I'm planning to have our `Migrate` class create the stored procedure so that migration scripts can use it, but it's still going to require everyone to remember to do that.

**Comment by jbrown-xentity** [comment]
When rolled out to staging, we get an error:
```
A Database Error Occurred, Error Number: 1419
You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
Filename: migrations/009_add_idempotent_migration_scaffolding.php</p><p>Line Number: 46
```
This has to be enabled at the AWS RDS level, you can see details [on AWS documentation](https://aws.amazon.com/premiumsupport/knowledge-center/rds-mysql-functions/)

Next Steps: 
1. Set up sandbox RDS appropriately for access, document necessary steps/terraform code
2. Open a ticket with BSP to set correct permissions on staging and production RDS, attach the necessary steps/terraform code

**Comment by mogul** [comment]
Here's an [example of setting the parameter group up in Terraform](https://github.com/terraform-providers/terraform-provider-aws/issues/217#issue-235633432)

**Comment by mogul** [comment]
Aaron notes that we should probably try to capture what the parameter group settings are on the BSP side, if they're not the default, so we can better understand where there might be deltas between sandbox and staging.

**Comment by mogul** [comment]
> Next Steps:
> 
> 1. Set up sandbox RDS appropriately for access, document necessary steps/terraform code
> 2. Open a ticket with BSP to set correct permissions on staging and production RDS, attach the necessary steps/terraform code

Aaron and I discussed today and decided that rather than sinking more time into the scope of this one issue, we'll simply request that BSP add the necessary parameter to the parameter group in production and staging (and tell us the full set for our records), then deploy this change. I've made that request (REQ0525850) and am moving this issue to `Blocked` until we get a response and can deploy the PR.

As for Terraform: Once we have the Parameter Group settings from BSP, we will close this issue and leave a documented `environment-drift` tech debt issue in its place covering the task of making the sandbox match production.

**Comment by adborden** [comment]
BSP has made the parameter group change this weekend, moving to In Progress.

**Comment by mogul** [comment]
Spoke too soon, they also need to restart the DBs for the parameters to
take effect. Any thoughts on acceptable hours for dashboard to be
unavailable?

**Comment by mogul** [comment]
I let them know that any time after west coast business close and east coast business open would be fine on Tuesday, but I haven't heard back. I poked the thread morning since we're still blocked on deploying this.

**Comment by mogul** [comment]
(ServiceNow reference: RITM0728478)

**Comment by mogul** [comment]
DB reboot is now expected to happen after 10pm ET today.

**Comment by mogul** [comment]
FCS confirmed the production reboot happened (not clear when), so this is unblocked.
