### ISSUE TITLE
Harvest not working for New Mexico

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1367]
The harvester attempts to add a large number of folders (1K+) in searching the WAF. After the full WAF scan, it gives this error:

`sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back by a nested rollback() call.  To begin a new transaction, issue Session.rollback() first.`

Summary of stack trace is as follows:
```
harvest/commands/harvester.py - ln 135
harvest/queue.py - ln 243
ckan/ckan/model/domain_object.py - ln 63 (save), ln 73 (commit)
```

## How to reproduce

1. Click Re-harvest on the [harvest source](https://admin-catalog.data.gov/harvest/admin/new-mexico-resource-geographic-information-system-nm-rgis)
2. Watch the gather logs for error (after 10+ minutes)

## Expected behavior

Harvest to complete successfully (or at least make it to fetch stage)

## Actual behavior

Harvest failed into bad state, says running but never successfully finished the gather stage and therefore is not truly "Running".

**Comment by hbarrett** [comment]
I believe we originally organized the metadata this way as there was a problem with harvesting from a folder with too many files in it. If this is more a problem with how we organized the files, rather than a problem with the harvester, we can re-organize the metadata. We have 116191 metadata files to harvest. If we sorted them by the first char of the UUID then we would only have 16 folders with a little over 7000 files per dir. Would that work?

**Comment by FuhuXia** [comment]
@hbarrett We tried harvesting the WAF source again in our development environment. 5402 metadata files were found and successfully harvested. I believe if there was 116191, harvesting should be fine too. The way files/folders are structured is good. We are looking at other cause for the Error.

**Comment by hkdctol** [comment]
Re-opening as broken links have been discovered so that we can look for cause. @FuhuXia do you recall if we ever harvested correctly on production? @hbarrett

**Comment by FuhuXia** [comment]
@hkdctol I did not harvested it manually on production. We can do it anytime if needed. I believe the issue that got it stuck has been resolved.

**Comment by FuhuXia** [comment]
It is harvested successfully today.
