### ISSUE TITLE
Mixed content over HTTPS

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1371]
Please keep sensitive details in our [Data.gov Drive](https://docs.google.com/document/d/1Dy0JK1kJR31z_0-VfzKmnojelZ9NwB_hZ97prn6j2eQ/edit#heading=h.2jted1abkj2c)

**Comment by ydave-reisys** [comment]
<img width="1440" alt="Staging after fix" src="https://user-images.githubusercontent.com/3017376/75278354-b84f2080-57d7-11ea-9c32-b1a62c64a2dd.png">
<img width="1440" alt="Prod after fix" src="https://user-images.githubusercontent.com/3017376/75278359-ba18e400-57d7-11ea-8eb9-5feb13456912.png">
![Uploading Staging before fix.png…]()

**Comment by ydave-reisys** [comment]
<img width="1440" alt="Staging after fix" src="https://user-images.githubusercontent.com/3017376/75278400-cd2bb400-57d7-11ea-8921-d8fe99fa78de.png">
<img width="1440" alt="Prod after fix" src="https://user-images.githubusercontent.com/3017376/75278403-ce5ce100-57d7-11ea-879e-16486bbbecb4.png">
<img width="1440" alt="Staging before fix" src="https://user-images.githubusercontent.com/3017376/75278408-cf8e0e00-57d7-11ea-926d-ff97823a7282.png">
<img width="1440" alt="Prod before fix" src="https://user-images.githubusercontent.com/3017376/75278411-d0bf3b00-57d7-11ea-8b63-3ad79edf6c3a.png">
