### ISSUE TITLE
Remove trusty infrastructure for inventory-web

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1374]
## User Story

As a Data.gov operator, I want inventory-web's trusty infrastructure remove so that I don't have to carry risk of having unused old infrastructure around.

## Details
Splitting this out from https://github.com/GSA/datagov-deploy/issues/717.

## Acceptance Criteria
- [ ] BSP ticket is created to remove the trusty EC2 instances

**Comment by mogul** [comment]
Holding off on this until April to make sure we're confident in our migration to Bionic.

**Comment by mogul** [comment]
Now that we're [removed the urgency to get off of 14.04](https://github.com/gsa/datagov-deploy/issues/571#issuecomment-648988887), we're planning to do the Bionic upgrade in the course of migrating to cloud.gov, rather than rolling our Ansible-managed hosts in FCS. So, closing this issue!
