### ISSUE TITLE
Remove ckanext-s3filestore fork

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1376]
## User Story

As a Data.gov developer, I want to remove the fork so that I have less code to own and maintain.

## Details
This issue is to track the discussion and details for removing ckanext-s3filestore

[Fork](https://github.com/GSA/ckanext-s3filestore)
[Upstream](https://github.com/okfn/ckanext-s3filestore)

## Acceptance Criteria
- [ ] Any bug fixes or features are submitted to upstream as pull requests
- [ ] Fork is rebased to a recent version of upstream

**Comment by adborden** [comment]
Seems there are only two commits on the fork related to using AWS IAM roles instead of access tokens.

**Comment by avdata99** [comment]
We also created #1423 which is a more deep analysis on this same matter. Maybe we can close this issue and continue there.

**Comment by adborden** [comment]
Closing as duplicate of https://github.com/GSA/datagov-deploy/issues/1423
