### ISSUE TITLE
[research: 3d] Identify www elements that need static replacements

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1382]
## User Story
In order to decide whether we should convert it to a static site before or after moving to cloud.gov, we need to understand the obstacles to replacing dynamic elements of the www.data.gov site.

## Acceptance Criteria
- [ ] We have a clear list of the dynamic elements on www.data.gov that don't already have a static-side equivalent available

## Details

We _think_ this is just the "contact us" form, but there may be others, or considerations around extensions in use. Touchpoints may be able to fill some gaps.

**Comment by adborden** [comment]
Some preliminary research has been done already https://docs.google.com/document/d/1VS2qLb8d24Icz7KLJft23KbDQK9WxuBmFbXiIq2etA4/edit#

**Comment by mogul** [comment]
Attaching PDF of the above document here as there's nothing secret in it. @SaiUdthawar-REI 
[WordPress migration to static site.pdf](https://github.com/GSA/datagov-deploy/files/4320959/WordPress.migration.to.static.site.pdf)

**Comment by SaiUdthawar-REI** [comment]
Here are the dynamic elements in Data.gov site where users send Data or Write Data to:

1) Contact Form-https://www.data.gov/contact
2)In Applications where users need to submit application suggestions to https://docs.google.com/forms/d/e/1FAIpQLSeiewrzB2ImS5xGSlgeR72VxpnbofubMe8zN5yCcEyG_xiZqA/viewform
3)Each Topic has got its respective contact form Like Agriculture Topic has its own ContactAgriculture where users use this form to contact the Agriculture Topic leads.
4)In Local Government Topic, users need to add their Data Catalog to Data.gov using https://www.data.gov/local/add.

**Comment by hkdctol** [comment]
I think we need 1) data.gov/contact and 4) Local Gov the /add form, the others we do not need.

**Comment by SaiUdthawar-REI** [comment]
We have 15 Custom built Plugins for Data.Gov in WordPress. Here are the Plugins and their Git Repos:

1)**ArcGis Map Validation**-This plugin validates map using the the map id and group id
      Git Repo: https://github.com/GSA/arcgis-map 
2)**Better WordPress External Link**-Gives you total control over external links on your website. This plugin 
       also comes with a comprehensive domain filtering feature. BWP External Links is based on the popular 
       Prime Links phpBB mod by Ken F. Innes IV (Prime Halo).
       Git Repo: https://github.com/GSA/bwp-external-links
3)**Custom Permalinks**-Set custom permalinks on a per-post basis
       Git Repo: https://github.com/GSA/custom-permalinks
4)**Custom Post Type View Generator**
       Git Repo: https://github.com/GSA/custom-post-view-generator.git
5)**DataGov Custom**-This plugin holds custom types/taxonomies definitions, actions, filters etc.
       Git Repo: https://github.com/GSA/datagov-custom
6)**Inactive Logout**-Inactive logout provides functionality to log out any idle users defined specified time 
       showing a message. Works for frontend as well.
       Git Repo: https://github.com/GSA/inactive-logout
7)**Metric Count**-This plugin makes API call to Ckan AND stores dataset count for each organization.
        Git Repo: https://github.com/GSA/metric-count
8)**Restrict Categories**-Restrict the categories that users can view, add, and edit in the admin panel.
       Git Repo: https://github.com/GSA/restrict-categories
9)**SAML 2.0 Single Sign-On**-Authenticate users using simpleSAMLphp.
        Git Repo: https://github.com/GSA/saml-20-single-sign-on
10)**Sticky Posts In Category**-Shows sticky posts on top of Category pages
         Git Repo: https://github.com/GSA/sticky-posts-in-category
11)**Twitter posts to Blog**-Post tweets to your blog
        Git Repo: https://github.com/GSA/twitter-posts-to-blog 
12)**Twitter Widget Pro**-A widget that properly handles twitter feeds, including @username, #hashtag, 
          and link parsing. It can even display profile images for the users. Requires PHP5.
          Git Repo: https://github.com/GSA/twitter-widget-pro
13)**USA search**-This plugin implements the USA search functionality.
         Git Repo: https://github.com/GSA/usa-search
14) **WP Sitemap Page**- Add a sitemap on any page/post using the simple shortcode [wp_sitemap_page]
           Git Repo: https://github.com/GSA/wp-sitemap-page
15)**Open311 Web App**-A WordPress plugin that acts as a web app for interacting with an Open311 
          service.
          Git Repo: https://github.com/GSA/wp-open311.

**Comment by SaiUdthawar-REI** [comment]
Attaching Word Document where I have went through few google pages and pasted the Links in Word Document so that we can move the Custom plugins from WordPress to a static site.

[https://app.zenhub.com/files/42135842/6a9d474d-d5f1-4a9b-b078-2889fafbe5f0/download](https://app.zenhub.com/files/42135842/6a9d474d-d5f1-4a9b-b078-2889fafbe5f0/download)

**Comment by mogul** [comment]
We're going to call the timebox done on this one... We're following up with #1465 since it may be easier to generate a static export directly rather than stop using Wordpress as the CMS/source-of-truth; this would save us trying to make everything work in Jekyll.
