### ISSUE TITLE
Some organization pages and datasets are showing insecure connection

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1384]
CKAN organization landing page, some individual organizations' page, and datasets of these organizations are showing insecure connection due to 'mixed content'. Further investigation shows it is due to organization using HTTP url for logo images.

## How to reproduce
https://catalog.data.gov/organization
https://catalog.data.gov/organization/census-gov
https://catalog.data.gov/dataset/2016-kml-boundary-file-united-states-1-20000000

## Expected behavior

The chrome browser should show a padlock next to the URL

## Actual behavior

The chrome browser is show a insecure icon next to url

**Comment by FuhuXia** [comment]
There are multiple organizations that use HTTP url for logos. So we need to run a query to find a complete list. Updating the URL to HTTPS, either thru Admin UI or DB query will fix the issue for organization pages, but for datasets page, a search-index rebuild is needed. Need to find way to fix dataset page without manually rebuilding  index.

**Comment by mogul** [comment]
Should be finished with this in a day or two.

**Comment by FuhuXia** [comment]
50k datasets are being synced, ETA 40 hours.

**Comment by FuhuXia** [comment]
This is done. To keep the insecure content out of the site, we need to train user, or find a way to enforce a rule, that only images from a https site with a valid certificate can be used for organization logo.

**Comment by adborden** [comment]
At least for right now, there are virtually no Catalog admins besides the Data.gov team, so I wouldn't put any effort into solving this in the near future.

However, it sounds like a feature request for CKAN. I would want to only allow image uploads for organization photos and not allow an arbitrary URL. That way CKAN can choose where to store it and ensure that it's served from an HTTPS location, like a CDN.
