### ISSUE TITLE
Inventory Datapusher gives 500 Error

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1385]
Production Inventory Datastore gives 500 error. User sees this error on UI when uploading a resource to datastore. A curl command to the local datapusher url will generate same error. Error logs generate message

```
from werkzeug.contrib.securecookie import SecureCookie
ImportError: No module named contrib.securecookie
```

## How to reproduce

1. ssh into inventory instance, run
`curl localhost:8800`
2. run command `tail /var/log/inventory/datapusher.error.log` to see the error message.

## Expected behavior

curl command should see 200 response

## Actual behavior
curl command sees 500 response

**Comment by FuhuXia** [comment]
Not sure when but the werkzeug module in datapusher app was upgraded version `1.0.0`. In the new version, `contrib` has been deprecated. On prod I manually switched it back to old version `0.16.0` to fix the issue temporarily.

**Comment by adborden** [comment]
Looks like we're not shipping pinned dependencies for datapusher, instead we're installing from loosely pinned packages in [requirements.txt](https://github.com/GSA/datapusher/blob/master/requirements.txt) and getting the latest ones. We should add a requirements-freeze.txt here.

This is going to block the release.

**Comment by adborden** [comment]
As part of this issue, we should add a smoke test for datapusher to the inventory playbook.

**Comment by jbrown-xentity** [comment]
@adborden can you be more descriptive when you say smoke test?

**Comment by jbrown-xentity** [comment]
[requirements-freeze.txt](https://github.com/GSA/datagov-deploy/files/4247189/requirements-freeze.txt)
This was pulled from current production, and should be what is being installed moving forward...

**Comment by adborden** [comment]
> @adborden can you be more descriptive when you say smoke test?

https://github.com/GSA/datagov-deploy/blob/82e629d/ansible/inventory.yml#L67-L85 is an example of host-level smoke test for Inventory. We're just doing an HTTP request to make sure the app is working.  Then an service-level test https://github.com/GSA/datagov-deploy/blob/82e629d/ansible/inventory.yml#L114-L137 at the load-balancer once all hosts are updated. We should add the same kind of test, but for a datapusher. Datapusher doesn't have a public URL, so we might only implement at the host level.
