### ISSUE TITLE
Setuptools warning in staging environment

### ISSUE THREAD

**Issue by ydave-reisys** [GSA/data.gov#1386]

**Comment by ydave-reisys** [comment]
<img width="1440" alt="Screen Shot 2020-02-18 at 3 11 54 PM" src="https://user-images.githubusercontent.com/3017376/74867421-a1fe1c00-5322-11ea-8a06-fe18a0b44332.png">

**Comment by adborden** [comment]
It looks like we are [already pinning](https://github.com/GSA/datagov-deploy/blob/3c3f35a56bff3b293c71d06e5dc5e2709ad0213e/ansible/roles/software/ckan/catalog/ckan-app/tasks/main.yml#L46) to `<45`, so I'm thinking this warning might have shown up during manual testing. Once we're done debugging the schema validation issue and restore the harvester with the playbook, we'll see if we continue to get this error.

**Comment by adborden** [comment]
So my above comment doesn't completely apply. We're pinning setuptools < 45 within the CKAN virtualenv. The stack trace in the error is referring to the OS install (/usr/local/lib/python2.7).

@ydave-reisys do you recall if you manually upgraded setuptools on the OS? I'm seeing setuptools 45 on catalog-harvest1d but not on catalog-harvest2d.

```
ubuntu@catalog-harvester1d:~$ pip list | grep setuptools
setuptools (45.2.0)

ubuntu@catalog-harvester2d:~$ pip list | grep setuptools
setuptools (3.3)
```

It looks like these files were manually installed incorrectly, with the wrong umask:
```
ubuntu@catalog-harvester1d:~$ ls -l /usr/local/lib/python2.7/dist-packages/
total 256
drwxr-x---  2 root root      4096 Feb 18 20:01 attr
drwxr-x---  2 root root      4096 Feb 18 20:01 attrs-19.3.0.dist-info
-rw-r-----  1 root root       126 Feb 18 20:01 easy_install.py
-rw-r-----  1 root root       321 Feb 18 20:01 easy_install.pyc
drwxr-x---  2 root root      4096 Feb 18 20:01 functools32
drwxr-x---  2 root root      4096 Feb 18 20:01 functools32-3.2.3.post2-py2.7.egg-info
drwxr-x---  4 root root      4096 Feb 18 20:01 importlib_metadata
drwxr-x---  2 root root      4096 Feb 18 20:01 importlib_metadata-1.5.0.dist-info
drwxr-x---  5 root root      4096 Feb 18 20:01 jsonschema
drwxr-x---  2 root root      4096 Feb 18 20:01 jsonschema-3.2.0.dist-info
drwxr-xr-x 12 root www-data  4096 Oct 18  2018 newrelic
drwxr-xr-x  2 root www-data  4096 Oct 18  2018 newrelic-4.4.1.104.egg-info
drwxr-x---  2 root root      4096 Feb 18 20:01 pathlib2
drwxr-x---  2 root root      4096 Feb 18 20:01 pathlib2-2.3.5.dist-info
drwxr-x---  4 root root      4096 Feb 18 20:01 pkg_resources
-rwxr-x---  1 root root     99188 Feb 18 20:01 pvectorc.so
drwxr-x---  2 root root      4096 Feb 18 20:01 pyrsistent
drwxr-x---  2 root root      4096 Feb 18 20:01 pyrsistent-0.15.7.egg-info
-rw-r-----  1 root root        23 Feb 18 20:00 _pyrsistent_version.py
-rw-r-----  1 root root       181 Feb 18 20:01 _pyrsistent_version.pyc
drwxr-x---  5 root root      4096 Feb 18 20:01 setuptools
drwxr-x---  2 root root      4096 Feb 18 20:01 setuptools-45.2.0-py2.7.egg-info
drwxr-x---  2 root root      4096 Feb 18 20:01 six-1.14.0.dist-info
-rw-r-----  1 root root     34074 Feb 18 20:01 six.py
-rw-r-----  1 root root     32309 Feb 18 20:01 six.pyc
```

For now, I've manually downgraded to setuptools 3.3, but we probably need to remove these files.

**Comment by adborden** [comment]
After manually downgrading to setuptools==3.3, still seeing emails come in with the warning. I removed all the files (`rm -rf /usr/local/lib/python2.7/dist-packages/*`) and restarted supervisor.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3401#issuecomment-1001082123
