### ISSUE TITLE
[research: 1d] Identify Inventory CKAN commits that are still necessary once on 2.8+ 

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1394]
## User Story

As a data.gov developer, I want a list of functionality that must be ported from inventory-app's CKAN 2.5 fork so that we can understand and break down the remaining work to get our CKAN deployment using CKAN 2.8.

## Acceptance Criteria
- [x] We have a list of issues covering the work needed to get off of the inventory-app fork of CKAN 2.5
- [x] For each change to be ported, we explicitly identify whether the stock data schema is implicated

**Comment by adborden** [comment]
We're tracking our forks in https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=0

CivicActions/datopian are also working on _other forks_.

**Comment by adborden** [comment]
Oops, my comment above was misleading. I edited it to reflect @jbrown-xentity and the Data.gov team are going to look at this issue, the Inventory ckan fork. Just a heads up that ckan multi folks are analyzing the other forks.

**Comment by jbrown-xentity** [comment]
[Current Documentation](https://github.com/GSA/datagov-deploy/wiki/Inventory-Upgrade-Documentation)
