### ISSUE TITLE
Jumpbox should have a trendmicro policy set in BSP environments

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1397]
Confirmed with SecOps that Jumpboxes should have a Trendmicro policy set, just like all other hosts in BSP environments (production, staging, mgmt).

This was identified when digging into https://github.com/GSA/datagov-deploy/issues/1389. I've added an assertion that will [enforce the condition](https://github.com/GSA/datagov-deploy-common/pull/42) that all hosts have a policy set.

## How to reproduce

1. `$ pipenv run ansible-inventory --host=jumpbox -i ansible/inventories/production | grep -w trendmicro_policy_id`

## Expected behavior

Should see output showing a trendmicro_policy_id is set.

## Actual behavior

No output. No trendmicro_policy_id is set for jumpbox.

**Comment by adborden** [comment]
[hotfix/trendmicro-jumpbox](https://github.com/GSA/datagov-deploy/tree/hotfix/trendmicro-jumpbox) has a fix to test.

We want to be cautious when rolling this out. I'm not sure the policy is configured properly, and if there's a misconfiguration, we could be locked out of the jumpbox and would need to work with SecOps to resolve the misconfiguration.

Therefore, I'll roll this out to mgmt -> staging -> production and test along the way to avoid locking us out of important environments.

**Comment by adborden** [comment]
The next steps are to take the [hotfix/trendmicro-jumpbox branch](https://github.com/GSA/datagov-deploy/tree/hotfix/trendmicro-jumpbox) and deploy it to each jumpbox, one at a time to make sure we can still login. For each environment, it looks like:

1. checkout the branch
1. ansible-playbook common.yml
1. Test that you can still login from another shell
1. Reboot the jumpbox
1. Test that you can still login from another shell

And repeat this for each environment:
- mgmt (datagovjump1m.mgmt-ocsit.bsp.gsa.gov)
- staging
- production

Then merge the branch.

As part of getting this out onto mgmt, we need to update [mgmt hosts](https://github.com/GSA/datagov-deploy/blob/develop/ansible/inventories/mgmt/hosts#L4) and the [README](https://github.com/GSA/datagov-deploy/pull/1454) which are missing information (or incorrect).

**Comment by mogul** [comment]
@ydave-reisys is verifying that the reboot happened in mgmt with `uptime` then move on to applying this change in the other environments. Branch to be tested on staging, then merged into master if successful.
