### ISSUE TITLE
Upgrade molecule to 3.x

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1399]
## User Story

As a data.gov developer, I want to upgrade molecule to the next major version (v3), so that I get the [latest features](https://molecule.readthedocs.io/en/latest/changelog.html#id2) and support.

## Acceptance Criteria
- [ ] Lock file is updated with the latest molecule version
- [ ] molecule [upgrade checklist](https://github.com/ansible-community/molecule/issues/2560) is performed

**Comment by adborden** [comment]
Not seeing any major improvements in 3.0 at least. Icebox for now.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
