### ISSUE TITLE
ckanext-saml2 can keep up with upstream

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/data.gov#1401]
This issue in particular refers to https://github.com/GSA/ckanext-saml2. See [the epic this issue belongs to](https://github.com/GSA/datagov-deploy/issues/1343) for further context.

## Acceptance Criteria
- [ ] When there's a new release upstream, we can get onto it in under an hour 
- [ ] When there's a new release upstream, we see a notification in a Slack channel
- [ ] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
- [ ] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them.
- [ ] A ["discussion" issue](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks#track-the-fork) is created for this fork that documents our [analysis](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=0) of outstanding commits and why the fork exists.

## Details
TBD

**Comment by avdata99** [comment]
Created the discussion issue: https://github.com/GSA/datagov-deploy/issues/1403 (I have no permission to add @mogul and @adborden there) 
Created a tests issue: https://github.com/DataShades/ckanext-saml2/issues/115

(I have no permissions to check the las two items in the issue's task list)

**Comment by mogul** [comment]
Closing as this largely duplicates #1403
