### ISSUE TITLE
Inventory 2.8 extensions

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1404]
## Feature/what we're after
[test: 1d] Test integration of required CKAN extensions for inventory

## Anticipated/hypothesized benefits
- Will provide necessary functionality on Inventory
- More stability for end users/better reliability

## Measurements/metrics
- Local tests work for all necessary extensions, and those that are not working are in a documented state with their own bugs

**Comment by pjsharpe07** [comment]
Current status of these extensions can be found [on this wiki](https://github.com/GSA/datagov-deploy/wiki/Inventory-Upgrade-Documentation)
