### ISSUE TITLE
Replace Use of PyZ3950

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/data.gov#1411]
## Feature

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we manage forks we need to update the use of [PyZ3950](https://github.com/asl2/PyZ3950).

We need to replace the use of outdated PyZ3950 wherever it occurs with the [pipy version](https://pypi.org/project/PyZ3950/)

## Anticipated/hypothesized benefits
- We are going to solve compatibility issues. We are using old repos
- We are going to use a community supported version

## Tasks

- [ ] [#127](https://github.com/GSA/ckanext-geodatagov/issues/127) Replace github install with pip install from https://pypi.org/project/PyZ3950/

**Comment by jbrown-xentity** [comment]
No longer plan on utilizing, closing.
