### ISSUE TITLE
harvest source package with large 'status' field generates solr error

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1412]
Some harvest source packages can't be indexed by Solr. Any editing on these affected harvest source will produce 500 error with detailed solr message on UI. Re-indexing the package on command line will have same error message.

`Unable to update search index.('Solr returned an error: 400 Bad Request .....Document contains at least one immense term in field="status" (whose UTF8 encoding is longer than the max length 32766.....bytes can be at most 32766 in length; got 51171. Perhaps the document has an indexed string field (solr.StrField).....`

Further investigation shows affected harvest sources contains a very large status field. When the bytes count reaches 32766+, we will see this error.

Here is a normal harvest source with normal char count in `status` field: 
https://catalog.data.gov/api/action/package_show?id=city-of-ferndale-michigan-data-json

Here is a harvest source with a `status` field getting large but still ok: 
https://catalog.data.gov/api/action/package_show?id=homeland-infrastructure-foundation-level-data-hifld

And this harvest source with `status` field containing 50K+ chars. It can't be indexed any more:
https://catalog.data.gov/api/action/package_show?id=city-of-sioux-falls-data-json

## How to reproduce

1. Description of steps to reproduce the issue.
Log in as admin and go to URL
https://admin-catalog.data.gov/harvest/edit/city-of-sioux-falls-data-json
Make some change such as adding a space at the end of title and hit 'Save' button.

## Expected behavior

change is saved with no error

## Actual behavior

500 error with above solr error message

**Comment by FuhuXia** [comment]
Opps, duplicate of https://github.com/GSA/datagov-deploy/issues/874

**Comment by FuhuXia** [comment]
`status` field is kept as `String` type in solr. When we put too many `object_error_summary` into this field, it goes beyond what String field can hold. We need to re-think if it make sense to put all detailed error in the `status` field, or allow large field by changing field type to `Text`.

**Comment by mogul** [comment]
Fixed in the duplicate issue.
