### ISSUE TITLE
NOAA Harvest to WAF

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1419]
## User Story

As a NOAA data manager, I want my data harvested from a WAF so that my data can be updated without any upgrades.

## Acceptance Criteria
- [x] NOAA data is removed from data.gov (Started 10 am ET 10/10/2020, completed by 2:45 pm ET)
- [x] NOAA data is harvested via WAF onto data.gov (All harvest sources created by 4:00 pm ET, [tracking started](https://docs.google.com/spreadsheets/d/1Afgx0nGPcsNu0-nIvhcQ3RRAJkcesaCPdcDqT4fIaBI/edit#gid=0))

## Details
Will require coordination with Chris MacDermaid - chris.macdermaid@noaa.gov.
**Make sure WAF harvest is tested in staging/sandbox before data is removed!**

**Comment by mogul** [comment]
Blocked until we have a complete list of their WAFs

**Comment by jbrown-xentity** [comment]
Requested update, do not currently have complete list of WAF's.

**Comment by jbrown-xentity** [comment]
[Data.gov-Harvest-WAFs.xlsx](https://github.com/GSA/datagov-deploy/files/4308515/Data.gov-Harvest-WAFs.xlsx)
List of WAF's that need to be harvested. Will spot-check various harvests manually, then do a full automated addition on sandbox.

**Comment by mogul** [comment]
@jbrown-xentity can you give an update on the state of this one?

**Comment by mogul** [comment]
James is saying there's very little left to do here, and that he can fit it in the margin of the O+M rotation he's taking this sprint.

**Comment by mogul** [comment]
Running in staging now to validate that it'll work. Next step is to coordinate with NOAA on when to run it in production. The NOAA contact is rolling off and doing a handover.

**Comment by mogul** [comment]
We're seeing SQL errors in staging. Trying to reproduce in sandbox, but #1700 is causing the database to fill up, which is blocking progress.

**Comment by jbrown-xentity** [comment]
Harvest run produced [these results](https://docs.google.com/spreadsheets/d/1Afgx0nGPcsNu0-nIvhcQ3RRAJkcesaCPdcDqT4fIaBI/edit#gid=0). Cannot do all harvest sources, as DB is almost full with 3 harvest sources not yet run. Suggest either 

1. Upgrade sandbox DB
2. Clear some harvest sources and harvest new

@adborden  thoughts?

**Comment by jbrown-xentity** [comment]
PyCSW cleared out, harvest sources being run and reported on spreadsheet.

**Comment by mogul** [comment]
Looks like we're waiting another 48 hours or so to fully harvest.

**Comment by jbrown-xentity** [comment]
Harvest sources still running after weekend. Attempted restart and speed-up of process, latest details on [results spreadsheet](https://docs.google.com/spreadsheets/d/1Afgx0nGPcsNu0-nIvhcQ3RRAJkcesaCPdcDqT4fIaBI/edit#gid=0).

**Comment by jbrown-xentity** [comment]
From the harvest reports, it seems we have 3 major issues to resolve:

1. What are the SQL "Unexpected Errors", why do they consistently occur, and what needs to be done to resolve them?
2. Can we relax the rules around the "tags" being required to allow valid metadata to come into data.gov, or do we need tags to be implemented in a specific way?
3. Can NOAA update the metadata that has spaces in the date formats?

@adborden @hkdctol should this be turned into an epic with separate tickets, or should they all be tracked here? I'll reach out to NOAA contacts to start the conversation on these things...

**Comment by hkdctol** [comment]
@jbrown-xentity 
Seems like it would be clearer to create an epic then put the issues in it.

**Comment by jbrown-xentity** [comment]
Current issues part of the epic:
- [Harvester "Validation Error: msising tags"](https://github.com/GSA/datagov-deploy/issues/1828)
- [Harvester "Unexpected Errors"](https://github.com/GSA/datagov-deploy/issues/1827)
- NOAA Time issue for removing spaces in time field (pending discussion and resolution)

**Comment by jbrown-xentity** [comment]
All major issues seem to be resolved. Current tests show a 7% error rate, with 4 harvest sources pending resolution (I expect that 7% error rate to drop below 2% once the last 4 harvest sources have been run).
Will continue to validate the final 4 harvest sources over the coming week.

**Comment by jbrown-xentity** [comment]
NOAA is going to data admins to verify data on sandbox and make comments. Plan is to aggregate feedback and if no blockers, set a date to cut over (clear and re-harvest) when we meet Oct 6.

**Comment by jbrown-xentity** [comment]
Latest spreadsheet counts are down to 1.5% error rate, with that expected to be < 1% after latest harvests are complete.

**Comment by jbrown-xentity** [comment]
Confirmation from data provider at NOAA that one set of errors are expected (dataset is published in multiple WAF's, and CKAN won't harvest the duplicate GUID). This leaves us with a [true error rate of 0.2%](https://docs.google.com/spreadsheets/d/1Afgx0nGPcsNu0-nIvhcQ3RRAJkcesaCPdcDqT4fIaBI/edit#gid=0). Will propose to move forward with CSW harvest source clear and WAF harvest source creation and automation next week, and work out a timeline that works for data.gov and NOAA...

**Comment by jbrown-xentity** [comment]
Harvest clear of CSW and switchover to WAF to commence early 10/12. NOAA description updated to reflect this, NOAA has updated personnel on their side.

**Comment by chris-macdermaid** [comment]
After purging NOAA records from the CSW harvest, 95,819 NOAA records added to Data.gov from 70 WAFs. Out the 96,651 records in the WAFs, 894 (>1%) failed to be added because of errors.
