### ISSUE TITLE
Dashboard office data should update from canonical source

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1425]
## User Story

In order to ensure the data.gov dashboard is pulling data from the right locations for the right agencies, we want the entries in the office table to be updated from a canonical API source of agency information, using the same IDs.

## Acceptance Criteria
- [ ] Existing `office` rows carry both their existing IDs and IDs that match their entry in the upstream API.
- [ ] `office` fields that refer to the same data upstream is regularly refreshed
- [ ] Dashboard URLs that don't rely on the old IDs are in use (and ideally don't expose the new ID)
- [ ] Dashboard URLs that rely on the old IDs forward to the new URL

## Details

[Phil wrote](https://github.com/GSA/datagov-deploy/issues/1224#issuecomment-572684711):

> new Federal Agency Directory API - https://github.com/usagov/USAGov-Platform-API-Documentation/wiki
> 
> e.g. https://usagov.platform.gsa.gov/usaapi/api/v1/usagov/directory_records.json
> 
> And for general reference, my master doc on the broader effort to establish more of a consolidated canonical registry of agency IDs can be found at https://docs.google.com/document/d/1vsusqxsgHqFhzaHSOXrTJ7sF3IN7LGZVFNNM3m66i4w/edit#
>

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
