### ISSUE TITLE
Discuss state of metrics page

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1437]
In order to decide what work is on our horizon for metrics that other agencies use, we need to talk about the state of https://www.data.gov/metrics and what we can/should do with it, and if there are any driving deadlines for changes.

## Acceptance Criteria
- [ ] We know what we need to do with this content and we have a breakdown of the work to be done documented

**Comment by adborden** [comment]
@FuhuXia do you know how these metrics are generated?

**Comment by mogul** [comment]
We've got a meeting scheduled to discuss this next week.

**Comment by FuhuXia** [comment]
@adborden A custom plugin [Metric Count](https://github.com/GSA/metric-count) is installed on www.data.gov WordPress site. It routinely checks catalog APIs to fetch dataset stats for agencies. We need to check the WP backend to see why the metrics page stops being updated.

**Comment by adborden** [comment]
Linking to the wordpress migration issue, since we'll loose any plugin functionality when moving to a static site https://github.com/GSA/datagov-deploy/issues/992

**Comment by hkdctol** [comment]
Next steps are:

@FuhuXia will look into prior process and whether we can retrieve current and past data on page views https://catalog.data.gov/dataset/data-gov-visitor-metrics

Investigate a replacement report through: https://github.com/ckan/ckanext-googleanalytics#setting-up-statistics-retrieval-from-google-analytics

Create separate ticket #1472 to remove current data.gov/metrics
