### ISSUE TITLE
CircleCi not building datagov-deploy

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1439]
All new builds of CircleCi are failing for datagov-deploy with the following error:

`ERROR: Missing Docker driver dependency. Please install via 'molecule[docker]' or refer to your INSTALL.rst driver documentation file`

There is very little information on this error on the internet, the above error only occurs when doing a sanity check for molecule installation.

## Mitigations tried

1. Testing locally (all successful)
2. SSH onto CircleCi box and manually test
  2.1 make setup (all as expected)
  2.2 setup command in various places (including in role folder) (no change)
  2.3 new Pipfile.lock from locking dependencies on local machine (more broken than before)
  2.4 Manual run of a specific molecule test (catalog/harvest) (same error)

## How to reproduce

1. [Log into CircleCi](https://circleci.com/gh/GSA/datagov-deploy) and re-run any workflow (including old working versions)
2. Review output

## Expected behavior

Successful build, as per multiple local testing confirms

## Actual behavior

Failing build

**Comment by adborden** [comment]
This looks like an issue with the dependency cache. We're clearing the CI cache as per [CircleCI's docs](https://circleci.com/docs/2.0/caching/#clearing-cache). The fix looks like https://github.com/GSA/datagov-deploy/commit/d95758b73291efd1d5c4f7d6649630a1a0ca0ddb
