### ISSUE TITLE
Proactive monitoring/restart of applications under pressure (monit)

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1449]
## User Story

In order to minimize the impact runaway processes on service availability, we want to automatically restart apache2 when threshold Y is observed.

## Acceptance Criteria

- [x] WHEN the monitored process on an application host is observed eating memory at a rate that will result in exhaustion in less than five minutes \
  THEN the monitored process is automatically restarted \
  AND the data.gov team is notified that the event happened \
  AND the notification includes a timestamp and a link to the relevant graph in New Relic

## Background

We sometimes see our catalog instances suddenly all climbing in memory (apache2/ckan) until eventually the host becomes unresponsive. This has been an ongoing issue for at least a year. 

As a workaround we've been restarting/reloading apache2 as described in the [runbook](https://github.com/GSA/datagov-deploy/wiki/catalog.data.gov#rapid-consumption-of-memory), but at this point it's reactive to an outage on our part, rather than proactively trying to avoid an outage, and SSH'ing in to do this is both a manual effort and potentially happens long after the problem appears.

## Sketch

- Try to make use of Monit to monitor and restart the relevant processes deployed on each host.

**Comment by adborden** [comment]
@jbrown-xentity asked if we should commit the retry_ssh.sh script to version control. I'm putting it here as a gist, but not sure if it's worth adding to datagov-deploy.

https://gist.github.com/adborden/45b999e37f872aaeeab98724099ca6cf

**Comment by adborden** [comment]
@FuhuXia is going to analyze the apache logs to determine if this is bot-related traffic. We'll start with a 4-hour timebox.

**Comment by mogul** [comment]
Fuhu is running through hypotheses to try to narrow this down. Next step is to try to analyze the situation while it's actually happening.

**Comment by mogul** [comment]
Blocked waiting for deployment of a fix to enable static asset caching, so that the logs are intelligible.

**Comment by adborden** [comment]
Now that we've shipped a few fixes, moving out of blocked to Sprint backlog.

**Comment by adborden** [comment]
Some tools available to us:
- [Upstart](http://upstart.ubuntu.com/wiki/Stanzas#limit) on Trusty allows us to set ulimits
- [Gunicorn](https://docs.gunicorn.org/en/latest/settings.html?highlight=memory#max-requests) allows a `max-requests` at which point it recycles the process. Catalog is not on gunicorn yet, and this isn't a fool-proof solution because it doesn't trigger based on memory
- Apache2 provides configuration for [MaxConnectionsPerChild](https://httpd.apache.org/docs/2.4/mod/mpm_common.html#maxconnectionsperchild) which helps to recycle processes. Doesn't trigger based on memory.
- Write a custom script with cron

**Comment by mogul** [comment]
Marking `Blocked` since there's nothing actionable here until we see our next few catalog events to help us calibrate our threshold for restarts.

**Comment by adborden** [comment]
I've been using [Monit](https://mmonit.com/) for another project and realizing it can do a lot more than I realized. Monit is a service that monitors the system for conditions (e.g. memory is greater than X threshold for Y cycles) and then takes actions (restart a service, send a notification, etc). It can do can even do [memory resource tests for processes](https://mmonit.com/monit/documentation/monit.html#Process-resource-tests) and its `TOTAL MEMORY` condition looks at a process _and its children_. Since the ckan processes are children of apache2, this feels like exactly what we're after here.

Another feature I'm excited about is the [file content test](https://mmonit.com/monit/documentation/monit.html#FILE-CONTENT-TEST) which essentially tails a log and check for a regex. In 12-factor terms, this would be a great tool to monitor our event streams (application logs) and perform actions based on them (alerting when dashboard crawl fails). Even if we use a custom script to log out memory conditions for apache2/ckan, Monit could handle the notification and restarting of services for us. That way our custom script would just focus on logging out events that humans need to take action on.

**Comment by FuhuXia** [comment]
Some kind of requests are responsible to cause high memory usage. From the log we can see certain apache process is taking 60% of mem handing one request of this kind for long period. It is difficult to capture the request from analyzing  access log, but if we can enable [extendedstatus](http://httpd.apache.org/docs/trunk/mod/core.html#extendedstatus) in apache for debugging purpose, it should help.

![Screenshot 2020-07-10 14 13 29](https://user-images.githubusercontent.com/1392461/87185440-c51c6e80-c2b7-11ea-857d-35afc96500eb.png)

**Comment by mogul** [comment]
Bumped to the top of the backlog based on the retro discussion today.

**Comment by FuhuXia** [comment]
In the Monit rule we set to monitor catalog-web-apache2, we use TOTALMEMORY. I think this is the memory used by apache process. It is always lower than whole System Memory usage as be reported by NewRelic.  So we want Monit to take action when System Memory reach `90%`, the TOTALMEMORY used by catalog-web-apache2 need to be lower, somewhere between  `80-85%`.
https://github.com/GSA/datagov-deploy/blob/be5b22966024588a08266d2007e004dcdcada4be/ansible/catalog-web.yml#L53
