### ISSUE TITLE
Resolve potential WordPress vector

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1455]
[Details in Google Drive](https://docs.google.com/document/d/1Dy0JK1kJR31z_0-VfzKmnojelZ9NwB_hZ97prn6j2eQ/edit#heading=h.ncmxcxtf14ej)

**Comment by jbrown-xentity** [comment]
PR in place, need to validate on staging for confirmation.

**Comment by FuhuXia** [comment]
Requesting SecOps to provide some clarification on this report. If no response, will mark it false positive.

**Comment by mogul** [comment]
Fuhu's going to ping them one more time with Lynnette on cc.

**Comment by FuhuXia** [comment]
Got response from SecOps. This is false positive.
> Looks like this was triggered due to a HTTP compression header, but I did not find any CSRF token reflected in the response. I will mark it as a false positive.
