### ISSUE TITLE
WordPress active mixed content (vulnerability class)

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1457]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1Dy0JK1kJR31z_0-VfzKmnojelZ9NwB_hZ97prn6j2eQ/edit#heading=h.t97juekqgk7f)._

**GH issue for vulnerability class\*:** N/A
**Date of report:** 2020-02-25
**Due date:** 2020-05-25

_\* When a finding is identified, we ususally create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurences of this vulnerability within the application._

**Comment by FuhuXia** [comment]
Tested WordPress plugin **SSL Insecure Content Fixer** on local. With setting set to **Content**, `http` links in the content were changed to `https`. This seems to be the plugin we need to fix the issue.

**Comment by FuhuXia** [comment]
verified on staging.

**Comment by FuhuXia** [comment]
Verified that Wordpress plugin `ssl-insecure-content-fixer` is installed and activated on Prod. This issue can be closed.
