### ISSUE TITLE
Complete annual update of Contingency Plan

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1460]
## User Story

Data.gov PMO needs to complete annual review and update of Contingency Plan

## Acceptance Criteria
- [x] Close out of open items in CP

## Details
There are a few comments left in https://docs.google.com/document/d/1DMtzlU56X1owthQCI6fEuHiTrdDbq-hkeZ4xQC8VLO4/edit?usp=sharing marked for action for @adborden

**Comment by adborden** [comment]
@hkdctol I responded to comments, please take another look.

**Comment by hkdctol** [comment]
Looks good I will forward to ISSO.
