### ISSUE TITLE
Dashboard does not report specific error when JSON is invalid

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1464]
https://labs.data.gov/dashboard/offices/detail/52583/#valid_json

The Dashboard is reporting that USAID's data.json is invalid and links to jsonlint.com for the viewer to validate the JSON file themselves. The dashboard should be able to report the specific error (with line/character) where the JSON parser failed.

This can be confusing because Dashboard continues on with the old data.json (I believe) and is validating stale dataset URLs which you can imagine are going to result in a lot of broken links.

In this case, the data.json is invalid because it contains a duplicate `mediaType` key.

## How to reproduce

1. https://labs.data.gov/dashboard/offices/detail/52583/#valid_json

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
