### ISSUE TITLE
[research: 3 days] Generate a static site from our Wordpress deployment

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1465]
## User Story

In order to identify the most straightforward way to proceed with making www.data.gov a static site, we want to spend up to 3 days exploring native-Wordpress options for exporting a static site.

## Acceptance Criteria
- [ ] We have a sketch of the tech/process needed to produce a straightforward static export of the site, ideally including a demo
- [ ] We have a list of the missing pieces or work to be done to make it real

## Sketch/potential tasks
1. Investigate straight one-time static conversions using whatever modern methods exist:
   - [ ] Get it working with an "empty" database
   - [ ] Get it working with the "full" database
2. Figure out hosting (GitHub + Federalist)
3. Investigate easier content editing options (eg [NetlifyCMS](https://www.netlifycms.org/docs/intro/) for GitHub content editing).

We may also investigate a hybrid approach that enables us to continue using Wordpress authoring workflow during development. For example:
1. [sync/store the whole Wordpress site+DB in GitHub](https://versionpress.com/)
2. [Spin up a Wordpress docker-compose based on the GitHub repo on demand](https://docs.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project#docker-dockerfile-or-image-settings) 
3. In a GitHub action, "rehydrate" the full site and do an export to a static destination
(This presumes that the static export could be done without hand-munging the result every time.)

## Background/additional details

In essence, we are investigating whether there is a fast path to generating a static site from our existing Wordpress deployment. If so, then this may be a faster path to our goal (only deploying a static site in production) without going so far as to stop using Wordpress and its DB as the CMS for the site.

**Comment by mogul** [comment]
@SaiUdthawar-REI, to be explicit, when you encounter plugins that are not translating well into the static output, just note those as part of the research, don't try to make them work as you see them.

**Comment by FuhuXia** [comment]
Researched [jekyll-exporter plugin](https://wordpress.org/plugins/jekyll-exporter/) on local site with production DB. The plugin worked out fine, it dis the job it was supposed to do. We can install this plugin on production and generate an up-to-date zip file in Jekyll structure containing all Wordpress contents. The content is converted by the plugin into Markdown format whenever possible, making it easy to manage using NetlifyCMS. So the final product looks like this: Jekyll code on GitHub, site hosted on Federalist, and content is managed via NetlifyCMS, editor user is authenticated via GitHub account. 
I haven't encountered any difficulty in the exporting process that need to use other tools. However, [other tools](https://import.jekyllrb.com/docs/wordpressdotcom/) are also available in case we need to export one particular or small amount of content.

In theory, we can make the new Jekyll site structured and looked identical the existing Wordpress site, making the switch process transparent to end users; same url, same content, and same style. The new site will be static site, so the dynamic part such as Contact Us form or Comments will not be possible. We can further research to see whether Federalist provide some tools to offer same functionality, but for now I considered those disabled in the new site.

## Challenges:
1. No more Comment, Contact Us page or any dynamic contents.
There are 809 Approved comments, last added on 2020/01/02 at 10:01 am by Crystal Carter in response to a user comment.

1. Styling the Jekyll site.
This will be a manual process. The whole site will share some common header/footer element. Other than root level pages, all contents can be grouped into different categories and each category will have some different UI elements that need custom layout. There are 20-30 categories, depending on what tool is used to do the counting, so there are 20-30 layouts needed to be coded in Jekyll.

2. Matching the content
Are all contents need to be exported, and how to verify we got all of them.
Wordpress reports 431 Posts are published. [Tools->Export All URLs](https://wordpress.sandbox.datagov.us/wp/wp-admin/tools.php?page=extract-all-urls-settings) reports 723 links available.  [Sitemap](https://wordpress.sandbox.datagov.us/detailed-sitemap) lists 800+ entries. There are 681 pages and posts exported by jekyll-exporter. So the question is: which is the go-to source to validate all Wordpress contents are in new Jekyll. I assume there will obsolete and orphaned content in Wordpress that is still in published state. Do we still export them? If we want to isolate those contents, we might have to use a web crawler to crawl the Wordpress site and use the that list as the source list.

## Sketch:
1. Launch a local Jekyll site, start with a simple root level page, get UI elements exported and base layout coded into Jekyll.
1. Sometime earlier in the process, move Jekyll site into federalist and connected it to NetlifyCMS.
1. Do a draft jekyll-export
1. Prioritize the missing layouts, decide which are bases for others
1. Pick some simple pages for each category and code its layout (static capture, no refactoring)
1. Have a final jekyll-export
1. Go through all jekyll-exported contents and verify its UI in its category layout.
1. Use the list from web crawler to verify all contents are live in Jekyll.
1. Refactor layouts to use templates at leisure

## Other thought:
Most of effort will be spent on dealing with layout in Jekyll. I don't see any way to avoid it. Once the layouts are ready, and we are manage content via NetlifyCMS, I don't see the point to keep Wordpress in a container and keep its DB for content management.

**Comment by jbrown-xentity** [comment]
Epic created to track work out of research: https://github.com/GSA/datagov-deploy/issues/2875
