### ISSUE TITLE
Catalog fails to grab dynamic menu from WordPress due to connection interruption

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1467]
> This site can’t be reachedThe webpage at https://www.data.gov/app/plugins/datagov-custom/wp_download_links.php might be temporarily down or it may have moved permanently to a new web address.
> ERR_HTTP2_PROTOCOL_ERROR

![Screenshot from 2020-03-17 16-08-10](https://user-images.githubusercontent.com/509703/76909849-9e01e300-6869-11ea-9087-22f237b0aee3.png)

## How to reproduce

1. https://www.data.gov/app/plugins/datagov-custom/wp_download_links.php

## Expected behavior

JSON file is accessible.

## Actual behavior

Connection is interrupted, Chrome reports an HTTP2 Protocol error.

**Comment by adborden** [comment]
You can get the json from https://wp-bsp.data.gov/app/plugins/datagov-custom/wp_download_links.php, although the URLs need to be edited.

I changed the CKAN configuration to use this URL, but I was still seeing the error that menu.json doesn't exist, so it seems there is something else going on here.

**Comment by adborden** [comment]
This looks like the WAF or firewall is interrupting the connection. Since wp-bsp works, it looks like the AWS WAF in gsaoppprod is causing the interruption. That would also explain why this started up all of a sudden without a code change to trigger it.

**Comment by adborden** [comment]
Because of this error, CKAN fails to serve requests https://github.com/GSA/catalog-app/issues/76

**Comment by nickumia-reisys** [comment]
Wordpress no longer exists.  Data.gov is on cloud.gov now,
- https://github.com/GSA/data.gov/issues/3555
- https://github.com/GSA/data.gov/issues/3554
- https://github.com/GSA/data.gov/issues/2788
- https://github.com/GSA/data.gov/issues/3541
- https://github.com/GSA/data.gov/issues/3891
