### ISSUE TITLE
Remove outdated data.gov/metrics page

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1472]
## User Story

Data.gov PMO wants to remove outdated content from www.data.gov, and the /metrics page is not updated, and will be replaced

## Acceptance Criteria
- [x] /metrics is removed from data.gov and navigation in footer

## Details
We are investigating alternatives in https://app.zenhub.com/workspaces/datagov-devsecops-579a2532d1d6ea9c3fcf5cfa/issues/gsa/datagov-deploy/1437
but for now we can remove outdated content from main page

**Comment by hkdctol** [comment]
GA indicates page views on /metrics are about .2% of total, and I have not received inquiries about it from agencies

**Comment by hkdctol** [comment]
For the time being, to avoid confusion https://www.data.gov/metrics should redirect to https://labs.data.gov/dashboard/offices/qa

**Comment by pjsharpe07** [comment]
@hkdctol the redirect has implemented through the wordpress ui. Would you check to see that the redirect is functioning as expected?

**Comment by mogul** [comment]
Waiting for the next meeting with GAO before we make this change.

**Comment by mogul** [comment]
(Note we decided to keep the link in the footer and just have it redirect.)
