### ISSUE TITLE
Create a CKAN role based on ckan-app to handle Inventory and Catalog

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1473]
## User Story

As a Data.gov Developer, I want a CKAN Ansible role that can be used for Inventory and Catalog so that I don't need to maintain several separate and inconsistent roles and to identify tasks that should be moved to the applications.

## Acceptance Criteria
- [ ] A new GitHub repository exists for the Ansible role
- [ ] CI is configured for the new role
- [ ] datagov-deploy is updated to use the new role
- [ ] Issues are created for any tasks that should be moved to the responsibility of the applications (e.g. installing a production extension like ckanext-s3filestore)

## Details

Currently we have several roles for Catalog and several roles for Inventory. They are doing similar things, but differently. Even though they are running different versions of CKAN, the installation process is similar enough that we should be able to create a single role that can be configured for both Inventory and Catalog.

The new role should be similar to https://github.com/GSA/datagov-deploy-pycsw, which creates an OS user for ckan, improved deployment directory rotation, a user-specific python and virtualenv install, and less code to maintain.

**Comment by nickumia-reisys** [comment]
Ansible no longer used and in charge of this,
- https://github.com/GSA/data.gov/issues/3710

Deployments to cloud.gov are managed as separate users per space (development, staging, prod) and these users are directly integrated with Github Actions for automated deployments.
