### ISSUE TITLE
ckan-tracking-update runs should complete daily

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1479]
We have a cron job to do tracking update nighly. But this command is taking days to finish, therefore we are not getting updated page view count everyday

## How to reproduce

Run the cronjob under a timer and consult the log of recent runs in tracking-update.log.

## Expected behavior

The cron job should finish in hours.

## Actual behavior

The cron job takes 3-4 days

## Notes

See CKAN notes on the topic [here](http://docs.ckan.org/en/2.9/maintaining/tracking.html), and the docs on running the command [here](http://docs.ckan.org/en/2.9/maintaining/cli.html#tracking-update-tracking-statistics)

**Comment by jbrown-xentity** [comment]
Current plan of action (cc @FuhuXia ):

- Run job manually on staging as a task, and check time to completion
- If reasonable, run job manually on production
- Setup recurring job on dev, staging, and prod such that this task is run nightly (and preferably can be run on request)

**Comment by hkdctol** [comment]
Fuhu working on some documentation

**Comment by FuhuXia** [comment]
Here is what we did to complete the job
- Added a customized `geodatagov tracking-update`.
- Manually run the initial update to calculate all hit stats since day 1 (`2021-02-03` for our new catalog). It took 24 hours.
- Set up a daily job. Daily job can finish in a hour or so (instead of 3-4 days)
- Tested weekly job can finish in 4 hours. We choose Daily not Weekly schedule. 
- Did not set up manual action to run the task on request. On an active web app as catalog, I don't see the point to add such an action.

TODO in the future:
- Eliminate the customization by pushing changes to upsteam, or 
- better Solr `defer_commit` configuration on catalog.

**Comment by hkdctol** [comment]
@FuhuXia can this one be marked closed?
