### ISSUE TITLE
Investigate replacing explicit metrics with Google Analytics metrics

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1480]
Investigate a replacement report through: https://github.com/ckan/ckanext-googleanalytics#setting-up-statistics-retrieval-from-google-analytics

## User Story
As Data.gov PMO, we want to understand what metrics might be easily available through Google Analytics

## Acceptance Criteria
- [ ] Create a list of potential questions that could be answered by GA: https://docs.google.com/document/d/16O-ynjzVku5xR3T65lUDC8DfGDlESQsLgxjBjVnYlDA/edit?usp=sharing
- [ ] Meet with Digital Analytics Program to determine what can be done through GA
- [ ] Work with Digital Analytics Program to establish the relevant settings on the GA account

**Comment by hkdctol** [comment]
Closing this one. We will create an updated ticket on the topic
