### ISSUE TITLE
Deploy CKAN 2.8-based Inventory in AWS sandbox

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1481]
## User Story

In order to validate inventory-2.8 without impacting our ability to deploy fixes to 2.5, we need a production-similar deployment of inventory-2.8 in the AWS Sandbox.

## Acceptance Criteria
- [x] a separate instance of inventory based on CKAN 2.8 is deployed in the AWS sandbox
- [ ] the instance is re-deployable using Ansible playbooks

## Details/tasks

- Add new hosts to the Terraform config and include them in a separate inventory

**Comment by adborden** [comment]
Removing the bullet about adding playbooks since we should be able to use the existing inventory.yml playbook for BSP and sandbox environments.

**Comment by adborden** [comment]
@pjsharpe07 what do you think about splitting the Ansible work into its own story?

**Comment by jbrown-xentity** [comment]
Terraform instances are deployed, but not tested. Next steps:

- Push terraform changes
- Test inventory standard playbook from ci
- Update datagov-deploy on inventory 2.8 branch to be additions and not changes
- Update datagov-deploy variables from terraform

**Comment by jbrown-xentity** [comment]
Current status:

- Have running version with gunicorn (DB not setup)

Next Steps:

- Configure DB (use docker start script and run `paster --plugin=ckan db upgrade -c /etc/ckan/production.ini` manually)
- Setup Ansible with supervisor and gunicorn (similar to pycsw)
  - Add redis configuration
- Run and validate ^^
- Discover/plan for dedicated redis server and discuss with team
- Consider implementing #1473 to simplify future catalog implementation

**Comment by jbrown-xentity** [comment]
gunicorn serve command: `gunicorn --paste /etc/ckan/production.ini -b localhost:8003`

**Comment by jbrown-xentity** [comment]
Need to add the following to ansible:
- Redis configuration (https://github.com/GSA/datagov-deploy/issues/1536)
- gunicorn installation (https://github.com/GSA/datagov-deploy/issues/1383)
- apache configuration (with gunicorn)
- supervisor configuration (with gunicorn)
- integrate ckan local login changes (https://github.com/GSA/datagov-deploy/issues/1517)

**Comment by adborden** [comment]
We have existing issues for most of these additional items. I'm pretty sure that the Terraform and the core Ansible work is done (we should wrap up if it's not) and call this done.

**Comment by pjsharpe07** [comment]
All separate issues can be found on the comments above. Marking this as done.
