### ISSUE TITLE
New data.json harvest source for VA

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1482]
## User Story

As Data.gov PMO, want to facilitate change in data.json for VA

## Details

VA wants to switch harvest location to https://data.va.gov/data.json They have tested on validator on labs.data.gov but would like it to be tested on staging.

## Acceptance Criteria
- [x] Test harvest the new source

- [x] Check results and provide them to VA and work through any errors

- [x] Switch VA harvest source to https://data.va.gov/data.json on production through catalog UI.

**Comment by ydave-reisys** [comment]
@hkdctol https://data.va.gov/data.json is redirected to https://www.ea.oit.va.gov/EAOIT/VA_EA/OpenData.asp which is not json content hence harvester fails.

**Comment by hkdctol** [comment]
@ydave-reisys this location is ready to go for testing VA's new data.json  https://va.data.socrata.com/data.json

**Comment by ydave-reisys** [comment]
@hkdctol This url went through fine in our harvester. Currently this url has no data for datasets so there are no datasets added when harvester completed successfully.

**Comment by ydave-reisys** [comment]
@hkdctol 4230 Datasets added successfully on staging.

**Comment by hkdctol** [comment]
Testing on staging looks good, relayed info to VA, they can let us know when it's ready on production and we will change harvest URL

**Comment by mogul** [comment]
@hkdctol is going to ping VA to see if we can move this to Done now.

**Comment by hkdctol** [comment]
Pinged VA. Awaiting response.

**Comment by hkdctol** [comment]
VA replied 5/1, confirmed they are still finalizing, will let us know when to switch harvest source

**Comment by mogul** [comment]
Hyon will ping to see how VA's doing.

**Comment by hkdctol** [comment]
Pinged VA about harvest source.

**Comment by hkdctol** [comment]
VA still going through final approvals on new harvest source.
