### ISSUE TITLE
Slack Notifications for Upstream Updates

### ISSUE THREAD

**Issue by estebanruseler** [GSA/data.gov#1495]
**Description:**

Stub issue. Paul to add to this... 

What slack channel do they want the notifications on. Do we need permissions? What's involved. I imagine this is quite simple... 

## User Story

As a [user description], I want [behavior description] so that [goal].

## Acceptance Criteria
- [ ] 

## Task-list 
- [ ]

**Comment by adborden** [comment]
The command is `/feed subscribe https://github.com/DataShades/ckanext-saml2/releases.atom` in #datagov-notifications.

It looks like the command is only available to non-guests, so I've just run this.
