### ISSUE TITLE
Update docs for provisioning a new jumpbox instance

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1499]
## User Story

As a Data.gov operator, I want documentation for initial jumpbox provisioning so that I can easily check that the jumpbox is configured correctly as well as configure new jumpbox instances when necessary.

## Acceptance Criteria
- [ ] Documentation exists in datagov-deploy

## Details

Some of this is captured in [datagov-infrastructure-live](https://github.com/GSA/datagov-infrastructure-live/blob/master/docs/datagov-deploy-environments.md#configure-ssh-for-jumpbox) but really should be moved to datagov-deploy where it will be more visible.

Additionally, how to configure the root SSH key is missing.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
