### ISSUE TITLE
Postfix SMTP server

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1501]
Start to getting email notifications from multiple hosts in prod and staging environments reporting this error. Outgoing email function on the hosts might be affected by this issue. 

Here is a sample error message in the email body

```
 Out: 220 catalog-web2d.dev-ocsit.bsp.gsa.gov ESMTP Postfix (Ubuntu)
 In:  EHLO 10.176.16.106
 Out: 250-catalog-web2d.dev-ocsit.bsp.gsa.gov
 Out: 250-PIPELINING
 Out: 250-SIZE 10240000
 Out: 250-VRFY
 Out: 250-ETRN
 Out: 250-STARTTLS
 Out: 250-ENHANCEDSTATUSCODES
 Out: 250-8BITMIME
 Out: 250 DSN
 In:  STARTTLS
 Out: 454 4.7.0 TLS not available due to local problem
 In:  QUIT
 Out: 221 2.0.0 Bye

For other details, see the local mail logfile
```

## How to reproduce

Emails addressed to data.gov help with subject line:
`Postfix SMTP server: errors from unknown[10.176.16.106]` 
or 
`Postfix SMTP server: errors from unknown[10.176.16.122]`

**Comment by mogul** [comment]
We suspect some misconfiguration here based on the IP addresses implicated. Will research more and if so escalate.

**Comment by adborden** [comment]
We took a look at this today. I think this is some remote machine trying to connect to postfix. This shouldn't really ever happen. In fact, we probably should be blocking inbound traffic to port 25.

On further inspection of the logs, one example is the attempt to deliver a message to postmaster@catalog-web2d.dev-ocsit.bsp.gsa.gov. My hunch is that this is a Non-Delivery Report in response to a message sent by catalog-web2d, another indication that postfix isn't configured correctly.

What we really want is postfix to be configured for outbound only, sending through smtp.gsa.gov. Any email not to a real email address (harvesters send to real addresses), should be sent to datagovhelp@.

I think this is probably not a priority right now.

**Comment by FuhuXia** [comment]
captured some logs from instance that has a working mail.log. It complains about missing file `/etc/ssl/certs/datagov_host.key`. Maybe find the file and put it into the right place could be a quick fix.

**Comment by adborden** [comment]
@FuhuXia good point. It's true that fixing permissions (or existence) of `/etc/ssl/certs/datagov_host.key` will fix the error.

I'll open a separate issue to address that postfix should not be allowing inbound connections.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
