### ISSUE TITLE
[Offboard] Yaditi Dave

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1513]
These tasks are performed by an Admin unless noted as an action for the outgoing team member.

- [x] Team member should move all Data.gov related documents to team drives
- [x] Team member should document any work in progress and schedule a hand-off for any remaining tasks
- [x] Remove team member from Data.gov GitHub teams
  - [data-gov-admins](https://github.com/orgs/GSA/teams/data-gov-admin/members)
  - [data-gov-support](https://github.com/orgs/GSA/teams/data-gov-support/members)
  - [data-gov-ckan-multi-partners](https://github.com/orgs/GSA/teams/data-gov-ckan-multi-partners)
- [x] Remove access from [GSA GitHub org](https://github.com/GSA/GitHub-Administration/blob/master/README.md#removing-access-to-the-gsa-organization) (if leaving GSA) - need to determine whether REI will have her on other GSA projects
- [x] Remove team member from [GCP account](https://console.cloud.google.com/iam-admin/iam?project=tts-datagov)
- [x] Remove team member from AWS OPP account
- [x] Remove team member from [AWS sandbox access](https://github.com/GSA/datagov-infrastructure-live/tree/master/iam#new-users)
- [x] Remove team member from [jumpbox operators](https://github.com/GSA/datagov-deploy/blob/develop/ansible/group_vars/all/vault.yml)
- [x] Remove team member from Data.gov email lists
  - [Data.gov support list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagov) - done
  - [Data.gov team list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagovhelp) - [made request to @philipashlock in Slack](https://gsa-tts.slack.com/archives/D0FL924RY/p1585891035000400), since he's the only one with perms
- [x] Remove team member from [Data.gov calendar](https://calendar.google.com/calendar/r/settings/calendar/Z3NhLmdvdl9zcjZ0NG52YjRhOTNjNnNzdHRxYXAzbjZtMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) and events
- [x] Remove team member from Uptrends via [email](https://docs.google.com/spreadsheets/d/1Z9Zpr1mpx-65i_fH2VTbVofPtidpLZs5cnkO0Jz53Vc/edit#gid=0) - requested
- [x] Remove team member from [New Relic](https://newrelic.com)
- [x] Remove team member from [Docker Hub](https://cloud.docker.com/orgs/datagov/teams)
- [x] Remove team member from [Data.gov system accounts](https://github.com/GSA/datagov-account-management) following [Account Mangement Procedures](https://docs.google.com/document/d/1ipn-RX2Py1-jAAI_dbc6OdrK1j4Z8jKaya9C8RPyDa4/edit)
- [x] Remove team member from TTS Bug Bounty access [#bug-bounty-partners](https://gsa-tts.slack.com/messages/C5JQCD9PH) - [requested](https://gsa-tts.slack.com/archives/C0X2FMJ86/p1585891878003900)
- [x] Remove team member from [Snyk](https://app.snyk.io/org/data.gov/manage/members)
- [x] Remove team member from [Agari](https://gsa-tts.bp.agari.com/) (see [#admins-dmarc](https://gsa-tts.slack.com/archives/CNDTG5ML5) or @adborden for access)
- [x] Rotate [Ansible Vault](https://github.com/GSA/datagov-deploy/wiki/Keypair-Rotation#ansible-vault) key

**Comment by adborden** [comment]
For ansible key rotation: https://docs.ansible.com/ansible/latest/user_guide/vault.html
