### ISSUE TITLE
Investigate dashboard crawls not running

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1515]
## Description
When you look at the labs.data.gov/dashboard page, every agency should have at least some record showing up for the current quarter. However, that's not always the case.

@philipashlock [said in Slack](https://gsa-tts.slack.com/archives/C2N85536E/p1585799655136500?thread_ts=1585677852.091500):
> It looked like there were already some issues in the past with the last few months of 2019 where crawls weren't running properly so they weren't showing up there before the change anyway, but I'll spend some time tomorrow or Friday looking into what data from that period is available to salvage anyway

We need to investigate whether crawls are being invoked as expected, and if so, what might be blocking their completion. We should also be checking that we are being made aware of this problem as soon as it happens via some kind of explicit alert or notification.

## Reproduction steps

View the [Department of Transportation report](https://labs.data.gov/dashboard/offices/detail/49035/2020-06-30) and the [Department of Commerce report](https://labs.data.gov/dashboard/offices/detail/52668/2020-06-30).

## Expected

There should be details from the most recent crawl.

## Actual

There's record that crawls happened, but no data on what was discovered.

**Comment by mogul** [comment]
In a quick scan of rows with no data, we found some 403s being returned for the data.json file location. There was at least one 301 as well. We need to investigate these results.

**Comment by mogul** [comment]
I suspect that these are resulting from another place where the PHP code crashes when it attempts to validate a large data.json file and exceeds available memory. I'm keeping my eye on [`ajv-cli`](https://github.com/ajv-validator/ajv-cli) as a potential option to use for that job in future.

**Comment by mogul** [comment]
I found that `crawl_status` was `final` for a whole bunch of rows in `datagov_campaign` for the current milestone. Similarly, a bunch of rows were `in_progress` when they should also have been `archive`.  If things are working right that column should have been `archive` in all rows except the most recent, which should be `current`.  

Aaron and I traced the code and found that when setting the status after the most recent crawl, it will (likely unintentionally) propagate the status from **the most recent previous row** when it tries to set the newest scan to `current`, no matter what status that previous row had. 

I suspect that a bunch of scans were manually marked `final` a few days after the end of the previous quarter, and because of the bug we observed, that `final` status gets propagated forward since it was the last one... over and over and over, even as new scans are done.

To clear this up, I marked all existing rows in the current milestone `archive`, then kicked off a new `datajson` scan. Sure enough, very soon there was a single row with the `current` status for each agency and the data was showing up in the dashboard.

I kicked off a `full-scan` overnight, and will monitor the results to see that new scans are reliably being shown in the dashboard. 

After that I'll revisit the question of whether any agencies are **not** being scanned regularly, and close or continue to work on this issue accordingly.

It sounds like a PR which prevents unintentionally propagating the status of the previous row is needed in any case.

**Comment by mogul** [comment]
> It sounds like a PR which prevents unintentionally propagating the status of the previous row is needed in any case.

I made [a separate issue about this bug](https://github.com/GSA/datagov-deploy/issues/1804).

**Comment by mogul** [comment]
Back to the original problem: @philipashlock thinks that some `full-scan` crawls (which is what the cronjob does) just time out/blow up sometimes. Sometimes re-running them works fine. He also suspects they're not as isolated as intended, so one crawl failing might result in the crawls following not happening; we might learn that's the case when #1801 is resolved.

**Comment by mogul** [comment]
Blocked until we know that #1801 is resolved and the end of the quarter milestone (June 30th) has passed.

**Comment by mogul** [comment]
It's July 9th, and the most recent crawls listed are from July 1st. The fix for #1801 just rolled out today so we can check tomorrow to see if crawls are running again.

**Comment by jbrown-xentity** [comment]
@mogul Dashboard did not have any successful crawls last night... :cry: 
Found this error when doing the log audit, please use if helpful:

```
dashboardweb1p.prod-ocsit.bsp.gsa.gov: 2020/07/10 07:58:30 [error] 1323#1323: *21122 
FastCGI sent in stderr: "Primary script unknown" while reading response header from 
upstream, client: 103.108.22.3, server: labs.data.gov, request: 
"GET /dashboard/offices/detail/49030/index.php HTTP/1.1", upstream: 
"fastcgi://127.0.0.1:9000", host: "labs.data.gov"
```

**Comment by pjsharpe07** [comment]
After implementing [the PR above](https://github.com/GSA/project-open-data-dashboard/pull/290) on staging, it looks like the crawls are moving again. Will continue to monitor throughout the current sprint cycle.

**Comment by pjsharpe07** [comment]
Continued monitor of what's on staging of the current crawls. As of 07/17 we had:
`in_progress`: 1132
`current`: 23
As of 07/20 we have:
`in_progress`: 1348
`current`: 37

All `in_progress` have null values for `crawl_end`, so some investigation is needed to find out what is going on with these crawls.

**Comment by pjsharpe07** [comment]
In staging, confirmed that crawls are running and populating data into the db  as expected. However, the `crawl_end` is being left as null and the `crawl_status` is being left as `in_progress`. 

The app will display the information for the current milestone if `crawl_status` is `current`. Verified on staging by manually changing the db's `crawl_status` for certain agencies.

During the `full-scan` crawl, this status should be updating during the [status_single_office function](https://github.com/GSA/project-open-data-dashboard/blob/master/application/controllers/Campaign.php#L663)  - specifically during the [datajson steps](https://github.com/GSA/project-open-data-dashboard/blob/master/application/controllers/Campaign.php#L841-L885). 

I think we could either:
- Create a script that will convert the most recent crawl's `crawl_status` from `in_progress` to `current` for agencies that meet certain criteria (ie at least some data in digitalstrategy, data, or datajson).
- Edit and test the current code base to find out why this isn't updating as expected

**Comment by pjsharpe07** [comment]
Blocked until #2019

**Comment by pjsharpe07** [comment]
A calendar invite has been added to the data.gov with instructions (current date is 12/01/2020).
