### ISSUE TITLE
Enable optional native login in the inventory ansible role

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1517]
## User Story

In order to enable deployment and testing of inventory CKAN in non-BSP environments, we want the setup of local vs SAML authentication to be configurable with a variable.

## Acceptance Criteria
- [x] GIVEN sandbox environments are configured with `inventory_ckan_saml2_enabled: false`
  WHEN the `inventory.yml` playbook is run
  THEN the environment is configured with CKAN's native user/password login
- [x] GIVEN that the BSP environments are configured with `inventory_ckan_saml2_enabled: true`
  WHEN the `inventory.yml` playbook is run
  THEN the environment is configured with SAML2 authentication

## Details

Similar work has [already been done for catalog](https://github.com/GSA/datagov-deploy/pull/1474).

Will need to 

- Upgrade to correct version of repoze.who library
- Use default who.ini file (don't replace with saml2 version)
- Add variable configuration for CKAN extensions list similar to current catalog implementation

**Comment by adborden** [comment]
Added some AC.

**Comment by adborden** [comment]
Was just chatting with @jbrown-xentity @pjsharpe07, we probably don't want to do this work, at least not as described. We can pull in a few similar changes from https://github.com/GSA/datagov-deploy/pull/1474/commits/1c86878e3da6d6ebba1a1679e870ae66b02cf9a0 and https://github.com/GSA/datagov-deploy/pull/1474/commits/71b64e9acde27f2be1e4f41aa74dc714b8a40ddf, but we don't actually need to combine saml2 into the inventory role. We should be able to just [skip the role](https://github.com/GSA/datagov-deploy/blob/develop/ansible/inventory.yml#L13) based on the `inventory_app_saml2_enabled` variable.

In the longer-term, https://github.com/GSA/datagov-deploy/issues/1473 will address the tech debt and remove the need for the saml2 role.

I'm going to rename this issue so it's more clear as to what we're after.
