### ISSUE TITLE
Ansible role for datapusher

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1524]
## User Story

As a Data.gov developer, I want a separate Ansible role for datapusher so that I can deploy datapusher separately from Inventory.

## Acceptance Criteria
- [ ] GIVEN that I run the datapusher.yml playbook
    THEN datapusher is deployed
    AND Inventory is unchanged

## Details
This helps us de-couple datapusher from Inventory which allows us to move datapusher to cloud.gov separately from Inventory.

It also keeps Inventory focused on CKAN and allows us to create a common role for Catalog and Inventory.

As a python app, the datapusher role should follow patters from [datagov-deploy-pycsw](https://github.com/GSA/datagov-deploy-pycsw).

**Comment by jbrown-xentity** [comment]
This is not complete, but the work to complete it is simplified by #2073

**Comment by nickumia-reisys** [comment]
No more ansible,
- https://github.com/GSA/data.gov/issues/3710

@jbrown-xentity @FuhuXia Can you confirm that we don't even have datapusher anymore?
- It would help for this issue too: https://github.com/GSA/data.gov/issues/2787
