### ISSUE TITLE
Catalog ssl directory has incorrect permissions

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1534]
Not sure when this started, but I'm seeing the SSL private directory with incorrect permissions on several staging catalog-web instances.

```
ubuntu@catalog-web1d:~$ sudo ls -ld /etc/ssl/private
drwx--x--- 2 root ssl-cert 4096 Mar 19 16:47 /etc/ssl/private
```

## How to reproduce

1. Connect to catalog-web1d
1. `sudo ls -ld /etc/ssl/private` 

## Expected behavior

Directory is readable by ssl-cert group (0750)

## Actual behavior

Directory is not readable by ssl-cert group (0710)

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
