### ISSUE TITLE
Provision Redis (ElastiCache) for CKAN 2.8 in sandbox environment

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1536]
## User Story

As a Data.gov developer, I want Redis ([ElastiCache](https://aws.amazon.com/redis/)) provisioned in sandbox so that I can deploy Inventory CKAN 2.8 and meet its dependencies.

As a Data.gov developer, I want Redis ([ElastiCache](https://aws.amazon.com/redis/)) terraform module so that I can pass it over to BSP to demonstrate exactly what I need using infrastructure as code.

## Acceptance Criteria
- [x] GIVEN we run terraform in the CI environment
  THEN a Redis ElastiCache instance is created for CKAN 2.8
  AND an output describes the connection settings for use in the Ansible inventory
- [x] GIVEN I create a ticket for BSP to provision Redis ElastiCache
  AND I link to the terraform templates
  THEN BSP is able to provision Redis ElastiCache using our templates as a reference.

## Details

CKAN 2.8 depends on Redis so we'll need to provision a new one. We already have Ansible roles to provision a self-hosted Redis, but using the AWS service would be preferred so we don't have to manage it ourselves.

**Comment by adborden** [comment]
https://gist.github.com/adborden/1f6ccddcf1b4f5f87d6fb1a737e142ef contains a gist with an example main.tf using the Redis module that we can hand off to BSP.

**Comment by adborden** [comment]
@woodt would you QA this?

**Comment by woodt** [comment]
So I think this looks fine ... two questions, mostly to cement my own understanding:

(1) We still need to add the catalog-next (really, catalog-harvester-next) redis host name to a group_vars?  I'd imagine we do that as part of one of the harvesting stories.

(2) Here's what the relevant portion of the ansible inventory looks like for sandbox, which seems OK to me but I want to confirm it is as intended:

```
 |--@redis:
  |  |--@redis-catalog:
  |  |  |--@tag_group_catalog_harvester:
  |  |  |  |--catalog-harvester-next1tf.internal.sandbox.datagov.us
  |  |  |  |--catalog-harvester1tf.internal.sandbox.datagov.us
  |--@redis-catalog-next:
  |--@redis-inventory-next:
```

**Comment by adborden** [comment]
Hmm, that looks wrong and needs to be fixed in the datagov-infrastructure-* repos. I'll look into that. `tag_group_catalog_harvester` should no longer be part of `redis` or `redis-catalog`.

The current plan is to use ElastiCache for the -next instances, so there should be 0 redis hosts in `redis-catalog-next`. I included the groups just to make it explicit that these groups exist, but they are empty. And in the possibility that ElastiCache falls through for BSP, it's obvious how to add a host to the Ansible inventory.

**Comment by woodt** [comment]
@adborden move this back to in progress, then?  Or deal with the incorrect EC2 tag in other ticket?

**Comment by adborden** [comment]
I'll move it back to In Progress. With your stuff merged, I also want to see the redis config makes it into production.ini.
