### ISSUE TITLE
CloudWatch Alarms on CPU move to New Relic (and tune)

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1544]
## User Story

In order to give us more control over how CPU alerts are generated and delivered, we want to disable CloudWatch Alarms for CPU on catalogweb and tune the CPU alerts on New Relic.

## Acceptance Criteria
- [x] WHEN we generate artificial load on a monitored host for more than 10 minutes
  THEN we see an alert from New Relic
  AND we see no alert from CloudWatch

**Comment by jbrown-xentity** [comment]
Also: Add an alert to New Relic for database performance

**Comment by pjsharpe07** [comment]
Testing on 05/08 yielded alarms for both New Relic and Cloudwatch (as expected).

Submitted a service request for BSP to deactivate the Cloudwatch alarms. Test again after completion of service ticket.

**Comment by pjsharpe07** [comment]
Service Now Ticket `RITM0730128`

**Comment by jbrown-xentity** [comment]
Consider tuning so that if a service is down, we only get an alert from 1 location, or a limited number. Received many notifications last night about dashboard being down.

**Comment by pjsharpe07** [comment]
The command line to test high cpu is: `sudo stress --io 4 --timeout 720`. Depending on the host, the io (number of workers) might need to be larger to force higher cpu load.
