### ISSUE TITLE
inventory-2-8-web1tf fails on sandbox blocking inventory testing

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1552]
##  How to reproduce

1. `ansible-playbook -i inventories/ci inventory.yml`

## Expected behavior

inventory-2-8 is not included, or fails in the same way as other instances

## Actual behavior
inventory-2-8 fails, blocking the playbook from running on non 2.8 hosts.

## Workaround
Work around is to skip the inventory-2-8 host

`--limit '!inventory-2-8-web1tf.internal.ci.datagov.us'`

**Comment by mogul** [comment]
@starsinmypockets FYI, we're putting this high in our backlog as of today so it hopefully won't trip us up much longer.

**Comment by adborden** [comment]
I think @jbrown-xentity was working on a fix, but feel free to hand off if you need.

**Comment by mogul** [comment]
Sounds like a fix is available, but needs to be back-ported from the current release. Fuhu will look into that.

**Comment by FuhuXia** [comment]
The fix is already in current release branch. We can back-port to `develop` by merging release once it is the release is complete.

**Comment by FuhuXia** [comment]
The fix is deployed and ported to `develop` branch.
https://github.com/GSA/datagov-deploy/pull/1566
