### ISSUE TITLE
Add New Relic Infrastructure agents

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#157]
Add New Relic Infrastructure and Language agents for Python/PHP/Java footprint https://github.com/newrelic/infrastructure-agent-ansible coordinating with current inventory/tags

**Comment by dano-reisys** [comment]
the infrastructure agent has been deployed to prod & staging

**Comment by kvuppala** [comment]
created a new ticket for application agents #174

**Comment by the-vladman** [comment]
could you integrate new relic to CKAN?
