### ISSUE TITLE
[research:2d] Investigate GitHub Actions as CircleCI alternative

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1571]
## User Story

In order to understand the level of effort required to remove CircleCI from our operations/compliance domain, we want to spend up to 2 days to converting the data.gov dashboard to use GitHub Actions to run tests and [this cloud.gov GitHub Action](https://github.com/cloud-gov/cg-cli-tools) for deployment.

## Acceptance Criteria
- [ ] We are able to estimate the LOE/time needed to get all of our repos to use GitHub Actions for CI.

## Details
See [the CircleCI to GitHub Actions migration guide](https://help.github.com/en/actions/migrating-to-github-actions/migrating-from-circleci-to-github-actions) and reference [this example](https://leerob.io/blog/github-actions)

**Comment by nickumia-reisys** [comment]
This has since been implemented.  Our most recent effort revolving Github Actions,
- https://github.com/GSA/data.gov/issues/4121
