### ISSUE TITLE
Entity already exists when new IAM user tries to create MFA device

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1594]
When adding a new IAM user and the new user tries to add a virtual MFA device, they receive an error:

**work around**

    $ aws iam delete-virtual-mfa-device --serial-number arn:aws:iam::587807691409:mfa/<user>

## How to reproduce

Following the [new IAM user docs](https://github.com/GSA/datagov-infrastructure-live/tree/master/iam#new-users):

1. Add a new user to `users.tf`
1. Admin enables console access and sets a temporary password
1. New user logs into the console, updates their password.
1. New user goes to add a new virtual MFA device.

## Expected behavior

User is able to create a new virtual MFA device.

## Actual behavior

![Screenshot from 2020-04-23 13-27-54](https://user-images.githubusercontent.com/509703/80131492-2d787100-854f-11ea-93ee-eed5fb9e0ac3.png)

**Comment by adborden** [comment]
:joy:  https://github.com/Beartime234/aws-mfa-entity-already-exists-fix

**Comment by jbrown-xentity** [comment]
This fix is already in place, closing.
