### ISSUE TITLE
Run solr-sync job automatically on a schedule

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1595]
[This issue is about running the solr-sync job regularly to take care of any problems that might result in CKAN and Solr being out of sync, eg what we see in #1542 .]

## User Story

As a [user description], I want [behavior description] so that [goal].

## Acceptance Criteria
- [ ]

**Comment by jbrown-xentity** [comment]
Closing as duplicate of https://github.com/GSA/datagov-deploy/issues/2213
