### ISSUE TITLE
Optimize catalog postgresql database

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1599]
## User Story

As a Data.gov user, I want to optimize the catalog database so that browsing the site feels consistent and smoother, without some requests taking a long time.

As a Data.gov operator, I want to optimize the catalog database so that I have fewer production issues related to database performance.

## Acceptance Criteria
- [ ] WHEN I view catalog performance in New Relic
  THEN there are fewer spikes from database time
  AND there are fewer spikes in database transaction time
  AND there are fewer spikes in the web transaction 95th percentile

## Details
As part of https://github.com/GSA/datagov-deploy/issues/1548, we were under a time crunch and didn't have time to optimize as much as we'd have liked. This story would involve a process similar to the major database upgrade: creating a new primary and replicas, doing some optimization (e.g. `VACUUM ANALYZE FULL`), rebuilding some or all indexes, possibly reducing the database volume size, and validating the changes against a production-like load.

We don't have to get too deep into CKAN performance, but if any issues are identified we should report them upstream.

Additionally we could consider creating stories for these:
- Identify a method to update the staging database with a production snapshot. Not sure if FCS can do this easily or if we have to come up with a "manual" alternative.
- Developing a method for load testing. This would've been helpful to test the database instance before putting it into service.
- Upgrade to Postgresql 9.6 or 10. [9.5 is EOL February 11, 2021](https://aws.amazon.com/blogs/database/moving-on-from-amazon-rds-for-postgresql-versions-9-4/) and 9.6 is EOL November 11, 2021.

**Comment by adborden** [comment]
@mogul is calling me out for un-testable/ambiguous acceptance criteria :) we'll chat more about this when we groom/triage.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
