### ISSUE TITLE
Pros/Cons of Ansible AWS Module vs. Cloudformation

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#16]
Ansible Modules:
https://github.com/ansible/ansible-modules-extras/tree/devel/cloud/amazon

**Comment by neilhunt1** [comment]
@JJediny I think you mentioned today that the current plan is to use Ansible AWS Module where possible over an AWS CloudFormation template? If that's the case, is there anything else to do here? Or do we still want to map out pros/cons of each solution and determine which way we want to go?
