### ISSUE TITLE
Jenkins1tf out of disk space from /var/lib/docker

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1610]
On Sandbox, jenkins server runs out of disk space and will not allow any new actions.

## How to reproduce

1.Allow disk to fill up on jenkins1tf due to Docker

## Expected behavior

Docker should be using the /data partition so that memory does not run out frequently

## Actual behavior

Docker fills up the disk and it becomes unresponsive

## Mitigation
Run the following commands:

```
    docker container prune
    docker volume prune
    docker image prune
```

You may also find other large pockets of data by running `sudo du -sh /*`, and following large data folders to the source of the problem.

**Comment by pjsharpe07** [comment]
Ran into this again today and used the mitigation steps listed in the issue description

**Comment by adborden** [comment]
Thinking about what the fix looks like... I think we want to add a new docker Ansible role that:
- installs and configures docker
- symlinks /var/lib/docker to /data/docker
- creates a daily cron to:
  - `docker container prune`
  - `docker volume prune`
  - `docker image prune`

**Comment by jbrown-xentity** [comment]
Happened again today, starting to hit this every 2 weeks...

**Comment by jbrown-xentity** [comment]
Hit again today, closer to 1 week since last incident...

**Comment by adborden** [comment]
~Next time the disk is full,~ we want to see if it's more on the docker side or the jenkins side. Both are on the same EBS volume. We'll want to adjust the size of the EBS and consider adjusting retention for Jenkins build history.

**Comment by jbrown-xentity** [comment]
Most of Jenkins data is held in a separate EBS, it's Docker that continues to fill up the system (as far as I can tell)...

**Comment by adborden** [comment]
Ah, I had manually setup a symlink /var/lib/docker -> /data/docker but it looks like that's been removed somehow, maybe from the playbook. Definitely worth resolving this GH issue in that case.

**Comment by jbrown-xentity** [comment]
Hit again today. Started mitigation, and then ran [these steps](https://www.guguweb.com/2019/02/07/how-to-move-docker-data-directory-to-another-location-on-ubuntu/) to implement docker installation in new place. Will see if it holds...

**Comment by jbrown-xentity** [comment]
Configuration holding with setting the `daemon.json` file at `/etc/docker` to be the following, marking as done...

```
{
    "graph": "/data/docker"
}
```
