### ISSUE TITLE
PyCSW in sandbox shares RDS instance with catalog CKAN

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1613]
In order to have better parity with production, we should have a separate RDS instance for PyCSW configured in sandbox like we have in BSP environments.

## How to reproduce

1. `grep db /etc/pycsw/pycsw-collection.cfg`

## Expected behavior

Database hostname is different than the hostname used for CKAN (/etc/ckan/production.ini)

## Actual behavior

Database hostname is the same as CKAN.

**Comment by nickumia-reisys** [comment]
No more pycsw.  No more FCS.
- https://github.com/GSA/data.gov/issues/3182
- #3710
