### ISSUE TITLE
Inventory smoke test fails because gunicorn service isn't started

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1614]
```
TASK [assert app is up] ***************************************************************************************************************************************
FAILED - RETRYING: assert app is up (3 retries left).
FAILED - RETRYING: assert app is up (2 retries left).
FAILED - RETRYING: assert app is up (1 retries left).
fatal: [inventory-web1tf.internal.sandbox.datagov.us]: FAILED! => {"attempts": 3, "changed": false, "connection": "close", "content": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n</body></html>\n", "content_length": "299", "content_type": "text/html; charset=iso-8859-1", "date": "Thu, 30 Apr 2020 00:50:42 GMT", "msg": "Status code was 503 and not [200]: HTTP Error 503: Service Unavailable", "redirected": false, "server": "Apache", "status": 503, "url": "http://inventory-web1tf.internal.sandbox.datagov.us/api/action/status_show"}
```

The proxy config exist in /etc/apache2/sites-enabled/ckan.conf but it looks like the service isn't actually running.

## How to reproduce

From the sandbox jumpbox:

1. `ansible-playbook inventory.yml`

## Expected behavior

Smoke test should succeed, supervisorctl status should show the ckan app.

## Actual behavior

Supervisor is not running the new gunicorn service
```
ubuntu@inventory-web1tf:~$ sudo supervisorctl status
beaker-cache-cleanup             STOPPED    Not started
```

**Comment by adborden** [comment]
I ran `supervisorctl reread && supervisorctl reload` but it looks like the service still isn't starting.

```
ubuntu@inventory-web1tf:~$ sudo supervisorctl status
beaker-cache-cleanup             STOPPED    Not started
gunicorn-web-app                 FATAL      can't find command '/usr/lib/ckan-new/bin/gunicorn'
```

**Comment by jbrown-xentity** [comment]
That is weird. I just double checked, gunicorn is in the [requirements-freeze file](https://github.com/GSA/inventory-app/blob/master/requirements-freeze.txt#L20). I can't see how it wouldn't be installed if the playbook ran... It just [pulls master](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/inventory/defaults/main.yml#L5) to pip install, right? Nothing has to update for it to pull latest inventory-app?

**Comment by pjsharpe07** [comment]
When on the host and running `/usr/lib/ckan-new/bin/gunicorn --paste /etc/ckan/production.ini -b localhost:5000` we encounter the following error:

`OperationalError: (OperationalError) FATAL:  password authentication failed for user "inventory"
FATAL:  password authentication failed for user "inventory"`

**Comment by adborden** [comment]
Not sure if this is a blocker for the release, @jbrown-xentity will look into it.
