### ISSUE TITLE
[research: 4h] Review USGPO repository for potential integration with Data.gov catalog

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1619]
## User Story

As Data.gov PMO, we want to understand what GPO has available on a public repository so that we can determine if there is an approach to integrate their catalog information so that GPO holdings get increased visibility through Data.gov catalog.

## Acceptance Criteria
- [x] Reviewed USGPO repository on GitHub
- [x] Provide response to USGPO on any potential next steps.

### Research findings
> Research found there are 18,933 records from all files combined on [USGPO github repository](https://github.com/usgpo/cataloging-records). Technically they should be able to fit into one data.json file to be hosted on UPSPG site, such as gpo.gov/data.json, and get harvested by catalog.data.gov.
> 
> Next step for the agency would be to find/develop a tool to generate the data.json file that conform to [Project Open Data Metadata Schema v1.1](https://resources.data.gov/schemas/dcat-us/v1.1/). During the file generation, some validation check should happen to exclude resources that are hot linked to other government web sites, and only keep resources hosted on gpo.gov site. This is necessary to avoid potential duplicated datasets harvested into catalog.data.gov. 

## Details
USGPO has a presence at https://github.com/usgpo/cataloging-records 
We recently had a call to discuss. They are aware of how Data.gov catalog works, the metadata schema, harvesting, etc. and are interested in getting our views on whether there is an approach to get what they are making available at GitHub available through Data.gov catalog.

**Comment by adborden** [comment]
Excellent summary, thanks @FuhuXia.
