### ISSUE TITLE
Preston O+M

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1620]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint.

Each day, you should start your triage by looking through the notification channels for anything **urgent** that came in after hours that might need immediate attention:

- [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) may contain critical host alerts
- [Bug bounty report (ad-hoc email)](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities#bug-bounty-report-ad-hoc-email)
- [Vulnerable dependency notifications (daily email reports)](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports)

## Acceptance criteria

You are responsible for all [O&M responsibilities](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten.

- [ ] [Audit log updated](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) for [AU-6 Log auditing](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities#au-6-log-auditing) (**Friday**).
- [ ] Any [New Relic alerts](https://alerts.newrelic.com/accounts/1601367/incidents) have been addressed or GH issues created.
- [ ] Weekly [Nessus scan](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities#nessus-host-scan-report-from-isso) has been triaged.
- [ ] If received, the monthly [Netsparker scan](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso) has been triaged.

**Comment by mogul** [comment]
@pjsharpe07 if you have any notes for the status as of the end of your shift, good to document them here for @FuhuXia to pick up!

**Comment by pjsharpe07** [comment]
There was an issue with a particular harvest `Original Product Resolution (OPR) Source Digital Elevation Models (DEMs) - USGS National Map`, I noticed it because it was marked `complete`, but wasn't truly done. I did some digging, but didn't make a new issue because we may never see it again. I'll pair with anyone if this harvest issue comes up again.
