### ISSUE TITLE
Review Gulf Coast agency harvest results

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1622]
We added a new agency, Gulf Coast Ecosystem Restoration Council. They have a CSW harvest source. We tried a harvest that resulted in errors.

The harvest URL is:

https://restorethegulf.gov/merlin/srv/eng/csw?request=GetCapabilities&service=CSW&version=2.0.2
![REstore gulf harvest](https://user-images.githubusercontent.com/3236989/80996821-74e3e480-8e0e-11ea-8cae-7c434e01fec8.png)

## How to reproduce

We tried the harvest a few times, with same error results.

## Expected behavior

Wasn't sure whether CSW harvest would work, errors with other agencies were with larger harvest jobs.

## Actual behavior

See harvest report.

**Comment by mogul** [comment]
We provided information about the validation errors back to the agency; it seems like this is something they can resolve on their side.
