### ISSUE TITLE
Unable to add users via UI to inventory.data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1625]
On occasion, we are not able to add users to inventory.data.gov and give elevated permissions, most often "Editor" status, even though user has done initial log in on inventory.data.gov and OMB MAX with 2FA or PIV.

## How to reproduce

Currently running into issue with new user for inventory.data.gov from HUD.

## Expected behavior

Once user has done initial log in, admin user on inventory.data.gov can go to organization, and add member through UI, and choose Editor status. At that point user is added to the list of users for that organization and can start editing metadata on inventory.data.gov.

## Actual behavior

Data.gov PMO unable to add user through admin UI.

**Comment by hkdctol** [comment]
@FuhuXia currently checking, but this issue does occur occasionally even when users have shown they have done initial log in.

**Comment by FuhuXia** [comment]
User entry is not found in CKAN database. Tested on staging and production inventory. A test user is added successfully after a max.gov login. So our max login is functioning properly. The issue for this particular user is most likely an error on user side. Please instruct user to provide a screenshot after logging into inventory site. On the top right corner, user's email address and some extra icons should show up as the attached screenshot.
 
![Screenshot 2020-05-06 13 56 27](https://user-images.githubusercontent.com/1392461/81221007-3ab24880-8fb0-11ea-843d-482754c0f8c3.png)

**Comment by FuhuXia** [comment]
After the user provided a screenshot showing his account info on top of the web page, admin can see the user on the UI and add him to the organization. Issue resolved.

Here is my theory for the cause of the issue. For a first-timer user, if MFA is not set up, max.gov will guide user through the MFA process, during which the redirecting mechanism is lost. At the end, user has a successful max.gov MFA log-in but user's browser will not be redirected to Inventory site, therefore user account will be not created in Inventory CKAN. 

For future reference, when this kind of issue happens, we need to instruct user to open Inventory site again. If the site still shows as "not authorized", user needs to click the login link and make sure the account info show up as demo'ed in the attached screenshot.
