### ISSUE TITLE
Wordpress TLS version support

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1629]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 05/04/2020 - nessus scan. 
**Due date:** unclear

### Brief description
This was part of the nessus scan for [121010 found here](https://docs.google.com/spreadsheets/d/1TiOgoKx52vfwEnAfIqzHjM8_2KmyieZnSsQyVmE3izs/edit#gid=115399693)

**Comment by FuhuXia** [comment]
Dashboard web hosts has same TLS version issue found in item [121010](https://docs.google.com/spreadsheets/d/1qInc2hrKBoBReklU9zbGvaeZcLY4-qmU0nae8nWZhEc) by nessus scan.

**Comment by FuhuXia** [comment]
TLS 1.1 removed from wordpress and dashboard, TLS 1.3 added. This ticket can be closed.

**Comment by adborden** [comment]
@FuhuXia I just deployed WordPress, but I'm still seeing TLSv1.1 in the nginx configuration. I think you still need to bump the Ansible role versions in requirements.yml.

**Comment by FuhuXia** [comment]
@adborden Yes I see. I thought we use master.

**Comment by FuhuXia** [comment]
requirements.yml updated with new tags, verified on sandbox. Ready to go to staging/prod.

**Comment by FuhuXia** [comment]
attaching screenshot showing TLS versions for wordpress and dashboard. 
![Screenshot 2020-06-25 13 28 37](https://user-images.githubusercontent.com/1392461/85803108-7a75f080-b714-11ea-9a2a-9528128af9b8.png)
![Screenshot 2020-06-25 13 28 51](https://user-images.githubusercontent.com/1392461/85803110-7b0e8700-b714-11ea-8710-0458ce588806.png)
