### ISSUE TITLE
jenkins role (jenkins_plugin) can't install plugins with CSRF enabled

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1634]
https://github.com/geerlingguy/ansible-role-jenkins/issues/269

**Work-around** on first run, temporarily pin the version of Jenkins to one where the default is not to enable CSRF.

    $ ansible-playbook jenkins.yml -e jenkins_version=2.191

On following runs, specify no plugins.

    $ ansible-playbook jenkins.yml -e '{"jenkins_plugins": []}'

## How to reproduce

1. ansible-playbook jenkins.yml

## Expected behavior

Playbook completes successfully and is able to install plugins.

## Actual behavior

Playbook fails when installing plugins with "403 cannot install plugin"

**Comment by adborden** [comment]
This is fixed in [Ansible](https://github.com/ansible/ansible/issues/61672) although unsure which version, [possibly 2.9.6](https://github.com/geerlingguy/ansible-role-jenkins/issues/269#issuecomment-595599157) and has yet to be backported.

**Comment by nickumia-reisys** [comment]
No more Jenkins.  No more Ansible,
- https://github.com/GSA/data.gov/issues/3710
