### ISSUE TITLE
Set up New Relic Synthetics for Data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1640]
## User Story

As Data.gov PMO, we want to set up New Relic Synthetics instead of Uptrends. 

## Acceptance Criteria
- [x] Access New Relic Synthetics to set up alerts for data.gov, catalog.data.gov, inventory.data.gov, labs.data.gov (are there others?)
- [x] Wait for a report through Synthetics and review 
- [x] Once familiar with Synthetics functionality, cancel current Uptrends alerts through email to GSA IT/Mike Tanski.

## Details

GSA use of Uptrends is time limited. Data.gov participated in new option period for New Relic with planned use of New Relic Synthetics. The option period has started and we can set this up and conclude Uptrends use.

**Comment by mogul** [comment]
To improve the signal-to-noise ratio, we need to do some additional work to roll up alerts from different test locations for the same observed problem.
