### ISSUE TITLE
Inventory on sandbox has incorrect DB connection string

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1654]
Inventory ckan wont start, complaining DB error. Manually run psql command using the credentials from production.ini gives wrong password error. 

## How to reproduce

`curl -L localhost`

## Expected behavior

A ckan page to be return

## Actual behavior

500 error

**Comment by adborden** [comment]
@FuhuXia I think this is resolved? https://inventory.sandbox.datagov.us/api/action/status_show is working just fine.

**Comment by FuhuXia** [comment]
Yes, resolved. Closing.
