### ISSUE TITLE
Change current redirect for https://www.data.gov/resources

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1658]
## User Story

As a user of the Federal Government's repository of open data resources, I want to find https://resources.data.gov/ without necessarily knowing the URL.

In order to make sure users who need the information on resources.data.gov, OMB, OGIS and GSA want to have https://www.data.gov/resources go to https://resources.data.gov/

Currently, https://www.data.gov/resources redirects to a part of the Climate topic https://www.data.gov/climate/climate-resources

**Comment by FuhuXia** [comment]
Done.
`/resources` and `/resources/` are configured in Wordpress Redirect plugin to be redirected to https://resources.data.gov/.
