### ISSUE TITLE
Nessus 05/11/2020

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1666]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 05/11/2020
**Due date:**  08/20/2020

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability

### Brief description
[Nessus Scan](https://docs.google.com/spreadsheets/d/1VOXp-4kwFzrFADb3tt5rjYvNsJtJ6hSrl3AOnjMUMIU/edit#gid=1792717016)

**Comment by mogul** [comment]
This is being addressed via PR #1810
