### ISSUE TITLE
Switching to high-contrast mode and back breaks images on sdg.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1670]
Report from email:

> Toggling the contrast switcher in the top right of the page from "high-contrast" to "default", all images on the site break. After some debugging, I have found that this is due to the imageFix function in the accessibilitySwitcher. When switching to "high-contrast", the string "high-contrast/" is added to the images' source path, but when switching to "default", only the string "high-contrast" is removed from the path. The leftover "/" gets left in the source path, and thus causes a 404.
>
> It is also worth mentioning that the code used here will remove all instances of the string "high-contrast". If you were to have an image with "high-contrast" in its file name, e.g. "img/high-contrast_logo.png" you would be left with just "img/_logo.png". Just something to consider. Attached is a screenshot of the error messages, as well as the code causing the problems.

I'm not sure if this has already been fixed upstream.

## How to reproduce

1. Open https://sdg.data.gov/
1. Click high-contrast mode in the top right
1. Click default contrast mode in the top right

## Expected behavior

Goal images appear in default contrast mode.

## Actual behavior

Goal images are broken.
![Screenshot from 2020-05-15 09-47-03](https://user-images.githubusercontent.com/509703/82075418-0ebe5380-9691-11ea-85bc-0bc7dd5ae605.png)

**Comment by jbrown-xentity** [comment]
This now works as expected, closing.
