### ISSUE TITLE
Automated initialization for new BSP instances

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1673]
## User Story

In order to avoid manual work while providing a consistent, repeatable process, Data.gov operator wants a script for initial instance provisioning in BSP.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN a new instance is provisioned in BSP
  AND I add the new instance to the Ansible inventory
  WHEN I follow the new instance provisioning process
  THEN I can run `ansible -m ping` on the new host successfully
  AND /var/log is mounted to a volume
  AND any data volumes are mounted to /data

## Background

The [new instance provisioning](https://github.com/GSA/datagov-deploy/wiki/Provisioning-new-hosts) process is rare and not well documented.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch
A simple shell script probably makes the most sense because until python is installed, we can't run Ansible. However, the script could literally by `ssh $host sh -c "sudo apt-get update && sudo apt-get install python"` and then Ansible could be used for anything following.

We also want to consider a solution that works for both sandbox (which is already done through terraform provisioning) and FCS.

**Comment by adborden** [comment]
Mostly just wanted to document that a) this is currently manual and b) there is a [wiki stub](https://github.com/GSA/datagov-deploy/wiki/Provisioning-new-hosts).

**Comment by hkdctol** [comment]
closing tickets related to BSP
