### ISSUE TITLE
[research 1d] Test the inventory upgrade/migration with production data

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1675]
## User Story

In order to determine if there is additional work to upgrade-in-place or migrate the existing Inventory production database, data.gov operator wants to test the inventory upgrade/migration with production data.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN we restore a recent production snapshot in staging
  WHEN I run through the switchover process
  THEN there exists a plan with documented step-by-step instructions that can be followed to completion
- [x] GIVEN the switchover process has been executed on staging
  WHEN I open the staging URL
  AND I submit a new dataset
  THEN I can view the new dataset's page
  AND I can export a data.json file with the new dataset.

## Background
Research story should be time boxed to 1 day.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
All activity will be in the staging environment. Any security concerns for the production migration will be noted as follow-on issues alongside other issues identified during the research.

## Sketch
- [x] Create a new RDS instance based on a recent Inventory production database snapshot in BSP
- [x] Run the `ckan db update` command
- [x] Identify any issues and possible remediations
- [x] Create additional GH issues for any additional work necessary
- [x] Draft a switchover plan with any step-by-step instructions to be exceuted in order to go live with CKAN 2.8 in a GH issue

**Comment by FuhuXia** [comment]
UI issue #2244, #2245, #2246
DB issue #2247
Switchover plan #2248
