### ISSUE TITLE
Provision new RDS database in staging for Inventory CKAN 2.8

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1676]
## User Story

In order to test CKAN2.8 is working properly in the staging environment without interrupting our ability to test against CKAN 2.5, data.gov operator wants a new RDS instance in staging.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I find the Inventory CKAN 2.8 ansible variable `inventory_ckan_db_host`
  WHEN I connect to this database
  THEN it has no CKAN tables

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None. Adding a new temporary database in staging for testing does not affect our scope.

## Sketch
- [x] Ticket for BSP
- [ ] Validate the database is created, provision it for Inventory (`ckan db init`, etc)

**Comment by jbrown-xentity** [comment]
Ticket for BSP [created](https://gsa.servicenowservices.com/sp/?id=sc_request&is_new_order=true&table=sc_request&sys_id=522576f71b0254509496ddb6bc4bcbc0).

**Comment by jbrown-xentity** [comment]
BSP has system in place, to verify today and close if configuration is as expected.

**Comment by jbrown-xentity** [comment]
Cannot use CKAN system to deploy DB, but BSP has DB in place. Will need to complete #1678 before can provision on sandbox and test deployment. Moving to blocked until #1678 is complete.
