### ISSUE TITLE
Enable builds for Inventory CKAN 2.8 on sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1678]
## User Story

In order to be confident that Inventory CKAN 2.8 will work in staging and production, data.gov developer wants deploys enabled in sandbox for Inventory CKAN 2.8.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I run the inventory.yml playbook in sandbox
  THEN the playbook runs successfully to completion

## Background
Inventory 2.8 is still [disabled on develop](https://github.com/GSA/datagov-deploy/blob/develop/ansible/inventory.yml#L3), so is not being deployed.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch
Need to model after catalog-next functionality:

- [x] Change inventory2_8 endpoints and variables to inventory-next
- [x] Apply ^^ to infrastructure in sandbox
- [x] Rebase inventory2_8 branch on current develop for datagov-deploy
- [x] Test deployment on sandbox manually via ansible

The following will be spun off into their own tickets to simplify the work being merged...
- [ ] Initialize the database
- [ ] Setup saml2 for enable/disable functionality for sandbox
- [ ] Fix datapusher configuration with [latest notes](https://docs.ckan.org/projects/datapusher/en/latest/deployment.html)
- [x] Fix gunicorn immediate crashing (SOLR configuration)
- [ ] Submit PR and finalize any issues with automated deployment via Jenkins

**Comment by jbrown-xentity** [comment]
@adborden I can't remove the current inventory2.8 infrastructure, I don't have permissions... Can you either add permissions for infrastructure destruction to develop role, or pull the [in-work branch](https://github.com/GSA/datagov-infrastructure-live/tree/feature/inventory-next) and run `terraform destroy -target=module.inventory_2_8` as a one-off?

**Comment by adborden** [comment]
@jbrown-xentity I'm worried that this is growing too much in scope. How about we limit the AC to just this:
> WHEN I run the inventory.yml playbook in sandbox
> THEN the playbook runs successfully to completion

and we set `datagov_in_service: false` so that even though it's not completely working, we're at least building and deploying. We can also add additional variables if we need to disable certain deploy tasks, e.g. datapusher.

Then we can create additional tickets for any work to get it actually running, e.g. datapusher, solr configuration, etc. We already have a separate issue for [MAX.gov/SAML2](https://github.com/GSA/datagov-deploy/issues/1186) so I don't think we want to spend time adding saml2 enable/disable, at least not in this story.

**Comment by jbrown-xentity** [comment]
Agreed. PR updated and ready to merge as is, inventory-next not in complete working state but deploy resolving as expected. Will spin off next bullet items as separate tickets from description @adborden ...
