### ISSUE TITLE
Ubuntu Advantage micropurchase

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1682]
## User Story

As a Data.gov operator, I want an [Ubuntu Advantage](https://ubuntu.com/advantage) subscription so that I get all the benefits and technical support from a commercially supported plan.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN the UA subscription is active
  WHEN I inspect apt sources on a UA host
  THEN the UA repository updates are enabled.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None.

## Sketch
- [x] Start a discussion with the ISSO in case there are any security compliance concerns
- [x] Micropurchase https://handbook.tts.gsa.gov/purchase-requests/
- [x] Enable UA subscription on select UA hosts.

**Comment by adborden** [comment]
Initial micropurchase request has been submitted.

**Comment by adborden** [comment]
The request was approved, I'm just following up to make sure it's being billed to the correct place.

**Comment by mogul** [comment]
@adborden saw that the request was approved last week, but there's been no movement since. He'll check in with Aidan to understand the next steps.

**Comment by adborden** [comment]
Purchase is going through on Monday.

**Comment by adborden** [comment]
:tada: we have UA! The next steps are:
1. Sign up for Ubuntu One account using TTS email (this is **not** datagovhelp@)
1. Get the UA token through Ubuntu One
1. [Setup the clients](https://wiki.ubuntu.com/UAclient)

**Comment by adborden** [comment]
@pjsharpe07 I manually installed ua on catalog-harvester1d just to check some things. So far, looks good!

**Comment by pjsharpe07** [comment]
UA is installed on select hosts! 🎉 You can verify by running `ua status` when on the host. There is also some detailed account level information in our [shared google drive](https://docs.google.com/document/d/1EQu5LR7OJ2UDbARiZD_ZDYw2YgLRUxQ1m3nmDbbESDM/edit)

Moving this to done as it was deployed as a hotfix.
