### ISSUE TITLE
logrotate error: destination already exists, renaming to [filename].backup

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1684]
logrotate on host catalogb-web1p gives error: 
 
```
/etc/cron.daily/logrotate:
error: destination /var/log/ckan/ckan.error.log.1 already exists, renaming to /var/log/ckan/ckan.error.log.1-2020051906.backup
error: destination /var/log/syslog.1.gz already exists, renaming to /var/log/syslog.1.gz-2020051906.backup
```
multiple backup files are generated on daily basis and will eventually fill up /var/log/ partition.

## How to reproduce

cron email notification.

## Expected behavior

log files being rotated by logrotate

## Actual behavior

new files are generated

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
