### ISSUE TITLE
catalog-harvester2d low disk space on root partition

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1687]
%95 disk usage on /.

It is due to many xml files in `/tmp/s3sitemap` generated by cronjob `ckan-sitemap`. Some are 30 days old.

**Comment by mogul** [comment]
We've got some time until this bugs us again after a manual clear; going to Icebox for now.

**Comment by adborden** [comment]
I think this is a duplicate of https://github.com/GSA/datagov-deploy/issues/742. The root cause is that the s3sitemap job fails in staging and doesn't cleanup the generated files.

**Comment by pjsharpe07** [comment]
Just ran into this issue again and did a manual cleanup of the `/tmp/s3sitemap` directory

**Comment by FuhuXia** [comment]
Same issue today. Manually cleaned up `/tmp/s3sitemap`.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
