### ISSUE TITLE
Enable Synthetics' Private Locations checks for staging URLS

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1694]
## User Story

In order to be alerted when staging services are unavailable, Data.gov operator wants Synthetics' Private Locations checks implemented in the BSP environment for staging URLs.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN a staging deploy completes successfully
  AND there is a latent issue with the deploy
  WHEN a staging service goes down
  THEN I receive a slack notification

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
The SSP should be updated to include how New Relic Synthetics Private Location checks are implemented in staging.

## Sketch
- Double check how many Private Locations checks we're allotted by the NR procurement and there is capacity for additional checks
- Identify which host should run/manage the checks
- Add [installation steps](https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/private-locations/private-locations-overview-monitor-internal-sites-add-new-locations) to Ansible playbooks

**Comment by nickumia-reisys** [comment]
No more FCS.  No equivalent on cloud.gov setup.
- https://github.com/GSA/data.gov/issues/3710
