### ISSUE TITLE
pycsw is loading data from production api from all env

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1700]
Sandbox and Staging have `pycsw-load` cronjob turned on. the `ckan_url` in the config is pointing to production api. As a result, it creates extra workload to production web instances, and their `pycsw` database get unnecessarily big with production data.

**Comment by jbrown-xentity** [comment]
Also this [Pull Request](https://github.com/GSA/datagov-deploy-pycsw/pull/9)
