### ISSUE TITLE
Nessus 05/24/2020

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1706]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 
**Due date:** 

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
[Nessus Scan](https://docs.google.com/spreadsheets/d/1qInc2hrKBoBReklU9zbGvaeZcLY4-qmU0nae8nWZhEc)

**Comment by mogul** [comment]
We already resolved this through the PR referenced above; this one is a dupe.
