### ISSUE TITLE
Catalog Tomcat upgrade

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1707]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 05/01/2020 - nessus scan
**Due date:** 05/31/2020

### Brief description
Items [133845, 126125, 132413](https://docs.google.com/spreadsheets/d/1qInc2hrKBoBReklU9zbGvaeZcLY4-qmU0nae8nWZhEc) in nessus scan

**Comment by adborden** [comment]
I removed tomcat from these hosts, which aren't supposed to have tomcat anyway.

```
ansible -m apt -a 'name=tomcat6 state=absent' catalog-web,inventory-web
```

**Comment by adborden** [comment]
Also removed from these hosts since they are not currently in service.

```
ansible -m apt -a 'name=tomcat8 state=absent' catalog-harvester-v2
```

**Comment by adborden** [comment]
I'm looking at the relevant CVEs and comparing versions to the Ubuntu repository and it looks like they are not available. Some investigation is necessary on what the right fix is, it's not as simple as apt-get upgrade.

**Comment by FuhuXia** [comment]
@adborden Are we planning to move tomcat out of harvesters, into a dedicated bionic instance?

**Comment by adborden** [comment]
Even if tomcat was running on bionic, it would not fix this.

**Comment by FuhuXia** [comment]
Tried on local. Manually removed tomcat6 from Trusty catalog harvester instance and installed tomcat 8.5.56 on it. It is working.

**Comment by mogul** [comment]
Is this one still in progress? (The compliance deadline for it is end of month five more days).

**Comment by FuhuXia** [comment]
Yes, getting a PR ready. Hopefully can go to sandbox tomorrow.

**Comment by FuhuXia** [comment]
Request send to BSP for fgdc2iso EC2 instances.
```
AMI: based on Ubuntu 18.04
instance type: t2.small (help to make better choice? )
name template: catalog-fgdc2iso1p
EBS:
 8GB root /
 8GB logs /var/log
The port 443 should be open internally to all catalog-harvester* instances in the same environment. 

Once the stack is created, please create one instance in DEV and one in PROD.

===========================
This instance will have tomcat 9 installed on it. Majority of  time it is sitting idle. When it is being used, it is accepting data from POST requests on port 443 from catalog harvester instances and return XML document.
```

**Comment by adborden** [comment]
Why t2 and not t3? In terms of memory usage, what have you seen in sandbox?

**Comment by FuhuXia** [comment]
Changed to `t3.small` since the new T3 appears to be more cost effective compared to T2. No supporting data from sandbox environment since sandbox is scaled down to a t2.micro instance, and no regular harvesting activity going on sandbox to collect CPU usage data.

**Comment by FuhuXia** [comment]
EC2 instance deployed on staging. Passed the test except SSL cert: SSL is not working since the new host is not listed as one of the Subject Alternative Names. Created two internal host certificate tickets today for the new certs.

**Comment by FuhuXia** [comment]
Still waiting for hosts certificates. The test performed 2 days ago was not supposed to pass, since we have not made firewall change request to open port 80/443. The test passed because Trend Micro was not installed. Making firewall change request today.

**Comment by FuhuXia** [comment]
Due to AZ restrictions in staging environment, we have to use `t2` instance type. So both fgdc2iso hosts on staging and production are on `t2.small`. Will follow this new host provision [doc](https://github.com/GSA/datagov-deploy/wiki/Provisioning-new-hosts) to mount `/var/log` parition.

**Comment by mogul** [comment]
Blocked waiting on the certificate to be issued

**Comment by mogul** [comment]
The most recent report still reports this problem on catalog-harvester... We'll need to investigate why that's happening, whether due to delayed report or false-positive, etc.
