### ISSUE TITLE
Netsparker reports jquery version 1.12.4 is out-of-date

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1712]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 05/22/2020
**Due date:** 

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

[Netspaker report](https://drive.google.com/drive/u/1/folders/1uvhNO4qIP6wX3CBcoz_iaVeeYEh6_9-H)
Current catalog and inventory are using 1.12.4.
Latest ckan 2.8.2 is using jquery v3.2.1.

**Comment by adborden** [comment]
This is one of the issues driving CKAN 2.8+

**Comment by jbrown-xentity** [comment]
@adborden has anyone tested JQuery 3.x on old catalog? What about the [JQuery Migrate versions](https://code.jquery.com/)? Would those provide any of the security vulnerability patches that we are looking for?

**Comment by adborden** [comment]
I'm not aware of anyone upgrading JQuery 3.x on Catalog 2.3. CKAN is no longer providing support for 2.3, so I doubt (hope :crossed_fingers:) anyone besides us is running 2.3. I'm not familiar with jQuery Migrate.

I think we should punt on this, since we're getting this with CKAN 2.8.

**Comment by jbrown-xentity** [comment]
Waiting for CKAN 2.8 on catalog...

**Comment by mogul** [comment]
Marking `Blocked` as this is waiting on the CKAN 2.8 upgrade, which should resolve it.

**Comment by FuhuXia** [comment]
Catalog and Inventory are running 2.8.7 now, its jquery version is 3.5.1. This issue can be closed.

**Comment by adborden** [comment]
Have we done the analysis to make sure this isn't effecting other applications? Please make sure to check that box above and include any notes.

**Comment by FuhuXia** [comment]
Analysis done and checked. Other apps are all good.
