### ISSUE TITLE
Netsparker: [Possible] BREACH on catalog

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1713]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.f97vuam3wilb)._

**Date of report:** May 22, 2020
**Due date:** August 22, 2020

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
https://drive.google.com/drive/u/1/folders/1uvhNO4qIP6wX3CBcoz_iaVeeYEh6_9-H

**Comment by jbrown-xentity** [comment]
Could this be a false positive similar to #1455?
@FuhuXia could you clarify how you determined #1455 to be a false positive so we can check catalog as well?

**Comment by FuhuXia** [comment]
@jbrown-xentity For [1455](https://github.com/GSA/datagov-deploy/issues/1455), I examined the http response header and body, could not find anything claimed by the report. Asked BSP for clarification, they could not find anything either.

**Comment by jbrown-xentity** [comment]
Noting is a similar false positive, marking as closed.

**Comment by FuhuXia** [comment]
This comes in late, but I edited the original issue description to add bookmark to the google docs.
