### ISSUE TITLE
JSON schema validator not picking up invalid URI entry

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1718]
Record containing this kind of accessURL should not pass validator. accessURL is `{"type": "string","format": "uri"}`. Characters such as `{` and `\"` are not valid as uri string. 
```
{
  "accessURL": "http://hub.arcgis.com/datasets/a73cb_0.geojson?outSR={\"latestWkid\":3857,\"wkid\":102100}",
  "@type": "dcat:Distribution",
  "format": "GeoJSON",
  "mediaType": "application/vnd.geo+json",
  "title": "GeoJSON"
}
```

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
