### ISSUE TITLE
Create default variables for custom roles

### ISSUE THREAD

**Issue by dano-reisys** [GSA/data.gov#173]
Add the default dir + main.yml with default vars to every role that is missing it.

**Comment by JJediny** [comment]
@dano-reisys please status...

- [x] catalog
- [x] crm-web
- [x] datagov-web
- [x] efk-nginx
- [x] efk-stack
- [x] elastalert
- [x] elasticsearch
- [x] fluentd
- [x] hardening
- [x] harvester
- [x] inventory
- [x] jekyll
- [x] jumpbox
- [x] kibana
- [x] secops
- [x] solr
- [x] trendmicro
- [x] web-proxy
- [x] webserver-frontend

Others?
