### ISSUE TITLE
Redis TLS encryption in transit

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1730]
## User Story

In order to meet best practices for secure transmission of data, as a data.gov operator, I want stand-alone redis instances provisioned with TLS encryption in transit.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I run the redis playbook to completion
  WHEN I connect to redis using `openssl s_client`
  THEN I see the data.gov host certificate is used
- [ ] GIVEN  I run the redis playbook to completion
  WHEN I tunnel `redis-cli` through openssl/stunnel
  AND I issue the `AUTH <password>` command
  THEN I receive a successful login (`OK`)

## Background
We currently use redis on catalog in a stand-alone local connection fashion. However, since we want dedicated redis hosts for catalog-next and inventory-next, we want to implement in-transit encryption. In general, all connections should be encrypted for security compliance.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
Within the SSP, any mentions of Redis should be updated. Documentation should include how the TLS is configured and how the unencrypted connections are restricted.

## Sketch
We could use [nginx to proxy TLS connections](https://github.com/Zertz/nginx-redis-ssl) since TLS is only supported in [Redis 6](https://redis.io/topics/encryption).

We can use the existing host TLS certificate/key that is installed on each host.

**Comment by adborden** [comment]
Before digging into the Ansible implementation, we might just want to vet that nginx + Redis is the best path forward.

**Comment by nickumia-reisys** [comment]
Although the implementation is completely different having switched infrastructures, CKAN is talking to Redis with TLS
- https://github.com/GSA/catalog.data.gov/commit/f3abc12f0ac40f4cc3790131eb4449f61a89fd19
  ![image](https://user-images.githubusercontent.com/85196563/216731470-d19edb50-d4e8-4fe4-ac1b-7cd6a9c6738d.png)

Other references:
- [Cloud.gov Redis Docs](https://cloud.gov/docs/services/aws-elasticache)
