### ISSUE TITLE
Remove vestigial request pages

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1732]
We've removed the public-facing helpdesk functionality from data.gov, but there are pages that still refer to it. They should be removed as well. 

## How to reproduce

1. Description of steps to reproduce the issue.

* Visit https://www.data.gov/requests/
* Visit https://www.data.gov/data-request/request-id/635038

## Expected behavior

*  The user is redirected to https://www.data.gov/contact

## Actual behavior

* The user sees pages referencing the CRM request search/view functionality.

## Background
Support request
> The page at https://www.data.gov/requests/ returns no results.
> 
> I was looking for information on request 635038. Previously this was at https://www.data.gov/data-request/request-id/635038.
> 
> Many other US government web sites were linking there, such as
> 
> https://toolkit.climate.gov/crt-search?query=data+requests&topic=9&resource=18&source=1
> 
> and so now those links are broken.
> 
> Is there a new page to find this?

**Comment by hkdctol** [comment]
This one is OBE--closing
