### ISSUE TITLE
Add new datasets to Climate topic

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1734]
## User Story

As a lead for the Climate topic, I want to add additional datasets to the Climate topic list of datasets.

## Acceptance Criteria

- [x] GIVEN datasets have been added to the Climate topic
       THEN we can find that datasets from the spreadsheet provided can be found in the data page for the Climate topic 

## Background
See #913 for background on methodology.
[4June2020_CDI_Retag_Request.xlsx](https://github.com/GSA/datagov-deploy/files/4736732/4June2020_CDI_Retag_Request.xlsx)

**Comment by FuhuXia** [comment]
Climate group and tags were assigned to 289 datasets, using steps described in [wiki](https://github.com/GSA/datagov-deploy/wiki/catalog.data.gov#update-datasets-groups-and-category-tags).

**Comment by hkdctol** [comment]
Informed Climate leads; will move to Done.
