### ISSUE TITLE
 Add New Relic application agents

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#174]
When this story is up for the next sprint: We think it should be broken up into one issue per app.

---
As an application developer, I need my application configured with New Relic so that I can can monitor and alert across all hosts.

## Acceptance criteria
- [ ] New Relic is added as an application dependency to app repo
- [ ] Application hosts report as a single application
- [ ] Only production and staging are enabled with staging labeled separately
- [ ] Configuration lives in application
- [ ] Apdex alerts are configured

## Details

We currently have language-specific playbooks to deploy and configure New Relic for applications. However, this has some deficiencies. The platform has to know details about the application, environments, app names, configuration settings. The platform has to know where to install hooks within the application (wsgi, worker scripts, etc). The platform might install conflicting versions of dependencies, outside of application pinned dependencies. The platform installing New Relic might cause an extra restart, prolonging any service disruption during deploy.

**Comment by kvuppala** [comment]
All front applications now have New Relic applications installed, Solr and Harvester agents are pending.

**Comment by kvuppala** [comment]
@dano-reisys We also need to group instances so each application metrics are consolidated.

**Comment by adborden** [comment]
Updated description.

**Comment by mogul** [comment]
We think this one probably should be broken up into one issue per app.

**Comment by nickumia-reisys** [comment]
This is super old and written for a different infrastructure.  For cloud.gov specifically, NR is installed on catalog, inventory and dashboard.  The only place we haven't implemented this is our Solr deployment, 
- https://github.com/GSA/data.gov/issues/3956
