### ISSUE TITLE
'make requirements' does not generate updated requirements-freeze.txt

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1745]
In inventory-app,  running `make clean build requirements` doesn't update requirements-freeze.txt, even though some package is supposed to be updated. 

## How to reproduce

1. Description of steps to reproduce the issue.
No reliable way to reproduce this. But when it happens, it only happens to an existing project folder. For a new repo clone, `make clean build requirements` always generates correct freeze file.

## Expected behavior

requirements-freeze.txt is updated if there is some package update.

## Actual behavior
requirements-freeze.txt has no change.

**Comment by mogul** [comment]
Icebox'ing for now; will pull this issue back out if we see this happen more often/reliably.
