### ISSUE TITLE
Datajson DOS risk

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1752]
See [HackerOne](https://hackerone.com/reports/885076) for details and triage

**Severity: Medium**

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by mogul** [comment]
We believe this was addressed by recent SSRF hardening efforts... @jbrown-xentity is confirming.
