### ISSUE TITLE
Dashboard Blind Server-Side Request Forgery (SSRF)

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1753]
See [HackerOne](https://hackerone.com/reports/895696) for details

**Date of report:** 
**Severity: Medium**
**Due date:** 

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by mogul** [comment]
I'm planning to sift logs to help verify the list of controller methods that *should* be public, and then flip all the remaining ones to private.

**Comment by mogul** [comment]
Because we've reduced the number of controllers in the app, I was able to do an exhaustive inventory of what methods should be private vs. public, and flip those that needed to be private. I also added a test which ensures that new public methods are not introduced without intent.
