### ISSUE TITLE
Create a second jumpbox in sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1755]
## User Story

As a Data.gov developer, I want a second jumpbox in the sandbox environment so that there is less contention of using sandbox resources when multiple developers are testing.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN a second developer is already using sandbox \
  AND I coordinate in slack which jumpbox is available
  WHEN I run `who` on the jumpbox
  THEN I am the only user

## Background
From our [Retro May 28th, 2020](https://app.retrium.com/team-room/577747ba-781b-4bff-b654-357e305e23d0
):
 > - [ ] Try to relieve the multi-team tension around a single sandbox jumpbox

Usually folks on sandbox are only using one host to test the deploy to. The real contention is on the jumpbox, where we all use the `ubuntu` user and a shared `datagov-deploy` directory.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
N/A

## Sketch
First, add a second jumpbox module to [datagov-infrastructure-live](https://github.com/GSA/datagov-infrastructure-live/blob/master/sandbox/jumpbox.tf). This may involve editing the datagov-infrastructure-modules so that two uniquely named jumpboxes can be created (e.g. they must have unique hostnames).

Jumpbox boostraping is described [here](https://github.com/GSA/datagov-infrastructure-live/blob/master/sandbox/README.md#bootstraping-the-jumpbox) and may require undocumented manual steps to copy the root sandbox SSH key and the [Ansible vault](https://github.com/GSA/datagov-deploy#ansible-vault).

**Comment by adborden** [comment]
FWIW, I often use my own user and SSH key forwarding to avoid contention on the jumpbox. The [Putty configuration](https://github.com/GSA/datagov-deploy/wiki/Horizon-Desktop) describes how to setup putty for SSH key forwarding. There may be one undocumented complication.

**Comment by nickumia-reisys** [comment]
No more jumpbox.  No more sandbox.
- https://github.com/GSA/data.gov/issues/3710
