### ISSUE TITLE
Mock DNS in dashboard tests

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1760]
## User Story

In order to easily test DNS-dependent behavior without relying on external services, the data.gov team wants an easy way to to mock DNS during dashboard tests.

## Acceptance Criteria
- [x]  WHEN I search for xip.io and ip6.name in the dashboard repo \
  THEN there are no results
- [x]  GIVEN I am observing the outgoing network traffic on my workstation \
  WHEN I run tests in the dashboard repo \
  THEN there I no DNS queries

(These need work!)

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This increases the reliability of our tests and increases the range of security-perilous configurations our code can deal with, but doesn't actually change DNS behavior in a deployed environment, so the net effect is nothing there.

## Sketch
Try to use [the Symfony phpunit-bridge extension](https://symfony.com/doc/current/components/phpunit_bridge.html#dns-sensitive-tests) and remove references to xip.io, ip6.name, and xpoc.pro in api_helper_test.php.

**Comment by jbrown-xentity** [comment]
Noted as useful in replacing test case on [Dashboard](https://github.com/GSA/project-open-data-dashboard/blob/master/application/tests/helpers/api_helper_test.php#L149)

**Comment by mogul** [comment]
I'm taking this on as part of resolving https://hackerone.com/reports/1186999
