### ISSUE TITLE
EAC dataset not included in harvest

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1763]
Election Assistance Commission is an agency that had some old datasets in catalog (pre-CKAN, pre-harvest model data.gov). EAC recently created a data.json and posted at https://www.eac.gov/data.json with one dataset. Harvest completed showing 0 errors but did not add the dataset. The data.json had validated when tested against validator on labs.data.gov.

## How to reproduce

Go to catalog, find EAC, and reharvest

## Expected behavior

Should add the dataset named 2018 Election Administration and Voting Survey

## Actual behavior

The harvest added the data.json as a dataset, but not the 2018 dataset within the data.json

Task is to look at https://www.eac.gov/data.json to see if any error can be identified that would cause a 0 error and 0 dataset added result.

**Comment by pjsharpe07** [comment]
Ran again this morning to see the output from the logs. Getting a url error `HTTP Error 404: Not Found` during the gather stage. The gather then crashes and restarts.

**Comment by pjsharpe07** [comment]
Confirmed on several machines and locally that the status code is 404. @hkdctol is going to follow up with EAC to see if they can validate the status code and potential next steps to resolve this.

**Comment by pjsharpe07** [comment]
This [harvest source](https://admin-catalog.data.gov/harvest/admin/eac-data) is functioning successfully.
