### ISSUE TITLE
Dashboard populating without data

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1784]
## How to reproduce

When deploying dashboard to production, the playbook runs without error. However, the [dashboard app](https://labs.data.gov/dashboard/offices/qa) populates without data.

Currently, this behavior is only on production and not staging.

## Expected behavior

[Dashboard](https://labs.data.gov/dashboard/offices/qa) populates with the correct date and has data.

## Actual behavior

Dashboard populates to correct date, but is missing all data.

**Comment by mogul** [comment]
Resolved in the course of investigating #1515
