### ISSUE TITLE
Default Tomcat error and landing page

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1799]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.fxtlqsr3wbco)._

**Date of report:** 06/24/2020
**Severity:** Medium
**Due date:** 09/24/2020

### Brief description
[Nessus Scan](https://docs.google.com/spreadsheets/d/1qgwcVBioneZ_-v6HZDrfGL19PMrsNFdnvOpoPpbIK9Y/edit#gid=929147753)

**Comment by pjsharpe07** [comment]
We have removed tomcat from the current harvesters by running `ansible -m apt -a 'name=tomcat6 state=absent' catalog-harvester-v1`. This should also be a part of #1874.

**Comment by pjsharpe07** [comment]
Submitted an issue to an upstream repo. Will wait for that before internally mitigating. [Issue here](https://github.com/robertdebock/ansible-role-tomcat/issues/20#issuecomment-673465050)

**Comment by chris-macdermaid** [comment]
@adborden @FuhuXia @pjsharpe07 

Status:
- Setting server.info in lib/org/apache/catalina/util/ServerInfo.properties without the version removes the version from being reported. This can be accomplished by creating the dir structure and adding that file or by opening lib/catalin.jar and changing it in ServerInfo.properties and updating the jar.
- The changes that robertdebock made break the playbook
- We haven't tested with the ROOT dir restored. Our putting it there caused errors on startup. -- The AJP Connector is configured with secretRequired="true" but the secret attribute is either null or ""

Next steps?:

- Let robertdebock know the changes he made didn't work and changing the ServerInfo.properties will fix the problem
- Change playbook to not delete the ROOT and files (this will fix the current errors)
- Make the changes to ServerInfo.properties

**Comment by FuhuXia** [comment]
It feels like we don't need ROOT any more if adding the `lib/org/apache/catalina/util/ServerInfo.properties`.

**Comment by chris-macdermaid** [comment]
Run the palybook on sandbox and tested Tomcat isn't displaying the version number.

**Comment by chris-macdermaid** [comment]
PR https://github.com/GSA/datagov-deploy-fgdc2iso/pull/1
