### ISSUE TITLE
Disable display errors in production Dashboard

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1800]
Errors, warnings, and stack traces can sometimes reveal sensitive information and are generally considered a low severity security issue. We should turn off the display of errors in production. Additionally, the error message isn't helpful to users and can create confusion.

https://labs.data.gov/dashboard/validate?schema=federal-v1.1&output=browser&datajson_url=http://0x7f000001:258/unique

![Screenshot from 2020-06-24 09-31-21](https://user-images.githubusercontent.com/509703/85595392-a6528280-b5fd-11ea-99df-4f2c365e5aef.png)

## How to reproduce

1. Find a controller that produces an error or warning, e.g. https://labs.data.gov/dashboard/validate?schema=federal-v1.1&output=browser&datajson_url=http://0x7f000001:258/unique

Or, you can throw an error in a controller as a test.

## Expected behavior

Error is not displayed on the page. Error is captured in the application logs.

## Actual behavior

Error is displayed on the page.

**Comment by jbrown-xentity** [comment]
@adborden what happened here that made the merge automatically close the issue, and how do we avoid that in the future?

**Comment by adborden** [comment]
@pjsharpe07 used the [resolve keyword](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) in his [pull request](https://github.com/GSA/project-open-data-dashboard/pull/287#issue-444939655).

![Screenshot from 2020-07-06 15-44-15](https://user-images.githubusercontent.com/509703/86660523-a9575680-bf9f-11ea-8b32-acbb28577226.png)

**Comment by jbrown-xentity** [comment]
So maybe the right word that isn't included in the keyword list is "address" or "addresses"? As in "Should address [Ticket Number]"?

**Comment by adborden** [comment]
Sure! I use "Part of [issue]" because often there are multiple PRs associated with an issue e.g. PR for ansible role, PR to bump requirements.yml. You can also just "[issue]" because really all you're doing is linking the PR to the issue. Whatever your preference.

**Comment by pjsharpe07** [comment]
Great to know there are some GH keywords that trigger actions!
