### ISSUE TITLE
Intermittent PHP errors failing to find pcntl.so on Dashboard

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1801]
We've seen this issue intermittently and some investigation is warranted. Specifically, the path being searched is `/usr/lib/php/20180731` which is not a standard path. Perhaps it's left over from a PPA install?

![Screenshot from 2020-06-24 09-19-06](https://user-images.githubusercontent.com/509703/85598076-16fa9e80-b600-11ea-9c5c-fb2fb2dad47e.png)

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by pjsharpe07** [comment]
Dig some digging and encountered the following:

![image](https://user-images.githubusercontent.com/38019872/86031275-dbdadf80-b9f2-11ea-8152-9bf2763a05c5.png)

So, the `pcntl` library is installed and enabled, but its searching for it through php's dynamic library sources. More investigation is still needed.

**Comment by pjsharpe07** [comment]
Deployed the changes above to sandbox and confirmed that pcntl is still enabled by running `php -m | grep pcntl` and `php -i | grep pcntl`. 

The pcntl.ini file is not present in `/etc/php/7.3/fpm/conf.d` so it's unlikely to see this issue again.
