### ISSUE TITLE
New dashboard crawls derive their status from the previous crawl

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1804]
The dashboard shows no data for the current milestone.

## How to reproduce

1. Set the crawl_status of the most recent crawl for a given office_id to `final`.
2. Run a crawl for that office, eg `php public/index.php campaign status 49113 datajson`

## Expected behavior

- The dashboard contains a row for that agency (49113 is CFPB) in the current milestone.
- The most recent crawl's `crawl_status` for that ID is `current`.
## Actual behavior

- The dashboard does not contain a row for that agency in the current milestone.
- The most recent crawl's `crawl_status` for that ID is `final`.

### Investigation
It appears that [this line](https://github.com/GSA/project-open-data-dashboard/blob/65f0dd08a9ecfa6d9871011ab664bad50f98abe4/application/models/Campaign_model.php#L2037) is overwriting the passed `$update->crawl_status` of `current` with the state of the row retrieved in the code just above. 

Normally this isn't a problem because the previous row was `current` as well. However, immediately after a milestone ends, the most recent row might be `final`. When that happens, all subsequent crawls are also marked `final`. Since the current milestone is still in progress, `final` rows are ignored, and no data is shown.

Per discussion after reproducing this with @philipashlock, we'll look into fixing it if we see the problem recurs after the finalization of data for the current milestone (June 30th). Otherwise we'll just leave it be.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
