### ISSUE TITLE
Document tmux pairing guidelines

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1806]
## User Story

In order to effectively pair on the jumpboxes, data.gov developer wants a short guide on how to join a tmux session with a pair.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I want to pair on the jumpbox with another developer
  WHEN I look at our docs and follow the listed commands
  THEN I'm able to type along side my pair

## Background
This came up as a retro item https://app.retrium.com/team-room/577747ba-781b-4bff-b654-357e305e23d0

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

None, tmux access is controlled by exisiting controls for accessing the jumpbox through SSH.

## Sketch

@FuhuXia has started on this and will demo in our next Sprint Review.

**Comment by mogul** [comment]
The documentation is [in the wiki](https://github.com/GSA/datagov-deploy/wiki/Team-Collaboration-and-Pair-Programming#tmux) now.
