### ISSUE TITLE
Task: delegate FCS liaison role

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1811]
## User Story

In order to take some responsibilities off of @adborden and allow others to play more active role in infrastructure, @adborden  wants to delegate the FCS liaison role to another devsecops team member.

Responsibilities:
- Act as point of contact with FCS
- Collect any feedback from devsecops to pass on to FCS
- Raise any blocking issues from the team with FCS
- Attend the monthly FCS Customer Enablement Tiger Team (CETT) meeting

## Background
This came up in our [June 25, 2020 retro](https://app.retrium.com/team-room/577747ba-781b-4bff-b654-357e305e23d0).

**Comment by mogul** [comment]
@jbrown-xentity has 🤚 for this role

**Comment by jbrown-xentity** [comment]
[Discussion notes](https://docs.google.com/document/d/1PzCZN2qCT-uzCvhkDMv0LOY1MCEztqD4C57YtxuHV1c/edit)

**Comment by adborden** [comment]
Thanks @jbrown-xentity !
