### ISSUE TITLE
Update playbooks and roles to handle bare variables

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1812]
## User Story

In order to have more reliable, predictable behavior of Ansible, data.gov developer wants the Ansible playbooks and roles updated to [handle bare variables correctly](https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.8.html#bare-variables-in-conditionals).

## Acceptance Criteria
- [ ]  WHEN I grep the environment for `ANSIBLE_CONDITIONAL_BARE_VARS` (`pipenv run sh -c 'env | grep ANSIBLE_CONDITIONAL_BARE_VARS`)
  THEN I see the variable is enabled
- [ ]  GIVEN I install vendored roles with `pipenv run make vendor`
  WHEN I grep the ansible playbooks and roles for `when` conditions (e.g. `grep -r 'when:' ansible/`)
  THEN I see any boolean variables have the `bool` filter applied (`when: is_enabled | bool`)
- [ ] GIVEN an ansible-lint rule exists for conditional bare variables
  WHEN I add a bare variable to a conditional
  AND I forget the `bool` filter
  THEN the linter gives an error

## Background

Bare variables in conditionals look like this:

```yaml
tasks:
  - include_tasks: teardown.yml
    when: teardown

  - include_tasks: provision.yml
    when: not teardown
```

From the [Ansible 2.8 upgrade](https://github.com/GSA/datagov-deploy/issues/1782) the porting guide called out a change to [bare variables in conditionals](https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.8.html#bare-variables-in-conditionals). The change is opt-in for 2.8 and will be forced in Ansible 2.10, so this work becomes a potential blocker for Ansible 2.10.

The reason for the change is that booleans are parsed ambiguously. So besides the Ansible 2.10 driver, addressing this would also improve our playbooks and avoiding "gotchas" when specifying boolean variables on the command line..

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None.

## Sketch
https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.8.html#bare-variables-in-conditionals describes several cases that need to be addressed.

**Comment by nickumia-reisys** [comment]
No more Ansible.  No equivalent issue in cloud.gov deployment pipeline
- https://github.com/GSA/data.gov/issues/3710
