### ISSUE TITLE
Document Snyk O&M process

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1822]
## User Story

In order to stay on top of vulnerabilities, we want a consistent process that people on O&M shift can follow to manage information surfaced by Snyk.

## Acceptance Criteria
- [x] GIVEN I am on the O&M shift for data.gov \
  AND I look at the Snyk dashboard \
  WHEN I see open issues reported \
  THEN I can refer to a process in the wiki that walks me through how to document the status.

## Background
In particular, we're looking for clear guidance about using .snyk files, how this fits into the usual vulnerability-reporting issue process, and how to understand the canonical state (eg what's already being ignored vs what is already in GitHub issues vs what needs triage).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
We intend to stick to our usual process for handling non-public vulnerability info (eg create a GitHub issue and link to a Google Doc for sensitive content). So no changes there.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
Added [Snyk overview notes](https://github.com/GSA/datagov-deploy/wiki/Snyk-configuration-notes), to update [O&M Snyk notes](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) next.
