### ISSUE TITLE
Redirect Project Open Data pages to resources.data.gov pages

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1824]
## User Story

In order to find the most up-to-date information about data.gov and open data, project open data users want project-open-data.cio.gov pages to redirect to resources.data.gov pages.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN I browse to https://project-open-data.cio.gov/
  AND I see the deprecation banner
  WHEN I click "View archived content on GitHub"
  THEN I can see the archived content on a GitHub branch

- [x] WHEN I browse to https://project-open-data.cio.gov/
  THEN I see the deprecation banner
  AND I see the page will redirect in 30 seconds
  AND after 30 seconds I am redirected to https://resources.data.gov/

- [x] WHEN I browse to any schema page e.g. https://project-open-data.cio.gov/v1.1/schema/
  THEN I see the deprecation banner
  AND I see the page will redirect in 30 seconds
  AND I am redirected to https://resources.data.gov/resources/dcat-us/

- [x] GIVEN I browse to an old https://project-open-data.cio.gov/ page
  WHEN I see there is no equivalent content on resources.data.gov
  AND I click browser back button to see the deprecation banner
  THEN I see instructions for emailing datagov@gsa.gov about missing content or to provide feedback

## Background
Since the OPEN Government Data Act was signed into law January 2019, Project Open Data is being sunset. As part of the new law, in June 2019, resources.data.gov was launched which will serve as a successor to Project Open Data. There is no official date for when Project Open Data should be shutdown, but the end of the year seems appropriate.

Now that resources.data.gov relaunched with a new Information Architecture, we should start directing people to resources.data.gov via forced redirects.

The deprecation banner should be updated to link to GitHub for the archived content and possibly provide a link to open a GH issue, or email data.gov to provide feedback on any missing content.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
project-open-data.cio.gov is hosted on GitHub Pages, which does not support 302/301 redirects. Instead we can use the [jekyll-redirect-from plugin](https://github.com/jekyll/jekyll-redirect-from) which uses an [html meta refresh](https://en.wikipedia.org/wiki/Meta_refresh) to perform the redirect in a browser.

This gives us the flexibility to set a default redirect to https://resources.data.gov/ and override it on a page-by-page basis.

**Comment by adborden** [comment]
From @philipashlock: pod.c.g continues to get more traffic than resources.data.gov. The schema pages are still the most popular pages on both pod and resources.data.gov, yet it is not very prominent in the r.d.g Information Architecture or the navigation.

**Comment by adborden** [comment]
We should try to do this work before 8/4, our next meeting with the r.d.g team.

**Comment by FuhuXia** [comment]
For our purpose, it is easier to edit the template than to use/customize jekyll-redirect-from plugin. Thoughts? @adborden

**Comment by adborden** [comment]
Works for me. We're not going to have to maintain this very long. Since it's a global change to all pages, editing the layout sounds like the simplest solution, thanks!
