### ISSUE TITLE
Harvester "Unexpected Errors" in CoRIS FGDC Metadata  harvest source

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1827]
Unexpected SQL errors are causing large numbers of geospatial datasets to not be harvested. Tested on sandbox with various NOAA harvest sources, see [here](https://docs.google.com/spreadsheets/d/1Afgx0nGPcsNu0-nIvhcQ3RRAJkcesaCPdcDqT4fIaBI/edit#gid=0) for various examples. The error logs are extremely basic with no log trace, they are occurring from [here in the code](https://github.com/GSA/ckanext-harvest/blob/datagov/ckanext/harvest/harvesters/base.py#L90). Might need to add stack tracing or debugging to discover the specific data objects that are trying to be committed to evaluate what is occurring for the SQL to fail.

## How to reproduce

1. Reharvest [CoRIS FGDC Metadata](https://catalog.sandbox.datagov.us/harvest/coris-fgdc-metadata/job/last) and see the latest error results on sandbox

## Expected behavior
Harvest completes with normal errors

## Actual behavior
Harvest marks almost all datasets with this "unexpected errors"

**Comment by jbrown-xentity** [comment]
Aaron suggested testing on CKAN-next to see if moving to 2.8 solves the problem

**Comment by chris-macdermaid** [comment]
Ran the harvest on the CKAN 2.8 to see if the errors would be fixed in the new version.  This introduced other errors. I open an issue for the errors: https://github.com/GSA/datagov-deploy/issues/2000

**Comment by chris-macdermaid** [comment]
Ran the harvest in my CKAN 2.8 without errors.

**Comment by chris-macdermaid** [comment]
Was able to get to the root of the unexpected error.  In the metadata record the keyword name is too long. 

sqlalchemy.exc.DataError: (DataError) value too long for type character varying(100)
 'INSERT INTO tag (id, name, vocabulary_id) VALUES (%(id)s, %(name)s, %(vocabulary_id)s)' {'vocabulary_id': None, 'id': u'504f2e2f-a0f6-413b-a501-aee2308f35a2', 'name': u'us doc; noaa; national environmental satellite data and information service; office of satellite data processing and distribution (osdpd)'}

From https://data.noaa.gov/waf/NOAA/coris/native/iso/xml/nodc_0099041_cw_region_meta_v2013.xml
<gmd:keyword>
<gco:CharacterString>
US DOC; NOAA; NATIONAL ENVIRONMENTAL SATELLITE DATA AND INFORMATION SERVICE; OFFICE OF SATELLITE DATA PROCESSING AND DISTRIBUTION (OSDPD)
</gco:CharacterString>
</gmd:keyword>

In CKAN 2.8 the key is truncated so the error doesn't occur.
This is the keyword in 2.8: 'US DOC; NOAA; NATIONAL ENVIRONMENTAL SATELLITE DATA AND INFORMATION SERVICE; OFFICE OF SATELLITE DAT'

**Comment by jbrown-xentity** [comment]
Nice find @chris-macdermaid! I think next steps for this are to raise this to Dana for a cleaner implementation on their side if possible, and then to bring in the relevant changes on CKAN2.8 to get around this issue in the short term... @adborden @hkdctol thoughts?

**Comment by adborden** [comment]
So CKAN has a 100 character limit for the keyword name, and this keyword is 137 characters?

Yeah, that seems reasonable to me. It's not really a good keyword, so having the dataset owner come up with better keywords sounds right...

@chris-macdermaid do you know where the truncation is happening in 2.8 e.g. ckanext-harvest or ckan? I would open a separate bug that the harvest process should generate a warning for the dataset owner when the keyword is too long. It's a breach of data integrity for CKAN to be modifying data like that without notifying the dataset owner.

**Comment by chris-macdermaid** [comment]
Sent email to NOAA. Response was that they have keywords that are longer than 100 characters. Also, discovered that the record in the current prod catalog has the record with the full keyword.

https://catalog.data.gov/dataset/parrotfish-abundance-and-biomass-in-st-croix-from-2001-02-06-to-2016-10-01
"Impacts of fishing on parrotfish grazing in St. Croix –A case study on the ecological impacts of fishery management actions".

This code in ckanext-spatial/ckanext/spatial/harvesters/base.py is truncating the keyword. But something else is changing it before it is inserted in the database which is causing an error. From debug statement, I see the truncated tags. 
https://github.com/GSA/ckanext-spatial/blob/datagov/ckanext/spatial/harvesters/base.py#L208-L212

 if 'tags' in iso_values:
            for tag in iso_values['tags']:
                log.debug('In before tags %s', tag)
                tag = tag[:50] if len(tag) > 50 else tag
                log.debug('In after tags %s', tag)
                tags.append({'name': tag})

**Comment by jbrown-xentity** [comment]
The only differences we can see between sandbox and current production harvest is that the production harvest source is CSW, while sandbox is a WAF (although they use the same import function?).
After further investigation, we need to decide on how to precede, @adborden :

1. Change the CKAN DB to allow for > 100 character limit on tags
1. Remove any tags > 100 character limit (and mark as an error?)
1. Edit the tag to be compliant, be either truncating or splitting on spaces/[gcmd tag types](https://github.com/ioos/catalog-ckan/pull/200/files#diff-877b275fc0912aac9bf7955c4489f4440)

**Comment by adborden** [comment]
Probably worth another [chat](https://gsa-tts.slack.com/archives/C2N85536E/p1597769975493000) on this. My gut is that we should probably just truncate the keywords to 100 characters as a quick fix to get things harvesting. But it depends on where the change is implemented e.g. ckanext-spatial vs ckan core vs ??? and how much technical debt it introduces.

Splitting the keywords would be better, but even then we're losing the hierarchy of the keywords which seems like an imperfect implementation. It's also more work and I suspect more technical debt.

Since the [Global Change Master Directory (GCMD) Keywords](https://earthdata.nasa.gov/earth-observation-data/find-data/gcmd/gcmd-keywords) are hierarchical, we should treat GCMD keywords as a new feature in order to support them properly in CKAN. Would this be a feature request in an existing extension, like ckanext-spatial, or is it a new extension that data.gov would maintain?

**Comment by chris-macdermaid** [comment]
@adborden @jbrown-xentity 
Determined that the keywords get processed a 2nd time in the Geodatagov extension. 
https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/harvesters/base.py#L75-L85

In this extension all tags are getting split on ">" which works for GCMD keywords, but not long keywords without that hierarchy.  So splitting is happening but not truncating.
Adding this would truncate the long keywords:
```
for t in tags:
    tt = t.split('>')
    tt = [t.lower().strip() for t in tt]
    tt = [t.lower().strip(';,') for t in tt]
    tt = [' '.join(t.split())[:100]for t in tt]
new_tags.extend(tt)
```

**Comment by chris-macdermaid** [comment]
Re-harvested CoRIS Native ISO Metadata and CoRIS FGDC Metadata without any errors related to the keyword after making the above change.

**Comment by chris-macdermaid** [comment]
Created PR https://github.com/GSA/ckanext-geodatagov/pull/147 to truncate keywords at 100 characters.
