### ISSUE TITLE
Cannot upload files to WordPress

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1830]
![Screenshot from 2020-07-07 11-23-52](https://user-images.githubusercontent.com/509703/86825618-71561f00-c044-11ea-9bc6-31da2a1b9318.png)

**Work-around** temporarily update the permissions of the uploads directory:
`pipenv run ansible -m file -a 'state=directory owner=ubuntu group=www-data mode=0775 dest=/var/www/datagov/current/web/app/uploads/2020/07' wordpress-web`

## How to reproduce

1. Log in to www.data.gov as admin
1. On the left menu, Media -> Add New
1. Click upload, browse to the file

## Expected behavior

File is uploaded to s3 successfully

## Actual behavior

Upload fails with error "Unable to create directory uploads/2020/07. Is its parent directory writable by the server?"

**Comment by adborden** [comment]
`/var/www/datagov/current/web/app/uploads/2020/07` exists and is owned by ubuntu:ubuntu 0755. It _should_ be writable by www-data, the user of php-fpm. It looks like this directory is created at some point in the ansible playbook, maybe from a `wp` cli command.

**Comment by hkdctol** [comment]
closing as we've left wordpress
