### ISSUE TITLE
Prevent catalog web log rotation from filling disk

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1833]
All four web catalog web instances got low disk space warning at roughly same time nightly, then `/var/log/` partition got 100% full within minutes.

> We agreed to change the logrotate settings to reduce the likelihood of being in this situation (not enough room to rotate) again. (We should also double-check the retention period documented via the SSP and make sure the new settings still meet that requirement.)

**Comment by FuhuXia** [comment]
`/var/log/ckan/ckan.error.log` file size is too big for all four instances. When the spike happens, another big file  `/var/log/ckan/ckan.error.log.1` is being created. Looks like it is due to logrotate activity.

**Comment by mogul** [comment]
Logrotate didn't have enough room available to split files when this happened. The situation was resolved this time by deleting data. 

We agreed to change the logrotate settings to reduce the likelihood of being in this situation (not enough room to rotate) again. (We should also double-check the retention period documented via the SSP and make sure the new settings still meet that requirement.)

**Comment by jbrown-xentity** [comment]
May have to implement in conjunction with #1890. Relevant logrotate options can be found [here](https://github.com/GSA/datagov-deploy/blob/develop/ansible/catalog-web.yml#L50-L64), and our log requirement details are [here](https://docs.google.com/document/d/1MkaYZr6633vobLkYpNZcqPfQTvCUgR4XNahcmeryXgg/edit#heading=h.x4g7k0n6m5it).

**Comment by jbrown-xentity** [comment]
Per documentation and testing today, can reduce log size on average (tested for 5.5 hours today) by 93% by changing log levels to `WARNING` [here](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/catalog/ckan-app/templates/etc_ckan_production.ini.j2#L280-L286). Would still need to implement changes to logrotate as mentioned above, and possibly increase the size of the log partition on all web instances.
