### ISSUE TITLE
CPU alarm for PYCSW Replica database on production

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1844]
Got CPU alarm for PYCSWPostgresRDSDBInstanceReplica1 from Amazon CloudWatch Alarm  "DATAGOV-Production-PYCSWPostgresRDSDBInstanceReplica1CPUAlarm-Z06FU4UL85N" every 20 or 30 mins for most of daytime today. 

Threshold:
- The alarm is in the ALARM state when the metric is GreaterThanThreshold 90.0 for 60 seconds.

Catalog ckan site and /csw endpoint appear to be working fine.

**Comment by FuhuXia** [comment]
The alarm went on for 12 hours then stopped on its own.

**Comment by mogul** [comment]
For future CPU issues with RDS instances, we should bring BSP into the loop and open an incident with them.

**Comment by mogul** [comment]
Closing until we see this happening more.
