### ISSUE TITLE
Update all BSP hosts to use the -v2 root SSH keys

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1847]
## User Story

In order to simplify the SSH configuration and not have to manage a .ssh/config file on the jumpbox, Data.gov operators want all hosts to use a single root SSH key.

## Acceptance Criteria

- [ ] WHEN I ssh into any host in a single environment with the ubuntu user and the root SSH key (`ssh -l ubuntu -i ~/.ssh/datagov-${env}-v2 ${host}`)
  THEN access is granted
- [ ] WHEN I inspect the ~/.ssh/config on the jumpbox
  THEN the only configuration option is StrictHostKeys=no
  AND there is no host-specific configuration

## Background
Each environment (prod, stage, sandbox) is configured with a unique [root SSH key](https://github.com/GSA/datagov-deploy/wiki/Keypair-Rotation#ssh-root-keys). The public key is configured in AWS by BSP. When new instances are created, they are created with only this key. Once our Ansible playbooks run, they ec2 instances then are configured with operator keys as well.

In the past, we managed key rotation by stack, so old keys for trusty are still in use. This meant we need to manage a .ssh/config to specify which hosts use which key. We want to simply this by simply making all hosts (trusty and bionic) use the same root SSH key.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
Update any documentation in the SSP referring to management of SSH keys.

## Sketch
- [ ] Add private key to jumpbox so ubuntu user can login to all other hosts
- [ ] Add v2 key to the authorized_keys file for every host
- [ ] Make sure BSP has latest key in the cloudformation template

**Comment by jbrown-xentity** [comment]
The current work-around for this is detailed [here under the Implementation notes](https://github.com/GSA/datagov-deploy/issues/1835).

**Comment by jbrown-xentity** [comment]
Noted that only instances still using the old key are inventory and catalog trusty instances. Given we are working towards retirement of these systems in favor of catalog-next and inventory-next, we are iceboxing this until the release is done.
At that point, the only work that will need to be done is verifying with BSP the cloudformation template has the latest key file, and the jumpbox `.ssh/config` files are cleaned up.

**Comment by hkdctol** [comment]
closing tickets related to bsp
