### ISSUE TITLE
Geodatagov extension commands not available

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1848]
The standard command `paster geodatagov --help` fails to run. 
There is [a requirement](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/commands.py#L31) on [this ckanext-harvest addition](https://github.com/GSA/ckanext-harvest/commit/8d6baa2389ffa5e10b3ec4503c9de91e0afc5428#diff-1ac7dce9b514a9ad5d660b46ba33d166), but the docker system for geodatagov [pulls in the upstream ckanext-harvest](https://github.com/GSA/ckanext-geodatagov/blob/master/ckan-docker/Dockerfile#L19). This immediately breaks the command script, and no commands can be run.

Should consider not only fix, but tests to cover this script for any similar future issues.

## How to reproduce

1. Spin up Docker environment for [ckanext-geodatagov](https://github.com/GSA/ckanext-geodatagov)
2. SSH onto the machine using [the docs](https://github.com/GSA/ckanext-geodatagov#build-environment)
3. Run `paster geodatagov --help` from the `ckanext-geodatagov` folder

## Expected behavior
Help output to be displayed

## Actual behavior
Error occurs and script quits

**Comment by jbrown-xentity** [comment]
@avdata99 @thejuliekramer I'm doing some analysis of all the CKAN extension jobs (#499) and I noted that the customization for the `harvest_source_info` table is really unnecessary. Essentially all of the logic is used to make sure that the harvest cleanup commands are only run if the harvester is running, but there are much simpler ways to make sure we don't clear out "stuck" jobs that haven't even been run (like looking at the timestamp of the harvest_run log file, for instance).
The use can be seen [here on geodatagov](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/commands.py#L663-L685), and [here on ckanext-harvest](https://github.com/GSA/ckanext-harvest/blob/datagov/ckanext/harvest/model/__init__.py#L41).

I say we remove this logic in geodatagov (maybe add a TODO for future check to make sure harvester is running) and then we should be able to use this script in catalog-next...

**Comment by avdata99** [comment]
I propose to remove the cleanup task @jbrown-xentity: https://github.com/GSA/ckanext-geodatagov/pull/159
Let me know if you think this is a good idea. We already have _timeouts_ in the new harvester, this function also mark as finished stuck jobs.

**Comment by avdata99** [comment]
To QA in sandbox:
 - Open the terminal
 - Run `sudo ckan --plugin=ckanext-geodatagov geodatagov --help`

**Comment by adborden** [comment]
Looks good to me.

```
$ docker-compose exec ckan paster --plugin=ckanext-geodatagov geodatagov --help
Usage: paster geodatagov [options]
    Commands:

        paster geodatagov import-harvest-source <harvest_source_data> -c <config>
        paster geodatagov import-orgs <data> -c <config>
        paster geodatagov post-install-dbinit -c <config>
        paster geodatagov import-dms -c <config>
        paster geodatagov import-doi -c <config>
        paster geodatagov clean-deleted -c <config>
        paster geodatagov combine-feeds -c <config>
        paster geodatagov harvest-job-cleanup -c <config>
        paster geodatagov export-csv -c <config>



Options:
  -h, --help            show this help message and exit
  -v, --verbose
  -c CONFIG, --config=CONFIG
                        Config file to use.
  -f FILE_PATH, --file=FILE_PATH
                        File to dump results to (if needed)
```


Was also able to run the jsonl-export job in local development.
