### ISSUE TITLE
can't log into to sandbox catalog

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1858]
User can't log into https://catalog.sandbox.datagov.us/. At HTTPS login screen, after form submission, the server sends user to HTTP and gives username password wrong error. At this point, if user changes the HTTP to HTTPS on the address bar, it actually shows user is logged in.

## How to reproduce

Go to https://catalog.sandbox.datagov.us/user/login, fill in correct credentials, click login button. 

## Expected behavior

User should be able to log in, and stay on HTTPS.

## Actual behavior

User sees an error page. URL changes to HTTP.

**Comment by adborden** [comment]
Need to pick this up to aid in debugging saml issues in sandbox.
