### ISSUE TITLE
Harvest of Restore-the-gulf Error

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1861]
Error Summary

Document Error
Element '{http://www.opengis.net/gml}TimePeriod': This element is not expected. Expected is one of ( {http://www.opengis.net/gml/3.2}AbstractTimePrimitive, {http://www.opengis.net/gml/3.2}TimeInstant, {http://www.opengis.net/gml/3.2}TimePeriod, {http://www.opengis.net/gml/3.2}TimeNode, {http://www.opengis.net/gml/3.2}TimeEdge ).
Element '{http://www.isotc211.org/2005/gmd}CI_Date': Missing child element(s). Expected is ( {http://www.isotc211.org/2005/gmd}dateType ).

Error details are [here](https://catalog.data.gov/harvest/restore-the-gulf/job/3895f220-8041-4a14-bced-707174694418)

## How to reproduce

1. Re-harvest the Restore-the-gulf CSW service

## Expected behavior

Successful harvest

## Actual behavior
Error in harvest

**Comment by adborden** [comment]
@jbrown-xentity is this a bug? It looks like the harvest owner needs to fix their metadata, is there something else going on?

**Comment by pjsharpe07** [comment]
Did some initial digging of the most recent [harvest job](https://admin-catalog.data.gov/harvest/restore-the-gulf/job/3895f220-8041-4a14-bced-707174694418) and found that the [remote content](https://stage.restorethegulf.gov/merlin/srv/eng/csw?OUTPUTFORMAT=application%2Fxml&SERVICE=CSW&OUTPUTSCHEMA=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&REQUEST=GetRecordById&VERSION=2.0.2&ID=f405be72-f9d0-4525-b6d6-886633d7bced) is different than the [local content](https://admin-catalog.data.gov/harvest/object/484c683c-14fc-47d9-84db-df742370aaf1). For example, one error mentions `TimePeriod` which you can find on the local content, but not on the remote content. Something is probably happening in the gather-stage, but more investigation is needed.

**Comment by FuhuXia** [comment]
There is one dataset in the source, and this dataset fails to validate against schema profile `ISO19139 XSD Schema (NGDC)`. For instance, each element of `<gmd:CI_Citation>` needs to have one or more `<gmd:date>` as defined in the [citation.xsd](https://github.com/GSA/ckanext-spatial/blob/datagov/ckanext/spatial/validation/xml/iso19139ngdc/schema/gmd/citation.xsd#L49). But one of the `CI_Citation`s in this dataset, titled `Federal Award Identification Number (FAIN)`, contains invalid `<gmd:date>` as in:
```
<gmd:CI_Citation>
  <gmd:title>
    <gco:CharacterString>Federal Award Identification Number (FAIN)</gco:CharacterString>
  </gmd:title>
  <gmd:date gco:nilReason="inapplicable">
    <gmd:CI_Date>
      <gmd:date/>
    </gmd:CI_Date>
  </gmd:date>
</gmd:CI_Citation>
```
It appears there are other violations as well like this one. Any of them will fail the validation.
