### ISSUE TITLE
Clear Tomcat

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1874]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.4asxy5y8h7o3)._

**Date of report: 7/12/2020** 
**Severity: Medium**
**Due date: 10/12/2020** 

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by pjsharpe07** [comment]
Received confirmation from ISSO that this is no longer an issue
