### ISSUE TITLE
Slow USGS harvesting

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1879]
One of USGS harvesting source Harvested from [Original Product Resolution (OPR) Source Digital Elevation Models (DEMs) - USGS National Map](https://catalog.data.gov/harvest/79036357-a26a-4bd9-892b-f2ae110322c3) is harvesting at very slow rate. Usually the fetching rate is 1 package created per second for other harvest source. This harvest source is fetching at 1 package created every 6 seconds. So it is 6 times slower. History shows it takes about 4 days for a job of this harvest source to finish.

This harvest source is a WAF collection FGDC type source on a monthly schedule. 

## How to reproduce
Kick off a harvest of this specific source

## What we expect to happen
The harvest completes within 24 hours

## What we see happen instead
The harvest takes up to 4 days

**Comment by FuhuXia** [comment]
When this job started, we noticed slight increase CPU usage on Harvester instance and Solr master. But 2 solr slaves had noticeable CPU usage bump, and their solr service crashed once each during the process. User also complain difficulty to open any harvest source page. Harvest nightly report shows high number of harvesting jobs are running (i.e. waiting in the queue).

![Screenshot 2020-07-15 16 16 49](https://user-images.githubusercontent.com/1392461/87594986-d2709900-c6bb-11ea-9545-b1f791080813.png)

**Comment by pjsharpe07** [comment]
We kicked off a new harvest today - a little before 5:00pm EST. We'll review the results Monday morning.

**Comment by pjsharpe07** [comment]
Pretty close. Looks like it took ~32 hours to complete...

| id                                   | created             | gather_started      | gather_finished     | finished           | time_ran | source_id                            | status   |
|--------------------------------------|---------------------|---------------------|---------------------|--------------------|----------|--------------------------------------|----------|
| b4d6dbf2-63f0-4723-bcac-f7dbb83c9d97 | 2020-07-31 20:54:51 | 2020-07-31 21:00:03 | 2020-07-31 22:29:25 | 2020-08-02 4:50:46 | 31:55:55| 79036357-a26a-4bd9-892b-f2ae110322c3 | Finished |

**Comment by pjsharpe07** [comment]
Kicked off another harvest with job id `1f685e03-e076-47dd-9391-80b2bddc6992`

Find our two harvest stat timings in [our google drive](https://docs.google.com/spreadsheets/d/1Lw9MTW5HXUkJ0A1xrkpQLwavQvQKUQGpeIR1-zxRTBk/edit#gid=0)

**Comment by jbrown-xentity** [comment]
Gather still running, and alert fired for high memory usage on catalog-harvester1p. Will continue to monitor.

**Comment by pjsharpe07** [comment]
The last harvest attempt finished with one dataset in a bad state, but finished all others in ~15 hours. We will try one more harvest later this week. If it's below the 24 hour threshold we can move this to done.

**Comment by pjsharpe07** [comment]
Kicked off new job yesterday afternoon ~4PM EST.

Job still running today. After some investigation, noticed that the `fetch` process was running slowly and suspected that not all `fetch` jobs were running even though their status was up. Restarted all fetch jobs and this made the process significantly faster.

Going to create a ticket to address the above.

**Comment by mogul** [comment]
We should check whether we're seeing the same performance under catalog 2.8+ before we dive back into this.

**Comment by mogul** [comment]
Icebox'ing in the catalog-next epic as a signal that we should re-evaluate this after the upgrade to see if it's still a problem.

**Comment by FuhuXia** [comment]
Same thing observed on USGS harvest source https://admin-catalog-next.data.gov/harvest/about/usgs-combined-vector-downloadable-data-collection on the new catalog. On local the harvesting was at speed of 1 dataset per second. On catalog-next production it was 1 dataset every 8 seconds.
