### ISSUE TITLE
Add package.json to strategy.data.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1882]
## User Story

As a [strategy.data.gov](strategy.data.gov) admin, I want to have all libraries documented in a package.json file so that I can scan for out of date dependencies and easily update to the latest version.

## Acceptance Criteria
- [ ] GIVEN a user views the [strategy GitHub repo](https://github.com/GSA/data-strategy)
  WHEN a library is out of date
  THEN a system manager can update the library directly

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
See [resources.data.gov repo](https://github.com/GSA/resources.data.gov) as an example.

**Comment by nickumia-reisys** [comment]
This was implemented some time in the past.  The most recent update work,
- https://github.com/GSA/data.gov/issues/4143
