### ISSUE TITLE
USWDS 2.8 not compatible with resources.data.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1883]
In trying to update USWDS to 2.8.0 on resources.data.gov, running build gives the following error:

```Error: `-"2px"` is not a valid `margin` token. You should correct this. Standard `margin` tokens:  neg-1px, neg-2px, neg-05, neg-1, neg-105, neg-2, neg-205, neg-3, 1px, 2px, 05, 1, 105, 2, 205, 3, 4, 5, 6, 7, 8, 9, 10, 15, 05em, 1em, 105em, 2em, 0```

in the following files:

- on line 93 of node_modules/uswds/dist/scss/core/_notifications.scss
- from line 21 of node_modules/uswds/dist/scss/packages/_required.scss
- from line 5 of node_modules/uswds/dist/scss/uswds.scss
- from line 31 of pages/_scss/styles.scss

## How to reproduce

1. Run [setup steps for resources.data.gov](https://github.com/GSA/resources.data.gov#setup), making sure uswds is marked as ^ 2.8.0 after `npm install` command (uninstall and re-install if not)
2. Note error that occurs at the build stage.

## Expected behavior

Clean tests run

## Actual behavior

Failure to build

**Comment by adborden** [comment]
@jbrown-xentity do you have a branch with uswds 2.8 so folks can easily pick this up?

**Comment by jbrown-xentity** [comment]
Sure, [branch feature/uswds_2_8](https://github.com/GSA/resources.data.gov/tree/feature/uswds_2_8)

**Comment by jbrown-xentity** [comment]
Also this [Snyk PR](https://github.com/GSA/resources.data.gov/pull/244)

**Comment by FuhuXia** [comment]
USWDS 2.9 is released. Showing different error on build stage.

```
[13:29:21] 'build-sass' errored after 307 ms
[13:29:21] Error in plugin "gulp-sass"
Message:
    node_modules/uswds/dist/scss/core/_functions.scss
Error: Neither "blue-60v" nor "base-lighter" can be AA contrast links and hovers on a "base-darkest" background.
        on line 1949 of node_modules/uswds/dist/scss/core/_functions.scss, in function `get-link-tokens-from-bg`
        from line 7 of node_modules/uswds/dist/scss/core/mixins/_set-link-from-bg.scss, in mixin `set-link-from-bg`
        from line 85 of node_modules/uswds/dist/scss/components/_identifier.scss
        from line 26 of node_modules/uswds/dist/scss/packages/_uswds-components.scss
        from line 13 of node_modules/uswds/dist/scss/uswds.scss
        from line 31 of pages/_scss/styles.scss
>>     @error 'Neither "#{$preferred-link-color}" nor "#{$fallback-link-color}"
   ----^
```

**Comment by pjsharpe07** [comment]
If this above PR gets merged then I'll create a new issue to upgrade to 2.9 w/Fuhu's copied stdout errors included.
