### ISSUE TITLE
Inventory 2.8 rollout

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1886]
## User Story

In order to reduce the operational overhead of hosting inventory.data.gov and keeping it secure, the team wants to redeploy the service using a modern, supported version of CKAN on a supported OS.

## Acceptance Criteria
- [ ] WHEN I curl https://inventory.data.gov/api/action/status_show \
  THEN I see "ckan_version: 2.8.x" in the result

## Background
Python 2 is EOL and CKAN 2.3/2/5 are really hard to work with.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
The new deployment is pushed out in the same way, no service interactions are added or removed, all related services are accessed locally on the hosts, etc. We expect this change to not impact the security of the deployment itself. We do expect this change to result in addressing various bugs and _potential_ security problems, and to make it easier to address any new security findings without the friction of an ancient codebase.

## Sketch
- Announce scheduled downtime to inventory users
- Rollout plan: #2248
- Previous DB migrations were completed in one afternoon

**Comment by FuhuXia** [comment]
Blocked by [Inventory user table house cleaning](https://github.com/GSA/datagov-deploy/issues/2758) and [Inventory authentication extension](https://github.com/GSA/datagov-deploy/issues/2575).
