### ISSUE TITLE
CKAN logging level change

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1890]
## User Story

As an O&M data.gov developer, I want the correct logging on the various CKAN logs so that I can quickly see the errors that have occurred and not be overwhelmed with debug and info logs.

## Acceptance Criteria

- [x] GIVEN the [audit log is run for catalog and inventory](https://github.com/GSA/datagov-deploy/wiki/Operation-and-Maintenance-Responsibilities#au-6-log-auditing)
  WHEN an error has occurred in the last week
  THEN that error is seen in the log review

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, logs are stored on the secure server.

## Sketch
Relevant deployment settings can be found [here](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/catalog/ckan-app/templates/etc_ckan_production.ini.j2#L265-L295)

**Comment by mogul** [comment]
@pjsharpe07 please remember to check and verify that this is working properly during your next audit log review.

**Comment by pjsharpe07** [comment]
The error logs looked like we were hoping. Moved this one to `done`
