### ISSUE TITLE
Delete Department of Education content from inventory.data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1893]
## User Story

As Data.gov PMO, want to delete obsolete content from Department of Education organization in inventory.data.gov. 

## Acceptance Criteria

- [x] Download the datasets and resources, in case they are needed in the future
- [x] Provide list of datasets to Department of Education
- [x] Delete content from inventory.data.gov for Department of Education after confirmation with Dept of Ed. 

## Background
There was a HackerOne issue upon discovery of an old dataset hosted on inventory.data.gov with a publicly accessible URL. Department of Education confirmed they are not using inventory.data.gov. Department of Education would like the list of old datasets on inventory.data.gov before we delete all the content.

**Comment by jbrown-xentity** [comment]
We might be able to just use the data.json endpoint as the "list"? So just download their inventory from the UI? We would still have to download all their resources manually though... Maybe we could write a quick script to do it? It's about 100 data files to download. @hkdctol could this be needed for other departments/organizations in the future?

**Comment by hkdctol** [comment]
I think Education has been using something else for their data.json for a while. Not sure they need full metadata maybe just the list of what's in inventory. I could see other agencies wanting to get all their files that are resources.

**Comment by jbrown-xentity** [comment]
The data has been fully downloaded. The [zip file](https://drive.google.com/file/d/1uTZc2JRG6NX6Ndw9MH1axIf6PyAF7YhY/view?usp=sharing) contains the full list of packages/datasets, metadata, and resource metadata. It also contains the raw data itself, along with the log file verifying that all data downloaded successfully. This should be sent to the Department of Education contact at this point I believe @hkdctol...
Next steps are to document/sanitize the code and save it as a gist, then remove the datasets via the API and another script...

**Comment by jbrown-xentity** [comment]
[Public Gist of script run to download data](https://gist.github.com/jbrown-xentity/3e31c4afb4354cdfb845f2a008c718d2)

**Comment by jbrown-xentity** [comment]
[Public Gist of script to remove data](https://gist.github.com/jbrown-xentity/06e2035688c4be56d994866ccc429919)

Data removed for department of education

**Comment by jbrown-xentity** [comment]
Purge did not work, to look at command line options/tools.

**Comment by jbrown-xentity** [comment]
Created new ticket for [purging data](https://github.com/GSA/datagov-deploy/issues/2271). This data is no longer accessible by the public, marking as done.
