### ISSUE TITLE
data.json harvesting fails after project-open-data.cio.gov is redirected

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1895]
After https://project-open-data.cio.gov is redirected to https://resources.data.gov, data.json harvesting start to fail. It only affects some datasets in some data.json sources. Debugging shows that jsonschema validator tries to reach url https://project-open-data.cio.gov/v1.1/schema/organization.json and raised an exception when it is redirected to resources's homepage.

## How to reproduce

harvest GSA's data.json source https://open.gsa.gov/data.json

## Expected behavior

harvest should complete

## Actual behavior

harvest is stuck. errors on fetch log.

**Comment by FuhuXia** [comment]
Debugging shows that it only affects dataset that has 3+ level of organizations, as in this one:
```
...
"license": "https://creativecommons.org/publicdomain/zero/1.0/",
"publisher": {
	"@type": "org:Organization",
	"name": "Data.gov",
	"subOrganizationOf": {
		"@type": "org:Organization",
		"name": "Technology Transformation Service",
		"subOrganizationOf": {
			"@type": "org:Organization",
			"name": "General Services Administration"
		}
	}
},
"accrualPeriodicity": "R/P1M",
...
```
On the 3rd level of `org:Organization`, validator is going out and reading url https://project-open-data.cio.gov/v1.1/schema/organization.json.

**Comment by FuhuXia** [comment]
POD schema files have been moved to new location at:

https://resources.data.gov/schemas/dcat-us/v1.1/schema/catalog.json
https://resources.data.gov/schemas/dcat-us/v1.1/schema/catalog.jsonld
https://resources.data.gov/schemas/dcat-us/v1.1/schema/dataset.json
https://resources.data.gov/schemas/dcat-us/v1.1/schema/distribution.json
https://resources.data.gov/schemas/dcat-us/v1.1/schema/organization.json
https://resources.data.gov/schemas/dcat-us/v1.1/schema/vcard.json
But in each json content, the `id` field still points to old domain project-open-data.cio.gov url. 

In a mock harvesting environment it shows that if we can update the `id` with new location, the issue is resolved. But this means a mandatory schema content change or version update for user using this POD schema. I feel a more elegant solution is doing point-to-point redirecting rather than the who domain redirecting. If we can keep url such as https://project-open-data.cio.gov/v1.1/schema/organization.json live and permanently redirecting to https://resources.data.gov/schemas/dcat-us/v1.1/schema/organization.json, then both schema can co-exist.

**Comment by avdata99** [comment]
@FuhuXia @adborden 
[This PR](https://github.com/GSA/ckanext-datajson/pull/70) could help.
It's not easy to fix because the new resources continue referring to old resources
For example, inside https://resources.data.gov/schemas/dcat-us/v1.1/schema/organization.json we still call to old URL
We need to update these resources to point new links

**Comment by adborden** [comment]
While we work out the longer-term fix with pod.c.g, I think there is a short term fix is to create a complete [jsonschema](https://json-schema.org/) based on the v1.1 schema and use that locally within the ckan extension.

Right now, we have a partial implementation of this. Our [embedded schema in ckanext-datajson](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/pod_schema/federal-v1.1/catalog.json#L52) uses [`$ref` to link to different entity definitions](https://github.com/GSA/resources.data.gov/blob/develop/pages/schemas/dcat-us/v1.1/schema/catalog.json#L52). Those references need to be fetched at runtime (probably during each harvest). Instead, we should be able to define the entire schema in a single file without references to p.c.g or r.d.g and pass that single schema to the jsonschema validator. Then we wouldn't have to worry about third-party systems (r.d.g or p.c.g) being online during harvesting.

Ultimately, we want to resolve the issue with p.c.g but we don't want to rush to an incomplete or short-sighted solution, so for this issue let's aim for a local fix.

**Comment by FuhuXia** [comment]
Good point to stick to localized schema file. As a matter of fact we are using localized an all-in-one [dataset schema file](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/pod_schema/federal-v1.1/dataset.json). This pod.c.g redirecting issue made us aware that there is bug in the `ckanext-datajson`/`jsonschema module` that the verifier is reading external url during harvesting. Here is my other findings:

1. The [catalog.json](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/pod_schema/federal-v1.1/catalog.json#L52) you mentioned with external json $ref is never used. The actual schema file `jsonschema` uses is the `dataset.json` file with every definition [locally defined](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/pod_schema/federal-v1.1/dataset.json#L475).

2. My test result suggests it is a bug in `jsonschema` when it deals with recursive self referenced definition as defined in [`subOrganizationOf`](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/pod_schema/federal-v1.1/dataset.json#L722-L724). 

3. If we don't use recursive $ref, the issue is gone. I spelt out the `organization` definition within `subOrganizationOf` and tested on local, it works. But this means we need to manually embed the repeated definition several levels. The most complex organization I noticed so far is in GSA data.json file, it has three levels, example given upstairs.

3. If we use `"$ref": "file:/path/to/organization.json"` instead of `"$ref": "#"` in [`subOrganizationOf`](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/pod_schema/federal-v1.1/dataset.json#L724), the issue is gone too. But this means we may have to reveal the full path of the schema file to public.

**Comment by FuhuXia** [comment]
GitHub issue created on [jsonschema repo](https://github.com/Julian/jsonschema/issues/710) for this reading-external-url-with-local-definition issue.

**Comment by adborden** [comment]
project-open-data.cio.gov has been restored, so this is no longer an urgent issue, but still an issue.

**Comment by willson-chen** [comment]
@adborden @FuhuXia Maybe this PR https://github.com/Julian/jsonschema/pull/717 could solve the problem.
