### ISSUE TITLE
Update data.gov/about for Evidence Act and OPEN Government Data Act

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1904]
## User Story

In order to communicate the mission, goals, and applicability of data.gov, Agency users want the about page updated to better reflect how data.gov might serve them for open and non-open datasets.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
Received an inquiry about why non-public datasets should be cataloged on data.gov. Was looking for general information explaining the federal government's strategy on leveraging data as an asset and how data.gov connects with that.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
@hkdctol we are triaging this one... Is this something you can work on soon? If so, please move it to the `Product Backlog`. Otherwise just leave it in the `Icebox`.
