### ISSUE TITLE
Update Ansible Role Pip

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1908]
## User Story

As a data.gov developer, I want the latest Ansible Role for pip so that no security patches are missed.

## Acceptance Criteria
- [ ] GIVEN the latest ansible role for pip is used
  WHEN data.gov services are deployed/tested
  THEN all services work as expected

## Background
Current [new release](https://github.com/geerlingguy/ansible-role-pip/releases/tag/2.0.0) requires changes to setup the various systems.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
We would need to specify the pip_package and pip_executable ([documentation here](https://github.com/geerlingguy/ansible-role-pip/tree/2.0.0#role-variables)) if we are using python 2, which we will be for the foreseeable future for CKAN.

**Comment by nickumia-reisys** [comment]
No more Ansible,
- https://github.com/GSA/data.gov/issues/3710
