### ISSUE TITLE
Geospatial full metadata not available on some datasets

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1940]
Geospatial document does not have full metadata view or download link available on the dataset page.

The root cause will have something to do with the harvest information missing, all harvest data is missing from the full metadata for this dataset page.

See email from Lynda on July 28th for request, and respond to that thread when ticket is resolved.

## How to reproduce

1. Go to [this dataset](https://catalog.data.gov/dataset/tiger-line-shapefile-2019-nation-u-s-current-metropolitan-division-national)
2. See no full metadata download or view link

## Expected behavior

Full metadata links are seen

## Actual behavior

Links are missing

**Comment by mogul** [comment]
@FuhuXia suggests that a re-index may resolve this. We're planning to do that sooner so that we can understand if more work will be required later.

**Comment by chris-macdermaid** [comment]
Re-indexing didn't resolve the issue.  There is only one dataset in this harvest source. Dataset displays correctly on sandbox. Next step, clear source and re-harvest.

**Comment by chris-macdermaid** [comment]
I cleared the harvest source and re-harvested. That corrected the issue.

**Comment by chris-macdermaid** [comment]
Responded to Lynda's July 28th email to let her know the record was fixed.

**Comment by mogul** [comment]
Noting from sprint review: We still aren't sure of the root cause here, so this situation may recur or need deeper investigation in future, and re-harvesting has a side effect of churning stats that we're not crazy about.
