### ISSUE TITLE
Create a site metrics dataset on inventory

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1941]
## User Story

In order to create a simpler crawl system to replace the dashboard crawl, datagov developers want a dataset created on inventory that contains all the necessary crawl information .

## Acceptance Criteria
- [ ] GIVEN I access inventory.data.gov/datasets/catalog-organization-statistics
  AND crawl.py has been completed and accepted
  THEN I can download a created static csv file
  AND I can use the dataStore API to access the most up-to-date data

**Note:** The name of the dataset *...catalog-organization-statistics* could be changed

## Background
We had a [research ticket](https://github.com/GSA/datagov-deploy/issues/1757) around using the API to create a dashboard alternative via csv. We have a basic script to collect data, but it needs to be edited/corrected to gather the correct information.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
This work should require the use of an api key which should not be exposed to the public.

## Sketch
- [ ] Complete crawl.py to collect all necessary information
- [ ] Run crawl.py and save csv locally
- [ ] Create a dataset on inventory.data.gov with this csv and any/all relevant metadata
- [ ] Confirm access via datapusher API

**Comment by hkdctol** [comment]
Closing this overtaken by other approaches
