### ISSUE TITLE
Crawl Update is Automated on inventory.data.gov

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1942]
## User Story

In order to create a simpler crawl system to replace dashboard crawls, datagov developers want the inventory dataset to run as scheduled, persist to datastore, and updated on inventory.data.gov

## Acceptance Criteria
- [ ] crawl code lives on geodatagov and runs automatically via supervisor (or an equivalent secure system that has access to the web and can safely store an API key)
- [ ] CSV is successfully created, added to inventory dataset as scheduled and accessible/discoverable on catalog.data.gov
- [ ] Discuss and create any new tickets using this API for a UI to view this information

**Note:** This last step will be to establish work for dashboard 2.0

## Background
We had a [research ticket](https://github.com/GSA/datagov-deploy/issues/1757) around using the API to create a dashboard alternative via csv. We have a basic script to collect data, but it needs to be edited/corrected to gather the correct information.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
This work should require the use of an api key which should not be exposed to the public.

## Sketch
crawl.py was created standalone because geodatagov was in a bad state for development. If still in a bad state, consider alternatives with team.

**Comment by jbrown-xentity** [comment]
Since we are doing this as an inventory dataset, this becomes much simpler. We don't even need to put this in a ckan extension. We can take the code as is, add another python script that sends the exported csv file to inventory (updating a previously created dataset, something like "Catalog data metrics"). CKAN2.9 on Py3 let's you create API tokens that can be rotated, changed, or revoked whenever we want, so we can use the inventory API.

**Comment by jbrown-xentity** [comment]
After looking at the code further, we may want to consider refactoring into [ckanapi](https://github.com/ckan/ckanapi#ckanapi-python-module) library, may simplify the approach (at least the api calls)...

**Comment by jbrown-xentity** [comment]
We won't be taking this on; we are approaching this with the CKAN report framework.
