### ISSUE TITLE
Harvest source page responds slowly during harvests

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1955]
We've noted that during a harvest, the harvest source page responds very slowly.

## How to reproduce

1. Kick off a long-running harvest such as the USGS job
2. Load a series of harvest pages
    - https://catalog.data.gov/harvest/usgs-historical-topographic-maps
    - https://catalog.data.gov/harvest/79036357-a26a-4bd9-892b-f2ae110322c3

## Expected behavior

The harvest job detail pages respond quickly. Some large harvest source default pages and harvest jobs list pages may also load slowly.

## Actual behavior

The harvest job detail pages respond slowly enough that users think something is wrong

**Comment by adborden** [comment]
We found this when debugging https://github.com/GSA/datagov-deploy/issues/1879
