### ISSUE TITLE
Limit harvest-run job to 24 hours

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1958]
## User Story

In order to give harvest-run headroom to complete it's tasks without holding up the queue indefinitely, Data.gov operators want a timeout set on harvest-run.

## Acceptance Criteria
- [ ] GIVEN a long running harvest-run job\*
  WHEN harvest-run has been running for more than 24 hours
  THEN the job is gracefully killed
  _AND datagov@ is notified_

\* We don't have a concrete conditions that would cause harvest-run to take longer than usual.

## Background
https://gsa-tts.slack.com/archives/CDCL978KZ/p1596127376406400

As part of QA'ing https://github.com/gsa/catalog.data.gov/issues/70, I was waiting a while for the re-harvest to start.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch

For  dashboard, we use the [timeout command](https://www.man7.org/linux/man-pages/man1/timeout.1.html) to kill the job after 24 hours.

We currently don't have a great solution around notifications.

**Comment by avdata99** [comment]
Probably done with #1946

**Comment by nickumia-reisys** [comment]
This was completed before, but then recently increased to 72 hours,
- https://github.com/GSA/data.gov/issues/4058
