### ISSUE TITLE
harvest-run can run over 24 hours with no output when email is misconfigured

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1959]
On sandbox, we have postfix configured with an invalid relay (the GSA SMTP relay).

We see this in the postfix logs.
```
==> /var/log/mail.log <==
Jul 30 19:13:28 catalog-harvester-next1tf postfix/master[992]: warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling
Jul 30 19:14:28 catalog-harvester-next1tf postfix/smtpd[9702]: fatal: in parameter smtpd_relay_restrictions or smtpd_recipient_restrictions, specify at least one working instance of: reject_unauth_destination, defer_unauth_destination, reject, defer, defer_if_permit or check_relay_domains
Jul 30 19:14:29 catalog-harvester-next1tf postfix/master[992]: warning: process /usr/lib/postfix/sbin/smtpd pid 9702 exit status 1
```

https://gsa-tts.slack.com/archives/CDCL978KZ/p1596127376406400

## How to reproduce

1. Configure postfix with invalid relay, or unset `smtpd_recipient_restrictions` in /etc/postfix/main.cf
1. `sudo service postfix restart`
1. `sudo supervisorctl start harvest-run`

## Expected behavior

harvest-run completes within a few minutes (or at most an hour under most circumstances).

## Actual behavior

harvest-run hangs in smtplib

**Comment by adborden** [comment]
The strange thing is that the postfix error has been around since we created sandbox. I'm not sure why it's only become an issue now.

**Comment by mogul** [comment]
@kimwdavidson it sounds like this is affecting your team's work too... Want to move it onto your board?
