### ISSUE TITLE
Ansible does not restart/reload gunicorn when ckan configuration changes for inventory.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1962]
## How to reproduce

1. Edit https://github.com/GSA/datagov-deploy/blob/master/ansible/roles/software/ckan/inventory/templates/etc/ckan/production.ini
1. Deploy inventory to sandbox
1. supervisorctl status

## Expected behavior

Gunicorn is restarted/reloaded.

## Actual behavior

Last build was an hour ago, but gunicorn is still running.

$ sudo supervisorctl status
beaker-cache-cleanup             STOPPED    Not started
gunicorn-web-app                 RUNNING    pid 30164, uptime 2 days, 11:00:44

**Comment by adborden** [comment]
https://github.com/GSA/datagov-deploy/pull/1923#pullrequestreview-456219102 We should add the supervisor reload handler to this task.

**Comment by mogul** [comment]
@jbrown-xentity says this may have just been fixed in release 20200806...

**Comment by jbrown-xentity** [comment]
Fix can be seen [here](https://github.com/GSA/datagov-deploy/pull/1995)
