### ISSUE TITLE
Create a catalog view for Older Americans initiative

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1964]
## User Story

As Data.gov PMO, I want to respond to an OMB/OSTP initiative, seeking a catalog view of datasets they have identified as relevant to an initiative on Older Americans.

## Acceptance Criteria

- [x] GIVEN the list of Data.gov datasets identified by the OMB OSTP initiative leads (attached), THEN we can provide a page view of the datasets, ~~in the order provided in the spreadsheet~~.
- [x] Create page view in sandbox so that OMB OSTP contacts can view
- [x] if they proceed, confirm that we will provide page view in production data.gov with a desired URL that redirects to the page view
[DatasetCompendium_DataGovProject_7_30_v.4.xlsx](https://github.com/GSA/datagov-deploy/files/5007660/DatasetCompendium_DataGovProject_7_30_v.4.xlsx)

## Background
OMB/OSTP has an initiative on issues relevant to Older Americans. They are not certain which route they will pursue on an online presence for the initiative, but they are interested in having a catalog page view, perhaps with a relevant URL such as catalog.data.gov/older-adults-health-data

We have done similar work in #1734 and background on [wiki](https://github.com/GSA/datagov-deploy/wiki/catalog.data.gov#update-datasets-groups-and-category-tags)

### Sketch
The following PR's were needed to test/implement the styling associated with adding an icon. We also needed to create a binary font file, see [icomoon comment](https://github.com/GSA/datagov-deploy/issues/1964#issuecomment-677812187) for details.

- Catalog
    - https://github.com/GSA/ckanext-datagovtheme/pull/46
    - https://github.com/GSA/catalog-app/pull/155
- Wordpress
    - https://github.com/GSA/data.gov/pull/897 (icon in css) & https://github.com/GSA/data.gov/pull/900 (icon in images folder for catalog)
    - https://github.com/GSA/datagov-wp-boilerplate/pull/52 & https://github.com/GSA/datagov-wp-boilerplate/pull/53
    - [Should not be necessary in future] https://github.com/GSA/datagov-deploy-wordpress/pull/16 (to test branch)
    - [Should not be necessary in future] https://github.com/GSA/datagov-deploy/pull/2005

**Comment by jbrown-xentity** [comment]
So this cannot be replicated on sandbox as currently built for a number of reasons. 

First is the datasets don't exist on sandbox. Current plan is to pull in 1 harvest source for an example of what a production deployment would look like, but not the full data list. 

Second, the options at the top of the page are built into our `dynamic_menu`, which still all points to production system and is hardcoded for data.gov endpoint. We can handle this 1 of 2 ways:

1. Setup dynamic menu on each environment and point to the relevant menu at the environment level (sandbox, staging, production)
2. Ignore this and link testers directly to the newly created page.

Thoughts on necessity of having it be part of dropdown in topics list @hkdctol? And thoughts on having a subset of the datasets listed in the spreadsheet on the example page?

**Comment by hkdctol** [comment]
No harm in creating a page directly on production. They can look at it and if they like it we'll set up a redirect from a URL they like.

**Comment by hkdctol** [comment]
I don't anticipate a repeated need for this so would minimize effort.

**Comment by jbrown-xentity** [comment]
So create the page view and group but don't update the dropdown topics list until it is approved? Publicly viewable but not discoverable?

**Comment by hkdctol** [comment]
Yep. Thanks.

**Comment by hkdctol** [comment]
Sounds good--I've forwarded the info to the requesters.

**Comment by hkdctol** [comment]
@jbrown-xentity I forwarded you email with a few edits from requesters on description.

**Comment by jbrown-xentity** [comment]
@hkdctol Title and description updated, good to reply...

**Comment by jbrown-xentity** [comment]
@hkdctol The about page is updated to latest description, and I have [isolated](https://www.data.gov/wp/wp-admin/nav-menus.php?action=edit&menu=33830) where the topic category is changed. Last steps are to pick an icon to represent this latest topic, similar to the other ones... Any icons will need to be added to wordpress and ckanext-theme for catalog...

**Comment by hkdctol** [comment]
@jbrown-xentity see email re icon selection

**Comment by hkdctol** [comment]
The initiative leads sent an updated dataset list @jbrown-xentity I forwarded in email

**Comment by jbrown-xentity** [comment]
Icon added to styling and viewable at [www.data.gov](https://data.gov) (under topics dropdown), will eventually propagate to catalog.data.gov. [Dataset list](https://catalog.data.gov/group/older-adults-health-data) up to date, in the future we would like datasets in [the following format](https://github.com/GSA/ckan-php-manager#assign-groups-and-category-tags-to-datasets) to streamline the update process...
@hkdctol

**Comment by jbrown-xentity** [comment]
The cache needed to be reset. It should be there now @hkdctol

**Comment by hkdctol** [comment]
I see it. There's one more email - they changed the About description. That should be it.

**Comment by jbrown-xentity** [comment]
Updated @hkdctol : https://catalog.data.gov/group/older-adults-health-data

**Comment by hkdctol** [comment]
@jbrown-xentity can the logo be also added to the catalog page itself https://catalog.data.gov/group/older-adults-health-data

**Comment by jbrown-xentity** [comment]
That can be setup, give me a few hours...

**Comment by jbrown-xentity** [comment]
@hkdctol the rollout is finalizing, but I did confirm the icon does show up as expected, and the list of PR's is added to the description for future bread crumbs on these changes in the future...
![image](https://user-images.githubusercontent.com/26980513/90076073-13100200-dcbc-11ea-9afd-a4662108ba8e.png)

**Comment by jbrown-xentity** [comment]
[Icomoon](https://icomoon.io/) is a tool that was used to edit the data.gov font files that contain the icons on the menu. Simply load the current svg file, add any necessary icons by adding other svg's, then download the font version of the system. Replace the values in the `data.gov` repo at `roots-nextdatagov/assets/fonts/datagov-icons.svg`, and the `ckanext-datagovtheme` repo at `ckanext/datagovtheme/fanstatic_library/fonts/datagov-icons.svg` with the downloaded files with the original file names. See description for list of PR's as an example.
