### ISSUE TITLE
Fresh catalog-web instances sees Error '/etc/ckan/saml2/attributemaps'

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1968]
Ran site.yml playbook on a freshly provisioned ubuntu trusty instance on staging. It gave this error when at task `assert app is up`:
```
OSError: [Errno 2] No such file or directory: '/etc/ckan/saml2/attributemaps'
```

Workaround is creating this directory manually and copying content from other web instance.

**Comment by adborden** [comment]
🤔  I wonder attributemaps was accidentally removed in the saml2 refactor.

**Comment by adborden** [comment]
Ah, I think https://github.com/GSA/datagov-deploy/blob/fdcfae7508fc3388620eaf24d45a6f7bc6f35b33/ansible/roles/software/ckan/catalog/ckan-app/tasks/saml2.yml#L18-L21 is copying the files to the wrong directory.

**Comment by adborden** [comment]
Tripping over this when trying to test in sandbox.
