### ISSUE TITLE
Catalog CKAN gives 404 when clearing facet terms under organization

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1972]
Under an organization, when clicking the link in the main body to clear any facet term, Catalog CKAN leads to a 404 page. 
For example, in the image below, when click the "**geospatial X**" link, the page should go to `https://catalog.data.gov/organization/gsa-gov`, but it actually goes to `https://catalog.data.gov/group/gsa-gov` and it is a 404.

![Screenshot 2020-08-03 16 14 16](https://user-images.githubusercontent.com/1392461/89223633-1cef8200-d5a5-11ea-9eb3-41895337acca.png)

## How to reproduce

1. Go to https://catalog.data.gov/organization/gsa-gov
2. Click **geospatial** on the left under Dataset Type facet filter.
3. Click "**geospatial X**" link in the page body.

## Expected behavior

It should clears the filter and go back to GSA organization page

## Actual behavior

It goes to https://catalog.data.gov/group/gsa-gov and gives '404 Not Found'.

**Comment by mogul** [comment]
This appears to be a bug in the geodatagov extension.

**Comment by jbrown-xentity** [comment]
Fixed upstream:
https://github.com/ckan/ckan/blob/master/ckan/controllers/group.py#L285-L289

[Example (catalog-next) of bug working](https://catalog-next.sandbox.datagov.us/organization/fe75ed93-9c93-4c56-bc02-11ab228d1abd?tags=nara)
