### ISSUE TITLE
Datajson harvest source `Validation Schema` is not being reflected properly in UI or harvests

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1974]
### How to reproduce
1. Set up a new datajson harvest source, choose `Non-Federal` as Validation Schema. Save.

### Expected behavior
1. The source should show `Federal`. 

### Actual behavior
1. The source shows `Non-Federal`. 

---
### How to reproduce

1. Harvest some datasets with a `Federal` Validation Schema

### Expected behavior

1. The datasets harvested should all be marked `Federal`

### Actual behavior
1. Datasets harvested are all marked as `Non-Federal` datasets.

**Comment by jbrown-xentity** [comment]
The UI bug is fixed in the above PR to geodatagov.
The bugs are **not** related as I previously hoped, [CDC data](https://admin-catalog.data.gov/harvest/edit/https-data-cdc-gov-data-json) is recently harvested as non-federal but the DB shows the default federal flag in the config. Still not sure how that is possible...

**Comment by jbrown-xentity** [comment]
CDC data is fixed. The banner at the top of a dataset is not related to the dataset itself, but to the organization ([see code in the theme for details](https://github.com/GSA/ckanext-datagovtheme/blob/master/ckanext/datagovtheme/templates/package/read_base.html#L28-L34)). 

Changed [CDC Org settings](https://admin-catalog.data.gov/organization/edit/centers-for-disease-control-and-prevention) to set the flag `organization_type` to be `Federal Government`, and all CDC datasets are now Federal and no banner is displayed. 

This was tested on staging and is currently live on production. @hkdctol let me know if there are any other organizations that need this flag set...
