### ISSUE TITLE
SDG Remediations cause incompatible dependencies versions

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1975]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.o3ia64d4a3bx)._

**Date of report:** 08/04/2020
**Severity:** High
**Due date:** 09/04/2020

### Brief description
[Google Doc](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.o3ia64d4a3bx)

[Snyk-bot PR](https://github.com/GSA/sdg-indicators-usa/pull/1007)

**Comment by pjsharpe07** [comment]
Looks like there's another [snyk-bot PR](https://github.com/GSA/sdg-indicators-usa/pull/1009/files) that's passing now...

**Comment by jbrown-xentity** [comment]
Latest tests and notes in [doc discussion](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.vz6tl5rmhlex)
