### ISSUE TITLE
AIDE is installed but not configured correctly when launching new host

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1982]
On staging, and maybe other environments, after launching a new host you will see emails come through with subject `Daily AIDE report for localhost` and body similar to:

![image.png](https://images.zenhubusercontent.com/5e1cbcd08dced94b250ef061/9480bac5-e986-4c1f-b788-c3acb317eee0)

## How to reproduce

Launch a new instance and run playbooks.

You should see emails show-up daily that look like the ones above.

## Expected behavior
These daily emails do not show up.

## Actual behavior
The emails show up

## Sketch
In the past, we might have manually uninstalled aide and/or simply removed it from the cron-file. Some potential steps could be:

- [ ] identify how aide is installed and configured
- [ ] remove/mitigate this via ansible playbooks (probably common)

**Comment by adborden** [comment]
👍  I suggest we add tasks to the common playbook to remove AIDE.

**Comment by pjsharpe07** [comment]
Running `dpkg -s aide` shows it's installed on catalog and inventory hosts on staging and production.

**Comment by adborden** [comment]
Maybe I just removed the cron file then.
