### ISSUE TITLE
DNS Outage - Incident Response

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1983]
On 08/04 we initiated an incident because of a DNS outage.

The [2020/08/04 incident response document](https://docs.google.com/document/d/1LA_CF1RK7CanqTbolcymJoIEasN2ywiuAMx4BTPzUJc/edit#) will have notes and several useful links under the [references heading](https://docs.google.com/document/d/1LA_CF1RK7CanqTbolcymJoIEasN2ywiuAMx4BTPzUJc/edit#heading=h.xhmjie3lrzxi)

### How to repro and triage

dig `NS data.gov` then you can trace route each server for example `dig @dns5.gsa.gov data.gov`

**Comment by mogul** [comment]
Closing as the document captures the timeline and discussion, and references all further action to be taken.
