### ISSUE TITLE
Add DNS monitoring and documentation

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1984]
## User Story

As a data.gov operator, I want DNS monitoring and alerting. This came up as a result of [this incident](https://docs.google.com/document/d/1LA_CF1RK7CanqTbolcymJoIEasN2ywiuAMx4BTPzUJc/edit)

## Acceptance Criteria
- [ ] GIVEN we experience a DNS outage
  THEN the data.gov team is alerted
 AND there are documented steps to resolve/triage
  
## Background
We experienced a DNS outage via opendns on 08/04. We did not receive any alerts.

## Sketch
- [ ] Contact New Relic to see if this is a feature they offer
- [ ] Implement on NR or investigate alternatives

**Comment by jbrown-xentity** [comment]
I believe New Relic would alert to site outage if DNS was having a failure. I believe this can be closed.
