### ISSUE TITLE
CSW harvest sources silently fails when it encounters errors

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1992]
Related to [Multi#356](https://github.com/GSA/datagov-ckan-multi/issues/356)

CSW harvest sources do not show errors properly. Examples
 - https://catalog-next.sandbox.datagov.us/harvest/admin/nc-onemap-csw 
   - using http://data.nconemap.com/geoportal/csw?Request=GetCapabilities&Service=CSW&Version=2.0.2 as URL
 - https://catalog-next.sandbox.datagov.us/harvest/admin/restore-the-gulf
   - using https://stage.restorethegulf.gov/merlin/srv/eng/csw?request=GetCapabilities&service=CSW&version=2.0.2 as URL

## How to reproduce

Add CSW sources and execute harvest jobs

## Expected behaviour

The job should be marked as finished and show information about the error

## Actual behaviour

Failing silently

Error for Gulf source: `Error contacting the CSW server: ('The read operation timed out',)`
Error for NC Onemap: `Error contacting the CSW server: Opening and ending tag mismatch: meta line 29 and head, line 40, column 10 (line 40)`

Both errors are not informed in the dashboard job.

**Comment by jbrown-xentity** [comment]
We don't plan to continue supporting CSW harvest sources, closing.
