### ISSUE TITLE
Remove develop branch and update readme for static sites

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2001]
## User Story

As a data.gov team member, I want a simpler way to update our static sites so that confusion is decreased from team members about how and when these sites get updated.

## Acceptance Criteria
- [x] GIVEN I visit any of our static sites github repos
  THEN I see clear documentation about how branches relate to environments
  AND the default branch is `main`
- [x] GIVEN I visit  our [release wiki](https://github.com/GSA/datagov-deploy/wiki/Releases)
  THEN I see no static site update steps for the release process

## Background
There's some confusion among the data.gov team and other teams about how our static sites should be updated. There's also some inconsistencies such as one repo's workflow is `feature` -> `develop` -> `master` where others only have `staging` and `master` sites with no clear workflow.

Note this is a small friction we encounter each time we do a release.

See the example for our [data-strategy repo](https://github.com/GSA/data-strategy/pull/231/files).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch
- [x] communicate with partners
- [x] update each static sites' readme
- [x] rename `master` to `main`
- [x] update Federalist settings; `main` as the live site, `develop` for demo site
- [x] remove develop branch from branch protection rules
- [x] update the release wiki

#### Static Sites Remaining
- [x] [GSA/data-strategy](https://github.com/GSA/data-strategy)	
- [x] [GSA/resources.data.gov](https://github.com/GSA/resources.data.gov)	
- [x] [GSA/us-data-federation](https://github.com/GSA/us-data-federation)	
- [x] [GSA/sdg-indicators-usa](https://github.com/GSA/sdg-indicators-usa)

**Comment by adborden** [comment]
Sent emails to collaborators, will wait a few days before merging these.
