### ISSUE TITLE
Research 2d: determine options for a local SAML2 IdP for local development

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2022]
## User Story

In order to include a standalone SAML2 IdP that can be used in local development for any SAML2 configuration or development work, data.gov developers to know which IdP solution is the most effective (low effort, that supports common workflows) for local development.

## Tasks
- [ ] Identify what standalone IdP solutions for local development
- [ ] Write up user stories for adding an IdP solution to local development

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
We've used these for service provider implementations, but they also support IdP implementations:
- [SimpleSAMLPHP](https://simplesamlphp.org/)
- [pysaml2](https://pysaml2.readthedocs.io/en/latest/index.html)
- Others?

Which solutions work out of the box? What additional configuration, code, or infrastructure would be required to run these for local development? In sandbox?

**Comment by jbrown-xentity** [comment]
We are able to get around this, and changes to IdP are rare. Closing.
