### ISSUE TITLE
Task: Update Terraform for AWS 3.x provider

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2032]
AWS Terraform provider 3.x was released and includes some [upgrade instructions](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade).

## Tasks
- [x] work through the upgrade guide to address any changes for datagov-infrastructure-modules and datagov-infrastructure-live

## Background

Example [build log from CI](https://app.circleci.com/jobs/github/GSA/datagov-infrastructure-live/1987).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Generally updating an officially-supported provider is relatively safe, but this is a major version change. We need to carefully stick to the upgrade guide to ensure we're not missing any changes that might introduce a vulnerability based on config we wrote for 2.x.

## Sketch

- [ ] Carefully review [the upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade) for resource and data types that we use.

**Comment by mogul** [comment]
I'm having to take this on now in order to have Terraform [generate DS records in Route53, which is only possible since v3.31.0 of the AWS provider was released in March](https://github.com/hashicorp/terraform-provider-aws/issues/17040#issuecomment-791047328).
