### ISSUE TITLE
Share fgdc2iso service in sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2034]
## User Story

In order to minimize resources in sandbox and match staging/production environments, data.gov operators want the fgdc2iso service in sandbox to be shared across different catalog instances (catalog and catalog-next).

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I run terraform 
  WHEN I review the AWS console for sandbox
  THEN I see a single instance matching fgdc2iso

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Minimal, reduces the number of instances to manage and keeps better parity with staging/production.

## Sketch
Pull [fgdc2iso](https://github.com/GSA/datagov-infrastructure-modules/blob/master/modules/catalog/main.tf#L206) into its own Terraform module so that we can declare a single instance to be shared between catalog and catalog-next. Security groups should allow for different catalog instances to connect.

**Comment by jbrown-xentity** [comment]
Overcome by https://github.com/GSA/datagov-deploy/issues/2917, closing.
