### ISSUE TITLE
PHP permissions error on captha

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#204]
@alex-perfilov-reisys cc @dano-reisys @FuhuXia seems like only 1 of 2 errors im seeing in APM, confirm?

Count | Transaction name and error class | Error message | First Occurrence | Last Occurrence
-- | -- | -- | -- | --
2 | /app/plugins/si-captcha-for-wordpress/captcha/securimage_show.phpE_WARNING | fopen(/var/www/datagov/new/web/app/plugins/si-captcha-for-wordpress/captcha/cache/wsP7bW4aGRtofwiw.php): failed to open stream: Permission denied

**Comment by hkdctol** [comment]
Closing old tickets
