### ISSUE TITLE
Python/SQL CKAN errors 

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#205]
@dano-reisys @FuhuXia cc @alex-perfilov-reisys @kvuppala (add john too)...

Count | Transaction name and error class | Error message | First Occurrence | Last Occurrence
-- | -- | -- | -- | --
100 | /ckan.controllers.error:ErrorController.documentsqlalchemy.exc:InternalError | (InternalError) cannot execute INSERT in a read-only transaction 'INSERT INTO beaker_cache (namespace, accessed, created, data) VALUES (%(namespace)s, %(accessed)s, %(created)s, %(data)s) RETURNING beaker_cache.id' {'namespace': '960ed31a77ed4f61b33d0477f8ff27df', 'data': <psycopg2._psycopg.Binary object at 0x7f63027e7440>, 'accessed': datetime.datetime(2017, 7, 14, 4, 16, 49, 607264), 'created': datetime.datetime(2017, 7, 14, 4, 16, 49, 607273)} | 11:46 PM | 12:17 AM
12 | /_trackingsqlalchemy.exc:InternalError | (InternalError) cannot execute INSERT in a read-only transaction 'INSERT INTO tracking_raw\n                     (user_key, url, tracking_type)\n                     VALUES (%s, %s, %s)' ('837f2ff25c0f735a40329cb535db50d348f5b4b9', u'/dataset/physical-profile-data-collected-from-ctd-casts-from-the-kaimimoana-in-the-equatorial-pacific-du99592', u'page') | 11:46 PM | 12:17 AM

**Comment by kvuppala** [comment]
@JJediny Are the errors on live site or on a different instance?

**Comment by JJediny** [comment]
only reporting errors from prod instances

**Comment by kvuppala** [comment]
On the front end all tracking requests seem to be going to admin which is a writable instance, will look more into the issue

**Comment by adborden** [comment]
As part of the pycsw debugging, I'm seeing the beaker insert error on every request to `/harvest/object/*`. Not sure what triggers the session save that doesn't happen in other ckan requests, but since these are read-only instances, the request fails when the session information can't be written to db.

As a work-around I'm using the in-memory session backend, but this won't work with multiple instances, since it isn't shared.

**Comment by adborden** [comment]
beaker_cache is different than beaker sessions. The cache is used for caching the view, so the only way to fix this is to disable caching, or allow writes to the database.

**Comment by nickumia-reisys** [comment]
Errors are too old on an ancient deprecated system and no longer relevant to Cloud.gov.
