### ISSUE TITLE
SNYK vulnerability found in inventory-app

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2068]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.5xnmwj4ghipl)._

**Date of report:** 08/09/2020
**Severity:** Medium
**Due date:** 11/09/2020

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
[Google doc](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.5xnmwj4ghipl)

**Comment by pjsharpe07** [comment]
There is no mention of this vulnerability in the affected application. This was checked again today and has already been added as an exception in our [snyk file](https://github.com/GSA/inventory-app/commit/6ad5f6a7a80f34dcae2c1a01d91a37a2d72c3305). Moving this ticket to done
