### ISSUE TITLE
Geodatagov harvest puts different values for tags in SOLR and database

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2071]
In debugging #1827, we found that the database needs the tag values to be truncated to 100 characters. However, this truncation was never implemented/designed for SOLR, and this extension uses the [before_index](https://github.com/GSA/ckanext-geodatagov/blob/fcbd05423d755a2f253bc57b3cdc46bf2e54d5d5/ckanext/geodatagov/plugins.py#L482-L486) hook to do special parsing for SOLR that is not included in the DB. This could cause the DB-SOLR sync job to change or break values.

There may be a more modern/robust way to do this.

## How to reproduce

1. Run a harvest with the following [ISO file](https://data.noaa.gov/waf/NOAA/coris/native/iso/xml/nodc_0099041_cw_region_meta_v2013.xml)

1. See values different in the DB and in SOLR

## Expected behavior

The DB and SOLR have the same tag values

## Actual behavior

DB and SOLR have different values

**Comment by mogul** [comment]
@kimwdavidson can y'all take a look at the way this is implemented and help us understand if there's a better way to accomplish this before we fix the existing method in-situ?

**Comment by mogul** [comment]
@kimwdavidson 🔔

**Comment by mogul** [comment]
We'll reconsider this when we're evaluating which forks to keep or move off of.
