### ISSUE TITLE
WAF harvest parses input multiple times

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2072]
We know through detailed logging that the WAF harvest source type runs through the parsing of the ISO xml twice, [here](https://github.com/GSA/ckanext-spatial/blob/datagov/ckanext/spatial/harvesters/base.py#L514) and [here](https://github.com/GSA/ckanext-spatial/blob/datagov/ckanext/spatial/harvesters/base.py#L560). This is fixed upstream, only called [once](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/harvesters/base.py#L559). Discovered while testing #1827

We also know this parsing is overwritten somehow by the geodatagov extension and it is parsing these values in it's [own get_package_dict function](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/harvesters/base.py#L71). A deep understanding is needed of the CKAN framework to understand why/how all 3 functions will fire for a single harvest record, and how the geodatagov extension is having the final determination of the values being parsed.

## How to reproduce

1. Harvest any WAF, and add debug statements to the logger

1. Review the logs for duplicate harvest name entries

## Expected behavior

Metadata XML is parsed once in a clearly defined function

## Actual behavior

Spaghetti code

**Comment by mogul** [comment]
We're expecting this will be addressed by the rollout of the upstream CKAN version, so we're Icebox'ing it for now. We're including it in the overall CKAN-next epic as a reminder to check that it's been resolved when closing out that epic.

**Comment by avdata99** [comment]
At catalog-next we use _upstream_ version in which [we don't have this problem](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/harvesters/base.py#L559-L569) proposed to close.

**Comment by avdata99** [comment]
The GeoDataGov extension [overrides the `get_package_dict` function](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/harvesters/base.py#L84:L84). This run just one time in _catalog-next_ with spatial upstream version, I just tested.
Should we remove from _catalog-next_ board?
