### ISSUE TITLE
Bump ansible-lint version

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2076]
## User Story

As a datagov developer, I want the most recent version of anisble-lint to be used.

## Acceptance Criteria
- [ ] GIVEN I look at datagov-deploy's Pipfile
  THEN I see at least ansible-lint version >= 4.3.1 

## Background
Ansible-lint 4.3.0 had some bugs, but this looks like 4.3.1 has this resolved. We now have a decent amount of linting errors in our playbooks. See the [circle ci linting errors](https://app.circleci.com/pipelines/github/GSA/datagov-deploy/867/workflows/8ca26e8c-a227-4b38-b401-f7f3abc428fd/jobs/9928) for the [dependabot PR](https://github.com/GSA/datagov-deploy/pull/2074).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch
- [ ] Up the version in the Pipfile
- [ ] Resolve linting errors as needed

**Comment by nickumia-reisys** [comment]
No more Ansible,
- https://github.com/GSA/data.gov/issues/3710
