### ISSUE TITLE
SSH agent connection within a tmux session is severed after disconnecting from the host

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2080]
When re-joining a tmux session, you might find that you can no longer connect over SSH to hosts (pubkey denied error).

When you initialize a tmux session, the environment is copied to the tmux session, which includes SSH agent connection information. When you disconnect from the host and re-connect, you might have new SSH agent settings. When you connect to tmux, instead of updating the environment variables, the existing tmux session variables which includes the old/stale SSH agent information.

There's a one-line config change for tmux to list environment variables to update when rejoining the tmux session.

**work-around** After you re-connect, you can just create a new session and that will inherit your update SSH_AUTH_SOCK (`tmux`).

## How to reproduce

1. SSH into jumpbox
1. Create a tmux session (`tmux`)
1. Disconnect from the tmux session (ctrl+b d), then disconnect from the jumpbox (ctrl+d)
1. Reconnect to the jumpbox
1. `env | grep SSH_AUTH_SOCK` (make a note of the path)
1. Re-join the tmux session (`tmux attach`)
1. `env | grep SSH_AUTH_SOCK`

## Expected behavior

SSH_AUTH_SOCK in the tmux session matches what is outside the tmux session.

## Actual behavior

SSH_AUTH_SOCK is different, so the tmux session no longer has a working SSH agent socket and cannot be used to connect to other hosts over SSH.

**Comment by adborden** [comment]
We can add the tmux configuration to datagov-deploy-common. I believe the tmux configuration to add to tmux.conf.
```
set -g update-environment "SSH_AUTH_SOCK SSH_CONNECTION"
```

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
