### ISSUE TITLE
catalog / redirects to HTTP

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2083]
We should be redirecting to HTTPS to avoid the extra redirect request.

## How to reproduce

1. `curl -v https://catalog.data.gov/ > /dev/null`

## Expected behavior

302 https://catalog.data.gov/dataset

## Actual behavior

302 http://catalog.data.gov/dataset ->
301 https://catalog.data.gov/dataset

**Comment by adborden** [comment]
I think this also affects inventory, but haven't confirmed.

**Comment by mogul** [comment]
This may be resolved with CKAN-next. Will check on it when we are upgraded!

**Comment by avdata99** [comment]
The catalog-next in the sandbox already include the expected redirection

<pre>
$ curl -v catalog-next.sandbox.datagov.us > /dev/null

> GET / HTTP/1.1
> Host: catalog-next.sandbox.datagov.us
> User-Agent: curl/7.68.0
> Accept: */*
<b>< HTTP/1.1 302 Found</b>

< Date: Mon, 09 Nov 2020 10:51:48 GMT
< Content-Type: text/plain; charset=utf8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: gunicorn/19.10.0
<b>< Location: https://catalog-next.sandbox.datagov.us/dataset</b>
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST, PUT, GET, DELETE, OPTIONS
< Access-Control-Allow-Headers: X-CKAN-API-KEY, Authorization, Content-Type
< Referrer-Policy: origin
</pre>

I'm not able to found where this behaviour is defined but it seems to work in the sandbox

New production is not ready

<pre>
curl -v catalog-next.data.gov > /dev/null
> GET / HTTP/1.1
> Host: catalog-next.data.gov
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
<b>< HTTP/1.1 302 Found : Moved Temporarily</b>
<b>< Location: https://catalog-next.data.gov/</b>
< Connection: close
< Cache-Control: no-cache
< Pragma: no-cache
</pre>

**Comment by adborden** [comment]
~I think this needs to be fixed within the CloudFront distribution or at the Netscaler level.~

**Comment by adborden** [comment]
It looks like this was causing issues on admin-catalog.data.gov and we had to revert https://github.com/GSA/datagov-deploy/pull/2429

**Comment by adborden** [comment]
Doesn't seem like this is working:
```
$ curl -v https://catalog.data.gov/ > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 99.84.238.68...
* TCP_NODELAY set
* Connected to catalog.data.gov (99.84.238.68) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [222 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [100 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4411 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=District of Columbia; L=Washington; O=General Services Administration (GSA); OU=Technology Transformation Service; CN=data.gov
*  start date: Mar 11 00:00:00 2020 GMT
*  expire date: Apr 23 12:00:00 2021 GMT
*  subjectAltName: host "catalog.data.gov" matched cert's "catalog.data.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fd32d008200)
> GET / HTTP/2
> Host: catalog.data.gov
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 302
< content-type: text/html; charset=iso-8859-1
< location: http://catalog.data.gov/dataset
< date: Fri, 13 Nov 2020 19:20:32 GMT
< server: Apache
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< set-cookie: citrix_ns_id=uAd/CKUVWSNhezxZdNyt/FVtReg0001; Domain=.data.gov; Path=/; HttpOnly
< x-cache-control-orig:
< cache-control: max-age=0, must-revalidate, private
< x-expires-orig: None
< x-cache: Miss from cloudfront
< via: 1.1 8f141d9c16ee1224e3bb57860513ca97.cloudfront.net (CloudFront)
< x-amz-cf-pop: SFO5-C3
< x-amz-cf-id: uN1iqlM9eIXnU02QZLiXS_sax51PbB-ILUP4u44QjnsgBoS7mbsmog==
<
{ [215 bytes data]
100   215    0   215    0     0    569      0 --:--:-- --:--:-- --:--:--   570
* Connection #0 to host catalog.data.gov left intact
```

**Comment by avdata99** [comment]
Do we need to change something outside this repo?
Where we handle these CloudFront redirections?

@adborden @jbrown-xentity 

<pre>
$ curl -L -v catalog.data.gov > /dev/null

> GET / HTTP/1.1
> Host: catalog.data.gov

< HTTP/1.1 301 Moved Permanently
<b>< Server: CloudFront</b>
< Location: https://catalog.data.gov/

> GET / HTTP/2
> Host: catalog.data.gov

> GET /dataset HTTP/1.1
> Host: catalog.data.gov

< HTTP/1.1 301 Moved Permanently
<b>< Server: CloudFront</b>
< Location: https://catalog.data.gov/dataset
< X-Cache: Redirect from cloudfront

< HTTP/2 200 
<b>< server: Apache</b>
< x-cache: Miss from cloudfront
< via: 1.1 af37d53aae0b69747c36702d02f33cc2.cloudfront.net (CloudFront)
<pre>

**Comment by nickumia-reisys** [comment]
I believe this was closed because it was an FCS-specific issue
- #3710
