### ISSUE TITLE
WAF harvest source Dataset visibility is not being reflected properly in UI

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2085]
Unable to save a harvest sources with the `public` Dataset visibility

## How to reproduce

1. Set up a new WAF harvest source, choose `public` as Dataset visibility. Save

## Expected behavior

The source should show `public` as Dataset visibility.

## Actual behavior

The source shows `private` as Dataset visibility.

**Comment by FuhuXia** [comment]
It affects UI only. Datasets harvested uses the correct Dataset Visibility when the source page is saved. But if the user edit the source page and save it again without noticing the Dataset Visibility is changed to private by this UI bug, all new datasets will be harvested as `private`.

**Comment by FuhuXia** [comment]
duplicate of https://github.com/GSA/datagov-deploy/issues/897

**Comment by mogul** [comment]
Closing as dupe.
