### ISSUE TITLE
Deploy new XSLT to fgdc2iso

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2088]
## User Story

As a member of FGDC, I want FGDC2ISO service use the newly designed XSLT transform file so that newly harvested FGDC dataset has new version of ISO Metadata.

## Acceptance Criteria
- [ ] GIVEN a new fgdc2iso.war file is released
  WHEN the war file is extracted
  THEN the xslt inside has the new content.
- [x] GIVEN a new FGDC dataset is harvested
  WHEN open the link Metadata Source ISO-19139 Metadata on the UI
  THEN the new banner is displayed

```
<!-- +########################################################################+ -->
<!-- +    This file was generated using an FGDC CSDGM to ISO19139 Transform   + -->
<!-- +                                                                        + -->
<!-- + This is accomplished using an XML Style sheet that transforms metadata + -->
<!-- + conforming to the CSDGM to the ISO 19139.                              + -->
<!-- #########################################################################+ -->

```
## Background
Related to story #865 and #1520

## Sketch
Given the fact that #865 is not completed yet and repo [catalog-fgdc2iso](https://github.com/GSA/catalog-fgdc2iso) is not automatically generating new war file, you will need to follow the [instruction](https://github.com/GSA/catalog-fgdc2iso/blob/master/fgdc2iso/README.md) and pack up the war file manually, then have it deployed.

**Comment by FuhuXia** [comment]
This is the [link to the XSLT file](https://github.com/GSA/datagov-deploy/files/4307367/csdgm_iso_transform.zip) from ticket #1520.

**Comment by chris-macdermaid** [comment]
https://github.com/GSA/datagov-deploy-fgdc2iso/pull/2   fgdc2iso war file
https://github.com/GSA/catalog-fgdc2iso/pull/2    Add xslt file
