### ISSUE TITLE
Upload to Datastore on staging inventory gives 500 error

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2094]
On staging, when adding new spreadsheet resource to inventory dataset, the datapusher app gives 500 error.

![Screen Shot 2020-08-28 at 2 15 48 PM](https://user-images.githubusercontent.com/1392461/91602309-21efe900-e939-11ea-9aa9-fee4f924ea2d.png)

## How to reproduce

1. Open any dataset page in staging Inventory, Click "Manage" button, then "Resources" tab
2. Click "Add new resource", choose "Upload a file", select some local csv/xlsx file to upload. 
3. Fill the form with other necessary info, click "Add".
4. Click the resource you just added, The resource view will not load. Click "Manage" button then "Datastore" tab, you see the error in the screenshot.

## Expected behavior

Data should be pushed to Datastore successfully. A few moments after resource is saved, the resource view should load, Datastore tab should show success message. 

## Actual behavior

500 Server Error on Datastore tab. resource view is not loading.

**Comment by FuhuXia** [comment]
datapusher.error.log shows
`ImportError: /usr/lib/datapusher/lib/python2.7/site-packages/lxml/etree.so: undefined symbol: PyFPE_jbuf`

![Screen Shot 2020-08-28 at 2 28 47 PM](https://user-images.githubusercontent.com/1392461/91603574-37fea900-e93b-11ea-8920-bff813c8784f.png)

**Comment by mogul** [comment]
Possibly fixed by recent datapusher work. There are other datapusher problems in staging and it might be best to tackle these all at once.

**Comment by jbrown-xentity** [comment]
This is currently working on staging, see screenshot of dataset that was loaded.
![image](https://user-images.githubusercontent.com/26980513/92166966-cb7e2100-edf6-11ea-82ac-9263f5e7002a.png)
