### ISSUE TITLE
Draft datasets in Inventory should be considered private and visible only to organization members

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2095]
## User Story

In order to draft datasets in Inventory without incomplete metadata being visible or published to other users, agency data managers want dataset and resource visibility in CKAN to be tied to Publish Status.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
- https://github.com/GSA/datagov-deploy/wiki/inventory.data.gov#access
- https://github.com/GSA/datagov-deploy/issues/1863

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
Consider CKAN's Private attribute to be an internal field not visible to users. Users should only be concerned with a single field, Publish Status, when considering visibility outside of the organization.

Use CKAN hooks to toggle the Private attribute of a dataset based on the Publish Status.

It's probably okay to ignore the case when a user manually changes the Private field (no need to update Publish Status in that case) to keep things simple.

**Comment by adborden** [comment]
FYI, as part of https://github.com/GSA/datagov-ckan-multi/issues/422, it looks like this is actually a bug in that publishing_status should be tied to CKAN's draft state (`state: draft`). I think this will be resolved with #422 and other changes from the form.

**Comment by jbrown-xentity** [comment]
This is resolved, organizations can only see their own datasets. Closing.
