### ISSUE TITLE
Enable read-only public access to published datasets in Inventory

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2096]
## User Story

In order to make federal open data more accessible and discoverable, open data users want to view datasets in Inventory.

This issue depends on https://github.com/GSA/datagov-deploy/issues/2095.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
- https://github.com/GSA/datagov-deploy/wiki/inventory.data.gov#access
- https://github.com/GSA/datagov-deploy/issues/1863

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Clarify any controls in the SSP around Inventory access. Resources in Inventory are already publicly accessible and dataset metadata is already published in the Catalog. This only provides a new read-only view for existing datasets.

## Sketch
Implement https://github.com/GSA/datagov-deploy/issues/2095 so that agency users can easily mark datasets as non-visible to the public.

**Comment by adborden** [comment]
Department of Labor was running into this. Datasets are marked as public_access, but still with CKAN `private: true` and they were confused why they could not see datasets using package_search.

I think we will end up closing this. With CKAN 2.8, we then have `include_private` parameter for package_search, and we'll have a better model of access from https://github.com/GSA/datagov-deploy/issues/2575, hopefully making this less confusing.

**Comment by jbrown-xentity** [comment]
We will close this, it's much more clear now to see datasets when logged in.
