### ISSUE TITLE
Follow up on TTS Digital Council URL removals

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2098]
## User Story

https://gsa-tts.slack.com/archives/CMGHQPSLC/p1597400759178700
**Deadline: September 30th, 2020**
[Spreadsheet of URLs](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit#gid=1506078684)

As a [user description], I want [behavior description] so that [goal].

[...or [alternatively](https://blog.crisp.se/2014/09/25/david-evans/as-a-i-want-so-that-considered-harmful)...]

In order to [goal], [stakeholder] wants [change].

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by adborden** [comment]
This should be done by PMO. I think for most of our URLs, we're just going to write a justification that these URLs need to be public for non-GSA partner review and automated QA checks by third-party services. Other programs have written similar justifications and we should crib off of that.

**Comment by adborden** [comment]
Email sent to our Digital Council representatives with justification for:
- federation-staging.data.gov
- resources-staging.data.gov
- sdg-staging.data.gov
- strategy-staging.data.gov

**Comment by jbrown-xentity** [comment]
Emails this morning show that either our justification was not accepted or it was not put in on time. Email requested to put justification in [spreadsheet](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit#gid=2013137748&fvid=1173684912) (would have done myself, but I only have read-only access).
Reopening to track...

**Comment by jbrown-xentity** [comment]
We have 18 sites under our domain/responsibility which are ["broken"](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit#gid=2013137748&fvid=1822148686) (search `datagovhelp`).

We have 6 sites under our domain/responsibility which need ["mod plans"](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit#gid=2013137748&fvid=1023115104) (search `datagovhelp`) or need to be justified.

@adborden let me know if we need new tickets for these other items...

**Comment by adborden** [comment]
@jbrown-xentity thanks for re-opening. @hkdctol and I will follow up.

**Comment by adborden** [comment]
Ammie from the Digital Council is following up on this.

**Comment by mogul** [comment]
Waiting on official guidance from the Digital Council.

**Comment by hkdctol** [comment]
This one is OBE, closing
