### ISSUE TITLE
Upgrade ansible-postfix

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2103]
## User Story

As a datagov developer I want our roles to be on the latest versions so that we avoid tech-debt as much as possible.

## Acceptance Criteria
- [x] Playbooks run on all hosts and I see that ansible-postfix is >= 3.1

## Background
The failed task is while [upgrading the configuration file](https://github.com/Oefenweb/ansible-postfix/blob/master/tasks/main.yml#L47-L58). Error message: `"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'lstrip'\n\nThe error appears to be in `

It looks like we register the variable `postfix_main_cf.`, during the [os-ubuntu-14](https://github.com/GSA/ansible-os-ubuntu-14/blob/master/tasks/section2.yml#L78-L82) playbook and the [os-ubuntu-16](https://github.com/GSA/ansible-os-ubuntu-16/blob/master/tasks/section2.yml#L161-L165).

This seems more likely to be the cause of the issue as running `pipenv run ansible-playbook common.yml --limit <any-host-you-want>` fails but `pipenv run ansible-playbook common.yml --limit <any-host-you-want> --tags postfix` does not.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None.

## Sketch
We could move the [postfix role](https://github.com/GSA/datagov-deploy-common/blob/d674f9c9793f4a1b770c3d569e498b25ad1fe6ed/tasks/main.yml#L72-L76) before the [os-ubuntu-xx role](https://github.com/GSA/datagov-deploy-common/blob/d674f9c9793f4a1b770c3d569e498b25ad1fe6ed/tasks/main.yml#L12-L26)

**Comment by adborden** [comment]
I opened https://github.com/GSA/ansible-os-ubuntu-16/issues/30 but I don't think GSA is maintaining this repo anymore.

**Comment by adborden** [comment]
`register`'d variables are up high on the [precedence list](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#ansible-variable-precedence), so the most practical fix is to use `set_fact` to set it to the role's default :(
