### ISSUE TITLE
inventory-next is deployed in staging

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2118]
## User Story

In order to have confidence in our coming rollout of inventory-next, the team wants inventory-next up and running in staging, irrespective of migration issues yet to be resolved.

## Acceptance Criteria

- [x] GIVEN the inventory playbook has been run in staging \
  WHEN I look at the bionic inventory hosts \
  THEN I can see that CKAN 2.8 is installed

## Background
This is separate infrastructure/playbook work that can happen irrespective of the production-readiness of inventory-next, functionality-wise.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
The deployment will use our usual processes for staging/production rollouts, and not introduce any new process or components where security problems are likely to appear.

## Sketch

- Prerequisites: Database, Redis, Solr, etc should all exist already; credentials should be added to the vault if they aren't already there.
- Check out [the changes that were needed to get inventory into sandbox](https://github.com/GSA/datagov-deploy/pull/2020) and work from there.

**Comment by jbrown-xentity** [comment]
Files to change (incomplete list):

- [x] inventories/staging/hosts
- [x] rename inventories/staging/group_vars/inventory-web-v2 to inventory-next
- [x] update inventories/staging/group_vars/inventory-next similar to sandbox/group_vars/inventory-next
- [x] add variables to inventories/staging/group_vars/all/vars.yml for inventory similar to sandbox/group_vars/all/vars.yml
- [x] add variables to inventories/staging/group_vars/all/vault.yml for inventory similar to sandbox/group_vars/all/vault.yml

**Comment by chris-macdermaid** [comment]
Created the playbook for deploying inventory-next on staging and tested deploying to staging.
