### ISSUE TITLE
[research:3d] prototype new geospatial metadata harvesting process

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2122]
## User Story

In order to standardize and simplify the geospatial metadata harvest processes between data.gov and Geoplatform in the federal government, Geoplatform and geospatial data users want the original geospatial metadata to be referenced or linked from catalog.data.gov.

In order to minimize human coordination between FGDC and data.gov, Geoplatform wants original metadata to be referenced from catalog.data.gov.

## Acceptance Criteria
- [x] [One-pager](https://docs.google.com/document/d/1_zh_j7_PAFnI8NkMSGTfc6-OsYAE5wrVdHXicsqpDwg/edit#) outline documented in Google Drive ([Full Research](https://docs.google.com/document/d/1VxC3rkIti2Lf2WdYJoe_Fjyrw3L2Fr0BBnTJciHnVkI/edit#))
- [X] [Examples of DCAT-US metadata demonstrating the solution](https://github.com/GSA/ckanext-datajson/tree/master/ckanext/datajson/tests/datajson-samples#datajson-examples)
- [x] [If necessary, any prototype code linked in GitHub gist or repository](https://gist.github.com/jbrown-xentity/a4af7682f00407eb6ca59b185d48e294)
- [X] Stories are written describing next steps

## Background
Today, metadata is manually curated on Geoplatform. The [intention](https://resources.data.gov/resources/data-gov-open-data-howto/#federated-metadata-harvest-architecture) was to have Geoplatform harvest geospatial metadata from catalog.data.gov in an automated fashion.

Federal Data Strategy has an action for [providing metadata in a single format](https://strategy.data.gov/action-plan/#action-6-publish-and-update-data-inventories), likely DCAT-US as the agency.gov/data.json. While DCAT-US includes a few minor fields for geospatial data, any transformation from a geospatial format to DCAT-US results in a loss of fidelity.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None for the research, but any additional stories coming out fo the research should include any security compliance considerations.

## Sketch
We'd like to identify a simplified set of metadata harvested by data.gov. Geoplatform has different requirements than data.gov and needs the original metadata. If catalog.data.gov can provide a link to the original metadata, without Geoplatform having to discover and find data itself, that would be enough.

In other words, Geoplatform should use catalog.data.gov as a catalog or index of all federal geospatial data and then find the original metadata from which to harvest.

Areas of research:
- How might we avoid any transformation of metadata required by data.gov?
- Minimize burden on agencies, can agencies define their metadata once and meet the federal requirements?
- Can we do this with the existing DCAT-US schema?
- What are the long term changes we'd like to make in DCAT-US?
- Are there any special considerations necessary for ISO19115-1 or consistency with the [FGDC Geospatial metadata technical guidance](https://www.fgdc.gov/technical-guidance/metadata/fgdc-technical-guidance-datagov-geoplatform-ngda.pdf)?

Review the DCAT-US schema, and identify where fields could be used today in order to provide or link to the original metadata.

**Comment by adborden** [comment]
Added a note about ISO 19115-1 and ensuring that agencies implementing the [FGDC technical guidance](https://www.fgdc.gov/technical-guidance/metadata/fgdc-technical-guidance-datagov-geoplatform-ngda.pdf) won't have any trouble understanding how to get their metadata into data.gov.

**Comment by jbrown-xentity** [comment]
Note ISO19115-1 support was requested 3.5 years ago: https://github.com/GSA/data.gov/issues/764

**Comment by jbrown-xentity** [comment]
For best practices, will consider the following from the [DCAT-US standard](https://resources.data.gov/resources/dcat-us/):

- Utilize the Dataset Distribution Fields
- Consider populating the `conformsTo` field for better scannability by Geoplatform
- Consider utilizing the describedBy and describedByType fields under current dataset distribution fields
    - Is that URL displayed or discoverable via the UI at all?
- Use the `downloadURL`, as the metadata being provided is a file (not a webpage)
- Are there any other specifications that need to be utilized for Geoplatform harvesting to occur, like a special `title`? `format`?

**Comment by jbrown-xentity** [comment]
NOAA has a v0.1 of a data.json file [here](https://data.noaa.gov/dataset/data.json). We will use 2 examples from this and link back to the geospatial metadata files found [in the current WAF harvest source](https://data.noaa.gov/waf/NOAA/nmfs/nwfsc/iso/xml/).

We will build a test file on the https://github.com/gsa/ckanext-datajson extension, and then create a harvest source for the raw json content to test what this will look like, and provide examples to Geoplatform and FGDC for review, and interested agencies as examples (once review is finalized).

**Comment by jbrown-xentity** [comment]
[Working public examples](https://catalog.sandbox.datagov.us/harvest/dcat-us-full-metadata-test) ([data.gov validation tool passing](https://labs.data.gov/dashboard/validate?schema=federal-v1.1&output=browser&datajson_url=https%3A%2F%2Fgithub.com%2FGSA%2Fckanext-datajson%2Fraw%2Ffeature%2Ftest-geospatial-link%2Fckanext%2Fdatajson%2Ftests%2Fdatajson-samples%2Fgeospatial.data.json&qa=true))

We can deliver to FGDC today and let them evaluate which direction seems the best to them. My recommendation is [conformsTo method](https://catalog.sandbox.datagov.us/dataset/conformsto-example-jellyfish-movement-data-determining-movement-patterns-of-jellyfish), which gives user visibility and more fully defines the metadata type.

Here is a [draft PR](https://github.com/GSA/ckanext-datajson/pull/86) where I will create some first draft guidance/explanation.

**Comment by jbrown-xentity** [comment]
[Gist of working download/parse example](https://gist.github.com/jbrown-xentity/a4af7682f00407eb6ca59b185d48e294)

**Comment by jbrown-xentity** [comment]
[1/2 pager documenting examples, data.gov suggested guidance, and next steps](https://docs.google.com/document/d/1_zh_j7_PAFnI8NkMSGTfc6-OsYAE5wrVdHXicsqpDwg/edit#)

**Comment by adborden** [comment]
This is looking good! Let's find some time to pair and we can consolidate the examples and proposal into something concise to share with Geoplatform.

**Comment by jbrown-xentity** [comment]
Final items:

- [x] Update [examples list](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/tests/datajson-samples/geospatial.data.json) to remove describedBy option, and add standard ISO example and standard CSDGM example
- [x] Simplify [test/example code](https://gist.github.com/jbrown-xentity/a4af7682f00407eb6ca59b185d48e294) to highlight important sections and streamline
- [x] Improve/cleanup [technical working document](https://docs.google.com/document/d/1_zh_j7_PAFnI8NkMSGTfc6-OsYAE5wrVdHXicsqpDwg/edit?ts=5f9cb474#)

**Comment by adborden** [comment]
I'm drafting up a [proposal](https://docs.google.com/document/d/1XDsFnQCKuqnQCVfMeCNuBnNKE4Oco69-lTVuVCrHV6c/edit#) to share with partners.
