### ISSUE TITLE
Add workers for staging environment

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#2123]
## User Story

As a GSA developer, I want various [workers](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/catalog/ckan-app/files/etc/cron.d/ckan_misc_worker#L3-L11) jobs to be running automatically and completing in staging so that I will have confidence that the following extensions/jobs will work on production: `ckanext-report`, `ckanext-qa` and `ckanext-datagovtheme`.

## Acceptance Criteria
- [ ] GIVEN the `ckanext-report` and `ckanext-qa` workers are running in the staging environment 
  WHEN I open a dataset page \
  THEN I can see _Openness score_ for each resource in the resources list.

## Background
This is related to [Multi#391](https://github.com/GSA/datagov-ckan-multi/issues/391)

## Security Considerations 
None

## Sketch
The workers are defined as [supervisor tasks](https://github.com/GSA/datagov-deploy/tree/develop/ansible/roles/software/ckan/catalog/ckan-app/templates) and should be executed as [cron jobs](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/catalog/ckan-app/files/etc/cron.d/ckan_misc_worker) but they are commented out.

**Comment by kimwdavidson** [comment]
Andres and Julie to determine which team should work on this

**Comment by FuhuXia** [comment]
I think the reason we turned off the cron jobs for those workers is that they took so long to finish, it is impractical to run it on such a large collection of datasets. So don't be surprised if we face the same slowness issue when they are turned back on.

**Comment by thejuliekramer** [comment]
@FuhuXia is it possible to turn these on for just one environment like staging - so we can test that some functionality is working and then turn them off again? Let me know if you have time to pair this week - we are blocked on numerous tickets without being able to start these workers - and we don't want to just turn them on without understanding the repercussions. Thanks!

**Comment by FuhuXia** [comment]
Sure, you can turn them on sandbox or staging. No need to change playbook. Just start a tmux session and run the ckan command.

**Comment by jbrown-xentity** [comment]
I would make sure to run them 1 at a time, otherwise the server may crash (it probably just did @thejuliekramer).
You can see all the available jobs by running `sudo supervisorctl status`, and run any single job you choose.
The automation of the jobs is handled through cron, and is turned off. You can see that [here](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/catalog/ckan-app/files/etc/cron.d/ckan_misc_worker), or on the server at `/etc/cron.d/ckan`.

**Comment by thejuliekramer** [comment]
@jbrown-xentity @FuhuXia does it matter which host I am ssh into?

**Comment by jbrown-xentity** [comment]
@thejuliekramer the harvester2d machine should have the supervisor jobs available, and others might have it available too.

**Comment by avdata99** [comment]
Since these tasks are huge the best idea here seems to be to run this manually.
**Proposed to move to icebox or done**

**Comment by thejuliekramer** [comment]
Yes I am running workers on catalogharvester2d one at a time manually - we can include this in the other tickets in blocked and move them into in progres

**Comment by thejuliekramer** [comment]
@cmugisha I think we can move this to done and track this in the issues in blocked
