### ISSUE TITLE
HSTS system-wide

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2125]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.tka5idg3rc5)._

**Date of report: 9/7/2020** 
**Severity: Medium**
**Due date: 12/6/2020** 

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by FuhuXia** [comment]
should be done after https://github.com/GSA/datagov-deploy/issues/570 is complete.

**Comment by jbrown-xentity** [comment]
Latest scan confirms complete

**Comment by FuhuXia** [comment]
The original Nessus was complaining missing HSTS on the individual host level. I think we still have to address it, otherwise it will come back in another scan.
