### ISSUE TITLE
New Relic Supervisor Permissions Issue

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2142]
In reviewing the syslog on inventory-2p, we discovered that a new relic job was constantly trying to poll supervisord status but was unable to do so. This isn't necessary for new relic to work, but is creating issues and unnecessary logs every minute.

```
inventory2p newrelic-infra: time="2020-09-15T06:29:47Z" level=error msg="getting supervisord data" 
error="supervisor.Processes: Post \"unix:///RPC2\": write unix @->/var/run/supervisor.sock.1423: write: broken pipe" plugin=Supervisor
```

## How to reproduce

1. SSH onto inventory2p.prod-ocsit.bsp.gsa.gov
2. Review /var/log/syslog

## Expected behavior

No New Relic errors

## Actual behavior

New Relic Errors

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
