### ISSUE TITLE
Data.gov Cipher Usage

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2144]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.myhsfzbhldtf)._

**Date of report: 9/16/2020** 
**Severity: Moderate**
**Due date: 12/16/2020** 

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by mogul** [comment]
Suspected false positive; checking.

**Comment by adborden** [comment]
The Pen Test does not call out any specific ciphers, so it's hard to tell what they have an issue with. The report says "SEED or 128-bit and 256-bit CBC ciphers". AWS lists the [OpenSSL ciphers used by policy](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html#secure-connections-supported-ciphers) which can be cross-referenced with the [IANA names](https://testssl.sh/openssl-iana.mapping.html). I think these are the ciphers in question:
- AES128-SHA256
- ECDHE-RSA-AES128-SHA256
- ECDHE-RSA-AES256-SHA384

... which we should have an exception from https://github.com/GSA/datagov-deploy/issues/1369, so this is pretty much a duplicate of https://github.com/GSA/datagov-deploy/issues/2182, except we should leave this open to track as a separate compliance finding.

AWS released a new recommended TLS policy, TLSv1.2_2019, which drops support for these ciphers:
- AES128-GCM-SHA256
- AES256-GCM-SHA384
- **AES128-SHA256**

I'm going to switch to this new policy for www.data.gov and catalog.data.gov. If the Pen Testers come back saying it's still unresolved, we can request more detail from them, but I suspect we'll seek out an exception based on AWS's policy.

**Comment by adborden** [comment]
FWIW, [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=www.data.gov&s=99.84.238.71) also reports these enabled ciphers as weak, which matches the above.

<img width="956" alt="Screen Shot 2020-11-13 at 2 56 33 PM" src="https://user-images.githubusercontent.com/509703/99128737-76157b80-25c0-11eb-845c-689f71ba5e1c.png">

So by switching to TLSv1.2_2019, our list of weak ciphers with exceptions becomes:
- ECDHE-RSA-AES128-SHA256 (TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256)
- ECDHE-RSA-AES256-SHA384 (TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384)

**Comment by adborden** [comment]
CloudFront distributions (catalog.data.gov and www.data.gov) are now using TLSv1.2_2019.

**Comment by mogul** [comment]
For future reference: The change to TLSv1.2_2019 was made manually through the AWS console.
