### ISSUE TITLE
Catalog.data.gov unavailable in the DC area

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2154]
catalog.data.gov was unavailable from 10:25 am ET until 1:00 pm ET. Our New Relic reporting in that region did not give out any alerts, and was reporting normal behavior. We started discussions with both FCS and AWS to discover the root cause. We found that the requests were failing to reach the servers from cloudfront. Seems to be a possible misconfiguration with NetScaler firewall rules, or something in that arena. FCS started a ticket ([see discussion thread for details](https://chat.google.com/u/2/room/AAAAcJQgkd8/GoxG_DV09eY)) to investigate the issue.

## How to reproduce

1. Unknown

## Expected behavior

catalog.data.gov available in all regions

## Actual behavior

catalog.data.gov intermittent

**Comment by adborden** [comment]
Rolling this up into https://github.com/GSA/datagov-deploy/issues/2398
