### ISSUE TITLE
404 on wordpress page https://www.data.gov/meta/highlights

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2157]
404 on https://www.data.gov/meta/highlights

![Screen Shot 2020-09-18 at 11 19 24 AM](https://user-images.githubusercontent.com/1392461/93615005-dd3bf880-f9a0-11ea-8c2e-328f63bad53a.png)

## How to reproduce

1. Go to https://www.data.gov/meta/
2. Click More Highlights link under the highlighted post

## Expected behavior

The page shows a list of highlighted meta posts

## Actual behavior

404

**Comment by FuhuXia** [comment]
Found this bug when dealing with a disappeared meta post in a [Slack conversation](https://gsa-tts.slack.com/archives/C2N85536E/p1600439407001500). Due to this bug, meta posts marked highlight will not show up in the /meta public page. 

With or without this bug, I think highlighted post should also be listed at the bottom overall update list, otherwise user will miss those highlighted posts unless they click **More Highlights** link. Thoughts on this to open another issue? @hkdctol

**Comment by adborden** [comment]
The post was marked Draft in WordPress, I re-published it.

**Comment by mogul** [comment]
(Missed as needed during our content review, hence it having been flipped to Draft status.)
