### ISSUE TITLE
Logs for Catalog RDS Postgres database size change

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2165]
## User Story

As a catalog.data.gov admin, I want to have a daily log file recording Catalog database's detailed size information so that I can have a better understanding what is the cause for the spikes in DB storage usage.

## Acceptance Criteria
- [ ] GIVEN a daily log file is generated
  WHEN production RDS database size increases
  THEN the log file shows which DB component(table, index...) contribute to the size increase

## Background
The catalog production database experienced a big drop in the available storage. The free available storage ran from 40GB to 0 in 15 hours and brought the admin site down. This story will help us to understand what the cause is and how to address it.

**Comment by jbrown-xentity** [comment]
Not something easily done in the cloud.gov world. Seems stable now, going to close.
