### ISSUE TITLE
Catalog RDS Postgres database size gets too big

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2168]
We have to increase Catalog RDS DB storage from 850DB to 950GB recently due to free space running out.  I think it is getting unnecessarily big. We need to research and find out:

1. What makes DB so big. 
2. Is there any Postgres DB maintenance job that we are supposed to run regularly to keep DB size in check.
3. What is the reasonable storage size for production Catalog RDS DB
4. What threshold to set for CloudWatch low storage alert that will give developer enough time ( ~30 days) to act on.
5. What cloud have happened in the DB when free space went from 70GB to 0 in 48 hours. (Fig1)
6. Explain when master DB free space dropped 70GB, replica DB size barely changed at the same time frame (Fig2).

**Fig1: Master DB size change:**
![image](https://user-images.githubusercontent.com/1392461/93922143-8ce5d300-fcdf-11ea-98d3-57ab6de48ce7.png)

 
**Fig2: Replica DB size change:**
![image](https://user-images.githubusercontent.com/1392461/93922945-aa676c80-fce0-11ea-9bd1-a0b490d12840.png)

**Comment by jbrown-xentity** [comment]
This hasn't been a problem in the last year+, I'm going to close this.
