### ISSUE TITLE
Redis service went down after reboot

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2173]
Host `redis1p.prod-ocsit.bsp.gsa.gov` was rebooted by the action/reboot.yml playbook. After reboot, New Relic reported
`redis service not running`. Logged into host to restart the service but it always returned the following error message:

```
Checking redis status shows error message:
...
Active: failed (Result: exit-code) since Wed 2020-09-23 13:25:58 UTC; 4s ago.
...
Sep 23 13:25:58 redis1p.prod-ocsit.bsp.gsa.gov systemd[1]: Stopped Advanced key-value store.
Sep 23 13:25:58 redis1p.prod-ocsit.bsp.gsa.gov systemd[1]: redis.service: Start request repeated too quickly.
Sep 23 13:25:58 redis1p.prod-ocsit.bsp.gsa.gov systemd[1]: redis.service: Failed with result 'exit-code'.
Sep 23 13:25:58 redis1p.prod-ocsit.bsp.gsa.gov systemd[1]: Failed to start Advanced key-value store.
```
## How to reproduce

Never happened before. After work-around in place, cant replicate.

## Work-around

Found out the folder `/var/log/redis` is missing. Mannually created this folder, giving same permission as the one on staging server, then things are back to normal.

`drwxr-xr-x  2 redis   redis    4096 Sep 23 13:29 redis
`

**Comment by mogul** [comment]
Going to wait until we see this happening again before we unthaw it.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
