### ISSUE TITLE
supervisord went down after reboot

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2174]
Host `redis1p.prod-ocsit.bsp.gsa.gov` was rebooted by the action/reboot.yml playbook. After reboot, New Relic reported
`supervisord not running`. Logged into host, ran command `supervisorctl restart all`, got this error

```
unix:///var/run/supervisor.sock no such file
```

## How to reproduce

Never happened before. After work-around in place, cant replicate.

## Work-around

Found out the folder `/var/log/supervisor` is missing. Here are the steps to bring service back.
```
sudo mkdir /var/log/supervisor
sudo chmod 755 /var/log/supervisor
sudo touch /var/run/supervisor.sock
sudo supervisord -c /etc/supervisor/supervisord.conf
sudo supervisorctl restart all
```

**Comment by FuhuXia** [comment]
It is related to https://github.com/GSA/datagov-deploy/issues/2173. Work-arounds are similar too, mkdir necessary folder in /var/log

**Comment by FuhuXia** [comment]
Took a closer look at what happens after `redis1p` reboot. It appears that partition` /var/log` lost all its content and everthing started fresh. All files and folders on this partition are timestamped after the reboot.

**Comment by mogul** [comment]
Will unthaw this one if we see it happening more

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
