### ISSUE TITLE
Netsparker 09222020 - Weak Ciphers Enabled

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2182]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.pcs30nu8hkyc)._

**Date of report:** 2020-09-22
**Severity:** Moderate
**Due date:** 2020-12-22

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
Details in [google doc](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.pcs30nu8hkyc)

**Comment by adborden** [comment]
These are the same ciphers from https://github.com/GSA/datagov-deploy/issues/1369 and should be considered excepted. @hkdctol has raised with our ISSO.

The only excepted ciphers should be:
- ECDHE-RSA-AES128-SHA256 (TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256)
- ECDHE-RSA-AES256-SHA384 (TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384)

**Comment by adborden** [comment]
@hkdctol is talking with the ISSO, who had to reach out to someone else to get an answer.

**Comment by mogul** [comment]
Still haven't heard back from Lynnette.

**Comment by adborden** [comment]
Confirmed from Lynnette and the scanning team that this is a false positive.
