### ISSUE TITLE
Smoke test for Solr

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2185]
## User Story

In order to ensure deploys to solr are successful before moving onto the ckan deploys, data.gov operator wants a smoke test added to the solr playbook.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I am logged into the jumpbox \
  WHEN I run the Solr playbook \
  THEN I see output from a task that verifies that Solr is running

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]
Solr has a [`ping`](https://lucene.apache.org/solr/guide/6_6/ping.html) for testing raw functionality. We may need to write other tests to make sure the necessary cores are available.

**Comment by nickumia-reisys** [comment]
This issue is no longer relevant since we have migrated to cloud.gov.  We are confident in our `cf create-service` method of deploying solr.  Additionally, when our main apps are deployed, it first checks to see if there is a successfully created solr service, so a deployment will not start if solr is not up.
