### ISSUE TITLE
Selectively re-index catalog datasets 

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2190]
## User Story

As a data.gov developer, I want to re-index a selective set of dataset so that the dataset has consistent data between database and Solr.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I am in the jumpbox \
  AND run an Ansible playbook \
  WHEN a dataset id is passed as argument \
  THEN the dataset is re-indexed
- [ ] GIVEN I am in the jumpbox \
  AND run an Ansible playbook \
  WHEN a list of dataset ids is passed as argument \
  THEN these datasets are re-indexed
- [ ] GIVEN I am in the jumpbox \
  AND run an Ansible playbook \
  WHEN an organization id is passed as argument \
  THEN all datasets of this organization are re-indexed

## Background
CKAN has build-in `ckan search-index rebuild [dataset_id]` command available. But it is dangerous to run this command in shell environment for a large set datasets. If `ckan search-index rebuild` (without any argument)  is run, it will erase the Solr index and may take days to finish re-indexing, during which user will see empty/incomplete datasets on the UI. Running the command in the playbook will prevent this from happening.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
None

**Comment by jbrown-xentity** [comment]
An analysis is run regularly on automation and syncing is occurring. Closing this.
