### ISSUE TITLE
dashboardweb2p storage full

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2191]
`dashboardweb2p` root partition has 0 disk space left. Under the dashboard web root folder, there is a hidden file `./shared/archive/datajson-lines/.raw`. It was generated two hours ago and 12GB in size. Failed to view the content of the file, but after gzip, it became 12MB in size. So most likely it is an erroneous file generated by PHP application with tons of empty lines and receptive chars in it. 

## Word around
Deleted the file.

**Comment by mogul** [comment]
Choosing to `Icebox` this one until we see it happening again.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
