### ISSUE TITLE
Tags are not discoverable in the catalog

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2193]
The tags filter shows the largest tags, clicking "Show more tags" will only show up to 50 tags. There are many more tags and there is nowhere to browse or search them all.

![Screen Shot 2020-09-25 at 12 37 17 PM](https://user-images.githubusercontent.com/509703/94308786-e5111500-ff2b-11ea-8189-b151ec64ec75.png)

## How to reproduce

1. https://catalog.data.gov/dataset

## Expected behavior

There is some hint at how to browse or search through all the tags in the catalog.

## Actual behavior

User is limited to the 50 most popular tags in the UI or must filter with other criteria first.

**Comment by jbrown-xentity** [comment]
This is partly a limitation of the metadata we accept; no limits on tags means making all the tags browseable is not possible.
There should probably be a search feature for tags. This is a long term play, and not probably something we'll take on as part of CKAN and changing the UI experience.
Tagging @CarolinaC-REI, @hkdctol , @tdlowden for thoughts.

**Comment by hkdctol** [comment]
I think the long term is there should be controlled vocabularies, which is in the DCAT 3 proposal. I think we can close the issue
