### ISSUE TITLE
tag_list API return 500

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2194]
## How to reproduce

1. $ curl -v https://catalog.data.gov/api/action/tag_list > /dev/null

## Expected behavior

200

## Actual behavior

500

**Comment by mogul** [comment]
Moving to `Icebox` since the API is not in active use by anyone other than us (when debugging)

**Comment by jbrown-xentity** [comment]
This scans every possible tag across every dataset and tries to return it. It's just too much data. Upstream CKAN bug, closing.
