### ISSUE TITLE
[Research] ckan-combine-feeds job

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2212]
## User Story

As a data.gov admin, I want to know if USAsearch/Bing can ingest pagination in atom feeds so that we can prioritize this work or deprecate this job/code.

## Acceptance Criteria

- [ ] GIVEN a USAsearch scan is done of the data.gov atom feed \
  WHEN a recently created dataset is searched \
  THEN the dataset is discoverable \
  OR a definition of how to make it discoverable is created

## Background
See [list of CKAN commands](https://github.com/GSA/datagov-deploy/wiki/CKAN-commands#catalog-commands) description for latest notes.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None (all information is designed for the public)

**Comment by mogul** [comment]
No pressing need for this job since it seems like the search engines are indexing using the sitemap.xml, which is generated correctly.

**Comment by jbrown-xentity** [comment]
This is no longer relevant, closing.
