### ISSUE TITLE
Test ckan-db-solr-sync job

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2213]
## User Story

As a data.gov admin, I want the ckan-db-solr-sync job to have tests and be tested against production data so that the job can be automated in production.

## Acceptance Criteria

- [ ] GIVEN the job has tests that pass circle-ci \
  AND there is production data available in a testing system \
  WHEN the job runs \
  THEN the job completes with relevant logs/errors \
  AND within 24 hours

## Background
This recurring job covers over a "smell" that something inside CKAN is updating one system but not another. Logging the datasets that are being updated and when may give insight into what may be going wrong to make this job necessary.

The time it takes this job to run will be the trickiest part of completing this ticket; the last run took days to complete.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
We want tests to be extremely clear in testing, because removing data that is supposed to be public is a security risk.

**Comment by robert-bryson** [comment]
For future Robby: [`db_solr_sync`](https://github.com/GSA/ckanext-geodatagov/blob/4ef71141dcdbf16e157841e184b7449fa3b0b23b/ckanext/geodatagov/commands.py#L498) is probably what will need reworkd.

**Comment by hkdctol** [comment]
please link geodatgov PR to this @robert-bryson

**Comment by robert-bryson** [comment]
[Example PR ](https://github.com/GSA/ckanext-geodatagov/pull/210/files#diff-e5710e239e81444e7dd15fc58323de11e4517a3456f6da7537b2ecc2294d9096) for adding to the CLI

**Comment by Jin-Sun-tts** [comment]
Revived old function db_solr_sync from commands.py to cli.py and modified, now this command works fine.  
Also added remove_orphaned_solr command to remove orphaned solr indexes. This method should have better performance.

**Comment by hkdctol** [comment]
@FuhuXia to create follow up ticket but this one is complete
