### ISSUE TITLE
inventory.data.gov uses login.gov for authn

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2220]
## User Story

As an organization data admin, I want to be able to access the latest version of the inventory app in a secure way so that I know that my data is secure.

## Acceptance Criteria

- [x] GIVEN login.gov is setup on inventory.data.gov \
  WHEN a user goes to https://inventory-next.data.gov/user/login [or staging equivalent] \
  THEN the user can login to login.gov \
  AND the user is redirected back to inventory-next.data.gov with the correct permissions

## Background
Should utilize [ckanext-saml2auth ckan2.8 extension](https://github.com/keitaroinc/ckanext-saml2auth/tree/ckan-2.8).
Catalog implemented this already, see [PR](https://github.com/GSA/catalog.data.gov/pull/198/files) and [configuration](https://github.com/GSA/catalog.data.gov/pull/199/files). Tests are in work, and should also be implemented; this should work locally if configured properly.
May also need to implement [change in login route similar to catalog](https://github.com/GSA/ckanext-datagovtheme/pull/80/files).
Will require change/addition in login.gov sandbox configuration for inventory, check catalog configuration.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
See SSP for user management details

**Comment by jbrown-xentity** [comment]
Paired with @woodt today. Went over the current status of https://github.com/GSA/datagov-ckan-multi/issues/348. To catch up to where catalog work currently is, we should:

- Setup an application on login.gov sandbox similar to [catalog-next](https://dashboard.int.identitysandbox.gov/service_providers/1129)
- Create draft PR's similar to the work for [catalog-next](https://github.com/GSA/datagov-ckan-multi/issues/348#issuecomment-706270960) (can use the current ckanext-saml2 branch, no need to create a new one).

Note that this will still be in a failing state, but we did work through the [encryption issue](https://github.com/GSA/datagov-ckan-multi/issues/348#issuecomment-715453866) (that setting is done in login.gov, not on a per-request basis as is normally done for saml2).

**Comment by FuhuXia** [comment]
App `inventory-next-sandbox` has been created on login.gov sandbox. 
![Screen Shot 2020-11-19 at 11 47 00 AM](https://user-images.githubusercontent.com/1392461/99696710-00485e80-2a5d-11eb-8337-ef2b1cc36ea7.png)

The certificate PEM was generated using command:
```
$ openssl req -x509 -nodes -newkey rsa:2048 -keyout mykey.pem -out mycert.pem -days 3650 -config <(
cat <<EOF
[req]
prompt = no
default_md = sha256
distinguished_name = dn

[ dn ]
C=US
ST=District of Columbia
L=Washington
O=General Services Administration
OU=Technology Transformation Service
emailAddress=datagovhelp@gsa.gov
CN=inventory-next.sandbox.datagov.us

EOF
)
```

**Comment by jbrown-xentity** [comment]
I found that our current blocker of a strange redirect [has happened before](https://gitter.im/ckan/chat?at=5d9b82a592920c36a12b23dc). Have twice reviewed the configuration, still have found nothing different between catalog and inventory setup. Need a pair to move forward.

**Comment by hkdctol** [comment]
I had a duplicate issue so I'm closing that one and have put some of the steps under Sketch here.

**Comment by FuhuXia** [comment]
App `inventory-next-sandbox` is deleted, app `inventory-next.sandbox.datagov.us` added, issuer and certificate kept same.

**Comment by FuhuXia** [comment]
inventory-next is integrated with login.gov in **sandbox** and **staging** environment. **Production** is on hold due to pending [PIV card issue](https://github.com/GSA/datagov-deploy/issues/2526).

**Comment by FuhuXia** [comment]
This is complete. All inventory-next apps integrated with login.gov. PIV card verified on staging and production. Sandbox does not require PIV card.
