### ISSUE TITLE
New Relic monitors use cache-busting URLs

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2235]
## User Story

In order to increase our visibility of potential production issues, the data.gov team wants New Relic to use cache-busting URLs to monitor production services.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
Inspired by [this incident](https://docs.google.com/document/d/1DEd2oiGj2SSdxxODsqE1rvfGAQDmXwyvcUZu3e_1rHY/edit#).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by adborden** [comment]
Monitor | Endpoint | Cached?
-------- | --------- | --------
admin-catalog.data.gov | https://admin-catalog.data.gov/api/action/status_show | N
catalog-next.data.gov | https://catalog-next.data.gov/api/action/status_show | N
catalog.data.gov | https://catalog.data.gov/api/action/status_show | N
CSW | https://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities | **Y**
dashboard | https://labs.data.gov/dashboard/offices/2020-03-31/qa | N
federation.data.gov | https://federation.data.gov/ | **Y**
inventory.data.gov | https://inventory.data.gov/api/action/status_show | N
resources.data.gov | https://resources.data.gov | **Y**
sdg.data.gov | https://sdg.data.gov | **Y**
strategy.data.gov | https://strategy.data.gov | **Y**
www.data.gov | https://www.data.gov/wp-json/ | N

Federalist sites are behind CloudFront with a max-age=60. CSW sets no cache headers, so CloudFront caches it using the default TTL of 24 hours.

**Comment by adborden** [comment]
I updated the CSW default to be 60 seconds.

I think we can call this story done.
