### ISSUE TITLE
Review health check endpoints for all applications

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2236]
## User Story

In order to ensure our existing monitoring is valuable, the data.gov team wants to review health check endpoints for all applications.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
Inspired by [this incident](https://docs.google.com/document/d/1DEd2oiGj2SSdxxODsqE1rvfGAQDmXwyvcUZu3e_1rHY/edit#).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
Currently monitoring is just doing a HEAD on the domain root; there's no special endpoint available or being checked in most places (except dashboard).

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
