### ISSUE TITLE
Add tests to ckan-report job

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2239]
## User Story

As a data.gov admin, I want the ckan-report job to have tests and be tested against production data so that the job can be automated in production.

## Acceptance Criteria

- [ ] GIVEN the job has tests that pass circle-ci \
  AND there is production data available in a testing system \
  WHEN the job runs \
  THEN the job completes with relevant logs/errors \
  AND within 24 hours

## Background
The only report this runs is the broken-links report, which lives [in another extension](https://github.com/GSA/ckanext-archiver/blob/datagov/ckanext/archiver/reports.py#L237-L247) (though is also referenced in [ckanext-report](https://github.com/GSA/ckanext-report/blob/datagov/ckanext/report/reports.py#L247-L258)). How it verifies the URL and how long the process can take on large organizations will need to be evaluated. Possibly this should be broken up into chunks.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

**Comment by mogul** [comment]
To be re-evaluated once we're on `catalog-next`

**Comment by mogul** [comment]
Iceboxing within the catalog-next epic as a signal that we can re-evaluate when that epic's done.

**Comment by nickumia-reisys** [comment]
This is superseded by,
- https://github.com/GSA/data.gov/issues/4116
