### ISSUE TITLE
Test qa-update job(s)

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2240]
## User Story

As a data.gov admin, I want the `qa-update` job to have tests and be tested against production data so that the job can be automated in production.

## Acceptance Criteria

- [ ] GIVEN the job has tests that pass circle-ci \
  AND there is production data available in a testing system \
  WHEN the job runs \
  THEN the job completes with relevant logs/errors \
  AND within 24 hours

## Background
There used to be a `qa-update-sel` job that was built to only run against recently modified datasets, but it [was removed](https://github.com/GSA/ckanext-qa/commit/93ea0aaaf985c7177a6bdebf1ddd4b3ce2c3c288#diff-190d6a167a536ae58f0689d24468bebbL191-R232) (possibly accidentally during a pull from upstream?). It needs to be determined how to chunk up this into processes that can finish within 24 hours, as this takes a long time to run currently.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
This is superseded by,
- https://github.com/GSA/data.gov/issues/3986

It technically is one of the steps that need to be done, but the infrastructure is completely different and this is more relevant as historical context than an actionable ticket.
