### ISSUE TITLE
Deleted DOI datasets do not appear on data.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2241]
## User Story

As a DOI data admin, I want datasets removed at the source catalog (data.doi.gov) to be removed in data.gov so that old data does not exist on data.gov.

## Acceptance Criteria

- [ ] GIVEN a dataset on data.doi.gov that was previously on data.gov has been removed \
  WHEN a data.gov harvest of DOI data happens \
  THEN the dataset is removed on data.gov

## Background
Even [upstream](https://github.com/ckan/ckanext-harvest/issues/396) does not implement any sort of package removal during a harvest. Items are either ignored, created, or updated. A first pass was made on the [GSA fork](https://github.com/GSA/ckanext-harvest/pull/5/files), but may still be incomplete.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Data removal needs to be done with care, tests must be complete.

## Sketch

- [ ] Consider alternative harvesting methods, improving the harvester, etc.

**Comment by jbrown-xentity** [comment]
As a note, this is possibly why we sometimes need to do a clear and re-harvest (though other external factors cause the clear and re-harvest to be necessary too). We have found that the code exists both upstream and on GSA fork to force a complete re-pull of data from the source; however the UI doesn't have a way to update this parameter. You can run an update on the harvest source config in the database to make this happen (replace {} with the id value):
```
UPDATE 
  harvest_source 
SET 
  config = '{"private_datasets": "False", "force_all": "True"}' 
WHERE 
  id = '{harvest-source-id}';
```

**Comment by mogul** [comment]
Another avenue to explore: Find a way that DOI could provide a data.json file within the constraints of the schema, so that CKAN-to-CKAN harvesting is not needed.

**Comment by mogul** [comment]
To keep in mind: If we fix this, let's make sure our fix is something that upstream is willing to accept.

**Comment by adborden** [comment]
Depending on #2462, we might want to go a different direction.
