### ISSUE TITLE
inventory-next UI - organization logo size

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2246]
Some of inventory organization logos are not sized properly.

![Screen Shot 2020-10-01 at 11 38 31 AM](https://user-images.githubusercontent.com/1392461/94831524-d10d5d80-03da-11eb-8787-aa7af45e5a33.png)

## How to reproduce

1. Go to inventory-next.domain.name/organization

## Expected behavior

All organization logos should have same width, fit within its grid.

## Actual behavior

Some logos are too big.

**Comment by adborden** [comment]
Consider if the image upload feature is working so thtat we can use that instead of the image linking.
