### ISSUE TITLE
Snyk should check both inventory and inventory-next

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2252]
## User Story
In order to avoid wasted time fixing issues that are addressed in newer versions of CKAN, the data.gov team wants Snyk to report on findings in the inventory-next codebase.

## Acceptance Criteria

- [x] WHEN an inventory application is ready to be released in an environment \
  THEN a snyk report is created/viewable 

## Background
Would be helpful to clean up inventory-next security vulnerabilities, but we don't want to miss vulnerabilities for inventory-classic that are currently in production...

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Careful consideration that both versions of the aplication are secure.

## Sketch
Using the Snyk CLI doesn't seem tenable (see comment), so should use either 2 repo's or use the Snyk beta.

**Comment by pjsharpe07** [comment]
It looks like the functionality through the UI is in [beta](https://support.snyk.io/hc/en-us/articles/360001497578-Which-branch-does-Snyk-Monitor)

**Comment by pjsharpe07** [comment]
I sent an email to snyk support to see if we can use their two branches, same repo beta.

**Comment by jbrown-xentity** [comment]
Looking at the [snyk cli cheat sheet (Snyk test header)](https://snyk.io/blog/snyk-cli-cheat-sheet/) we need to pip install our dependencies before running the snyk monitor, which would involve either

1. Creating a custom build of our dependency jobs on a python 2.7 container
1. Add npm and snyk cli to the docker container, including validation information

[Current work is being done here](https://github.com/GSA/inventory-app/tree/snyk/monitor-inventory-2-8)

Both look like a ton of work and are not really complete. We could use catalog's next plan, and create a whole new repo (inventory.data.gov) to work on inventory-next and then easily create a snyk scan via the UI. Thoughts @adborden @FuhuXia?

**Comment by jbrown-xentity** [comment]
Snyk added our account to the beta, it is now scanning both repositories!
[inventory-classic](https://app.snyk.io/org/data.gov/project/ebc2495d-0dea-47d5-b623-86caed4b7bae)
[inventory-next](https://app.snyk.io/org/data.gov/project/4a97baff-91fa-4489-9d10-0f6ac9ddee06)

Both can be seen on the [projects page](https://app.snyk.io/org/data.gov/projects)
