### ISSUE TITLE
Netsparker 2020-09-22 reports jquery out-of-date

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2254]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.ym51y6s86z8y)._

**Date of report:** 2020-09-18
**Severity:** Medium
**Due date:** 2020-12-18

### Brief description
jQuery out-of-date.

Affecting Inventory and Catalog. [Details](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.ym51y6s86z8y)

**Comment by mogul** [comment]
We're expecting this to be resolved by rolling out inventory-next and catalog-next.

**Comment by pjsharpe07** [comment]
This appeared on this month's netsparker report as well

**Comment by adborden** [comment]
Going into POAM land 🤞

**Comment by jbrown-xentity** [comment]
Validate catalog is done, confirm inventory-next *should* pass. To close, verify inventory is passing once #2858 is done.

**Comment by jbrown-xentity** [comment]
Verified catalog production and inventory next is using jquery > 3.5.0. Moving to blocked until #2858 is done...
