### ISSUE TITLE
Implement GSA fork of usmetadata on inventory-next

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2261]
## User Story

As a data.gov developer, I want to reduce forked code so that ongoing maintenance is simpler and safer.

## Acceptance Criteria
- [ ] GIVEN the inventory-next application is using the GSA usmetadata extension
  WHEN I run the inventory playbook
  THEN the playbook runs without error
  AND the app functions as expected
  AND the usmetadata extension functions as expected

## Background
We currently use the Datopian fork of usmetadata on inventory-next [see requirements file](https://github.com/GSA/inventory-app/blob/inventory_ckan_2.8/requirements.txt#L3). We would like to be using [GSA's usmetadata extension](https://github.com/GSA/USMetadata) instead.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
Dependency issues in GSA's usmetadata repo should be resolved.

## Sketch
- [ ] Merge Datopian's changes upstream to the GSA-owned repo (on a branch specific to CKAN 2.8)
- [ ] Change the requirements file and update the dependencies & requirements-freeze file through make commands
- [ ] Run app locally and test
- [ ] Iterate on ^^ until the app works as expected.

**Comment by pjsharpe07** [comment]
It looks like there is [an old PR](https://github.com/GSA/USMetadata/pull/39) that started this work.

**Comment by nickumia-reisys** [comment]
Data.gov is the primary maintainer of usmetadata,
- https://github.com/GSA/ckanext-usmetadata
