### ISSUE TITLE
GSA usmetadata extension is under CI/CD

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2262]
## User Story

**ticket needs grooming**

As a data.gov developer, I want confidence that I am not committing bad code through ci/cd.

## Acceptance Criteria
- [ ] GIVEN I have configured circleci on usmetada repo
  WHEN I make a commit into this repo
  THEN circleci runs tests

## Background
Currently circleci is not configured to run on [GSA's usmetadata repo](https://github.com/GSA/USMetadata). We might not have to write tests as [there is a test folder](https://github.com/GSA/USMetadata/tree/master/ckanext/usmetadata/tests) and tests are mentioned [in the readme](https://github.com/GSA/USMetadata#tests)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch
- [ ] Investigate the currents tests on this repo and make changes as necessary
- [x] configure ci
- [ ] commit and iterate as necessary

**Comment by adborden** [comment]
lgtm.
