### ISSUE TITLE
Add New Relic Application agent for catalog

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2263]
## User Story

As a catalog administrator, I want need catalog configured with New Relic so that I can can monitor and evaluate blocking requests/weak points in the system.

## Acceptance Criteria

- [ ] GIVEN the catalog playbook is run on staging and production \
  WHEN I look at New Relic UI \
  THEN I can see the different applications and machines \
  AND a breakdown of the different components of the application

## Background
We currently have language-specific playbooks to deploy and configure New Relic for applications. However, this has some deficiencies. The platform has to know details about the application, environments, app names, configuration settings. The platform has to know where to install hooks within the application (wsgi, worker scripts, etc). The platform might install conflicting versions of dependencies, outside of application pinned dependencies. The platform installing New Relic might cause an extra restart, prolonging any service disruption during deploy.

Related to #174.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, New Relic is already installed, just tweaking the configuration.

## Sketch
- [x] Remove the python-agent-ansible role from catalog-next playbook
- [x] Add new relic python to dependency list
- [x] Add new relic addition/configuration to gunicorn ([look for best practices](https://docs.newrelic.com/docs/agents/python-agent/web-frameworks-servers/python-agent-gunicorn-wsgi-web-server))
- [x] Use [environment variables instead of config file](https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration) so usage depends on environment and not changing config file (see current config for what can/should be overwritten)
    - Turn off [monitor mode](https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration#monitor_mode) in local environment.

**Comment by jbrown-xentity** [comment]
Specific to catalog, we need to:
- [ ] Remove the python-agent-ansible role from catalog-next playbook
- [ ] Add new relic python to dependency list
- [ ] Add new relic addition/configuration to gunicorn ([look for best practices](https://docs.newrelic.com/docs/agents/python-agent/web-frameworks-servers/python-agent-gunicorn-wsgi-web-server))
- [ ] Use [environment variables instead of config file](https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration) so usage depends on environment and not changing config file (see current config for what can/should be overwritten)
    - Turn off [monitor mode](https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration#monitor_mode) in local environment.

**Comment by jbrown-xentity** [comment]
Not sure how to proceed. Gunicorn implementation is only done at the ansible level as part of supervisor, the docker system implements the OKFN docker build which [starts the application using UWSGI](https://github.com/okfn/docker-ckan/blob/master/ckan-base/setup/start_ckan.sh#L43) (or possibly [paster serve](https://github.com/okfn/docker-ckan/blob/master/ckan-dev/setup/start_ckan_development.sh#L81)?). Not sure what the best practice is at this point to add new relic in as part of the application. @adborden

**Comment by adborden** [comment]
Just summarizing the conversation from sync, not sure if you have any updates since then:

This is probably a two-part story (or two stories). First, let's add a start.sh script that calls newrelic-admin and gunicorn. Then update datagov-deploy to run the start.sh as part of the application (update the supervisor configuration).

The second part would be to get the start.sh integrated into the development workflow. That could end up being a number of things. Maybe we replace OKFN image with a Dockerfile and call start.sh OR maybe it's a feature request for the OKFN image to call a start.sh and then we just overwrite the start.sh file as part of the docker build.

**Comment by jbrown-xentity** [comment]
Current work is being tested on the [feature/new-relic branch](https://github.com/GSA/catalog.data.gov/tree/feature/new-relic).
Was able to get version of the bash script working from supervisor on sandbox. Still need to add the following:

- Configure path to include /usr/lib/ckan/bin/gunicorn and new-relic from python install in ansible, or make script variable to pass full path.
- Add new relic variables in vault as environment variables in the catalog playbook
    - newrelic_license_key
    - newrelic_app_name
    - monitor_mode
    - log_file
    - log_level
    - host (NEW_RELIC_HOST)

**Comment by jbrown-xentity** [comment]
@adborden it looks like configuring the path is untenable, I will just map variables between docker and ansible in the environment and call it a day. Should I use [the environment setting in supervisor](http://supervisord.org/subprocess.html#subprocess-environment) to specify the values, as that file is already a template in datagov-deploy and is the go-between on platform and application? Or should this be specified somewhere else, as some kind of script?

*Update*: The environment installs a .env script into the local directory for the ckan web server script, and the script looks for and tries to read in that file if it exists.

**Comment by jbrown-xentity** [comment]
[Requested added feature upstream](https://github.com/okfn/docker-ckan/issues/53).
