### ISSUE TITLE
CDOs can easily run their own CKAN*

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2267]
## Feature/what we're after
An agency CDO can deploy a production-worthy, compliant CKAN service in less than a day.

## Anticipated/hypothesized benefits
- Dramatically reduce the acquisition, development, and operations effort/cost for federal agencies to start running their own CKAN data service
- Reduce the compliance effort needed to put a CKAN deployment through an agency ATO process
- Agency CDOs contribute back to a common CKAN distribution/deployment/management repository

## Measurements/metrics
- How long does it take someone unfamiliar with CKAN to get a working deployment up and running?
- How long does it take to create compliance documentation suitable for submitting the deployment to the local A&A process?

## References/background
- We've had agencies approach us about replicating inventory.data.gov... That is, they need to run their own data catalog/hosting service for their agency's local usage, whether for private or public data. They want to learn from how we operate data.gov, but the current deployment method in BSP is not easily for them to replicate.
- The hope here is that we can leverage our own IaC deployment of inventory.data.gov to cloud.gov, along with GitHub Actions and the Terraform Cloud Foundry provider, to provide a turnkey deployment of CKAN ready for agency use. We can also provide compliance documentation covering the non-agency-specific aspects of that deployment.

**Comment by hkdctol** [comment]
This epic has been entered into github projects https://github.com/orgs/GSA/projects/11/views/4
