### ISSUE TITLE
s3Filestore not working for inventory-next

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2268]
S3 extension is able to save the dataset on s3, but is unable to extract it (gives a 500 internal server error when you try). This *seems* to break datapusher, but datapusher works fine as long as it can download the file.

## How to reproduce

1. Upload a new resource on an inventory-next deployment
1. Download that resource that was just uploaded

## Expected behavior

Download completes

## Actual behavior

Download fails with 500

**Comment by FuhuXia** [comment]
fixed with https://github.com/GSA/ckanext-s3filestore/pull/1
