### ISSUE TITLE
[research: 4h] Catalog returns 500 for some datasets

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2273]
Came across a list of datasets.  Clicking on one of them leads to a 500 error. Need to look for the cause and see if it is specific to this dataset, or it affects many others as well.

## How to reproduce

From https://catalog.data.gov/dataset?groups=local#topic=local_navigation, the [Local Weather Archive](https://catalog.data.gov/dataset/local-weather-archive) is listed as 3rd one from top.

## Expected behavior

200 response

## Actual behavior

500 error

**Comment by mogul** [comment]
We're going to timebox 4 hours to investigate whether this is indicative of a more widespread problem, and whether it's a problem in catalog-next.

**Comment by nickumia-reisys** [comment]
Seeing as this is still occurring, it was not a problem specific to `catalog-next`....  See the following issue for more details?  Maybe?
- https://github.com/GSA/data.gov/issues/4444
