### ISSUE TITLE
Pycsw tests

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2276]
## User Story

As a data.gov admin, I want CircleCi tests added to the [pycsw repo](https://github.com/GSA/pycsw) so that I know if new/updated code will break releases.

## Acceptance Criteria

- [ ] WHEN a push is made to the GSA/pycsw repository \
  THEN cicleCi tests are run \
  AND any failures results in an inability to merge the broken changes

## Background
https://github.com/GSA/pycsw/pull/19#pullrequestreview-507615934

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
Upstream uses [travis.yml file](https://github.com/GSA/pycsw/blob/datagov/v2.4.x/.travis.yml). We should run the upstream tests in CircleCI.

**Comment by nickumia-reisys** [comment]
No more pycsw.
- https://github.com/GSA/data.gov/issues/3182
