### ISSUE TITLE
[Offboard] paul.walker@gsa.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2279]
These tasks are performed by an Admin unless noted as an action for the outgoing team member.

- [x] Team member should move all Data.gov related documents to team drives
- [x] Team member should document any work in progress and schedule a hand-off for any remaining tasks
- [x] Remove team member's access to the [shared Google Drive](https://drive.google.com/drive/folders/0AMRwhrSyJ5R4Uk9PVA)
- [x] Remove team member from Data.gov GitHub teams
  - [data-gov-admins](https://github.com/orgs/GSA/teams/data-gov-admin/members)
  - [data-gov-support](https://github.com/orgs/GSA/teams/data-gov-support/members)
  - [data-gov-ckan-multi-partners](https://github.com/orgs/GSA/teams/data-gov-ckan-multi-partners)
- [x] Remove team member from [the `gsa-datagov` organization](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/90047c5d-337f-4802-bd48-2149a4265040/users) on cloud.gov
- [x] Remove team member from [GCP account](https://console.cloud.google.com/iam-admin/iam?project=tts-datagov)
- [x] Remove team member from AWS OPP account
- [x] Remove team member from [AWS sandbox access](https://github.com/GSA/datagov-infrastructure-live/tree/master/iam#new-users)
- [x] Disable team member in [jumpbox operators](https://github.com/GSA/datagov-deploy/blob/develop/ansible/group_vars/all/vault.yml) **set `active: false`** (removing them from the list will leave the account active https://github.com/GSA/datagov-deploy/issues/1837)
- [x] Remove team member from Data.gov email lists
  - [Data.gov support list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagov)
  - [Data.gov team list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagovhelp)
- [x] Remove team member from [Data.gov calendar](https://calendar.google.com/calendar/r/settings/calendar/Z3NhLmdvdl9zcjZ0NG52YjRhOTNjNnNzdHRxYXAzbjZtMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) and events
- [x] Remove team member from [New Relic](https://newrelic.com)
- [x] Remove team member from [Docker Hub](https://cloud.docker.com/orgs/datagov/teams)
- [x] Remove team member from [Data.gov system accounts](https://github.com/GSA/datagov-deploy/wiki/CKAN-commands#system-administrator-accounts) on Inventory and Catalog
- [x] Remove team member from TTS Bug Bounty access [#bug-bounty-partners](https://gsa-tts.slack.com/messages/C5JQCD9PH)
- [x] Remove team member from [Snyk](https://app.snyk.io/org/data.gov/manage/members)
- [x] Remove team member from [Agari](https://gsa-tts.bp.agari.com/) (see [#admins-dmarc](https://gsa-tts.slack.com/archives/CNDTG5ML5) or @adborden for access)
- [x] [Rotate Ansible Vault key](https://github.com/GSA/datagov-deploy/wiki/Keypair-Rotation#ansible-vault) and [update the canonical location](https://docs.google.com/document/d/1detdsnIuwmqz6asrIfUWrmxCr56MGschY1yV0UeC_24/edit)
- [x] Remove team member from Slack

If the team member is also leaving GSA:
- [x] Request the user be removed from Federalist by posting to [#federalist-support](https://gsa-tts.slack.com/archives/C1NUUGTT5) with the member's GitHub username
- [x] Remove access from [GSA GitHub org](https://github.com/GSA/GitHub-Administration/blob/master/README.md#removing-access-to-the-gsa-organization)
- [x] Create "Offboard from GSA IT" ticket
- [x] Notify HSPD-12 if needed

**Comment by hkdctol** [comment]
@adborden the checklist should have a Remove from Slack item (done) and under the leaving GSA section, also a "Create Offboard from GSA IT ticket" and "Notify HSPD-12 if needed" (both done)
