### ISSUE TITLE
Add SOLR hosts for inventory-next

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2284]
## User Story

As a data.gov developer, I want to have a set of SOLR instances set up in BSP production environment so that they are ready to serve as SOLR servers for inventory-next hosts.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I SSH into prod jumpbox \
  AND `cd /datagoiv-deploy/ansible` \
  WHEN I run `pipenv run ansible -m ping solr-next` \
  THEN I see  `pong` responses from three hosts

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
We can use existing SOLR instances as template to create these new instances so they will be created in the right APP tier.

## Sketch
- [x] Request new instances (BSP ticket)

After new insantances are ready, follow the [Adding New Host](https://docs.google.com/document/d/11_cYR1h75b6tOdQKHzPE5MfQA6BJ5Hh1yYv2pdcn2nc) doc and
- [x] Add new partitions
- [x] ~~Request firewall change (BSP ticket)~~
- [x] Add new host to our inventory

**Comment by FuhuXia** [comment]
RITM0777433 is created for three EC2 instances.
```
datagov-solrm1p-v2.prod-ocsit.bsp.gsa.gov
datagov-solr1p-v2.prod-ocsit.bsp.gsa.gov
datagov-solr2p-v2.prod-ocsit.bsp.gsa.gov
```

**Comment by adborden** [comment]
@FuhuXia re: firewall, I think we're already set here. Solr hosts should receive the APP tier for trendmicro policy in datagov-deploy. No BSP ticket necessary.

**Comment by FuhuXia** [comment]
@adborden I see. I thought they have rules set for individual ips within a tier. Now it sounds like the rule apply for all ips of the same tier. We already have SOLR v1 set before so we are good. I will checked the firewall off the list.

**Comment by FuhuXia** [comment]
RITM0777433 is completed. Three EC2's are ready.

**Comment by FuhuXia** [comment]
`/data` and `/var/log` partitions are added.
