### ISSUE TITLE
inventory-next deployment in production

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2285]
## User Story

In order to have confidence in our upcoming [inventory-next switchover](https://github.com/GSA/datagov-deploy/issues/2248), the team wants inventory-next up and running in production, irrespective of switchover plan yet to be tested.

## Acceptance Criteria
- [x] GIVEN the inventory playbook has been run in production \
  WHEN I look at the bionic inventory hosts \
  THEN I can see that CKAN 2.8 is installed

## Background
Similar to inventory-next [staging deployment](https://github.com/GSA/datagov-deploy/issues/2118)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
The deployment will use our usual processes for staging/production rollouts, and not introduce any new process or components where security problems are likely to appear.

## Sketch
Inventory-next prerequisites were captured in story #2118.

The RDS are snapshots from production DB for CKAN 2.5, not 2.8. We might want to manually add some blank DB entries, and use the new DB entries in the playbook for the initial deployment. After things are verified, we then change the Ansible playbook variable to point to the migrated DB entries to test migration.

**Comment by mogul** [comment]
Closing this as the production environment deployment #2272  already includes this task.
