### ISSUE TITLE
catalog.data.gov and admin-catalog.data.gov unavailable after 20201015 release

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2287]
During production rollout of [catalog.data.gov release](https://github.com/GSA/datagov-deploy/issues/2251), we received alerts that catalog.data.gov and admin-catalog.data.gov were unavailable. We started our [incident response](https://docs.google.com/document/d/19YhtdNZ3x9n3FJLWmue3XH9drxn8PVTHGnpeu-gdtao/edit#) and resolved by rolling back the release.

We saw that catalog-bsp.data.gov was down, indicating an issue between NetScaler and the catalog-web hosts, or possibly a configuration issue effecting NetScaler's health check.

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by FuhuXia** [comment]
Among [all the changes](https://github.com/GSA/datagov-deploy/pull/2280/files) in this release, most likely changes in file  `etc_apache2_sites-enabled_ckan.conf.j2` in [this commit](https://github.com/GSA/datagov-deploy/commit/884de1995ab3ee6ab9873063a253f0e6f7ce1075) is to blame.

Effectively, using catalog-web1p as example, this changes content of file `/etc/apache2/site-enabled/ckan.conf` from 
```
<VirtualHost 0.0.0.0:80>
  ServerName ckan
...
```
to 
```
<VirtualHost 0.0.0.0:80>
  ServerName ckan
  Redirect 404 /
</VirtualHost>

<VirtualHost 0.0.0.0:80>
    ServerName catalog.data.gov
      ServerAlias localhost
    ServerAlias catalog-web1p.prod-ocsit.bsp.gsa.gov
...
```

Still trying to figure out why this change made server unavailable.

**Comment by FuhuXia** [comment]
It turns out NetScaler is using IP addresses to do the health check. We can either request to reconfigure NetScaler to use hostnames, or we add the IP address as ServerAlias into apache conf.

**Comment by adborden** [comment]
FWIW, I think AWS ALB health check also works this way, so by using the IP address in the ServerName/ServerAlias, it would satisfy both health checks. We're doing something similar in our nginx configuration.
