### ISSUE TITLE
Confirm this is a template and not the content encypted by Ansible Vault

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#229]
@alex-perfilov-reisys 
https://github.com/GSA/datagov-deploy/blob/3f0b488fbc0c89f3aa44db17acb7fdb9f27d5e97/ansible/roles/monitoring/efk-nginx-saml/defaults/main.yml#L16-L31

**Comment by vasili4** [comment]
true that's just test key for https://www.testshib.org 
https://github.com/GSA/datagov-deploy/blob/3f0b488fbc0c89f3aa44db17acb7fdb9f27d5e97/ansible/roles/monitoring/efk-nginx-saml/defaults/main.yml#L10

**Comment by JJediny** [comment]
thx @alex-perfilov-reisys
