### ISSUE TITLE
Syslog error in Logrotate Cron job

### ISSUE THREAD

**Issue by srinirei** [GSA/data.gov#2294]
/etc/cron.daily/logrotate:
error: syslog:1 missing '{' after log files definition
error: found error in file syslog, skipping

The email originated from instance "catalog-web2d.dev-ocsit.bsp.gsa.gov"

## How to reproduce

cron email notification.

## Expected behavior

log files being rotated by logrotate

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
