### ISSUE TITLE
Entering text for tags without hitting Tab results in "Tags are required" error

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2297]
Text has been entered into the field but on submit we see the "Tags are required" error.

<img width="482" alt="Screen Shot 2020-10-15 at 4 44 55 PM" src="https://user-images.githubusercontent.com/509703/96197063-d3f16d80-0f05-11eb-94ae-ff1231623cfd.png">

![Screen Shot 2020-10-15 at 3 15 26 PM](https://user-images.githubusercontent.com/1392461/96175729-4ad43980-0ef9-11eb-92e0-b5aaa645e884.png)

**Work around:** after entering text for Tags field, hit the Tab key to enter the text as a tag.

## How to reproduce

1. Log into https://inventory.sandbox.datagov.us and create a new dataset. Fill in required fields.
1. For Tags field, enter "abcd" but do not hit Tab
1. Click on the next field
1. Complete other required fields
1. Click Save and Continue

## Expected behavior

Text in Tags field is submitted as a tag and the dataset is created successfully.

## Actual behavior

Submission fails, error message "Tags are required"

**Comment by mogul** [comment]
@adborden is going to connect with the CKAN multi team to talk about this one.

**Comment by adborden** [comment]
Updated the issue with more details and included a work around. I don't think this is a blocker for shipping the form or for shipping inventory-next.
