### ISSUE TITLE
Staging Inventory/Catalog SAML2 login error

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2305]
Staging Inventory and Catalog SAML2 login stopped working today. They gave 500 error after test.login.max.gov authentication. Error log shows message:
```
KeyError: 'maxemail' 
```

![Screen Shot 2020-10-19 at 12 45 39 PM](https://user-images.githubusercontent.com/1392461/96493626-35ba1c00-1213-11eb-97a0-79e86a5cca1f.png)

## How to reproduce

On staging, go the inventory staging site, click login and go thru test.login.max.gov authentication.

## Expected behavior

Successful login

## Actual behavior

500 Error.

**Comment by FuhuXia** [comment]
Upon examining the saml info returned from test.login.max.gov, it shows `maxemail` does not exist. There is a key `emailaddress`. It seems test.login.max.gov changed their specs.

Email sent to MAX support asking about the change.

**Comment by mogul** [comment]
According to MAX, they've resolve the issue on their side (and they didn't intend to introduce any breakage for us). We still need to verify.

**Comment by FuhuXia** [comment]
Verified the issue is resolved with test.login.MAX.GOV fix. No change done on our side.

> FROM MAX.GOV SUPPORT:
> The upgrade we did in test this weekend inserted a "FriendlyName" on all the attributes, so that the attribute with a Name of "maxEmail" is given a friendly name of "EmailAddress".  It seems that your SAML integration library is choosing to map the "FriendlyName" when faced with an attribute that has both a "Name" and a "FriendlyName".  Our spec, such that it is, assumes integrators will use the "Name".
> 
> We'll update our configuration such that "FriendlyName" and "Name" match in a few minutes, but if you can update your system to use the "Name" as the attribute name rather than "FriendlyName", that will work too.
