### ISSUE TITLE
Incorrect link within https://www.data.gov/open-gov/

### ISSUE THREAD

**Issue by crysacarter** [GSA/data.gov#2316]
Related to #2320, see comments in that ticket for resolution details.

## How to reproduce

1. Description of steps to reproduce the issue.

https://www.data.gov/open-gov/ 
list views
international 
Indonesia 

## Expected behavior

link to https://data.go.id/

## Actual behavior

 links to http://satupemerintah.net/ which is dating site

**Comment by jbrown-xentity** [comment]
@FuhuXia I think this is where it needs to be edited... https://github.com/GSA/data.gov/blob/master/roots-nextdatagov/assets/LeafletMap2/data/international.geojson
