### ISSUE TITLE
Migrate to new email service

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2321]
## User Story

In order to gain more reliability into delivery of Data.gov's harvest report emails, agency data managers want data.gov to move to a new email service compatible with cloud.gov and non-GSA domains.

## Acceptance Criteria
- [x] GIVEN I run `cf login -a api.fr.cloud.gov --sso` and authenticate \
  AND I run `cf target -o gsa-datagov -s <development|staging|production>`  \
  WHEN I run `cf marketplace` \
  THEN I see an AWS SES service and plans listed
- [x] GIVEN I run `cf login -a api.fr.cloud.gov --sso` and authenticate \
  AND I run `cf target -o gsa-datagov -s <development|staging|production>`  \
  WHEN I run `cf create-service csb-aws-ses common datagov-ses -p ` \
  THEN I see the instance is running
  AND I can `cf bind-service <app-name> <instance-name>` \
  AND I can see SMTP credentials for the AWS SES instance in `cf env <app-name>`
  AND I can see a successful mail delivery when I use those credentials for sending mail.

## Background
https://github.com/GSA/datagov-deploy/issues/507

This could happen via a PR to [csb-brokerpak-aws](https://github.com/GSA/csb-brokerpak-aws), but we need to weigh that route's compliance impact vs other options, if any.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This will be a new brokered service provided by the SSB. We will need to extend our SSP content to include SES wherever we already reference Solr.

## Sketch

- [ ] Add a new [service manifest](https://github.com/GSA/csb-brokerpak-aws) ([upstream docs](https://github.com/cloudfoundry-incubator/cloud-service-broker/tree/master/docs)) and [terraform directory](https://github.com/GSA/csb-brokerpak-aws/tree/main/terraform) to csb-brokerpak-aws.
- [ ] Configure SES using the Terraform AWS provider.
  - Example of [verifying DNS and certificates automatically using Terraform](https://github.com/GSA/eks-brokerpak/blob/c2d1bdeacdc092c758f9178f9fa08854aea3a117/services/terraform/eks-provision.tf#L504-L577).
- [ ] Add tests for the new SES service
- [ ] Create new compliance diagrams for the SES service, based on the [existing diagrams for the Solr service](https://github.com/GSA/datagov-compliance/blob/main/ssb-service-scratchpad.md).
- [ ] Add the diagrams and necessary control narratives to the SSB SSP.

**Comment by adborden** [comment]
Adding that for cloud.gov we need a new email service anyway. This would cover more than just harvesting.

**Comment by adborden** [comment]
Just a reminder, production DNS for data.gov is still managed by GSA so I don't think we'll be able to automate much DKIM or SPF with terraform.

**Comment by FuhuXia** [comment]
Terraform part of this story is being addressed in this branch. https://github.com/FuhuXia/csb-brokerpak-aws/tree/aws-ses
The binding outputs include `ses_smtp_server`, `ses_smtp_user`, and `ses_smtp_password`. 

`ssb-dev.datagov.us` is hard coded as a default domain, since that is the only domain I found available in the route53, no DKIM during the provisioning.

Next step will be releasing the brokerpak and trying it on cloud.gov.

**Comment by FuhuXia** [comment]
PR https://github.com/GSA/csb-brokerpak-aws/pull/16 created.

**Comment by mogul** [comment]
I moved this back to `In Progress` until the .brokerpak is actually being deployed by the SSB.
