### ISSUE TITLE
Add New Relic Application Agent to Inventory-next

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2328]
## User Story

As an inventory administrator, I want inventory configured with New Relic so that I can can monitor and evaluate blocking requests/weak points in the system.

## Acceptance Criteria

- [x] GIVEN the inventory playbook is run on staging
  WHEN I look at New Relic UI \
  THEN I can see the different applications and machines \
  AND a breakdown of the different components of the application

## Background
We currently have language-specific playbooks to deploy and configure New Relic for applications. However, this has some deficiencies. The platform has to know details about the application, environments, app names, configuration settings. The platform has to know where to install hooks within the application (wsgi, worker scripts, etc). The platform might install conflicting versions of dependencies, outside of application pinned dependencies. The platform installing New Relic might cause an extra restart, prolonging any service disruption during deploy.

Related to #174.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, New Relic is already installed, just tweaking the configuration.

**Comment by jbrown-xentity** [comment]
@pjsharpe07 you'll want to examine the following PR's for catalog-next to do for inventory:

- https://github.com/GSA/datagov-deploy/pull/2317
- https://github.com/GSA/catalog.data.gov/pull/149

**Comment by pjsharpe07** [comment]
I believe we still need two more edits to [enable the role for inventory-next](https://github.com/GSA/datagov-deploy/blob/develop/ansible/inventory.yml#L70) and [datagov_in_service](https://github.com/GSA/datagov-deploy/blob/aa63abd91eed093fd3216a3ef6350010753ac486/ansible/inventories/staging/group_vars/inventory-web-v2/vars.yml#L2).

**Comment by jbrown-xentity** [comment]
The former link is to the old new relic implementation, which we will leave as is until inventory-next is live and replaced inventory-classic on production. And the second one can be removed, it's not being utilized.

**Comment by pjsharpe07** [comment]
The inventory-next part of [this ticket](https://github.com/GSA/datagov-deploy/issues/174)
