### ISSUE TITLE
Automate AWS infrastructure via Terraform

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#233]
Automate AWS infrastructure via Terraform for application
- [x] Catalog
- [ ] data.gov WP
- [ ] inventory
- [ ] CRM
- [ ] Labs Dashboard
- [ ] Jekyll Sites
- [ ] Jumpbox
- [ ] ES and Kibana

**Comment by adborden** [comment]
We have terraform templates for our sandbox environments https://github.com/GSA/datagov-infrastructure-live
