### ISSUE TITLE
Inventory-next no navigation links for anonymous user

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2331]
Issue #2314 tracks what page to show to anonymous user, but when the dataset page is shown, there are no navigation links.

## How to reproduce

1. Open chrome incognito and visit inventory-next site without logging in.

## Expected behavior

If dataset page is shown, there should be navigation links.
![Screen Shot 2020-10-23 at 4 15 00 PM](https://user-images.githubusercontent.com/1392461/97050192-ee04fe80-154a-11eb-890d-ec9969f1aa50.png)

## Actual behavior

No navigation links
![Screen Shot 2020-10-23 at 4 07 02 PM](https://user-images.githubusercontent.com/1392461/97049519-d8430980-1549-11eb-9e48-d2990f922d96.png)

**Comment by mogul** [comment]
The proper behavior depends on the resolution of the discussion in #2314 ... If anonymous users see data sets, then they should also see navigation links.

**Comment by FuhuXia** [comment]
No longer an issue after Inventory 2.8 roll out. Navigation links are visible.
