### ISSUE TITLE
ckanext-archiver writes to /tmp/archive and fills up disk in 2 hours

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2333]
I'm not sure what caused this, but I'm seeing an alert for [low disk space on catalogharvester2d](https://one.newrelic.com/launcher/nrai.launcher?pane=eyJuZXJkbGV0SWQiOiJhbGVydGluZy11aS1jbGFzc2ljLmluY2lkZW50cyIsIm5hdiI6IkluY2lkZW50cyIsImluY2lkZW50SWQiOiIxNzQ3OTgyMDEifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucmFpLm5hdmlnYXRpb24tYmFyIiwibmF2IjoiSW5jaWRlbnRzIn0=&platform[accountId]=1601367&platform[timeRange][duration]=604800000&platform[$isFallbackTimeRange]=true). The jobs are disabled in cron, so I'm not sure what triggered this.

<img width="382" alt="Screen Shot 2020-10-23 at 1 50 31 PM" src="https://user-images.githubusercontent.com/509703/97053070-0bc86880-1537-11eb-9cd2-7b789bf1e081.png">

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by nickumia-reisys** [comment]
Good historical reference for
- https://github.com/GSA/data.gov/issues/3986
