### ISSUE TITLE
Inventory-next: resource description shows HTML <p></p> tag

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2339]
resource description shows HTML tag such as `<p>Some resources description</p>`

## How to reproduce
1. Go to inventory-next site
1. Add a new resource to an existing dataset
1. Provide a Markdown description (no HTML tags), and submit the form to add the resource.
1. Go to the newly added resource page.

## Expected behavior
Description is displayed normally.

## Actual behavior
Description is wrapped with `<p></p>`.

![Screen Shot 2020-10-26 at 12 44 28 PM](https://user-images.githubusercontent.com/1392461/97202062-85579500-1789-11eb-9161-d8562d0974db.png)

**Comment by adborden** [comment]
The form is supposed to accept markdown, so we might want to update the reproduction steps to include that.

**Comment by FuhuXia** [comment]
Still an issue after inventory 2.8 roll out.

**Comment by jbrown-xentity** [comment]
This has been fixed, closing.
