### ISSUE TITLE
Task: upgrade postgres databases from EOL 9.5

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2344]
## User Story

Due: 02/16/2021

On February 16th, 2021, Postgresql 9.5 will be End of Life in AWS's RDS service. These databases must be removed or upgraded.

## Background
You will need to coordinate with BSP in order to address these.

BSP prod:
- ~datagov-datapusher-2020-09-23-06-23~ _datagav-datastore-next is running 9.6_
- ~datagov-inventory2~ _datagav-inventory-next is running 9.6_
- ~datagovcatalog95~ _catalog-next is running 9.6_
- ~datagov-inventory~ _datagav-inventory is running 9.6_
- ~datagov-pycsw~ _csw is being decommissioned_
- ~datagov-datapusher~ _datagav-datastore is running 9.6_

BSP dev:
- ~datagov-datapusher-2020-09-23-05-45~ _datagav-datastore-next is running 9.6_
- ~datagovcatalog~ _catalog-next is running 9.6_
- ~datagov-datapusher~ _datagav-datastore is running 9.6_
- ~datagov-pycsw~ _csw is being decommissioned_

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
You can [upgrade a snapshot](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBSnapshot.PostgreSQL.html) before it is turned on. 
This could be useful for inventory2, to upgrade the DB at the same time as Inventory2.8 to avoid any future downtime...

**Comment by adborden** [comment]
Good to know. I don't think we want to increase the scope of the inventory-next release. @FuhuXia has already started [testing the existing rollout plan](https://github.com/GSA/datagov-deploy/issues/2248) which doesn't include the postgresql upgrade.

Getting onto CKAN 2.8 is the priority so we shouldn't be tacking on additional work like re-writing our plan, re-testing the plan, and testing/tuning a database upgrade. Downtime isn't really a concern for us on inventory so I wouldn't let that distract us from inventory-next. Since the postgres upgrade has plenty of runway, it's not a priority at the moment.

**Comment by jbrown-xentity** [comment]
Need to split this into 4 tickets, to be handled separately: catalog, inventory, csw, and datapusher.
