### ISSUE TITLE
Pipenv upgrade broken

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2353]
When an upgrade is run for datagov-deploy (`pipenv update`), the system breaks trying to update ansible to 2.10.x. We have pinned ansible to 2.8.x. If you uninstall and re-install ansible, then the pipenv update works, but adds `ansible-base` version 2.10.x. This causes the whole system to not work as expected.

```
Cannot install ansible-base with a pre-existing ansible==2.8.16
[pipenv.exceptions.InstallError]:       installation.
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:       Installing ansible-base with ansible-2.9 or older currently installed with
[pipenv.exceptions.InstallError]:       pip is known to cause problems. Please uninstall ansible and install the new
[pipenv.exceptions.InstallError]:       version:
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:           pip uninstall ansible
[pipenv.exceptions.InstallError]:           pip install ansible-base
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:       If you want to skip the conflict checks and manually resolve any issues
[pipenv.exceptions.InstallError]:       afterwards, set the ANSIBLE_SKIP_CONFLICT_CHECK environment variable:
```

### Mitigation
Remove the ansible-base code manually from the `Pipfile.lock` as per [this commit](https://github.com/GSA/datagov-deploy/pull/2347/commits/1dc6b39dd24e9bfb2b646557be53bfdc1a787440#diff-a86c67a0a29ed0e95909b9b7c420140f302d17399ee6dcce4e1a51a14d27fd51)

## How to reproduce

1. Run `pipenv update`

## Expected behavior

`Pipfile.lock` file is created without errors.

## Actual behavior

Error occurs

**Comment by adborden** [comment]
This looks like an ansible bug to me or maybe molecule. Let's try to create a simple repro with just pip and a requirements file. It seems like ansible<2.10 conflicts with ansible-base, so it looks like something is pulling in ansible-base when it shouldn't.

Have we looked into that work-around, setting `ANSIBLE_SKIP_CONFLICT_CHECK`?

**Comment by nickumia-reisys** [comment]
No more Ansible,
- https://github.com/GSA/data.gov/issues/3710
