### ISSUE TITLE
Validate key use-cases are working on inventory-next

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2362]
## User Story

In order to be confident that we have identified issues blocking production rollout of inventory 2.8, we want to validate that all key inventory use-cases work in the staging environment and create issues for blockers encountered.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

GIVEN credentials for an agency account \
WHEN I visit inventory.dat.gov I can successfully
- [x] ...log in with my existing credentials 
- [ ] ...create a new data set -- not checking this one off, but we do have WIP around this
- [x] ...edit an existing data set
- [x] ...export a data.json file
- [x] ...list data sets using the API
- [x] ...update a data set using the API
- [ ] ...load a CSV into datastore - see details below
- [x] ....delete a dataset

GIVEN credentials for a sysadmin \
WHEN I visit inventory.dat.gov I can successfully
- [x] ...add a user
- [x] ...delete a user
- [x] ... edit a user
- [x] CRUD with an organization

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by pjsharpe07** [comment]
Keeping some running notes in [this google sheet](https://docs.google.com/spreadsheets/d/1wilEacIMO2c2tJZjrAN_s2U1rak-wE1zVUau3z-B7zo/edit#gid=0)

**Comment by pjsharpe07** [comment]
Cannot upload csv to datastore:

Steps to reproduce om sandbox:
1. Navigate to https://inventory-next.sandbox.datagov.us/dataset/test123/resource/31e3cba0-3fa8-4b9f-becf-20c144fd21a7
2. Click `Manage`
3. Select `DataStore` icon
4. Select `Upload to DataStore` button

You should receive this error message. 
![image](https://user-images.githubusercontent.com/38019872/98171696-60f86880-1ead-11eb-909c-61585c6a4434.png)

Not sure if this is related to https://github.com/GSA/datagov-ckan-multi/issues/488 or not.

**Comment by pjsharpe07** [comment]
Datasets successfully created and updated on sandbox and staging.
