### ISSUE TITLE
Inventory Ansible role does not restart supervisor web service after a deploy

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2364]
## How to reproduce

1. Apply the inventory playbook `ansible-playbook inventory.yml`
1. From an inventory machine, check supervisor `ssh inventory1d.dev-ocsit.bsp.gsa.gov sudo supervisorctl restart gunicorn-web-app`

## Expected behavior

Supervisor web service is running for less than a minute

## Actual behavior

```
gunicorn-web-app                 RUNNING    pid 19511, uptime 7 days, 8:09:48
```

**Comment by jbrown-xentity** [comment]
Verified on inventory-next in staging. After running the site playbook, we got the following output (hours after site had been run):

```
$ sudo supervisorctl status
beaker-cache-cleanup        STOPPED     Not started
ckan                                    RUNNING    pid 1502, uptime 2:23:29
```
