### ISSUE TITLE
Ansible role for pycsw-next picks the wrong version of python

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2384]
pycsw_python_version: 2.7.16 is set as a default and is installed as part of the role. However, the Pipfile in GSA/pycsw specifies python 3, so the dependencies require python3. pipenv? is finding a local python3 and using that even though it is not expected.

## How to reproduce

1. Set pycsw_python_version: 2.7.16
1. Bump GSA/pycsw Pipfile to use python 3
1. Run the pycsw playbook `ansible-playbook pycsw.yml --limit v2`
1. Inspect the pycsw virtualenv `sudo /home/pycsw/current/.venv/bin/python --version`

## Expected behavior

Python 2.7.16 is used.

## Actual behavior
Python 3 is used in the virtualenv.

```
pycsw@catalog-next-web1tf:~$ current/.venv/bin/python --version
Python 3.6.9
```

Here we see python version is unset, so the role default of 2.7.16 is used:
```
$ pipenv run ansible-inventory -i ansible/inventories/sandbox --host=catalog-next-web1tf.internal.sandbox.datagov.us | grep pycsw_python_version
```

**Comment by nickumia-reisys** [comment]
Similar to the below issue, no more ansible... no more pycsw...
- https://github.com/GSA/data.gov/issues/1228#issuecomment-1416523909
- https://github.com/GSA/data.gov/issues/3710
- https://github.com/GSA/data.gov/issues/3182
