### ISSUE TITLE
Add Jenkins task for pycsw deploy to sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2394]
## User Story

In order to test application deployment and get quicker feedback on changes, data.gov developers want pycsw to be deployed by jenkins automatically on changes to the main data.gov pycsw branch.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN a commit is made to the GSA/pycsw repo's main data.gov branch (datagov/v2.4.x)
  WHEN CI completes successfully
  AND I visit ci.sandbox.datagov.us
  THEN I see the pycsw jenkins job applying the pycsw playbook.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
No more Jenkins.  No more pycsw.  No more sandbox.
- https://github.com/GSA/data.gov/issues/3710
- https://github.com/GSA/data.gov/issues/3182
- https://github.com/GSA/data.gov/issues/1228#issuecomment-1416523909
