### ISSUE TITLE
Enable GitHub security alert notifications for all data.gov repositories

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2397]
## User Story

In order to ensure that security alerts are addressed in a timely fashion, Data.gov developers want to receive and manage GitHub security alerts from Data.gov repositories.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN a GH security alert exists
  WHEN I visit the alerts page on a Data.gov repo (e.g. https://github.com/GSA/datagov-deploy/network/alerts) as a GSA/data-gov-support team member
  THEN I can see the security alert

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This change will raise team awareness of automated security findings associated with GitHub repositories in use by the data.gov team. This will be a positive change in our security posture without any obvious downsides.

## Sketch

- [ ] Investigate [GHAD](https://github.com/18F/ghad)... 
  - The repository README says [it is already in use for TTS repositories](https://github.com/18F/ghad#usage-in-tts). 
  - Are we covered? If not, how hard would it be to add our repositories?

- Write some Terraform that automatically adds the right GitHub group under `Access to Alerts` on the correct tab in each of our respositories' settings. (Example: https://github.com/GSA/datagov-deploy/settings/security_analysis)
- See if we can automate some of our other [default GitHub repo settings](https://github.com/GSA/datagov-deploy/wiki/Checklist-for-new-repositories)

**Comment by mogul** [comment]
It appears that TTS Tech Portfolio may already be doing this! See https://github.com/18F/ghad before taking on this work.

**Comment by mogul** [comment]
I asked the TTS Tech Portfolio team the questions we need answers for immediately:
![image](https://user-images.githubusercontent.com/47762/112544961-e1dcd180-8d74-11eb-8848-0b815f75c8ee.png)

**Comment by mogul** [comment]
Confirmed that this is happening! We now need to just confirm that all of our repositories have given `Admin` permissions to `GSA/tts-admins`.

**Comment by mogul** [comment]
> Confirmed that this is happening! We now need to just confirm that all of our repositories have given `Admin` permissions to `GSA/tts-admins`.

We'll be taking this up in a new story specifically about ensuring all GitHub repos are set up consistently.

**Comment by mogul** [comment]
> We'll be taking this up in a new story specifically about ensuring all GitHub repos are set up consistently.

[That story is here.](https://github.com/GSA/datagov-deploy/issues/3067)
