### ISSUE TITLE
Catalog Cloudfront 504 Error in DC region

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2398]
This issue happened several times in the past a few years. When it happens, users from DC area (including Northern VA and maybe other neighboring areas) see 504 Error when accessing catalog.data.gov site. Most of time the issue last for the whole day, and resolved itself at the end of day.

Here is the list of occurrences we have in record:

[2022-01-21: DC, NY](https://gsa-tts.slack.com/archives/C2N85536E/p1642776575002200)

[2022-01-10: DC, NY](https://gsa-tts.slack.com/archives/C2N85536E/p1641832500011400)

[2021-07-28: DC, NY](https://gsa-tts.slack.com/archives/C2N85536E/p1627493841005000)

[2021-07-23: DC, NJ, NY](https://gsa-tts.slack.com/archives/C2N85536E/p1627063966009100)

2021-03-10: [DC](https://gsa-tts.slack.com/archives/C2N85536E/p1615384511036000) and [Colorado](https://gsa-tts.slack.com/archives/C2N85536E/p1615393500044500)

[2020-11-04](https://gsa-tts.slack.com/archives/C2N85536E/p1604505251061600?thread_ts=1604499767.061400&cid=C2N85536E)

[2020-09-19](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1600491564008400?thread_ts=1600491501.008300&cid=C4RGAM1Q8)

[2020-09-17](https://github.com/GSA/datagov-deploy/issues/2154) ([discussion](https://chat.google.com/u/0/room/AAAAcJQgkd8/GoxG_DV09eY))

[2020-09-14](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1600093513040300)

[2020-06-02](https://gsa-tts.slack.com/archives/C2N85536E/p1591109617375400)

2020-05-26 https://github.com/GSA/data.gov/issues/894

[2018-09-25](https://gsa-tts.slack.com/archives/C2N85536E/p1537882828000100)

The last one 2020-11-04 is also captured in the [Incidence Response doc](https://docs.google.com/document/d/193UUWNO7rvGYsiXZJJb4AlRV4s1iT-ZG5mkAXfrv404).  

## How to reproduce

Access https://catalog.data.gov/dataset

## Expected behavior

Page loads with 200 response code

## Actual behavior
504 Error.

![image](https://user-images.githubusercontent.com/1392461/98282472-49cc8000-1f6c-11eb-9881-8dc40c238c6f.png)

**Comment by mogul** [comment]
Fuhu's asked FCS whether they have any insight into the problem from their side.

**Comment by adborden** [comment]
We saw this again last night 11/6/2020 ~9pm to 10:15pm on our [DC-only monitor](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJzeW50aGV0aWNzLW5lcmRsZXRzLm1vbml0b3ItZmFpbHVyZXMiLCJlbnRpdHlJZCI6Ik1UWXdNVE0yTjN4VFdVNVVTSHhOVDA1SlZFOVNmRGhrTVdVMk1UVTBMV1ptWkRjdE5HSmlZaTFoWmpBekxUUTNaVFkwWmpreE4yTmhZUSJ9&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVFl3TVRNMk4zeFRXVTVVU0h4TlQwNUpWRTlTZkRoa01XVTJNVFUwTFdabVpEY3ROR0ppWWkxaFpqQXpMVFEzWlRZMFpqa3hOMk5oWVEiLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoic3ludGhldGljcy1uZXJkbGV0cy5tb25pdG9yLWZhaWx1cmVzIn19&platform[timeRange][duration]=86400000&platform[$isFallbackTimeRange]=false).

![screencapture-one-newrelic-launcher-nr1-core-explorer-2020-11-06-09_30_32](https://user-images.githubusercontent.com/509703/98396846-40e2b980-2013-11eb-9f80-03db37bdda37.png)


The only errors on the all-locations monitor was from DC.

**Comment by adborden** [comment]
FYI, debugging CloudFront (unrelated to this issue), and I'm noticing some strange behavior to note. tl;dr, make sure to invalidate the cache after changing any CF settings.

I just updated the CF default TTL is set to 60 seconds for this endpoint. You can see the `age` header shows the object 50 seconds old, and the response is cached (x-cache: hit).
```
$ curl -v 'https://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities'  > /dev/null
< HTTP/2 200
< content-type: application/xml; charset=UTF-8
< date: Thu, 19 Nov 2020 22:48:36 GMT
< server: gunicorn/19.10.0
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< access-control-allow-origin: *
< access-control-allow-methods: POST, PUT, GET, DELETE, OPTIONS
< access-control-allow-headers: X-CKAN-API-KEY, Authorization, Content-Type
< referrer-policy: origin
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< vary: Accept-Encoding
< x-cache: Hit from cloudfront
< via: 1.1 ea7c4b0407882327307bae4ed233d142.cloudfront.net (CloudFront)
< x-amz-cf-pop: SFO5-C3
< x-amz-cf-id: mJEcdmrvflX9730_IRUu6OhX5lfkwx4uIl3lfUfo8H8H3AMK9vpfcw==
< age: 50
```

15 seconds later, I would expect an `x-cache: Miss`, but instead we get a Hit, with an age of 1305:
```
$ curl -v 'https://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities'  > /dev/null
< HTTP/2 200
< content-type: application/xml; charset=UTF-8
< date: Thu, 19 Nov 2020 22:26:38 GMT
< server: gunicorn/19.10.0
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< access-control-allow-origin: *
< access-control-allow-methods: POST, PUT, GET, DELETE, OPTIONS
< access-control-allow-headers: X-CKAN-API-KEY, Authorization, Content-Type
< referrer-policy: origin
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< vary: Accept-Encoding
< x-cache: Hit from cloudfront
< via: 1.1 92a230c43d1bce04e861702af2b980a9.cloudfront.net (CloudFront)
< x-amz-cf-pop: SFO5-C3
< x-amz-cf-id: eo3cIv7XsB4FdKxXuIDsIcnSxT4Wr6gp8VZyRWboc0iAfgZ8M5zwSQ==
< age: 1385
```

A second later, I try again and see a miss.
```
$ curl -v 'https://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities'  > /dev/null
< HTTP/2 200
< content-type: application/xml; charset=UTF-8
< date: Thu, 19 Nov 2020 22:49:53 GMT
< server: gunicorn/19.10.0
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< access-control-allow-origin: *
< access-control-allow-methods: POST, PUT, GET, DELETE, OPTIONS
< access-control-allow-headers: X-CKAN-API-KEY, Authorization, Content-Type
< referrer-policy: origin
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< vary: Accept-Encoding
< x-cache: Miss from cloudfront
< via: 1.1 e9ba0a9a729ff2960a04323bf1833df8.cloudfront.net (CloudFront)
< x-amz-cf-pop: SFO5-C3
< x-amz-cf-id: jvT2Bjr1mSPSCP8eU7vg4exH1WGgIYX7-u0k4PYDkuUfA9ggm0inyg==
```

It's almost like there are still old objects cached with the older default TTL. After invalidating the cache, the behavior goes away and I never see an object with age above the 60 second TTL.

**Comment by FuhuXia** [comment]
Today again. Outage noticed in DC, NJ, NY. It last about 2 hours. 

https://gsa-tts.slack.com/archives/C2N85536E/p1627063966009100

**Comment by FuhuXia** [comment]
A service-now incident ticket is created `INC3518734`. It will be assigned to Delivery team to investigate.

**Comment by nickumia-reisys** [comment]
Most likely just an FCS Issue, but we do see (unrelated, but similar) unknown networking issues (from time to time) on cloud.gov,
- https://github.com/GSA/data.gov/issues/3710
