### ISSUE TITLE
Rapid debugging and testing for inventory-app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2402]
## User Story

In order to ensure we can rapidly diagnose problems, the team wants to be able to inspect the environment when a particular line of code is hit.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I need to debug CKAN code in inventory-app
  AND I map my local ckan repository into inventory-app (via docker bind `~/projects/ckan:/usr/lib/ckan/src/ckan`)
  WHEN I edit code
  THEN I see CKAN reload in the docker log output
- [ ] GIVEN I need to debug CKAN extension code in inventory-app
  AND I map my local ckan extension repository into inventory-app (via docker bind `~/projects/ckanext-dcatus_metadata:/usr/lib/ckan/src/ckanext-dcat_usmetadata`)
  WHEN I edit code
  THEN I see CKAN reload in the docker log output
- [x] GIVEN I need to inspect the state of code at a particular line
  AND I drop a breakpoint in the source with `import pdb; pdb.set_trace()`
  WHEN I reload the app and hit that code
  THEN I see trace output in the terminal.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."

None. These facilities would only be enabled during local development with Docker.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- There are some [native debugging facilities](https://github.com/okfn/docker-ckan#running-the-debugger-pdb--ipdb) in the Docker image that we can use. 
- VSCode also has the ability to [debug Python in a running container](https://code.visualstudio.com/docs/containers/debug-python) though we may not need to go that far to get the iteration boost we need.

**Comment by jbrown-xentity** [comment]
See PR, ready for review. Only thing we could not get working is automatic code reload, gunicorn --reload option does not work well with paster configuration of CKAN (has to do with `.ini` file having paths in it, well documented bug). Have workaround make command that gets typical docker-compose restart down from 1+ minute to ~7 seconds.

**Comment by mogul** [comment]
James is going to clean up the branch and then review with Aaron.
