### ISSUE TITLE
Release 20201112

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2406]
## Release MM/DD/YYYY
Roll out [updates/release to production](https://github.com/GSA/datagov-deploy/wiki/Releases) so that the latest bug fixes and feature code is available.

### Acceptance Criteria

- [x] Release is cut (datagov-deploy, catalog-app, inventory-app, static sites)
- [x] Playbook run with no errors/expected errors in sandbox
- [x] Playbook run with no errors/expected errors in staging, and all systems verified up
- [x] Playbook run with no errors/expected errors in production, and all systems verified up

### Implementation notes

<!-- Write notes of things that went poorly that should be noted for next time. Include link to release thread if appropriate. --!>
Staging will not catch issue #2405, if it is still unresolved by the release date.

**Comment by jbrown-xentity** [comment]
All went fine, a number of isolated issues came up during staging and production release. A second run resolved both times.
