### ISSUE TITLE
Task: Ensure smoke tests include a request that represents the healthcheck used by Netscaler/load balancers

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2432]
## User Story

In order to ensure that our application is responding to healthchecks properly, data.gov operators want the Ansible playbooks to include a smoke test that makes a request just like the healthcheck made by Netscaler or ALBs.

## Acceptance Criteria
- Each service (solr, redis, etc) and application (catalog, dashboard, etc) should have a smoke test in it's playbook
- In addition to high-profile endpoints, a smoke test representing the application's healthcheck exists matching what is configured in Netscaler.

## Background
[2020/10/14 - data.gov incident response - catalog.data.gov unavailable](https://docs.google.com/document/d/19YhtdNZ3x9n3FJLWmue3XH9drxn8PVTHGnpeu-gdtao/edit#)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
Starting point for healthcheck endpoints: https://docs.google.com/spreadsheets/d/1Qee_TQuLGEASnZ08v1rLBf47kes2KDSoPPTphfXNfc4

**Comment by nickumia-reisys** [comment]
No more Ansible.  No more Netscaler.
- https://github.com/GSA/data.gov/issues/3710
