### ISSUE TITLE
Gather test artifacts needed for ATO submission

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2435]
## User Story

In order to assess data.gov components for ATO on cloud.gov, GSA A&A wants recent contingency, and IR test results.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I look at [the Google Drive folder for compliance-related documents](https://drive.google.com/drive/folders/1tSDcAaDOc6vVxbMoNWTistjxiRTWjHUl) \
  THEN I see recent documents representing the IR, and CP test results.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
We are creating this issue to remind us that we should be running these tests and gathering these artifacts during the month of January.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, documents are all stored in permission-controlled Google Drive.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]
- Run a CP exercise and show we can follow the plan
- Select an IR retro doc as our representative example

**Comment by hkdctol** [comment]
Added links to the most recent IR and CP Test Results.
