### ISSUE TITLE
Debug script to capture information from DC catalog.data.gov outage

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2437]
## User Story
From the 2020-11-04 partial outage.

In order to ensure we have common baseline for data collection around debugging the [partial outage for catalog.data.gov in DC](https://github.com/GSA/datagov-deploy/issues/2398), Data.gov developers want a script that we can run before/after/during an outage that collects a standard set of information about the behavior we're seeing.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
- [2020-11-04 Incident Response](https://docs.google.com/document/d/193UUWNO7rvGYsiXZJJb4AlRV4s1iT-ZG5mkAXfrv404/edit#)
- https://github.com/GSA/datagov-deploy/issues/2398

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
Based on information we collected in the [IR doc](https://docs.google.com/document/d/193UUWNO7rvGYsiXZJJb4AlRV4s1iT-ZG5mkAXfrv404/edit#), create a script that will capture similar information:
- CloudFront IP addresses (dig output from catalog.data.gov)
- curl output from various endpoints (404, status_show, dataset page), including status and cache headers

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data.gov/issues/2398
