### ISSUE TITLE
Run WordPress migrations at application startup

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2446]
## User Story

In order to ensure migrations are run as soon as an upgrade is applied, data.gov developer wants any wordpress database migrations to be applied at application startup time.

## Acceptance Criteria
- [ ] GIVEN a new version of WordPress or WP plugin is available
  WHEN I run the datagov-web.yml wordpress playbook
  THEN any migrations are applied when the new version of wordpress starts up

## Background
Right now, it's a manual step to a) notice that a migration is required and b) apply the migration. If the migration doesn't happen right away, it might block a user from using WordPress. By then, it's too late to test and debug in a staging/testing environment.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None.

## Sketch
The wp CLI has an [update-db](https://developer.wordpress.org/cli/commands/core/update-db/) command. I'm not sure if this includes plugin db migrations or if there are additional commands to run.

**Comment by hkdctol** [comment]
closing as we've left wordpress
