### ISSUE TITLE
SSL error POSTing tracking 

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#2454]
Related to [datagovcatalog#20](https://github.com/GSA/ckanext-datagovcatalog/issues/20)
Probably related to #570 

After deploying the [last PR](https://github.com/GSA/datagov-deploy/pull/2447) we now see the redirections work as expected but is still failing 

```
$ curl -L -v https://admin-catalog-next.data.gov/_tracking -d "url=/dataset/department-for-the-aging-dfta-geriatric-mental-health-contracted-providers&type=page"
*   Trying 34.193.244.109:443...
* TCP_NODELAY set
* Connected to admin-catalog-next.data.gov (34.193.244.109) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, unrecognized name (624):
* error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
* Closing connection 0
curl: (35) error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
```

## How to reproduce

`$ curl -L -v https://admin-catalog-next.data.gov/_tracking -d "url/dataset/department-for-the-aging-dfta-geriatric-mental-health-contracted-providers&type=page"`

## Expected behavior

Get a 200 response after adding track information to DB

## Actual behavior

Fails with an SSL error `curl: (35) error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name`

**Comment by thejuliekramer** [comment]
<img width="1479" alt="Screen Shot 2020-11-19 at 10 56 23 AM" src="https://user-images.githubusercontent.com/7378770/99702009-e6a61780-2a5a-11eb-9272-ba1c6120aa53.png">

**Comment by adborden** [comment]
@thejuliekramer That error is expected until admin-catalog-next.data.gov is working and it's [SSL/TLS certificate is installed properly](https://github.com/GSA/datagov-ckan-multi/issues/298).

![Screen Shot 2020-11-19 at 9 39 40 AM](https://user-images.githubusercontent.com/509703/99702966-5f04dc80-2a4b-11eb-8bf1-14585046d022.png)

**Comment by avdata99** [comment]
Now I'm getting `403` error

<pre>
$ curl -L -v https://admin-catalog-next.data.gov/_tracking -d "url=/dataset/department-for-the-aging-dfta-geriatric-mental-health-contracted-providers&type=page"
*   Trying 34.193.244.109:443...
* TCP_NODELAY set
* Connected to admin-catalog-next.data.gov (34.193.244.109) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=District of Columbia; L=Washington; O=General Services Administration (GSA); OU=Technology Transformation Service; CN=data.gov
*  start date: Oct 26 00:00:00 2020 GMT
*  expire date: Apr 21 23:59:59 2021 GMT
*  subjectAltName: host "admin-catalog-next.data.gov" matched cert's "admin-catalog-next.data.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> POST /_tracking HTTP/1.1
> Host: admin-catalog-next.data.gov
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 97
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 97 out of 97 bytes
* Mark bundle as not supporting multiuse
<b>< HTTP/1.1 403 Forbidden</b>
< Server: nginx/1.18.0 (Ubuntu)
< Date: Fri, 20 Nov 2020 13:58:52 GMT
< Content-Type: text/html
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Set-Cookie: citrix_ns_id=jLXLSrmFIsfT+P+l91+14K/CcVo0001; Domain=.data.gov; Path=/; HttpOnly
< X-Cache-Control-Orig: 
< Cache-Control: max-age=0, must-revalidate, private
< X-Expires-Orig: None
< Transfer-Encoding: chunked
< 
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host admin-catalog-next.data.gov left intact

</pre>

**Comment by avdata99** [comment]
Now we get an `HTTP/1.1 200 OK` for 
```
curl -L -v https://admin-catalog-next.data.gov/_tracking -d "url=/dataset/department-for-the-aging-dfta-geriatric-mental-health-contracted-providers&type=page"

and (with redirection)

curl -L -v https://catalog-next.data.gov/_tracking -d "url=/dataset/department-for-the-aging-dfta-geriatric-mental-health-contracted-providers&type=page"
```

It's working on the website (sometimes strangely cancelled)
![image](https://user-images.githubusercontent.com/3237309/100358500-08f8e180-2fd5-11eb-95dc-8a01904c0f9d.png)

**Comment by adborden** [comment]
If you see cancelled, it's probably the browser blocking the [CORS]() request.

In firefox, I'm seeing `Access-Control-Request-Headers: x-requested-with` in the OPTIONS request. That is probably missing from our CORS response.

![Screen Shot 2020-12-15 at 5 36 06 PM](https://user-images.githubusercontent.com/509703/102293691-732de380-3efc-11eb-9b7c-0542d9139b5f.png)

**Comment by adborden** [comment]
I tried [adding the header](https://github.com/GSA/datagov-deploy/commit/85be750f28396a3fbf38556798e54814c7093fbf) but I'm still getting the same result in staging.
