### ISSUE TITLE
Link takeover on dashboard

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2458]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.2oxas95byze0)._

https://hackerone.com/reports/1035400

**Date of report:** 2020-11-16
**Severity:** Low
**Due date:** 2020-02-16

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* ([#2459](https://github.com/GSA/datagov-deploy/issues/2459))

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by FuhuXia** [comment]
Fixed on prod. Details in [Google Doc](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.2oxas95byze0). HTML-encoded some character so the [PHP function](https://github.com/GSA/project-open-data-dashboard/blob/master/application/helpers/api_helper.php#L417-L423) won't convert the text to hyperlinked html anchor.
