### ISSUE TITLE
Broken link checking on all sites

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2459]
## User Story

In order to ensure that we are providing the most up to date content and preventing link rot and link takeovers, data.gov users want a broken link check that reports to the data.gov team.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN a link is broken on a data.gov site
  WHEN the broken link checker runs
  THEN the data.gov team is notified of the broken link.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
Keeping this on our radar as a way to mitigate link-squatting attacks generally.

**Comment by nickumia-reisys** [comment]
Superseded by
- https://github.com/GSA/data.gov/issues/4143
- https://github.com/GSA/data.gov/issues/4182
