### ISSUE TITLE
Catalog-next doesn't harvest ckan->ckan correctly

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2462]
Catalog-next is able to harvest from data.doi.gov as a CKAN harvest source. However, the `Metadata Source` section is wrong.

It is reporting the values around this the same as downstream, but the actual content is CKAN JSON metadata. See [this dataset](https://catalog.data.gov/dataset/the-geologic-map-of-arkansas) and it's [Metadata Source](https://catalog.data.gov/harvest/object/88105457-20ab-4803-a9dd-0b082c5616e8) as an example. This should be ISO metadata.

This was [a customization done for data.gov 2 years ago](https://github.com/GSA/ckanext-harvest/commit/84ae3f9f8959eee31394367581653fb9aee26c8b#diff-dc07bd6e5620f676d05e92c12accf899ebc6598db3e70adfd65e35434f24d652R402-R414). This allows the CKAN harvester to be chained (ie a CKAN system harvests metadata, which is then harvested by another CKAN system) without losing the original source metadata.

## How to reproduce

1. Harvest a CKAN system that itself has harvested metadata (ie data.doi.gov)
1. View the `Metadata Source` section (ie [this dataset](https://catalog.data.gov/dataset/the-geologic-map-of-arkansas))
1. See CKAN metadata (instead of true source metadata)

## Expected behavior

ISO metadata is returned

## Actual behavior

CKAN metadata is returned

**Comment by nickumia-reisys** [comment]
I randomly found this while searching for another ticket.  For the next person who sees this, it is still an issue.  The only known harvest source that is CKAN type is doi-open-data which is manual.  I wrote the following one-line to determine this:
```bash
curl 'https://catalog.data.gov/api/action/package_search?fq=dataset_type:harvest&rows=1000' | jq '.result.results[] | select(.source_type=="ckan")'
```

Inspecting this harvest source, looking at a [single dataset](https://catalog.data.gov/dataset/usgs-us-topo-map-collection), the "View Metadat Source" button points to the harvester copy of the metadata and not the link to the original metadata.

![image](https://user-images.githubusercontent.com/85196563/215544692-59c76c30-a4fc-4205-9aaf-e7f27e30cd0b.png)

**Comment by jbrown-xentity** [comment]
This harvest source can be deleted, it's no longer functional or in use.

**Comment by nickumia-reisys** [comment]
After team consensus to delete: Harvest source had 0 datasets.  It was cleared and then deleted.
<details closed>
<summary>Historical Information</summary>
<br>

```json
{
  "config": "{\"private_datasets\": \"False\", \"force_all\": true}",
  "creator_user_id": "a4aca618-886b-4597-8af0-96dfbf874935",
  "force_all": true,
  "frequency": "MANUAL",
  "id": "3a60d81e-ede6-416f-b7f9-7b3298ef2115",
  "metadata_created": "2020-11-10T19:42:32.704541",
  "metadata_modified": "2020-11-10T22:51:46.965794",
  "name": "doi-open-data",
  "notes": "The Open Data provided by the Department of the Interior",
  "organization": {
    "id": "143529f7-2eef-4a07-b227-93ac9e84fad8",
    "name": "doi-gov",
    "title": "Department of the Interior",
    "type": "organization",
    "description": "The Department of the Interior (DOI) conserves and manages the Nation’s natural resources and cultural heritage for the benefit and enjoyment of the American people, provides scientific and other information about natural resources and natural hazards to address societal challenges and create opportunities for the American people, and honors the Nation’s trust responsibilities or special commitments to American Indians, Alaska Natives, and affiliated island communities to help them prosper.\r\n\r\nSee more at https://www.doi.gov/",
    "image_url": "https://www.doi.gov/sites/doi.opengov.ibmcloud.com/themes/custom/doi_gov/logo.png",
    "created": "2020-11-10T15:11:40.499004",
    "is_organization": true,
    "approval_status": "approved",
    "state": "active"
  },
  "owner_org": "143529f7-2eef-4a07-b227-93ac9e84fad8",
  "private": false,
  "private_datasets": "False",
  "source_type": "ckan",
  "state": "active",
  "title": "DOI Open Data",
  "type": "harvest",
  "url": "https://data.doi.gov",
  "resources": [],
  "tags": [],
  "groups": [],
  "relationships_as_subject": [],
  "relationships_as_object": []
}
```

</details>

With these new developments, this ticket is no longer relevant since we have no CKAN -> CKAN harvesting.  If a CKAN harvest source does get added in the future, this may need to be revived.
