### ISSUE TITLE
Dataset page layout on ipad on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2464]
- Menu should be the mobile hamburger menu, collapsed on load
- Filter menu should be loaded in a collapsed state
- The filter menu border extends down into the dataset results

<img width="403" alt="Screen Shot 2020-11-20 at 2 20 04 PM" src="https://user-images.githubusercontent.com/509703/99855535-ef224f00-2b3b-11eb-813b-4c4b288c0151.png">

## How to reproduce

On an ipad, or in chrom developer tools, emulate ipad.
1. https://catalog-next.data.gov/dataset

## Expected behavior

- menus should be initialized as collapsed
- tablet layout

**Comment by FuhuXia** [comment]
Still an issue on CKAN 2.9 on cloud.gov.

**Comment by jbrown-xentity** [comment]
This is resolved, closing.
