### ISSUE TITLE
FEMA organization logo does not load

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2467]
<img width="734" alt="Screen Shot 2020-11-20 at 2 56 12 PM" src="https://user-images.githubusercontent.com/509703/99857673-986b4400-2b40-11eb-87fb-2fa5a974cc08.png">

## How to reproduce

1. https://catalog.data.gov/organization/fema-gov

**Comment by jbrown-xentity** [comment]
Resolved, closing.
