### ISSUE TITLE
Dashboard crawls are running twice a day

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2495]
## How to reproduce

The daily crawls are only supposed to run once per day. Recently, they have been running twice - once at 4am EST and another a little after 10am. 

View some of the crawls: [NSF example](https://labs.data.gov/dashboard/offices/detail/52640/2020-12-31).  You can also see the results from the dashboard db: ![image.png](https://images.zenhubusercontent.com/5e1cbcd08dced94b250ef061/94759b79-0447-4f60-9c3a-68c687399a7a)

This could be a sign of larger bugs/issues. If encountered, keep the white noise threshold in mind for creating new tickets.

## Expected behavior

The crawls only occur once per day.

## Actual behavior

They are, somewhat inconsistently, happening twice per day.

## Sketch

These aren't checklist items to do, but potential places to start debugging:

- [x] See if these results are isolated to production or also occur on staging
- [x] Run the commands for the full-scan crawls and tail the logs
- [x] Enable logging for the nightly crawl and verify results

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
