### ISSUE TITLE
[spike: 4d] Investigate ECS as compliance short-cut for Solr hosting

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2505]
## User Story

In order to minimize the risk of delaying data.gov's new ATO, Bret wants to investigate ECS as an alternative for standing up Solr with lower compliance overhead.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] After presenting the results of the spike at the next sprint review, we can make a decision about the viability of pursuing this approach.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

In reviewing our plan to stand up the SSB with Manoj of GSA ISE (the architecture evaluation group), we talked about how the broker will use AWS EKS as the back-end for our Solr instances. He said that another group in GSA was working hard on getting their own EKS service up and running, and that it had been a long slog with a lot of complexity to meet their own compliance requirements; Manoj will share some documentation about what they've done. That will reduce uncertainty about what's required for our own implementation, but it's possible there will be elements of their solution that we can't easily/quickly reimplement ourselves (particularly if they require a procurement). This might also increase the complexity of our SSP to a point where we end up jeopardizing our mid-February ATO submission slot.

So: We should investigate alternatives that remove AWS EKS from the equation to reduce the hardening and compliance burden that it may imply.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
Nothing yet, this will just be a spike in a sandbox AWS account to evaluate the feasibility. If it works out, future issues will cover hardening necessary for production work.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

Goal: Find a quick way to run SolrCloud in AWS ECS
- There is definitely precedent for doing this: [video](https://www.slideshare.net/lucidworks/a-self-healing-solr-cloud-built-using-cloud-design-patterns), [slides](https://www.youtube.com/watch?v=Z0N2JxOvtDA), an outdated [ECS-specific Docker image](https://github.com/hybox/solr-ecs).
  - In the time since that presentation, ECS and Fargate added support for EFS, so the S3 workaround for backups is no longer necessary.
- Using ECS with Fargate removes both EKS and EC2 from our boundary concerns.
    - After the work to set up ECS in the first place, the developer/operator surface is similar to the cloud.gov/PaaS level:
      - "These are the tasks to run, and I want this many of each, with this much memory."
- Obstacles: 
  - Experience with ECS in the team (at least in Bret!) is light-to-nonexistent.
  - The presenter was unable to open-source their Terraform module, so we'd have to start from zero.
  - Existing tutorials on managing ECS with Terraform are pretty convoluted and involve touching a lot of other AWS services
  - There are many moving parts just to get the ECS cluster ready for use!

Approaches to try: 
1. See if [this new method of using `docker-compose` to deploy onto ECS+Fargate](https://aws.amazon.com/blogs/containers/deploy-applications-on-amazon-ecs-using-docker-compose/) is viable! \
  Should be able to use [the stock docker-compose examples](https://github.com/docker-solr/docker-solr/blob/master/README.md)
2. Try working from [this Terraform ECS template](https://github.com/turnerlabs/terraform-ecs-fargate). \
  If not, then try working from [tutorial 1](https://engineering.finleap.com/posts/2020-02-20-ecs-fargate-terraform/) or [tutorial 2](https://dev.to/txheo/a-guide-to-provisioning-aws-ecs-fargate-using-terraform-1joo).
3. If Zookeper proves to be an obstacle, maybe try [this load-balancer-based architecture](https://engineering.zalando.com/posts/2016/05/zookeeper-less-solr-architecture-aws.html)?

**Comment by JJediny** [comment]
admittedly ugly - but couldn't you emulate a zookeeper-less AWS architecture (ref in your issue - https://engineering.zalando.com/posts/2016/05/zookeeper-less-solr-architecture-aws.html) using cloud.gov to push 1 large solr master as an docker container cf-push app and do the same for 3-5 read replicas as apps, then dns to bind/network to them?

**Comment by mogul** [comment]
That's a good idea! Unfortunately the Solr file data is upwards of 70GB, and the cloud.gov hard limit for the application filesystem is 2GB.

**Comment by mogul** [comment]
[Repository for this work is here](https://github.com/GSA/datagov-terraform-ecs-solr)
@srinirei is going to keep exploring this for a bit, while I re-evaluate the EKS route based on new guidance we got from GSA IT.

**Comment by mogul** [comment]
After more investigation, this is not as straightforward as we'd first hoped, either technically or compliance-wise.
