### ISSUE TITLE
Dataset Page missing `description` on catalog-classic

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2515]
## How to reproduce

The description appears on [list views of datasets](https://catalog.data.gov/dataset?q=rexus&as_sfid=AAAAAAVpgvgLwhiWWqz6SXeWzqmqdLHwaMcRq3NOhAjWBnDd12o-R9e38B9U58a-q3elZr_CxvzY9dHO5m40F20ZvBvJlADZIJcevUqvKeAu1wjVxMv0WyO2AyLNsyxncZbefqA%3D&as_fid=9e9ffa47cddb561790b7f2ddcc43a3741160f0d9) but the description does not appear see:

[this example](https://catalog.data.gov/dataset/real-estate-across-the-united-states-rexus-lease) or [this example](https://catalog.data.gov/dataset/real-estate-across-the-united-states-rexus-lease)

We believe that the error is [within this chunk of code](https://github.com/GSA/ckanext-datagovtheme/blob/master/ckanext/datagovtheme/templates/package/read.html#L36-L40)

## Expected behavior

The description appears.

## Actual behavior

No description.

**Comment by jbrown-xentity** [comment]
Tested on sandbox, rolling back [this PR](https://github.com/GSA/ckanext-datagovtheme/pull/47/files), specifically changing the line [h.get_translated](https://github.com/GSA/ckanext-datagovtheme/commit/638cf2f22d2c81498e26a0afd292f347f4b8a450#diff-203a1737f44a0fa87b9d1a10a81ab484951f49d7a912dc91d4c38c5d62b657daR39) to be the old [c.package_notes_formatted](https://github.com/GSA/ckanext-datagovtheme/commit/638cf2f22d2c81498e26a0afd292f347f4b8a450#diff-203a1737f44a0fa87b9d1a10a81ab484951f49d7a912dc91d4c38c5d62b657daL40) did the trick.
@avdata99 @adborden what's the best way to add logic for different versions of CKAN into the jinja template?

**Comment by adborden** [comment]
Hmm, is it possible this has been an issue on catalog-classic since August/September?

@avdata99 we're going to rollback the original fix. Let's add an integration test to both catalog-classic and catalog-next to catch this in the future.

**Comment by adborden** [comment]
This has been deployed.

**Comment by avdata99** [comment]
@adborden @jbrown-xentity I will add logic for different versions of CKAN into the jinja template and sent a new PR with tests

**Comment by hkdctol** [comment]
Descriptions appear on catalog classic
![descriptions](https://user-images.githubusercontent.com/3236989/102107089-5495f280-3dff-11eb-8f52-c4e491e9c016.png)
