### ISSUE TITLE
502 Proxy Error intermittently on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2520]
I see this kind of randomly, but enough to cause concern. It looks like in some cases gunicorn is unavailable momentarily, so apache returns the proxy error. I've also seen this on inventory-next.

![Screen Shot 2020-12-07 at 6 07 18 PM](https://user-images.githubusercontent.com/509703/101429150-18223e00-38b7-11eb-8981-f4275d27484b.png)

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
