### ISSUE TITLE
Non-federal users with login.gov accounts can authenticate with CKAN

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2526]
As was always the case with Data.gov, we delegate account creation to our SAML2 provider (formerly MAX.gov) but assign authorization with CKAN's organization membership and roles. Any government user can sign in with MAX.gov and create an account in Inventory or Catalog, but without an administrator to assign them a role or organization, they would have no more authorization than an anonymous user.

With login.gov any non-gov user can create a login.gov account (unlike max.gov). There's not much of a security implication there, but we should be keeping the records clean for auditing purposes. Having a bunch of inert users doesn't help that.

## How to reproduce

1. Register a login.gov sandbox account with a non-gov account https://idp.int.identitysandbox.gov/sign_up/enter_email
1. Login to sandbox with your new account https://catalog-next.sandbox.datagov.us/user/login

## Expected behavior

- Non .gov accounts are rejected (403 Forbidden)
- Account in CKAN is not created

## Actual behavior

Account is created. User successfully logs in.

**Comment by adborden** [comment]
We might want to consider requiring PIV card access so only PIV card users can create accounts.

**Comment by adborden** [comment]
Login.gov folks recommend using PIV card authentication. In practice, this means including `http://idmanagement.gov/ns/assurance/aal/3?hspd12=true` for the [Authentication Context Class Reference](https://developers.login.gov/oidc/#aal-values) in our SAML request.

**Comment by adborden** [comment]
@avdata99 can you take a look at this?

**Comment by adborden** [comment]
In case it's helpful, when we were using MAX.gov we had to [fork pysaml2](https://github.com/GSA/pysaml2/blob/8b605c824ff1d042e9040a9971c28f369197cac2/src/saml2/client_base.py#L240-L246). Hopefully 4.9.0 gives us a better way to do this.

```python
        if config.get('saml2.max_security_level'):
            context_class_ref = saml.AuthnContextClassRef()
            context_class_ref.text = config.get('saml2.max_security_level')
            requested_authn_context = samlp.RequestedAuthnContext()
            requested_authn_context.authn_context_class_ref.append(
                context_class_ref
            )
```

**Comment by avdata99** [comment]
@adborden 
If we want to have control over who is able to create CKAN users we can:

 - Work on saml2 extensibility: https://github.com/keitaroinc/ckanext-saml2auth/issues/13. Here we can drop user if they don't fit our requirements
 - We can propose to add a new setting like `ckanext.saml2auth.allow_users_from=gsa.gov,us.gov` to limit the email addresses that are able to create users

About this context you mention is not clear for me how this works.
I just check the upstream pysaml2 and see that allow adding context: https://github.com/IdentityPython/pysaml2/blob/v4.9.0/src/saml2/client_base.py#L314

**Comment by adborden** [comment]
@avdata99 I don't think matching the the email domain is the right way, that list could potentially be all government domains. I think really what we're after is PIV card authentication which requires us to set the Authentication Assurance Level via the `requested_authn_context` as you point out in pysaml2.

I think what this means:
- [ ] Add CKAN config for `ckanext.saml2auth.requested_authn_context` to ckanext-saml2auth
- [ ] Update ckanext-saml2auth to include `requested_authn_context` as kwargs in [prepare_for_authenticate()](https://github.com/keitaroinc/ckanext-saml2auth/blob/6670cd01240244ad1d960abdb0862ccdcba98398/ckanext/saml2auth/views/saml2auth.py#L162)
- [ ] Update staging and production environments to include the configuration `ckanext.saml2auth.requested_authn_context = http://idmanagement.gov/ns/assurance/aal/3?hspd12=true`

Does this make sense? I'm not familiar with the ckanext-saml2auth code, but it looks like calling prepare_to_authenticate will pass the kwargs down to the method you pointed out.

**Comment by adborden** [comment]
... except that requested_authn_context should be passed into prepare_for_authenticate() as an object, it's not really a single string type. It might look similar to the old code from the max.gov fork:
```python
prepare_kwargs = {}
if config.get('saml2auth.requested_authn_context'):
    requested_authn_context = samlp.RequestedAuthnContext()
    prepare_kwargs['requested_authn_context'] = requested_authn_context
    for item in config.get('saml2auth.requested_authn_context', []):
        context_class_ref = saml.AuthnContextClassRef()
        context_class_ref.text = item
        requested_authn_context.authn_context_class_ref.append(context_class_ref)

client.prepare_to_authenticate(**prepare_kwargs)
```

**Comment by adborden** [comment]
I opened https://github.com/keitaroinc/ckanext-saml2auth/issues/24 upstream to get some feedback on implementation and suggest it be part of a plugin interface.

**Comment by hkdctol** [comment]
Confirmed that on https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/ you can't log in with a nongov/no PIV card login account.
