### ISSUE TITLE
Incorporate IaaS-level diagrams and descriptions into SSB SSP sections 1-12

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2534]
## User Story

In order to sign off on our readiness for ATO submission, GSA ISE wants to review a description of the IaaS portion of our deployment in sections 1-12 of the the SSB SSP.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I am viewing [the SSB SSP](https://docs.google.com/document/d/15bP07LtTXY2gvNHlM_reehTp4_k3tMZh/edit#heading=h.gjdgxs) description of the IaaS portion of our deployment \
  WHEN I review sections 9 and 10 \
  THEN I see diagrams ([1](https://docs.google.com/document/d/15bP07LtTXY2gvNHlM_reehTp4_k3tMZh/edit#bookmark=id.tjju555h0jnb)) ([2](https://docs.google.com/document/d/15bP07LtTXY2gvNHlM_reehTp4_k3tMZh/edit#bookmark=id.sbmedcbsxkvy)) and [narratives](https://docs.google.com/document/d/15bP07LtTXY2gvNHlM_reehTp4_k3tMZh/edit#heading=h.pef56067y099) that include details about the brokered AWS EKS and Solr instances. 

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
For this issue we're just going to be documenting the AWS EKS service as-is today. That is, not directly addressing the OCISO container-scanning wishlist. Future issues will take those requirements on piece-by-piece (eg implement a requirement and update that section of the docs).

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
[Source for the existing diagrams](https://github.com/GSA/datagov-compliance/blob/master/solr-service-scratchpad.md)

[Live editor for PlantUML](http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000)

[A sample diagram for the terraform-aws-eks module](https://gruntwork.io/repos/images/v0.29.1/terraform-aws-eks/_docs/eks-architecture.png?raw=true) we're using. In our case, there are no worker nodes, only Fargate.

**Comment by adborden** [comment]
@mogul when you have a moment can you add data-gov-admins to [GSA/datagov-compliance](https://github.com/GSA/datagov-compliance)?

**Comment by mogul** [comment]
> @mogul when you have a moment can you add data-gov-admins to [GSA/datagov-compliance](https://github.com/GSA/datagov-compliance)?

Done, sorry about that.

**Comment by mogul** [comment]
Aaron and I paired today to do a first-pass through sections 9-10. We indicated where sections should have a separate narrative for the "SSB Application Boundary" vs the "SSB Managed Boundary". We also left comments on what needed to be done throughout.

**Comment by mogul** [comment]
There are still some specific points to cover in Section 9, but I managed to get through all of section 10.7 yesterday.

**Comment by mogul** [comment]
Completed section 10.8 today.

**Comment by mogul** [comment]
Completed section 10.9 today. 

It's going to be a happy new year! 🥳 

(Lots of issues were created along the way and we have a lot to do, but the compliance docs are done.)
