### ISSUE TITLE
Upgrade Wordpress Version

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2539]
## User Story

In order to keep www.data.gov easy to update and secure, the team wants www.data.gov to be running the most recent supported version of WordPress (5.6.0).

## Acceptance Criteria

- [ ] GIVEN I am logged into WordPress as an admin \
 WHEN I look at the version information in the lower-right of the dashboard \
 THEN I see that the version is 5.6.0 or higher

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
We believe this will only improve our security posture with no changes to overall architecture/deployment.

**Comment by hkdctol** [comment]
closing as we've left wordpress
