### ISSUE TITLE
Polish data.gov components SSP for ATO submission

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2543]
## User Story

In order to submit data.gov components on cloud.gov for ATO, the GSA A&A team wants to see no internal "todo" notes in the SSP.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I have opened [the draft SSP](https://docs.google.com/document/d/1WuoO419OV-SHiQU5k_IWZYsWbjPE_VXmj-jNMH0KDDI/edit#heading=h.gjdgxs) \
  AND I have opened the [draft Contingency Plan](https://docs.google.com/document/d/1fZ6IF-sS7O0w4b5rFP0NdngbkuHQ1SBBXza_61w69-Y/edit#) \
  AND I have opened the [draft Business Impact Analysis](https://docs.google.com/document/d/1kF9MhpzkHZpdXZNDBnta4Yj0Ccv3Gri3uWauTpB6EBc/edit) \
  AND I have opened the [draft Configuration Management Plan](https://docs.google.com/document/d/1XTfrqywAc08luDJiYvKrKyswuWY3NXmLjIYBMxuOHYc/edit#) \
  WHEN I search for comments \
  THEN I see no comments indicating that further content is needed

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
We left a grab-bag of items in the SSP and other documents for later explication, some because we didn't know the answers at the time (eg whether we were going to use OMB MAX or login.gov for authentication), or because the scope changed to incorporate all components halfway through the process. Now we need to revisit those items to ensure they're sufficiently detailed for our ATO submission.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, everything we're working on is in a permission-controlled Google Drive folder. 

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

For the System Security Plan: 
- [x] Address notes in the narratives for each of these controls:
  - [x] AC-2 (4)
  - [x] AC-3
  - [x] AC-7
  - [x] AC-11
  - [x] AC-20
  - [x] AU-3 (1)
  - [x] AU-6 (3)
  - [x] AU-7
  - [x] AU7 (1)
  - [x] AU-9
  - [x] AU-9 (4)
  - [x] CM-7 (4)
  - [x] CM-8 (3)
  - [x] CP-3
  - [x] CP-9
  - [x] IR-4 (1)
  - [x] SA-3
  - [x] SA-10 – Jason
  - [x] SC-7
  - [x] SC-20
  - [x] SI-4

For the [Contingency Plan (CP)](https://docs.google.com/document/d/1fZ6IF-sS7O0w4b5rFP0NdngbkuHQ1SBBXza_61w69-Y/edit#): 
- [x] General text
  - [Appendix C](https://docs.google.com/document/d/1vshttklBlj7irGQaZ_Y-1NOT181BzA9Z/edit?disco=AAAAKnecaBA) wil be elaborated in the course of completing https://github.com/GSA/datagov-deploy/issues/2768

For the Business Impact Analysis (BIA):
- [x] Needs review by Hyon

For the draft [Configuration Management Plan (CM Plan)](https://docs.google.com/document/d/1XTfrqywAc08luDJiYvKrKyswuWY3NXmLjIYBMxuOHYc/edit#):
- [x] Needs review by Bret

**Comment by mogul** [comment]
Blocked waiting for access to the new documents from Lynnette.

**Comment by hkdctol** [comment]
I've added the data.gov specific test items to that table in Contingency Plan. I have reviewed BIA. Did not see any changes but there were two sections just want to double check that no updates are needed and assigned to @mogul and just asked Lynnette for access to doc so you can make any edits that are needed.

**Comment by hkdctol** [comment]
@mogul I think all that's left on this ticket are a few places where I've left comments for you in BIA for any required updates for cloud.gov environment.
