### ISSUE TITLE
Sign and verify images made/used in all Makefiles and docker-compose files

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2544]
## User Story

In order to have a verifiable supply chain for Docker-based workflows and operations, the team wants to use Docker Content Trust to verify pulled images haven't been tampered with before using them.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN we set our environment to use [a registry with tampered images](https://docs.docker.com/engine/security/trust/trust_sandbox/#test-with-malicious-images) \
  WHEN we run a `make` or `docker-compose` that pulls its images from that registry \
  THEN we see an error indicating that the image could not be verified.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
We mostly use Docker Official Images from hub.docker.com, where the images were based on Dockerfiles provided directly by the teams that create the software. These images are generated directly by Docker Hub, which uses Notary to sign the created images. However, we aren't checking those Notary signatures when we pull and use images. We should!

See [section 10.8.4](https://docs.google.com/document/d/1WuoO419OV-SHiQU5k_IWZYsWbjPE_VXmj-jNMH0KDDI/edit#heading=h.lxouofl0149) in the data.gov SSP for additional context.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
This only tightens our security and makes it obvious whenever we do not rely on official images (because they will fail to run).

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]
- In all Makefiles: Make sure we set `DOCKER_CONTENT_TRUST=1`.
- Use [`trusted-compose`](https://medium.com/sse-blog/bringing-content-trust-into-the-world-of-docker-compose-12836b3537d) instead of `docker-compose`.
- In our own Dockerfiles, prefix any referenced image name with an environment variable:
```
ARG DOCKER_REGISTRY
FROM ${DOCKER_REGISTRY}debian:stable
```

**Comment by adborden** [comment]
Just want to add that we should consider https://github.com/GSA/eks-brokerpak/issues/13 when looking at this story. We'd prefer to use the same signature/verification scheme for container images in local development and production.

**Comment by mogul** [comment]
I just stumbled across [cosign](https://github.com/sigstore/cosign) which might be useful in a variety of workflows!

**Comment by mogul** [comment]
Related: the umbrella [sigstore](https://sigstore.dev/what_is_sigstore/) project.

**Comment by mogul** [comment]
`compose` is now available as a sub-command of the main `docker` binary. I _think_ if we use it that way then `DOCKER_CONTENT_TRUST` is all we need.

**Comment by mogul** [comment]
Seems like maybe [the existing Alpine image on which so much is based hasn't been signed for a while](https://gitlab.alpinelinux.org/alpine/tsc/-/issues/34)...?

**Comment by mogul** [comment]
Seems like maybe [the existing Alpine image on which so much is based hasn't been signed for a while](https://gitlab.alpinelinux.org/alpine/tsc/-/issues/34)...?
