### ISSUE TITLE
Redis restart fails when password changes

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2548]
## How to reproduce

If the redis password gets changed, then the service fails to restart/pickup the new password change. This leaves the harvester in a bad state - specifically the harvester_run will fail due to a redis password error. This issue is [documented upstream](https://github.com/DavidWittman/ansible-redis/issues/115).

## Expected behavior

When we change the redis password and run the playbooks, then the new password is recognized and all services are running as expected.

## Actual behavior

When we change the redis password and run the playbooks it puts the harvester in a bad state - and there may be other unrecognized issues as well.

**Comment by chris-macdermaid** [comment]
A work around is to log into the server running redis and kill the redis process by running 'kill <redis process id>' Redis will not be stopped by running 'service redis stop'

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
