### ISSUE TITLE
inventory2p "RSA certificate for ckan:443 does NOT include an ID with matches the server name"

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#2556]
inventory2p.prod-ocsit.bsp.gsa.gov:/var/log/inventory/ckan.error.log is reporting this error:

[Thu Dec 10 18:25:10.666338 2020] [ssl:warn] [pid 6054:tid 139980101977984] AH01909: RSA certificate configured for ckan:443 does NOT include an ID which matches the server name

**Comment by jbrown-xentity** [comment]
This log entry can be safely ignored. Closing.
