### ISSUE TITLE
Update extensions for CKAN 2.9

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2560]
## User Story

In order to ensure data.gov can be upgraded to CKAN 2.9, Data.gov developers want continuous integration environments enabled for CKAN 2.9.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
Really rough evaluation of [CKAN 2.9 compatibility](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0), mainly looking at whether or not CI exists for ckan 2.9 environments.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
Tracked to completion here,
- https://github.com/GSA/datagov-deploy/issues/3401#issuecomment-1001082123
