### ISSUE TITLE
Command Injection

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#2561]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.m8mg1ef0svcl)._

**Date of report:** 2020-12-13
**Severity:** Moderate
**Due date:** 2021-3-13

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
See Google Doc
https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.m8mg1ef0svcl

**Comment by pjsharpe07** [comment]
pivoted from using node-sass and instead started using [gulp-dart-sass](https://github.com/GSA/resources.data.gov/blob/develop/package.json#L17)
