### ISSUE TITLE
Incorrect/Missing Health Check requests

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2568]
data.gov sites have Health Check endpoints configured to received request from Netscaler/AWS_ELB Load Balancers. 
1. [catalog sites](https://github.com/GSA/datagov-deploy/wiki/catalog.data.gov#cdn-and-health-checks)
2. [inventory sites](https://github.com/GSA/datagov-deploy/wiki/inventory.data.gov#health-checks)
3. [wordpress sites](https://github.com/GSA/datagov-deploy/wiki/www.data.gov#cdn-and-health-checks)
4. [dashboard sites](https://github.com/GSA/datagov-deploy/wiki/Dashboard#health-checks)

However, some sites are not seeing correct the requests, as recorded in this [google doc](https://docs.google.com/spreadsheets/d/1Qee_TQuLGEASnZ08v1rLBf47kes2KDSoPPTphfXNfc4).

## How to reproduce

Inspect the access.log.

## Expected behavior

Correct health check requests.

## Actual behavior

Incorrect/Missing health check requests on some instances. 

## Sketch
1. Verify instances generate correct response codes to Health Check requests.
2. Contact BSP to correct Netscaler Health Check configuration.
3. Terraform changes in [infrastructure-modules](https://github.com/GSA/datagov-infrastructure-modules) to correct ELB Health Check configuration.
4. Update [google doc](https://docs.google.com/spreadsheets/d/1Qee_TQuLGEASnZ08v1rLBf47kes2KDSoPPTphfXNfc4).

**Comment by nickumia-reisys** [comment]
Data.gov is on cloud.gov now,
- https://github.com/GSA/data.gov/issues/3555
- https://github.com/GSA/data.gov/issues/3554
- https://github.com/GSA/data.gov/issues/2788
- https://github.com/GSA/data.gov/issues/3541
- https://github.com/GSA/data.gov/issues/3891
