### ISSUE TITLE
Inventory authentication extension

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2575]
## User Story

As an inventory developer, I want a well defined authentication extension so that authentication is well documented, can be changed, and the logic is isolated for inventory.

## Acceptance Criteria
- [x] GIVEN inventory web is running \
  and the ckanext-inventory_auth extension is enabled \
  WHEN an anonymous user requests any page other than a resource \
  THEN the user is redirected to the login page (or equivalent)

## Background
From research on [inventory anonymous user seeing dataset pages in inventory-2.8](https://github.com/GSA/datagov-deploy/issues/2314)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
Should contain tests to verify that pages and API is inaccessible

## Sketch
We will want to create and store this extension in the [inventory-app](https://github.com/gsa/inventory-app).
Utilize the [CKAN documentation](https://docs.ckan.org/en/2.9/extensions/) and [previous extension work](https://github.com/GSA/ckanext-datagovcatalog).
The original implementation of this is [here](https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L581-L593), but behavior was inconsistent and some metadata was discoverable that was not intended. Use this as a starting point, but may need to implement access limitations for all CKAN actions except for resource viewing/download access.

**Comment by chris-macdermaid** [comment]
Ran into this open CKAN issue: 
Chained auth functions lose anonymous access
https://github.com/ckan/ckan/issues/5751

We can create a auth chain in the new extension for logged in users, but because of the open issue this won't work to allow anonymous users to see resources. There is an active open [PR](https://github.com/ckan/ckan/pull/5756) to fix this.

**Comment by pjsharpe07** [comment]
Remaining steps for this ticket:

- [x] Rename [current extension](https://github.com/GSA/inventory-app/tree/feature/ckanext-iauth/ckanext-datagov_iauthfunctions) to be `datagov_inventory` or something similar
- [x] Confirm all changes in [ckan's default auth](https://github.com/ckan/ckan/tree/2.8/ckan/logic/auth) behavior is what we want and make any remaining changes/edits
- [x] Create a custom error template for `403` error codes
- [x] Create unit tests for this extension's iauth functionality
- [x] ~~Edit the dcat-usmetadata extension to add a disclaimer about how adding a dataset will make it public~~ _Moved to not take this step as we're asking data editor's to contact us first before adding a dataset_
- [x] Edit inventory's [production.ini](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/inventory/templates/etc/ckan/production.ini) authorization section. Copy this over to development's .ini file as well
- [x] Will probably need to create new ansible variable to [pre-pend the auth extension only on inventory-next](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/inventory/templates/etc/ckan/production.ini#L112)
- [x] Confirm that using a [local path in the requirements-freeze file](https://github.com/GSA/inventory-app/blob/feature/ckanext-iauth/requirements-freeze.txt) will work when [deployed with ansible](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/inventory/tasks/main.yml#L67-L73)

**Comment by pjsharpe07** [comment]
We should be wary about [the functionality of auth defaulting to an ip address if no user is found](https://github.com/ckan/ckan/blob/2.8/ckan/logic/auth/get.py#L263-L270). We haven't seen this in local testing yet (default is an empty string). Leaving this here as an artifact.

**Comment by pjsharpe07** [comment]
[Google Sheet](https://docs.google.com/spreadsheets/d/15klFAYtanNWoVww14I3wC5IT1Vjv65DjEamjrl8cIOU/edit#gid=0) for current state of site access for anonymous vs logged in user

**Comment by mogul** [comment]
@chris-macdermaid and @jbrown-xentity will be pairing through a review to get this one wrapped up.
