### ISSUE TITLE
Load spikes on catalog-next

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#2581]
## How to reproduce

Around 4:30 UTC daily the load spikes on catalogweb[1,2]p and catalogbweb[1,2]. 

The load stays high for about an hour. During this spike hosts become unreachable. New Relic alerts on the load and unreachable server. 

The load stays high for about an hour and then comes down. Most times the host is reachable after the spike, but sometimes the host is still unreachable even after the load comes down. In those cases a BSP request needs to be submitted to reboot the host.

A reboot was needed on 12/16/2020 and 12/22/2020

At the same time there is a PyCSW worker time out

```
[2020-12-18 04:32:39 +0000] [2015] [CRITICAL] WORKER TIMEOUT (pid:2064)
[2020-12-19 04:53:07 +0000] [2046] [CRITICAL] WORKER TIMEOUT (pid:2100)
[2020-12-20 05:04:59 +0000] [2046] [CRITICAL] WORKER TIMEOUT (pid:16801)
```

CKAN logs and syslogs didn't appear to show anything significant at that time

![Screenshot from 2020-12-23 09-58-33](https://user-images.githubusercontent.com/64213093/103020814-5ac65600-4506-11eb-993b-5d6f10b4dae8.png)
![Screenshot from 2020-12-23 09-58-04](https://user-images.githubusercontent.com/64213093/103020815-5b5eec80-4506-11eb-9385-879025a99913.png)

**Comment by FuhuXia** [comment]
Reading from log, the downtime matches the requests `GET /datajson`
```
root@catalogbweb1p:/var/log/ckan# zgrep 'GET /data.json' /var/log/ckan/ckan.access.log.*|head -5
/var/log/ckan/ckan.access.log.1.gz:10.177.16.71 - - [28/Dec/2020:04:54:23 +0000] "GET /data.json HTTP/1.1" 502 0 "-" "Python-urllib/3.7"
/var/log/ckan/ckan.access.log.12.gz:10.177.16.71 - - [17/Dec/2020:04:47:42 +0000] "GET /data.json HTTP/1.1" 502 154 "-" "Python-urllib/3.7"
/var/log/ckan/ckan.access.log.17.gz:10.177.16.71 - - [12/Dec/2020:04:34:17 +0000] "GET /data.json HTTP/1.1" 502 154 "-" "Python-urllib/3.7"
/var/log/ckan/ckan.access.log.23.gz:52.222.122.97 - - [06/Dec/2020:04:28:51 +0000] "GET /data.json HTTP/1.1" 502 0 "-" "Python-urllib/3.7"
/var/log/ckan/ckan.access.log.25.gz:185.191.171.5 - - [03/Dec/2020:11:36:53 +0000] "GET /data.json HTTP/1.1" 502 544 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"
```

Endpoint `/data.json` is not supposed to open for a CKAN application with large amount of datasets.  Will create a ticket to disable this endpoint on catalog next.
