### ISSUE TITLE
ckan-jsonl-export runs out of disk space

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2583]
Data.gov does a monthly export of metadata in JSONL format, available on the [catalog](https://catalog.data.gov/dataset/data-gov-ckan-api). The job writes files to /tmp/jsonl (hardcoded) which is part of the root fs (16GB). This is not enough space.

At some point, a 50GB EBS volume was created/mounted to `/newmount` on catalog-harvester2p. This is not part of our standard setup and jobs from 2017 were using /newmount for the JSONL job (perhaps with a symlink /tmp/jsonl -> /newmount/jsonl).

## How to reproduce

From catalog-harvester2p:
1. `sudo supervisorctl start ckan-jsonl-export`

## Expected behavior

Job completes successfully, writes logs to /var/lib/ckan/jsonl-export.log, and the gzipped archive is uploaded to filestore.data.gov.

## Actual behavior

Disk fills up and the metadata archive cannot be updated.

## Sketch

- [ ] ~mount an EBS volume to a ckan data directory e.g. /var/lib/ckan~ upload directly to S3
- [ ] update the job to write to the ckan data directory (or have it configurable)
- [ ] clean up on error
- [ ] avoid writing intermediate uncompressed file, pipe directly into gzip in job

**Comment by adborden** [comment]
Even with the 50G mount, the job runs out of space on compress. If we compress as we write to disk, this will save us space, but it looks like we're close to the limit anyway. In the cloud.gov world, we'll want to upload directly to S3 since we won't have the diskspace.

```
ubuntu@catalog-harvester2p:~$ sudo ls -lh /newmount/jsonl/
total 50G
-rw------- 1 root root 52M Dec 24 05:19 jsonl-5DB10k.json.gz
-rw------- 1 root root   0 Sep  9  2017 jsonl-Iok_x9.json.gz
-rw------- 1 root root   0 Jan 22  2018 jsonl-Qs4Ngn.json.gz
-rw------- 1 root root   0 Sep  9  2017 jsonl-ugXxN6.json
-rw------- 1 root root 49G Dec 24 05:19 jsonl-wVbdX7.json
```

**Comment by adborden** [comment]
Ah, this feature might exist upstream https://docs.ckan.org/en/2.8/maintaining/database-management.html#datasets-dump

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
