### ISSUE TITLE
Netsparker 2020-12-22 reports HSTS (Strict Transport Security) Errors and Warnings

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2598]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.v1yag4y1vkdu)._

**Date of report:** 2020-12-22
**Severity:** Medium
**Due date:** 2021-03-22

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

HSTS (Strict Transport Security) Errors and Warnings across all datagov apps.

**Comment by adborden** [comment]
@FuhuXia have we done the analysis to make sure this isn't effecting other applications? Please make sure to check that box above and include any notes.

**Comment by FuhuXia** [comment]
Analysis done and checked. All apps in staging and production environments are clean.
