### ISSUE TITLE
Automate the CKAN sysadmin user creation

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#26]
For CKAN setting up the first sysadmin account is done through a command prompt after using paster command:
`ckan sysadmin add {{ user }}`
- [ ] Setup an linux `expect` script to launch the ckan sysadmin add command using Ansible variables injected as part of the secrets file.
## Approach:
- [ ] setup an expect script to automate the interactive session?
- [ ] use Ansible directly for the interactive session?

**Comment by nickumia-reisys** [comment]
This is automated on our new cloud.gov deployment.
- We have a list of sysadmins
  ![image](https://user-images.githubusercontent.com/85196563/216669956-08b3a727-672d-4b72-9c09-4ea4727e26a7.png)
- When a user logs in with `ckanext-saml2auth`, the extension reads the list and automatically applies the proper permissions on user creation.
