### ISSUE TITLE
Deploy dashboard app on cloud.gov

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2606]
## User Story

In order to reduce the operation and maintenance burden of `labs.data.gov/dashboard`, the data.gov team wants the `labs.data.gov/dashboard` application deployed on cloud.gov.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I commit a change to the `main` branch in the `GSA/project-open-data-dashboard` repository \
  AND I browse to [the CircleCI dashboard](https://app.circleci.com/pipelines/github/GSA/project-open-data-dashboard)
  THEN I see a deployment pipeline kick off \
  AND the pipeline completes successfully \
  AND the change is visible at https://dashboard-data-gov.app.cloud.gov
- [x] If any manual preparation of the target space was necessary, then an issue exists about automating that setup in future.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
We are deploying from the `main` branch to the `gsa-datagov/production` space only. Other branches and spaces are considered out of scope here. Note cronjobs are also out of scope for now.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
None. This work is being done in an environment completely separate from the existing deployment, and only open source and open data are implied.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- [x] Rename the `master` branch if necessary
- [x] Bring any existing cloud-gov branch up to date
- [x] Create any necessary services in the target space with `cf create-service`
- [x] Create a manifest.yml capturing any settings or bindings
- [x] Practice a hand-driven deployment
- [x] Ensure environment settings are installed from `$VCAP_SERVICES`
- [x] Make sure the health check is correct and passing
- [x] Make sure the homepage comes up
- [x] The README.md should have instructions for hand-deployment
- [x] Add CircleCI or GitHub Action config for deployment to the `production` space

**Comment by pjsharpe07** [comment]
We have a current working version in `development`, `staging`, and `prod` spaces. Some items to still take on:

- [x] edit the readme.md to ensure accuracy
- [x] configure the manifest.yml file to use vars.yml
- [x] enable github actions
- [x] rename `master` branch to `main`

**Comment by pjsharpe07** [comment]
Deployed through gh actions:

[staging](https://dashboard-stage-datagov.app.cloud.gov/)
[prod](https://dashboard-prod-datagov.app.cloud.gov/)

![image](https://user-images.githubusercontent.com/38019872/108399272-2bb32480-71d7-11eb-9262-a5305b5ee38e.png)
