### ISSUE TITLE
Allow organization admins to make datasets CKAN public on inventory.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2632]
## User Story

In order to use the package_search API on inventory.data.gov, data managers want to be able to make datasets public.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I am an admin of an organization
  WHEN I browse to the [dataset bulk edit page](https://inventory.data.gov/organization/bulk_process/department-of-labor)
  AND I check a dataset
  AND I click "Make Public"
  THEN the dataset is made public (`private: false`)
  AND I can see the dataset in `/api/action/package_show?fq=organization:department-of-labor`

## Background
CKAN 2.5 is missing the `include_private` parameter for `package_search`. This means data managers cannot use package_search without making their datasets public.

Department of Labor is specifically interested in this **now** so they can continue development and testing of automatically updating metadata through the inventory.data.gov.

Moving to CKAN 2.8 would resolve this issue.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
Update the dataset bulk edit CKAN template to show the make private/public buttons. Might also need to change the authorization logic to allow org admins to edit in this way.

**Comment by mogul** [comment]
This is resolved since there's a flag in 2.8 that enables searching the API. @adborden said he'd make sure they know about this, then it can be closed.

**Comment by adborden** [comment]
Reached out to Labor and let them know.
