### ISSUE TITLE
[research: 2d] Clarify Snyk exceptions in catalog-app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2643]
In order to ensure we have accounted for vulnerabilities that affect us, an auditor would expect to review Snyk findings for the catalog-app and understand which vulns do not apply to our specific usage of CKAN 2.3.

## Acceptance Criteria
- [ ] For each of the following [Snyk exceptions](https://github.com/GSA/catalog-app/blob/master/.snyk) we explicitly indicate if the vulnerability does not affect us, or if the vulnerability does affect us, why the risk is acceptable.
- [ ] An issue exists in the backlog for each finding that does affect us and for which the risk is unacceptable.

### Brief description
https://snyk.io/vuln/SNYK-PYTHON-SQLALCHEMY-590109
The exception refers to group_by which is not part of the vulnerability. Let's confirm we've audited our usage correctly.

https://snyk.io/vuln/SNYK-PYTHON-JINJA2-455616
Not sure why this only applies to forms. What about dataset search? This is a public form.

https://snyk.io/vuln/SNYK-PYTHON-JINJA2-174126
Not sure why this only applies to forms. What about dataset search? This is a public form.

https://snyk.io/vuln/SNYK-PYTHON-WEBOB-40490
Resolution says update to CKAN 2.8 but this is already overdue.

https://snyk.io/vuln/SNYK-PYTHON-SOLRPY-598893
Says "upstream" will resolve the issue. What does that mean?

https://snyk.io/vuln/SNYK-PYTHON-RSA-1038401
https://snyk.io/vuln/SNYK-PYTHON-M2CRYPTO-1040426
If there's no fix for M2Crypto, why are we shipping M2Crypto in production?

**Comment by mogul** [comment]
Is there a reason we didn't take this one on?

**Comment by jbrown-xentity** [comment]
We've been taking it offline this week, I believe this can be marked for closing due to https://github.com/GSA/datagov-deploy/issues/2838

**Comment by mogul** [comment]
Closing as this was handled by #2838... catalog-app is archived.
