### ISSUE TITLE
Rate-limit heavy users

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2645]
## User Story

In order to deliver a consistent responsive experience for users, data.gov users want rate limiting applied to applications so that power users don't negatively impact the experience of other users. 

## Acceptance Criteria

- [x] WHEN I make many requests against an application, up to the limit of X requests over Y seconds
  THEN I receive a 429 so that I know to throttle/back off

## Background
Every few days or so we get crawled  to the point of saturation, and receive alerts. One user is affecting the site performance for all other users in a disproportionate way. We expect that some partners have a good reason to crawl regularly as well, so we don't want to come down too hard on people who do it.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, although this improves our ability to deliver a consistent experience and controls against some types of DoS.

## Sketch
I think we want to implement this in apache2/nginx so that we can configure it as part of our deploy.

IP-based rate limiting is probably what we want, although we need to be careful to pay attention to CDN IP vs real-IP. I don't think we want to slow connections by bandwith like [Apache's mod_ratelimit](https://httpd.apache.org/docs/2.4/mod/mod_ratelimit.html). The sooner we can process a request and get rid of it the better. I think we should be rejecting requests that hit a limit with an http client error status code e.g. [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).

Nginx implements this in the [limit_req_module](https://nginx.org/en/docs/http/ngx_http_limit_req_module.html) and has a [rate limiting guide](https://www.nginx.com/blog/rate-limiting-nginx/). This module limits the number of requests over a configurable time interval.

[Fail2ban](https://www.fail2ban.org/wiki/index.php/Main_Page) works for both Nginx and Apache2. It can scan Nginx/Apache2 access logs, collect the true IPs of heavy users, then set IPTABLES rule to block requests containing the IPs via packet inspection. We had this implemented before.

We also need to be careful that we don't end up blocking good traffic from known-heavy users, eg GeoPlatform.

**Comment by FuhuXia** [comment]
For the past a few days the crawling traffic surfaced again, causing two SOLR slaves CPU spike and catalog-next poor Apdex score.

**Comment by jbrown-xentity** [comment]
We updated the throttle to be 120 RPM for wordpress, and 240 RPM for catalog (has to be sustained over a 5 minute period).
If another overload event occurs, we should review configuration to see if any IP's have been blocked:
- [Wordpress](https://console.aws.amazon.com/wafv2/home?region=global#/rules/detail/RATE_BASED/f0ae1920-6fae-4d12-9f24-e02ad476f0b4)
- [Catalog](https://console.aws.amazon.com/wafv2/home?region=global#/rules/detail/RATE_BASED/72d5e5d7-e330-4490-8e23-36415697df39)

**Comment by jbrown-xentity** [comment]
Will wait 2 weeks (one sprint) to see if helpful and/or tweak the configuration, otherwise we will consider closing or further testing.

**Comment by mogul** [comment]
We decided to run a test to see if we can verify that heavy access will be rate limited.

**Comment by jbrown-xentity** [comment]
In trying to get static site dump (#3465) we found that rate limiting is occurring, and blocked the scan.

We whitelisted the IP of our scanner so that we can get the full static site. Propose we can mark this as done.

**Comment by jbrown-xentity** [comment]
The running log (where you can track requests being blocked) can be found [here](https://console.aws.amazon.com/wafv2/home?region=global#/webacls/requests/be42522d-f8cf-4ca8-b7d0-6d7a858c378f)
