### ISSUE TITLE
[research: 3d] Identify options for generating a static site from CKAN

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2647]
## User Story

In order to hedge our bets against funding levels for our program's O&M, we want to spend up to three days investigating options for deploying a static site that would meet the requirements for publishing US Gov federal open data.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] We have a clear sense of whether this is even possible, and if so, what the most promising route might be

## Background

We are considering what we could do to reduce the number of moving parts in our production deployment. If there's a way to use CKAN for "authoring" (eg harvesting and indexing) and deploy a static site with the results, that might be easier to maintain without any contract help available. If not, that's also good to know for when we talk about what the bare minimum requirements are for the program in future.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

None, this is just research.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by hkdctol** [comment]
Closing this one for now in light of ongoing static site work

**Comment by nickumia-reisys** [comment]
Continued journey of the static site:
- https://github.com/GSA/data.gov/issues/3743
- https://github.com/GSA/data.gov/issues/3891
- https://github.com/GSA/data.gov/issues/4029
- https://github.com/GSA/data.gov/issues/4141
