### ISSUE TITLE
Error downloading data.json file with data_quality value is "Yes"

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2654]
When creating a new dataset, selecting Yes in the data quality field gives a value of string "Yes" to the field. It generates an error when user downloads the data.json file, therefore the dataset can't be published.

Error log when downloading the data.json.
```
[('Invalid Field Value (Optional Fields)', ['The field \'dataQuality\' must be true or false, as a JSON boolean literal (not the string "true" or "false"). (1 locations)'])]
```

**Comment by FuhuXia** [comment]
Per user request, manual edit of the DB field, updating the value from `'Yes'` to `true` for key of `data_quality` ,  eliminates the error and gets data.json downloaded.  It is a workaround not a fix.

**Comment by osahon-okungbowa** [comment]
@cmugisha this has been completed and deployed to sandbox today. I don't have access to this repo, so please move to QA.

**Comment by FuhuXia** [comment]
The change is live on production.

**Comment by adborden** [comment]
Confirmed this is fixed on production.
