### ISSUE TITLE
"Ensure core dumps are restricted" task consistently fails with sysctl error trying to apply IPv6 settings to disabled IPv6 subsystem

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2655]
The common playbook fails the first time it is run in our staging environment. The step is consistent at [gsa.ansible-os-ubuntu-16 : 1.5.1 | Ensure core dumps are restricted](https://github.com/GSA/ansible-os-ubuntu-16/blob/master/tasks/section1.yml#L159-L167). Error:

`"msg": Failed to reload sysctl...
No such file or directory sysctl: cannot stat /proc/sys/net/ipv6/cibf/default/accept_redirects: No such file or directory
`

This doesn't seem to be affecting all hosts.

## How to reproduce

1. Running the common playbook on staging the first time.

## Expected behavior

Playbook runs without failure the first time.

## Actual behavior

Playbook fails its first run. This step is successful running the common playbook again.

**Comment by pjsharpe07** [comment]
We saw this for the first time during [the 2021-02-04](https://github.com/GSA/datagov-deploy/issues/2712) release in production

**Comment by adborden** [comment]
Same step, also on some hosts it's more than one sysctl that fails:
```
08:05:34  fatal: [catalogharvester1p.prod-ocsit.bsp.gsa.gov]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: fs.suid_dumpable = 0\nkernel.randomize_va_space = 2\nnet.ipv4.ip_forward = 0\nnet.ipv4.conf.all.send_redirects = 0\nnet.ipv4.conf.default.send_redirects = 0\nnet.ipv4.conf.all.accept_source_route = 0\nnet.ipv4.conf.default.accept_source_route = 0\nnet.ipv4.conf.all.accept_redirects = 0\nnet.ipv4.conf.default.accept_redirects = 0\nnet.ipv4.conf.all.secure_redirects = 0\nnet.ipv4.conf.default.secure_redirects = 0\nnet.ipv4.conf.all.log_martians = 1\nnet.ipv4.conf.default.log_martians = 1\nnet.ipv4.icmp_echo_ignore_broadcasts = 1\nnet.ipv4.icmp_ignore_bogus_error_responses = 1\nnet.ipv4.conf.all.rp_filter = 1\nnet.ipv4.conf.default.rp_filter = 1\nnet.ipv4.tcp_syncookies = 1\nvm.overcommit_memory = 1\nsysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_ra: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv6/conf/default/accept_ra: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_redirects: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv6/conf/default/accept_redirects: No such file or directory\n"}
```

**Comment by adborden** [comment]
Moving this to New to re-consider for triage. This ends up blocking automated deploys often enough, and even though the failure happens 7 minutes into the build, you don't usually get feedback until the end ~50 minutes. Since we're doing staged rollouts, you could hit this on each environment, staging, production, mgmt, having to retry 3 times before getting a successful build through.

**Comment by adborden** [comment]
There's a related bug in ansible-ubuntu-16 where multiple GRUB_CMDLINE_LINUX lines are appended to the grub config. Only the last one will apply. This means that we're not setting all the security options that are intended.

**Comment by adborden** [comment]
```
$ grep GRUB_CMDLINE_LINUX= /etc/default/grub
GRUB_CMDLINE_LINUX=apparmor="1 security=apparmor"
GRUB_CMDLINE_LINUX="ipv6.disable=1"
GRUB_CMDLINE_LINUX="audit=1"
```

This is probably why this issue doesn't affect all machines consistently. Depending on the order, some machines might have ipv6 enabled, some would be disabled.

**Comment by adborden** [comment]
_edit: this is not necessary._

~Find all offending lines.~

    $ dsh -g all grep 'GRUB_CMDLINE_LINUX=\"ipv6.disable=1\"' /etc/default/grub

~Remove all offending lines:~

    $ dsh -g all sudo sed -i -e '/GRUB_CMDLINE_LINUX=\"ipv6.disable=1\"/d' /etc/default/grub

~Update grub to pick up the config change:~

    $ dsh -g all sudo update-grub2

**Comment by adborden** [comment]
To fix, run the common playbook to apply the correct grub/sysctl configuration. Because of this issue, you might have to run it twice.

    $ ansible-playbook common.yml --tags hardening

Manually update GRUB:

    $ dsh -g all sudo update-grub2

Reboot hosts to pick up the change.

    $ ansible-playbook actions/reboot.yml -e force_reboot=1
