### ISSUE TITLE
[research 0.5d] Determine Identity Assurance Level (IAL) for login.gov usage

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2660]
## User Story

In order to reduce the burden for agency users while meeting compliance requirements for identity management, data.gov PMO wants to understand what Identity Assurance Level to use within the SSP.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] WHEN I audit our Digital Identity Acceptance Statement and related compliance documentation
  THEN I see GitHub issues for implementation  in our Account Management process and Login.gov that would satisfy our IAL, AAL, and FAL levels.

## Background
[SP-800-63](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63-3.pdf) describes digital identity guidelines and [OMB M-04-4](https://georgewbush-whitehouse.archives.gov/omb/memoranda/fy04/m04-04.pdf) describes E-Authentication guidance.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by adborden** [comment]
Not being familiar with the compliance requirements, I just want to capture this thought:

From a security perspective, I don't think there's a requirement for identity proofing (Identity Assurance Level) within data.gov applications. We do care about Authentication Assurance Level, though, AAL3+HSPD12, which requires PIV card to authenticate.

Taking Inventory as an example, we don't really care that the users are who they say they are or that they're tied to a specific identity. Agency data managers essentially dictate who has access to their metadata and provide us a list of email addresses. We only care that they can prove via PIV that they are tied to that email address.

**Comment by adborden** [comment]
The work to specify AAL3+HSPD12 for CKAN applications is https://github.com/GSA/datagov-deploy/issues/2526

**Comment by jbrown-xentity** [comment]
We should review the digital identity statement

**Comment by adborden** [comment]
We've determined that IAL1 is correct for Data.gov. We've updated the Digital Identity Acceptance Statement and will submit it for review. I reached out to Login.gov to go forward with IAL1.

@mogul anything left to do on the cloud.gov side? I assume we're sharing the same DIAS document.

**Comment by mogul** [comment]
Since all the factors surrounding our implementation of login.gov are functionally the same after we move to cloud.gov, there are no changes to be made to IAL/AAL/FAL.

**Comment by adborden** [comment]
In that case, there are no follow up issues for implementation beyond what already exists. Moving this to Done.
