### ISSUE TITLE
Information disclosure in datastore_search_sql in Inventory

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2661]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.ggrdzkd36d3x)._

https://hackerone.com/reports/1079477

**Date of report:** 01/15/2021
**Severity:** Low
**Due date:** 04/15/2021

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by adborden** [comment]
Some analysis is tracked in https://github.com/GSA/datagov-deploy/issues/2659

**Comment by mogul** [comment]
This may be fixed fully in an upstream release by now... We need to check as resolving that way is much-preferred compared to forking our version to add it. If not, then we should be contacting the maintainers to talk about that plan.

**Comment by FuhuXia** [comment]
Upstream has not release the patch yet. Inquiry sent 4 days ago. We plan to patch it in a forked branch if no response from maintainer in the next a few days.

**Comment by FuhuXia** [comment]
Fix deployed to prod. 
![Screen Shot 2021-04-23 at 3 54 55 PM](https://user-images.githubusercontent.com/1392461/115923555-68f09880-a44c-11eb-9121-90001c2e7e8a.png)
