### ISSUE TITLE
Catalog Postgres DB upgrade to 9.6

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2667]
## User Story

Due Date: 2/16/2021

In order to have a compliant database, data.gov operators need to upgrade catalog Postgres 9.5 instances to 9.6 (EOL Nov 2021).

## Acceptance Criteria

- [ ] GIVEN the Postgres DB is connected to catalog app
  WHEN a user runs `SELECT version()` \
  THEN the version is reported as 9.6

## Background
[Previous upgrade](https://github.com/GSA/datagov-deploy/issues/1548)
[AWS upgrade documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Check that the documentation reflects the correct versions.

## Sketch
For sandbox, will need to remove current DB and create new DB (via terraform) with 9.6.

Need to schedule with BSP to do on staging and validate. Then schedule and implement on prod.

**Comment by FuhuXia** [comment]
Confirmed catalog-next are running on Postgres 9.6 with POSTGIS 2.3.7 in all environments. Catalog classic DB upgrade is on hold.

During the version check, Sandbox catalog-next shows postgis needs an update.
```
=> SELECT postgis_full_version();

POSTGIS="2.3.7 r16523" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.4, released 2017/06/23" LIBXML="2.9.1" LIBJSON="0.12" (core procs from "2.3.0 r15146" need upgrade) RASTER (raster procs from "2.3.0 r15146" need upgrade)
```
After a update command the results look clean.
```
=> ALTER EXTENSION postgis UPDATE;
=> SELECT postgis_full_version();
POSTGIS="2.3.7 r16523" PGSQL="96" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.4, released 2017/06/23" LIBXML="2.9.1" LIBJSON="0.12" RASTER
```

Only done on sandbox. Staging and Production postgis are already up to date.
