### ISSUE TITLE
Inventory Postgres DB Upgrade to 9.6

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2668]
## User Story

Due Date: 2/16/2021

In order to have a compliant database, data.gov operators need to upgrade inventory Postgres 9.5 instances to 9.6 (EOL Nov 2021).

## Acceptance Criteria

- [ ] GIVEN the Postgres DB is connected to inventory app
  WHEN a user runs `SELECT version()` \
  THEN the version is reported as 9.6

## Background
[Previous upgrade](https://github.com/GSA/datagov-deploy/issues/1548) (may be less relevant for inventory, as no read-replicas are utilized).
[AWS upgrade documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Check that the documentation reflects the correct versions.

## Sketch
For sandbox, will need to remove current DB and create new DB (via terraform) with 9.6.

Need to schedule with BSP to do on staging and validate. Then schedule and implement on prod.

**Comment by FuhuXia** [comment]
REQ0582645 was submitted.

Steps proposed:

1. data.gov team stops db write activities.
2. FCS takes final snapshots.
3. FCS restores snapshot to new instance and have it upgraded to 9.6
4. data.gov team run ANALYZE psql command.
5. data.gov team runs anisble playbooks with new RDS instance variable. 
6. data.gov team verifies datapusher is working.
7. FCS delete old 9.5 RDS instances.

**Comment by FuhuXia** [comment]
Sandbox and Staging Inventory CKAN DBs are on postgres 9.6.  Production are on 9.5.

**REQ0583047** open for request Production Postgres 9.5 -> 9.6 upgrade.

Same steps as mentioned on [Inventory Datastore upgrade](https://github.com/GSA/datagov-deploy/issues/2670#issuecomment-770087699).

**Comment by FuhuXia** [comment]
Inventory production DB upgraded to 9.6 and verified.
