### ISSUE TITLE
CSW Postgres DB upgrade to 9.6

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2669]
## User Story

Due Date: 2/16/2021

In order to have a compliant database, data.gov operators need to upgrade csw Postgres 9.5 instances to 9.6 (EOL Nov 2021).

## Acceptance Criteria

- [ ] GIVEN the Postgres DB is connected to csw app
  WHEN a user runs `SELECT version()` \
  THEN the version is reported as 9.6

## Background
[Previous upgrade](https://github.com/GSA/datagov-deploy/issues/1548) (may be less relevant for csw, as no read-replicas are utilized).
[AWS upgrade documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Check that the documentation reflects the correct versions.

## Sketch
For sandbox, will need to remove current DB and create new DB (via terraform) with 9.6.

Need to schedule with BSP to do on staging and validate. Then schedule and implement on prod.

**Comment by FuhuXia** [comment]
Closing based the decommissioning CSW decision from https://github.com/GSA/datagov-deploy/issues/2383.
