### ISSUE TITLE
Promote production and staging login.gov applications out of sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2673]
## User Story

In order to provide production level SLAs and compliance, data.gov data managers want the login.gov application to be using the production environment instead of the identity sandbox.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I browse to https://catalog-next.data.gov/user/saml2login
  THEN I see the production login.gov login screen
  AND I don't see the identity sandbox test banner
  AND I can login with my production login.gov account

## Background
Development and testing of Login.gov applications are done in the Identity Sandbox environment. Once testing has been validated, the applications are "promoted" to their production environment.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
- [x] reach out to login.gov to promote all the login.gov applications
  - catalog.data.gov
  - catalog-datagov.dev-ocsit.bsp.gsa.gov
  - inventory.data.gov
  - inventory-datagov.dev-ocsit.bsp.gsa.gov
  - ci.data.gov
- [x] update saml2 configuration to point to production IdP

**Comment by adborden** [comment]
Pinged the login.gov thread.

**Comment by mogul** [comment]
@adborden will ping again today.

**Comment by adborden** [comment]
We met with Login.gov folks on Tuesday, a small issue with the IAA is being resolved.

**Comment by mogul** [comment]
Pinged login.gov again today. There's a meeting on Tuesday; we'll check back in after that, and hope there will be resolution next week.

**Comment by mogul** [comment]
Escalated again today.

**Comment by mogul** [comment]
Latest word is that it should be done this week (eg tomorrow). 🤞

**Comment by mogul** [comment]
MOU is clear!

**Comment by FuhuXia** [comment]
PR ⬆️  ready and waiting for the sandbox-> prod move. No words when it will happen, but according to [login.gov site](https://developers.login.gov/production/):

> Regular deployments occur every Thursday by the close of the business day.

**Comment by FuhuXia** [comment]
Login.gov team plans to manually deploy our apps today. We are inquiring on their support channel to see the actual promotion process is a MOVE or COPY process from sandbox to production. COPY is preferred. Some downtime is expected if it is MOVE.

**Comment by mogul** [comment]
The answer is that they COPY.
![image](https://user-images.githubusercontent.com/47762/112361323-7b7e8300-8c90-11eb-9055-98fcf3034dd8.png)

**Comment by FuhuXia** [comment]
FCS catalog, inventory and jenkins are using login.gov production. This can be closed.
