### ISSUE TITLE
Harvest Abort Job Command in Production Causes Harvester to Go Down

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/data.gov#2685]
## How to reproduce

Access catalogharvester1p.prod-ocsit.bsp.gsa.gov and use command `harvester job_abort` on a large sources like [usgs-lidar-point-cloud-las-harvest-source](https://catalog-next.data.gov/harvest/usgs-lidar-point-cloud-las-harvest-source) 

## Expected behavior

It should abort the job and not cause server performance issues

## Actual behavior

It does not abort the job and causes performance [issues](https://one.newrelic.com/launcher/nrai.launcher?pane=eyJuZXJkbGV0SWQiOiJhbGVydGluZy11aS1jbGFzc2ljLmluY2lkZW50cyIsIm5hdiI6IkluY2lkZW50cyIsImluY2lkZW50SWQiOiIyMTA2NTM5NzgifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucmFpLm5hdmlnYXRpb24tYmFyIiwibmF2IjoiSW5jaWRlbnRzIn0=&platform[accountId]=1601367)

**Comment by adborden** [comment]
Should this be reported upstream as well?

**Comment by thejuliekramer** [comment]
> Should this be reported upstream as well?

Upstream to CKAN?

**Comment by adborden** [comment]
Probably upstream to ckanext-harvest. It's not data.gov specific code that has the problem, it's the abort job doesn't handle large harvest sources. Am I understanding that right?

**Comment by thejuliekramer** [comment]
I think it does handle it but the job takes up  a lot of server capacity which we  didn't have before this change - do you think I should report that this job can cause  performance  issues?

**Comment by thejuliekramer** [comment]
@adborden I created this issue upstream https://github.com/ckan/ckanext-harvest/issues/430
