### ISSUE TITLE
New login.gov saml2 user session does not expire 

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2687]
After user logs into inventory-next via login.gov, the sessions seems to stay valid forever until manually click logout button.

## How to reproduce

Log into inventory-next.sandbox.datagov.us. Keep it idle for 50 mins or longer, then refresh page.

## Expected behavior

User should be logged out.

## Actual behavior

User session is still alive. 

## Sketch
The value for `beaker.session.timeout` on current production is set as 3000 (i.e. 50 mins)

**Comment by adborden** [comment]
Also double check the session timeout matches our documentation in the SSP.

**Comment by hkdctol** [comment]
@FuhuXia was this only an issue when inventory was still on FCS? It's not like that on cloud.gov though I'm not sure of the time period.

**Comment by FuhuXia** [comment]
@hkdctol Verified that Inventory session was timed out after 15 min, matching SSP. https://github.com/GSA/datagov-deploy/issues/2751

This can be closed.
