### ISSUE TITLE
Require PIV card authentication for ci.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2692]
## User Story

In order to meet our compliance requirements of mutlifactor auth, data.gov team wants ci to contain the necessary saml2 requirements to force PIV card usage from idp.

## Acceptance Criteria

- [ ] WHEN I got to ci.data.gov \
  THEN I'm redirected to login.gov \
  AND login.gov requires PIV and associated PIN

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
To force multi-factor and insure gov personnel only.

## Sketch

- [ ] Add authentication request context yaml option to jenkins configuration-as-code.

**Comment by jbrown-xentity** [comment]
Need to validate if whole team can/has PIV cards before implementing this.

**Comment by adborden** [comment]
Branch here: https://github.com/GSA/datagov-deploy/tree/feature/jenkins-piv

**Comment by adborden** [comment]
This was implemented, PIV is required on CI.

**Comment by adborden** [comment]
nm, it hasn't been merged.

**Comment by nickumia-reisys** [comment]
No more Jenkins,
- https://github.com/GSA/data.gov/issues/3710

Also, `ci.data.gov` has just expired and we don't use it anymore...
![image](https://user-images.githubusercontent.com/85196563/216735482-51f5b796-ac6b-42af-be90-d521c6c5ba66.png)
