### ISSUE TITLE
Login requests are redirected to /user/login instead of /user/saml2login

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2702]
When I browse to a URL that requires authorization, (maybe my session expired), I'm redirected to the /user/login page which is disabled. Instead I should be redirected to /user/saml2login where I can start the login process.

Related:
- https://github.com/GSA/datagov-deploy/issues/1249
- https://github.com/GSA/datagov-deploy/issues/1201

## How to reproduce

As a logged out user:
1. https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/restore-the-gulf-csw-harvest-source/job/last

## Expected behavior

I'm redirected to /user/saml2auth to start the login process. After login, I am returned to the original URL.

## Actual behavior

I'm redirected to /user/login and receive a 403.
https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/user/login?came_from=https%3A%2F%2Fadmin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov%2Fharvest%2Frestore-the-gulf-csw-harvest-source%2Fjob%2Flast

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by thejuliekramer** [comment]
@adborden this is the code that is causing this behavior https://github.com/keitaroinc/ckanext-saml2auth/blob/main/ckanext/saml2auth/views/saml2auth.py#L197 

We are using an upstream version of saml2auth - do we want to fork it instead and change this behavior?  Or suggest a change upstream?

**Comment by FuhuXia** [comment]
@thejuliekramer Anything different in the way we configure saml2auth in catalog and inventory? inventory is using upstream version but has no such issue.

**Comment by thejuliekramer** [comment]
@FuhuXia from looking at datagov deploy the configuration looks the same to me - are you testing the use case Aaron is saying? Where does it redirect to when you try to access a restricted page?

**Comment by FuhuXia** [comment]
@thejuliekramer 
I see. Inventory has no similar use case to test. Inventory redirects unauthorized user at apache level, not at ckan level. I think we are seeing a bug from upstream and should be raised at upstream. Another thing I noticed is that the redirect behavior is not consistent. `/harvest/restore-the-gulf-csw-harvest-source/job/last` redirects you to the login page, but `/organization/new` just gives 403 error message no redirect.

**Comment by adborden** [comment]
@FuhuXia I can reproduce this in inventory-next staging.

1. As a logged out user, browse to https://inventory-next-datagov.dev-ocsit.bsp.gsa.gov/organization/edit/aphis-usda-gov

![Screen Shot 2021-02-16 at 9 32 46 AM](https://user-images.githubusercontent.com/509703/108099978-28cefd00-703a-11eb-963b-7d01758fe89b.png)

You should be redirected to login.

**Comment by adborden** [comment]
@thejuliekramer I think this needs to be a fix upstream. One way to fix is to change that view function to redirect to the login controller, but I think the better fix is to replace the login controller with the saml2login controller when default login is disabled.

**Comment by adborden** [comment]
@FuhuXia ah, nevermind, I see what you mean. The behavior is slightly different in inventory, but it is still a bug.

**Comment by FuhuXia** [comment]
@adborden FYI, in vanilla CKAN 2.8 installation, unauthorized access to `/organization/edit/aphis-usda-gov` sees a 403 error message, not getting redirected.

**Comment by adborden** [comment]
@FuhuXia let's open a bug upstream for that. I think that should redirect to the login controller.

**Comment by thejuliekramer** [comment]
@adborden Is reporting the upstream bug in CKAN all that is needed or do we  want to request an upstream change to ckanext-saml2auth  as well?

**Comment by adborden** [comment]
@thejuliekramer There are two different issues, both are upstream. CKAN should redirect to login controller instead of 403 for some pages that don't already rediect.

ckanext-saml2auth needs to redirect to the saml controller when the default login is disabled and ckan is trying to redirect to the login controller.

**Comment by thejuliekramer** [comment]
If I change to [redirect](https://github.com/keitaroinc/ckanext-saml2auth/blob/main/ckanext/saml2auth/views/saml2auth.py#L212) to the saml2login() instead of a 403 do you think it seems like I am changing the behavior they purposefully added? They are checking if the default login is enabled and if it isn't they are always throwing this 403 error for `user/login`. Should I suggest they not throw this 403 error? Or maybe I can add an extra config for this? For example if I create a config named  `unauthorized_logged_out_redirect_to_saml2_login` and if true update the redirect to the saml2login() method.

**Comment by adborden** [comment]
It's really up to upstream. This came up in conversation earlier since the
concept of disabling default login was our use case, but the use case is
not to _disable_ default login but _replace_ it. If we could override the
user.login controller with the saml one, we wouldn't have a bug here.

**Comment by thejuliekramer** [comment]
Ok I will open up an issue  to address this and see what they say

**Comment by thejuliekramer** [comment]
@adborden https://github.com/keitaroinc/ckanext-saml2auth/issues/33 does  this sound like what you are thinking?

**Comment by adborden** [comment]
Sounds fine.
