### ISSUE TITLE
Remove docker from Jenkins

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2708]
## User Story

In order to minimize compliance burden and having to implement additional container security controls, data.gov wants to remove docker from Jenkins.

## Acceptance Criteria

- [ ] GIVEN a build is triggered on Jenkins \
  WHEN I inspect the build log
  THEN I see Jenkins artifacts used
  AND I don't see any usage of docker

## Background
Originally docker was used in sandbox as a simple method to package datagov-deploy as an artifact and reuse it across builds. The usage of docker was never implemented with much hardening and doesn't isolate builds from the host sufficiently.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
Removing docker from Jenkins keeps our implementation consistent with the security controls documented in our SSP.

## Sketch
- Use [archiveArtifact](https://www.jenkins.io/doc/pipeline/steps/core/#archiveartifacts-archive-the-artifacts) to store the latest successful build, including playbooks, python virtualenv and Ansible vendored roles.
- Use [copyArtifact](https://www.jenkins.io/doc/pipeline/steps/copyartifact/#copyartifacts-copy-artifacts-from-another-project) to copy the datagov-deploy artifact for use in application deploys.

**Comment by adborden** [comment]
Parking this work on the [feature/jenkins-artifact branch](https://github.com/GSA/datagov-deploy/tree/feature/jenkins-artifact). There's also a branch on [catalog-app](https://github.com/GSA/catalog-app/tree/adborden/ci-test) to consume the artifact.

This is a bit tangled with [feature/jenkins-branch](https://github.com/GSA/datagov-deploy/tree/feature/jenkins-branch) and needs some heavy cleanup.

**Comment by jbrown-xentity** [comment]
@adborden could use a pair on resolving this blocker (permissions issues with unarchiving)

**Comment by adborden** [comment]
Wanted to leave an implementation note here...

Jenkins' `zip` and `unzip` were giving me problems. It seemed like the executable bit was getting lost, so bin/jenkins-deploy was not executable (Permission denied). If you download the zip manually, the permissions look correct 🤷 

So I opted to tar and untar via `sh` instead of using the built-ins.
