### ISSUE TITLE
[Task] review SSP for Jenkins details

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2709]
## User Story

In order to ensure our compliance documentation matches our implementation, data.gov team wants another pass over Jenkins documentation in the SSP.

## Acceptance Criteria
- [ ] WHEN I review the SSP
  AND search for "jenkins"
  THEN I see jenkins mentioned in the ports table
  AND control documentation related to deploying

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
SSP should be updated to reflect reality of the implementation.

**Comment by nickumia-reisys** [comment]
No more Jenkins.  New SSPP.
- https://github.com/GSA/data.gov/issues/3710
- https://github.com/GSA/data.gov/issues/3911
