### ISSUE TITLE
Regex DOS in several repos

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2713]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.8fxx1fe71o3h)._

**Date of report:** 02/02/2021
**Severity:** High
**Due date:**  03/02/2021

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

[Link to Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.8fxx1fe71o3h)

**Comment by adborden** [comment]
https://snyk.io/vuln/SNYK-PYTHON-PYGMENTS-1086606 lists this as a High severity issue. This is overdue. I've updated the due date.
