### ISSUE TITLE
Catalog database contention in read replicas

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2716]
Under load, seeing these errors:

> (psycopg2.extensions.TransactionRollbackError) canceling statement due to conflict with recoveryDETAIL:  User query might have needed to see row versions that must be removed. [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT distinct(harvest_object_error.harvest_object_id) AS distinct_1 \nFROM harvest_object_error JOIN harvest_object ON harvest_object.id = harvest_object_error.harvest_object_id \nWHERE harvest_object.harvest_job_id = %(harvest_job_id_1)s) AS anon_1'] [parameters: {'harvest_job_id_1': u'fdcf871a-11ff-4990-a992-f573c85ece14'}]

> (psycopg2.extensions.TransactionRollbackError) canceling statement due to conflict with recoveryDETAIL:  User query might have needed to see row versions that must be removed. [SQL: 'SELECT harvest_object.id AS harvest_object_id, harvest_object.guid AS harvest_object_guid, harvest_object.current AS harvest_object_current, harvest_object.gathered AS harvest_object_gathered, harvest_object.fetch_started AS harvest_object_fetch_started, harvest_object.content AS harvest_object_content, harvest_object.fetch_finished AS harvest_object_fetch_finished, harvest_object.import_started AS harvest_object_import_started, harvest_object.import_finished AS harvest_object_import_finished, harvest_object.state AS harvest_object_state, harvest_object.metadata_modified_date AS harvest_object_metadata_modified_date, harvest_object.retry_times AS harvest_object_retry_times, harvest_object.harvest_job_id AS harvest_object_harvest_job_id, harvest_object.harvest_source_id AS harvest_object_harvest_source_id, harvest_object.package_id AS harvest_object_package_id, harvest_object.report_status AS harvest_object_report_status \nFROM harvest_object \nWHERE harvest_object.package_id = %(package_id_1)s AND harvest_object.current = true \n LIMIT %(param_1)s'] [parameters: {'package_id_1': u'3343792e-56e7-4c45-84ec-51a0b2842583', 'param_1': 1}]

> (psycopg2.extensions.TransactionRollbackError) canceling statement due to conflict with recoveryDETAIL:  User query might have needed to see row versions that must be removed. [SQL: 'SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id \nFROM system_info \nWHERE system_info.key = %(key_1)s \n LIMIT %(param_1)s'] [parameters: {'key_1': 'ckan.config_update', 'param_1': 1}]

... etc.

This appears to be replication contention while the main db is under (heavy?) write load. Disabling the harvesters resolves the error.

## How to reproduce

1. Queue up some heavy harvest sources.
2. Apply load to catalog

## Expected behavior

No errors in the logs

## Actual behavior

> (psycopg2.extensions.TransactionRollbackError) canceling statement due to conflict with recoveryDETAIL:  User query might have needed to see row versions that must be removed.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
Not a problem in the cloud.gov environment due to lack of read-replicas there.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
