### ISSUE TITLE
HSTS not enabled

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2727]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.m1867uj8kgkj)._

[Netsparker report](https://drive.google.com/file/d/1zqKVd7OC3YOcUiQLLxkB3xSDZRcz1P7D/view?usp=sharing)

**Date of report:** 2021-02-02
**Severity:** Moderate
**Due date:** 2021-05-02

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by FuhuXia** [comment]
Done.
HSTS header was added to host traffic, no duplicate header in site traffic.

![Screen Shot 2021-04-22 at 9 23 04 AM](https://user-images.githubusercontent.com/1392461/115727058-43cb2f80-a351-11eb-9ecf-95a2ec01c6fe.png)
