### ISSUE TITLE
Out-of-date jQuery

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2728]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.15ilwsndbxm8)._

[Netsparker report](https://drive.google.com/file/d/1zqKVd7OC3YOcUiQLLxkB3xSDZRcz1P7D/view?usp=sharing)

**Date of report:** 2021-02-02
**Severity:** Moderate
**Due date:** 2021-05-02

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by mogul** [comment]
We also got a report for our Federalist sites. When this is resolved, please mail support+id173@federalist-support.zendesk.com to let them know we've handled it.

**Comment by jbrown-xentity** [comment]
For Jenkins, this has already been done: https://ci.sandbox.datagov.us/static/7edba4b3/jsbundles/vendors.js (see jquery version 3.5.1)

**Comment by jbrown-xentity** [comment]
All sites updated, info for federalist in email.
