### ISSUE TITLE
Automated deployment from git push

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2733]
## User Story

In order to get quick feedback from code and configuration changes, data.gov wants deploys triggered from CircleCI after a successful build.

## Acceptance Criteria

- [ ] GIVEN I merge a change to the `master`  branches
  WHEN the automated tests succeed
  THEN a deploy build is started in Jenkins.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This story changes our boundary because Jenkins must be listening on port 80/443 in order to receive the successful notification from CircleCI. Ensure SSP is up to date.

## Sketch
Update circleci.yml in all repositories to trigger the correct Jenkins job.

**Comment by adborden** [comment]
In the meantime, I've [updated the FCS jobs to use polling](https://github.com/GSA/datagov-deploy/pull/2871), so when you push, there is a short delay, but the build will be triggered.

**Comment by nickumia-reisys** [comment]
No more FCS.  No more CircleCi.
- https://github.com/GSA/data.gov/issues/3710

No link for getting off of CircleCI 😞 But it just happened through random development.

**Comment by nickumia-reisys** [comment]
As mentioned in the issue below, we have automated deployments on push to `main` for `prod` and `develop` for `development`
- https://github.com/GSA/data.gov/issues/2705#issuecomment-1416562771
