### ISSUE TITLE
Running supervisor processes are not restarted after deploy

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2742]
## How to reproduce

1. Description of steps to reproduce the issue.

## Sketch
Add a task to the catalog Ansible role to explicitly restart the catalog web service and the workers in supervisord

**Comment by nickumia-reisys** [comment]
No more Ansible.  No more supervisor.
- https://github.com/GSA/data.gov/issues/3710

Our current cloud.gov deployments automatically restart the apps.  It's just how cloud.gov works.
