### ISSUE TITLE
Announce the decommission of CSW service on data.gov blog

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2743]
## User Story

As Data.gov PMO, we want to announce through blog post that we are discontinuing CSW service on data.gov in order to inform any relevant users.

## Acceptance Criteria

- [x] GIVEN Data.gov PMO is planning on discontinuing the CSW service\
 THEN there is an announcement on data.gov blog with information on the discontinuation and effective date.

## Background
https://github.com/GSA/datagov-deploy/issues/2383

## Sketch
- [x] Pick a date, write a short post
- [x] Review with team
- [x] Get approval through TTS process
- [x] Post on data.gov

**Comment by hkdctol** [comment]
Announcement went through TTS review and has been posted on Data.gov.
