### ISSUE TITLE
Freeze BSP branches

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2745]
## User Story

In order to reduce the risk of making changes to mainline on our way to cloud.gov, the team wants datagov-deploy ansible playbooks to refer to the branches frozen for FCS.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I have made a commit to application branch `fcs` \
  WHEN I a perform an ansible-deploy from the `master` branch \
  THEN I can see the expected change in production

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
All vulnerabilities will be addressed on the mainline (intended for cloud.gov) according to our usual process during our O+M rotation. Updates will only be carried over to the `fcs` branches on a best-effort basis except when high or critical vulnerabilities are approaching their due date; remediations for those are definitely carried over.

## Sketch
- [x] Changes to datagov-deploy should be based on master as a hotfix
- [x] git branch fcs; git push fcs
- [x] update the branch references in datagov-deploy Ansible inventory variables
- [x] Review the release documentation, contributing.md, and datagov-deploy README.md to ensure this change is accounted for.
- [x] Update [git_ref](https://github.com/GSA/datagov-deploy/blob/cb96060abffe2b115b6babb4208c74266940e308/ansible/inventories/sandbox/group_vars/all/vars.yml#L136-L153) in Jenkins jobs
- [x] Update CircleCi deploy branch filter in each application repo
- [x] Update Jenkinsfile branch filter in each application repo
#### Branch 'fcs' created
- [x] Catalog-classic (maybe not needed)
- [x] Catalog-next
- [x] Inventory-classic
- [x] Inventory-next (should wait until released)
- [x] Dashboard
- [x] Wordpress
- [x] catalog-fgdc2iso
- [x] CSW

#### Edited on datagov-deploy-*
- [x] Catalog-classic (maybe not needed)
- [x] Catalog-next
- [x] Inventory-classic
- [x] Inventory-next (should wait until released)
- [x] Dashboard
- [x] Wordpress
- [x] catalog-fgdc2iso
- [x] CSW

**Comment by adborden** [comment]
FYI, I added protected branch settings for these repos.
