### ISSUE TITLE
Prepare inventory user table for login.gov and ckanext-saml2auth

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2758]
In order to [authenticate existing inventory user with login.gov](https://github.com/GSA/datagov-deploy/issues/2533), we need to do some house clean work on the inventory user table.

- [x] Each valid email address should only appear once.
- [x] Each valid email address should be lower case. 

## Sketch
- Use CKAN CLI or API to modify users, so the revision history and audit log is maintained, and we reduce the risk of mishaps. 
  - If not possible, fall back to DB queries
- When multiple user entries found using same email address, keep the email address to the user entry that makes most sense, such as the only active one, or last created one. 
- Append `.localdomain` to the email address to  be de-duplicated.

**Comment by jbrown-xentity** [comment]
To be done on inventory classic, and work will be ported over to inventory-next in the DB migration.

**Comment by FuhuXia** [comment]
Not able to find any CLI/API way to update info for a deleted user. Plan to use DB query for the update.

**Comment by FuhuXia** [comment]
Two DB queries have been run on prod inventory.
```
-- convert all emails to lower case
UPDATE "user" SET email = LOWER(email);

-- append '.localdomain' to duplicated emails, leaving the most-recent/active email intact
WITH ec AS (SELECT email, count(*) FROM "user" GROUP BY email HAVING count(*) > 1)
UPDATE "user" SET email = CONCAT(email, '.localdomain') WHERE email IN (SELECT email FROM ec)
AND id NOT IN (...[list of hand-picked ids]...)
```

**Comment by mogul** [comment]
We need to schedule downtime before we roll this out into production.

**Comment by FuhuXia** [comment]
This finding comes late, but we can use [ckanapi](https://github.com/ckan/ckanapi) to update the user info, including deleted user. 
```
/usr/lib/ckan/bin/pip install ckanapi
/usr/lib/ckan/bin/ckanapi -c /etc/ckan/production.ini action user_update id=someusername email=some@email.address.localdomain
```
