### ISSUE TITLE
application autologout after 15 min of inactivity

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#276]
Currently it is more than 15 min, need to configure and verify all aspects to logout in 15 min.

- [x] Data.gov WP 
- [x] Labs Dashboard
- [x] Labs CRM
- [ ] CKAN catalog
- [x] CKAN inventory

**Comment by kvuppala** [comment]
@John123Yu @FuhuXia 
Admin Catalog logout seem to work as well, however the URL is not redirecting to public website which is the case when you manually logout.

**Comment by FuhuXia** [comment]
We experienced similar issue before. We use presence of ckan cookie `auth_tkt` as indicator whether a browser is authenticated or not on the Apache level. However, CKAN has a weird behavior that it creates the cookie on user authentication, but does not remove the cookie from a browser once a non-authenticated session is detected. We need to add this function into CKAN core.
