### ISSUE TITLE
Replace csb-aws-postgresql with cloud.gov's aws-rds

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2760]
## User Story

In order to use a secure and low-latency postgresql service on cloud.gov, data.gov team wants to replace the csb-aws-postgresql broke with cloud.gov's aws-rds broker..

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] WHEN I run `cf services` in the production space
  THEN I see aws-rds services
  AND I don't see csb-aws-postgresql services

## Background
https://github.com/GSA/datagov-deploy/issues/2603

For the initial CKAN 2.8 applications that require postgresql <= 11, we used the csb broker because the cloud.gov broker only supports creation of postgresql 12.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
SSP already states that we are using the cloud.gov broker for postgresql. This work brings us in-line with documentation. 

## Sketch
- [x] update README with the correct cf create-service commands
- [x] ensure publicly_accessible is **not** set
- [x] create the new aws-rds services and delete the existing csb-aws-postgresql services
- [x] production should use a non-shared service plan

**Comment by adborden** [comment]
@mogul this is blocked by the cloud.gov work. Is there a GH issue to link to?

**Comment by mogul** [comment]
PR: https://github.com/cloud-gov/aws-broker/pull/143

**Comment by mogul** [comment]
Issue: https://github.com/cloud-gov/aws-broker/issues/142

**Comment by adborden** [comment]
I confirmed with Inventory that we can create a Postgres 11 db and the app successfully starts up.

    $ cf create-service aws-rds small-psql ${app_name}-db -c '{"version": 11}'

**Comment by adborden** [comment]
To update the services, I did this for each space for catalog and inventory.

```
cf rename-service $app_name ${app_name}-csb-db
cf create-service aws-rds small-psql ${app_name}-db -c '{"version": 11}'
# wait until services created...
# trigger a deploy..
```

**Comment by jbrown-xentity** [comment]
@adborden in review, both staging and production for both catalog and inventory need to be re-deployed to pick up the new db binding. Will watch documentation PR's to make sure deployment works, then we can mark this as done...

**Comment by jbrown-xentity** [comment]
All csb services deleted, services confirmed still up. Marking as done!
