### ISSUE TITLE
Fix linting false positive in ckanext-datagov_inventory

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2772]
The linting check in inventory-app is not checking out the code, so no errors are detected.

https://app.circleci.com/pipelines/github/GSA/inventory-app/749/workflows/9430baa6-6e07-41cd-9893-c15ccd0acd3f/jobs/984

With code checked out:
https://github.com/GSA/inventory-app/runs/1860285840?check_suite_focus=true

## How to reproduce

1. Description of steps to reproduce the issue.

## Expected behavior

Lint check is working in CI.

## Actual behavior

Lint check results in a false positive.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by adborden** [comment]
@jbrown-xentity I think you fixed this on inventory_ckan_2.8 and main branches, right?

**Comment by jbrown-xentity** [comment]
This is fixed on main only, see [commit](https://github.com/GSA/inventory-app/pull/227/commits/d4d889fa2654fc2ebabe29ad0805bce33ccca346).
