### ISSUE TITLE
New ckan user to be created with email address as display name 

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2781]
After a new user logs into our catalog/inventory app, the display name is formatted as "`john.smith example.gov`". It looks like the `ckanext-saml2auth` extension grabs the email address `john.smith@example.org` and split it at the `@` char to generate the display name. The desired behavior is to using email address as display name. 

## How to reproduce

New user logs into our catalog/inventory app.

## Expected behavior

Name is displayed in the format `john.smith@example.gov`

## Actual behavior

Name is displayed in the format `john.smith example.gov`

## Sketch
This behavior might be configurable. So try that first.

All existing users are not affected. Users created by `max.gov/ckanext-saml2` are using email addresses as display name. We want to keep the behavior consistent.

**Comment by mogul** [comment]
Icebox'ing due to the slow growth in new users and solely-cosmetic nature of the problem.
