### ISSUE TITLE
Configure New Relic alerts for cloud.gov applications

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2782]
## User Story

In order to be alerted when the applications are not performing as expected, data.gov team wants each application to be configured with New Relic APM and alerts setup for important metrics.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN an application is served at https://catalog-stage-datagov.app.cloud.gov
  WHEN the application becomes unavailable
  AND https://catalog-stage-datagov.app.cloud.gov is no longer available
  THEN I see an alert in #datagov-alerts
- [x] WHEN the application metric goes outside of a threshold
  THEN I see an alert in #datagov-alerts

## Background

We are already using NR APM. Some applications are not configured with NR but need to be. Alerts and monitored metrics should be consistent across applications.

The PHP New Relic agent works differently than the Python one. The [PHP buildpack](https://docs.cloudfoundry.org/buildpacks/php/gsg-php-newrelic.html) looks for the NEWRELIC_LICENSE env variable and will configure it for you.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
Application monitoring and alerting in New Relic is explicitly stated in the SSP for several controls. Implementation must be consistent with the documented controls.

## Sketch
- [x] Synthetics alerts for URLs
- [x] APM alerts for Apdex, Errors, Response time
- [x] Alerts for production go to #datagov-alerts

All applications are implemented:
- [x] inventory
- [x] catalog
- [x] dashboard

**Comment by chris-macdermaid** [comment]
Synthetic Monitors:
[catalog-prod](https://one.nr/01qwL9A9OR5)
[catalog-stage](https://one.nr/0LkjnKyM1Qo)
[inventory-prod](https://one.nr/0eqwy1agdwn)
[inventory-stage](https://one.nr/0JBQrz2mDQZ)

Dashboard's data hasn't been loaded so data returned isn't be monitored, just the URL
[dashboard-prod](https://one.nr/0DvwBJNAPwp)
[dashboard-stage](https://one.nr/0dBj3vm8xRX)

**Comment by chris-macdermaid** [comment]
These newrelic PHP extension defaults can be overridden:
'NEWRELIC_HOST'
'NEWRELIC_PACKAGE'
'NEWRELIC_DOWNLOAD_URL'
 'NEWRELIC_STRIP':
  https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/newrelic/extension.py#L27-L33

**Comment by chris-macdermaid** [comment]
Monitoring policies created:
[Cloud.gov(Alarm)](https://one.nr/0WBQ1yvzAQx) and [Cloud.gov(Warn)](https://one.nr/0nVjYbxLqQ0) - Synthetic monitors for prod and staging.

[Cloud application performance (production)](https://one.nr/0dBj3pbY2QX) and [Cloud application performance (staging)](https://one.nr/0Y8wpNlZ9jO) - Application monitors for prod and staging.

For dashboard's PHP, this uses the newrelic extension that is part of the PHP buildpack. Added github secret for license and added updated manifest in this [PR](https://github.com/GSA/project-open-data-dashboard/pull/327).

Catalog was updated in these [PR1](https://github.com/GSA/catalog.data.gov/pull/261/files) and [PR2](https://github.com/GSA/catalog.data.gov/pull/263)

This is now emailing and sending the alerts to slack.
![Screenshot from 2021-03-26 09-00-40](https://user-images.githubusercontent.com/64213093/112651227-cffd3c00-8e11-11eb-8126-b04e5db3736d.png)


![Screenshot from 2021-03-26 08-58-18](https://user-images.githubusercontent.com/64213093/112650954-8876b000-8e11-11eb-971e-443aed433b20.png)
