### ISSUE TITLE
Deploy datapusher application on cloud.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2787]
## User Story

In order to reduce the operation and maintenance burden of inventory.data.gov and datapusher, the data.gov team wants the datagov application deployed on cloud.gov.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] WHEN I commit a change to the `main` branch in the `GSA/datagov-datapusher` repository \
  AND I browse to GH actions
  THEN I see a deployment pipeline kick off \
  AND the pipeline completes successfully \
  AND the change is visible at https://inventory-prod-datagov.app.cloud.gov
- [ ] If any manual preparation of the target space was necessary, then an issue exists about automating that setup in future.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
We are deploying from the `main` branch to the `gsa-datagov/production` space only. Other branches and spaces are considered out of scope here. Note cronjobs are also out of scope for now.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
None. This work is being done in an environment completely separate from the existing deployment, and only open source and open data are involved.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- [x] Create a new GH repository [GSA/datagov-datapusher](https://github.com/GSA/datagov-datapusher)
- [ ] Create any necessary services in the target space with `cf create-service`
- [ ] Create a manifest.yml capturing any settings or bindings
- [ ] Practice a hand-driven deployment
- [ ] Ensure environment settings are configured based on `$VCAP_SERVICES`
- [ ] Make sure the health check is correct and passing
- [ ] Update Inventory and supply the datapusher URL though the environment
- [ ] The README.md should have instructions for hand-deployment
- [ ] Add CircleCI or GitHub Action config for deployment to the `production` space

**Comment by adborden** [comment]
@mogul since datapusher is an internal application, what should it's sketch look like?

I think that datapusher will be a new repo with it's own requirements.txt and configuration. Does it need to be deployed with inventory or can it be deployed independently?

**Comment by mogul** [comment]
Definitely deploy independently, and it sounds like it can live on the `app.internal` domain as well.

**Comment by pjsharpe07** [comment]
From thoughts on fgdc2iso, a way to perform a smoke test with an internal route is:

> Probably will use cf ssh and port forwarding to curl against that instance.

**Comment by jbrown-xentity** [comment]
Will consider #1486 to simplify the number of applications and services running before taking on this work.

**Comment by mogul** [comment]
Iceboxing this in favor of #1486.

**Comment by mogul** [comment]
Likely closeable now, we just want to see xloader working on cloud.gov.
