### ISSUE TITLE
Avoid logging sensitive service credentials

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2789]
Catalog and Inventory are using a cfstart.sh script that uses ckan config-tool to update the config. ckan config-tool ends up logging to stdout, so sensitive information is leaked into the logs.

## How to reproduce

1. cf restart $app_name
2. cf logs $app_name | grep SQLALCHEMY

## Expected behavior

No sensitive information appears from the application startup.

## Actual behavior

Database credentials are logged to stdout.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
Did not capture any sensitive info output by ckan `config-tool` command in `inventory` or `catalog` app.

Inventory `config-tool` output looks clean:
![Screen Shot 2021-03-18 at 12 01 14 PM](https://user-images.githubusercontent.com/1392461/111657322-b2145380-87e1-11eb-9304-8e9aeb28a131.png)

Catalog `config-tool` output looks clean:
![Screen Shot 2021-03-18 at 11 54 21 AM](https://user-images.githubusercontent.com/1392461/111657112-84c7a580-87e1-11eb-89d6-a99fa8093047.png)

However, command [datastore-usersetup.py](https://github.com/GSA/inventory-app/blob/main/cfstart.sh#L79) is printing datastore user's password to screen. Will fix it.
![Screen Shot 2021-03-18 at 11 56 08 AM](https://user-images.githubusercontent.com/1392461/111657891-3ebf1180-87e2-11eb-9624-7c1ec9c4b8a2.png)
