### ISSUE TITLE
Publish catalog docker image using GitHub Actions

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2791]
Need to replace the [circle-ci jobs for publishing docker images](https://github.com/GSA/catalog.data.gov/blob/main/.circleci/config.yml) with the new [github actions](https://github.com/GSA/catalog.data.gov/pull/240).

The docker images are being saved, but the docker hub credentials will need to be added as github secrets.
## How to reproduce

1. Merge a PR into master

## Expected behavior

GitHub Actions handles all automated deployment/publishing

## Actual behavior

CircleCi handles docker hub publishing

## Sketch
- [x] Ensure `fcs` continue to use CircleCI and hub.docker.com for their published images
- [x] Migrate publish workflows to GitHub Actions (https://github.com/GSA/catalog.data.gov/pull/270)
- [x] [Publish containers to GitHub Container Registry](https://github.com/orgs/GSA/packages) (ghcr.io)
- [x] Consider moving images to https://github.com/GSA/datagov-docker as building blocks for other repos to consume

**Comment by adborden** [comment]
FYI, we also want to make sure to tag the docker image correctly. FCS is currently pushing images with the `latest` tag.

**Comment by jbrown-xentity** [comment]
Blocked until DockerHub credentials are on GitHub...

**Comment by mogul** [comment]
Prior art: 
- https://github.com/GSA/cloud-service-broker/blob/master/.github/workflows/publish_image.yaml
- https://github.com/GSA/datagov-logstack/blob/main/.github/workflows/commit.yml

**Comment by jbrown-xentity** [comment]
I think this would clarify things in the future, but not sure if this PR is necessary: https://github.com/GSA/catalog.data.gov/pull/269
