### ISSUE TITLE
Inventory forbidden page links to wrong login link

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2796]
The new inventory Forbidden page is linking to /user/login when it should link to /user/saml2login

![Screen Shot 2021-02-11 at 5 16 50 PM](https://user-images.githubusercontent.com/509703/107719379-f36a8e00-6c8c-11eb-996a-9c30230512cf.png)

## How to reproduce

1. https://inventory-next.sandbox.datagov.us/dataset
2. Click "Log in" in the body

## Expected behavior

Links to /user/saml2login and to Login.gov
or
The link doesn't exist

## Actual behavior

Links to /user/login and I see another Forbidden page.

## Sketch
Replace the login controller with saml2login or conditionally replace which controller is linked.

**Comment by pjsharpe07** [comment]
If you're not logged in and you navigate to the [dataset page](https://inventory-prod-datagov.app.cloud.gov/dataset) you'll see that the login link is non-existent.
