### ISSUE TITLE
Improper Certificate Validation

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#2804]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 1/12/2021
**Severity:** Meduim
**Due date:** 4/12/2021

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
[Google Doc](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.j313cpbxinuy)

**Comment by jbrown-xentity** [comment]
Handled with https://github.com/GSA/resources.data.gov/pull/318
