### ISSUE TITLE
catalog harvester process runs in cloud.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2810]
## User Story

As a catalog admin, I want a harvester in cloud.gov so that data can be updated.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN a catalog web application is running in cloud.gov environment \
  WHEN a harvest request is made through the UI \
  THEN the gather and harvest processes pick up the job \
  AND the harvest runs to completion

## Background
Will need to turn on catalog application but use different start/run commands to implement the various components of the jobs. Will require running the `gather`, `fetch`, and `run` jobs. See [here for examples](https://github.com/GSA/catalog.data.gov/blob/main/Makefile#L95-L102). Should implement each of these as a separate application.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, all harvests are done of publicly available data.

## Sketch
[Should use the Procfile to specify different  start commands](https://www.cloudfoundry.org/blog/build-cf-push-learn-procfiles/)

**Comment by pjsharpe07** [comment]
[fgdc2iso app is up](https://github.com/GSA/datagov-deploy/issues/1299) in all three spaces but is currently stopped. Turn them off before attempting to harvest any geospatial harvests.

**Comment by adborden** [comment]
Instead of porting the existing harvest system to cloud.gov, we should look at picking up the harvest-ng work https://github.com/GSA/datagov-deploy/issues/2995

**Comment by jbrown-xentity** [comment]
Using [processes](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#processes) in manifest file instead of the `Procfile`, as the Procfile doesn't give the full options that the manifest file has...

**Comment by mogul** [comment]
Currently hitting quota limits... Need to revisit them after we move Solr from apps to brokered

**Comment by mogul** [comment]
@jbrown-xentity is this still blocked now that we raised our quota?

**Comment by jbrown-xentity** [comment]
Have not checked. There were 2 main blockers: quota, and solr changing to service in cloud.gov. The current solr service was not connecting to the dev app, and so creating and running a harvest would have been pointless. Turns out we needed to run [this step of add-network-policy](https://github.com/gsa/catalog.data.gov#deploying-to-cloudgov) to setup catalog and catalog-solr to connect. So this can be unblocked, and the following would need to be run to check if harvests are working:

1. Merge the draft branch onto develop
2. Run `cf run-task` to create a harvest source that is working on prod
3. Verify harvests worked

Normally the above could be done via the UI, but is blocked by #3508, although testing ckan one-off commands through cf run-task would be a good thing to validate...

**Comment by jbrown-xentity** [comment]
Never mind, it's blocked by #3508. While you can create a harvest source and users through the command line, we can't create [organizations with the cli](https://docs.ckan.org/en/2.9/maintaining/cli.html). Since a harvest source has to be in an org, this breaks the workflow of validating this.
Once the login is working, this becomes very straightforward to login, setup the user as a sysadmin as a one-off, and then do all other testing via the UI. The branch is pushed to development as a test, and all pieces are working as expected...

**Comment by jbrown-xentity** [comment]
The code is deployed, but to demonstrate our acceptance criteria we need to be able to log in. Leaving as blocked for now...

**Comment by jbrown-xentity** [comment]
The processes are running, and restart if they fail.
You can see that [staging](https://catalog-stage-datagov.app.cloud.gov/) harvested data.
You can see harvest sources [here](https://catalog-stage-datagov.app.cloud.gov/harvest/).
Created #3549 and #3550 as follow up items; not sure that either needs to be fixed before go-live.
