### ISSUE TITLE
Catalog sitemap pages are too large for Google

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2813]
![Screen Shot 2021-02-12 at 1 22 06 PM](https://user-images.githubusercontent.com/509703/107823852-56affb00-6d35-11eb-894f-89d3369cface.png)

sitemap-1.xml was 8.4M and 200,000 lines, 50,000 URLs. Maybe we need to make them a bit smaller.

## How to reproduce

1. Description of steps to reproduce the issue.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
The title is misleading, but we did make it smaller and Google still had an issue, so there has to be another reason for Google not being able to fetch sitemaps
- https://github.com/GSA/data.gov/issues/4061

Also, this is good historical reference for,
- https://github.com/GSA/data.gov/issues/3426
- https://github.com/GSA/data.gov/issues/3490
