### ISSUE TITLE
Configure monitoring and alerting for cloud.gov app logs and metrics

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2814]
## User Story

In order to meet the monitoring and alerting needs for data.gov applications running in cloud.gov, the data.gov team wants to monitor logs and telemetry from cloud.gov apps and alert when suspicious conditions arise.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] WHEN an application in a space in the `gsa-datagov` organization on cloud.gov logs a "test" error \
  THEN the data.gov team is alerted that the test was logged.
- [ ] [something about the specific kings of monitoring and alerting we want to do goes here; should it be a separate issue to configure specific alerts for each app??]

## Background

- [This Terraform provider explicitly supports OpenDistro features in AWS ES](https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Relates to section SI-4(5) of our SSP](https://docs.google.com/document/d/1WuoO419OV-SHiQU5k_IWZYsWbjPE_VXmj-jNMH0KDDI/edit#heading=h.28ongge8nlp3). 

## Sketch

The Loki+Grafana path:
- [ ] Drain logs to Loki via syslog -> Fluent Bit (or promtail)
- [ ] Configure Grafana to alert to Slack

The AWS ES path:
- [ ] Practice [configuring monitoring and alerting directly in the Kibana UI](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/alerting.html); this is probably enough to meet the immediate needs of the story.
- [ ] Bonus points: 
  - [ ] Use the ES API to [siphon out our configured monitors and alerts](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/api/).
  - [ ] Use the [ODfE Terraform provider](https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs) to configure our monitoring and alerts via CI. (This is to make Contingency Planning and auditing easier.)

**Comment by adborden** [comment]
We're considering this as an improvement to monitoring/alerting and have other controls in place to meet compliance requirements.

**Comment by mogul** [comment]
Closing as a dupe of #3062
