### ISSUE TITLE
Add netlify admin to static sites

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2823]
## User Story

As a [user description], I want [behavior description] so that [goal].

[...or [alternatively](https://blog.crisp.se/2014/09/25/david-evans/as-a-i-want-so-that-considered-harmful)...]

In order to [goal], [stakeholder] wants [change].

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
We already have this setup for resources.data.gov, we should add it to other static sites (sdg, strategy, federation).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
- [ ] https://federalist.18f.gov/documentation/getting-started-with-netlify-cms/
- [ ] Get partners added to Federalist
- [ ] Communicate with partners about the change

**Comment by FuhuXia** [comment]
It seems everyone need to be a Federalist user.
> Because Federalist facilitates the authentication with Github, we require users of Netlify CMS to be Federalist users in addition to having write permissions to the Github repository.

Error when try to login:
> Apologies; you are not authorized to access Federalist! Please contact the Federalist team if this is in error.

>If your office uses Federalist, ask your team’s primary contact to send an email to federalist-support@gsa.gov with the GitHub usernames that need access.

**Comment by adborden** [comment]
@FuhuXia can you try this URL? https://resources.data.gov/admin/#/

**Comment by adborden** [comment]
Ah, yes, I see the configuration [here](https://github.com/GSA/resources.data.gov/blob/b28a9f39c06d41e7be9a974dc0029be13ce4600a/pages/admin/config.yml#L1). I'll add a note about adding partners to Federalist.

**Comment by hkdctol** [comment]
Unless there's a change in direction I don't think this is needed; closing for now.
