### ISSUE TITLE
Disable Server header in gunicorn

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2826]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 2020-02-16
**Severity:** Low
**Due date:** 2020-05-16

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

Remove the Server header from CKAN/gunicorn.

**Comment by FuhuXia** [comment]
Verified inventory and catalog are returning empty server header in the response.
```
🍏 09:34:14 [~]
$ curl -I -s https://inventory.data.gov/dataset | grep -i server
Server:
```
```
🍏 09:34:26 [~]
$ curl -I -s https://catalog.data.gov/dataset | grep -i server
server:
$
```
