### ISSUE TITLE
Partial decommission of catalog-classic

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2837]
## User Story

In order to reduce the number of hosts we have to patch and maintain, data.gov team wants some of the catalog-classic FCS resources decommissioned.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I browse to catalog-datagov.dev-ocsit.bsp.gsa.gov \
  THEN I get an unresolved domain error.

## Background
https://github.com/GSA/datagov-ckan-multi/issues/400

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
**Note: We are leaving catalog-admin temporarily to allow access to the catalog-classic database.**
- [x] Open FCS ticket to terminate hosts (RITM0816722)
  - catalog-web1d
  - catalog-web2d
  - catalog-web1p
  - catalog-web2p
  - catalogb-web1p
  - catalogb-web2p
  - catalog-harvester1d
  - catalog-harvester2d
  - catalog-harvester1p
  - catalog-harvester2p
  - catalog-harvester3p
  - catalog-harvester4p
  - catalog-harvester5p
  - catalog-harvester6p
- [x] Remove above hosts from staging and production hosts file
- [x] Remove above hosts from [System Inventory](https://docs.google.com/spreadsheets/d/1ZYahWuDasufr8VXCHJSlrXHB6-UYk7g2agU87MMKnCk/edit#gid=1724757408) and notify ISSO
- [x] Remove catalog-datagov.dev-ocsit.bsp.gsa.gov Netscaler and DNS record (REQ0588674)
- [x] Remove RDS **replicas only** (RITM0821529)
  - datagovcatalog-readreplica1.cwyyxljkfrkk.us-east-1.rds.amazonaws.com
  - datagovcatalog95-replica2.cy0fc5s0csfm.us-east-1.rds.amazonaws.com
  - datagovcatalog95-replica1.cy0fc5s0csfm.us-east-1.rds.amazonaws.com

**Comment by adborden** [comment]
Opened RITM0816722 to decommission the catalog instances.

**Comment by adborden** [comment]
Moving to blocked until the FCS ticket is resolved.

**Comment by adborden** [comment]
RITM0816722 is complete and the hosts have been terminated.

**Comment by adborden** [comment]
Opened RITM0821529 to remove db replicas.

**Comment by mogul** [comment]
Aaron's pinging the one remaining upstream request (REQ0588674) which has been stuck.

**Comment by jbrown-xentity** [comment]
Aaron pinging again as it's been a week and no response.

**Comment by adborden** [comment]
Ticket was resolved on Friday, but the DNS still resolves.

**Comment by adborden** [comment]
Fixed.
