### ISSUE TITLE
Decommission remaining catalog-classic resources

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2838]
## User Story

In order to reduce the number of hosts we have to patch and maintain, data.gov team wants the rest of the catalog-classic FCS resources decommissioned.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I browse to https://admin-catalog-next.data.gov/api/action/status_show \
  THEN the site is on CKAN2.8 or higher \
  AND the staging site is equivalently moved

## Background
Partial decommission (https://github.com/GSA/datagov-deploy/issues/2837)
catalog-next launch (https://github.com/GSA/datagov-ckan-multi/issues/400)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This will clean up code that is no longer well supported.

## Sketch
- [x] Get sign-off from PMO (we're keeping resources around temporarily)
- [X] Open FCS ticket to terminate hosts (REQ0594356)
  - catalogpub-web1d
  - catalogpub-web1p
- [x] Remove above hosts from staging and production hosts file
- [x] Remove above hosts from [System Inventory](https://docs.google.com/spreadsheets/d/1ZYahWuDasufr8VXCHJSlrXHB6-UYk7g2agU87MMKnCk/edit#gid=1724757408) and notify ISSO
- [ ] ~~Remove or rename admin-catalog.data.gov~~
- [ ] ~~Open FCS ticket to remove RDS instance~~ (to be done later, own ticket [here](https://github.com/GSA/datagov-deploy/issues/2990))

**Comment by jbrown-xentity** [comment]
Scheduled for 2021-03-19

**Comment by jbrown-xentity** [comment]
Opened ticket on 3/22, will ping on 3/26 on G-Chat if no movement by then (per FCS suggestion).

**Comment by adborden** [comment]
With inventory removed, we can remove the old solr primary instances as well. I put in a ticket RITM0834738 to remove:
- datagov-solrm1p.prod-ocsit.bsp.gsa.gov
- datagov-solrm1d.dev-ocsit.bsp.gsa.gov
