### ISSUE TITLE
Catalog not harvest complete datasets from data.json source, possibly skipping children datasets

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2840]
There are 265 datasets in [GSA json](https://open.gsa.gov/data.json) harvest source. Catalog harvest job stops (hangs) at 106 datasets, leaving 159 not harvested.

## How to reproduce

Count the datasets at /harvest/admin/gsa-json.

## Expected behavior

265 datasets

## Actual behavior

106 datasets

## Background
Out of 265 datasets, 106 are standalone/parent datasets. 159 are children datasets. Looking at the number it is obvious that only standalone/parent datasets are harvested. The 2nd job for children datasets is not initialized.

Confirmed on production.

**Comment by jbrown-xentity** [comment]
This is a false positive. The collection datasets are getting harvested ([see example here](https://admin-catalog-next.data.gov/dataset/networx-business-parent)).
The way the UI reports it is very confusing, but only the collection level datasets are reported in the harvest report; all datasets inside a collection are not reported.
You can confirm by searching the organization for datasets with a `collection_package_id`:
https://catalog.data.gov/api/action/package_search?fq=collection_package_id:*%20AND%20organization:gsa-gov&rows=1000
This reports the missing 159.

**Comment by adborden** [comment]
Please add docs about collection_package_id to https://github.com/GSA/datagov-deploy/wiki/Collections

I think collection_package_id only applies to datajson harvest sources, right?

**Comment by jbrown-xentity** [comment]
Applied updates to docs: https://github.com/GSA/datagov-deploy/wiki/Collections#collection-package-id
