### ISSUE TITLE
FGDC2ISO license not in random directory

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2841]
We would like to implement FGDC2ISO service with a license file in a random location created at run time. We had this [fleshed out here](https://github.com/GSA/catalog-fgdc2iso/pull/4/files#diff-bc6ad6fc9708246c27d94e16f911c92e7cd03f60df8087ab2e3f2d5a323362aeR1-R19), but the environment variable export did not persist into the python code in `app.py`, where we needed the license file location. Documentation is sparse on the java buildpack `.profile` usage and capabilities, but is supposed to be a pre-hook before java application starts up. Exporting the file to a standard location works, see profile script and TODOs.

## How to reproduce

1. Uncomment out code in `.profile`, rebuild and re-deploy

## Expected behavior

saxon license file is stored in a secure temporary location at run time, and file path is passed to the application

## Actual behavior

file path is not passed to the application, file cannot be found and the application fails to respond to requests

**Comment by adborden** [comment]
@jbrown-xentity alternatively, we could make a code change to read that file in from environment variable (and fall back to file if we want).

I've seen a pattern where two env variables are optional. One indicates it is the content, the other indicates it's a filename.

- `SAXON_LICENSE`: The license content itself, stored as an environment variable.
- `SAXON_LICENSE_FILE`: The value is a filepath, read it and treat the content as `SAXON_LICENSE`.

**Comment by jbrown-xentity** [comment]
Overcome by https://github.com/GSA/datagov-deploy/issues/2917, closing.
