### ISSUE TITLE
Cryptographic Issues in ipaddress

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2844]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.b6igeflbdewp)._

https://snyk.io/vuln/SNYK-PYTHON-IPADDRESS-590065

**Date of report:** 2021-02-18
**Severity:** Moderate
**Due date:** 2021-05-18

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

[Google Doc link](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.lb2mn3rmhf04)

**Comment by FuhuXia** [comment]
This is considered a low risk for our CKAN applications after some research. Details in google doc. Send back to icebox.

**Comment by mogul** [comment]
We'll check back in here after we're on CKAN 2.9, which should resolve it.
