### ISSUE TITLE
Insecure validation and defaults in pysaml2

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2845]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.pkbkuu1s2nev)._

https://snyk.io/vuln/SNYK-PYTHON-PYSAML2-1063038
https://snyk.io/vuln/SNYK-PYTHON-PYSAML2-1063039

**Date of report:** 2021-02-18
**Severity:** Moderate
**Due date:** 2021-05-18

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by adborden** [comment]
Confirmed the first fix is on production and login is working.

Going to switch to looking into https://github.com/gsa/datagov-deploy/issues/3170

**Comment by mogul** [comment]
@adborden can you clarify what state this issue is in? It's not clear what has yet to be done, or what's blocking this from proceeding.

**Comment by adborden** [comment]
There's some non-public discussion in the [security doc](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.t99541mgdfx5). I'll ping you on Slack.

**Comment by mogul** [comment]
Noting here since I keep forgetting: We are choosing to resolve this by continuing [our efforts to migrate to python3](https://github.com/GSA/datagov-ckan-multi/issues/563); it's blocked until that is done.

**Comment by jbrown-xentity** [comment]
Upgraded to pysaml2 on catalog and inventory to 7.0.1 ([inventory](https://github.com/GSA/inventory-app/blob/main/requirements.txt#L61) and [catalog](https://github.com/GSA/catalog.data.gov/blob/main/ckan/requirements.txt#L68)). This can be closed.

**Comment by nickumia-reisys** [comment]
:microphone: :fallen_leaf: (read: mic fall leave --> mic drop)
