### ISSUE TITLE
FGDC2ISO should use smoke tests in GH action deployment to cloud.gov

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2847]
## User Story

As a data.gov team member, I want validation that fgdc2iso is in a working state so that we can catch bugs before they deploy to production.

## Acceptance Criteria
- [ ] GIVEN smoke tests are integrated into the current GH actions of catalog-fgdc2iso
  WHEN a commit is pushed to `main`
  THEN I see a successful smoke test during the deploy to staging before being pushed to production

## Background
fgdc2iso uses an internal route so there is a certain setup needed.  If possible, we should also post data and validate the result - see the [current smoke tests](https://github.com/GSA/datagov-deploy/blob/develop/ansible/fgdc2iso.yml#L56-L780) or, probably easier to implement, the [current bats test on the app repo](https://github.com/GSA/catalog-fgdc2iso/blob/main/test/ping.bats#L17).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
None that come to mind.

## Sketch
Needs more grooming.

**Comment by jbrown-xentity** [comment]
Probably will use `cf ssh` and port forwarding to curl against that instance.

**Comment by jbrown-xentity** [comment]
This has been overcome by https://github.com/GSA/datagov-deploy/issues/2917, closing.
