### ISSUE TITLE
Catalog API no longer has harvest_object_id in package

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2854]
Reported from Geoplatform; their process of harvesting from data.gov is completely blocked.

The value still exists, because the "Metadata Source" section is still populated with the harvest_object_id embedded in the URL (see [this dataset](https://catalog.data.gov/dataset/airports-national-national-geospatial-data-asset-ngda-airports) for an example). It's not being reported under the "Additional Metadata" section as it was before, and is no longer in the API response.

#### Email Message from Geoplatform
What we used to do is query the package_show api with the metadata id with a request like this: 

    https://catalog.data.gov/api/3/action/package_show?id=airports-national-national-geospatial-data-asset-ngda-airports

and in that response, in `result.extras` there was usually an entry with {key: "harvest_object_id", value: "<UUID>"}. Using that <UUID> to construct a request to 

    https://catalog.data.gov/harvest/object/<UUID>

would give us the xml document, but it looks like that "harvest_object_id" entry is missing from the response.

I'm assuming this is a result of your recent CKAN upgrade, and if there's a workaround or better way to grab the harvest object from you for any particular dataset with the recent changes.

## How to reproduce

1. Go to https://catalog.data.gov/api/3/action/package_show?id=airports-national-national-geospatial-data-asset-ngda-airports, see no `harvest_object_id` in result

## Expected behavior

`harvest_object_id` is in the package response

## Actual behavior

`harvest_object_id` is missing in the response

## Sketch
Believe that one of the extensions is overwriting the response that the harvest extension normally inserts into the package extra info. Not sure if this is at the solr or the db level. Also not sure if the data used to be "injected" from the harvest tables at run time, or if the data was stored in the package info when harvested; more investigation is needed to find the previous logic in order to find the breakdown.

- [x] Ensure an integration test exists for this behavior

**Comment by adborden** [comment]
When we look into this, let's see if we can track down the [duplicate issue](https://github.com/GSA/datagov-deploy/issues/1182) with harvest_object_id so the value is correct.

**Comment by jbrown-xentity** [comment]
Would like to document how to use this API as we decommision the CSW service for those that need to get the metadata from the CKAN API.

**Comment by jbrown-xentity** [comment]
I've tracked the issue to [here](https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/plugin/__init__.py#L153), changing the default context.get('validate', False): allows the harvest info to show up. This code hasn't changed in years; in fact it's even in the GSA fork of the ckanext-harvest repo. I think that somehow we are resetting the context, but the [package_show route sets the context and it doesn't seem to be passed into extensions until the end](https://github.com/ckan/ckan/blob/2.8/ckan/logic/action/get.py#L980-L1074), and I've validated before the after_show function calls that the context doesn't have this value set...

**Comment by jbrown-xentity** [comment]
I dug into the old catalog code to see what has changed. I ended up testing against the old catalog on sandbox, and could not find how it was working. The same code injection listed above fails for the same reason.
The database is not storing the harvest object/source info in the package_extras.
The package extras contains the harvest info in the old system before any extension/plugin code is called.
My gut is that a custom workaround was built into GSA CKAN somehow, but could not find anything there either...

**Comment by adborden** [comment]
It's interesting that these fields are still available in package_search:
```
$ curl  -s 'https://catalog.data.gov/api/action/package_search?fq=name:airports-national-national-geospatial-data-asset-ngda-airports&rows=1' | jq -r '.result.results[0].extras[] | .key'
bbox-south-lat
bbox-east-long
contact-email
metadata-language
bbox-west-long
metadata-date
dataset-reference-date
resource-type
bbox-north-lat
spatial-reference-system
coupled-resource
spatial-data-service-type
frequency-of-update
licence
metadata_type
responsible-party
spatial
guid
progress
access_constraints
spatial_harvester
harvest_object_id
harvest_source_id
harvest_source_title
```

**Comment by jbrown-xentity** [comment]
This is another smell that I'm on the right track. Digging into the package_search functionality, ckan core uses the `before_view` function in ckanext-harvest the same as package_show; but then the variables get removed by `after_show` and never re-inserted. Raised to CKAN gitter this morning to see if I could get any feedback/clarification, and will probably make an upstream bug today.

**Comment by jbrown-xentity** [comment]
Raised to the Geoplatform team that they can get unblocked and make their API calls more efficient by using the `package_search` returned objects as the complete list; and then parse and request the full metadata directly from there. Might do some light support and documentation on best practices for that for future geospatial users (as we plan to deprecate CSW service)...

**Comment by jbrown-xentity** [comment]
No response on CKAN gitter. Raised ticket in ckanext-harvest: https://github.com/ckan/ckanext-harvest/issues/433

**Comment by jbrown-xentity** [comment]
Discussed issue with @adborden and @chris-macdermaid. Decided that more investigation on our end would be worth providing an upstream fix. Investigated the code, and tried to get ckanext-harvest tests working in our catalog.data.gov repo. Did not work, but noted that ckanext-harvest has github actions setup. Utilized this to make [a failing test](https://github.com/ckan/ckanext-harvest/pull/434) for our bug replicating the issue, and testing proposed solution.

**Comment by mogul** [comment]
Blocked waiting on action on the upstream PR.

**Comment by mogul** [comment]
Still waiting; no response from upstream maintainers on our submission. One contingency option would be to just work with the new harvesters.

**Comment by jbrown-xentity** [comment]
We have a response from Adria, with a request for a different approach. Need to implement and push to see if tests will pass.

**Comment by jbrown-xentity** [comment]
Ongoing work at https://github.com/ckan/ckanext-harvest/pull/438

**Comment by mogul** [comment]
@jbrown-xentity is going to look into the current status.

**Comment by jbrown-xentity** [comment]
Finally replaced defunct PR with one from GSA: https://github.com/ckan/ckanext-harvest/pull/458

Will remain blocked until we get someone to look at it.

**Comment by mogul** [comment]
While the upstream PR has been pending, we've started using this in a local branch. However, it caused problems with other stuff we use, so there's more work to be done and pushed upstream here.

**Comment by jbrown-xentity** [comment]
Expect the recent PR's to ckanext-harvest and catalog to resolve this issue for us, but upstream PR will leave this ticket blocked.

**Comment by jbrown-xentity** [comment]
Whoa, upstream merged our latest changes! I think I accidentally included @nickumia-reisys py3 patch as well, so it looks like we can get back on upstream!
https://github.com/ckan/ckanext-harvest/pull/458/files#diff-8ced6748a1ed15891f848eab285e9b304756761c9ef4a984c22acd9dab9c77b0R136
