### ISSUE TITLE
Renew data.gov site certificate

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2855]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 2021-02-19
**Severity:** N/A
**Due date:** 2021-04-20

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
The site certificate is due to expire in 60 days, we should renew the certificate and re-install it with netscaler and on CloudFront.

**Comment by adborden** [comment]
I think I recently renewed the site certificate as part of the Jenkins work but have not installed it. Check the expiration of the certificate in [Drive](https://drive.google.com/drive/folders/1E5R_hvgXdeF4pEId5xKPK-O4D-B4dqJR).

**Comment by adborden** [comment]
I confirmed that the certificate in Google Drive expires Not After : Jan 30 23:59:59 2022 GMT. All that is left for this issue is to work with FCS and SecOps to install the certificate and key.

**Comment by adborden** [comment]
Not sure why we have two different certs in production, but I noticed that Inventory and Dashboard expire Wednesday, April 21, 2021 at 4:59:59 PM Pacific Daylight Time. Updating the issue description.

**Comment by chris-macdermaid** [comment]
For the renewal:

Added the new cert to the AWS Cert Manager

Created a Service Desk ticket to  Install the certificate on Netscaler and coordinate with Secops
[RITM0834284](https://gsa.servicenowservices.com/nav_to.do?uri=sc_req_item.do%3Fsys_id=f5bf0b011b6fac10f001eb96bc4bcb07%26sysparm_stack=sc_req_item_list.do%3Fsysparm_query=active=true)

Sent message to  FCS Google Chat channel

To do:
Configure CloudFront distributions to use the new cert

**Comment by chris-macdermaid** [comment]
CloudFront distributions updated with new cert.

![Dashboard](https://user-images.githubusercontent.com/64213093/115443469-8b767d80-a1d0-11eb-83fd-9bdcfb90edf4.png)
![Inventory](https://user-images.githubusercontent.com/64213093/115443616-b52fa480-a1d0-11eb-82c5-85baacb99587.png)
![WordPress](https://user-images.githubusercontent.com/64213093/115443666-c4165700-a1d0-11eb-983e-654d732dbe53.png)
![Catalog](https://user-images.githubusercontent.com/64213093/115443716-d2fd0980-a1d0-11eb-9791-0b37df0f5c21.png)
![Admin Catalog](https://user-images.githubusercontent.com/64213093/115443839-02ac1180-a1d1-11eb-9cea-bd96b3cb01b5.png)

**Comment by adborden** [comment]
FYI, the CAA DNS records aren't really relevant here. This is the proof you're looking for, notice the expiration date is now January 30th, 2022.
![Screen Shot 2021-04-20 at 11 23 51 AM](https://user-images.githubusercontent.com/509703/115445645-fd4bc880-a1ca-11eb-9742-b8600b4a3e43.png)

You can also see this with openssl. Fetch the certificate and show print the dates.
```
$ echo | openssl s_client -servername catalog.data.gov -connect catalog.data.gov:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Feb  1 00:00:00 2021 GMT
notAfter=Jan 30 23:59:59 2022 GMT
```

**Comment by chris-macdermaid** [comment]
Verified the certs were updated using openssl. 
Added a 12/1/2021 reminder to datagov calendar to update certs.
