### ISSUE TITLE
Inventory Roll Out

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2858]
## User Story
As a data.gov developer, I want use well tested inventory-next.data.gov running CKAN 2.8 to serve for inventory production traffic so that we can use new features and security enhancement offered by CKAN 2.8.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I visit https://inventory.data.gov/api/action/status_show \
  THEN I see "ckan_version: 2.8.7" in the result

- [x] GIVEN I have a login.gov account \
  And it is MFA enabled with PIV card  \
  WHEN click login button on inventory.data.gov \
  THEN I can log in as a valid user

- [x] GIVEN I am a logged in user
  WHEN I visit https://inventory.data.gov/dataset \
  THEN I see production datasets

- [x] GIVEN I am a logged in user \
  AND pick a test dataset \
  WHEN upload the spreadsheet file as resource \
  THEN I can preview the spreadsheet data in Data Explorer

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
- [x] Schedule switchover tasks and notify inventory user the downtime.
- [x] FCS takes inventory production DB snapshot and restore to inventory-next DB. 
- [x] data.gov team follows [switchover plan](https://github.com/GSA/datagov-deploy/issues/2248) to make DB and S3 ready. 
- [x] data.gov team verifies results on `inventory-next.data.gov` 
- [x] data.gov team changes `inventory-next.data.gov` to `inventory.data.gov` in saml2/login.gov configuration. 
- [x] FCS configures NetScaler to use `inventory-next.data.gov` for inventory production. 
- [x] data.gov team verifies results on `inventory.data.gov`. 
- [x] Review [the set of issues attached to this Epic that are still in the Icebox](https://github.com/GSA/datagov-deploy/issues/993), and determine if they can be closed

**Comment by FuhuXia** [comment]
Two BSP ticket created.
REQ0588748 (RITM0817808) for RDS snapshot requested to be scheduled on 2021-03-03 5pm ET
REQ0588753 (RITM0817813) for NetScaler config change requested to be scheduled on next morning.
