### ISSUE TITLE
[Research 0.5d]: Determine strategy to backup secrets in cloud.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2864]
## User Story

In order to quickly recover from an accidentally deleted user-provided service, data.gov team wants a plan of how to backup and restore secrets to cloud.gov applications.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
Since `cf update-user-provided-service` is an all-or-nothing operation, it's easy to blow away the secrets in your user-provided service. We want to have a plan on how to backup secrets so that the user-provided service can be recreated without having to figure out where to find secrets.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."

## Sketch
- [ ] Secrets that are "precious" (eg Saxon license file) should use Google Drive as the "source-of-truth" so we don't have to worry about them.
- [ ] Other secrets should be easy to re-generate (e.g. automatically rotate a randomly generated password), create issues for any secrets in this category that are not automatically updated.
- [ ] Any remaining secrets should be backed up

**Comment by adborden** [comment]
IMHO, I would like to see a plan that incorporates these qualities:

- README driven (application secrets are documented in the application)
- Avoid confusing the source of truth (New Relic license key should live in New Relic)
- Avoid over-engineering (manual process is good)

**Comment by mogul** [comment]
I don't see this as much different from ensuring backups of service instance content are regularly made. 

My plan for that was to share the service instances we care about into the `management` space, then have an app or task that runs there which makes dumps and puts them in an S3 bucket.  However, I'm not sure if you can share a user-provided service instance. 🤔
