### ISSUE TITLE
Wordpress to Static Site*

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2875]
## Feature/what we're after
Move Wordpress content to static federalist site.

## Anticipated/hypothesized benefits
- Lower administrative burden
- Lower tech debt
- Lower SSP burden

## Measurements/metrics
- www.data.gov should be available through Federalist

## References/background

**Comment by hkdctol** [comment]
Gradually adding Epics to https://github.com/orgs/GSA/projects/11 this one and associated issues have been added.

**Comment by hkdctol** [comment]
This epic has been entered into Github projects board https://github.com/orgs/GSA/projects/11/views/4

**Comment by hkdctol** [comment]
Closing this as we did move out of WordPress and didn't any other tickets to be under this Epic.
