### ISSUE TITLE
[research: 0.5d] identify a process for handling Terraform issues

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#2889]
## User Story

As a person in O&M role, I want a process to triage Snyk Terraform issues.

## Acceptance Criteria
- [ ] Test Synk CLI/wizzard for potential guidance for creating .snyk
- [ ] Test CLI/GitHub integration to enforce snyk tests on PRs?

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
No security concerns. This a research ticket.

## Sketch
[Example Terraform snyk issue](https://app.snyk.io/org/data.gov/project/3d110968-3e38-40b6-b6d4-0b1586cf1543)

The snyk Terraform scanning documentation is [here](https://support.snyk.io/hc/en-us/articles/360010916577-Scan-and-fix-security-issues-in-your-Terraform-files).

The snyk CLI documentation is [here](https://support.snyk.io/hc/en-us/categories/360000456217-Snyk-CLI). 

The snyk GitHub integration documentation is [here](https://support.snyk.io/hc/en-us/articles/360004032117-GitHub-integration)

**Comment by mogul** [comment]
James and I discovered that Snyk does provide options for snoozing/ignoring Terraform findings in the Snyk UI; it appears it's keeping some sort of .snyk for itself behind the scenes...? In which case this work may not be necessary. We may still need a way to show where we've got ignored issues documented, though; to date we only know how to find them through the Snyk filters on an individual .TF file.

**Comment by hkdctol** [comment]
@jbrown-xentity can pair with team member picking this one up

**Comment by jbrown-xentity** [comment]
Going to not take on this work, as we are not sure at this time the value of this process.

**Comment by nickumia-reisys** [comment]
I feel like this was superseded by
- https://github.com/GSA/data.gov/issues/4094

Yes, we sort of stopped doing it, but since we are picking up SSB work again, I think it might be important to revisit..
