### ISSUE TITLE
Update O&M Snyk triage documentation

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#2891]
## User Story

As a person in O&M role, I want the O&M [Snyk triage documentation](https://github.com/GSA/datagov-deploy/wiki/Dependency-scanning) updated to improve the process: lower overhead to manage known vulnerabilities, and improve process for updating/upgrading dependencies.

## Acceptance Criteria
- [x] Review O&M Snyk triage documentation
- [x] O&M Snyk triage documentation updated

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
No security concerns. This will improve the security compliance process.

## Sketch
More background can be found in the [notes](https://docs.google.com/document/d/1M4DeIohkY5YXmkv9Y495HclKrTf7nheKUprvePzlveA/edit?usp=sharing) from the reviewing the state of Snyk discussion on 2/24/2021.

Items to add to the O&M documentation:
- [x] Clean up outdated Snyk rules as part of the triage of compliance issues (white noise threshold and fix expectation, validate issues created for vulnerabilities, etc)
- [x] Provide a link to the GitHub issue within any Snyk issue.
- [x] Clarify snyk exception handling (when exception expires and upgrading is still unavailable, what needs to happen? Should raise on Slack for discussion when example arises)
- [x] Add labels to compliance Github issues: month milestone, component affected

**Comment by hkdctol** [comment]
@jbrown-xentity will pair with the team member picking this up

**Comment by hkdctol** [comment]
Will look at this in pairing
