### ISSUE TITLE
USGS Original Product Resolution harvest source not harvesting

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2896]
## How to reproduce

This is among the USGS harvest sources we were not able to successfully harvest before new catalog launch. 

Name of source: Original Product Resolution (OPR) Source Digital Elevation Models (DEMs) - USGS National Map

URL: http://thor-f5.er.usgs.gov/ngtoc/metadata/waf/elevation/opr_dem/arcgrid/

## Expected behavior

Successful harvest of source

## Actual behavior

Errors--see latest report
![USGS2](https://user-images.githubusercontent.com/3236989/108576375-6efeb780-72eb-11eb-8bbc-c67b3222b534.png)

**Comment by chris-macdermaid** [comment]
The WAF has a lot of collection metadata records and is slow. I tried using curl to get the records and after 6 hours and GBs of metadata, I cut it off. I also tried to scrape the pages using a Python script, but it was still running after 12 hours. Give this, I'm not able to determine the number of metadata records in the WAF.

**Comment by mogul** [comment]
Hyon has reached out for a meeting; no response yet.

**Comment by mogul** [comment]
Pinged USGS rep today; no response yet.

**Comment by hkdctol** [comment]
Created a root record only harvest source.

**Comment by hkdctol** [comment]
Harvest of root record successful. https://catalog.data.gov/dataset/original-product-resolution-opr-source-digital-elevation-models-dems-usgs-national-map-3dep-dow1
