### ISSUE TITLE
USGS harvest source usgs-historical-topographic not harvesting

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2897]
## How to reproduce

Among USGS sources that did not harvest successfully before new catalog launch.

Name: usgs-historical-topographic-maps
URL: http://thor-f5.er.usgs.gov/ngtoc/metadata/htmc/

## Expected behavior

Successful harvest of source

## Actual behavior

See errors--latest report
![USGS 1](https://user-images.githubusercontent.com/3236989/108576523-ef251d00-72eb-11eb-8e89-e38126334e13.png)

## Sketch

Short term solution, make the harvest source manual:
- Create a new harvest source with a similar title but add "root record only"
- Use the "Single Spatial Metadata Document" harvest type
- Use the URL from the previous harvest source that was the "collection record URL" as the harvest URL
- Setup harvest update schedule to be the same as the collection harvest source

**Comment by jbrown-xentity** [comment]
Testing on production now. Harvest job created at 9:12 am ET, hit gather blocker #2155; restarted jobs and now harvest job officially picked up at 10:45 am ET. Watching logs for issues and timing...

**Comment by mogul** [comment]
Pinged USGS rep today; no response yet.

**Comment by hkdctol** [comment]
Moving the various USGS harvest source tickets to icebox until we hear back from USGS.

**Comment by hkdctol** [comment]
Harvest of the root record successful. https://catalog.data.gov/dataset/usgs-historical-topographic-map-collection1
