### ISSUE TITLE
USGS harvest source - USGS US Topo Maps not harvesting

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2898]
## How to reproduce

USGS harvest source that did not harvest before new catalog launch

Name: USGS US Topo Maps

URL: https://thor-f5.er.usgs.gov/ngtoc/metadata/waf/ustopo/geopdf/

## Expected behavior

Successful harvest of source with datasets added

## Actual behavior

See errors in latest report
![USGS3](https://user-images.githubusercontent.com/3236989/108576623-41663e00-72ec-11eb-9a2f-2ce37739a4c0.png)

**Comment by mogul** [comment]
Pinged USGS rep today; no response yet.

**Comment by hkdctol** [comment]
Created a root record only harvest source.

**Comment by hkdctol** [comment]
Moving to icebox pending further feedback from USGS. See notes of May 7 meeting https://docs.google.com/document/d/1hJFB-cNpWMKNBx1niXhp0YUs8TT2Ynd1gtIDz5UL4yQ/edit
