### ISSUE TITLE
Bad Gateway error when login to catalog

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2899]
Error seen after login.gov login process and redirected back to catalog site.

Redirected to: admin-catalog-next.data.gov/acs
**Bad Gateway**

![Screen Shot 2021-02-25 at 4 07 37 PM](https://user-images.githubusercontent.com/1392461/109217713-28460d00-7784-11eb-9a9a-46eab5d133ed.png)
## How to reproduce

This is intermittent when login to catalog.data.gov

## Expected behavior

successful login

## Actual behavior

Error. Have to repeat login process.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
Tested just now, login worked with no issues. Is this intermittent or constant @FuhuXia?

**Comment by FuhuXia** [comment]
Intermittent.  Very rare actually. Saw twice after login.gov integration.

**Comment by FuhuXia** [comment]
Could be some production deployment ongoing at the time when we saw the error.

**Comment by FuhuXia** [comment]
Keep seeing the same error on inventory today. A browser refresh usually solves it. 
![Screen Shot 2021-03-11 at 11 23 35 AM](https://user-images.githubusercontent.com/1392461/110820123-ce057b80-825c-11eb-9749-2129bd18c64b.png)

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
