### ISSUE TITLE
SSB Managed Boundary documented in SSP Section 13

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2900]
## User Story

In order to complete the ATO assessment of the SSB, GSA A&A personnel want to read about the SSB Managed Boundary in Section 13 of the SSP.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I am looking at the SSB SSP in Google Docs \
  WHEN I read the control descriptions for the AC, AU, IA, SC, and SI families \
  THEN I see an "SSB Application Boundary" section with info about the application on cloud.gov \
  AND  I see an "SSB Managed Boundary" section with info about the provisioned resources in AWS.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

We copied from the data.gov SSP for the SSB application information, but that was before the Managed Boundary was added to the SSP. Now that it's in there we have to go through the same process for documenting IaaS-specific configuration.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."

Information in the SSP is controlled according to normal Google Doc restrictions on SSPs in place for GSA IT.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- [x] Add the Boundary delimiting markers

Fill in the Managed Boundary for each of the technical families
- [x] AC
- [x] AU
- [x] IA
- [x] SC
- [x] SI

**Comment by adborden** [comment]
🏁   AC family complete! The controls after AC-12 were much easier 😼

**Comment by mogul** [comment]
Aaron and I started working on the SI family today and made it through SI-7 (about halfway).

**Comment by adborden** [comment]
🏁  we completed SI family.

**Comment by adborden** [comment]
🏁  SC family complete!

**Comment by adborden** [comment]
🏁  AU family complete pending review!

@jbrown-xentity and I paired up to AU-8. @jbrown-xentity, if you have some time, please review my narratives for the rest of the AU family.

I went through the document comments and created a few issues where we have Planned controls.

**Comment by mogul** [comment]
Filled out the Privileged User Authentication flow for AWS in Section 9.4, now that we know how AssumeRole will work with our accounts.
![image](https://user-images.githubusercontent.com/47762/114810323-b1c79380-9d60-11eb-916b-940f45533490.png)
