### ISSUE TITLE
USGS harvest source National Hydrography Dataset Plus High Resolution not harvesting

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2904]
## How to reproduce

This is a valid harvest source that we confirmed with USGS representative. Old catalog shows datasets, new catalog shows zero datasets.

## Expected behavior

Valid harvest of WAF collection

## Actual behavior

Harvest source is in new catalog, with no datasets.

## Sketch
-Try manual harvest of source in new catalog. 
Name: National Hydrography Dataset Plus High Resolution (NHDPlus HR) - USGS National Map
URL: https://thor-f5.er.usgs.gov/ngtoc/metadata/waf/hydrography/nhdplus_hr/gdb/

-Note results
-See if result is same as in previous worksheet, line 558 https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?usp=sharing

**Comment by mogul** [comment]
Waiting on conversation with USGS

**Comment by mogul** [comment]
Pinged USGS rep today; no response yet.

**Comment by hkdctol** [comment]
Created a root record only harvest source.

**Comment by mogul** [comment]
Once again waiting on feedback from USGS.

**Comment by mogul** [comment]
Icebox'ing until we get valid URLs back from USGS

**Comment by hkdctol** [comment]
I got a valid URL from USGS yesterday and was able to harvest the root record on this one. Moving to needs review until we can discuss and decide whether we close these.

**Comment by hkdctol** [comment]
I'm going to move this back to icebox. We had discussed perhaps USGS getting user input on what we decided to do which was just get a single record for some of these harvest sources. We can turn to this again when we have time or if USGS has a comment.
