### ISSUE TITLE
USGS harvest source Alaska Digital Surface Models (DSMs) not harvesting

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2905]
This is a valid harvest source we confirmed with USGS rep.

## How to reproduce

Harvest source under USGS in new catalog under this name, shows zero datasets

## Expected behavior

Harvest source in old catalog indicates this source should have 399 datasets

## Actual behavior

Harvest source is in new catalog with no datasets

## Sketch
Try manual harvest
Name: Alaska Digital Surface Models (DSMs) - USGS National Map
URL: https://thor-f5.er.usgs.gov/ngtoc/metadata/waf/elevation/dsm_ifsar/
Note errors in harvest report
See line 144 of the worksheet: https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?usp=sharing

**Comment by mogul** [comment]
Waiting on conversation with USGS

**Comment by mogul** [comment]
Pinged USGS rep today; no response yet.

**Comment by hkdctol** [comment]
@jbrown-xentity on this one, the existing harvest source had the same URL in the main URL field and in the collection metadata field - https://thor-f5.er.usgs.gov/ngtoc/metadata/waf/elevation/dsm_ifsar/  would that still work for single record source type? Should I try to delete the existing source first then?

**Comment by jbrown-xentity** [comment]
That is very strange. I don't know that this record would harvest correctly as a collection then. We might need to reach out to USGS to figure out what the "root" record should be.

**Comment by hkdctol** [comment]
This is in blocked--we reached out to USGS about the appropriate harvest URL for getting a single metdata record on this.

**Comment by mogul** [comment]
@hkdctol is going to ping USGS again.

**Comment by mogul** [comment]
Icebox'ing until we get valid URLs back from USGS

**Comment by hkdctol** [comment]
Got a valid URL from USGS and was able to harvest root record.

**Comment by hkdctol** [comment]
Closing these old USGS tickets--we've met recently and are up to date on the sources they've asked for harvesting.
