### ISSUE TITLE
Firewall prevents Jenkins from deploying to mgmt and production jumpbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2912]
When deploying via Jenkins, we see the ansible ping step fail because the connection times out for both the mgmt and production jumbox.

## How to reproduce

1. Connect to the mgmt jumpbox `ssh datagovjump1m.mgmt-ocsit.bsp.gsa.gov`
2. Connect to Jenkins with agent forwarding `ssh -A jenkins.mgmt-ocsit.bsp.gsa.gov`
3. Connect to prod or mgmt jumpbox `ssh datagov-jump2p.prod-ocsit.bsp.gsa.gov`

## Expected behavior

Connection succeeds, you get a shell on the production jumpbox.

## Actual behavior

Timeout error.

## Sketch
- [ ] Open a Firewall Change Request.
- [ ] Remove the `\\!jumpbox` exclusions from the Jenkinsfile.

**Comment by adborden** [comment]
Fallout from https://github.com/GSA/datagov-deploy/issues/2708

**Comment by mogul** [comment]
Iceboxing as we can work around this manually for now if we need to.

**Comment by nickumia-reisys** [comment]
No more Jenkins.  No more jumpbox.
- https://github.com/GSA/data.gov/issues/3710
