### ISSUE TITLE
Federal agencies are informed that all dataset resources on catalog.data.gov must be served over HTTPS

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2915]
## User Story

In order to maintain trust and accessibility of datasets we index (by preventing browser warnings), we want partner agencies to replace HTTP URLs with HTTPS URLs

## Acceptance Criteria

- [x] All agencies are informed that in order to ensure that a data.gov user clicking on a download URL, the download is available, all agency URLs have to be https. 

## Background
https://blog.chromium.org/2020/02/protecting-users-from-insecure.html

Lynda reported this.
https://catalog.data.gov/dataset/fws-critical-habitat-for-threatened-and-endangered-species-datasetd55fc
Links to http resources, and chrome (and other modern web browsers) will block these downloads.

http://ecos.fws.gov/docs/crithab/crithab_all/crithab_all_layers.zip
http://ecos.fws.gov/docs/crithab/crithab_all/crithab_all_shapefiles.zip

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
This ticket is for the agency communication only.

**Comment by adborden** [comment]
Part of this is outreach to agencies to update http links with https.

And/or... we can try to do something in the harvesters to try the https link when we come across an http and replace it transparently and raise a warning and error if the https link does not exist.

And/or... we can add regular monitoring/scanning that identifies these links... although that sounds like what the harvesters do to me.

**Comment by adborden** [comment]
Opened https://github.com/ckan/ckanext-harvest/issues/435 upstream.

**Comment by hkdctol** [comment]
Email message sent to agency POCs on 3/16.
