### ISSUE TITLE
Wrong type of metadata showing for datasets harvested from ckan source

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2916]
Datasets harvested from [DOI Open Data](https://catalog.data.gov/harvest/doi-open-data) is showing `ISO-19139 Metadata` as the metadata source,  but it is actually type of `Data.json Metadata`. 

## How to reproduce

Pick any dataset harvested from [DOI Open Data](https://catalog.data.gov/harvest/3a60d81e-ede6-416f-b7f9-7b3298ef2115). Such as [this one](https://catalog.data.gov/dataset/outer-continental-shelf-official-protraction-diagrams-and-lease-maps-gulf-of-mexico-region-nad). 

Go to **Metadata Source** section. 

## Expected behavior

![Screen Shot 2021-03-01 at 1 57 40 PM](https://user-images.githubusercontent.com/1392461/109544926-23d86780-7a96-11eb-9c12-d3306104b6a5.png)

## Actual behavior
![Screen Shot 2021-03-01 at 1 58 31 PM](https://user-images.githubusercontent.com/1392461/109544988-3d79af00-7a96-11eb-9034-01d54a3a4410.png)

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
This is wrong only for CKAN harvest types, not for others. The [logic in ckanext-datagovtheme](https://github.com/GSA/ckanext-datagovtheme/blob/master/ckanext/datagovtheme/helpers.py#L38-L89) checks for `ckan_url`, which doesn't exist in DOI package object.
DOI is the only current user of the CKAN-to-CKAN harvest and plans to deprecate in the coming month for DCAT-US.
