### ISSUE TITLE
DOI CKAN harvesting psycopg2.IntegrityError

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2920]
There were 57 psycopg2.IntegrityError errors when harvesting from data.doi.gov, as reported in [this job](https://admin-catalog-next.data.gov/harvest/doi-open-data/job/1d9e81f4-3005-4093-8f46-4155c8ae04c5). 

```
e4df57d3-3c45-405a-932d-c78bab2e82f9
(psycopg2.IntegrityError) insert or update on table "harvest_object" violates foreign key constraint "harvest_object_package_id_fkey" DETAIL: Key (package_id)=(e4df57d3-3c45-405a-932d-c78bab2e82f9) is not present in table "package".
```

## How to reproduce

As show in the harvest job Error Report.

**Comment by mogul** [comment]
Iceboxing since we're going to be moving to DCAT-US.

We should open an issue upstream about this behavior before we close this one.
