### ISSUE TITLE
Drain logs from cloud.gov spaces to AWS Elasticsearch instance

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2921]
## User Story

In order to support data.gov's needs for monitoring and alerting on app behavior, the data.gov team wants to drain logs from cloud.gov spaces to a brokered instance of AWS ES.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I am logged into the Kibana associated with the `gsa-datagov/management` space \
  WHEN I generate traffic to a data.gov application in any space in the `gsa-datagov` organization \
  THEN I see the activity logged via the Kibana UI.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This story configures cloud.gov's platform-provided logging facilities to send logs from our spaces to a cloud.gov-brokered instance of AWS Elasticsearch. We assume that cloud.gov has ensured that the communication mechanisms are secured with TLS, and that client credentials are used for accessing the AWS ES endpoints; this should be verified. If IP restrictions are in place (eg only the cloud.gov egress IP ranges are permitted), then we should be noting that and documenting how to access the Kibana UI in our runbook. (Even if cloud.gov does not apply IP restrictions on its own, we should consider whether we want to add them ourselves.)

Note that AWS ES should be configured to prevent modifications of records in accordance with AU-9 if possible. If that's not possible, we may want to investigate how to also drain logs to [CloudWatch Logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html); this would likely happen via a separate issue.

## Sketch

- [x] Broker [an `es-medium-ha` instance of the `aws-elasticsearch`](https://cloud.gov/docs/services/aws-elasticsearch/) service in the `management` space
- [x] Try to figure out how cloud.gov is configuring the access control, and see if we need to do more (as described in [the AWS docs for provisioning an instance](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-gsg-create-domain.html)).
- [x] [Generate a syslog URL if necessary](https://docs.cloudfoundry.org/devguide/services/log-management.html#step1) (meaning if cloud.gov and AWS ES do not supply one by default).
  - [ ] ~There's [a syslog input plugin for ES](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html).~ AWS ES doesn't allow installation of plugins.
  - [x] Alternatively, we can [run `fluent-bit` as an app using the apt-buildpack](https://docs.fluentbit.io/manual/installation/linux/ubuntu), configured with [the syslog input](https://docs.fluentbit.io/manual/pipeline/inputs/syslog) and [the Elasticsearch output](https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch). ([Cloud Foundry documents how to configure the input plugin.](https://docs.cloudfoundry.org/devguide/services/fluentd.html#config))
  - [x] Another option is using Logstash. [Swisscom has documented how to do this using the stock docker image with Cloud Foundry.](https://docs.developer.swisscom.com/service-offerings/logstash-docker.html)
- [x] Configure cloud.gov to [drain logs to the service instance](https://docs.cloudfoundry.org/devguide/services/log-management.html#user-provided). Rather than binding each individual app in each space to the log drain, **set up the log drain once for each space** using the [`log-drain` CF CLI plugin](https://github.com/cloudfoundry/cf-drain-cli#drain-all-apps-in-a-space).
- [x] Verify that we can [authenticate with Kibana and view the UI](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-kibana.html)
- [x] Test that any logs generated are showing up in Elasticsearch.

**Comment by mogul** [comment]
Need to make a decision on Fluent Bit vs LogStash

**Comment by adborden** [comment]
notes to self:

Take a look at the logstash configs available from https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry

How do we push our indexing config?

**Comment by adborden** [comment]
Memory calculation for Logstash https://github.com/cloudfoundry/java-buildpack-memory-calculator

**Comment by mogul** [comment]
And now, Brand X.
https://sematext.com/docs/logagent/
https://sematext.com/docs/logagent/input-plugin-cloudfoundry/
https://sematext.com/docs/logagent/output-plugin-aws-elasticsearch/
