### ISSUE TITLE
Open an issue on datagov-deploy when broken links are identified on static sites

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2922]
## User Story

In order to promptly notify and nudge the team to take action when broken links are identified, data.gov team wants static sites to open a GH issue in datagov-deploy when a qa check fails.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
Some of our sites ([resources.data.gov](https://github.com/GSA/resources.data.gov/issues/258)) have a `qa` task that checks for broken links. This is run ~weekly in CI, but its easy to miss. Only those following the CircleCI project will receive an email. If we open an issue in datagov-deploy, we'll make sure to triage it as it is discovered and can even get a weekly reminder on it.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
- [x] Move CI to GitHub Actions
- [ ] Use the the same Issue Notifier action from https://github.com/GSA/datagov-deploy/issues/2827, with a custom title.

**Comment by mogul** [comment]
In the meantime, we can add checking the QA task output to the O&M role.

**Comment by nickumia-reisys** [comment]
Seeing as how the broken link checking algorithm is flaky, this is not a priority as the false positive rate would be too high.  The following issue is related:
- https://github.com/GSA/data.gov/issues/4182

We may pick this up in the future?  We have the infrastructure to enable this since we create issues when catalog/inventory restarts/deployments fail,
- https://github.com/GSA/data.gov/issues/2827

Since the QA Job is a Github Action, the same design could be implemented here.

**Comment by hkdctol** [comment]
Might be taken care of by #4476 so icebox for now, might be closed if we finish that other one
