### ISSUE TITLE
Add rows to dashboard for agencies with identified CDOs

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2923]
## User Story

As Data.gov PMO, want to have a listing of agencies that have identified CDOs to keep track of efforts in adding agencies to the catalog.

## Acceptance Criteria
The dashboard, even though we may replace with another measure, is still a location where we want to have agencies listed with identified CDOs

## Background
The CDO council recently launched a website and identified agencies and CDOs https://www.cdo.gov/council-members/
Even if they are not ready with metadata inventories, we should list them on the dashboard now as we continue outreach.

## Sketch
Add the following agencies to the dashboard https://labs.data.gov/dashboard under "Other Agencies"

Administrative Conference of the United States
American Battle Monuments Commission
Commodity Futures Trading Commission
Consumer Product Safety Commission
Corporation for National and Community Service
Court Services and Offender Supervision Agency for the District of Columbia
Department of the Army
District of Columbia Courts
Export-Import Bank of the U.S.
Farm Credit Administration
Farm Credit System Insurance Corporation
Federal Communications Commission
Federal Energy Regulatory Commission
Federal Maritime Commission
Federal Mediation and Conciliation Service
Federal Retirement Thrift Investment Board
Gulf Coast Ecosystem Restoration Council
Intelligence Community
Inter-American Foundation
National Capital Planning Commission
National Credit Union Administration
National Endowment for the Arts
National Mediation Board
Nuclear Waste Technical Review Board
Office of Government Ethics
Office of the Comptroller of the Currency
Peace Corps
Securities and Exchange Commission
Selective Service System
Surface Transportation Board
U.S. Access Board
U.S. Agency for Global Media
U.S. Air Force
U.S, Commission of Fine Arts
U.S. Department of Navy
U.S. Occupational Safety and Health Review Commission
U.S. Office of Special Counsel
U.S. Trade and Development Agency

**Comment by pjsharpe07** [comment]
Strange that we already have a lot of these agencies accounted for in [this db migration step](https://github.com/GSA/project-open-data-dashboard/blob/main/application/migrations/007_add_omb_monitored_flag.php).

We still need the changes to and from the `main` branch.

**Comment by pjsharpe07** [comment]
After the navy changes, we'll make sure to bring over these to `main`

**Comment by pjsharpe07** [comment]
See this [slack thread for confirmation](https://gsa-tts.slack.com/archives/C2N85536E/p1615421564069900?thread_ts=1615410926.061600&cid=C2N85536E)
