### ISSUE TITLE
Inventory 2.8 branch add ckanext_datagov_inventory as git+git://github.com:GSA/

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2925]
CKAN extensions are added to requirements-freeze.txt as  `git+https://github.com/...`. But `ckanext_datagov_inventory` is added as `git+git://github.com:GSA/...`. 

## How to reproduce

Check in https://github.com/GSA/inventory-app/tree/inventory_ckan_2.8
Run `make requirements`

## Expected behavior
`ckanext_datagov_inventory` to be added as
```
-e git+https://github.com/GSA/inventory-app.git@...
```
## Actual behavior

`ckanext_datagov_inventory` is added as
```
-e git+git://github.com:GSA/inventory-app.git@...
```

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
Since this is only a problem when you re-freeze requirements (a manual operation) and you can manually resolve the problem at that time, we're choosing not to address this and Icebox'ing.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
