### ISSUE TITLE
Universal update to a metadata field in inventory.data.gov for an agency

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2928]
## User Story

As an inventory.data.gov user, it will be useful to have the data.gov team make universal updates to all metadata records for a particular field, rather than opening and editing each dataset record.

## Acceptance Criteria
- [x] GIVEN that an agency has a need to update the value of a particular metadata field for all the agency datasets \
  WHEN an agency has a particular need\
  THEN the agency can request the change by contacting Data.gov\
  AND the Data.gov team can do the update automatically.
- [x] In this particular case, all datasets for EIA https://inventory.data.gov/organization/eia-gov need to have Contact Name changed from Melinda Hobbs to William Jeffers.

## Background
EIA asked about this by email 3/3/21. Seems like a request that could come up again with other agencies and it will be useful to know how to make universal changes to particular metadata field.

## Sketch
See similar work https://github.com/GSA/ckan-php-manager

**Comment by hkdctol** [comment]
EIA pinged about this today (5/19/21). I informed them of the status of the ticket. It's not urgent for them but they are still interested in this.

**Comment by FuhuXia** [comment]
For any EIA dataset with Contact Name `Melinda Hobbs`, it was changed to Contact Name: `William Jeffers`, using the following command:

`php cli/update_extra_fields.php`

The sample CSV file used for this task:
```
dataset,extra_field,old_value,new_value
some-dataset-name,contact_name,Melinda Hobbs,William Jeffers
some-other-dataset-name,contact_name,Melinda Hobbs,William Jeffers
```

**Comment by FuhuXia** [comment]
One dataset has contact name `Mark Elber`. It is also updated to `William Jeffers`.
