### ISSUE TITLE
Jenkins polling is not detecting changes

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2931]
Last datagov-deploy build was 2/27 87e3c18776e9b726595060ec4def83eb7dda8bbb  https://ci-datagov.mgmt-ocsit.bsp.gsa.gov/job/deploy-ci-platform/lastBuild/

Last master commit was 3/3 431cd9bf3c54935ce00b02202fc544295e549e6f

Polling log says no changes https://ci-datagov.mgmt-ocsit.bsp.gsa.gov/job/deploy-ci-platform/scmPollLog/ but there definitely have been.
```
Started on Mar 3, 2021 11:59:00 PM
Using strategy: Default
[poll] Last Built Revision: Revision 87e3c18776e9b726595060ec4def83eb7dda8bbb (refs/remotes/origin/master)
The recommended git tool is: NONE
No credentials specified
 > git --version # timeout=10
 > git --version # 'git version 2.17.1'
 > git ls-remote -h -- https://github.com/gsa/datagov-deploy.git # timeout=10
Found 62 remote heads on https://github.com/gsa/datagov-deploy.git
Using strategy: Default
[poll] Last Built Revision: Revision 87e3c18776e9b726595060ec4def83eb7dda8bbb (refs/remotes/origin/master)
The recommended git tool is: NONE
No credentials specified
 > git --version # timeout=10
 > git --version # 'git version 2.17.1'
 > git ls-remote -h -- https://github.com/gsa/datagov-deploy.git # timeout=10
Found 62 remote heads on https://github.com/gsa/datagov-deploy.git
Done. Took 0.28 sec
No changes
```

## How to reproduce

Push up a new commit to `master` and look for an update at the URL above.

## Expected behavior

Changes are detected and rolled out.

## Actual behavior

"No changes"

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
I believe https://github.com/GSA/catalog.data.gov/pull/256 did not deploy either; would be interested in pairing to resolve @adborden ...
