### ISSUE TITLE
Task: Renew data.gov domain registration

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2936]
**Due April 3rd, 2021**

Domain registration with dotgov.gov is expiring.  We need to provide payment.

**Comment by mogul** [comment]
Waiting on p-card activity

**Comment by mogul** [comment]
Still waiting on a p-card bearer. Hyon is pinging Cindy to see if it can get some attention.

**Comment by hkdctol** [comment]
I was informed this was done today. Will check with @adborden if he got the confirmation email before marking as done.

**Comment by adborden** [comment]
I did receive a confirmation from dotgov.gov. All set here until April 3, 2022.
