### ISSUE TITLE
Catalog language URLs are indexed by Google

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2938]
It looks like language pages are not using the canonical URL tag https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls

## How to reproduce

1. Google search for "catalog.data.gov russian" https://www.google.com/search?hl=en&q=catalog.data.gov%20russian

## Expected behavior

I only see canonical (non-language) URLs.

## Actual behavior

Non-canonical language URLs appear in Google.

https://catalog.data.gov/es/dataset/maps-of-the-russian-far-east

## Sketch
Add canonical tag to language pages.

**Comment by nickumia-reisys** [comment]
Non-english pages have been disabled,
- https://github.com/GSA/data.gov/issues/3905
- https://github.com/GSA/data.gov/issues/2788
- https://github.com/GSA/catalog.data.gov/pull/510

Historical reference for,
- https://github.com/GSA/data.gov/issues/4061
- https://github.com/GSA/data.gov/issues/3426
- https://github.com/GSA/data.gov/issues/3490
