### ISSUE TITLE
Build a test environment in AWS using Terraform

### ISSUE THREAD

**Issue by hareeshreddyg** [GSA/data.gov#295]
Build a test environment using terraform in AWS, mirror to current production environment.

**Comment by theresaanna** [comment]
What is the estimated level of effort required for this? This maybe feels like a ticket that should be split into pieces.

**Comment by hareeshreddyg** [comment]
It could be two weeks approximately from today, but we'll try to complete it ASAP and update the status on each step once done out of  below four
1. Launch the Infrastructure using Terraform in AWS.
2. Deploy Software using Ansible.
3. Go for review and get approvals.
4. Close the task

**Comment by JJediny** [comment]
completed see updated readme
