### ISSUE TITLE
Task: update Publishers list for Federal Retirement Thrift Investment Board

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2969]
Update the Publishers list for Federal Retirement Thrift Investment Board on inventory.data.gov.

## Sketch
See instructions https://github.com/GSA/ckanext-dcat_usmetadata/pull/249

**Comment by jbrown-xentity** [comment]
Documentation great, task done.
![image](https://user-images.githubusercontent.com/26980513/110679920-3ee16080-8195-11eb-97df-36600a97e57d.png)
