### ISSUE TITLE
Upgrade FGDC2ISO

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2970]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.o034x9yaisv4)._

**Date of report: 2021-03-08** 
**Severity: Medium**
**Due date: 2021-06-06** 

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (N/A)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
Ideally this application can be deprecated once https://github.com/GSA/datagov-deploy/issues/2917 is done, and this work does not need to be taken on.

**Comment by FuhuXia** [comment]
The PR :point_up_2: contains good info for future tomcat upgrade task.

**Comment by adborden** [comment]
Bumped the version of Tomcat. We already monitor new versions of components, no vulnerability class issue necessary.
