### ISSUE TITLE
Duplicate datasets harvested from data.json source

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2981]
The [NIST harvest source](https://admin-catalog-next.data.gov/harvest/nist/job/6c7b6d11-ebf8-48b4-95b3-dd7a8de35422) was harvested today. The harvest system reported 553 added, no issues. This matches [the source](https://www.nist.gov/sites/default/files/data.json) of 553.

However, the [harvest page](https://admin-catalog-next.data.gov/harvest/nist) shows 780.

The [CKAN API](https://catalog.data.gov/api/action/package_search?q=organization:national-institute-of-standards-and-technology&rows=1000&sort=metadata_created%20DESC) reports that all datasets were created today, all have harvest object id's (spot check), and that there are 780.

Not sure where the discrepancy is coming from.

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by FuhuXia** [comment]
There are 227 duplicate packages created during the harvesting. For example, [a good dataset](https://catalog.data.gov/dataset/a-reference-schema-for-the-unit-manufacturing-process-information-model-13caf) and its [duplicate](https://catalog.data.gov/dataset/a-reference-schema-for-the-unit-manufacturing-process-information-model-c02a4). The duplicate has no entries in the `harvest_object` table, as a result, it has no metadata source link on the UI.

We can run some API command to remove these 227 packages.

**Comment by jbrown-xentity** [comment]
Here's the confusing part: which one do you remove? They both come from the same harvest_object_id, but one is apparently "newer" than the other. For example, [this dataset](https://catalog.data.gov/dataset/a-reference-schema-for-the-unit-manufacturing-process-information-model-c02a4) has the metadata source section on the dataset page, but [this one does not](https://catalog.data.gov/dataset/a-reference-schema-for-the-unit-manufacturing-process-information-model-13caf). I think you'll have to scan the harvest object table to know which dataset it is pointing to...

**Comment by FuhuXia** [comment]
Upon further investigation, there are total `23723` packages that has no `harvest_object` entries. That is `2%` of the total packages, so it is wide spread issue for multiple organizations and harvest sources.
```
Commerce(doc-gov) 23423
NIST(national-institute-of-standards-and-technology) 227
EPA(epa-gov) 31
Energy(doe-gov) 26
Transportation(dot-gov) 12
FEMA(fema-gov) 3
Agriculture(usda-gov) 1
```
It seems all are data.json harvest source? Maybe a bug in the `ckanext-datajson`?

**Comment by FuhuXia** [comment]
@jbrown-xentity The one without its package_id in table `harvest_object` is to be removed. Here is the query I used.

![Screen Shot 2021-03-16 at 12 25 10 PM](https://user-images.githubusercontent.com/1392461/111344598-e3124e00-8652-11eb-9c39-3b9edf221b11.png)

**Comment by jbrown-xentity** [comment]
I believe there is a bug in the JSON harvester. Some of the duplicates above have been removed, but there are still 224 in the NIST org.
The [de-dupe script assumes that the oldest dataset is the most accurate](https://github.com/GSA/datagov-dedupe/blob/main/dedupe/deduper.py#L182-L190). This is not our case, as we have 

1. [correct dataset with metadata source](https://catalog.data.gov/dataset/zeno-software-for-calculating-hydrodynamic-electrical-and-shape-properties-of-polymer-and--75dab) created at 2021-03-11T17:18:52.233488
1. [duplicate dataset without metadata source](https://catalog.data.gov/dataset/zeno-software-for-calculating-hydrodynamic-electrical-and-shape-properties-of-polymer-and--7f679) created at 2021-03-11T17:16:37.192000

Will look at locating the bug now.

**Comment by jbrown-xentity** [comment]
[This code block](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/datajson_ckan_28.py#L722-L737) smells like crazy. It basically admits that the fetch jobs may step on each other.
I would think that if there is an `Integrity Error`, aka a conflict arises, then the code should not create another dataset.

**Comment by jbrown-xentity** [comment]
Also [this block](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/datajson_ckan_28.py#L744-L748) explains why the "later" created dataset would be the one that has the harvest_object_id, as that is saved in the harvest_object and the later "run" would overwrite any previous changes.

**Comment by adborden** [comment]
> [This code block](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/datajson_ckan_28.py#L722-L737) smells like crazy. It basically admits that the fetch jobs may step on each other.
> I would think that if there is an `Integrity Error`, aka a conflict arises, then the code should not create another dataset.

I think it's fine to remove this retry logic but at least I want to point out there is a valid case for this: when two different organization's harvest jobs are running in parallel and the dataset titles are identical. That's allowed and would cause the IntegrityError. But, even without the retry it's fine to fail one of the jobs for the race condition and it should succeed on a following run.

**Comment by adborden** [comment]
... but doesn't that mean there's a second bug? Why are there two harvest objects with identical titles from the same job?

**Comment by jbrown-xentity** [comment]
Once the de-dupe PR is reviewed and merged, we will run this on the various organizations that are affected.

**Comment by FuhuXia** [comment]
My thoughts on the [dedupe process](https://github.com/GSA/datagov-dedupe/blob/main/dedupe/ckan_api.py#L114-L128):
1. same identifier is not a valid sign of duplicate datasets. Within same org, datasets with same identifiers are legit as long as they are from different harvest source.
2. CKAN harvester are good at ensuring identifier uniqueness. I haven't seen multiple datasets from one harvest source having same identifier.
3. The real duplicate dataset only happens when a dataset lost its link to harvest source. Harvester does not see it in this harvest source therefore it will harvest again on next job. That is when most duplicates happens, if not all.
4. Those datasets without harvest source info (no harvest_object_id) are erroneous for sure, since all datasets on catalog are supposed to be harvested. If we can delete them first, 99% duplicate dataset will be eliminated, if not all.

**Comment by jbrown-xentity** [comment]
While it is not perfect to evaluate identifiers across an entire org, the spec does expect that it is [consistent across the org](https://resources.data.gov/resources/dcat-us/#identifier). Most organizations only have 1 DCAT-US harvest source, so I think de-duping by org is a very small risk.
In my review, all the duplicates that are no longer linked to the harvest source table would be removed (spot checking the dry-run). Also each organization to this point has matched up with the counts posted previously in @FuhuXia 's analysis.

**Comment by FuhuXia** [comment]
Well, I guess good result can justify disreputable logic. The change of [keeping newest dataset](https://github.com/GSA/datagov-dedupe/pull/19) did the trick since it is always that old dataset lost harvest_object_id and valid dataset is later re-harvested.

**Comment by adborden** [comment]
> My thoughts on the [dedupe process](https://github.com/GSA/datagov-dedupe/blob/main/dedupe/ckan_api.py#L114-L128):
> 
> 1. same identifier is not a valid sign of duplicate datasets. Within same org, datasets with same identifiers are legit as long as they are from different harvest source.

That's an interesting case that we should be considering when we touch harvest code and tests and within the dedupe logic. But I agree with @jbrown-xentity that we should be enforcing unique identifiers within an organization.

For the dedupe logic, we might want to add some assertions that the datasets we're looking at belong to the same harvest source.

> 3. The real duplicate dataset only happens when a dataset lost its link to harvest source. Harvester does not see it in this harvest source therefore it will harvest again on next job. That is when most duplicates happens, if not all.
> 4. Those datasets without harvest source info (no harvest_object_id) are erroneous for sure, since all datasets on catalog are supposed to be harvested. If we can delete them first, 99% duplicate dataset will be eliminated, if not all.

Right, to me this is the root of the bug, how do datasets lose the link to their harvest source? And this is what needs to be fixed. Removing the duplicates doesn't fix the issue. Don't forget everything in catalog-next _was_ harvested just recently, so if some datasets are disconnected, we need to understand how that happens.

**Comment by FuhuXia** [comment]
> For the dedupe logic, we might want to add some assertions that the datasets we're looking at belong to the same harvest source.

We can't do any harvest source assertion as of now, since the API does not return harvest source info on the new catalog. When it does, we can simply delete all datasets without harvest_object_id, this logic is much more solid than looking for identifier.

> ...so if some datasets are disconnected, we need to understand how that happens.

In the NIST case, duplicate datasets happened within minutes. I think something happens during that time. Gather/Fetch log might give some clue.

**Comment by jbrown-xentity** [comment]
The de-duplication process has been run. The command to clean was `python duplicates-identifier-api.py national-institute-of-standards-and-technology --newest --commit`.
See [G-Drive for log files](https://drive.google.com/drive/u/2/folders/11DA4hZSK-HSoegaxL6md-e1_2BQ_43vq) on de-duplication run.

**Comment by FuhuXia** [comment]
[Runbook](https://github.com/GSA/datagov-deploy/wiki/catalog.data.gov#remove-duplicate-datasets) created for future task of this kind.

**Comment by FuhuXia** [comment]
Post latest duplicate dataset status affected by this bug:
![image](https://user-images.githubusercontent.com/1392461/130143982-1db627c7-826b-4f5a-82ba-470e7ea0ef6f.png)

**Comment by FuhuXia** [comment]
Noticed a negative effect by the de-dupe script. If a parent dataset was removed, its child datasets still point to the deleted dataset. New parent dataset shows 0 child in its collection.

**Comment by jbrown-xentity** [comment]
Did you run this with the `--newest` flag? It probably deleted the wrong duplicate version; should it have deleted the oldest or the newest?

**Comment by FuhuXia** [comment]
`--newest` is used. That is all correct since the de-dupe script is supposed to delete the old ones since it is the olds ones that lost linking to `harvest_object`. But when it comes to parent datasets, the negative effects becomes an issue.

**Comment by jbrown-xentity** [comment]
Initial changes made to handle collections edge case, but PR is blocked because [datagov-dedupe](https://github.com/GSA/datagov-dedupe) is archived. Blocked until that is resolved.

**Comment by jbrown-xentity** [comment]
Solved for future by implementing https://github.com/GSA/datagov-dedupe/pull/20
