### ISSUE TITLE
Federal datasets are showing non-federal banner

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2982]
New harvest sources for NIST, NCUA, have harvested but their datasets are showing non-federal banner

## How to reproduce

Go to a dataset under National Institute of Standards and Technology or National Credit Union Administration

## Expected behavior

No non-federal banner on datasets

## Actual behavior

Non-federal banner on top of dataset page

## Sketch
UI for both harvest sources are set at federal, but is it actually set to non-federal?
![NIST dataset](https://user-images.githubusercontent.com/3236989/110850751-28630400-827e-11eb-9b6f-20e5b102842d.png)
![NCUA harvest source](https://user-images.githubusercontent.com/3236989/110850782-34e75c80-827e-11eb-96df-76b5fe3a808f.png)

**Comment by jbrown-xentity** [comment]
This is a false positive. The harvest source does not control the "Non-federal" banner.
The following custom fields need to be set in the organization admin page, and the banner will be gone.
![image](https://user-images.githubusercontent.com/26980513/110853937-732a4f00-8271-11eb-87a5-9dee84f94b17.png)
@hkdctol should this be done for any other organizations?

**Comment by hkdctol** [comment]
oh, I think I knew this and forgot. I think it's just NCUA and NIST for now. Thanks.
