### ISSUE TITLE
Decommission catalog-classic RDS

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2990]
## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN the old DB is no longer needed for research purposes
  WHEN the FCS environment is examined \
  THEN all catalog-classic RDS's are removed.

## Background
Partial decommission (#2837)
catalog-next launch (GSA/datagov-ckan-multi#400)
catalog-admin decommision (https://github.com/GSA/datagov-deploy/issues/2838)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
It may be that this work is unnecessary and this is decommissioned when the account is closed.
Currently attached to May milestone, but an arbitrary date that can be moved at team's discretion.

**Comment by adborden** [comment]
Opened RITM0832173.

**Comment by mogul** [comment]
@adborden will follow up on the status of this one.

**Comment by mogul** [comment]
@adborden any progress on the RITM?

**Comment by adborden** [comment]
It was assigned to the wrong queue again. FCS is looking at it now.

**Comment by adborden** [comment]
From FCS:
> I have taken a final snapshot of datagovcatalog95.cy0fc5s0csfm.us-east-1.rds.amazonaws.com and deleted it.
