### ISSUE TITLE
Prototype Pollution / XSS

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2996]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.36sbdqzho4nt)._

https://hackerone.com/reports/1125274
https://hackerone.com/reports/1125279

**Date of report:** 2021-03-13
**Severity:** moderate
**Due date:** 2021-06-13

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by FuhuXia** [comment]
Inventory has been [upgraded to CKAN core 2.8.8](https://github.com/GSA/inventory-app/pull/323) and XSS is confirmed patched. [Catalog 2.8.8 PR](https://github.com/GSA/catalog.data.gov/pull/297) is in progress.

**Comment by adborden** [comment]
@FuhuXia can you reply to the H1 issues that this is resolved?

**Comment by FuhuXia** [comment]
Both inventory and catalog are now fixed. H1 issues are replied with Resolve comments.
