### ISSUE TITLE
Broken link takeover on www.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2997]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.1e2e11iut0bi)._

https://hackerone.com/reports/1114229

**Date of report:** 2021-03-15
**Severity:** low
**Due date:** 2021-06-15

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (https://github.com/GSA/datagov-deploy/issues/2459)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by FuhuXia** [comment]
The hyperlink that gives 404 is removed. CloufFront cached cleared. Commented on the H1 issue to mark it as resolved.
