### ISSUE TITLE
Rotate login.gov metadata for 2021

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3004]
**Date of report:** 2021-03-16
**Severity:** N/A
**Due date:** 2021-04-01

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (N/A)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

This message is intended for all partners who have a SAML integration with login.gov. OpenID Connect (OIDC) integrations are not affected.

The 2020 SAML certificates for https://idp.int.identitysandbox.gov/ and https://secure.login.gov/ each expire on April 1, 2021. In order to ensure the security of your application, you should transition to the 2021 endpoints before April 1, 2021.

Briefly:

/api/saml/metadata2020 becomes /api/saml/metadata2021
/api/saml/auth2020 becomes /api/saml/auth2021
/api/saml/logout2020 becomes /api/saml/logout2021

Please refer to our developer documentation for more details: https://developers.login.gov/saml/#annual-certificate-rotation

If you have any questions, please send an email to partners@login.gov or message us in the #login-partner-support Slack channel.

---

Data.gov documentation on login.gov https://github.com/GSA/datagov-deploy/wiki/SAML2-authentication#working-with-logingov

**Comment by mogul** [comment]
FCS done, now on to cloud.gov.

**Comment by FuhuXia** [comment]
IdP metadata were updated for all apps in production, staging, management environments in FCS,  sandbox environment in AWS, production, staging, development in cloud.gov, and local environment in docker.

SP certificates were updated with 2 years expiry date for production, staging, management environments in FCS. Other non-production SP certificates were inspected, and updated only if its expiry date is less than 2 years.

**Comment by FuhuXia** [comment]
Detailed steps for the yearly login.gov SAML certificate rotation are documented [in the wiki](https://github.com/GSA/datagov-deploy/wiki/Login.gov-SAML-certificate-rotation-steps).
