### ISSUE TITLE
Add GSA Star mark as a footer to Data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3012]
## User Story

As Data.gov PMO, we want to meet website consistency requirements for the 21st Century IDEA Act. One of the requirements is GSA star mark.

## Acceptance Criteria

- [x] GIVEN a user is on any data.gov site\
  THEN the GSA star mark is  visible in footer \
  AND clicking on GSA star mark leads user to gsa.gov home page

## Background
Based on GSA Guidelines https://docs.google.com/document/d/1E0K_LDlDqEgHKESTqHKlKN50OJAxCcl_FcKB-qLL13A/edit?usp=sharing and Strengthening our Brand guide https://drive.google.com/file/d/1Diq8aPf7Ez1L3D7iivEdCtIqCwSX-x1H/view?usp=sharing

**Comment by mogul** [comment]
Dawn is also adding a "More TTS Solutions" column to the bottom right of the search.gov footer. In the absence of any higher-level movement in the area of product portfolio marketing, I would love for us to do the same as part of "halo" branding/cross-promotion of what TTS Solutions offers. I've asked her for a screenshot.

**Comment by mogul** [comment]
This is their draft:
![image](https://user-images.githubusercontent.com/47762/111694758-87c99280-87ef-11eb-9c7b-e1afdbc2a521.png)

**Comment by hkdctol** [comment]
This work was recently completed in data.gov and catalog

**Comment by nickumia-reisys** [comment]
This was a duplicate of
- https://github.com/GSA/data.gov/issues/4247
