### ISSUE TITLE
[research: 1d] Understand how using ng-harvester would change the extension porting work, if at all

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3026]
## User Story

In order to nail down the path to Python 3, the data.gov team wants to understand if using ng-harvesters would make any extension-porting effort unnecessary.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] WHEN I look at this issue \
  THEN I see notes from a meeting with Datopian to discuss ng-harvester and extensions \
  AND the data.gov team understands whether the extension-porting work can be reduced.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
As part of the data.gov assessment, it's likely we'll need to have data.gov components using Python3 before we are granted our ATO for operating on cloud.gov. We are trying to get to grips with [the existing work identified to port extensions](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit?usp=chrome_omnibox&ouid=113395049738099785114)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
No concerns. This is strictly an architecture conjecture discussion with no direct implementation associated.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- Schedule a meeting with Andre@Datopian to catch up on ng-harvest status, and its relationship to extensions.

**Comment by hkdctol** [comment]
Tentative schedule for meeting with Datopian 10 a.m. on 3/30 at 10 a.m. EDT.

**Comment by adborden** [comment]
Notes with Datopian https://docs.google.com/document/d/1t-sT9vn0SFk1jLXa5vKp41LCUm8HyUzpJm-2CC-9yU4/edit

Next steps for this story:

- ng-harvest only depends on ckanext-harvest (at the moment). Need to identify which extensions have APIs, UI, or domain logic components that we need to keep in the ng-harvester world

Next steps for ng-harvest implementation:

- Implement Airflow and ng-harvest in cloud.gov
- WAF and WAF collections need to be implemented
- Is error reporting too painful, do we need to implement job error reporting APIs now or later?
- Consider looking at other orchestrators later, Airflow looks good enough for now. 2.0 has improved API support
- How do you clean up previous runs via API or scheduled command?
- Datopian has a few more hours to answer questions or even do some research for us.

**Comment by hkdctol** [comment]
Closing this in light of Harvester 2.0 work
