### ISSUE TITLE
Identify or alert when secrets are logged by Ansible

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3028]
## User Story

In order to ensure any secrets exposed in Ansible logs are scrubbed and handled properly, data.gov team wants to be alerted when a secret is logged by Ansible on managed hosts and the Ansible controller.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
This should address this class of vulnerabilities https://github.com/GSA/datagov-deploy/issues/3027

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
`Icebox`'ing since we're likely to be off of FCS/Ansible before the next time this is a problem.

**Comment by FuhuXia** [comment]
No longer an issue. Ansible upgraded.

**Comment by nickumia-reisys** [comment]
No more Ansible log for secrets to be exposed in
- https://github.com/GSA/data.gov/issues/3710

(Although, it seems like this issue should have been closed with @FuhuXia's comment above.)
