### ISSUE TITLE
Create a SolrCloud config set suitable for CKAN with bootstrapping code

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3030]
## User Story

In order to configure Solr as recommended by CKAN core and optimized for data.gov, data.gov wants to create a config set that can be uploaded to SolrCloud at runtime.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I have brokered a Solr service \
  AND I have set CKAN_SOLR_URL, CKAN_SOLR_USER, and CKAN_SOLR_PASSWORD environment variables \
  AND I am in a [catalog.data.gov|inventory] checkout \
  WHEN I run  `solr/migrate-solrcloud-schema` \
  AND I `curl /solr/admin/collections?action=LIST` \
  THEN I see a CKAN collection exists \
  AND I see that it is the expected version.

## Background
SolrCloud has a [ConfigSets API](https://solr.apache.org/guide/6_6/configsets-api.html#ConfigSetsAPI-upload) that allows us to upload a zipped set of configuration files at runtime.

In the SolrCloud case we must configure collections through the API. This is separate from the solrconfig.xml and the schema.xml. 

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
We haven't been able to identify any impact; the brokered SolrCloud user already has permission to use the relevant APIs.

## Sketch
- Identify the optimal configuration files from existing examples and prior research (see past GH issues).
- The ConfigSet files should be included in version control alongside the application that uses them, along with notes on how to update/rebase them.
- Implement the ConfigSet upload via the script named in the ACs.

**Comment by mogul** [comment]
@adborden can you confirm that with ConfigSets, we won't need to create a custom Solr image anymore? In other words, applications are responsible for uploading those ConfigSets if they don't exist (the same way applications manage the schema in brokered databases that they use)? Or maybe the ConfigSet is something you supply as a parameter when brokering a Solr instance...?

**Comment by adborden** [comment]
I think we chatted about this, but writing it down here too.

ConfigSets allow us to specify things like stopwords and protowords for Solr optimization, so it's not _critical_ to implement this in order to move off of our custom images, hence the Icebox.

**Comment by mogul** [comment]
Aaron has figured out to do this [over here](https://github.com/GSA/datagov-deploy/issues/2778#issuecomment-984207128)

**Comment by jbrown-xentity** [comment]
We used [this code](https://github.com/GSA/inventory-app/blob/fcs/start.sh#L24-L39) back in the day. It looks like you may be able to check the "core" or "collections" output for the "ckan" collection, and only create if not found...

For inventory, we'll need to actually create the necessary config set(s) and strip out anything that's catalog specific, may need to pair with someone who's been on the program a long time to find the extra stuff...

**Comment by mogul** [comment]
Note that the relevant environment variables that get set/used are:
- CKAN_SOLR_URL
- CKAN_SOLR_USER
- CKAN_SOLR_PASSWORD

(The ACs were lacking the CKAN_ prefix when we groomed this story yesterday.)

**Comment by robert-bryson** [comment]
Update comment: new configSet files and `migrate-solr-schema.sh` at https://github.com/GSA/catalog.data.gov/tree/feature/3030-config-sets/solr for catalog using Aaron and James' comments. I could use some guidance on how to grab those environment variables, @mogul. Can we pair on it a bit later?

**Comment by mogul** [comment]
> I could use some guidance on how to grab those environment variables, @mogul. Can we pair on it a bit later?

Sure thing.

**Comment by robert-bryson** [comment]
For the AC:
With a new collection named `a-new-collection`.
Running `$ ./migrate-solrcloud-schema.sh a-new-collection`, should respond with: 
```bash
Uploading config set...
Creating solr connection...
```
And checking the collection: 
```bash
curl --get --silent --location-trusted --user $CKAN_SOLR_USER:$CKAN_SOLR_PASSWORD \
    $CKAN_SOLR_URL/solr/admin/collections \
    --data-urlencode action=list \
    --data-urlencode wt=json | grep a-new-collection
```
should respond with JSON containing the collections including, in this case the collection `a-new-collection`.
