### ISSUE TITLE
Catalog Signal vs Noise tweaking for New Relic Alerts

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#3033]
## How to reproduce

The catalog high error rate is triggering fairly often. After some digging, it appears to be part of the release.

## Expected behavior

Release runs without triggering a NR alert.

## Actual behavior

New Relic high error alert triggers when we run a release

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
[Tweaked configuration](https://one.newrelic.com/launcher/nrai.launcher?platform[accountId]=1601367&pane=eyJuZXJkbGV0SWQiOiJhbGVydGluZy11aS1jbGFzc2ljLnBvbGljaWVzIiwibmF2IjoiUG9saWNpZXMiLCJzZWxlY3RlZEZpZWxkIjoidGhyZXNob2xkcyIsInBvbGljeUlkIjoiOTMyMDAiLCJjb25kaXRpb25JZCI6IjE3NzM0NjYwIn0&sidebars[0]=eyJuZXJkbGV0SWQiOiJucmFpLm5hdmlnYXRpb24tYmFyIiwibmF2IjoiUG9saWNpZXMifQ) to warn at 15% error rate after 5 minutes, and error alert of >1% error rate for at least 10 minutes to no longer alert on every release...

**Comment by nickumia-reisys** [comment]
The signal-to-noise ratio is an ongoing problem, but as it relates to release deployments, this doesn't exist anymore.  A few more recent issues,
- https://github.com/GSA/data.gov/issues/3833
- https://github.com/GSA/data.gov/issues/4234
- https://github.com/GSA/data.gov/issues/4047
