### ISSUE TITLE
Inventory Signal vs Noise tweaking for New Relic Alerts

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#3034]
## How to reproduce

We are getting intermittent alerting for high error rate for our inventory application. This appears to be due to the way ckan handles 403's through the werkzeug.exceptions.Forbidden.

## Expected behavior

403's do not add to the high error rate counts in New Relic.

## Actual behavior

Alerts are thrown at expected 403s.

## Sketch
Should consider redirecting to login instead of sending a 403.

**Comment by hkdctol** [comment]
Closing as we have more specific tickets on this

**Comment by nickumia-reisys** [comment]
More specific tickets being:
- https://github.com/GSA/data.gov/issues/3635
- https://github.com/GSA/data.gov/issues/4042
- https://github.com/GSA/data.gov/issues/4044
