### ISSUE TITLE
Jenkins "No space left on device"

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3041]
The jenkins server recently ran out of space, see https://github.com/GSA/datagov-deploy/issues/3037 and https://github.com/GSA/datagov-deploy/issues/3040.

Long term should probably add space for all builds

## How to reproduce

1. Trigger builds for all branches (multi-branch builds already turned on)
1. Let server disk fill up

## Expected behavior

Server has capacity (either external drive or simplified builds)

## Actual behavior

Server ran out of disk space.

## Sketch
- [ ] Format and mount the existing volumes on the hosts on `/data` and `/var/log`
- [ ] Open ticket for FCS to remove extra volumes

## Workaround
Went onto jenkins server, and cleared out all the branch builds that were not being used:

    $ cd /data/jenkins/jobs/deploy-ci-platform-mb
    $ find ./branches -mindepth 1 ! -regex '^./branches/master\(/.*\)?' -delete

However, this was only temporarily effective because Jenkins just rebuilds the missing branches each night.

**Comment by adborden** [comment]
When we open the ticket for FCS, what size should the EBS be? Do we have a sense of how much space we need for Jenkins? We currently retain the past builds for [90 days](https://github.com/GSA/datagov-deploy/blob/master/ansible/templates/jenkins_config.yml.j2#L97). We can switch this to number of builds instead of days, or we can reduce this to more like 30 days.

**Comment by jbrown-xentity** [comment]
Double check that there is an EBS attached that the jenkins system utilizes appropriately.

**Comment by adborden** [comment]
I think in my haste when the Jenkins instance was re-provisioned by FCS, I forgot to setup the EBS volumes 🤦 . There are duplicate volumes here that should be removed.

```
ubuntu@jenkins:~$ lsblk
NAME    MAJ:MIN  RM  SIZE RO TYPE MOUNTPOINT
loop0     7:0     0 32.3M  1 loop /snap/amazon-ssm-agent/2996
loop1     7:1     0 55.5M  1 loop /snap/core18/1997
loop2     7:2     0 32.3M  1 loop /snap/snapd/11107
loop3     7:3     0 55.5M  1 loop /snap/core18/1988
loop4     7:4     0 32.3M  1 loop /snap/snapd/11402
loop5     7:5     0 33.3M  1 loop /snap/amazon-ssm-agent/3552
xvda    202:0     0   16G  0 disk
└─xvda1 202:1     0   16G  0 part /
xvde    202:64    0   16G  0 disk
xvdf    202:80    0   16G  0 disk
xvdg    202:96    0  100G  0 disk
xvdz    202:6400  0  100G  0 disk
```

Should be 16G for /var/log, 100G for /data. The [instructions](https://github.com/GSA/datagov-deploy/wiki/Provisioning-new-hosts#disk-mounts) are roughly documented on the wiki. I think we should use partitions, which are not documented on the wiki.

**Comment by adborden** [comment]
Don't use this script... _but_ there's an example of using gparted to partition. You can also use it interactively https://github.com/GSA/datagov-infrastructure-live/blob/main/modules/stateful/bin/initialize-stateful.sh#L13

**Comment by jbrown-xentity** [comment]
Everything was installed properly manually. The jenkins system is running through all builds now, catching up.

**Comment by jbrown-xentity** [comment]
There was a bug, where the old `/data` and `/var/log` folders that were mapped to a drive still contained the old data. we followed advice to map the current drive onto /mnt/ and remove the old data; we now are only using 40% of the system drive and should not run out of space again (or at least for a very long time).
