### ISSUE TITLE
Conduct Accessibility Testing for Data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3050]
## User Story

In order to meet Accessibility Requirements, conduct testing on Data.gov

## Acceptance Criteria

- [x] GIVEN that Data.gov needs to meet accessibility requirements\
  AND Data.gov needs to know specific shortfalls
  THEN Data.gov has a specific list of required fixes
  

## Background
After research and selection of accessibility testing tool and completion of a testing plan, Data.gov will conduct testing

**Comment by hkdctol** [comment]
This was for the Calendar Year 2022 requirements and the work was completed

**Comment by nickumia-reisys** [comment]
Results can be found on [google drive](https://drive.google.com/drive/folders/1THQWMi1tVFh_2nj2h2rDchwa2KlF3glK) and also on the AMP Tool (which needs VPN to access).
