### ISSUE TITLE
Link to GSA Accessibility page

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3054]
## User Story

Among the requirements for having an websites,

## Acceptance Criteria

- [x] GIVEN a user goes to Data.gov\THEN there is a link to the GSA Accessibility page\
https://www.gsa.gov/website-information/accessibility-aids

## Background
See details of requirements https://digital.gov/resources/required-web-content-and-links/?=checklist

**Comment by hkdctol** [comment]
This was completed

**Comment by nickumia-reisys** [comment]
Implemented with
- https://github.com/GSA/datagov-11ty/pull/87
