### ISSUE TITLE
Enable Logging for Cloud.gov App Logs

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3062]
## User Story

In order to be able to get alerts on logs, data.gov sysadmins wants application logs on cloud.gov to be directed to New Relic.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN all application logs are sent to New Relic \
  WHEN an exception/error is logged \
  THEN New Relic receives the logs

## Background
- [Logs product](https://newrelic.com/products/logs)
- [NR Logs documentation](https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/enable-log-management-new-relic/)

New Relic Logs provides an ingest service for application logs and enables alerting on the logs which would satisfy monitoring controls using a product we already use.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
New Relic logs is already approved, no security concerns

## Sketch
- [x] Determine if fluent-bit is required, or if we can log straight from cloud.gov to NR Logs
- [x] Update [datagov-logstack](https://github.com/GSA/datagov-logstack) to use [fluent-bit with the NR plugin](https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/fluent-bit-plugin-log-forwarding/)
- [x] Add logdrain to development, staging, and prod spaces.

**Comment by adborden** [comment]
Some back of the envelope math...

Catalog gunicorn logs are rotated at 50MB for a maximum of 10 logs. The period of those 10 logs cover an average of 6 days. We estimate over a month, that's 10.55 GB of data. We're already using ~25GB of data from NR instrumentation ingestion already. Assuming catalog is our largest application in terms of log volume, between catalog, inventory, dashboard, we should still be under the 100GB free tier monthly limit. Beyond that, it would be $0.25/GB.


host | start | end | size (MB) | delta (days) | MB/day | GB/mo
-- | -- | -- | -- | -- | -- | --
catalogbweb1p.prod-ocsit.bsp.gsa.gov | 2021-03-30 7:18:13 | 2021-03-24 8:32:58 | 500 | 5.948090278 | 84.06059368 | 2.462712705
catalogbweb2p.prod-ocsit.bsp.gsa.gov | 2021-03-30 0:45:42 | 2021-03-23 23:27:42 | 500 | 6.054166667 | 82.58774948 | 2.419562973
catalogweb1p.prod-ocsit.bsp.gsa.gov | 2021-03-30 10:45:06 | 2021-03-24 21:08:38 | 500 | 5.566990741 | 89.81513052 | 2.631302652
catalogweb2p.prod-ocsit.bsp.gsa.gov | 2021-03-30 1:43:20 | 2021-03-25 3:44:30 | 500 | 4.915856481 | 101.7116757 | 2.979834248
catalogpubweb1p.prod-ocsit.bsp.gsa.gov | 2021-03-31 0:21:50 | 2021-03-09 18:43:12 | 43.42 | 21.23516204 | 2.044721859 | 0.05990396072
| |   |   |   |   |  **Total** | 10.55331654

**Comment by adborden** [comment]
Could this be used for SSB managed boundary for AU-6 (3)? Can we ship logs from AWS to NR Logs?

**Comment by adborden** [comment]
> Could this be used for SSB managed boundary for AU-6 (3)? Can we ship logs from AWS to NR Logs?

Yes, we're already running fluent-bit in SSB, we just need to add the [NR plugin](https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/fluent-bit-plugin-log-forwarding/) and configuration

**Comment by jbrown-xentity** [comment]
May need to improve server run commands to include running with gunicorn and new-relic.

**Comment by jbrown-xentity** [comment]
To note, we definitely need to have Aaron's custom log solution to ingest cloud.gov logs before sending them to New Relic.

**Comment by mogul** [comment]
The log service exists, but it's not bound consistently to the apps between staging and prod:

```
bmogilefsky@rocinante-w10:~/Documents/Code/catalog.data.gov$ cf t -s prod
API endpoint:   https://api.fr.cloud.gov
API version:    3.109.0
user:           bret.mogilefsky@gsa.gov
org:            gsa-datagov
space:          prod
bmogilefsky@rocinante-w10:~/Documents/Code/catalog.data.gov$ cf services | grep logs
logstack-space-drain-prod      user-provided                                          inventory, dashboard, catalog                                                                      
bmogilefsky@rocinante-w10:~/Documents/Code/catalog.data.gov$ cf t -s staging
API endpoint:   https://api.fr.cloud.gov
API version:    3.109.0
user:           bret.mogilefsky@gsa.gov
org:            gsa-datagov
space:          staging
bmogilefsky@rocinante-w10:~/Documents/Code/catalog.data.gov$ cf services | grep logs
logstack-space-drain-staging    user-provided                                          inventory  
```

**Comment by mogul** [comment]
More information on how that all works [over here](https://docs.cloudfoundry.org/devguide/services/log-management.html#user-provided).

**Comment by mogul** [comment]
I just [ripped out the FluentBit option](https://github.com/GSA/datagov-logstack/pull/12) because it doesn't do the filter-processing that the LogStash option already does for CF logs. However, it's easy to add the New Relic output plugin to LogStash. I will do that shortly.

**Comment by jbrown-xentity** [comment]
[Docs on New Relic plugin for LogStash](https://docs.newrelic.com/docs/logs/forward-logs/logstash-plugin-log-forwarding/)

**Comment by jbrown-xentity** [comment]
I think the https://github.com/GSA/datagov-logstack/pull/28 PR added most of the necessary fixes. However, the [actual license key wasn't implemented](https://github.com/GSA/datagov-logstack/blob/main/vars.management.yml#L19). I think this will take a small redesign to implement this properly. We can either use a secret like inventory (see [manifest](https://github.com/GSA/inventory-app/blob/main/manifest.yml#L15) and [.profile](https://github.com/GSA/inventory-app/blob/main/.profile#L42)), or we could add to the environment in a different way (removing from manifest, and [adding environment variable manually](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#env-block)), or something else I'm not thinking of.

**Comment by nickumia-reisys** [comment]
To be clear, when this is working, are we expecting to see the logs here?

![image](https://user-images.githubusercontent.com/85196563/165759754-ff20b179-003a-4d38-856e-b4534f74ee0c.png)

**Comment by nickumia-reisys** [comment]
Current Status:
- New code with NR plugin deployed to management space
- S3 log forward has issues
- NR log forward does not seem to be working

TODO:
- [x] Fix the datagov-logstack github action deploy (using wrong cf action)
- [x] Debug the S3/NR errors (or lack thereof)
- [ ] Create a manual test of NR log forward by creating a dummy docker-compose app and use NR License Key to use docker-compose logstash to forward logs and see if they show up.

**Comment by nickumia-reisys** [comment]
Current state of the app:

![image](https://user-images.githubusercontent.com/85196563/166090079-903fc7bd-fb40-4550-9eea-45114394ea5e.png)


Possible Next Steps:
- [ ] Do unit testing locally with logstash
- [ ] Try to get production logs to work

**Comment by jbrown-xentity** [comment]
That log triggered something; I think we have a different endpoint for NewRelic. Not sure how/if we can set that in the logstash new relic plugin... See https://github.com/GSA/inventory-app/blob/main/manifest.yml#L29

**Comment by nickumia-reisys** [comment]
That gave a different error,

![image](https://user-images.githubusercontent.com/85196563/166107448-1be2d653-7d4c-4688-988b-afb1f33b057e.png)

I do think the last part of this is just figuring out the right URL.

**Comment by nickumia-reisys** [comment]
And no.. specifying the rest of the generic `/log/v1` doesn't work 😕 

![image](https://user-images.githubusercontent.com/85196563/166107614-75d54cd9-86e6-4e36-99ec-35929a6d9404.png)

**Comment by nickumia-reisys** [comment]
[I maybe found it!](https://docs.newrelic.com/docs/security/security-privacy/compliance/fedramp-compliant-endpoints/#log-api) 😀

**Comment by nickumia-reisys** [comment]
No way!!

![image](https://user-images.githubusercontent.com/85196563/166107979-8e9c61f7-579e-4efa-8088-b4b7a61fdc3a.png)

P.S. No idea why NR thinks I'm PDT all the time 🙄

**Comment by nickumia-reisys** [comment]
Well.. something's broken... it sends logs for a bit and then stops.. The only way to spur it again is to ~re-push~ restart the app (with proper RAM allocation)

![image](https://user-images.githubusercontent.com/85196563/166108584-507f7ddb-e998-4b26-9430-586ebe06e9c6.png)

**Comment by nickumia-reisys** [comment]
Turns out the app is crashing,
- One factor was RAM allocation.  700M was originally allocated, it has grown to 920M.
- Another factor is unknown.  The logs are not helpful in debugging.  I wonder if it's because it has issues with the S3 output.  Will investigate.

**Comment by nickumia-reisys** [comment]
Removing the S3 output made it more stable,

![image](https://user-images.githubusercontent.com/85196563/166109405-63080935-31fd-448d-ba00-adb07d254cd4.png)

It also dropped RAM usage to 650M.

**Comment by nickumia-reisys** [comment]
It's been stable for the last 24 hours,

![image](https://user-images.githubusercontent.com/85196563/166154651-4cbf6cb1-b40c-4c48-83d1-aa90d9719d6b.png)

But we need to discuss the following,
- [ ] ~I turned off S3 output because it was erroring out.  I guess this should be a separate issue if we need to fix it.~
- [ ] ~I hardcoded the NR license key and URL, this PR would fix that,~
  - ~https://github.com/GSA/datagov-logstack/pull/39~

**Comment by mogul** [comment]
S3 output should be fixed... That export is how our logs were being shipped to GSA's SOC.

**Comment by nickumia-reisys** [comment]
NR and S3 Outputs working harmoniously,

![image](https://user-images.githubusercontent.com/85196563/166257554-8441563e-fdcc-4fcb-a34d-4d9e79f6c509.png)

- https://github.com/GSA/datagov-logstack/pull/40

**Comment by nickumia-reisys** [comment]
Summary of work completed:
- https://github.com/GSA/datagov-logstack/pull/28
- https://github.com/GSA/datagov-logstack/pull/30
- https://github.com/GSA/datagov-logstack/pull/32
- https://github.com/GSA/datagov-logstack/pull/34
- https://github.com/GSA/datagov-logstack/pull/35
- https://github.com/GSA/datagov-logstack/pull/36
- https://github.com/GSA/datagov-logstack/pull/37

- Use the correct version of the NR Log API to send logs for FedRAMP compliance. ([`https://gov-log-api.newrelic.com/log/v1`](https://docs.newrelic.com/docs/security/security-privacy/compliance/fedramp-compliant-endpoints/#log-api))

Current state of Logstack application:
- Everything about the CD works except the last step which tries to drain all of the logs from all of the apps in the `prod` and `staging` space.  This step is skipped if it's already set up.  There is an automated script that works when run manually locally.  However, in github actions, the script fails because of weird discrepancies in the file struture and/or missing dependencies.
- Logs from all of our apps are being populated in NR.
