### ISSUE TITLE
Automate Compliance configuration for SSB AWS accounts

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3064]
## User Story

In order to easily audit and manage AWS accounts for the Supplemental Service Broker, data.gov PMO wants to manage SSB AWS accounts via configuration-as-code.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I I have logged into the TTS TechPortfolio AWS jump account \
  AND I am a member of the [datagov-pmo|datagov-developers] user group
  WHEN I [AssumeRole for [SSBAdmin|SSBDev] in the [staging|production] SSB account](https://signin.aws.amazon.com/switchrole?roleName=SSBAdmin&account=ssb-staging)
  THEN I see that the upper corner says that I am acting with the intended role in the intended account.
- [x] WHEN I inspect the Terraform state for the [staging|production] SSB AWS account \
  THEN I see that SSBAdmin and SSBDev IAM roles are managed by Terraform.
- [x] WHEN I inspect the Terraform state for the [staging|production] SSB AWS account \
  THEN I see that [ssb-smtp-broker|ssb-eks-broker] accounts exist and are managed by Terraform \
  AND the accounts have the `AdministratorAccess` policy attached \
  AND the SSB broker applications use the corresponding user credentials to manage resources.

## Background
SSB has three AWS accounts, dev, staging, and production that cover the Managed Boundary. These are currently managed manually (although there might some foundational automation from the [TTS tech portfolio](https://github.com/18f/aws-admin)).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Account IAM policies should be implemented as described in the SSP. Repository access should be updated to match the SSP.

## Sketch
Mostly this takes the form of edits to https://github.com/GSA/datagov-ssb. Create policies. Assign those policies to roles, not groups, so that we can AssumeRole from the TTS jump account. 

In each target account:
- [x] Implement SSBAdmin role with policies: AdministratorAccess
- [x] Implement SSBDev role with policies: PowerUserAccess
- [x] Create a programmatic access user for the SMTP broker, with the AdministratorAccess policy attached
- [x] Create a programmatic access user for the EKS broker, with the AdministratorAccess policy attached
- [x] Pass the credentials from the programmatic access users to the appropriate SSB apps
- [x] [Require AssumeRole users to have been validated with MFA](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_configure-api-require.html#MFAProtectedAPI-cross-account-delegation)

In the TTS TechPortfolio jump account, map from the datagov users to the ssb roles:
- [x] Configure AssumeRole policy for user groups datagov-pmo and datagov-developers: 
   - datagov-pmo can assume the SSBAdmin role in the ssb-[development|staging|production] accounts
   - datagov-developers can assume the SSBDev role in the ssb-[development|staging|production] accounts
- [x] Add the appropriate user accounts to the datagov-developers and datagov-pmo groups.
- [x] Test that AssumeRole works from the jump account for all the appropriate people and roles.
- [x] Make sure there's an issue covering the cleanup necessary to remove the existing explicit users from the 3x SSB accounts.

**Comment by mogul** [comment]
I've been bashing my head against this, unable to figure out why I couldn't get Terraform to properly use the S3 backend to get the Terraform state. It turned out it's because the credentials cloud.gov supplied for the S3 bucket are invalid. After using [the sample script](https://cloud.gov/docs/services/s3/#interacting-with-your-s3-bucket-from-outside-cloudgov) to populate the requisite environment vars:
```
$ ./s3creds.sh 
Creating service key terraform-s3-key for service instance terraform-s3 as bret.mogilefsky@gsa.gov...
OK

$ aws s3 ls s3://${BUCKET_NAME}

An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.
```

I've asked the #cg-support channel for help, but it was too late in the day today for anyone to be available.

**Comment by mogul** [comment]
Resolved the Terraform credentials issue; now on to actually doing the work of this issue!

**Comment by mogul** [comment]
Blocked on waiting for the aws-admin PR to be merged, so that we can test that AssumeRole works correctly.

**Comment by mogul** [comment]
The PR was merged; now working on ensuring it works from the TTS jump account.

**Comment by mogul** [comment]
@adborden confirmed that AssumeRole works correctly today! Will sync up with him to see what's necessary before we can start using the jump account as our primary way of interacting with the accounts (and removing our explicit users).

**Comment by mogul** [comment]
I need to do some additional work to get the trusted AWS account ID out of the code.

**Comment by mogul** [comment]
Confirmed working today!
![image](https://user-images.githubusercontent.com/47762/131749195-3a24350a-31d3-407c-9ca0-20b26dc47c16.png)

**Comment by mogul** [comment]
Screenshot evidence, having now removed the humans from the accounts...

Production:
![image](https://user-images.githubusercontent.com/47762/131750526-5035ae13-b232-472a-a89a-3982460025bf.png)

Staging: 
![image](https://user-images.githubusercontent.com/47762/131750605-c5c38136-d6df-4cdd-9ea8-ac4d686c87d1.png)

Development:
![image](https://user-images.githubusercontent.com/47762/131750674-1cc70da4-118c-4ac1-bd8d-95b2faac1f0d.png)
