### ISSUE TITLE
Application restarts occasionally hit memory quota cap

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3066]
During a restart of applications, sometimes we briefly go over our quota cap and the command fails.
Example is [here](https://github.com/GSA/project-open-data-dashboard/runs/2247580710?check_suite_focus=true).
This will happen randomly, and almost always on dashboard.

## How to reproduce

Review the [restart application jobs](https://github.com/GSA/project-open-data-dashboard/actions/workflows/restart.yml), see failures

## Expected behavior

No errors, rolling restart finishes successfully

## Actual behavior

Rolling restart fails with quota error

## Sketch
We can try one of 3 things:

1. Change our timing to hopefully overlap less with rolling releases
2. Change our quota so we don't hit the limit
3. Change how often we do application restarts to limit overlap between applications

**Comment by nickumia-reisys** [comment]
Our quota has since been increased, but we are right around our limit again because of the number of additional apps that we have.  Future work would be related to
- https://github.com/GSA/data.gov/issues/3651
