### ISSUE TITLE
Enable AWS Shield Standard for ALBs used in SSB

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3079]
## User Story

In order to meet compliance requirements for SC-5: Denial of Service Protection, SSB team wants AWS Shield Standard enabled for any SSB ALBs.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I review the SSB architecture \
  THEN I am confident AWS Shield Standard protection is in effect.

## Background
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/shield_protection
- https://docs.aws.amazon.com/waf/latest/developerguide/configure-new-protection.html

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
AWS Shield Standard provides base-level DDoS protection for ALBs. There are not any settings to misconfigure.

## Sketch
- [x] ~Update PMO with expected cost estimates incurred for Shield usage.~ (Shield Standard is free)
- [x] ~Implement Shield protection via Terraform resource in https://github.com/GSA/eks-brokerpak~ (Shield Standard is automatically in effect for all ALBs without configuration.)

**Comment by mogul** [comment]
I've confirmed in every way I can that there really is no charge, and no explicit configuration needed to enable AWS Shield Standard. So there's nothing to do for AWS Shield unless/until we decide we want AWS Shield Advanced.
