### ISSUE TITLE
Update About and Privacy Policies on Data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3099]
## User Story

In order to meet USWDS, the new Data.gov site should have an updated About and Privacy Policy pages at footer.

## Acceptance Criteria
- [x] GIVEN a user goes to Data.gov\
  AND views footer \
  THEN there are updated links to an About page and Privacy Policy page that meet USWDS

## Background
See https://digital.gov/resources/required-web-content-and-links/?dg for requirements in About and Privacy Policy pages, which are among the required links for USG websites

## Sketch
- [x] Review the requirements for the About and Privacy Policy pages according to https://digital.gov/resources/required-web-content-and-links/?dg
- [x] Update current language for Data.gov website that would fall under "About" and "Privacy"
- [x] Put links to updated About and Privacy Policy pages on the new Data.gov site when it launches on cloud.gov

**Comment by hkdctol** [comment]
When updating Privacy policy, confirm that language is adequate pursuant to requirements on page 6 of  [M 03-22](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2003/m03_22.pdf)

**Comment by hkdctol** [comment]
Make sure to link to our privacy policy, or the GSA one, on all our sites--needed on resources, catalog, sdg and dashboard. See spreadsheet https://docs.google.com/spreadsheets/d/14GUVegR3Gy2jWduSyEpuwirKpwctTyvk23oY9HoYQi0/edit?usp=sharing

**Comment by hkdctol** [comment]
We made these fixes with the new home page

**Comment by nickumia-reisys** [comment]
Implemented with
- https://github.com/GSA/datagov-11ty/pull/87

(There were subsequent minor udpates, but this was the main one).
