### ISSUE TITLE
Setup Graylog2 Stack

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#31]
Pending confirmation from BSP, we will setup a Graylog2 server, presumably using Ansible. This would include ElasticSearch (since AWS ElasticSearch service only exposes HTTP endpoints and graylog2 makes backend TCP calls to ES, so we can't use AWS's service) and probably other services as well.

There is a [role](https://github.com/Graylog2/graylog-ansible-role) for this open-sourced, but this would definitely need to be modified.

**Comment by neilhunt1** [comment]
I finally got it stood up manually. Need to organize this into an ansible script...

**Comment by neilhunt1** [comment]
1. Needed more partition space on the disk so make sure you create an instance with larger than normal (I used 30GB) space
2. Install [java8 on ubuntu](http://ubuntuhandbook.org/index.php/2015/01/install-openjdk-8-ubuntu-14-04-12-04-lts/)
3. Install mongodb-server
4. Change /etc/mongodb.conf file "dbpath" entry to /mongodb and make sure that dir exists and is owned by mongodb
5. Install elasticsearch from apt.
6. Change /etc/elasticsearch/elasticsearch.yml "cluster.name" entry to "graylog"
7. Install [graylog on ubuntu](http://docs.graylog.org/en/2.0/pages/installation/operating_system_packages.html#deb-apt)
8. Open ports 9000 and 12900 on your security group
9. Add password_secret and root_password_sha2 to /etc/graylog/server/server.conf
10. Change rest_listen_uri = http://0.0.0.0:12900
11. Change rest_transport_uri = http://external-ip:12900
12. Change web_listen_uri = http://0.0.0.0:9000

**Comment by JJediny** [comment]
To be inline with GSA IT logging/monitoring we will be going with ELK Stack
