### ISSUE TITLE
Upgrade MySQL databases to AWS-supported versions

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#3100]
## User Story

In order to keep AWS support for the production and staging dashboard and wordpress instance DBs, the data.gov team wants to update the DB versions in use to versions that are supported by AWS.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I log into the AWS console \
  WHEN I look at the RDS service in the production and staging accounts \
  THEN I see no unsupported DBs listed.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
Amazon RDS for MySQL 5.5 major version is reaching end of life, and it’s recommended to upgrade to newer supported major versions. https://aws.amazon.com/blogs/database/upgrading-from-amazon-rds-for-mysql-version-5-5/

The PostgreSQL community version 9.5 will reach EOL on February 11, 2021.
https://aws.amazon.com/blogs/database/upgrading-from-amazon-rds-for-postgresql-version-9-5/

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, this only helps us keep up to date with security problems that might pop up on the DB side.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- Update MySQL databases:
Production:
dashboardrds.cy0fc5s0csfm.us-east-1.rds.amazonaws.com
5.5.46
wordpressrds.cy0fc5s0csfm.us-east-1.rds.amazonaws.com
5.5.46
Staging:
wordpressrds.cwyyxljkfrkk.us-east-1.rds.amazonaws.com
5.5.46
dashboardrds.cwyyxljkfrkk.us-east-1.rds.amazonaws.com
5.5.46

- Get rid of unused PostgreSQL databases:
Production (can probably be removed due to deprecated service):
datagov-pycsw.cy0fc5s0csfm.us-east-1.rds.amazon.com
9.5.24
Staging (can probably be removed due to deprecated service):
datagov-pycsw.cwyyxljkfrkk.us-east-1.rds.amazonaws.com
Can't connect to this db. Verify it doesn't still exist.

**Comment by mogul** [comment]
We'll check back in and see if our DBs have already been upgraded a month from now, and whether any action is warranted.

**Comment by FuhuXia** [comment]
Verified datagov-pycsw dbs on staging and production are not accessible. Assuming they are terminated.
