### ISSUE TITLE
Nessus Agent update

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#3102]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.3keamhryqg6o)._

**Date of report:**  4/11/2021
**Severity:** Medium
**Due date:** 7/11/2021

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

[Google Doc](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.3keamhryqg6o)

**Comment by adborden** [comment]
Look in our [contacts list](https://docs.google.com/spreadsheets/d/1Z9Zpr1mpx-65i_fH2VTbVofPtidpLZs5cnkO0Jz53Vc/edit#gid=0) for who to reach out to. Either the scanning team or SecOps should be able to help.

**Comment by FuhuXia** [comment]
running this command shows newer version of `nessus` agent. This issue can be closed.
```
# /opt/nessus_agent/sbin/nessusd -v
```
