### ISSUE TITLE
Inventory anomalous behavior

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#3103]
## How to reproduce

1. Description of steps to reproduce the issue.
New Relic is reporting anomalous behavior on inventory on Cloud.gov 

We detected anomalous behavior in 169.254.169.254 and /ckan.controllers.api:ApiController.action around the same time this violation opened.

[View incident](https://alerts.newrelic.com/accounts/1601367/incidents/248881683)

![Screenshot from 2021-04-14 10-43-14](https://user-images.githubusercontent.com/64213093/114748148-d98e0b80-9d0e-11eb-8e60-9911afab353c.png)
![Screenshot from 2021-04-14 10-47-08](https://user-images.githubusercontent.com/64213093/114748160-dc88fc00-9d0e-11eb-85d0-96898778b2b5.png)

## Expected behavior

Based on actual usage, the error rate should be flat.

## Actual behavior

The error rate is periodically elevated for more than 5 minutes.

## Sketch

We should look at the app logs (logs.fr.cloud.gov) and events (`cf events`) to see if anything noteworthy was happening with the app around that time.

**Comment by adborden** [comment]
Unfortunately, I think we missed the window for investigation on this one.

I can't find any reference to New Relic's anomaly detection, the slack message is the only reference we have of it. Anomalies should be displayed in this feed, but none are shown.
![Screen Shot 2021-05-17 at 2 48 58 PM](https://user-images.githubusercontent.com/509703/118562063-dd071f00-b720-11eb-8de9-ad628b8eda83.png)

I looked at logs.fr.cloud.gov for any messages containing `169.254.169.254` and there were no results on April 12th. I audited the logs for inventory prod over the 30 minutes around the error and saw nothing suspicious.

https://logs.fr.cloud.gov/app/discover#/view/428a3480-b75c-11eb-a7df-47811650f47e?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-12T16:00:00.000Z',to:'2021-04-12T16:30:00.000Z'))&_a=(columns:!('@message'),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logs-app*',key:'@cf.app',negate:!f,params:(query:inventory),type:phrase),query:(match_phrase:('@cf.app':inventory))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logs-app*',key:'@type',negate:!t,params:(query:ContainerMetric),type:phrase),query:(match_phrase:('@type':ContainerMetric))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logs-app*',key:'@cf.space',negate:!f,params:(query:prod),type:phrase),query:(match_phrase:('@cf.space':prod)))),index:'logs-app*',interval:auto,query:(language:kuery,query:''),sort:!())
