### ISSUE TITLE
[Task] Work with SecOps to enable authenticated scans

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3105]
## User Story

In order to support SecOps to perform the annual authenticated scan of Data.gov URLs, SecOps wants their ENT user added to Data.gov applications.

## Background
Monthly, SecOps performs unauthenticated scans on all data.gov URLs.

Annually, SecOps performs authenticated scans on all data.gov URLs and requires assistance from the data.gov team.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Adding SecOps user should follow normal [account management procedures](https://github.com/GSA/datagov-account-management) where possible. If procedures are not applicable or an exception is made, we will document that exception in our account management repo and compliance documentation.

## Sketch
- [x] See email with subject "Q-Data.Gov FY21 Authenticated Scanning"
- [x] Add secops user to to applications supporting authentication following our [account management process](https://github.com/GSA/datagov-account-management)
- [x] Provide list of URLs and whether or not they support authentication (static sites do not support authentication for example)
- [x] Support SecOps on how to access authenticated accounts through Login.gov or MAX.gov as applicable
- [x] Document any exceptions made from our account management process

**Comment by FuhuXia** [comment]
Email sent to SecOps to start their account set up process.

**Comment by FuhuXia** [comment]
SecOps web scan account is a machine account without PIV card, but our current login.gov authentication method requires a PIV/CAC card as 2FA. While we were exploring options to enabling logging without PIV/CAC card, SecOps offers to use one of their team member's account. Three accounts has been created on our wordpress and ckan applications. 

Just for the record, the option we were exploring include:
1. Other ways of 2FA on login.gov for example the yubikey or some Authentication Applications,
2. Create a CKAN machine account and give SecOps the API key for their scan,
3. Temporally enable CKAN native login in the configuration and disable it after the annual scan.

**Comment by FuhuXia** [comment]
SecOps developer offered to use his PIV card for the account. Task completed.
