### ISSUE TITLE
Show login banner for applications AC-8

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3109]
## User Story

In order to meet the requirements of NIST AC-8 (System Use Notification), data.gov applications should show users warnings about acceptable use and monitoring before login.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I am on inventory.data.gov \
  WHEN I click `Login` \
  THEN I see a clear warning about acceptable use and monitoring of my activity in the system.
- [x] GIVEN I am on catalog.data.gov \
  WHEN I click `Login` \
  THEN I see a clear warning about acceptable use and monitoring of my activity in the system.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

As an example of a FedRAMP-approved implementation, the cloud.gov banner looks like this:
![image](https://user-images.githubusercontent.com/47762/115066937-11c75280-9ea5-11eb-9e80-30c742e55597.png)
...and when you click "Read more details" you see...
![image](https://user-images.githubusercontent.com/47762/115066911-05db9080-9ea5-11eb-94fb-03c8b281b4c5.png)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
No actual security implications. Consistency with other implementations of AC-8 on this point is a positive signifier in terms of UX for "an official website of the US Government". 

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by adborden** [comment]
I asked [login.gov about this](https://gsa-tts.slack.com/archives/CG64NU5C7/p1618516121014600).

**Comment by mogul** [comment]
Turns out there is facility in login.gov for us to add the text ourselves!
> a partner can also set custom help text on a per-service provider basis that appears on the login page for users who come to login.gov from that specific service provider, e.g. https://ecos.fws.gov/ec
> (that should pop open a login.gov sign in page with the custom FWS message)
> we define that in the configuration for the service provider. On the Dashboard it's at the bottom of the form to create / edit an "app" / service provider
> we support different text for the sign in page (the starting point), the sign up page (to create a new account), and the forgot password page. We also support localization in Spanish and French for each one

**Comment by adborden** [comment]
> This is a U.S. General Services Administration federal government service, for official use by U.S. government employees and contractors working on U.S. government digital services.
>
> All use of data.gov may be monitored, recorded, and subject to audit, by data.gov operations staff and other federal government authorities. There is no expectation of privacy for users of this system. By continuing to use this system, you consent to your use being monitored and recorded.
>
> Unauthorized use is prohibited, and individuals found performing unauthorized activities are subject to disciplinary action including criminal prosecution.
