### ISSUE TITLE
resources.data.gov broken links

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#3113]
## How to reproduce

April 12, 2021 [resource.data.gov broken link report](https://circleci.com/api/v1.1/project/github/GSA/resources.data.gov/1193/output/107/0?file=true&allocation-id=607462e66052af45f01a2856-0-build%2F20528CF4)

- _site/about/governance/index.html
  *  External link https://github.com/GSA/resources.data.gov/blob/develop/CONTRIBUTING.md failed: 404 No error
- _site/glossary/api-analytics/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/api-analytics.html failed: 404 No error
- _site/glossary/api-documentation/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/api-documentation.html failed: 404 No error
- _site/glossary/api/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/api.html failed: 404 No error
- _site/glossary/basic-auth/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/basic-auth.html failed: 404 No error
- _site/glossary/code-library/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/code-library.html failed: 404 No error
- _site/glossary/content-api/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/content-api.html failed: 404 No error
- _site/glossary/csv/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/csv.html failed: 404 No error
- _site/glossary/csw/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/csw.html failed: 404 No error
- _site/glossary/data-asset/index.html
  *  External link https://csrc.nist.gov/glossary/term/data-asset failed: 404 No error
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/data-asset.html failed: 404 No error
- _site/glossary/data-vs.-information/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/data-vs.-information.html failed: 404 No error
- _site/glossary/database/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/database.html failed: 404 No error
- _site/glossary/dataset/index.html
  *  External link http://www.data.gov/glossary failed: 404 No error
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/dataset.html failed: 404 No error
- _site/glossary/endpoint/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/endpoint.html failed: 404 No error
- _site/glossary/error-response-code/index.html
  *  External link https://csrc.nist.gov/glossary/term/error-detection-code failed: 404 No error
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/error-response-code.html failed: 404 No error
- _site/glossary/github/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/github.html failed: 404 No error
- _site/glossary/hackathon/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/hackathon.html failed: 404 No error
- _site/glossary/information-life-cycle/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/information-life-cycle.html failed: 404 No error
- _site/glossary/information-system-life-cycle/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/information-system-life-cycle.html failed: 404 No error
- _site/glossary/information-system/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/information-system.html failed: 404 No error
- _site/glossary/json-ld/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/json-ld.html failed: 404 No error
- _site/glossary/json/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/json.html failed: 404 No error
- _site/glossary/jsonp/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/jsonp.html failed: 404 No error
- _site/glossary/machine-readable-file/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/machine-readable-file.html failed: 404 No error
- _site/glossary/metadata/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/metadata.html failed: 404 No error
- _site/glossary/oauth/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/oauth.html failed: 404 No error
- _site/glossary/ogc/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/ogc.html failed: 404 No error
- _site/glossary/open-source-software/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/open-source-software.html failed: 404 No error
- _site/glossary/open-standard/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/open-standard.html failed: 404 No error
- _site/glossary/parameter/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/parameter.html failed: 404 No error
- _site/glossary/rdf/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/rdf.html failed: 404 No error
- _site/glossary/rdfa-lite/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/rdfa-lite.html failed: 404 No error
- _site/glossary/rest/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/rest.html failed: 404 No error
- _site/glossary/rss/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/rss.html failed: 404 No error
- _site/glossary/schema/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/schema.html failed: 404 No error
- _site/glossary/sdk/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/sdk.html failed: 404 No error
- _site/glossary/service-oriented-architecture/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/service-oriented-architecture.html failed: 404 No error
- _site/glossary/soap/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/soap.html failed: 404 No error
- _site/glossary/swagger/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/swagger.html failed: 404 No error
- _site/glossary/terms-of-service/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/terms-of-service.html failed: 404 No error
- _site/glossary/tsv/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/tsv.html failed: 404 No error
- _site/glossary/unstructured-data/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/unstructured-data.html failed: 404 No error
- _site/glossary/web-service/index.html
  *  External link https://csrc.nist.gov/glossary/term/Web-Service failed: 404 No error
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/web-service.html failed: 404 No error
- _site/glossary/wsdl/index.html
  *  External link https://csrc.nist.gov/glossary/term/Web-Services-Description-Language failed: 404 No error
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/wsdl.html failed: 404 No error
- _site/glossary/xml/index.html
  *  External link https://github.com/GSA/resources.data.gov/edit/main/pages/glossary/xml.html failed: 404 No error
- _site/guidance_tags/a119/index.html
  *  External link https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A119/revised_circular_a-119_as_of_1_22.pdf failed: 403 No error
- _site/keywords/inventory-data-gov/index.html
  *  External link https://inventory.data.gov/ failed: 403 No error
- _site/licensing-resources/index.html
  *  External link http://www.whitehouse.gov/sites/default/files/docs/us_open_data_action_plan_high_value_datasets.csv failed: 403 No error
  *  External link http://www.whitehouse.gov/sites/default/files/microsites/ostp/us_open_data_action_plan.pdf failed: 403 No error
  *  External link https://bit.ly/HowToFOSS failed: 400 No error
- _site/open-licenses/index.html
  *  External link https://acquisition.gov/far/current/html/Subpart%2027_4.html failed: 404 No error
- _site/resources/data-gov-open-data-howto/index.html
  *  External link https://www.geoplatform.gov/csw-resources failed: 404 No error
- _site/resources/dcat-us-priorities/index.html
  *  External link https://www.whitehouse.gov/presidential-actions/executive-order-maintaining-american-leadership-artificial-intelligence/ failed: 403 No error
- _site/resources/dcat-us/index.html
  *  External link https://catalog.data.gov/dataset/farmers-markets-locations failed: 404 No error
  *  External link https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/assets/a11_current_year/a11_2017/app_c.pdf failed: 403 No error
- _site/resources/dot-inventory/index.html
  *  External link http://safetydata.fra.dot.gov/OfficeofSafety/default.aspx failed: 302 SSL peer certificate or SSH remote key was not OK
  *  External link https://safetydata.fra.dot.gov/MasterWebService/FRASafetyDataAPIs.aspx failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL peer certificate or SSH remote key was not OK
- _site/resources/govt-data-hubs/index.html
  *  External link http://safetydata.fra.dot.gov/ failed: 302 SSL peer certificate or SSH remote key was not OK
  *  External link http://studentaid.ed.gov/data-center failed: 403 No error
  *  External link http://www.fas.usda.gov/data failed: 302 SSL peer certificate or SSH remote key was not OK
  *  External link http://www.ssab.gov/DATA.aspx failed: 404 No error
  *  External link http://www.transtats.bts.gov/ failed: 302 SSL peer certificate or SSH remote key was not OK
  *  External link http://www.ucrdatatool.gov/ failed: 504 No error
- _site/resources/inventory-data-gov-guide/index.html
  *  External link http://inventory.data.gov/ failed: 403 No error
  *  External link http://www.httpie.org/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
  *  External link https://inventory.data.gov/dataset failed: 403 No error
- _site/resources/m-13-13-guidance/index.html
  *  External link https://www.performance.gov/CAP/CAP_goals.html failed: 404 No error
- _site/resources/open-data/index.html
  *  External link https://healthdata.gov/node/86/revisions/131/view failed: 404 No error
- _site/standards/concepts/index.html
  *  External link https://www.naics.com/naics-code-description/?code=515112 failed: got a time out (response code 0)

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by hkdctol** [comment]
We've done a few broken links updates since, and are working on another round now. Marking this old one as complete
