### ISSUE TITLE
Erroneous Harvest object ID for datasets harvested from another CKAN source

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3128]
The harvest_object_id is becoming polluted, causing issues for users trying to extract the full original metadata (Geoplatform).

The CKAN API reports mutliple harvest_object_id's in the extras field of [this FWS dataset](https://catalog.data.gov/api/3/action/package_search?rows=1&q=name:fws-critical-habitat-for-threatened-and-endangered-species-datasetd55fc). And the [dataset page](https://catalog.data.gov/dataset/fws-critical-habitat-for-threatened-and-endangered-species-datasetd55fc) shows a different id.

## How to reproduce

1. Examine the ID in the full metadata link on the [dataset page](https://catalog.data.gov/dataset/fws-critical-habitat-for-threatened-and-endangered-species-datasetd55fc)
1. Examine the harvest_object_id in the [API](https://catalog.data.gov/api/3/action/package_search?rows=1&q=name:fws-critical-habitat-for-threatened-and-endangered-species-datasetd55fc)

## Expected behavior

There is only 1 harvest_object_id in the API and in the UI, all matching

## Actual behavior

All kinds of weirdness

## Sketch
This is probably due to weird behavior around SOLR caching and the index not being updated properly.
This may be resolved by #2854, but cleanup of the data issues would need to be resolved by a re-index or some other process.

**Comment by mogul** [comment]
@adborden is going to reach out to better understand how much of a blocker this is for Geoplatform stakeholders so we can better prioritize it.

**Comment by adborden** [comment]
In our recent meeting, GP said that they were able to harvest successfully as is. Sounds like this is something to be worked on, but is not a significant blocker to them.

**Comment by chris-macdermaid** [comment]
Hi @adborden

I'm working on analyzing GP's harvesting errors.

There are about 16,000 geospatial records that don't return a harvest_object_id with a package_search or package_show. This is happening mostly with NOAA records. There are some EPA and FEMA records with this problem.

    curl  -s 'https://catalog.data.gov/api/action/package_search?fq=name:tier-ii-facilities-northern-mariana-islands-2013-us-epa-region-9' | jq -r '.result.results[0].extras[] | .key'

    curl  -s 'https://catalog.data.gov/api/action/package_show?id=tier-ii-facilities-northern-mariana-islands-2013-us-epa-region-9' | jq -r '.result.extras[] | .key'


    curl  -s 'https://catalog.data.gov/api/action/package_search?fq=name:meteorological-physical-and-time-series-data-collected-from-station-sipf1-by-florida-institute-' | jq -r '.result.results[0].extras[] | .key'

    curl  -s 'https://catalog.data.gov/api/action/package_show?id=meteorological-physical-and-time-series-data-collected-from-station-sipf1-by-florida-institute-' | jq -r '.result.extras[] | .key'

**Comment by FuhuXia** [comment]
Datasets with multiple `harvest_object_id` seem all harvested from source of another CKAN instance. The extra set of `harvest_object_id`, `harvest_source_id`, `harvest_source_title` are actually ingested from the source.

The correct behavior should be ignoring them from the source, only adding the local set, as tested with a latest `ckan 2.9` and latest `ckanext-harvest` installation. In our catalog, even with latest `ckanext-harvest`, we still observe this issue. It means somewhere we overwrite the default behavior of harvester. We should exam all harvester related extensions to see where the overwrite happens, and modify the behavior accordingly. Depending on the findings, we could either raise it upstream, or modify locally, maybe ignore `harvest_object_id`, `harvest_source_id`, `harvest_source_title` from source during fetch stage.

Further investigation is ongoing.

**Comment by FuhuXia** [comment]
The PR above should have addressed the issue. For existing datasets harvested from all ckan harvest sources, we need to do a re-harvest with force-update flag turned on.

**Comment by FuhuXia** [comment]
@chris-macdermaid The issue you described bas been analyzed and raised in [another ticket](https://github.com/GSA/datagov-deploy/issues/3403).
