### ISSUE TITLE
Terraform CI cannot connect via SSH

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3141]
When running an [apply on datagov-infrastructure-live](https://github.com/GSA/datagov-infrastructure-live/runs/2450326344?check_suite_focus=true#step:5:1218), we get an error related to SSH.

## How to reproduce

1. Re-run the apply GitHub action for datagov-infrastructure-live on provisioning any new ec2 instance

## Expected behavior

Apply completes without errors

## Actual behavior

SSH failure

## Workaround

Run Terraform directly from a workstation

## Sketch
We think related to using a container for terraform, and the library we are using to add the SSH keys may not be working (see [here](https://github.com/webfactory/ssh-agent#container-based-workflows))

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
