### ISSUE TITLE
Provide responses and artifacts for AU controls

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3150]
## User Story

In order to achieve ATO on new Data.gov, Data.gov PMO needs to provide responses to assessors on AU controls.

https://docs.google.com/spreadsheets/d/1i3IYGdXryt4isA_LgAxLRvdBOh-papQb8GAcoI7BQ6w/edit?usp=sharing

## Acceptance Criteria

- [x] GIVEN the spreadsheet at https://docs.google.com/spreadsheets/d/1i3IYGdXryt4isA_LgAxLRvdBOh-papQb8GAcoI7BQ6w/edit?usp=sharing\
  THEN all rows in AU section that are marked "open" in column R have been responded to and any artifacts uploaded to the AU folder in 
 https://drive.google.com/drive/folders/1c1AF7g8Hw6nUr2GCkGZEKEJR2pMrSgat

## Background
When uploading artifacts, name files with specific controls such as AU-02(a)(02).

**Comment by mogul** [comment]
We're going to hold off on responses here since we suspect the assessor will be updating this section with a lot of stuff removed following our last interview session. Once he uploads a new sheet, then we'll unblock this one if work is still needed, and mark Done otherwise.

**Comment by hkdctol** [comment]
The spreadsheet at https://docs.google.com/spreadsheets/d/1i3IYGdXryt4isA_LgAxLRvdBOh-papQb8GAcoI7BQ6w/edit?usp=sharing has been updated with many rows addressed from our discussion at last week's interview. I have uploaded a few artifacts and there are 7 remaining rows for response/examples and assigned to either @mogul or @adborden by row number.
