### ISSUE TITLE
[spike 5d]: Upgrade CKAN extensions to python 3

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3170]
## User Story

In order to determine if we need to carry POAMs for python 2 constrained compliance findings, data.gov wants to spend up to 5 days upgrading CKAN extensions to Python 3.

## Acceptance Criteria
- [x] GIVEN we've spent up to 5 days
  WHEN we consider the remaining work
  THEN we can confidently make a decision on resolving (or carrying POAMs for) the python 2 related compliance issues

## Background
The list of stories are all attached to the [Python 3 epic](https://github.com/gsa/datagov-ckan-multi/issues/563) with additional details in the [spreadsheet](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0).

This work will help us understand how far we are from being on a well supported version of Python.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
This spike does not include addressing any compliance findings in code. That will be addressed as Snyk and NetSparker findings come in.

## Sketch
- [x] work from the [spreadsheet](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0) based on time available.
- [x] After updating ckan to 2.9 and python 3, do the tests run successfully? Can you add matrix builds to CI to include Python 3 + ckan 2.9

**Comment by adborden** [comment]
Some resources:
- [CKAN 2.9 Changelog](https://docs.ckan.org/en/2.9/changelog.html)
- [Python 3 migration for CKAN extensions](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions)
- [Python's porting guide](https://docs.python.org/3/howto/pyporting.html)
- [2to3 automatic Python 2 to 3 conversion tool](https://docs.python.org/3/library/2to3.html)

**Comment by mogul** [comment]
Aaron's working on an issue template that provides a checklist for things to be examined, which will help us quantify the amount of actual work needed to update a given extension. He'll then try the biggest extension to see how far he can get in the timebox, which will give us a better sense of how long each of the others will take in relative terms.

**Comment by adborden** [comment]
Issue template (work in progress until this issue is closed)

---
## User Story

As a data.gov developer, I want [ckanext-ext] running with CKAN 2.9 and Python 3 so that we can move out of CKAN 2.8 and reduce our technical debt and meet compliance standards.


## Acceptance Criteria
- [ ] WHEN I view CI
  THEN I see a successful job testing the extension under CKAN 2.9
  AND I see a successful job testing the extension under CKAN 2.8
  AND I see a successful job testing the extension under the legacy test environment
- [ ] WHEN I remove the tests
  THEN I see CI fail due to test coverage being below a threshold

## Background

CKAN 2.9 extension [tracker](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0).

## Details / tasks

The goal is to support running this extension against CKAN 2.9 (Python 3) and CKAN 2.8 (Python 2) environments.
Please refer to the main CKAN documentation for [Python 3 extensions migration](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions). We're not following this guide exactly. Instead of creating a long-lived py3 branch, we should be merging often. New CI test suites don't need to required or to be fully passing in order to merge. It's only important that changes don't introduce new failures or break the existing test suites.

Below are a list of tasks. Depending on the extension's functionality, not all tasks will be actionable.

Tasks:

* [ ] Update [spreadsheet](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0) to indicate the extension upgrade is in progress
* [ ] Rename default branch -> `main`.
* [ ] Remove any CKAN 2.3 tests and functionality
  - Look for `check_ckan_version`
  - grep for '2.3'
  - See https://github.com/GSA/ckanext-datagovtheme/pull/87/commits/5968f42fe31ef3fb7b3d8c118c03d8629d471449 for additional examples
* [ ] Dependencies must be python 3 compatible (run `caniusepython3 -r requirements.txt` from within the virtualenv) and post the results to this issue ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#dependencies-must-be-python-3-compatible))
* [ ] Add **additional** [CI config](https://raw.githubusercontent.com/ckan/ckanext-harvest/master/.github/workflows/test.yml) for CKAN 2.8 and 2.9 Update CI config. These new CI jobs do not to be **required** yet ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#running-tests-for-python-2-and-3-on-travis))
  - add code coverage reporting and required threshold ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/b220d57d7ec735e9d553227243b632162e745d88))
* [ ] Update documentation with compatibility table ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#compatibility-table))
  - Features
  - "Usage" (how to use/install/configure the extension) vs "Development" (how to test etc)
  - Required extensions and dependencies
  - "Weak" dependencies or how this code interacts with other extensions
* [ ] Update/add docker-compose environment in order to run tests locally ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/files#diff-97fcd588316b223e7cc6117f27d34961cebf0d727d79c71ae6cd0a5e99688ef2))
* [ ] Update test suite ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#test-suite))
  - consider copying `tests` dir to `tests/nose` in order to preserve existing test environment ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/173eaba76a8aa43bd07cb6e27ec0da6ace374e59))
  - replace nose with pytest ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/57723d1c72b6e6a8f268b1a525f094c94eca1f74))
* [ ] Fix Python 3 issues / futurize code ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#fix-python-3-issues--futurize-code))
  - Install [future](https://pypi.org/project/future/) and run `futurize --both-stages --write ckanext`
* [ ] Import from core ckan using toolkit (`git grep -w 'paste\|pylons'` should return no imports) ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#import-from-core-ckan-using-toolkit))
* [ ] (optional) Create Mixin plugin implementations for Pylons / Flask ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#create-mixin-plugin-implementations-for-pylons--flask)) ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/41803e77612ecd8d931d3d48de9d21dccce123b3))
* [ ] Convert controllers to flask views/blueprints ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#convert-controllers-to-flask-viewsblueprints))
* [ ] Migrate Paster CLI commands to Click ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#command-line-commands))
* [ ] Migrate js and css assets to Web assets ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#web-assets-js-and-css)) ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/98698b714f8295d23d449d9d03df1044c28c4e24))
* [ ] Update templates ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#templates)) ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/f8b0ab1ed78b28ad24efa201971abc1681d8ea2b))
  - you may want to split the template for CKAN >=2.9 in order to keep templates readable while maintaining backwards compatibility
  - update resource tags to asset for Web Assets
  - update `controller='package'` -> `controller='dataset'` or `controller='resource'`
* [ ] Update [spreadsheet](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0) to indicate the extension upgrade is complete


Additional resources:
- [CKAN 2.9 Changelog](https://docs.ckan.org/en/2.9/changelog.html)
- [Python 3 migration for CKAN extensions](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions)
- [Python's porting guide](https://docs.python.org/3/howto/pyporting.html)
- [2to3 automatic Python 2 to 3 conversion tool](https://docs.python.org/3/library/2to3.html)

**Comment by adborden** [comment]
Scheduled a meeting with the team to discuss the technical details of the PR.

**Comment by mogul** [comment]
Waiting on James' return to finish the review and close out the issue.

**Comment by adborden** [comment]
I will update the existing issues with the template and call this done.

**Comment by adborden** [comment]
I've updated all the issues with this upgrade template, moving to Done.
