### ISSUE TITLE
Inventory connection error when upload large resource

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3173]
Uploading a csv file of big size (170 MB) generates an error after 12+ minutes. 

## How to reproduce

Upload a large resource file to inventory

## Expected behavior

Successful resource creation

## Actual behavior

UI gives error message: 
```
Error saving metadata
Please, check your connection or try again later. If the issue persists, contact site administrator.
```
The chrome console give error message:
```
net::ERR_CONNECTION_RESET
```
![Screen Shot 2021-04-30 at 11 51 19 AM](https://user-images.githubusercontent.com/1392461/116721955-e1ef7300-a9ab-11eb-9b3c-f8401cc9e5ba.png)

## Word-around
Transfer the file to inventory instance, upload via curl calling `resource_create` API:
```
curl -k -X  POST https://127.0.0.1/api/3/action/resource_create -H "Authorization: {API-KEY}" -F 'package_id={PACKAGE-ID}' -F 'name={CSV-FILE-NAME}' -F 'format=csv' -F 'mimetype=text/csv' -F 'fileName={CSV-FILE-NAME}' -F 'upload=@{CSV-FILE-NAME}'
```

**Comment by mogul** [comment]
Fuhu said uploading directly from the instance worked fine too, so we suspect this may be a NetScaler or other load-balancing issue.

**Comment by adborden** [comment]
Cindy tried uploading 9 CSVs recently, 6 failed. The smallest was 132.9MB, the largest was 296.7MB.

**Comment by FuhuXia** [comment]
Netscaler turns out have a **100MB** limit. It might be increased in the near future.

**Comment by FuhuXia** [comment]
The 100MB limit is caused by a unresolvable bug in Netscaler. BSP is exploring the possibility of replacing Netscaler with Nginx but no concrete date set on when it will happen.

**Comment by FuhuXia** [comment]
After inventory moved to cloud.gov, the 100MB limit is no longer there. User can upload 150MB file. But when uploading some bigger (300MB) file, same error shows up. Examining the backlog it shows

```
OSError: [Errno 28] No space left on device
```

SSH'ed into the inventory app to check disk, it shows the size of 1GB total with 300+MB free space. We can increase the size to 2G to see if the issue is resolved on cloud.gov.

```
$ cf ssh inventory
~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         1.0G  719M  306M  71% /
```

**Comment by FuhuXia** [comment]
Bumping disk_quota from 1G to 2G solved the space issue. Now we see another error when a 200MB file is uploaded. 
```
Worker with pid 236 was terminated due to signal 9
```
It is OOM. Will bump memory on production to 750MB, which will be sufficient to handle upload of 300MB in size. I don't anticipate we need to handle file bigger than that. 

Staging and development space remain at 1GB disk quota and 300MB memory.

**Comment by FuhuXia** [comment]
Need to bump 300MB list to 1GB. Saw various errors along the way but finally resolved all of them.

```
413 Request Entity Too Large
client intended to send too large body
upstream prematurely closed connection while reading response header from upstream
Worker with pid 257 was terminated due to signal 9     
OUT Exit status 137 (out of memory)
No space left on device
```
