### ISSUE TITLE
Decommission pycsw

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3182]
## User Story

In order to reduce operations and maintenance burden for a service with no users, data.gov team wants the pycsw service decommissioned.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I browse to https://catalog.data.gov/csw
  THEN I get a 404

## Background
We [announced](https://www.data.gov/meta/data-gov-to-discontinue-csw-service-on-may-1/) pycsw would be sunset on May 1st, 2021.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, this reduces the number of components that are part of the data.gov system and reduces the attack surface area. The cloud.gov SSP does not include pycsw, no update necessary.

## Sketch
We need to do a little research before we can sketch out some steps here.

**Comment by kalxas** [comment]
Sorry to hear this
