### ISSUE TITLE
Duplicate DOC records

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#3203]
## Description
There are duplicate records for the DOC harvest and additionally, NOAA is publishing the same records with the same guid. The duplicate records are not being indexed in a clear way.

## How to reproduce
Description of steps to reproduce the issue.

As an example, a search for the H00954A NOS hydrographic survey shows 4 results all with the same guid:
https://catalog.data.gov/dataset?q=%22H00954A+NOS+Hydrographic+Survey%2C+%2C+1869-12-31%22

Only one guid is being indexed. Searching for guid:"gov.noaa.nos.h00001-h02000:H00954A" returns one record:
https://catalog.data.gov/dataset?q=%22H00954A+NOS+Hydrographic+Survey%2C+%2C+1869-12-31%22

## Expected behavior

Only one of the metadata records should be in the catalog.

## Actual behavior

Multiple records are in the catalog and three don't show up in the search.

## Sketch

- Change the reporting behavior to make the situation clear to the data owner.
- Only create records for the data once.
  - We think maybe this was the case before... Did something change as of the newer CKAN version?
  - It may be because these are different organizations and different sources, which are effectively namespaces and not de-duped against each other. In other words, GUIDs are not in fact globally-unique.

**Comment by hkdctol** [comment]
This got resolved with a change in DOC data.json
