### ISSUE TITLE
Add FCC to labs.data.gov/dashboard

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3206]
## User Story

In order to reflect accurate status of federal agencies currently in catalog.data.gov, Data.gov PMO wants to add Federal Communications Commission to the dashboard.

## Acceptance Criteria

- [x] GIVEN a user goes to labs.data.gov/dashboard\
  THEN there is a row for Federal Communications Commission in the Other Agencies section

## Background
FCC has datasets on catalog.data.gov https://catalog.data.gov/organization/fcc-gov

http://opendata.fcc.gov/data.json is harvesting location

**Comment by hkdctol** [comment]
Should first step be that we ask FCC about posting at a https link?

**Comment by mogul** [comment]
Let's tell them that we will harvest from https://fcc.gov/data.json, and it's up to them to get the certificate and redirect in place.
