### ISSUE TITLE
SSRF in dashboard

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3220]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.bbzg61tvshk7)._

**Date of report:** 5/6/2021
**Severity:** Moderate
**Due date:** 8/6/2021

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
https://hackerone.com/reports/1186999

**Comment by mogul** [comment]
We're still having trouble reproducing this one locally... We've asked the reporting hacker to try to reproduce it to make sure it still exists in the live site, though we don't think we might have done anything to inadvertently.

**Comment by mogul** [comment]
Fix is live, and I've been unable to reproduce the report since then. Asked for confirmation on H1, but expect this is `Done`.
