### ISSUE TITLE
Directory Traversal by Babel < 2.9.1

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3231]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.9ewg4mfuik6m)._

https://app.snyk.io/vuln/SNYK-PYTHON-BABEL-1278589

**Date of report:** 02 May, 2021
**Severity:** Medium
**Due date:** 02 August 2021

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by jbrown-xentity** [comment]
@adborden and @FuhuXia to sync up on research status.

**Comment by adborden** [comment]
https://gsa-tts.slack.com/archives/C2N85536E/p1621274715001700

**Comment by mogul** [comment]
Verified working on development, will update PR.

**Comment by FuhuXia** [comment]
Babel 2.9.1 is live on prod.

```
root@catalogweb1p:~# /usr/lib/ckan/bin/pip show babel
Name: Babel
Version: 2.9.1
...
```

**Comment by mogul** [comment]
@FuhuXia will report that 2.9.1 is working to the upstream team.
