### ISSUE TITLE
Catalog XXE

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3245]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.jwv64j45giwt)._

**Date of report:** 2021-05-21
**Severity:** High
**Due date:** 2021-06-21

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (https://github.com/GSA/datagov-deploy/issues/3246 https://github.com/GSA/datagov-deploy/issues/3250)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by adborden** [comment]
Vulnerability class analysis has been triaged https://github.com/GSA/datagov-deploy/issues/3246

**Comment by adborden** [comment]
This does not affect FCS.

**Comment by adborden** [comment]
I'm a bit confused on this one. I was expecting that solrconfig.xml needs updating, but it already matches the solr 6.6.6 config from keitaroinc/docker-ckan. I also tried an example solrconfig.xml from the official solr 6.6.6 tarball.

**Comment by mogul** [comment]
@nickumia-reisys take a look at the `solr` subdirectory and the GitHub Action for publishing the Docker image to ghcr.io here: https://github.com/GSA/catalog.data.gov

**Comment by nickumia-reisys** [comment]
I found an issue with the Solr container where it doesn't stay alive.  Solr needs to be force started to allow the user to be root.  A **temporary** fix is available on my forked version, branch `solr-upgrade`, commit  [f9667d9](https://github.com/nickumia-reisys/catalog.data.gov/commit/f9667d97bf2c33b89f8b1d0ad5b3eeec0e1f78dd)
