### ISSUE TITLE
Add automated tests for XML External Entity (XXE) for data.gov components

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3246]
## User Story

In order to ensure that any data.gov components handling XML are not susceptible to XXE, data.gov wants automated tests to check for XXE in any data.gov components where applicable.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
This issue is to address the XXE class of vulnerabilities https://github.com/GSA/datagov-deploy/issues/3245

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
Consider any components that handle untrusted XML.
- CKAN harvesters
- Fgdc2iso (both [GSA/catalog-fgdc2iso](https://github.com/GSA/catalog-fgdc2iso) and an in https://github.com/GSA/datagov-deploy/issues/2917
- ...

**Comment by hkdctol** [comment]
Closing after team discussion
