### ISSUE TITLE
Dashboard error log CSV only offered sporadically/with broken link

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3252]
The documentation for the `Correct format (accessURL/format)` refers to an error log CSV file for more details. The link to get the CSV files appears only sometimes, and sometimes that link gives a 404.

![image.png](https://images.zenhubusercontent.com/57045ffe6caf56c9d38f5e4c/0aed1bc1-c8df-4813-a88a-2facfb7dfd56)

## How to reproduce

1. Visit https://labs.data.gov/dashboard
2. Click on the entry in column "Correct Format" on any row where it's less than 100%. (For example, [this link for USDA](https://labs.data.gov/dashboard/offices/detail/49015/2021-06-30#metrics_accessURL_format).)
3. Scroll up to view the blue area. 

## Expected behavior

There's a link to download the `full error log as CSV`, and the link goes to a valid .CSV file.
![image.png](https://images.zenhubusercontent.com/57045ffe6caf56c9d38f5e4c/b4e48ba4-f1b0-4590-b11e-8519f661f9cc)

## Actual behavior

The link is only there _sometimes_, and the conditions that influence that are not at all clear. 
![image](https://user-images.githubusercontent.com/47762/119726325-ddd93880-be25-11eb-9fb7-cfe305559448.png)

Also it's not clear if the link will ever actually get you a valid CSV file rather than a 404:
![image.png](https://images.zenhubusercontent.com/57045ffe6caf56c9d38f5e4c/46dfed3b-12a9-4256-85ab-df16aadd40d6)

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
Given how infrequently we've heard about this to date, we're `Icebox`'ing this and hoping we deprecate the Dashboard codebase before we ever get to it.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
