### ISSUE TITLE
datagov-theme bug causes dataset pages to not load

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3256]
The move to python3 support for datagov-theme CKAN extension broke support for bureau codes. This caused all dataset pages to break for DCAT-US harvested datasets. See stack trace below

```
File '/usr/lib/ckan-new/src/ckanext-qa/ckanext/qa/templates/snippets/organization.html', line 1 in top-level template code
  {% ckan_extends %}
File '/usr/lib/ckan-new/src/ckanext-datagovtheme/ckanext/datagovtheme/plugin/../templates/templates_2_8/snippets/organization.html', line 17 in top-level template code
  {% do exists.append(h.get_bureau_info(extra.value)) %}
File '/usr/lib/ckan-new/src/ckanext-datagovtheme/ckanext/datagovtheme/helpers.py', line 798 in get_bureau_info
  for row in csv.reader(io.StringIO(file_conent)):
TypeError: initial_value must be unicode or None, not str
```

## How to reproduce

1. Release catalog with latest `main` branch of `ckanext-datagov-theme`
1. Harvest data from a DCAT-US endpoint
1. Hit a dataset page

## Expected behavior

Dataset page loads normally

## Actual behavior

Dataset page gives a 404

## Sketch
Started [a fix PR](https://github.com/GSA/ckanext-datagovtheme/pull/93), still needs tests.

**Comment by adborden** [comment]
https://github.com/GSA/ckanext-datagovtheme/pull/94 has been tested in local development on catalog and loads the bureau csv just fine and logos render properly. Once merged, we need to bump ckanext-datagovtheme in GSA/catalog.data.gov.
