### ISSUE TITLE
Duplicate FEM Datasets

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#3281]
## Description of steps to reproduce the issue.

There are duplicate FEMA datasets in the catalog.

2 datasets found for "DCS Terrain Submission for Unincorporated Cowlitz County PAL, Cowlitz County WA"
https://catalog.data.gov/dataset?q=%22DCS+Terrain+Submission+for+Unincorporated+Cowlitz+County+PAL%2C+Cowlitz+County+WA%22

4 datasets found for "DIGITAL FLOOD INSURANCE RATE MAP DATABASE, SAN BENITO COUNTY, CALIFORNIA, USA"
https://catalog.data.gov/dataset?q=%22DIGITAL+FLOOD+INSURANCE+RATE+MAP+DATABASE%2C+SAN+BENITO+COUNTY%2C+CALIFORNIA%2C+USA%22

2 datasets found for "DCS Survey Submission for City of Woodland PAL, Cowlitz County, WA"
https://catalog.data.gov/dataset?q=%22DCS+Survey+Submission+for+City+of+Woodland+PAL%2C+Cowlitz+County%2C+WA%22

**Comment by mogul** [comment]
Thanks for the report, Chris. We'll investigate whether the duplicates are coming from the harvest sources or if they're somehow being created on our side.

**Comment by FuhuXia** [comment]
@chris-macdermaid 

The duplicates are from the WAF source side.

```
----------------------------------------------------------------------------------
https://hazards.fema.gov/filedownload/metadata/R10/637135-DevTopographicData.xml
https://hazards.fema.gov/filedownload/metadata/R10/637144-DevTopographicData.xml
(2 rows)

----------------------------------------------------------------------------------
https://hazards.fema.gov/filedownload/metadata/R09/1173416-PostPrelimProcessing.xml
https://hazards.fema.gov/filedownload/metadata/R09/1173424-PostPrelimProcessing.xml
https://hazards.fema.gov/filedownload/metadata/R09/1173393-PostPrelimProcessing.xml
https://hazards.fema.gov/filedownload/metadata/R09/629321-PostPrelimProcessing.xml
(4 rows)

----------------------------------------------------------------------------------
https://hazards.fema.gov/filedownload/metadata/R10/637321-PerformFieldSurvey.xml
https://hazards.fema.gov/filedownload/metadata/R10/637333-PerformFieldSurvey.xml
(2 rows)
```
