### ISSUE TITLE
Directory Listing enabled from pen test

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3283]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.3gr5dbcuk6ks)._

**Date of report:** 2021-05-26
**Severity:** Moderate
**Due date:** 2021-08-26

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by nickumia-reisys** [comment]
See https://github.com/GSA/catalog.data.gov/pull/318

**Comment by mogul** [comment]
Re-PR'd in https://github.com/GSA/catalog.data.gov/pull/319
