### ISSUE TITLE
SOLR admin UI redirect failing

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3296]
When upgrading SOLR to use angular 1.8.2 and jquery 3.6.0, the UI does not redirect appropriately on tab selection.

## How to reproduce

1. Pull up SOLR admin UI after #3284 and #3285 are complete
1. Select any tab other than `Home`
1. See no UI change

## Expected behavior

New page is shown (redirected properly)

## Actual behavior

URL adds `#%2f` into the address which needs to be removed to go to the correct tab

## Sketch
Not sure what is causing this, but is a direct result of us having to upgrade angular due to security concerns in the solr version that is supported by CKAN.

**Comment by jbrown-xentity** [comment]
Not prioritizing due to low use of SOLR admin UI. May consider upgrading SOLR instead of fixing this bug (Angular fixed in SOLR 8.5.2)

**Comment by nickumia-reisys** [comment]
With the plethora of Solr updates we have accomplished, this has been resolved without direct work.

Proof:
![solr_redirect](https://user-images.githubusercontent.com/85196563/158030389-dd4bee05-08e9-4d62-b455-44028e435d7e.gif)
