### ISSUE TITLE
Add SPF to SES service

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3301]
## User Story

In order to ensure mail sent via provisioned SES services is accepted by receivers, the SSB team wants brokered SES services to include Sender Policy Framework (SPF) records for AWS.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I have have provisioned an SES service instance \
  AND I did NOT provide a `domain` configuration during provisioning
  WHEN I check the DNS for the associated domain \
  THEN I find a valid SPF record for AWS
- [x] GIVEN I have have provisioned an SES service instance \
  AND I DID provide a `domain` configuration during provisioning
  WHEN I check the credentials for a service binding \
  THEN I see content for a SPF record for AWS \
  AND the instructions tell me to create that record in my DNS system

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
SPF: https://dmarcian.com/what-is-spf/
Truss' example: https://github.com/trussworks/terraform-aws-ses-domain/blob/2df07ab2452d65f13701e984cb3ad0caeb315aee/main.tf#L66-L85

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This change will prevent bad actors from sending mail on behalf of one of our SES services without going through AWS and having it blindly accepted by SPF-conversant hosts. It will also ensure deliverability of legitimate mail.

## Sketch
- [x] [Add the SPF record output to the provisioning spec](https://github.com/GSA/datagov-brokerpak-smtp/blob/4ffdf630a008457a2d6693b44e5e4e182031c8c3/smtp.yml#L70-L85)
- [x] Output the SPF record when a domain is supplied (in [outputs.tf](https://github.com/GSA/datagov-brokerpak-smtp/blob/main/terraform/provision/outputs.tf))
- [x] Generate the record in Route53 when no domain is supplied (in [verification.tf](https://github.com/GSA/datagov-brokerpak-smtp/blob/main/terraform/provision/verification.tf))

**Comment by mogul** [comment]
We need some kind of test to ensure we have SPF set up correctly. Here are some options:
- https://github.com/serain/mailspoof
- https://email-test.had.dnsops.gov/
- https://dmarcmonitor.net/dmarc-spf-dkim-validator/
- https://www.dmarcanalyzer.com/spf/checker/

**Comment by nickumia-reisys** [comment]
Can we create a fake SMTP server and test sending mail internally? https://www.tothenew.com/blog/setting-up-sendmail-inside-your-docker-container/

**Comment by nickumia-reisys** [comment]
All of the automated tests pretty much just check if there is a record that looks like SPF and returns true if that's met, so I implemented [a version](https://support.mailessentials.gfi.com/hc/en-us/articles/360015116520-How-to-check-and-read-a-Sender-Policy-Framework-record-for-a-domain) of that.
