### ISSUE TITLE
High CPU Usage on logstack-logstash

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3318]
The logstack-logstash CPU is continuing to spike. Please make sure to check the app functioning as expected, it is processing the expected workloads, and if you can scale the number of instances, that will help distribute the workloads.

## How to reproduce

CF Log into org `gsa-datagov` and space `management`, run
```
cf app logstack-logstash
```

## Expected behavior

reasonable CPU usage

## Actual behavior

High CPU usage
```
     state     since                  cpu      memory           disk           details
#0   running   2021-07-01T14:20:52Z   517.8%   561.4M of 576M   880.2M of 1G
```
![Screen Shot 2021-07-01 at 11 55 30 AM](https://user-images.githubusercontent.com/1392461/124160933-cb789d00-da6a-11eb-88b7-0d0832b50bdc.png)

## Sketch

- [ ] Check logs.fr.cloud.gov for unusual activity spikes or error messages
- [ ] Check for other apps that might be emitting a ton of logs all at once

**Comment by FuhuXia** [comment]
As of now, the physical memory assigned to this app is only 576M, so the JVM heap size is too small compared to recommended 4GB, which supposes to end up high CPU spike.

Here is the [Logstash reference](https://www.elastic.co/guide/en/logstash/current/performance-troubleshooting.html):
```
The recommended heap size for typical ingestion scenarios should be no less than 4GB and no more than 8GB.
...
CPU utilization can increase unnecessarily if the heap size is too low, resulting in the JVM constantly garbage collecting.
```

**Comment by hkdctol** [comment]
@FuhuXia will take a look and close if not needed.

**Comment by FuhuXia** [comment]
Did not see app `logstack-logstash` in the `management` space.  Checked in app `logstack-shipper`, its CPU usage it under control. Memory is close to 95% usage, though.
```
$ cf app logstack-shipper
...
     state     since                  cpu     memory         disk           details
#0   running   2022-10-20T21:41:57Z   16.9%   949.2M of 1G   721.6M of 2G
#1   running   2022-10-20T22:31:41Z   16.7%   965.3M of 1G   721.6M of 2G
```
