### ISSUE TITLE
Data.gov Review of Updated Metadata Guidelines for data.gov and Geoplatform

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3335]
## User Story

In order to support geospatial harvesting, Data.gov should provide edits and comments to the latest Draft Updated Metadata Guidelines for Data.gov and Geoplatform

## Acceptance Criteria

- [x] GIVEN the latest draft guidelines circulated by Lorna Schmid for an August 5 meeting,\
  THEN Data.gov team has reviewed and provided edits and comments.

## Background
Lorna Schmid recently circulated latest draft guidelines in preparation for an August 5 meeting. We should provide comments back and attend the meeting.

## Sketch
Provide any additional comments to the version attached here paying special attention to comments where Data.gov team confirmation is requested and/or there is highlighted text[https://app.zenhub.com/files/42135842/444da365-366b-4e3f-8ab7-f05de50faa43/download](https://app.zenhub.com/files/42135842/444da365-366b-4e3f-8ab7-f05de50faa43/download)

**Comment by hkdctol** [comment]
There is an updated version that requires consolidated Data.gov comments by 9/1/21. @jbrown-xentity could you look at this version and confirm/comment on the few sections that are called out for Data.gov team?[https://app.zenhub.com/files/42135842/e1750bde-4223-4f3d-a6ea-9a054546afe6/download](https://app.zenhub.com/files/42135842/e1750bde-4223-4f3d-a6ea-9a054546afe6/download)

**Comment by jbrown-xentity** [comment]
https://docs.google.com/document/d/1f1EdjbwcvKZsLIG49gtGegtmIYPJs01X/edit#

Looks done.
