### ISSUE TITLE
Collection dataset fails to load on Catalog

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3336]
Collection datasets harvested into Catalog from a data.json  fails to load. It generates a 500 Error with message 
```
Module ckanext.datagovtheme.helpers:797 in get_bureau_info
...
filename | '/var/tmp/ckan/logos/bureau.csv'
...
...
for row in csv.reader(io.StringIO(file_conent)):
...
TypeError: initial_value must be unicode or None, not str
```
## How to reproduce

Run `make clean test` on branch https://github.com/GSA/catalog.data.gov/tree/test-collection-ui

## Expected behavior

Tests pass for these [three tests](https://github.com/GSA/catalog.data.gov/commit/0332e3d228419e73c8559e2c77f43def0618dd9d).

## Actual behavior
Error as show in https://github.com/GSA/catalog.data.gov/runs/3087440641#step:4:184

![Screen Shot 2021-07-16 at 11 34 50 AM](https://user-images.githubusercontent.com/1392461/125972816-c65a2d30-c35c-4a52-ae4d-b27693f6adde.png)

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
Looks like it has to do with datagovtheme... https://github.com/GSA/catalog.data.gov/runs/3087440641#step:4:773

**Comment by jbrown-xentity** [comment]
[Current working production example](https://catalog.data.gov/dataset/purchase-card-transactions-civilian-board-of-contract-appeals-cbca-parent)

**Comment by FuhuXia** [comment]
> [Current working production example](https://catalog.data.gov/dataset/purchase-card-transactions-civilian-board-of-contract-appeals-cbca-parent)

Yeah, but it failed on local docker, I guess it failed on cloud.gov too.

**Comment by FuhuXia** [comment]
It is working on prod because FCS is using rolled-back datagovtheme https://github.com/GSA/catalog.data.gov/pull/308/files

**Comment by jbrown-xentity** [comment]
Huh, I thought we re-deployed once the fix was in place...

**Comment by FuhuXia** [comment]
You are right, it is fixed in the main branch. Issue resolved after pulling latest. https://github.com/GSA/catalog.data.gov/pull/323/commits/8d562c0e4fd73b09497e35e6f925f211635800d5

But not sure why doing a `make update-dependencies` in https://github.com/GSA/catalog.data.gov always reverts the requirement change and goes back to old `ckanext-datagovtheme` and `ckanext-datajson`.
