### ISSUE TITLE
Survey Agency User Needs re Data.gov Wordpress

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3337]
## User Story

In order to implement the transition from a WordPress to static site for Data.gov, we need to consult again with agency users.

## Acceptance Criteria

- [x] GIVEN Data.gov PMO's plan to transition from WordPress to static site\
  AND passage of time since the last time we surveyed agency users\
  THEN Data.gov PMO needs a current assessment of agency user needs going forward for posting content to Data.gov main site.

## Background
We did a similar review over a year ago when we did a site clean up, taking offline abandoned Topic pages, etc.

## Sketch
- [x] Consult with any active WordPress users outside GSA
- [x] Consult with POCs for remaining Topics
- [x] Develop basic requirements for continuing content on main Data.gov in a static site
- [x] Review records retention policies applicable to Data.gov/GSA
- [x] Add the results of this to planning documents for static site

**Comment by hkdctol** [comment]
Will move to blocked; currently awaiting responses from a few agencies on continuing need for their "Topics"

**Comment by hkdctol** [comment]
Pinged agency leads to see if they have views on old Topics content and need for posting going forward.

**Comment by hkdctol** [comment]
Pinged agencies and got some feedback from USDA.

**Comment by mogul** [comment]
@hkdctol how much longer do we want to wait before we summarize the results and close this out?

**Comment by hkdctol** [comment]
Basic requirements are here: https://docs.google.com/document/d/1DV7TX0PymWhGh6uyEsOpramF3S554tEItb0Rr0VzMmI/edit?usp=sharing

**Comment by hkdctol** [comment]
Not sure we need more than the google doc for now, we can move what's in Wordpress, and delete content that we don't need as described in the google doc.
