### ISSUE TITLE
Inventory is not responding to other requests when generating data.json

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3359]
Inventory may take a minute or two when generating data.json file if the organization has a few thousand of datasets, during which the all other web requests will wait.

## How to reproduce

1. Pick an organization with large amount of datasets on Inventory.
2. Click button "Unredacted Inventory" to download data.json.
3. While it is spinning, open another browser tab to make a request to inventory homepage.

## Expected behavior

Inventory homepage loads.

## Actual behavior

Inventory homepage wont loads until data.json is processed.

Behind a load balancer, the instance processing data.json will be considered not responding, so the 2nd homepage request might be routed to other instance. So it is better to test this on the sandbox.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
~~Resolved by rolling code back. We'll add another issue about adding a test for this scenario.~~
Comment for the wrong issue.

**Comment by mogul** [comment]
(Re-opening after the "resolve" message auto-closed.)

**Comment by FuhuXia** [comment]
"increase gunicorn timeout and add more workers" fixed the issue. It crashes inventory app on cloud.gov with workers set to 3. Changing the worker number to 2 seems to solve the problem. PR still pending, but the issue is fixed on production.

**Comment by FuhuXia** [comment]
[New PR](https://github.com/GSA/inventory-app/pull/344) merged and deployed on to cloud.gov staging and production. This ticket can be closed.
