### ISSUE TITLE
Remove defunct contact pages on www.data.gov

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3366]
We have many defunct contact pages on www.data.gov that does not work any more but consume a lot of resources to process POST requests from probing traffic. When we have a few requests like this going on simultaneously, www.data.gov server is brought down.

## Sketch
We have the main contact page https://www.data.gov/contact working.
Search in the wordpress admin dashboard, or filter thru web logs, to find all other contact pages, remove them.

**Comment by nickumia-reisys** [comment]
Superseded by
- #4141
