### ISSUE TITLE
Consolidate users and groups from datagov-iam into aws-admin

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3372]
## User Story

In order to have SSO and a consistent compliance-friendly process for managing permissions across our AWS accounts, the data.gov PMO wants to factor user and group definitions in [`datagov-iam`](https://github.com/GSA/datagov-iam) out into the aws-admin repository.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

[We just did this for the SSB](https://github.com/GSA/datagov-deploy/issues/3064). We should be applying the same process to the non-SSB data.gov account, as demonstrated in the PRs there.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- [ ] Re-specify the user groups as roles.
- [ ] Add the roles to the assumable-roles set granted to datagov-pmo and datagov-developers in aws-admin.
- [ ] Remove the existing explicit users and groups in the account.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
