### ISSUE TITLE
Testing Inventory for CKAN 2.9 under Py3

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3374]
## User Story

In order to increase confidence that we are ready to run in a Python 3 environment, the team wants to validate our applications with all their extensions under Py3.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN all relevant ckan extension is upgraded to CKAN 2.9 + PY3 \
  When the testing environment for inventory-app supports CKAN 2.9 + PY3 \
  THEN the inventory-app tests can run and pass \

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
Since they're not all consistent, we want to make sure we're using all the right branches/versions of the various extensions in inventory and catalog, and ensure they're all at least minimally working correctly in an integrated deployment.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None.

## Sketch

Any necessary changes go on main (we have no expectation to backport to CKAN 2.8/Py2)
- [x] Use the cloud.gov-provided Python buildpack (which is Py3)
- [x] If we need an integration test to validate each extension is working correctly, we add it
- [x] The local test environment is updated to use the openknowledge foundation ckan-dev image

**Comment by jbrown-xentity** [comment]
Inventory is complete ([deployment run](https://github.com/GSA/inventory-app/runs/3437777816?check_suite_focus=true)).

Catalog will be tackled in a separate ticket.
