### ISSUE TITLE
datajson_harvest does not support paginated data.json harvest source

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3379]
Some agency uses extension [ckanext-dcat](https://github.com/ckan/ckanext-dcat) to generate paginated data.json harvest source such as:
```
https://data.ca.gov/data.json
https://data.ca.gov/data.json?page=2
https://data.ca.gov/data.json?page=3
...
```
`datajson_harvest` does not have pagination feature therefore it only harvests datasets in the first page. Using `dcat_json_harvester` can harvest paginated data.json harvest source, but it does not support [DCAT-US Schema](https://resources.data.gov/resources/dcat-us/) therefore quite some fields of the harvested dataset are not being displayed on the UI. Collection datasets are not recognized by `dcat_json_harvester`.

Below shows a comparison of same dataset harvested via `datajson_harvest` and `dcat_json_harvester`:
![screencapture-catalog-data-gov-dataset-terrestrial-species-list-ace-ds2700-2021-08-16-10_08_58](https://user-images.githubusercontent.com/1392461/129585047-34014236-50b5-4e4a-870f-35258597b183.png)

![screencapture-catalog-next-sandbox-datagov-us-dataset-terrestrial-species-list-ace-ds27002-2021-08-16-11_44_52](https://user-images.githubusercontent.com/1392461/129591468-f1452b8d-1f31-4a67-8af7-a874c9dfa7c0.png)

## How to reproduce

Harvest CA data.json at https://data.ca.gov/data.json using `datajson_harvest`. 

## Expected behavior

2k+ of datasets are harvested.

## Actual behavior

500 datasets are harvested.

## Sketch
We can add paginated feature into `datajson_harvest`, or 

submit feature requests to [ckanext-dcat](https://github.com/ckan/ckanext-dcat) to support DCAT-US Schema v1.1 and Collection etc.

**Comment by FuhuXia** [comment]
CA is going to explore the possibility/effect of temporarily turning off pagination so the data.json can be harvested using `datajson_harvest`, not `dcat_json_harvester`, in favor of keeping `DCAT-US Schema` features.

**Comment by mogul** [comment]
Waiting for word back; will mark this Blocked as a reminder to check back on the status.

**Comment by mogul** [comment]
Apparently we no longer need to paginate as the partner who was encountering this issue doesn't rely on that capability anymore.
