### ISSUE TITLE
Upgrade inventory-app extension to support CKAN2.9 and Python3

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3388]
## User Story

As a data.gov developer, I want ckanext-datagov_inventory running with CKAN 2.9 and Python 3 so that we can move out of CKAN 2.8 and reduce our technical debt and meet compliance standards.

## Acceptance Criteria
- [ ] WHEN I view CI
  THEN I see a successful job testing the extension under CKAN 2.9
  AND I see a successful job testing the extension under CKAN 2.8
  AND I see a successful job testing the extension under the legacy test environment
- [ ] WHEN I remove the tests
  THEN I see CI fail due to test coverage being below a threshold

## Background

CKAN 2.9 extension [tracker](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0).

## Details / tasks

The goal is to support running this extension against CKAN 2.9 (Python 3) and CKAN 2.8 (Python 2) environments.
Please refer to the main CKAN documentation for [Python 3 extensions migration](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions). We're not following this guide exactly. Instead of creating a long-lived py3 branch, we should be merging often. New CI test suites don't need to required or to be fully passing in order to merge. It's only important that changes don't introduce new failures or break the existing test suites.

Below are a list of tasks. Depending on the extension's functionality, not all tasks will be actionable.

Tasks:

* [x] Update [spreadsheet](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0) to indicate the extension upgrade is in progress
* [x] Rename default branch -> `main`.
* [x] Remove any CKAN 2.3 tests and functionality
  - Look for `check_ckan_version`
  - grep for '2.3'
  - See https://github.com/GSA/ckanext-datagovtheme/pull/87/commits/5968f42fe31ef3fb7b3d8c118c03d8629d471449 for additional examples
* [x] Dependencies must be python 3 compatible (run `caniusepython3 -r requirements.txt` from within the virtualenv) and post the results to this issue ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#dependencies-must-be-python-3-compatible))
* [x] Add **additional** [CI config](https://raw.githubusercontent.com/ckan/ckanext-harvest/master/.github/workflows/test.yml) for CKAN 2.8 and 2.9 Update CI config. These new CI jobs do not to be **required** yet ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#running-tests-for-python-2-and-3-on-travis))
  - add code coverage reporting and required threshold ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/b220d57d7ec735e9d553227243b632162e745d88))
* [x] Update documentation with compatibility table ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#compatibility-table))
  - Features
  - "Usage" (how to use/install/configure the extension) vs "Development" (how to test etc)
  - Required extensions and dependencies
  - "Weak" dependencies or how this code interacts with other extensions
* [x] Update/add docker-compose environment in order to run tests locally ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/files#diff-97fcd588316b223e7cc6117f27d34961cebf0d727d79c71ae6cd0a5e99688ef2))
* [x] Update test suite ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#test-suite))
  - consider copying `tests` dir to `tests/nose` in order to preserve existing test environment ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/173eaba76a8aa43bd07cb6e27ec0da6ace374e59))
  - replace nose with pytest ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/57723d1c72b6e6a8f268b1a525f094c94eca1f74))
* [x] Fix Python 3 issues / futurize code ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#fix-python-3-issues--futurize-code))
  - Install [future](https://pypi.org/project/future/) and run `futurize --both-stages --write ckanext`
* [x] Import from core ckan using toolkit (`git grep -w 'paste\|pylons'` should return no imports) ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#import-from-core-ckan-using-toolkit))
* [x] (optional) Create Mixin plugin implementations for Pylons / Flask ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#create-mixin-plugin-implementations-for-pylons--flask)) ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/41803e77612ecd8d931d3d48de9d21dccce123b3))
* [x] Convert controllers to flask views/blueprints ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#convert-controllers-to-flask-viewsblueprints))
* [x] Migrate Paster CLI commands to Click ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#command-line-commands))
* [x] Migrate js and css assets to Web assets ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#web-assets-js-and-css)) ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/98698b714f8295d23d449d9d03df1044c28c4e24))
* [x] Update templates ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#templates)) ([example](https://github.com/GSA/ckanext-datagovtheme/pull/88/commits/f8b0ab1ed78b28ad24efa201971abc1681d8ea2b))
  - you may want to split the template for CKAN >=2.9 in order to keep templates readable while maintaining backwards compatibility
  - update resource tags to asset for Web Assets
  - update `controller='package'` -> `controller='dataset'` or `controller='resource'`
* [x] Update [spreadsheet](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0) to indicate the extension upgrade is complete
* [x] Re-enable commented-out tests in the inventory-app deployment

Additional resources:
- [CKAN 2.9 Changelog](https://docs.ckan.org/en/2.9/changelog.html)
- [Python 3 migration for CKAN extensions](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions)
- [Python's porting guide](https://docs.python.org/3/howto/pyporting.html)
- [2to3 automatic Python 2 to 3 conversion tool](https://docs.python.org/3/library/2to3.html)

**Comment by nickumia-reisys** [comment]
This is strange given that this is branched off of the working py3_build... 

```
~/inventory-app$ caniusepython3 -r requirements.txt
[WARNING] Skipping '-e git+https://github.com/GSA/ckanext-datajson.git@a842fa67ff8e3e9e85e80ebc3b34d3c17a38dd2f': could not parse requirement
[WARNING] Skipping '-e git+https://github.com/GSA/ckanext-googleanalyticsbasic@10ebfe25744b0f6e4cb1294f4a16654eb13119f6': could not parse requirement
[WARNING] Skipping '-e git+https://github.com/GSA/ckanext-usmetadata.git@f28f00bf255a16d59117f443949a290108344a89': could not parse requirement
[WARNING] Skipping '-e git+https://github.com/ckan/ckanext-xloader.git@c770ef16b3673c12965af2465cb23991a01850ac': could not parse requirement
[WARNING] Skipping ckan: URL-specified projects unsupported
[WARNING] Skipping ckanext-s3filestore: URL-specified projects unsupported
[WARNING] Skipping ckanext-saml2auth: URL-specified projects unsupported
Finding and checking dependencies ...
[ERROR] Failed to get external data for https://www.red-dove.com/pypi/projects/C/ckanext-dcat-usmetadata/project.json: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/nickumia/.local/lib/python3.8/site-packages/distlib/util.py", line 915, in _get_external_data
    resp = urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[WARNING] ckanext-dcat-usmetadata not found; false-negatives possible

You need 14 projects to transition to Python 3.
Of those 14 projects, 14 have no direct dependencies blocking their transition:

  ckanext-envvars
  ckantoolkit
  click
  flask
  itsdangerous
  jinja2
  json-table-schema
  lepl
  markupsafe
  messytables
  passlib
  pathtools
  shutilwhich
  werkzeug
```

```
~/inventory-app$ caniusepython3 -r requirements.in.txt
[WARNING] Skipping 'git+https://github.com/ckan/ckan.git@ckan-2.9.3': could not parse requirement
[WARNING] Skipping '-e git+https://github.com/GSA/ckanext-googleanalyticsbasic': could not parse requirement
[WARNING] Skipping '-e git+https://github.com/GSA/ckanext-usmetadata.git@main': could not parse requirement
[WARNING] Skipping '-e git+https://github.com/GSA/ckanext-datajson.git@main': could not parse requirement
[WARNING] Skipping 'git+https://github.com/keitaroinc/ckanext-saml2auth.git@main': could not parse requirement
[WARNING] Skipping 'git+https://github.com/keitaroinc/ckanext-s3filestore.git': could not parse requirement
[WARNING] Skipping '-e git+https://github.com/ckan/ckanext-xloader.git@master': could not parse requirement
[WARNING] Skipping '-r ${SRC_DIR}/ckan/requirements.txt': could not parse requirement
Finding and checking dependencies ...
[ERROR] Failed to get external data for https://www.red-dove.com/pypi/projects/C/ckanext-dcat-usmetadata/project.json: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/nickumia/.local/lib/python3.8/site-packages/distlib/util.py", line 915, in _get_external_data
    resp = urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[WARNING] ckanext-dcat-usmetadata not found; false-negatives possible

You need 5 projects to transition to Python 3.
Of those 5 projects, 4 have no direct dependencies blocking their transition:

  ckanext-envvars
  ckantoolkit
  lepl
  json-table-schema (which is blocking messytables)
```

**Comment by nickumia-reisys** [comment]
Important CKAN change: https://github.com/ckan/ckan/pull/3972
