### ISSUE TITLE
data error in catalog harvest_object table

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3403]
Some data errors in catalog harvest_object table were observed. The causes are unknown, but most likely they are due to harvest job glitches, especially when stuck harvest jobs were reset by CKAN or sysadmin.

Error 1:
**Dataset package has not current harvest object.** 
Current production has 1,296k datasets, 61k of them has no current harvest object.  These datasets have no harvest source info displayed on UI, no harvest_object_id included in  package_search API call, as describe [here](https://github.com/GSA/datagov-deploy/issues/3128#issuecomment-857777586).

Among the 61k datasets, 34k of them have previous Complete harvest objects. They were relinked by a [background process](https://github.com/GSA/datagov-deploy/pull/3470). 27k of them do not have a Complete harvest object, and are left untouched.

Error 2:
**Dataset package has multiple current harvest objects.**
200+ package_id have multiple current harvest_object. UI impack unknown.

## How to reproduce
SQL queries help to see the issues.
```
select count(package_id) from harvest_object where current;
select count(distinct(package_id)) from harvest_object where current;
select count(distinct(p.id)) from package p join harvest_object h on p.id = h.package_id where p.type='dataset' and  p.state='active' and h.current;
```

**Comment by mogul** [comment]
For this one: 

> Error 2:
> **Dataset package has multiple current harvest objects.**
> 200+ package_id have multiple current harvest_object. UI impack unknown.

We expect that moving to dcat_usmetadata for the harvest source will resolve the problem.

**Comment by mogul** [comment]
We're going to prioritize fixing this as we have geodata consumers that are affected by the errors.

**Comment by mogul** [comment]
Fuhu is verifying that we've resolved this.

**Comment by FuhuXia** [comment]
Ran the relink command manually for a few harvest sources, results verified. Before the command run, a sample dataset has no `harvest_object` info on the UI, it has erroneous `harvest_object_id` in `package_search` api response. Both are fixed after the command.

We have 61k datasets affected by the **Error 1: Dataset package has not current harvest object**. It will take 6 hours for the relink command to fix all. Once above PRs are merged, we can run it manually one time during off hours, then exam the results in next a few weeks to see how often the error re-occur, then figure out the appropriate cronjob schedule.

**Comment by FuhuXia** [comment]
Relink process finished. Out of 61k datasets to be fixed, 34k were relinked to a valid harvest object. 27k datasets have no valid harvest objects found in the DB. The log is saved to [Google Drive](https://drive.google.com/drive/folders/1rmUIR-ZO7qYtUxnxmokM-xf2wtKQWXub).

[A new issue](https://github.com/GSA/datagov-deploy/issues/3475) is created to handle the remaining datasets, or maybe a better way to replace the relink process.
