### ISSUE TITLE
Ubuntu 18.04 LTS Linux kernel vulnerability

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3409]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.aykleaaw5v0l)._

**Date of report:** 2021-07-27
**Severity:** High
**Due date:** 2021-08-26

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by FuhuXia** [comment]
Service ticket **RITM0879633** is created for FCS to update Ubuntu.

**Comment by FuhuXia** [comment]
FCS and SecOps do not handle OS update/patch. Ticket being re-routed.

**Comment by mogul** [comment]
We believe this is being detected because the packages for the kernel are still installed, not because they're still in use.

**Comment by mogul** [comment]
Here's [the Ubuntu wiki page about auto-removing old kernel packages](https://help.ubuntu.com/community/RemoveOldKernels). Note there are differences between Ubuntu versions...

**Comment by jbrown-xentity** [comment]
The noted packages have been removed. We will run a full site deployment to verify this does not come back...

**Comment by jbrown-xentity** [comment]
If needed, you can use the following commands to

confirm what is installed: `pipenv run ansible -m shell -a "sudo apt list --installed | grep bad-module-name" all`

to uninstall across all servers: `pipenv run ansible -m apt -a "name=bad-module-name-and-version state=absent force=yes" all`

**Comment by jbrown-xentity** [comment]
We confirmed that the modules are still not installed, even after full deployment and reboots. This is done.
