### ISSUE TITLE
Publish CKAN extensions on PyPI

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3414]
## User Story

In order to meet best practice industry standards for publishing and managing code releases, data.gov admins wants all CKAN extension code managed by data.gov personnel published and implemented via PyPI.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN the github actions are setup to publish to PyPI \
  WHEN a new commit is made to main on any data.gov CKAN extension repo [datajson, datagovtheme, etc) \
  THEN a new release is made on PyPI \
  AND the relevant application code can be easily upgraded via normal process

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
This was being done for dcat-usmetadata, but was lost during transition from circle-ci to github actions. Should look at any pre-made github actions for doing this, and the previous [circle-ci code](https://github.com/GSA/ckanext-dcat_usmetadata/blob/main/.circleci/config.yml#L51-L94).

**Comment by jbrown-xentity** [comment]
Here is an example of a github action: https://github.com/marketplace/actions/pypi-publish

**Comment by mogul** [comment]
We implemented this in [a PR for ckanext-dcat_usmetadata](https://github.com/GSA/ckanext-dcat_usmetadata/pull/272).

**Comment by nickumia-reisys** [comment]
## List of extenstions to complete

### Catalog.data.gov (owned) - should definitely do
- [x] [ckanext-dcat_usmetadata](https://github.com/GSA/ckanext-dcat_usmetadata)
- [x] [ckanext-googleanalyticsbasic](https://github.com/GSA/ckanext-googleanalyticsbasic.git)
- [x] [ckanext-datajson](https://github.com/GSA/ckanext-datajson.git)
- [x] [ckanext-datagovcatalog](https://github.com/GSA/ckanext-datagovcatalog.git)
- [x] [ckanext-datagovtheme](https://github.com/GSA/ckanext-datagovtheme.git)
- [x] [ckanext-geodatagov](https://github.com/GSA/ckanext-geodatagov.git)

### Catalog.data.gov (upstream) - could help upstream, needs to garner support for it
- [x] [ckanext-envvars](https://github.com/GSA/ckanext-envvars.git)
- [ ] [ckanext-dcat](https://github.com/ckan/ckanext-dcat)
- [ ] [ckanext-harvest](https://github.com/ckan/ckanext-harvest.git)
- [ ] [ckanext-saml2auth](https://github.com/keitaroinc/ckanext-saml2auth.git)

### Inventory (owned) - should definitely do
- [x] [ckanext-datajson](https://github.com/GSA/ckanext-datajson.git)
- [x] [ckanext-usmetadata](https://github.com/GSA/ckanext-usmetadata.git)

### Inventory (upstream) - could help upstream, needs to garner support for it
- [ ] [ckanext-s3filestore](https://github.com/keitaroinc/ckanext-s3filestore.git)
- [ ] [ckanext-xloader](https://github.com/ckan/ckanext-xloader.git)

**Comment by nickumia-reisys** [comment]
General Process for creating release to PyPI:
- [ ] Add PyPI API Token for each new repo to release to PyPI
  - Note 1: Initial project release requires an unrestricted API token
  - Note 2: API token can then be updated to be project-specific (after first successful upload to PyPI)
- [ ] Copy `deploy.yml` from [example](https://github.com/GSA/ckanext-googleanalyticsbasic/blob/main/.github/workflows/deploy.yml)
  - Note: Action needs to run on `pull_request` to [conditionally publish on merge](https://github.com/GSA/ckanext-envvars/pull/4/commits/e1c622003f6056274b986e8a5faf652d6c1579c0)
- [ ] Moving extension-specific requirements from `requirements.txt` to `setup.py -- install_requires`
- [ ] Leave github dependencies in `requirements.txt`
- [ ] Update `setup.py` with
  - [ ] Add `long_description` from README (if not already done)
  - [ ] Add `long_description_content_type` from README (if not already done)
  - [ ] Ensure `url` is a [valid url for PyPI](https://packaging.python.org/en/latest/specifications/core-metadata/)
  - [ ] Add `setup_requires=['wheel'],` to build release
  - [ ] Consolidate version specification if bloated ([example](https://github.com/GSA/ckanext-googleanalyticsbasic/pull/9/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L11-L15))
  - [ ] Add classifier for `'Programming Language :: Python :: 3'`
- [ ] Add PyPI Version Badge using https://badge.fury.io/for/py/
