### ISSUE TITLE
SEO loss on catalog

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3426]
Once the new catalog was released in Feb 2021, the number of page views from google decreased 70-80%. We need to investigate why this happened (ckanext-dcat misconfiguration? sitemap error? robots.txt change?) and make the necessary fixes to be indexed by Google better.

## User Story

In order to understand significant changes in Data.gov page views in Google Analytics, Data.gov PMO needs to investigate possible causes and make necessary fixes.

## Acceptance Criteria

- [ ] GIVEN the significant drops in page views that started to occur in early 2021 \
  THEN Data.gov PMO has an identified cause \
  AND has identified necessary actions to correct any errors or misconfiguration.

## Background
There has been significant drops in page views, when comparing the same month from year to year, in GA. See details at https://docs.google.com/spreadsheets/d/14zlpisixgr4_KrEwmRlWQsVk-0tE_o-5eRfGRzLNHqA/edit?usp=sharing

## Sketch
- [ ] Review numbers on Data.gov account in GA (UA-42145528)
- [ ] Correlate with events at key times, such as launch of new version of catalog (CKAN 2.8)
- [ ] Investigate causes including change in catalog URLs

**Comment by jbrown-xentity** [comment]
Could consider improving analytics, see email on 9/28/2021 at 2:23 ET. [Get a new tag](https://notifications.google.com/g/p/AD-FnEwT9MXlY2lTCC3Fl3CUY1jhtRZWGPySJmKQXi13E5yNVSTziXI2ALBbplu39gebzladh6rnzcbEM2V3Qhx0ylgT8xJNORBz3SErkNf-iVZTC0F6JDbsxv1aKZpHrTxtcEBFd-oDe9gV4gKVmL7_DLfecfrAu0siqXhP3SwqJ4LcrIEmaXz-eTuMSNNcrSfYb1wVB8q7BTBl4kY-xwxkl3rD9z3JWffiAM9Q2t_WytUpLIUcRNrVId1IfrMI9dpzzbhJTTrvGnFATRDSYyEHWkh_E2jLg6YCGRtAZXWYG_1QI_8zysBLmQogpnMwzrXsrHiEj7AZby80a-7oY77A-yAhZCxkHr9MN2HavFX5).

**Comment by hkdctol** [comment]
![Screen Shot 2021-10-05 at 5 00 48 PM](https://user-images.githubusercontent.com/3236989/136103390-5c77dac2-5c3c-4bc7-b30b-9a841228f895.png)
![Screen Shot 2021-10-05 at 5 01 48 PM](https://user-images.githubusercontent.com/3236989/136103407-226af36f-ad6f-4c93-9f9a-edc04439821d.png)
In 2020 and prior months, google was top source, and sometime in February-March 2021, google drops off significantly and top source is direct

**Comment by hkdctol** [comment]
I looked through this time period, and there was not an obvious drop off point in the switching places between google and direct. For instance it did not appear tied to the launch of the new catalog (2/5/21)

**Comment by hkdctol** [comment]
There's also an email today about GA 4: https://analytics.google.com/analytics/web/?utm_campaign=2021-q4-gbl-all-gafree&utm_source=google-growth&utm_medium=email&utm_content=ga4-sot-ga4-setup-assistant-nonadv#/a42542568w72309185p0/admin/ga4-setup-assistant

**Comment by hkdctol** [comment]
The switch seems to have happened in mid-February 2021

![Screen Shot 2021-10-19 at 4.05.50 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/cc053a02-1ffe-459d-a218-038500387864)![Screen Shot 2021-10-19 at 4.05.30 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/19006c8a-3d6f-4c19-815a-83fa74296224)

**Comment by hkdctol** [comment]
Situation remains the same in recent analytics view:
![Screen Shot 2022-01-04 at 6.33.12 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/97365bc0-72b2-492d-bd6e-40616c81312e)

**Comment by hkdctol** [comment]
Searching for some popular datasets, such as GSA federal real property, or GSA per diem, the GSA pages appear at top of search results, catalog.data.gov version not found until second page for the real property dataset, and not found at all for per diem.

**Comment by hkdctol** [comment]
Everyone on the team should have access to Google Search Console now for data.gov. There's a good DAP training on GSC at  https://www.youtube.com/watch?v=uuP0FAHOrz8&list=PLd9b-GuOJ3nEz1NYl66orgVZIu17laKba&index=48

**Comment by hkdctol** [comment]
The training points out parts of Google Search Console to check for things that might prevent Google indexing![Screen Shot 2022-01-10 at 11.26.19 AM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/2189e930-ced0-413a-a3f6-560e3a055121)

**Comment by hkdctol** [comment]
The training also emphasized submitting a sitemap in Google Search Console.

**Comment by hkdctol** [comment]
A month by month comparison is in this [doc](https://docs.google.com/spreadsheets/d/14zlpisixgr4_KrEwmRlWQsVk-0tE_o-5eRfGRzLNHqA/edit?usp=sharing)

**Comment by jbrown-xentity** [comment]
With recent sitemap publishing, we hope that this trends upward soon. If not, we should consider finding expert help in guiding how to improve SEO, not investigate how/what we broke. In the case of long term improvements, this should be considered an epic where details would need to be filled in during some type of planning session.

**Comment by hkdctol** [comment]
So far (January 2023), google as referral being low has not changed 

![Image](https://user-images.githubusercontent.com/3236989/216179864-8f18a8b6-0d2a-4d41-ba22-976d5d007f71.png)

**Comment by hkdctol** [comment]
We'll close this once we've created all the other new ones.

**Comment by hkdctol** [comment]
I think we're clear now on where we are on newly created GA4 account after our meeting today

**Comment by btylerburton** [comment]
Currently https://github.com/ckan/ckanext-googleanalytics only supports piping to a single account. We should be able to fork the repo and add support for multiple accounts.
