### ISSUE TITLE
Catalog Map Search stops working

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3434]
After some recent [catalog update](https://github.com/GSA/catalog.data.gov/pull/335), map search on the landing `/dataset` page stops working. Map is not loading.

## How to reproduce

1. Description of steps to reproduce the issue.
Go to https://catalog.data.gov/dataset

## Expected behavior
Map loads as illustrated below:

![Screen Shot 2021-02-22 at 2 18 49 PM](https://user-images.githubusercontent.com/1392461/133675734-7652a17a-5402-43f8-bd78-379c43040fc4.png)

## Actual behavior
Empty map: 
![image](https://user-images.githubusercontent.com/1392461/133675786-2a5436b3-c0d1-459e-a202-583b3ca57fa3.png)

## Sketch
- [x]  Which change in [the PR](https://github.com/GSA/catalog.data.gov/pull/335) broken this function?
- [x] Add test in integration tests to ensure map search function is working. (part of story https://github.com/GSA/datagov-deploy/issues/3491)

**Comment by jbrown-xentity** [comment]
After pairing, we think the issue has to do with [this code change](https://github.com/GSA/ckanext-datagovtheme/compare/704c45921a9246fd6072ea99711992e57d3bc416...29d7454afd516b63cdabb41e7b1dfd4f69daffd4#diff-5a4bd3c7ecad7a80664ea601370a0d39ca18a2eef34716f67aac0943ab115108). We're going to follow the following steps to try to rectify it:

1.  Use catalog.data.gov repo, the `fcs` branch, to test
2.  Clone ckanext-datagovtheme into the `src` folder of catalog repo
3. Make desired changes (remove setTimeout)
4. Run `make clean build up`
5. Validate map working (iterate if necessary)
6. Make PR of changes to ckanext-datagovtheme
7. Once ^^ is merged, update catalog.data.gov `fcs` branch with latest ckanext-datagovtheme version (use `make update-dependencies` or something

**Comment by mogul** [comment]
@jbrown-xentity and Neeraja will be putting in some pairing time on this later today.

**Comment by jbrown-xentity** [comment]
The [ckanext-datagovtheme PR](https://github.com/GSA/ckanext-datagovtheme/pull/106) is ready for review, once merged we can pull latest into [catalog PR](https://github.com/GSA/catalog.data.gov/pull/363) and merge (tests are done and working as expected).

**Comment by robert-bryson** [comment]
I just merged it, @jbrown-xentity. Sorry about the delay.
