### ISSUE TITLE
[Task] Renew certificate for https://sdg.data.gov/

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3454]
This may be handled automatically by Federalist, but not sure.

**Date of report: 9/27/2021** 
**Severity: Medium**
**Due date: 11/4/2021** 

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by mogul** [comment]
We believe this is handled automatically by Federalist. I'll confirm that before we close this.

**Comment by mogul** [comment]
Confirmed!
