### ISSUE TITLE
Error when using site-wide search

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3477]
When searching the catalog, there is an option to "Show results in entire Data.gov site"

## How to reproduce

1. Go to catalog.data.gov
2. Enter a search term
3. In the results screen, click on "Show results in entire Data.gov site"

## Expected behavior

Search results of overall Data.gov site

## Actual behavior
Page unavailable result

![Screen Shot 2021-10-12 at 10.23.27 AM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/f9debd62-c493-4acd-99f6-686741375278)![Screen Shot 2021-10-12 at 10.23.33 AM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/a10bab31-dcad-423a-b5fe-bdc6e139a764)

**Comment by jbrown-xentity** [comment]
I don't believe the static site will have this functionality, we should probably consider just removing this functionality and funneling all search into catalog...

**Comment by FuhuXia** [comment]
Static site can use service like https://search.gov/ for the site search.

**Comment by mogul** [comment]
Confirming... I set up search.gov on the cloud.gov static site in about an hour back in the day!

**Comment by jbrown-xentity** [comment]
Won't fix, will implement different similar features on next iteration of catalog and static site.
