### ISSUE TITLE
harvesting report email stopped

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3480]
catalog [harvesting report emails](https://mail.google.com/mail/#search/subject%3A%22CKAN+-+Harvesting+Job+%22) stopped, last one was received on `Oct 5, 2021, 5:39 PM` GMT.

**Possible cause:**
Last change for catalog.data.gov app was https://github.com/GSA/catalog.data.gov/pull/355, within which some extensions were updated, including `ckanext-geodatagov`, `ckanext-harvest`, and `ckanext-report`. It was deployed on `Oct 5, 2021, 6:02 PM` GMT.

**Comment by jbrown-xentity** [comment]
Opened issue upstream, with a PR to fix it: https://github.com/ckan/ckanext-harvest/issues/469

**Comment by FuhuXia** [comment]
Email is back after the PR merge.

**Comment by FuhuXia** [comment]
[Upstream PR](https://github.com/ckan/ckanext-harvest/pull/470) got merged as well. It is OK to un-pin the requirements and switch back to ckanext-harvest upstream master branch .
