### ISSUE TITLE
harvest job page fails to load

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3484]
harvest job page fails to load. It give a 500 error. This usually happens to the harvest source that has  the Update Frequency set as `Daily`.

## How to reproduce
For example:
https://admin-catalog-next.data.gov/harvest/usda-json/job

## Expected behavior

Page load with list of jobs shown.

## Actual behavior

500 Error.
In the log it shows error  as `[CRITICAL] WORKER TIMEOUT`

## Sketch
1. Increase timeout value, or
2. Paginate the harvest job list. Should be an upstream feature request.

**Comment by jbrown-xentity** [comment]
We should definitely paginate long term...

**Comment by jbrown-xentity** [comment]
This issue might already exist upstream, but we might need to make the PR...

**Comment by FuhuXia** [comment]
Upstream issue created https://github.com/ckan/ckanext-harvest/issues/468

**Comment by nickumia-reisys** [comment]
Does the upstream fix of clearing everything except the current jobs not work for us? @jbrown-xentity @FuhuXia 
- https://github.com/ckan/ckanext-harvest/pull/484

**Comment by jbrown-xentity** [comment]
I think this is an interesting option. We would want to make sure any users are made aware of the change, so they don't get confused/concerned when harvest jobs are removed. But I think especially for daily sources, this would be a good option to keep things clean. So we may want to run this on the whole system, or just on [the daily harvest sources](https://catalog.data.gov/api/action/package_search?fq=dataset_type:harvest%20AND%20frequency:DAILY) or the [weekly](https://catalog.data.gov/api/action/package_search?fq=dataset_type:harvest%20AND%20frequency:WEEKLY).

**Comment by nickumia-reisys** [comment]
Example of how to query for source ids of a frequency type:

```bash
curl -sL https://catalog-dev-admin-datagov.app.cloud.gov/api/action/harvest_source_list | jq -r '.result[] |
 select(.frequency=="WEEKLY") | .id'
```

![image](https://user-images.githubusercontent.com/85196563/193631781-ea7f275c-a8f1-495c-ba22-7216c31499d9.png)

![image](https://user-images.githubusercontent.com/85196563/193631742-50ef5e5e-4555-40a9-bdac-d0e5c114ab7a.png)

![image](https://user-images.githubusercontent.com/85196563/193631833-102c2dec-0e67-4db4-96cb-12df6e5e8a79.png)

**Comment by FuhuXia** [comment]
Too extreme to remove all job history. We want some job history, if not all.
Latest 20?

**Comment by nickumia-reisys** [comment]
This is how they clear the history.  If we wanted to write a custom function that does everything except the last `n` items, or something similar, this would be the place to do it.  Adding a parameter or something.
- https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/logic/action/update.py#L344-L419

**Comment by hkdctol** [comment]
Consider which approach most likely to be accepted upstream. Pagination is probably most likely.

**Comment by jbrown-xentity** [comment]
Currently the GSA harvest page loads after 8.5 seconds, with 519 jobs (all on one page). We can revisit this if it becomes a problem in the future.

**Comment by nickumia-reisys** [comment]
@FuhuXia did a manual DB fix that sped up the existing process, making this issue less critical.  Moving back to the Product Backlog.
- https://github.com/GSA/data.gov/issues/4000#issuecomment-1273733336

**Comment by hkdctol** [comment]
This is in acceptable status for now.
