### ISSUE TITLE
Dynamic content not updating on data.gov static site

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3486]
On the data.gov wordpress site, there are Twitter and StackExchange feeds that are are supposed to update dynamically: 
![image.png](https://images.zenhubusercontent.com/615477f9d57459b3cbe8ae7a/93573aaf-e98d-42f1-928c-5084df56d559)
As well as the current running number of datasets available: 
![image.png](https://images.zenhubusercontent.com/615477f9d57459b3cbe8ae7a/2f633d22-d951-4da2-86db-d478b0d1aeda)

[https://www.data.gov/contact](https://www.data.gov/contact)
![image.png](https://images.zenhubusercontent.com/615477f9d57459b3cbe8ae7a/e2f24641-c3ac-4de9-952c-0dc862e17683)

When crawling the site to create a static version to be run on Federalist, this content is frozen and no longer dynamically updated. 

## How to reproduce

1. Look at any page with dynamic content on the data.gov static site and see the old feed items. 

## Expected behavior

Up to date content

## Actual behavior

Out of date content

## Sketch

The fix for this will either need to be: 
- Find a way of keeping the static site up to date (or running frontend code on it to do so)
- Removing the out of date content blocks
- Accepting the stale content for the meantime

**Comment by nickumia-reisys** [comment]
New content and design options will follow after,
- https://github.com/GSA/data.gov/issues/4029
- https://github.com/GSA/data.gov/issues/4141
