### ISSUE TITLE
Finalize 404s and bad links in data.gov static site crawl

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3487]
When crawling the data.gov static site, most pages were cleanly recovered and converted to local links, however many files were saved with strange file names (versioning info caught as file names) and many HTML files referenced literal https://www.data.gov/ resources instead of local http://localhost:8000/ or Federalist-hosted https://federalist-a1176d2b-cb31-49a0-ba20-a47542ee2ec5.app.cloud.gov/preview/gsa/datagov-website/ resources. 

## How to reproduce

Browse a local or Federalist version of the data.gov static site and note pages that do not load or have issues. The Network tab on the browser DevTools is handy.

## Expected behavior

All pages working correctly on a local version. 

## Actual behavior

Most pages working correctly on a local version. 

## Sketch

- Identity ongoing failing links or misnamed files
- Fix as appropriate (probably with grep/find/regexes)
- ?

**Comment by mogul** [comment]
@robert-bryson is going to add a list of links known to be bad so we have some test cases to investigate.

**Comment by robert-bryson** [comment]
I was thinking about this over the weekend and wanted to be able to better organize this repo. I like the pattern of using `Makefiles` in other repos so I implemented that here. 

To do that, I needed a way to move the static site files into their own directory structure and after [reaching out to Federalist support](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1636386853003500), they pointed me in the direction of the docs for [using a monorepo](https://federalist.18f.gov/documentation/monorepos-on-federalist/). I set that up and switched the build engine to `nodejs` and now have that working. 

From here, I will be able to add statements to the `Makefile` to enable quick reproduction of this whole process.

**Comment by robert-bryson** [comment]
Line count with references to `www.data.gov`:

```bash
$ grep -rnw www.data.gov -e 'www.data.gov' | wc -l
    22371 
```

They mostly break down into larger categories (local links, references to js/css files, etc), but there are a number of loose ones to track down. See [badlinks.txt](https://github.com/GSA/datagov-deploy/files/7514748/badlinks.txt) for full list.

I am still working on the scripting portion for when files have an `...css?ver=1.0.0` extension and need to be both renamed from data.gov to a local reference and have links to those files updated.

**Comment by robert-bryson** [comment]
As per discussion with @adborden yesterday, pushed [last work](https://github.com/GSA/datagov-website/commit/8d2a444529bed30f4822450bb9b66975257c820b) on `sed` scripting. 
Finishing up remaining issues, namely children pages having poorly converted  relative links and paginations.

**Comment by robert-bryson** [comment]
Opened PR at https://github.com/GSA/datagov-website/pull/5

There remain 13,251 references to `https?://www.data.gov/` in 999 files. I believe the vast majority of these are like below; meaning part of SEO meta props and should remain as they are.

```html
  
	<!-- This site is optimized with the Yoast SEO plugin v17.5 - https://yoast.com/wordpress/plugins/seo/ -->
	<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
	<link rel="canonical" href="index.html" />
	<meta property="og:locale" content="en_US" />
	<meta property="og:type" content="article" />
	<meta property="og:title" content="Cities - Data.gov" />
	<meta property="og:url" content="https://www.data.gov/cities/" />
	<meta property="og:site_name" content="Data.gov" />
	<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"WebSite","@id":"https://www.data.gov/#website","url":"https://www.data.gov/","name":"Data.gov","description":"The home of the U.S. Government\u2019s open data","potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.data.gov/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-US"},{"@type":"CollectionPage","@id":"https://www.data.gov/cities/#webpage","url":"https://www.data.gov/cities/","name":"Cities - Data.gov","isPartOf":{"@id":"https://www.data.gov/#website"},"breadcrumb":{"@id":"https://www.data.gov/cities/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://www.data.gov/cities/"]}]},{"@type":"BreadcrumbList","@id":"https://www.data.gov/cities/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.data.gov/"},{"@type":"ListItem","position":2,"name":"Cities"}]}]}</script>
	<!-- / Yoast SEO plugin. -->
```

Overall, though, I think this leaves the static site in a reasonable place in the context of the scope of this ticket.

**Comment by robert-bryson** [comment]
### Hand convert notes
Below are the fixes/screen shots of the steps taken to fix relative links during this process

- [x]  `<link rel="stylesheet" href="../../../wp/wp-includes/css/dist/block-library/style.min.css?ver=5.5.7">`
- [x]  `<img src="http://www.data.gov/app/themes/roots-nextdatagov/assets/img/logo.svg" />`
- [x]  `<link rel="stylesheet" href="http://www.data.gov/app/themes/roots-nextdatagov/assets/css/rei.css?ver=5.5.7">`
- [x]  `<script type='text/javascript' src='http://www.data.gov/app/plugins/m-wp-popup/js/wpp-popup-frontend.js'</script>`
- [x]  `<img src="http://www.data.gov/app/themes/roots-nextdatagov/assets/img/logo.svg" />`
- [x]  `<li class="menu-events"><a href="http://www.data.gov/events/">Events</a></li>`
- [x]  `<script type='text/javascript' src='http://www.data.gov/app/plugins/m-wp-popup/js/wpp-popup-frontend.js'</script>`
- [x]  `<link rel="stylesheet" href="http://www.data.gov/wp/wp-includes/css/dist/block-library/style.min.css?ver=5.5.7">`
- [x]  `<form action="https://www.data.gov/wp/wp-comments-post.php"`
- [x]  `<link rel="prev" href="https://www.data.gov/climate/foodresilience/page/2/" />`
- [x]  `<link rel="stylesheet" href="../../../../app/plugins/m-wp-popup/css/colorbox/colorbox.css?ver=0.1">`
- [x]  `<script type='text/javascript' src='http://www.data.gov/app/plugins/m-wp-popup/js/wpp-popup-frontend.js'</script>`
- [x]  `<link rel="stylesheet" href="[https://www.data.gov/app/plugins/category-sticky-post/css/plugin.css?ver=5.5.7](https://www.data.gov/app/plugins/category-sticky-post/css/plugin.css?ver=5.5.7)">`
- [x]  `<script type='text/javascript' src='http://www.data.gov/wp/wp-includes/js/dist/vendor/wp-polyfill.min.js'>`
- [x]  `<img src="http://www.data.gov/app/themes/roots-nextdatagov/assets/img/logo.svg" />`
- [x]  `<img src="http://www.data.gov/app/themes/roots-nextdatagov/assets/img/logo.svg" />`
- [x]  `<link rel="stylesheet" href="http://www.data.gov/app/plugins/simple-tooltips/zebra_tooltips.css?ver=5.5.7">`
- [x]  `<link rel="stylesheet" href="http://www.data.gov/app/plugins/wp-open311/public/assets/css/chosen.min.css?ver=1.0.0">`
- [x]  `<script type='text/javascript' src='http://www.data.gov/app/plugins/m-wp-popup/js/wpp-popup-frontend.js'></script>`
- [x]  `<img src="http://www.data.gov/app/themes/roots-nextdatagov/assets/img/logo.svg" />`
- [x]  `<li class="current-post-ancestor active current-post-parent menu-arctic"><a href="https://www.data.gov/climate/arctic/" class="local-link">Arctic</a></li>`
- [x]  `<script type='text/javascript' src='http://www.data.gov/app/plugins/m-wp-popup/js/wpp-popup-frontend.js'></script>`
- [x]  `( 'fetch' in window ) || document.write( '<script src="http://www.data.gov/wp/wp-includes/js/d`
- [x]  `<li class="menu-contact-climate"><a href="https://www.data.gov/climate/contact/">Contact Climate</a></li>`
- [x]  `<ul class='pagination'><li><span class='page-numbers pagenav current'> 1 </span></li><li><a class='page-numbers pagenav' href='https://www.data.gov/food/highlights?currentpage=2'> 2 </a></li> <li class='pagination-next'> <a href='https://www.data.gov/food/highlights?currentpage=2'> Next</a></li> </ul>        </div>`
- [x]  `<script type='text/javascript' src='http://www.data.gov/app/plugins/m-wp-popup/js/wpp-popup-frontend.js'></script>`
- [x]  `<img src="http://www.data.gov/app/themes/roots-nextdatagov/assets/img/logo.svg" />`


![Untitled 16](https://user-images.githubusercontent.com/91547795/144105996-5ebf7b00-d4d5-4e58-b465-b167339aa2a9.png)
![Untitled 17](https://user-images.githubusercontent.com/91547795/144105999-1a132c09-53dc-4a96-ba60-1df7d57ee37e.png)
![Untitled 18](https://user-images.githubusercontent.com/91547795/144106001-cf1658b3-3fe9-4a74-9827-590794d3dc00.png)
![Untitled 19](https://user-images.githubusercontent.com/91547795/144106003-9f0e8a0c-3997-4a29-ae70-0f88bf6419a3.png)
![Untitled 20](https://user-images.githubusercontent.com/91547795/144106006-e4fc78e2-3016-4982-bbca-848ceffc5d79.png)
![Untitled 21](https://user-images.githubusercontent.com/91547795/144106008-61827998-219a-4baf-aec5-877f0927c1c5.png)
![Untitled 22](https://user-images.githubusercontent.com/91547795/144106010-e9bf970b-545e-4462-9ede-9085afdffdac.png)
![Untitled 23](https://user-images.githubusercontent.com/91547795/144106011-95426667-6d98-46e7-ad20-89ea9060e968.png)
![Untitled 24](https://user-images.githubusercontent.com/91547795/144106013-b694acc9-fbe2-49de-bc05-0685d46b3635.png)
![Untitled 25](https://user-images.githubusercontent.com/91547795/144106015-c0b1c85e-3237-45b8-a94f-37fdeeff2541.png)
![Untitled 26](https://user-images.githubusercontent.com/91547795/144106017-13c8e82e-64bf-4de8-82d3-2739a52fda05.png)
![Untitled 27](https://user-images.githubusercontent.com/91547795/144106018-0f39486b-7724-4d37-a271-70c36c7ac048.png)
![Untitled 28](https://user-images.githubusercontent.com/91547795/144106019-674b6d0f-d521-4065-b00e-0be91ce45cd9.png)
![Untitled](https://user-images.githubusercontent.com/91547795/144106020-02f6fad9-bb4b-4fee-8ece-cf94466f73c8.png)
![Untitled 1](https://user-images.githubusercontent.com/91547795/144105967-12b6be26-5fab-4342-b9fb-fe6565e47615.png)
![Untitled 2](https://user-images.githubusercontent.com/91547795/144105969-7192bf2c-3c47-49c8-96d4-f4377a2e7581.png)
![Untitled 3](https://user-images.githubusercontent.com/91547795/144105970-8d547a31-42d1-4559-a8c4-c81a3564bb33.png)
![Untitled 4](https://user-images.githubusercontent.com/91547795/144105972-2714ad35-39c6-437a-9f24-59b4e4258de9.png)
![Untitled 5](https://user-images.githubusercontent.com/91547795/144105974-4b486a8d-c880-42e5-919d-0a158a792b0b.png)
![Untitled 6](https://user-images.githubusercontent.com/91547795/144105975-42252b15-b605-4021-b363-119f942decbf.png)
![Untitled 7](https://user-images.githubusercontent.com/91547795/144105976-7be050fd-3f2c-4678-90f6-6e5b4b882978.png)
![Untitled 8](https://user-images.githubusercontent.com/91547795/144105979-004512dc-8613-427e-b69d-37d8cda65fbd.png)
![Untitled 9](https://user-images.githubusercontent.com/91547795/144105981-f1c043ed-4f56-4bea-82ca-407031a0d74c.png)
![Untitled 10](https://user-images.githubusercontent.com/91547795/144105983-ec9f865b-6033-4441-8cad-98b47d35e334.png)
![Untitled 11](https://user-images.githubusercontent.com/91547795/144105985-71a94725-f0c3-4c5e-bcd4-dbbffffb4947.png)
![Untitled 12](https://user-images.githubusercontent.com/91547795/144105986-9e9cd4a1-1693-49e8-a630-fe17cec64821.png)
![Untitled 13](https://user-images.githubusercontent.com/91547795/144105989-bced8054-43c8-4d30-879f-980890225d6e.png)
![Untitled 14](https://user-images.githubusercontent.com/91547795/144105991-abf74de2-5d68-4f34-bbd0-b3d3930ab32b.png)
![Untitled 15](https://user-images.githubusercontent.com/91547795/144105993-c3642619-36df-4d19-9e77-07a50126be45.png)
