### ISSUE TITLE
data.gov feedback forms work in a static site deployment

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3488]
## User Story

In order to deploy the data.gov static site outside of FCS as soon as possible, feedback forms on www.data.gov or data.gov targets should not rely on the Wordpress backend.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a static version of the data.gov site 
  WHEN a feedback form is submitted  
  THEN the content is collected 
   AND data.gov contact points are notified of the form submission (perhaps not immediately)

## Background
This story is largely the result of the issues uncovered during [[spike] Test static archive of www.data.gov as a .temporary solution for migration #3465](https://github.com/gsa/datagov-deploy/issues/3465). In particular, see Bret's [comment on items that need addressing](https://github.com/gsa/datagov-deploy/issues/3465#issuecomment-945017390).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Existing forms that rely on the Wordpress application backend would instead use Touchpoints as their target. Touchpoints has its own ATO. This change reduces the number of moving parts that the data.gov team has to maintain in order to get customer feedback.

## Sketch
- Potentially using [Touchpoints](https://touchpoints.digital.gov/) for the new forms
- If implementation of Touchpoints as a popup or embedded in the page is difficult, then it's OK to use Touchpoints via link to a touchpoints.app.cloud.gov URL.
- Two potential paths for implementing
  - Modify the Wordpress form implementations pre-scrape
  - Modify the scraped pages in-situ wherever forms are in use

- [x] Remove topic-specific contact forms from the site

**Comment by robert-bryson** [comment]
[Documentation on adding forms](https://federalist.18f.gov/documentation/forms/) from the Federalist site.

**Comment by adborden** [comment]
I ended up redirect the topic-specific forms to the main /contact form

**Comment by adborden** [comment]
Invited datagov-comms to the Touchpoints form and updated the notification address to datagov@
