### ISSUE TITLE
Integration tests to test CKAN site javascript functions

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3491]
## User Story

In order to provide confidence that CKAN applications are working fine, Data.gov developers want to add more integration tests for certain critical UI elements.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] WHEN a commit is pushed to Catalog and Inventory repos \
  THEN a cypress test is run to test organization machine name auto-generation
- [ ]  WHEN a commit is pushed to **Catalog** repo \
  THEN a cypress test is run to test map is loaded in the map search box 
- [ ]  WHEN a commit is pushed to **Catalog** repo \
  THEN a cypress test is run to test creating a harvest source loads corresponding UI options for the selected harvest type

## Background
Screenshots to demo working UI elements: 
1. Organization machine name auto-generation:
When type `My Organization`, js should generate `my-organization`
![image](https://user-images.githubusercontent.com/1392461/137991114-402b8ab1-3933-47e4-8bc2-01310e7712f9.png)

2. Map search box on catalog /dataset page
![image](https://user-images.githubusercontent.com/1392461/133675734-7652a17a-5402-43f8-bd78-379c43040fc4.png)

3. Different harvest source type loads different options.
![image](https://user-images.githubusercontent.com/1392461/137991272-76a13967-8bb6-4172-9d94-51792c443ba6.png)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
We're already creating harvest sources and testing the map with cypress, I'm not sure there's much value in this ticket...

**Comment by hkdctol** [comment]
Consider as OBE
