### ISSUE TITLE
data.gov /applications filter broken in static site

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3492]
The filter search on ```/applications``` does not work on a static copy of the data.gov site.

## How to reproduce

1. On a local version of the static site, browse to the equivalent to https://www.data.gov/applications
1. Use the Search Applications form

## Expected behavior

Just correct application results are returned.

## Actual behavior

All application results are returned and it seems like the page is just being reloaded

## Sketch

Wordpress is handling the query server-side with the request: ```https://www.data.gov/applications?q={query}&sort={sorting stuff}&as_sfid={token?}```. 

We would need to either:
- Implement an alternative endpoint for this
- Sort on the front end (jQuery? a bit of React?)
- Decide how much value a search bar adds in this case and maybe cut it

**Comment by robert-bryson** [comment]
Updated and removed myself.

**Comment by nickumia-reisys** [comment]
This page has been removed entirely from the static site.  New content and design options will follow after,
- https://github.com/GSA/data.gov/issues/4029
- https://github.com/GSA/data.gov/issues/4141
