### ISSUE TITLE
Redirects special domains to data.gov topic pages on cloud.gov

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3497]
## User Story

In order to ensure existing links aren't broken by our move to a static site, the cloud.gov team wants redirects from [certain domains](https://docs.google.com/spreadsheets/d/1XzP6bbIa7A1Jf0mEkDdEhQfsfYfE0YG0EHOtqPQJ6HM/edit?usp=sharing) to particular pages on the data.gov static site.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I click on a link to one of the special domain names \
  THEN I am redirected to the appropriate topic page on data.gov.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
See [this spreadsheet](https://docs.google.com/spreadsheets/d/1XzP6bbIa7A1Jf0mEkDdEhQfsfYfE0YG0EHOtqPQJ6HM/edit?usp=sharing) for the existing list of domains. We don't mind losing most since they don't work anyway, but we'd like to reimplement the ones for the topic sub-pages marked "Keep" in the sheet.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- Presume we have already moved data.gov onto Federalist and [migrated www.data.gov and data.gov to point to it](https://federalist.18f.gov/documentation/custom-domains/)
- Options for handling the redirects
  - We can push an  the [nginx-buildpack app]() with an nginx.conf that handles redirects for the special domains, and point all the domains to it.
  - We can have a [static_buildpack app]() that just includes a `<meta http-equiv="refresh" content="0; url=http://example.com/">` header, and point all the domains to it.
    - Would maybe instead use JS for the redirect since it needs to know which domain it was served under.

**Comment by adborden** [comment]
Opened ticket RITM0903860 with GSA DNS to update CNAME records for the ["Keep" domains](https://docs.google.com/spreadsheets/d/1XzP6bbIa7A1Jf0mEkDdEhQfsfYfE0YG0EHOtqPQJ6HM/edit?usp=sharing).

```
Please update CNAME records for the following domains to point to www-redirects-prod-datagov.app.cloud.gov

agriculture.data.gov
climate.data.gov
developer.data.gov
energy.data.gov
food.data.gov
highlights.data.gov
labs.data.gov
ocean.data.gov
```

**Comment by adborden** [comment]
Also opened RITM0904225 to create validation records for the external domain service.

```
Hello, please create the following CNAME records used for TLS certificate validation:

_acme-challenge.agriculture.data.gov. CNAME _acme-challenge.agriculture.data.gov.external-domains-production.cloud.gov.
_acme-challenge.catalog.data.gov. CNAME _acme-challenge.catalog.data.gov.external-domains-production.cloud.gov.
_acme-challenge.climate.data.gov. CNAME _acme-challenge.climate.data.gov.external-domains-production.cloud.gov.
_acme-challenge.dashboard.data.gov. CNAME _acme-challenge.dashboard.data.gov.external-domains-production.cloud.gov.
_acme-challenge.developer.data.gov. CNAME _acme-challenge.developer.data.gov.external-domains-production.cloud.gov.
_acme-challenge.energy.data.gov. CNAME _acme-challenge.energy.data.gov.external-domains-production.cloud.gov.
_acme-challenge.food.data.gov. CNAME _acme-challenge.food.data.gov.external-domains-production.cloud.gov.
_acme-challenge.highlights.data.gov. CNAME _acme-challenge.highlights.data.gov.external-domains-production.cloud.gov.
_acme-challenge.inventory.data.gov. CNAME _acme-challenge.inventory.data.gov.external-domains-production.cloud.gov.
_acme-challenge.labs.data.gov. CNAME _acme-challenge.labs.data.gov.external-domains-production.cloud.gov.
_acme-challenge.ocean.data.gov. CNAME _acme-challenge.ocean.data.gov.external-domains-production.cloud.gov.
_acme-challenge.www.data.gov. CNAME _acme-challenge.www.data.gov.external-domains-production.cloud.gov.
_acme-challenge.data.gov. CNAME _acme-challenge.data.gov.external-domains-production.cloud.gov.
```

**Comment by adborden** [comment]
PRs are merged, just waiting on DNS tickets before completing this.

**Comment by adborden** [comment]
We had an issue adding the domain to cloud.gov.
```
$ cf create-domain gsa-datagov data.gov
Creating private domain data.gov for org gsa-datagov as aaron.borden@gsa.gov...
The domain name "data.gov" cannot be created because "staging.api.data.gov" is already reserved by another domain
FAILED
```

cg-support recommending creating the domains individually as private domains `cf create-private-domain gsa-datagov agriculture.data.gov`.

**Comment by mogul** [comment]
[The merged PR is deploying now.](https://github.com/GSA/datagov-website/actions/runs/1517849745) Once that's done successfully Aaron will verify and mark this Done.

**Comment by adborden** [comment]
This is all set. The `labs.data.gov` domain hasn't been updated yet. It will be moved as part of the [dashboard migration](https://github.com/GSA/datagov-deploy/issues/3555).
