### ISSUE TITLE
Deprecate the Dashboard

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3502]
## User Story

In order to reduce technical debt, data.gov sysadmin wants the dashboard application deprecated and archived.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN all dashboard features are replicated in other systems correctly \
  WHEN I view the [project-open-data-dashboard](https://github.com/GSA/project-open-data-dashboard) code\
  THEN all deployments have been turned off \
  AND the repository is archived

- [x] WHEN I visit labs.data.gov/dashboard \
  THEN my browser is redirected to the new location of our reporting data

- [x] WHEN I go to the data.gov cloud.gov account
  THEN there are no apps or services taking up space for dashboard.

## Background
Goal is to reduce the compliance and maintenance burden of a tool thatdoes a separate scan of the data, and is not reflective of the actual catalog statistics.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, this will remove/release compliance burden, and remove an attack surface.

## Sketch
Once the rest of the items in this epic are done, simply make a PR to note the repository/project is archived, remove all deployment steps, and then mark the repository as archived once the PR is merged.
Then add a URL to redirect from dashboard to the catalog dataset, and/or maybe other information.

**Comment by robert-bryson** [comment]
Note: for the middle AC, `labs.data.gov` as been removed so we will not add a redirect.

**Comment by robert-bryson** [comment]
So far: 
- Disabled all `project-open-data-dashboard` [github actions](https://github.com/GSA/project-open-data-dashboard/actions)
- Deleted all `dashboard` and `dashboard-egress` apps
- Deleted all routes in all spaces (except `dashboard.data.gov` for redirect)
- Network policies appear to be removed with apps, no security groups to update

To do:
- Someone with permissions archive the repo (do we want to add a note?)

**Comment by hkdctol** [comment]
@robert-bryson I drafted some text as explanation https://docs.google.com/document/d/148bUgGPHkYNkcshZtWUfpCst7G3HnfYTezqhca02K18/edit?usp=sharing

**Comment by robert-bryson** [comment]
Awesome, that looks great! Thank you. Would you like me to fully replace [the current `README.md`](https://github.com/GSA/project-open-data-dashboard/blob/main/README.md) or just prepend this new text, @hkdctol ?

**Comment by hkdctol** [comment]
@robert-bryson I forgot to mention -- how about putting the new text at the top, so we maintain text about what it used to do

**Comment by robert-bryson** [comment]
Perfect, thank you! PR [here](https://github.com/GSA/project-open-data-dashboard/pull/419).

**Comment by btylerburton** [comment]
Merged and Archived.
