### ISSUE TITLE
[research: 3d] Decide on approach for implementing canned maintenance tasks/actions

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3510]
## Purpose

We want to keep our prod environment hands-off, but we're not sure how to do that given we have a bunch of recurring maintenance processes.

Given above uncertainty, conducting prototyping is needed to provide confidence in future steps.

3 days of effort has been allocated and once compete, findings will be demonstrated and specific future actions will be decided.

### Acceptance Criteria

[ACs should be clearly demo-able/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] WHEN [time box] expires\
  THEN [findings are demonstrable] \
  AND [future action is decided] \
  AND [stories covering future action are created if needed]

### Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

### Sketch

Identify the list of things we want to encapsulate:
> For example, if recovering from data degradation on database or SOLR, could use the CKAN sync command to get SOLR synced from the DB (or vice versa).

One idea for how to encapsulate:
> In order to have a non-technical way to run one-off jobs, data.gov sysadmins want github actions created that are manually deployable (with input if necessary) to run one off jobs.
- [ ] GIVEN a well defined CKAN (or other application task) needs to be run in some environment \
  WHEN a data.gov sysadmin runs the job via github actions \
  THEN the job is run successfully

**Comment by mogul** [comment]
Choosing not to take this on; it's pretty clear at this point that triggering jobs via GitHub Actions makes sense.
