### ISSUE TITLE
Static Site tests run on GitHub Actions

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3513]
## User Story

In order to get off of CircleCi, data.gov admins want static sites (see [wiki for list](https://github.com/GSA/datagov-deploy/wiki/Static-sites)) to be tested on GitHub Actions and all CircleCi code to be removed.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN all circleCi configuration is removed from static site repo's \
  WHEN a PR is made on one of the static site repo's \
  THEN the necessary tests are run in GitHub Actions

## Background
Should be straightforward, we've done this on many CKAN repositories as well as the dashboard.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, all of the code is open to the public already.

## Sketch
- [x] Analyze current CircleCi Actions
- [x] Research any GitHub Actions to test/verify Jekyll sites automatically
- [x] Replicate in GitHub Actions

**Comment by jbrown-xentity** [comment]
See example porting for resources: https://github.com/GSA/resources.data.gov/pull/524/files
We should take this on soon, as federation is currently blocked: https://github.com/GSA/us-data-federation

**Comment by btylerburton** [comment]
https://github.com/GSA/sdg-indicators-usa will be left off the list of conversions. Currently the site is creating Federalist builds successfully, and any attempt to upgrade to GH Actions and a supported version of Ruby results in build errors in the plugins; alternately, Federalist will fail the build when forced to use an unsupported version of Ruby.

GH Actions error with Ruby 3.1:

```
jekyll 3.9.2 | Error:  undefined method `each' for nil:NilClass

          site.data['meta'].each do |indicator_id, meta|
                           ^^^^^
/Users/brendantburton/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/jekyll-open-sdg-plugins-0.0.16/lib/jekyll-open-sdg-plugins/multilingual_metadata.rb:14:in `block in generate': undefined method `each' for nil:NilClass (NoMethodError)

          site.data['meta'].each do |indicator_id, meta|
                           ^^^^^
```

Federalist error with Ruby 2.6:

```
2022-12-16 19:53:33 INFO [setup-ruby] Using ruby version in .ruby-version

2022-12-16 19:53:34 INFO [setup-ruby] Required ruby-2.6.0 is not installed.

2022-12-16 19:53:34 INFO [setup-ruby] To install do: 'rvm install "ruby-2.6.0"'

2022-12-16 19:53:34 ERROR [setup-ruby] ERROR: Unsupported ruby version specified in .ruby-version.

2022-12-16 19:53:34 ERROR [setup-ruby] Please upgrade to an actively supported version, see https://www.ruby-lang.org/en/downloads/branches/ for details.

2022-12-16 19:53:34 ERROR [main] There was a problem setting up Ruby, see the above logs for details.
```

**Comment by btylerburton** [comment]
Quick followup: I was able to remove Circelci from https://github.com/GSA/sdg-indicators-usa by not implementing the reusable template.
