### ISSUE TITLE
Unknown Unique Identifier for all datasets from data.json harvest source

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3515]
On catalog, datasets of data.json harvest type has a `Unique Identifier` field on the UI. Its value shows `Unknown` for all dataset. 

Two rows down there is another `Identifier` field which correctly using `identifier` values from the data.json source.

## How to reproduce

Open any data.json type of datasets on catalog 
For example, https://catalog.data.gov/dataset/annual-reports

## Expected behavior

`Unique Identifier` field has meaningful value

## Actual behavior

`Unique Identifier` shows `Unknown`

## Sketch
Need to figure out the purpose of field `Unique Identifier`.  Is it intended to be mapped to `identifier` from the json? Otherwise,  no point to have this field if the value is always `Unknown`.

**Comment by FuhuXia** [comment]
Compare current UI to the UI snapshot a year old, it shows `Unique Identifier` should be mapped to `identifier` like the way it was before.

# UI current:
![140144433-5cdf6f7d-1cba-4ac5-98e1-9492b6e61658](https://user-images.githubusercontent.com/1392461/140166020-90d14c82-33ea-4b53-8b54-583d73862fef.png)

# UI from 1 year old snapshot:
![140140916-69d44f71-970d-4cc1-806b-67b6e93fca0a](https://user-images.githubusercontent.com/1392461/140166021-db6e22c6-a319-45b1-9bc6-855d73bf25a4.png)

**Comment by nickumia-reisys** [comment]
Not sure if this is related; but does anyone know why this line is commented out?
- https://github.com/GSA/ckanext-datagovtheme/blob/c566378a432d18bffcc857fcab0baefd1b4fd60f/ckanext/datagovtheme/helpers.py#L673

**Comment by FuhuXia** [comment]
> Not sure if this is related; but does anyone know why this line is commented out?
> 
> * https://github.com/GSA/ckanext-datagovtheme/blob/c566378a432d18bffcc857fcab0baefd1b4fd60f/ckanext/datagovtheme/helpers.py#L673

A wild guess, because the Identifier is not Unique across all harvest sources?

**Comment by nickumia-reisys** [comment]
But the function is specifically for "schema11", which I thought was defined as unique?  You're saying that it's just about display, not about information lookup?

**Comment by FuhuXia** [comment]
Where does Unique Identifier come from and what is the purpose of it, is it used anywhere else? The answer might gives some clue.

**Comment by jbrown-xentity** [comment]
Clearly the UI component comes from [this block](https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/templates/package/read.html#L291-L365). It's doing some weird stuff, and checking to see if the data is DCAT-US 1.1 and doing some custom stuff.

**Comment by robert-bryson** [comment]
Paired with James and we decided to remove the UID block. With [this](https://github.com/GSA/ckanext-datagovtheme/pull/151) and [this](https://github.com/GSA/catalog.data.gov/pull/708), it should be gone..

**Comment by robert-bryson** [comment]
For evidence: 

![Image](https://user-images.githubusercontent.com/91547795/209203151-acc77b2a-a6cb-484e-bd77-110f8943f126.png)
