### ISSUE TITLE
Unknown Contact Email for non-data.json datasets

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3516]
On catalog, datasets always show "Unknown" as value for the field `Contact Email`. It only happens to datasets harvested from non-data.json harvest type.

## How to reproduce

[Example dataset 1](https://catalog.data.gov/dataset/enviroatlas-2016-floodplain-land-cover-proportions-for-the-conterminous-united-states)
[Example dataset 2](https://catalog.data.gov/dataset/enviroatlas-2016-floodplain-land-cover-proportions-for-the-conterminous-united-states
)

## Expected behavior

Display correct email address if there is a valid value.
![image](https://user-images.githubusercontent.com/1392461/140182440-9526013c-1fe6-4294-884c-a3f18e0d80c3.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/1392461/140182524-c823530e-89ff-4ac9-b48f-f79251de96a0.png)

It displays `Unknown` as value. But the  `Unknown` is actually hyper-linked to a valid email address.

**Comment by jbrown-xentity** [comment]
@hkdctol this is the issue, it's already created.
We have another dataset use case of this: https://catalog.data.gov/dataset/large-scale-international-boundaries3
I believe there is something fishy with this logic, and we may be able to fix this to the desired outcome: https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/templates/templates_new/package/read.html#L353-L359

**Comment by btylerburton** [comment]
updated link to the above: https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/templates/package/read.html#L353-L359

**Comment by nickumia-reisys** [comment]
I don't remember the exact reason for why the fix worked, but it had to do the template not handling the `unknown` case properly.  Either way, the example datasets above have been fixed and this is actually completed.
