### ISSUE TITLE
catalog bureau codes filter do not show name

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3520]
Catalog.data.gov used to replace the raw "bureau codes" filter at the bottom of the left panel with the nice names. This is no longer working.

## How to reproduce

1. Visit https://catalog.data.gov/dataset
1. Scroll to "Bureau" section on left side
1. See raw codes

## Expected behavior

Pretty Bureau names are used

## Actual behavior

Codes are used

## Sketch

Pretty sure this is in datagovtheme or data.json , and if it doesn't have it in the csv or lookup list then it rolls back to the raw code. Either it's not parsing the lookup table properly, or there is some kind of syntax change in the way bureau codes are parsed that causes the lookup to fail.

**Comment by hkdctol** [comment]
geodatagov or datagov catalog extensions are also possibilities

**Comment by jbrown-xentity** [comment]
The data that *should* be used is here: https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/data/omb_bureau_codes.csv
