### ISSUE TITLE
ckanext-datagovtheme has UI tests

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3521]
## User Story

In order to have confidence in UI changes in datagovtheme, data.gov sysadmins want Cypress tests (or other UI tests) implemented in datagovtheme.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a change is made to an html page in datagovtheme \
  WHEN tests are run on datagovtheme \
  THEN the tests evaluate the UI as a user would \
  AND errors are reported if the UI is not as expected

## Background

We have a lot of UI bugs that have slipped through to production recently. We want to catch these bugs at the source, and not have to create tests at the catalog level that may be incomplete. We already do this for ckanext-dcat_usmetadata.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, all code is already public

## Sketch

Use cypress examples from catalog, inventory, and ckanext-dcat_usmetadata. Create test cases for key items:

- [x] [bureau filter section shows up as name and not code](https://github.com/GSA/datagov-deploy/issues/3520)
- [x] [the dataset page doesn't have "unique Identifier" as "unknown"](https://github.com/GSA/datagov-deploy/issues/3515)
- [x] the dataset page doesn't have "unknown" for contact point when it has the email (maybe default to "email"?)

**Comment by jbrown-xentity** [comment]
Should consider using https://playwright.dev/python/docs/test-runners instead of cypress here, to keep everything in python.

**Comment by hkdctol** [comment]
Sentiment leans toward Cypress

**Comment by hkdctol** [comment]
@Jin-Sun-tts will create an additional related ticket

**Comment by Jin-Sun-tts** [comment]
created issue #4066 to fix the broken CKAN functions in datagovtheme.

**Comment by Jin-Sun-tts** [comment]
Because datagovtheme does not have all dependencies for creating new harvest source from UI function, we just created test datasets from code, the do the cypress UI tests. This may have limits for some tests, but this make datagovtheme only keeps necessary  components.

**Comment by nickumia-reisys** [comment]
Looking back at tickets we never closed properly is fun because you can see the struggle it took to figure out how to design a solution and then how it was fixed.  @Jin-Sun-tts implemented cypress tests for datagovtheme in the above PR.
