### ISSUE TITLE
CKAN dataset update slow

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3527]
## User Story

In order to remove/update datasets quickly, data providers want CKAN optimized to allow quick updates of the metadata via the API.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN a dataset needs to be updated/removed via the API \
  WHEN the API is called with `dataset_purge` or `package_update` \
  THEN the update occurs within (1?) second \
  AND a success response is returned

## Background

The de-duper script takes 1 minute per dataset to check a duplicate, mark it for keeping, removing duplicate, and update (if necessary). Currently running this on DOI, for 25K datasets, and will take 16 days (by best estimation, running 24/7). This needs to be faster.
New Relic reported [slowdowns in certain queries](https://one.newrelic.com/launcher/nr1-core.explorer?platform[accountId]=1601367&platform[timeRange][duration]=1800000&pane=eyJuZXJkbGV0SWQiOiJhcG0tbmVyZGxldHMuZGF0YWJhc2VzIiwic3BhUGF0aCI6Ii9vdmVydmlldy9BbGwvZHJpbGxkb3duIiwibWV0cmljIjoiRGF0YXN0b3JlL3N0YXRlbWVudC9Qb3N0Z3Jlcy9yZXNvdXJjZV9yZXZpc2lvbi9zZWxlY3QiLCJzb3J0IjoidG90YWxfY2FsbF90aW1lX3Blcl9taW51dGUiLCJlbnRpdHlHdWlkIjoiTVRZd01UTTJOM3hCVUUxOFFWQlFURWxEUVZSSlQwNThOall3T0RRek5UUXcifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5R3VpZCI6Ik1UWXdNVE0yTjN4QlVFMThRVkJRVEVsRFFWUkpUMDU4TmpZd09EUXpOVFF3Iiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImFwbS1uZXJkbGV0cy5kYXRhYmFzZXMifX0=&state=6ad73a3d-d96d-e7ce-a900-1bdbb0ebe870), and we will need to optimize these queries to solve these slowdowns.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, other than touching production DB

## Sketch

- [x] Review [resource](https://github.com/ckan/ckan/blob/c5c529d10ebe63d8573515483fdd46e0839477f0/ckan/model/resource.py) and resource_revision tables
- [x] Research ways to optimize query reported from New Relic
- [x] Investigate indexes created in upstream CKAN, probably in [migrations somewhere](https://github.com/ckan/ckan/search?q=create_index)
- [x] Propose solution for data.gov
- [x] Test solution for data.gov in staging
- [x] Merge solution for data.gov
- [x] Propose solution upstream

**Comment by FuhuXia** [comment]
Back to old days, with DB sized double or triple of current prod db, `search.rebuild(pkg_id)` in [db_solr_sync ](https://github.com/GSA/ckanext-geodatagov/blob/main/ckanext/geodatagov/commands.py#L597-L600) command can run at 6 datasets per second. That should gives some idea what benchmark we want to achieve.

Of cause, calling api is different from running ckan commands. Should be much slower.

**Comment by jbrown-xentity** [comment]
There are 2 main queries, which while related will require separate approaches...
1. `SELECT * FROM resource WHERE resource.package_id = "" ORDER BY resource.position`

This is being run from [this function](https://github.com/ckan/ckan/blob/2.8/ckan/lib/dictization/model_save.py#L71), trying to update the resource list given a new resource list. The logic here is extremely complex, using [sqlalchemy backref](https://docs.sqlalchemy.org/en/14/orm/backref.html) defined [here](https://github.com/ckan/ckan/blob/c5c529d10ebe63d8573515483fdd46e0839477f0/ckan/model/resource.py#L141-L152) to get the ordered list of resources, and then update them appropriately. The slow part is by far the order by; if we could do that as a secondary step the query speed would increase a ton (but see code comments, some magic is happening on handling the "order" field and would take a deep dive and testing to understand).
It should also be noted that there are only 2 indexes on the resource table, for `id` and `url` fields. So there is no quick search for resources matching a package_id, which seems weird because the only way you look at resources is from the package...
```
ckan=> SELECT
ckan->     tablename,
ckan->     indexname,
ckan->     indexdef
ckan-> FROM
ckan->     pg_indexes
ckan-> WHERE
ckan->     tablename= 'resource'
ckan-> ORDER BY
ckan->     indexname;
 tablename |        indexname         |                                  indexdef
-----------+--------------------------+----------------------------------------------------------------------------
 resource  | idx_package_resource_id  | CREATE INDEX idx_package_resource_id ON public.resource USING btree (id)
 resource  | idx_package_resource_url | CREATE INDEX idx_package_resource_url ON public.resource USING btree (url)
 resource  | resource_pkey            | CREATE UNIQUE INDEX resource_pkey ON public.resource USING btree (id)
```
For scale, there are 8 million rows in the resource table (actually lower than I expected)

2. `SELECT * FROM resource_revision AS rr WHERE rr.package_id = "" AND rr.revision_timestamp <= "some_date" AND rr.expired_timestamp > "expired_date"`

This query is being called from [here](https://github.com/ckan/ckan/blob/2.8/ckan/lib/dictization/model_dictize.py#L137). This has to do with getting the specific revision of any object. Changing any of the logic here could cause serious problems for other tables and would not be advised. Since this query needs to be run as is, we should consider using an index. The index would be a multi-column index, as described by postgres docs [here](https://www.postgresql.org/docs/9.6/indexes-multicolumn.html) and utilized by CKAN [here](https://github.com/ckan/ckan/blob/2.8/ckan/migration/versions/070_add_activity_and_resource_indexes.py#L13-L14).
The resource_revision table is only 10 million records, much closer to resource table size than one would think.
The resource revision table has more indexes, and one that is almost what we need (uses `id` instead of `package_id`):
```
ckan=> SELECT
    tablename,
    indexname,
    indexdef
FROM
    pg_indexes
WHERE
    tablename= 'resource_revision'
ORDER BY
    indexname;
     tablename     |          indexname          |                                                       indexdef
-------------------+-----------------------------+----------------------------------------------------------------------------------------------------------------------
 resource_revision | idx_package_resource_rev_id | CREATE INDEX idx_package_resource_rev_id ON public.resource_revision USING btree (revision_id)
 resource_revision | idx_resource_continuity_id  | CREATE INDEX idx_resource_continuity_id ON public.resource_revision USING btree (continuity_id)
 resource_revision | idx_resource_current        | CREATE INDEX idx_resource_current ON public.resource_revision USING btree (current)
 resource_revision | idx_resource_period         | CREATE INDEX idx_resource_period ON public.resource_revision USING btree (revision_timestamp, expired_timestamp, id)
 resource_revision | resource_revision_pkey      | CREATE UNIQUE INDEX resource_revision_pkey ON public.resource_revision USING btree (id, revision_id)
```
The initial and ongoing performance change of creating indexes would be unknown; indexes can take a long time to create on tables with > 1 million rows. Indexes also tend to speed up reads but slow down writes, as the write has to be inserted into the index properly. However, with the average time of these queries taking >5 seconds each, any package/dataset update on a large scale is completely untenable currently.

**Comment by FuhuXia** [comment]
Definitely add index on `package_id` first on both tables, at all cost.

**Comment by jbrown-xentity** [comment]
The output for `EXPLAIN ANALYZE` the queries (1 & 2) are below, along with a link to a "pretty" format for easier parsing:
1. `SELECT * FROM resource WHERE resource.package_id = '' ORDER BY resource.position;`; [pretty explain](https://explain.depesz.com/s/DmrB)
```
ckan=> EXPLAIN ANALYZE SELECT * FROM resource WHERE resource.package_id = '5b40a981-30f9-4d2a-9280-823b29ee7f94' ORDER BY resource.position;
                                                      QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------
 Sort  (cost=549423.62..549423.86 rows=96 width=556) (actual time=2894.740..2894.750 rows=24 loops=1)
   Sort Key: "position"
   Sort Method: quicksort  Memory: 38kB
   ->  Seq Scan on resource  (cost=0.00..549420.46 rows=96 width=556) (actual time=1947.442..2894.673 rows=24 loops=1)
         Filter: (package_id = '5b40a981-30f9-4d2a-9280-823b29ee7f94'::text)
         Rows Removed by Filter: 8503591
 Planning time: 0.111 ms
 Execution time: 2894.795 ms
(8 rows)
```
2. `SELECT * FROM resource_revision AS rr WHERE rr.package_id = "" AND rr.revision_timestamp <= "some_date" AND rr.expired_timestamp > "expired_date"` [pretty explain](https://explain.depesz.com/s/mCwC#html)
```
EXPLAIN ANALYZE SELECT * FROM resource_revision AS rr WHERE rr.package_id = '5b40a981-30f9-4d2a-9280-823b29ee7f94' AND rr.revision_timestamp <= '2021-06-26 13:36:51.717104' AND rr.expired_timestamp > '2021-06-26 13:36:51.717104';
 QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------
 Seq Scan on resource_revision rr  (cost=0.00..834633.73 rows=100 width=648) (actual time=2509.923..4920.857 rows=16 loops=1)
   Filter: ((revision_timestamp <= '2021-06-26 13:36:51.717104'::timestamp without time zone) AND (expired_timestamp > '2021-06-26 13:36:51.717104'::timestamp without time zone) AND (package_id = '5b40a981-30f9-4d2a-9280-823b29ee7f94'::text))
   Rows Removed by Filter: 10723871
 Planning time: 0.147 ms
 Execution time: 4920.893 ms
```

**Comment by jbrown-xentity** [comment]
I created indexes that I believed would speed up these queries on staging, which has around 250K datasets (prod is 350K). Before the index was created I was having similar performance issues on staging. After creating the following indexes, we cut our original time by > 90% (from 3.6 sec to 0.3 seconds). The indexes were created in about 1 minute or so.
1. `CREATE INDEX idx_package_resource_package_id ON public.resource USING btree (package_id);`

Before:
```
ckan=> EXPLAIN ANALYZE SELECT * FROM resource WHERE resource.package_id = '5b40a981-30f9-4d2a-9280-823b29ee7f94' ORDER BY resource.position;
                                                      QUERY PLAN
----------------------------------------------------------------------------------------------------------------------
 Sort  (cost=448128.03..448128.25 rows=89 width=583) (actual time=2689.546..2689.546 rows=0 loops=1)
   Sort Key: "position"
   Sort Method: quicksort  Memory: 25kB
   ->  Seq Scan on resource  (cost=0.00..448125.15 rows=89 width=583) (actual time=2689.532..2689.532 rows=0 loops=1)
         Filter: (package_id = '5b40a981-30f9-4d2a-9280-823b29ee7f94'::text)
         Rows Removed by Filter: 6576996
 Planning time: 0.943 ms
 Execution time: 2689.601 ms
(8 rows)
```

After
```
ckan=> EXPLAIN ANALYZE SELECT * FROM resource WHERE resource.package_id = '5b40a981-30f9-4d2a-9280-823b29ee7f94' ORDER BY resource.position;
                                                                  QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=369.06..369.29 rows=91 width=583) (actual time=0.098..0.098 rows=0 loops=1)
   Sort Key: "position"
   Sort Method: quicksort  Memory: 25kB
   ->  Bitmap Heap Scan on resource  (cost=5.26..366.10 rows=91 width=583) (actual time=0.085..0.085 rows=0 loops=1)
         Recheck Cond: (package_id = '5b40a981-30f9-4d2a-9280-823b29ee7f94'::text)
         ->  Bitmap Index Scan on idx_package_resource_package_id  (cost=0.00..5.24 rows=91 width=0) (actual time=0.082..0.082 rows=0 loops=1)
               Index Cond: (package_id = '5b40a981-30f9-4d2a-9280-823b29ee7f94'::text)
 Planning time: 0.287 ms
 Execution time: 0.136 ms
(9 rows)
```

2. `CREATE INDEX idx_package_resource_revision_period ON public.resource_revision USING btree (package_id, revision_timestamp, expired_timestamp);`

After
```
 EXPLAIN ANALYZE SELECT * FROM resource_revision AS rr WHERE rr.package_id = '86ba1a37-7a6c-4b69-9309-481636d4558b' AND rr.revision_timestamp <= '2021-06-26 13:36:51.717104' AND rr.expired_timestamp > '2021-06-26 13:36:51.717104';
 QUERY PLAN                                                                                                     
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using idx_package_resource_revision_period on resource_revision rr  (cost=0.56..366.88 rows=89 width=673) (actual time=0.031..0.048 rows=14 loops=1)
   Index Cond: ((package_id = '86ba1a37-7a6c-4b69-9309-481636d4558b'::text) AND (revision_timestamp <= '2021-06-26 13:36:51.717104'::timestamp without time zone) AND (expired_timestamp > '2021-06-26 13:36:51.717104'::timestamp without time zone))
 Planning time: 0.133 ms
 Execution time: 0.077 ms
(4 rows)
```

**Comment by jbrown-xentity** [comment]
Unfortunately we are having issues with staging replica DB now (the indexes were created on main DB), which we have almost never seen before. It's possible that the spike of data from main to replica caused the replica to go down, and we need a real buffer on the replicas before we can make change like this in prod. It's already been noted that some spikes on the replicas occur that go below our warning threshold, but the instances have always recovered in the past...

**Comment by jbrown-xentity** [comment]
After investigation, staging replica was at 99% usage before index failure. After checking prod space, we concluded we can move forward.
Just implemented indexes on production, and kicked off the de-dupe process. Went from 65 sec / dataset to ~3 sec / dataset, a 95.5% improvement. This will take the dedupe process from 16 days to around 16 hours. Will continue to run as time allows.

**Comment by jbrown-xentity** [comment]
Good news is, upstream CKAN already has 1 of the indexes: https://github.com/ckan/ckan/blob/master/ckan/migration/versions/092_01afcadbd8c0_resource_package_id_index.py.
We even have the same index name, completely by accident.
Made a PR to add the other index: https://github.com/ckan/ckan/pull/6533

**Comment by jbrown-xentity** [comment]
Looks like the revision tables aren't used in CKAN2.9, so upstream PR is defunct. We won't need this on CKAN2.9...
