### ISSUE TITLE
[spike 1d]: Explore exporting WordPress content and taxonomy from wp-json API

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3551]
## Purpose

We want to create a clean and maintainable static site that includes the majority of our WordPress content as markdown files (with simple html content), but we're not sure how to do that.

Given above question, conducting investigation/prototyping is needed to provide factual knowledge on future steps.

1 day of effort has been allocated and once compete, findings will be demonstrated and specific future actions will be decided.

### Acceptance Criteria

[ACs should be clearly demo-able/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] WHEN 1 day expires\
  THEN there exists a GitHub repository of a maintainable Jekyll content and structure

### Background

Several WordPress exporters and Jekyll importers exist, they only focus on content and they aren't very smart when it comes to the site hierarchy and taxonomy.

WordPress exposes a wp-json API (which appears in our crawl as json files) that is much simpler to understand URLs, taxonomy, and content. A simple script with this API might be able to get us a better organization of our .md file and site structure.

### Sketch

[Notes or a checklist reflecting our plan for tackling the uncertainty]

**Comment by robert-bryson** [comment]
Well, since this has already gone over time: I have been out for the holidays, but Mon/Tues last week I had been trying to use a tool called [rePress](https://github.com/gboone/rePress) that promised to do the wp-api to jekyll markdown conversion for me. After wrestling with `ruby` and `gem` and `jekyll` not playing nicely together and trying to get this tool to work properly,  all I have really found is that it doesn't work. 

It pulls from the wp website rather than the local files, but still returns this error:

```
rob@mba: ~/work/repos/rePress master ⚡
$ jekyll build --trace --incremental                                                                                                                                                              [9:19:05]
Configuration file: /Users/rob/work/repos/rePress/_config.yml
            Source: /Users/rob/work/repos/rePress
       Destination: /Users/rob/work/repos/rePress/_site
 Incremental build: enabled
      Generating... 
Traceback (most recent call last):
	24: from /Users/rob/.gem/ruby/2.7.4/bin/jekyll:25:in `<main>'
	23: from /Users/rob/.gem/ruby/2.7.4/bin/jekyll:25:in `load'
	22: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	21: from /Users/rob/.gem/ruby/2.7.4/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	20: from /Users/rob/.gem/ruby/2.7.4/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	19: from /Users/rob/.gem/ruby/2.7.4/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	18: from /Users/rob/.gem/ruby/2.7.4/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	17: from /Users/rob/.gem/ruby/2.7.4/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	16: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	15: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	14: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	13: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	12: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:36:in `process'
	11: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:65:in `build'
	10: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/command.rb:28:in `process_site'
	 9: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/site.rb:79:in `process'
	 8: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/site.rb:191:in `generate'
	 7: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/site.rb:191:in `each'
	 6: from /Users/rob/.gem/ruby/2.7.4/gems/jekyll-4.2.1/lib/jekyll/site.rb:193:in `block in generate'
	 5: from /Users/rob/work/repos/rePress/_plugins/wordpress.rb:19:in `generate'
	 4: from /Users/rob/.gem/ruby/2.7.4/gems/wordpress-api-0.0.3/lib/wordpress-api.rb:58:in `get_posts'
	 3: from /Users/rob/.gem/ruby/2.7.4/gems/wordpress-api-0.0.3/lib/wordpress-api.rb:39:in `query_load_json'
	 2: from /Users/rob/.rubies/ruby-2.7.4/lib/ruby/2.7.0/json/common.rb:335:in `load'
	 1: from /Users/rob/.rubies/ruby-2.7.4/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/Users/rob/.rubies/ruby-2.7.4/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at '<!DOCTYPE html> (JSON::ParserError)
<html class="no-js" dir="ltr" lang="en-US">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Page Not Found - Data.gov</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

.... many more lines of apparently invalid html
```

I think this was a bad rabbit hole to try to go down and, in retrospect, should have been trying to write up a quick script myself to do this.

In any case, I believe the `wp-json` files to still be a viable option for getting clean copies of page content moving forward. After speaking with Aaron just now, it was decided to icebox this approach for now and perhaps revisit this when creating a fully jekyll-ified version of the site.
