### ISSUE TITLE
Netsparker Nov 2021 finds Wordpress cookie issue

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3566]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.vpc04bf39i0h)._

**Date of report: 2021-11-25
**Severity: High
**Due date: 2021-12-25

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by adborden** [comment]
This will be resolved once data.gov is live on Federalist https://github.com/gsa/datagov-deploy/issues/3547

**Comment by nickumia-reisys** [comment]
Woah!  An ancient wordpress ticket 😉  Cloud.gov Pages has replaced Federalist which replaced FCS.  11ty replaced raw html files which replaced wordpress.
