### ISSUE TITLE
Enable New Relic and Gunicorn with CKAN

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3569]
## User Story

In order to utilize Gunicorn features and have New Relic insights, data.gov sysadmin wants CKAN web servers to utilize Gunicorn with the New Relic wrapper.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN a CKAN instance is running in dev, staging, or prod (catalog or inventory) \
  WHEN the server responds to a request \
  THEN entries appear in New Relic

## Background

We simplified our MVP for CKAN by using the `ckan run` command [in our start scripts](https://github.com/GSA/inventory-app/blob/main/config/server_start.sh#L11). We need to move back to New Relic with Gunicorn (see commented code [here](https://github.com/GSA/inventory-app/blob/main/config/server_start.sh#L6).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, just improvements

## Sketch
Needs to be done for inventory and catalog, just documenting inventory first.
- [x] ~Update [local start command](https://github.com/GSA/inventory-app/blob/main/start.sh#L90) to not depend on server_start.sh~
- [x] Debug why gunicorn command no longer works (test locally first, if working test on cloud.gov), iterate on issues (don't use New Relic wrapper command yet)
- [x] Add New Relic wrapper, debug any issues
- [x] Test on cloud.gov dev (if haven't yet)
- [x] PR and merge

**Comment by jbrown-xentity** [comment]
Looks like someone already ran into this, and found a solution: https://github.com/ckan/ckan/issues/6496

**Comment by robert-bryson** [comment]
As a demo of the completed work:

![image](https://user-images.githubusercontent.com/91547795/148426818-539e6a24-5f33-4747-bb19-2b25757deea3.png)

This is a screenshot of the New Relic alerts today showing the target as inventory.
