### ISSUE TITLE
Update data.gov Google Analytics tag (analytics.js) to the GA4 (gtag.js)

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3571]
## User Story

In order to benefit from the  new generation of Google Analytics, data.gov teams wants upgrade to Google's GA4 (gtag.js) tagging solution.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] WHEN visit https://catalog.data.gov
  THEN we see `https://www.googletagmanager.com/gtag/js` in the source code \
  AND visitor data are collected to the new GA4 properties on the GA dashboard.
- [x] WHEN visit https://www.data.gov
  THEN we see `https://www.googletagmanager.com/gtag/js` in the source code \
  AND visitor data are collected to the new GA4 properties on the GA dashboard.
- [x] WHEN visit https://sdg.data.gov/
  THEN we see `https://www.googletagmanager.com/gtag/js` in the source code \
  AND visitor data are collected to the new GA4 properties on the GA dashboard.
- [x] WHEN visit https://resources.data.gov/
  THEN we see `https://www.googletagmanager.com/gtag/js` in the source code \
  AND visitor data are collected to the new GA4 properties on the GA dashboard.

## Background

We got [email notification](https://mail.google.com/mail/#search/Upgrade+your+tag+to+experience+the+future+of+Google+Analytics) from Google to encourage for the upgrade.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Developer will need to gain access to the GA dashboard to configure GA4 properties.

## Sketch
- [x] Configure new GA4 properties on the GA dashboard.
- [x] Add gtag.js snippet to [ckanext-googleanalyticsbasic](https://github.com/GSA/ckanext-googleanalyticsbasic) ckan extensions for catalog.data.gov and static code to www.data.gov
- [x] ~~Leave both old generation `analytics.js` snippet and new generation `gtag.js` snippet on for a while, verify it is working expected before taking `analytics.js`  off.~~

**Comment by jbrown-xentity** [comment]
Search `analytics` issues, there are 9 issues that are semi-related. Should validate this ticket with other possible work.

**Comment by btylerburton** [comment]
Based on comments at the TTS Digital Council, we should first enroll in GSA's GA360 enterprise analytics program. This will give our UA implementation another year of life and then GA360 admins will create a GA4 account for us, after which developers can create implementation tickets.

**Comment by hkdctol** [comment]
Discussion at IRL was we update our own existing account and enroll in the GSA GA 360

**Comment by FuhuXia** [comment]
It turns out we lost the whole block `<!-- Google Analytics --> ... <!-- End Google Analytics -->` when we migrated from ckan `2.8.10` to `2.9.5` in August of 2022.

**Comment by dlennox24** [comment]
We determined that the CKAN templates were being overwritten by other CKAN plugins. Fuhu was able to resolve this with this PR: https://github.com/GSA/catalog.data.gov/pull/1084. This likely also contributed to the lost of overall views in the GA reports. I've updated the PR with the GA4 tracking code. Once this is deployed we can verify if data is flowing into the GA4 property.

**Comment by dlennox24** [comment]
PR is merged and data from catalog.data.gov is flowing into the GA4 property. Next steps are to ensure static site data is being ingested into the GA4 property. This will likely require a separate data stream to allow for the difference in subdomains.

![Image](https://github.com/GSA/data.gov/assets/11825880/c549ba47-6ffc-4a30-be7b-bea798e02c21)

**Comment by dlennox24** [comment]
Verified that the new gtag javascript was being used in the data.gov static site. I've update the tracking code to use the GA4 version. Once this is deployed, I can verify that data is flowing into the GA4 property from the static sites. Once that verification is complete, this story can be marked complete.

PR: https://github.com/GSA/datagov-11ty/pull/158



![Image](https://github.com/GSA/data.gov/assets/11825880/c8d22ea5-7914-4a0c-a593-3809252b0d71)

**Comment by dlennox24** [comment]
I verified that data is flowing into the GA4 from both catalog.data.gov and the 11ty site.

Examples:
- [Page data from 11ty](https://analytics.google.com/analytics/web/#/p381392243/reports/explorer?params=_u..nav%3Dmaui%26_r.explorerCard..seldim%3D%5B%22unifiedPagePathScreen%22%5D%26_r.explorerCard..startRow%3D0&r=all-pages-and-screens&ruid=all-pages-and-screens,life-cycle,engagement&collectionId=life-cycle)
- [catalog.data.gov page data](https://analytics.google.com/analytics/web/#/p381392243/reports/explorer?params=_u..nav%3Dmaui%26_r.explorerCard..seldim%3D%5B%22unifiedPagePathScreen%22%5D%26_r.explorerCard..startRow%3D0&r=all-pages-and-screens&ruid=all-pages-and-screens,life-cycle,engagement&collectionId=life-cycle)

**Comment by hkdctol** [comment]
@dlennox24 what we discussed about making sure that sdg and resources are included in the Data.gov GA4, can we include that here, and then we can close ticket

**Comment by dlennox24** [comment]
I added https://sdg.data.gov/ and https://resources.data.gov/ to the acceptance criteria and moved this back to in progress. These sites don't have the new GA4 tag/code added to them yet.

**Comment by dlennox24** [comment]
I've added the new GA4 code to resources and sdg. The PRs are currently pending review and approval.

**Comment by hkdctol** [comment]
@dlennox24 will close after confirming data is flowing

**Comment by dlennox24** [comment]
Data has been flowing! Marking as complete.

![Image](https://github.com/GSA/data.gov/assets/11825880/3b7e26f1-6228-4973-bb3f-d0b39ff20f8f)
