### ISSUE TITLE
Cannot add data.gov domain to cloud.gov org

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3573]
Found in https://github.com/gsa/datagov-deploy/issues/3555#issuecomment-980454451

Hit a snag when creating the data.gov domain in cloud.gov. We're working through this with the cg-support team.

```
$ cf create-domain gsa-datagov data.gov
Creating private domain data.gov for org gsa-datagov as aaron.borden@gsa.gov...
The domain name "data.gov" cannot be created because "staging.api.data.gov" is already reserved by another domain
FAILED
```

The workaround is to create the individual domains as private domains.

    $ cf create-private-domain gsa-datagov catalog.data.gov
    $ cf map-route catalog catalog.data.gov

## How to reproduce

1. `cf create-domain gsa-datagov data.gov`

## Expected behavior

domain is created successfully and I can map any *.data.gov route to applications

## Actual behavior

cf error with domain conflict

## Sketch

[Resolve conflict with cloud.gov support](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1638470894017000?thread_ts=1637958146.006300&cid=C09CR1Q9Z).

**Comment by mogul** [comment]
Closing as we have a workaround (explicitly create a CF domain for each of the subdomains).
