### ISSUE TITLE
Redirect www.data.gov to data.gov (outside of FCS)

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3576]
## User Story

In order to decommission services in FCS, data.gov team wants to handle redirects from www.data.gov -> data.gov entirely within cloud.gov.

https://github.com/gsa/datagov-deploy/issues/3547#issuecomment-985863987

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] WHEN I curl -v https://www.data.gov/foo
  THEN I see a 302 redirect to https://data.gov/foo

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
None.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

- [Add a redirect to our www-redirects app that sends traffic for www.data.gov to data.gov](https://github.com/GSA/datagov-website#www-redirects)

**Comment by adborden** [comment]
As an alternative, we could [migrate to Route53](https://github.com/GSA/datagov-deploy/issues/1001) which supports ALIAS records and does not require a redirect server.

**Comment by adborden** [comment]
From the GSA Web team:
1. Include data.gov certificate to the Jira ticket, password protected and notify Chudi,  Chudi will configure the re-direct for data.gov to point to www.data.gov
1. Submit a DNS update for A  record for data.gov record host address : 159.142.191.107 (APEX Production) via SN

**Comment by jbrown-xentity** [comment]
Waiting on Dave on the Federalist team to report on scans complete, and then we can make the request to GSA Web team...

**Comment by adborden** [comment]
@jbrown-xentity that's not a blocker. Setting up the redirect is independent from the Federalist migration. This issue needs to be completed to move out of FCS. We should try to go ahead with this based on our availability.

**Comment by adborden** [comment]
Originally I opened https://cm-jira.usa.gov/servicedesk/customer/portal/5/GSAW-77 but GSA is waiting on us to upload a password-encrypted certificate/key. I have no idea of others (once you all have Jira accounts) will be able to view/edit the request.

However, based on the discussion today, it sounds like we will work on the [route53 issue](https://github.com/GSA/datagov-deploy/issues/1001) and skip the redirect. It has about the same level of waiting on external teams, but puts us in a better place going forward (having control of our own DNS).

**Comment by jbrown-xentity** [comment]
We have moved to route53 to manage DNS, this is no longer necessary.

**Comment by mogul** [comment]
We determined that using the A/ALIAS record for data.gov to point to www.data.gov would result in the site being available at both URLs with no redirect, which isn't desirable. So we're going back to implementing a redirect. At the same time, we've decided the canonical URL should be data.gov, not www.data.gov.

We'll be using [our existing method for handling subdomain redirects](https://github.com/GSA/datagov-website#www-redirects) to implement the www.data.gov -> data.gov redirection. The story and ACs were updated accordingly.

**Comment by mogul** [comment]
Next steps: 

1. Approve and merge [this PR](https://github.com/GSA/datagov-website/pull/24) (which enables our cloud.gov-hosted redirect from [www.data.gov](http://www.data.gov/) -> [data.gov](http://data.gov/)).
Make sure it deploys without incident.
1. Mark [this PR](https://github.com/18F/dns/pull/586) ready for review, and post in [#tts-tech-portfolio](https://gsa-tts.slack.com/archives/CNW3GL70S) asking for a review+merge ASAP
1. Wait for that PR to be merged and deployed
1. PARTY! Because now [data.gov](http://data.gov/) is hosted in Federalist, redirects to it are completely implemented in [cloud.gov](http://cloud.gov/), and we can push the FCS Wordpress site into the :volcano:.
