### ISSUE TITLE
Catalog map and location search not working

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3587]
On cloud.gov environment, the map is not loading in the map search, location input box does not show dropdown when clicked.

## How to reproduce

https://catalog-dev-datagov.app.cloud.gov/dataset

## Expected behavior

![image](https://user-images.githubusercontent.com/1392461/145439340-ba5cf970-663f-4008-85e6-3c50ebff55bc.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/1392461/145439459-36056591-d4a2-4533-9a48-ad091e33105c.png)
## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
We have fixed a similar issue before #3434. This time there is more, such as the location search box not loading. In Chrome if you open the dev tools and refresh page, the map loads, but location search box is still broken.

**Comment by jbrown-xentity** [comment]
Noting here, that when I do a geospatial filter I get "There was an error while searching", so maybe something is messed up with our solr config.

**Comment by nickumia-reisys** [comment]
Noting also, the map loads on staging and production, but doesn't load locally.  There has to be configuration differences, but I haven't found anything.  Also, I tried to get the search box to work by changing the `z-index` in case it was similar to the other UI bugs we were seeing, but it did not get the search box to work either.

Unless someone has specific things to try, I think this warrants a pair.
