### ISSUE TITLE
Dashboard crawl archives are not public in dashboard-s3

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3588]
## How to reproduce

1. https://dashboard.data.gov/offices/detail/49021/2014-11-30#metrics_valid_count
2. Click "Analyze archive from 2014-11-30" link

## Expected behavior
Browser downloads the archive file

## Actual behavior

403 S3 error

## Sketch

- [x] update [s3-migration script](https://github.com/GSA/datagov-s3-migrate) to run on cloud.gov
- [x] update s3-migration script to parse src/dest from vcap services
- [x] create a new basic-public dashboard-s3-public service
- [x] run the script in cloud.gov to migrate dashboard-s3 to dashboard-s3-public
- [x] use cf rename-service to update dashboard-s3
- [x] cf restart dashboard
- [x] run cf delete-service on the non-public dashboard-s3 service

**Comment by adborden** [comment]
I have this running in staging now.

**Comment by adborden** [comment]
The improvements to https://github.com/GSA/datagov-s3-migrate to run on cloud.gov are working, but I realized the original s3-migrate script ended up copying 0 byte files 😱  That means we have to migrate the dashboard s3 bucket again.

The silver lining is that this round, we're copying the entire FCS bucket over to cloud.gov. Then each application can copy app-specific files via the bucket prefix (e.g. /datagov/dashboard/) to an application bucket within cloud.gov using a single run-task. The staging and production s3 copying is happening now.

**Comment by adborden** [comment]
Staging fcs-lifeboat copy completed successfully.
```
real    1163m40.736s
user    90m0.191s
sys     53m49.629s
```

**Comment by nickumia-reisys** [comment]
There is a new error `NoSuchBucket`.  Do we have to change something else for the bucket name to update?
![image](https://user-images.githubusercontent.com/85196563/146227742-b5070b89-1fb2-423e-a8db-ceafb3c0ee27.png)
![image](https://user-images.githubusercontent.com/85196563/146227654-9887f7c7-e3a2-4494-a2ea-58b07c2ea598.png)

**Comment by nickumia-reisys** [comment]
Use this link to showcase success: https://dashboard.data.gov/offices/detail/49015/2017-05-31#metrics-datajson-analyze-archive

**Comment by mogul** [comment]
Thank you @nickumia-reisys! Moved to `Done`.
