### ISSUE TITLE
pyproj blocks catalog build on Python 3.9+

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3607]
Catalog: `pyproj` wheel fails to build on `python 3.10`.  We are not sure if we can upgrade `pyproj` because upstream `ckanext-spatial` has pinned the package to 2.6.1.  This may be able to be upgraded.

Inventory: `Markdown` 

As a mitigation, catalog has been pinned to `python 3.8.x`

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by hkdctol** [comment]
Will move to product backlog just for the check of status, before we decide how to proceed

**Comment by nickumia-reisys** [comment]
Upstream CKAN is still relying on Python 3.7 for their tests.  Python 3.7 also has an EOL in June 2023 (long enough that we think dependencies may be resolved upstream before this date).  Cloudfoundry will likely support Python 3.7 until that time.

Please refer to [slack discussion](https://gsa-tts.slack.com/archives/C2N85536E/p1655906827558949) for current status.
- https://github.com/GSA/catalog.data.gov/pull/478

**Comment by hkdctol** [comment]
@nickumia-reisys just going through milestones tickets -- what's the status of this one as far as upstream?

**Comment by nickumia-reisys** [comment]
The `pyproj` issue has been resolved.  Upstream has different requirements for [`Python<3.9 and Python>=3.9`](https://github.com/ckan/ckanext-spatial/blob/bae9290395b252ee8e40056256fa694569d1d78b/requirements.txt#L8-L9).  

Commit that upgrades `pyproj` + `Python 3.9`: https://github.com/GSA/catalog.data.gov/commit/86b0ffe933aca443e84a9696aef66ccbeb881895

<hr>

> Inventory: `Markdown`

This other part of the ticket is still an issue but it blocks `Python 3.10` and is tracked in the following issue:
- https://github.com/GSA/data.gov/issues/4056

<hr>

This issue can be safely closed.
