### ISSUE TITLE
Inventory agency user screen initially does not show datasets

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3614]
When logged in as editor/admin on inventory, initially no datasets are listed

## How to reproduce

1. Log in to inventory.data.gov as Editor/Admin
2. Go to organization and select

## Expected behavior

When logged in as agency user, there should be a list of agency datasets, for GSA organization, it is 308 datasets

## Actual behavior

No datasets display, with a filter(?) for "read"
If you x out the "read" filter, all the datasets display

![Screen Shot 2021-12-22 at 3.22.05 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/ceee11d6-ae14-4b6e-895f-23ad9ed7b849)![Screen Shot 2021-12-22 at 3.38.33 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/fbc89b12-109a-4c1b-96e6-a3bb84691578)

**Comment by nickumia-reisys** [comment]
I found the problem.. but still trying to track down where it's being set,
![image](https://user-images.githubusercontent.com/85196563/164248961-5ee2ed41-ff1d-47e5-a732-c568b21b3713.png)

If we remove the `?action=read` from the url link, the organization page loads fine.  Seeing as how we don't customize templates for inventory nearly as much, if at all, compared to catalog, I'm inclined to say it's an upstream bug.   @jbrown-xentity @FuhuXia If you have any ideas on where how this URL is generated, it would be appreciated 😄

**Comment by nickumia-reisys** [comment]
To further demonstrate the bug, if we put anything in that field, it will populate the tag with the same text, 
![image](https://user-images.githubusercontent.com/85196563/164250094-f90342df-65bb-41d0-8860-327d22bc0c76.png)

**Comment by jbrown-xentity** [comment]
@nickumia-reisys this looks suspicious upstream... https://github.com/ckan/ckan/blob/2.9/ckan/templates/organization/snippets/organization_item.html#L14
You could try reproducing this locally, and copying the template and replacing content to see what's going on. I do think it's a problem with the organization list template; clicking on anything in the organization list sends you to the "wrong" URL with the extra parameters it shouldn't have. Simply removing the extra parameters should fix it...

**Comment by jbrown-xentity** [comment]
I'm leaning towards the idea that organization/group "types" were more explicitly handled in 2.9; so if the organizations were created cleanly in 2.9 then the data in the DB would look differently. I would start with a clean DB locally and see if this problem arises; if it doesn't then we have some DB additions to make into our prod 2.8 db. If it does happen locally, then something is wrong upstream that we need to raise...

**Comment by nickumia-reisys** [comment]
I hadn't yet read @jbrown-xentity's comment above, but I think I've found a temporary solution and I've tested locally that it works..

For future reference, the hierarchy of files that generate the organization page is,
- [ckan/templates/organization/index.html](https://github.com/ckan/ckan/blob/master/ckan/templates/organization/index.html)
- [ckan/templates/organization/snippets/organization_list.html](https://github.com/ckan/ckan/blob/master/ckan/templates/organization/snippets/organization_list.html)
- [ckan/templates/organization/snippets/organization_item.html](https://github.com/ckan/ckan/blob/master/ckan/templates/organization/snippets/organization_item.html)

I've traced down the change to [this commit](https://github.com/ckan/ckan/commit/ff1afa59ca81d36a946b04a9adb0604d2e3b109c#diff-024c95332db1746be8e923d93c34aa0a05556203511fe228d40c2bbb4b05ddbbL13-R15)

This is the [`url_for` function](https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L309) that's generating the URL as well.

I was able to implement a temporary workaround shown in https://github.com/GSA/inventory-app/pull/432

**Comment by nickumia-reisys** [comment]
Fixed by 
- https://github.com/GSA/inventory-app/pull/433
