### ISSUE TITLE
Data.json export not working on inventory.data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3616]
When agency user attempts to download data.json by clicking on either Unredacted Inventory or Redacted Inventory buttons, there is a system error

## How to reproduce

1. Log in as agency user
2. Click on either Unredacted Inventory or Redacted Inventory

## Expected behavior

User gets a download of a folder with data.json and error log

## Actual behavior

System error message and no download

![Screen Shot 2021-12-22 at 3.29.48 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/12f9b602-10d6-4f86-831c-e9b93f66b097)

**Comment by FuhuXia** [comment]
Detailed error message in the log:
```
<class 'AttributeError'> : blueprint.py : 197 : module 'string' has no attribute 'split'
...
...
...
  File "/home/vcap/deps/1/src/ckanext-datajson/ckanext/datajson/blueprint.py", line 45, in generate_redacted
    return generate('redacted', org_id=org_id)
  File "/home/vcap/deps/1/src/ckanext-datajson/ckanext/datajson/blueprint.py", line 85, in generate
    resp = Response(make_json(export_type, org_id), mimetype='application/octet-stream')
  File "/home/vcap/deps/1/src/ckanext-datajson/ckanext/datajson/blueprint.py", line 234, in make_json
    return write_zip(data, error, errors_json, zip_name=export_type)
  File "/home/vcap/deps/1/src/ckanext-datajson/ckanext/datajson/blueprint.py", line 333, in write_zip
    zf.writestr('errorlog.txt', error.encode('utf8').replace("\n", "\r\n"))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by FuhuXia** [comment]
It is fixed and pushed to the production.
