### ISSUE TITLE
Weak Ciphers Enabled - Netsparker scan Dec 2021

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3622]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.1vncr2nb12rj)._

**Date of report:** 2021-12-29
**Severity:** Moderate
**Due date:** 2022-03-29

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by mogul** [comment]
I believe this may be [another false-positive](https://cloud.gov/docs/compliance/domain-standards/#ssltls-implementation).

**Comment by robert-bryson** [comment]
As per [@pburkholder's comment](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1647039859733149?thread_ts=1647021005.693449&cid=C09CR1Q9Z) to my mis-copied screenshot: "The finding is an operational requirement until [cloud.gov](http://cloud.gov/) updates their available ciphersuites". Closing and marking as resolved.
