### ISSUE TITLE
Dashboard Long Crawl failed

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3626]
https://github.com/GSA/project-open-data-dashboard/runs/4679297084?check_suite_focus=true

## How to reproduce

1. Re-run [long crawl action](https://github.com/GSA/project-open-data-dashboard/actions/workflows/crawl-long.yml)

## Expected behavior

Long crawl kicks off successfully (can't wait to see if completes successfully, as job will take longer than 6 hours)

## Actual behavior

Crawl fails to start

## Sketch

It might just be that the script isn't executable? Not sure...

**Comment by robert-bryson** [comment]
Will check back with this once the long crawl completes. (6-24hrs?)

**Comment by robert-bryson** [comment]
![image](https://user-images.githubusercontent.com/91547795/157504011-2a20b78d-4dcc-4544-a429-55943c08219d.png)

`cf tasks dashboard` in `prod` space to check. Looks like task id `165`.

**Comment by robert-bryson** [comment]
![image](https://user-images.githubusercontent.com/91547795/157720252-f81fd6e0-6626-4730-a1cc-e8dc267208eb.png)
