### ISSUE TITLE
Proxy catalog traffic for scalability

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3629]
## User Story

In order to scale the amount of traffic that the `catalog` app can handle, we want to [deploy a proxy server](https://docs.gunicorn.org/en/stable/deploy.html#nginx-configuration) that will manage client requests.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN I have run `cf t -o gsa-datagov -s [staging|prod]` \
  WHEN I run `cf apps` \
  THEN I see a `catalog-proxy` app \
  AND I see that the `catalog-proxy` app is bound to the `catalog-stage-datagov.app.cloud.gov` route \
  THEN I see a `catalog` app \
  AND I see that the `catalog` app is bound to the `catalog-stage-datagov.apps.internal` route
- [x] GIVEN I have run `cf t -o gsa-datagov -s [staging|prod]` \
  WHEN I run `cf network-policies` \
  THEN I see an entry from `catalog-proxy` to `catalog`, protocol `tcp`, port `61443`

## Background

In the FCS environment, we load-test catalog by hitting Apache, which proxies traffic to gunicorn. In the cloud.gov environment, we load-test catalog by directly hitting gunicorn, with no web server acting as a proxy. The traffic being handled on the cloud.gov side is about 50% of the FCS load, and in New Relic we're seeing a lot of our time is going to request-queuing. 

We want to better match both the FCS architecture and [gunicorn's recommended deployment](https://docs.gunicorn.org/en/stable/deploy.html#nginx-configuration) by putting a web proxy in front of the catalog application, which we expect will eliminate the request-queuing time.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."

This change will stop the `catalog` app from directly handling requests from the public. As a result, the surface-area for external attackers will be limited to bugs in nginx, which is a much more constrained attack surface.

(A separate issue will be created cover moving the `catalog-proxy` app to [an egress-limited space](https://cloud.gov/2021/11/16/controlled-space-egress/), which will further tighten the security of the proxy app. We should also be able to move the `catalog` app to that space, while leaving the `catalog-harvest` and `catalog-gather` apps in the egress-permitted space.)

## Sketch

- Move the catalog app route to the `apps.internal` domain. 
  - The route would be `catalog-stage-datagov.apps.internal`
  - Update the launch command to allow requests from any IP (eg `gunicorn -w 3 --forwarded-allow-ips='*' test:app`)
- Add an [nginx-buildpack app](https://docs.cloudfoundry.org/buildpacks/nginx/) named `catalog-proxy` to the existing `manifest.yml`
  - The app can be added as a subdirectory in the catalog repo, with the app's entry in the manifest referring to that subdirectory. 
  - The content of the subdirectory should look like the [nginx buildpack test fixture app](https://github.com/cloudfoundry/nginx-buildpack/tree/master/fixtures/mainline)
  - Keep elements of [the default `nginx.conf`](https://github.com/cloudfoundry/nginx-buildpack/blob/master/fixtures/mainline/nginx.conf), [eg `{{port}}`](https://docs.cloudfoundry.org/buildpacks/nginx/#port), but add in [the recommended gunicorn config](https://docs.gunicorn.org/en/stable/deploy.html#nginx-configuration).
  - In place of `http://app_server` use `https://catalog-stage-datagov.apps.internal:61443`
    - This will [ensure the traffic between the nginx-proxy and the catalog app goes over TLS](https://github.com/cloudfoundry/diego-release/issues/587#issuecomment-999142420)
    - You can [specify the route name via an environment variable](https://docs.cloudfoundry.org/buildpacks/nginx/#env) so that there's no difference between staging and prod
- Allow traffic from the nginx proxy to the catalog app
  - `cf add-network-policy catalog-proxy catalog --protocol tcp --port 61443`
- Bind the `catalog-stage-datagov.apps.fr.cloud.gov` route to the `catalog-proxy` (and unbind it from `catalog`.
- Double-check that the `catalog` app is only bound to the `apps.internal` route.
  - If we've been deploying this all via CI, it's likely that it was never unbound from the public route.

**Comment by nickumia-reisys** [comment]
Reading about routes and domain on cloud.gov, I think this is what we need to do..
- [ ] Create private domain for staging and prod catalog
  - [ ] `cf create-private-domain gsa-datagov catalog-stage-datagov.apps.internal`
  - [ ] `cf create-private-domain gsa-datagov catalog-prod-datagov.apps.internal`
- [ ] Create routes to newly created domains
  - [ ] `cf create-route catalog-stage-datagov.apps.internal --hostname catalog` 
      - (be sure to be `staging` space!!)
  - [ ] `cf create-route catalog-prod-datagov.apps.internal --hostname catalog`
      - (be sure to be `prod` space!!)

I'll work on the rest of the tasks, but I can't do the domain/route stuff 😅 
![image](https://user-images.githubusercontent.com/85196563/149173121-4a2d518b-93cf-4de1-b19e-e629cf9ee8ed.png)

**Comment by FuhuXia** [comment]
In current FCS catalog we can set gunicorn worker 8. 
![image](https://user-images.githubusercontent.com/1392461/149192881-9ca0a5cc-3209-4f53-aca3-6d8feeab128b.png)

But in latest test result with inventory on cloud.gov, worker number more than 2 will send CPU usage to 100%. 
https://github.com/GSA/inventory-app/pull/344

It is worth another try with catalog on cloud.gov to get the best worker number.

**Comment by jbrown-xentity** [comment]
To create an internal route, use language like `cf create-route apps.internal --hostname catalog-stage-datagov`

**Comment by nickumia-reisys** [comment]
Another useful command: `cf unmap-route catalog app.cloud.gov --hostname catalog-stage-datagov`

**Comment by jbrown-xentity** [comment]
## Sketch
Follow [previous example](https://stackoverflow.com/questions/60576263/cloudfoundry-how-to-use-multiple-buildpacks-nginx-django-gunicorn):
- [ ] Add nginx buildpack in the middle of the buildpacks [here](https://github.com/GSA/catalog.data.gov/blob/main/manifest.yml#L6)
- [ ] Decide on new CKAN port (5000? dynamic?) to run in the background; can't collide with whatever is given by cloud.gov as $PORT
- [ ] Update [server_start.sh](https://github.com/GSA/catalog.data.gov/blob/main/ckan/setup/server_start.sh) to include nginx start command (and kill process)
- [ ] Update [nginx conf](https://github.com/GSA/catalog.data.gov/blob/main/proxy/nginx.conf) to point to local python service.

**Comment by robert-bryson** [comment]
I think I followed the sketch with [this](https://github.com/GSA/catalog.data.gov/pull/423/commits/2b2ec3e1a8c12b919fa0d06b5a89ab8f17a87a29) but need some guidance. Draft PR at https://github.com/GSA/catalog.data.gov/pull/423

**Comment by mogul** [comment]
Update: We've found a method to move forward with the proxy continuing as a separate app.

**Comment by robert-bryson** [comment]
After the changes yesterday, we had been having inconsistent responses from the proxy, and many issues like: 
![image](https://user-images.githubusercontent.com/91547795/156239231-8af2f2bc-5e44-4883-aa82-dabbe2a355a9.png)
 I believe this is because [by default](http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver) the resolver we added looks up both ipv4 and ipv6 address. 

Adding an `ipv6=off` tag to it seems to resolve the issue and responses are consistent.

**Comment by robert-bryson** [comment]
`cf add-network-policy catalog-proxy catalog --protocol tcp --port 61443` will need to be run in `staging` and `prod` (to allow `catalog-proxy` to route to `catalog` in those spaces). Not sure if it should be added before or after merging.

**Comment by robert-bryson** [comment]
With this [PR](https://github.com/GSA/catalog.data.gov/pull/427), catalog-proxy is deployed and working. As per above, the network-policy had to be added in stage and still needs to be added in prod. 

It is currently blocked in prod by catalog not being deployed due to solr issues I don't really understand. Once that is cleared up, the network policy will need to be addede there.

**Comment by robert-bryson** [comment]
Working now in [prod](https://catalog-prod-datagov.app.cloud.gov/dataset). Someone must have done the `cf add-network-policy`, thanks friendly stranger!

**Comment by nickumia-reisys** [comment]
@robert-bryson Sorry, I mentioned it in slack that I fixed it to get catalog up for solr testing!

**Comment by robert-bryson** [comment]
Thank you for doing it, @nickumia-reisys !

**Comment by robert-bryson** [comment]
For the eventual evidence: 

AC 1:
<img width="1199" alt="Screen Shot 2022-03-17 at 3 38 51 PM" src="https://user-images.githubusercontent.com/91547795/158829701-c401140d-ddf0-4ad7-b8d9-5ba76ef9a501.png">

AC 2:
<img width="730" alt="Screen Shot 2022-03-17 at 3 42 17 PM" src="https://user-images.githubusercontent.com/91547795/158829850-523d2af8-1f69-4c1d-b5d6-6ea13badbee9.png">

**Comment by robert-bryson** [comment]
To compliment @mogul unmapping catalog's now extraneous old external route, I deleted it: 
```
➜ cf delete-route app.cloud.gov --hostname catalog-prod-1041c49a-20d2-4f21-8bbc-e64bf739d8dd                                                                          at 18:59:01
This action impacts all apps using this route.
Deleting this route will make apps unreachable via this route.
Really delete the route catalog-prod-1041c49a-20d2-4f21-8bbc-e64bf739d8dd.app.cloud.gov? [yN]: y
Deleting route catalog-prod-1041c49a-20d2-4f21-8bbc-e64bf739d8dd.app.cloud.gov...
OK
```
