### ISSUE TITLE
BREACH vulnerability in cloud.gov from Penetration Test

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3633]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.vam7349osvj6)._

**Date of report: 2022-01-07
**Severity: Moderate 
**Due date: 2022-04-07

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by mogul** [comment]
From Peter at cloud.gov:
> This is a Low finding. The overall SSLScan score for [cloud.gov](http://cloud.gov/) apps is 93 (A+). The finding is an operational requirement until [cloud.gov](http://cloud.gov/) updates their available ciphersuites (which we’ll likely do this year). The option of turning off compression  is unacceptable because of the impact it would have on low-bandwidth users.

We'll essentially be using this same language to call this an Operational Requirement for data.gov.

**Comment by robert-bryson** [comment]
I guess Bret beat me to it, but will use this language for response. Closing and will resolve.
