### ISSUE TITLE
Inventory high error rate due to scanning/probing traffic

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3635]
We need to find a way to reduce amount of Inventory High Error Rate NewRelic alerts. When there are scanning/probing traffic hits Inventory, such as requests to /blog/mt-atom.cgi, or /bin/wcm/contentfinder/connector/suggestions.json, due to the Inventory low traffic nature, the 404 resulted from the request will generate a High Error Rate alerts.

## How to reproduce

Look at Inventory NewRelic dashboard to Error rate

## Expected behavior

Error rate < 1%
 
## Actual behavior

Error percentage > 1% for at least 5 minutes on 'inventory'

In 24 hours: 
![image](https://user-images.githubusercontent.com/1392461/149374205-d9f62d61-5ab6-456e-9162-acb600ba9c36.png)

## Sketch
1. Change Alert policy to set higher threshold for Inventory.
2. Ignore all 404s.
3. Reject non-CKAN traffic on Nginx level.

**Comment by btylerburton** [comment]
Error config for inventory has been updated to ignore 404s.

**Comment by btylerburton** [comment]
Zero alerts since removing 404's from the error list 5 days ago. We also have Apdex score and response time metrics still in place so we should still be aware if we have a genuine error preventing users from accessing the site. Closing this ticket as this fix addressed the issue of keeping the app generally available.

**Comment by FuhuXia** [comment]
This continues to be an issue. We see high error rate due to error message 
`405 Method Not Allowed: The method is not allowed for the requested URL.`

![image](https://user-images.githubusercontent.com/1392461/197783407-a69ad3a3-a2a4-4e99-b43c-42238e64e03d.png)

Here is some sample requests:
```
POST to /fileserver/yfceau.txt
POST to /
POST to /search.php
POST to /login/verify
```

**Comment by FuhuXia** [comment]
Multiple alerts in one day. We need to address this.

**Comment by FuhuXia** [comment]
Took the easy route and ignore MethodNotAllowed errors, so we dont have constant alerts.

**Comment by FuhuXia** [comment]
Copy discussion in the PR https://github.com/GSA/data.gov/issues/3635 here. 
> @[nickumia-reisys](https://github.com/nickumia-reisys)
> Weren't you saying that you didn't want to ignore valid errors like if a user is trying to update a resource and calls the wrong method?


> @[jbrown-xentity](https://github.com/jbrown-xentity)
> This is the better of 2 bad options; either ignore this and get notified of all other error types (where users are trying to do things they are not permitted to do), or miss valid important alerts because there are too many not actionable alerts...

**Comment by FuhuXia** [comment]
We took the 2nd approach listed in the sketch and simply ignored the all `NotFound`, `Forbidden`, and `MethodNotAllowed` errors, kind of defeating the purpose of setting up this alert. It is deployed now, hopefully no more noisy alerts from now on. But should we explore the 3rd option in the sketch?

**Comment by hkdctol** [comment]
Can close this because we are working on #4044
