### ISSUE TITLE
Solr 504 Gateway Time-out

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3636]
Solr returns a 504 Gateway Time-out with query [https://default-solr-2e001a6400465b1e-solrcloud.54a8e908-f9ea-49ea-8891-d927fd60261e.ssb.data.gov/solr/ckan/select?q=*%3A*&start=311111](https://default-solr-2e001a6400465b1e-solrcloud.54a8e908-f9ea-49ea-8891-d927fd60261e.ssb.data.gov/solr/ckan/select?q=*%3A*&start=311111) (or any query that hits deep in the pagination).

## How to reproduce

1. Hit solr with above query

## Expected behavior

Responds successfully and quickly

## Actual behavior

504 Gateway Time-out error

## Sketch

This was surfaced with deep paginations of the cloud.gov catalog site ([like this for example](https://catalog-stage-datagov.app.cloud.gov/dataset?page=10000)) taking a long time to return (around 1min). 

Probably related to https://github.com/GSA/datagov-deploy/issues/3642

**Comment by mogul** [comment]
We've increased the ingress-nginx timeout, which we believe was the source of the problem. However, we have yet to verify this as we need to complete load-testing first.

**Comment by nickumia-reisys** [comment]
Most recent result from the above query... Not sure how to interpret it yet.

![image](https://user-images.githubusercontent.com/85196563/158408388-513c6879-701c-448b-816d-764d4122c255.png)

**Comment by nickumia-reisys** [comment]
I checked this link, https://catalog-stage-datagov.app.cloud.gov/dataset/?page=1800

It still takes a long time to load, but it actually loads.

**Comment by FuhuXia** [comment]
> I checked this link, https://catalog-stage-datagov.app.cloud.gov/dataset/?page=1800
> 
> It still takes a long time to load, but it actually loads.

On staging it timed 20+ seconds for most of deep pagination pages (> 15000). On prod it was about 40 seconds, probably due to prod Solr was busy at re-indexing.

**Comment by FuhuXia** [comment]
We rarely see the 500 error. We will mark resolved.
