### ISSUE TITLE
Organization pages in general

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3639]
Organization pages are ugly with bad organization/missing icons/css and problems in general. 

Also dropdown resets on change (returns correct results, but resets the visible dropdown selection to relevance).

Happening post move to CKAN 2.9

## How to reproduce

Description of steps to reproduce the issue.

1. Visit an organization page on catalog on cloud.gov. 

## Expected behavior

An [organization page](https://catalog.data.gov/organization/allegheny-county-city-of-pittsburgh-western-pa-regional-data-center?q=&sort=title_string+desc&as_sfid=AAAAAAXn8PPzAoeDkSuUR9mT3PSLOLnaiu--3KHLvXHfkZMAB6Cp9NSim_dzdtlWREUvWCbmhVxMrn21LdTFo1-vE_LiiqrKYI6JLcR_0KFThGrmigVdHc6aYV87mtY5-tG0uJQ%3D&as_fid=a2bbca393f4b7c2c30d11cc4c8072b6286a1b080) should look like: 

![image](https://user-images.githubusercontent.com/91547795/149391846-af2a1492-20b5-4187-b25e-7cbd03ef6978.png)

## Actual behavior

An [organization page](https://catalog-stage-datagov.app.cloud.gov/organization/allegheny-county-city-of-pittsburgh-western-pa-regional-data-center) looks like: 

![image](https://user-images.githubusercontent.com/91547795/149392021-4edf75f8-9558-4abf-bbe3-dfaabb959489.png)

## Sketch

- [ ] Look at customization at why organization is displaying improperly.

**Comment by hkdctol** [comment]
@Jin-Sun-tts tested locally. Continuing to work on it.

**Comment by Jin-Sun-tts** [comment]
Pushed to main branch and tested in catalog development server.   

Updated catalog with latest version of this repo in the requirements.txt. Confirmed the fix in the stage and production UI.
