### ISSUE TITLE
https://catalog-stage-datagov.app.cloud.gov/ should redirect to /datasets

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3640]
[https://catalog.data.gov/](https://catalog.data.gov/) redirects to [https://catalog.data.gov/dataset](https://catalog.data.gov/dataset). The cloud.gov version of catalog should as well.

## How to reproduce

Description of steps to reproduce the issue.

1. Visit [https://catalog-stage-datagov.app.cloud.gov/](https://catalog-stage-datagov.app.cloud.gov/)

## Expected behavior

Redirection to [https://catalog-stage-datagov.app.cloud.gov/dataset/](https://catalog-stage-datagov.app.cloud.gov/dataset/)

## Actual behavior

Does not redirect.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
Could be done easily as part of #3629

**Comment by FuhuXia** [comment]
The redirect from `/` to `/dataset` is supposed to be done in [datagovtheme](https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/plugin/__init__.py#L79). Let us not rely on nginx config for this redirect.

**Comment by nickumia-reisys** [comment]
This is being taken care of in https://github.com/GSA/ckanext-datagovtheme/pull/109
