### ISSUE TITLE
https://catalog-stage-datagov.app.cloud.gov/user/saml2login not working

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3641]
The login link should redirect to [login.gov](https://secure.login.gov/). 

![image](https://user-images.githubusercontent.com/91547795/149393227-60b27954-cc6b-4f91-8894-94e9f6b33c67.png)

## How to reproduce

Description of steps to reproduce the issue.

1. Visit [https://catalog-stage-datagov.app.cloud.gov/user/saml2login](https://catalog-stage-datagov.app.cloud.gov/user/saml2login) (https://catalog-stage-datagov.app.cloud.gov/)

## Expected behavior

Redirection to [login.gov](https://secure.login.gov/).

## Actual behavior

403 Forbidden 

![image](https://user-images.githubusercontent.com/91547795/149393473-91b86869-7ce7-4bec-8063-1750a1f7544e.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
Confirmed, deployed (to staging and dev, prod still not available with solr).
![image](https://user-images.githubusercontent.com/26980513/156419710-2418e76c-b420-429b-a441-7e572772b3e1.png)
