### ISSUE TITLE
Topic icons missing

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3643]
## How to reproduce

Description of steps to reproduce the issue.

1. Click on the Topics dropdown on any page on [https://catalog-prod-datagov.app.cloud.gov/dataset/](https://catalog-prod-datagov.app.cloud.gov/dataset/)

## Expected behavior

Topics look like: 

![image](https://user-images.githubusercontent.com/91547795/149395383-b568de58-52ba-4594-8360-fae8367b58bc.png)

## Actual behavior

Topics look like: 

![image](https://user-images.githubusercontent.com/91547795/149395290-0903ac0e-2be5-4a55-9ea0-dea3b41e1d46.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
New content and design options will follow after,
- https://github.com/GSA/data.gov/issues/4029
- https://github.com/GSA/data.gov/issues/4141
