### ISSUE TITLE
Broken left column on dataset resources pages

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3644]
The left hand column on dataset resources pages is broken. Links are unable to be clicked, `onHover` doesn't work, CSS seems off.

## How to reproduce

Description of steps to reproduce the issue.

1. Try to interact with the left column on [dataset resources pages](https://catalog-prod-datagov.app.cloud.gov/dataset/navigation-data-for-marine-geophysical-data-collected-between-point-sal-and-refugio-sta-02/resource/0ec2024a-e383-490a-8ae1-b70ea1feba6c). 

## Expected behavior

Happily click on and interact with links on pages [like this](https://catalog.data.gov/dataset/multibeam-bathymetry-data-collected-in-2018-offshore-of-cedar-key-florida/resource/510b6ce1-f716-4836-81bc-e89b274028f0?inner_span=True):

![image](https://user-images.githubusercontent.com/91547795/149395939-cc15bb10-8301-4a48-9864-167427dacb18.png)

## Actual behavior

Unhappily, unable to click on links [like this](https://catalog-prod-datagov.app.cloud.gov/dataset/multibeam-bathymetry-data-collected-in-2018-offshore-of-cedar-key-florida/resource/ae046495-36a6-4d32-b8b5-e281e92d4b25): 

![image](https://user-images.githubusercontent.com/91547795/149395817-0e85bf46-3d8b-4244-a7d8-26a6c93ca3f6.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

Probably related to https://github.com/GSA/datagov-deploy/issues/3646

**Comment by nickumia-reisys** [comment]
Best test proof until ckanext-datagovtheme is merged into catalog...

![image](https://user-images.githubusercontent.com/85196563/149845505-ffdef037-cd41-4ba2-bb80-79b895cbb3da.png)
