### ISSUE TITLE
Left column broken

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3646]
Seemingly sitewide on [catalog on cloud.gov](https://catalog-prod-datagov.app.cloud.gov/dataset/), the left column is not able to be interacted with and features are broken. This seems like a pretty big deal. 

## How to reproduce

Description of steps to reproduce the issue.

1. Visit https://catalog-prod-datagov.app.cloud.gov/dataset/
2. Try to click buttons on the left column

## Expected behavior

- Map loads, works as expected. 
- Filters work
- Links clickable and working correctly

![image](https://user-images.githubusercontent.com/91547795/149397821-093ecf25-55c9-4407-869a-a0e03b8496a5.png) ![image](https://user-images.githubusercontent.com/91547795/149398176-091993a9-a659-4b79-982e-2bf277104328.png) 
![image](https://user-images.githubusercontent.com/91547795/149398324-15910b15-e8ae-4d8c-8e9c-bf83efc039e8.png)

## Actual behavior

Entire  column unable to be interacted with and features not working. 

![image](https://user-images.githubusercontent.com/91547795/149397924-882bd040-371c-4c0a-b0bb-899da3ca5a6d.png)

Sometimes after refreshing the map loads, but is still unable to be interacted with: 

![image](https://user-images.githubusercontent.com/91547795/149398754-28dae3e5-2ab5-4bb3-b638-ed8431fc2ca6.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

Probably related to https://github.com/GSA/datagov-deploy/issues/3644

**Comment by jbrown-xentity** [comment]
Noting that most things are clickable, but the "load more" of tags, etc does not work. Need to figure out why.

**Comment by FuhuXia** [comment]
Instead of bringing piece by piece to the front by setting high z-index, we can bring top blocking piece down. That will solve it. I will create a PR for it.
