### ISSUE TITLE
Solr Resiliency Issues

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3647]
Component: Solr
Version: 8.11
Environment: cloud.gov

This issue is primarily for historical reference.  The specific issues may be no-ops in reality..

## How to reproduce

1. Specify solr configuration
2. Create solr service
3. Load data into solr
4. Load test (high volume or deep data)

or

1. Specify solr configuration
2. Create solr service
3. Load some data into solr
4. Wait a while
5. Try to reindex the rest of the data

## Expected behavior

Reliable Sub-200ms Response times
Resilient Operations

## Actual behavior

- Varaible (up to 2000ms) Response times

- Shard lost.  If the leader shard is lost before another replica can take over, it causes ckan to completely fail.
![image](https://user-images.githubusercontent.com/85196563/149561539-46ddc467-d087-4552-9b0f-78cab00eba6a.png)

- Search-Reindex fails... (reason unknown, suspect: Zookeeper lost)
![image](https://user-images.githubusercontent.com/85196563/149561791-11334d25-92bc-48a4-b353-4d4439cdc5db.png)
![image](https://user-images.githubusercontent.com/85196563/149561341-95b97ba1-c06d-4769-90f8-0b24735d300b.png)
![image](https://user-images.githubusercontent.com/85196563/149562162-f03af958-0ffa-40ad-97be-2cfc4bf52c05.png)
![image](https://user-images.githubusercontent.com/85196563/149562268-6515b4a8-9d07-4a71-b8d8-0ea59569081d.png)

## Sketch

[TO DO]

## References

- Here's a short review of someone [optimizing solr performance](https://tech.olx.com/improving-solr-performance-f4202d28b72d) in their own system.  A few of the concepts are helpful.

**Comment by nickumia-reisys** [comment]
I think we've proven that solr is not resilient across changes.  If we define a specification and let it run, it's stable.  But if we `update-service`, solr has a high probability of breaking..

More References for the future:
- Solr Performance Data, https://cwiki.apache.org/confluence/display/SOLR/SolrPerformanceData
- https://cwiki.apache.org/confluence/display/SOLR/SolrPerformanceFactors
- https://stackoverflow.com/questions/55081729/how-many-shards-are-proper-for-each-collections-in-solr
- https://cwiki.apache.org/confluence/display/solr/SolrPerformanceProblems

**Comment by jbrown-xentity** [comment]
After discussion, we want to be able to raise the RAM limit that is hardcoded in the code.
- Update [solr brokerpak](https://github.com/GSA/datagov-brokerpak-solr) to allow for variable node size (RAM)
- Merge and tag the release
- Utilize this tag in the ssb broker to create more nodes and specify RAM (~32G)
Focus on prod, but do in parallel on staging.

**Comment by nickumia-reisys** [comment]
`datagov-brokerpak-solr` change: 
- https://github.com/GSA/datagov-brokerpak-solr/pull/30

`datagov-ssb` change:
- https://github.com/GSA/datagov-ssb/pull/113

`catalog.data.gov` change:
- https://github.com/GSA/catalog.data.gov/pull/405
  - [CKAN Collection parameters](https://github.com/GSA/catalog.data.gov/pull/405/commits/f4daaec28cb591cc1db2c9dfc9737f724c1f10e8#diff-ac6c240902b96a5b02db6a238395c0f3fe8454296147ef92aa8a5f0b0505abcdR51)
  - [Solr Service parameters](https://github.com/GSA/catalog.data.gov/pull/405/commits/0c4d558c0c5299c699ccc41584f316ed27e9273c)

**Comment by nickumia-reisys** [comment]
This is more of a historical issue now.  It is specifically related to Solrcloud which we have abandoned in favor of the stability of Solr on ECS.  Investigation into this would be covered by the following ticket.  Although the specific investigation of SolrCloud would need to be a deliberate effort,
- https://github.com/GSA/data.gov/issues/3956

As more context for the future, per @jbrown-xentity, 
> Due to load/compatability issues, we do not plan to use solr cloud without significant research and development.
