### ISSUE TITLE
Renew data.gov site certificate and host certificate

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3649]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report: 
**Severity: N/A
**Due date: 2022-01-30

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
For catalog hosts in BSP environment.

**Comment by FuhuXia** [comment]
Four servicenow tickets created:
1. REQ0662893 for data.gov site certificate.
2. REQ0662904 for staging host certificate.
3. REQ0662906 for mgmt host certificate.
4. REQ0662909 for production host certificate.

**Comment by FuhuXia** [comment]
The three host certificates were generated. But upon examining the existing host certificates, we realized the existing ones are good until Nov 3 of 2022 and Apr 10 of 2023. FCS were looking at old certs and mistakenly notified us the wrong date. We will keep the new cert PEM file and update when it is time.

We are still waiting for the data.gov site certificate.

**Comment by FuhuXia** [comment]
Talked to Samuel Mcgehee. Hopefully we will have site certificate issued today or tomorrow. Will coordinate with FCS to set up a time to have it installed.

**Comment by FuhuXia** [comment]
Created servicedesk ticket REQ0664497 to add add a TXT DNS record on data.gov required by digicert for domain ownership proof. 

UPDATE: For future reference, this ticket should be created as a DNS Request, so that it will automatically be assigned to CISO.Firewall team for quick response.

**Comment by FuhuXia** [comment]
_dnsauth.data.gov TXT record is now created. Waiting for digicert to issue the cert.
```
$ dig _dnsauth.data.gov txt | grep "ANSWER SECTION" -A 1
;; ANSWER SECTION:
_dnsauth.data.gov.	3058	IN	TXT	"7cqdjv5g2yjh9gccmp3yxsxgqvcz89rz"
```

**Comment by FuhuXia** [comment]
DigiCert issued the certificate. Request number REQ0664644 created to have FCS network team and SecOps install the certificate, scheduled later today.

**Comment by FuhuXia** [comment]
New certificate is imported into AWS Certificate Manager. CloudFront is showing the new certificate with expiry date January 26, 2023. 

Scheduled to install it on FCS 5pm today.

**Comment by FuhuXia** [comment]
New site certificate for data.gov from DigiCert is deployed on FCS. All *.data.gov site on FCS is showing January 26, 2023 as expiry date.

![image](https://user-images.githubusercontent.com/1392461/151453239-721a9e2a-ccf9-4f9a-91ff-98b8368fb72a.png)

**Comment by FuhuXia** [comment]
More discussion in [slack](https://gsa-tts.slack.com/archives/C2N85536E/p1643323976014800?thread_ts=1643320724.014400&cid=C2N85536E).

**Comment by jbrown-xentity** [comment]
While the installation is done, cleanup is still in progress (@FuhuXia keeping tabs on latest discussions)
