### ISSUE TITLE
Dashboard Validator gives 503 error on big data.json file

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3663]
When the uploaded data.json file is more than a few megabytes, or the linked url is a big data.json file, Dashboard Validator gives 503 Service Unavailable error:
```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

## How to reproduce

Validate a data.json file 5 MB in size.

## Expected behavior

200 response code

## Actual behavior

60-70 % of validate requests, it gives 503 error with message as described  above. It responds with 200 code for other requests.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
May be happening due to the small memory reserved for the dashboard app. We can probably raise that again now that we have additional memory quota available.
