### ISSUE TITLE
[SC-7] Restrict egress traffic from EKS workloads by default, allow by configuration 

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3665]
## User Story

In order to meet the intent of SC-7 (and sub-controls), EKS clusters provisioned by the SSB should restrict outbound traffic by default, and allow by exception/explicit configuration.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

Outbound: 
- [ ] GIVEN I have provisioned an EKS cluster through the SSB \
  AND I did not configure allowed outbound CIDRs during provision \
  WHEN I `kubectl ssh` into a pod \
  AND try to ping well-known public IPs \
  THEN the traffic is blocked.
- [ ] GIVEN I have provisioned an EKS cluster through the SSB \
  AND I configured allowed outbound CIDRs during provision \
  WHEN I `kubectl ssh` into a pod \
  AND try to ping an IP in those allowed CIDR ranges \
  THEN the traffic is permitted.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
NIST SC-7 says outbound traffic should be permitted by exception, not by default. We can restrict outbound IP ranges to just those configured at provisioning (or none, if none were provided) to meet the intent of this control for the SSB's managed boundary.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
Most flexible option for users of the broker (though more complex and not a core k8s feature):
- Implement hostname-based egress proxying by deploying the [Monzo egress-operator](https://monzo.com/blog/controlling-outbound-traffic-from-kubernetes).

The simplest-to-implement near-term alternative is to just implementing CIDR-based controls:

- [Deploy a default-deny k8s NetworkPolicy in each requested namespace](https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic).

**Comment by mogul** [comment]
> ## Sketch
> [...]
> Two alternative options for implementing CIDR-based controls:
> 
> [...]
> * [Deploy a default-deny k8s NetworkPolicy in each requested namespace](https://github.com/monzo/egress-operator#blocking-non-gateway-traffic). (customizable per-namespace)

I said in our meeting today that I thought the VPC-CNI add-on for EKS would be sufficient for us to implement a default-deny `NetworkPolicy`, but I was wrong... We still need Calico to do that. Luckily [installing and validating Calico is pretty easy these days](https://docs.aws.amazon.com/eks/latest/userguide/calico.html).

**Comment by mogul** [comment]
Note that [the monzo-operator hasn't been touched in 11 months](https://github.com/monzo/egress-operator), so it may no longer be a first-choice solution.

**Comment by nickumia-reisys** [comment]
Resources Used:
- [AWS Install Calico](https://docs.aws.amazon.com/eks/latest/userguide/calico.html)
- [Calico Helm Instructions](https://projectcalico.docs.tigera.io/getting-started/kubernetes/helm)
- Terraform [kubernetes_namespace](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/namespace)
- Terraform [kubernetes_network_policy](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/network_policy)

**Comment by nickumia-reisys** [comment]
There's no way to implement a network policy that applies to all namespaces, so we must do them individually 😢 

https://kubernetes.io/docs/concepts/services-networking/network-policies/#what-you-can-t-do-with-network-policies-at-least-not-yet

**Comment by mogul** [comment]
That's fine, we can do that with a `for_each` resource. Besides, right now we're brokering only one namespace, `default`.

**Comment by mogul** [comment]
For future reference: Replacing Calico with Cilium would give us DNS-based egress control (like the Monzo operator) and mTLS between pods as well as many other service-mesh features.
https://cilium.io/
