### ISSUE TITLE
Netsparker scan finds missing HSTS directives on cloud.gov apps

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3666]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.agw7w131ftue)._

**Date of report:** 2022-01-28
**Severity:** Moderate
**Due date:** 2022-04-28

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by jbrown-xentity** [comment]
This may be a false positive.

**Comment by mogul** [comment]
In particular:

- The domains in question have no subdomains so the directive would not be doing anything even if it was present.
- The data.gov root domain is already in the HSTS preload list with subdomains included.

**Comment by jbrown-xentity** [comment]
data.gov root domain was fixed with preload yesterday; we should be able to verify on the next scan.
Currently inventory.data.gov is preloaded.

**Comment by FuhuXia** [comment]
Mark it as false positive.
Netsparker scan still reported `preload directive not present`  in 2022-03-28  scan.

**Comment by FuhuXia** [comment]
All *.cloud.gov and *.data.gov subdomains are validated  HSTS preloaded.


![image](https://github.com/GSA/data.gov/assets/1392461/4bd9c936-00cb-4622-b008-15984a875c30)

![image](https://github.com/GSA/data.gov/assets/1392461/b34d509a-7099-4d13-9776-fb4528b4ceba)

**Comment by btylerburton** [comment]
Isn't the violation for not having the directive in our HTTP response?

I tried both CDN and Cloud.gov Admin and still get the same response that raised the violation in the headers.

<img width="1270" alt="Screenshot 2024-01-30 at 6 18 37 PM" src="https://github.com/GSA/data.gov/assets/104455281/0c70aeff-d306-4eb1-8404-c528d290626f">

<img width="1278" alt="Screenshot 2024-01-30 at 6 18 13 PM" src="https://github.com/GSA/data.gov/assets/104455281/f3cce927-426d-4831-82c4-e43bc31f0fd2">

**Comment by btylerburton** [comment]
Based on this SO answer, we may have had it configured correctly in the past and now we're just skating by? https://stackoverflow.com/a/71385852

**Comment by FuhuXia** [comment]
@btylerburton 
1. if a top domain has `includeSubDomains` and `preload` directives, then all its subdomains are covered. you can verify this by checking any existent or nonexistent subdomain such as `abc.data.gov` at https://hstspreload.org/. that is why we mark this issue false positive. 
2. data.gov top domain does not have `includeSubDomains`, even we verified that all its subdomain are preloaded. So we create [a ticket](https://github.com/GSA/data.gov/issues/4575) for it just to close the loop.
