### ISSUE TITLE
EKS nodes meet CIS hardening benchmarks

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3668]
## User Story

In order to ensure all EC2 instances meet CIS hardening benchmarks, data.gov wants managed node groups underlying EKS instances to use the [AMI provided by GSA ISE](https://github.com/GSA/odp-jenkins-hardening-pipeline).

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN the GSA AMI's are deployed to EKS \
  WHEN I look at the [EC2 Instance](https://console.aws.amazon.com/ec2/v2/home?#Instances:) tagged with the eks cluster \
  THEN I see the GSA AMI (which is not the one pictured below; that's just showing where you'd check)

![image](https://user-images.githubusercontent.com/85196563/153020702-bf01b893-cf1a-47bf-ad63-c5fbbf93c8dc.png)
![image](https://user-images.githubusercontent.com/85196563/153020494-1238f995-ba52-4e0d-8692-6ccc5364ea84.png)

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This will improve security by hardening the EKS AMI.

## Sketch

- [x] Ensure [the GSA-hardened AMI is available in each AWS account](https://docs.google.com/forms/d/1YozYgs8UQMGkIzalyLRl8NIV3gZuhFmzqXHo-iuiwEY/viewform?edit_requested=true) (production already available, dev and staging requested)
  - Note the GSA contacts here are Jeremy Gillikin and Kannan Chithiraputhiran
- [x] Set the EKS module to use that AMI for the Managed Node Groups we create
  - See [Step 5 in the EKS module documentation](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest#node-group-configuration)
  - Per the docs there, you may also need to deal with [the custom AMI bootscript](https://github.com/GSA/odp-jenkins-hardening-pipeline#bootscript)

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
The images `AMI ISE-AMZ-LINUX-EKS-v1.21-GSA-HARDENED*` are now available in the SSB production account. I've asked for them to also be made available to our staging and development accounts.

**Comment by mogul** [comment]
Note the images don't show up in searches by default... From [this link](https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#LaunchInstanceWizard:)  in the production account (us-west-2 region)I had to select `My AMIs` and then check the box for `Ownership> Shared with me` before they showed up in the list of available AMIs.

**Comment by hkdctol** [comment]
Awaiting response from GSA Security folks. @mogul checking and added datagov help email to thread

**Comment by nickumia-reisys** [comment]
@mogul I tried checking that the images are there and it doesn't look like the images show up when I'm using the SSBDev Role in production.. is there something I'm missing? 
![image](https://user-images.githubusercontent.com/85196563/160453121-5e5fdc69-b644-4d11-88ab-321b0da04367.png)

**Comment by mogul** [comment]
I'm no longer seeing them with the SSBAdmin role either. I will ping in the email thread!

**Comment by mogul** [comment]
Here's a [direct link to the list](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=private;v=3;owner=752281881774;imageName=:ISE-AMZ-LINUX-EKS-v1.21-GSA-HARDENED)... I think we weren't seeing them because we were looking at `us-west-2` instead of `us-east-1`.

**Comment by nickumia-reisys** [comment]
Gotcha.  I'm currently copying them to the correct region.  I'm also going to share the one in the production account with our staging and development accounts, since they still don't show up there.
![image](https://user-images.githubusercontent.com/85196563/160462401-bc56971a-a226-44bb-9535-66d6c938a5f8.png)

**Comment by mogul** [comment]
Yup, that's the right thing to do according to Jeremy. That process should be a candidate for automation in the future... Jeremy said in the email thread that they only maintain/share the most recent two releases.

**Comment by mogul** [comment]
AWS Inspector no longer checks for CIS hardening, but I think I saw a RunCommand that does it somewhere in SSM when we were first poking around. If that exists it might be worth adding as a task in the maintenance window. I don't know where/how to report back findings, though... maybe there's already something in the task that does that?

**Comment by mogul** [comment]
I think this is it:
https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-chef-inspec.html

Potentially useful benchmarks in the referenced list:
https://github.com/dev-sec/cis-dil-benchmark
https://github.com/dev-sec/cis-kubernetes-benchmark
https://github.com/dev-sec/linux-baseline

Maybe implementing this is a separate issue... 🤔

**Comment by nickumia-reisys** [comment]
Currently working through this issue.  It seems specifying the ami id is not enough for the managed node group to configure itself.  Need to research what exactly we need to change to get managed node groups to use a custom ami.

P.S. The error shows up on the console too if I try to create a new launch template specifying the GSA CIS-hardened image.

![image](https://user-images.githubusercontent.com/85196563/160641079-c8d65067-1c18-4fa6-8298-4fce76dfa302.png)

**Comment by mogul** [comment]
Does item 5 here help?
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest#eks-managed-node-groups

**Comment by nickumia-reisys** [comment]
That's what I tried and hit this snag.

**Comment by nickumia-reisys** [comment]
I got something to work. but I have start from scratch and see how it likes things.  Pay no attention to the 50 node size haha..  It looks like right now it's creating a new node group everytime terraform is run which is unsual, but it may actually be correct..

![image](https://user-images.githubusercontent.com/85196563/160662655-e37784e1-f12c-431b-b714-bb8fb646ee18.png)

**Comment by nickumia-reisys** [comment]
Instructions on sharing AMIs cross-region and cross-account:
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html
- https://aws.amazon.com/premiumsupport/knowledge-center/copy-ami-region/

**Comment by mogul** [comment]
> Potentially useful benchmarks in the referenced list: https://github.com/dev-sec/cis-dil-benchmark https://github.com/dev-sec/cis-kubernetes-benchmark https://github.com/dev-sec/linux-baseline
> 
> Maybe implementing this is a separate issue... 🤔

Oh, it looks like AWS moved their built-in CIS scan that was happening in AWS Inspector Classic over into Security Hub: https://us-west-2.console.aws.amazon.com/securityhub/home?region=us-west-2#/landing
![image](https://user-images.githubusercontent.com/47762/160716772-bbbed2b3-fda4-4e88-878e-5ee98b1b75b6.png)

**Comment by mogul** [comment]
> Yup, that's the right thing to do according to Jeremy. That process should be a candidate for automation in the future... Jeremy said in the email thread that they only maintain/share the most recent two releases.

Useful for this, can be driven from the CLI (and hence GitHub Actions): https://aws.amazon.com/blogs/mt/managing-aws-resources-across-multiple-accounts-and-regions-using-aws-systems-manager-automation/

**Comment by nickumia-reisys** [comment]
This fix is deployed to our production EKS cluster.  The PR is having issues passing though.

**Comment by nickumia-reisys** [comment]
😀 Just fixed the PR.  Waiting for the test to pass on CI.

**Comment by nickumia-reisys** [comment]
Confirmation that the Production EKS cluster is running the most recent (as of date) GSA ISE AMI,
![image](https://user-images.githubusercontent.com/85196563/161066419-7a45e51b-5aeb-4d1e-873f-9c9472d8ae48.png)

![image](https://user-images.githubusercontent.com/85196563/161066941-90e06e81-2e49-4976-9ee2-02f7a9e4dd3a.png)
