### ISSUE TITLE
Setup auto-scaling for Managed Node Groups (MNGs)

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3669]
## User Story

In order to avoid running out of compute resources underlying brokered SOLR instances, data.gov wants EC2 instances to be added on an as-needed basis to handle EKS workloads.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN the an EKS cluster was brokered with a desired managed node group of 1 \
  AND kubectl shows 1 node \ 
  WHEN a SOLR cloud instance is brokered with 10 replicas and 12G mem (each) \
  AND the appropriate amount of time has passed (20 min?) \
  THEN kubectl shows the number of nodes is greater than 1

## Background

AWS Managed Node Groups have autoscaling capabilitied built-in by [default](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html#managed-node-group-concepts).  However, for kubernetes to utlize the AWS capability, it needs to deploy an [autoscaling mechanism](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html) that is aware of the AWS infrastructure. (The EKS module we're using also has [an example of configuring cluster autoscaling](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/irsa_autoscale_refresh).)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
None. 

## Sketch

- [ ] Familiarize yourself with the `AWS Console`, `datagov-brokerpak-eks` and `datagov-brokerpak-solr`
- [x] Investigate whether to implement [Cluster Autoscaler](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html#cluster-autoscaler) or [Karpenter](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html#karpenter)
- [x] Pick up the [Auto-Scaler PR](https://github.com/GSA/datagov-brokerpak-eks/pull/67/files) to finish implementing a design.
- [x] Add test to verify the ACs
  - [x] Useful link: https://stackoverflow.com/questions/62146263/kubernetes-cluster-autoscaler-how-to-verify-autoscaling-is-working

**Comment by mogul** [comment]
I stumbled on a [recent blog post describing how to use Karpenter with spot instances](https://aws.amazon.com/blogs/containers/using-amazon-ec2-spot-instances-with-karpenter/).

**Comment by nickumia-reisys** [comment]
It's working!!  A node randomly appears!

![image](https://user-images.githubusercontent.com/85196563/161187040-e37f892c-efdb-4431-a4eb-a12bcd2740b1.png)
![image](https://user-images.githubusercontent.com/85196563/161187063-092d26ec-976b-4c3b-9dd6-13e0c766fc6f.png)

**Comment by nickumia-reisys** [comment]
This seems exceedingly unhelpful 😞 It started another node, but the first node never became ready... Lots of people were experiencing the issue [here](https://github.com/kubernetes/kubernetes/issues/34314)
, but alas, no resolution.  Will keep looking.

![image](https://user-images.githubusercontent.com/85196563/161187717-1d2b8e3b-a2d7-42c5-b2f1-ee214bb0aa8c.png)

**Comment by nickumia-reisys** [comment]
So happy 😭 

![image](https://user-images.githubusercontent.com/85196563/161281287-2667bba5-4d42-4f38-b7d0-e2ab2605e92b.png)

**Comment by nickumia-reisys** [comment]
🥲 
![image](https://user-images.githubusercontent.com/85196563/161281753-9faa2697-0f09-4592-a2e8-4c19dabd0fbe.png)

**Comment by nickumia-reisys** [comment]
[This is a problem](https://github.com/kubernetes/kubernetes/issues/34583) that was hit.. not sure a work-around right now.  But it might not be super important..
