### ISSUE TITLE
500 error with organization page filters on catalog

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3672]
## How to reproduce

1. Visit any organization on the [catalog-stage](https://catalog-stage-cdd4197f-65a7-450e-a34c-f24c9042f9ef.app.cloud.gov/organization/) site
2. Select any filter on left
3. See malformed page with 500 error

![Recording 2022-02-02 at 08 57 14](https://user-images.githubusercontent.com/91547795/152200832-995cbed4-fab4-4d24-b053-e894115b63fa.gif)

## Expected behavior

Page renders nicely

## Actual behavior

Page does not render nicely

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
Should check if #3630 resolution solves this bug
