### ISSUE TITLE
Encrypt EBS Volumes for EKS

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3683]
## How to reproduce

1. Description of steps to reproduce the issue.

## Expected behavior

Dynamic EBS Volumes are encrypted by default

## Actual behavior

![image](https://user-images.githubusercontent.com/85196563/153018995-03bce978-f18f-4293-be5c-a8a34cdd467a.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]
- [x] Add IAM Policy for addon to have key permissions
  - https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html#csi-iam-role
  - >If you use a custom KMS key for encryption on your EBS volumes, customize the IAM policy as needed. For example, add the following to the IAM policy and replace custom-key-id with the custom KMS key ID.
- [x] Modify the [current storage class](https://github.com/GSA/datagov-brokerpak-eks/blob/main/terraform/provision/persistent-storage.tf#L162-L168) to one that [enables encryption](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/storageclass/specs/example.yaml#L1-L16).
- [x] Ensure the ebs tests still pass.
- [x] Check the AWS Console to see if the volumes are actually encrypted

Useful resources:
- [Modifying addon configurations](https://docs.aws.amazon.com/eks/latest/userguide/add-ons-configuration.html)

**Comment by mogul** [comment]
We'll need to [configure a StorageClass that includes the `encrypted: "true"` setting](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/storageclass) at EKS provisioning time.
