### ISSUE TITLE
Mysterious Unencrypted EBS Volume

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3694]
EKS Brokerpak v2.3.2+

## How to reproduce

1. Bring up an EKS Cluster

## Expected behavior

All Volumes are encrypted.

## Actual behavior

New volumes using our custom `ebs-sc` (ebs storage class) are encrypted.  (This was verified in https://github.com/GSA/datagov-deploy/issues/3683)  However, during startup there is a volume that mysteriously gets created and is not encrypted.

![image](https://user-images.githubusercontent.com/85196563/154722967-caabff0b-60a5-4464-955a-6bcfcb54c6a2.png)

## Sketch

- [x] Determine what's creating the volume
- [ ] Update the thing creating the volume to ensure it specifies the encrypted volumes should be used.
  - There's a way to specify attributes for the EC2 nodes that get used in our Managed Node Groups in [AWS' Terraform EKS module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest?tab=inputs), which we're using. We need to do that! [Start here.](https://github.com/GSA/datagov-brokerpak-eks/blob/ce40c4302a4fb568cf52591203141ba0ce2cb401/terraform/provision/eks.tf#L84-L97)

**Comment by mogul** [comment]
I'm pretty sure that the EBS volume we're seeing here is the volume attached to the managed-node group EC2 instance. We are not setting any parameters that we could be to ensure MNGs use encrypted volumes by default. In other words this is unrelated to the PVC/CSI work we did recently.
