### ISSUE TITLE
Inventory uses SOLR 8

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3697]
## User Story

In order to [goal], [stakeholder] wants [change].

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
Inventory is now successfully running with Solr 8 in development space, https://inventory-dev-datagov.app.cloud.gov/dataset/
![image](https://user-images.githubusercontent.com/85196563/158035442-262050a2-b7e8-48e0-97ef-e3c8736c0460.png)

It is using the `ssb-solrcloud` broker and had no issues creating a Solr 8 cluster,
![image](https://user-images.githubusercontent.com/85196563/158035809-6abd9a3e-82ce-488f-a9a5-41ebe0a234fb.png)
![image](https://user-images.githubusercontent.com/85196563/158035814-f2e0c8bd-75af-4039-ae7c-4df6d6b36d21.png)

Upon relevant review and discussions, we can update Inventory to Solr 8 at any time.

**Comment by nickumia-reisys** [comment]
I tried running a search-index-rebuild but there was no data in the DB.  Good news is that it succeeded though haha..

![image](https://user-images.githubusercontent.com/85196563/158179574-18113961-bdfd-46c7-8d17-c88556b03c2e.png)

**Comment by mogul** [comment]
We're going to hold off on deploying this change until catalog.data.gov is also on cloud.gov and we're less worried disturbing the static deployment of EKS that underpins it.

**Comment by jbrown-xentity** [comment]
We have decided that while catalog has certain blockers, these aren't relevant for inventory. The security and other benefits from using a single stack are worth taking this work on now, instead of staying on solr 6.

@nickumia-reisys re-deployed to development workspace, and the system looks great. I tested searching on dataset title, description, email field, and publisher: all worked great. We will need to schedule around @hkdctol various showcases, and will want to deploy to staging manually to verify the re-sync will go fine as the next steps for this ticket.

**Comment by hkdctol** [comment]
Moving to blocked until SOLR8 in the SSB is production ready

**Comment by hkdctol** [comment]
Leaving in blocked for now, pending #3817

**Comment by nickumia-reisys** [comment]
Historical Issues:
- https://github.com/GSA/data.gov/issues/3826
