### ISSUE TITLE
Style data.gov/about

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3703]
data.gov/about was reported un-styled. A [quick fix](https://github.com/GSA/datagov-website/pull/29) gave it basic style but the body content is still raw-looking.

## How to reproduce

https://data.gov/about

## Expected behavior

Same style as it was on FCS wordpress
![image](https://user-images.githubusercontent.com/1392461/156050403-a99e2e54-8c08-4f10-95e9-99b9e2766f51.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/1392461/156050493-dfff3931-5647-4e8b-81fa-c823a1754e61.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by hkdctol** [comment]
We did a new version in connection with new home page, so closing this ticket

**Comment by nickumia-reisys** [comment]
New version deployed by
- #4141
