### ISSUE TITLE
Logging out of inventory-stage/catalog-stage causes 500 and fails to log out

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3708]
## How to reproduce

1. Log in to https://catalog-stage-datagov.app.cloud.gov/dataset/
1. Try to log out. 

![Recording 2022-03-03 at 09.03.00.gif](https://images.zenhubusercontent.com/615477f9d57459b3cbe8ae7a/e25dcffb-bdd1-45d9-95b7-8d2da82935da)

## Expected behavior

To be logged out

## Actual behavior

500 and still logged in

## Sketch

- [ ] Review the log, it will show the line that's responsible for this error

Check out the [log captured by @FuhuXia](https://github.com/GSA/datagov-deploy/issues/3544#issuecomment-972027883)

**Comment by mogul** [comment]
Better report of #3544

**Comment by jbrown-xentity** [comment]
We think something is wrong with login.gov saml2 implementation. To prove, we will implement our own basic local saml2 idp and verify login/logout works. If logout has similar error, then we will debug locally.
https://github.com/kenchan0130/docker-simplesamlphp

**Comment by FuhuXia** [comment]
Did some testing and found out [these changes](https://github.com/keitaroinc/ckanext-saml2auth/compare/v1.1.1...v1.2.0) in ckanext-saml2auth create the `UnsupportedBinding` error.

**Comment by nickumia-reisys** [comment]
Maybe we just don't need this class?  `Saml2Client`

https://github.com/keitaroinc/ckanext-saml2auth/compare/v1.1.1...v1.2.0#diff-a6ec9057428c583be5e30d5957777044930d96bad02075c3a49216cc5ed9b875R26-R35

And also the changes in this file? `spconfig.py`

https://github.com/keitaroinc/ckanext-saml2auth/compare/v1.1.1...v1.2.0#diff-f93bdc28690445ac844aa23fd815e5b8a06979b8841f02394ffa5a9fd1066218

This function also looks suspect.. `slo`

@FuhuXia @Jin-Sun-tts This is where the `/slo` route is defined now, https://github.com/keitaroinc/ckanext-saml2auth/compare/v1.1.1...v1.2.0#diff-378569e0e5d273cc24bfa0db31c7a4b0f82b334cd22176091c1a5fa2e00a59c7R333

**Comment by Jin-Sun-tts** [comment]
found the code where it calls the perform_slo function in the plugin.py.  Forked a version to GSA/ckanext-saml2auth, and changed the logout function. Tested on development. will deploy to master branch for production.

**Comment by Jin-Sun-tts** [comment]
![Screen Shot 2022-06-29 at 4 37 35 PM](https://user-images.githubusercontent.com/104456257/176540063-a779d72b-529b-4486-a4a5-57b5c02e3022.png)

Added 'UnsupportedBinding' exception, and also stop the further process when there is exception from the SLO.

![Screen Shot 2022-06-29 at 4 43 43 PM](https://user-images.githubusercontent.com/104456257/176541229-f89b32ac-7966-4ed8-8692-6d8334334942.png)

**Comment by Jin-Sun-tts** [comment]
![Screen Shot 2022-06-30 at 1 01 27 PM](https://user-images.githubusercontent.com/104456257/176735937-6a33b8d1-dbc0-443a-85a3-b6a30053174a.png)
Fixed in production. Will submit upstream PR.

**Comment by FuhuXia** [comment]
Can you apply same fix to Inventory?

**Comment by Jin-Sun-tts** [comment]
working on the same fix for inventory, need to find out any dependencies issue.

**Comment by Jin-Sun-tts** [comment]
This issue is fixed in inventory now.
