### ISSUE TITLE
Catalog dataset pages do not link to contact form

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3709]
Each catalog dataset page has links to "Submit Data Story" and "Report Data Issue." They previously directed to the Wordpress contact page. They should direct to the new data.gov/contact form that uses Touchpoints

## How to reproduce

Go to any catalog page and hit "Submit Data Story" or "Report Data Issue" button

## Expected behavior

Both should direct to the new data.gov/contact form that uses Touchpoints

## Actual behavior

"Submit Data Story" directs to a 404. "Report Data Issue" goes to old contact form

## Sketch

Direct both to the new contact form![Screen Shot 2022-03-03 at 3.20.53 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/fd13d127-4f13-46aa-ae8d-6902ab792e21)![Screen Shot 2022-03-02 at 5.36.03 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/64c44c95-196b-421e-94dc-64b4928c31a6)![Screen Shot 2022-03-03 at 3.19.30 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/cb8a2361-01b5-4f0a-9c48-ac017b241922)

**Comment by hkdctol** [comment]
Moving to done since we've launched catalog and dataset pages link to contact form.

**Comment by jbrown-xentity** [comment]
https://github.com/GSA/ckanext-datagovtheme/pull/115
