### ISSUE TITLE
FCS resources removed

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3710]
## User Story

In order to be secure and save resources, data.gov sysadmin want all FCS resources removed.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] WHEN we check the FCS servers \
  THEN the server is not resolvable\
  AND all databases, etc are removed.

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None. We have saved a backup of the database if we need to re-create the site locally.

## Sketch

- [x] Remove tests
- [x] Remove related Ansible playbook
- [x] Request VM and DB removal from FCS
- [x] Confirm resource removal
- [x] Turn off CircleCI
- [x] Remove AWS sandbox account
- [x] Check that FCS related entries are removed from DNS (handled in https://github.com/GSA/data.gov/issues/3949)

**Comment by FuhuXia** [comment]
In case we still need to access the content after FCS removal, I have a fully working local instance with the final db backup of 2021-11-10-production-wordpress.sql.gz.

**Comment by FuhuXia** [comment]
AWS sandbox resources are manually terminated. Need an admin user to delete the account.

**Comment by FuhuXia** [comment]
From FCS:
"most of the resources had been deleted already. To make sure no misc charges from AWS, we need to terminate these 3 accounts."

They are deleting the 3 AWS accounts 
bsp-ocsit-dev
bsp-ocsit-prod
bsp-ocsit-test

**Comment by FuhuXia** [comment]
JIRA ticket still pending, FCS hasn't provided a final confirmation. Requested an status update today via gchat.

**Comment by FuhuXia** [comment]
FCS confirmed resources are removed.
