### ISSUE TITLE
Script ECS/EKS Cleanup Procedures

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3714]
## User Story

In order to easily clean up borked eks instances, data.gov team wants to create an idempotent script that can cleanup dangling services and resources in the AWS development/staging/production accounts.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I have SSBAdmin access to an AWS account \
  AND an k8s instance ID (eg k8s-something) and subdomain (eg foo.ssb-dev.data.gov) \
  WHEN I run `bin/instance-cleanup.sh INSTANCE DOMAIN` \
  THEN I am prompted with the set of tags applied to the instance \
  AND am asked to confirm before continuing
- [ ] GIVEN I have SSBAdmin access to an AWS account \
  AND I have run `bin/instance-cleanup.sh INSTANCE DOMAIN` \
  WHEN I confirm that the script should continue \
  THEN all resources related to the instance are removed from the AWS account
- [ ] GIVEN I have SSBAdmin access to an AWS account \
  AND I run `bin/instance-cleanup.sh INSTANCE DOMAIN` \
  AND I confirm that the script should continue \
  WHEN the script encounters errors \
  THEN the errors are presented \
  AND I am advised to run the script again once resources already deleted have had a chance to be deprovisioned.

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
The script is only useful for those who already have access to an AWS account with an instance using the specified name and subdomain present, who have already placed their credentials in their environment. As these are already privileged users and they are providing the inputs by hand rather than from untrusted input, there's no security worry here.

## Sketch

- [ ] Define script inputs
  - [ ] AWS Credentials (as environment variables)
    - [ ] `AWS_ACCESS_KEY_ID`
    - [ ] `AWS_SECRET_ACCESS_KEY`
    - [ ] `AWS_DEFAULT_REGION`
    - [ ] `AWS_ZONE`
  - [ ] Instance name (replicate same hashing function to compute the k8s cluster name)
  - [ ] Subdomain
- [ ] For each step in [instance cleanup](https://github.com/GSA/datagov-brokerpak-eks/blob/main/docs/instance-cleanup.md),
  - Determine AWS CLI Command to complete the cleanup.
  - In script, correlate AWS CLI Command to List number in cleanup doc.

**Comment by mogul** [comment]
[Gruntwork's `cloud-nuke`](https://github.com/gruntwork-io/cloud-nuke) would be a good building block for this cleanup tool.

**Comment by hkdctol** [comment]
Working on #3617 and that may mean we can push this one off, moving to Icebox.

**Comment by nickumia-reisys** [comment]
Working on this ticket for only the ECS part.

**Comment by nickumia-reisys** [comment]
Overall, the work done on the ECS part helps expedite the cleanup of all resources in the development account, however, it's a scripted assist (as opposed to an automated helper).  The feature gained is:
- Check for all components of a certain type and print out relevant identifying information (e.g. tags)
- Ask for human input (yes to delete, no to keep)
- If human wants to delete it, then the script uses `cloud-nuke` to delete the resources automatically.

The next step would be more to what this ticket was actually written for, i.e. given a specific identifier, delete all AWS resources with that identifier.  It should be noted that this ticket was originally intended for EKS clusters, but will have to be re-purposed or translated into a new ticket for ECS clusters.

**Comment by nickumia-reisys** [comment]
It feels like forever since we've touched EKS/ECS/Solr things.  This is definitely not a priority anymore.  As mentioned above, it exists for the ECS stuff, but not the EKS stuff.  I'm going to close this for now.  Data.gov does not think it will move back to an EKS design in the plan-able future.
