### ISSUE TITLE
Location/Map search error on catalog

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3717]
Search by location or Map generate no results. It shows an error message:
```
No datasets found
There was an error while searching. Please try again.
```

![image](https://user-images.githubusercontent.com/1392461/157075382-5951b15b-25f2-408c-a8e8-81452e4faa34.png)
 

## How to reproduce

[Search and choose Virginia on location search](https://catalog-stage-datagov.app.cloud.gov/dataset?q=&sort=views_recent+desc&ext_location=Virginia&ext_bbox=-83.6752%2C36.5416%2C-75.2422%2C39.457&ext_prev_extent=). 

## Expected behavior

Show a list of datasets.

## Actual behavior

Error as demo'ed above.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
I think this is because the recent upgrades did not make it to staging.  I'm redeploying the last deploy action and I'll let you know if this is actually a problem.
![image](https://user-images.githubusercontent.com/85196563/157082189-051e7efe-0f94-492d-9041-14eb71ca12d6.png)

**Comment by FuhuXia** [comment]
Staging appears to up-to-date with latest fixes. I think it is solr settings.

**Comment by nickumia-reisys** [comment]
It just finished updating, and yeah, the bug is still there 😢

**Comment by nickumia-reisys** [comment]
Success! 🚀 

![image](https://user-images.githubusercontent.com/85196563/162063065-511ad298-2a6d-4e64-bed1-a21091c01639.png)
