### ISSUE TITLE
Change GitHub link in footer to proper repository

### ISSUE THREAD

**Issue by lukefretwell** [GSA/data.gov#3719]
## How to reproduce

1. Go to footer on Data.gov.
2. Click GitHub icon.

## Expected behavior

I would expect it to go to the Data.gov repository where I can submit issues and view the project board and roadmap.

## Actual behavior

It appears it's taking me to a repository that is not the correct one.

## Sketch

![Screenshot 2022-03-08 at 11-28-12 Data gov](https://user-images.githubusercontent.com/1569463/157311981-2998707f-387f-45cf-99fb-62961c9f9d00.png)

**Comment by robert-bryson** [comment]
@lukefretwell , thanks for letting us know about this! Much appreciated. 

These links on data.gov should now point to the correct repo. Though the fix PR is out, the links on catalog.data.gov will not be publicly visible immediately as we are making some infrastructure changes internally, though hopefully soon!

**Comment by lukefretwell** [comment]
Thank you @robert-bryson! Appreciate the engagement. Is there a difference between data.gov and catalog.data.gov?

**Comment by jbrown-xentity** [comment]
data.gov is a static site that we publish information on: how to use the site, how to get data published, open data blogs, etc.
catalog.data.gov is the catalog of open data, powered by CKAN. That deployment process (still in work) is at https://github.com/gsa/catalog.data.gov.

**Comment by robert-bryson** [comment]
Yes, they are separate sites. 

data.gov is a static site that was recently transitioned from a Word Press site to a site on [Federalist](https://federalist.18f.gov/). Its repo is https://github.com/GSA/datagov-website. 

catalog.data.gov is dynamic site running [ckan](https://ckan.org/) under the hood. It is in the middle of a similar but more complex transition (which is what is blocking the updating of the Github links). It is combination of https://github.com/GSA/catalog.data.gov and https://github.com/GSA/ckanext-datagovtheme.

edit: looks like @jbrown-xentity beat me to it :P

**Comment by lukefretwell** [comment]
@robert-bryson thank you. Honestly, it's all a little confusing for someone external. I'd love to collaborate and give feedback (if you want it 😛 ) but having three different repos makes it hard to discern where I should go to do what.

What would be helpful is to where to submit what, but also just see one collective project board of all the repo activity related to data.gov.

**Comment by mogul** [comment]
> having three different repos makes it hard to discern where I should go to do what.
> 
> What would be helpful is to where to submit what, but also just see one collective project board of all the repo activity related to data.gov.

Three repos would be a dream... The reality is that there's 24+ repos associated with data.gov.😬 

We'd be unable to manage the complexity ourselves without looking at it via ZenHub, which collects all of those repos onto one board. If you're wiling to log in with your GitHub ID, then you can view our board [at the ZenHub website](https://app.zenhub.com/workspaces/datagov-devsecops-579a2532d1d6ea9c3fcf5cfa/board?repos=44114489,12955910,136068192,9089664,373322046,153296282,42135842,178487997,133704507,133682447,133707812,177497769,133715954,130082947,205086683,176801704,202268378,133823738,133861312,133712387,101686186,281211047,305896342,13834532). If you're further willing to install the ZenHub browser extension, then you can [view it directly in GitHub](https://github.com/GSA/datagov-deploy#workspaces/datagov-devsecops-579a2532d1d6ea9c3fcf5cfa/board?epics:settings=noEpics&filterLogic=any&notFullScreen=false&repos=42135842,13834532,9089664,191667085,44114489,178487997,177497769,101686186,133861312,176801704,12955910,130082947,202268378,133682447,133704507,133707812,133715954,133823738,205086683,133712387,153296282,281211047,305896342&showPRs=false&showEstimates=false&showReleases=false).

**Comment by lukefretwell** [comment]
@mogul why not use GitHub org project board that let's you add multiple repos. Then you could make that public and folks wouldn't need GitHub or a browser extension. GitHub Actions is also pretty powerful. I'm not familiar with ZenHub so haven't seen all of its advantages.

**Comment by mogul** [comment]
It's only recently (with the new [GitHub Projects Beta](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects)) that GitHub boards grew enough features to make it a viable replacement for ZenHub. There is still some uncertainty if Projects included in GitHub's FedRAMP Li-SaaS compliance boundary while it's still in Beta, and we also have to do a bunch of manual migration of Epic relationships in ZenHub before we can use it. Since ZenHub is working and we've also got much bigger fish to fry, we have been holding off on migrating to GitHub projects for now.

**Comment by mogul** [comment]
The link now points to https://www.github.com/GSA/datagov-deploy. We've recently renamed that repository, but GitHub is properly forwarding clicks on that link to the new location. Going to mark this resolved. (We will make the link point to the canonical location when we do some cleanup on the Jekyll layouts in future.)

**Comment by robert-bryson** [comment]
This is a white noise fix, so I just did it while waiting on local builds to finish for my other story. See https://github.com/GSA/datagov-website/pull/34
