### ISSUE TITLE
Add JAVA_OPTS to catalina.sh to control memory heapsize as ansible variable

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#372]
export JAVA_OPTS="-Xmx={{ solr-max-memory }}"

**Comment by adborden** [comment]
@JJediny I don't see `solr-max-memory` or anything similar set in the inventory. What value should I set it to?

**Comment by adborden** [comment]
On Thu, 2018-10-04 at 11:26 -0700, John Jediny <notifications@github.com> wrote:
> this would be a `16G` on dev and `28G` on prod, but given we are
> moving to jetty as the java webserver for solr refactoring work it may
> be a null point to address this issue re tomcat6 `catalina.sh` startup
> script

Hmm, what was the original issue?


--
Aaron D Borden
Human and Hacker

**Comment by adborden** [comment]
This is configured in the group/host vars https://github.com/GSA/datagov-deploy/pull/455/files#diff-9384888b89f2e037ef6a758df8467908

**Comment by JJediny** [comment]
We are moving to jetty and the vendored playbook includes the ability to pass in JAVA_OPTS
