### ISSUE TITLE
Add 404 page for data.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3725]
## User Story

In order to have a good user experience, data.gov admins want a data.gov themed 404 page.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN a generic 404 page is created for data.gov \
  WHEN a user goes to https://data.gov/something \
  THEN I see the standard data.gov header on the page with a useful error message \
  AND a 404 is returned

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

Look at jekyll process for adding 404 or other generic error pages.

There are also 404 basic static pages that were built for cloudfront, see https://github.com/GSA/datagov-filestore-landing

**Comment by nickumia-reisys** [comment]
Waiting to do this after the [other PR](https://github.com/GSA/datagov-website/pull/32) merges.

The solution:
Adding the following into `404.md`
```
------
title: Data.gov 404
layout: legacy-page
permalink: /404.html
---

<Data.gov 404 message>
```

**Comment by nickumia-reisys** [comment]
Preliminary testing results:
- If we specify a `404.html` (specifically `.html`), jekyll will pick it up and serve.
- Similary, federalist will pick up a `404.html`, https://federalist.18f.gov/documentation/customization/
- However, `404.md` borrowing a style template won't work.  

Quick and dirty solution, create a full html page with 100s of lines of random crawled web results for header and footer.

Something that needs to be done,
- [x] Investigate the link that James posted in the issue.

**Comment by nickumia-reisys** [comment]
This is the 404 page from the link above, 
![image](https://user-images.githubusercontent.com/85196563/158222649-7afde1a6-15a6-420d-b77d-71f685d8846e.png)

I thought we wanted to keep the same data.gov web styling.

**Comment by nickumia-reisys** [comment]
Useful reference: https://github.com/jekyll/jekyll/issues/7451

**Comment by nickumia-reisys** [comment]
Success!

![image](https://user-images.githubusercontent.com/85196563/160474535-cefe3e94-dee8-4f7f-86dc-e2067ddb2192.png)

**Comment by mogul** [comment]
![image](https://user-images.githubusercontent.com/47762/161128520-9fd870d8-eb7c-4ec2-80dc-a158e27f4bb1.png)
