### ISSUE TITLE
Create a time-limited comment form for Data.gov that is present throughout website

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3726]
## User Story

In order to mark [Sunshine Week](https://www.newsleaders.org/sunshine-week-about) and to assist in ongoing user research for Data.gov, Data.gov wants to create a temporary comment form inviting users to share their comments about Data.gov that is present throughout the website.

## Acceptance Criteria

- [ ] GIVEN a user navigates to data.gov or a dataset page on catalog.data.gov \
  WHEN this use is during a defined period of time for comment collection (Sunshine Week March 13-19, or longer as determined by the Data.gov team)
  THEN the user sees a prompt to the comment form
AND there is a link to the comment form created for this.

## Background

Sunshine Week is March 13-19, 2022, an annual week with events on open government and open data. To mark the event and also to assist with ongoing user research for Data.gov, Data.gov wants to solicit comments from users to help determine the future direction of Data.gov.

## Sketch

- [x] Follow the example of the current general contact form at https://data.gov/contact/
- [x] Use the language in https://docs.google.com/document/d/1Yr0yDwg8EdsabpAHyg5z73cBhvWm1bHrTjRB5Ebnz98/edit?usp=sharing to create a new survey in [Touchpoints](https://touchpoints.app.cloud.gov/index)
- [x] Create a page for the new survey/comment page on data.gov
- [x] Create link to the comment form from Data.gov main site
- [x] Create link to the comment form from catalog.data.gov pages

**Comment by nickumia-reisys** [comment]
@hkdctol Is `data.gov/sunshine-week` a good url name for the link?

**Comment by hkdctol** [comment]
@nickumia-reisys yes I think that would be fine

**Comment by nickumia-reisys** [comment]
Does this look okay for the banner on catalog.data.gov?

![image](https://user-images.githubusercontent.com/85196563/157810879-0f8cbf74-f5ca-4db4-9157-1a6aeefb1434.png)

**Comment by nickumia-reisys** [comment]
This was the "default" banner type on the static site.  Which one do we think is better for our presentation?  I'll update either with the consolidated format.  @hkdctol @jbrown-xentity @FuhuXia @robert-bryson 

![image](https://user-images.githubusercontent.com/85196563/157874815-4aa954a1-30ee-4437-9105-88cc241744f1.png)

**Comment by hkdctol** [comment]
@nickumia-reisys I think the first one stands out more. Are there different options on color?

**Comment by nickumia-reisys** [comment]
Yes!  We can choose any color that we want.  Here's a link to some [pre-defined colors](https://materialui.co/colors/) based on the Material UI Design Standard.  We can pull colors from anywhere though.

These are [some colors ](https://designsystem.digital.gov/utilities/color/)from the USWDS page, but it's not as outlined.

**Comment by hkdctol** [comment]
@nickumia-reisys on the form https://touchpoints.app.cloud.gov/touchpoints/e445c71e/submit can "Sunshine Week" link to https://www.newsleaders.org/sunshine-week-about

**Comment by nickumia-reisys** [comment]
@hkdctol Unfortunately, there does not seem to be a hyperlink text option in formatting the touchpoints form.  I added the link as a "question" under the instructions to get it to show up as a separate block.  Otherwise, it would be meshed with the instruction block and be lost at the end.  Let me know if it's too confusing and we can add the link to the webpage itself instead of relying on touchpoints to show instructions.

So it looks like 
![image](https://user-images.githubusercontent.com/85196563/157954969-ae7ab95b-096c-4251-a9ce-2a997cf9f895.png)
Instead of
![image](https://user-images.githubusercontent.com/85196563/157954817-a704fd3d-b973-4004-a7c6-b6952cb6acad.png)

**Comment by hkdctol** [comment]
I think the first one is fine. We may leave the form up longer than the week, and at that point we'd remove the reference and the link
