### ISSUE TITLE
Proxy inventory traffic for flexibility

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3729]
## User Story

In order to handle special header and redirect needs for the `inventory` app, we want to [deploy a proxy server](https://docs.gunicorn.org/en/stable/deploy.html#nginx-configuration) that will manage client requests.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN I have run `cf t -o gsa-datagov -s [staging|prod]` \
  WHEN I run `cf apps` \
  THEN I see a `inventory-proxy` app \
  AND I see that the `inventory-proxy` app is bound to the `inventory-[space]-datagov.app.cloud.gov` route \
  AND I see a `inventory` app \
  AND I see that the `inventory` app is bound to the `inventory-[space]-datagov.apps.internal` route
- [x] GIVEN I have run `cf t -o gsa-datagov -s [staging|prod]` \
  WHEN I run `cf network-policies` \
  THEN I see an entry from `inventory-proxy` to `inventory`, protocol `tcp`, port `61443`

## Background

We have found a couple problems ([1](https://github.com/GSA/datagov-deploy/issues/3715), [2](https://github.com/GSA/datagov-deploy/issues/3689)) where having an NGINX proxy in front of inventory would enable addressing them trivially.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."

This change will stop the `inventory` app from directly handling requests from the public. As a result, the surface-area for external attackers will be limited to bugs in nginx, which is a much more constrained attack surface.

## Sketch

- Move the inventory app route to the `apps.internal` domain. 
  - The route would be `catalog-stage-datagov.apps.internal`
  - Update the launch command to allow requests from any IP (eg `gunicorn -w 3 --forwarded-allow-ips='*' test:app`)
- Add an [nginx-buildpack app](https://docs.cloudfoundry.org/buildpacks/nginx/) named `inventory-proxy` to the existing `manifest.yml`
  - The app can be added as a subdirectory in the inventory repo, with the app's entry in the manifest referring to that subdirectory. 
  - The content of the subdirectory should look like the [nginx buildpack test fixture app](https://github.com/cloudfoundry/nginx-buildpack/tree/master/fixtures/mainline)
  - Keep elements of [the default `nginx.conf`](https://github.com/cloudfoundry/nginx-buildpack/blob/master/fixtures/mainline/nginx.conf), [eg `{{port}}`](https://docs.cloudfoundry.org/buildpacks/nginx/#port), but add in [the recommended gunicorn config](https://docs.gunicorn.org/en/stable/deploy.html#nginx-configuration).
  - In place of `http://app_server` use `https://inventory-[space[-datagov.apps.internal:61443`
    - This will [ensure the traffic between the nginx-proxy and the catalog app goes over TLS](https://github.com/cloudfoundry/diego-release/issues/587#issuecomment-999142420)
    - You can [specify the route name via an environment variable](https://docs.cloudfoundry.org/buildpacks/nginx/#env) so that there's no difference between staging and prod
- Allow traffic from the nginx proxy to the inventory app
  - `cf add-network-policy inventory-proxy inventory--protocol tcp --port 61443`
- Bind the `ivnentory-[space]-datagov.apps.fr.cloud.gov` route to the `inventory-proxy` (and unbind it from `inventory`.
- Double-check that the `inventory` app is only bound to the `apps.internal` route.
  - If we've been deploying this all via CI, it's likely that it was never unbound from the public route.

**Comment by jbrown-xentity** [comment]
We are able to confirm that in catalog, the proxy should be successful running `curl https://catalog-stage-datagov.apps.internal:61443/` (once SSH'd in). In inventory, this is also successful (with the expected 403 response).

It's possible the 403 response in CKAN is causing nginx to not return the full result?

In testing this in staging, this got mucked up with a PR release; we'll need to take on #3803 in order to have a stable place outside of release workflow to test this properly.

**Comment by robert-bryson** [comment]
PR at https://github.com/GSA/inventory-app/pull/439. I believe this is ready to be merged to main as it no longer is based on the solr8 branch.

**Comment by robert-bryson** [comment]
Hotfix in prod as I had not correctly set up the network policy, but working now. Thank you @jbrown-xentity for your fixes earlier!

**Comment by robert-bryson** [comment]
For evidence, here are the inventory and inventory-proxy apps in prod with the proxy listening to the public route and the main app listening on the internal route: 
<img width="727" alt="image" src="https://user-images.githubusercontent.com/91547795/168124532-974fef7c-3553-4ed1-a3a4-0b0dcb06daff.png">

and the network policy showing traffic being directed from the proxy to the main app over port 61443: 
<img width="866" alt="image" src="https://user-images.githubusercontent.com/91547795/168124934-82e049cd-2db6-494c-a3c6-62e397a43761.png">
