### ISSUE TITLE
Ensure all EC2 instances in SSB accounts are regularly scanned 

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3733]
## User Story

In order to satisfy vulnerability scanning needs for managed node groups, the data.gov team wants to enable[ AWS Inspector](https://aws.amazon.com/inspector/?nc=sn&loc=1) in the SSB accounts.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN I am logged into the AWS Console for an account used for the SSB \
  WHEN I look at the AWS Inspector service \
  THEN I see that the service is active \
  AND that the EC2 nodes underlying EKS are in scope.

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]
Now that we've switched from Fargate to Managed Node Groups for our EKS nodes, we need to be regularly scanning and responding to results found on those hosts. AWS Inspector is a quick way to get a process in place.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This change improves our security posture by adding scanning oversight where it didn't exist before (EC2 hosts).

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

- Turn on AWS Inspector
- Make sure our EC2 node groups are in-scope and reporting is working
- Enable the same configuration using Terraform, following [this login.gov example](https://github.com/18F/identity-devops/blob/main/terraform/app/ssm.tf)

**Comment by FuhuXia** [comment]
Inspector was enabled on our AWS account to scan all EC2 instances. All EC2 instances are reported `Unmanaged` by SSM. Ran steps as described in [AWSSupport-TroubleshootManagedInstance](https://console.aws.amazon.com/systems-manager/automation/execute/AWSSupport-TroubleshootManagedInstance), it failed at ` Step 8: CheckInstanceIAM` with `AccessDenied` error. 

Sample message:
```
[SSBDev role] is not authorized to perform: iam:GetInstanceProfile on resource: 
instance profile eks-52bfca78-c89f-73fa-1596-b1f83c25369a.
```

**Comment by mogul** [comment]
Here's the AWS IAM policy role that the login.gov team uses (link above to private repository):
```hcl
# Policy and roles to permit SSM access / actions on EC2 instances, and to allow them to send metrics and logs to CloudWatch


data "aws_iam_policy_document" "ssm_access_role_policy" {
  statement {
    sid = "SSMCoreAccess"
    actions = [
      "ssm:DescribeAssociation",
      "ssm:GetDeployablePatchSnapshotForInstance",
      "ssm:GetDocument",
      "ssm:DescribeDocument",
      "ssm:GetManifest",
      "ssm:GetParameter",
      "ssm:GetParameters",
      "ssm:ListAssociations",
      "ssm:ListInstanceAssociations",
      "ssm:PutInventory",
      "ssm:PutComplianceItems",
      "ssm:PutConfigurePackageResult",
      "ssm:UpdateAssociationStatus",
      "ssm:UpdateInstanceAssociationStatus",
      "ssm:UpdateInstanceInformation",
      "ssmmessages:CreateControlChannel",
      "ssmmessages:CreateDataChannel",
      "ssmmessages:OpenControlChannel",
      "ssmmessages:OpenDataChannel",
      "ec2messages:AcknowledgeMessage",
      "ec2messages:DeleteMessage",
      "ec2messages:FailMessage",
      "ec2messages:GetEndpoint",
      "ec2messages:GetMessages",
      "ec2messages:SendReply",
    ]


    resources = [
      "*",
    ]
  }
  statement {
    sid = "CloudWatchAgentAccess"
    actions = [
      "cloudwatch:PutMetricData",
      "ec2:DescribeVolumes",
      "ec2:DescribeTags",
    ]


    resources = [
      "*",
    ]
  }
  statement {
    sid = "CloudWatchLogsAccess"
    actions = [
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:DescribeLogGroups",
      "logs:DescribeLogStreams",
      "logs:PutLogEvents",
    ]


    resources = [
      "*"
    ]
  }
}
```

To attach the policy to all the right roles (the ones used for our EC2 instances in managed node groups) follow [the two existing examples](https://github.com/GSA/datagov-brokerpak-eks/blob/8b7c4fdbbeddcdd5a4f1bdfab06efb0c733de021/terraform/modules/provision-aws/eks.tf#L126-L144).

**Comment by mogul** [comment]
[Confirmed that we should basically just need to create the policy and attach it to the EC2 service instances...](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-prereqs.html) The only thing here that requires explicit action from us is "For on-premises servers, edge devices, and VMs, create an IAM service role."

**Comment by FuhuXia** [comment]
PR is merged. Any new EC2 should be covered. Existing EC2 may need to be terminated and re-created? Or there is a way to manually attach the aws_iam_policy to exising EC2's?

**Comment by mogul** [comment]
I'll apply the Terraform manually on the instances that I'm working with in the dev account. @nickumia-reisys already applied it to the static production deployment.
