### ISSUE TITLE
Check that pycsw permissions are correct with new hardening

### ISSUE THREAD

**Issue by hareeshreddyg** [GSA/data.gov#374]
Need to check that pycsw permissions are correct with new hardening

* WSGIScriptAlias /csw /etc/ckan/pycsw.wsgi
* SetEnvIf Request_URI "/csw" PYCSW_CONFIG=/etc/ckan/pycsw-collection.cfg
* WSGIScriptAlias /csw-all /etc/ckan/pycsw.wsgi
* SetEnvIf Request_URI "/csw-all" PYCSW_CONFIG=/etc/ckan/pycsw-all.cfg

files/folders: 
**changed permissions to www-data on below status

chmod 0750 /usr/lib/ckan/bin/activate_this.py
chown -R www-data /usr/lib/ckan-new/
chown -R www-data /usr/lib/ckan
chown -R www-data /etc/ckan/**

**Comment by adborden** [comment]
With the work in https://github.com/GSA/datagov-deploy/pull/898, this issue no longer applies.
