### ISSUE TITLE
Dataset does not have harvest source or raw metadata information

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3742]
https://catalog.data.gov/dataset/north-american-rail-nodes-national-national-geospatial-data-asset-ngda-north-american-rail-node

This is probably due to a solr sync issue, or something similar

## How to reproduce

1. Go to https://catalog.data.gov/dataset/north-american-rail-nodes-national-national-geospatial-data-asset-ngda-north-american-rail-node
1. Note missing harvest information and raw metadata info

## Expected behavior

Both sections with links appear
## Actual behavior

Missing info

## Sketch

SOLR sync?
Should check in on this after cloud.gov go live, to see if re-index solved the problem.

**Comment by jbrown-xentity** [comment]
Already fixed in staging: https://catalog-stage-datagov.app.cloud.gov/dataset/north-american-rail-nodes-national-national-geospatial-data-asset-ngda-north-american-rail-node

**Comment by hkdctol** [comment]
Should be resolved once we move to cloud.gov

**Comment by hkdctol** [comment]
Leaving in blocked, should be resolved once catalog moves to cloud.gov

**Comment by chris-macdermaid** [comment]
Adding a note that the National Address Database (NAD) record is also missing its harvest information and raw metadata info.

https://catalog.data.gov/dataset/national-address-database-nad

**Comment by chris-macdermaid** [comment]
Adding a note that these NOAA records are missing their harvest information and raw metadata info.

- Geoid Height and Deflections of the Vertical Models - National Geospatial Data Asset (NGDA) Geoid Models
https://catalog.data.gov/dataset/geoid-height-and-deflections-of-the-vertical-models-national-geospatial-data-asset-ngda-geoid-m

- National Geospatial Data Asset (NGDA) NOAA Continuously Operating Reference Stations (CORS) Network
https://catalog.data.gov/dataset/national-geospatial-data-asset-ngda-noaa-continuously-operating-reference-stations-cors-network

**Comment by chris-macdermaid** [comment]
Adding a note that this Department of State record is missing its harvest information and raw metadata info.

Large Scale International Boundaries
https://catalog.data.gov/dataset/large-scale-international-boundaries1

**Comment by hkdctol** [comment]
Thought this might be done with move of catalog -- but it looks like some of the datasets listed above do not have harvest source info visible?

**Comment by jbrown-xentity** [comment]
I think this has to do with somehow having bad harvest object ID's. It was assumed that SOLR didn't have the updated harvest object ID's and that was what was causing the breakdown. It seems like the issue persisted, even after a clean SOLR sync. The harvest object ID's don't resolve to a good value/data:

- https://catalog.data.gov/dataset/geoid-height-and-deflections-of-the-vertical-models-national-geospatial-data-asset-ngda-geoid-m resolves to https://catalog.data.gov/harvest/object/4519c152-ea89-41cc-b61e-8f8a452bf661, which 404's
- https://catalog.data.gov/dataset/national-geospatial-data-asset-ngda-noaa-continuously-operating-reference-stations-cors-network resolves to https://catalog.data.gov/harvest/object/e4e083ce-7e67-43a5-aaa5-2a3d57d50114, which 404's

My gut is that there is something occurring that causes SOLR to be out of sync with the DB information, which causes problems. It's unclear if this can be solved with current ckan search-index rebuild command, or if it will require code changes. Looking at the DB and trying to rebuild SOLR index for one of these datasets might give us some clue...

**Comment by hkdctol** [comment]
@jbrown-xentity to check if this is still an issue

**Comment by jbrown-xentity** [comment]
So far all of the examples above are correct, and the download links work. Going to close this for now.

**Comment by jbrown-xentity** [comment]
Have report of datasets with the same issue, re-opening...

**Comment by chris-macdermaid** [comment]
Finding some records with a missing harvest source. These are all NOAA records. Haven't seen this with other agency records.

https://catalog.data.gov/dataset/u-s-coastal-lidar-elevation-data-including-the-great-lakes-and-territories-1996-present
https://catalog.data.gov/dataset/coastal-digital-elevation-models-dems
https://catalog.data.gov/dataset/multibeam-bathymetry-database-mbbdb
https://catalog.data.gov/dataset/nos-hydrographic-surveys-collection

**Comment by chris-macdermaid** [comment]
This DOI record is missing its harvest source.

https://catalog.data.gov/dataset/usfws-national-wetlands-inventory

**Comment by FuhuXia** [comment]
Not an issue any more. All example datasets are fine.

**Comment by hkdctol** [comment]
Closing this one as issues on this ticket were resolved
