### ISSUE TITLE
GSA - data.gov static site content migration - indefinite (whatever we can get)

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3743]
_This is the template for the 18F staffing microrequest. I'm leaving the following info about labels in place until we've filled out this issue and transferred it to the `18f/staffing` repository._
```
Required:

- Orange Vertical label
- Blue chapter label (of the Chapters you need people from)
- Purple phase label:
    
    *Pending IAA* - This project's SOW and prep survey have been submitted to the agreements process but no action is needed at this time. 
    
    *Staffing Request* - A fully executed IAA that can be billed against exists for this project and it is ready for chapter staffing leads to actually assign staff. This should be applied to all projects with a signed IAA and a current staffing need.
    
This is the applicable category. There is an existing MOU between 18F and Office of Solutions. IAA 18FSOL210003 Order #0001


    *Waiting Room* - A project that is not ready to close the issue but does not need action at this time.
    
    *Inflight* - A project that is actively underway has a new or changed staffing need.

Conditional:

- Yellow Microrequest label (if the need is for fewer than four hours total work _per week_)

Once you've applied labels and a title, delete everything above and including this sentence.
```

**Project Description**

[Data.gov](https://data.gov/) needs assistance in jump starting an effort to create a new static site. As part of our migration from our old infrastructure to cloud.gov, we decommissioned our existing WordPress site, and just brought over html into federalist.  We did not do a content review as part of that migration. There is existing old content that does not need to be brought into a new version of the site. We would like to get started on a new version using the existing template at https://github.com/18F/federalist-uswds-jekyll
There will be portions that we are not transferring to the new site (for instance, most of the Topics). Mainly it is existing Highlights/Blog posts.

- Client - Data.gov (part of Office of Solutions)
- Engagement type (Prototype)
- Travel expectation (None)
- Problem to be solved - getting a new basic Jekyll version of main Data.gov site
- Direct questions about this engagement to @hkdctol 

**Timeline**

Required:

- Duration of engagement: Dependent on availability -- if there's someone who can work on this in the next month or so, it would be helpful.
- Last date on which work can be done per the agreement: 8/22/22
- Start date: immediate--depending on availability

Optional: 
- Start date -- as soon as there is availability

**Skill type(s) needed**

- [ ] Front end/HTML/Jekyll
  - Number of weeks this role is needed: Duration of engagement
  - Hourly commitment per week: variable

**Prior to closing this issue**

- [ ] Ping @elieberkowitz that the issue is ready to close, so he can update some things.

**Comment by hkdctol** [comment]
Contacted 18F about transferring this issue to their staffing repository. They are meeting on it today.

**Comment by hkdctol** [comment]
I will ping 18F on results of their staffing meeting

**Comment by jbrown-xentity** [comment]
@hbillings the list of blog posts: https://data.gov/meta.html
The current repo (a mess) lives here: https://github.com/gsa/datagov-website

**Comment by jbrown-xentity** [comment]
@FuhuXia noted the shape of the catalog isn't easily changeable, so if we want to match it check it out here: https://catalog.data.gov/dataset.
We also should consider having an external theme that can be shared across the main site and the catalog...

**Comment by hbillings** [comment]
We are working on this [over here](https://github.com/18F/datagov-11ty/) for right now.

**Comment by hkdctol** [comment]
@hbillings checking in on status of this -- we're around if you need our input.

**Comment by hkdctol** [comment]
Awaiting a new engineer to be assigned by 18F, to do remaining work.

**Comment by hkdctol** [comment]
Will be scheduling time with 18F week of 7/18 to do handoff of current work.

**Comment by hkdctol** [comment]
Will mark this one as done and create a new ticket for remaining work on static site.
