### ISSUE TITLE
Limit brokered EKS service endpoints to cloud.gov egress IP ranges by default

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3744]
## User Story

In order to minimize the public surface area of back-end services, we want SSB-brokered k8s service instances to limit control plane client traffic to [the cloud.gov egress ranges](https://cloud.gov/docs/management/static-egress/#cloudgov-egress-ranges) by default. 

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN I have provisioned an instance of EKS \
  AND I am running commands **outside** of cloud.gov (eg on my workstation) \
  WHEN I run `kubectl get all -n default` with the broker-provided kube API endpoint URL and the broker-provided credentials \
  THEN the command errors out due to the kube API being inaccessible.
- [x] GIVEN I have provisioned an instance of EKS \
  AND I am running commands **inside** of cloud.gov (eg after running `cf ssh`) \
  WHEN I run `kubectl get all -n default` with the broker-provided kube API endpoint URL and the broker-provided credentials \
  THEN I see a normal response.
- [x] GIVEN I have provisioned an instance of EKS \
  AND I specified an allowed range of client IPs during provisioning \
  AND I am running commands from a host where outgoing traffic egresses from an IP in that range \
  WHEN I run `kubectl get all -n default` with the broker-provided kube API endpoint URL and the broker-provided credentials \
  THEN I see a normal response.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This change will reduce the public-facing surface area of provisioned EKS instances. This change mitigates the potential risk of credentials for an EKS instance being exported from cloud.gov; they won't be useful from anywhere other than the intended client ranges.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- Use the [`cluster_endpoint_public_access_cidrs` in the Terraform EKS module](cluster_endpoint_public_access_cidrs) to restrict access to the kube API to:
  - cloud.gov egress ranges by default
  - configured IP ranges if specified (eg a brokerpak parameter)

**Comment by nickumia-reisys** [comment]
~Is this a duplicate of https://github.com/GSA/data.gov/issues/3355?~

This is for the k8s admin server vs. the workload, right?

**Comment by nickumia-reisys** [comment]
Before we take this on, I think we need a formal process for interacting with EKS clusters.  Many of the developers don't have a development environment on GSA-connected computer or Cloud.gov-connected system.  Without adding individual IPs of maintainers to our configuration or code, this does not seem like an operationally efficient feature.

**Comment by mogul** [comment]
> This is for the k8s admin server vs. the workload, right?

Correct.

**Comment by mogul** [comment]
> Before we take this on, I think we need a formal process for interacting with EKS clusters. Many of the developers don't have a development environment on GSA-connected computer or Cloud.gov-connected system. Without adding individual IPs of maintainers to our configuration or code, this does not seem like an operationally efficient feature.

Note that the summary says "by default"... We can explicitly configure the GSA VPN egress ranges, or leave it wide open for now as a so-called "Operational Requirement". The point is that the defaults are sane.

**Comment by hkdctol** [comment]
If it's not a POA&M or ATO condition, we will move to Icebox for now

**Comment by hkdctol** [comment]
@mogul could you review this one when you have a chance?

**Comment by mogul** [comment]
Still seems good... What's changed?

**Comment by nickumia-reisys** [comment]
@mogul The PR is ready to be approved and merged if no changes need to be made.  The PR is just waiting your approval since the rest of the team doesn't feel as confident in giving the official sign off. 
- https://github.com/GSA/datagov-brokerpak-eks/pull/101

**Comment by hkdctol** [comment]
Sprint 05262022
