### ISSUE TITLE
Ensure High/Critical vulnerabilities in Managed Node Groups are mitigated ASAP

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3752]
## User Story

In order to ensure that High or Critical findings on live EC2 instances are addressed, the data.gov team want to automatically install patched packages that address findings whenever they are available.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN I am logged into the AWS Console \
  AND I am looking at AWS Inspector \
  AND I see a CVE detected for which an updated package is available
  WHEN the next maintenance window passes \
  THEN I see that the CVE is no longer detected

## Background

Amazon periodically releases new AWS Linux 2 AMIs for EKS that incorporate updates. However, some updates may be available between AMI versions that address CVEs, etc. We want to make sure that these updates, if they address a High or Critical finding, are installed on running instances even between the AMI update schedule. AWS Systems Manager provides a subset of functionality called Patch Manager that does this. We just need to turn it on and make sure it's running the update task on all of our EC2 instances.

Out of scope: 
- Ensuring that our Managed Node Groups are restarted with the latest AMI for our EKS version as soon as a new one becomes available. 
- Ensuring that our EKS control plane is running the latest k8s version available.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This work will make our compliance with the SI family of controls much tighter. No real downside identified.

## Sketch

- [x] In `datagov-brokerpak-eks`
  - [x] configure an [`aws_ssm_maintenance_window_target`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window_target)
  - [x] configure an [`aws_ssm_maintenance_window_task`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window_task) that will run [the default patch baseline task provided by AWS SSM Patch Manager](https://us-west-2.console.aws.amazon.com/systems-manager/run-command/send-command?region=us-west-2) on all images tagged with `eks:cluster-name` equal to the cluster name during that window

**Comment by mogul** [comment]
A nice example module for doing this:
https://github.com/cloudposse/terraform-aws-ssm-patch-manager

**Comment by mogul** [comment]
If we do end up having to define a policy for the task, there's an example of what it needs to look like here;
https://github.com/osodevops/aws-terraform-module-ssm-automated-patching/blob/master/aws_patching_iam_policy_document.tf

**Comment by mogul** [comment]
Iterated a bit on an SSM-focused IAM policy in the AWS Console (https://github.com/GSA/datagov-ssb/pull/133) and tag-based target selection (https://github.com/GSA/datagov-brokerpak-eks/pull/85) until the branch that @nickumia-reisys pushed was working locally.

**Comment by mogul** [comment]
@hkdctol: This is the issue where we set up automatic remediation of Critical and High vulnerabilities detected in our managed nodes, in which EKS runs. (The initial scans turned up just one CVE, which has already been remediated.) 

Since we never install custom code on these nodes, we expect that AWS' continuing release of patches and our ongoing adoption of new AMI baselines (which we will also automate) mean we may never have to touch them beyond this.

**Comment by mogul** [comment]
Confirmed working... We saw an OpenSSL CVE in the manually-deployed EKS. You can see the "41" here referring to how many hosts had the finding.
![image](https://user-images.githubusercontent.com/47762/159986942-b95ed241-8edd-4beb-a639-338fb86bc9da.png)

We triggered the update manually (it's automatically triggered during a maintenance window at 1pm ET), and we were able to watch the number go down gradually....
![image](https://user-images.githubusercontent.com/47762/159992514-2355a793-74de-4f09-b089-9c260f6026d9.png)

Inspector now reports they're all clean.
![image](https://user-images.githubusercontent.com/47762/159997350-b6181951-9376-4bdc-97d6-ce0096c80229.png)

QED

**Comment by hkdctol** [comment]
@nickumia-reisys on Bret's points in the above comments -- do you have screenshots or something else to export that I can set to Ryan?

**Comment by mogul** [comment]
I made sure Ryan saw the posts and screenshots above. From DM with him:

![image](https://user-images.githubusercontent.com/47762/160480922-265d535c-41d0-472c-89fe-f652403fbbe0.png)

**Comment by hkdctol** [comment]
@mogul does Ryan need anything else from us before we cut over catalog to cloud.gov version?

**Comment by mogul** [comment]
He wants to see us [use the GSA CIS-hardened machine images for our clusters](https://github.com/GSA/data.gov/issues/3668).

He's also asking about container-scanning, but AFAIK he grudgingly agrees that was not part of the original ATO conditions. I've copied you on those DMs privately.

**Comment by rpalmer-gsa** [comment]
@mogul I think you indicated that you were going to use the hardened images provided by ISE. Container scanning isn't part of original ATO conditions, but its not a sustainable gap long term.

**Comment by hkdctol** [comment]
@rpalmer-gsa we've done that at #3668 and will cut over to cloud.gov unless we hear otherwise. Thanks!

**Comment by nickumia-reisys** [comment]
Note: a copy of the findings closed from this issue were exported via the process outlined [here](https://github.com/GSA/data.gov/issues/3754#issuecomment-1085014311).
