### ISSUE TITLE
Disable Links to Harvest Pages

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3757]
## User Story

In order to minimize performance issues from crawlers or other unnecessary requests, the data.gov team wants to remove public links to the harvest pages.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

This is a preemptive measure to https://github.com/GSA/data.gov/issues/3749

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by hkdctol** [comment]
@jbrown-xentity is fixing

**Comment by jbrown-xentity** [comment]
This is deployed to cloud.gov prod: 
![image](https://user-images.githubusercontent.com/26980513/160450543-e7d38dcd-5893-4ea7-a5bc-b0eb24ea5e8f.png)
