### ISSUE TITLE
Dependabot alert on data.gov Pipfile.lock (Paramiko)

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3762]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=id.27aqr3itu127)._

**Date of report:** 2022-03-29
**Severity:** Moderate
**Due date:** 2022-06-29

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

**Comment by FuhuXia** [comment]
Record keeping only. We should have removed the item by the due date.

**Comment by hkdctol** [comment]
Will put in Icebox for now, should be irrelevant after moving out of FCS

**Comment by hkdctol** [comment]
Files will be removed after move from FCS, moving to blocked for now.
