### ISSUE TITLE
Migrate apache rewrite rules to catalog nginx

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3771]
Catalog apache has some [rewrite rules](https://github.com/GSA/data.gov/blob/master/ansible/roles/software/ckan/catalog/ckan-app/templates/etc_apache2_sites-enabled_ckan.conf.j2#L90-L103) in apache config to protect catalog from some expensive API calls. They need to be migrated to catalog Nginx config.

**Comment by nickumia-reisys** [comment]
Investigating how to convert [apache rewrite to nginx rewrite](https://www.nginx.com/blog/converting-apache-to-nginx-rewrite-rules/).
