### ISSUE TITLE
SOLR Classic configuration test

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3780]
## User Story

In order to have a stable solr service, data.gov admins wants SOLR deployed in a classic configuration (static leader with replica nodes).

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] WHEN SOLR classic is deployed \
  THEN a CKAN instance can connect to the SOLR leader \
  AND the SOLR can handle/recover from large harvests

## Background

Due to instability of current SOLR cloud configuration, we want to know if the classic/legacy SOLR architecture will provide more stability.
https://solr.apache.org/guide/8_7/index-replication.html
[Current FCS configuration](https://github.com/GSA/datagov-deploy-solr/blob/master/templates/solrconfig-replica.xml.j2#L968-L976)
We are not sure what needs to be implemented in the follower, check SOLR docs and/or FCS configuration and deployment.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Create diagram of the SOLR architecture
- [ ] Create a [Kubernetes manifest](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/) of the architecture
  - [x] A [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) for the SOLR leader (We need [statefutsets ](https://stackoverflow.com/a/56865064)for production, but for the demo, it's not necessary, a deployment is okay.)
  - [ ] ~A StatefulSet for the follower(s)~ (todo after this test)
  - [x] Each pod in the StatefulSets has a dynamic [PersistentVolumeClaim](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#using-dynamic-provisioning)
  - [x] [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) for a SOLR leader [Service](https://kubernetes.io/docs/concepts/services-networking/service/)
  - [ ] ~Ingress for a SOLR followers Service~ (todo after this test)
  - [ ] ~[NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) that allow the followers to connect to the leader Service~ (todo after this test)
- [x] Demo/run this (either locally or in AWS)
- [x] Connect to local/dev CKAN instance to verify working

**Comment by mogul** [comment]
I was wrong, we don't want Deployments, we do want StatefulSets. I changed the sketch accordingly, and also added links to the corresponding pages in the k8s docs.

@FuhuXia when you work on this you may want to start from [the 2048 manifest](https://github.com/GSA/datagov-brokerpak-eks/blob/main/terraform/modules/provision-aws/2048_fixture.yml) that we use as a test fixture and work up from there. That way you've always got something working.

**Comment by mogul** [comment]
You might also find it easier to start from a working `docker-compose` version and then apply this tool:
https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

**Comment by hkdctol** [comment]
Putting in Icebox for now given outlook on SolrCloud

**Comment by nickumia-reisys** [comment]
Overcome by Solr on ECS Solution
- https://github.com/GSA/data.gov/issues/3826
