### ISSUE TITLE
[SC-7] Restrict egress traffic from inventory

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3786]
This is a copy of https://github.com/GSA/data.gov/issues/3755 pared down to just the **inventory** apps. 

## User Story

In order to minimize the harm a compromised app can do, the data.gov team wants egress traffic from cloud.gov-hosted data.gov **inventory** applications to be limited to just expected destinations.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- GIVEN I am logged into cloud.gov \
  AND I am targeting the `gsa-datagov` organization
  - [ ] WHEN I run `cf t -s prod-egress; cf apps` \
    THEN I see a running instance of the [`cg-egress-proxy`](https://github.com/GSA/cg-egress-proxy#deploying-proxies-for-a-bunch-of-apps-automatically) for each app with egress needs in the `prod` space.
  - [ ] WHEN I run `cf t -s prod; cf network-policies` \
    THEN I see a rules allowing traffic from each app with egress needs in the `prod` space to port 443 on the corresponding proxy app in the `prod-egress` space.

## Background

SC-7 has traditionally been hard to implement for cloud.gov apps. However, the cloud.gov team has now made it possible to [drop the ASG allowing public egress traffic](https://cloud.gov/docs/management/space-egress/) for particular spaces. This enables us to run our production space in the "restricted" configuration, when egress traffic is only allowed for bound services (excluding S3). We then set up dedicated egress proxies in a space with external access. Doing this also enables apps in spaces without `public_egress` to access S3.

[`cg-egress-proxy`](https://github.com/GSA/cg-egress-proxy) was developed for a high-profile GSA project deployed on cloud.gov that had extremely high public visibility, and was required to meet NIST control SC-7 to ensure egress/lateral compromise was not possible. However, that app did not proceed to production despite getting an ATO. As a result, data.gov might be the first team to ship a working SC-7 egress solution for cloud.gov apps. This will set a new precedent for TTS' standard cloud.gov compliance practice, so be sure to make any fixes necessary upstream in `cg-egress-proxy`!

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This work will ensure egress traffic from cloud.gov-hosted data.gov apps is properly restricted by default, as required by NIST control SC-7.

## Sketch

- [ ] Follow the instructions to [deploy egress proxies in the `prod-egress` space based on .acl files, with network policies that allow each app to talk to the corresponding proxy](https://github.com/GSA/cg-egress-proxy#automatically-deploying-proxies-for-multiple-apps)
  - [ ] In particular, the script should be run with .acl files present corresponding to the `inventory` apps allowing them to reach the expected set of .gov/.mil/whatever domains that they crawl. 
- [ ] If we note any problems with apps connecting to S3 buckets after properly configuring them to use the proxy, we should work with Bret/cloud.gov support/AWS support to resolve [this issue](https://github.com/GSA/cg-egress-proxy/issues/5).

**Comment by jbrown-xentity** [comment]
Currently blocked by https://github.com/cloud-gov/product/issues/1775

**Comment by hkdctol** [comment]
Moving to blocked for now pending cloud.gov ticket on S3 issue

**Comment by mogul** [comment]
[Latest update](https://gsa-tts.slack.com/archives/C0ENP71UG/p1659979299161439): 
> > any update on the S3 gateway proxying blockers...? I saw that the Federalist and image repository issues seemed to be resolved...

> Yes finally got an answer from AWS and need to test it out in staging. Will work on that this week.

**Comment by robert-bryson** [comment]
I took [a quick](https://github.com/GSA/data.gov/pull/4031/files) [look](https://github.com/GSA/data.gov/actions/runs/3340195319/jobs/5530023393) at this and it seems like a very similar issue as before: 
` ERR botocore.exceptions.SSLError: SSL validation failed for https://s3-us-gov-west-1.amazonaws.com/cg-efc8a388-5300-46f2-97a7-62792fb14b53 [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)`
Will look more deeply, but don't feel optimistic.

**Comment by nickumia-reisys** [comment]
Is egress proxy working for `catalog`?  Because if it is, there should be no platform reasons why it shouldn't work for `inventory`, right?

**Comment by nickumia-reisys** [comment]
We are on different version of python and probably have some other small change that could effect this.

**Comment by nickumia-reisys** [comment]
Egress proxy has been successfully deployed to inventory and has been live for more than a day.  I feel like there should be important notes that we put here.  But I can't think of anything, so hopefully the notes in the above PRs are enough.
