### ISSUE TITLE
[SC-7] Restrict egress traffic from catalog

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3787]
This is a copy of https://github.com/GSA/data.gov/issues/3755 pared down to just the **catalog** apps. 

## User Story

In order to minimize the harm a compromised app can do, the data.gov team wants egress traffic from cloud.gov-hosted data.gov **catalog** applications to be limited to just expected destinations.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- GIVEN I am logged into cloud.gov \
  AND I am targeting the `gsa-datagov` organization
  - [ ] WHEN I run `cf t -s prod-egress; cf apps` \
    THEN I see a running instance of the [`cg-egress-proxy`](https://github.com/GSA/cg-egress-proxy#deploying-proxies-for-a-bunch-of-apps-automatically) for each app with egress needs in the `prod` space.
  - [ ] WHEN I run `cf t -s prod; cf network-policies` \
    THEN I see a rules allowing traffic from each app with egress needs in the `prod` space to port 443 on the corresponding proxy app in the `prod-egress` space.

## Background

SC-7 has traditionally been hard to implement for cloud.gov apps. However, the cloud.gov team has now made it possible to [drop the ASG allowing public egress traffic](https://cloud.gov/docs/management/space-egress/) for particular spaces. This enables us to run our production space in the "restricted" configuration, when egress traffic is only allowed for bound services (excluding S3). We then set up dedicated egress proxies in a space with external access. Doing this also enables apps in spaces without `public_egress` to access S3.

[`cg-egress-proxy`](https://github.com/GSA/cg-egress-proxy) was developed for a high-profile GSA project deployed on cloud.gov that had extremely high public visibility, and was required to meet NIST control SC-7 to ensure egress/lateral compromise was not possible. However, that app did not proceed to production despite getting an ATO. As a result, data.gov might be the first team to ship a working SC-7 egress solution for cloud.gov apps. This will set a new precedent for TTS' standard cloud.gov compliance practice, so be sure to make any fixes necessary upstream in `cg-egress-proxy`!

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This work will ensure egress traffic from cloud.gov-hosted data.gov apps is properly restricted by default, as required by NIST control SC-7.

## Sketch

- [ ] Follow the instructions to [deploy egress proxies in the `prod-egress` space based on .acl files, with network policies that allow each app to talk to the corresponding proxy](https://github.com/GSA/cg-egress-proxy#automatically-deploying-proxies-for-multiple-apps)
  - [ ] In particular, the script should be run with .acl files present corresponding to the `catalog`, `catalog-fetch`, & `catalog-gather` apps allowing them to reach the expected set of .gov/.mil/whatever domains that they crawl. 
- [ ] If we note any problems with apps connecting to S3 buckets after properly configuring them to use the proxy, we should work with Bret/cloud.gov support/AWS support to resolve [this issue](https://github.com/GSA/cg-egress-proxy/issues/5).

**Comment by robert-bryson** [comment]
Moving to blocked for now to not step on catalog's toes in stage/prod. @FuhuXia, please let me know when it is ok to go ahead with this once you're done with #3780.

**Comment by robert-bryson** [comment]
While working on this last night I was able to deploy to the development space seemingly without problem. In stage/prod there is a `407` error that is a new one for me: 
![image](https://user-images.githubusercontent.com/91547795/165350840-495efe83-06da-4361-ab99-5c77014bfabd.png)

I thought there might be a bug with the `cf-deployproxy` modifications that reset the auth to the egress proxy app, but I tested with dummy values and I don't think that's it.

**Comment by robert-bryson** [comment]
Not really any new information, but I was thinking about this a little and found that for some reason `catalog-proxy` can hit the solr url but `catalog` cannot. The egress proxy settings/deployment are identical. 

From `➜ cf run-task catalog-proxy --command "curl -I 'https://the_correct_:user_and_password@default-solr-65187a14179185f
6-solrcloud.nickumia-singleaz.ssb.data.gov'" --name why_solr` on `catalog-proxy`. 
![image](https://user-images.githubusercontent.com/91547795/165800769-bfe3fa9e-c6ac-4321-919a-2d70b00fd244.png)

**Comment by robert-bryson** [comment]
Moving to blocked until the environment is more stable. I am not able to make progress with the current work going on.

**Comment by hkdctol** [comment]
Moving back to blocked based on current status of catalog.

**Comment by robert-bryson** [comment]
Has something changed with catalog? Has anyone had this issue with even a `cf rs`? There's an issue with a new version of the Python buildpack catalog is trying to grab: 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/91547795/170721225-1c07a2ed-da05-4200-824a-1f8f8ddf6ab6.png">

**Comment by hkdctol** [comment]
Solr not passing through the datasets. @robert-bryson working it.

**Comment by robert-bryson** [comment]
The egress proxy appears to work in both `dev` and `stage`, however in both environments causes at cert error when making requests to solr: `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)\')))")',)`. Still digging into causes, but in `stage`, it appears to be working (ie datasets are present in the app's ui with the egress proxy enabled) whereas in `dev` they are not.

**Comment by robert-bryson** [comment]
Well, if nothing else, setting all the `log` directives in the proxy `Caddyfile` to `DEBUG` surfaces the (an?) issue. 

`curl` requests from within catalog result in a log like: 
```   
2022-06-08T09:12:19.38-0700 [APP/PROC/WEB/0] OUT {"level":"info","ts":1654704739.3840969,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_addr":"10.255.73.19:38912","proto":"HTTP/1.1","method":"CONNECT","host":"solr-69ec800a-4cdb-46a2-a90d-cc15c.ssb.data.gov:443","uri":"solr-69ec800a-4cdb-46a2-a90d-cc15c.ssb.data.gov:443","headers":{"Proxy-Connection":["Keep-Alive"],"Proxy-Authorization":["Basic c2VjcmuZG9tdXNlcjpzZWNyZXRyYW5kb21wYXNzd29yZA=="],"User-Agent":["curl/7.58.0"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"http/1.1","proto_mutual":true,"server_name":"proxy-gsa-datagov-development-catalog.apps.internal"}},"common_log":"10.255.73.19 - - [08/Jun/2022:16:12:19 +0000] \"CONNECT solr-69ec800a-4cdb-46a2-a90d-cc15c.ssb.data.gov:443 HTTP/1.1\" 0 0","user_id":"","duration":0.074871252,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
```
Whereas the requests that are failing (from catalog's log: `(Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)\')))")',)` show a `caddy` log like:
```
   2022-06-08T09:16:30.82-0700 [APP/PROC/WEB/1] ERR 1.654704990822468e+09       debug   tls.handshake   matched certificate in cache    {"subjects": ["286b7f5c-9aeb-4ff2-560a-1093", "proxy-gsa-datagov-development-catalog.apps.internal"], "managed": false, "expiration": 1654790862, "hash": "912af1e98f600a8ba06b120f6450c71c0e4daf58f42d57268be63f4fb6aae"}
   2022-06-08T09:16:30.82-0700 [APP/PROC/WEB/1] ERR 1.654704990825261e+09       debug   http.stdlib     http: TLS handshake error from 10.255.73.19:60100: local error: tls: bad record MAC
```

**Comment by robert-bryson** [comment]
Findings:
- `ckan` [uses](https://github.com/ckan/ckan/blob/b88286ecdf224732d7c86a9956b9038b629ad531/ckan/lib/search/common.py#L9) [pysolr](https://github.com/django-haystack/pysolr) to connect to solr.
- `pysolr` hasn't [released](https://github.com/django-haystack/pysolr/releases/tag/v3.9.0) since 2020 with `3.9.0`, and catalog is using an even older [version `3.6.0`](https://github.com/GSA/catalog.data.gov/blob/a2947bfe125311fc2609fddbc74002e73ca00620/ckan/requirements.in#L112).
- My hope was that updating these would solve the issue, but regardless of the permutations of dependencies, there still exists the SSL issue.
- Digging further in, `pysolr` [uses](https://github.com/django-haystack/pysolr/blob/cbc9b9eeccffa301b5a404c91cc394d227f2c334/pysolr.py#L373) [`requests`](https://github.com/psf/requests) (a `requests.Session`) to actually make the requests to solr. 
- The problem seems to be in `requests` handling of certs through a proxy.
    - Found by sshing into catalog with egress enabled and making requests to solr directly with `requests` and `urllib3` (an unrelated python module for making http requests) with the local python intepreter.
    - ```urllib3.PoolManager().request('GET', r"https://our_solr_url").data``` returns data as expected.
    - ```requests.get(r"https://our_solr_url", auth=('user', 'pass')).text``` throws the same error I have been seeing: ```ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)```
    - Trying the same as above, but with `verify=False` to disable checking cert validity seems to work (as in returns the expected data without a SSL error) but with expected warnings: ```InsecureRequestWarning: Unverified HTTPS request is being made to host 'proxy-gsa-datagov-development catalog.apps.internal'. Adding certificate verification is strongly advised.```
- `requests` is being actively worked on with [`2.28.0` coming out yesterday](https://github.com/psf/requests/releases/tag/v2.28.0) with seemingly relevant fixes in `2.28.0`, `2.27.1`, and `2.27.0` for SSL issues and using a proxy. Unfortunately, bumping the version used to check above to `2.28.0` does not solve the issue.

This is all to say that there is a bug upstream that is blocking this story until either a fix is implemented or workaround found. The code in `requests` doing the handling of this isn't too complicated so I am looking into making the fix.

**Comment by jbrown-xentity** [comment]
@mogul thinks that while the library seems to be the culprit from the findings above, it might be worth making sure that the [ca trust store is set up properly](https://github.com/GSA/cg-egress-proxy#proxying-s3-bucket-access), there is a link for python to try and see if that helps.

**Comment by robert-bryson** [comment]
Now that catalog stage/prod have stabilized, I `cf push`ed the changes out and they have been running stably. Moving ticket to done at long last.
