### ISSUE TITLE
Egress management and restarts

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3789]
## User Story

In order to properly manage egress app and run restarts, data.gov admins want automated process for egress app restarts and well-documented process of hand-deploying and hand-managing the egress app and data.gov app connections.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN the egress app has been deployed \
  WHEN 48 hours have passed since deployment/last restart \
  THEN the egress app has restarted (in each space)

## Background

Will block full deployment for #3785

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, restarts will improve security

## Sketch

- [ ] Create wiki page on data.gov repo, containing information about egress app and specific deployment for data.gov
- [x] Create github workflow for restart of egress apps
- [x] Create credentials on cloud.gov for restarting, and add to GitHub

**Comment by jbrown-xentity** [comment]
To get around this in the short term, can restart egress app:
```
cf t -s prod-egress
cf rs egress-proxy-gsa-datagov-prod
```

**Comment by mogul** [comment]
I thought that [my method for handling cert rotations](https://github.com/GSA/cg-egress-proxy/blob/f587da014034f7718367c82b037f2a9f35b0e277/proxy/start.sh#L3-L22) was solid, but it sounds like maybe it isn't...? 

From [this discussion in Slack](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1650554989160469) it sounds like we can in fact just have Caddy listen on port 61443 and then not worry about the cert rotation.

**Comment by jbrown-xentity** [comment]
If implemented, should evaluate if rolling restart causes any downtime in application outside world access...

**Comment by robert-bryson** [comment]
Note to future Robby: dev/stage have secrets for `CF_SERVICE_EGRESS_USER/AUTH`, [prod tbd](https://gsa-tts.slack.com/archives/C2N85536E/p1651866127213239)

**Comment by robert-bryson** [comment]
Docs started on [the wiki](https://github.com/GSA/data.gov/wiki/Egress-&-ingress-proxies).

**Comment by robert-bryson** [comment]
For evidence, here is the scheduled Github Actions run of the [restart task](https://github.com/GSA/data.gov/actions/runs/2310430551).

And the deny working correctly:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/91547795/168123993-a814966b-df4c-4795-ba26-6756fc701746.png">

and allow: 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/91547795/168124075-f7ca4057-1c82-4cbe-a5dc-1ecad4053f9e.png">
<img width="748" alt="image" src="https://user-images.githubusercontent.com/91547795/168124121-a7239dff-6a12-4b72-84e3-5e81ea942ee7.png">
