### ISSUE TITLE
Determine process for restarting catalog gather process

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3796]
## User Story

In order to support cybersecurity and operational requirements, the catalog.data.gov team wants to implement a way to not interrupt the gather process.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] WHEN a restart is requested for gather (every 15 minutes) \
  THEN if the gather is not busy THEN gather process restarts \
  else if gather is busy then gather process continues

## Background

Sometimes the gather process takes >1 hour to process large harvest jobs.  During a scheduled restart, the gather process exits with a 143 (graceful termination) and then does not do anything upon startup again.  It forgets all information about processed data and job progress.  Whether we allow longer times between restarts or determine a new method for ensuring secure operation is up for question.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
`catalog-gather` needs to meet two conditions to be considered idling and can be safely restarted:

1. Run `cf logs --recent catalog-gather` to check the timestamp of the last entry. The timestamp is older than half of the restart internval, or if the log is empty.
2. Run `cf app catalog-gather | tail -n 1 | awk '{ print $4 }'` to grab the CPU usage. It is in the format of percentage and the value is less than 1%.

**Comment by FuhuXia** [comment]
When this issue is addressed, it will also resolve [an issue](https://github.com/GSA/data.gov/issues/2862#issuecomment-786194515) we observed that gather appears to fall asleep after idling for a long time and need to be manually woken up (restarted) for harvesting to resume.
