### ISSUE TITLE
Encoded characters in harvest report email

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3801]
When there are errors in harvesting, the harvest report emails sent to users contains encoded characters, such as `&#39;`.  This makes it hard for users to understand the error message.  For example:

```
- Identifier: https://data.usaid.gov/api/views/78sy-m3wq; Title: USAID Construction Assessment, Primary Awards: Section 2; 1 Error(s) Found. ### ERROR #1: &#39;references&#39;:[&#39;https://data.usaid.gov/api/views/4fip-vqi3/files/2aa9f48e-2421-4505-8ecf-ed518b737b2c&#39;, &#39;https://data.usaid.gov/api/views/4fip-vqi3/files/167837b5-d9a7-4818-b47b-6ff73b3ce0ce&#39;, &#39;https://data.usaid.gov/api/views/4fip-vqi3/files/c58b951f-f187-42e8-badc-70ea19b82cf7&#39;, &#39;https://data.usaid.gov/api/views/4fip-vqi3/files/85ef0cae-e634-4cf3-a886-a8a674d61f49&#39;, &#39;no&#39;] is not valid under any of the given schemas.
```

## How to reproduce

Check [harvest report emails](https://mail.google.com/mail/#search/from%3A(harvest-report)).

## Expected behavior

No encoded characters.

## Actual behavior

 `&#39;` in message as shown in the example.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by Jin-Sun-tts** [comment]
Here is the code where forms the error message: 
https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/datajson.py#L364

The html.unescape(xxx) function should convert a string with '&#34;' and '&#39;'  to  double quote and single quote,  but it does not change the output text in the email, also tried json.dumps(xxx) in case the error is json format, still could not change the text in email. Also tried just replace '&#34;' and '&#39;' in the msg string, but the email text does not change.

Trying to find out where the double quote and single quote become decimal encoded characters.

**Comment by Jin-Sun-tts** [comment]
email body text is formed here:
https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/logic/action/update.py#L800

added html.unescape(body) and tested the email, it shows quote instead of number entities. 
![Screen Shot 2022-12-21 at 3 54 36 PM](https://user-images.githubusercontent.com/104456257/209001137-a8813bc1-67fc-45d0-9ff3-021b38354aae.png)
![Screen Shot 2022-12-21 at 3 55 01 PM](https://user-images.githubusercontent.com/104456257/209001162-8cb10ae4-c3b9-4588-819d-c12a30c67d1a.png)

Will make a PR in upstream repo to fix this issue.

**Comment by Jin-Sun-tts** [comment]
https://github.com/ckan/ckanext-harvest/pull/517 

html.unescape is available for Python3.4 and above,  need to compatible with Python 2 (CKAN 2.7) too.

**Comment by Jin-Sun-tts** [comment]
import different unescape package through `six` for python3.4+ and python2 user (https://github.com/ckan/ckanext-harvest/pull/517/commits/84780a9633893dd0ffe8f269fb2141f3bbe4d1aa)

**Comment by hkdctol** [comment]
Just pinged Andres by email to his datopian address as well but we need Adria?

**Comment by FuhuXia** [comment]
The latest harvest report shows the issue is resolved.
