### ISSUE TITLE
Catalog dev in bad state

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3802]
Catalog dev is in a bad state, not coming up.

## How to reproduce

1. https://catalog-dev-datagov.app.cloud.gov/dataset

## Expected behavior

Works

## Actual behavior

500

## Sketch

- [ ] Check if someone is actively working/debugging on development catalog
- [ ] Rebase dev from main (`git fetch; git pull main; git push origin main:develop --force`)
- [ ] Check logs for error
- [ ] Iterate on bugs/issues

Goal is to make sure if someone wanted to test changes, they could test without debugging external factors...

**Comment by nickumia-reisys** [comment]
Based on preliminary investigation, this is due to egress proxy errors.

**Comment by nickumia-reisys** [comment]
Not sure if it was actually the egress proxy, but the egress proxy was undone in `development` and the `INTERNAL_ROUTE` variable was fixed and catalog is working in dev again,

![image](https://user-images.githubusercontent.com/85196563/166608899-fe0765c5-38d7-4af6-b86f-36983f34e587.png)
