### ISSUE TITLE
Inventory dev in a bad state

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3803]
Inventory dev is in a bad state, not coming up.

## How to reproduce

1. https://inventory-dev-datagov.app.cloud.gov/user/login

## Expected behavior

Works

## Actual behavior

500

## Sketch

- [ ] Check if someone is actively working/debugging on development inventory
- [x] Rebase dev from main (`git fetch; git pull main; git push origin main:develop --force`)
- [ ] Check logs for error
- [ ] Iterate on bugs/issues

Goal is to make sure if someone wanted to test changes, they could test without debugging external factors...

**Comment by nickumia-reisys** [comment]
The main issue was Solr version being out of compatibility with the CKAN version.  This was fixed by,
- Recreating Solr 8 from scratch
- Removing the egress-proxy work
- Removing the nginx-proxy work
- Resetting the CKAN main app code
