### ISSUE TITLE
Amazon EKS Kubernetes 1.19 Deprecation

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3804]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 2022-04-28
**Severity:**
**Due date:** 2022-06-30

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
Our Inventory on staging and prod are using Amazon EKS with Kubernetes version 1.19 for SOLR. AWS will stop its support on June 30, 2022, existing EKS clusters will be updates to 1.20. We will want to manually update Inventory Solr(cloud) to use new EKS by that time.

**Comment by hkdctol** [comment]
If we don't move to Solr 8 before this due date 6/30, we should address this.

**Comment by hkdctol** [comment]
@FuhuXia will check with @mogul on whether this can be deleted.

**Comment by FuhuXia** [comment]
Did some research, we have one EKS 1.19 on Development AWS account. We decide to leave it alone and let AWS do the 1.21 upgrade and hope it works out well.

We also have one EKS 1.19 on Production AWS account, which the current Inventory SOLR is using. We should be able to move Inventory from EKS based SolrCloud to standalone SOLR 8 based on ECS following this [catalog PR](https://github.com/GSA/catalog.data.gov/pull/460) as example before the due date.

**Comment by hkdctol** [comment]
We moved inventory to Solr on ECS we can close this
