### ISSUE TITLE
Purge Solr 6 Deployment

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3805]
## User Story

In order to complete our upgrade from Solr 6 to Solr 8, the Data.gov SSB team wants stop deploying and supporting Solr 6 as a brokered service.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [x] Decide if `datagov-brokerpak-solr` should still have the ability to deploy Solr 6 (requires old CRDs, different version of EKS)
  - [ ] Note in the `datagov-brokerpak-solr` that Solr 6 is no longer supported.
- [x] Remove the `ssb-solr` app and related resources from `datagov-ssb`

**Comment by hkdctol** [comment]
#3679 is blocking this
