### ISSUE TITLE
Deprecation of AWSConfigRole IAM Managed Policy

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3809]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 2022-05-03
**Severity:**
**Due date:** 2022-07-05 (or next SSB IAM update)

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

AWS is replacing it's `AWSConfigRole` with `AWS_ConfigRole` and no longer supporting updates to the deprecated role.  Work will need to be done to assess the impact to the SSB.  See email for more information.

**Comment by hkdctol** [comment]
Move inventory to Solr 8 on the ECS solution, and then this ticket would be resolved.

**Comment by hkdctol** [comment]
@nickumia-reisys to review

**Comment by nickumia-reisys** [comment]
Inspection from the aws cli revealed that the role in question is used to provide AWS Config access to other services.  The role was created 12/2020 and is being used for automated compliance testing.  There is no critical risk to current services.  The existing role will persist; however, we should probably update the Role with the new Role.  (This will require an SSBAdmin with IAM access)

Will create new ticket with further actions. (No immediate action is required)
