### ISSUE TITLE
Debug and create test for datagov-smtp broker

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3810]
datagov-brokerpak-smtp @ main 

## How to reproduce

1. Create a datagov-smtp service
2. Bind service to catalog main app
3. Configure CKAN with smtp credentials
4. Perform action that would send email (e.g. harvesting)
5. Wait for email to be generated

## Expected behavior

Email sent to desired recipient

## Actual behavior

```bash
 2022-05-03T21:09:30.89-0400 [APP/TASK/harvester/0] ERR 2022-05-04 01:09:30,896 ERROR [ckan.lib.mailer] SMTPDataError(554, b"Access denied: User `arn:aws:iam::821341638715:user/cf/ses-b7a1cd34ddf3b0cf-csb--e3a67950-0aa6-4cb0-b272-76cfcf93cb8a' is not authorized to perform `ses:SendRawEmail' on resource `arn:aws:ses:us-west-2:821341638715:identity/aaron.borden@gsa.gov'")
   2022-05-03T21:09:30.89-0400 [APP/TASK/harvester/0] ERR Traceback (most recent call last):
   2022-05-03T21:09:30.89-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/ckan/lib/mailer.py", line 107, in _mail_recipient
   2022-05-03T21:09:30.89-0400 [APP/TASK/harvester/0] ERR smtp_connection.sendmail(mail_from, [recipient_email], msg.as_string())
   2022-05-03T21:09:30.89-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/smtplib.py", line 893, in sendmail
   2022-05-03T21:09:30.89-0400 [APP/TASK/harvester/0] ERR raise SMTPDataError(code, resp)
   2022-05-03T21:09:30.89-0400 [APP/TASK/harvester/0] ERR smtplib.SMTPDataError: (554, b"Access denied: User `arn:aws:iam::821341638715:user/cf/ses-b7a1cd34ddf3b0cf-csb--e3a67950-0aa6-4cb0-b272-76cfcf93cb8a' is not authorized to perform `ses:SendRawEmail' on resource `arn:aws:ses:us-west-2:821341638715:identity/aaron.borden@gsa.gov'")
```

## Sketch

- [x] Investigate where Aaron's email is set
- [x] Untie smtp brokerpak from his account (since his account is probably deactivated)
- [x] Create a manual test in smtp brokerpak to see if it can send email
- [x] Promote AWS SES Account from `Sandbox` to `Production`
- [x] Push and release updates

**Comment by nickumia-reisys** [comment]
Verified in the AWS Console, the SES instance was verified,

![image](https://user-images.githubusercontent.com/85196563/166729435-4d1fa2f8-175f-49f1-bb1f-58b237aef0ac.png)

**Comment by nickumia-reisys** [comment]
Ohhhh, I think I found the problem.. I think we should be doing [this](https://docs.aws.amazon.com/ses/latest/dg/control-user-access.html#iam-and-ses-examples-email-sending-actions), 
```yaml
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Effect":"Allow",
      "Action":[
        "ses:SendEmail",
        "ses:SendRawEmail"
      ],
      "Resource":"*"
    }
  ]
}
```

Instead of doing [this](https://github.com/GSA/datagov-brokerpak-smtp/blob/main/terraform/bind/main.tf#L15-L35),
```yaml
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action":[
        "ses:SendEmail",
        "ses:SendRawEmail"
      ],
      "Resource": "${var.domain_arn}"
    }
  ]
}
```

The second one restricts sending emails only to itself as opposed to, to anywhere.

**Comment by nickumia-reisys** [comment]
Okay.. well... there's a few steps that need to happen here,
- [x] Promote our SES Account to production from sandbox to be able to send real emails to external accounts
- [ ] This PR needs to be reviewed and merged to be able to send emails to anyone, instead of just to itself.
  - [x] I'm writing a test to manually send an email.

My script will continue to fail with `Email Address not verified` until our SES Account is promoted to production,
![image](https://user-images.githubusercontent.com/85196563/166805231-8ed14546-a7dd-48c1-9ce4-742e340821aa.png)

This blocker is described [here](https://stackoverflow.com/a/37528929) and I think requires a government person to be involved.

**Comment by nickumia-reisys** [comment]
The original error was trying to send an email to aaron's email, not use aaron's email to do something.

**Comment by nickumia-reisys** [comment]
Proof that sending emails works 😄 

![image](https://user-images.githubusercontent.com/85196563/166815960-af32a1d1-4772-4972-81a6-54a1a02930db.png)

![image](https://user-images.githubusercontent.com/85196563/166816015-9e3e8c30-c95f-4888-9139-e69641d0dcd5.png)

**Comment by mogul** [comment]
> Ohhhh, I think I found the problem.. I think we should be doing [this](https://docs.aws.amazon.com/ses/latest/dg/control-user-access.html#iam-and-ses-examples-email-sending-actions),
> 
> ```yaml
> {
>   "Version":"2012-10-17",
>   "Statement":[
>     {
>       "Effect":"Allow",
>       "Action":[
>         "ses:SendEmail",
>         "ses:SendRawEmail"
>       ],
>       "Resource":"*"
>     }
>   ]
> }
> ```
> 
> Instead of doing [this](https://github.com/GSA/datagov-brokerpak-smtp/blob/main/terraform/bind/main.tf#L15-L35),
> 
> ```yaml
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Effect": "Allow",
>       "Action":[
>         "ses:SendEmail",
>         "ses:SendRawEmail"
>       ],
>       "Resource": "${var.domain_arn}"
>     }
>   ]
> }
> ```
> 
> The second one restricts sending emails only to itself as opposed to, to anywhere.

I don't think that's what is happening here... Restricting to just a particular target address [looks different](https://docs.aws.amazon.com/ses/latest/dg/control-user-access.html#iam-and-ses-examples-recipients).

**Comment by mogul** [comment]
See also how the word "Resource" is applied here... It refers to the SES identity being used for sending, not the recipient.

![image](https://user-images.githubusercontent.com/47762/166836138-c154bfcf-79b5-4126-8122-8791fedea093.png)

Here's a list of brokered SES identities:
![image](https://user-images.githubusercontent.com/47762/166836489-c4a296a5-838a-47f6-a54b-51c8d27a6497.png)

If you make the resource `*` instead of `${var.domain_arn}` then you are saying that credentials brokered for one service instance can also be used to send from the identity associated with another instance. Definitely not what we want!

**Comment by nickumia-reisys** [comment]
Summary of work:
- https://github.com/GSA/datagov-brokerpak-smtp/pull/15
- https://github.com/GSA/datagov-brokerpak-smtp/pull/16

- A manual test was created in the `datagov-brokerpak-smtp` repo where an SMTP instance can be provisioned locally and then a user can use an email they have access to in order to check if an email can be properly sent from the provisioned SMTP service to their provided email.

- The updates were packaged into a PR for catalog.data.gov.  However, it is being held off until we actually transition to cloud.gov and need to send emails.  If it was merged prematurely, it could cause confusion for users as they would receive multiple sets of harvesting emails from different platforms.
- https://github.com/GSA/catalog.data.gov/pull/457
