### ISSUE TITLE
Test GSA ISE Hardened AMI's compatibility with SolrCloud

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3812]
## User Story

In order to meet cybersecurity requirements, the Data.gov Solr Team wants ensure that the GSA Hardened AMI for running EKS does not have any operational conflicts with our SolrCloud setup.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN an EKS cluster is configured and deployed with GSA Hardened AMI \
  WHEN a SolrCloud deployment happens \
  THEN a production-scale catalog instance can remain stable beyond one week

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [x] Make sure the most recent GSA-Hardened AMI is in the account of testing.
- [x] Manually deploy EKS cluster from `datagov-brokerpak-eks` repo
- [x] Install credentials into SolrCloud Broker
- [x] `cf create-service solr-cloud base "${app_name}-solr" -c solr/service-config.json -b "ssb-solrcloud-gsa-datagov-${space}" --wait&`
- [x] cf bind-service catalog catalog-solr
- [x] Turn off harvesting on catalog instance
- [ ] Reindex catalog
- [ ] Turn on harvesting on catalog instance
- [ ] Continuously monitor Solr service for errors or faults.

**Comment by nickumia-reisys** [comment]
See [instructions here](https://github.com/GSA/datagov-brokerpak-eks/blob/static-eks/docs/gsa-hardened-ami.md) on how to copy/share AMIs.

**Comment by jbrown-xentity** [comment]
@mogul mentioned that if the slowdown is a serious problem, we should consider running an index on a non-hardened-AMI and the hardened AMI side by side, and checking top to see what is running and what may be causing the slowdown... @robert-bryson @nickumia-reisys maybe we can try this?

**Comment by nickumia-reisys** [comment]
I'll have to see the best way of ssh'ing into a node because we've never done this (other than to run CIS Benchmark tests).  Maybe the best way would be to use SSM Fleet Manager, but yeah.. it is possible.  `top` might also not be the best indicator of slowdown, but it is a start.  Just beware, that it may actually be hardware settings that are getting in the way, not software processes.

**Comment by mogul** [comment]
[Directions for starting a terminal session.](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-sessions-start.html)

(No need to SSH.)

**Comment by nickumia-reisys** [comment]
Upon initial inspection of the GSA-Hardened AMIs alone (because that's the only thing we have indexing right now), all three nodes with Solr nodes on them have CPU Utilizations of <15% and RAM is not anywhere near the limit.

**Comment by nickumia-reisys** [comment]
As we've moved away from the SolrCloud solution (permanently?), this ticket is no longer relevant.  In case this ticket is ever revisited, from my current recollection, we didn't find any process or task that could be attributed to the CPU/RAM issues with SolrCloud.  So this exploration would be from scratch the next time around.
