### ISSUE TITLE
Catalog missing Collection UI elements

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3834]
If a dataset is a collection, the dataset page should display a search button leading to a list of datasets within the collection. On the listing page, the top should display the collection information. These two elements are missing from cloud.gov catalog app.

## How to reproduce

Find a collection on cloud.gov catalog app, go to the collection dataset page.
For example, https://catalog-prod-datagov.app.cloud.gov/dataset/fas-parent

## Expected behavior

_Collection UI element 1:_
![image](https://user-images.githubusercontent.com/1392461/170356464-aaab1523-5b34-4429-a2d0-d83c07693b9f.png)

_Collection UI element 2:_
![image](https://user-images.githubusercontent.com/1392461/170356593-d1c34a18-5bba-42d5-a03b-298ece6fdd58.png)

## Actual behavior

The two elements are missing from the UI.

## Sketch

- [ ] Locate the code that is responsible for these UI elements in current FCS code
- [ ] Compare with the template in the CKAN 2.9 version to see why it's not working
- [ ] Add appropriate code back to new template

**Comment by hkdctol** [comment]
Would need to fix if possible before moving catalog to cloud.gov

**Comment by jbrown-xentity** [comment]
I thought that maybe this was a backend issue, but that doesn't seem to be the case. All of the relevant information is there: 

- Looking at [this example dataset](https://catalog-prod-datagov.app.cloud.gov/dataset/purchase-card-transactions-civilian-board-of-contract-appeals-cbca-parent)
- Comes from [GSA data.json](https://open.gsa.gov/data.json), search on "Purchase Card Transactions - Civilian Board of Contract Appeals (CBCA) Parent"
- Note there are about 27 items that should exist in the collection (search on GSA defined unique identifier, `GSA-2016-01-06-1`)
- CKAN translates this into the `collection_package_id` extras field, and uses the CKAN ID (not the data.json id, as those don't always exist in CSDGM/ISO)
- You can verify the data still exists by hitting the api: https://catalog-prod-datagov.app.cloud.gov/api/action/package_search?fq=collection_package_id:147a1ade-99b6-46eb-a275-302dfd436bbe

**Comment by jbrown-xentity** [comment]
We'll need to fix geodatagov extension, upgrade to flask missed an item:

```
ckan_1                  |   File "/srv/app/src/ckanext-geodatagov/ckanext/geodatagov/templates/templates_new/package/search.html", line 4, in block 'primary_content'
ckan_1                  |     {% if request.params.collection_package_id %}
```
