### ISSUE TITLE
Create proper Solr Leader-Follower design

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3838]
## User Story

In order to create a leader-follower paradigm for solr, the data.gov catalog/solr/ssb/ecs team wants to define how to route the right requests from the catalog main/harvester apps to the appropriate solr instance (whether leader or follower, i.e. read or write) based on the request.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
Theoretically we can add a rule, where all `/[ckan]/select` requests get redirected to the followers, and all other requests (the default) go to the leader... That might have some ramifications for gather and fetch (as they might need up-to-the-second recent data), so those applications may need a separate load balancer that always goes directly to the leader.

**Comment by hkdctol** [comment]
Will probably go to cloud.gov without working this.

**Comment by hkdctol** [comment]
Logs indicate we can go to production with Leader only.

**Comment by hkdctol** [comment]
Closing as duplicative of #3854
