### ISSUE TITLE
Duplicate datasets from DOI

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3852]
There are duplicate datasets on DOI. DOI has confirmed it is not passing duplicates in it's DCAT-US file, and that something is happening on the data.gov side.

## How to reproduce

1. https://catalog.data.gov/api/action/package_search?q=publisher:%22Bureau%20of%20Land%20Management%22&facet.field=[%22identifier%22]&facet.limit=4000&facet.mincount=2

## Expected behavior

Should be zero facet results; DOI datasets are all harvested via data.json and the identifier should be required to be unique.

## Actual behavior

Duplicates

## Sketch

Run de-dupe script: https://github.com/GSA/datagov-dedupe

**Comment by jbrown-xentity** [comment]
Found 849 duplicate records in DOI (via dry run). Confirmed with api call: https://catalog.data.gov/api/action/package_search?q=organization:doi-gov&facet.field=[%22identifier%22]&facet.limit=4000&facet.mincount=2.
Running de-dupe with commit now, expect to finish overnight.

**Comment by jbrown-xentity** [comment]
[duplicate-packages-doi_blm.csv](https://github.com/GSA/data.gov/files/8910033/duplicate-packages-doi_blm.csv)
This is the log of the de-dupe process that was run. 962 duplicates were removed.

**Comment by jbrown-xentity** [comment]
Also discovered DOI harvest issue that isn't reported by the harvester, as it fails to import due to the spatial extension.

The error: ckan.logic.ValidationError: None - {'spatial': ['Error creating geometry: Context does not provide geo interface']}

The spatial component of the USGS DCAT is bad; currently it looks like: "spatial":"[[30.126883, -89.035786], [30.215336, -88.637281]]". T[here](https://resources.data.gov/resources/dcat-us/#spatial) are a number of options for how to implement this documented here, but here are some alternatives to the above example:

- `{"type": "Polygon", "coordinates": [[[-180.0, 13.6400003433], [180.0, 13.6400003433], [180.0, 70.3300018311], [-180.0, 70.3300018311], [-180.0, 13.6400003433]]]}`
- `"-179.231086,-14.601813,179.859681,71.441059"`

This is on DOI to figure out and fix...

**Comment by hkdctol** [comment]
Harvester crashes and results in processes that continue to create dupes. #3864 addresses this and we will continue to look at it.
