### ISSUE TITLE
Add Authorization header to Inventory New Relic health check

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3861]
## User Story

In order to be alerted when Inventory solr is down, data.gov team wants use a better health check URL with user authentication token.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a working Inventory app\
  WHEN its inventory-solr service is unbound \
  THEN a NewRelic app is unavailable incidence alert is generated 

## Background

Current Inventory health check url is using root url '/'. It generates a 403 response regardless the solr is up or down. In New Relic health check config it allows to add request header. We can add a user api token in the header so the that request can be authenticated and check url is set as '/dataset', which is supposed to generate a 200 response code. In case the solr is down (or unbound), it generates 500 response code.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

We have a common Internal ckan user (non-saml2) in all Inventory instances. We can create a API token for that user and use it in the New Relic config.

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
- [ ] Pick an internal (non-saml2) ckan user and generate a API token
- [ ] In New Relic health check config, use the token to add a "Authorization: XXX" header.
- [ ] Change health check url to be /dataset

**Comment by albionzeglin-gsa** [comment]
We need to ensure the token used does not have permissions that New Relic does not need. The token also needs to either replaced on a schedule prior to expiration, or not expire.

**Comment by Jin-Sun-tts** [comment]
https://docs.ckan.org/en/2.9/api/#authentication-and-api-tokens

Added header X-CKAN-API-Key with API token for user 'inventory' for both production and staging
Changed the health check URL to /dataset

**Comment by Jin-Sun-tts** [comment]
During test we found out even the solr was down, the check status still returns success, so we added keyword 'datasets found' as the checking text. Then tested staging we do see the alert like below when solr was down. 

<img width="417" alt="Screen Shot 2022-07-14 at 1 58 18 PM" src="https://user-images.githubusercontent.com/104456257/179051188-49ef69b4-9079-49e1-80f9-2f87b5cd27c6.png">


<img width="540" alt="Screen Shot 2022-07-14 at 1 56 53 PM" src="https://user-images.githubusercontent.com/104456257/179050829-ff4ad442-362f-427c-9d1d-6c293d91fa7b.png">

**Comment by hkdctol** [comment]
We've validated this fix and moving to done.
