### ISSUE TITLE
SOLR EFS Backups

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3862]
## User Story

In order to have easy SOLR disaster recovery, data.gov admins wants EFS to have regular backups and a recovery process.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN backups are occurring of EFS data for SOLR \
  WHEN SOLR EFS/data is lost happens \
  THEN a backup of EFS can be restored \

## Background

https://docs.aws.amazon.com/efs/latest/ug/awsbackup.html

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_backup_policy

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, all solr data is public

## Sketch

Should be adding the necessary terraform to solr brokerpack for regular backups.

Should also involve a test of restoring a backup (does not have to be a full DB/SOLR)

**Comment by nickumia-reisys** [comment]
Proof that EFS Backups are enabled,

## In AWS Backup
![image](https://user-images.githubusercontent.com/85196563/174309239-68e6b489-bc8e-42f9-a9d4-d93f2c388029.png)

## In EFS (each volume)
![image](https://user-images.githubusercontent.com/85196563/174309847-9480bdff-2fb4-4ab2-a3ab-5e21f7a2ae62.png)

**Comment by FuhuXia** [comment]
The default setting is `daily backups with a 35-day retention period`.
35-day is more than what we need. With same amount the resources, a 6-hour backup with 7-day retention make more sense, if more frequent backup does not impact solr performance.

**Comment by nickumia-reisys** [comment]
Default settings are as follows, Backups:
- Start within 8 hours of 0500 UTC
- Complete within 7 days
- Retained for 35-days
- Run daily

Terraform does not provide native support for configuring this plan as part of EFS.  However, we may be able to create a custom Backup plan that does not use the default Automatic Backups behavior.  Additional testing would be necessary to configure it properly.

**Comment by FuhuXia** [comment]
Can we tell how long did it take for one backup?

**Comment by nickumia-reisys** [comment]
We can check the status of current backups and see how long backups took previously.

**Comment by nickumia-reisys** [comment]
It would seem like the backups are relatively quick, the 23GB full-production backup took ~2 hours.

![image](https://user-images.githubusercontent.com/85196563/174807006-55d2fe9a-051c-4720-9802-6ff3ca02d7c7.png)

**Comment by albionzeglin-gsa** [comment]
The EFS backups are sensitive to changes that occur to files during backup. We need to confirm that either SOLR is paused during backup execution, or that SOLR is not sensitive to file inconsistencies in backup restores.
