### ISSUE TITLE
redis server storage low

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3865]
Today we gets quite some storage low alerts from New Relic for redis production server, sometimes redis host went down because of it. SSH'ed into the redis1p instance and ran `df -h`, it showed the root partition constantly fluctuates between 93% to 100% usage.  The log in /var/log/redis/ shows error message:
```
Write error saving DB on disk: No space left on device
```
`top -c` shows process `redis-rdb-bgsave` is using 100% CPU.
There are some `/var/lib/redis/temp-#####.rdb` files being generated and then disappeared rapidly, each time it used/released a few hundred MB storage.

Restarted the server a few times, it took a while (20-30 mins) each time before the host came back up from the restart.

**Comment by jbrown-xentity** [comment]
@FuhuXia can you provide an update on this?

**Comment by FuhuXia** [comment]
After a few restarts, redis is back to normal again, storage usage stabilized at  91% on root partition. We requested FCS to increase the root partition storage from 8GB to 20GB. Should be good now and future proof. This ticket can be closed.

**Comment by hkdctol** [comment]
This was addressed with FCS. Can be closed.

**Comment by nickumia-reisys** [comment]
Reference:
- https://github.com/GSA/data.gov/issues/3710
