### ISSUE TITLE
Data.gov sites address issues identified in AMP scanning

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3871]
## User Story

In order to meet Accessibility requirements, Data.gov PMO should address issues found in AMP scans provided by GSA.

## Acceptance Criteria

- [ ] GIVEN AMP scans of data.gov sites\
  THEN top issues in reports have been addressed.

## Background

GSA has agency goals for meeting minimum accessibility requirements on all GSA sites. GSA provides scans from the AMP tool. GSA sites are required to meet standards by August 31.

## Sketch
- [X] Review AMP reports https://gsa.levelaccess.us/public/reporting/view_report.php?report_id=266522
(for catalog) and https://gsa.levelaccess.us/public/reporting/view_report.php?report_id=266805 (resources)
- [X] Review the guidance at https://docs.google.com/document/d/1U8xYhMjYnuul8U1WiMXP_P1ltQZDkk5h7ylrSkvSobQ/edit?usp=sharing
- [X] Review top identified issues (provide alternative text for images)
- [X] Follow recommendations in report
- [X] Create other tickets to fix as needed.

**Comment by btylerburton** [comment]
Emailed AMP leads for guidance on how to proceed with images served 3rd party Leaflet plugin / OpenStreetmap plugin that is embedded in CKAN core.

ex. `<img src="//b.tile.openstreetmap.org/2/0/1.png" style="height: 256px; width: 256px; transform: translate3d(-109px, -31px, 0px);" class="leaflet-tile leaflet-tile-loaded"/>`

12 of 18 flagged high severity issues originate from Leaflet.

https://gsa.levelaccess.us/public/reporting/view_instances.php?report_id=266522
