### ISSUE TITLE
Enable/disable egress action

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3873]
## User Story

In order to [manage egress], [team datagov team] wants [be able to easily enable and disable egress for a given app with a GitHub action].

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN [an app with egress enabled] \
  [AND there is a potential issue with egress] \
  WHEN [a Github action is run] \
  THEN [egress is disabled for the app] \

- [x] GIVEN [an app with egress disabled] \
  [AND egress needs to be re-enabled] \
  WHEN [a Github action is run] \
  THEN [egress is enabledfor the app] \

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

Disable egress is already partially working with [this action](https://github.com/GSA/data.gov/blob/master/.github/workflows/disable-egress.yml), but there is a bug with grabbing the network-policy data. 

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

- See the [disable-egress](https://github.com/GSA/data.gov/blob/master/bin/disable-egress) and [enable-egress](https://github.com/GSA/data.gov/blob/master/bin/enable-egress) scripts. 
- The disable script is mostly working, but needs to be made more robust (idempotent). 
- `enable-egress` is very much a stub and not working. It will need an action to grab the [cg-egress-proxy](https://github.com/GSA/cg-egress-proxy) repo and use it to deploy the egress proxy.

**Comment by nickumia-reisys** [comment]
Documentation on how to manually disable egress proxies (...if it ever becomes necessary again):
```bash
# Remove network policy (update app(s)/space(s) as needed
cf remove-network-policy catalog-web egress-proxy-gsa-datagov-prod -s prod-egress -o gsa-datagov --protocol tcp --port 8080
# Remove https_proxy env 
cf unset-env catalog-web https_proxy
cf unset-env catalog-web http_proxy
# Restart app
cf restart catalog-web
```
