### ISSUE TITLE
Stay on a supported version of Python 3

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3876]
## User Story

In order to stay on a supported version of Python 3, the Data.gov O&M team wants to monitor and upgrade python in accordance with cloudfoundry buildpaks, ckan support and python support.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]
Due to the evolving and advancing nature of technology, there is only limited support for python versions.  We would like to stay on top of the EOL timelines to ensure our applications don't become vulnerable to out-of-date software.

### Python
- Reference: https://endoflife.date/python
- Python 3.7 -- June 2023
- Python 3.6 -- December 2021

### Cloudfoundry Python Buildpak
- Reference: https://github.com/cloudfoundry/python-buildpack/releases
- Python 3.7 -- EOL Unknown
- Python 3.6 -- [Feburary 2022](https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.50)

### Historical Issues
- https://github.com/GSA/data.gov/issues/1049
- https://github.com/GSA/data.gov/issues/1268
- https://github.com/GSA/data.gov/issues/3843
- https://github.com/GSA/data.gov/issues/3607

### CKAN Support for python
- Reference: https://github.com/ckan/ckan/blob/master/.github/workflows/cypress.yml#L5
- CKAN 2.8 only worked with Python 2.  CKAN 2.9 supports both Python 2 and Python 3 (although versions are not explicitly specified).
- CKAN may support newer version of python.  However, a specific dependency (`pyproj`) has different install requirements depending on the version of `python`, `os` and `proj` installed to accompany it.  See [slack discussion](https://gsa-tts.slack.com/archives/C2N85536E/p1655906827558949) for more information.
- The version of Alpine referenced [here](https://github.com/okfn/docker-ckan/blob/master/ckan-base/2.9/Dockerfile#L1) is important to monitor since our tests are based on it for now (unless we [mirror the functionality](https://gsa-tts.slack.com/archives/C2N85536E/p1655909165405669?thread_ts=1655906827.558949&cid=C2N85536E) for ourselves going forward).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]
- [ ] Monitor dependencies
  - [ ] Python 3.7 EOL
  - [ ] Cloudfoundry Python Buildpak deprecating support of Python 3.7
  - [ ] CKAN (and ckanext) support for Python 3.7
- [ ] Determine upgrade process when the time is ready.

**Comment by nickumia-reisys** [comment]
Immediate pressure has been relaxed on this issue since we've successfully upgraded `catalog` to `Python 3.8`.

**Comment by nickumia-reisys** [comment]
Current versions of python:
- `Catalog` ➡️ `Python 3.8`
- `Inventory` ➡️ `Python 3.9`

The blockers are not the same for both applications.  Some of them are the same, some of them are unique.
- https://github.com/GSA/data.gov/issues/4056
- https://github.com/GSA/data.gov/issues/4057
- Catalog-specific:
  - https://github.com/GSA/data.gov/issues/3607
- There are more, just not properly documented, since many of them are co-dependent or have not been discovered yet.

There is also confusion surrounding buildpack releases.  The buildpack tries to use the latest version of Python (that it knows about), this may cause our code to randomly break since we vendor requirements for a specific version of Python.

**Comment by hkdctol** [comment]
Focus on CKAN 2.10 for now

**Comment by hkdctol** [comment]
@nickumia-reisys is this ticket obsolete?

**Comment by nickumia-reisys** [comment]
Maybe?  This ticket I think should be one of many that define our constant responsibility to remain current and relevant in the world of technology.  For all of the major things that we use, I think it would be fine to have a single long-running ticket that describes the upgrades that were needed over time.  I know long-running tickets/epics are not ideal for the majority of work.  So... I'm okay closing this as previously complete.

The ["best" version](https://devguide.python.org/versions/) of Python to be on (as of writing) looks to be `v3.12`.  However, CKAN most probably won't work on that.  The deciding factor to upgrade is typically if a security vulnerability comes out.  As Data.gov decouples from CKAN, being on the latest version of Python will fall more on us and, since it's hard to remember everything all of the time, I think it would be useful to have big tickets like this as a reminder.

**Comment by btylerburton** [comment]
we're on python 3.10. good to close
