### ISSUE TITLE
Catalog page cache improvement 

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3887]
## User Story

In order to improve page loading performance for catalog apps, data.gov teams wants see more pages/assets cached on CDN.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN an anonymous user hits catalog app behind CloudFront
  WHEN access url `/dataset` for the second time
  THEN `x-cache: Hit from cloudfront` found in the response header
- [x] GIVEN an anonymous user hits catalog app behind CloudFront
  WHEN access url `/images/logo.svg` for the second time
  THEN `x-cache: Hit from cloudfront` found in the response header
- [x] GIVEN an anonymous user hits catalog app behind CloudFront
  WHEN access url `/dataset/?page=2` and `/dataset/?page=3`
  THEN two pages have different content
- [ ] ~~GIVEN an logged-in user hits catalog app behind CloudFront
  WHEN access url `/dashboard/` for the second time
  THEN `cache-control: private` and `x-cache: Miss from cloudfront` found in the response header~~
- [x] GIVEN an anonymous user hits catalog app behind CloudFront
  WHEN access API url `/api/3` for the second time
  THEN `cache-control: public` and `x-cache: Miss from cloudfront` found in the response header

## Background

We did some work in https://github.com/GSA/data.gov/issues/1311 but it seems incomplete. Current production `/dataset` page is not cached. The catalog app needs to spend quite some resources to repeatedly serve this home page request. 

In order to have let CloudFront to cache most pages, we need to [enable ckan cache control.](https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-cache-enabled)

For static assets with 'cache-control: no-cache' in the response header, we can set [Minimum TTL to be 300](https://stackoverflow.com/questions/18774069/amazon-cloudfront-cache-control-no-cache-header-has-no-effect-after-24-hours) in CloudFront config so CDN will not communicate with catalog server for static assets for five minutes. 

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
If admin site shares same URL as anonymous site, extra caution need to be taken when 1) dealing the /dataset page showing private dataset be cached and displayed to anonymous user. 2) If `cache-control: private` is cached by CDN, we will want to set Minimum TTL 0 and disregard AC#2.
If story #3893 is implemented, then above mentioned 1 & 2 security concerns are not applicable, and AC#4 can be disregarded.  

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
The default cache expiry is set to be 24 hours in both CloudFront and CKAN ini. We can re-evaluate a good number a few weeks after cloud.gov migration. 

Update: we are using 1 hour cache now.

**Comment by hkdctol** [comment]
We will evaluate later whether we can do this work after going live on cloud.gov

**Comment by FuhuXia** [comment]
Added last AC for disabling caching for API calls. This might affect performance especially during load test ( constant `package_search` API calls.. We implement if our server can handle the traffic.

**Comment by FuhuXia** [comment]
Added behavior for `/api/*` with this configuration to disable caching for API calls.

![image](https://user-images.githubusercontent.com/1392461/180514335-a07392be-19ba-484a-82ae-9fc5a519c334.png)

**Comment by FuhuXia** [comment]
Story #3893 is completed, therefore AC#4 is disregarded. All other ACs are verified.

**Comment by FuhuXia** [comment]
Catalog is switched to cloud.gov today. We immediately see big improvement on the cache performance. Will check back and post another graph a few weeks after the migration when catalog is running normally without extra protection(e.g., 24 hour cache TTL and cached API results)

![image](https://user-images.githubusercontent.com/1392461/182752486-d2f58e5e-9148-449d-bafb-4e09a8036432.png)
