### ISSUE TITLE
Finish work on new version of static site

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3891]
## User Story

Data.gov team needs a completed version of the new static site started by 18F engineers

## Acceptance Criteria

- [x] GIVEN user goes to Data.gov
  THEN user sees new version of static site using 11ty

## Background

18F team assisted with work in migrating former WordPress site that is in Federalist, using 11ty (#3743) but did not have staffing to complete the migration.

## Sketch

- [x] Review https://github.com/cloud-gov/11ty-uswds-template
- [x] Review list of what's been done/what remains to be done (see email screenshot)
- [x] Review status document on https://docs.google.com/document/d/14Nr2GJjmRef_tQfLwp6cUyeXmTaqXFm3etzWfAOg6nQ/edit?usp=sharing
- [x] Work through open items on this [list](https://docs.google.com/spreadsheets/d/1VBgpCsTPgM3RSskRGIM5iugKFtC0igTbTI0oXHWqJYQ/edit?usp=sharing)

![Screen Shot 2022-07-25 at 12.12.34 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/bc344440-2506-43bf-80f9-40e1c1fd9bcf)

**Comment by hkdctol** [comment]
Finishing the work here will complete the footer requirements for Data.gov #3501

**Comment by nickumia-reisys** [comment]
Old Repo: https://github.com/GSA/datagov-website/
New Repo: https://github.com/18F/datagov-11ty/

Current completion metrics: **_12%_**
- Total pages: 996
- Pages complete and/or needs review: 119
- Pages not started: 877

Reached out about [questions](https://gsa-tts.slack.com/archives/C2N85536E/p1658840057130749).   Waiting for feedback before further updates.

**Comment by nickumia-reisys** [comment]
Remaining work consists of:
- [x] Cleaning/Fortifying up styling configuration
  - [ ] Start with [this PR](https://github.com/18F/datagov-11ty/pull/10)
  - [ ] Review additional work as needed
- [ ] Making [PRs like this](https://github.com/18F/datagov-11ty/pull/9) to convert old pages into new pages. (~900 pages minus any duplicates, not sure of true number)
- [x] Having a review of the team for quality assurance
- [ ] Go live 😄

**Comment by btylerburton** [comment]
Once we convert the content, we can optimize some parts of the build with plugins, particularly the image pipeline...

https://github.com/esbuild/community-plugins

**Comment by btylerburton** [comment]
https://federalist-2ac784db-2321-4734-8d02-933835d88304.app.cloud.gov/site/gsa/datagov-11ty/

@hkdctol here's the latest federalist build.

**Comment by hkdctol** [comment]
Will move to done, pending any new tickets on design work,

**Comment by nickumia-reisys** [comment]
For as much as this was completing the content migration from `datagov-website` repo to `datagov-11ty` repo, this has been completed for a while.  Again, we probably forgot to close this issue.  As exciting share (having revisited this ticket), we have a new look brewing! 🦞
