### ISSUE TITLE
Create catalog-admin app

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3893]
## User Story

In order to let catalog admin be able to make changes through the catalog UI and API, data.gov team wants a catalog-admin app that is separated from public catalog app and connected to leader SOLR.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN a user visits https://catalog-prod-datagov.app.cloud.gov/ \
  AND click the [Login](https://catalog-prod-datagov.app.cloud.gov/user/saml2login) link \
  WHEN the user finishes login.gov authentication \
  THEN user is redirected to site admin site https://catalog-prod-admin-datagov.app.cloud.gov/ \
  AND the /dashboard page loads successfully
- [x] GIVEN a logged in admin user visits the admin site to edit a [sample harvest source](https://catalog-prod-admin-datagov.app.cloud.gov/harvest/edit/testfiles-datajson) \
  AND makes and saves changes in the description field \
  WHEN the user visits the [API result on the public app](https://catalog-prod-datagov.app.cloud.gov/api/action/package_search?fq=dataset_type:harvest&q=name:testfiles-datajson)   \
  THEN the newly edit description is shown in the notes field

## Background

Historical Issues:
- https://github.com/GSA/data.gov/issues/3854

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [x] Compared to public `catalog` app, the `catalog-admin` app has a new domain name, connects to SOLR leader, and may need less memory. 
- [x] Changes need to be made on login.gov and identitysandbox.gov to point to the new domain for assertion endpoint and return URL.
- [x] No CloudFront CDN needed
- [ ] ~~The domain names will be `catalog.data.gov` and `catalog-admin.data.gov` after cloud.gov migration.~~ [A new ticket](https://github.com/GSA/data.gov/issues/3908) for this.

**Comment by jbrown-xentity** [comment]
These are the things we customized in the FCS environment. It was all handled at the apache server level. Maybe we could pass the admin route to the nginx buildpack, and do similar customizations? But then, do we need another nginx app in front of the admin app?
https://github.com/GSA/data.gov/blob/master/ansible/roles/software/ckan/catalog/ckan-app/templates/etc_apache2_sites-enabled_ckan.conf.j2#L73-L88

**Comment by FuhuXia** [comment]
> These are the things we customized in the FCS environment. It was all handled at the apache server level. Maybe we could pass the admin route to the nginx buildpack, and do similar customizations? But then, do we need another nginx app in front of the admin app? https://github.com/GSA/data.gov/blob/master/ansible/roles/software/ckan/catalog/ckan-app/templates/etc_apache2_sites-enabled_ckan.conf.j2#L73-L88

We used same catalog-proxy for the catalog-admin app, all Nginx config from catalog-web app is applied to catalog-admin as well. In Nginx we configured to allow GSA network traffic only, for now. Later we may need to consider other methods to stop general public from visiting catalog-admin.
