### ISSUE TITLE
Delete link to dashboard from Data.gov main page

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3897]
## User Story

In order to reduce confusion, delete the reference to dashboard that is on Data.gov home page

## Acceptance Criteria

- [ ] GIVEN user goes to Data.gov main page
  THEN there is no link to dashboard.data.gov

## Background

In user testing, there was some confusion when user clicked on link to dashboard from main page.

## Sketch

- [ ] When we get to the redesign using 11ty, make sure to delete the link to dashboard, as it was confusing to user who clicked on it during test,.![Screen Shot 2022-07-22 at 4.37.35 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/81a4a70b-1e60-43ea-8be7-cafed773e282)

**Comment by hkdctol** [comment]
the link is under "Get Started"

**Comment by hkdctol** [comment]
Closing this as we will be replacing home page soon

**Comment by nickumia-reisys** [comment]
Homepage Replacement
- https://github.com/GSA/data.gov/issues/4141
