### ISSUE TITLE
Create guidance for public users of Data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3899]
## User Story

In order to assist public users of Data.gov, there should be a guide/"how to" for most common uses of the catalog

## Acceptance Criteria

- [ ] GIVEN a user goes to data.gov catalog or data.gov main page
  THEN there is a prominent link to additional resources explaining common uses of catalog.

## Background

User testing in 2022 showed that the catalog is not easy to use for many public users without familiarity with Data.gov. While we have guides for agency users on resources.data.gov, we don't have similar guidance for public users.

## Sketch

- [x] Make a list of most common uses of data.gov
- [x] Review findings in user [testing ](https://drive.google.com/drive/folders/1_fHDPd2BpH0R7pLYBQlnIxlGYjWhfx4Y)
- [x] Create a guidance document for common uses
- [ ] Create the page for user guide in new static site
- [ ] Post to resources.data.gov
- [ ] Link from main data.gov page, and catalog pages

**Comment by hkdctol** [comment]
This is one of the options for Data.gov main page, under discussion in #4029

**Comment by hkdctol** [comment]
Most of the useful text from what's under "Developers" right now can be folded in to a new user guide.

**Comment by nickumia-reisys** [comment]
Not sure if it's helpful, but here's a sample of a [User Guide](https://data.seattle.gov/stories/s/Getting-Started-on-the-Open-Data-Portal/feq8-x3ti/) from the City of Seattle.  I'm not a big fan of this page.  I guess this is an example of what it shouldn't look like (from my perspective).

**Comment by nickumia-reisys** [comment]
This [User Guide](https://www.cambridgema.gov/departments/opendata/data/open-data-user-guide/index.html#/) from the City of Cambridge is pretty impressive in its presentation style, even though it's way beyond the scope of what we are looking to develop.  It is really cool!

**Comment by nickumia-reisys** [comment]
I like the "Beginner", "Intermediate", "Advanced" distinctions in this [User Guide](https://opendata.cern.ch/docs/cms-guide-for-education).  And I think we can at least have the "Beginner" and "Advanced" distinctions in our user guide.  It would help give context to the instructions being given.

**Comment by btylerburton** [comment]
Treating the user guide as a tutorial would go a long way to helping demystify how to actually use the catalog. 

I really like the CERN example (good find @nickumia-reisys) as it's straightforward (not an app!) and actually makes learning how to use data portal fun by working through practical, real-world examples.

**Comment by hkdctol** [comment]
Created screenshots for the user guide. Probably should be trimmed to show the focus areas. But they are in share drive in this [folder](https://drive.google.com/drive/folders/1rslJvUgz-uY68nSWFiwJrmmt9uHKseo4?usp=share_link)

**Comment by hkdctol** [comment]
Text updated https://docs.google.com/document/d/1ZEYty8ZthiRHrAS073QP1A_dZ-XASSQ2YfrQPkmDWXY/edit?usp=sharing

**Comment by hkdctol** [comment]
@btylerburton could you do the next step of creating the page based on the text in the google doc?

**Comment by btylerburton** [comment]
Sure thing. I can take care of that.

**Comment by btylerburton** [comment]
@hkdctol quick question about our link generator...

Do we want to convert a) only explicitly typed links (ex. `http(s)://abcd.efg`), or b) everything that looks like a link (ex. `abcd.efg`)...

My vote is for A.

## a) only explicitly typed links
![Image](https://user-images.githubusercontent.com/104455281/212186995-a13b92ee-c6fc-48f4-bed6-f49adc4cde1d.png)

## b) everything
![Image](https://user-images.githubusercontent.com/104455281/212186996-c09b125a-e049-4fc0-93f7-82d8619f68be.png)

**Comment by hkdctol** [comment]
@btylerburton agree I'd vote A also

**Comment by btylerburton** [comment]
Here's a link to the latest build for that page: https://federalist-2ac784db-2321-4734-8d02-933835d88304.sites.pages.cloud.gov/preview/gsa/datagov-11ty/user-guide-updates/user-guide/

**Comment by hkdctol** [comment]
@btylerburton there's still a redundant "Office of Management and Budget" otherwise looks good, and if you can crop the screenshots

![Image](https://user-images.githubusercontent.com/3236989/213028008-f6a617a9-8f1e-4809-a302-9e730d8c09e6.png)
