### ISSUE TITLE
Declare python version and install path as part of `software/common/ubuntu` role

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#390]
We want to declare the version of python as a variable to the ckan roles, but we want to install the OS python in standard paths.

We currently compile an updated python with `--prefix=/usr/local/lib/python2.7.10`. This is a non-standard path and so we have to manage the `LD_LIBRARY_PATH` env or update `/etc/ld.so.conf` in order to include it. Compiling without an explicit prefix (installing to `/usr/local`) would eliminate the need to manage the extra library path.

**Comment by hkdctol** [comment]
Closing old tickets
