### ISSUE TITLE
replace temporary dev/staging CDN URLs with data.gov domain

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3900]
We are using AWS cloudfront.net URLs for our catalog app in development and staging CDN. Need to create data.gov subdomains and replace the cloudfront.net URLs with `catalog-stage.data.gov` and `catalog-dev.data.gov`.

**Comment by hkdctol** [comment]
Connected to #3988 and #3949

**Comment by FuhuXia** [comment]
This is done. catalog-dev.data.gov and catalog-stage.data.gov are live.
