### ISSUE TITLE
Set up CloudWatch alarms for ECS Solr memory spike

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3903]
## User Story

In order to be aware when ECS Solr is running out of memory, data.gov team wants to notified when ECS task MemoryUtilized reaches certain threshold.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN a ECS Solr task MemoryUtilized reaches 90% \
  WHEN it lasts for more than 1 min \
  THEN an alert is sent to datagov-alerts channel 
- [x] GIVEN a ECS Solr task MemoryUtilized drops below 90% \
  WHEN it lasts for more than 1 min \
  THEN an alert is sent to datagov-alerts channel 

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
Alarm message:
![image](https://user-images.githubusercontent.com/1392461/182902364-f80b5bc3-b1cb-459f-a7a1-33a17df679c4.png)

OK message:
![image](https://user-images.githubusercontent.com/1392461/182902695-8154d9ab-5cae-421b-87d4-33f41b949504.png)

**Comment by nickumia-reisys** [comment]
@FuhuXia Can you document what steps you took to set up this alarm?
