### ISSUE TITLE
Restart SOLR when under memory pressure

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3904]
## User Story

In order to prevent SOLR on ECS running out of memory , data.gov team wants SOLR instances restarted automatically when memory shortage is detected.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] WHEN a SOLR ECS instance's memory Utilization reaches a set threshold \
  THEN an email alert is sent to datagov team \
  an alert sent to datagov-alert slack channel
- [x] WHEN there is an alert for SOLR  memory Utilization\
  THEN the affected SOLR ECS instance is restarted \
  AND an OK alert is sent to email and slack channel

## Background

Historical Issues:
- https://github.com/GSA/data.gov/issues/3903

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
@nickumia-reisys mentioned it might be possible for the [CloudWatch Alarm we have](https://github.com/GSA/data.gov/issues/3903) to take action to restart ECS task.

**Comment by nickumia-reisys** [comment]
Current researched commands:
```bash
# Check the information for an alarm based on name
# Reference: https://awscli.amazonaws.com/v2/documentation/api/2.1.29/reference/cloudwatch/describe-alarms.html
aws cloudwatch describe-alarms --alarm-names "Solr follower 1 MemoryRecovered" "Solr follower 1 OutOfMemory"
```

```bash
# Check which alarms are in the "OK" or "ALARM" state
aws cloudwatch describe-alarms --state-value="OK"
aws cloudwatch describe-alarms --state-value="ALARM"
```

```bash
# Look up the task id based on cluster/service
# service-name/cluster-name taken from `describe-alarm` above
# Reference: https://docs.aws.amazon.com/cli/latest/reference/ecs/list-tasks.html
aws ecs list-tasks --service-name "<service-name>" --cluster "<cluster-name>"
```

```bash
# Restart task
# Reference: https://stackoverflow.com/questions/42735328/aws-ecs-restart-service-with-the-same-task-definition-and-image-with-no-downtime
aws ecs update-service --force-new-deployment --service "<my-service>" --cluster "<cluster-name>"
```

**Comment by nickumia-reisys** [comment]
@FuhuXia The right way to do it would be to set up an SNS topic that is read by AWS Lambda which runs the function to restart the task.

Example: https://docs.aws.amazon.com/lambda/latest/dg/with-sns-example.html

**Comment by FuhuXia** [comment]
@nickumia-reisys Put cloudwatch alarm, SNS, and lambda all into Terraform? Develop has no privilege to manually create lambda.

**Comment by FuhuXia** [comment]
Criteria to send alarm, when the MemoryUtilization goes beyond 25000 for the duration of 1 minute, 4 of 4 datapoints.

Avoid restarting all followers at the same time.

[update]
With 4 of 4 datapoints, cloudwatch still sends another alarm during the the stop/start process. 10 of 10 datapoints is proven to be working. This will avoid sending stop-task command to a service that has an ongoing restart process.

We have three followers. The possibility that all three reach the alarm states at the same time (one after another within ~0.5 hour) is very very low. It is ok to not handle "Avoid restarting all followers at the same time."

**Comment by nickumia-reisys** [comment]
@FuhuXia If you want to jog your memory with brokerpak updates.  This is one instance of creating changes in the `datagov-brokerpak-solr` and then deploying it with `datagov-ssb`.
