### ISSUE TITLE
Disable Catalog CKAN other than the default English

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3905]
We see a large portion of traffic is crawling Catalog CKAN on locales other than default `en`, such as `ru` and `zh_Hans_CN`. We only need to support `en`, We also receives user complaints that the search engines show results in other locales which is confusing. 

Tried CKAN options such as `ckan.locale_default`, `ckan.locales_offered`, `ckan.locales_filtered_out`,  they need to have no effect. We might want to create a Nginx rule to do 301 redirects.

**Comment by mogul** [comment]
@jbrown-xentity already took care of this.

**Comment by jbrown-xentity** [comment]
Completed here: https://github.com/GSA/catalog.data.gov/pull/510
