### ISSUE TITLE
Catalog + Inventory Restarts Failing

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3906]
catalog.data.gov @ main
inventory.data.gov @ main

## How to reproduce

1. Look at failing `Restart` Github Actions for catalog/inventory.

## Expected behavior

Restart successful

## Actual behavior

- https://github.com/GSA/inventory-app/runs/7631908673?check_suite_focus=true
- https://github.com/GSA/catalog.data.gov/runs/7631931299?check_suite_focus=true

![image](https://user-images.githubusercontent.com/85196563/182389712-449e6708-b2a0-4a1d-abd4-de2ad51882e5.png)

![image](https://user-images.githubusercontent.com/85196563/182389757-c1fedb6c-0fad-4f92-aea2-633c52d15d0d.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
Just to note:
- Inventory restarts have been failing since 7/28 (some intermittently working)
- Catalog restarts had a different issue, but started showing the same error as Inventory since yesterday.

**Comment by nickumia-reisys** [comment]
### Manually trying to restart the inventory app showed this error:
![image](https://user-images.githubusercontent.com/85196563/182393987-adc344f8-4746-4be0-8c09-eb4e78f0b1f2.png)

**Comment by FuhuXia** [comment]
catalog restarts fine now. Inventory restart issue and work-around captured in [another ticket](https://github.com/GSA/data.gov/issues/3927). 
This one can be closed.
