### ISSUE TITLE
Create a maintenance page for catalog app

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3907]
## User Story

In order to have a better UI when Calalog app is taken down for maintenance, data.gov team wants to create a maintenance page.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN catalog-app is in normal mode \
  WHEN a  GitHub action is run \
  THEN catalog-app is in maintenance mode 
  AND all web requests except /api/action/status_show are responded with a maintenance page
- [x] GIVEN catalog-app is in maintenance mode \
  WHEN a GitHub action is run \
  THEN catalog-app is back to normal mode

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

For developer without cloud.gov access:
- add a local nginx server on top of your local catalog app.
- use nginx conf from https://github.com/GSA/catalog.data.gov/tree/main/proxy, simplified.
- create a static maintenance page for catalog (html, css, images), stored in nginx /public
- modify nginx conf to take an environment variable, `OPERATION_MODE` 
  - when `OPERATION_MODE=normal` as default, direct traffic to catalog-app
  - when `OPERATION_MODE=maintenance`, direct traffic to the maintenance page

Added step for  developer with cloud.gov access:
- verify by setting (set-env) OPERATION_MODE followed with a cf restart, catalog toggles between normal and maintenance pages.
- convert the cf set-env and cf restart commands into a GitHub action.

**Comment by FuhuXia** [comment]
Due to some fundamental cloud.gov issue, from time to time we may have to delete an app (including catalog-web) and redeploy it, during which a 5 to 6-min of downtime is expected. A maintenance page is helpful in this scenario. 

latest case:
- https://gsa-tts.slack.com/archives/C2N85536E/p1705465491771139
- https://github.com/GSA/catalog.data.gov/issues/1206

**Comment by FuhuXia** [comment]
Will pair with Krishna to work on this.

**Comment by FuhuXia** [comment]
updated the Sketch.

**Comment by krishnasanaka** [comment]
Worked on adding env variables in config file.

**Comment by FuhuXia** [comment]
The four screen shots show
- the github action UI
- the maintenance message
- the unschedule down message, and 
- slack notification. 


![image](https://github.com/GSA/data.gov/assets/1392461/bf97981a-deea-4eca-93bf-2ea0b46d9141)
![image](https://github.com/GSA/data.gov/assets/1392461/b2f1db57-6c28-4ba5-a130-ed251e028e13)
![image](https://github.com/GSA/data.gov/assets/1392461/036407b6-088c-426a-aebc-694760806589)
![image](https://github.com/GSA/data.gov/assets/1392461/044416ac-de86-4cd0-9994-9f484b4a912a)
