### ISSUE TITLE
Hide/Redirect cloud.gov url for catalog app if it is behind CDN

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3909]
We have put catalog-web app behinds CDN, but the cloud.gov url is still working.

## How to reproduce

https://catalog-dev-datagov.app.cloud.gov/api/3

## Expected behavior

No site found, or redirect to CDN url.

## Actual behavior

loads with 200 response.

## Sketch

This should be done after https://github.com/GSA/data.gov/issues/3900, so we can a url easy to remember.

**Comment by mogul** [comment]
I think you can do this by just making the route random/not-obvious.

**Comment by FuhuXia** [comment]
Yeah, making a random url will achieve the same result, almost. My concern is that if it is there, eventually some crawler will be able to find it (e.g., from our github discussion) and we might see some traffic.

**Comment by mogul** [comment]
Right. The app proxy could also reject connections that don't include the CDN header, or only accept connections that come from Cloudfront or the GSA VPN egress range... Various ways to attack this. I'm not sure if cloud.gov has a suggested way to handle it; might be worth asking.

**Comment by FuhuXia** [comment]
Onging discussion:
https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1659551891866499

**Comment by FuhuXia** [comment]
Did user-agent detection and send traffic to 403 if it is not from `Amazon CloudFront`.
https://github.com/GSA/catalog.data.gov/pull/512/commits/935a85dbaf6cbbb3070a19d6909af8a21047e229
