### ISSUE TITLE
Block visitors from accessing prod data in Staging space

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3910]
Catalog in Development and Staging spaces have almost the same database as prod. we should not make prod data publicly accessible on URLs other than catalog.data.gov.

Staging needs an equivalently big database. So we can keep same DB but put Staging behind VPN or basic auth.

Development can have a small database with test data.

**Comment by FuhuXia** [comment]
Production data has been removed from the development space.

**Comment by jbrown-xentity** [comment]
The system used to be configured to only allow certain IP access, but we opened it up. This would be locking it down, but only for staging. See PR here for where we removed it: https://github.com/GSA/catalog.data.gov/pull/511/files

**Comment by jbrown-xentity** [comment]
After sync discussion, we've decided we should pursue basic auth: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by btylerburton** [comment]
Username/password recorded here: https://docs.google.com/document/d/1bfr7W1NPhkbT99g03tktPLAP6nAeyZXBYhEsvP0W4x4/edit?usp=sharing
