### ISSUE TITLE
Create materials for sharing Data.gov experience in migration to cloud.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3912]
## User Story

In order to document and share lessons learned in Data.gov's migration to cloud.gov and use of Supplementary Services Broker (SSB), Data.gov team wants to develop materials (could be in the form of talks, blog posts).

## Acceptance Criteria

- [ ] GIVEN the variety of issues encountered in migrating data.gov to cloud.gov and the use of the SSB and potential interest to colleagues in GSA and elsewhere
  THEN Data.gov team has a set of materials to document and share that information in the form of talks or blog posts.

## Sketch

- [ ] Review the [history ](https://docs.google.com/document/d/1_2GroL3kkzgWePPcNhzRD6SFDc-5Kt0ic8DiZln_TAs/edit?usp=sharing) document on challenges of moving catalog to cloud.gov
- [ ] Select topics for further elaboration
- [ ] Develop content (talks, blog posts, etc.)
- [ ] Present talks or publish blog posts

**Comment by jbrown-xentity** [comment]
@mogul any movement on this?

**Comment by mogul** [comment]
I keep kicking the can down the road, sorry.
