### ISSUE TITLE
Topic icons missing on Catalog

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3915]
## How to reproduce

1. Go to catalog.data.gov
2. Click on Topics
3. See missing icons

![Recording 2022-08-05 at 09 18 30](https://user-images.githubusercontent.com/91547795/183119314-24f97b05-8266-4d60-8464-5db9320a1247.gif)

## Expected behavior

Icons

## Actual behavior

No icons

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by hkdctol** [comment]
Let's revisit after work on new static site gets further along. We intend to replace header with the header that will be built in 11ty and Topics icons will no longer be relevant in that case.

**Comment by hkdctol** [comment]
This is OBE, closing.
