### ISSUE TITLE
Restore catalog from backup

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3918]
## User Story

In order to have a clean data slate, data.gov admins want catalog DB and SOLR restored to pre-harvest state.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN the DB is restored from FCS dump \
  WHEN we cutover \
  THEN the catalog count & datasets is in the old FCS state

## Background

Related to dataset duplication issue

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- Create new catalog app
- Create new DB (from DB backup)
- Create new SOLR
- Resync SOLR
- Cutover app
  - Move new SOLR and DB into catalog and rename SOLR and DB
  - OR switch out app for endpoint (serving traffic)
- Remove old stuff (DB, SOLR, app, etc)

**Comment by FuhuXia** [comment]
Completed. Steps recorded in [slack](https://gsa-tts.slack.com/archives/C2N85536E/p1660222453061519).
