### ISSUE TITLE
Failed to restart inventory app in cloud.gov

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3927]
Inventory in cloud.gov `prod` space can't be restarted. When we issue `cf rs` command, it times out. It is ok in `staging` and `development`  spaces.

## How to reproduce
Run this in `prod` space.
`$ cf rs inventory --strategy rolling`

## Expected behavior

Command succeed.

## Actual behavior

Command times out out.

## Word-around
restart is fine when we have only 1 instance of inventory app. So the current work-around steps are:
```
$cf scale inventory -i 1
$cf rs inventory --strategy rolling
$cf scale inventory -i 2
```
The issue was reported in[ a thread](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1660679897477429) in the` #cg-support` Slack channel.

**Comment by hkdctol** [comment]
Moving to blocked for now pending cloud.gov

**Comment by FuhuXia** [comment]
In a recent change, we [increased disk space to 3G](https://github.com/GSA/inventory-app/pull/472) in order to [allow big resource upload](https://github.com/GSA/data.gov/issues/3173). Obviously 3G disk space is beyond a 2G limit that cloud.gov has as a limit, as a result, we wont be able restart or deploy the app if the app has multiple instances, as discussed in the [cg-support slack thread](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1660679897477429).

**Comment by FuhuXia** [comment]
Some new progress. It might have been fixed. We should give it a try. 
[Slack discussion](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1666815360263169?thread_ts=1660679897.477429&cid=C09CR1Q9Z).
https://github.com/cloud-gov/cg-deploy-cf/pull/710

**Comment by FuhuXia** [comment]
verified this issue to fixed by cloud.gov
