### ISSUE TITLE
Issues with map on Catalog

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3933]
## How to reproduce

1. Go to a dataset with a map on [catalog](catalog.data.gov). For example [this one](https://catalog.data.gov/dataset/noaa-borehole-10006111).
1. Look at the map

## Expected behavior

The map looks and behaves normally.

## Actual behavior

Whatever this is:

![index-1](https://user-images.githubusercontent.com/91547795/186237270-103f277e-b97b-4939-97c7-84de800ab0f2.gif)

Longg map:

![image.png](https://images.zenhubusercontent.com/615477f9d57459b3cbe8ae7a/7388f247-9b12-4d7c-90b5-7880d740e191)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
I think this is a new issue, should be related to some latest theme changes. Also notices some subtle changes on fonts and color here and there.

**Comment by FuhuXia** [comment]
This page looks ok for both chrome and firefox.
https://catalog.data.gov/dataset/western-italian-alps-monthly-snowfall-and-snow-cover-duration

**Comment by nickumia-reisys** [comment]
### Proof for @FuhuXia's post
![map](https://user-images.githubusercontent.com/85196563/186266364-608b4a88-9dd4-458a-a21b-9c08e0811a87.gif)

**Comment by hkdctol** [comment]
Will icebox until it's reproduced

**Comment by hkdctol** [comment]
I don't think we've seen reoccurrence, so closing this.
