### ISSUE TITLE
Search datasets on the main data.gov site gives no results

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3935]
We allow search catalog.data.gov site from data.gov landing page. But the function is broken as of now, giving no results for any search terms.

![image](https://user-images.githubusercontent.com/1392461/186706463-caecd1b8-5d0b-4177-be07-64a5397ef87b.png)

![image](https://user-images.githubusercontent.com/1392461/186706441-372961d6-9e0a-4b1e-bd1b-48975a650e08.png)

## How to reproduce

1. Go to https://data.gov
2. Enter "test" in the search box and Enter.

## Expected behavior

Results shown in the catalog.data.gov site

## Actual behavior

No datasets found for "test"

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by btylerburton** [comment]
I just saw this yesterday! Thanks for creating this issue, Fuhu.

**Comment by btylerburton** [comment]
Should be resolved in new static site repository code (https://github.com/GSA/datagov-11ty). Related to GSA/data.gov#3891

**Comment by btylerburton** [comment]
https://github.com/GSA/datagov-website/blob/main/www.data.gov/index.html#L225

- Anyone know if have a reason to retain these hidden inputs?
- Can we push a new build with federalist pretty easily?

We can fix this pretty easily by removing those.

**Comment by nickumia-reisys** [comment]
Although this will soon be ancient history as the code fix will be live in a deprecated repo due to a fresh and young new data.gov homepage, this was a great first step for @btylerburton into the historical complexities of data.gov 🎐
