### ISSUE TITLE
Create AWS resource inventory list

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3936]
## User Story

In order to keep track of resources used and for compliance purposes, Data.gov team needs an AWS resource inventory list

## Acceptance Criteria

- [ ] GIVEN Data.gov use of AWS resources outside of cloud.gov (Solr) \
  THEN Data.gov has a current inventory of AWS resources used

## Background

SSB/Solr are outside of cloud.gov, and run on AWS accounts billed through Solutions. The resources are not constant, and though they may not change very much going forward, we need a method to always have a current AWS resource inventory list.

Historical issues:
- https://github.com/GSA/data.gov/issues/3826

## Sketch

- [ ] Check all services created using offering `solr-on-ecs` in all spaces, output can be a spreadsheet of containing two lists.
- [ ] First list contains the service `name`, `guid `for `catalog-solr` and `inventory-solr` in the `development`, `staging` and `prod` spaces. These are the servers we know we want to keep
- [ ] Record other services in the second list. These are services created by user for various purpose. We can contact other developers to know their purposes and whether they can be deleted or not.

**Comment by nickumia-reisys** [comment]
[`cloud-nuke` Documentation](https://github.com/gruntwork-io/cloud-nuke#nuke-or-inspect-resources-in-certain-regions)

Example implementation: https://github.com/GSA/datagov-brokerpak-solr/pull/58/files#diff-a4f817543607893caf9e9b3bd9d9af5407ca5239fbf9fd2ccff0e52a94f89c47

**Comment by Jin-Sun-tts** [comment]
https://docs.google.com/spreadsheets/d/1pGZbT8MjDfo3_W70MFmJyDXaym1tQGmFYDNXEA6Lp8o/edit#gid=929673682

**Comment by Jin-Sun-tts** [comment]
Added aws-eks-service service for the inventory list. Here is the  output spreadsheet:
https://docs.google.com/spreadsheets/d/1pGZbT8MjDfo3_W70MFmJyDXaym1tQGmFYDNXEA6Lp8o/edit#gid=929673682


The script to generate the inventory list is here:
https://github.com/GSA/data.gov/blob/add_script_for_get_inventory_list/bin/get_inventory_list.sh
