### ISSUE TITLE
Reintegrate ckanext-spatial upstream into catalog.data.gov

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#3938]
## User Story

In order to reduce our maintenance burden, Data.gov team wants investigate whether we can reintegrate catalog.data.gov with the upstream version of the ckanext-spatial extension.

Reference:
- [GSA/ckanext-spatial](https://github.com/gsa/ckanext-spatial)

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Check if catalog builds and functions correctly with ckanext-spatial upstream.
  - [ ] Reintegrate with upstream.

**Comment by jbrown-xentity** [comment]
We should make sure [our fork of ckanext-spatial](https://github.com/GSA/ckanext-spatial) is as up to date as possible. Review recent PR's to see if anything needs to be merged upstream, or any other fixes.
One specific item [Update Package Schema for Tags](https://github.com/GSA/ckanext-spatial/pull/12) will not be merged. We should take out this code and put it in https://github.com/GSA/ckanext-datagovcatalog. And document the crap out of it.

**Comment by nickumia-reisys** [comment]
Our customizations:
- (Old) https://github.com/GSA/ckanext-spatial/pull/9
  - Overwritten by: https://github.com/GSA/ckanext-spatial/pull/10
- https://github.com/GSA/ckanext-spatial/pull/11
- https://github.com/GSA/ckanext-spatial/pull/12
- https://github.com/GSA/ckanext-spatial/pull/14
- https://github.com/GSA/ckanext-spatial/pull/16

Merged (or at least started) Upstream:
- https://github.com/ckan/ckanext-spatial/pull/252
- https://github.com/ckan/ckanext-spatial/pull/278
- https://github.com/ckan/ckanext-spatial/pull/261

TODO:
- [x] Move package schema update for tags to different extension

**Comment by nickumia-reisys** [comment]
Only one customization is not captured and I believe it is not critical. 
- https://github.com/ckan/ckanext-spatial/pull/261

Can you confirm @jbrown-xentity?

**Comment by nickumia-reisys** [comment]
It was determined that the above changes may cause issues, but will be taken care of in a separate ticket.
