### ISSUE TITLE
Reintegrate ckanext-saml2auth upstream into catalog.data.gov

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#3939]
## User Story

In order to reduce our maintenance burden, Data.gov team wants investigate whether we can reintegrate catalog.data.gov with the upstream version of the ckanext-saml2auth extension.

Reference:
- [GSA/ckanext-saml2auth](https://github.com/gsa/ckanext-saml2auth)

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Check if catalog builds and functions correctly with ckanext-saml2auth upstream.
  - [ ] Reintegrate with upstream.

**Comment by nickumia-reisys** [comment]
This is our only customization:
- https://github.com/GSA/ckanext-saml2auth/pull/1

It was merged upstream:
- https://github.com/keitaroinc/ckanext-saml2auth/pull/72
