### ISSUE TITLE
Catalog does not create any resources from CSW source

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3942]
Catalog does not create any resources from CSW harvest source after migrated to CKAN 2.9 on cloud.gov.

## How to reproduce

Clear and reharvest https://catalog-dev-admin-datagov.app.cloud.gov/harvest/state-csw

## Expected behavior

2 datasets harvested with resources in each.

![image](https://user-images.githubusercontent.com/1392461/188964858-579f540c-1777-4e9a-b1c8-58faf7a2461e.png)

## Actual behavior
2 datasets harvested without any resources.

![image](https://user-images.githubusercontent.com/1392461/188964892-86005746-5835-41cc-a539-46f268627629.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
This is probably another residual PY3 conversion bug.

**Comment by jbrown-xentity** [comment]
Related to #3938 , the CSW harvesting is in ckanext-spatial and we don't want to maintain a fork long term.

**Comment by jbrown-xentity** [comment]
I believe this has been resolved...

![Image](https://user-images.githubusercontent.com/26980513/204665301-dd0c839c-df95-4120-94c3-c055004e668b.png)

**Comment by jbrown-xentity** [comment]
See https://catalog.data.gov/harvest/opentopography-csw and https://catalog.data.gov/harvest/geonode-state-csw as current examples.

**Comment by hkdctol** [comment]
Archiving for now the one active source (State) has resources

**Comment by nickumia-reisys** [comment]
I believe I closed this because we no longer support CSW harvesting, but I revisited this issue in pursuit of the harvesting requirements work and I want to make sure it is for the right reason:
- https://github.com/GSA/data.gov/issues/4411
- https://github.com/GSA/catalog.data.gov/pull/921
