### ISSUE TITLE
Opt-in to using the new vCPU-based quotas for Amazon ECS task

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3946]
AWS announcement: [AWS Fargate announces migration of service quotas to vCPU-based quotas](https://mail.google.com/mail/#search/AWS+Fargate+announces). The transition to vCPU quotas will not have any impact on running tasks and pods.

We might want to opt-in our ECS tasks earlier  to use vCPU quotas to test it out.

Timelines:

- Phase 1: starting **September 8, 2022**, you can opt-in to use vCPU quotas earlier.
- Phase 2: starting **October 3, 2022** all accounts will be automatically migrated to the new vCPU-based quotas in a phased manner
- Phase 3: starting **November 1, 2022**,  Fargate will automatically transition accounts to vCPU quotas regardless of your account settings

**Comment by nickumia-reisys** [comment]
This should be a no-op.

Reference: https://aws.amazon.com/blogs/containers/migrating-fargate-service-quotas-to-vcpu-based-quotas/

**Comment by FuhuXia** [comment]
> This should be a no-op.
> 
> Reference: https://aws.amazon.com/blogs/containers/migrating-fargate-service-quotas-to-vcpu-based-quotas/

I doubt it will affect our application in any way. But to play by the book, we can
1. Exam our current quota usage 
2. Call  [PutAccountSettingDefaultAPI](https://docs.aws.amazon.com/cli/latest/reference/ecs/put-account-setting-default.html)  to proactively change the quota to vCPU before phase II on staging then prod to make sure no service disruption.

**Comment by hkdctol** [comment]
Closing as not needed.
