### ISSUE TITLE
Re-integrate (QA | ARCHIVER | REPORT) extensions to catalog.data.gov

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3957]
## User Story

In order to restore dilapidated features on catalog.data.gov, the Data.gov Catalog team wants to re-integrate [`ckanext-qa`](https://github.com/GSA/datagov-ckan-multi/issues/574), [`ckanext-archiver`](https://github.com/GSA/datagov-ckan-multi/issues/578) and [`ckanext-report`](https://github.com/GSA/datagov-ckan-multi/issues/580).

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN the extensions have been deployed to production \
  WHEN I visit a dataset on catalog.data.gov \
  THEN I can see that the extensions are live at https://catalog.data.gov/api/action/status_show

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]
- [x] Incorporate the extensions into a local test environment
- [x] Inspect how the extensions work with some test data
- [x] Add tests
- [x] Deploy to development on cloud.gov
- [x] Fix bugs (if there are any)
- [x] Deploy to production

**Comment by nickumia-reisys** [comment]
## List of things that work and don't work

### `ckan report generate openness` -- OK

![image](https://user-images.githubusercontent.com/85196563/191290547-bd13a3fd-01e8-4cc9-af3f-8812e15376d2.png)

### `ckan qa update` -- OK

![image](https://user-images.githubusercontent.com/85196563/191290689-fa2f9e68-f2c2-484d-8a6d-eb102bf9fc7e.png)
![image](https://user-images.githubusercontent.com/85196563/191290824-92ea0bb7-8f02-4ee5-bde0-f0b337df134f.png)

### `ckan report list` -- OK

![image](https://user-images.githubusercontent.com/85196563/191291011-ad9f1ee9-388b-450b-9e3c-3e6054aee23a.png)

### Visiting `/report` -- OK

![image](https://user-images.githubusercontent.com/85196563/191291243-65705e96-f2a4-447a-bd66-9333d8a479a4.png)

### Visiting `/report/broken-links` -- OK

![image](https://user-images.githubusercontent.com/85196563/191291447-f183df4a-4883-4f11-acce-303dc74b0bb7.png)

### Visiting `/report/openness` -- NOT OK

- https://github.com/GSA/data.gov/issues/3964
![image](https://user-images.githubusercontent.com/85196563/191291707-695d0aa6-2e1a-4970-9641-fd843cbdd153.png)

### Openness scores on datasets -- NOT OK

- https://github.com/GSA/data.gov/issues/3965

### Openness scores on resources -- NOT OK

- https://github.com/GSA/data.gov/issues/3966

**Comment by nickumia-reisys** [comment]
`cf run-task catalog-web -c "ckan report generate openness" -k 2G -m 2G` 
- Took `6 mins` to complete `28834 datasets` on development
- ETA for prod: `270 mins`

**Comment by nickumia-reisys** [comment]
`cf run-task catalog-web -c "ckan qa update" -k 2G -m 2G`
- Took `3 mins` to complete `28834 dataset` on development
- ETA for prod: `135 mins`

**Comment by nickumia-reisys** [comment]
Note: We are on a fork of [`ckanext-qa`](https://github.com/gsa/ckanext-qa)
- https://github.com/GSA/ckanext-qa/pull/10

**Comment by jbrown-xentity** [comment]
> Note: We are on a fork of [`ckanext-qa`](https://github.com/gsa/ckanext-qa)
> 
> * [PY3 Fix - iteritems only in PY2 ckanext-qa#10](https://github.com/GSA/ckanext-qa/pull/10)

Do we want to attempt to merge these changes back upstream? That might be a separate ticket... Or were there more changes than just the PR above?

**Comment by nickumia-reisys** [comment]
So... archiver tries to use [Redis to process the archival queue, but falls back to celery if there is an ImportError](https://github.com/ckan/ckanext-archiver/blob/master/ckanext/archiver/lib.py#L14-L22) 😕 

It looks like it's falling back to celery, but I'm not sure why...
![image](https://user-images.githubusercontent.com/85196563/191528621-f980fd4b-2c78-431e-8132-d8c4e394af20.png)

Since celery is not installed, the openness score is not computed per dataset.

------------------------

> Do we want to attempt to merge these changes back upstream? That might be a separate ticket... Or were there more changes than just the PR above?

@jbrown-xentity That was the only PR.  We can try to merge it upstream.  But I think upstream is still supporting PY2, so we'd have to do a conditional `iteritems` for PY2 and `items` for PY3.  When they completely drop support for PY2, it's an easy merge upstream.. but right now, I don't think they'll take it.

**Comment by nickumia-reisys** [comment]
This is the solution to getting the queue to finish!!
- https://github.com/ckan/ckanext-qa/issues/67#issuecomment-533595304

We need to specify the queue that has the work to do when calling `ckan jobs worker`
```bash
ckan jobs worker bulk
```

**Comment by nickumia-reisys** [comment]
Welp... looks like they don't care about PY2 support after all, Yay!
- https://github.com/ckan/ckanext-qa/pull/75
- https://github.com/ckan/ckanext-qa/pull/75/files#diff-4c03098a67d3e12c420b0d7dcaead5c049f389c7c918a4c59909858f4268a736R75

The above PR fixes two issues.  The `.items()` issue and the template not found issue 😅

**Comment by nickumia-reisys** [comment]
Also going to note, at least we know of at least one CKAN instance that is actively use the QA extension, Finnish Digital Agency 
- https://github.com/vrk-kpa
