### ISSUE TITLE
Harvest error: Transformation to ISO failed

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3959]
Received harvest job reports for https://catalog.data.gov/harvest/environmental-dataset-gateway-fgdc-csdgm, it contains 1383 errors with message "Transformation to ISO failed".

This harvest source was harvested fine in FCS with CKAN 2.8 before 08/01/2022, the day we took final FCS DB snapshot.

![image](https://user-images.githubusercontent.com/1392461/190724844-40c5bfbe-c87a-4823-9fbe-a709902c694d.png)

## How to reproduce

https://catalog.data.gov/harvest/environmental-dataset-gateway-fgdc-csdgm

## Expected behavior

Harvest successful
## Actual behavior

Transformation to ISO failed

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
DOT WAF source cant be updated due to this issue. 
https://catalog.data.gov/harvest/national-transportation-atlas-database-ntad-metadata

**Comment by jbrown-xentity** [comment]
This is a catch-all error I believe, this may need further investigation. There may be multiple reasons for these errors.

**Comment by FuhuXia** [comment]
For some harvest sources, it failed for all records with this error, such as DOT one.  For other sources , it only failed for some records, such as this one https://catalog.data.gov/harvest/environmental-dataset-gateway-iso-geospatial-metadata.

**Comment by nickumia-reisys** [comment]
Fixed by
- https://github.com/GSA/data.gov/issues/4173
