### ISSUE TITLE
dashboard gives 500 error

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#3961]
The dashboard site is unavailable when there are a lot of traffic, this traffic appears come from a crawling script

![image](https://user-images.githubusercontent.com/104456257/191063356-863a5661-9c45-42e4-9c05-f0747addc1ea.png)

## How to reproduce

slack datagov-alerts channel 

## Expected behavior

This site should have very light traffic, so the site should be stay up. 

## Actual behavior

too much traffic, the site responding 500 error to all requests

## Sketch
Try the following approaches in order. Maybe one of them, or two combined, will solve the issue
- [x] scale up dashboard instance
- [x] resovle the error `[pool www] server reached pm.max_children setting (5), consider raising it`, `Error dispatching request to : (polling)`
- [ ] customize CDN on cloud.gov (enable rate-limit, increase caching time)
- [x] create CDN in oppprod with rate-limit enabled account

**Comment by FuhuXia** [comment]
scaling up to 4 instances does not seems to help. trying PHP config changes...

**Comment by FuhuXia** [comment]
We are adding a CDN on top of dashboard with rate-limit enabled. Our existing data.gov certs does not include dashboard.data.gov as a SAN (subject alternative name). Created [a JIRA ticket](https://cm-jira.usa.gov/servicedesk/customer/portal/12/FCSTS-3516) for a new certificate. The old one [is expiring](https://github.com/GSA/data.gov/issues/3949). 
```
data.gov
catalog.data.gov
dashboard.data.gov
catalog-dev.data.gov
catalog-stage.data.gov
dashboard-dev.data.gov
dashboard-stage.data.gov
```

**Comment by hkdctol** [comment]
Going to put back since we're working on dashboard replacement.

**Comment by hkdctol** [comment]
Closing dashboard issues
