### ISSUE TITLE
Remove harvest report email list from public view

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3967]
There is no need to expose organization harvest report email list to general public.

## How to reproduce

https://catalog.data.gov/organization/about/doj-gov

## Expected behavior

email does not show

## Actual behavior

email addressed shown

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by hkdctol** [comment]
Just got an agency request about this, so let's fix this this sprint.

**Comment by nickumia-reisys** [comment]
### Success 🛩️ 

![image](https://user-images.githubusercontent.com/85196563/201136053-5c9efc44-6f04-4e72-8817-9a6713785df0.png)
