### ISSUE TITLE
Upgrade production database to Postgres 9.6

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#397]
We've upgraded the production instance to 9.4.18 since [AWS was retiring 9.3](https://trello.com/c/79oSNUGD/67-postgres-93-retirement). In order to upgrade to 9.5, we need to upgrade and then upgrade PostGIS to 2.2.5. Then we can upgrade to Postgres 9.6, and then PostGIS to 2.3.5.

~To prevent downtime, we should upgrade the read replicas first, one at a time. Last time BSP removed the replicas and re-created them which meant we couldn't even switch to a live replica to prevent downtime for users. Once the read replicas are upgraded, we can upgrade the master. Once they are all updated, then we can run the PostGIS upgrade via ansible playbook.~

We'll discuss with BSP on the best method to upgrade. [AWS suggests](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion) the read replicas cannot be upgraded through major versions. Once the master is upgraded, add new read replicas and phase out the old ones in a create-before-destroy fashion. Once they are all updated and replication is stable, then we can run the PostGIS upgrade via ansible playbook.

**Comment by adborden** [comment]
This query will show you what versions are available:

```sql
SELECT * FROM pg_available_extension_versions WHERE name = 'postgis';
```

This will show you the current versions:

```sql
SELECT version();
SELECT postgis_lib_version();
```

And this is the command to upgrade the extension:

```sql
ALTER EXTENSION postgis UPDATE TO '<version>';
```

**Comment by JJediny** [comment]
completed

**Comment by adborden** [comment]
FYI, I think production is actually on 9.4, but that's good enough. We'll probably replace the RDS instance with an up-to-date version before AWS end-of-lifes this one.
