### ISSUE TITLE
Chrome and MS Edge fail to download HTTP resource

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3974]
If a dataset on catalog contains a HTTP resource, `Chrome` and `Edge` users are not able to click and download the resource.

Chrome user clicks and nothing happens. On the Developer Tools it shows HTTP->HTTPS redirect then nothing.
![image](https://user-images.githubusercontent.com/1392461/192570784-dd5ed92b-147b-4f1d-b735-17baebc457cc.png)

Edge user clicks the link then sees a popup with error message. 
```
... can't be downloaded securely
```

![image](https://user-images.githubusercontent.com/1392461/192571395-1a34a03b-94c4-4aba-b3b0-3640a4071f34.png)

## How to reproduce
Go the this dataset page and click the zip file link
https://catalog.data.gov/dataset/military-installations-ranges-and-training-areas
https://catalog.data.gov/dataset/military-installations-ranges-and-training-areas/resource/61798a6b-57ff-41f2-8f1c-1a22c70f8524

## Expected behavior

Browser downloads the zip file

## Actual behavior

`Chrome` and `Edge` do not download

## Work-around

Copy link URL and paste into browser URL field.
Or, use `Safari` or `Firefox`.

## Sketch

Harvesting job can check the resource to be HTTPS only.

**Comment by jbrown-xentity** [comment]
Related to https://github.com/GSA/data.gov/issues/3476

**Comment by jbrown-xentity** [comment]
This is a fun one. I found 2 http links, one works and one doesn't:

- Working: https://catalog.data.gov/dataset/food-price-outlook
- Not working: https://catalog.data.gov/dataset/military-installations-ranges-and-training-areas

Should investigate further about why one is working, and the other does not. For reference, when something isn't working you still get a mouse icon change to what you would expect for a link; clicking on it does nothing however. If you right click, you can copy the URL and paste in chrome and it goes there fine.

**Comment by FuhuXia** [comment]
Even it is a http link, chrome allows you to click and it does follow the http->https redirecting. If the redirecting is a web page in https, it is working. If the redirecting is a download, it will get blocked, even it is https.

**Comment by jbrown-xentity** [comment]
We intend to address this at the data source level, improving data quality from the provider. We don't intend to force redirects to https of harvest sources. We are going to close this, as we will not be implementing any code fixes for this.
