### ISSUE TITLE
Remove extra comma in the inventory date field

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3978]
All date fields in the Inventory dataset form has a extra leading comma.

![image](https://user-images.githubusercontent.com/1392461/193057572-2306e9f9-c3db-4316-a7d1-c85fccaadc45.png)

## How to reproduce

Create or edit a dataset in Inventory, go to any date field

## Expected behavior

field display as `MM/DD/YYYY`

## Actual behavior

`, MM/DD/YYYY`

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
This seems like it would come from the `dcat-usmetadata` extension... but when I converted this extension from PY2 to PY3, this wasn't an issue.  So I'm confused when this would have happened.

**Comment by jbrown-xentity** [comment]
This seems fine now...

![Image](https://user-images.githubusercontent.com/26980513/205167498-d8d92344-78f8-4be3-947e-7bcb7e2d9828.png)
