### ISSUE TITLE
Catalog doesn't work with latest pysaml2

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3980]
See https://github.com/GSA/data.gov/issues/3969 for current mitigation, pinning pysaml2 to 7.0.1
We tested this with inventory, and it worked fine: https://github.com/GSA/inventory-app/actions/runs/3153444373
![image](https://user-images.githubusercontent.com/26980513/193122105-5fc22952-6b33-487f-b246-1e5577a2113d.png)

Something is causing specifically catalog to not like this version.
It's possible it has something to do with [pinning catalog to python 3.7](https://github.com/GSA/catalog.data.gov/blob/main/runtime.txt#L1). However, upstream does intend for this to work with [python2.7](https://github.com/keitaroinc/ckanext-saml2auth/blob/main/.github/workflows/ci.yml#L38), though the latest main branch test was [3 months ago](https://github.com/keitaroinc/ckanext-saml2auth/actions/workflows/ci.yml)

## How to reproduce

1. Allow normal upgrade of catalog (remove [this](https://github.com/GSA/catalog.data.gov/blob/main/ckan/requirements.in#L20-L21) and update requirements, or change [this](https://github.com/GSA/catalog.data.gov/blob/main/ckan/requirements.txt#L76) to latest)
2. Push to development (create local feature branch, and use `git push origin feature-branch:develop`)
3. Try logging in

## Expected behavior

Login works successfully

## Actual behavior

Login internal server error

## Sketch

Debug via logs, see if there is anything relevant. I expect something is going on with python version since inventory works fine, but there may be other details we're missing.

**Comment by nickumia-reisys** [comment]
Being on Python 3.8 for catalog now, I thought this would be resolved, but it isn't.  Oh well.

**Comment by hkdctol** [comment]
If we get to CKAN 2.10 this one should be obsolete.

**Comment by nickumia-reisys** [comment]
We are on a non-vulnerable version (although not latest).  If a vulnerability appears, we can upgrade in a new issue.
- [SNYK Vulnerabilities](https://security.snyk.io/package/pip/pysaml2)
- [GSA ckanext-saml2auth requirement](https://github.com/GSA/ckanext-saml2auth/blob/main/dev-requirements.txt#L2) - no version specification
- [Upstream ckanext-saml2auth requirements](https://github.com/keitaroinc/ckanext-saml2auth/blob/main/dev-requirements.txt#L2) - no version specification
- [catalog.data.gov requirement](https://github.com/GSA/catalog.data.gov/blob/1322ad65d23e8d8190cd742520320d4ab370782a/ckan/requirements.in#L20) - `v7.0.1`
- [inventory.data.gov requirement](https://github.com/GSA/inventory-app/blob/382e36e360f95b3dd893fed2163c65c3c15ef41e/requirements.in.txt#L43) - `v7.0.1`
