### ISSUE TITLE
[Discovery] Build Report to replace Dashboard

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3982]
## User Story

In order to retire dashboard, data.gov admin wants a similar data report on the metadata in catalog.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN research is complete \
  THEN a path is documented on how to build a report

## Background

Related to recent release of catalog with the report extension: https://github.com/ckan/ckanext-report

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

There was [previous analysis](https://docs.google.com/document/d/1_q9qHwzSrd2_TzbTJkWqlvcibD6tWyoK3wYNHfy2Fx0/edit#heading=h.81d43aps8pug) that examined what it would look like to gather the data via the API.
We also want to examine if anyone has created a ckanext-report extension that does this (or something similar).
The final step of this ticket should just be a summary of findings: 
1. Extensions that implement ckanext-report in a similar manner
2. Documentation/links around how to build our own report
3. Document data needed to replicate dashboard report

**Comment by jbrown-xentity** [comment]
A first pass at building a csv was done [here](https://docs.google.com/document/d/1_q9qHwzSrd2_TzbTJkWqlvcibD6tWyoK3wYNHfy2Fx0/edit#heading=h.8oilp0lq56qd). See previous ticket notes [here](https://github.com/GSA/data.gov/issues/1757).

**Comment by nickumia-reisys** [comment]
Documentation on how to make a new report extension: https://github.com/ckan/ckanext-report#creating-a-report

**Comment by nickumia-reisys** [comment]
From preliminary research about CKAN Extensions and the requirements of using `ckanext-report`, it seems like there is no other extension that is generating reports using this extension other than `ckanext-qa`.  (Definition of "no other extension" meaning no other active/recent, successfully building or dependent on the `ckanext-report` extension)

Investigations completed:
- https://extensions.ckan.org/
- Looking on Github and Google for references to `ckanext-report`
  - https://github.com/search?p=1&q=requires+%22ckanext.report%22&type=Code
  - https://www.google.com/search?q=github+%22ckanext.report%22


Closest results (but not at all useful):
- https://github.com/geosolutions-it/ckanext-gsreport
- https://github.com/abdelrahman146/opendata (don't know why there's a bunch of extensions just listed here 🤷 )

**Comment by jbrown-xentity** [comment]
To make a new repo: https://github.com/GSA/data.gov/wiki/Checklist-for-new-repositories
To make a new CKAN extension, use CKAN command documented [here](https://docs.ckan.org/en/2.9/extensions/tutorial.html#creating-a-new-extension)

**Comment by nickumia-reisys** [comment]
@btylerburton @Jin-Sun-tts When one of you gets a chance, can you just following the `Checklist for new repos` to create a new repo called `ckanext-dashboard`?  (We can always rename it later, if someone has a better name)  Also, if you have a better name, by all means, use it 😄

**Comment by btylerburton** [comment]
Glad to. How about `ckannext-report-dashboard`?

**Comment by nickumia-reisys** [comment]
I agree `dashboard` is waayyyy too vague.  I thought I saw `metrics-dashboard` from you before (but maybe I was hallucinating).  I liked `metrics-dashboard`.  I think `report-dashboard` is a bit too misleading, all of the reports won't be shown on this dashboard... unless that is the intended design?  Then, I can join that bandwagon :carousel_horse:

**Comment by btylerburton** [comment]
https://github.com/GSA/ckanext-metrics-dashboard
Base repo created. Let's pair to add GH actions and a make file.

**Comment by nickumia-reisys** [comment]
Sketch Item 1. See comment above https://github.com/GSA/data.gov/issues/3982#issuecomment-1265534184

Sketch Item 2. Completed
> Documentation on how to make a new report extension: https://github.com/ckan/ckanext-report#creating-a-report

Sketch Item 3. No idea where to start.

**Comment by jbrown-xentity** [comment]
Check out [previously built spreadsheet](https://docs.google.com/spreadsheets/d/1W251dBWw35nx_R8E8H7SVUVNvhK6imPPZQeYGuKYFMM/edit#gid=0) as a starting point for what fields we want. This is intended for auditors and/or organization admins to validate how they are doing. Key points are:
- Summary by organization
- Recent harvest dates
- Most recent data modified dates (not CKAN modified date, the data modified date)
- Number of datasets
- Number of resources
- Number of items that are failing to harvest (this one we might not want to make publicly available, @hkdctol thoughts?)

If this is difficult, we can break it down by harvest instead.

**Comment by nickumia-reisys** [comment]
This is well documented enough that I don't have a comment to add 🥲

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data.gov/issues/3502
