### ISSUE TITLE
manual and automate running db_solr_sync task

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3985]
## User Story

In order to clean up discrepancies between catalog DB and Solr, data.gov team wants to be able to run [`db_solr_sync`](https://github.com/GSA/data.gov/issues/2213) manually and on scheduled GitHub actions.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x]  WHEN `db_solr_sync` is run as CF task \
  THEN a dry run will show the DB-Solr discrepancies \
  AND real run will synchronize DB and Solr

- [x] GIVEN a GH action is created for `db_solr_sync` \
  WHEN `db_solr_sync` action is manually run \
  THEN a dry run will output the DB-Solr discrepancies 
  AND a real run will synchronize catalog DB and SOLR

- [x] GIVEN a GH action is scheduled to run for `db_solr_sync` \
  WHEN it is on schedule time \
  THEN `db_solr_sync` is run \
  AND catalog DB and SOLR are synchronized

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
Same as other GH action to get credential secrets to run CF task on GitHub.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by robert-bryson** [comment]
This action will probably look quite similar to the [`sitemap-to-s3` one](https://github.com/GSA/catalog.data.gov/blob/main/.github/workflows/s3-to-sitemap.yml).

**Comment by nickumia-reisys** [comment]
This was implemented for a while now and has been running every day.  We probably just forgot to close this issue.
