### ISSUE TITLE
Improve PR review/workflow

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3993]
## User Story

In order to write better and more sustainable code, data.gov QA wants PR templates for all repo's that have regular changes.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a template is in place for data.gov repos \
  WHEN a PR is made for the data.gov team \
  THEN a checklist exists to make sure key use cases are covered

## Background

We are constantly frustrated by functions and classes that are not clearly defined and misunderstood, both in CKAN community in general and in our own extension code. We discussed idealized improvements, see below.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

We have a first pass done [here](https://github.com/GSA/ckanext-geodatagov/blob/main/.github/pull_request_template.md), the file location should be the same across repositories.
We should do the list of repositories [here](https://github.com/GSA/data.gov/wiki/Hmm...-where-to-start%3F-by-nickumia), and their sub-dependencies (for example, [catalog dependencies](https://github.com/GSA/catalog.data.gov/blob/main/ckan/requirements.in#L6-L18))
Our idealized list includes the following:

[Summary of what this does]

Related to [TICKET]

- [ ] Tests added to cover change
  - [ ] Unit tests
  - [ ] Integration tests
- [ ] Code comments (the what/why, not the how)
- [ ] Change Log
- [ ] Feature documentation (readme, etc)
  - [ ] What does this code do/accomplish?
- [ ] [If changes to cloud.gov/infrastructure], has this been deployed to develop?
- [ ] [If required] Bumped version?
- [ ] [If required] Does scale matter? If so, has this been tested/evaluated for memory needs?

**Comment by hkdctol** [comment]
What are the repositories that this should be added to?

**Comment by nickumia-reisys** [comment]
If we can configure this at an organization level, it would help a ton since we wouldn't need to duplicate this file 15 times for each of our repos.  According to [this SO answer](https://stackoverflow.com/a/62293875), it's possible, but I don't know how to do it.

cc @btylerburton @Jin-Sun-tts

**Comment by btylerburton** [comment]
Given this would apply to the whole of GSA, if I'm reading this correctly, I think it would be easier to add it to our repos individually.

**Comment by nickumia-reisys** [comment]
Well, two things... (1) Even if it is at the GSA org-level, we can preface it with "data.gov" and it wouldn't hurt that others have access to it.  (2) If we don't want to do that, maybe we can create it as part of the `datagovteam` thing?

It makes maintenance super hard with the 10s of files duplicated across repos that don't need to be 😢

**Comment by nickumia-reisys** [comment]
So technically, the organization-level solution wouldn't need external help.  We would be able to implement it ourselves; we decided against it, but here's the reference anyway:
- https://chromatichq.com/insights/sharing-github-issue-pull-request-templates/

**Comment by btylerburton** [comment]
@btylerburton to check if this can be applied to the team level.

**Comment by nickumia-reisys** [comment]
I don't think this issue is well-defined in it's implementation methodology.  I agree we should formalize our PR review process and I think the steps outlined in the sketch are good enough to use for this part.  However, the other part is creating a process that is easy to maintain.  (I doubt this can be implemented at the team level, I wish it was).

Since circumstances are such that we need to be more agile than normal, I am a strong proponent of creating sustainable processes and designs.  Creating duplicate templates that need to be updated individually is not sustainable.  I would say the best thing would be to keep the template in our Wiki and then make it a human job to copy and paste it when making a new PR.

**Comment by btylerburton** [comment]
Doesn't look like this can be applied at the Team level. Only the whole org.

**Comment by btylerburton** [comment]
I agree with Nick's sentiment here:

> I would say the best thing would be to keep the template in our Wiki and then make it a human job to copy and paste it when making a new PR.

**Comment by btylerburton** [comment]
Added PR Template page to wiki and to wiki landing page Project/Team heading

- https://github.com/GSA/data.gov/wiki
- https://github.com/GSA/data.gov/wiki/Pull-Request-Template
