### ISSUE TITLE
Update Github Action environment varibles

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3996]
## User Story

In order to [consolidate and clean up the Github actions code], [datagov team] wants [refactor our Github actions using the new `environ` inputs] and [clean up `prod` vs `production` naming].

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

Repos that run actions that will likely need to be updated:
	- datagov-ssb
	- inventory-app
	- catalog
	- data.gov
	- datagov-logstack
	- mystery repo number 6

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]
- [ ] Check existing actions for repeated code for different environements/spaces, if possible update to use `environ` as per [this example](https://github.com/GSA/catalog.data.gov/blob/main/.github/workflows/db-solr-sync.yml#L18)
- [ ] Check secret values in repo settings
- [ ] Remove old `production` credentials

**Comment by nickumia-reisys** [comment]
@btylerburton Can you verify that we've complete this?  I think we set everything up, but I guess can you just check the settings again?  The only ones that are important are probably:
- [x] data.gov
- [x] inventory
- [x] catalog

If we want to update the other repos in the future, we can always re-open the issue.  But I don't think this applies to anything else.
