### ISSUE TITLE
Quota exceeded when run any CF task on catalog-admin 

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3998]
Failed to run any task on catalog-admin app. It gives `Quota exceeded` error.

## How to reproduce
Run command on `development` space:
```
cf run-task catalog-admin -c "ls"
```
## Expected behavior

SUCCESS

## Actual behavior
FAILED
```
[CELL/0] ERR Copying into the container failed: stream-in: nstar: error streaming in: exit status 2. Output: tar: ./app/ only 2560 of 10240 bytes
[CELL/0] ERR tar: ./app/vendor/Markdown-3.1.1-py2.py3-none-any.whl: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/vendor/xlrd-2.0.1-py2.py3-none-any.whl: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/vendor/PyUtilib-5.7.1-py2.py3-none-any.whl: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/vendor/m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/vendor/click-7.1.2-py2.py3-none-any.whl: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/.env: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/.prettierrc: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/.profile: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/.snyk: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/Dockerfile: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/Makefile: Cannot open: Quota exceeded
[CELL/0] ERR tar: ./app/README.md: Cannot open: Quota exceeded
```
## Work-around

scale up the disk quota in the command line

cf run-task catalog-admin -c "ls" `-k 1200M`

**Comment by FuhuXia** [comment]
catalog app disk usage changed from `988.9M` to `1.1G` in the past a few days, exceeding the default `1G`.

**Comment by nickumia-reisys** [comment]
We've seen this issue at various times since the beginning of the year.  There is no cost to increase disk quota, but there are limits on how much it can be scaled.  The theoretical limit is `6G`, but the highest I've been able to witness is `3G`.

**Comment by hkdctol** [comment]
@FuhuXia will bring up with cloud.gov support

**Comment by FuhuXia** [comment]
> We've seen this issue at various times since the beginning of the year. There is no cost to increase disk quota, but there are limits on how much it can be scaled. The theoretical limit is `6G`, but the highest I've been able to witness is `3G`.

This is different issue. It is not about the disk_quota we set for the app in the manifest.yml. It is the running task is not using the set disk_quota, but using default 1G.

**Comment by FuhuXia** [comment]
[Slack discussion](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1665110872250089) in cg-support channel.

**Comment by nickumia-reisys** [comment]
P.S. I've needed to specify it on `run-task` too, I just never questioned it.

**Comment by FuhuXia** [comment]
It turns out that the task always uses the  default memory and disk allocations specified by the `cc.default_app_memory` and `cc.default_app_disk_in_mb` properties in the system-wide [Configuration Properties](https://docs.cloudfoundry.org/devguide/using-tasks.html). The work-around is the fix.

We can close this ticket.

**Comment by nickumia-reisys** [comment]
Cloud.gov is weird. 🪱
