### ISSUE TITLE
Integrate shibboleth with Kibana auth proxy

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#40]
Implement two factor auth on Linux servers using [Shibboleth](https://shibboleth.net/)
Test site: http://www.testshib.org/

We will need to integrate shibboleth authentication with our kibana server, once that is up and running (#74)

**Comment by neilhunt1** [comment]
From Eric: We have installed and configured an IDP and a SP server. However, we are not able to access the metdata.xml file from the idp server, which may be preventing us from accessing the login page. We are close to getting this going, the inability to access the metadata.xml file has halted the process.

**Comment by kvuppala** [comment]
@JJediny As we have enabled GA two factor on Jumpbox, can we close this?

**Comment by JJediny** [comment]
Closing for now as it's already part of another ticket, the approach is now to add a Max.gov domain @ management.data.gov and set up a SAML proxy using Nginx instance in VPC
