### ISSUE TITLE
Deploy latest redis playbooks to production

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#400]
- [x] update the playbook to install to `/usr/local` instead of `/opt` to avoid permissions issues with the hardening script
- [x] Run the `remove_old_redis` playbook to remove Redis 2.x
- [x] Run the harvester playbook with redis tag to push Redis 4.x

**Comment by JJediny** [comment]
Completed

**Comment by adborden** [comment]
Apply to production
- [ ] catalog playbook catalog-harvester hosts
