### ISSUE TITLE
Redirect Dashboard Data.json Validator

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4001]
## User Story

In order to deprecated Dashboard Data.json Validator, the Data.gov Validation Team wants to forward the existing dashboard validator route to the new catalog validator.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] WHEN I visit https://dashboard.data.gov/validate
    THEN my browser is redirected to the new validator location

## Background
Current dashboard validator exists [here](https://labs.data.gov/dashboard/validate).
New dashboard validator exists [here](catalog.data.gov/dcat-us/validator).
- https://github.com/GSA/data.gov/issues/3503

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Not sure?

## Sketch

- [ ] Create a proxy rule in `www-redirects` app
  - [ ] Redirect `dashboard.data.gov/validate` to `catalog.data.gov/dcat-us/validator`

**Comment by robert-bryson** [comment]
Relative to the sketch, the AC appears to be incorrect. labs.data.gov `404`s as it has been removed from `18f/dns`. I believe the sketch (as currently written), `dashboard.data.gov/validate` is correct. Please confirm, @nickumia-reisys .

**Comment by nickumia-reisys** [comment]
I wasn't aware that we were deprecating the `labs.data.gov` domain.  But if that's the case, I updated the AC to reference `dashboard.data.gov`

**Comment by jbrown-xentity** [comment]
If we utilize the [redirect app](https://github.com/GSA/datagov-website/blob/main/vars.production.yml), we can avoid making any changes to 18f dns at this time. The redirect would occur at the redirect app cloud.gov level. We would need to:

- Add the `dashboard.data.gov` to the redirect app list of subdomains in [this PR](https://github.com/GSA/datagov-website/pull/47)
- Merge https://github.com/GSA/datagov-website/pull/48 with the above PR
- Create draft PR of deprecating the route in dashboard of cloud.gov
- Merge 1
- Merge 2
- Monitor and roll-back if issues

**Comment by robert-bryson** [comment]
As of the merging of https://github.com/GSA/datagov-website/pull/50, this is working: 
![Recording 2023-06-12 at 09 13 20](https://github.com/GSA/data.gov/assets/91547795/b7de7f7f-4b56-4f7f-bff4-291e7e3de87d)

**Comment by robert-bryson** [comment]
Dashboard route removed with https://github.com/GSA/project-open-data-dashboard/pull/418. Closing.

**Comment by robert-bryson** [comment]
Well, I did not notice that this wasn't working 100% correctly, but appears to be now: 
![image](https://github.com/GSA/data.gov/assets/91547795/742b83e5-4709-4c3c-aa1f-e351e885ca29)

Thanks @jbrown-xentity for the second set of eyes on this!
