### ISSUE TITLE
Github Checkout Action Deprecating?

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4005]
## How to reproduce

1. Look here, https://github.com/GSA/catalog.data.gov/actions/runs/3228383267

## Expected behavior

No warnings

## Actual behavior

```yaml

Publish Images on GHCR (postgresql)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, docker/login-action, docker/build-push-action, docker/build-push-action, docker/login-action, actions/checkout
```

![image](https://user-images.githubusercontent.com/85196563/195146790-64e04c8f-488d-4763-ac8d-5ccfa19009f8.png)

![image](https://user-images.githubusercontent.com/85196563/195147209-961d9590-1c38-461d-bf62-403e636e0075.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

Repos to update:
- [x] [catalog.data.gov](https://github.com/GSA/catalog.data.gov/pull/579)
- [x] [ckanext-datagovcatalog](https://github.com/GSA/ckanext-datagovcatalog/pull/37)
- [x] [ckanext-archiver](https://github.com/GSA/ckanext-archiver/pull/7)
- [x] [ckanext-brokerpak-solr](https://github.com/GSA/datagov-brokerpak-solr/pull/66)
- [x] [ckanex-dcat_usmetadata](https://github.com/GSA/ckanext-dcat_usmetadata/pull/298)
- [x] [ckanext-datagovtheme](https://github.com/GSA/ckanext-datagovtheme/pull/145)
- [x] [ckanext-datajson](https://github.com/GSA/ckanext-datajson/pull/128)
- [x] [ckanext-geodatagov](https://github.com/GSA/ckanext-geodatagov/commit/a60c7fb89715dbc2ca45c961bd26c9bd00768c0d)
- [x] [ckanext-googleanalyticsbasic](https://github.com/GSA/ckanext-googleanalyticsbasic/pull/13)
- [x] [ckanext-metrics_dashboard](https://github.com/GSA/ckanext-metrics_dashboard/pull/3)
- [ ] ~ckanext-saml2auth~ (our fork of this repo is no longer used and thus no update is needed, but I did make a [PR upstream](https://github.com/keitaroinc/ckanext-saml2auth/pull/76))
- [x] [ckanext-spatial](https://github.com/GSA/ckanext-spatial/pull/17)
- [x] [ckanext-usmetadata](https://github.com/GSA/ckanext-usmetadata/pull/66)
- [ ] ~[datagov-brokerpak-eks](https://github.com/GSA/datagov-brokerpak-eks/pull/105)~ (not being used actively, there is a weird issue with the terraform that has been blocking)
- [x] [datagov-website](https://github.com/GSA/datagov-website/pull/42)
- [x] [inventory-app](https://github.com/GSA/inventory-app/pull/493)
- [x] [project-open-data-dashboard](https://github.com/GSA/project-open-data-dashboard/pull/404)

**Comment by btylerburton** [comment]
https://github.com/actions/checkout 
https://github.com/actions/download-artifact

are both on V3 now, with Node 16 support

**Comment by robert-bryson** [comment]
Updated on ckanext-geodatagov with [this commit](https://github.com/GSA/ckanext-geodatagov/commit/a60c7fb89715dbc2ca45c961bd26c9bd00768c0d). Note that [`actions/setup-python`](https://github.com/actions/setup-python) is now at `v4`.

**Comment by robert-bryson** [comment]
This ticket is somewhat self-documenting (see [the sketch](https://github.com/GSA/data.gov/issues/4005#issue-1404917195) and [the issue](https://github.com/GSA/data.gov/issues/4005)), but I believe I have gotten to all the repos we use. Anyone else know of any other? Or have a better list to work from? 

If not, will someone on the datagov team please close the the remaining open PRs?

**Comment by robert-bryson** [comment]
Closing, there are two outstanding repos, see sketch for reasoning on not updating them.
