### ISSUE TITLE
Remove broken link beneath catalog search bar

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4006]
After I search for a topic (ex. healthcare) on data.gov catalog, I am presented with a message "You are searching in the list of datasets. Show results in [entire Data.gov site](https://www.data.gov/search-results/?group=site&q=health%20care)." 

Upon clicking this link, I am presented with a data.gov 404 page.

This is rendered from datagovtheme: https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/templates/package/search.html#L87

## How to reproduce

1. Search for any issue
2. Click link beneath search bar
3. See 404

## Expected behavior

I would expect this to present more datasets than originally searched for.

## Actual behavior

Users get a 404 page.

## Sketch

- [ ] Determine reason for the link's presence in datagovtheme, if possible.
- [ ] Remove link if no longer needed

**Comment by nickumia-reisys** [comment]
If you notice, this search is being done by `data.gov` which I would assume was the old wordpress site, so I'm not sure this is a catalog issue.

![image](https://user-images.githubusercontent.com/85196563/195898387-af960901-eb67-4357-a333-e666dd6f5c5d.png)

**Comment by FuhuXia** [comment]
We can remove it from catalog for now, before we re-enable static site search on the www site.

**Comment by Jin-Sun-tts** [comment]
Removed this broken link from the search result page:



![Image](https://user-images.githubusercontent.com/104456257/198128062-d6a08f26-4e40-43f8-855e-2071c8230cb4.png)



> .html

**Comment by nickumia-reisys** [comment]
💇
