### ISSUE TITLE
metrics-dashboard initial working/integrated version

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4016]
## User Story

In order to build dashboard replacement, data.gov admins want basic report extension that can report a page.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN the newly created report extension is setup \
  WHEN I got to `/new-report` \
  THEN some data is displayed

## Background

Related to https://github.com/GSA/data.gov/issues/3982

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

Use https://github.com/GSA/ckanext-metrics-dashboard
Need to have a test framework, a CKAN `make up` framework, needs to integrate ckanext-report, etc

**Comment by hkdctol** [comment]
Interesting example I just ran across: https://data.europa.eu/mqa/?locale=en

**Comment by btylerburton** [comment]
Thanks for sharing @hkdctol! There's some good ideas in there for some self-reported metrics. I need to document that along with some other ideas for enhancements for us to consider in future.

**Comment by btylerburton** [comment]
New wrinkle in the caching/internal-routes discussion:

This resolves: https://catalog.data.gov/report/metrics-dashboard/doi-gov
This doesn't: https://catalog.data.gov/report/metrics-dashboard

No explanation why, either.

**Comment by nickumia-reisys** [comment]
Being the follow on to https://github.com/GSA/data.gov/issues/3982, the same holds true.  Although there may be things to be said about the nuances of getting this work.

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data.gov/issues/3502
