### ISSUE TITLE
metrics-dashboard initial data report

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4017]
## User Story

In order to deprecate dashboard, data.gov admins want an OMB necessary data report for the catalog.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN OMB needs the [following information reported](https://docs.google.com/document/d/1_q9qHwzSrd2_TzbTJkWqlvcibD6tWyoK3wYNHfy2Fx0/edit#heading=h.81d43aps8pug) \
  WHEN I get a report of a CKAN catalog \
  THEN I can see the requested information

## Background

See https://github.com/GSA/data.gov/issues/3982 and https://github.com/GSA/data.gov/issues/4016

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

Use the following as focuses for the data we want to extract, and consider using CKAN or ckanext-harvest API's to get the data where possible:
- Summary by organization
- Recent harvest dates
- Most recent data modified dates (not CKAN modified date, the data modified date)
- Number of datasets
- Number of resources
- Number of items that are failing to harvest

**Comment by btylerburton** [comment]
Done in https://github.com/GSA/data.gov/issues/4016

**Comment by nickumia-reisys** [comment]
Being the follow on to https://github.com/GSA/data.gov/issues/3982, the same holds true.

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data.gov/issues/3502
