### ISSUE TITLE
metrics-dashboard cached results

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4018]
## User Story

In order to deprecate dashboard, data.gov admins want cached metrics-dashboard such that it can handle the catalog load.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN the caching job has been run \
  WHEN I go to https://catalog.data.gov/report \
  THEN the metrics-dashboard report is viewable/usable

## Background

Related to https://github.com/GSA/data.gov/issues/4017, https://github.com/GSA/data.gov/issues/4016, and https://github.com/GSA/data.gov/issues/3982

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

Need to look at [generating a report](https://github.com/ckan/ckanext-report#command-line-interface), and debugging any scaling issues on staging for amount of data and any optimizations, scheduling, etc that needs to occur.

**Comment by btylerburton** [comment]
Given the report is only cached at the instance level, we resolved that we will look at caching this in Cloudfront.

cc @nickumia-reisys and @FuhuXia

**Comment by btylerburton** [comment]
Cloudfront caching behavior for `/report/*` has been updated in dev & staging.

Min: 302400
Max: 1209600
Default: 604800

**Comment by btylerburton** [comment]
Set cache in prod to a single day for all values to start. We can tune as needed.

**Comment by btylerburton** [comment]
We are still not caching prior to a user requesting the page in each edge region. The ticket below will dig into implementing a holistic caching solution for all reports: 

https://github.com/GSA/data.gov/issues/4116

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data.gov/issues/3502
