### ISSUE TITLE
Develop a process to sync catalog DB from prod to staging

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4024]
We need, once in a while, to sync Catalog production database to staging. We need to have the steps in details on 
- Production DB dump to S3
- Staging DB restore from S3
- Sanitize the Staging DB
  - Set all harvest source to the Manual schedule, 
  - Remove all user API keys and API Tokens
  - Change all user emails to `localdomain` so that no accidental emails go out

**Comment by jbrown-xentity** [comment]
This should satisfy our db backup and restore process that should be performed annually.

**Comment by nickumia-reisys** [comment]
Important historical DB commands: 
- https://github.com/GSA/data.gov/issues/3813#issuecomment-1118893986

**Comment by Jin-Sun-tts** [comment]
Added two scripts to backup and restore DB from production:
https://github.com/GSA/cf-backup-manager/tree/main/docs/backup_restore

Staging restored the production DB from date 2022-12-13.
