### ISSUE TITLE
Solr replica core is locked after restart

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4026]
We have developed some [stragtegy](https://github.com/GSA/catalog.data.gov/pull/518/files) to deal with Solr core locking after FCS task restart. We even added some logic to deal with some rare occasions that Solr index folder may get renamed. But we noticed twice Solr still gets itself locked after a restart.

## How to reproduce

Cant replicate. It happened twice so far.
https://github.com/GSA/data.gov/issues/4008#issuecomment-1287024762

## Sketch

- Add more checks and fixes into [solr_setup.py](https://github.com/GSA/catalog.data.gov/blob/main/solr/solr_setup.sh). The goal is to ensure Solr is in a good state after a restart.
- Get notified if any of of the Solr instances is locked.

**Comment by FuhuXia** [comment]
Developed a New Relic alert policy ["Solr Core Lock"](https://one.newrelic.com/nrai/alerts-classic/policies). If we defect Solr core lock message in catalog apps, we will get notified in Slack and email.

**Comment by FuhuXia** [comment]
So far it happened three times in the past 30 days. 
1. Follower 0 index folder changed to `index.20221007160458545`
https://github.com/GSA/data.gov/issues/3983#issuecomment-1272110406
2. Follower 1 index folder changed twice in a short time and became `index.20221020222750768`
https://github.com/GSA/data.gov/issues/4008#issuecomment-1287024762
3. Follower 1 index folder changed a few times, back to be `index`. 
https://github.com/GSA/data.gov/issues/4039#issuecomment-1300748852

**Comment by FuhuXia** [comment]
We noticed that right before the issue happens, there are multiple index folders in `/var/solr/data/ckan/data/`, the current one and newly added one. Based on this finding, an easy fix can be adding a timed shutdown command upon detecting multiple index folder, let the Solr do its thing to settle down on one index folder, core locking expected at this point, then the task gets shutdown after a minute or two. ECS will launch a new task, new task will be core unlocked by our existing script. When new task is up and running, the Solr service is recovered.

**Comment by nickumia-reisys** [comment]
This continues to be an issue, but is superseded by,
- https://github.com/GSA/data.gov/issues/4138
