### ISSUE TITLE
catalog styles aren't loaded

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4027]
Go to any dataset page, and open the web console. See 404 on 6 font files.

## How to reproduce

1. Go to https://catalog.data.gov/dataset/ek500-water-column-sonar-data-collected-during-al0001
2. Open web dev tools
3. Check network/console

## Expected behavior

No 404 errors

## Actual behavior

404 errors

## Sketch

We must be bundling datagovtheme wrong, or the css is referencing the wrong routes...

**Comment by nickumia-reisys** [comment]
### Before Picture:
![image](https://user-images.githubusercontent.com/85196563/197790194-54298c4a-aa42-49d7-9bc1-223957d61b2b.png)

![image](https://user-images.githubusercontent.com/85196563/197790485-bb5d4482-5179-4fff-a9ac-67d104f80631.png)

**Comment by nickumia-reisys** [comment]
### After Picture:
![image](https://user-images.githubusercontent.com/85196563/197808101-4ae621a1-f3c7-41d0-a815-08dec4b8d3c7.png)
