### ISSUE TITLE
Sitemap Update response in Github Action

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#4028]
## User Story

In order to [ensure that CF tasks that get triggered by a github action complete successfully], [datagov team] wants [the actions to monitor their tasks for success/failure].

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [an action that triggers a cf task] \
  WHEN [the task actually completes] happens \
  THEN [that status is reflected in the action status]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

At the moment, we had a number of actions that trigger `cf run-task`. These actions trigger their task, then quickly report success in terms of the task being triggered, but do not monitor to see if their task actually succeeds on the `cf` side. Monitoring is often done by `grep`ing the logs of the task, or in New Relic. We would have better visibility in this if the status (and perhaps logs) were reported in the github action UI. 

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

There would be a number of ways to achieve this, but one approach could be something like:

- Make each task name unique
- Query `cf` for that unique task name
- Log logs
- Exit with code

One thing that maybe be helpful is querying via the `cf curl` api: 
```
cf curl "/v3/apps/$(cf app APPNAME --guid)/tasks?names=TASKNAME" | jq . 
```

**Comment by nickumia-reisys** [comment]
A similar but different mechanism exists for the `db-solr-sync` task.  The logs of the task are output to Github and if the app exits successfully on CF, Github reports success, otherwise it reports failure.
- https://github.com/GSA/catalog.data.gov/blob/main/tools/monitor_cf_logs.sh
- https://github.com/GSA/catalog.data.gov/blob/main/.github/workflows/db-solr-sync-automated.yml#L38-L47

**Comment by jbrown-xentity** [comment]
Link of monitor_cf_logs usage is dead, see https://github.com/GSA/catalog.data.gov/blob/main/.github/workflows/ckan_auto.yml#L128-L137

**Comment by nickumia-reisys** [comment]
As an initial pass, we can try to borrow the current logic we have.  If it doesn't work the way we want it to, we can explore the monitoring logic seen in sketch above.

**Comment by nickumia-reisys** [comment]
Will monitor sitemap action tomorrow and see if it is working.

**Comment by nickumia-reisys** [comment]
This is complete as evident by 
- https://github.com/GSA/catalog.data.gov/issues/882
