### ISSUE TITLE
Propose design options for data.gov site

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4029]
## User Story

In order to make design choices on next steps on new Data.gov static site, Data.gov team needs to develop some options for review.

## Acceptance Criteria

- [ ] GIVEN our "draft" new site for Data.gov main page \
 THEN Data.gov team has some choices/mood boards for next steps for full mockup.

## Background

Data.gov migrated from Wordpress to Federalist, and has a new version of the site using 11ty. See #3891 

## Sketch
- [ ] Review work done to date at #3891 
- [ ] Review the current [version](https://federalist-2ac784db-2321-4734-8d02-933835d88304.app.cloud.gov/site/gsa/datagov-11ty/)
- [ ] Review current [catalog](https://catalog.data.gov/dataset) for required consistency
- [ ] Present options/mood board on choices on colors, font, images, icons, etc.

**Comment by CarolinaC-REI** [comment]
Created two mood board options https://305v2q.axshare.com.

**Comment by CarolinaC-REI** [comment]
Created wireframes options https://305v2q.axshare.com

**Comment by nickumia-reisys** [comment]
I feel like this document should be linked here: https://docs.google.com/document/d/1EWN0n8qdO0UhcXeeZd9tcf6_OjoiZUl-A95LNAJcuQk/edit#

**Comment by CarolinaC-REI** [comment]
Please find the image assets for the homepage design.

[dataGov-homepage-assets.zip](https://github.com/GSA/data.gov/files/10572907/dataGov-homepage-assets.zip)

I will adding a pdf file for the style guide as soon as that is completed.

Please let me know if you have any questions.

**Comment by nickumia-reisys** [comment]
I think this ticket can be closed, right?  Being built on with
- https://github.com/GSA/data.gov/issues/4181
- https://github.com/GSA/data.gov/issues/4202
- https://github.com/GSA/data.gov/issues/4204
- https://github.com/GSA/data.gov/issues/4205
- https://github.com/GSA/data.gov/issues/4210
- https://github.com/GSA/data.gov/issues/4213
- https://github.com/GSA/data.gov/issues/4141

**Comment by nickumia-reisys** [comment]
Followed on by
- https://github.com/GSA/data.gov/issues/4141
