### ISSUE TITLE
Port over Open Gov page to new 11ty site

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4032]
## User Story

As a data.gov user, I want to see a picture of open government initiatives across the world.

## Acceptance Criteria

- [ ] https://data.gov/open-gov/ page is ported to new static site

**Comment by hkdctol** [comment]
As an initial task, @crysacarter currently updating the CSV of open data sites

**Comment by jbrown-xentity** [comment]
Just FYI, there are 3 versions of this data. One is a spreadsheet style (csv and xls), the other is geojson that powers the map. If we're rebuilding this page, I don't think we need 3, csv is fine (we don't need xls), but we might need to re-generate the geojson from the new clean csv if we want the map.
- [geojson's](https://github.com/GSA/datagov-website/tree/main/www.data.gov/app/themes/roots-nextdatagov/assets/LeafletMap2/data)
- [csv](https://github.com/GSA/datagov-website/blob/main/www.data.gov/datagov/wordpress/2019/09/opendatasites91819.csv)
- [xls](https://github.com/GSA/datagov-website/blob/main/www.data.gov/datagov/wordpress/2019/09/opendatasites91819.xls)

**Comment by crysacarter** [comment]
[opendatasites11322.csv](https://github.com/GSA/data.gov/files/9931785/opendatasites11322.csv)

updated csv

**Comment by crysacarter** [comment]
[opendatasites112122.csv](https://github.com/GSA/data.gov/files/10058482/opendatasites112122.csv)

I found  and corrected an error in the first upload.

**Comment by hkdctol** [comment]
I think the text can be transferred to new site as is, except that in third paragraph, first sentence, I would delete "new" since the law isn't so new at this point.

**Comment by nickumia-reisys** [comment]
@hkdctol Do we want a table of the open data sites?  I uploaded the file @crysacarter posted to S3 and then put a link to it at the bottom.

### Old Way
![image](https://user-images.githubusercontent.com/85196563/205378593-e44709e8-2195-4018-a400-351577b42667.png)

### Newly Proposed way -- (Interim way until we decide if we want to do the map)
![image](https://user-images.githubusercontent.com/85196563/205378677-ee64216f-5a8b-4243-9f0d-938bd78e97c2.png)

**Comment by nickumia-reisys** [comment]
The full preview is: https://federalist-2ac784db-2321-4734-8d02-933835d88304.app.cloud.gov/preview/gsa/datagov-11ty/add-open-gov-page/open-gov/

**Comment by hkdctol** [comment]
that seems fine to me as interim solution
