### ISSUE TITLE
Fix relative pathing of 11ty Static Site

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4033]
We should be able to supply a `process.env.BASEURL` to the build that will allow relative links to function correctly. This will remove the 404's from the Federalist build.

## How to reproduce

1. Navigate to the Federalist build https://federalist-2ac784db-2321-4734-8d02-933835d88304.app.cloud.gov/site/gsa/datagov-11ty/
2. Attempt to click on any relative link: 
2.1. https://federalist-2ac784db-2321-4734-8d02-933835d88304.app.cloud.gov/maritime/hydrosurvey-data-archive-for-federal-navigation-projects/ >> gives a 404
2.2. https://federalist-2ac784db-2321-4734-8d02-933835d88304.app.cloud.gov/site/gsa/datagov-11ty/maritime/hydrosurvey-data-archive-for-federal-navigation-projects/ >> resolves correctly because it lacks `site/gsa/datagov-11ty/`

## Expected behavior

I expect relative URLs to resolve.

## Actual behavior

Relative URLs give a 404 due to incorrect pathing.

## Sketch

- This will be fixed either by supplying the environment variable, or using a prefix to each permalink.

**Comment by btylerburton** [comment]
One recommendation was to find/replace `{{ site.baseurl }}` with `{{ "path" | url }}`, but that has not been tested.

**Comment by btylerburton** [comment]
11ty documentation

https://www.11ty.dev/docs/config/#deploy-to-a-subdirectory-with-a-path-prefix

**Comment by nickumia-reisys** [comment]
The preliminary results from testing reveals:
- Federalist is setting the `BASEURL` environment variable somewhere and it is the correct path
- `.eleventy.js` is pulling in `BASEURL` properly
- I got `updates/index.html` to have the right redirect ... but nothing else is working so far 😕

**Comment by nickumia-reisys** [comment]
This is mostly done.  It just needs a few more eyes and tests to see what's broken if anything.

**Comment by nickumia-reisys** [comment]
Fixed a few more bugs... The situations handled:
- Homepage to other root pages
- Homepage to topics
- Topics to posts
- Posts to topics
- Posts to Homepage
