### ISSUE TITLE
[Spike] Python UI test

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4034]
## Purpose

We want to write UI tests for ckanext-datagovtheme, but we're not sure how to do that.

Given above unknown, conducting researching and first attempt at building a test suite using [playwright](https://playwright.dev/python/docs/test-runners) is needed to provide factual knowledge on future steps.

8 hours of effort has been allocated and once compete, findings will be demonstrated and we will decide whether to pursue writing these types of tests in Python or in the current Cypress model (see catalog e2e tests for example).

### Acceptance Criteria

[ACs should be clearly demo-able/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN playwright is usable and installable \
  WHEN 8 hours expires\
  THEN a draft PR is created with working/usable examples \
  AND a recommendation is made on the value of this tool \
  AND a team vote is taken on the direction we should go

### Background

https://playwright.dev/python/docs/test-runners
Related to https://github.com/GSA/data.gov/issues/3521

### Sketch

Just read and code quickly, we can worry about quality/cleanliness after we know more!
Test something on the main page, facets, clicking, searching, etc.

**Comment by Jin-Sun-tts** [comment]
Installed and tested locally, by running the playwright codegen <url>, it records pytest code when clicking through the page. 

We may modify the test codes in datagovtheme to use playwright, but while add playwright in the dev-requirements.txt file, found out Alpine does not support playwright, it only officially compatible with Ubuntu 18.04/20.04 so far. 

If we decide to use playwright, we may need find alternate way either use separate docker image for pytest or switch to Ubuntu.

**Comment by nickumia-reisys** [comment]
Due to integration issues, we chose to implement cypress tests over playwright tests.
- https://github.com/GSA/data.gov/issues/3521
- https://github.com/GSA/ckanext-datagovtheme/pull/149
