### ISSUE TITLE
Egress-proxy inhibits datajson harvester

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4053]
## How to reproduce

1. Try to harvest data.json source

## Expected behavior

Connect to source and harvest data successfully.

## Actual behavior

Connection refused.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]
Possible solutions:
- [x] Disable egress-proxy
- [x] Convert datajson harvesters from `urllib` to `requests`

Notes:
- Caddy 2 no longer supports mime type sniffing
  - https://github.com/GSA/cg-egress-proxy/pull/11
  - https://github.com/GSA/cg-egress-proxy/pull/12

**Comment by nickumia-reisys** [comment]
The fix for this has been deployed. The egress-proxy is currently being re-deployed.  Will evaluate whether this problem still exists the next time harvesting is run.

**Comment by FuhuXia** [comment]
Issue is resolved. Egress-proxy enabled, `urllib` replaced with `requests`. Sites are functioning.
