### ISSUE TITLE
Egress-proxy causes app staging failure

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4055]
## How to reproduce

1. Enable the egress proxy
2. Try to deploy an app

## Expected behavior

App starts successfully

## Actual behavior

Error downloading python buildpack
```bash
   **ERROR** Could not install python: Get "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.8.13_linux_x64_cflinuxfs3_2918e5cd.tgz": malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x10\x00\x00"
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
```

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

Notes:
- This is related to https://github.com/GSA/data.gov/issues/3755

**Comment by mogul** [comment]
See comment here:
https://github.com/GSA/data.gov/issues/3755#issuecomment-1310598529
