### ISSUE TITLE
Set up a task to find stuck harvest jobs

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4058]
When a harvest job got stuck, we set to let it force-finished [after 24 hours](https://github.com/GSA/catalog.data.gov/blob/main/ckan/setup/ckan.ini#L233-L234). We should give it a longer time span, say, 36 hours. This will give us time to troubleshoot the error instead of letting it go unnoticed.

We can set a nightly GitHub action to find the stuck harvest jobs.

## How to reproduce

1. Description of steps to reproduce the issue.

## Sketch
- [x] change ckan.harvest.timeout to use 72 hours
- [ ] set up GH a nightly action to use `ckan harvester` command to find stuck jobs, or
- [x] add a `ckan geodatagov` command to use SQL query to find the stuck jobs.

**Comment by hkdctol** [comment]
Let's find out how often this is occurring and then prioritize

**Comment by FuhuXia** [comment]
For the past month, we have 38 harvest jobs got force finished for 9 different harvest sources. 
```
SELECT source_id, count(*) FROM harvest_job
WHERE created > '2022-10-01' AND finished-created > '23:55:55'
GROUP BY source_id
ORDER BY 2 DESC;

              source_id               | count
--------------------------------------+-------
 651e43b2-321c-4e4c-b86a-835cfc342cb0 |    11
 3598ae88-5b46-4ca2-bc1b-821f195ad725 |    10
 0aeddf52-9cb0-4ab6-bc1f-b53172fe5348 |     7
 bee011ae-6f4a-4b9b-bef9-6c8b6453c562 |     3
 74e175d9-66b3-4323-ac98-e2a90eeb93c0 |     3
 8812445c-2f10-47c5-80d9-c1bc92ca956d |     1
 0eb61eac-016f-4f95-a6c3-2974339749bb |     1
 803bdba9-bfcb-453c-ae2a-ed81f240ff5a |     1
 7c55db6f-78c3-4120-a882-c4b8b0b43026 |     1
(9 rows)
```

**Comment by FuhuXia** [comment]
Ideally we should fix all stuck issues so that we don't have to force-finish any jobs. Even if we have to, it seems important to make sure all fetch processes are healthy and idling before force-finish it. Things can get weird for pending fetch items when the job is gone. Setting it 36 hours gives us enough time to debug and prepare the force finish. 

To check whether you have pending Fetch items, run `ckan harvester run` command. The log should NOT have the following entry:
``` 
[#] Ongoing jobs for [job-id] (source:[source-id])
```
This log entry could be persistent if fetch instances are running in a crash loop. The retry logic in harvesting further complicate things, so the `ckan harvester run` might need to run a few times to clear the pending fetch items.

**Comment by Jin-Sun-tts** [comment]
Changed ckan.harvest.timeout to use 72 hours.
Created new command in geodatagov to find the harvest stuck jobs.
Added manual and automated GH workflow to run the check-stuck-jobs and open issue when find stuck jobs. 
Turned on the harvest run on staging.
