### ISSUE TITLE
data.gov feature list

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4060]
## Purpose

We want to have a complete feature list of data.gov (categorized via MuSCoW: Must, Should, Could, Would), but we're not sure how to do that.

Given above has grown over the last decade, conducting research, code review, and documentation is needed to provide factual knowledge on future steps.

2 days of effort has been allocated and once compete, findings will be demonstrated and specific future actions will be decided.

### Acceptance Criteria

[ACs should be clearly demo-able/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN an audit is complete \
  WHEN 2 days of effort expires\
  THEN a detailed spreadsheet is given \
  AND a discussion is had on future data.gov tickets/epics

### Background

Came out of discussion from [harvesting discussion](https://docs.google.com/document/d/106qzAxebIy1hXn59HQOaQ6ovpM1ynk3FSTswxSaLCTY/edit#)

### Sketch

The spreadsheet should contain Feature, why (if available/applicable), complexity (t-shirt size), category (UI, harvesting, SEO, search, etc), sub-category

**Comment by jbrown-xentity** [comment]
[Feature List on data.gov drive](https://docs.google.com/spreadsheets/d/1nMkbX5MKBV14G7SyNbjrXLqIZtLW2SqS6uEZ-2kQrAo/edit#gid=0)

**Comment by jbrown-xentity** [comment]
I left some more comments, notes, and items around the [Open Data Act](https://www.congress.gov/bill/115th-congress/house-bill/1770/text) on the [Feature List](https://docs.google.com/spreadsheets/d/1nMkbX5MKBV14G7SyNbjrXLqIZtLW2SqS6uEZ-2kQrAo/edit#gid=1715179699). We should review this during a pairing session to answer questions and finalize on this for planning future epics.

**Comment by jbrown-xentity** [comment]
After review with @nickumia-reisys and his work on #4089 , we have merged this where each feature is listed with it's corresponding law/memorandum requirements. See the [Feature List on data.gov drive](https://docs.google.com/spreadsheets/d/1nMkbX5MKBV14G7SyNbjrXLqIZtLW2SqS6uEZ-2kQrAo/edit#gid=0) for latest information. This can be considered done, with review occurring with team during sprint review after discussions.

**Comment by nickumia-reisys** [comment]
This is a beautiful ticket 🥲

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data.gov/issues/4354
