### ISSUE TITLE
some CKAN functions are broken in datagovtheme 

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#4066]
## How to reproduce

start CKAN in datagovtheme repo, try to login as admin to create new organization and dataset.

## Expected behavior

it should be able to add new org/dataset as the admin user. 

## Actual behavior

1. could not use admin user to login, need manually add it from bash console.
2. could not add new organization, got errors.  

## Sketch

start ckan from datagovtheme, test functions to create new org/dataset as admin user.

**Comment by nickumia-reisys** [comment]
There were two things broken:
- Storage write-permissions
- Sysadmin initialization.

Both fixed in the above PR.
