### ISSUE TITLE
Staging Basic Auth not working with CloudFront

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4067]
Staging environment is password protected by basic auth, but something is preventing the password dialog box from disappearing even when inputting the correct credentials.

## How to reproduce

1. Visit staging URL
2. Input proper username/password into authentication box
3. Dialog box disappears momentarily, but then returns

## Expected behavior

- Dialog box should disappear after user enters correct credentials

## Actual behavior

- Dialog box reappears after user enters correct credentials

## Sketch

- explore if this is related to Cloudfront and the passing of Authorization headers

**Comment by btylerburton** [comment]
Authorization was not being passed for `/api/*` behavior. Once that was added, the issue was fixed.

**Comment by nickumia-reisys** [comment]
🎤 🍂 (read: mic fall leave --> mic drop)
