### ISSUE TITLE
CDC data duplicated on U.S. Department of Health & Human Services

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4073]
[Total list of site-wide duplicates](https://catalog.data.gov/api/action/package_search?facet.field=[%22identifier%22]&facet.limit=-1&facet.mincount=2&rows=0). 804 records, all but 10 are CDC records.
CDC has their own organization: https://catalog.data.gov/organization/centers-for-disease-control-and-prevention
However, it looks like all the CDC data is replicated in US Department of Health: https://catalog.data.gov/organization/hhs-gov
In fact, it looks like US Department of Health has more records: https://catalog.data.gov/dataset/?q=%22https%3A%2F%2Fdata.cdc.gov%2Fapi%2Fviews%2F%22&sort=views_recent+desc&ext_location=&ext_bbox=&ext_prev_extent=-150.46875%2C-80.17871349622823%2C151.875%2C80.17871349622823

## Expected behavior

Department harvest sources are cleaned such that they don't provide duplicates

## Actual behavior

Multiple harvest sources (one from agency, one from department) causing duplicates.

## Sketch

Validate with CDC that Department of Health is getting their updated data, and remove CDC harvest source.
https://catalog.data.gov/harvest/https-data-cdc-gov-data-json
Both the harvest sources are being harvested daily...

**Comment by hkdctol** [comment]
Reaching out to HHS to track down some current contacts to work on this.

**Comment by hkdctol** [comment]
Pinged HHS again; moving to blocked for now

**Comment by hkdctol** [comment]
Still blocked but HHS confirms they are investigating the issue

**Comment by hkdctol** [comment]
Pinging HHS again--to confirm that we can delete CDC because HHS data.json covers it

**Comment by hkdctol** [comment]
HHS confirms that CDC harvest source and organization can be deleted, but there's a harvest job right now so will delete next week.

**Comment by hkdctol** [comment]
I tried to clear CDC data.json as a harvest source, but got an error:

![Image](https://user-images.githubusercontent.com/3236989/209704182-8a6ff77e-e3ca-481d-92a8-5044a21b6c02.png)

**Comment by FuhuXia** [comment]
The error is from web server timeout. The clearing process has finished regardless. I see CDC has 0 datasets. 
https://catalog.data.gov/organization/centers-for-disease-control-and-prevention

**Comment by FuhuXia** [comment]
CDC harvest source is cleared and deleted.

**Comment by hkdctol** [comment]
Organization deleted.
