### ISSUE TITLE
Dataset harvest object not in Solr

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4079]
Some datasets' harvest objects are not indexed in Solr. It is fine in the DB and on the UI. 

## How to reproduce
As of today there are 6 datasets
https://catalog.data.gov/api/action/package_search?fq=-(harvest_object_id:*)

## Expected behavior

These 6 datasets has harvest objects in DB, it shows on the UI. Should also show in the Solr.

## Actual behavior

no `harvest_object_id` on the API call.

## Sketch

- Spot check id's for recent item changes (sort API by modified date), and see if anything jumps out. Feel free to consider faceting and looking at common factors such as organization, harvest_source_title, etc.
- Our [ckan geodatagov db-solr-sync](https://github.com/GSA/catalog.data.gov/actions/runs/4535767238/jobs/7991618184#logs) automated job should be fixing these automatically, finding objects in the DB and in solr that are out of sync. Research code and/or recent runs to discover what may have gone wrong with these.
- Research DB and state of these items (specifically the link between the `package` table and `harvest_object` table, harvest_object should have a `package_id` for every item. This may involve the need to either open up ssh access on prod for a short time, or to copy prod to staging. See [harvester code](https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/model/__init__.py#L341-L374) for data model, and how things link together.

**Comment by Jin-Sun-tts** [comment]
as of today, dataset without harvest_object_id increased from 6 to 24 now:

`https://catalog.data.gov/api/action/package_search?fq=((*:*)%20AND%20-(harvest_object_id:*))&fl=id&rows=1000`

```
"51415b91-b81b-4596-b625-65b5b1a3de1e"

"281f4c8f-729a-4b5b-927a-90604b950db7"

"deb45554-2e74-46ef-8320-ae9f77f2111d"

"597704ca-4cc7-4e29-9ed2-edc6dcf5fd54"

"86744a88-c00f-448d-9a11-e26273a2dc4c"

"4a66c9ae-a44d-4b68-9b1d-9f9f33515333"

"19ffdd41-6f0b-435f-9e7b-28952bc35bcc"

"37c460b3-2929-4b9c-9437-68240ce49ffd"

"2037d890-6d7c-4862-b962-54cbece85ac1"

"ffcf658e-4593-43fd-96e8-446dce81d187"

"25a9c1ec-5e05-4077-b9db-6ac65d7244cf"

"6bde7efe-6fb5-4881-bf38-83d344ca7995"

"f9e012eb-e8d3-47b5-808e-b14acb50fb96"

"38c948cf-dfc3-43da-ab3e-7445e044fcf2"

"f2cf2c7b-95d4-40ed-a599-70d3185b66a0"

"2850353e-26a2-463e-89d0-e1e38a50d047"

"a83a9480-0254-4fc5-bdf5-ef9672949e1b"

"d71fa6b1-d473-4e4f-94fa-19434809e6d1"

"9181081c-d951-4816-a91b-cc8b395f82fc"

"3b7587ac-d83d-44a3-a370-edbe6d6cd72b"

"d7ba9d63-6578-4c23-a4eb-497f7101fc5f"

"5ba40271-9fc2-448d-9aa9-297b70e762dc"

"a9082f4b-6700-4648-9fef-8fdd2d4bfe2d"

"acecfc1e-4c0a-4dc1-af1e-f78e21bc3551"
```

**Comment by jbrown-xentity** [comment]
Got an email referencing this issue from Census. Specific use case: https://catalog.data.gov/dataset/tiger-line-shapefile-2020-county-marin-county-ca-topological-faces-polygons-with-all-geocodes. Shows up in the api detailed above.

**Comment by nickumia-reisys** [comment]
Today's count is `34`

**Comment by robert-bryson** [comment]
Hmm... 

![Image](https://user-images.githubusercontent.com/91547795/228010050-0928a3df-af6a-4004-8af2-82ba348bb583.png)

**Comment by jbrown-xentity** [comment]
Related to https://github.com/GSA/data.gov/issues/4177

**Comment by robert-bryson** [comment]
Well, if nothing else this has been holding steady at 152. Trying to narrow down what might have happened over the weekend and also why `db-solr-sync` isn't. 

Edit: 155 on the morning of the 31st.

**Comment by robert-bryson** [comment]
Overall, the issue seems to lie in spatial harvest sources not being handed off correctly between the harvest and spatial extensions. Most spatial sources are obviously not experiencing this issue so I am still narrowing down the cases in which this happens. Since I haven't worked with this aspect of ckan at all yet this ticket has been a slow process of reading ckan docs that say that is actually a harvester thing, then reading harvester docs that say that is actually a spatail harvest thing, then reading ...etc. 

In any case, the count is holding steady so I haven't had any new job logs to compare to, for better or worse.

**Comment by robert-bryson** [comment]
As I'm focusing on O&M for the week, I'll put this back into the queue in case anyone is feeling luckier than I am. Will take back up next week once I'm done O&M if it remains in queue.

**Comment by FuhuXia** [comment]
~Those packages should be leftover duplicate packages that original one has been removed by harvesting jobs. We need to run this step again https://github.com/GSA/data.gov/issues/4007 to clear them.~

There are 240 returned from the API, most of them, if not all, are due to the error in the harvest_object table as described Error 1 in https://github.com/GSA/data.gov/issues/3403. If we run the [relink](https://github.com/GSA/data.gov/pull/3470) process, either via GH cron and manually run once, the count will be reduced to single digit.

**Comment by FuhuXia** [comment]
Running `harvest-object-relink` cf task on catalog. The [number ](https://catalog.data.gov/api/action/package_search?fq=-(harvest_object_id:*)&rows=0) is decreasing.

**Comment by FuhuXia** [comment]
2k datasets fixed by the newly deployed cf command `harvest-object-relink`, which reduces the count of 240 from the api call to 60. The remaining 60 are datasets with no valid harvest object. They are now manually deleted via cli command. As of now, the [api](https://catalog.data.gov/api/action/package_search?fq=-(harvest_object_id:*)) returns 0.

We can check back in a few weeks to see the API result again. 

Just for the reference, the 2k datasets were mostly from this NOAA harvest source [NOAA/NESDIS/ncei/accessions](https://catalog.data.gov/harvest/about/noaa-nesdis-ncei-accessions). We know it is a large XML WAF source with all file timestamp updated daily which causes unnecessary loads on harvesters.

**Comment by FuhuXia** [comment]
Today API shows **5212** erroneous datasets found.  So it is a recurring issue. 
```
count: 5212,
facets: {
  organization: {
    noaa-gov: 5210,
    census-gov: 1,
    epa-gov: 1
  }
},
```
Running cf command `ckan geodatagov harvest-object-relink`, fixing **9116** datasets now.
