### ISSUE TITLE
gather fails on datajson record without an identifier

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4080]
If there is one record in a datajson file that has no `identifier`, the gather process fail. None of the datasets will be harvested. 

## How to reproduce

It happens to doc harvest source. 

## Expected behavior

report the error and move on to harvest the other datasets

## Actual behavior

gather fails. none dataset is harvested.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by Jin-Sun-tts** [comment]
This issue is resolved at [#3658](https://github.com/GSA/data.gov/issues/3658)
