### ISSUE TITLE
robots.txt on catalog development

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4083]
robots.txt on catalog development space is allowing search access. 

## How to reproduce

Access catalog /robots.txt

## Expected behavior

Different from prod robots.txt. It should disallow search all engine.

## Actual behavior

Same setting as prod.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
Checked the development URL on google, we have two pages indexed.

**Comment by nickumia-reisys** [comment]
We wanted to prevent google from indexed our development version of catalog, so we set the following at https://catalog-dev-admin-datagov.app.cloud.gov/robots.txt,
```bash
User-agent: *
Disallow: /
```

Google should not have any results from the development url, https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fcatalog-dev-admin-datagov.app.cloud.gov
![image](https://user-images.githubusercontent.com/85196563/216461131-45aba19e-b9f7-4b8f-9908-0d2b3e39d85c.png)


At any time, if the above verifications don't work, this issue should be re-opened.  But for now, aal iz well 😄
