### ISSUE TITLE
Add individual non-government domains to the egress allow list

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4086]
With [egress enabled](https://github.com/GSA/data.gov/issues/3755) on catalog, harvest sources with URL doamin other than `.gov` and `.mil` are blocked. We need to add some trusted `.org` and `.com` URLs to the allow list.  

## List to add
This query is used to get the list, excluding those sources on MANUAL schedule or non-HTTPS url. 
```
SELECT url
FROM harvest_source
WHERE url NOT LIKE '%.gov%'
AND url NOT LIKE '%.mil%'
AND url LIKE 'https%'
AND frequency !='MANUAL';
```
Here are the domains to add to egress allow list.
```
*.opendata.arcgis.com
services3.arcgis.com
data.srcity.org
portal.opentopography.org
data.arlingtonva.us
nycopendata.socrata.com
data.cityofchicago.org
data.sfgov.org
data.townofcary.org
data.lacity.org
data.muni.org
dataworks.siouxfalls.org
www.chapelhillopendata.org
openei.org
```

**Comment by nickumia-reisys** [comment]
Apps to update:
- [x] catalog-web
  - [x] development
  - [x] staging
  - [x] prod
- [x] catalog-admin
  - [x] development
  - [x] staging
  - [x] prod
- [x] catalog-fetch
  - [x] development
  - [x] staging
  - [x] prod
- [x] catalog-gather
  - [x] development
  - [x] staging
  - [x] prod
- [x] ~catalog-proxy~
  - [ ] ~development~
  - [ ] ~staging~
  - [ ] ~prod~

**Comment by nickumia-reisys** [comment]
We made this a bit more secure by removing unnecessary domains:
- `raw.githubusercontent.com`
- `*.cloudfoundry.org`
- `*.github.com`
