### ISSUE TITLE
Identify desired changes to metadata schema DCAT US 1.1

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4092]
## User Story

In order to incorporate useful changes to DCAT US 1.1, the Data.gov team needs to create a list of changes for the upcoming update.

## Acceptance Criteria

- [ ] GIVEN an anticipated minimal update to DCAT US 1.1 \
  THEN Data.gov team wants to identify a list of updates that would improve functioning of the catalog.

## Background
We anticipate a small update to DCAT US 1.1 largely driven by OMB compliance issues and we want to identify changes that would be beneficial based on our experience.

## Sketch

- [x] Review the [worksheet](https://docs.google.com/spreadsheets/d/16synVUcVAM-f19Euev2VcSYhR7UAsh1g/edit?usp=sharing&ouid=113511966954817069922&rtpof=true&sd=true) that has potential changes
- [x] Review the current DCAT 1.1 and note the changes that we would recommend from Data.gov team experience
- [ ] Work with OMB or other relevant group on whatever process of incorporating our changes to the official update

**Comment by jbrown-xentity** [comment]
As a start:
- Remove bureau code (or have OMB commit to a maintenance plan on keeping an up-to-date list)
- Remove program code (or have OMB commit to a maintenance plan on keeping an up-to-date list)
- Improve the `relation` field, such that it isn't limited to a single URL but can incorporate the type of relationship... See DCAT 3 documentation [here](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_relation), and ESRI notes from a year or 2 ago [here](https://docs.google.com/document/d/1ue2_HI68Lx88rjG816ys2w-05yMxO3jAgVclsdjIRlE/edit#)

**Comment by hkdctol** [comment]
Started a [doc](https://docs.google.com/document/d/1em-ejsy3DV05mbEW3jmsZJBxrYT1RkwJkC1KNkCfv58/edit?usp=sharing) to collect comments from agencies by email

**Comment by hkdctol** [comment]
Can be archived until we see further movement on schema.

**Comment by hkdctol** [comment]
Keeping open. Awaiting specific asks from OMB on schema updates. Confirmed this is in process.

**Comment by nick-j-roberts** [comment]
The DCAT-US schema indicates that the ["temporal"](https://resources.data.gov/resources/dcat-us/#temporal) and ["spatial"](https://resources.data.gov/resources/dcat-us/#spatial) properties are instances of the DC Terms properties ["temporal"](http://purl.org/dc/terms/temporal) and ["spatial"](http://purl.org/dc/terms/spatial) respectively.

However, the expected values for both are literal values, which are not allowed as properties of the DC Terms properties. This appears to be an invalid mapping.

**Comment by hkdctol** [comment]
Requirements for this are currently being collected at https://github.com/DOI-DO/dcat-us/issues through June 30

**Comment by hkdctol** [comment]
Going to move this issue to "Done" for now. Will open new issues as needed as FAIRness project develops.
