### ISSUE TITLE
Improve/clean terraform via snyk

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4094]
## User Story

In order to have the most secure infrastructure, data.gov admin wants a complete review of the outstanding snyk vulnerabilities across the data.gov org and resolution via fixes, ignoring, or removing scans where appropriate.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN 2 days have passed \
  WHEN I look at the snyk dashboard \
  THEN all terraform code registers as clean \
  OR a specific issue is created to resolve the current state

## Background

Discussed during pairing; we want to clean up the snyk dashboard and validate that our code is up to spec.
These have all been cleared and re-created to make sure they have the latest files/code.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Consult [snyk dashboard](https://app.snyk.io/org/data.gov/projects) for details.

## Sketch

Examine the following projects in snyk, and any outstanding vulnerabilities. Please use pairing/review when appropriate; the goal of the snyk dashboard is to help us create secure infrastructure and use secure libraries in production. If something is being scanned that isn't relevant to that, then you can remove the scanning for that particular file (called "project" in snyk). See [Dependency Scanning wiki](https://github.com/GSA/data.gov/wiki/Dependency-scanning) for our details and best practices...
- eks-brokerpak
- datagov-iam
- datagov-ssb
- datagov-brokerpak-solr
- ...

**Comment by nickumia-reisys** [comment]
@GSA/data-gov-team This comment needs to be reviewed:
- https://app.snyk.io/org/data.gov/project/d52e37d3-b1a9-43c7-b3a9-48cc66ba6d05#issue-SNYK-CC-TF-116_resource.aws_iam_user_policy_attachment[ci]

If someone agrees with my assessment, we can ignore this permanently.

**Comment by nickumia-reisys** [comment]
@GSA/data-gov-team These comments are all the same to highlight the same problem that is repeated three times and needs to be reviewed:
- https://app.snyk.io/org/data.gov/project/3d6f6d77-e1d0-4d96-87da-69ae61d58af8#issue-SNYK-CC-TF-116_resource.aws_iam_user_policy_attachment[eks_broker_policies]
- https://app.snyk.io/org/data.gov/project/3d6f6d77-e1d0-4d96-87da-69ae61d58af8#issue-SNYK-CC-TF-116_resource.aws_iam_user_policy_attachment[smtp_broker_policies]
- https://app.snyk.io/org/data.gov/project/3d6f6d77-e1d0-4d96-87da-69ae61d58af8#issue-SNYK-CC-TF-116_resource.aws_iam_user_policy_attachment[solr_broker_policies]

If someone agrees with my assessment, we can "ignore" this permanently as "not vulnerable".

**Comment by jbrown-xentity** [comment]
Ignore those permanently, attaching to roles doesn't make sense in the context of a single automated user...

**Comment by nickumia-reisys** [comment]
The following issues have been made for the remainder of the snyk alerts:
- https://github.com/GSA/data.gov/issues/4095
- https://github.com/GSA/data.gov/issues/4096
- https://github.com/GSA/data.gov/issues/4097
- https://github.com/GSA/data.gov/issues/4100
- https://github.com/GSA/data.gov/issues/4101
- https://github.com/GSA/data.gov/issues/4102
- https://github.com/GSA/data.gov/issues/4103
- https://github.com/GSA/data.gov/issues/4104
- https://github.com/GSA/data.gov/issues/4105
- https://github.com/GSA/data.gov/issues/4106
- https://github.com/GSA/data.gov/issues/4107

General process used to  triage alerts:
- Determine if alert is a real vulnerability or a design choice
- If it is a design choice, `ignore permanently` with a detailed reason about the implementation details.
- If it is a vulnerability, open new issue and `ignore temporarily` for `xx days` (depending on our vulnerability timelines) to reassess the vulnerability at a later date.

**Comment by nickumia-reisys** [comment]
Other related efforts (for datagov-brokerpak-solr specifically):
- https://github.com/GSA/datagov-brokerpak-solr/pull/67
- https://github.com/GSA/datagov-brokerpak-solr/pull/68
