### ISSUE TITLE
Consider changes to SMTP Broker

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4098]
## User Story

In order to handle new updates to the SMTP Broker, the Data.gov maintenance team wants to assess whether the new changes to the SMTP Broker are worth incorporating.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN an assessment has been made \
  WHEN the SMTP Broker is updated happens \
  THEN the desired changes take effect.

## Background

- https://github.com/GSA-TTS/datagov-brokerpak-smtp/pull/18

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
May result in new permission for the SMTP Broker, but nothing out of the ordinary.

## Sketch

- [ ] Decide whether we want the new features
  - [ ] If we DO NOT want the features,
    - [x] Set `enabled_feedback_notifications: false` in the SMTP creation for `catalog` and `inventory`
  - [ ] If we DO want the features,
    - [ ] Update permissions for the SMTP broker in `datagov-ssb`
    - [ ] Optionally set `enabled_feedback_notifications: true` (the default is true, so it would just be documentation that this is enabled)

**Comment by jbrown-xentity** [comment]
Going to take initial mitigation steps, then delay the feature integration... cc @nickumia-reisys

**Comment by nickumia-reisys** [comment]
Mitigation steps complete ✔️

**Comment by nickumia-reisys** [comment]
Superseded by
- https://github.com/GSA/data.gov/issues/4232
