### ISSUE TITLE
[datagov-brokerpak-solr] EFS in task definition does not encrypt data in transit 

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4102]
**Date of report:** 12/06/2022
**Severity:** Moderate

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] [EFS in task definition does not encrypt data in transit](https://app.snyk.io/org/data.gov/project/ac53c00a-f125-4fbd-a4e8-49c716381d86#issue-SNYK-CC-AWS-413_resource.aws_ecs_task_definition[solr-follower].volume.efs_volume_configuration.transit_encryption) (Moderate)
  - Detailed paths
    - Path: [terraform/ecs/provision/follower.tf](https://github.com/GSA/datagov-brokerpak-solr/blob/main/terraform/ecs/provision/follower.tf)
    - Introduced through: ` resource › aws_ecs_task_definition[solr-follower] › volume › efs_volume_configuration › transit_encryption `
  - This issue is...
    - Data between ECS host and EFS server is not encrypted in transit
  - The impact of this is...
    - The content could be intercepted and manipulated in transit
  - You can resolve it by...
    - Set `volume.efs_volume_configuration.transit_encryption` attribute to `ENABLED`.
- [ ] [EFS in task definition does not encrypt data in transit](https://app.snyk.io/org/data.gov/project/e438fe88-58bc-4cf2-8cbe-0d2ee767d3a2#issue-SNYK-CC-AWS-413_resource.aws_ecs_task_definition[solr].volume.efs_volume_configuration.transit_encryption) (Moderate)
  - Detailed paths
    - Path: [terraform/ecs/provision/leader.tf](https://github.com/GSA/datagov-brokerpak-solr/blob/main/terraform/ecs/provision/leader.tf)
    - Introduced through: ` resource › aws_ecs_task_definition[solr] › volume › efs_volume_configuration › transit_encryption `
  - This issue is...
    - Data between ECS host and EFS server is not encrypted in transit
  - The impact of this is...
    - The content could be intercepted and manipulated in transit
  - You can resolve it by...
    - Set `volume.efs_volume_configuration.transit_encryption` attribute to `ENABLED`.

**Comment by nickumia-reisys** [comment]
I remember we've had issues with this in the past... here's some links for historical reference:
- https://github.com/GSA/datagov-brokerpak-solr/pull/36/commits/5e0ac34b58a9a9127de9da60dbea32829ad51e7b
- https://github.com/GSA/datagov-brokerpak-solr/pull/36/commits/4cf4c5aa89cd38e132c1c6482590b9739b959d2e
- https://github.com/GSA/datagov-brokerpak-solr/pull/36/commits/622b81461ac37cbea097c576c5666e232b53ed69
- https://github.com/GSA/datagov-brokerpak-solr/commit/f18654dd22fad2b921411b8bdd2d2b05dab155db

**Comment by hkdctol** [comment]
This seems duplicative of #4119
