### ISSUE TITLE
catalog egress rule leaves HTTP traffic open

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4112]
[Catalog egress](https://github.com/GSA/data.gov/issues/4086) is working as expected for `HTTPS` traffic, blocking all outgoing requests except for domains on [the allow list](https://github.com/GSA/data.gov/blob/main/egress/acl/allow.acl). But it does not restrict any HTTP traffic. 

## How to reproduce

ssh into any catalog instance, load `/tmp/lifecycle/shell` and `.profile`, run:
```
curl -I http://www.yahoo.com/
```
## Expected behavior

403 error, blocked by the egress-proxy

## Actual behavior

301. traffic went through.

## Sketch

1. Block all `HTTP` traffic, or
2. Redirect all `HTTP` to `HTTPS`, or
3. Copy the `HTTPS` logic and create an allow list to `HTTP`?

**Comment by hkdctol** [comment]
I have checked most of the harvest sources, but will do a bit more looking before we go ahead with option 1 - of blocking all HTTP traffic

**Comment by hkdctol** [comment]
I've finished the rest of the checking--I think we can go ahead with option 1 in the sketch

**Comment by hkdctol** [comment]
@FuhuXia can we go with option 1 on this to close it out?

**Comment by FuhuXia** [comment]
HTTP traffic is now limited to the [allowed list](https://github.com/GSA/data.gov/tree/main/egress/acl) only. So command `curl -I http://www.yahoo.com/` is failing now. To totally block all port 80 traffic, even for domain on the allowed list, which means command `curl -I http://www.gsa.gov` will fail as well, we are waiting for cg-egress-proxy PR to merge.

**Comment by FuhuXia** [comment]
cg-egress-proxy PR is merged. After updated the repo commit and re-enable egress app, now requests to `http://www.yahoo.com:80` and `http://www.gsa.gov:80` are seeing 403 forbidden. Will re-enable the egress app to all apps in all environments to apply the fix.
