### ISSUE TITLE
Add explainer text to Organizations Page

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4117]
## User Story

In order to assist users who may want to look at datasets by agency, we need to add some explanatory text to https://catalog.data.gov/organization/

## Acceptance Criteria

- [ ] GIVEN a user goes to https://catalog.data.gov/organization/
  THEN there are directions or help desk that make it clear it's a way to view all datasets from a particular agency, and how to get the list of datasets

## Background

We may link to an Organizations view from a redesigned data.gov home page, see #4029 

## Sketch

- [ ] Identify needed additional description or help text or organizations page
- [ ] Make the text changes on  https://catalog.data.gov/organization/

**Comment by hkdctol** [comment]
Proposed updated language is at https://docs.google.com/document/d/1JY-vAQzcFKu1b-tv5c0d3NoGCGliByiw-uc0jfBm0XE/edit?usp=sharing

**Comment by btylerburton** [comment]
This is a lot more user-focused. Nicely done. Should I update the text on the page, or would you like to wait for more feedback?

**Comment by hkdctol** [comment]
@btylerburton let's go ahead
