### ISSUE TITLE
[SC-23] Ensure all inter-component traffic within Solr is sent over TLS

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4119]
## User Story

In order to increase our security posture, the Data.gov Solr Team wants to secure all communication channels within our Solr deployment.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN communication between Solr and the LB is encrypted \
  WHEN I look at the Solr service
  THEN I see it listening only on port 443

- [ ] GIVEN communication between Solr and the Admin Init app is encrypted \
  WHEN I look at the logs of the Admin Init app
  THEN I see it talking to Solr over https

- [ ] GIVEN communication between Solr and EFS is encrypted \
  WHEN I look at the Solr service
  THEN I see it talking to EFS in an encrypted way

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]
Related tickets:
- https://github.com/GSA/data.gov/issues/3826
- https://github.com/GSA/data.gov/issues/4102

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
TODO

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]
- [ ] Determine the scope of what traffic falls under this category
  - [ ] All internal traffic is unencrypted in the current design
    - [ ] Solr to/from LB
    - [ ] Solr to/from Admin Init app
    - [ ] Solr to/from EFS
- [ ] Design solutions for each component
- [ ] Implement them

**Comment by nickumia-reisys** [comment]
Full disclosure: This is not an easy issue.  There are known issues as to why we couldn't get EFS encrypted-in-transit and to support HTTPS from the Solr node itself would require installing either self-signed certificates or some other solution which is further customization to the design (not to mention the implementation details themselves).

**Comment by hkdctol** [comment]
We don't know if this is possible to be implemented; may have to look into getting acceptance of current.

**Comment by btylerburton** [comment]
have things changed? is this easy now?
https://docs.aws.amazon.com/efs/latest/ug/encryption-in-transit.html

**Comment by nickumia-reisys** [comment]
So, I remembered that I looked at that page and that I tried to use the `efs-utils`.  I was trying to track down the problem we saw when we tried to implement it.  However, as a trail of that specific work @btylerburton:
- Commit that introduces it: https://github.com/GSA/datagov-brokerpak-solr/pull/36/commits/4cf4c5aa89cd38e132c1c6482590b9739b959d2e
- Commit that removes it: https://github.com/GSA/datagov-brokerpak-solr/commit/f18654dd22fad2b921411b8bdd2d2b05dab155db
- Commit that added the tools to the Solr image: https://github.com/GSA/catalog.data.gov/commit/63faf929f591f42f84c42770cb53c46cb449b3f2

There was some issue with connectivity.  Either AWS didn't like the hack with efs-utils trying to initiate the connection after the Solr container was already running and since it couldn't establish the connection, Solr just made a temporary directory for its data.  The primary issue was that the connection was not being established TLS and there were no errors, no warnings, no indications about which part of the connection was failing.  Not being able to debug it, I had given up.  We can try again, but I stand by the fact that it is not worth the effort to investigate this.

We had even submitted an issue with AWS Support and there wasn't any specific help that they could provide because they thought it was an application/infrastructure-specific issue that they were not knowledgeable enough to diagnose.

**Comment by hkdctol** [comment]
Next step looks like discuss with our ISSO.

**Comment by hkdctol** [comment]
Discussed with ISSO on 2/14/23. He will raise with ISSM.

**Comment by jbrown-xentity** [comment]
[Summary doc](https://docs.google.com/document/d/1egtR31T6ex5M7aa7WS9OwV9-WTMPPMDQt1ecpRtEkeQ/edit#heading=h.lc8ka4297uo) @hkdctol

**Comment by hkdctol** [comment]
ISSO advises we start work on AOR, https://docs.google.com/document/d/18AvgMBln6fKgoznb3BWTvu2JHO7iISyf/edit?usp=sharing&ouid=113511966954817069922&rtpof=true&sd=true

**Comment by hkdctol** [comment]
Draft sent to ISSO

**Comment by hkdctol** [comment]
Met with ISSM 8/9, this is pending CISO's return from leave in a few weeks

**Comment by nickumia-reisys** [comment]
While the work wasn't fully documented in motion, an exhaustive search for how to enable TLS for EFS volumes in ECS was pursued combining documentation at the crossroads of Solr, Terraform and AWS.  The full list of options were attempted without success setting up the IAM permissions, EFS volume, EFS access points, ECS mounting and solr volume setup.  There may have been a bug or something very unique about our Solr application that was causing issues; however, all attempts were inconclusive.  

All of the commits where in this PR:
- https://github.com/GSA-TTS/datagov-brokerpak-solr/pull/36
  - In the range of:
    - https://github.com/GSA-TTS/datagov-brokerpak-solr/pull/36/commits/d71744e39e94782360bd7d3543a2b4931ff325d8
    - https://github.com/GSA-TTS/datagov-brokerpak-solr/pull/36/commits/a7f84a107ee2aad83066794f1af7e40926ff8533

List of references used:
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/tutorial-efs-volumes.html#efs-add-content
- https://aws.amazon.com/premiumsupport/knowledge-center/ecs-fargate-mount-efs-containers-tasks/
- https://aws.amazon.com/premiumsupport/knowledge-center/fargate-unable-to-mount-efs/
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_access_point
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/efs-volumes.html#specify-efs-config
- https://docs.aws.amazon.com/efs/latest/ug/iam-access-control-nfs-efs.html
- https://medium.com/@ilia.lazebnik/attaching-an-efs-file-system-to-an-ecs-task-7bd15b76a6ef
- https://aws.amazon.com/blogs/containers/developers-guide-to-using-amazon-efs-with-amazon-ecs-and-aws-fargate-part-3/
- https://stackoverflow.com/questions/56403309/how-can-i-mount-an-efs-share-to-aws-fargate

AWS Support Ticket:
- https://support.console.aws.amazon.com/support/home?region=us-west-2#/case/?displayId=10114958361&language=en

**Comment by rpalmer-gsa** [comment]
@nickumia-reisys can you dump the support ticket to a PDF as I don't have access to view it. 

Thank you

**Comment by nickumia-reisys** [comment]
@rpalmer-gsa Here is the [doc version](https://docs.google.com/document/d/16oHvkr05dmgme5kIj6OMqQ6uyaiPRVDGYWy2c3K4Jcw/edit#heading=h.lwp2kgaybf51) of the support ticket.

P.S. I tried my best to paste it in a readable structure. ([additional discussion](https://gsa-tts.slack.com/archives/C2N85536E/p1695330288690229))

**Comment by hkdctol** [comment]
Met with ISSM 1/22, he will follow up on AOR status

**Comment by btylerburton** [comment]
Not carried over as a new POA&M
