### ISSUE TITLE
Design "Updated Dataset per Time Period" Metric for static site

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4129]
## User Story

In order to improve user engagement, the Data.gov UI/UX Team wants to design a metric that shows data.gov activity.  The logic is this: If users see that our datasets are consistently updated or otherwise active, users will gain more trust and confidence in our platform, applications and (most importantly) community!

## Acceptance Criteria

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an equation/formula/expression that represents the metric

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an implementation sketch on how to gather the data to input into the equation/formula/expression (i.e. where is the data available)

## Background

Instead of trying to create a new way to search catalog.data.gov, this is a shift to make our data more transparent, understandable and discoverable.  By creating high-level metrics to quantify or qualify our data, we are helping to engage our users and make our platform more interactive.

A few thoughts on this from [initial discussion](https://docs.google.com/document/d/1EWN0n8qdO0UhcXeeZd9tcf6_OjoiZUl-A95LNAJcuQk/edit#heading=h.rqodwgrr8pq2):
- The number of updated datasets can be seen from harvesting
- @FuhuXia had a great point that: There needs to be a context to understand the number of "updates".  Saying "5 datasets were updated" in one span of time and "500 datasets were updated" in the next sequential span of time does not give very meaningful information to users.
- The idea is to represent how current data.gov is.  This also means showing users the limits of what current are.  Which then lets them evaluate how successful we are in staying current.
- Possible starting representations: (1) percentages and (2) time graphs.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None!

## Sketch

There is no defined sketch for performing this analysis.  Be creative in how you gather the data and draw inspiration from your life experiences on how best to visualize and convey the information.  This is a team effort and peer-development/reviewing will bring together the final design.

**Comment by nickumia-reisys** [comment]
A random note... (I feel like) we haven't had a well-defined ticket like this in a while where all of the fields in the template were relevant and made sense.  I'm proud that I was able to write this 🥲

**Comment by hkdctol** [comment]
Need to structure--what is the time period, what is updated mean, etc. and then how do you represent that.

**Comment by nickumia-reisys** [comment]
The two main questions to answer here are:
- What does "updated" mean?
  - There are three types of "updates" that occur during harvesting: (1) An existing dataset is modified, (2) An existing dataset is deleted and (3) A new dataset is added.  It might make sense to track each of these cases separately.
  - Deleted datasets might not make sense to end users because open data should not be deleted (unless it is permanently deleted from records for being too old or otherwise irrelevant) The question I have here is: What are all of the causes of deleted datasets?
  - Updated datasets are useless if there are no real updates and it is only toil because agencies are using an automated system that changes the ordering of fields or tags which aren't tracked by our harvesting system properly and forces an update.  This would require another statement of "this may be inaccurate due to harvesting issues"
- What is a good value or range of values for "time period"?
  - Time period can be broken down into two parts: (1) Time span length and (2) Frequency of time span lengths.  Monthly, for example, defines 28-31 day periods (i.e. time span lengths).  However, showing monthly data for a year, or in essence 12 data points is the frequency of time span lengths.

Expanding the above definitions, I think it would be nice to have an aggregated bar chart visual with options for 
- Type of update operation (added, deleted, modified)
- With (at least) one year's worth of different time periods (12xmonthly (one year), 26xweekly (six months), 21xdaily (three weeks))

With respect to having a context to the number of datasets, we could make it relative to the number of datasets in each harvest source or across all harvest sources.  If 5% of datasets are being updated a week it might be more meaningful than saving 500 datasets are being updated a week.  In this respect, this metric would track a similar growth or decay of datasets on a more granular level than https://github.com/GSA/data.gov/issues/4132.  By splitting it up into added/deleted/modified, it does show much more than the high-level total dataset growth/decay.

I think this metric should highlight agency involvement more so than the growth/decay of data.gov.  We could aggregate the updates and have more of a "contribution" score per organization.  Github considers commits/opening PRs/reviews all part of "contributions" and then gives this nice graph.  We could do a similar thing for data.gov
![image](https://user-images.githubusercontent.com/85196563/214930790-338e61c1-c8e6-4f62-afbc-09f7c642f90e.png)

**Comment by nickumia-reisys** [comment]
Passing to @Jin-Sun-tts

**Comment by Jin-Sun-tts** [comment]
Did couple of API calls to get the number of datasets be updated per time period:

dataset updated per week: 9003 [(filter)](
https://catalog.data.gov/api/action/package_search?q=metadata_modified:[2023-01-23T00:00:00Z%20TO%202023-01-30T00:00:00Z])
dataset updated per  month: 52952 [(filter)](
https://catalog.data.gov/api/action/package_search?q=metadata_modified:[2023-12-30T00:00:00Z%20TO%202023-01-30T00:00:00Z])
dataset updated per  year: 166913 [(filter)](
https://catalog.data.gov/api/action/package_search?q=metadata_modified:[2022-01-31T00:00:00Z%20TO%202023-01-30T00:00:00Z])

some case like if some harvest jobs are monthly, the weekly dataset update number may not be consistent when monthly job running at same week. 

Also next we need to find the way to separate the type of update operation (added, deleted, modified?)

Passing to @FuhuXia

**Comment by FuhuXia** [comment]
We can use this to show the age distribution of our datasets

| DATASET AGE  | COUNT |
| ------------- | ------------- |
| 1 week  | 29K  |
| 1 week to 1 month  | 53K  |
| 1 month to 1 year  | 102K  |
| 1+ year  | 71K  |


![image](https://user-images.githubusercontent.com/1392461/217093809-6e38227b-01c5-4c1e-a269-a3560e96f1b3.png)

**Comment by FuhuXia** [comment]
passing to @btylerburton

**Comment by btylerburton** [comment]
I think [@FuhuXia](https://github.com/FuhuXia)'s bar chart visualization, while it obscures some detail, lands on a simple, effective way to highlight the age of datasets in catalog.

While it doesn't account for the flux of added vs deleted vs modified, and the churn of an agency updating tags and timestamps will throw off the true accuracy of the numbers, I would argue that any attempt at representing those individual attributes adds noise to the visualization. 

A better way to arrive at a more accurate representation might to inform our agency partners about best practices for harvest source maintenance in an updated user guide.

**Comment by btylerburton** [comment]
passing to @jbrown-xentity

**Comment by jbrown-xentity** [comment]
This is a wonderful discussion on how to gain insights at the macro level of the data we have. However, as something the "general" or "basic" user can consume, I think we need to keep it simple. @FuhuXia's is great, or we could do as @Jin-Sun-tts suggests and do something even simpler with counts of datasets modified (which includes datasets added) for each time range.
As to qualifiers, we can try to add those but at the end of the day if we don't trust our own data, then we should abandon this ticket and pick up tickets to improve/change harvesting, as the metric won't provide enough value for the work involved.

**Comment by jbrown-xentity** [comment]
Passing to @robert-bryson , but this might already be a wrap...

**Comment by robert-bryson** [comment]
Sorry, I didn't click the button on my comment, but I like the simplified and clear version that @FuhuXia shared.

**Comment by hkdctol** [comment]
For now we're going with approach in @FuhuXia comment above
