### ISSUE TITLE
Design "Daily User Visit" Metric

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4130]
## User Story

In order to improve user engagement, the Data.gov UI/UX Team wants to design a metric that shows data.gov activity.  The logic is this: If users see that our site has active human traffic, data.gov has better reputation as a trusted source of metadata of datasets.  A better reputation means, users will gain more trust and confidence in our platform, applications and (most importantly) community!

## Acceptance Criteria

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an equation/formula/expression that represents the metric

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an implementation sketch on how to gather the data to input into the equation/formula/expression (i.e. where is the data available)

## Background

Instead of trying to create a new way to search catalog.data.gov, this is a shift to make our data more transparent, understandable and discoverable.  By creating high-level metrics to quantify or qualify our data, we are helping to engage our users and make our platform more interactive.

A few thoughts on this from [initial discussion](https://docs.google.com/document/d/1EWN0n8qdO0UhcXeeZd9tcf6_OjoiZUl-A95LNAJcuQk/edit#heading=h.rqodwgrr8pq2):
- The source of this data can be: (1) google analytics (GA), (2) native ckan tracking ... other sources can be used if we think they're relevant (access logs, proxy logs, ckan logs, et cetera)
- GA is a work in progress, so it might not be as accurate as a source for this information
- Key question(s) to answer:
  - What counts as a page hit/visit?  Browser traffic?  Solr traffic? Non-API traffic? Some other fourth thing?
  - Do multiple page loads from a single user count once?
  - Does it make sense to give a few different visit metrics?  Visits per last 24 hours?  Most visits within 24 hours (and the day it occured on) for the year?  Average visits per week?
- Possible starting representations: (1) Numbers

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None!

## Sketch

There is no defined sketch for performing this analysis.  Be creative in how you gather the data and draw inspiration from your life experiences on how best to visualize and convey the information.  This is a team effort and peer-development/reviewing will bring together the final design.

**Comment by nickumia-reisys** [comment]
Since Google Analytics data is out-of-scope near term, we decided to try to use the native ckan tracking summary data.

The general documentation,
- https://docs.ckan.org/en/2.9/maintaining/tracking.html#retrieving-tracking-data

Tracking information is only available at the `package_show` level, not the `package_search` level,
- https://github.com/ckan/ckan/issues/3648

Currently, only the first 186 pages of catalog have tracking information, that's ~1860 datasets.  
- This was determined by manually loading each dataset main page until I saw the count disappear.
  ![image](https://user-images.githubusercontent.com/85196563/219577053-0a95173a-9581-4987-9914-52c6699e884d.png)

We could write a script to query each dataset upto `n` pages (200?) and then aggregate that data into a graph.  The following query will show package information,
```go
https://catalog.data.gov/api/action/package_show?id=<package-name>&include_tracking=True
```
![image](https://user-images.githubusercontent.com/85196563/219578408-4358270d-33be-403d-92b0-1ca0faa02c55.png)

**Comment by hkdctol** [comment]
I think we can close this one after our discussion today, and create a new ticket for basic metrics
