### ISSUE TITLE
Design "Data.gov Age" Metric

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4131]
## User Story

In order to improve user engagement, the Data.gov UI/UX Team wants to design a metric that shows the history and depth of data.gov.  The logic is this: If users see depth and breadth of our history, users will understand that we've been around since the beginning of the US Government's open data/open government initiative and we are still pioneering the future of it as well.  This is NOT to say, this is all the government has ever done and this is all the government will do.  We need to demonstrate our evolution and growth to highlight our determination and dedication to open data.

## Acceptance Criteria

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an equation/formula/expression that represents the metric

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an implementation sketch on how to gather the data to input into the equation/formula/expression (i.e. where is the data available)

## Background

Instead of trying to create a new way to search catalog.data.gov, this is a shift to make our data more transparent, understandable and discoverable.  By writing our story, we are helping to engage our users and make our platform more inclusive and welcoming.

A few thoughts on this from [initial discussion](https://docs.google.com/document/d/1EWN0n8qdO0UhcXeeZd9tcf6_OjoiZUl-A95LNAJcuQk/edit#heading=h.rqodwgrr8pq2):
- Key question(s) to answer:
  - Per @btylerburton, How are we measuring this?
    - @nickumia-reisys's answer: years (and/or) months (and/or) days since the launch of data.gov with the date of the 2009 Presidential Memo as the inception date.
- It was a thought that this should link to a page about "Our Story" which consists of the evolution of the law and the evolution of our technical solutions in relation to the law and also the global arena of open data advancements.
- Possible starting representations: (1) Numbers, (2) Infographics

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None!

## Sketch

There is no defined sketch for performing this analysis.  Be creative in how you gather the data and draw inspiration from your life experiences on how best to visualize and convey the information.  This is a team effort and peer-development/reviewing will bring together the final design.

**Comment by hkdctol** [comment]
The launch date for Data.gov was May 21, 2009.

**Comment by nickumia-reisys** [comment]
Age for a data aggregation system is a rather complicated issue.  There are the following ages to consider:
- The age of the platform/system (May 21st, 2009 mentioned above)
- The real age of the data on data.gov (dependent on when it was created)
- The age of when the data was documented (typically younger than the real age)
- The age of how long the data has lived on data.gov (typically younger than the documented age)

I think it would be nice to highlight:
- The age of the platform (14 years is good enough)
- ~The oldest dataset age~
  - Note: The oldest `metadata_created` date is in [11/2020](https://follower.solr-deb2a1db-ed85.ssb.data.gov:9000/solr/#/ckan/query?q=metadata_created:%5B2020-10-01T00:00:00Z%20TO%202020-11-01T00:00:00Z%5D&q.op=OR&indent=true).  There are 98759 datasets from that range.  This may be less meaningful because it is so far from our platform origin date of 2009.  It would have been cool to show that some dataset has existed since the beginning of data.gov.  However, it seems like our platform [does not show that](https://follower.solr-deb2a1db-ed85.ssb.data.gov:9000/solr/#/ckan/query?q=metadata_created:%5B2009-01-01T00:00:00Z%20TO%202020-11-01T00:00:00Z%5D&q.op=OR&indent=true), even if there are datasets that would've been around before then.
- ~The average age of data on data.gov~
  - This would take a bit of processing (`sum(metadata_modified - metadata_created)/count(datasets)`), but it would be a relatively young age (probably averaging to 1 year old).  Since it is not accurate, it might not make sense to show this either.  The idea is to show how new the data is to end users.  
- A recency age?
  - Also a bit of processing (`sum(metadata_modified - NOW)/count(datasets)`).  This could be months old which would be another measure of how updated the datasets are.

I don't have a visualization in mind, but it would kind of just be a bunch of dates/ages/numbers with labels.

Useful Reference for Solr Date lookup:
- https://stackoverflow.com/a/17838551

----

Passing to @hkdctol

**Comment by hkdctol** [comment]
I agree that some of these metrics are not meaningful because with the catalog changes, there isn't information about datasets that pre-date those 2020 changes. I think it's fine to start with the ones that are available--age of platform and recency.

**Comment by nickumia-reisys** [comment]
Passing to @Jin-Sun-tts

**Comment by Jin-Sun-tts** [comment]
I agree the age of platform and recency are good enough for now, and other ages may not meaningful to end users.

**Comment by btylerburton** [comment]
Agree that a simple age of platform should suffice. 

It could be nice to link this to "Our Story" as alluded to above, but I feel like focusing on improvements to the current catalog are more important than defining its historical evolution at this point in time.

**Comment by btylerburton** [comment]
passing to @robert-bryson

**Comment by nickumia-reisys** [comment]
I think Fuhu's comment is better served for this ticket,
- https://github.com/GSA/data.gov/issues/4129#issuecomment-1419810378

**Comment by robert-bryson** [comment]
I also didn't click the button on this, but I guess I'm not sure how we want this as a 'metric' in the sense of something that is being measured over time to determine something. It seems like it is just a simple fact that datagov is x age and perhaps we should display that somewhere in text or as part of a narrative, but I don't think this information fits well into a graphic or chart.

**Comment by hkdctol** [comment]
Agreeing to close and archive for now, may return to this at a later time.

**Comment by CarolinaC-REI** [comment]
**Homepage and timeline mockups and assets:**
![14-anniversary-homepage](https://github.com/GSA/data.gov/assets/108142696/ecbc0e5d-8aa3-4b43-bef7-e10944dc5738)
![14-anniversary-logo](https://github.com/GSA/data.gov/assets/108142696/35136ac0-86ee-474b-bc7b-caef3c499d7a)!

**Figma link:** [https://www.figma.com/file/pzf102CQrXYRweRn7FnAC1/Data.gov-homepage?type=design&node-id=91%3A903&t=Jrl4sfPeTMfHS3sp-1](https://www.figma.com/file/pzf102CQrXYRweRn7FnAC1/Data.gov-homepage?type=design&node-id=91%3A903&t=Jrl4sfPeTMfHS3sp-1)

**Timeline code:** [https://codyhouse.co/gem/vertical-timeline/](https://codyhouse.co/gem/vertical-timeline/)

**Comment by hkdctol** [comment]
@CarolinaC-REI looks good, can you delete "the" so that it's "Celebrating Data.gov's 14th Anniversary"

**Comment by CarolinaC-REI** [comment]
Sure thing, will add the updated mockup in a minute. Thank you

**Comment by CarolinaC-REI** [comment]
**Updated timeline page:** 
![Timeline-anniversary-page](https://github.com/GSA/data.gov/assets/108142696/5c7c80de-e755-41fc-b6f2-a6dbbd5e0eb0)

**Comment by hkdctol** [comment]
Looks good

**Comment by btylerburton** [comment]
WIP timeline page: https://federalist-2ac784db-2321-4734-8d02-933835d88304.sites.pages.cloud.gov/preview/gsa/datagov-11ty/datagov-timeline/timeline/

**Comment by btylerburton** [comment]
Build updated with new link to timeline on homepage: https://federalist-2ac784db-2321-4734-8d02-933835d88304.sites.pages.cloud.gov/preview/gsa/datagov-11ty/datagov-timeline/
