### ISSUE TITLE
Design a "Number of Datasets" Metric

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4132]
## User Story

In order to improve user engagement, the Data.gov UI/UX Team wants to design a metric that shows scale of data.gov.  The logic is this: If users see depth and breadth of our data, users will understand how much data they have access to and how diverse the datasets are.  By understanding the scale of our sites, users will be able to plan and make informed decisions about how to parse and organize the data.  More informed users means we are doing our job as aggregators and distributors of federal open data.

## Acceptance Criteria

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an equation/formula/expression that represents the metric

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an implementation sketch on how to gather the data to input into the equation/formula/expression (i.e. where is the data available)

## Background

Instead of trying to create a new way to search catalog.data.gov, this is a shift to make our data more transparent, understandable and discoverable.

A few thoughts on this from [initial discussion](https://docs.google.com/document/d/1EWN0n8qdO0UhcXeeZd9tcf6_OjoiZUl-A95LNAJcuQk/edit#heading=h.rqodwgrr8pq2):
- Key question(s) to answer:
  - Should we show dataset count change over a time period (e.g. a year)?
- There is a concern of how duplicates may inflate or otherwise distract from the meaningfulness of this metric
- Possible starting representations: (1) Numbers, (2) Infographics, (3) Time graphs

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None!

## Sketch

There is no defined sketch for performing this analysis.  Be creative in how you gather the data and draw inspiration from your life experiences on how best to visualize and convey the information.  This is a team effort and peer-development/reviewing will bring together the final design.

**Comment by nickumia-reisys** [comment]
To kick off this discussion, here's a list of data sources that should be considered for this metric (number at the time of writing):
- The number of datasets visible on our catalog homepage ([242,779](https://catalog.data.gov/api/action/package_search?rows=0))
- The number of individual datasets (241834)
- The number of "collections" ([945](https://catalog.data.gov/api/action/package_search?fq=(collection_metadata:*)&include_private=true&rows=0))
- The number of total datasets including "collections" children ([367399](https://catalog.data.gov/api/action/package_search?fq=(collection_package_id:*%20OR%20*:*)&include_private=true&rows=0))

In terms of duplicates, I think it's important to be transparent to end users and say that, "at any given time, these numbers may be inaccurate because of duplicate harvesting issues"

In terms of how this number changes over time, it may not be useful because of how duplicates have plagued our history.  But it would be a cool metric to track.  It would highlight the growth (or decay) of open data over time and give users confidence that open data is (hopefully) here to stay.

In terms of how to visual present this, I don't have anything in mind yet.  However, I'll pass it on to someone else to give more thoughts on what the "number of datasets" could be and anything else they can think about.

P.S. Shoutout to @FuhuXia for helping with the API queries above 😄

**Comment by nickumia-reisys** [comment]
Passing to @btylerburton

**Comment by hkdctol** [comment]
Line chart over time? With the explanations that Nick suggests including?

**Comment by btylerburton** [comment]
A line chart over time seems like the best fit for this metric. We might consider highlighting individual datasets vs total datasets including "collections" children, like in the sample screenshot below.

Also, even with duplicate bloat, a time series would help to highlight the growth (or decay) of the catalog over time as @nickumia-reisys mentioned.
 

![Image](https://user-images.githubusercontent.com/104455281/217958485-618b7944-b0b6-433c-936d-7ea5fec2b420.png)

[Chart.js sample line chart here](https://www.chartjs.org/docs/latest/samples/line/line.html)

**Comment by btylerburton** [comment]
Passing to @FuhuXia

**Comment by FuhuXia** [comment]
A total number will do. I see little value in plotting it against time.

Or we take the opportunity to inform user how many datasets are in collections which do not show up in the default search result.

![image](https://user-images.githubusercontent.com/1392461/218572877-90eb8534-3eca-4bc2-9899-1c7cb43dda2e.png)

**Comment by FuhuXia** [comment]
Passing to @jbrown-xentity.

**Comment by jbrown-xentity** [comment]
I like @FuhuXia 's metric. Ideally we would include some kind of "learn more about collections here" link, with an article detailing what they are, and how we handle them.

**Comment by jbrown-xentity** [comment]
Passing to @robert-bryson

**Comment by robert-bryson** [comment]
I think a line chart over time also makes sense here. 

I agree with Fuhu that I don't know if it would be 'valuable' to users per se, but a line chart does tell a story about datagov's growth or decline over time and users are more likely to be more engaged in a platform that seems to be growing I think.

Pass to @Jin-Sun-tts

**Comment by hkdctol** [comment]
Looking at options for representing the two numbers, we also need to add a section to user guide where we we link for more info on collections

**Comment by hkdctol** [comment]
The section of the user guide we would link to is highlighted in yellow in the google doc https://docs.google.com/document/d/1ZEYty8ZthiRHrAS073QP1A_dZ-XASSQ2YfrQPkmDWXY/edit?usp=sharing
