### ISSUE TITLE
Design an "Organization Distribution" Metric

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4133]
## User Story

In order to improve user engagement, the Data.gov UI/UX Team wants to design a metric that shows scale of data.gov.  The logic is this: If users see the source of the data, users will understand the source context of the data they have access to.  By understanding the scale of our collaborations and integrations, users will be able to plan and make informed decisions about how to parse and organize the data.  More informed users means we are doing our job as aggregators and distributors of federal open data.

## Acceptance Criteria

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an equation/formula/expression that represents the metric

- [ ] GIVEN the metric has been designed
  WHEN I look at this ticket
  THEN there is an implementation sketch on how to gather the data to input into the equation/formula/expression (i.e. where is the data available)

## Background

Instead of trying to create a new way to search catalog.data.gov, this is a shift to make our data more transparent, understandable and discoverable.

A few thoughts on this from [initial discussion](https://docs.google.com/document/d/1EWN0n8qdO0UhcXeeZd9tcf6_OjoiZUl-A95LNAJcuQk/edit#heading=h.rqodwgrr8pq2):
- There is no agreed upon number of Federal Agencies.
- We could show the distribution of Federal vs. State vs. City/Local Governments (pie chart)
- We could show the distribution of organizations, but also datasets owned by organizations
- Possible starting representations: (1) Pie charts

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None!

## Sketch

There is no defined sketch for performing this analysis.  Be creative in how you gather the data and draw inspiration from your life experiences on how best to visualize and convey the information.  This is a team effort and peer-development/reviewing will bring together the final design.

**Comment by nickumia-reisys** [comment]
This metric is arguably harder than others because there is no de facto answer to the organization or structure of the US government.  Showing the distribution of federal vs. state vs. city/local governments is secondary to the primary goal of Data.gov.  Data.gov is primary focused on federal open data.  The fact that we also have non-federal data is important to show users as well, so they understand the context of the data they are looking at.

As a general first pass, here are the pieces of information that are relevant to this metric:
- There are 206,713 datasets from federal agencies ([filter](https://catalog.data.gov/dataset/?organization_type=Federal+Government))
- There are 11,016 datasets from state agencies ([filter](https://catalog.data.gov/dataset/?organization_type=State+Government))
- There are 8,214 datasets from city governments ([filter](https://catalog.data.gov/dataset/?organization_type=City+Government))
- There are 1,921 datasets from country governments ([filter](https://catalog.data.gov/dataset/?organization_type=County+Government))
- There are 6,170 datasets from "universities" ([filter](https://catalog.data.gov/dataset/?organization_type=University))
- Organization type count (132 total):
  - `{None: 7, 'County Government': 8, 'Federal Government': 62, 'City Government': 28, 'Tribal': 1, 'University': 7, 'State Government': 18, 'Non-Profit': 1}`
    ```python
    import requests

    org_type = {}
    org_type[None] = 0

    def get_next(offset):
        print(offset)
        r = requests.get('https://catalog.data.gov/api/action/organization_list?all_fields=true&offset=%s' % (offset))
        if "The request could not be satisfied." in r.text:
            return None
        return r.json()['result']

    for i in range(6):
        resp = get_next(i*25)
        for org in resp:
            try:
                if org['organization_type'] in org_type:
                    org_type[org['organization_type']] += 1
                else:
                    org_type[org['organization_type']] = 1
                print(i, len(resp), org['organization_type'])
            except:
                org_type[None] += 1
                print(i, len(resp), None)

    print(org_type)
    ```

It would make sense to show the above information in the form of a pie chart.  What I think is missing is the context of what organizations are missing which might be out of scope for this effort.  The other thing to note is that some organizations have parent/child relationships that would mess with the distribution (e.g. There is a DoD org and also an Army Corps org.  There is DOI and there's USGS which is part of DOI.)  Just something to keep in mind.

**Comment by nickumia-reisys** [comment]
Passing to @FuhuXia

**Comment by FuhuXia** [comment]
Given the large portion of data are from federal agencies, this chart will give user the impression that our data is mostly federal, mixed with a bit of something else with a percentage so low that i doubt the actual number is useful/valuable to any users. We can build this metric but I wont place it at prominent spot on the frontage.
![image](https://user-images.githubusercontent.com/1392461/217082927-1eb1b29f-9167-4192-af5a-db8005dce77f.png)

**Comment by FuhuXia** [comment]
passing to @Jin-Sun-tts

**Comment by Jin-Sun-tts** [comment]
We may also get the dataset numbers from the call `https://catalog.data.gov/api/action/organization_list?all_fields=true`, but this one may not include collections ("package_count") and need to confirm. 

And question like do we need to show the datasets per organization as a chart?  There are about 133 orgs.

**Comment by Jin-Sun-tts** [comment]
passing to @btylerburton

**Comment by btylerburton** [comment]
Based on the comments above, this metric is of questionable value, particularly since we already highlight these as filters/facets on the catalog sidebar.

There might be some value in compiling a comprehensive list of agencies / bureaus / programs -- possibly using the list referenced below from the dashboard -- and listing our percentage represented in the catalog. 

https://dashboard.data.gov/docs#metrics_programs
Bureaus represented
This number represents the number of bureaus (based on codes from [OMB Circular A-11](http://www.whitehouse.gov/sites/default/files/omb/assets/a11_current_year/app_c.pdf) for the Common Government-wide Accounting Classification - CGAC in Appendix C) that have data sets reported in the agency's EDI. (Quantitative)

Programs represented
This is a count of primary agency programs that are represented within the EDI based on the [Federal Program Inventory](http://goals.performance.gov/federalprograminventory). (Quantitative)

Both links currently do not resolve, however.
https://www.whitehouse.gov/sites/default/files/omb/assets/a11_current_year/app_c.pdf

https://goals.performance.gov/federalprograminventory

**Comment by btylerburton** [comment]
passing to @robert-bryson

**Comment by robert-bryson** [comment]
I do agree that the majority of our orgs being federal trying to show a chart would just highlight federal data being dominant. I also agree that this probably isn't the metric that we would want to display most prominently, but our users might be interested to get a bit of insight into the scale and diversity of our datasets. If so, maybe we don't want to use a graphic for this.

Perhaps my eye is simplistic, but Nick's way of just showing in text the count of datasets and agencies did catch my attention. Maybe something built on that? With links to the pages showing those results?

- xxx,xxx datasets from xx federal agencies
- xx,xxx datasets from xx state agences
- etc.

Pass to @jbrown-xentity

**Comment by hkdctol** [comment]
We are going with the approach outlined in @robert-bryson comment above. I would not include university (to not get into the question re geospatial authorities etc.)

**Comment by hkdctol** [comment]
Visual? Bubble with a log scale? Can just do a table as well. Not just the number of datasets but number of organizations of each type, or harvest sources.

**Comment by btylerburton** [comment]
Consensus is Bubble chart
Unique color represents org type
X axis is agency count per org
Y axis is harvest source count
Bubble size is dataset count.
