### ISSUE TITLE
Solr follower core locked after restart with multiple index folders found

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4138]
Once in a while one of the Solr Followers gives core locked error. 

```
ckan: org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Index
dir '/var/solr/data/ckan/data/index/' of core 'ckan' is already locked. The most likely cause
is another Solr server (or another solr core in this server) also configured to use this directory;
other possible causes may be specific to lockType: simple
```
When it happens, the port is up therefore ECS considers the instance is healthy but its Solr is not serving any request, causing one catalog.data.gov Solr error for every three requests (we have three followers). 

## How to reproduce

2022-10-20 [Slack discussion](https://gsa-tts.slack.com/archives/C2N85536E/p1666306801657799).

2022-12-25 [Slack discussion](https://gsa-tts.slack.com/archives/C2N85536E/p1672074412607449). 

2023-01-30 [Slack discussion](https://gsa-tts.slack.com/archives/C2N85536E/p1675087724666689)

2023-02-07 [Slack alert](https://gsa.enterprise.slack.com/files/USLACKBOT/F04P5AE01GQ/ok___solr-deb2a1db-ed85-follower-2-memorythreshold__in_us_west__oregon_)

2023-02-23 [Slack discussion](https://gsa-tts.slack.com/archives/C2N85536E/p1677161114450729)

2023-05-12 [Slack discussion](https://gsa-tts.slack.com/archives/C2N85536E/p1683896567288579)

## Sketch
1. [Manual steps](https://github.com/GSA/data.gov/wiki/catalog.data.gov#restart-failed-solr-instance) to recover it. Or,
2. Add an auto recover step in [solr_setup.sh](https://github.com/GSA/catalog.data.gov/blob/main/solr/solr_setup.sh):
When it happens, we always see multiple index folders in the `/var/solr/data/ckan/data` directory. We can detect this and set a timer to restart Solr after a few minutes, equivalent to the manual steps, which is known to always solve the issue.

**Comment by FuhuXia** [comment]
Expecting this happens once in every month or two, causing catalog going down until manual restart. We need to fix it.

**Comment by nickumia-reisys** [comment]
Script that Fuhu is proposing (@FuhuXia edit this comment if not true):
```bash
while http://localhost:8983 is not 200:
    sleep 1

if there are two index folders:
   pkill solr-fg
```

In order for this to be self-contained, the script or function would need to be defined in the existing solr_setup.py script or the brokerpak would need to be modified to download a second script file.  I think defining a function and starting it in the background should be okay.  It might take some effort to test this fully..

-----------------------------------------
[update]
we can use solr command to stop the server more gracefully without risking any file corruption
```
solr stop -p 8983
or
solr restart
```

**Comment by FuhuXia** [comment]
~~Not quite yet. This `while` loop will make the script waiting forever for the solr process which never gets a change to start.~~

I got what you mean. Yes, a new script, initiated by the solr_setup.py.

**Comment by FuhuXia** [comment]
Changes is live. Restarted Staging Solr to verify the results. Logs shows it is working as expected in a happy path scenario.  It may be hard to capture the real core lock event unless we diligently check the logs shortly after every Solr reboot event. Until then, this fix may remain as an unsung hero, fixing core lock event without ever being noticed. 

![image](https://user-images.githubusercontent.com/1392461/221936887-cc917519-b280-4834-974b-83fc55a88206.png)

**Comment by FuhuXia** [comment]
The script appears working for restart initiated by us on the AWS console, but in a real Solr restart incidence the script sent solr to a restart loop for 15 times and it took 30 mins for the solr to finally start normal. We have reverted the change. 

Will change the script to a diagnostic tool, print out logs to help us better understand the multiple-index-folder situation before coming up with a better fix. The information we want to capture include:
1. index folder count for 5 minutes after a solr restart (hopefully with replicating actitivty);
2. index folder size;
3. lock file inside index folder(s);
4. any core lock message in Solr log.

**Comment by FuhuXia** [comment]
Captured logs during a solr restart. The logs show a second temporary index folder is normal during replicating on the followers. Will compare the logs between a successful restart and failed restart (by core lock) to see the difference. Waiting for a failed restart...

[solr-restart-log.txt](https://github.com/GSA/data.gov/files/10900121/solr-restart-log.txt)

**Comment by hkdctol** [comment]
Waiting for next occurrence

**Comment by FuhuXia** [comment]
The above PR detects core lock exception in the /var/solr/logs/solr.log and have solr restarted if found. This should resolve the issue.
