### ISSUE TITLE
Create a replacement page for open data community

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4139]
## User Story

In order to maintain an informational page about the federal open data community, the Data.gov team needs a replacement page for https://digital.gov/communities/open-data/

## Acceptance Criteria

- [ ] GIVEN a user goes to https://digital.gov/communities/open-data/
  THEN user is redirected to a page on data.gov with the equivalent information

## Background

Digital.gov is revamping its communities pages and asked that the open data community page be a link on data.gov. Once we create the page, Digital.gov will take care of redirect.

## Sketch

- [ ] Create a page in the new static site with the same information as in https://digital.gov/communities/open-data/ but exclude the link that reads Read More about the Open Data Working Group as it leads to old project open data link, and add at end of Who We Are section--For more information, contact datagov@gsa.gov

**Comment by hkdctol** [comment]
Digital.gov needs to be able to redirect to a new page by January 27

**Comment by btylerburton** [comment]
Text, for historical purposes:

# Open Data Community

## Join
To join, send an email to [listserv@listserv.gsa.gov](mailto:listserv@listserv.gsa.gov?subject=&body=subscribe%20open-data) with nothing in the subject, and body content containing “subscribe open-data.”

[Read more about the Open Data Working Group »](https://project-open-data.cio.gov/working-group/)

## Who we are
A community listserv and working group that unites 900 open data leads at federal agencies, data stewards, and all others in government interested in open data, enterprise data inventory, civic tech, and data-driven government issues.

Monthly implementation support meetings are held the first Tuesday at the U.S. General Services Administration (GSA) for Federal employees and contractors.

## Community Conduct
The Communities of Practice are hosted by digital.gov, a service of the Technology Transformation Services (TTS) within the General Services Administration (GSA). GSA is a federal agency subject to the Freedom of Information Act (FOIA) and must comply with requests for records made under FOIA. As a result, all communications made on this Communities of Practice LISTSERV are subject to release under FOIA.

When participating in this CoP, follow [Digital.gov Community Guidelines.](https://digital.gov/communities/manage-your-subscription/)

**Comment by hkdctol** [comment]
![Image](https://user-images.githubusercontent.com/3236989/213584969-76a18944-6357-46f0-926e-017383e2aa0d.png)

**Comment by hkdctol** [comment]
It's listed currently under https://resources.data.gov/categories/communities/ so all we need for now is a page on resources.data.gov with the same content--have it go to a resources page rather than digital.gov

**Comment by btylerburton** [comment]
Page is live at: https://resources.data.gov/open-data/

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data.gov/issues/4354
