### ISSUE TITLE
Use upstream versions of pysaml2 and ckanext-saml2 for MAX.gov authentication

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#414]
Currently, we're using forks of these two packages. This is not great since they receive no security updates. Let's try using the upstream versions of these packages and update the SAML metadata for MAX.gov.

- https://pypi.org/project/pysaml2/
- https://github.com/DataShades/ckanext-saml2

**Comment by mogul** [comment]
We're closing this one as it duplicates more complete efforts happening via #1416 and #1403 .
