### ISSUE TITLE
"Open With Plotly" Not Working

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4140]
As a datagov user, I expect documents which offer the "Open With plot.ly" extension to open in a valid plot.ly plot.

## How to reproduce

1. Navigate to a dataset with "Open With" functionality (ex. `.xls`)
2. Click "Open With" button
3. Choose "plot.ly"

## Expected behavior

I expect the dataset to be opened within a plot.ly window

<img width="774" alt="Screen Shot 2022-12-28 at 1 13 30 PM" src="https://user-images.githubusercontent.com/104455281/209855597-3e139d63-7ef2-429f-aa3d-818e1f484d52.png">

## Actual behavior

The tab is redirected to a plot.ly error page.

<img width="1552" alt="Screen Shot 2022-12-28 at 1 13 43 PM" src="https://user-images.githubusercontent.com/104455281/209855620-aa085d2c-1713-4cf5-99f6-bd8236eb2185.png">

## Sketch

- [ ] ~Follow fix recommendations on https://plotly.com/chart-studio-help/getting-data/~
- [ ] ~Modify `ckanext-datagovtheme/ckanext/datagovtheme/templates/package/snippets/resource_item.html` to include updated URL~
- [ ] ~Confirm redirect is fixed~
- [x] Burn it all!!  (Well, not all of it, but the html stuff)

**Comment by jbrown-xentity** [comment]
Remove the "Open With" whole button/dropdown, as both aren't working. Will revisit data visualization in another epic.

**Comment by nickumia-reisys** [comment]
Do we want to remove all of the "Open With" options?  I don't think any of them are working
- ArcGIS
- CartoDB
- Plotly

**Comment by hkdctol** [comment]
There's an ArcGIS option? I agree we should just remove them and think about other ways to enable visualizations

**Comment by nickumia-reisys** [comment]
Yup...  That sounds good, thanks @hkdctol!

![image](https://user-images.githubusercontent.com/85196563/227273094-f0add7ad-efe6-42cb-83bb-895ab15a6094.png)

**Comment by nickumia-reisys** [comment]
All "Open With" references have been successful removed.
