### ISSUE TITLE
Harvest info missing from dataset

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4147]
We have another loss of harvest object to a dataset: https://catalog.data.gov/dataset/geographic-names-server-gns.

This is an ongoing problem, we've clearly not solved this at the source. This is an NGDA (National Geospatial Data Asset), and is considered important to be complete for Geoplatform to have. See email forwarded to datagovhelp.

## How to reproduce

1. Go to https://catalog.data.gov/dataset/geographic-names-server-gns

## Expected behavior

Download metadata link exists

## Actual behavior

No metadata link

## Sketch

We've fixed some of these before, but we're not sure why this is failing. Either some loss of data in solr, or some database shenanigans that cause the link between dataset and harvest object to become lost.

**Comment by Jin-Sun-tts** [comment]
this is one of the dataset without harvest_object_id in this issue https://github.com/GSA/data.gov/issues/4079

We close this one as duplicate of issue #4079. 

However this dataset  has whole `extras` field empty, not like other ones missing just`havest_object_id`.

**Comment by FuhuXia** [comment]
Figured it out. It is missing harvest info because it was not created by harvester. This was created by the organization user manually on the UI, as shown in the newrelic log.
