### ISSUE TITLE
Inventory users upload geospatial metadata

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4150]
## User Story

In order to allow inventory users to use the [geospatial link in DCAT-US metadata process](https://github.com/GSA/ckanext-datajson/tree/main/ckanext/datajson/tests/datajson-samples#datajson-examples), GSA inventory admins want a field to specify the conformsTo field.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN GSA has an ISO compliant XML file that represents a dataset \
  AND the dataset is already represented on inventory \
  WHEN the ISO file is loaded \
  THEN a field exists to specify the conformsTo field \
  AND it is logged in the database appropriately.

## Background

https://github.com/GSA/ckanext-datajson/tree/main/ckanext/datajson/tests/datajson-samples#datajson-examples
This is for the GSA team IOLP dataset, which needs to make it onto Geoplatform.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

Not sure of all the details, but's here's a place to start:
 - location where data is loaded from react app to CKAN: https://github.com/GSA/ckanext-dcat_usmetadata/blob/main/metadata-app/src/components/MetadataForm/index.js#L346
 - Inventory should map `conformsTo` field in a resource into the DCAT-US file correctly, see mapping file for inventory [here](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/export_map/export.inventory.map.sample.json#L124-L126)

So it should be creating a new data entry field (text box), calling it conformsTo, using [resources.data.gov definition of the field](https://resources.data.gov/resources/dcat-us/#distribution-conformsTo) to provide context in some type of description/help way, and then making sure that information is bundled appropriately when the CKAN api is called. Ideally we would have some kind of end-to-end test, validating in cypress that we can utilize that field, and then validate it's there in the dcat-us exported file.

**Comment by btylerburton** [comment]
@jbrown-xentity Where is the best place in the form flow for this field? 

Based on the BDD spec, I'd guess it might fit in the Resource Upload page beneath the Media Type, to only display this field when the Media Type is XML. But I don't see where we confirm the resource is ISO compliant.

**Comment by jbrown-xentity** [comment]
It would go on the resource upload page, beneath media type is fine. As to when to display it, I would say always. While our use case is specific, the spec isn't; technically people could put other things in that conformsTo field that fit the metadata. And we don't need to do any confirmation other than what is in the spec: https://resources.data.gov/resources/dcat-us/#distribution-conformsTo. 

The only validation would be that it's a resolvable URL, but not even sure that's necessary in this case. However in some type of title or help text, I would point to the geospatial documentation: https://github.com/GSA/ckanext-datajson/tree/main/ckanext/datajson/tests/datajson-samples#datajson-examples. This will be helpful for GSA metadata creators in understanding what they should be entering there and why.
