### ISSUE TITLE
Cleanup sitemap files on generation

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#4151]
## User Story

In order to [ensure sitemap files are up to date], [datagov team] wants [clear out old sitemap files in the s3 bucket before regeneration].

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a nightly run of the sitemap action] \
  THEN [the sitemap bucket is cleared before new sitemap files are added] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

When new sitemap files are generated and uploaded to the s3 bucket they overwrite the existing file. If the number of files changes (cleaning dupes, etc.), on the next run the old files will remain. Ideally these files would be cleaned out beforehand.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

- Write a function to take the s3 bucket object and clear it [somewhere around here](https://github.com/GSA/ckanext-geodatagov/blob/main/ckanext/geodatagov/cli.py#L265) before the new files are uploaded

**Comment by jbrown-xentity** [comment]
@robert-bryson @dlennox24 this might be a fix we should implement with latest changes to how we create the sitemap...

**Comment by hkdctol** [comment]
This has been done through #4442
