### ISSUE TITLE
Metrics Dashboard Extension doesn't allow for CSV/JSON download

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4154]
As a datagov user, I'd expect to be able to download copies of the Metrics Dashboard reports in CSV and JSON when clicking the CSV & JSON buttons

## How to reproduce

1. Navigate to https://catalog.data.gov/report/metrics-dashboard
2. Click Download "CSV" or "JSON" buttons

## Expected behavior

I expect the browser to allow me to download a CSV or JSON formatted version of the data.

## Actual behavior

The browser reloads, but doesn't download the artifact.

NOTE: This works fine when user is logged in.

## Sketch

- [ ] Examine Cloudfront for the issue, as we get the expected result when not behind Cloudfront.
- [ ] Compare Cloudfront settings in Development, as this is not an issue there.

**Comment by btylerburton** [comment]
Looks like switching from FCS Cloudfront to our new implementation has fixed this issue. 

@hkdctol can you confirm by trying to click CSV / JSON here? https://catalog.data.gov/report/metrics-dashboard

**Comment by hkdctol** [comment]
@btylerburton confirm--could download both

**Comment by FuhuXia** [comment]
> Looks like switching from FCS Cloudfront to our new implementation has fixed this issue.
> 
Good to know it is fixed, but the new CloudFront keeps the same settings as the old one. It is surprising that the switch makes any different on the downloading behavior.

**Comment by btylerburton** [comment]
@FuhuXia I'd be curious if query string param forwarding was turned on in FCS. If it was, then there was something else blocking them being passed along that we weren't aware of.

https://stackoverflow.com/questions/54965779/how-to-configure-query-params-in-aws-cloudfront

**Comment by FuhuXia** [comment]
Right, `query string` was set to `None` at the old CF. It was a mistake.
