### ISSUE TITLE
Annual renew catalog.data.gov certificate

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4156]
[catalog.data.gov CloudFront](https://us-east-1.console.aws.amazon.com/cloudfront/v3/home?region=us-east-1#/distributions) has an AWS ACM issued [certificate](https://us-east-1.console.aws.amazon.com/acm/home?region=us-east-1#/certificates/list) installed that needs to be renewed annually. It is in our `ssb-production` AWS account.

### Next expiry date: 
15 February 2024

## Sketch
After completion, create another compliance ticket with the next January milestone.

**Comment by hkdctol** [comment]
Moving to product backlog as it is January 2024 milestone

**Comment by FuhuXia** [comment]
Received email from AWS states:
```
Your new certificate expires on Jan 15, 2025 at 23:59:59 UTC.
```
Verified with Chrome:

![image](https://github.com/GSA/data.gov/assets/1392461/246e80ce-3425-4954-8b6a-605881f0f773)
