### ISSUE TITLE
Do not allow user to register new account on catalog/inventory

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4160]
Anyone with a login.gov account can register themselves on catalog and inventory, and log into our ckan apps.

## How to reproduce

Change your email address in catalog dev db.  Then log in to catalog dev.

## Expected behavior

login unsuccessful.

## Actual behavior

login successful.
## Sketch

Given new user's email (.gov or .mil) address, Admin needs to add the user account manually first, then the user can login.

**Comment by btylerburton** [comment]
@jbrown-xentity and @FuhuXia I recall the conversation we had about this at planning, but I don't remember the result... Did we decide that this was only possible by removing the UI button, or can we restrict account creation in CKAN by other means?

**Comment by jbrown-xentity** [comment]
This needs to be restricted at the extension level, and will require some CKAN extension coding.

**Comment by FuhuXia** [comment]
CKAN has the following config:
`create_user_via_api = false`
`create_user_via_web = true `

we can add an equivalent one for saml2auth
`create_user_via_saml = true`

So the change need to happen in ckanext-saml2auth. After that, we can add user via cf task using cli command before the user can log in.
```
ckan user add {unique-user-name} email={user-at-gov-or-mil} password=$(cat /proc/sys/kernel/random/uuid)
```

**Comment by FuhuXia** [comment]
[PR](https://github.com/keitaroinc/ckanext-saml2auth/pull/85) in upstream saml2auth is created.

**Comment by FuhuXia** [comment]
More changes needed to complete the PR. Previously a SAML login will auto re-activate a deleted user. With this option enabled, it make sense to re-activate a deleted user only if we set the config that way.

**Comment by FuhuXia** [comment]
[PR](https://github.com/keitaroinc/ckanext-saml2auth/pull/85) updated and ready for upstream to review.

Once deployed, we need to do an initial clean, delete users that are not on the approval list.

**Comment by FuhuXia** [comment]
Let us not wait for upstream merge. We can use our fork for now and start the initial user cleaning process.

**Comment by FuhuXia** [comment]
changes are deployed. Existing users not listed in the user registration spreadsheet are deleted. User will not be able to auto create an account by simply logging in via SAML. New user has to added by running CF command, or later on using GH actions, by running cf command:
```
ckan user add firstname-lastname email=email@agency.gov password=$(cat /proc/sys/kernel/random/uuid)
```

**Comment by FuhuXia** [comment]
We should not allow org admin to add members. [A separate GH issue ](https://github.com/GSA/data.gov/issues/4286) is created for this.

**Comment by FuhuXia** [comment]
This is broken.  Valid Saml user can create an new account or re-activate an deleted account.

**Comment by FuhuXia** [comment]
Verified on cloud.gov development space. when a user is deleted or does not exist, the login failed with this message:


![image](https://github.com/GSA/data.gov/assets/1392461/e00da6ea-c6ac-49c0-b222-1e58109ff036)
