### ISSUE TITLE
disable new dataset creation on catalog

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4161]
All datasets on catalog are supposed to be harvested, not manually added. But we saw datasets created by user.

## How to reproduce

Log into dev and hit `/dataset/new`.

## Expected behavior

UI tells the user that the action is not allowed.

## Actual behavior

User can create dataset

## Sketch

- [ ] Remove "Add Dataset" button from template that generates the `dashboard/datasets` route
- [ ] Locate and remove any other instances of that button
- [ ] Block the route at the NGINX level, which should not affect tests within our GH Actions.

**Comment by btylerburton** [comment]
We have a lot of tests that are dependent on this route. There is also a button on the profile home when you login. I believe that we should think a bit more about this. Kicking it back.

**Comment by hkdctol** [comment]
Possibly get rid of the button on the template, wherever there is a add a dataset button, disable route on nginx

**Comment by btylerburton** [comment]
Updated sketch

**Comment by FuhuXia** [comment]
As of now, anything starts with /dataset/new is blocked as in `/dataset/new-hampshire-and-southern-maine-ocean-uses-atlas`.

**Comment by FuhuXia** [comment]
This is resolved.

**Comment by Jin-Sun-tts** [comment]
verified in the New Relic log, this issue is resolved. 

![Screenshot 2023-10-25 at 4 21 02 PM](https://github.com/GSA/data.gov/assets/104456257/400f4b3f-961e-4bca-bb09-ee3a9168f6d7)
