### ISSUE TITLE
Add CloudFront rules and alarms to the new account

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4162]
Catalog has switched to the new CF, but the WAF rules and cloudwatch alarms has not be added.

## How to reproduce

1. Description of steps to reproduce the issue.

## Expected behavior

The rules and alarms should be added to the new CF.

## Actual behavior

No rule and alarms except the rate-limit WAF rule.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
@FuhuXia Can you document that the rules and alarms are?  Since I don't have access to the old instance, I can't do a side by side comparison ☹️

**Comment by FuhuXia** [comment]
AWS WAF rules are documented [here](https://docs.google.com/document/d/1-Xa_bpUkn59Xz2HoI-96FcOonZxWV0POIzLsHI92Izg) in the team google drive.

**Comment by FuhuXia** [comment]
Flood, SQL injection and XSS scripting rules are migrated.

**Comment by FuhuXia** [comment]
Alarms created to monitor Cloudfront high 5xx rate, high 4xx rate and requestnumber.
