### ISSUE TITLE
NGDA marker on dataset search

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4165]
## User Story

In order to highlight valuable and important federal data, Census wants a National Geospatial Data Asset (NGDA) tag on datasets that are NGDA's.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a dataset is tagged with NGDA \
  WHEN a search with an NGDA dataset is performed \
  THEN a visual marker is seen on the dataset marking it as an NGDA

## Background

Came out of discussions with Census, noting that NGDA's are well maintained and considered of high value to most users.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

According to Census, FGDC best practices for NGDA's being marked are to include the tag "ngda", and no other datasets should include that tag. We would want to check with FGDC and validate our current datasets for the number of datasets tagged with "ngda". If we move forward, it would be fairly straightforward to highlight any dataset that has an "ngda" tag in the metadata.

**Comment by jbrown-xentity** [comment]
There is no already created icon, so we can just use some type of text... https://www.fgdc.gov/initiatives/ngda-management-plan

**Comment by FuhuXia** [comment]
For visual indicator, will this do?

![image](https://github.com/GSA/data.gov/assets/1392461/b55a62bf-d436-496b-80a6-05574e912358)

**Comment by btylerburton** [comment]
Is this a pattern we want to use with any other tags? Could there be more than one tag? 
Does it look better when it's following the title instead of preceding it?

**Comment by FuhuXia** [comment]
both options (marker before and after title) are presented in dev for preview.
![image](https://github.com/GSA/data.gov/assets/1392461/d89324ff-3b5e-4543-8b05-2f69794cecdd)

**Comment by FuhuXia** [comment]
Deployed to prod.

![image](https://github.com/GSA/data.gov/assets/1392461/ddb5184d-630f-4b18-81c3-34bdf14b9ee2)
