### ISSUE TITLE
CSDGM->ISO transformation not working

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4173]
Raised on issue with [this NTAD harvest source](https://catalog-prod-admin-datagov.app.cloud.gov/harvest/national-transportation-atlas-database-ntad-metadata/job/last).
Went into the logs, and found this beauty:
` 2023-01-25 03:52:24,251 ERROR [ckanext.geodatagov.harvesters.base] ISO Transform Failure: b'Stylesheet file /home/vcap/deps/1/python/lib/python3.8/site-packages/ckanext/geodatagov/harvesters/fgdcrse2iso19115-2.xslt does not exist\n'`

## How to reproduce

1. Re-harvest https://catalog-prod-admin-datagov.app.cloud.gov/harvest/national-transportation-atlas-database-ntad-metadata

## Expected behavior

Harvests the data (there may be some number of errors)

## Actual behavior

Failure to transform to ISO because of missing/misplaced file

## Sketch

We have automated tests for this, but because our tests and our production are in separate images/environments, my guess is something got lost in translation. Might need to debug and/or ssh onto dev to figure out what may be occurring. [This is the file](https://github.com/GSA/ckanext-geodatagov/blob/main/ckanext/geodatagov/harvesters/fgdcrse2iso19115-2.xslt), and can be tested [in that extension](https://github.com/GSA/ckanext-geodatagov/blob/main/Makefile#L19-L20) as well as an e2e test [here](https://github.com/GSA/catalog.data.gov/blob/main/e2e/cypress/integration/000_harvest.spec.js#L6).

The code to find the file is [here](https://github.com/GSA/ckanext-geodatagov/blob/main/ckanext/geodatagov/harvesters/base.py#L157-L160), either this code is wrong or the pypi bundle is messed up and the file isn't stored properly...

**Comment by FuhuXia** [comment]
This error is first seen on 2022-10-28T10:04:59.538Z in NewRelic log, max age of NewRelic log. So it has been there for a while.

**Comment by FuhuXia** [comment]
No error if ckanext-geodatagov is installed locally. So it looks like pypi packaging issue.

**Comment by btylerburton** [comment]
do we need to add the extension `xslt` here?
https://github.com/GSA/ckanext-geodatagov/blob/main/MANIFEST.in

**Comment by btylerburton** [comment]
ha. you beat me to it @FuhuXia

**Comment by jbrown-xentity** [comment]
Looks like we aren't doing any kind of testing of the CSDGM dataset that we import in our tests... We would want to add something [here](https://github.com/GSA/catalog.data.gov/blob/main/e2e/cypress/integration/000_harvest.spec.js#L137), validating something like the title in the [metadata](https://github.com/GSA/catalog.data.gov/blob/main/tests/harvest-sources/fgdc-waf/fgdc_metadata_1.xml)

**Comment by FuhuXia** [comment]
Issue fixed. Tests added for all harvest sources.

**Comment by nickumia-reisys** [comment]
Probably related to
- https://github.com/GSA/data.gov/issues/3959
