### ISSUE TITLE
CKAN-to-CKAN geospatial harvest

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#418]
The CKAN-to-CKAN harvester does not pull geospatial data in the harvest. To implement this, the CKAN-to-CKAN harvest will need to implement v3 of the CKAN API, and pull the full metadata from each object and load it correctly.

**Comment by jbrown-xentity** [comment]
Current DOI dev version working for full metadata harvest, first test in catalog-web-test environment failed. Next test to be run validating DB configuration and status is the same and API information is the same, final steps are to find solution and test on BSP dev.

**Comment by jbrown-xentity** [comment]
Full metadata link is not showing as the latest, in debug to find out why. The most recent harvest record has the correct metadata, and the dataset shows the most recent harvest object id, but the link to the full metadata is to the wrong full metadata (old copy).

**Comment by JJediny** [comment]
fixed by recent work
