### ISSUE TITLE
Fix Broken Links on Data.gov Static Sites

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4182]
A number of legacy static sites that have now been wired into Github actions are reporting failures on external links for a number of reasons.

## How to reproduce

- Examine the reports for the latest QA jobs
  - https://github.com/GSA/resources.data.gov/actions/runs/4045172365/jobs/6956286227
  - https://github.com/GSA/data-strategy/actions/runs/4045138761/jobs/6956208486
  - https://github.com/GSA/us-data-federation/actions/runs/4045187373/jobs/6956321516
  - https://github.com/GSA/sdg-indicators-usa/actions/runs/4045135024/jobs/6956200675

## Expected behavior

Links should resolve correctly.

## Actual behavior

Some links are outdated or not working.

## Sketch

- [ ] Update links wherever possible
  - [ ] 302's - redirects should be replaced with the updated URL
  - [ ] 404's - not found should be replaced with an alternative URL
  - [ ] 403's - forbidden should be updated to a non-restriced URL 
    - [ ] some are attributable to https://inventory.data.gov, should they be ignored?

**Comment by btylerburton** [comment]
@hkdctol created this triage ticket which we can use to update links as we are able.

**Comment by nickumia-reisys** [comment]
Just as another thing to fix, there is definitely something wrong with how it's testing some of the links too:
- https://www.congress.gov/bill/115th-congress/house-bill/4174/text is valid, but it reports as failed..
![image](https://user-images.githubusercontent.com/85196563/215795793-8f1caf45-e5df-4a62-92cb-57d21a1ef8ad.png)

**Comment by btylerburton** [comment]
But...

```
$ curl -I https://www.congress.gov/bill/115th-congress/house-bill/4174/text
----
HTTP/2 403 
date: Tue, 31 Jan 2023 20:52:45 GMT
```

**Comment by nickumia-reisys** [comment]
If you look at the content of that `curl`, it isn't a `curl`-friendly link.  I think the way that the QA checks broken links needs to change.

<details closed>
<summary>HTML Content</summary>
<br>
```html
<div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico" alt="Icon for www.congress.gov"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            www.congress.gov
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7925748ccde16daf')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            www.congress.gov needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/bill/115th-congress/house-bill/4174/text?__cf_chl_f_tk=_MRhbXIE4fXc2nPVOaC1JO.VYgKQXPlEb_YEzWskIW8-1675199648-0-gaNycGzNBuU" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="jn17bSTPRtwhJbTZrYA9ST_fZMQqiKsr17jGjtGs8Y0-1675199648-0-AZs3DrlWAnt1B-VsD_2qhfz1c3vD0HVKGTs36f1iEQ9ZjKv8PmxvP1IchuX1XppcNFhpKekdTzvKH0-pX_BgaaKbZXVfJy5AUXOk4O87qP9mw_zL-s9bcGV1M2MhOYyyNjCAWI1CDXT6w30zPvuUTjnrGe2dQZmRCSrM8-GtTi5U5zbsDFcXtI_TG57dPF9SIUD9fKvpsJw9n5dmMXBEuY1GGpTf01LXqkvS03d0ynfuiX3nMIa92ILKWH_YDcT6KOs1WaP_2uVZwmBT24BADKnOXEB9RUeiOWYXDr8GeqFur1w8xnimevaEvjsqw65EPLsAXhaW_1N24gioiLIL0MFLIyRKLJ_Tj-OhjFKqr4vRHBKbrlhG8ZX6JD7r6rYj7YuB0cG-w7z712sYdDdu1PG8yJO1N9GlmhLp_Pcd54VTZMhEwPbrzqvDnYknYCcHDVucdR0NgDVvujJWfe2cIUC6rfUuPEssvyOIA4PvleEp9bmazkF_ZTTyhb56sxWRCC18LsTzegx3EdMlwpLXlH5DFV5Y4de_AEsCZuyjuKCBZm4Lta8CWAf5IXic-ipYRQ">
            <input type="hidden" name="r" value="wZIARxGUQZPk90A9dJLp.dbSOMqb2kaaM2_ByQGDcE8-1675199648-0-AXBK1pvRu3vSR9xpHwWyID4qGWFUVifJRyK42CO1fq9uPfL0uOGAD9FKirf/gPOV0GQ2CM9fToI1dn+2T+N2Dhiw8tRLXzRorwlqSu/k6hLJbATneV8KzZoEwKpeAB95vhcdygbu1rxSyhdQ/k4i9peKx22oP+N7BXusyOf8B6WpqE9eKsl93JnwlSyOuKm/Ig2IIt/bS/TvIvclaslUE4ibyhTc1ffdwrkf3Bnys1dOSEu3daXESpZLb3cWoWgG7M6M0/p354okNGkbMS9UrmREeJ5xpVneuVynoEWFZD5hys4Ghwa42r79gxULZ7TxgHRLgPvsMEFbM8KXaas9rpSnuz4bIr8G5skZYvCrRZfNHcm9ii+57kn77nrDg+hchLAfT8XY+px8rNEyv9zJZ+dPCv8ScsFsKf0KsPaSRH1YNawi8u04djkyEjOS23yh+9QbkYfSy4Oo6hJzbhNzL3pevg9PvrZfhQ/FKOXmx3ZXi6G7ht8CUMYP3PawkSDIBUHlQjI+FVjEIfM5bPvo3gzrfAagHdBbyjAYhiMJX0RXqCxQ1ypdQ8MxKXKMApGE7owxDfSEQKwj2xIZVKmonYx/K8wqiuQ+HM1q20vomyT7WRxN9b88L6vpQo7wqy46jVOe7TldGH0H5k04QfvRZ9rZUDk47qwvK8F67skkWZow0jpFRhCY58FzYKyVP5gqY7l1kYvf3NZH322+spuswmUMnEZJ2xSMSGVhjXxZeeNglR7a2bDRYGcdzGzlhbx3Vn+gRLgs3+nxpkcwhgXI/og4wodjJXkQ7CBt4GHbM1x4QeWfdygXs3OR7RT75oBaLg3ekOk2ZFUyBJtrXtv8XCw5z70eEo/pa4lzvtmv/9iIIhWKntXzJjlQqzcw+RXkuS8tCk+Ar9kjULBAk/V2ueLrCfYlrOfSZczq/qu0SO9QzHf3g/9VVpn7vsjxGaPUaAQ5CVWVKn0M9vNf7MWJrWYMFm4Ec1//tGo5l29TQ9UegAoC5/7N/UiWI4edRK82JdyAVj9ykGZ11BxIm49GJBUCMfEI1QI9sAiI2uWPPmaaCMohWs1ft/yLJ6ESe7AoooTR6QerUz26KMV69OOIHxZqqMNd45hj0KOCPvlC/6aqA2WJm+luD+JCiiB2j/F34/IHrJvMctZWztu8Ltq/zokF1ebslYb8IXgB1/Z2oydZ7pdp7leAJMXXBvj3I5wEasAx30BGkOqfvsz1eqONnZTlpYSRY6Z6Pi+9M3l7kRQRuL9P4DXb/K773Pf+v0iF6YQ4j8Br/4qDzF1sdxs7iiBFHHgDTfGEISfiFYKQu7Lz6jrKgO+tHjwajTnpQss/xKYBDK3b5pn3/zo54LV/Zpy1UDvZclFCXN27HWHkeyYVJVDYyLN5S/0dRxJgWXlV/hszR9z9zImGEwNNf40H1jMCNgbAbm6522TZBKIwfhUwLjJXhdhrO8vm3V32Gd8DWs/6+c40ofnuTYMn0psvUo5cXMmTEjCuXdTN56fP5Q5MEd5VlILH3NZR/KLzv7aAOTIdFfQiyCQxYpC83M4hIqxfrTAyUQzwFr3bjekGRg7ovlFMiZAOppv2znUY3aoFzMNOfWnagWxrfZWa7MvzkKkn3z4NDtjU3c8Nn8GHrXQMh2IQnFLSBiwQ5XDurBcfj1E/BYnAxoOV9Jl4SuYtXpQDYoUDgaM5gscp3h1uNKS5">
        </form>
    </div>
</div>
```
</details>

**Comment by nickumia-reisys** [comment]
Just a small update from the most recent QA Scan on https://github.com/GSA/us-data-federation

 - [_site/us-data-federation-framework/index.html](https://github.com/GSA/us-data-federation/blob/main/framework.md)
    * [ ] External link https://govex.jhu.edu/author/anicklin/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Unsupported protocol
    * [ ] External link https://opencivicdata.readthedocs.io/en/latest/index.html failed: 404 No error
    * [ ] External link https://www.linkedin.com/in/markheadd failed: 999 No error
    * [ ] External link https://www.nist.gov/people/wo-l-chang failed: 404 No error
- [_site/voting-information-project/index.html](https://github.com/GSA/us-data-federation/blob/main/_initiatives/voting-information-project.md)
    * [ ] External link https://vip-specification.readthedocs.io/en/vip5/index.html failed: 404 No error

**Comment by crysacarter** [comment]
broken links updated

**Comment by hkdctol** [comment]
We've completed the broken link replacements.
