### ISSUE TITLE
Organizations without organization_type?

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4183]
## How to reproduce

1. Look at any of the following organizations:
    - [Commodity Futures Trading Commission](https://catalog.data.gov/organization/about/commodity-futures-trading-commission)
    - [Gulf Coast Ecosystem Restoration Council](https://catalog.data.gov/organization/about/gulf-coast-ecosystem-restoration-council)
    - [Lake County, Illinois](https://catalog.data.gov/organization/about/lake-county-illinois)
    - [Office of Management and Budget](https://catalog.data.gov/organization/about/office-of-management-and-budget)
    - [Pennsylvania Geospatial Data Clearinghouse](https://catalog.data.gov/organization/about/pennsylvania-geospatial-data-clearinghouse)
    - [Sandbox Organization](https://catalog.data.gov/organization/about/sandbox-organization)
    - [U.S. Department of Labor Bureau of Labor Statistics](https://catalog.data.gov/organization/about/u-s-department-of-labor-bureau-of-labor-statistics)

## Expected behavior

They should have an organization_type.
![image](https://user-images.githubusercontent.com/85196563/215791153-81891abc-8606-4582-a827-3937078cf1b6.png)

## Actual behavior

They do not have an organization_type.
![image](https://user-images.githubusercontent.com/85196563/215791250-c22bb478-7840-4c45-9cd0-232d1c298f7a.png)

## Sketch

Update with proper organization_type (if applicable?)

**Comment by hkdctol** [comment]
Reviewed organizations list; added organization types through UI on any that were missing them
