### ISSUE TITLE
Fix Harvesting Restarts

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4187]
catalog.data.gov@main
https://github.com/GSA/catalog.data.gov/blob/main/tools/restart_harvester.sh

## How to reproduce

1. Look at various logs from github action restarts

## Expected behavior

A mix of restarts and delayed restarts

## Actual behavior

`catalog-gather` always restarts
```bash
Running command: tools/restart_harvester.sh catalog-gather
Restarting instance 0 of process web of app catalog-gather in org gsa-datagov / space prod as ***...
OK

```

`catalog-fetch` never restarts
```bash
Running command: tools/restart_harvester.sh catalog-fetch
tools/restart_harvester.sh: line 17: [: !=: unary operator expected
Logs are too new!  Not going to restart
```

## Sketch

- [ ] Debug script and fix errors

P.S. This may also be causing weird harvesting issues (duplication and even https://github.com/GSA/data.gov/issues/4177) since `catalog-gather` is being interrupted every 15 mins?  Don't quote me on this...

**Comment by FuhuXia** [comment]
`catalog-gather` and `catalog-fetch` are restarted as designed, i.e., restarted on schedule when idle, skip a schedule if it is found busy.
