### ISSUE TITLE
Redis Queue overflow

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4188]
We have a harvest logs reporting that redis is out of memory, and the harvests are unable to be performed.

## How to reproduce

1. Check out https://github.com/GSA/catalog.data.gov/issues/760

## Expected behavior

Redis handles queue length gracefully

## Actual behavior

Redis throws up

## Sketch

This might be a 2 pronged approach, since having harvesters be offline for a long period isn't acceptable. Short term approach would be to either 1. Rename and re-create redis service or 2. Upgrade redis to have more memory.

To find the deeper problem, we have a theory: that [ckanext-archiver](https://github.com/ckan/ckanext-archiver) is running and adding items to be archived into the queue, but we aren't draining/handling this queue appropriately. Not sure what features ckanext-qa relies on (we know qa relies on archiver). But we aren't running [these commands](https://github.com/ckan/ckanext-archiver#using-archiver), and we have log statements showing that the archiver queue is being added to (` 2023-02-01 11:28:05,721 DEBUG [ckanext.archiver.plugin] Creating archiver task: near-mag-data-for-earth-1fe0d`). However, we should investigate further by spinning up a task that can examine redis using the cli (see some nice commands on the ckanext-archiver git readme).

**Comment by nickumia-reisys** [comment]
Created a new redis service with [`redis-3node-large`](https://cloud.gov/docs/services/aws-elasticache/#plans) plan.  The `large` has a 1.3GB memory limit vs. the non-large with a 512Mb memory limit.  It is the same 3-node count that we had before.

(This will probably be a temporary change until we figure out why the redis queue has exploded..)

**Comment by nickumia-reisys** [comment]
I was able to connect to the redis server and at least see that the memory did peak!  (Need to investigate more)

```bash
# Memory
used_memory:401919264
used_memory_human:383.30M
used_memory_peak:402962248
used_memory_peak_human:384.29M
used_memory_peak_perc:99.74%
```

**Comment by nickumia-reisys** [comment]
The full redis has a bunch of `rq:job:****` keys taking up `395444` entries.
The new redis (1-2 hours old) has `1474` entries with a few unique ones, but also a bunch of `rq:job:****`

The unique keys are:
- `"ckanext-harvest:datagov_catalog:harvest_object_id"`
- `"rq:queue:ckan:datagov_catalog:priority"`
- `"rq:queues"`

On both redis servers, there is only one "database" and an `n` number of keys.  I'm not well versed on what a database or key is and I don't know how this relates to queues, but I'll do more research.

With respect to this ticket, there are a bunch of keys that seem to be building without being cleared, so we'll need to figure out (1) how to prevent them from being added, (2) actually do the work to clear them or (3) just forcibly delete them.

**Comment by nickumia-reisys** [comment]
From the NR logs, we can see the OOM issue too:
```bash
2023-01-31 23:21:14,029 ERROR [ckan.model.modification] Command # 2 (HSET rq:job:3fb52cdc-913f-4238-a9a5-6b2155f5d4b3 status queued) of pipeline caused error: OOM command not allowed when used memory > 'maxmemory'.
2023-01-31 23:21:14,029 ERROR [ckan.model.modification] Command # 2 (HSET rq:job:3fb52cdc-913f-4238-a9a5-6b2155f5d4b3 status queued) of pipeline caused error: OOM command not allowed when used memory > 'maxmemory'.
redis.exceptions.ResponseError: Command # 2 (HSET rq:job:3fb52cdc-913f-4238-a9a5-6b2155f5d4b3 status queued) of pipeline caused error: OOM command not allowed when used memory > 'maxmemory'. 
redis.exceptions.ResponseError: Command # 2 (HSET rq:job:3fb52cdc-913f-4238-a9a5-6b2155f5d4b3 status queued) of pipeline caused error: OOM command not allowed when used memory > 'maxmemory'.
2023-01-31 23:24:15,359 ERROR [ckan.model.modification] Command # 3 (HMSET rq:job:12284698-03ec-4933-9827-48f441935305 created_at 2023-01-31T23:24:15.358046Z data x�k`��=��ىy�%z�E��e�Ez%����z�)�%���@���)~�SzT�,,�L
2023-01-31 23:24:15,359 ERROR [ckan.model.modification] Command # 3 (HMSET rq:job:12284698-03ec-4933-9827-48f441935305 created_at 2023-01-31T23:24:15.358046Z data x�k`��=��ىy�%z�E��e�Ez%����z�)�%���@���)~�SzT�,,�L
2023-01-31 23:24:14,767 ERROR [ckan.model.modification] Command # 3 (HMSET rq:job:ef8c6d80-4f80-43db-8b72-39f1dc0cc194 created_at 2023-01-31T23:24:14.762463Z data x�k`��=��ىy�%z�E��e�Ez%����z�)�%���@���)~�SzTL,-��
redis.exceptions.ResponseError: Command # 3 (HMSET rq:job:ef8c6d80-4f80-43db-8b72-39f1dc0cc194 created_at 2023-01-31T23:24:14.762463Z data x�k`��=��ىy�%z�E��e�Ez%����z�)�%���@���)~�SzTL,-��
2023-01-31 23:24:14,767 ERROR [ckan.model.modification] Command # 3 (HMSET rq:job:ef8c6d80-4f80-43db-8b72-39f1dc0cc194 created_at 2023-01-31T23:24:14.762463Z data x�k`��=��ىy�%z�E��e�Ez%����z�)�%���@���)~�SzTL,-��
redis.exceptions.ResponseError: Command # 3 (HMSET rq:job:12284698-03ec-4933-9827-48f441935305 created_at 2023-01-31T23:24:15.358046Z data x�k`��=��ىy�%z�E��e�Ez%����z�)�%���@���)~�SzT�,,�L
```

**Comment by nickumia-reisys** [comment]
Harvesting has been sporadically had issues with the queue all yesterday:
![image](https://user-images.githubusercontent.com/85196563/216165742-a2a72c92-1f17-449a-ae67-abc17f873848.png)

**Comment by nickumia-reisys** [comment]
The new redis service still only has `1674` keys, so it's not growing dramatically day-by-day, but it could definitely balloon over time depending on the number of harvests and, by extension, archiving (or other redis-based) events.

**Comment by nickumia-reisys** [comment]
Not sure what to make of this, but considering that all of the `rq:job:****` keys are associated with the archiver, so at least @jbrown-xentity's theory is validated:
```bash
localhost:8001> hgetall "rq:job:eff2e511-4a32-42c6-963a-194609b35f5d"
 1) "enqueued_at"
 2) "2023-02-01T19:21:42.731923Z"
 3) "status"
 4) "queued"
 5) "origin"
 6) "ckan:datagov_catalog:priority"
 7) "description"
 8) "ckanext.archiver.tasks.update_package('646731ad-ff53-47c6-b185-e8fa2c4cce79')"
 9) "meta"
10) "\x80\x05\x95\r\x00\x00\x00\x00\x00\x00\x00}\x94\x8c\x05title\x94Ns."
11) "created_at"
12) "2023-02-01T19:21:42.731803Z"
13) "timeout"
14) "180"
15) "data"
16) "x\x9ck`\x9d\x1a\xc9\x00\x01\x1a=\xaa\xc9\xd9\x89y\xa9\x15%z\x89E\xc9\x19\x99e\xa9Ez%\x89\xc5\xd9\xc5z\xa5\x05)\x89%\xa9\xf1\x05\x89@\xf9\xf4\xd4)~\xb1SzT\xccL\xcc\xcc\x8d\r\x13St\xd3\xd2L\x8duM\xcc\x93\xcdt\x93\x0c-LuS-\xd2\x12\x8d\x92M\x92\x93S\xcd-\xa7$\xd6N)\x99\xa2\a\x00.\xc2 `"
```

**Comment by nickumia-reisys** [comment]
The deliberate archiving queue is empty on the new service (as well as the old service).
```bash
localhost:8001> LLEN bulk
(integer) 0
localhost:8001> LINDEX bulk 0
(nil)
localhost:8001>
```

But the `priority` queue is taking up all of the space on the old instance:
```bash
localhost:8000> LLEN rq:queue:ckan:datagov_catalog:priority
(integer) 395441
localhost:8000> LINDEX rq:queue:ckan:datagov_catalog:priority 0
"39931038-9b15-4c37-9edc-3e7c3b80b734"
localhost:8000>
```

It is also taking up the most space on the new service as well...
```bash
localhost:8001> LLEN rq:queue:ckan:datagov_catalog:priority
(integer) 1672
localhost:8001> LINDEX rq:queue:ckan:datagov_catalog:priority 0
"3fe35325-5c3e-4ba7-b1ea-b5c8bfb9b1b7"
localhost:8001>
```

We could run the `redis-cli -n 1 DEL bulk` command that is referenced in the `ckanext-archiver` README (found by James) and obviously replace the `bulk` queue with the `rq:queue:ckan:datagov_catalog:priority` queue.  Since it doesn't happen often and we don't particularly care about the archiving, we could run this command.  Otherwise, we can figure out if archiving has any benefits and actually make sure the queue is worked on.

**Comment by nickumia-reisys** [comment]
Final steps:
- [x] Disable Archiver and QA Extensions
- [x] ~Run `redis-cli -n 1 DEL rq:queue:ckan:datagov_catalog:priority` to clear the queue (but ssh needs to be re-enabled on `prod`~
- [x] Downgrade redis plan from `redis-3node-large` to `redis-3node` to go back to our original plan.

(Harvesting was verified complete/stopped.  The redis downgrade is destructive, so no need to delete the archiver queue.)

**Comment by nickumia-reisys** [comment]
The next steps are to,
- https://github.com/GSA/data.gov/issues/3986

**Comment by nickumia-reisys** [comment]
Nice StackOverflow answer about [different redis types](https://stackoverflow.com/a/44444966).
