### ISSUE TITLE
Restarts are deploying catalog-proxy?

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4193]
## How to reproduce

1. Look at the failed (or passing?) restarts
    - https://github.com/GSA/catalog.data.gov/actions/runs/4104254265/jobs/7079487131
    - https://github.com/GSA/catalog.data.gov/actions/runs/4103557686/jobs/7077905736

## Expected behavior

All app are restarted.

## Actual behavior

![image](https://user-images.githubusercontent.com/85196563/216995821-08cb20c2-6a96-4900-bb5a-96f96b0d0be6.png)

## Sketch

- [ ] Investigate the templates
- [ ] Figure out the rest accordingly

**Comment by robert-bryson** [comment]
The restarts are still happening: https://github.com/GSA/catalog.data.gov/actions/runs/4106387800/jobs/7084546748#step:4:85

Fix [here](https://github.com/GSA/data.gov/pull/4195).

**Comment by robert-bryson** [comment]
Fix for failing jobs template missing: https://github.com/GSA/data.gov/pull/4196/files

**Comment by robert-bryson** [comment]
Well, this one happened to time out but proof of restarts being called restarts and not deploys: 

![Image](https://user-images.githubusercontent.com/91547795/217056549-9badee59-7f62-48b9-b0b8-1218d76b70d8.png)
