### ISSUE TITLE
Install New Relic Redis monitoring agent

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#420]
Create/extend New Relic playbook to enable: 
https://github.com/newrelic/nri-redis

**Comment by adborden** [comment]
Redis hasn't really ever been a problem. I would be interested in monitoring that kept an eye on the queue sizes. CKAN is pretty bad at cleaning up after itself, so I imagine the queues will fill up eventually. That said, I would rather just deal with that when it happens. It's not going to be a major outage, just clearing the queue and pending harvest jobs. That would be a good time to see what can be improved for redis.
