### ISSUE TITLE
Assess ckanext-spatial changes

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4207]
Reference Github Hashes
- https://github.com/ckan/ckanext-spatial.git@17d5a341cf8f40b35b25df91a18ce72c31195ba3
- https://github.com/ckan/ckanext-spatial.git@9d9bc236952ab055f59d392304aad148fd945e75

## How to reproduce

1. Update ckanext-spatial on catalog
    - https://github.com/GSA/catalog.data.gov/pull/776

## Expected behavior

All tests are passing.

## Actual behavior

Failed tests,
![image](https://user-images.githubusercontent.com/85196563/217898431-7e6345c4-b15b-4940-9f08-8071138af1c0.png)

## Sketch

- [ ] Read change logs/release notes.
- [ ] Figure out what the new dependency, `geojson`, is doing.
- [ ] Figure out how the tests and (probably more specifically) harvesting is effected.

**Comment by nickumia-reisys** [comment]
Github Action Run:
- https://github.com/GSA/catalog.data.gov/actions/runs/4136065599/jobs/7149389433#step:4:991

**Comment by FuhuXia** [comment]
This issue has been resolved. Tests are passing. We are on the latest ckanext-spatial release.
