### ISSUE TITLE
CKAN 2.9.8 patch

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4208]
## User Story

In order to utilized latest CKAN patches, data.gov admins want CKAN updated to 2.9.8.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN catalog is upgraded \
  WHEN I go to https://catalog.data.gov/api/action/status_show \
  THEN ckan version shows 2.9.8

## Background

https://github.com/GSA/catalog.data.gov/blob/main/ckan/requirements.txt#L11
https://github.com/GSA/data.gov/issues/4113
See email on CKAN mailing list:
```
Hi all,

If all goes according to plan, next Wednesday 15th February around 13:00 UTC (14:00 CET, 08:00 EST) we will be releasing the next stable version of CKAN, 2.10, as well as patch releases for the 2.9 line (2.9.8).

Users are strongly encouraged to always run on the latest patch release for their version, as these include important security and
stability fixes. The latest patch release is the only one supported by the CKAN team (patch releases don't contain backwards incompatible changes).

More information about CKAN releases can be found here:

http://docs.ckan.org/en/latest/maintaining/upgrading/index.html#ckan-releases

Best,

Adrià 
```

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

First just try upgrading in catalog, and running `make clean build up`. If that works, run tests. If not, debug issues.

**Comment by nickumia-reisys** [comment]
This had a bit of a scare with datagovtheme styles on catalog [not loading properly](https://gsa-tts.slack.com/archives/C2N85536E/p1676656879850649); but it is not a major problem.  It seems like, specifically between ckan version updates, the webassets need to be regenerated and the cache everywhere is no longer valid.  Any styles that are cached on local machines who had already loaded need to wait (the ~5 minutes) for it to expire before things load properly.  We haven't seen this occur before this upgrade, but just noting for future reference.
