### ISSUE TITLE
Static Site QA

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4213]
## User Story

In order to release 11ty data.gov main site, data.gov admins want a sign off of all developers that the quality is adequate for release.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN 11ty site is built on federalist \
  WHEN the data.gov admin reviews the site (layout, cosmetic, functionality) \
  THEN the site is approved for launch

## Background

Final ticket before https://github.com/GSA/data.gov/issues/4141

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

Ideally we should have a sign off for each person, on each aspect:

| Team Member | Cosmetic | Functionality |
| ---------------- | ---------- | -------------- |
| James Brown   | <ul><li>[X] </li></ul> | <ul><li>[X] </li></ul> |
| Hyon Kim        | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> |
| Tyler Burton     | <ul><li>[X] </li></ul> | <ul><li>[X] </li></ul> |
| Jin Sun             | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> |
| Fuhu Xia          | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> |
| Robert Bryson   | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> |
| Nick Kumia      | <ul><li>[x] (binding) </li></ul> | <ul><li>[x] (non-binding)</li></ul> |

**Comment by hkdctol** [comment]
@btylerburton since we updated explainer text on organization page, can you swap an updated screenshot in the appropriate section of the User Guide?

![Image](https://user-images.githubusercontent.com/3236989/223220270-9dfbce3f-e673-468a-8763-1eba1b2a2edd.png)

**Comment by hkdctol** [comment]
Could we change to "Datasets by Organization" -- right now it's vague

![Image](https://user-images.githubusercontent.com/3236989/223284916-68bd4522-741a-43f4-9d23-7373c93cc663.png)

**Comment by hkdctol** [comment]
On the Dataset Age, could we have hover text that says "Datasets grouped by when they were added to the catalog" (assuming that's correct!)

![Image](https://user-images.githubusercontent.com/3236989/223285366-24c555e1-34bc-4a76-8ffa-99d20e0ebace.png)

**Comment by btylerburton** [comment]
"Dataset Age" is "Datasets grouped by when metadata was last modified". How's that sound for the tooltip @hkdctol?
https://github.com/GSA/data.gov/issues/4213#issuecomment-1457252256

**Comment by btylerburton** [comment]
All comments addressed in: https://github.com/GSA/datagov-11ty/pull/123

**Comment by jbrown-xentity** [comment]
Just to make sure: the `Open Government` and `Contact` tab/link redirects don't work in the current preview, but the pages exist. It just takes you to the wrong link, it doubles up on part of the URL like `/site/gsa/datagov-11ty/site/gsa/datagov-11ty/open-gov`. Any idea why that may be happening, and if it will require a fix before go-live?

Also it's a very clean look, I like it, but I can't help but notice there aren't any links that are "discoverable" from the main page. There's no categorization, no dropdowns, no searching. We'll have to rely on people getting to most specific pages (other than contact, open government, and user guide) via google or some other search engine. With that in mind, we might need to generate a sitemap in the future so that google can index us well, as some pages google won't just "find".

![Image](https://user-images.githubusercontent.com/26980513/225156409-86813909-277e-45a0-a223-f2350995034b.png)

**Comment by btylerburton** [comment]
new PR fixes the above: https://github.com/GSA/datagov-11ty/pull/128

**Comment by robert-bryson** [comment]
Overall looks great! Great work! 

I doubt it is an issue, but I did notice that the open data site CSV url leaks the bucket: 

![Image](https://user-images.githubusercontent.com/91547795/225699025-dc83a043-48e9-4adf-b364-e0a7f639afc7.png)

**Comment by nickumia-reisys** [comment]
Good first iteration 🎆 

For future work, It would be nice to have the "you are now leaving the Data.gov website" for external links.

**Comment by FuhuXia** [comment]
The dataset age graph looks a lot different than a month ago. Not sure which one is more representative. We can let it run for a few sprints and might need to adjust the scale (a month, half year, 1 year, 1year +) to  make a graph more reasonable. It does not help to have a bar so tiny that it is not clickable.

![image](https://user-images.githubusercontent.com/1392461/225738019-ea8b6742-943f-47e9-a2e3-03cea591fa0e.png)
![image](https://user-images.githubusercontent.com/1392461/217093809-6e38227b-01c5-4c1e-a269-a3560e96f1b3.png)

**Comment by nickumia-reisys** [comment]
I disagree with "not showing the 1 week because it is too small", but if it helps the "clickability", we can convert the total number into a percentage (i.e. 1% updated in the last week, 10% in the last month).  I think it's important to show that our datasets are not updated super frequently.

**Comment by btylerburton** [comment]
Site went live 03.23.23
