### ISSUE TITLE
[4 day Spike] Harvesting pipeline in cloud.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4215]
## Purpose

We want to utilize cloud.gov as a harvester engine, but we're not sure how to do that.

Given above uncertainty, creating a "hello ... world" pipeline is needed to provide factual knowledge on future steps.

4 days of effort has been allocated and once compete, findings will be demonstrated and specific future actions will be decided.

### Acceptance Criteria

[ACs should be clearly demo-able/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a queue pipeline has been created
  WHEN 4 days expires\
  THEN the pipeline is shown via 0.5 hour presentation
  AND a recommendation is made on this approach for catalog harvesting

### Background

[Harvesting 2.0 proposed architecture](https://docs.google.com/document/d/1XzfTrPxu-asJ_55GoeZ2UOJsie9CuCegStS28BAL_40/edit#heading=h.434psjuabm80)
- Contending with https://github.com/GSA/data.gov/issues/4216

### Sketch

Pre-work assumptions:
- This will utilize [celery](https://docs.celeryq.dev/en/stable/getting-started/first-steps-with-celery.html) queues with a redis backend. Due to cost constraints, will probably want to do this in your cloud.gov sandbox account, and not in the main data.gov account. Initial development may be quicker and easier with just local development.
- ~A new repository is created, specifically for this work (which may be thrown away if we decide later to abandon this approach)~. https://github.com/GSA/datagov-harvester-test-cloudgov
- Don't focus on automated deployment, use basic deployment procedures.
If cloud.gov deployment is a problem, utilize normal python local use-case and implement s3 and redis via docker images. See catalog or inventory repo's for examples.

As time allows, this is what would be ideal to see:
- Utilizes celery queue
- Has an extract job that kicks off and posts to a queue (could be just "hello world", or pull data from catalog; something like https://catalog.data.gov/harvest/object/a6a9f0b0-66aa-439e-9716-6c76731604fa)
- Receives from queue and process the message (edits, etc)
- Saves at the front and backend to s3 (using boto3?)
- Chain multiple queues together (extract, validation, transform, load), these don't have to actually do anything.
- The stack deployed in cloud.gov (s3, redis, and python app) (may need to be sandbox, as datagov account is low on memory space)

**Comment by Jin-Sun-tts** [comment]
Create celery tasks with redis as backend

Create flask UI to take some input and run the process (extract, validate, transform, load) with the celery tasks. 

At the extract and load step,  update file to s3 bucket.


Then deploy to cloud.gov, first tried on sandbox, but looks like there are some restriction, then deployed to development space with ssl setup for redis.  It works as expected. ` https://etl-test.app.cloud.gov`

See the test codes at `https://github.com/GSA/datagov-harvester-test-cloudgov/tree/main
`

**Comment by hkdctol** [comment]
Let's create some documentation on this before moving to done.

**Comment by Jin-Sun-tts** [comment]
Here is the [documentation](https://docs.google.com/document/d/1pKdy4kqWhQAR4VgsiB9nhHkVu1rPc0Hre5JjqAOVmU4), please feel free to add/modify it. Thanks!
