### ISSUE TITLE
Community/Topic Explanation text

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4226]
## User Story

In order to have useful endpoints for data.gov communities, data.gov admins want text explaining why they no longer exist.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a text explaining community removal is written and exists on the new site \
  WHEN a user goes to one of the [redirected community domains](https://github.com/GSA/datagov-website/blob/main/redirects/nginx.conf#L18-L79) \
  THEN the user is redirected successfully

## Background

Community removal was done partly for technical reasons, and partly due to loss of community leader involvement.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

- [ ] Write text similar to new site announcement
- [ ] Create draft PR for redirect changes to blog URL
- [ ] Merge PR post-live 11ty release

**Comment by hkdctol** [comment]
I can draft explanation text, but we did carry over the topics that were requested, climate and maritime, right--we just don't have navigation to it--but the existing links should redirect?

**Comment by hkdctol** [comment]
Does this work for https://docs.google.com/document/d/1NjBPPdIVrvq-i3-nd4c1DjWYFrweXk0aubxBpNjgZd4/edit?usp=sharing explainer text?

**Comment by btylerburton** [comment]
Fixed in https://github.com/GSA/datagov-11ty/pull/124/files
