### ISSUE TITLE
New Relic: Update Browser Agent 

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4229]
## User Story

In order to ensure accurate monitoring, the DatagovTeam Browser Agent on New Relic should be updated. 

From the email:

> You’re receiving this email because you’re running an unsupported version (any version prior to v1198) of our browser monitoring agent. Beginning June 30th, 2023, New Relic will discontinue compatibility for all browser monitoring agent versions prior to v1198. As a result, if you do not upgrade your browser agent by that date, you may experience partial browser data drop due to New Relic services rejecting some payloads entirely.
> 
> Mitigation measures are currently in place to prevent this rejection for accounts with older versions of the browser agent, but these measures are temporary. To prevent rejection of your browser data to New Relic, you will need to upgrade your browser agent to the latest supported version no later than June 30th, 2023. Please follow the [steps for upgrading your browser agent](https://get.newrelic.com/MzQxLVhLUC0zMTAAAAGKVthMn3RZCjiNM-zIXMmZG996mRapJIJWn4e312z0cm-WQzsQfcmDeXVu34KAAQN3EQNkYQc=) based on your installation type.
> 
> Again, this upgrade must be completed by June 30th, 2023, to avoid interruption to your services.
> 
> [Update the browser agent | New Relic Documentation](https://get.newrelic.com/MzQxLVhLUC0zMTAAAAGKVthMn3RZCjiNM-zIXMmZG996mRapJIJWn4e312z0cm-WQzsQfcmDeXVu34KAAQN3EQNkYQc=)
> [Browser agent v1198 | New Relic Documentation](https://get.newrelic.com/MzQxLVhLUC0zMTAAAAGKVthMn-G09cuDbLcbB5otIImNj93RZC9r0XUkZGT6K3JF0drBnU_0Zwg7O6Sxvw3ugwNPIVs=)
> 

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by robert-bryson** [comment]
This ticket is a no-op and will close.

The long answer is that New Relic APM ships with this browser agent that gets (from what I can tell) kicked off by the `server_start.sh` on allegedly a number of our apps. The update process described above is not applicable in our case as nowhere are we providing the hardcoded js in the `<head>` of our pages. We do not set a specific version of the New Relic Browser Agent, but rather set in our [requirements.txt](https://github.com/GSA/catalog.data.gov/blob/main/ckan/requirements.txt#L63) (`newrelic==9.0.0` currently). I believe the New Relic python agent magically grabs the current browser agent ([current `v1.242.0`](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.242.0/)) and inspects the app to provide data back to New Relic. From what I can tell, the python agent grabs new versions as they are available as the apps that are providing data ([`catalog-web-prod`](https://one.newrelic.com/nr1-core/browser-entity-preview/browser-application-preview/MTYwMTM2N3xCUk9XU0VSfEFQUExJQ0FUSU9OfDExMzQyNTc3OTg?account=1601367&duration=1800000&filters=%28domain%3D%27BROWSER%27%20AND%20type%3D%27APPLICATION%27%29&state=e8f9dd50-4eea-8e90-11bc-42a8ca76b3cd) and [`inventory-prod`](https://one.newrelic.com/nr1-core/browser-entity-preview/browser-application-preview/MTYwMTM2N3xCUk9XU0VSfEFQUExJQ0FUSU9OfDExMzQyNTg3NjQ?account=1601367&duration=1800000&filters=%28domain%20IN%20%28%27BROWSER%27%2C%20%27BROWSER%27%29%20AND%20type%20IN%20%28%27APPLICATION%27%2C%20%27MICRO_FRONTEND%27%29%29&state=e8f9dd50-4eea-8e90-11bc-42a8ca76b3cd)) both report a Max Agent Version as `1242`. 

That all being said, there are a number of old apps that probably should be cleaned up. They are not running, obviously, but in the New Relic ui they do report various older versions of the browser agent. 

I have already cleaned up:
	- wordpress-web1p
	- wordpress-web2p
	- crm-2p
	- catalog-web1p
	- catalog-web2p
	- catalog-next

Currently there remain:
<img width="366" alt="image" src="https://github.com/GSA/data.gov/assets/91547795/805c579a-82fb-4f2f-8a4e-50a81f88c493">

We probably want to remove all the apps save the ones reporting data. 

Spent some more time on this and also paired with James to make sure my understanding was correct.

**Comment by nickumia-reisys** [comment]
The other short answer is that we need to ensure we're using the newest possible version of the `newrelic` pypi package, right?

**Comment by robert-bryson** [comment]
> The other short answer is that we need to ensure we're using the newest possible version of the `newrelic` pypi package, right?

Yes, we should be doing that. The email in the story says "(any version prior to v1198)" which our current version surpasses. Going forward, the New Relic python agent should update as we update our dependencies normally as [it is not pinned in the `requirements.in`](https://github.com/GSA/catalog.data.gov/blob/main/ckan/requirements.in#L112).
