### ISSUE TITLE
[Snyk] OWSLib Vulnerability

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4231]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 03/09/2023
**Severity:** High
**Due date:** 04/09/2023

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

From our automated snyk scans, the above vulnerability in the `owslib` package was highlighted. After an investigation of our [Github Action Tests](https://github.com/GSA/catalog.data.gov/actions/runs/4375304207/jobs/7656363202), it seems like it is breaking the CSW Harvest Jobs.
- https://github.com/GSA/catalog.data.gov/pull/861
- https://security.snyk.io/vuln/SNYK-PYTHON-OWSLIB-3356626

**Comment by hkdctol** [comment]
For one thing--check on the need of the existing CSW harvest sources. Perhaps not use the CSW harvest source at all but get single harvest record.

**Comment by hkdctol** [comment]
We might fix on our own. Also XML from trusted sources.

**Comment by nickumia-reisys** [comment]
@btylerburton It seems like the CSW Harvest source is failing on main with the older version of `owslib` now... so... it might be unrelated now?
- https://github.com/GSA/catalog.data.gov/pull/918

https://user-images.githubusercontent.com/85196563/230918303-68a74b35-fefd-48cb-9e02-8bf46c18e59e.mp4

**Comment by btylerburton** [comment]
The upgrades to `owslib` broke the CSW service in deep and unidentifiable ways. After some consideration, since CSW is deprecated as a data source, the team has decided to remove support for the CSW format. Closing this.

**Comment by btylerburton** [comment]
Leaving open as the vulnerability will still need to be addressed. Moving to blocked until we do that.

**Comment by btylerburton** [comment]
Fixed in https://github.com/GSA/catalog.data.gov/pull/921

**Comment by nickumia-reisys** [comment]
For full transparency, I believe this is the starting point for why/when/how we stopped supporting CSW Harvesting.
