### ISSUE TITLE
Support user/password authentication (non-saml/max.gov) in test environment 

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#424]
- [ ] Remove redirect in apache2 site from readable hosts to write hosts (there is no distinction?)
- [ ] Remove saml plugin from production.ini
- [ ] Update who.ini with user/password config
- [ ] Install alternate version of repoze.who (`/usr/lib/ckan/bin/pip install -U repoze.who==2.0 Paste==1.7.5.1`)
- [ ] production.ini who session must be configured with `who.secure = false` or the load balancer must be configured with HTTPS

**Comment by jbrown-xentity** [comment]
@adborden some of those look familiar, looks like a good place to start!

**Comment by adborden** [comment]
@JJediny suggested we do a "hotfix" playbook to be run after the ckan playbooks that would perform the above tasks to configure the host with native user/password authentication.
