### ISSUE TITLE
Rebuild data.gov 11ty site nightly on schedule

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4244]
## User Story

In order to have an updated homepage, datagovteam wants to update the static site nightly.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

None 

## Sketch

- [ ] Create scheduled job to build and publish 11ty pages build on `main` branch.

**Comment by jbrown-xentity** [comment]
https://cloud.gov/pages/documentation/how-builds-work/#scheduling-nightly-builds

**Comment by nickumia-reisys** [comment]
I think this is done.  I saved the setting in the UI.  If someone else wants to check it, we'll see if the "metadata updated" time changes tomorrow.

**Comment by nickumia-reisys** [comment]
It kicked off a build immediately.  I'll monitor to see if it does this tomorrow as well



![Image](https://user-images.githubusercontent.com/85196563/226419955-7dfb43b7-b2bd-44f2-bb46-4c9c264c4edf.png)

**Comment by nickumia-reisys** [comment]
Yup, it's working 🥲 

![image](https://user-images.githubusercontent.com/85196563/226627720-c395f4ec-837a-4b42-9cb0-648803ec5e28.png)
