### ISSUE TITLE
Add GSA Star Mark to new Data.gov home page

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4247]
## User Story

In order to meet GSA requirements, Data.gov team needs to add GSA star mark to footer of the new home page.

## Acceptance Criteria

- [ ] GIVEN user goes to new Data.gov home page and goes to footer\
  THEN GSA star mark and "An official website of the GSA’s Technology Transformation Services" is seen

## Sketch

- [x] See example at https://www.performance.gov/
- [x] Add star mark on left of existing section, and have text read "An official website of the GSA's Technology Transformation Services" and for TTS link to https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services
- [x] Make the same addition to footer for catalog pages
<img width="489" alt="Screen Shot 2023-03-21 at 6 23 05 PM" src="https://user-images.githubusercontent.com/3236989/226755604-df095282-8bae-433e-8f5b-52a2b944ec71.png">

**Comment by nickumia-reisys** [comment]
As a reference to those who need to do similar work in the future,
- I did not know the structure of the html components or class names that was needed to implement this correctly.
  - There may have been articles or documentation that could be referenced.
  - The way I did it though was by inspecting the website of performance.gov and borrowing the names and structure from there.
- performance.gov was also hosting their own version of the gsa starmark, so I copied their version to our S3 bucket for images and then referenced our "local" copy.  Whether this is the correct acquisition of resources, I don't know.
- To implement this in catalog right now, it's a straight copy from the `datagov-11ty/_includes/identifier.html` to `ckanext-datagovtheme/ckanext/datagovtheme/templates/snippets/identifier.html`  minus the svgs which needed the shortCode function to be replaced by the actual svg data.
  - It could be copied from one of the output files from `_site/` but that seemed like more trouble than it was worth.

Overall, it's not too difficult.  But as we don't have well-defined processes for this right now, it just takes a bit of finagling.
