### ISSUE TITLE
Make navigation on catalog.data.gov pages consistent with new home page

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4248]
## User Story

In order to maintain consistency across Data.gov, catalog.data.gov page should be consistent with that on new home page.

## Acceptance Criteria

- [x] GIVEN user goes from new Data.gov home page to catalog.data.gov pages
  THEN there is consistent navigation on top of both pages

## Sketch

- [x] Change catalog.data.gov header to have navigation consistent with new home page
- [x] Delete the second search box that's at upper right of catalog pages
<img width="1490" alt="Screen Shot 2023-03-21 at 6 28 03 PM" src="https://user-images.githubusercontent.com/3236989/226756743-8df44169-3d14-43f3-aa22-386374843be0.png">
<img width="1456" alt="Screen Shot 2023-03-21 at 6 28 15 PM" src="https://user-images.githubusercontent.com/3236989/226756756-556d9830-69df-417f-9f76-fa2b7bed9c68.png">

**Comment by FuhuXia** [comment]
End result will be like this:

![Untitled1](https://user-images.githubusercontent.com/1392461/229570602-25989fe2-1ac7-43d0-bc70-f1f2473d4389.png)

**Comment by FuhuXia** [comment]
The new look: 
![Screenshot from 2023-04-10 12-48-44](https://user-images.githubusercontent.com/1392461/230950791-99a1edf4-eea4-4e80-bc59-82919a08544d.png)

**Comment by FuhuXia** [comment]
It is deployed to catalog.data.gov.
