### ISSUE TITLE
ckanext-report cache upgrade

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4254]
## User Story

In order to avoid a complicate report taking too long to generate or even timing out when user is visiting the report, data.gov admins want a way to always serve cached data to report requests.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a configuration flag is set \
  WHEN a report is requested from the web UI \
  THEN the report is always served from the cached data.
- [ ] GIVEN a report is out-dated  \
  WHEN a command is issued via CLI or API call \
  THEN the report is showing the latest data.

## Background

https://github.com/GSA/data.gov/issues/4116
https://github.com/GSA/data.gov/issues/4018

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

We'll plan to fork ckanext-report, make the changes, and then try to push upstream.

**Comment by FuhuXia** [comment]
After some research, all reports data are saved to DB in table `data_cache`. The ticket is about how to add a config so we can set desired `max_age` of cache instead of [hard-coded 2 days](https://github.com/ckan/ckanext-report/blob/3588577f46d17e5f6ef163bb984d0e7016daef71/ckanext/report/model.py#L108). In our case, we want to set it the max_age a real long time, and fresh the reports via cli or api call.

**Comment by FuhuXia** [comment]
[PR](https://github.com/ckan/ckanext-report/pull/34) submited to upstream.  We can use our forked branch for now. 

After the deployment, we can set cached data not expire by giving the max age a real big value, e.g.,
```
ckanext-report.max_age_in_days = 365
```
Then use CF action to run tasks on schedule to fresh the report cache on demand:
```
ckan report generate [report-name]
```

**Comment by nickumia-reisys** [comment]
A week of successful report generation.  Most recent run: https://github.com/GSA/catalog.data.gov/actions/runs/4657679668/jobs/8242511808

**Comment by FuhuXia** [comment]
We can go ahead and use default 2-day cache age. If we start to experience issues, or if upstream have the PR merged, we will revisit this ticket.
