### ISSUE TITLE
datagov-harvesting repository setup

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4255]
## User Story

In order to write simple python code, data.gov admins want a streamlined GitHub Repository with all the components built in.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN a repository exists for data.gov harvesting in python \
  WHEN a PR is created \
  THEN automated tests occur (linting and tests) \
  AND a code coverage report is generated on the PR \
  AND a snyk scan is run \
  AND a [PR template is utilized](https://github.com/GSA/data.gov/issues/3993#issuecomment-1366755173) \
  AND a README of the idealized code structure is implemented

## Background

https://github.com/GSA/GitHub-Administration#each-repository-should
https://github.com/18F/django-template

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

We need to create a new repository for this, something like `datagov-harvesting` (maybe since we don't know the final utilization of this code, we should use something less generic, something like `datagov-harvesting-logic`?).
We want to take the good from some of the stuff we've done on our CKAN extensions, but improve the simplicity. We want a "typical" python developer to be able to come on and plug in.
- Use docker and/or docker-compose only when necessary for other services; another repository will be utilized to verify platform and library compatibility for deployment (whether on cloud.gov, or on Lambda)
- Use `poetry` that allows for locking and doesn't require our [current janky setup](https://github.com/gsa/catalog.data.gov#note-on-requirements).
- Utilize [poetry for saved commands](https://python-poetry.org/docs/cli/#run) like running tests, don't rely on `Makefile`.
- Use github actions that facilitate the necessary requirements that we already use, such as [linting](https://github.com/GSA/data.gov/blob/main/.github/workflows/ckan-test.yml#L18-L28) and [pytest with coverage](https://github.com/GSA/data.gov/blob/main/.github/workflows/ckan-test.yml#L94-L100)
- Limit bash scripting, as it can be non-portable between unix/linux

**Comment by Jin-Sun-tts** [comment]
created repo here: https://github.com/GSA/datagov-harvesting-logic
