### ISSUE TITLE
Validation of DCAT-US record

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4256]
## User Story

In order to validate a DCAT-US record, data.gov admins (and community) wants a well defined [json-schema](https://json-schema.org/) file.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN a valid DCAT-US record exists and the validation file \
  WHEN the record is processed via the validation file \
  THEN the record passes \
  AND a test replicates this process

- [x] GIVEN an invalid DCAT-US record exists and the validation file \
  WHEN the invalid record is processed via the validation file \
  THEN the record fails with meaningful response \
  AND a test replicates this process

## Background

We currently have a [custom configuration file](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/pod_schema/federal-v1.1/dataset.json) that plugs into some custom logic. We [theoretically do this now](https://github.com/GSA/ckanext-datajson/blob/main/docs/datajson_validator.md#datajson-validator), except we use some strange function called `Draft4Validator` instead of the [standard implementation](https://github.com/python-jsonschema/jsonschema#jsonschema).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

This might be as simple as copying https://github.com/GSA/ckanext-datajson/tree/main/ckanext/datajson/pod_schema/federal-v1.1 to repo created from https://github.com/GSA/data.gov/issues/4255, and installing https://github.com/python-jsonschema/jsonschema#jsonschema and validating working as expected. We would like to test against our current test files [here](https://github.com/GSA/ckanext-datajson/tree/main/ckanext/datajson/tests/datajson-samples). There might be new features/broken items lingering, so consider implementing some of the type of tests [here](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/tests/test_datajson_validation.py) (though not the actual code, as much of that isn't what we want or expect the output to look like).

**Comment by nickumia-reisys** [comment]
There is an code architecture question of how to best abstract this code and organize it so that it makes sense.  What other functions will need to call the validation function?  Are we going for a functional vs. object-oriented design?  What are the high level abstractions other than "E", "T", "L" that we want to have (if any)?

**Comment by jbrown-xentity** [comment]
As part of cleanup of the repo, also look to tackle:

- [ ] Implement poetry setup as an action: https://github.com/marketplace/actions/python-poetry-action
- [ ] Pair with GSA gov team members to publish on pypi like we do [for other python repo's](https://github.com/GSA/ckanext-datagovtheme/blob/main/.github/workflows/deploy.yml), requires secrets setup (or if not possible, create ticket for this item).

**Comment by rshewitt** [comment]
Ruff doesn't like unused imports. The issue derives from an imported fixture function being used as a string within `@pytest.mark.parametrize( "args...", [ ( "fixture_function", file_to_validate.json, is_valid ) ] )`.  This has been resolved. I learned about the conftest.py file for storing fixtures and making them accessible to other files.

**Comment by rshewitt** [comment]
[jsonschema validation errors](https://python-jsonschema.readthedocs.io/en/v4.9.1/errors/)

**Comment by rshewitt** [comment]
[pytest-depends plugin](https://pypi.org/project/pytest-depends/)

**Comment by jbrown-xentity** [comment]
Discovered that json-schema has releases to the spec. Since our spec uses [release 4](https://github.com/GSA/datagov-harvesting-logic/pull/5/files#diff-128c95eaa4cef4a8493c1040611f5e36d78e8f9bcb95ec06d42175bd7abdda4dR2), we need to follow the upgrade path from the [official documentation](https://json-schema.org/specification.html#migrating-from-older-drafts) to get on the most supported/most recent json-schema spec.
This will also allow us to get response for all validation errors (not just the first one found), and will allow us to give complete feedback/changes needed to data provider.

**Comment by rshewitt** [comment]
[json schema release transformer](https://alterschema.sourcemeta.com/)
