### ISSUE TITLE
Develop Extract for JSON format

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4257]
## User Story

In order to harvest DCAT-US catalog JSON files, data.gov admins want:

- an extract utility to load and validate a root JSON file
- a function to then parse that file into individual dataset records identified by a UUID

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN a JSON URL is supplied to the python code (such as https://data.doi.gov/data.json) \
  WHEN the JSON is downloaded  
  THEN it will pass a validation utility to confirm the file can be opened and extracted

- [x] GIVEN the JSON is valid
  THEN a new UUID "identifier" will be generated for the record

- [x] GIVEN we have a valid JSON record with an identifier
  THEN we save that JSON record to S3 with the filename `identifier` with prefix as `<feature>/<sourceId>/<jobId>/<recordId>`

## Background

[Old CKAN process](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/datajson.py#L109-L342).

This is the first functional step of the harvesting pipeline.  See the [Harvest Job Lifecycle](https://drive.google.com/file/d/174fsTVgQCIZh0QOihR2bRZG0dpEgcMIj/view?usp=share_link) for pre- and post- steps.  Also see the [Controller Outline](https://drive.google.com/file/d/1jExSqgB5H_fkvdO85CGgQob0y8CNiX4V/view) for the inputs and output data types and data structures.  There will be future work related to extracting different types of file formats.  

It is key not to confuse the file formats with the metadata schemas (i.e. JSON vs. DCAT-US).

We would like to be as abstract in this extract function definition so it can be easily extensible and scalable with future capabilities.

FYI: In order to create a repeatable test, you can create a local test server like we did for catalog. See test files [here](https://github.com/GSA/catalog.data.gov/tree/main/tests/harvest-sources) and mock server [here](https://github.com/GSA/catalog.data.gov/blob/main/docker-compose.yml#L49-L53) and [here](https://github.com/GSA/catalog.data.gov/blob/main/tests/nginx.conf).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Confirm file at URL is valid JSON format
- [ ] Parse root JSON into individual records
  - [ ] This should be done outside the root JSON validation
- [ ] Generate a new UUID for each potential record to store it in S3 and track it within the pipeline
- [ ] Save the new record to S3 with the filename `identifier` with prefix as `<feature>/<sourceId>/<jobId>/<recordId>`

**Comment by jbrown-xentity** [comment]
Replace [current github action logic](https://github.com/GSA/datagov-harvesting-logic/blob/main/.github/workflows/test.yml#L8-L22) with [poetry action setup](https://github.com/marketplace/actions/python-poetry-action)

**Comment by rshewitt** [comment]
Waiting for discussion on error handling, functional vs OOP, env var formats, and docstrings.

**Comment by rshewitt** [comment]
#### refactored approach
- download file ( xml, json, waf-html ) THIS WILL ALWAYS BE THE CATALOG
- schema_specific check ( e.g. is_dcatus ( json ) or iso ( xml ) ) 
- parse catalog ( this is schema specific )
- upload to s3 

#### additions
- add tests which address exceptions
  - 404, 403, .json() doesn't work
