### ISSUE TITLE
1911 Duplicate Identifiers found in SOLR

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4260]
1911 duplicate identifiers found in Solr. On Friday 3.24 the count was 982. This should be investigated.

## How to reproduce

1. Query Solr: https://catalog.data.gov/api/action/package_search?facet.field=%5B%22identifier%22%5D&facet.limit=-1&facet.mincount=2&rows=0
2. Counrt number of duplicate identifiers

## Expected behavior

I should see no duplicates.

## Actual behavior

I see duplicates.

## Sketch

- [ ] Remove duplicates via the https://github.com/GSA/datagov-dedupe process

**Comment by jbrown-xentity** [comment]
We've narrowed this down to california and nasa: https://github.com/GSA/datagov-dedupe/actions/runs/4534843489. Some things to check to discover how this occurred:

- check logs for when this ran, and any error at the beginning/end (especially the gather)
- Spot check timestamps for the duplicate records, to see if they are close together (gather/fetch queues are picking up multiple items, or something like that), or if the timestamps are far apart (ie completely separate job)
- Check if the harvest_object_id's are the same, or different (at least some are different in this case). This tells us that the gather created a unique record to be harvested.

Code is here: [gather](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/datajson.py#L109-L342) and [import](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/datajson.py#L462-L829)

**Comment by Jin-Sun-tts** [comment]
Run de-dupe from https://github.com/GSA/datagov-dedupe/actions/workflows/run_dedupe.yml for each organization with duplications. There is no organization has duplications now by running 'Check org duplicates',

Checking https://catalog.data.gov/api/action/package_search?facet.field=%5B%22identifier%22%5D&facet.limit=-1&facet.mincount=2&rows=0, it shows result like below:



![Image](https://user-images.githubusercontent.com/104456257/232800212-90d9ea06-881c-4009-a702-6ff49ce077b7.png)
