### ISSUE TITLE
Harvesting gets cancelled by deployment

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4261]
App restart GH action does not interrupt harvest job because of [this extra checks](https://github.com/GSA/data.gov/blob/0332e17a271fc6d12e62d72137e305fb37e52ad2/bin/check-and-renew#L70), but app deployment still cancel in-progress harvest jobs. 

## How to reproduce

Start a big harvest job like nasa data.json. Make a deployment during the gather stage.

## Expected behavior

harvest job finishes on its own.

## Actual behavior

harvest job hangs until force-finished 73 hour later.

## Sketch

Apply same checks as in app restart GH action, unless manually overridden.

**Comment by nickumia-reisys** [comment]
We do have the same checks for `deploy` and `restart`
- https://github.com/GSA/data.gov/blob/main/.github/workflows/deploy-template.yml#L48
- https://github.com/GSA/data.gov/blob/main/.github/workflows/app-restart-template.yml#L37

```bash
check_running_job "$@"

if [[ "$action" == "restart" ]]; then
  if [[ $ok_to_restart == "YES" ]]; then
      cf restart "$app_to_check" --strategy rolling
  else
      echo "Restart $app_to_check cancelled."
  fi
fi

if [[ "$action" == "deploy" ]]; then
  cf push "$app_to_check" --vars-file vars.$space.yml --strategy rolling
fi
```

The only problem is that we don't stop deployment, only restarts.  Do we want to stop deployment for the same exact criteria as restart (i.e. CPU usage and Log timestamp)? @FuhuXia

**Comment by nickumia-reisys** [comment]
Full "algorithm" for deployments:
```python

def is_busy(app):
    if app.cf_deploy_in_progress():
        return True
    if app.cf_restart_in_progress():
        return True
    if app == 'catalog-gather' or app =='catalog-fetch':
        if app.logs_too_new():
            return True

def do_gh_deployment(apps_to_deploy=ALL):
    current_gh_deployments = get_gh_deployments()
    if current_gh_deployments:
        cancel_deployment(current_gh_deployments)

    for app in apps_to_deploy:
        if action == 'deploy':
            if not is_busy(app):
                app.deploy()
                return True
            else:
                sleep(600)
                do_gh_deployment(apps_to_deploy=app)
        if action == 'restart':
            if not is_busy(app):
                app.restart()
                return True
            else:
                return False
