### ISSUE TITLE
Inventory constantly logging errors for missing jQuery library

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4262]
>90 % of Inventory New Relic logs describe a missing jQuery library which is not referenced in the Inventory code base.

## How to reproduce

1. Examine New Relic logs for Inventory Prod
2. You will see a majority of them reference this error:
2.1 `Trying to include unknown asset: <base/vendor/jquery.js>`

## Expected behavior

- I expect to see this script referenced somewhere in the code base
- I expect that URI to fail, however: https://inventory.data.gov/base/vendor/jquery.js resolves with a 200
- I expect to see this error in the browser console when I land on the page.

## Actual behavior

- I don't see this library referenced by name anywhere in the code base
- New Relic logs this error constantly
- I receive no error in the browser when visiting Inventory, nor does my visit cause any change in the logstream.
- I see no similar logs in my local inventory instance

## Sketch

- [x] Examine enabled extensions to see if they are calling jQuery
- [x] Deteremine any configuration deltas between local and cloud installs
- [x] Determine if this issue occurs in the lower environments

**Comment by btylerburton** [comment]
Also seeing `Trying to include unknown asset: <dcat_usmetadata/custom.css>`

**Comment by robert-bryson** [comment]
Note that with [this work blocking routes](https://github.com/GSA/data.gov/issues/4044), any new route will need to be added to inventory's [`proxy/nginx.conf`](https://github.com/GSA/inventory-app/blob/main/proxy/nginx.conf#L46).

**Comment by btylerburton** [comment]
This line looks promising

https://github.com/GSA/ckanext-usmetadata/blob/main/ckanext/usmetadata/templates/base.html#L11

**Comment by nickumia-reisys** [comment]
Finally done 😌 

Notes:
- Fixes `Trying to include unknown asset: <base/vendor/jquery.js>`
- Fixes `Trying to include unknown asset: <dcat_usmetadata/custom.css>`
- There's no way to capture this "class" of error since it was a programming mistake, not a true error.
- dcat-usmetadata is stuck on CKAN 2.9.7 for local testing since login is broken on 2.9.8.  (Work to test on CKAN 2.10 is future and may resolve this broken local testing issue)
