### ISSUE TITLE
catalog staging redis memory full

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4264]
catalog staging redis is full of memory. We need to follow https://github.com/GSA/cf-backup-manager/blob/main/docs/redis-support.md to clear out and resolve
![image](https://user-images.githubusercontent.com/26980513/228320565-3b60248a-ed57-47a3-ae74-b11cfb6dfe1b.png)

## How to reproduce

Try to harvest any source

## Expected behavior

Harvesting starts

## Actual behavior

Error (see above)

## Sketch

We can just clear out all of redis. We aren't worried in general about duplicates or failed harvest points for staging.

**Comment by Jin-Sun-tts** [comment]
Followed the steps in https://github.com/GSA/cf-backup-manager/blob/main/docs/redis-support.md and run `flushdb` to clear out. 

Double check on UI, there is no memory error anymore
![Screen Shot 2023-03-30 at 12 43 57 PM](https://user-images.githubusercontent.com/104456257/228906940-23934426-c51e-4486-bfb2-f9767e97148d.png)
