### ISSUE TITLE
DCAT usmetadata extension has node build issues

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4274]
## How to reproduce

1. Use newer version of node to build dcat_usmetadata react app

## Expected behavior

App builds

## Actual behavior

```bash
$ yarn build:metadata-app && yarn rename:builds
warning package.json: "dependencies" has dependency "babel-eslint" with range "10.1.0" that collides with a dependency in "devDependencies" of the same name with version "^10.1.0"
warning package.json: "dependencies" has dependency "eslint-plugin-react" with range "7.22.0" that collides with a dependency in "devDependencies" of the same name with version "^7.22.0"
$ node react-scripts/build.js
Creating an optimized production build...
/home/runner/work/ckanext-dcat_usmetadata/ckanext-dcat_usmetadata/react-scripts/build.js:11
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/runner/work/ckanext-dcat_usmetadata/ckanext-dcat_usmetadata/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/work/ckanext-dcat_usmetadata/ckanext-dcat_usmetadata/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/runner/work/ckanext-dcat_usmetadata/ckanext-dcat_usmetadata/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/runner/work/ckanext-dcat_usmetadata/ckanext-dcat_usmetadata/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/runner/work/ckanext-dcat_usmetadata/ckanext-dcat_usmetadata/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/runner/work/ckanext-dcat_usmetadata/ckanext-dcat_usmetadata/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/runner/work/ckanext-dcat_usmetadata/ckanext-dcat_usmetadata/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/runner/work/ckanext-dcat_usmetadata/ckanext-dcat_usmetadata/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

## Sketch

TBD.  Webpack has issues on newer version of node.

**Comment by hkdctol** [comment]
Node v16 EOL September 2023

**Comment by jbrown-xentity** [comment]
The process, as we see it now:

1. Confirm the node 18 problem (locally)
2. Research react/other library upgrades as appropriate for error message
3. Iterate until working
4. Test and verify working with ckan extension

Should consider node 20, if the fix for 18 goes well. If not, make another ticket and mark for the correct milestone (https://nodejs.dev/en/about/releases/)

**Comment by rshewitt** [comment]
webpack is using a hash algorithm which isn't compatible with the default openSSL 3.0 provider used by node v17.0+. enabling the legacy openSSL provider via `NODE_OPTIONS=--openssl-legacy-provider` allows the build to complete but seems like a [security concern](https://www.openssl.org/docs/manmaster/man7/OSSL_PROVIDER-legacy.html#:~:text=The%20OpenSSL%20legacy%20provider%20supplies%20OpenSSL%20implementations%20of%20algorithms%20that%20have%20been%20deemed%20legacy.%20Such%20algorithms%20have%20commonly%20fallen%20out%20of%20use%2C%20have%20been%20deemed%20insecure%20by%20the%20cryptography%20community%2C%20or%20something%20similar.)

**Comment by btylerburton** [comment]
Is this an issue that only affects local development / running a dev server, or does it prevent us from running a build?

**Comment by rshewitt** [comment]
It prevents us from running the `react-scripts` build.

**Comment by btylerburton** [comment]
Converting to Vite might be worth exploring
https://www.robinwieruch.de/vite-create-react-app/

*based on this SO answer: https://stackoverflow.com/questions/75181657/create-react-app-not-working-on-node-18-lts-version

**Comment by rshewitt** [comment]
Updating inventory-app to pull latest version of this app.
