### ISSUE TITLE
Conduct FY2023 Data.gov Contingency Plan Test

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4278]
## User Story

In order to meet FISMA and GSA requirements, Data.gov team needs to conduct a Contingency Plan Test for FY 2023.

## Acceptance Criteria

- [x] GIVEN the requirement for an annual CP test and the template provided by ISSO\
  THEN Data.gov team has completed a test\
  AND outcome is documented in the template provided by ISSO.

## Sketch

- [x] Develop a test scenario
- [x] Schedule and conduct test
- [x] Retro on the test
- [x] Complete the CP test template

**Comment by hkdctol** [comment]
Template is https://docs.google.com/document/d/1W6ksZ-TObjlt7HRa34YbQum2sa1GIxDES9km9NnK9U4/edit?usp=sharing

Feel free to post ideas for CP scenarios

**Comment by nickumia-reisys** [comment]
Possible scenarios (to inspire others to think of more):
- Catalog/Inventory solr volume gets corrupted
- Catalog/Inventory db becomes unresponsive
- Catalog/Inventory proxy returning 500 because it can't talk to web (or admin)
- Catalog/Inventory secrets are deleted/corrupted

**Comment by hkdctol** [comment]
Test planned for 5/12. Before that, review
- [x] [Contingency Plan](https://docs.google.com/document/d/1szGIZK4y_e1kGcATK2CaLitAUt6kTh7A3XqlSTihuOc/edit?usp=sharing)
- [x] [Contingency Plan Test Plan](https://docs.google.com/document/d/1vkrTdPK2m0M3E1QLO9o24gwPVeTBDWHY5LMx4Cqf8zQ/edit?usp=sharing)
- [x] [Incident Response Plan](https://docs.google.com/document/d/12L-KeuXudGeQ2SdNOGy53ljxHA38nX3v/edit?usp=sharing&ouid=113511966954817069922&rtpof=true&sd=true)
- [x] Past [example] of incident response and writeup (https://docs.google.com/document/d/1BvUX0zEdUm5kOOMPtN7kTIv2C-hesSbffSn615_feyU/edit?usp=sharing)

**Comment by hkdctol** [comment]
Blank template for writing up FY23 CP test https://docs.google.com/document/d/1zrGqWyAy02NnqhbLqnsasBm4qzBdKdJXUhIof-k59vc/edit?usp=sharing

**Comment by hkdctol** [comment]
Completed test and documentation and submitted to ISSO.
