### ISSUE TITLE
CKAN 2.10 - datagovtheme broken UI items

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4285]
ckanext-datagovtheme @ ckan-210

## How to reproduce

1. `make clean buld up`

## Expected behavior

![image](https://user-images.githubusercontent.com/85196563/233194954-212199e2-c81c-43d7-8da4-c4a4091d919f.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/85196563/233195444-a81c4edd-60b3-47bb-baf5-9157d39f31ce.png)

## Sketch

Ask @FuhuXia

**Comment by nickumia-reisys** [comment]
@FuhuXia 👉 @Jin-Sun-tts and I worked on fixing some of the formatting.  Please look at the changes and see if you agree with them: 
- https://github.com/GSA/ckanext-datagovtheme/pull/162/commits/63f4cf1250fa9ff3d8e4a598440d99f323193749

The "order by" box is much trickier and could probably use some insight on you for how to re-work it.  I don't like any of the solutions I'm coming up with.

**Comment by FuhuXia** [comment]
New header works. I think the changes can be limited to one file instead of involving multiple files and inline styling.

~~I see there are changes need to be done other than the header. The order by is definitely an issue. The whole body color also has undesired change.~~

**Comment by Jin-Sun-tts** [comment]
Fixes are in sort_by.html,  replaced the class names to be same as in the organization page:


![Image](https://github.com/GSA/data.gov/assets/104456257/5c91de0a-b853-4786-b358-29a147a015d0)

**Comment by FuhuXia** [comment]
reduce home button size
![image](https://github.com/GSA/data.gov/assets/1392461/55647eea-18fd-403a-9d5b-771e5d934aba)

**Comment by FuhuXia** [comment]
landing page multiple issues
![image](https://github.com/GSA/ckanext-datagovtheme/assets/1392461/269b1714-fa87-4299-86a6-6c86615b5adb)

**Comment by FuhuXia** [comment]
more padding between line and title
![image](https://github.com/GSA/data.gov/assets/1392461/362e4f63-a2cc-43b2-9476-51692da5b8fe)

**Comment by FuhuXia** [comment]
Empty facet on organization landing page.

![image](https://github.com/GSA/data.gov/assets/1392461/4217bc42-27fc-4ae3-b883-a2dd14af3956)

**Comment by FuhuXia** [comment]
Need smaller font so there are padding around text; need rounded corners.
![image](https://github.com/GSA/data.gov/assets/1392461/de3f21d3-8a57-48ff-b087-31e500a44af3)

**Comment by FuhuXia** [comment]
adjust padding on harvest jobs page.

![image](https://github.com/GSA/data.gov/assets/1392461/c19ea36c-b14b-4ad3-8450-752c722fff5d)

**Comment by FuhuXia** [comment]
Each item on its own line. reduce Question mark size.
![image](https://github.com/GSA/data.gov/assets/1392461/f689a91b-625b-4392-b535-1337cc5dc39a)

**Comment by FuhuXia** [comment]
bulk_process shows 0 datasets.

![image](https://github.com/GSA/data.gov/assets/1392461/81819edf-1d81-40da-aaf0-46309e1569a8)

**Comment by Jin-Sun-tts** [comment]
landing page: home iconand source type colors

![Image](https://github.com/GSA/data.gov/assets/104456257/33c58c27-6ccc-4a05-bbf6-cb8e1f482cc2)


pagination, twitter and github icons:

![Image](https://github.com/GSA/data.gov/assets/104456257/b6472179-67cc-4be8-96a7-6374f2e072d7)


space between line and title :

![Image](https://github.com/GSA/data.gov/assets/104456257/a00d3fb8-6863-4772-a50d-4e9fd6bdd1c1)


harvester page: label style and source type format
![Image](https://github.com/GSA/data.gov/assets/104456257/addab073-4a55-4adf-abc7-23f9375dc7bd)

![Image](https://github.com/GSA/data.gov/assets/104456257/b391f7d9-0843-4fc1-b981-91d6ae753cc3)

![Image](https://github.com/GSA/data.gov/assets/104456257/bc8c1422-2c12-4bf0-9505-0c1edb963ed5)


facet on organization landing page.

![Image](https://github.com/GSA/data.gov/assets/104456257/1c513fe3-306a-4674-8fee-474d70a18465)


bulk_process page, dataset list shows up:
![Image](https://github.com/GSA/data.gov/assets/104456257/e2868370-238d-46bd-b425-a98050caf220)

**Comment by FuhuXia** [comment]
Calendar and license icons are missing. calender icon is [an old issue](https://github.com/GSA/data.gov/issues/2927), can be fixed at the same time. 

![image](https://github.com/GSA/data.gov/assets/1392461/1c78fea8-171d-467e-978d-9c58c3fab711)

Edit icon is missing.

![image](https://github.com/GSA/data.gov/assets/1392461/2221d597-be75-47a0-8ad4-a61f0e43a219)

**Comment by Jin-Sun-tts** [comment]
Fixed the icon for calendar, license, Edit etc:

![Screen Shot 2023-06-13 at 11 08 05 AM](https://github.com/GSA/data.gov/assets/104456257/6edec3a8-b1b6-4c44-84c0-26ecb6fa8f2e)
![Screen Shot 2023-06-13 at 11 08 54 AM](https://github.com/GSA/data.gov/assets/104456257/20aae122-6cd3-455e-bb91-7fe78606e5f6)

Also found 'collection' label and icon did not shows up correctly:
![Screen Shot 2023-06-13 at 12 48 55 PM](https://github.com/GSA/data.gov/assets/104456257/109d7d41-0389-48e2-8158-638fe04fee3e)

Fixed it here:
![Screen Shot 2023-06-13 at 12 48 09 PM](https://github.com/GSA/data.gov/assets/104456257/b8f4df01-2319-4689-af64-4a334ca35703)

**Comment by FuhuXia** [comment]
Flash message is not visible.

![image](https://github.com/GSA/data.gov/assets/1392461/f5c2832d-89b5-405c-9323-3e02a13fd908)

**Comment by Jin-Sun-tts** [comment]
Fixed this issue by changing the category and class name in the page.html at datagovtheme.



![Image](https://github.com/GSA/data.gov/assets/104456257/2748b580-3ce0-4a6b-bfc5-a93d3327ff2f)

**Comment by FuhuXia** [comment]
[ Update ] fixed by https://github.com/GSA/ckanext-datagovtheme/pull/167
_________________
The `/dataset` link on the header is not working, carrying `new index` into the search.
![image](https://github.com/GSA/data.gov/assets/1392461/47dee2d5-2936-4a9f-a270-1108ef28b13b)

**Comment by Jin-Sun-tts** [comment]
Removed hightlight_actions from the dataset link in the header.

**Comment by FuhuXia** [comment]
issue https://github.com/GSA/data.gov/issues/4285#issuecomment-1569085353 is back.
