### ISSUE TITLE
Inventory shows wrong URL for resource link

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4289]
Uploaded resource in Inventory shows a wrong url `inventorynew-prod-datagov.apps.internal` for download.

## How to reproduce

Go to https://inventory.data.gov/dataset/inventory-of-owned-and-leased-properties-3983 and click one of the resources.

![image](https://user-images.githubusercontent.com/1392461/234675350-0445c237-5080-4218-aaf8-95c5e0f2ed19.png)

## Expected behavior

It shows a valid url and link is clickable.

## Actual behavior
Wrong URL. not downloadable.

**Comment by jbrown-xentity** [comment]
Looks to be a SOLR index problem, indexed under the wrong site_url. Need to re-index...

**Comment by FuhuXia** [comment]
Fixed. Re-index was done during off hours.
