### ISSUE TITLE
Upgrade all cloud.gov apps to `cflinux4`

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4291]
## User Story

In order to keep a high level of cybersecurity, the Data.gov O&M team wants to upgrade all instances of apps to use the `cflinux4` container image stack.

## Acceptance Criteria

- [ ] GIVEN the upgrade is complete \
  WHEN `cf audit-stack` is run \
  THEN all apps show `cflinux4`

## Background

- https://gsa-tts.slack.com/archives/C2N85536E/p1682704877887719
- https://github.com/cloudfoundry/stack-auditor

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None.

## Sketch

- List of repos
  - [ ] datagov-logstack
  - [ ] data.gov
  - [ ] catalog.data.gov
  - [ ] inventory-app
  - [ ] datagov-ssb
  - [ ] cf-backup-manager
  - [ ] datagov-logstack
  - [ ] dashboard

- Actions that need to be done for each repo
  - [ ] Update manifest to specify `cflinux4` as the stack ([example](https://github.com/GSA-TTS/cg-egress-proxy/pull/26/files#diff-24c51d6f58480f0d1e1b3f4068768cbdea5c9896edb96ca0165f8122224217a8R6))
  - [ ] Deploy new app with rolling strategy
  - [ ] Revert the stack specification.

**Comment by robert-bryson** [comment]
Note that `audit-stack` is [a cf plugin](https://docs.cloudfoundry.org/adminguide/stack-auditor.html) and not built into `cf` or in the CF-Community plugin repo. 

To install:  
- Get the latest release for your arch [here](https://github.com/cloudfoundry/stack-auditor/releases)
- Run `cf install-plugin <stack-auditor-binary>`

**Comment by hkdctol** [comment]
See notice at https://cloud.gov/2023/04/27/cflinuxfs3-deprecation-update/ and email from cloud.gov team --there will be live demos every day week of 5/15.

**Comment by robert-bryson** [comment]
For context from the starting point: 

![Image](https://github.com/GSA/data.gov/assets/91547795/3ad3b7ec-e7b4-4005-a9d3-115f88865c3f)

**Comment by robert-bryson** [comment]
Well, flipped the numbers almost, but there are a few outliers with issues. 

![Image](https://github.com/GSA/data.gov/assets/91547795/d68381a3-d79e-4ca1-a866-9b9fff2b516e)

There are a variety of issues with the remaining apps which I am working down. Thanks @nickumia-reisys  for helping with this earlier. 

![Image](https://github.com/GSA/data.gov/assets/91547795/54aec225-1547-45cb-9023-41efc74005bd)

**Comment by robert-bryson** [comment]
Current outstanding list: 

![Image](https://github.com/GSA/data.gov/assets/91547795/26e53e18-f945-497d-bed6-7de2f96c414f)

**Comment by robert-bryson** [comment]
Thanks to the team's help (and especially @nickumia-reisys) in the huddle, we are at: 

![Image](https://github.com/GSA/data.gov/assets/91547795/c1e25d3f-2868-4596-aced-5e3ae057a221)

The remaining 3 are all dashboard: 

![Image](https://github.com/GSA/data.gov/assets/91547795/2a096612-26d5-4a65-9bea-5f39af59db91)

Since dashboard is not long for the world, we as a team agreed to accept that it is on the old stack and move on.

**Comment by robert-bryson** [comment]
It looks like these dashboard stacks will need be updated if the Deprecate Dashboard ticket https://github.com/GSA/data.gov/issues/3502 does not get completed before [June 29th, 2023](https://cloud.gov/2023/05/16/cflinuxfs3-buildpack-deprecation/#important-dates) (thanks @hkdctol for finding this).
