### ISSUE TITLE
Deleted CKAN users show up in the organization list

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4292]
When a user is deleted from ckan, the user should not show in the organization list

## How to reproduce

Log into Inventory and go to url https://inventory.data.gov/organization/members/nda-usda-gov

## Expected behavior

No admin users, since we have converted all Admin to Editor

## Actual behavior

![image](https://user-images.githubusercontent.com/1392461/235473836-8e4898d8-2d65-4bdd-83a1-df1a825ca931.png)

These Admin users have been deleted. They should not show up in the list.

## Sketch

This could be a CKAN bug upstream. Verify it in the fresh CKAN 2.9/2.10 installation and report a bug in CKAN upstream.

**Comment by hkdctol** [comment]
@FuhuXia I believe those accounts are old entries from before we were in login.gov, and we didn't delete them. Those old accounts without any login.gov couldn't have actually logged in once we went to login, I believe.

**Comment by FuhuXia** [comment]
@hkdctol If you click on one of the usernames, it leads to the user details page showing user state as **Deleted**. It is right that it is not a security concern since deleted user cannot log in, but it creates confusion when Admin are managing users and seeing the false info.
