### ISSUE TITLE
CKAN 2.10 `license_list` not working

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4293]
ckan @ 2.10
ckanext-spatial @ main
geodatagov @ ckan-210

## How to reproduce

1. Run tests and look at output from `ckanext/geodatagov/tests/test_waf.py::TestWafHarvester::test_datasets_from_waf_fgdc_sample`

## Expected behavior

Test passes..

## Actual behavior

`KeyError: 'as_dict'` 

```python
/srv/app/ckanext/geodatagov/tests/test_waf.py:131:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/srv/app/ckanext/geodatagov/tests/test_waf.py:81: in run_import
    result = self.harvester.import_stage(harvest_object)
/srv/app/src/ckanext-spatial/ckanext/spatial/harvesters/base.py:625: in import_stage
    package_dict = self.get_package_dict(iso_values, harvest_object)
/srv/app/ckanext/geodatagov/harvesters/base.py:88: in get_package_dict
    package_dict = super(GeoDataGovHarvester, self).get_package_dict(iso_values, harvest_object)
/srv/app/src/ckanext-spatial/ckanext/spatial/harvesters/base.py:361: in get_package_dict
    license_list = p.toolkit.get_action('license_list')(context, {})
/srv/app/src/ckan/ckan/logic/__init__.py:551: in wrapped
    result = _action(context, data_dict, **kw)
/srv/app/src/ckan/ckan/logic/action/get.py:762: in license_list
    licenses = [l.as_dict() for l in licenses]
/srv/app/src/ckan/ckan/logic/action/get.py:762: in <listcomp>
    licenses = [l.as_dict() for l in licenses]
```

Important references:
- [CKAN 2.9 Deprecation warning](https://github.com/ckan/ckan/blob/2.9/ckan/model/license.py#L79-L98)
- [CKAN 2.10 "replacement" type function](https://github.com/ckan/ckan/blob/2.10/ckan/model/license.py#L188-L193)
- [CKAN 2.10 reference to deprecated and removed function name](https://github.com/ckan/ckan/blob/2.10/ckan/logic/action/get.py#L762)
- https://github.com/GSA/data.gov/issues/4209

## Sketch

Uhhh.. wait for upstream to fix?

**Comment by jbrown-xentity** [comment]
Blocking completion of #4209

**Comment by btylerburton** [comment]
test

**Comment by nickumia-reisys** [comment]
CKAN core implemented a fix for this, but we won't have access until they make a new release...
- https://github.com/ckan/ckan/issues/7447

Thoughts anyone? @GSA/data-gov-team

**Comment by jbrown-xentity** [comment]
> CKAN core implemented a fix for this, but we won't have access until they make a new release...
> 
> * [The API method license_list no longer works with CKAN 2.10.0 ckan/ckan#7447](https://github.com/ckan/ckan/issues/7447)

We could [pin ckan version to a commit](https://github.com/GSA/catalog.data.gov/blob/main/ckan/requirements.in#L2), the commit in the PR above. This might have ramifications, because that branch might have other changes/development at that point from base 2.10. However, it seems like they already [found a lot of bugs](https://github.com/ckan/ckan/issues?q=label%3A%22Backport+2.10.1%22+is%3Aclosed) that have been addressed, so we could try reaching out to CKAN core to see when they think a 2.10.1 will be released...

**Comment by jbrown-xentity** [comment]
2.10.1 was released with the necessary patch, closing this.
