### ISSUE TITLE
Setup branching/merging strategy in git

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#43]
Would be good if we weren't all committing directly to master. We should consider at minimum using feature branches and tagging our commits with issue numbers.

**Comment by dano-reisys** [comment]
https://www.infoq.com/news/2015/10/branching-continuous-integration
http://martinfowler.com/books/continuousDelivery.html

Are we still trying to achieve CI/CD?

**Comment by neilhunt1** [comment]
We need to discuss some details, but short answer is certainly yes. For git branching/merging, I follow [Atlassian's guide](https://www.atlassian.com/git/tutorials/comparing-workflows/). Hoping we can at least get to Feature Branch workflow.

**Comment by dano-reisys** [comment]
as far as I know CI/CD is all about committing often to trunk/master.

**Comment by neilhunt1** [comment]
That is true. But it’s more than that: Continuous Delivery is about having code in a stable branch (master) readily reasable at any time. So there are reasons to use branches that are still compatible with CD:

1.       Issuing branch merge pull requests so that at least one other person reviews code prior to merging onto master

2.       Isolated development without affecting master. In order to keep master stable, new dev should usually be done in a separate branch.

3.       More advanced release management strategies are available using Gitflow once we get into production mode.

I’ll plan to show a CD demo using branched development model soon, using Jenkins.

**Comment by dano-reisys** [comment]
I'd be more than happy to take a look at it. I still think that dev should be done in one branch (local branching should be fine).

**Comment by kvuppala** [comment]
@JJediny any changes needed here, should we close it?
