### ISSUE TITLE
Fix schema.org linkage

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4307]
We've found that we don't have the schema.org stuff in our data pages anymore. We install [dcat](https://github.com/ckan/ckanext-dcat#structured-data-and-google-dataset-search-indexing), and it's in [our plugins](https://github.com/GSA/catalog.data.gov/blob/280031a0a92bba1c6654d9a981abdcd48a46e2cb/.env#L50), but it doesn't come through on the dataset page.

## How to reproduce

1. Go to https://catalog.data.gov/dataset/electric-vehicle-population-data

## Expected behavior

Find script tag `script type="application/ld+json"` in html

## Actual behavior

No script of ld+json

## Sketch

We think we're overriding this poorly, need to investigate: https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/templates/package/read_base.html
It could also be that changing the order of the extensions may have the desired affects (ie dcat integrates with ckan, then we blow the whole thing away in datagovtheme), so changing the plugin order may make a difference.

**Comment by gujral-rei** [comment]
- team agrees to pick this up after bulk of H2 work is complete

**Comment by jbrown-xentity** [comment]
Robby mentioned this might already be complete, and it is! See attached screenshot; you can see that the json-ld containing DCAT metadata is embedded on the webpage.
This can be closed.![Image](https://github.com/user-attachments/assets/5089c895-b297-437b-b4cc-fb04ebec2cc4)
