### ISSUE TITLE
Setup external service for S3 ( dev )

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4308]
## User Story

In order to store our records during test runs, data.gov wants to setup an external testing service to mirror S3 in development using a Docker container.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN I want to use the Python SDK to interact with the S3 client
  AND I want to perform these operations in a local Pytest framework
  THEN I expect all responses to mirror production S3

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch
- [x] Create locally available S3 stand-in using localstack
- [x] Configure Docker Compose with S3
  - [x] Expose port for local testing
  - [x] Create Health Check

**Comment by rshewitt** [comment]
We used `localstack` as the S3 bucket in the [extract dcatus ticket](https://github.com/orgs/GSA/projects/11?pane=issue&itemId=23777726). For continuity, @nickumia-reisys and I think docker should be used. I replaced some of the wording in this ticket to reflect this. Please let me know if anything is unclear.

**Comment by rshewitt** [comment]
redis and postgres env vars used in [catalog](https://github.com/GSA/catalog.data.gov/blob/3c2b0598dd0776c83c53d212ff8ff88622fc305f/.env)

**Comment by rshewitt** [comment]
[postgres build context](https://github.com/GSA/catalog.data.gov/tree/3c2b0598dd0776c83c53d212ff8ff88622fc305f/postgresql) in catalog.

**Comment by rshewitt** [comment]
Add test using bad S3 config value ( e.g. `"endpoint_url" = "garbage"` ) to ensure `boto3` responds correctly.

**Comment by rshewitt** [comment]
Add test to see how long it takes to count through 100k files in an S3 bucket. this relates to the compare portion of the harvester.

**Comment by rshewitt** [comment]
current S3 docker [implementation](https://github.com/GSA/datagov-harvesting-logic/blob/21a02529f0529fec2fdf98c4a9f27c5732c7eea0/docker-compose.yml#L12-L26)

**Comment by rshewitt** [comment]
Do we want to explicitly test whether the localstack/s3 container is healthy by checking the [container health property](https://github.com/peter-evans/docker-compose-healthcheck#:~:text=If%20the%20check%20is%20successful%20the%20container%20will%20be%20marked%20as%20healthy). Successful record insertion can only occur if the service is healthy and we know records are being inserted.

**Comment by jbrown-xentity** [comment]
Not a bad test. It's an intermediate one, that tells us what went wrong (in this case, a test harness error, not a code change error). Ideally this isn't necessary, but may be helpful if something goes wrong with localstack in the future. @rshewitt

**Comment by rshewitt** [comment]
Interestingly enough the `localstack`container state is actually `unhealthy` but the tests run as expected. health property discussion on [docker-py issue](https://github.com/docker/docker-py/issues/2229)

![Image](https://github.com/GSA/data.gov/assets/92057378/001d0dd3-1536-46d7-a832-f38b2b55c3c7)

nvm ignore this comment. my health check was checking `pg_isready` ... yeah go figure

**Comment by rshewitt** [comment]
`localstack` and `nginx` services most likely don't need to talk to each other but the parent extract app should be able to talk to both. we're not going to configure the docker-compose `network` in this ticket.

**Comment by rshewitt** [comment]
`localstack` container will be destroyed after tests are conducted. how do we want the s3 instance to persist?

**Comment by rshewitt** [comment]
going to leave a snapshot of the time it takes to count 100k records in an S3 bucket.

**Comment by rshewitt** [comment]
26 seconds to count 100k dcatus catalogs from `localstack`. Forgot the ask was for records not catalogs but I think the test still stands. 
![Image](https://github.com/GSA/data.gov/assets/92057378/324e0279-a6fe-459a-887f-7c64d1133ad4)

**Comment by jbrown-xentity** [comment]
> 26 seconds to count 100k dcatus catalogs from `localstack`. Forgot the ask was for records not catalogs but I think the test still stands.

I would think we could do better, although I would assume that localstack wouldn't be as performant at scale as a true AWS S3 would (though the network latency is smaller). Did we try something like https://stackoverflow.com/questions/32408167/how-do-i-get-the-size-of-a-boto3-collection?

**Comment by rshewitt** [comment]
my dummy credentials don't seem to be honored when iterating through the object collection returned by `S3.Bucket.objects.all()`. error >>> `botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.`

**Comment by nickumia-reisys** [comment]
I think 26 seconds is wayy too slow 🐢 

Goal should be 0.5s, threshold 1s.

![image](https://github.com/GSA/data.gov/assets/85196563/79afa067-4325-4a9a-91ed-e7893a201504)

... Consider if we needed to call this function in different steps that knew nothing about each other.  We'd like to be time and memory efficient.  No need to store this value in memory if it's quick enough to compute.  At 26s, if we call it 10 times, then that's 5mins already wasted in our harvesting timeline.

**Comment by rshewitt** [comment]
Dropped the count down to 11 seconds using the `aws` cli. counting the number of objects in `boto3` using something like `sum( 1 for _  in bucket.objects.all() )` or `len(list(bucket.objects.all()))` results in an `InvalidAccessKeyId` error. I've setup a `~/.aws` dir with default credentials and configurations. I can count via pagination ( see above ). I don't intend to store the results i'm just trying anything. I'm passing `localhost:4566` to the `endpoint-url` when I create the s3 client.

![Image](https://github.com/GSA/data.gov/assets/92057378/2c10dbb7-3c47-44e1-850a-f070b2364811)
