### ISSUE TITLE
WIP: Create DB tables using Alembic

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4309]
## User Story

In order to ensure reproducibility, data.gov wants to create database tables with a versioning tool, to allow for clean upgrades and downgrades as needed. 

Note, Alembic is the proposed solution, but if there is adequate reason to consider an alternative, please bring that up to the team.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN data.gov want to create a database
  AND allow for clean and reproducible upgrades and downgrades
  THEN we want to ensure that the DB is created with a tool that allows for programatic versioning

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Configure new harvest DB tables with a schema using a tool (ex. Alembic) that allows for programatic versioning in code

**Comment by hkdctol** [comment]
Elasticsearch, MySQL, Postgres as options.
