### ISSUE TITLE
Document how jekyll hosts publish to S3 without credentials

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#431]
S3 [credentials are empty](https://github.com/GSA/datagov-deploy/blob/master/ansible/roles/software/jekyll/files/root/.s3cfg) on the Jekyll hosts, yet they are able to publish to the s3 bucket.

**Comment by adborden** [comment]
The EC2 instance is configured with a role that allows writing and configuring the S3 buckets.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
