### ISSUE TITLE
Invicti Scan April of 2023: Out-of-date Moment.js

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4311]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#bookmark=kix.ptswtnqjz7ca)._

**Date of report:** 2023-04-28
**Severity:** High
**Due date:**  2023-05-28

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
Latest stable version is 2.29.4

**Comment by nickumia-reisys** [comment]
If we get to `CKAN 2.10.0`, moment is on a non-vulnerable version...

![image](https://github.com/GSA/data.gov/assets/85196563/30f80bf7-71f8-499c-854f-01fd3008b9b1)

![image](https://github.com/GSA/data.gov/assets/85196563/ad7b98d3-d3b4-4831-b571-912046e83d85)

**Comment by FuhuXia** [comment]
If we want to patch 2.9.8 before 2.10 is deployed, we can fork the core and point ckan requirement to our fork repository instead of pypi package. This will get us off the time pressure.

**Comment by nickumia-reisys** [comment]
This has been completed for dashboard, catalog and inventory.  All running the patched version of `moment.js`.

We probably need to let the SecOps team know, so they can re-scan the applications?

**Comment by hkdctol** [comment]
Shared status with ISSO and ISSM.
