### ISSUE TITLE
WIP: Implement Redis queue system

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4316]
## User Story

In order to achieve stability in the Harvesting 2.0 pipeline, data.gov wants to implement a Redis queue system.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a user/process wishes to initiate a harvesting job
  THEN the job processing will be managed by a Redis queue

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

The Redis queue was defined here: https://github.com/GSA/data.gov/issues/4314

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

None

## Sketch

- [ ] Implement pre-defined Redis queue in ETL pipeline

**Comment by hkdctol** [comment]
TO DO: this might be two tickets, one for job queue and one for the record queue.
