### ISSUE TITLE
Redirect Dashboard Homepage

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4331]
## User Story

In order to deprecated Dashboard, the Data.gov Dashboard Team wants to forward the existing dashboard homepage to the new catalog reports page.

## Acceptance Criteria
- [ ] WHEN I visit https://dashboard.data.gov \
    THEN my browser is redirected to the new catalog reports page, https://catalog.data.gov/report/metrics-dashboard

## Background
Current dashboard validator exists [here](https://labs.data.gov/dashboard/validate).
New dashboard validator exists [here](catalog.data.gov/dcat-us/validator).
- https://github.com/GSA/data.gov/issues/3503
- https://github.com/GSA/data.gov/issues/4001

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Not sure?

## Sketch

- [ ] Create a proxy rule in `www-redirects` app
  - [ ] Redirect `dashboard.data.gov` to `catalog.data.gov/reports`

**Comment by robert-bryson** [comment]
Working as of the merge of https://github.com/GSA/datagov-website/pull/50: 
![Recording 2023-06-12 at 09 38 35](https://github.com/GSA/data.gov/assets/91547795/cffe1260-08a0-4fd6-8b45-40b17b85c56a)

Note that the redirect is to `/report` instead of the correct `/report/metrics-dashboard`. PR for that https://github.com/GSA/datagov-website/pull/51

**Comment by robert-bryson** [comment]
Dashboard route removed with https://github.com/GSA/project-open-data-dashboard/pull/418. Closing.
