### ISSUE TITLE
Setup external service for Postgres

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4332]
## User Story

In order to allow for reliable unit-testing of Harvest 2.0 modules, data.gov wants to set up a test service for Postgres

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I use the PSQL syntax to interact with the Postgres client
  THEN I expect all responses to mirror production

- [ ] GIVEN I would like to query the state of a harvest job
  AND I have a key defined by the `<jobId>`
  THEN I want a utility to query the job state associated with that `<jobId>`

- [ ] GIVEN I want to test an error response
  THEN I want a mechanism to force the service to respond in error

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Create reusable Postgres service using docker

**Comment by rshewitt** [comment]
going to focus on s3 and extract. this ticket is already partially complete on this [branch](https://github.com/GSA/datagov-harvesting-logic/tree/setup-test-services-s3-db-redis)

**Comment by rshewitt** [comment]
pausing harvester 2.0 work.

**Comment by btylerburton** [comment]
Completed in https://github.com/GSA/datagov-harvester/pull/3
