### ISSUE TITLE
Setup Interface for Postgres

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4336]
## User Story

In order to track the state of a harvesting job within the pipeline, which will be stored in a Postgres database, datagov wants an interface to interact with the Cloud.gov Postgres service or the local Docker test-service equivalent.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I want to start a harvest job
  AND I have a `<jobId>` defined by a UUID
  THEN I want utility to store that as a new entry defined by `<jobId>` and status `new`

- [ ] GIVEN I have an entry in the DB in status "new"
  THEN I want a utility to change that status based on its progression through the pipeline: `Extract`, `Compare`, `Load`, `Validate`, `Transform`, `Error`

- [ ] GIVEN I have defined (#TODO!) a job storage lifecycle
  THEN I would like a utility to perform bulk updates on all entries once the lifecycle transition preconditions are met

## Background

We will use Postgres to track that status of a harvest job through the pipeline. Once a job is initiated, a new entry is made into the Postgres DB with status "new". As that job progresses through the steps of the pipeline, we use the Postgres utility to update the job's status. Once a job is complete, it's status will be marked as "Finished" or "Error".

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Create Python module to interact with Postgres DB using PSQL syntax
- [ ] Abstract away any direct commands to DB

**Comment by robert-bryson** [comment]
Well, the details have taken a lot longer to work out that expected, but [PR is open](https://github.com/GSA/datagov-harvesting-logic/pull/11). 

Lessons learned: 
  - Just do your own testing. Slick fixture suites are slick, but seem to not work well. 
  - Just use SQL. I'm sure there are better wrappers, but for this simple logic it is more straightforward to just write raw SQL.

**Comment by btylerburton** [comment]
Not needed given Airflow handles calls to and from the DB
