### ISSUE TITLE
Confirm all Cloud.gov static sites built using Ruby 3.x

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4339]
## User Story

In order to continue building static sites on Cloud.gov, all build processes using Ruby will need to be upgraded to Ruby 3.x.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I have a static site on Cloud.gov pages
  WHEN I would like to publish a new build
  THEN I would need to do so using Ruby 3.x starting Dec. 1, 2023

## Background

Ruby 2.x has reached it's end-of-life for support and Cloud.gov will no longer build sites in Ruby 2.x after November 31, 2023. It is incumbent upon data.gov to upgrade all static sites by then so they can continue being built.

https://cloud.gov/2023/05/24/cloud-gov-pages-jekyll-ruby-upgrade/

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
Sites will no longer be able to be built if Ruby is not upgraded.

## Sketch

- [x] Confirm all sites below are explicitly using Ruby 3.x (ex. using a `.tool-versions` file), and deploy a new updated version.
  - [x] https://federation.data.gov/
  - [x] https://strategy.data.gov/
  - [x] https://resources.data.gov/

**Comment by btylerburton** [comment]
This will likely be painless for everything but SDG, which will need to have it's Jekyll plugin rebuilt to support Ruby 3.x.

**Comment by btylerburton** [comment]
OpenSDG hasn't release version 2.3.0 of Jekyll plugin, but they believe they are getting close. We should revisit as milestone approaches.

**Comment by rshewitt** [comment]
ruby 3.1 is supported until 31 Mar 2025

**Comment by btylerburton** [comment]
Brock has outlined the path for integrating a pre-release version into SDG. I'm going to break this effort off into a new ticket as  it is somewhat extensive and segmented from the other upgrades:

https://github.com/open-sdg/open-sdg/discussions/2067

**Comment by btylerburton** [comment]
Related: https://github.com/GSA/data.gov/issues/4514

**Comment by rshewitt** [comment]
ruby upgrades were done in [#4488](https://github.com/GSA/data.gov/issues/4488)
