### ISSUE TITLE
Upgrade MySQL in affected Cloud.gov services

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4344]
## User Story

In order to continue running our databases on AWS, datagov must upgrade MySQL from 5.7.x to 8.0.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a service running MySQL
  AND the version is 5.7.x
  THEN it should be upgraded to 8.0.0 to continue functioning as expected.

## Background

Datagov team were provided a list of affected applications in `management` and `management-staging` spaces, and those have been confirmed to be running MySQL 5.7.x.

Recommended course of action is to follow this guide and upgrade the affected services: https://cloud.gov/2023/06/05/aws-ending-support-mysql-57/

The list of affected services is below:
<img width="762" alt="Screen Shot 2023-06-07 at 10 30 36 AM" src="https://github.com/GSA/data.gov/assets/104455281/50547105-76fd-4f9d-9fd1-e7d2185c2500">

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Follow upgrade guide for affected services in all spaces
- [ ] Check migration notes from 5.7.x to 8.0.0
  - [ ] Cross-reference those changes with cloud-service-broker database design and confirm no methods have been removed or renamed that might affect architecture

**Comment by rshewitt** [comment]
| space   | service | version |
| -------- | ------- | ------- |
| development | dashboard-db | service missing |
| management  | ssb-smtp-db | 8.0.36 |
| management  | ssb-eks-db | not authorized to connect to service | 
| management-staging  | ssb-smtp-db | 8.0.36 |
| management-staging  | ssb-eks-db | 8.0.36 |
| prod  | dashboard-db | 8.0.36 |
| staging  | dashboard-db | service missing |

**Comment by rshewitt** [comment]
cloudgov upgraded all our mysql service instances to the appropriate version(s)
