### ISSUE TITLE
change tracking update from nightly job to weekly

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4345]
Stats shows catalog visits to `/_tracking` in June doubles in number compared to April stats. The count of unique dataset page visits is four times more. Together with recent questionable Solr performance, they makes the nightly tracking update job takes too long to finish.  Give the fact the page visit stats is not critical to be processes nightly, we can change to a weekly job. 

## Sketch
1. ~~tracking-update is supposed to run nightly according to [CKAN core](https://github.com/ckan/ckan/blob/master/ckan/cli/tracking.py#L49-L51). We need to change to default behavior in [ckanext-geodatagov](https://github.com/GSA/ckanext-geodatagov/blob/main/ckanext/geodatagov/cli.py#L605) so it handles weekly data.~~
2. Change [GH action cron](https://github.com/GSA/catalog.data.gov/blob/main/.github/workflows/ckan_auto.yml#L6) to weekly.

**Comment by FuhuXia** [comment]
Stats were collected 3 days in April (10, 11, 12) and June (05, 06, 07). 
Newrelic shows hits to `/_tracking` are **394K** in April and **762K** in June.
DB query shows **65K** unique dataset visited in April and **256K** in June.

```
--sample query
SELECT count(*) FROM tracking_summary
where package_id!='~~not~found~~'
and tracking_date in ('2023-06-05', '2023-06-06', '2023-06-07')
```

**Comment by Jin-Sun-tts** [comment]
catalog cron job change: https://github.com/GSA/catalog.data.gov/pull/962

**Comment by nickumia-reisys** [comment]
Random follow-on notes: We suspect this issue is caused by bot tracking inflating the `/tracking` route.  I thought a ticket was made, but apparently not.  If we limit bot traffic to the catalog instance and this action should be able to be run nightly again.

**Comment by FuhuXia** [comment]
> Random follow-on notes: We suspect this issue is caused by bot tracking inflating the `/tracking` route. I thought a ticket was made, but apparently not. If we limit bot traffic to the catalog instance and this action should be able to be run nightly again.

Not to limit bot traffic, but to exclude bot traffic from tracking count. We need to use above three days data, April (10, 11, 12) and June (05, 06, 07), combined with CloudWatch log data (containing user-agent info), to see the effect of excluding bot traffic to the tracking count.
