### ISSUE TITLE
Upgrade CKAN DB from `2.9` to `2.10`

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4346]
## User Story

In order to be able to upgrade to the latest version of CKAN, the Data.gov O&M development team wants to ensure there is a solid procedure for how to upgrade the existing DBs in cloud.gov `development`, `staging` and `prod`.

## Acceptance Criteria

- [ ] GIVEN there is a CKAN 2.9 DB
  WHEN @FuhuXia's DB upgrade process happens
  THEN it is a CKAN 2.10 DB

## Background

Related to
- https://github.com/GSA/data.gov/issues/4209
- https://github.com/GSA/inventory-app/pull/611

A DB upgrade was attempted for inventory on cloud.gov and it failed because it could not perform the DB operations outside of the flask web app context.
![image](https://github.com/GSA/data.gov/assets/85196563/f6f651a2-f402-40da-b611-d527c4c0b997)
![image](https://github.com/GSA/data.gov/assets/85196563/32bfebe2-0725-4d40-bafc-ce182db383c9)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
...

## Sketch

- [ ] Document @FuhuXia's process
- [ ] Test with inventory development

**Comment by FuhuXia** [comment]
1. Push an Ubuntu image to cloud.gov to install CKAN 2.10 on
```
cf push ckan-210 --docker-image ubuntu/apache2:2.4-20.04_edge
cf scale ckan-210 -m 2G -k 2G
cf ssh ckan-210
```
2. Install CKAN 2.10
```
apt update
# install for ckan
apt install python3-dev libpq-dev python3-pip python3-venv git-core redis-server
# to fix an error about libmagic
apt install  libmagic-dev

mkdir -p /usr/lib/ckan/default
python3 -m venv /usr/lib/ckan/default
. /usr/lib/ckan/default/bin/activate
pip install --upgrade pip
pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.10.1#egg=ckan[requirements]'
deactivate
. /usr/lib/ckan/default/bin/activate

mkdir -p /etc/ckan/default
ckan generate config /etc/ckan/default/ckan.ini
```
3. Edit ckan.ini to use existing `sqlalchemy` connections, `solr` connection, `redis` connection, and `ckan.site_id` value

```
vi /etc/ckan/default/ckan.ini
```

4. Upgrade DB
```
# within the same virtualenv above
ckan -c /etc/ckan/default/ckan.ini db upgrade
```

* *notes*
1. Try with a ckan 2.9 install first and make sure you can run a harmless `ckan user list` to verify everything works before trying ckan 2.10.
2. For catalog, dont forget https://github.com/GSA/catalog.data.gov#note-on-db-migration

**Comment by FuhuXia** [comment]
Above steps were proven to be working, inventory DB on development space was upgraded from CKAN 2.9.8 to CKAN 2.10.1

**Comment by jbrown-xentity** [comment]
This may not be needed at this time, as some other bugs were fixed in order that this is not necessary. Closing for now.
