### ISSUE TITLE
Fix CKAN `2.10` Harvesting

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4347]
## User Story

In order to be able to upgrade to the latest version of CKAN, the Data.gov O&M development team wants to get all of catalog.data.gov harvesting tests passing with CKAN `2.10`.

## Acceptance Criteria

- [ ] GIVEN a development catalog build is running CKAN `2.10`
  WHEN any harvesting operation happens
  THEN it is successful

## Background

Related to
- https://github.com/GSA/data.gov/issues/4209
- https://github.com/GSA/catalog.data.gov/pull/953

Video of current harvest tests failing: https://github.com/GSA/data.gov/assets/85196563/bf64b719-e181-417c-9110-6b23ba1c4d24

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
...

## Sketch

- [x] Watch broken catalog test videos
- [x] Debug locally
  - Pull https://github.com/GSA/catalog.data.gov/pull/953/files
  - Turn on server via docker locally
  - Login and create a harvest source
  - Run manually
  - Evaluate error messages/bugs in browser and in docker logs
  - Raise to team if not sure what the errors mean
- [x] Fix tests
  - [x] Can't create harvest source
  - [x] Harvest jobs run?
  - [x] Harvest data checks?

**Comment by jbrown-xentity** [comment]
See stack trace of issue [here](https://github.com/GSA/data.gov/issues/4209#issuecomment-1571974014)

**Comment by nickumia-reisys** [comment]
Error logs when hitting `/harvest/new`: 
- https://github.com/GSA/data.gov/issues/4209#issuecomment-1571974014

**Comment by Jin-Sun-tts** [comment]
After removed following set in the .env file, the add new harvest source page does not give error anymore.  

CKAN__HARVEST__LOG_SCOPE=0

Then I tried to set to 1, the harvest page works without error.

**Comment by jbrown-xentity** [comment]
Relevant harvest documentation [here](https://github.com/ckan/ckanext-harvest#database-logger-configurationoptional)

**Comment by Jin-Sun-tts** [comment]
Logging to the database is disabled by default. So removed this configuration parameter CKAN__HARVEST__LOG_SCOPE to avoid the logging issue from harvesting.

**Comment by Jin-Sun-tts** [comment]
Now the created new harvest page works. 

The harvesting job does not finished with errors like below:

* test the ckan source, gather and fetch works fine, but got error when do harvester run:

    2023-06-20 16:38:20,193 DEBUG [ckanext.harvest.logic.action.update] Notifications: All:True On error:False Errors:0
    ......
    werkzeug.routing.BuildError: Could not build url for endpoint 'harvest.job_show' with values ['id', 'source']. Did you mean 'harvester.job_show' instead?
    
    Tried to set CKAN__HARVEST__STATUS_MAIL__ALL=False, it works without errors.

* test the datajson source, shows error at fetch-consumer:

    2023-06-20 17:12:00,160 ERROR [ckanext.datajson.datajson] Failed to create package purchase-card-transactions-office-of-inspector-general-parent from https://gsa.gov/data.json
    ......       
    AttributeError: type object 'str' has no attribute '__code__'
    ......
    TypeError: str cannot be used as validator because it is not a user-defined function

**Comment by Jin-Sun-tts** [comment]
Fixed issue for Type error in file plugin.py at ckanext-datagovcatalog to use String function. 
Fixed the NoneType error for unknown spatial values in file at ckanext-geodatagov.
Found a bug in upstream ckan/ckanext-harvest update.py file, it should use **harvester**.job_show instead of **harvest**.job_show. Just tested through a fork repo having the fixes, it works without error. Will submit PR to fix it.

**Comment by Jin-Sun-tts** [comment]
ckan/ckanext-harvest PR: https://github.com/ckan/ckanext-harvest/pull/534
