### ISSUE TITLE
Missing Harvest source

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#4348]
The issue of missing harvest sources is appearing again. In the past, these issues would clear up overnight. The [National Transportation Atlas Database records](https://catalog.data.gov/harvest/national-transportation-atlas-database-ntad-metadata) that were harvest June 4, 2023 has a number of records with this issue.

The harvest_object_id returns a 404.
https://catalog.data.gov/harvest/object/c0498763-83d9-4af0-9a80-fe7322dd3065

![image](https://github.com/GSA/data.gov/assets/64213093/f5416cf1-1fc3-453f-876f-0e295471093e)

![image](https://github.com/GSA/data.gov/assets/64213093/751f2514-c101-46fe-9e8c-0915cf91f594)

**Comment by jbrown-xentity** [comment]
@FuhuXia can you take a look at this?

**Comment by FuhuXia** [comment]
I have not done anything yet but I could not replicate the issue. The dataset has a different harvest_object_id and it is valid. In the DB there is not trace of `c0498763-83d9-4af0-9a80-fe7322dd3065`. Can you show another example? @chris-macdermaid

**Comment by chris-macdermaid** [comment]
@FuhuXia, At this point, none of the records from that harvest source are missing their harvest source. If it helps attached is the package_show for runway record with the harvest object that didn't resolve.
[package_show-runway-json.txt](https://github.com/GSA/data.gov/files/11710272/package_show-runway-json.txt)

**Comment by FuhuXia** [comment]
Thanks. Keep up posted if there are more cases like this and do not resolve after overnight.

**Comment by chris-macdermaid** [comment]
@FuhuXia  here is an example of a record with a missing harvest object. GeoPlatform first tried to harvest it on June 12, 2023 at 6:09 AM MDT. At June 14, 2023 at 2:47 PM MDT  the harvest object from package_show is still returning a 404.
[fars-package_show-json.txt](https://github.com/GSA/data.gov/files/11750449/fars-package_show-json.txt)

https://catalog.data.gov/dataset/2020-persons-involved-auxiliary-data-fars

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 4:07 PM MDT this record is missing its harvest source.

https://catalog.data.gov/dataset/navigable-waterway-network-nodes

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 4:35 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/strategic-ports

GeoPlatform also failed to harvest this on June 12, 2023 at 6:09 AM MDT because of the missing harvest source.

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 4:42 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/runway-points

GeoPlatform also failed to harvest this on June 12, 2023 at 6:09 AM MDT because of the missing harvest source.

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 4:54 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/ferry-routes

GeoPlatform also failed to harvest this on June 12, 2023 at 6:09 AM MDT because of the missing harvest source.

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 5:17 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/fmcsa-regions

GeoPlatform also failed to harvest this on June 12, 2023 at 6:09 AM MDT because of the missing harvest source.

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 5:20 PM MDT this record is missing its harvest source.

https://catalog.data.gov/dataset/freight-analysis-framework-faf5-highway-network-assignments

GeoPlatform also failed to harvest this on June 12, 2023 at 6:09 AM MDT because of the missing harvest source.

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 5:32 PM MDT this record is missing its harvest source.

https://catalog.data.gov/dataset/phmsa-hazmat-regions

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 5:38 PM MDT this record is missing its harvest source.

https://catalog.data.gov/dataset/freight-analysis-framework-faf5-network-links

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 5:54 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/alternative-fuel-corridors

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 5:59 PM MDT this record is missing its harvest source.

https://catalog.data.gov/dataset/2021-vehicle-information-auxiliary-data-fars

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 6:03 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/amtrak-routes

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 6:09 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/military-bases

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 6:20 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/nonattainment-area-sulfur-dioxide-so2-2010-standard

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 6:22 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/waterway-locks

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 6:37 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/populated-places2

**Comment by chris-macdermaid** [comment]
As of June 14, 2023 at 6:39 PM MDT this record is missing its harvest source.
https://catalog.data.gov/dataset/nonattainment-area-1-hr-ozone-1979-standard-revoked

**Comment by jbrown-xentity** [comment]
Looks like this is still an open issue...

**Comment by FuhuXia** [comment]
Thanks for the 17 new examples. Manually running search-index rebuild for the first two datasets fixed the two:
https://catalog.data.gov/dataset/2020-persons-involved-auxiliary-data-fars
https://catalog.data.gov/dataset/navigable-waterway-network-nodes

They were due to the very typical issue that solr has a harvest_object_id value that does not exist in db. 

Now running db-solr-sync manually to see if it fixes the rest 15 dataset. If it does, it means nightly job will fix them. If not, we will look further.

Stay tuned.

**Comment by FuhuXia** [comment]
The rest 15 are fixed by the db-solr-sync job, which means even we dont do anything, they will be fixed tomorrow. However, if you keep seeing same set of datasets show up in your error list everyday, it may means a reharvest will always generate the error and waiting to be fixed by db-solr-sync job. I am reharvesting them now.

**Comment by FuhuXia** [comment]
Ok, confirmed an new harvest issue for DOT WAF source `/harvest/national-transportation-atlas-database-ntad-metadata`. Will track in another GH issue.

**Comment by hkdctol** [comment]
We are working on this under #4362 and closing this ticket.
