### ISSUE TITLE
catalog ckan 2.10 release

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4352]
## Release Catalog 2.10

Roll out CKAN2.10 release on catalog

### Acceptance Criteria

- [x] All required bugfixes are done
- [x] QA is performed by 2 personnel
- [x] New app is created and receiving traffic

### Implementation notes

This will require some of the following steps (this list may be incomplete). This should be implemented on staging/dev first, to verify the process.

- [x] Make announcement to users
- [x] Stop catalog activity
  - [x] Create PR 
    - [x] Turn off all automated commands (`auto_ckan.yml`)
    - [x] Set `catalog-gather` and `catalog-fetch` to 0 instances in the manifest
    - [x] Turn off auto restarts (`restarts.yml`)
   - [x] Scale catalog-gather and catalog-fetch to 0 
- [x] Track `Last Modified` time on Solr Leader 
- [x] Create CKAN 2.10 DB
- [x] Backup CKAN 2.9 DB
- [x] Ensure `Last Modified` time on Solr Leader is the same as above. (If not, take a new backup)
- [x] "Delete" users from CKAN 2.9 DB
- [x] Restore CKAN 2.9 DB to CKAN 2.10 DB
- [x] DROP INDEX idx_view_resource_id;
- [x] Create `catalog-new-*` apps with CKAN 2.10 DB
  - [x] `cf push` **catalog-new-web** to get DB upgraded
  - [x] `cf push` **catalog-new-proxy** and `cf add-network-policy` to verify CKAN 2.10 frontend
- [x] Switching catalog.data.gov to use the new app
  - [x] `cf push` **catalog-new-web** again with prod routes. 
  - [x] `cf add-network-policy` so that **catalog-new-web** is serving traffic at catalog.data.gov
  - [x] delete old catalog-web and clear cloud front cache
  - [x] `cf rename-service`  catalog-db to catalog-old-db, and catalog-new-db to catalog-db
  - [x] `cf rename catalog-new-web catalog-web`
  - [x] `cf push` all catalog-* apps with ckan-210 branch
  - [x] manually run harvesting jobs to verify harvesting. 
- [x] Merge CKAN 2.10 PR

**Comment by hkdctol** [comment]
UI on dev looks good. On harvest reports -- the first box being that rust color that makes the number hard to read--is that something we don't have an option on?

![Image](https://github.com/GSA/data.gov/assets/3236989/1998f564-1dc3-4d37-8c00-7df9a37f74b9)

**Comment by jbrown-xentity** [comment]
It is. I don't know how important it is to fix that now... I played around with a few color changes, how does this look @hkdctol ? for the record, the hex color is `#f28c28`... I went with orange to be different from `deleted` (pink), not dark red, but still a bright color to highlight this field, as errors are the most likely viewed part of the summary report... It's embedded in ckanext-harvest, but we could overwrite it in datagovtheme or geodatagov on the `data-diff="error"` section.
![image](https://github.com/GSA/data.gov/assets/26980513/bb22d7f8-cf94-44d6-a279-d3fea95f3fdc)

**Comment by FuhuXia** [comment]
This is the color what we had long time ago.
![image](https://github.com/GSA/data.gov/assets/1392461/de9694dc-8f61-4251-a504-137607470e90)

**Comment by hkdctol** [comment]
That light orange is much easier to read @jbrown-xentity

**Comment by FuhuXia** [comment]
CKAN 2.10 is released to catalog. Detailed steps were recorded in a [Slack thread](https://gsa-tts.slack.com/archives/C2N85536E/p1689268678802759).

Post-release PRs were created for merging:
1. https://github.com/GSA/catalog.data.gov/pull/953
2. https://github.com/GSA/catalog.data.gov/pull/987

Merging these PRs will restore all GubHub actions for backend processes such as harvesting jobs. Until then, will manually run harvesting daily.
