### ISSUE TITLE
Collate Data.gov mission/vision

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4354]
## User Story

In order for the team to feel confident in the data.gov mission, data.gov team wants the purpose and vision of data.gov laid out.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] WHEN someone wants to understand the data.gov vision \
  THEN the necessary information is easily accessible and findable.

## Background

This ticket is to create/find the background, but this is a recurring item in the retro times.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

Get all the stuff we've already created, create a wiki page summarizing and documenting, and link to onboarding.

Get feedback from team on missing pieces.

**Comment by hkdctol** [comment]
Starting a google doc at https://docs.google.com/document/d/1WVENd4xCWeGiyMn-BZ8tMD-GLIM8zU-lumqwDhsq45c/edit?usp=sharing
Most of the material is not sensitive, but I've marked a few things I would not publish in a public wiki. Also gathering examples of other vision/strategy documents we could use as guides for a new Data.gov document.

**Comment by jbrown-xentity** [comment]
@data-gov-team could use a review of https://github.com/GSA/data.gov/wiki/Data.gov-Mission-and-Strategy... Lots of information in these documents. Let me know what you would find more helpful, and happy to add into the wiki for more shorthand search!

**Comment by hkdctol** [comment]
Thanks @jbrown-xentity for organizing it on a wiki so that the material is all in one place. I'll be working on an updated document that's more of a mission/vision doc.

**Comment by nickumia-reisys** [comment]
This feels weird to write, but I actually know all of the documents on the new wiki page 😱 .  Looking at the page though.. it's not clear who it's for or what the content means.  A more accurate title would be "Things related to data.gov mission and strategy".  As it stands right now, (if I didn't know about the documents like I do), I could not piece together a meaningful idea from the list of resources.  A question that may or may not influence the improvement of the page:  Is the audience of the wiki: (1) new members of the data.gov team or (2) the general public?

In both cases, more scope should be added to help understand where things are coming from (P.S. The opening paragraph of the wiki is very accurate 😉)

We have the work that tried to explain why we exist:
- https://github.com/GSA/data.gov/issues/4089

We have work that explains (what we do) and (how we do what we do):
- Maybe no real tickets associated with this, but the existence of catalog, inventory, resources, strategy and the static site are essentially the core here.
- (e.g. We do "harvesting" [what we do] through the existence of "catalog.data.gov" [how we do what we do])

We have things that describe what has happened (where we've been):
- Milestones, timelines, presentations and reports

We have a few loose ideas about where we are going:
- ...

Is the intent to have all of this on that wiki?  If yes, it's a bit messy right now.  If not, we can probably remove what we don't want?  Or make more dedicated pages for each thing that we do want?

**Comment by hkdctol** [comment]
I think the intent was only to collect what we have, to indicate what we need to create.

**Comment by nickumia-reisys** [comment]
Follow-on work in
- #4390
