### ISSUE TITLE
Confirm technical questions around UA360 implementation

### ISSUE THREAD

**Issue by dlennox24** [GSA/data.gov#4358]
## User Story

Determine what technical unknowns we have about the UA 360 transition. 

## Acceptance Criteria

- [x] GIVEN that our existing UA property is migrating to UA 360
THEN we need to determine what infrastructure changes we need to make (eg UA tracking codes, etc), if any

## Sketch
- [x] Determine permission requirements for data.gov team
- [x] Create suggestions/tickets to implement any necessary changes discovered

**Comment by hkdctol** [comment]
We have required permissions for the Data.gov "property" in the UA360 account. We should proceed with plans for a Data.gov GA4 that we would maintain separate from DAP.
