### ISSUE TITLE
Determine why Google Analytics is showing page views to dead pages

### ISSUE THREAD

**Issue by dlennox24** [GSA/data.gov#4359]
## User Story

There is still traffic going to now dead paths on the [data.gov](http://data.gov/) site. We need to determine where the origin of these are.

## Acceptance Criteria

- [ ] GIVEN some users are attempting access dead pages that now 404
THEN discovery why these users are hitting this pages and if there is anything we can do to route them to the correct location

## Sketch
- [ ] Determine origin of users going to dead paths
- [ ] Create suggestions and follow up tickets based on what was discovered

**Comment by dlennox24** [comment]
I created some [GA4 explorations](https://analytics.google.com/analytics/web/#/analysis/p381392243/edit/eA3MGI5mRySuEzi-hAgRVQ) to determine where these 404s may be coming from. These explorations can be used in the future as well.

It appears all current 404s are direct access to the URL. These are often times external links such as bookmarks, external documentation, and external sites linking to data.gov. All of these are outside of our ability to modify.

**Comment by hkdctol** [comment]
We reviewed this in our meeting today.

**Comment by hkdctol** [comment]
@FuhuXia wants to make sure there isn't additional reason for this

**Comment by btylerburton** [comment]
cc @btylerburton

**Comment by FuhuXia** [comment]
Checked in the NewRelic log. These 404 looks legit, mostly due to popular pages being deleted by harvest activity.
