### ISSUE TITLE
Internal server error searching for Bailey's Ecoregions and Subregions Dataset

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#4364]
In looking for the USDA's "Bailey's Ecoregions and Subregions Dataset" record, searching for either, bailey, ecoregion, or subregion returns an internal server error.

The Bailey's Ecoregions and Subregions Dataset record came from the [usda-json harvest](https://catalog.data.gov/dataset/usda-json). The record isn't in the latest updated USDA data.json (6/21/2023). I'm working with the USDA on that record. It should be in the latest update. It will be in future updates to USDA's data.json.

If the record was deleted with the latest harvest, did the indexing error exist before the deletion? Is the indexing error related to the apostrophe? Without using an apostrophe in the search the search was failing. What is needed to search for the exact title with the apostrophe?

## How to reproduce
Search for either, bailey, ecoregion, or subregion

`https://catalog.data.gov/dataset?q=bailey`

`https://catalog.data.gov/dataset?q=ecoregion`

`https://catalog.data.gov/dataset?q=subregion`

![image](https://github.com/GSA/data.gov/assets/64213093/514c6e32-deb0-4715-bcb5-59fb8e43132e)

Searching for USDA records sorted by title so this record is near the top returns an internal server error.

`https://catalog.data.gov/dataset/?q=&sort=title_string+asc&organization=usda-gov`

![image](https://github.com/GSA/data.gov/assets/64213093/abbdc6b6-2bd8-4813-a42a-b3af086d80ad)

## Expected behavior

Search retruns results or no results.

## Actual behavior

Search returns an internal server error.

**Comment by FuhuXia** [comment]
Thanks @chris-macdermaid yes it is an solr issue. We are on it.

**Comment by FuhuXia** [comment]
Fixed.
