### ISSUE TITLE
Make meaningful Inventory Homepage for anonymous users

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4365]
## User Story

In order to give users a better UX, the Data.gov inventory development team wants to implement a custom homepage for anonymous users to know that inventory requires a login for normal use.

## Acceptance Criteria

- [x] GIVEN a user IS NOT authenticated
  WHEN they visit the homepage
  THEN they see the custom login prompt

- [x] GIVEN a user IS authenticated
  WHEN they visit the homepage
  THEN they are redirected to `/dataset`

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
...

## Sketch

- [x] Implement a blueprint to redirect `/` to `/{route}`
  - [x] If user is logged in, show the real page
  - [x] If user is anonymous, show the custom user message

**Comment by nickumia-reisys** [comment]
@hkdctol If you can come up with a heading and a sentence or two to greet and inform users, please post them here.
![image](https://github.com/GSA/data.gov/assets/85196563/9623c22d-6ed1-47e3-b84b-3ec1336fe7ea)

**Comment by hkdctol** [comment]
Heading could be "Authorized Access Only"

Explanatory text could be: Inventory.data.gov is a non-public website used by federal agencies to create and maintain metadata  intended for publication on the Data.gov [catalog](https://catalog.data.gov/dataset). Agency users who need access to inventory.data.gov should contact the team at datagov@gsa.gov.

**Comment by nickumia-reisys** [comment]
Text is live on dev: https://inventory-dev-datagov.app.cloud.gov/

![image](https://github.com/GSA/data.gov/assets/85196563/ce8404aa-4917-4dc6-950c-b6409f2db5b9)
