### ISSUE TITLE
CKAN 2.10 - Catalog Collections UI Button is Missing

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4369]
## How to reproduce

1. Look at tests on catalog `ckan-210` branch

## Expected behavior

![image](https://github.com/GSA/data.gov/assets/85196563/d5d5ab76-fc0c-4058-9658-4d2469c678cf)

## Actual behavior

![image](https://github.com/GSA/data.gov/assets/85196563/bc35dc14-8dcf-4fd0-9941-544c4d945a57)

## Sketch

- [ ] Investigate `ckanext/geodatagov/templates/package/read.html` template in `geodatagov`
  - [ ] `h.get_pkg_dict_extra(c.pkg_dict, 'collection_metadata', '')` seems suspicious

**Comment by FuhuXia** [comment]
So this template is not working as expected.
https://github.com/GSA/ckanext-geodatagov/blob/main/ckanext/geodatagov/templates/package/read.html#L10

**Comment by nickumia-reisys** [comment]
> So this template is not working as expected.

Most likely?

**Comment by Jin-Sun-tts** [comment]
Fixed this issue in datagovtheme read.html to apply supper() for the collection_resources block from geodatagov.

![Screen Shot 2023-06-28 at 4 43 45 PM](https://github.com/GSA/data.gov/assets/104456257/4f8dd949-edee-49d7-a7f9-23c3c457bccc)
