### ISSUE TITLE
Fix Inventory Dataset Summary Blob

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4377]
## How to reproduce

1. Visit inventory.data.gov/dataset

## Expected behavior

Top label (public/private) is supposed to be on the right side.  The file type labels should be colored and formatted prettier

## Actual behavior

![image](https://github.com/GSA/data.gov/assets/85196563/6c8f6459-cac2-4f57-9f76-88bb0037cf29)

## Sketch

TBD

**Comment by nickumia-reisys** [comment]
Label coloring fixed on production.

**Comment by Jin-Sun-tts** [comment]
The `PUBLIC` label was like below in 2.9:

![Screenshot 2023-07-06 at 4 07 21 PM](https://github.com/GSA/data.gov/assets/104456257/9b2de277-b9d6-4a9e-8589-a88d06ff0d59)

**Comment by Jin-Sun-tts** [comment]
Added related css styles in datagov_inventory.css

![Screenshot 2023-07-10 at 10 36 13 AM](https://github.com/GSA/data.gov/assets/104456257/254782df-ee5f-45c2-8abf-d2665ae99e4c)
