### ISSUE TITLE
Catalog Harvester needs to support TLS v1.2 harvest sources

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#438]
It is unclear whether harvester is able to connect using TLS v1.2, we need to confirm this either way.

**Potential User Story**
Users setting up harvest sources that only enable SSL connections using TLS v1.2 will fail because our current harvester can only support secure connections using up to TLS v1.1.

**Comment by nickumia-reisys** [comment]
TLS is at least on 1.3 now and we are supporting that protocol on cloud.gov now.  

From internal discussions, we might be considering enforcing `https` for all harvest sources.  But we'll make a new ticket if that's the case.
