### ISSUE TITLE
Fix Harvesting Error Color

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4383]
## How to reproduce

1. Look at a completed harvest job on CKAN 2.10

## Expected behavior

https://github.com/GSA/data.gov/issues/4352#issuecomment-1628935412

## Actual behavior

https://github.com/GSA/data.gov/issues/4352#issuecomment-1626039203

## Sketch

- [ ] Use updated color from https://github.com/GSA/data.gov/issues/4352#issuecomment-1629749645

**Comment by Jin-Sun-tts** [comment]
![Screenshot 2023-07-18 at 12 15 29 PM](https://github.com/GSA/data.gov/assets/104456257/2eb65eee-40ae-4cfe-b5ae-d02b986562bc)

@hkdctol  Looks like before the 'ERROR' text were white, do we want to change it like below, or change the background to a new color 'Orange'?

![Screenshot 2023-07-18 at 11 48 36 AM](https://github.com/GSA/data.gov/assets/104456257/bd4c8f71-b829-4b62-9aad-193ee6600678)

**Comment by Jin-Sun-tts** [comment]
Also noticed in this harvest job list page, the background of these label changed to black when hover on. Will disable the hover reaction for this page.  

![Screenshot 2023-07-18 at 1 17 05 PM](https://github.com/GSA/data.gov/assets/104456257/2e270a9a-9849-41ed-b21d-48c2423b75d5)
