### ISSUE TITLE
S3 Clients must use TLS 1.2

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4384]
## Description: 
AWS deprecated support for TLS 1.0 and TLS 1.1 across all of its services on June 28, 2023, meaning connections must be made using at least TLS 1.2 after that date. 

This ticket will confirm that the S3 clients are working as expected and have been upgraded.

## Full text of email:

> Dear [cloud.gov](http://cloud.gov/) customer,
>  
> We are reaching out to inform you that you need to upgrade your clients to use at least TLS1.2 when making requests to some of your brokered S3 buckets.
>  
> [TLS means Transport Layer Security and is the protocol that facilitates privacy and data security on the Internet](https://www.cloudflare.com/learning/ssl/transport-layer-security-tls/).
>  
> There are different versions of TLS and as of June 28, 2023, AWS is deprecating support for TLS 1.0 and TLS 1.1 across all of its services, meaning connections must be made using at least TLS 1.2 after that date.
>  
> We have determined that you are making requests to these brokered S3 buckets using TLS 1.0/1.1:
>  
> org: gsa-datagov, space: prod, service name: static-site-images
>  
> Specifically, these were the user agents making the TLS 1.0/1.1 requests:
>  
> [Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko]
>  
> To avoid request failures to your S3 buckets after June 28, 2023, you need to update the clients making requests to these S3 buckets to use at least TLS1.2. Here is some guidance on how to use TLS1.2 for different languages and tools:
>  
> Javascript: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/enforcing-tls.html
> Go: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/tls.html
> .NET: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/enforcing-tls.html
> AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/cli-security-enforcing-tls.html
> Python/boto3: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/security.html#enforcing-tls-1-2
>  
> Please feel free to reply to this email or contact [support@cloud.gov](mailto:support@cloud.gov) if you have any questions or concerns.
>  
> Thanks for being our customer,
> The [cloud.gov](http://cloud.gov/) team
> 

## Sketch

- [ ] Examine affected `prod` services that pull images from the `static-site-images` S3 bucket and confirm they have been upgraded, based on the instructions above for each language.
- [ ] Based on string matching, these repos should be examined for S3 clients:
  - [ ] https://github.com/GSA/datagov-11ty
  - [ ] https://github.com/GSA/ckanext-geodatagov/blob/main/ckanext/geodatagov/cli.py
  - [ ] https://github.com/keitaroinc/ckanext-s3filestore (for inventory)

**Comment by jbrown-xentity** [comment]
Need to confirm that the s3 libraries we use (boto3) support TLS 1.2, and I'm not sure how to handle 11ty (we just have raw reference links in there, so not sure how to make sure that is supported)....

**Comment by robert-bryson** [comment]
Pairing with James yesterday we determined that this is a no op so closing. 

We did find that the bucket in question is being used by the 11ty static site via simple links to the resources in the bucket (not relevant to this ticket as they are being served over the internet) and that we could [add a minimum TLS version in the S3 bucket policy](https://docs.aws.amazon.com/AmazonS3/latest/userguide/amazon-s3-policy-keys.html#example-object-tls-version) if needed in the future.
