### ISSUE TITLE
Inventory error on organization Datasets tab

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4388]
As an admin, when clicking the Datasets tab under an organization, it gives 500 `Internal server error`.

![image](https://github.com/GSA/data.gov/assets/1392461/a6a4ba2f-e797-4618-837e-51db7cba40fb)

## Sketch

Catalog 2.9 and 2.10 are OK.

**Comment by hkdctol** [comment]
Look at US metadata extension

**Comment by Jin-Sun-tts** [comment]
reproduced this issue locally with the error like below:

![Screenshot 2023-07-21 at 11 47 07 AM](https://github.com/GSA/data.gov/assets/104456257/30494e27-28a0-42b0-bf5e-76d02950fd39)

**Comment by Jin-Sun-tts** [comment]
Fixed the syntax error, then the page looks like below:

![Image](https://github.com/GSA/data.gov/assets/104456257/c25476cb-b572-425b-83b4-2ae97122906b)

Looks like the local version does not work, so removed this bulk_process local file in usmetadata to use upstream standard,  confirmed with Fuhu, this page looks good as expected. So we just removed the our customized version. 

![Image](https://github.com/GSA/data.gov/assets/104456257/fb500073-5d41-4b05-a4fe-4c7e5f6bf611)

**Comment by Jin-Sun-tts** [comment]
https://github.com/GSA/ckanext-usmetadata/pull/74
