### ISSUE TITLE
harvest error "str cannot be used as validator"

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4392]
We saw this error after catalog was updated to CAKN 2.10.

"str cannot be used as validator because it is not a user-defined function"

![image](https://github.com/GSA/data.gov/assets/1392461/8e459731-a105-4085-8c15-a1abffe56deb)

## How to reproduce

Saw in the log for harvest source `/harvest/ioos/`

## Sketch

Maybe it is due to some glitches when one harvesting job runs across two CKAN versions (2.9 and 2.10). If we don't see this any more in the next harvest job on the same source, then we don't have to do anything for this.

**Comment by nickumia-reisys** [comment]
If this keeps happening, then it's for a harvest source that we aren't testing.  This caused test failures all of which we fixed.

**Comment by nickumia-reisys** [comment]
Do you think this line is effecting it (as per the discussion in the linked ticket in the issue)?
- https://github.com/GSA/catalog.data.gov/blob/4dcac20de7674f929eee5d9b63d11c2b84b9850c/ckan/setup/who.ini#L8

**Comment by FuhuXia** [comment]
Saw a similar error when saving a non-federal datajson harvest source, which is fixed in https://github.com/GSA/ckanext-datajson/pull/147. Might be related but this `/harvest/ioos` is not a datajson type.

**Comment by hkdctol** [comment]
This should be resolved by now.

**Comment by FuhuXia** [comment]
![image](https://github.com/GSA/data.gov/assets/1392461/e8def115-567f-4649-bba7-eed55c555dbc)

The issue resurfaced. We need to address it.

**Comment by FuhuXia** [comment]
Use a forked branch while waiting for the [PR on upstream ckanext-spatial ](https://github.com/ckan/ckanext-spatial/pull/312).

**Comment by FuhuXia** [comment]
Change is deployed and issue resolved. Will keep eye on the upstream PR and update requirement when it is merged into next release.
