### ISSUE TITLE
Missing metadata source

### ISSUE THREAD

**Issue by chris-macdermaid** [GSA/data.gov#4397]
## How to reproduce

These DOT records missing a metadata source.

https://catalog.data.gov/dataset/runway-lines
![image](https://github.com/GSA/data.gov/assets/64213093/d50f84c0-cf69-4f9e-b80c-8804c99204c4)

https://catalog.data.gov/dataset/north-american-rail-network-nodes
![image](https://github.com/GSA/data.gov/assets/64213093/902a6a25-0f6b-41e1-a00b-c71f565c5018)

https://catalog.data.gov/dataset/north-american-rail-network-lines
![image](https://github.com/GSA/data.gov/assets/64213093/91cc87b2-7703-4104-92ce-3e0e8668c1d9)

https://catalog.data.gov/dataset/intermodal-passenger-connectivity-database-ipcd1
![image](https://github.com/GSA/data.gov/assets/64213093/8e616942-b438-44e7-9fdb-448db11fbf01)

## Expected behavior

The harvest object would exist and the metadata source would be displayed in the UI.

## Actual behavior

The harvest object in a package_show doesn't exist

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
The issue is tracked here https://github.com/GSA/data.gov/issues/4362
