### ISSUE TITLE
catalog topic csv daily snapshot and USA search custom feed to be placed on permanent store

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#44]
for BSP migration below two daily snapshot CSV files and feed XML need to be persisted in DB or S3.

catalog.data.gov/csv/topic_datasets_11212016.csv [catalog.data.gov/csv/topic_datasets_MMDDYYYY.csv] 
https://catalog.data.gov/usasearch-custom-feed.xml

We also need to migrate the old CSV files (atleast for the this month) to DB or S3 for historical comparision.

**Comment by FuhuXia** [comment]
Both are ready on catalog production. The urls are

https://catalog.data.gov/usasearch-custom-feed.xml

https://catalog.data.gov/topics-csv/ for latest csv, or https://catalog.data.gov/topics-csv/YYYYMMDD for specific dates.
