### ISSUE TITLE
catalog-harvesters are not reporting to new relic

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#440]

**Comment by nickumia-reisys** [comment]
We are using a completely different infrastructure architecture now and harvesting logs are being sent to NR.
- https://github.com/GSA/catalog.data.gov/blob/main/manifest.yml#L96
  ![image](https://user-images.githubusercontent.com/85196563/216667009-85fe75f6-bc98-4273-947d-5ab2cf29b270.png)
  ![image](https://user-images.githubusercontent.com/85196563/216667063-e307cf2b-d2e7-4e2a-a9bb-504981508a30.png)
