### ISSUE TITLE
Add a routing to check egress status for ckan apps

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4407]
We have an egress proxy for each CKAN app to control the outgoing traffic. We noticed that occasionally the egress was disabled for some app, and it can go unnoticed for quite a while. Sometimes CKAN app failed to connect to proxy and caused down time, as described in a [slack thread](https://gsa-tts.slack.com/archives/C2N85536E/p1690550413620689).

We want to run some routing checks on egress status, and get notified if the checks fail.

## Sketch

We can add a GH action running CF task on each app to curl some external URL, 
1. traffic to www.gsa.gov should always go thru.
2. traffic to www.yahoo.com should always be blocked.

**Comment by nickumia-reisys** [comment]
Fully implemented and tested.  Action lives [in catalog](https://github.com/GSA/catalog.data.gov/actions/workflows/egress_check.yml) and will create [issues in catalog](https://github.com/GSA/catalog.data.gov/issues/1019) when it fails.

🗡️ Passed Fuhu's final test:
- https://github.com/GSA/catalog.data.gov/issues/1023
