### ISSUE TITLE
newrelic is installed to wrong python directory

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#441]
newrelic is installed to [`/usr/local`](https://github.com/GSA/datagov-deploy/blob/93fb619b17ba8f58d4a1f3ea8b9c420ea443822e/ansible/roles/monitoring/newrelic/python-agent-ansible/tasks/main.yml#L13) which might be different than `python_home` (on the catalog and inventory instances, this is `/usr/local/lib/python2.7.10`.

**Comment by adborden** [comment]
Instead of just swapping out the hardcoded path to `python_home`, I would suggest moving the dependency to `requirements.txt`. This allows us to better control the version, it also allows us to instrument the harvester (#440) properly.

**Comment by nickumia-reisys** [comment]
We are managing newrelic install with python requirements.txt now (for catalog and inventory), so this is complete (although no longer relevant in it's described form).
