### ISSUE TITLE
⛽ Harvesting 2.0 Planning + CKAN Harvesting Documentation

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4411]
## User Story

In order to get an idea on where harvesting should go, the data.gov Harvesting team wants to track everything that's happened related to harvesting in our codebases and formalize that information into a coherent review document that can: (1) Improve maintainability of CKAN and (2) Drive harvesting 2.0 planning.

## Acceptance Criteria

- [x] GIVEN research has been completed \
  WHEN I look at this ticket \
  THEN there is documentation about harvesting.

## Background

See [proposal document](https://docs.google.com/document/d/13q2i5UG29lsg2cvVd9Ee-P_DFAlfrI0_hcN2qXGLS5U/edit).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Unknown yet.  Deferred to future children tickets.

## Sketch

- [x] Fill out [documentation](https://docs.google.com/document/d/103KGQFP0kt3o7wp99fyp0Bebd-cqr1-TL_M0zu1RZOE/edit#heading=h.85tqc7cks4lc).
- [x] Discuss key/relevant/required features/config/processes.
- [ ] Revise documentation.
- [x] Create a formal Wiki or README somewhere.

**Comment by Jin-Sun-tts** [comment]
[Ckan Plugin documentation](https://docs.google.com/document/d/103KGQFP0kt3o7wp99fyp0Bebd-cqr1-TL_M0zu1RZOE/edit#heading=h.85tqc7cks4lc) :

- ckanext-datagovtheme - done
- ckanext-geodatagov - done
- ckanext-harvest - done
- ckanext-spatial - done
- ckanext-dcat - done

**Comment by nickumia-reisys** [comment]
The work for this ticket is spread between three documents:
1. [Proposal](https://docs.google.com/document/d/13q2i5UG29lsg2cvVd9Ee-P_DFAlfrI0_hcN2qXGLS5U/edit) (mentioned in ticket)
2. [Current System Details](https://docs.google.com/document/d/103KGQFP0kt3o7wp99fyp0Bebd-cqr1-TL_M0zu1RZOE/edit) (mentioned in ticket and @Jin-Sun-tts's comment)
3. [Harvesting Requirements](https://docs.google.com/document/d/1bQLFvn-A8OyC6wStl2Wfs64BoSVj6j1HW3_KzA8cIfI/edit)

**Comment by jbrown-xentity** [comment]
I left a bunch of comments in the harvesting requirements doc. Good work overall! It's very detailed, though not always equally distributed (some things might take minutes, others weeks or months). @nickumia-reisys

**Comment by nickumia-reisys** [comment]
This issue can soon be safely marked as completed.  A big kudos to @Jin-Sun-tts for staying focused and tunneling through the complete mess that CKAN is.  There is a lot of ongoing work and most of this ticket was explorative in nature in how to begin the long-term documentation and planning for the future of Data.gov harvesting.  Key points to highlight:
- A [living document](https://docs.google.com/document/d/103KGQFP0kt3o7wp99fyp0Bebd-cqr1-TL_M0zu1RZOE/edit) that compiles all of the existing CKAN extensions/plugins was given a complete first pass.
  - While thorough and exhaustive, this document is a bit unwieldy to be a primary reference.  
  - An aggregation of the code into flowcharts and/or data transformations and/or pipelines should be completed (see below).
  - As more detail is needed from our "old" system, this document should be updated accordingly.
- A first pass was done at [top-level harvesting requirements](https://docs.google.com/document/d/1bQLFvn-A8OyC6wStl2Wfs64BoSVj6j1HW3_KzA8cIfI/edit) pulling in information, experience and inspiration from: (1) Existing Code + Documentation, (2) Historical Data.gov Harvesting Tickets, (3) Open Data Laws, (4) Previous Planning Work
  - There are a ton of open questions surrounding the specific details that the Data.gov team will accept as its baseline.  These questions should be answered in multiple upcoming meetings.  Before these meetings, the following should occur:
    - [x] Finish going through historical harvesting tickets
    - [x] Add more detail surrounding the https://github.com/GSA/data.gov/issues/4433.
- Once we complete the discussion about top-level harvesting requirements, I believe we'll be in a good position to properly plan the next steps in this saga ♠️

**Comment by nickumia-reisys** [comment]
Having completed https://github.com/GSA/data.gov/issues/4433, we have a more complete picture of what needs to be done and how to act upon it.  We still have to finish the initial review the [harvesting requirements](https://docs.google.com/document/d/1bQLFvn-A8OyC6wStl2Wfs64BoSVj6j1HW3_KzA8cIfI/edit) and answer [open design questions](https://docs.google.com/document/d/1feSHkV-FhnTuZqHw20ID8vi0d9Qj4u8J2xTUalD_4pQ/edit#heading=h.7dgki99nqrsr); however, that is an ongoing discussion and will be iterative as we continue.
