### ISSUE TITLE
Dedupe script is broken

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4412]
## How to reproduce

1. Run the [Check org duplicates](https://github.com/GSA/datagov-dedupe/actions/workflows/check_org_duplicates.yml) action.
2. Run the [Run De-dupe](https://github.com/GSA/datagov-dedupe/actions/workflows/run_dedupe.yml) action on any org with the results.

Background:
- See https://github.com/GSA/data.gov/issues/4409: `fema-gov` had "8000" duplicates of "1" dataset... After running the de-dupe, all of the data was deleted and needed to be re-harvested.

## Expected behavior

Only duplicates deleted.

## Actual behavior

Good datasets deleted.

## Sketch

TBD

**Comment by btylerburton** [comment]
@FuhuXia is this still valid?

**Comment by FuhuXia** [comment]
Cant replicate it. The dedupe action is working fine.
