### ISSUE TITLE
O+M 8/18/2023

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4420]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

Check the [O&M Rotation Schedule](https://docs.google.com/spreadsheets/d/1cF73HkzFuQth3z9voLfVO1Cc4kjBd6ecHGE2gkj5LCc/edit?usp=sharing) for future planning.

## Miscs
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
Check Production State/Actions
- [ ] [README](https://github.com/GSA/data.gov)
> **Note: Catalog Auto Tasks**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.
- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

**Comment by robert-bryson** [comment]
Yesteday's Notes: 

- Harvest emails look good
- Catalog admin prod [alert](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692031339011229), [self resolve](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692033542808479)
- [PR to 11ty site](https://github.com/GSA/datagov-11ty/pull/147) by Crystal
- Catalog web prod [alert](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692035605476189), [self resolve](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692038335489489)
- Another catalog admin prod [alert](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692036251642319), [self resolve](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692041959530349)
- Another catalog admin prod [alert](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692043462880749)
- And another catalog web prod [alert](https://radar-api.service.newrelic.com/accounts/1601367/issues/289261b1-6a42-4252-b0b6-699f9ab042c4?notifier=SLACK_LEGACY)
- Solr follow memory [alert](https://gsa.enterprise.slack.com/files/USLACKBOT/F05MQHE9UDB/alarm___solr-deb2a1db-ed85-follower-2-memorythreshold__in_us_west__oregon_)

**Comment by robert-bryson** [comment]
Notes 2023-08-15:
- Harvest emails ok
- db-solr-sync:
	- ![Image](https://github.com/GSA/data.gov/assets/91547795/f464a6b5-d8fd-49ed-8b55-dc9be2aa5684)
- datagov-11ty snyk bump `chart.js` [PR](https://github.com/GSA/datagov-11ty/pull/148)
- Solr follower-1 memory [alert](https://gsa.enterprise.slack.com/files/USLACKBOT/F05MHQGV6MV/alarm___solr-deb2a1db-ed85-follower-1-memorythreshold__in_us_west__oregon_)
- Catalog admin prod [alert](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692137112515159), [self resolve](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692149073714789)
- Catalog admin prod [alert](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692149676024669)
- Inventory prod [alert](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692150741589689)

**Comment by robert-bryson** [comment]
## 2023-08-16

- Datagov-11ty snyk bump `chart.js` `4.3.1` to `4.3.2` [PR](https://github.com/GSA/datagov-11ty/pull/149)
- Catalog web prod [alert](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692204262628559)
- Harvest emails ok
- db solr sync
	- ![Image](https://github.com/GSA/data.gov/assets/91547795/9a19f27b-e4b6-4e71-a8f0-f160d7087116)

**Comment by robert-bryson** [comment]
## [[2023-08-17]]

- [Out of memory error](https://github.com/GSA/catalog.data.gov/actions/runs/5885957882/job/15963108833#step:6:218) with sitemap job caused action to fail
- DB solr sync
	-  ![Image](https://github.com/GSA/data.gov/assets/91547795/8a56cfc2-eb2e-4e54-abd0-9144f5a38f13)
	- 6k has been somewhat consistent, seems like a lot each day

## [[2023-08-18]]

- Solr follow memory alerts this morning (PDT):
	- 8:15 am follower two [memory threshold](https://gsa.enterprise.slack.com/files/USLACKBOT/F05NDBCV3QV/alarm___solr-deb2a1db-ed85-follower-2-memorythreshold__in_us_west__oregon_)
	- 8:16 am New relic [reports](https://one.newrelic.com/alerts-ai/issue?account=1601367&duration=259200000&state=0951b5d3-e214-7c32-43ea-bc387fd4c99d) 2 or more locations down for catalog
	- 8:46 am New relic [alert ok](https://gsa-tts.slack.com/archives/C4RGAM1Q8/p1692373570365429)
	- 9:07 am follower one [memory threshold](https://gsa.enterprise.slack.com/files/USLACKBOT/F05NV8A7PKK/alarm___solr-deb2a1db-ed85-follower-1-memorythreshold__in_us_west__oregon_)
- DB solr sync
	-  ![Image](https://github.com/GSA/data.gov/assets/91547795/fb906b51-12bf-4ca3-9f40-3747c1f65ebd)
- Sitemap ran successfully [last night](https://github.com/GSA/catalog.data.gov/actions/runs/5898012010/job/15998434428)
