### ISSUE TITLE
SPIKE: Create harvesting workflow using apache airflow.

### ISSUE THREAD

**Issue by rshewitt** [GSA/data.gov#4422]
## User Story
- In order to determine the viability of apache airflow as a data harvesting workflow solution, [data.gov](http://data.gov/) will standup an instance of Apache airflow and run a harvest source through the harvest job lifecycle seen in the [Harvest Job Lifecycle diagram]( https://drive.google.com/drive/folders/13a_3pg6gDoGVU_VMi8kNckCcECV3HDYY )

## Acceptance Criteria

- GIVEN [data.gov](http://data.gov/) wants to explore existing workflow solutions for a new harvesting pipeline and 4 days time, THEN apache airflow and the [harvesting repo](https://github.com/GSA/datagov-harvesting-logic) will be used to determine solution viability and deployment to [cloud.gov](http://cloud.gov/) along with discussion of findings.

## Background

- [Apache airflow](https://airflow.apache.org/)
    - Develop, schedule, and monitor data workflows with python.
    - Well documented and maintaining open source tool
    - Potentially integrate with SSB and/or [cloud.gov](http://cloud.gov/) well. 
- [DAG as a workflow representation](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html)

## Sketch

Do the following in order, as time allows given this is a spike:
- Spin up Apache Airflow locally using docker
- Create a DAG that extracts and validates a DCAT-US catalog (use test examples from harvesting-logic repo)
- Validate ^^ process works
- Validate UI works for exploration of jobs

**Comment by btylerburton** [comment]
Some assumptions to test...
  - Queue
    - Can we spin up multiple workers?
    - Parallelize harvest processing
  - Processing
    - One to many for workers
  - UI
    - Managed access

**Comment by btylerburton** [comment]
I'm going to put my name on this as I'll be devoting some time to it, but that shouldn't preclude others from working on it as well, either collaboratively or in private.

**Comment by rshewitt** [comment]
The airflow scheduler ( airflow version `2.3.0` ) won't detect a DAG using the [TaskFlow API](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/taskflow.html) approach ( e.g. decorating with `task` instead of using `PythonOperator` see comment below as an example ) unless you assign the DAG function invocation to something. For example, this works...
```python 
_ = dag_function()
```

This doesn't work...
```python 
dag_function()
```
When using the latter approach the scheduler log indicates `...WARNING - No viable dags retrieved from [location of dag script.py]`). This seems to conflict with an [example](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/taskflow.html#:~:text=(fahrenheit)-,etl(),-Custom%20Objects) found in the TaskFlow documentation

**Comment by rshewitt** [comment]
using the TaskFlow API approach means less code to write. For example, 
```python
#dag creation has already occurred 
@task(task_id="transform")
def transform():
    # do something
transform() #dag workflow
```
compares to
```python
#dag creation has already occurred
def transform():
  #do something

task1 = PythonOperator(
    task_id='transform',
    python_callable=tranform,
    dag=dag, # attach task to dag
)
task1() #dag workflow
```
Long story short it removes the explicit need for the `PythonOperator` ( in this instance ). It may apply to any conventional airflow operator ( e.g. email, python, bash ).

**Comment by rshewitt** [comment]
I published my branch `airflow-etl-test-reid`. it's intended as a WIP. I paired with @jbrown-xentity earlier and went over my current findings. we discussed the possibility of tasks needing to share data between themselves ( e.g. extract to transform ) and based on what i've read tasks are meant to execute in isolation but airflow offers a cross-task communication mechanism called [XComs](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/xcoms.html) which allows for this. the amount/size of information passed in order to see a reaction in airflow could be a valuable test.

**Comment by rshewitt** [comment]
if sharing data between tasks proves unacceptable one alternative could be having each task pull data from s3, process it, then load it back to s3. i'm unsure if this is better.

**Comment by rshewitt** [comment]
looks like tasks push to xcom by [default](https://github.com/apache/airflow/blob/1.8.2/airflow/models.py#L1392-L1394) if they return a value that is not `None`

**Comment by rshewitt** [comment]
some run information when extracting and validating a [large spatial dataset](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/tests/datajson-samples/large-spatial.data.json). Notably the `Max Run Duration`. This could be a miscalculation based on limited information from the task. it's probably something to do with the first run start and last run start.

<img width="595" alt="Screenshot 2023-08-21 at 12 29 04 PM" src="https://github.com/GSA/data.gov/assets/92057378/e9c6d975-9d2d-4660-a0dc-acc2f713ab1d">

**Comment by jbrown-xentity** [comment]
To summarize: we have a working version of a DAG (a harvest) that does the extract of a full DCAT-US catalog and distributes the individual datasets into a new workflow where they get validated independently.
There are 4 things we would like to investigate further:
- The ability of airflow to handle one-to-many streams (and then one-to-one after one-to-many)
- How can branching be used to implement railway programming and handle failures gracefully? https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#branching
- Creating DAG's based on a template and list of configs: https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#dynamic-dags (so the UI looks similar to current data.gov harvesting, in each harvest source is represented).
- Deploy a working UI to cloud.gov (and integrate any of the current working features)

**Comment by rshewitt** [comment]
Test case where 2 of the dcatus records in the catalog are invalid. 

![Screenshot 2023-08-22 at 12 43 19 PM](https://github.com/GSA/data.gov/assets/92057378/c37b7aed-0a4c-43ef-b697-9e97ad03e84c)

Proceeded by only 1 load ( the valid record ). 

![Screenshot 2023-08-22 at 12 43 29 PM](https://github.com/GSA/data.gov/assets/92057378/2461f2ea-b42d-4458-8e9d-8fb7eac3f880)

**Comment by rshewitt** [comment]
Test case where the extraction failed resulting in all downstream tasks ( validate & load ) to fail.

![Screenshot 2023-08-22 at 12 48 40 PM](https://github.com/GSA/data.gov/assets/92057378/3997a1ad-6de2-4923-9d6f-573d94b5ffcd)

**Comment by rshewitt** [comment]
The picture above indicates the validate and load were kicked off which we may want to avoid entirely but looking at the task duration below of the validate shows that despite the job kicking off no time was spent on it. 

![Screenshot 2023-08-22 at 12 58 42 PM](https://github.com/GSA/data.gov/assets/92057378/9f2487a8-2d73-41e0-937e-72c99ef7cc6d)

**Comment by rshewitt** [comment]
i'm going to use a subset of the current catalog harvest sources using this [query](https://catalog.data.gov/api/action/package_search?fq=dataset_type:harvest%20AND%20source_type:datajson%20AND%20frequency:DAILY&rows=1000) as the input for dynamically generating DAGs.

**Comment by jbrown-xentity** [comment]
For cloud.gov installation, would utilize pip installation on python runner, probably with redis extras: https://airflow.apache.org/docs/apache-airflow/1.10.10/installation.html#extra-packages

**Comment by robert-bryson** [comment]
Breaking off the deploy onto cloudgov work into https://github.com/GSA/data.gov/issues/4434

**Comment by rshewitt** [comment]
in response to my previous [comment](https://github.com/GSA/data.gov/issues/4422#issuecomment-1684095157) i've since found that DAG’s are identified by whether they exist in the global namespace of the file ( i.e. if they are in `globals()`) when the file is processed. function invocation or class instantiation without storing the value in a variable does not add to the global namespace of the file. since `globals()` returns a dictionary not using a variable is not assigning a key to the value.

**Comment by rshewitt** [comment]
the size limit for an xcom using a postgres backend looks to be [1 GB](https://www.postgresql.org/docs/current/limits.html#:~:text=field%20size,1%20GB). I've seen this value referenced in other articles as well.

**Comment by rshewitt** [comment]
docker crashed after attempting to process 16 instances of a dataset on my local machine. it appeared to be a memory issue.

**Comment by btylerburton** [comment]
let's do some real load testing on cloud.gov after @robert-bryson's work is stood up.

**Comment by rshewitt** [comment]
Something to note on [callback execution of tasks](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/callbacks.html#:~:text=Callback%20functions%20are%20only%20invoked%20when%20the%20task%20state%20changes%20due%20to%20execution%20by%20a%20worker.%20As%20such%2C%20task%20changes%20set%20by%20the%20command%20line%20interface%20(CLI)%20or%20user%20interface%20(UI)%20do%20not%20execute%20callback%20functions.). This is in reference to my work on error handling.

**Comment by rshewitt** [comment]
callbacks functions are provided with the associated task context. here's a [list of the variables](https://airflow.apache.org/docs/apache-airflow/stable/templates-ref.html) within a context

**Comment by rshewitt** [comment]
What kind of techniques do we have to control the flow of information when something wrong occurs?
- [branching](https://airflow.apache.org/docs/apache-airflow/1.10.10/concepts.html#branching)
- [trigger rules](https://airflow.apache.org/docs/apache-airflow/1.10.10/concepts.html#trigger-rules)
- [callbacks](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/callbacks.html)

**Comment by rshewitt** [comment]
using the TaskFlow API approach requires calling the tasks in the workflow in order for them to work properly. 
```python
# TaskFlow API approach
@dag(*args,**kwargs)
def test_pipeline():

  @task(task_id="task1")
  def task1():
    return "example"
  
  @task(task_id="task2")
  def task2():
    return "another example"

  task1() >> task2() #calling the functions

_ = test_pipeline()

#Traditional approach
with DAG(**kwargs) as dag: #using a context manager because decorating would be using TaskFlow. i'm sure you can use a context manager with TaskFlow and it would work fine.

  task1 = EmptyOperator(task_id="task1")
  task2 = EmptyOperator(task_id="task2")

  task1 >> task2 #not calling the operators

_ = dag() #i figure this is still applicable??
```

issue [comment](https://github.com/apache/airflow/issues/27859#issuecomment-1326922559) for reference on TaskFlow approach.

Basically, if you're using operators then you don't need to invoke them. if you're using functions decorated with `task` then you need to invoke them.

**Comment by rshewitt** [comment]
Rule of thumb, anytime branching is implemented ALWAYS consider the `trigger_rule` of downstream processes. By default tasks have a `trigger_rule` of `"all_success"` meaning all immediate parents tasks must succeed. In the event of a branch, the successful branch is followed and the failure branch is not causing all tasks in the failure branch to be skipped. `skipped` is a state of a task. `skipped` != `success`. a common pattern is to have branches join together eventually ( e.g. a  bulk `load` ). this load would be skipped if a branch converging into it was skipped as a result of the branching process.

**Comment by rshewitt** [comment]
We could potentially store our validation schema's as [variables](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/variable/index.html) in airflow.

**Comment by rshewitt** [comment]
```  
                     -> task C (true)    \
                    /
 task A -> taskBranch                            -> task F
                    \  ->  task E(Dummy)(false) /
```

^ this works.

apparently branching requires at least 2 tasks. one for `true` and one for `false`. it seems like `taskBranch` can't create a direct dependency to `task F` if a false task isn't provided so a dummy operator needs to be used. 

```  
                     -> task C (true)  \
                   /
 task A -> taskBranch   -----            -> task F
```

^ this doesn't work.

**Comment by rshewitt** [comment]
Error extracting `commerce_non_spatial_data.json_harvest_source_workflow` in airflow. The size of the downloaded json is too large for xcom to push (i.e. `airflow.exceptions.UnmappableXComLengthPushed: unmappable return value length: 1609 > 1024`). [source](https://github.com/apache/airflow/blob/b9acffa81bf61dcf0c5553942c52629c7f75ebe2/airflow/exceptions.py#L139)

**Comment by rshewitt** [comment]
Error extracting `bls_data_workflow`. The airflow log indicates a json decode error. Attempting to download the json file manually indicates a `403` http status code.
