### ISSUE TITLE
Create new page featuring Data.gov vision/mission

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4432]
## User Story

In order to share Data.gov vision/mission statements, Data.gov needs to create a new page featuring this content linked from home page.

## Acceptance Criteria

- [ ] GIVEN user navigates to data.gov \
  THEN there is a link to a page that features Data.gov vision and mission statements.

## Sketch

- [x] Review samples of other website pages featuring vision/mission
- [ ] Design layout/graphics of a page featuring Data.gov vision/mission
- [ ] Create link from data.gov home page

**Comment by hkdctol** [comment]
We have mission/vision language we agreed to https://docs.google.com/document/d/1N3q6PQooi037OwRQArnfbttImcuqFwSk7DbJNMnLkic/edit?usp=sharing

**Comment by hkdctol** [comment]
@CarolinaC-REI I didn't necessarily have a strong reaction to one example over another, but here are some https://docs.google.com/document/d/1LefM-bmv0_YKM6jWMZwowK1qOwYKRHRZ6DpDMyNMDBk/edit?usp=sharing

**Comment by CarolinaC-REI** [comment]
@hkdctol Thank you for sharing the example document. I will work on a few mockup options this week. Should be able to share with you and the team by beginning of next week.

**Comment by CarolinaC-REI** [comment]
@hkdctol I have made some changes to the mockup based on today's feedback. Please find the link below:
https://www.figma.com/proto/pzf102CQrXYRweRn7FnAC1/Data.gov-homepage?page-id=91%3A903&type=design&node-id=510-2618&viewport=-5079%2C1473%2C0.5&t=3ocSOvUM7r1s3WC0-1&scaling=min-zoom&mode=design

**Comment by hkdctol** [comment]
@crysacarter and others please review and comment

**Comment by hkdctol** [comment]
I like the third approach which was mission leading to another page, with the metrics graphs moved to beneath on main page

**Comment by btylerburton** [comment]
Pages 9-11 look really nice. I believe that is the same option Hyon was leaning towards.

**Comment by crysacarter** [comment]
I'm in the same camp - The third approach

**Comment by CarolinaC-REI** [comment]
@btylerburton Please find attached the images for the mission section. Please let me know if you need anything else. Thank you
[mission-images.zip](https://github.com/GSA/data.gov/files/13745800/mission-images.zip)

**Comment by btylerburton** [comment]
Thank you for the setup @CarolinaC-REI . I'm going to move this in the sprint backlog as it's ready for implementation.

**Comment by robert-bryson** [comment]
WIP build at https://federalist-2ac784db-2321-4734-8d02-933835d88304.sites.pages.cloud.gov/preview/gsa/datagov-11ty/4432-new-mission/

**Comment by FuhuXia** [comment]
The graphs do not look right after the change. 

Before 
![image](https://github.com/GSA/data.gov/assets/1392461/2d897d5e-1812-4840-b58e-950c4b47f3bb)

After
![image](https://github.com/GSA/data.gov/assets/1392461/20f9de5f-c8f8-43e4-a46b-db2de1e60d50)

**Comment by hkdctol** [comment]
It's duplicative to have both the About Data.gov and Mission sections--shouldn't it be just the Mission section now--and then the About page has the link to the timeline?

**Comment by hkdctol** [comment]
Also in the current Mission section -- the word "and" is where there is a blue dot in the background image--so it's hard to see--can the placement be adjusted? Not sure if that's a question for @CarolinaC-REI

**Comment by btylerburton** [comment]
I added my feedback to the PR. We shouldn't need any new assets from Carolina.

> The graphs do not look right after the change.

I don't see this issue, @FuhuXia. Perhaps Robbie fixed it, or you were resizing across a breakpoint? The chart has never been fully responsive. If you change breakpoints it needs a page refresh to repaint.

**Comment by FuhuXia** [comment]
@btylerburton ok, the chart issue is likely due to  caching. it is fine incognito.

**Comment by hkdctol** [comment]
I reviewed again, and on the About page, I would delete the section titled "What standards were used to develop the metadata displayed on Data.gov?" because it's not accurate (there are other than DCAT datasets) and the later section links to what will be the updated how to get data on Data.gov article, which will be more detailed/accurate

**Comment by rshewitt** [comment]
idk if it's worth fixing but this is what the graphic looks like in chrome configured to dark mode

![Image](https://github.com/GSA/data.gov/assets/92057378/e9893f7f-9dd8-4031-8a0e-fc6c5e4bc7c1)

**Comment by btylerburton** [comment]
@CarolinaC-REI while we're at it, if there's any tweaks we could do to help with that dark mode issue above, that would be helpful. thanks!

**Comment by CarolinaC-REI** [comment]
@btylerburton Sure thing, I will adjust to make sure they are dark mode friendly. Thank you for all your feedback.

**Comment by CarolinaC-REI** [comment]
@btylerburton @robert-bryson Please find attached the new assets. I have added a new version for the background image, please let me know if you are still having issues on fitting the image with the content. Thank you
[new-assets.zip](https://github.com/GSA/data.gov/files/14424942/new-assets.zip)

**Comment by CarolinaC-REI** [comment]
@btylerburton Regarding the dark mode issue. I have tested on my end and was not able to replicate the issue. I checked with @rshewitt and it seem that this is no longer an issue. Please let me know if you are still seeing on your end and I would be happy to take another look.

**Comment by robert-bryson** [comment]
All items in `new-assets.zip` uploaded to s3.
