### ISSUE TITLE
🍀 Document the FOUR Data Pipelines

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4433]
## User Story

In order to inform existing and new harvesting processes and procedures, the Data.go Architect Team wants to document the FOUR pipelines that all harvesting travels through.  These pipelines will either be (1) optimized in the current system or (2) fed into building a better new system from the start.

## Acceptance Criteria

- [x] GIVEN research and analysis has been done surrounding the pipelines \
  WHEN I look at this ticket \
  THEN there is documentation about how the pipelines are structured with supporting details or insight into the complex intricacies

## Background

- https://github.com/GSA/data.gov/issues/4411
- [CKAN Extension/Plugin Documentation](https://docs.google.com/document/d/103KGQFP0kt3o7wp99fyp0Bebd-cqr1-TL_M0zu1RZOE/edit#heading=h.e4ksfy9ung6x)
- [The CKAN Harvesting Interface](https://github.com/ckan/ckanext-harvest#the-harvesting-interface)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
...

## Sketch

- Work through the data lifecycle and pipeline structure for each of the following pipelines
    -  [x] `file json DCAT`
        - Classes of concern: `DataJsonHarvester`, `DatasetHarvesterBase`, `HarvesterBase`
    - [x] `file xml FDGC/ISO`
        - Classes of concern: `GeoDataGovDocHarvester`, `DocHarvester`, `GeoDataGovHarvester`, `SpatialHarvester`, `HarvesterBase`
    - [x] `file xml waf FDGC`
        - Classes of concern: `GeoDataGovWAFHarvester`, `WAFHarvester`, `GeoDataGovHarvester`, `SpatialHarvester`, `HarvesterBase`
    - [x] `api json ARCGIS`
        - Classes of concern: `ArcGISHarvester`, `SpatialHarvester`, `HarvesterBase`
    - Note: Each pipeline consists of a source file interface (file, api, waf), a file type association (json, xml) and a schema 
specification (dcat, fdgc, arcgis).  The idea behind specifying these is to highlight areas of abstraction to make the code more relevant and reusable.  A proposed NEW pipeline consists of `api json DCAT` for large DCAT data.json files that are unwieldy when processed as a single entity.
    - `api json DCAT`
        - PROPOSED
- Data lifecycle consists of: (1) Source creation, (2) Source execution (job run) schedule, (3) Gather Stage, (4) Fetch Stage, (5) Import Stage
  - Note: the current harvesting methodology does the create/update/delete/etc at non-sequential times through the gather/fetch/import stages.  Be sure to note the real sequence as it stands currently.  If we decide to optimize or change something, that should be done as follow on work.

**Comment by nickumia-reisys** [comment]
Note: TWO harvesting pipelines have been deprecated (I believe both of these are FGDC/ISO, but not sure):
- `api csw ??? ???`
- `api cms ???`

**Comment by nickumia-reisys** [comment]
Comment is in history.  I deleted it to make the ticket cleaner.  See diagrams below for the most up to date information.

**Comment by btylerburton** [comment]
Link to MD Translator spike: https://github.com/GSA/data.gov/issues/4200

**Comment by nickumia-reisys** [comment]
<details close>
<summary>DCAT Pipeline initial pass complete.</summary>
<br>

![dcat](https://github.com/GSA/data.gov/assets/85196563/a149c4a1-190f-4525-8ba0-3247fc1afe40)

</details>

... Moving on to `file xml FDGC/ISO`

Just as a random note, our DCAT code is much more unorganized compared to the spatial upstream code...

**Comment by nickumia-reisys** [comment]
<details close>
<summary>Single XML Pipeline initial pass complete.</summary>
<br>

![single_xml](https://github.com/GSA/data.gov/assets/85196563/aefb436c-3f99-4aa9-bad9-79ab1325863f)

</details>

... Moving on to `file xml waf FDGC/ISO` tomorrow

**Comment by nickumia-reisys** [comment]
<details close>
<summary>WAF XML Pipeline initial pass complete.</summary>
<br>

![waf_xml](https://github.com/GSA/data.gov/assets/85196563/eeb25e72-5ca3-4d40-9277-f0fc0c7794f6)

</details>

... Moving on to `api json ARCGIS` next

**Comment by nickumia-reisys** [comment]
<details close>
<summary>ArcGIS Pipeline initial pass complete.</summary>
<br>

![arcgis](https://github.com/GSA/data.gov/assets/85196563/e977564f-c274-410e-941b-01e0d181cfd9)

</details>

... I'm done? 🎉

**Comment by nickumia-reisys** [comment]
The diagrams in the comments above represent the core of the harvesting optimization problem.  What happens when.. What errors are not being captured... What assumptions are made that fail to be true.. The next step is reviewing the code, abstracting it into meaningful chunks, testing the functionality, preserving the best parts and fixing the broken parts.  One of the corner stones of implementing a new version of this code deals with the [following requirement](https://docs.google.com/document/d/1bQLFvn-A8OyC6wStl2Wfs64BoSVj6j1HW3_KzA8cIfI/edit):
> 1.2.3 Data.gov should be able to adapt to new data formats not originally accounted for in its design.

The [controller diagram](https://drive.google.com/file/d/1jExSqgB5H_fkvdO85CGgQob0y8CNiX4V/view) highlights some high-level abstractions for input/output definitions.  However, for example, within the `extract` component, we want to be able to support multiple file types (and possibly new ones, i.e. `rdf`), so creating an abstraction for between "data download" and "data parsing/input" would allow us to hook in a new file type.  Further discussion will ensue and we'll answer a lot of [open questions](https://docs.google.com/document/d/1feSHkV-FhnTuZqHw20ID8vi0d9Qj4u8J2xTUalD_4pQ/edit#heading=h.7dgki99nqrsr).  From there, it'll be easier to start implementing and executing on this work.

**Comment by nickumia** [comment]
@btylerburton This might be worth a revisit as a check-in with the current Harvester milestones
