### ISSUE TITLE
CKAN does not capture user login event any more

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4436]
We made an effort to capture user login and logout events.
- https://github.com/GSA/data.gov/issues/2867

But after [CKAN2.10 deployment](https://github.com/GSA/catalog.data.gov/pull/985), login event is not captured any more, as shown in the catalog-admin NewRelic log. Same for Inventory. 

![image](https://github.com/GSA/data.gov/assets/1392461/a079e09f-04e6-4581-b1bb-a91367e64941)

## How to reproduce

Log in to catalog and search for "logged in successfully" in catalog-admin NewRelic log. 

## Expected behavior

See the entry.

## Actual behavior

No entry.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
Code to put api token logging: [load_user_from_request](https://github.com/ckan/ckan/blob/ckan-2.10.1/ckan/config/middleware/flask_app.py#L321)

Important functions:
- [`get_user_from_token`](https://github.com/ckan/ckan/blob/ckan-2.10.1/ckan/lib/api_token.py#L118)
- [`_get_user_for_apitoken`](https://github.com/ckan/ckan/blob/ckan-2.10.1/ckan/views/__init__.py#L122)

-----

CORRECTION!

API Token is being logged: [`log.debug(u'Received API Token: %s' % apitoken`)](https://github.com/ckan/ckan/blob/ckan-2.10.1/ckan/views/__init__.py#L139).  However, this requires `debug` at the `ckan` level, which is currently set to `info` for catalog and inventory.  While it's not the most effective solution.  To get the specific user directly, we'd need to submit a PR upstream to log the user (instead? or as well?).  We could add a [`log.info(u'User used API Token: %s' % user)`](https://github.com/ckan/ckan/blob/ckan-2.10.1/ckan/views/__init__.py#L141)... but it requires team discussion.

**Comment by FuhuXia** [comment]
Or extend [identify() in IAuthenticator](https://github.com/ckan/ckan/blob/master/ckan/plugins/interfaces.py#L1671) in `ckanext-saml2auth` or a new `ckanext-datagovcommon` with the following code:

```python
def identify(self):
    if current_user.is_authenticated and current_user.is_active and not session.get('last_active'):
        log.info('User {} logged in{}'.format(
            current_user.name, 
            ' via saml' if session.get('_saml_session_info') else ''
        ))
```

**Comment by Jin-Sun-tts** [comment]
The UI login were fixed to have the log.info in the 2.10 condition in the saml2auth.py file.  While working on the solution to capture API login too, added identity  in the plugin.py file to extend in IAuthenticator. So we do not need the login info in the saml2auth location anymore as the identify function log both situation. here are the test result from local:

From UI login:
![Image](https://github.com/GSA/data.gov/assets/104456257/2a9cd3ad-93c1-40c8-a1ae-83efd0db259f)


From curl call:
![Image](https://github.com/GSA/data.gov/assets/104456257/073d539f-b10b-4722-8c14-eb9ebedc06fa)

**Comment by Jin-Sun-tts** [comment]
We have the change in gsa/ckanext-saml2auth  create_user_via_saml.log_210 branch. Requested PR to upstream https://github.com/keitaroinc/ckanext-saml2auth/pull/92
