### ISSUE TITLE
[2023.08.28] Invicti Scan Catalog MongoDB Vulnerability

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4439]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 2023.08.28
**Severity:** HIGH
**Due date:** 2023.09.28

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.df0ffb7howvl

**Comment by nickumia-reisys** [comment]
False alarm.  We do not have a MondoDB instance in our application stack.

**Comment by nickumia-reisys** [comment]
Follow-on conversation: https://gsa-tts.slack.com/archives/C2N85536E/p1695315668061409

**Comment by FuhuXia** [comment]
Same vulnerability shows up again in SecOps Invict September 2023 report, claiming `first seen 9/9/23`.
