### ISSUE TITLE
Inventory user housekeeping

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4457]
We need Inventory user to match what we have on spreadsheet submitted via google form application.  Delete those users that are not listed on the spreadsheet. 

## How to reproduce

We have **126** users listed under https://inventory.data.gov/user/
Some are gmail and yahoo users created recently.

## Expected behavior

We should only have
- **one** user for NewRelic synthetic monitoring token
- **9** sysadmin users, listed in `sysadmin-users` cf environment variable. 
- those listed on the spreadsheet via google form. **85** on the list as of now.

## Actual behavior

More users than listed.

## Sketch
- [x] Add detailed steps for user creation and deletion. (Done by [this PR](https://github.com/GSA/datagov-account-management/pull/535).)
- [ ] Investigate how gmail/yahoo users were created after we deploy https://github.com/GSA/data.gov/issues/4160. Create and fix any issue if found.
- [ ]  Delete users that are not listed.
- [ ]  Check for user email duplicate. Make sure all emails are lowercase.

**Comment by FuhuXia** [comment]
To find out which user does not belong to any organizations, we can use the combination of api calls 
- `/api/action/user_list `and 
-  `/api/action/organization_list_for_user?id=< username >`

**Comment by FuhuXia** [comment]
The yahoo and gmail user accounts were created due to 
- https://github.com/GSA/data.gov/issues/4297

So unless this #4297 is fixed, there is no meaningful housekeeping canbe done.

**Comment by crysacarter** [comment]
[CY 2023 Inventory.data.gov User List .xlsx](https://github.com/GSA/data.gov/files/12563250/CY.2023.Inventory.data.gov.User.List.xlsx)

**Comment by FuhuXia** [comment]
File CY.2023.Inventory.data.gov.User.List.xlsx is attached and downloaded.

**Comment by FuhuXia** [comment]
Deleted users from catalog and inventory that are not on the:
CY 2024 Catalog.data.gov User List .xlsx
CY 2024 Inventory.data.gov User List.xlsx
