### ISSUE TITLE
Harvester 2.0: Deploy mdTranslator on cloud.gov

### ISSUE THREAD

**Issue by rshewitt** [GSA/data.gov#4467]
## User Story

In order to have a transformation service available to the harvester 2.0 pipeline, data.gov wants deploy an instance of [mdTranslator](https://github.com/adiwg/mdTranslator) on cloud.gov. 

## Acceptance Criteria

- [ ] GIVEN an mdTranslator app deployed on cloud.gov \
  WHEN a request is made against the service  \
  THEN a response containing the translated metadata is provided 

## Background

- [harvester 2.0](https://github.com/GSA/data.gov/wiki/Harvesting-2.0)
- mdTranslator is mature, actively worked on, we have direct contact with those that work on it, and it supports metadata standards we care about.
- example [api](http://34.201.136.147:3002/api/v3)
- [mdTranslator rails API](https://github.com/adiwg/mdTranslator-rails)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

none

## Sketch

- Standup local instance of mdTranslator ( optional )
  - Capture local deployment instructions in README
- Determine repo to use ([Jin's](https://github.com/GSA/mdTranslator)/[Aspenwall's](https://github.com/adiwg/mdTranslator/tree/feature/DCAT-US-v1)/[ADIWG `develop`](https://github.com/adiwg/mdTranslator))
- Determine repo to store the code
- Write cloud foundry [manifest](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html) using [ruby buildpack](https://docs.cloudfoundry.org/buildpacks/ruby/index.html)
- Push and debug 
- Integrate with github actions for testing and deployment 
  - Use the tests which come from the repo you choose

**Comment by rshewitt** [comment]
macos has a system ruby pre-installed. if you want to install mdTranslator locally and have a mac make sure to install a version manager like `RVM` or `rbenv`.

**Comment by rshewitt** [comment]
- update from call with johnathan
  - we're going to use the [science base api](https://api.sciencebase.gov/mdTranslator) for the moment
    - science base has been/is currently in hot water for violating SLA. 
    - we're holding off on deploying our own instance of the rails API and the translator gem on cloud.gov.
  - unless we need to add our own features sooner rather than later we may be good just sticking to their [rail repo](https://github.com/adiwg/mdTranslator-rails) and [translator repo](https://github.com/adiwg/mdTranslator) ( i.e not using a fork )
  - dcatus reader could be ready at the beginning of the year.
  - [mdtoolkit docker registry](https://hub.docker.com/u/mdtoolkit)

**Comment by rshewitt** [comment]
[sandbox branch](https://github.com/GSA/datagov-harvesting-logic/tree/transform-science-base-api) with example post to mdtranslator converting fgdc to iso19110. I can probably just read the file instead of parsing it as a tree.

**Comment by rshewitt** [comment]
[science base mdtranslator api](https://api.sciencebase.gov/mdTranslator/api/v3/translator) returns a `200` response despite errors existing in the [input fgdc dataset](https://catalog.data.gov/dataset/national-park-boundaries)
- `ERROR: ISO-19115-1 writer: spatial reference system identifier is missing: CONTEXT is resource spatial reference system`
- `ERROR: ISO-19115-1 writer: spatial reference system type is missing: CONTEXT is resource spatial reference system`

There's a [forceValid](https://api.sciencebase.gov/mdTranslator/api/v3#:~:text=forceValid%3D%20%5Btrue%20%7C%20false%5D%20%3A) option which substitutes required content ( true = substitue; false = don't substitute ). Both cases includes the errors in the response content.

**Comment by rshewitt** [comment]
according to the mdtranslator api documentation "if validation errors prevent the writer from generating a return, messages will be returned as 'text/plain'". In that case, we would have to parse the response content to derive meaning from it. So far it seems as long as the response is okay ( e.g. 200 ) regardless of whether the transformation is successful the response contains what could be transformed.

**Comment by nickumia-reisys** [comment]
A tangential point... If we would be implementing our own version of the mdTranslator and the API configuration is separate from the translator logic, details on the response of the API seem to be biased and no necessarily representative on what we would be expecting in our setup.

**Comment by rshewitt** [comment]
mdtranslator rails app uses ruby 2.7.7. cf ruby buildpacks don't support 2.x. need to bump ruby to deploy.

**Comment by rshewitt** [comment]
mdtranslator is deployed [here](https://mdtranslator-dev-surprised-aardvark-te.app.cloud.gov/api/v3/translator). parts of the ui aren't going to work but since we only care about the api it doesn't matter. that instance is using `develop`. this comment is no longer relevant.

**Comment by rshewitt** [comment]
bare bone mdtranslator app is deployed [here](https://mdtranslator-dev-busy-hyrax-ei.app.cloud.gov/translates). this route only accepts posts. here's a python implementation as an [example](https://github.com/GSA/datagov-harvesting-logic/blob/transform-science-base-api/harvester/transform/mdtranslator.py). you can get some example data [here](https://api.sciencebase.gov/mdTranslator/demo)

**Comment by rshewitt** [comment]
i'm going to remove as much content as needed from the app which derived from the rails start project utility before I commit anything to the transformation [repo](https://github.com/GSA/datagov-harvest-transformer)

**Comment by rshewitt** [comment]
[sinatra](https://sinatrarb.com/intro.html) could be a lighter alternative than rails

**Comment by rshewitt** [comment]
blocked until cf credentials are stored in repo

**Comment by rshewitt** [comment]
dropped instances to 0. app couldn't deploy using 64mb so bumped it to 128.
