### ISSUE TITLE
Configure S3 to store Airflow Logs

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#4470]
Airflow can store logs in a variety of ways. Should we want to use the deploy scenario of Airflow on Cloud Foundry, we would want to store the logs externally. There is functionality to allow [writing logs to `s3`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/logging/s3-task-handler.html) that uses a `s3` connector to handle the auth. 

See additional context https://github.com/GSA/data.gov/issues/4434 and https://github.com/GSA/datagov-harvester/pull/1.

## How to reproduce

1. View the logs on a dag run (for [example](https://test-airflow-webserver.app.cloud.gov/dags/arm_data.json_workflow/grid?execution_date=2023-09-26T00%3A00%3A00%2B00%3A00&tab=logs&dag_run_id=scheduled__2023-09-26T00%3A00%3A00%2B00%3A00&task_id=extract_dcatus)) on the https://test-airflow-webserver.app.cloud.gov/ deployment. 
2. See error in the `cf app` logs: 
![image](https://github.com/GSA/data.gov/assets/91547795/83fe3b75-d08d-4bc7-aa2d-6be3dd3a5ef2)

## Expected behavior

Populated logs

![image](https://github.com/GSA/data.gov/assets/91547795/fe4a473a-920d-496f-b2b8-86dffbfdc353)

## Actual behavior

No logs

![image](https://github.com/GSA/data.gov/assets/91547795/e3be33e5-0441-4ec4-b1fa-ff01b78b8ba9)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

- Check the `s3` service is set up correctly to allow Airflow to connect
- Check the `s3` connection in Airflow is set up correctly
- ???

**Comment by btylerburton** [comment]
Question for the team, if we have logs in New Relic, do we want them also in S3?

**Comment by robert-bryson** [comment]
I suppose it doesn't make sense to double store the logs. I believe the idea behind the s3 connector is that all the various airflow components can drop logs in one place and then you can use whatever you'd like to aggregate them from there. Since our team is already using New Relic for this, it probably isn't necessary. Should we icebox or close this?

**Comment by btylerburton** [comment]
I'm going to close it. If we need to revive it should be easy enough since it has the h20 label.

**Comment by btylerburton** [comment]
When the airflow configuration changes (worker scaling, etc), the logs are not guaranteed to be accessible, from what I've seen, so I believe this is worth reopening and revisiting in the future. 

![Image](https://github.com/GSA/data.gov/assets/104455281/53816643-2dec-4058-a0d6-cbd857263232)

**Comment by nickumia** [comment]
It seems like there isn't a good consensus on operational and maintenance procedures.. If the logs are in NR, then creating a process for linking to those logs (i.e. doing an API call to fetch the logs in whatever viewer makes sense might work OR just going to NR being an expert in finding logs haha...).  The alternative of having "duplicate" logs only hurts if there's a heavy cost or maintenance burden involved, neither of which sound like it's the case.  NR only stores 3 months of logs as is, soo... S3 would give you longer log storage too.
