### ISSUE TITLE
Airflow on CF: CeleryExecutor/redis communication issues

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#4471]
Airflow can use a variety of executors. Should we want to use the deploy scenario of Airflow on Cloud Foundry, we would need to fix the `CeleryExecutor`. In the current deployment (https://test-airflow-webserver.app.cloud.gov/), there is an issue somewhere around the communication of the application components, the celery workers, and redis. 

See additional context https://github.com/GSA/data.gov/issues/4434 and https://github.com/GSA/datagov-harvester/pull/1.

## How to reproduce

1. Inspect the `test-airflow-redis` service and various components of the current test deployment:
![image](https://github.com/GSA/data.gov/assets/91547795/0ac09644-28a4-45ec-bf1e-16f58791f7c0)
2. See that they are not communicating correctly in flower: https://test-airflow-flower.app.cloud.gov/

## Expected behavior

Something akin to this: 

![image](https://github.com/GSA/data.gov/assets/91547795/63a1341d-7ae9-4c97-b6aa-b0f253781a11)

## Actual behavior

No workers :/

![image](https://github.com/GSA/data.gov/assets/91547795/f1bd4966-c7e6-418f-b6dd-2a85aea27591)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

- Not sure what would be useful here, I have been experimenting with using [the `docker-compose.yml` version](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html) of the deploy locally and contrasting that with the config/env on the cf deploy

**Comment by hkdctol** [comment]
Icebox for now, because currently not planning on using Celery Executor

**Comment by btylerburton** [comment]
Rudimentary configuration of CeleryExecutor with Webserver, Scheduler and Worker [is complete](https://github.com/GSA/data.gov/issues/4539). 

We will add additional components (Flower, Triggerer, DagProcessor) at a later date, but communication issues have been solved.
