### ISSUE TITLE
Attempt to install New Relic infrastructure agent

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4474]
## User Story

In order to monitor our system more effectively, @GSA/data-gov-team wants to attempt to install the NR Infrastructure agent.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

After speaking with NR support on 9.27.23, we determined that we had configured the NR agent at the app level but not at the container level. We have doubts as to whether this is possible due to the K8s cluster being abstracted away from us by cloud.gov, but we plan to follow the NR tutorial they provided and see what's possible.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

Ensure that the agent is not exfiltrating information to sites other than NR to the best of our ability.

## Sketch

- [x] Follow instructions on NR site ([link](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent/))
- [x] Attempt to install without Cloud.gov support
- [x] Contact cloud.gov support if we can't do it by ourselves

**Comment by robert-bryson** [comment]
According to the docs, should be working with PRs: https://github.com/GSA/data.gov/pull/4500 and https://github.com/GSA/catalog.data.gov/pull/1111

Cannot test until first PR is merged and New Relic is allowed through the egress proxy.

**Comment by robert-bryson** [comment]
I have been having an issue with my machine's docker environment due something with the `datagov-deploy` redirects happening in the `Dockerfile` for postgres. Should be fixed with https://github.com/GSA/catalog.data.gov/pull/1143. Thanks James for your help on this. 

Should be back on track to being able to debug the NR connectivity issues.

**Comment by gujral-rei** [comment]
@FuhuXia or @btylerburton, I came across this ticket while researching how to install New Relic on docker containers in the Cloud.gov environment. Have you seen this, or if it is of any help in the context of our problem?

https://github.com/GSA-TTS/FAC/issues/1007

**Comment by btylerburton** [comment]
@gujral-rei AFAIK this is for the new APM agent, which we already have configured.

**Comment by FuhuXia** [comment]
It is not possible to install New Relic infra agent on the container level. 
- [Install the infrastructure monitoring agent for Linux](https://hub.docker.com/r/newrelic/infrastructure/)
- [docker hub newrelic/infrastructure](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux/)
- [slack discussion in cg-support](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1706032211188049?thread_ts=1705517170.379619&cid=C09CR1Q9Z)

**Comment by btylerburton** [comment]
@FuhuXia to wrap up this ticket cleanly, do you think it's best to revert the two PR's that Robbie added above?
