### ISSUE TITLE
Create New Relic Broken Links Synthetic Monitor

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4476]
## User Story

In order to proactively triage broken links, datagovteam would like a monitor that crawls the site. 

NR broken links synthetic monitor looks promising to achieve that. https://newrelic.com/instant-observability/synthetics-page-link-crawler

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN there is a data catalog
  AND there are broken links present in some of the resources 
  THEN the team would like to know about this proactively

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Consider if implementing NR Broken Links synthetic agent will achieve our goals of proactively monitoring broken links

**Comment by hkdctol** [comment]
This might replace #2922 and #4277

**Comment by btylerburton** [comment]
Closing in favor of this ticket https://github.com/GSA/data.gov/issues/4277
