### ISSUE TITLE
Deprecate UA360 Account in favor of GA4 Account

### ISSUE THREAD

**Issue by dlennox24** [GSA/data.gov#4482]
## User Story

Google Analytics data has been routed to the UA360 property while we migrated to GA4. Once GA4 is operational, we need to remove the old UA360 property and transfer any user permissions to the new GA4 one.

## Acceptance Criteria

- [ ] GIVEN the current UA360 property
THEN deprecate usage of the UA360

## Sketch

- [ ] Ensure no data is flowing into UA360 after transition to GA4 property
- [ ] Ensure all users in UA360 who need access to GA4 property have it
- [ ] Remove/shutdown UA360 property

**Comment by hkdctol** [comment]
@dlennox24 does anything remain here? If this is a clean up thing--can you complete remaining tasks and close?

**Comment by dlennox24** [comment]
@hkdctol Here is the list of the GA properties as they stand.

[Marked for deletion](https://analytics.google.com/analytics/web/#/a42145528p381392243/admin/trashcan): 
- GSA Data.gov > Resources.data.gov - GA4
- GSA Data.gov > next.data.gov

Ready for deletion with all of UA360:
Blocked by the determination of the Wordpress property
- Moving TTS UA Properties to GSA Acq Gateway > Agriculture
- Moving TTS UA Properties to GSA Acq Gateway > All Web Site Data
- Moving TTS UA Properties to GSA Acq Gateway > Catalog
- Moving TTS UA Properties to GSA Acq Gateway > Disasters

[Data backed up to GDrive](https://drive.google.com/drive/folders/1PxSH16-dmASjBVx_hWjI1HMHmDtzZuqg):
- GSA Data.gov > Resources - UA data
- GSA Data.gov > SDG - UA data
- Moving TTS UA Properties to GSA Acq Gateway > Catalog - UA360 data

Pending determination of data retention and deletion:
- GSA Data.gov > Federal Data Strategy - UA
- GSA Data.gov > open.USA.gov - UA
- GSA Data.gov > Project Open Data - UA
- GSA Data.gov > Resouraces.data.gov - UA
- GSA Data.gov > Sustainable Development Goals - U.S. NRP - UA
- Moving TTS UA Properties to GSA Acq Gateway > Wordpress

**Comment by hkdctol** [comment]
@dlennox24 Federal Data Strategy--is there any old data to save? Then I would save it, otherwise the list for deletion looks fine.

**Comment by dlennox24** [comment]
Per Feb 26th:
- Don't save:
  - Wordpress
  - Project Open Data

Save the data for the rest and mark for deletion.

**Comment by tdlowden** [comment]
@dlennox24 should we close this?
