### ISSUE TITLE
UI is broken on the Catalog Topics page 

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4486]
## How to reproduce

https://catalog.data.gov/dataset/?groups=climate5434

## Expected behavior

![image](https://github.com/GSA/data.gov/assets/1392461/a48a3891-d087-4a90-b109-35169a32775d)

## Actual behavior

![image](https://github.com/GSA/data.gov/assets/1392461/dddb2458-f85a-48ae-a22b-28c6fab46535)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by btylerburton** [comment]
strangely enough this group looks fine: https://catalog.data.gov/dataset/?groups=older-adults-health-data

**Comment by FuhuXia** [comment]
This issue is fixed.
