### ISSUE TITLE
Upgrade all NodeJS versions

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4488]
## User Story

In order to stay current with security & support, datagovteam wants to upgrade the node version on our static sites to a version supported by cloud.gov.

Ideally, we'd like to move to V20, but V18 will be supported through April 2025.
## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

High value.
Node versions should be kept current to take advantage of security patches.

## Sketch

- [x] Upgrade static sites (using Node V20 if possible, v18 if not)
  - [x] https://github.com/gsa/datagov-11ty
  - [x] https://github.com/gsa/resources.data.gov
  - [x] https://github.com/gsa/data-strategy
  - [x] https://github.com/gsa/us-data-federation

**Comment by rshewitt** [comment]
the latest action for datagov-11ty succeeded despite Pa11y failing on the first URL ( privacy-policy ). need to update the [static site build template](https://github.com/GSA/data.gov/blob/main/.github/workflows/static-site-build-template.yml) used in the action file?

**Comment by btylerburton** [comment]
related: https://github.com/GSA/data.gov/issues/4273

**Comment by rshewitt** [comment]
acknowledging the issue with pa11y silently quitting during testing ( considering it a non-priority ) i'm going to proceed forward with upgrading the node versions without addressing this issue.

**Comment by rshewitt** [comment]
resources.data.gov uses ruby 2.6 which isn't supported anymore. i'm gonna bump the ruby version.

**Comment by rshewitt** [comment]
cloud.gov ruby upgrade [doc](https://cloud.gov/2023/05/24/cloud-gov-pages-jekyll-ruby-upgrade/) mentions 3.1. i'm gonna use 3.1.4.

**Comment by rshewitt** [comment]
I'm checking the sites off in the sketch when the PR has been approved and merged.
