### ISSUE TITLE
rotate CF service keys due to brokered S3 credential incident

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4497]
For the incident, or as a routing best practice, we need to rotate service keys to  brokered S3 buckets.

## How to reproduce

GSA email "cloud.gov brokered S3 credential incident"

## Sketch
Copied from email:

You can rotate your keys by un-binding and re-binding your S3 buckets to each bound application. In a terminal, using the cf command line tool:

        	
        		# list all spaces in your organization
        		cf spaces

        		# target a space
        		cf target -s SPACE-NAME

        		# list all s3 services in the space and the applications bound to them.
        		cf services | grep s3

        		# for each application bound to the service, un-bind it from the service, re-bind it, and restage it.
        		cf unbind-service YOUR-APPLICATION YOUR-SERVICE
        		cf bind-service YOUR-APPLICATION YOUR-SERVICE
        		cf restage YOUR-APPLICATION
        	
        
Note that re-staging your application may cause downtime.

You will also need to delete and recreate any service keys for your S3 services:

        	
        		# delete and recreate service keys for each service
        		cf delete-service-key SERVICE SERVICE_KEY
        		cf create-service-key SERVICE SERVICE_KEY

**Comment by FuhuXia** [comment]
There will be app down time (up to 2 mins) if we simplying unbinding and re-binding the app's S3 keys. There is a way to do it without any downtime but it is a quite lengthy process. Not worth it. I have done unbinding and re-binding for all development and staging apps and some prod apps, leaving the last one to be done during off hours.
```
cf t -s prod
cf us inventory inventory-s3
cf bs inventory inventory-s3
cf rs inventory --strategy rolling
```
To minimize the downtime, we dont need to restage the app. We can do restart (rs) instead.

**Comment by FuhuXia** [comment]
We can take the opportunity to remove any unused S3 services. The following will be removed if no one claims it:

- development:catalog-web-s3
- development:dashboard-s3
- development:demo-test3-s3
- development:etl-test-s3 
- development:s3-test
- development:test-airflow-s3
- staging:dashboard-s3
- staging:dashboard-s3-public
- staging:fcs-lifeboat 
- prod:dashboard-s3 
- prod:dashboard-s3-venerable 
- prod:fcs-lifeboat

**Comment by FuhuXia** [comment]
We need to discuss the following S3 services. It could be dangerous to remove or reset their keys.
 
- prod:static-site-images 
- management:ami-scans 
- management:backup-manager-s3
- management:terraform-s3

**Comment by nickumia** [comment]
> prod:static-site-images

These keys should be nonessential, this was used for just uploading images, not for active use.

> management:ami-scans

This should also be a human managed only service.  I believe these were to share the scans with the GSA ISE team. 

> management:backup-manager-s3

Nonessential.  If `fcs-lifeboat` isn't needed, then this can safely be changed as well.  It is bound to the `backup-manager` app, so it would just need to be recycled. 

> management:terraform-s3

This is the only real dangerous one.  I'll leave it up to the discretion of the team how to talk about this.

**Comment by FuhuXia** [comment]
@btylerburton @Jin-Sun-tts

Can you go thru the follwing repos and **message me on Slack** the secret values we are using for any S3 access key ids? I only need the key ids to compare with what we have to cloud.gov service keys. I do **not** need the secret access key. 
 
- https://github.com/GSA/datagov-website
- https://github.com/GSA/datagov-ssb
- https://github.com/GSA-TTS/datagov-brokerpak-solr
- https://github.com/GSA-TTS/datagov-brokerpak-eks
- https://github.com/GSA-TTS/datagov-brokerpak-smtp

**Comment by btylerburton** [comment]
I can take care of this @Jin-Sun-tts

**Comment by FuhuXia** [comment]
Ran GH action in repo https://github.com/GSA/datagov-ssb and reviewed the last four chars of the `${{ secrets.AWS_ACCESS_KEY_ID }}` is `VE66`, maching what we have in the service-key in cloud.gov. We can safely rotate the key and update GH secrets. 


![image](https://github.com/GSA/data.gov/assets/1392461/fc68482a-c9ea-4de5-88e3-f2d667e28092)
![image](https://github.com/GSA/data.gov/assets/1392461/90e9bf42-5f8d-483d-9e6d-086b445d8896)

**Comment by FuhuXia** [comment]
The last s3 service `management:terraform-s3` has its key rotated and updated in `datagov-ssb` repo secrets. This task is completed.
