### ISSUE TITLE
dataset lost harvest object when xml file timestamp changed without xml content change

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4505]
WAF source file timestamp changes without real content change is causing other issues such as https://github.com/GSA/data.gov/issues/4425, but it also make dataset losing its harvest object on the UI, and potentially it is  the biggest contributor to the db-solr-sync workload.

## How to reproduce

Modify a XML file timestamp on a WAF souce, reharvest

## Expected behavior

No change on the dataset. UI stays the same, no addition workload to db-solr-sync

## Actual behavior

See the error in the fetch log
```
Document with GUID ### unchanged, skipping...
```

On the UI, dataset lost its harvest souce metadata info

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by Jin-Sun-tts** [comment]
reproduce this issue in local test:

![Image](https://github.com/GSA/data.gov/assets/104456257/3f907b4b-92c1-4302-bff1-06075c98fe1f)

metadata update date were changed to new timestamp from the file, but lost its harvest souce metadata info

**Comment by Jin-Sun-tts** [comment]
After conducting local testing, identified the code responsible for the root cause of the issue: https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/harvesters/base.py#L709C1-L710C70.

In the testing, above rebuild index call did not refresh Solr from DB, and discovered that calling `package_update `or `package_patch` instead of `package_index.index_package` resolved the issue and displayed the metadata info in the UI.

will investigate alternative methods for rebuilding the index to address this problem.

**Comment by Jin-Sun-tts** [comment]
Tested the most recent version of Ckan, utilizing only two extensions` harvest `and `spatial` without incorporating any additional customized modifications. was able to replicate the same problem.

**Comment by Jin-Sun-tts** [comment]
After conducting additional tests, it was observed that by adding `model.Session.commit()` prior to invoking `package_index.index_package`, the process functions as expected. 

Furthermore, an examination of the package dictionary transmitted to Solr, same contents regardless of whether a commit was performed or not. 

Further investigation is required to determine why package_index.index_package needs a database commit to refresh Solr.

**Comment by Jin-Sun-tts** [comment]
created upstream issue https://github.com/ckan/ckanext-spatial/issues/324

**Comment by FuhuXia** [comment]
The root cause of the issue is illustrated in the above PR/commit. It shows the query with current=True is getting results with current=False. Could be a CKAN core bug that when querying updated records in an uncommited transaction, wrong results are returned.
