### ISSUE TITLE
catalog web proxy error for url http://www.google-analytics.com/collect

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4508]
NewRelic Log review on prod:catalog-web and prod:catalog-admin showing these error. Staging space has similiar error.
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='proxy-gsa-datagov-prod-catalog-admin.apps.internal',
port=61443): Max retries exceeded with url: http://www.google-analytics.com/collect (Caused by ProxyError('Cannot
connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
```
The error stared on 2023-10-03 4:08PM EDT.

![image](https://github.com/GSA/data.gov/assets/1392461/cceaf473-3f93-43a3-8b04-0707ecdfde25)

## How to reproduce

Search MaxRetryError in the NewReloc

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
According to [ckanext-googleanalytics](https://github.com/ckan/ckanext-googleanalytics#features) readme, it needs to send data to url `www.google-analytics.com` to send events data. 


> Adds Google Analytics Event Tracking to resource download links, so that resource downloads will be displayed as Events in the Google Analytics reporting interface.
> 
> Adds Google Analytics Event Tracking to some API calls so that usage of the API can be reported on via Google Analytics.
> 
> Add Google Analytics Event Tracking function that can be used in any exstension to create your custom events tracking.

So we need to add `www.google-analytics.com` to our proxy allow list.

**Comment by FuhuXia** [comment]
We have added www.google-analytics.com to the allow list, see the [PR above](https://github.com/GSA/data.gov/pull/4509). 

But in the [ckanext-googleanalytics code,](https://github.com/ckan/ckanext-googleanalytics/blob/master/ckanext/googleanalytics/utils.py#L79-L87) `HTTP` instead of `HTTPS` is used. We need convince ckan upstream to use HTTPS, in the meanwhile we can use a fork.

**Comment by Jin-Sun-tts** [comment]
verified in the New Relic log, after fixes there is no more error message:

![Screenshot 2023-10-25 at 4 28 05 PM](https://github.com/GSA/data.gov/assets/104456257/fd03e0cd-a984-4d8f-a96e-5c79e0c05181)
