### ISSUE TITLE
software/catalog/ckan-app role for harvester depends on apache

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#451]
The software/catalog/ckan-app role installs ckan, including it's apache site configuration. This makes sense, but on the apache role is not tagged for harvester, so the config directory does not exist and the ckan-app role fails.

**Comment by adborden** [comment]
Not sure if we should just tag the apache role with harvester (simplest fix) or refactor things so that ckan-app installs on harvester without needing the apache role since it really isn't necessary for harvester.

**Comment by nickumia-reisys** [comment]
CKAN install and hosting is all managed by Cloud.gov manifests now.  There isn't a single reference for this and the original concern is no longer valid.
