### ISSUE TITLE
Migrate Static Sites to GSA-TTS & add build checks

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4510]
## User Story

In order to maintain our list of static sites within the GSA's Pages ATO umbrella, the Pages team would like datagovteam to migrate our static sites to the GSA-TTS org and enable a list of build checks to confirm the build is secure.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I have a site configured on pages.cloud.gov
  THEN I expect to see the source repository listed under the GSA-TTS org
  AND that it is managed by [@GSA-TTS/data-gov-team-tts](https://github.com/orgs/GSA-TTS/teams/data-gov-team-tts)
  AND that is is configured with Github Security, Security Scorecard, Github AllStar, Codeql, Dependabot and Snyk

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Migrate the repo to GSA-TTS org
- [ ] Add [data-gov-team-tts](https://github.com/orgs/GSA-TTS/teams/data-gov-team-tts) as maintainer
- [ ] Configure Github Security
- [ ] Configure Security Scorecard
- [ ] Configure Github AllStar
- [ ] Configure Codeql
- [ ] Configure Dependabot
- [ ] Configure Snyk

Repeat the above steps for each of the following repos:
  - [ ] https://github.com/gsa/feedback.usa.gov (no longer a site)
  - [x] https://github.com/gsa/us-data-federation
  - [x] https://github.com/gsa/data-strategy
  - [x] https://github.com/gsa/resources.data.gov
  - [x] https://github.com/gsa/datagov-11ty
  - [x] https://github.com/GSA/sdg-indicators-usa

**Comment by btylerburton** [comment]
Blocked pending attendance of Pages Office Hours to clarify some of the security implementation details...

**Comment by btylerburton** [comment]
Office hours scheduled for 11/2 at 11:30AM EST

EDIT: We will complete a single site with Pages team and then repeat the process for the rest of the sites.

**Comment by Jin-Sun-tts** [comment]
resources.data.gov: 

https://docs.google.com/document/d/16uJVDXZYNPpjC5q5Cxmx-k003mj0SGFRU33I2uKFrQ4/edit#heading=h.m7d74e15hego

**Comment by Jin-Sun-tts** [comment]
- Go to the /settings/access/ page and confirm the admin and resource group settings.
- Implement a security policy by including a security.md file.
- Activate vulnerability reporting.
- Establish a dependabot.yml file within the .github directory and configure the package ecosystem value.
- Enable CodeQL analysis for code scanning (set to default settings).
- Enable secret scanning.

**Comment by Jin-Sun-tts** [comment]
setup package-ecosystem value `npm` in dependabot.yml file https://github.com/GSA/resources.data.gov/pull/626
`The property '#/updates/0/package-ecosystem' value "" did not match one of the following values: npm, bundler, composer, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub, swift`

**Comment by Jin-Sun-tts** [comment]
data-strategy:
https://docs.google.com/document/d/12PRQTkHCEp04S6KoWT_UNBb6tWeRQTAegtQPIwNfcHM/edit

**Comment by Jin-Sun-tts** [comment]
data-strategy:
https://docs.google.com/document/d/12PRQTkHCEp04S6KoWT_UNBb6tWeRQTAegtQPIwNfcHM

datagov-11ty:
https://docs.google.com/document/d/1srG6dMEpZBMVtMLNpgWC8hIXSBLcmHaEfsjZQfohxF0

us-data-federation:
https://docs.google.com/document/d/1lu4Axr44gyB1KldlyO3J7gHpt4cMHpVWmPmsE4o16tI

sdg-indicators-usa:
https://docs.google.com/document/d/1GR2RKVd4tE1LXZEBvbDfsRhrcu2CjuuTruq962-tPvs/edit

**Comment by btylerburton** [comment]
@Jin-Sun-tts let's circle back together to add sdg.data.gov to this list.

**Comment by Jin-Sun-tts** [comment]
Finished all security setup/modification in  https://github.com/GSA/sdg-indicators-usa except the dependabot update.  

Could not setup dependabot.yml file because of unsolved PR https://github.com/GSA/sdg-indicators-usa/pull/1054, will check with @btylerburton on Monday.

**Comment by Jin-Sun-tts** [comment]
configuration and documentation for sdg.data.gov is done.

**Comment by Jin-Sun-tts** [comment]
checked with Ryan Wold, the [feedback.usa.gov](http://feedback.usa.gov/) is no longer a site, and @btylerburton will work with Ryan to remove it from our https://pages.cloud.gov/sites account.
