### ISSUE TITLE
Integrate Pre-Release version of OpenSDG to mitigate Ruby 2.x EOL

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4514]
## User Story

Cloud.gov Pages is ending support for Ruby 2.x at the end of November. ([link](https://cloud.gov/2023/05/24/cloud-gov-pages-jekyll-ruby-upgrade/))

In order to keep https://sdg.data.gov/ and https://sdg-staging.data.gov/ building, datagovteam would like to integrate a pre-release version of OpenSDG plugin that supports Ruby 3.x.

The process has been outlined by a core maintainer here: https://github.com/open-sdg/open-sdg/discussions/2067

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I would like to build a new version of sdg.data.gov
  AND cloud.gov has ended support for Ruby 2.x
  THEN I see a build complete successfully whenever I push changes.

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

Ruby 2.x security support ended on 31 Mar 2023.

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Follow instructions in discussion thread on OpenSDG:
  - [ ] https://github.com/GSA/sdg-data-usa
  - [ ] https://github.com/GSA/sdg-data-usa-staging
    - [ ] Bump version in `scripts/requirements.txt`
    - [ ] Bump version in `config_data.yml`
  - [ ] https://github.com/GSA/sdg-indicators-usa
    - [ ] Bump version in `Gemfile`
    - [ ] Bump version in `_config.yml`
  - [ ] GH Actions
    - [ ] Bump version in: https://github.com/GSA/sdg-indicators-usa/blob/main/.github/workflows/build.yml
    - [ ] Bump version in: https://github.com/GSA/sdg-indicators-usa/blob/main/.github/workflows/qa.yml

**Comment by rshewitt** [comment]
@btylerburton i'm gonna work on this today since you're out and i've been working on the ruby upgrades

**Comment by hkdctol** [comment]
November 30th milestone on this

**Comment by rshewitt** [comment]
build for staging has passed. next step is integrating the new build with production.

**Comment by rshewitt** [comment]
i'll update the sdg-indicators-usa readme to mention pages.cloud.gov helps publish the static webpages on cloud.gov.

**Comment by btylerburton** [comment]
NOTE: Changes made to `develop` branch **only** in `sdg-indicators-usa` as main is using old version of plugin that does not support Ruby 3.x

Also, no changes applied to `sdg-data-usa` as that is the data repo for production, using the old version, which will be superseded by the new (staging) site once it's ready.
