### ISSUE TITLE
solr index error: this IndexWriter is closed

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4515]
When researching on issue https://github.com/GSA/catalog.data.gov/issues/1121, it shows harvesting job fails whenever there is a finished job and harvest source needs to be updated. Manually run a `ckan search-index rebuild some-harvest-source-name` in cf run-task command gives the following error:

```
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/lib/search/index.py", line 330, in commit
ERR raise SearchIndexError(e)
ERR ckan.lib.search.common.SearchIndexError: Solr responded with an error (HTTP 500): [Reason: this IndexWriter is closed]
OUT Exit status 1
```

This error means solr leader is not able to make any changes. Therefore no dataset or harvest source can be updated, db-solr-sync and tracking-update job will fail as well. 

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
A solr leader manual restart fixed the issue. Solr leader restarts itself once in a while due to ECS memeory leak, but at a much less frequency compared to the followsers, maybe once in a month. Last time it restarted is 2 weeks ago.

This is the first time we notice this `IndexWriter is closed` error. We know a manual restart should solve the issue.

**Comment by nickumia** [comment]
Woah!  This was eventful haha.. I would ask the question whether the restart script for the leader is the same as the followers.  I know we did work to make the restart script more reliable.  I suspect that the leader script is out-of-sync which is why the manual restart was required.

**Comment by FuhuXia** [comment]
@nickumia Our [restart script](https://github.com/GSA/catalog.data.gov/blob/main/solr/solr_setup.sh#L45-L52) does not handle this kind of error, not yet. It was designed to run the first 10 mins to detect abnormality in the log, mostly for core lock for followers. If everything looks good for the first 10 mins, the script will quit. This new error happens in the middle of a solr life cycle, we can add this error detection to our script but we have to let the script runs in a indefinite loop. We will consider this if the error happen more often, or we have to handle some other similar errors.

**Comment by nickumia** [comment]
That (mostly) makes sense.  (P.S. That is not really the restart script, that is the setup/startup script.)  That script should not even be running super long (at least as a blocking first step, but it is a necessary evil).  The restart script is actually the [lambda function](https://github.com/GSA-TTS/datagov-brokerpak-solr/blob/main/terraform/ecs/provision/app_template.tf) that hits only on memory spike.  I'm not opposed to a function that runs in the background, initiated by the startup script.  Either way, you are right in that, it doesn't make sense to fix this if it happens rarely.

I honestly don't have a good solution to this, if it does need to be revisited.  There is only one leader and for a restart to work properly, all open connections need to be paused which isn't possible..

**Comment by FuhuXia** [comment]
It is a good solution already, because leader solr can be restarted without any downtime to public users. It affects only internal user and backend harvesting.
