### ISSUE TITLE
Show U.S.A. (not worldwide) map on catalog landing page

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4519]
Our data is U.S.A focused. It makes sense to show USA map on the landing page, matching the location droopdown search in USA scope. This is also the behavior we had before, not sure when it got changed to a worldwide map, probably by a mistake.

![image](https://github.com/GSA/data.gov/assets/1392461/73d725b4-314a-43eb-8e0c-7a30850d93aa)![image](https://github.com/GSA/data.gov/assets/1392461/1d37b56c-61cf-4c0d-add3-1b9a2298cd08)![image](https://github.com/GSA/data.gov/assets/1392461/2c124a9f-a092-42ed-a0ee-845f34ee6fe2)

## How to reproduce

go to catalog.data.gov

**Comment by jbrown-xentity** [comment]
Theoretically, this should be customized in ckanext-datagovtheme (or wherever the snippet is implemented): https://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html#spatial-search-widget

**Comment by FuhuXia** [comment]
Fixed in PR https://github.com/GSA/ckanext-datagovtheme/pull/173/files#diff-2a9447ae2cc36803e58a92ae5babb6d1d086585180d67e7cf8f974988bd8c3f4R139-R143
