### ISSUE TITLE
Update user guide with info on new USGS basemap

### ISSUE THREAD

**Issue by rshewitt** [GSA/data.gov#4520]
## User Story

In order to assist users on what to expect from the catalog leaflet map widget, datagov wants to provide information explaining the new USGS basemap.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN the existing user guide \
  WHEN content on the USGS basemap is added
  THEN the information is reflected in the prod webpage. 

## Background
- we switched basemap layers to a free alternative in order to avoid paying for a tiling service
- the basemap layer has 8 zooms levels for the planet and 16 for USA.
- if the mapview requests a tile which the service does not offer ( because the user has zoomed into a neighborhood in tokyo for example ) then nothing will appear in the mapview
- providing information to the user on why this happens is beneficial because it explains why something isn't appearing. with no explanation the user may lose confidence in the mapping widget.

## Sketch
- update the [user guide](https://github.com/GSA/datagov-11ty/blob/main/pages/user-guide.md) with information on the new USGS basemap.

**Comment by hkdctol** [comment]
@rshewitt will close this if it ends up being unnecessary
