### ISSUE TITLE
Publish harvester logic module to PyPI

### ISSUE THREAD

**Issue by rshewitt** [GSA/data.gov#4522]
## User Story

In order to make the harvester logic module available for public use, data.gov wants publish it to PyPI 

## Acceptance Criteria

- [ ] GIVEN the harvester logic repo \
  WHEN the module is published to PyPI \
  THEN it is available for download on PyPI \

## Sketch
- follow steps for publishing on PyPI using poetry ( [example](https://www.digitalocean.com/community/tutorials/how-to-publish-python-packages-to-pypi-using-poetry-on-ubuntu-22-04) )

**Comment by btylerburton** [comment]
closing in favor of this: https://github.com/GSA/data.gov/issues/4544
