### ISSUE TITLE
harvester sees SSLError SSLCertVerificationError when harvesting DOI source

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4526]
This error started a week ago when harvesting url https://datainventory.doi.gov/data.json

**Harvester reports error:** 
```
ConnectionError getting json source: HTTPSConnectionPool(host='datainventory.doi.gov', port=443):
Max retries exceeded with url: /data.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer
certificate (_ssl.c:1129)'))).
```

**curl shows the same kind of error:**
```
$ curl -I  https://datainventory.doi.gov/data.json
HTTP/1.1 200 OK
Server: Caddy
Content-Length: 0

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**SSL certificate is fine for Chrome browser:**
![image](https://github.com/GSA/data.gov/assets/1392461/58417616-c8b9-45e9-820b-3c6024bb8804)

## How to reproduce

Check harvest source /harvest/test-new-doi-datajson

**Comment by FuhuXia** [comment]
It appears the issue is on DOI side, their Digicert SSL certificate is incorrectly installed. 
```
The server is not sending the required intermediate certificate.
```
https://www.digicert.com/help/
https://www.sslshopper.com/ssl-checker.html#hostname=datainventory.doi.gov

**Comment by hkdctol** [comment]
Awaiting answer from DOI

**Comment by jbrown-xentity** [comment]
In checking the cert via @FuhuXia 's link above, it's reported as valid now. So we should be able to re-harvest this source...

**Comment by jbrown-xentity** [comment]
Fuhu is correct, there is still a broken piece in the chain. Check curl (as per the description), or see here:

![Image](https://github.com/GSA/data.gov/assets/26980513/27ce6c66-6fa2-4313-9507-880adb822964)

**Comment by FuhuXia** [comment]
All checks are green now. `curl` command is successful. datainventory.doi.gov has its SSL certificate fixed.
