### ISSUE TITLE
words are broken at line wrap in organization description

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4528]
Looks odd when words are broken.

![image](https://github.com/GSA/data.gov/assets/1392461/c7ec49a8-893b-44da-98d8-e7fc5258a8bc)
![image](https://github.com/GSA/data.gov/assets/1392461/9b19111b-07b1-4c58-b6b6-fa8128ecefca)

## How to reproduce

https://catalog.data.gov/organization/americorps-gov
https://catalog.data.gov/organization/city-and-county-of-durham-north-carolina

## Sketch

Do not use `word-break: break-all` in the css;

**Comment by rshewitt** [comment]
![Image](https://github.com/GSA/data.gov/assets/92057378/00035120-9cda-471d-9210-473d1bb9b70d)

**Comment by rshewitt** [comment]
![Image](https://github.com/GSA/data.gov/assets/92057378/548efc32-f23c-43bf-aabc-c004f2e79adf)
