### ISSUE TITLE
GitHub CF actions are failing with /entrypoint.sh error 

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4531]
Cloud Foundry server was down for a few hours. After it came back, all cf commands are failing with error message:
```
exec /entrypoint.sh: no such file or directory
```

## How to reproduce

check catalog actions https://github.com/GSA/catalog.data.gov/actions

**Comment by FuhuXia** [comment]
It appears it has been fixed with `cg-cli-tools`'s lastest PR https://github.com/cloud-gov/cg-cli-tools/pull/21.

**Comment by robert-bryson** [comment]
Is this probably the reason that these restarts are failing? https://github.com/GSA/inventory-app/actions/runs/6882239216

**Comment by FuhuXia** [comment]
yeah, all cf task was failing. now it is fine.
