### ISSUE TITLE
Website has errors on organization dataset list pages

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#454]
First noticed on DOI organization page, confirmed to occur on other organizations. The first and last pages will work as expected (possibly cached?), but many other pages will not work. Some dataset pages found on the organization list also do not load with a 503 error, see example below.
Examples:
DOI Org: https://catalog.data.gov/organization/doi-gov?page=4826
Arkansas Org: https://catalog.data.gov/organization/arkansas-gov?page=16
DOI dataset page: https://catalog.data.gov/dataset/digital-data-sets-that-describe-aquifer-characteristics-of-the-alluvial-and-terrace-deposits-alcd79d

**Comment by jbrown-xentity** [comment]
Noted might be related to uptrends alert on data.gov at 12 MST on 10/29/2018, review and priority TBD by @JJediny.

**Comment by JJediny** [comment]
The problem caused by short-lived site outage and cache not reflecting the accurate pages
