### ISSUE TITLE
catalog 500 error on some datasets in block 'collection_resources'

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4553]
Some dataset returns 500 error with error message

```
ERR {{ super() }}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 19, in block 'page'
ERR {%- block content %}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 22, in block 'content'
ERR {% block main_content %}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 74, in block 'main_content'
ERR {% block primary %}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 87, in block 'primary'
ERR {% block primary_content %}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read_base.html", line 59, in block 'primary_content'
ERR {% block primary_content_inner %}{% endblock %}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/package/read.html", line 34, in block 'primary_content_inner'
ERR {% block package_resources %}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read.html", line 113, in block 'package_resources'
ERR {% block collection_resources %}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read.html", line 114, in block 'collection_resources'
ERR {{ super() }}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/geodatagov/templates/package/read.html", line 14, in block 'collection_resources'
ERR {% set collection_package = h.get_collection_package(collection_package_id) %}
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/geodatagov/helpers.py", line 62, in get_collection_package
ERR package = p.toolkit.get_action('package_show')({}, {'id': collection_package_id})
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/__init__.py", line 551, in wrapped
ERR result = _action(context, data_dict, **kw)
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/action/get.py", line 1018, in package_show
ERR raise NotFound
ERR ckan.logic.NotFound
OUT 2023-12-11 19:20:31,334 INFO  [ckan.config.middleware.flask_app]  500 /dataset/tiger-line-shapefile-2013-county-santa-cruz-county-ca-all-roads-county-based-shapefile render time 4.394 seconds

```

## How to reproduce

1. Description of steps to reproduce the issue.
Go to [this dataset url](https://catalog.data.gov/dataset/tiger-line-shapefile-2013-county-santa-cruz-county-ca-all-roads-county-based-shapefile), or search `" 500 " NginxLog` in NewRelic on app catalog-proxy for more examples. 

## Expected behavior

200 or 404 response code
## Actual behavior

500 response code

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by gujral-rei** [comment]
Handle 500 error gracefully

**Comment by btylerburton** [comment]
Previously there was a 500 graceful error page. That was lost during the cloud.gov migration. Possibly tied to NGINX config.

**Comment by chris-macdermaid** [comment]
Here's a screenshot of what I'm seeing.

![image](https://github.com/GSA/data.gov/assets/64213093/a4c46253-d15c-4f35-bb83-9b4aaa04de46)

**Comment by Jin-Sun-tts** [comment]
![Image](https://github.com/GSA/data.gov/assets/104456257/84cef108-8acb-41be-9e05-5f2c26d50099)

checked those datasets are in a collection, but the parent is deleted.

**Comment by Jin-Sun-tts** [comment]
FYI. The UI display for datasets have valid parent collection:
![Screenshot 2024-01-23 at 12 45 35 PM](https://github.com/GSA/data.gov/assets/104456257/3f251728-6b7c-4147-bbec-952e0480e94b)



**The error returned when the parent collection was not found. To address this, we implemented error handling and have the following options for UI changes for this situation:**

1. Maintain the current display format but include a message indicating that the parent collection does not exist.
![Screenshot 2024-01-23 at 12 47 13 PM](https://github.com/GSA/data.gov/assets/104456257/4ffdb7ab-f697-4bd1-8d96-9a14087807ee)


2. Enhance the display by adding a link to search for sibling datasets within the same collection.
![Screenshot 2024-01-23 at 12 56 51 PM](https://github.com/GSA/data.gov/assets/104456257/532babc2-4256-42da-af91-cadd396d65d3)

3. Completely omit the 'Collection' section from the display in this scenario.

Furthermore, will do additional research to understand how the harvester behaves when harvesting dataset without a parent collection existing.

**Comment by Jin-Sun-tts** [comment]
After discussing with the team, we have decided to resolve the 500 error by implementing the following UI changes:

![Screenshot 2024-01-24 at 12 29 41 PM](https://github.com/GSA/data.gov/assets/104456257/d7269369-a391-4426-9f01-1f0cc5dcef8a)


Additionally, created a new ticket (https://github.com/GSA/data.gov/issues/4594) to implement the necessary logic to prevent the deletion of the parent collection during the harvesting stage.

**Comment by Jin-Sun-tts** [comment]
After pushed the change to catalog, double checked on catalog production, the error from the missing parent issue is fixed. 

![Image](https://github.com/GSA/data.gov/assets/104456257/17dc463d-3362-4ba7-ac12-8f26d047249e)
