### ISSUE TITLE
Create agencies report in Google Analytics

### ISSUE THREAD

**Issue by dlennox24** [GSA/data.gov#4568]
## User Story

In order to improve transparency to agency partners and the public, Data.gov needs to integrate the unique tracking groups of agency partners and their datasets into a report. This will allow Data.gov to publish statistics on the agency partners dataset viewership.

## Acceptance Criteria

- [ ] GIVEN current CKAN version and Google Analytics status for Data.gov \
  THEN Data.gov will create Google Analytics 4 report to explore the agency partner viewership data

## Background

With the completion of the agency partner groupings (#4567), Data.gov can now set up reports within Google Analytics and explore exporting parts of this data externally of Google Analytics to be publicly viewable on the Data.gov website.

## Sketch

- [ ] Create a Google Analytics report in GA4 that tracks groups
- [ ] Explore the best way to export a subset of data to be publicly viewable on the Data.gov website

**Comment by tdlowden** [comment]
Scraped the organization and publisher from dataset pages to better classify
This is imperfect at the moment and we’re not sure why
About 60% of pageloads correctly record and org/pub, 40% do not. Maybe bots, maybe GA free limitations? Will continue to investigate

**Comment by tdlowden** [comment]
#4743 addresses fixing this. closing this issue
