### ISSUE TITLE
add ansible tag "config" to only update application configuration

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#457]
As an operator, I want an ansible tag "config" that only runs task related to application configuration updates so that I can have faster playbook runs that make fewer changes when I only need to update hosts or settings within application configuration files.

This also helps when I don't want to update versions or anything, I only want to make a surgical change on the app configs.

**Comment by nickumia-reisys** [comment]
Ansible no longer being used.
- https://github.com/GSA/data.gov/issues/3710
