### ISSUE TITLE
SNYK Scan finding: CKAN - Improper Handling of Length Parameter Inconsistency

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4571]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 2023-12-14
**Severity:** Medium
**Due date:** 2023-03-14

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

https://security.snyk.io/vuln/SNYK-PYTHON-CKAN-6124881

**Comment by FuhuXia** [comment]
it is been worked on in the other tickets
- https://github.com/GSA/data.gov/issues/4559
- https://github.com/GSA/data.gov/issues/4560
