### ISSUE TITLE
SNYK Scan Finding: Cryptography - Information Exposure

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4572]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 2023-12-14
**Severity:** Medium
**Due date:** 2024-03-14

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description

https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-6126975

**Comment by rshewitt** [comment]
catalog and inventory use the recommended version of cryptography to resolve this issue
