### ISSUE TITLE
Harvester Email

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4582]
## User Story

In order to notify data providers of harvest job completion and/or errors, data.gov data providers want an email sent out on harvest job completion.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN the email is extractable from the CKAN organization \
  WHEN a harvest job occurs for a given harvest source \
  THEN an email is sent with a summary to the emails specified above \
  AND there is some way to digest the problems (whether in the email, or through a link)

## Background

Popped into my brain from [this comment, what do we do with errors](https://github.com/GSA/data.gov/issues/4577#issuecomment-1879043155). This is what we do.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
No security considerations. Some data providers may balk at their harvests being publicly available

## Sketch

No idea at this point. Need to investigate airflow options and best practices, possibly utilizing the SES cloud.gov service (to keep email from point consistent). If there are no out of the box items, change this to a spike/discovery ticket on how to approach this problem.

**Comment by nickumia** [comment]
Maybe useful references when the time comes:
- https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html
- https://docs.astronomer.io/learn/error-notifications-in-airflow

**Comment by rshewitt** [comment]
[flask mail extension](https://pythonhosted.org/Flask-Mail/)

**Comment by btylerburton** [comment]
Agree for MVP to send a link to the Harvest UI Jobs page

**Comment by Jin-Sun-tts** [comment]
Initially, consider using the `flask-mail` plugin, which allows sending emails directly from a Flask application. However, our requirement is to incorporate the email step into the harvest process as the final action within the report step.

If we use `flask-mail,` we would need access to the application instance to send emails. This could lead to redundancy in app instances or require creating an API route that the harvest runner would call, potentially increasing network traffic.

Instead, working on Python's built-in `smtplib` library to send emails directly from the harvest process. This approach avoids the need for a Flask app instance and eliminates the overhead of creating an API route, reducing potential network traffic and simplifying the integration.

**Comment by Jin-Sun-tts** [comment]
The email function is now woking in development, sample email like below:

Subject: Harvest Job Completed

![Image](https://github.com/user-attachments/assets/e7bdc923-80a9-4aac-892e-0938e0cbbfc6)
