### ISSUE TITLE
NewRelic ARM monitoring stopped

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4587]
Since 01/05/2025, for all ckan instances.

![image](https://github.com/GSA/data.gov/assets/1392461/50c53a47-65eb-4fb2-a86e-671fd8e42a6b)

## How to reproduce

1. Description of steps to reproduce the issue.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by btylerburton** [comment]
This has also broken our O&M dashboard. 

![Image](https://github.com/GSA/data.gov/assets/104455281/68800d3a-f430-48c1-9c00-35370ea77811)

**Comment by gujral-rei** [comment]
We were trying to rotate the keys a couple of weeks ago. Would that have caused this issue?

**Comment by FuhuXia** [comment]
:+1:  It got to be, the timing tells, on 2024-01-05.
https://github.com/GSA/data.gov/issues/4580

**Comment by FuhuXia** [comment]
updated `inventory-secrets` with the new key. Added `NEW_RELIC_LICENSE_KEY` into catalog-secrets. After restart, ARM is working again for all ckan apps.
