### ISSUE TITLE
SNYK Scan Finding: Cryptography - Resource Exhaustion

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4590]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 2024-01-16
**Severity:** Moderate
**Due date:**  2024-04-16

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-6157248

**Comment by rshewitt** [comment]
this issue has been resolved in inventory and catalog by upgrading cryptography
[catalog](https://github.com/GSA/catalog.data.gov/blob/1bc9b604d0016b8e5e5ea5966ca7aea7f668e6b7/ckan/requirements.txt#L28)
[inventory](https://github.com/GSA/inventory-app/blob/856ea48699c6e888ff72714fab06a64ac6bf10d1/requirements.txt#L25C5-L25C21)
