### ISSUE TITLE
View Full Metadata Link omits many elements

### ISSUE THREAD

**Issue by torrin47** [GSA/data.gov#4597]
On data.gov details pages corresponding to ISO 19139 records, a link is displayed to "View Full Metadata", which loads a version of the metadata presented as a static HTML page - presumably run through a stylesheet.

![image](https://github.com/GSA/data.gov/assets/2127036/9d238d72-c973-406a-8c8b-b8cdce86defe)

Our data stewards have been taking issue with the characterization of what displays at this link as being "Full". It may be many things, but it is emphatically not full, complete, comprehensive, or in any way representative of all of the metadata content. We're honestly not sure how it might more accurately be characterized - ugly and confusing seems to be the consensus. 

We see three possible solutions:

1. Overhaul the stylesheet used to generate the HTML page so that it truly approaches the "Full" metadata record, and presents it in a layout that is organized and logical
2. Rename the link to something that more accurately describe what is displayed
3. Remove the link until option 1 can be achieved

## How to reproduce

1. Click link to "view full metadata". 
2. Recoil in confusion at the result

## Expected behavior

We've searched for an example of a better display of full ISO 19139 metadata, and honestly, none of them are great, but most are better than what's currently displayed here. Here's an example of Esri's HTML:
https://www.arcgis.com/sharing/rest/content/items/3700342d3d184b0d92eae99a78d9c7a3/info/metadata/metadata.xml?format=default&output=html
and here's a version from GeoNetwork that's a lot fancier but still manages to be confusing to novices:
https://sdi.eea.europa.eu/catalogue/srv/eng/catalog.search#/metadata/ff63d80d-a1e8-414b-9a42-6b35d54fff30/formatters/xsl-view?root=div&view=advanced
In a perfect world, the page would more closely resemble something like this:
![image](https://github.com/GSA/data.gov/assets/2127036/82efee86-ebbf-4689-ad12-9b577b659cf9)

## Actual behavior

This is an example of what we see at data.gov:
https://catalog.data.gov/harvest/object/dcd876c5-1ed6-4a2b-9666-b4d87ca21806/html

**Comment by jbrown-xentity** [comment]
I do see this as not working correctly. Some dataset pages it works with limitations, many just display nothing.
As we are not CSDGM or ISO metadata experts, we probably shouldn't have these views in the first place. I have removed the links, as it seemed the most prudent thing to do. See PR [here](https://github.com/GSA/ckanext-datagovtheme/pull/185).
If you are interested in building a template for what this should look like, please let us know. It looks like the logic for those views is a third party CKAN extension detailed [here](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/views.py#L40-L61), something we work with but do not support or maintain directly.

**Comment by torrin47** [comment]
Thanks, removing the links does seem like a fine near-term solution.

Odd that many if not most of the stylesheets I'm finding date to 2011, including the CKAN extension:
https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/templates/ckanext/spatial/gemini2-html-stylesheet.xsl
qGIS:
https://github.com/nextgis/qgis_metatools/blob/master/xsl/iso19115.xsl
NOAA:
https://metadata-standards.data.bas.ac.uk/static/xml-stylesheets/iso-html/xml-to-html-ISO.xsl
It seems as if enthusiasm for ISO dropped off after that point - likely because of the work to adopt 19115-1/19115-3, but -3 has been available since 2016, and we're still waiting for tools and implementation examples. Perhaps folks are just fried on XML and are now waiting for 19115-4 so we can all work in JSON?  https://www.iso.org/standard/86968.html
I think we'd be interested in collaborating on a template, but aren't in a position to go it alone and would want to be sure we're aligned with the rest of the community. Perhaps we'll work through the FGDC for coordination. Thanks again!

**Comment by jbrown-xentity** [comment]
We have this merged in, you can see an example at https://catalog.data.gov/dataset/u-s-hourly-precipitation-data2, where the only option is to download the metadata, not "view" it.
Thanks!

**Comment by torrin47** [comment]
That seems fine to me - the raw xml metadata still has value, wouldn't want to remove that.  But now we're also seeing the GeoPlatform links show up on many of these pages, including the example you cited, though the links always end in dead ends:

![image](https://github.com/GSA/data.gov/assets/2127036/d9aab976-ce10-462e-85d1-496d31c3717a)

![image](https://github.com/GSA/data.gov/assets/2127036/13a602f3-7c60-489e-bfda-71e70bd53505)

are these updates related? On your radar? Thanks again for the quick response.

**Comment by jbrown-xentity** [comment]
Yes, that is an outstanding issue. Geoplatform recently redid all their backend services (https://kb.geoplatform.gov/gp-info/geoplatform-gov-release-notes.html#november-2023-version-1-62-0), and the API we reference is not working correctly at the moment. I've been told fixes are currently in work for this API on the Geoplatform side.
cc'ing @chris-macdermaid @borisacha from Geoplatform for updates when a fix for this API is in place...
Thanks @torrin47

**Comment by chris-macdermaid** [comment]
A fix for this will be added to production with GeoPlatform's next release.
