### ISSUE TITLE
Write GH Action to perform H2.0 Catalog Load Test in Staging

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4599]
## User Story

In order to accurately assess the performance of our new harvesting system, and to ensure ongoing testing can be completed smoothly, datagovteam wants to create a Github action to run a harvest of a single source, report on it, then clean up the resources.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I have provided a harvest source title, url, owner_org, and source_type to the script invoked by GH Actions
  THEN I expect to see the records corresponding to that source harvested and created in the Data.gov staging environments instance of catalog.

- [ ] GIVEN the script has processed the records for the above harvest source,
  THEN the script will output a report of the actions performed and a list of metrics: count, time, and any other metrics that are identified as important to benchmark performance

- [ ] GIVEN the script has generated a report,
  THEN the GH Action will then cleanup the resources in the staging environment to ensure that the next invocation can run cleanly.

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Take code to run a harvest and put it in a script
- [ ] Create a GH action that invokes the above script
- [ ] Supply the GH action with the values needed for harvesting: title, url, owner_org, and source_type
  - [ ] by hard coding those values
  - [ ] making them available in a JSON source
  - [ ] or ideally by making them configurable inputs to the GH action
- [ ] Create a report method to output job metrics
  - [ ] return them to standard out
  - [ ] push them to an external log file
- [ ] Create a script to delete all the records processed by the above load test
  - [ ] As CKAN provides no documented way to batch delete this will more than likely involve a DB reset.

**Comment by rshewitt** [comment]
recent load on staging processed for about 4.5 hours before pausing indefinitely. restarting the harvesting script at the same source didn't result in the same pause but instead a completion of processing for that source

[harvest_load.log](https://github.com/GSA/data.gov/files/14113713/harvest_load.log)

**Comment by rshewitt** [comment]
need to update hashing in harvesting logic to reflect what's happening in [datajson extension](https://github.com/GSA/ckanext-datajson/blob/a3bc214fa7585115b9ff911b105884ef209aa416/ckanext/datajson/datajson.py#L279). two hash algorithms have been used so we need to use the correct one.

**Comment by rshewitt** [comment]
ckanifying a dcatus record is almost instant, often taking at most a millisecond to process. this occurs immediately before creating/updating on ckan. previous loads have paused indefinitely near record creation/updating. I say near because previously I didn't have a logging statement indicating the completion of the ckanifying function, this has since been added. i don't think ckanifying a record causes this pause. my gut is that it has something to do with a timeout not occuring. not sure if the [ckan.requests.timeout](https://docs.ckan.org/en/2.9/maintaining/configuration.html#:~:text=timeout%20%3D%203-,Default%20value%3A%205,-Default%20timeout%20for)  configuration is applicable here. the current harvester probably doesn't do this so what's different?

**Comment by rshewitt** [comment]
ckanapi.RemoteCKAN relies on a [session object](https://github.com/ckan/ckanapi/blob/963f92716e1a0d514cedab51e8f389a5fe881c6b/ckanapi/remoteckan.py#L91-L92) to make requests regardless of whether one is provided. i'm gonna try to pass a session when I initialize remoteckan with a default timeout of 15 secs to see if it fixes the pause issue. something like...
```python
session = requests.Session()
session.request = functools.partial(session.request, timeout=15)
ckan = ckanapi.RemoteCKAN(
    os.getenv("CKAN_URL_STAGE"),
    apikey=os.getenv("CKAN_API_TOKEN_STAGE"),
    session=session,
)
```

**Comment by btylerburton** [comment]
https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-requests-timeout

Looks like the timeout is for GET requests only.

**Comment by btylerburton** [comment]
Have you run the load test a few times, does it always happen at the same point? What are the exact steps that happen between ckanifying the record and the POST?

**Comment by rshewitt** [comment]
> Have you run the load test a few times, does it always happen at the same point? What are the exact steps that happen between ckanifying the record and the POST?

so far it has happened at different points. the only thing which occurs between ckanifying the record and the POST is a retrieval of the current datetime with the intention of clocking how long ckan takes to update/create

**Comment by rshewitt** [comment]
one load instance processed from 2024-01-30 14:16:07,080 to 2024-01-30 18:37:22,957 so roughly 4.25 hours

**Comment by rshewitt** [comment]
another load instance processed from 2024-01-25 22:41:39,188 to 2024-01-26 00:03:16,472 so roughly 1.3 hours

**Comment by rshewitt** [comment]
the current load test has been stable for about 5.5 hours

**Comment by rshewitt** [comment]
latest load test ran for 12.5 hours. I was intending on having it run all night but accidentally closed vsc. I'm confident it would have still been processing. I'm pretty sure configuring the timeout for requests in the session object did the trick. I want to double check and make sure that doesn't alter that setting globally for all requests ( e.g. when we `requests.get` a dcatus catalog ) 

[harvest_load.log](https://github.com/GSA/data.gov/files/14181966/harvest_load.log)

**Comment by rshewitt** [comment]
adding notes on my fixes in my last pr here. i figure the more info on our load tests the better
- configured `session.request` to have 15s timeout to fix the hangup issue
- fixed an issue with the `get_ckan_records` by passing an empty list to results on function call which caused results from a previous harvest source to persist ( weird one )
- made a slight optimization to the `get_ckan_records` function which reduces the number of requests made to ckan by 1 per harvest source

**Comment by rshewitt** [comment]
I grabbed the necessary munge functions and placed them into a separate ckan utility script rather than adding ckan as a dependency

**Comment by btylerburton** [comment]
Running load test on NIST source in Load Test Org...
Load test:
https://github.com/GSA/datagov-harvesting-logic/actions/runs/7805777861/job/21290708117
Catalog Admin link to Test Org:
https://catalog-stage-admin-datagov.app.cloud.gov/organization/load-test-org

**Comment by btylerburton** [comment]
Initial load test of NIST data source:

Run:
Time 1h33m20s
https://github.com/GSA/datagov-harvesting-logic/actions/runs/7805777861/job/21290708117

Report:
[2024-02-06 22:09:19,622] INFO [harvester.harvest.report:336] expected operations to be done
[2024-02-06 22:09:19,622] INFO [harvester.harvest.report:337] {'delete': 0, 'create': 982, 'update': 0}
[2024-02-06 22:09:19,622] INFO [harvester.harvest.report:355] actual operations completed
[2024-02-06 22:09:19,623] INFO [harvester.harvest.report:356] {'deleted': 0, 'updated': 0, 'created': 899, 'nothing': 83}
[2024-02-06 22:09:19,623] INFO [harvester.harvest.report:359] validity of the records
[2024-02-06 22:09:19,623] INFO [harvester.harvest.report:360] {'valid': 982, 'invalid': 0}

New Relic:
5.57s average transaction time
13.5 records per minute

CKAN:
908 records in Load Test Org

**Comment by btylerburton** [comment]
Subsequent load test of NIST data source:
_no records from previous run deleted_

Run:
Time 3m12s
https://github.com/GSA/datagov-harvesting-logic/actions/runs/7807177293/job/21295024865

Report:
[2024-02-06 22:52:50,447] INFO [harvester.harvest.report:336] expected operations to be done
[2024-02-06 22:52:50,447] INFO [harvester.harvest.report:337] {'delete': 0, 'create': 79, 'update': 0}
[2024-02-06 22:52:50,448] INFO [harvester.harvest.report:355] actual operations completed
[2024-02-06 22:52:50,448] INFO [harvester.harvest.report:356] {'deleted': 0, 'updated': 0, 'created': 0, 'nothing': 982}
[2024-02-06 22:52:50,448] INFO [harvester.harvest.report:359] validity of the records
[2024-02-06 22:52:50,448] INFO [harvester.harvest.report:360] {'valid': 79, 'invalid': 903}

New Relic:
.012s average transaction time
6.5 records per minute

CKAN:
908 records in Load Test Org

**Comment by btylerburton** [comment]
Ran adapted package clear command, see here: https://gist.github.com/btylerburton/c73aeb43b3208374f42332a383f3bfa7

Admin DB reports:
```
cgawsbrokerprod9ujc4bpcbx8f2kc=> SELECT state, count(*) from package
WHERE owner_org = 'b9bfa457-9f66-4aab-861a-ceac5b53ad6d'
AND type = 'dataset'
GROUP BY state;
 state | count 
-------+-------
(0 rows)
```

Org page initially returns an internal server error until db-solr-sync job is re-run.

Load test delete SUCCESS. 
Load Test Org resolves and reports 0 datasets.

**Comment by btylerburton** [comment]
New load test of NIST source
variable: increased memory to 2G
result: no variation

3 runs total
- 1st run encountered several 500 errors
- 2nd run completed bulk of work
- 3rd was validation that no new datasets would be created

**First:**

GH Action: 11m37s
https://github.com/GSA/datagov-harvesting-logic/actions/runs/7818029259/job/21327305423

New Relic:
4.7s average transaction time
10.5 records per minute

CKAN:
121 records in Load Test Org

[2024-02-07 16:43:40,271] INFO [harvester.harvest.report:336] expected operations to be done
[2024-02-07 16:43:40,271] INFO [harvester.harvest.report:337] {'delete': 0, 'create': 982, 'update': 0}
[2024-02-07 16:43:40,271] INFO [harvester.harvest.report:355] actual operations completed
[2024-02-07 16:43:40,271] INFO [harvester.harvest.report:356] {'deleted': 0, 'updated': 0, 'created': 121, 'nothing': 861}
[2024-02-07 16:43:40,271] INFO [harvester.harvest.report:359] validity of the records
[2024-02-07 16:43:40,271] INFO [harvester.harvest.report:360] {'valid': 982, 'invalid': 0}

**Second:**

GH Action: 1h5m7s
https://github.com/GSA/datagov-harvesting-logic/actions/runs/7818912842/job/21330173969

New Relic:
4.7s average transaction time
15.2 records per minute

CKAN:
121 records in Load Test Org

[2024-02-07 18:45:03,457] INFO [harvester.harvest.report:336] expected operations to be done
[2024-02-07 18:45:03,457] INFO [harvester.harvest.report:337] {'delete': 0, 'create': 861, 'update': 0}
[2024-02-07 18:45:03,458] INFO [harvester.harvest.report:355] actual operations completed
[2024-02-07 18:45:03,458] INFO [harvester.harvest.report:356] {'deleted': 0, 'updated': 0, 'created': 782, 'nothing': 200}
[2024-02-07 18:45:03,458] INFO [harvester.harvest.report:359] validity of the records
[2024-02-07 18:45:03,458] INFO [harvester.harvest.report:360] {'valid': 861, 'invalid': 121}

**Comment by rshewitt** [comment]
`Record` instances have a default status of "nothing" ( [source](https://github.com/GSA/datagov-harvesting-logic/blob/369b124539b90a74187dd75f371cf071494f5cca/harvester/harvest.py#L409) ). the reason for using "nothing" instead of `None` is to maintain dtypes. only when the record has successfully been updated, deleted, or created does the [status change](https://github.com/GSA/datagov-harvesting-logic/blob/369b124539b90a74187dd75f371cf071494f5cca/harvester/harvest.py#L640-L651) to reflect what occurred

**Comment by btylerburton** [comment]
02.07.23 load test of NIST source
variable: 
- increased instances of catalog-admin to 2
- restricted memory to original 850M

result: slight improvement

GH Action: 1h 11m 53s
https://github.com/GSA/datagov-harvesting-logic/actions/runs/7821598434/job/21338902807

New Relic:
4.6s average transaction time
16.6 records per minute

CKAN:
902 records in Load Test Org

[2024-02-07 23:02:04,153] INFO [harvester.harvest.report:336] expected operations to be done
[2024-02-07 23:02:04,153] INFO [harvester.harvest.report:337] {'delete': 0, 'create': 982, 'update': 0}
[2024-02-07 23:02:04,154] INFO [harvester.harvest.report:355] actual operations completed
[2024-02-07 23:02:04,154] INFO [harvester.harvest.report:356] {'deleted': 0, 'updated': 0, 'created': 902, 'nothing': 80}
[2024-02-07 23:02:04,154] INFO [harvester.harvest.report:359] validity of the records
[2024-02-07 23:02:04,154] INFO [harvester.harvest.report:360] {'valid': 982, 'invalid': 0}

**Comment by btylerburton** [comment]
Let's close this. We've learned what we needed to learn.
