### ISSUE TITLE
RDS Cloud.gov upgrades

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4601]
## User Story

In order to keep the SSB connections alive, cloud.gov admins want all RDS instances to be moved to a supported MySQL instance.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN the cloud.gov responds to our checks \
  WHEN cloud.gov reviews the data.gov services on cloud.gov \
  THEN there are no instances that will be upgraded automatically by AWS \

## Background

See email from [cloud.gov Support](support@cloud-gov-new.zendesk.com) on 1/30/2024

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch

Follow the steps laid out in the email:

Heavily Recommended: Create a new db instance, migrate the data, test your application, delete the old db instance.
There is tooling provided at [https://github.com/cloud-gov/cg-manage-rds ](https://github.com/cloud-gov/cg-manage-rds)which shows how to import and export brokered databases
Additional upgrade help for MySQL 5.7 to 8 can be found at https://dev.mysql.com/blog-archive/upgrading-to-mysql-8-0-here-is-what-you-need-to-know/

List of items to be upgraded:

space | instance name | instance engine | TODO
 -- | -- | -- | -- |
management-staging | ssb-smtp-db | mysql | 
management | ssb-smtp-db | mysq | 
prod | dashboard-db | mysql | This doesn't need to be upgraded, just removed (confirm data retention/backup policy)
management | ssb-eks-db | mysql | This isn't utilized in production, can be utilized for testing
 management-staging | ssb-eks-db | mysql | This isn't utilized in production, can be utilized for testing

Expected tasks for each DB:

1. Take a dump of the DB
2. Create a new DB in a supported version
3. Load DB dump into new DB
4. Switch out names/connections such that the application connects with the DB
5. Verify SSB service works as expected.

**Comment by FuhuXia** [comment]
There is an unexpected issue to go the recommended route. The brokerpak app seems to be tied with the existing database, as if it reads its guid . I tried to clone a db, do all the service renaming and app restarting/restaging, the app failed to start wheneven the old service is unbind'ed, regardless its service name, with error message:
```
"cloud-service-broker.Invalid VCAP_SERVICES environment variable - falling back to explicit environment variables","log_level":1,"data":{}}
"cloud-service-broker.Database Setup","log_level":2,"data":{"error":"DB_HOST, DB_USERNAME and DB_PASSWORD are required environment variables"}}
```

**Comment by FuhuXia** [comment]
Talked to Mark Boyd from cg-support. If we don't want to fix the way how broker app is bound with db  service before the Feb 29 deadline, we can take the other route and upgrade the mysql db engine in place, so that the db identifier (cf guid/aws arn...) remains the same to the app. Will work with cg-support and do in the staging space first.

**Comment by FuhuXia** [comment]
Verified that `gsa-datagov:management-staging:ssb-smtp-db` was upgraded to mysql `8.0.36`.
Verified that staging email was working with mysql `8.0.36`.
Verified we can create service, bind service to app with mysql `8.0.36`.

```
cf t -s staging
cf create-service datagov-smtp base testing-smtp -c '{}' -b ssb-smtp-gsa-datagov-staging
cf bind-service catalog-web testing-smtp
...
...
cf unbind-service catalog-web testing-smtp
cf delete-service testing-smtp
```

Instructions was given to cf-support to upgrade all remaining mysql old engine.
