### ISSUE TITLE
Solr Search Response Time

### ISSUE THREAD

**Issue by gujral-rei** [GSA/data.gov#4608]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

Check the [O&M Rotation Schedule](https://docs.google.com/spreadsheets/d/1cF73HkzFuQth3z9voLfVO1Cc4kjBd6ecHGE2gkj5LCc/edit?usp=sharing) for future planning.

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
- [ ] [Check Production State/Actions](https://github.com/GSA/data.gov#datagov-actions)
> **Note: Catalog Auto Tasks**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.
- [ ] [Check auto generated O&M tickets](https://github.com/orgs/GSA/projects/11?pane=issue&itemId=47716346) from no status column
- [ ] Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)
    - NOTE: This job will consistently timeout, but it is processing results ((more details)[https://github.com/GSA/data.gov/issues/4345])
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)

## Monthly Checklist
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

## ad-hoc checklist
- [ ] audit/review applications on cloud foundry and determine what can be stopped and/or deleted. 

## Reference
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)
-   Update and revise [Data.gov O&M Tasks](https://docs.google.com/document/d/1SVkY7SUhkcu6IAXIyuVo-s_E_Z400Is1JG9v5rbI7mI/edit?usp=sharing)

**Comment by gujral-rei** [comment]
Per New Relic, the SOLR search takes around 6 seconds on average. The number of requests stays constant at around two requests per minute. I'm not sure if it's typical for SOLR to take this long, irrespective of the type of transaction.

https://one.newrelic.com/nr1-core/apm-features/transactions/MTYwMTM2N3xBUE18QVBQTElDQVRJT058MTAwMzAxMDk1Ng?account=1601367&duration=259200000&state=ecca532c-8046-2ce7-562f-35b935e08ac7

![Image](https://github.com/GSA/data.gov/assets/149192026/336c3f16-503b-40c2-bee6-b13f98b319b6)

**Comment by gujral-rei** [comment]
I re-checked with Fuhu, and the average response time of 6 to 8 seconds is not normal. The image and link below give more details.

Below is the link: https://onenr.io/02R5zLdl0jb

![Image](https://github.com/GSA/data.gov/assets/149192026/9c3497a6-94ae-4db4-8897-48e9ed7f3dc8)

**Comment by gujral-rei** [comment]
On average, the SOLR servers are processing the requests with 200 to 300 milliseconds. However, considering the above analysis and the analysis below, the time taken to parse the SOLR response from the SOLR server is likely the bottleneck.  When we look at it from a Transaction standpoint (total time including a trip to the SOLR server), the SOLR transaction takes 5 seconds on average. When we look at it from the SOLR DB/Servers standpoint, it is taking around 200 to 300 ms. So, where did 4.5 seconds go?

Average
SELECT average(apm.service.datastore.operation.duration * 1000) FROM Metric WHERE (entity.guid = 'MTYwMTM2N3xBUE18QVBQTElDQVRJT058MTAwMzAxMDk1Ng') AND ((`db.system` = 'Solr')) FACET `db.system` LIMIT 5 SINCE 1 week  AGO TIMESERIES 

Max
SELECT max(apm.service.datastore.operation.duration * 1000) FROM Metric WHERE (entity.guid = 'MTYwMTM2N3xBUE18QVBQTElDQVRJT058MTAwMzAxMDk1Ng') AND ((`db.system` = 'Solr')) FACET `db.system` LIMIT 5 SINCE 1 week  AGO TIMESERIES 



![Image](https://github.com/GSA/data.gov/assets/149192026/e7371426-cbeb-49ca-be3f-1e3b43f5e482)



![Image](https://github.com/GSA/data.gov/assets/149192026/f0e14e46-8186-4747-ac36-3336ddf7cf00)

**Comment by gujral-rei** [comment]
I continued looking for why the transactions were taking slowly and narrowed it down to the fact that we call SOLR DB up to 20 times in one web request. While one SOLR request may take between 200 to 300 milliseconds (this can be further improved), calling it 20 times in one request makes it around 5 seconds on average. We have to look at the code block and see if there is a for loop that can be optimized.

https://onenr.io/0oR8G5dv3wG



![Image](https://github.com/GSA/data.gov/assets/149192026/e0a350ed-937a-46ce-b76f-d7bbbc22b2ee)

**Comment by FuhuXia** [comment]
That is good finding. 20+ solr transactions in one request makes sense, since ckan lists 20 datasets per pagination. These 20 datasets can be loaded with one solr transaction, not 20 transactions.

**Comment by jbrown-xentity** [comment]
That is a crazy number. I would be surprised if we're getting the datasets one at a time; I think more likely it's related to the filters on the left side. Each filter needs to scan the entire catalog and summarize the numbers for each thing (21,378 datasets are in the `Local Government` Topic, for instance). These 9 categories, called each time the catalog search loads, probably contributes to the slowdown...

**Comment by FuhuXia** [comment]
@jbrown-xentity the proof to support the slowness iis due to 20 solr calls for 20 datasets on one page, not facet queries, is that on pages with less dataset listed, such as last page, or some search result returns few datasets, the load time is much less. still same amount of facet queries, but less datasets. I think all the facets query is done within one call.

**Comment by btylerburton** [comment]
Great findings here @gujral-rei. If pagination is controlled by a config we could change the number and confirm. 

@FuhuXia do you think there's low hanging fruit here to reduce those calls to a single transaction? If it was that easy, I'd think CKAN core would've been optimized already.

**Comment by FuhuXia** [comment]
We can confirm the findings and then file an issue to CKAN core. It's not a problem for instances with Solr sitting right next to it. It's for us where Solr is across many infrastructure spaghetti cables.

**Comment by btylerburton** [comment]
@FuhuXia did the upgrade to 2.10.4 solve this issue?

**Comment by FuhuXia** [comment]
No. But during the testing I confirmed on my local that there is only **one** solr call for each page listing, not 20. So we need to look more into the 20-time solr call finding.

**Comment by jbrown-xentity** [comment]
This has been remediated.
