### ISSUE TITLE
newrelic-java fails on solr hosts, expecting tomcat6 to be installed

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#461]
```
TASK [monitoring/newrelic/java-agent-ansible : Pass the -javaagent argument on tomcat] **********************************************************************************************
fatal: [datagovsolr3p.prod-ocsit.bsp.gsa.gov]: FAILED! => {"changed": false, "checksum": "5f72d6d448624f82f6e30329c767839429c58f4d", "failed": true, "msg": "Destination directory /usr/share/tomcat6/bin does not exist"}
```

**Comment by adborden** [comment]
@JJediny can we drop the newrelic-java support? seems strange to be profiling solr. Isn't the infrastructure agent enough?

**Comment by JJediny** [comment]
@adborden I think its still worth having to profile the JVM environment for errors/threads/etcs if its just a matter of changing the ansible playbook to pass the `-javaagent` argument to jetty. https://docs.newrelic.com/docs/agents/java-agent/installation/include-java-agent-jvm-argument#Installing_on_Jetty

**Comment by nickumia-reisys** [comment]
This ticket is technically superseded by
- https://github.com/GSA/data.gov/issues/3956
