### ISSUE TITLE
Create Basic Flask Harvest Administration App

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4619]
## User Story

In order to add new harvest sources to our Harvest DB, datagovteam wants to create a new Flask app to handle basic CRUD of Harvest Source configs, and to kick off harvest jobs.

Links:
- Datagov Harvest Orchestrator repo: https://github.com/GSA/datagov-harvest-orchestrator
- Tutorial for adding a basic form to your Flask app: https://www.digitalocean.com/community/tutorials/how-to-use-flask-sqlalchemy-to-interact-with-databases-in-a-flask-application
- Previous work done on Flask / DB integration: https://github.com/GSA/data.gov/issues/4612#issuecomment-1947326542

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

Harvest Source Form Fields:

```
name (str) **required
notification_emails (array)
organization_name (str) (*self-reported)
frequency (str) (cron) **required
url (str) **required
schema_type (str) **required
source_type (str) **required

```

- [x] GIVEN I have created a Flask app and added it to the repository above
AND that app has imported datagov-harvesting-logic as a dependency
THEN I can proceed with the creation of the routes below

- [x] GIVEN I call the route `{url}/harvests/new`
AND I have followed [the pattern](https://www.digitalocean.com/community/tutorials/how-to-use-flask-sqlalchemy-to-interact-with-databases-in-a-flask-application) outlined in the links above to develop a form to update Harvest Source with the fields outlined above
WHEN I save a new Harvest Source with a valid config then I expect it to post to the Harvest DB.

- [x] GIVEN I call the route `{url}/harvests/{id}`
THEN I expect to see the details for the harvest source with the corresponding id.

- [x] GIVEN I call the route `{url}/harvests/` with no corresponding ID
THEN I expect to see a list of all harvest sources in the DB

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [x] Create basic Flask app 
  - Potentially [reusing code from this branch](https://github.com/GSA/datagov-harvesting-logic/tree/create-harvest-db)
- [x] Import datagov-harvesting-logic as a dependency
- [x] Move [initialization](https://github.com/GSA/datagov-harvesting-logic/blob/22c380afa890378f6536daaeac38aee49776c15c/harvester/database/init_db.py) of DB Tables out of harvesting logic and into this repo
  - [x] Make this an invokable script that can ideally can be run from the commmand line
- [x] Create routes to GET one config / all configs
- [x] Create route to POST to a new config and create the corresponding form template

**Comment by krishnasanaka** [comment]
Created below branch in repo and ran flak app on localhost 
https://github.com/GSA/datagov-harvest-orchestrator/tree/Create_Basic_Flask_Harvest

<img width="366" alt="Capture" src="https://github.com/GSA/data.gov/assets/156855484/9f9d87df-74fe-409c-8862-fd5d2960b1b3">

**Comment by krishnasanaka** [comment]
Imported datagov-harvesting-logic as a dependency into datagov-harvest-orchestrator repo

**Comment by krishnasanaka** [comment]
Created invokable script and testing it.

**Comment by krishnasanaka** [comment]
Invokable script running from  command line and creating  DDL's 
![Capture](https://github.com/GSA/data.gov/assets/156855484/d98b57bd-834d-4a16-aafa-bc8a51df9a9e)

**Comment by krishnasanaka** [comment]
Working on POST method, created UI page to insert data into PostgresDB and verified data is inserted successfully.
![Capture3](https://github.com/GSA/data.gov/assets/156855484/93ed57a8-5367-46af-a32d-4c467fd4b5b6)
 inserted 
![Capture2](https://github.com/GSA/data.gov/assets/156855484/8d1afa95-f6ee-474c-a46f-470e6b8ce617)

**Comment by krishnasanaka** [comment]
GET for one and all records in DB
![GET all records](https://github.com/GSA/data.gov/assets/156855484/fe9aa9f2-e547-400a-96d3-7180d0ddfb4d)
![GET one record](https://github.com/GSA/data.gov/assets/156855484/ea5958d6-8da1-42b9-8a48-61dba5285d4e)

**Comment by Jin-Sun-tts** [comment]
The code has been transferred from the `datagov-harvesting-logic` repository, and it has been configured, set up, and thoroughly tested. PR: https://github.com/GSA/datagov-harvest-orchestrator/pull/1

**Comment by krishnasanaka** [comment]
Post request with  updated fields 
![Post](https://github.com/GSA/data.gov/assets/156855484/0ef7287c-270b-4ca1-bfdb-34f74f5516fb)

**Comment by Jin-Sun-tts** [comment]
please check https://harvester-dev-datagov.app.cloud.gov/ for the basic Flask app.

**Comment by Jin-Sun-tts** [comment]
![Image](https://github.com/GSA/data.gov/assets/104456257/1f4f86b9-8b40-4abb-8b6e-00a5e2b30c48)
