### ISSUE TITLE
Create New Harvester UI repository and test data

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4626]
## User Story

In order to give our agency partners a view into the state of their harvest sources, datagovteam wants to create a Harvest UI application. This initial ticket will establish the framework and basic test data for the views.

## Acceptance Criteria

GIVEN I have created a repo to house the harvester-ui code
AND I have provided a docker-compose file for launching the test API, plus a Makefile for convenience
WHEN I run `make dev` I'm going to see a working instance of harvest DB API with the following routes:
- For an organization at `localhost:5000/api/organization/{org_id}`
- For a harvest source at `localhost:5000/api/harvest/{source_id}`
- For a harvest job api at `localhost:5000/api/job/{job_id}`

## Background

A harvest UI will encompass, at minimum, three-interrelated views: harvest job, harvest source, and organization.

A harvest job contains information about a particular harvest job. A harvest source contains information about the source itself and a list of harvest jobs. An organization contains a list of all associated harvest sources.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

This application will be open to the public, but will be read-only, drawing from the datagov-harvest-orchestrator's API so there will be no risk of database compromise with this application, and it will set behind cloudfront, so all views will be cacheable, whereas the live data will not.

## Sketch

- [ ] Create Github repo
- [ ] Run `npm create svelte@latest datagov-harvest-ui` to create a new Svelte boilerplate project structure and link that to the github repo
- [ ] Create a Docker compose file which will spin up a DB and a basic Flask API with the routes specified in the AC:
  - [ ] organization
  - [ ] harvest source
  - [ ] harvest job

**Comment by rshewitt** [comment]
are we still intending on completely replacing catalog/inventory front-end? i know the current ui work is internal so I think people can pursue whatever framework they want but we may want to solidify something ( maybe get a list of options and discuss) before too much work is invested

**Comment by btylerburton** [comment]
Yeah, that is the plan. Given whatever we build catalog with will use USWDS, I feel less urgency to determine UI direction as opposed to searchability which feels like the bigger part of the usability discussion.

**Comment by btylerburton** [comment]
merged
