### ISSUE TITLE
Resolve DAP Script Regression

### ISSUE THREAD

**Issue by dlennox24** [GSA/data.gov#4632]
## User Story

With the switch to the official CKAN analytics plugin, we lost the analytics script injection for DAP. We need to add this back so DAP can receive analytics data from catalog and data.gov.

## Acceptance Criteria

- [ ] GIVEN DAP script is in the CKAN template
THEN analytical data is flowing into the DAP properties for data.gov

## Sketch

- [x] Add the following script to the [base.html](https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/templates/base.html) template (? unsure if this is the proper CKAN template)
```html
<script 
    id="_fed_an_ua_tag"
    src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA&subagency=TTS"
/>
```
- [x] Validate the script is being injected into the HTML page of both catalog pages and static pages on data.gov
- [x] Verify the data is flowing into DAP for data.gov

**Comment by FuhuXia** [comment]
We used to have similar code before this commit
https://github.com/GSA/ckanext-datagovtheme/commit/6db62df

**Comment by dlennox24** [comment]
@FuhuXia Would you be able to take a look at https://github.com/GSA/ckanext-datagovtheme/pull/186 and give it a review?
