### ISSUE TITLE
Explore replacing existing GA tags with CKAN-supported Google Tag Manager

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4633]
## User Story

In order to more easily manage google analytics tags and custom analytics, datagov team members want to implement Google Tag Manager (GTM).

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN CKAN can support using GTM \
  AND the team has a desire to manage analytics tags without touching site code \
  WHEN a pageload happens \
  THEN Google Tag Manager will fire and collect data to send to the datagov and DAP GA accounts \

## Background

For the work we'd like to do to customize Google Analytics to track specific downloads, button clicks, or capture `publisher` to create more meaningful metrics, getting GTM in place would allow Tim and/or other less technical team members to use the GTM interface to create custom triggers or send data to the dataLayer.

This _appears_ to be supported by CKAN https://github.com/ckan/ckanext-googleanalytics/blob/24d9a7ff62235bc2d543e6594f7362763411b0f9/ckanext/googleanalytics/templates/googleanalytics/snippets/_gtm.html

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

Will need to potentially add to SSPP/ATO docs.

The GTM account permissions should be well-managed and documented so that no unwanted parties can access.

## Sketch

- [x] Research if GTM is supported by CKAN
- [x] Set up GA tags in GTM
- [x] Add GTM tags to dev environment
- [x] Use GTM debugger to check if firing
- [ ] Confirm traffic in datagov and DAP GA accounts

**Comment by tdlowden** [comment]
GTM ID: GTM-WZJC8CX7

@dlennox24 are you able to try pushing this to `dev` sometime Monday?

**Comment by dlennox24** [comment]
@tdlowden Yes! Working PR is available here: https://github.com/GSA/ckanext-datagovtheme/pull/187

**Comment by tdlowden** [comment]
Can confirm GTM is firing on `dev`. Right now, I have the data.gov GA4 tag `paused`, because when we push to prod, we'll need to remove the existing <script> tag at the same time I make the GTM tag active. 

![image](https://github.com/GSA/data.gov/assets/6556888/9ecd8078-141e-4ef1-a5f4-5d164e419e69)

**Comment by tdlowden** [comment]
an aspect of this I forgot to document is that we need to remove the existing `<script>` tag from catalog (or anywhere this GTM container is being implemented) because I created the GA tag from within the GTM interface to be fired from the container. @dlennox24 I spoke with @FuhuXia and he is going to push the container to `prod`, but I'll leave the GA tag in GTM paused. Then you and I can coordinate to remove the existing script and simultaneously turn on the GTM tag.
