### ISSUE TITLE
Complete Content Review

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4635]
As per the TTS Digital Council, a quarterly content review is now being required. 

We'll do a manual review of content using this for: https://docs.google.com/spreadsheets/d/1TKzf_56bD3iadlprSynbzgEiobu2ilujXFcFeMMYaTg/edit#gid=1519962703

Acceptance Criteria

- [x] Content for each static page is reviewed
- [ ] Any out-of date content is removed or edited as needed
- [ ] Broken links are removed or edited

**Comment by tdlowden** [comment]
Using this spreadhseet https://docs.google.com/spreadsheets/d/1TKzf_56bD3iadlprSynbzgEiobu2ilujXFcFeMMYaTg/edit#gid=1519962703

Also #4277 will be worked on to help complete

**Comment by hkdctol** [comment]
We've completed the compliance exercise and have open issues for related work
