### ISSUE TITLE
Link checking does not produce accurate results

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4636]
Based on https://github.com/GSA/data.gov/issues/4182, the previously used `curl` method for checking the status of links doesn't produce accurate results, bc some links are "not `curl`-able". Since we are going to have to execute quarterly content reviews for the TTS Digital Council, it would behoove us to have a reliable, automated solution for efficiency.

## How to reproduce

1. Run previous methods of link checking using `curl`

## Expected behavior

An automated process to crawl pages and check links will provide a list of links that do not resolve, so that we may replace them or remove them to be compliant with quarterly content reviews.

## Actual behavior

Currently, the method previously used does not provide an accurate reporting of links that truly do not resolve, in some cases reporting false negatives.

## Sketch

TBD

**Comment by rshewitt** [comment]
These sites implement `htmlproofer` as an automated link checker. If you check out their respective `package.json` file you'll see a `qa` script using it
- [data-strategy](https://github.com/GSA/data-strategy) 
- [resources](https://github.com/GSA/resources.data.gov)
- [us-data-federation](https://github.com/GSA/us-data-federation)

related ticket: [#4277](https://github.com/GSA/data.gov/issues/4277)

**Comment by tdlowden** [comment]
Oy, sorry to duplicate tickets. Thanks for that catch @rshewitt. Great, looks like we're almost at the finish line? @rshewitt it seems like I should close this issue as a dupe, would you agree? Then we can just ask @gujral-rei to add the existing open issue to the next sprint plan workload.

**Comment by rshewitt** [comment]
yeah I think closing this is fine @tdlowden

**Comment by btylerburton** [comment]
I think we can close this as a dupe and then pull the other ticket higher into product backlog. Reid worked on this for a bit but we never got a clean solution and then harvester work took precedence. If we have capacity, this would be a nice one to close out along with the sitemaps ticket.

**Comment by tdlowden** [comment]
Sounds good! closing
