### ISSUE TITLE
Add logrotate roles to catalog-harvester

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#464]
Just found a 14G ckan_tracking.log on harvester2p. Here's a list of some recent logs that are not configured with logrotate.

```
- [ ] ckan-combine-feeds.log
- [ ] ckan-export-csv.log
- [ ] ckan_report.log
- [ ] ckan_tracking.log
- [ ] harvest_job_cleanup.log
- [ ] pycsw_load.log
- [ ] sitemap-to-s3.log
```

**Comment by adborden** [comment]
I _think_ [log rotation is handled by supervisor](http://supervisord.org/logging.html#child-process-logs). We should confirm this is true and configured correctly. Then this story becomes "ensure jobs are running in supervisor".

I want to call out https://github.com/GSA/datagov-deploy/issues/1106, for fetch-consumer.log we have log rotation in addition to supervisor. If we confirm how supervisor handles log rotation, we should remove our logrotate config for the harvest jobs.

**Comment by nickumia-reisys** [comment]
Ansible no longer being used.
- https://github.com/GSA/data.gov/issues/3710

Logs are being stored in NR now for 3 months.  Cloud.gov might have an archiving process for logs older than that, but I'm not sure.
