### ISSUE TITLE
search certain keywords such as catalog in data.gov generate complete irrelevant result 

### ISSUE THREAD

**Issue by guocity** [GSA/data.gov#4640]
search certain keywords such as catalog in data.gov generate complete irrelevant result 

## How to reproduce

search for keyword catalog, in data.gov, result complete irrelevant

## Expected behavior

I am expect result such as Open NY Catalog

## Actual behavior

108,261 datasets found for "catalog", dataset has no catalog

## Question
is there catalog file contain info about all 292,269 DATASETS?
what are the links to the json file harvest from each organization?

**Comment by jbrown-xentity** [comment]
Hello @guocity , thanks for your feedback!
Data.gov uses CKAN for cataloging and searching. They have some advanced features to refine you search, I encourage you to check those out [here](https://docs.ckan.org/en/2.10/user-guide.html?highlight=search#search-in-detail). For example, you can use something like `title:catalog` ([link](https://catalog.data.gov/dataset/?q=title%3Acatalog&sort=views_recent+desc&ext_location=&ext_bbox=&ext_prev_extent=)) to get datasets that have catalog in the name, or you can search `"NY Catalog"` ([link](https://catalog.data.gov/dataset/?q=%22NY+Catalog%22&sort=views_recent+desc&ext_location=&ext_bbox=&ext_prev_extent=)) to get datasets that match the whole string exactly.
As to a full export of the catalog; we don't have a single location at the moment. The best place to get that information is probably using our sitemap that google and other bots use to crawl through our data; the list of all the sitemap files (that contain the actual dataset page links) is [here](https://catalog.data.gov/sitemap.xml).
The location on where these are harvested can be browsed at https://catalog.data.gov/harvest, and to get a downloaded list you can use the CKAN API: https://catalog.data.gov/api/action/package_search?fq=dataset_type:harvest
