### ISSUE TITLE
Implement Integration of Flask Application with HarvestDB Update Feature

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#4647]
## User Story

integrate the Flask application with HarvestDB's update functionality so that database changes can be easily managed and applied within the Flask environment.

Links:
- Related work done on Flask / DB integration: https://github.com/GSA/data.gov/issues/4612#issuecomment-1947326542
- Deprecated repo : Datagov Harvest Orchestrator repo: https://github.com/GSA/datagov-harvest-orchestrator
- Planning documentation:
https://docs.google.com/document/d/1XzfTrPxu-asJ_55GoeZ2UOJsie9CuCegStS28BAL_40/

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN the code resides in the orchestrator repository
  AND the objective is to consolidate it into the harvesting-logic repository
  THEN deploy and test the app on cloud.gov and

- [x] GIVEN the team has settled on the Table structure 
  AND it has been defined in an SQLAlchemy file
  THEN it should be able to be created programmatically in a Docker container by running a DB initialization script.

- [x] GIVEN that the DB has been initialized
  WHEN alterations are made to database tables,
  THEN execute the database update function to apply updates.

## Background

Continuing the work in https://github.com/GSA/data.gov/issues/4612, implement database table structure update functions within the application logic.

## Sketch

- [x] research and test Flask-SQLAlchemy versus SQLAlchemy
- [x] test database table changes with flask commands

**Comment by Jin-Sun-tts** [comment]
Changed to `Flask-Alchemy` and organized the app directory to accommodate Flask-related files.
Also configured `Flask-Migrate` for handling database upgrades

![Image](https://github.com/GSA/data.gov/assets/104456257/5c122cc1-3c4d-4ea7-80d5-68b33fe14480)

**Comment by rshewitt** [comment]
[quick article](https://patrickkarsh.medium.com/choosing-the-right-index-database-design-basics-e797cb49a7c8#:~:text=Choosing%20the%20Right%20Columns%20to%20Index,-To%20avoid%20the&text=Look%20for%20patterns%20in%20query,of%20values%20in%20a%20column.) on some things to consider when indexing. this was more for my curiosity but liked how concise it was so i'm sharing.
