### ISSUE TITLE
Update user guide to improve search experience

### ISSUE THREAD

**Issue by gujral-rei** [GSA/data.gov#4649]
## User Story

In order to improve the searching experience on data.gov, data.gov users want more options and context into how to make more fine-grained searches.

## Sketch
Refer to ticket - #4640
We can improve the search experience by providing additional context for performing advanced searches. See sketch below.

1. Add [CKAN advanced search](https://docs.ckan.org/en/2.10/user-guide.html?highlight=search#search-in-detail) to the [user guide](https://github.com/GSA/datagov-11ty/blob/main/pages/user-guide.md), and add an advanced search section describing some of the options available.
1. Add a comment and link below the search box (fancy points for doing it only on searches that return > 1000 results): "Didn't find what you are looking for? See tips on advanced search.", and link to the section added above in the user guide.

**Comment by tdlowden** [comment]
![Image](https://github.com/GSA/data.gov/assets/6556888/af44e8e7-36d2-4c51-9f31-2ba8b859bb5d)

**Comment by tdlowden** [comment]
We decided to leave ```2. Add a comment and link below the search box (fancy points for doing it only on searches that return > 1000 results): "Didn't find what you are looking for? See tips on advanced search.", and link to the section added above in the user guide." until a future date.``` Will separate into another ticket.
