### ISSUE TITLE
Documentation and Update of community group (topic) system on data.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#465]
From harvest issues, various topic links to datasets have become broken for DOI. Need to get archived copy and reset via php tool.

**Comment by hkdctol** [comment]
@jbrown-xentity @philipashlock says there's an old copy (early 2018) that we could look at. Let's turn to this when we're able to and see if restoring tags is feasible and also decide what if anything to do going forward.

**Comment by hkdctol** [comment]
OBE; but overall issue can be brought into metadata schema update discussions

**Comment by nickumia-reisys** [comment]
Related repo:
- https://github.com/DCAT-US/DCAT-US-Schema-v3.0/issues
