### ISSUE TITLE
Catalog page URLs are not consistent with trailing slashes

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4655]
on catalog, some sources of traffic to the homepage are producing `/dataset` and some `/dataset/`. The trailing slash also varies on search terms, with some producing `/dataset?...` and some `/dataset/?...`. This disaggregates traffic in Google Analytics and makes more rows of data than is necessary.

## How to reproduce

1. navigate to data.gov, then click `Most Viewed Datasets`. You will be taken to `catalog.data.gov/dataset` (no slash)
2. Type in a search term, which will produce `/dataset?q=...` (no slash)
3. Advance to page 2 in the pagination, the URL will now be `/dataset/?q=...` (with trailing slash)

## Expected behavior

All instances of pageviews to the catalog "homepage" and searches should include the trailing slash, and have a consistent `/dataset/`

## Actual behavior

The trailing slash appears in some cases, and does not appear in some cases.

## Sketch

TBD

**Comment by tdlowden** [comment]
This could start to affect us more as we move to publishing top pages on dashboard. Moving back into `product backlog` for discussion 

![Image](https://github.com/GSA/data.gov/assets/6556888/48a20973-419a-49c9-9cf8-8c128621d4d8)

**Comment by FuhuXia** [comment]
Looking at https://demo.ckan.org/, it seems `/dataset/` is the way to stick to. We are doing redirecting `/` to `/dataset`. If we change it to /`dataset/` that should solve the problem.

**Comment by FuhuXia** [comment]
Here
https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/blueprint.py#L36-L38

**Comment by FuhuXia** [comment]
done while doing some `datagovtheme` work.
