### ISSUE TITLE
Implement link previews for catalog links on social media

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4656]
## User Story

In order to be more appealing and entice me to click, public social media users wants social meta tags on datset pages.

## Acceptance Criteria

- [ ] GIVEN the data.gov team or private individuals share links to specific dataset on social media platforms
  WHEN a catalog.data.gov link is shared to social media happens 
  THEN a link preview should appear

## Background

In posting about fascinating datasets on X, Tim noticed that catalog pages have no social meta tags to create an appealing link preview.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

None

## Sketch

- [ ] Add social meta tags to all catalog pages

**Comment by gujral-rei** [comment]
Scope effort/work.

**Comment by tdlowden** [comment]
@robert-bryson Just realized that this might be a good `og:image` as a default for data.gov and catalog.data.gov: https://s3-us-gov-west-1.amazonaws.com/cg-0817d6e3-93c4-4de8-8b32-da6919464e61/hero-image-bg.svg 

I also now realized resources.data.gov also needs to be implemented. I can create a separate ticket for that if you feel it's out of scope here.

**Comment by robert-bryson** [comment]
From slack: 
![image](https://github.com/GSA/data.gov/assets/91547795/6a9438e1-d220-4d41-94a2-660386c0a4b6)
