### ISSUE TITLE
Clean CKAN BEAKER_CACHE table daily 

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4657]
## User Story

In order to keep table BEAKER_CACHE 's size in check, datagov team wants to have it trimmed on daily basis.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a GH action task is set up to to run twice a daily \
  WHEN table BEAKER_CACHE is checked \
  THEN no entry is older than one day \
  AND total count is well below 1000000. 

## Background

We implemented this before but did not have it ported over to the cloud.gov environment. 
https://github.com/GSA/data.gov/pull/1440

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

Add the function into ckanext-geodatagov so that it can be called via `ckan geodatagov clean-beaker-cache`

**Comment by Bagesary** [comment]
Nice to have to avoid database size increase

**Comment by Bagesary** [comment]
Team will create tickets with milestone

**Comment by FuhuXia** [comment]
Last clean was 8 months ago on 2024-03-12. Now it contains 400 million records in table BEAKER_CACHE. 
```
=> select CREATED from BEAKER_CACHE order by id limit 1;
          created
----------------------------
 2024-03-12 20:25:25.182841
(1 row)

=> select count(*) from BEAKER_CACHE;
   count
-----------
 398158047
(1 row)

```

**Comment by FuhuXia** [comment]
Ran this query on catalog-db in prod space to delete the records that are more the 2 days old. 

```
DELETE FROM BEAKER_CACHE WHERE ACCESSED < CURRENT_TIMESTAMP - INTERVAL '2 day';
```
