### ISSUE TITLE
Update CKAN-to-CKAN harvester to remove deleted datsets from source

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#466]
Harvester ignores datasets that have been removed from the source, marking the harvest as an "error". Need to resolve to remove the deleted dataset.

**Comment by jbrown-xentity** [comment]
Test applied and noted successful in staging. Full validation pending on production.

**Comment by adborden** [comment]
This is done in our fork, but #2241 is about pushing that work upstream.
