### ISSUE TITLE
Change link and text to Accessibility Statement in footer of all data.gov sites

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4662]
## User Story

In order to better serve users with accessibility needs and remain in GSA website compliance, the TTS Digital Council wants updated links to the GSA accessibility statement.

## Acceptance Criteria

- [ ] GIVEN an accessibility link is in the footer\
  WHEN a user clicks on that link\
  THEN it should point to https://www.gsa.gov/website-information/accessibility-statement \
 AND the text should read `Accessibility Statement` instead of `Support`

## Background

USWDS has made updates to its identifier with this data. We need to update manually to be in compliance.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

None

## Sketch

- [ ] Update text to say `Accessibility Statement`
- [ ] Update link to https://www.gsa.gov/website-information/accessibility-statement
- [ ] Apply to all relevant data.gov sites if possible

**Comment by rshewitt** [comment]
prod

![Image](https://github.com/GSA/data.gov/assets/92057378/59f4a840-083e-4e32-9c1f-7f15d0e50428)


the page associated with the anchor
![Image](https://github.com/GSA/data.gov/assets/92057378/1618c3a1-001f-4737-950f-3ba9bc2115f4)

**Comment by tdlowden** [comment]
@gujral-rei need to re-open, I just checked and would like to add to resources.data.gov as well, which has not yet been addressed:

![image](https://github.com/GSA/data.gov/assets/6556888/030a7e10-2e83-489e-bc98-4b102edc3e95)

data.gov and catalog.data.gov have been remedied, and I don't think we need to worry about strategy, federation, or sdg, but resources would be good to address.

**Comment by rshewitt** [comment]
![Image](https://github.com/GSA/data.gov/assets/92057378/efc38b3f-c150-4c5f-9d5d-7eab61440385)
