### ISSUE TITLE
Annotate Data.gov and SSB SSPPs

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4664]
## User Story

In order to determine next steps in Authority To Operate renewal process, Data.gov team needs annotated version of current SSPPs marking all sections that will require changes based on a new harvester

## Acceptance Criteria

- [x] GIVEN current copies of SSPPs \
  AND current state of knowledge on replacement harvester \
  THEN Data.gov team has annotated version of current google doc versions of SSPPs indicating all sections where changes will be needed

## Sketch

- [x] Review working copy of Data.gov [SSPP](https://docs.google.com/document/d/1s7ZImF9Eb-k5aiTm3atepUNz_Z3FHnwRskwPZwiI0-g/edit?usp=drive_link) and annotate required changes
- [x] Review working copy of SSB [SSPP](https://docs.google.com/document/d/1_YNfeE8oplBiWoumXHLpp8mq7-65uhG9/edit?usp=drive_link&ouid=113511966954817069922&rtpof=true&sd=true) annotate required changes

**Comment by hkdctol** [comment]
We will meet with ISSM next steps 4/18--the work for this particular ticket is complete

**Comment by btylerburton** [comment]
Gives me time to transfer my notes from the PDF to the Cloud.gov SSPP.
