### ISSUE TITLE
[SPIKE] Discover if pg_cron will work for job kickoff

### ISSUE THREAD

**Issue by rshewitt** [GSA/data.gov#4670]
## User Story

In order to schedule a harvest job, datagov wants to utilize [pg_cron](https://github.com/citusdata/pg_cron) to implement job kickoff.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a harvest source has a defined schedule\
  WHEN it is time for a harvest source to start \
  THEN the correct signal is started/sent to the flask app to kickoff the job

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

Ideally we would follow [this blog](https://supabase.com/blog/postgres-as-a-cron-server), however it doesn't seem like the http extension is available by default in [aws RDS](https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-extensions.html#postgresql-extensions-16x).

In practice, we can test using pg_cron to create new jobs with a status of "Pending" for anything that is due for a job (and doesn't have a job currently in work or pending). Follow up work will need to be done (ticket needs to be created) that will then do polling every minute against the job table to decide on starting the job and kicking off a task. Bonus: maybe we have a job hierarchy somehow, so that any manual request gets precedent over automated requests?

**Comment by btylerburton** [comment]
this might be superceded by a revised design which init's tasks per job

**Comment by rshewitt** [comment]
sending an http request opens the database up to unclosed connections. idk if setting a timeout would mitigate this but if caution isn't properly taken the database performance could be impacted

**Comment by rshewitt** [comment]
postgres native [notify/listen](https://www.postgresql.org/docs/current/sql-notify.html)

**Comment by rshewitt** [comment]
other than pg_cron i'd like to avoid installing any other additional extensions or 3rd party libraries

**Comment by rshewitt** [comment]
[flask-socketio](https://flask-socketio.readthedocs.io/en/latest/getting_started.html). using websockets gets us full-duplex communication which seems ideal for pub/sub. [example of app](https://stackoverflow.com/questions/49462024/combining-socketio-and-simple-web-server-in-same-app-using-background-task) with both normal routes and sockets

**Comment by rshewitt** [comment]
here's the [pg_cron branch](https://github.com/GSA/datagov-harvesting-logic/tree/pg_cron). at the time of this comment all it does is install it, add the extension, and add a cleaning/vacuum job to be performed every minute. i pushed the branch without the expectation of any actions working.

**Comment by rshewitt** [comment]
it seems that we're moving away from having postgres be responsible for job scheduling and initialization in favor of having flask do it. one reason is that postgres logs aren't auditable by us. another being setup and updates on cron jobs will go through the flask app anyways

**Comment by rshewitt** [comment]
i updated the title of this ticket to a spike since that's what it ended up like
