### ISSUE TITLE
Propose strategy to consolidate federation.data.gov into resources or data.gov

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4682]
## Purpose

We want to stop supporting and being required to do compliance on federation.data.gov and strategy.data.gov, but we're not sure how to do that.

Given above desire, conducting research is needed to provide factual knowledge on future steps.

2 weeks of effort has been allocated and once complete, findings will be demonstrated and specific future actions will be decided.

### Acceptance Criteria

- [x] GIVEN availability of stakeholders
  WHEN 2 weeks expires
  THEN research will be delivered
  AND a proposal will be put forth

### Background

OMB is supportive of consolidation

### Sketch

- [x] Examine existing content and determine what should live on
- [x] Interview stakeholders about what they'd like to see
- [x] Decide a proposed spot for content to live
- [x] Make a proposal to Hyon and potentially OMB

**Comment by tdlowden** [comment]
https://docs.google.com/document/d/1w17nvZ6M4XYFqjDEyao7bZwCUbuLmM7QaJotLWKLdsU/edit

**Comment by hkdctol** [comment]
Looks good
