### ISSUE TITLE
Documented API end-point `package_list` just returns 302 HTML instead of a json with a list

### ISSUE THREAD

**Issue by yarikoptic** [GSA/data.gov#4693]
## How to reproduce

1. https://docs.ckan.org/en/latest/api/ describes endpoint working on ckan demo:

```
❯ curl --silent https://demo.ckan.org/api/3/action/package_list
{"help": "https://demo.ckan.org/api/3/action/help_show?name=package_list", "success": true, "result": ["annakarenina", "sample-dataset-1", "warandpeace"]}%   
```

2. https://data.gov/user-guide/#data-gov-ckan-api says that base URL for API is https://catalog.data.gov/api/3/  and we do get similar returned on both
```
❯ curl --silent https://catalog.data.gov/api/3/
{"version": 3}%                                                                                                                                                                     
❯ curl --silent https://demo.ckan.org/api/3/
{"version": 3}%         
```

but that package_list endpoint doesn't:

```shell
❯ curl --silent https://catalog.data.gov/api/3/action/package_list
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.25.4</center>
</body>
</html>
```

and even if request JSON:

```shell
❯ curl --silent -H 'accept: application/json' https://catalog.data.gov/api/3/action/package_list
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.25.4</center>
</body>
</html>
```
## Expected behavior

get a listing of datasets

## Actual behavior

302

**Comment by FuhuXia** [comment]
Action `package_list` is blocked on purpose. Use `package_search` instead.

**Comment by yarikoptic** [comment]
Is there a way to get a full list of datasets without abusing search end point?

**Comment by FuhuXia** [comment]
Sure, `package_search` can get you paginated full list of datasets. For example:
```
https://catalog.data.gov/api/3/action/package_search?sort=id+asc&fl=id&rows=1000&start=0
https://catalog.data.gov/api/3/action/package_search?sort=id+asc&fl=id&rows=1000&start=1000
https://catalog.data.gov/api/3/action/package_search?sort=id+asc&fl=id&rows=1000&start=2000
...
```

**Comment by yarikoptic** [comment]
sorry - this just now came up back to my radar. Would you be so kind to show where the returned ids could be used since seems not for package_show and there is no mentioning of UUID on https://docs.ckan.org/en/latest/api/ 

```shell
❯ curl 'https://catalog.data.gov/api/3/action/package_search?sort=id+asc&fl=id&rows=2&start=0'
{"help": "https://catalog.data.gov/api/3/action/help_show?name=package_search", "success": true, "result": {"count": 318478, "facets": {}, "results": [{"id": "00004f18-62cc-4d22-aae6-724aadc7868d"}, {"id": "00006613-b2fc-4503-b928-963915936a31"}], "sort": "id asc", "search_facets": {}}}%                                          
❯ curl https://demo.ckan.org/api/3/action/package_show?id=00004f18-62cc-4d22-aae6-724aadc7868d
{"help": "https://demo.ckan.org/api/3/action/help_show?name=package_show", "error": {"__type": "Not Found Error", "message": "Not found"}, "success": false}%   
```

or in other words -- is there an option (like `metadata=1`) option to `package_search` endpoint to get as a result not just `ids` but also full associated record to avoid subsequent separate `318478` queries?

**Comment by FuhuXia** [comment]
- In the code example, you are curling the wrong domain. replace demo.ckan.org with catalog.data.gov.
- remove `&fl=id` to have the full metadata. So instead of 1st, use 2nd.
  - `https://catalog.data.gov/api/3/action/package_search?sort=id+asc&fl=id&rows=2&start=0`
  - `https://catalog.data.gov/api/3/action/package_search?sort=id+asc&rows=2&start=0`

**Comment by yarikoptic** [comment]
ha -- evil cut&paste and old 👀 , thanks @FuhuXia , seems to work nicely!
