### ISSUE TITLE
Add text and link under search bar to help users discover CKAN instructions

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4697]
## User Story

In order to improve the searching experience on data.gov, data.gov users want more options and context into how to make more fine-grained searches.

## Background

Follow on to https://github.com/GSA/data.gov/issues/4649

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

None

## Sketch

Add a comment and link below the search box: "Didn't find what you are looking for? See tips on advanced search", and link to the section in the user guide.

**Comment by btylerburton** [comment]
Put this up on dev today 10/11/24: 
https://catalog-dev.data.gov/dataset

**Comment by tdlowden** [comment]
@btylerburton can we make the link target=_blank to open in a new tab?

**Comment by btylerburton** [comment]
Yes. I remember you mentioning this on Slack. Let's get that done and then re-evaluate.

**Comment by rshewitt** [comment]
looks off on mobile

![Image](https://github.com/user-attachments/assets/a5124222-5307-4c3e-95d8-51d4f33cc5f5)

removing the top margin fixes it 

![Image](https://github.com/user-attachments/assets/b2281eee-f837-4478-9e64-3ef6aac62b5d)

but changes it on desktop ( very subtle but different )

![Image](https://github.com/user-attachments/assets/e796cf3d-d5a2-4fc3-9380-8facaea1b4db)

**Comment by tdlowden** [comment]
Great catch @rshewitt. I think it's ok with your change.

**Comment by rshewitt** [comment]
![Image](https://github.com/user-attachments/assets/886d258d-d92a-48b5-9c3b-9cf385268e15)

**Comment by rshewitt** [comment]
it should be there without querying something

![Image](https://github.com/user-attachments/assets/77e7989b-6ee3-41dd-a00d-90aff6958deb)
