### ISSUE TITLE
efficient handing of cron jobs and catalog harvester on BSP

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#47]
As most of the data.gov instances have two web servers in BSP, we need to make sure the cron jobs in dashboard / wordpress if any and CKAN catalog harvester gather/consume processes don't duplicate the work/data.

## Remediation
- [x] For Dashboad, we can make sure to enable the cron jobs only on the main harvester
- [x] For CKAN Catalog, both the harvesters can be configured in such a way that it doesn't duplicate the gather function, but consume process can be split and run on both harvesters. 
- [x] Also for catalog, all other back end QA cron, topics csv snapshot etc can be configured on the second harvester

**Comment by dano-reisys** [comment]
I believe we can achieve this using:

http://docs.ansible.com/ansible/playbooks_delegation.html#id12

@JJediny @neilhunt1   what do you think?

**Comment by neilhunt1** [comment]
Yep, that looks like a simple ansible-powered option similar to EC2 Run Commands or Rundeck.
