### ISSUE TITLE
Add arg parsing to datagov harvesting logic

### ISSUE THREAD

**Issue by rshewitt** [GSA/data.gov#4710]
## User Story

In order to use harvest.py as a command line utility in cloud foundry ( via cf run-task), datagov wants to add command line argument parsing to datagov harvesting logic

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN datagov harvesting logic \
  WHEN the arg parsing function is called \
  THEN the passed arguments will be in a structured format easy to use by harvest.py

## Background

we intend to use harvest.py as our runner code. the runner should accept a job_id. in order to do that we need to add an argument parsing library. 

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
- implement [argparse](https://docs.python.org/3/library/argparse.html)
- create function for parsing incoming arguments
- create test verifying arg parsing function works as intended.
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by rshewitt** [comment]
harvest.py doesn't implement the arg parsing function. that'll happen in [#4715](https://github.com/GSA/data.gov/issues/4715). i reworded this ticket.

**Comment by btylerburton** [comment]
resolved with #4715
