### ISSUE TITLE
Apply deduplication script for duplicate datasets on production

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#472]
https://docs.google.com/document/d/1AUCO8VoXY8caoY2WJx1jTH_jJYzq0DStemBb9FgKe3I/edit#heading=h.48ayyncqtc2v

This is the current plan. Run the steps in order.
- [x] Run the dedupe script in dry-mode on staging
- [x] Run the dedupe script in write-mode on staging, save the logs
- [x] Run dedupe script in dry-mode on production
- [x] Calculate rough estimate on how long the script will take to run on all agencies
- [x] Run dedupe script in write-mode on small agency with duplicates
- [x] Run dedupe script on all agencies
- [x] Publish/archive logs for production runs

To run the dedupe script against admin, we need to temporarily upgrade repoze.who (and disable saml2). The easiest way to do this is to run the ckan-native-login playbook.
1. `ansible-playbook ckan-native-login.yml -i inventories/production --limit 'catalogpub-web1p.prod-ocsit.bsp.gsa.gov'`
1. Run dedupe script `nohup python duplicates-identifier-api.py --verbose --commit ssa-gov >> dedupe.log &`
1. Run the catalog.yml playbook to revert `ansible-playbook -i inventories/production catalog.yml --tags="frontend,ami-fix,bsp" --skip-tags="solr,db,cron" --limit 'catalogpub-web1p.prod-ocsit.bsp.gsa.gov'`

**Comment by JJediny** [comment]
Update:

Consildating documentation and current bugs

**Comment by adborden** [comment]
We refactored the script and are testing it in test and staging environments.

**Comment by adborden** [comment]
There's about 59K duplicate records to be deleted. Ballpark estimate is 13 hours to run through all of them.
