### ISSUE TITLE
Performance lagging due to large css sourcemap

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4722]
Lighthouse shows data.gov with a performance score of 62. The 10X team also uses 11ty for their site, and found that adjusting the CSS made for an improved performance.

## How to reproduce

1. Load data.gov
2. Open Chrome dev tools
3. Click Lighthouse tab
4. Run Lighthouse report

## Expected behavior

Faster load time of the page

## Actual behavior

A slow load time of the page

## Sketch

From the 10X person who messaged me:

Ok here are the changes for your group to try out:
1. package.json
change the `assets:autoprefix` line to:
`"assets:autoprefix": "postcss _site/assets/styles/*.css -r",`

2. and postcss.config.js
```
module.exports = {
  plugins: [require('autoprefixer')({
    map: process.env.ELEVENTY_ENV !== 'production'
  })],
};
```
3. in the `config/buildAssets.js`
this seemed to help our build too, adding this line to the esbuild.build array
```
minifyWhitespace: true, 
```

**Comment by btylerburton** [comment]
Note: this work has been partially completed in https://github.com/GSA/datagov-11ty/pull/276

**Comment by btylerburton** [comment]
![Image](https://github.com/user-attachments/assets/75d7d231-1e7f-470d-b56d-a8a186fb1291)
Current snapshot as of 10/9/24

**Comment by tdlowden** [comment]
@btylerburton should we close this ticket?

**Comment by btylerburton** [comment]
I think we can close this one, and I can make a new ticket to run lighthouse evals on all our sites though, because it's nice to get a baseline.
