### ISSUE TITLE
Link preview image not displaying correct page title

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4723]
![Image](https://github.com/GSA/data.gov/assets/6556888/4186e241-2992-496c-ac53-9e8f4e50e66a)

![Image](https://github.com/GSA/data.gov/assets/6556888/075363e5-dff8-477c-b155-a2923a4e83ad)

When linking to a catalog page, the link preview image contains `Data.gov Home, data.gov`. I believe it should  show the page title of the page being linked.

## How to reproduce

1. Link to a catalog page in slack, x, facebook, etc
2. View the link preview

## Expected behavior

The link preview should cite the page Title of the page linked

![Image](https://github.com/GSA/data.gov/assets/6556888/2aafed32-c83a-4944-8d42-cfcbb2c2b5a9)

## Actual behavior

The link preview displays "Data.gov Home" as the page title

## Sketch

Fix the `og:title` to be the current page title

**Comment by robert-bryson** [comment]
Initial attempt at https://github.com/GSA/ckanext-datagovtheme/pull/212, but the embedded logic isn't quite working correctly so still working on the fix.

**Comment by robert-bryson** [comment]
This is working correctly. Perhaps when updating previously CloudFront had been hitting the cache or something. 

![Image](https://github.com/user-attachments/assets/e960c9b2-f0d0-43f3-9d1e-fdef0399e86e)

Also, when discussing with @tdlowden, we noticed that the 11ty site did not have an image in the link preview. This should be added with [this PR](https://github.com/GSA/datagov-11ty/pull/328).

**Comment by robert-bryson** [comment]
With https://github.com/GSA/catalog.data.gov/pull/1452 this is deployed and working in prod. 

![Image](https://github.com/user-attachments/assets/7f01d0bb-8109-4547-84b3-3bdb59f3abcb)

The additional fixup (beyond this ticket's scope, but related) for the 11ty site [is still in progress](https://github.com/GSA/datagov-11ty/pull/328). 

Closing this ticket.

**Comment by Bagesary** [comment]
bags to follow up with Robert
