### ISSUE TITLE
Org logos broken in catalog

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4724]
images not loading on org page or dataset pages

![Image](https://github.com/GSA/data.gov/assets/6556888/7779eda7-eb1f-48f8-88e8-8580766600a7)

Following orgs are affected:

- https://catalog.data.gov/organization/city-and-county-of-durham-north-carolina
- https://catalog.data.gov/organization/city-of-chesapeake
- https://catalog.data.gov/organization/city-of-san-francisco
- https://catalog.data.gov/organization/city-of-santa-rosa
- https://catalog.data.gov/organization/city-of-sioux-falls
- https://catalog.data.gov/organization/city-of-tempe
- https://catalog.data.gov/organization/cdatribe-nsn-gov
- https://catalog.data.gov/organization/usda-gov
- https://catalog.data.gov/organization/doi-gov
- https://catalog.data.gov/organization/eac-gov
- https://catalog.data.gov/organization/fema-gov
- https://catalog.data.gov/organization/fhfa-gov
- https://catalog.data.gov/organization/federal-laboratory-consortium
- https://catalog.data.gov/organization/federal-retirement-thrift-investment-board
- https://catalog.data.gov/organization/florida-department-of-environmental-protection
- https://catalog.data.gov/organization/neh-gov
- https://catalog.data.gov/organization/ssa-gov
- https://catalog.data.gov/organization/u-washington-edu
- https://catalog.data.gov/organization/vcgi-org

a few of these have 0 datasets, and #4740 will remove them

## How to reproduce

1. Visit https://catalog.data.gov/organization/usda-gov or https://catalog.data.gov/organization/doi-gov

## Expected behavior

logo displays

## Actual behavior

image breaks

## Sketch

log into catalog and switch the logo source

- [x] - https://catalog.data.gov/organization/city-and-county-of-durham-north-carolina
- [x] - https://catalog.data.gov/organization/city-of-chesapeake
- [x] - https://catalog.data.gov/organization/city-of-san-francisco
- [x] - https://catalog.data.gov/organization/city-of-santa-rosa
- [x] - https://catalog.data.gov/organization/city-of-sioux-falls
- [x] - https://catalog.data.gov/organization/city-of-tempe
- [x] - https://catalog.data.gov/organization/cdatribe-nsn-gov
- [x] - https://catalog.data.gov/organization/usda-gov
- [x] - https://catalog.data.gov/organization/doi-gov
- [x] - https://catalog.data.gov/organization/eac-gov
- [x] - https://catalog.data.gov/organization/fema-gov
- [x] - https://catalog.data.gov/organization/fhfa-gov
- [x] - https://catalog.data.gov/organization/federal-laboratory-consortium
- [x] - https://catalog.data.gov/organization/federal-retirement-thrift-investment-board
- [x] - https://catalog.data.gov/organization/florida-department-of-environmental-protection
- [x] - https://catalog.data.gov/organization/neh-gov
- [x] - https://catalog.data.gov/organization/ssa-gov
- [x] - https://catalog.data.gov/organization/u-washington-edu
- [x] - https://catalog.data.gov/organization/vcgi-org

**Comment by btylerburton** [comment]
USDA - https://www.usda.gov/style-guide/logo
DOI - https://www.usgs.gov/media/images/doi-logo

**Comment by tdlowden** [comment]
logos listed updated
