### ISSUE TITLE
Create catalog-next

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4734]
## User Story

In order to have a stable catalog-next to test against, data.gov admins wants a protected branch and infrastructure for another catalog to be deployed.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN the `next` branch is created and protected \
  [AND optionally another precondition] \
  WHEN a user goes to [catalog-next](https://catalog-next.data.gov) \
  THEN the CKAN site is up \
  AND the harvest extension (and others) are not installed.

## Background

Related to Harvesting2.0

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

We want to utilize current models where we can. Suggest implement a `next` branch, and a similar branch for `ckanext-datagovteam` such that the `next` branch in catalog is protected, requires reviews for merge, etc. We also want to deploy on `next` branch merges, and figure out how to separate that from `main`.
In this iteration we only need to do development for dev; stage and prod can be considered follow-up tickets (please create follow up tickets if not implemented).

**Comment by jbrown-xentity** [comment]
Deployment is done in dev, want to setup a github action for auto-deploying from `catalog-next` branch, and do branch protections (maybe future).

**Comment by FuhuXia** [comment]
[catalog-next branch](https://github.com/GSA/catalog.data.gov/commits/catalog-next/) is created. Latest commit is 868b6b2d6ba83efa319dceadc5ed9f040ab66ce6. 

deployed to 
https://catalog-next-dev-datagov.app.cloud.gov/dataset/

Changes done:
- removed harvest related components
- used harvest_next versions of ckanext-datagovtheme and ckanext_datagovcatalog
- added harvest_next related vars to ckan.ini
- added GitHub workflow to deploy three catalog-next apps on development space upon changes on catalog-next branch
  - catalog-next-web
  - catalog-next-admin
  - catalog-next-proxy
- created api token upon user login in cypress so that ckan api call can be made
- kept cypress test minimal

TODO:
add back cypress tests for more complicated tests.

**Comment by Bagesary** [comment]
Discussion needed with Reid and Tyler to remove the blocker i.e. get the sample data

**Comment by FuhuXia** [comment]
Created [a dataset](https://catalog-next-dev-datagov.app.cloud.gov/dataset/test-dataset) on development:catalog-next by calling package_create api with [this payload](https://github.com/GSA/catalog.data.gov/blob/868b6b2d6ba83efa319dceadc5ed9f040ab66ce6/e2e/cypress/fixtures/ckan_dataset.json), dataset is created in db but could not find it in the solr. It is fine in local environment. 

Need to troubleshoot.

**Comment by FuhuXia** [comment]
Hooked my local to the catalog-next's solr. Dataset was created and indexed fine. But catalog-next still shows 0 dataset, even they are connected to the same solr, or not?

Need to figure out what solr catalog-next is connecting to.

**Comment by Bagesary** [comment]
Will continue to push the data set.

**Comment by FuhuXia** [comment]
Things are fine after [a typo fix](https://github.com/GSA/catalog.data.gov/commit/f9e6be362d446cba9a6bb5aaee56d767a3fc926e). The admin was connected to the solr replica because of the typo and caused all kinds of weird behaviors.

 Test dataset was pushed. All looks fine.
