### ISSUE TITLE
Create graphic for marking Data.gov 15th anniversary

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4737]
## User Story

In order to accompany any potential home page changes/blog post to mark Data.gov anniversary, the team would like an image to mark that it is the 15th anniversary.

## Acceptance Criteria

- [ ] GIVEN plans to mark Data.gov's 15th anniversary
  THEN Data.gov has an image to use in any updates to home page or a blog post.

## Sketch

- [ ] Review work done last year for home page updates
- [ ] Design options for 15th anniversary
- [ ] Team selects option

**Comment by hkdctol** [comment]
@CarolinaC-REI our anniversary is 5/21, we'd like to mark it in some way, not sure what yet, but could we get a graphic? Last year for home page re-design you had the one that marked "14"?

**Comment by CarolinaC-REI** [comment]
Good morning @hkdctol,
Quick questions about this request:
- Do you want to repurpose the same anniversary graphic you had before just changing 14 to 15, or are you open to options? 
- The location were the graphic will be added will dictate the size and style of the graphic. Would you like some options on possible locations where to add the anniversary graphic?
- Are you planning to have the anniversary graphic be displayed a short period of type or until next year?

**Comment by hkdctol** [comment]
Open to options, not sure about location, I would like options, and probably not all year--limited amount of time

**Comment by CarolinaC-REI** [comment]
Sounds good, thank you. I will start working on it shortly. I should have options to review by Friday.

**Comment by CarolinaC-REI** [comment]
Good afternoon, the graphics took a little longer than expected. I will be providing the options by early next week.

**Comment by CarolinaC-REI** [comment]
@hkdctol Please find below the link for the mockup layout and graphic options for your review. You should be able to see 4 options, please let me know if you are having any issues with the link. Please let me know if you have any questions. Thank you
https://www.figma.com/proto/E56AIJwAnOy4TDRQEkj9Wt/Data.gov-15th-anniversary?type=design&node-id=20-258&t=gZA0YGCr8fxX8ujz-1&scaling=min-zoom&page-id=0%3A1

**Comment by CarolinaC-REI** [comment]
@tdlowden Please find the information and assets needed for the 15th anniversary sections.
**Font used for the bonus banner:** Segoe UI Regular, Segoe UI Bold
**Updates Figma File Page 2**: https://www.figma.com/design/E56AIJwAnOy4TDRQEkj9Wt/Data.gov-15th-anniversary?node-id=70%3A1006&t=BE5TuRsja4S2Sfs4-1

**On the Zip attached I have two banner sizes and the image graphic in case you would like to re-create using CSS:**
[15anniversary.zip](https://github.com/GSA/data.gov/files/15340221/15anniversary.zip)

Please let me know if you have any questions. Thank you

**Comment by hkdctol** [comment]
@btylerburton see above

**Comment by btylerburton** [comment]
Thanks @hkdctol I'll turn that around on Monday.

**Comment by btylerburton** [comment]
Merged
