### ISSUE TITLE
MAY 21 - Post 15th anniversary image and content on data.gov homepage

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4742]
## User Story

In order to create awareness for 15th anniversary, datagov team wants to add an acknowledgement on homepage.

## Acceptance Criteria

- [ ] GIVEN May 21st is data.gov's 15 year anniversary
  WHEN May 21st happens
  THEN a visual and textual acknowledgment will be posted in a prominent spot on the homepage

## Background

Could do something similar to:

![Image](https://github.com/GSA/data.gov/assets/6556888/7a6b0ef2-32c1-45e2-926b-ea9e91b3cb73)

Incorporate the image from #4737 and the text:

**Data.gov at 15**

On May 21, 2009, Data.gov launched with a total of 47 datasets. After the landmark [2013 Open Data Policy](https://digital.gov/resources/open-data-policy-m-13-13/) required agencies to create comprehensive data inventories and public data listings, the site grew to 115,000+ datasets from 88 organizations by 2015. Today, Data.gov is nearing 300,000 datasets and dataset collections in the catalog, harvested from over 100 organizations, and counts over a million monthly pageviews from people like you, looking to discover that information. In 2024, Data.gov continues its commitment to open government data and transparency. Thank you for 15 years!

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

none

## Sketch

- [ ] Add a banner or visual element that incorporates the image from #4737 and the above text
- [ ] Publish on May 21

**Comment by hkdctol** [comment]
@CarolinaC-REI we like the banner, but can you create an image for 15 like you did in https://web.archive.org/web/20240104221145/https://data.gov/
what we're thinking is have the banner, but also an image for 15, and then have text next to it--the paragraph that's at the top of this doc: https://docs.google.com/document/d/1Nbr8iwceulP38QREFZcHajVOOTps7QF4VsVHhu_5RcQ/edit?usp=sharing

**Comment by tdlowden** [comment]
Dropping here in case no access:

**Data.gov at 15**

On May 21, 2009, Data.gov launched with a total of 47 datasets. After the landmark [2013 Open Data Policy](https://digital.gov/resources/open-data-policy-m-13-13/) required agencies to create comprehensive data inventories and public data listings, the site grew to 115,000+ datasets from 88 organizations by 2015. Today, Data.gov is nearing 300,000 datasets and dataset collections in the catalog, harvested from over 100 organizations, and counts over a million monthly pageviews from people like you, looking to discover that information. In 2024, Data.gov continues its commitment to open government data and transparency. Thank you for 15 years!

**Comment by CarolinaC-REI** [comment]
Hi everyone,

Please find the new graphic with the text on the mockup link below for your
review.

I was not sure if the banner you were mentioning was the blue or white so I
added an option for both of them.

https://www.figma.com/proto/E56AIJwAnOy4TDRQEkj9Wt/Data.gov-15th-anniversary?node-id=70-1009&t=fifukLLjK31pVJTD-1&scaling=min-zoom&page-id=70%3A1006

Please let me know if you have any updates.

@Timothy Lowden - Q2AACC ***@***.***>  Thank you for dropping
the content. I was able to access the document but if not that would be
very helpful.

Best,

Carolina Cacioli

**Comment by hkdctol** [comment]
Looks really good--maybe we can all look at sync tomorrow and decide

**Comment by hkdctol** [comment]
@CarolinaC-REI @btylerburton @tdlowden making a small change to mention the statute--replacement text below:

Data.gov at 15

On May 21, 2009, Data.gov launched with a total of 47 datasets. After the landmark [2013 Open Data Policy](https://digital.gov/resources/open-data-policy-m-13-13/) required agencies to create comprehensive data inventories and public data listings, the site grew to 115,000+ datasets from 88 organizations by 2015. These requirements were enacted into the [Open Government Data Act](https://www.congress.gov/115/plaws/publ435/PLAW-115publ435.pdf) in 2019. Today, Data.gov is nearing 300,000 datasets and dataset collections in the catalog, harvested from over 100 organizations, and counts over a million monthly pageviews from people like you, looking to discover that information. In 2024, Data.gov continues its commitment to open government data and transparency. Thank you for 15 years!

**Comment by btylerburton** [comment]
Merged
