### ISSUE TITLE
GA not recording `org` and `publisher` correctly

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4743]
After implementing CSS Selectors to collect `organization` and `publisher` (when present), GA is showing that the implementation worked, but it is recording those variables for some pageviews and not all.

![Image](https://github.com/GSA/data.gov/assets/6556888/325b9acf-472b-4e4b-ad08-ab4d56406546)

## How to reproduce

1. Log into datagovGA4
2. Create a report to show datagov_dataset_organization
3. Filter by a specific dataset URL
4. witness the variance in organization and (not set)

## Expected behavior

100% of dataset pageviews will attribute a `datagov_dataset_organization` and a `datagov_dataset_publisher`. Each dataset page will contain one value per variable, and not a value and also (not set) for some pageviews.

## Actual behavior

~60% of pageviews record an `org` and `publisher`, and ~40% record `(not set)`

## Sketch

- [ ] Research activity to determine issue or if it is related to bots
- [ ] Make necessary changes
- [ ] Validate changes work in GA

**Comment by tdlowden** [comment]
New goal: Have the `organization` and `publisher` drawn from CKAN directly to populate a dataLayer array upon pageload, like usa.gov does:


![Image](https://github.com/GSA/data.gov/assets/6556888/a50afa34-b7b7-42f1-8571-30bdaa35a14d)


This would apply on all pages related to a dataset, for example:

- https://catalog.data.gov/dataset/electric-vehicle-population-data
- https://catalog.data.gov/dataset/electric-vehicle-population-data/resource/8abbca4e-2f1c-4249-989f-b96201dd4710
- https://catalog.data.gov/dataset/electric-vehicle-population-data/resource/cb5a9adb-b9f1-44f5-aa3f-7f3c768da5d3

Should all have the same array with `organization` set to `State of Washington` and `publisher` set to `data.wa.gov`

This tutorial should help: https://www.analyticsmania.com/post/ultimate-google-tag-manager-data-layer-tutorial/

From there, I can use GTM dataLayer variables to collect the data and send on pageviews and file downloads to GA, to associate those events with the org.

**Comment by tdlowden** [comment]
@robert-bryson any updates here?

**Comment by gujral-rei** [comment]
@robert-bryson , please update the ticket.

**Comment by robert-bryson** [comment]
The current approach (JS Google Tag Manger script) is the recommended by Tag Manager but not working for us, obviously. There is a way to generate it via an official server-side tagging option. The docs describe a very different scenario than what is presented above so I am working on achieving the above with the official functionality if possible.

**Comment by robert-bryson** [comment]
Draft PR at https://github.com/GSA/ckanext-datagovtheme/pull/204.

**Comment by tdlowden** [comment]
FYI:

https://github.com/GSA/data.gov/issues/4783#issuecomment-2214240705


Thanks to @jbrown-xentity for a quick fix PR

**Comment by tdlowden** [comment]
@robert-bryson added 
```
window.dataLayer = window.dataLayer \|\| [];
--
  |  
  | dataLayer.push({

```
 which resolved the GTM issue. Moving to blocked until pentesting is done so we can push to prod

**Comment by tdlowden** [comment]
Pushed to prod. Subject to data populating, will QA Wednesday

**Comment by tdlowden** [comment]
as of 7/17, we now have 98% accuracy. Not perfect, but well within a margin of error for bots that I feel comfortable with making the data public 

![Image](https://github.com/user-attachments/assets/6d99559d-b4f4-4f5e-bca6-4d37b2656b1e)
