### ISSUE TITLE
Update DB After Validate

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4747]
## User Story

In order to keep an accurate count of the state of our datasets, datagovteam wants to update the Harvesting database with the results of the Validate operation.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a record needs to validated to conform to DCAT-US spec
AND that operation is successful
THEN that dataset should be passed along to the sync operation

- [ ] GIVEN a record needs to validated 
AND that operation is unsuccessful
THEN we should log that failure
AND we should create a new error in the harvest_error table
AND that dataset should be added to a list to be marked as "status: error" in the harvest_records db

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [x] Loop over records to be deleted
- [x] Create an error if necessary at runtime
- [x] Log the result of the validate operation

**Comment by rshewitt** [comment]
we have a FK reference on a nullable field in [harvest errors](https://github.com/GSA/datagov-harvesting-logic/blob/4df8981cfdb7095a8fc17224f5d311a26eb5dac4/database/models.py#L78C5-L78C81). the FK reference field ( harvest_record.id) is a primary key which can't be null.

**Comment by btylerburton** [comment]
Blocked pending conversation about db config
