### ISSUE TITLE
Catalog-next updates for datagovtheme

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4749]
## User Story

In order to have an integrated CKAN for the new harvester2.0, data.gov admins want a fixed version of datagovtheme.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a collection record is harvested via harvester2.0 \
  WHEN I view the dataset page \
  THEN a link exists to search for all items within the collection \
  AND each collection item has a link back to the parent

- [x] GIVEN a dataset is in catalog-next via harvester2.0 \
   WHEN I view the dataset page \
   THEN a link exists to the full original metadata in the harvester2.0 API \
   AND the link resolves as expected with harvester2.0 API

## Background

Related to catalog-next work, and final implementation of Harvester2.0

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

This may also involve integrating/completing the work @FuhuXia already did to remove the harvest extension from datagovtheme.

Should be straightforward fix of various templates.

To fix the collection, you'll want to redirect to a simple search, something like `parent_id = "parent_uuid"` as defined by the metadata.
The collection item pointing back to the parent will require a little client side api call, checking what the URL is for the parent and then linking to that URL.

This may also require patches to the harvester2.0 work; it should be setup such that all parents are marked as such (as that doesn't need to be defined in the metadata); but that code may need to be written. Should result in a metadata field called `is_parent`, and that should be true.

**Comment by FuhuXia** [comment]
PR https://github.com/GSA/ckanext-datagovtheme/pull/205 removed `ckanext-harvest` dependency.

TODO:
- discuss parent-children relationship for datasets added via harvester2.0
- URL for harvest_object and harvest_source links to harvester2.0 UI.

**Comment by FuhuXia** [comment]
Metadata link part of task is fnished in https://github.com/GSA/ckanext-datagovtheme/pull/213.
Collection part of task is divided into two stories: https://github.com/GSA/data.gov/issues/4969 and https://github.com/GSA/data.gov/issues/4970.

Close this one.
