### ISSUE TITLE
Require signed commits for main branch in all repos

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4768]
## User Story

In order to ensure compliance with GSA-wide security initiatives, datagovteam wants to require developers to ensure their commits to github are signed.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I have a repo in GSA org
  WHEN I configure the branch rules
  THEN I will require signed commits to the main branch

- [ ] GIVEN I am a developer on data.gov
WHEN I want to add code to a branch on a github repository
THEN I will have my github profile configured to support signed commits
  
## Background

Related to: 
- https://github.com/GSA/resources.data.gov/issues/662

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [x] Require signed commits to `main` branch of all repos below:
  - [x] https://github.com/GSA/data.gov
  - [x] https://github.com/GSA/resources.data.gov
  - [x] https://github.com/GSA/catalog.data.gov
  - [x] https://github.com/GSA/ckanext-datagovtheme
  - [x] https://github.com/GSA/ckanext-datajson
  - [x] https://github.com/GSA/ckanext-metrics_dashboard
  - [x] https://github.com/GSA/datagov-11ty
  - [x] https://github.com/GSA/ckanext-geodatagov
  - [x] https://github.com/GSA/datagov-ssb
  - [x] https://github.com/GSA/inventory-app
  - [x] https://github.com/GSA/datagov-logstack
  - [x] https://github.com/GSA/data-strategy
- [ ] Configure signed commits for self
- [ ] Document process for setting up signed commits
- [ ] Ensure all developers are aware of requirement for signed commits and how to configure them

**Comment by gujral-rei** [comment]
need help/info from authorized individual (admin access)
update the onboarding documentation
individual team members need to action

**Comment by btylerburton** [comment]
FYI I left the GSA-TTS repos off the list.

**Comment by btylerburton** [comment]
Some recent bookmarks from GSA Slack regarding signed commits:
- https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1701888584663899
- https://gsa-tts.slack.com/archives/C03EMDS6P/p1710444339851359

**Comment by Jin-Sun-tts** [comment]
sign with SSH key:
https://calebhearth.com/sign-git-with-ssh

**Comment by btylerburton** [comment]
Hi @Jin-Sun-tts thanks for those instructions. They were super straightforward! Let me know when I can test pushing to a repo that forces signed commits.

**Comment by Jin-Sun-tts** [comment]
The `main` branches of our repositories are protected, and merges are performed through pull requests on the GitHub web interface, which already ensures that all commits are `verified`. 

To enforce signed commits from the command line, I have enabled the Require signed commits setting on the main branches for all our repositories.


The setup instructions below will ensure that any commits made from the command line are signed and verified.


**Add an SSH Key in GitHub Settings:** 

If you don’t have an SSH key yet, generate one and add your public SSH key to GitHub by going to `Settings > SSH and GPG keys > New SSH key.`  (note: You may need to add the same key as a Signing Key initially. However, you can remove it later if needed.)

**Configure Git to Use SSH for Commit Signing:**

- Set your SSH key as the signing key:
`git config --global user.signingkey ~/.ssh/id_ed25519`

- Specify SSH as the format for signing:
`git config --global gpg.format ssh`

- Enable automatic signing for all commits:
`git config --global commit.gpgSign true`

**(Optional) Verify SSH-Signed Commits Locally:**

- Create a file to store trusted public keys:
`touch ~/.ssh/allowed_signers`
- Add your SSH public key to this file in the format:
`git_username ssh-ed25519 AAAAC3NzaC1lZDI1NTE5...`
Replace git_username with your GitHub username and add your SSH public key after that.

- Set secure permissions on the file:
`chmod 600 ~/.ssh/allowed_signers`

- Tell Git to use this file for SSH signature verification:
`git config --global gpg.ssh.allowedSignersFile ~/.ssh/allowed_signers`

- Verify the Commit Signature:
Check the latest commit’s signature with:
`git log --show-signature -1`

**Comment by btylerburton** [comment]
We only need to configure this once, right? Or is there something we need to do for each repo?

**Comment by btylerburton** [comment]
I was confused by the fact that SSH keys can be used for authentication and for signing and if using for both they need to be uploaded twice... 

https://1password.community/discussion/135873/git-commit-signing-with-ssh-key-unverified-persists

**Comment by Jin-Sun-tts** [comment]
> We only need to configure this once, right? Or is there something we need to do for each repo?

We only need to setup this once in your own git account.  

For each repo, I already enabled the Require signed commits setting.

**Comment by Jin-Sun-tts** [comment]
> I was confused by the fact that SSH keys can be used for authentication and for signing and if using for both they need to be uploaded twice...

Currently, I only have an `Authentication Key` set up, and it works fine for me. I do recall adding a `Signing Key` when I first started testing, but I later removed it and kept only the `Authentication Key`. Everything continues to function as expected.

**Comment by btylerburton** [comment]
I had only an Authentication key setup and it wouldn't work until I uploaded the same key for signing. Maybe once it's set, you can remove it, which feels like a bug, but regardless I'm good now.
