### ISSUE TITLE
standardize flask routes

### ISSUE THREAD

**Issue by rshewitt** [GSA/data.gov#4769]
## User Story

In order to provide a meaningful and consistent route design, datagov wants to standardize the flask app routes

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN the current routes managed by the flask app \
  WHEN standardization occurs \
  THEN the routes will follow a common pattern and contain no redundancy

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by btylerburton** [comment]
we have #4815 which covers this same issue in more detail
