### ISSUE TITLE
Consolidate ansible secrets

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#477]
This issue is a discussion, not a task description.

Here are some issues I'd like to address with our secrets
- a few secrets were not generated with a random password generator
- all inventory vaults share the same encryption key
- the vault files are scattered across directories, making it difficult to audit

- [ ] Update the [wiki](https://github.com/GSA/datagov-deploy/wiki/Best-Practices#secure-vs-insecure-data).

**Comment by adborden** [comment]
Here's a proposed solution:

- Move the vault files to a single vault per inventory, under `group_vars/all/vault.yml`
- Create a different encryption key per inventory
- Audit the secrets

I believe this address the issues above. Here are some cons with this approach:

- Increased complexity for developers to manage the encryption keys per inventory. Maybe we instead of one key per inventory, we have one key for prod, one for stage, and one key for the others.
- There may be a few exceptions when the vault variable needs to be overridden per group or host and would want to put a vault file in those subdirs. An alternative would be to create multiple vault variables and reference them in the group/host var files e.g. `vault_secret_host1` and `vault_secret_host2` both in `all/vault.yml` but reference them appropriately in the subdirs.

**Comment by adborden** [comment]
@JJediny @philipashlock these are things currently in vaults which IMHO don't need to be in the vault. They aren't really secrets. Are you okay moving them into the inventory variables? It makes it easier to grep and find things. The vault generally hides things, which is good for real secrets, but less good for general configuration.

- host names
- user names
- database names
- email addresses (e.g. for alerts)
- public keys (e.g. certs and ssh)

**Comment by adborden** [comment]
This wiki should be updated https://github.com/GSA/datagov-deploy/wiki/Best-Practices#secure-vs-insecure-data.

**Comment by nickumia-reisys** [comment]
Ansible no longer being used.
- https://github.com/GSA/data.gov/issues/3710
