### ISSUE TITLE
Harvest 2.0 Original Metadata API route

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4773]
## User Story

In order to have the originally harvested metadata, geospatial metadata users want an API that allows to get the original harvested metadata.

## Acceptance Criteria

- [ ] GIVEN the harvester2.0 API is available and the route `/harvest_record/raw/{id}` is created \
  WHEN a legitimate ID is used to hit the API at `/harvest_record/raw/{id}` \
  THEN the original metadata is returned with correct formatting (ie xml, json, etc with correct content type)

## Background

Related to https://github.com/GSA/data.gov/issues/4749, this ticket is required before #4749 can be taken on.
Should consider updating the [Flask Routes documentation](https://docs.google.com/document/d/1XzfTrPxu-asJ_55GoeZ2UOJsie9CuCegStS28BAL_40/edit#heading=h.njcvzj6q25gg)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

Simply do the lookup in the DB for the information and return it. 404 if the resource is not in the DB.
Make sure to setup the content type correctly for the different metadata standard, whether SML or JSON.

**Comment by btylerburton** [comment]
Resolved by https://github.com/GSA/datagov-harvester/pull/103

**Comment by rshewitt** [comment]
> Resolved by [GSA/datagov-harvester#103](https://github.com/GSA/datagov-harvester/pull/103)

closing because?...
