### ISSUE TITLE
Resolve resources.data.gov gulp dependency issues

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4778]
## User Story

In order to ensure builds are able to be promoted to production, datagovteam wants to resolve issues with our gulp tasks that prevent upgrading to v5.

Related: 
- https://github.com/GSA/data.gov/issues/4756
- https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/#introducing-uswds-compile-2

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I have upgraded Gulp to V5 and integrated uswds-compile
  WHEN I run a build
  THEN the site builds successfully and there are no errors

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Upgrade from uswds-gulp to [uswds-compile](https://github.com/uswds/uswds-compile#readme)
- [ ] Modify gulpfile to follow new standard
- [ ] Confirm build passing

**Comment by FuhuXia** [comment]
As of now, `npm install` gives me errors.
```
🐧 Tue 12:57:10 [~/git/datagov/resources.data.gov (main =)]
$ node -v
v20.14.0
🐧 Tue 12:57:13 [~/git/datagov/resources.data.gov (main =)]
$ npm install

up to date, audited 918 packages in 6s

90 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (8 moderate, 11 high)
```

**Comment by rshewitt** [comment]
uswds-compile reverted back to [4.0.2](https://github.com/uswds/uswds-compile/commit/74ddb4ca8ce5fec113a152265d31fb2450d33d65) recently
