### ISSUE TITLE
Clarify options for download json in inventory.data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4780]
## User Story

In order to update UI on inventory.data.gov for agency users, we should just have one button for downloading a data.json

## Acceptance Criteria

- [ ] GIVEN agency user logs in \
  THEN they should see just one button/option for downloading data.json

## Background

Based on different practices during early years of inventory.data.gov, we currently have two buttons for download data.json that say redacted inventory and unredacted inventory but there are no functional differences between the two and is confusing for users
<img width="677" alt="Screenshot 2024-06-04 at 5 39 49 PM" src="https://github.com/GSA/data.gov/assets/3236989/62f2b267-0141-4681-a763-640b7fc498ed">

## Sketch

- [ ] Delete one of the buttons for downloading inventory
- [ ] Rename one button as "download inventory" or something else if team has suggestions for the button

**Comment by rshewitt** [comment]
will bump datajson version in catalog and inventory following merge

**Comment by rshewitt** [comment]
@FuhuXia 

![Image](https://github.com/GSA/data.gov/assets/92057378/d199c3c5-3e88-4f03-aa99-0cba58830075)
