### ISSUE TITLE
DCAT-US Load Test in Cloud.gov

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4784]
## User Story

In order to properly assess progress and define bugs in the new harvester, datagovteam wants to load test some DCAT-US sources in Cloud.gov.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN I have configured an organization and a harvest source in the datagov-harvester-admin
AND I have created the same organization in the corresponding CKAN environment
  WHEN I trigger a harvest in the admin app
  THEN I expect on refresh of the application that the LoadManager would schedule a new harvest run

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [x] Confirm datagov-harvester-admin and datagov-harvester-runner are deployed to the latest version
- [x] Confirm a Test Organization and Harvest Source are configured in datagov-harvester-admin
- [x] Confirm the same Test Organization is configured at the corresponding CKAN instance
- [x] Confirm the datasets enumerated in the configured harvest source URL are not already posted to the corresponding CKAN instance
- [x] Trigger a new harvest in datagov-harvester-admin
- [x] Restart the datagov-harvester-admin application to kick off the load manager

**Comment by btylerburton** [comment]
Load test daily EOD:

- I need ckan `id` to delete a dataset. We aren't storing that. Should we store that on create/update just to make things easier?
- If a delete fails, we mark it as an error, but what we need to recreate current state of CKAN source is packages with `action: create/update, state: success` AND `action: delete, state: error`

**Comment by Bagesary** [comment]
Load testing is on hold.

**Comment by btylerburton** [comment]
Need to check CKAN_API_TOKEN to confirm it's present in user-provided-service

**Comment by btylerburton** [comment]
Observed:
- Triggered delete of org with NASA harvest source attached. 20k records + 3k errors.
- Browser unresponsive for 30+ seconds and then it returned to home screen.
- This was before we merged in CKAN API delete call
- Did not have dev tools open so didn't observe if that meant a long lived POST request

**Comment by btylerburton** [comment]
🎉 With modifications to control for unique URLs in place, we harvested NASA data source with no unexpected errors! 

https://datagov-harvest-admin-dev.app.cloud.gov/harvest_job/36f1bfd5-3f88-4fc7-8069-f26bbafc9764

![Image](https://github.com/user-attachments/assets/a0be7874-4078-4c59-9728-4878dd954176)

**Comment by btylerburton** [comment]
😢 even with 8GB of memory, the harvest-runner fails with an OOM when I try to reharvest the NASA source...

```
   2024-08-26T17:05:04.55-0500 [APP/TASK/harvest-job-649995a9-33d6-4161-8978-d4dc38b22ff5/0] OUT [2024-08-26 22:05:04,554] INFO [harvest_runner.get_record_changes:223] getting records changes for NASA source using https://data.nasa.gov/data.json
   2024-08-26T17:05:04.55-0500 [APP/TASK/harvest-job-649995a9-33d6-4161-8978-d4dc38b22ff5/0] OUT [2024-08-26 22:05:04,554] INFO [harvest_runner.prepare_internal_data:170] retrieving and preparing internal records.
   2024-08-26T17:05:05.46-0500 [APP/TASK/harvest-job-649995a9-33d6-4161-8978-d4dc38b22ff5/0] OUT [2024-08-26 22:05:05,460] INFO [harvest_runner.prepare_external_data:181] retrieving and preparing external records.
   2024-08-26T17:05:31.28-0500 [APP/TASK/harvest-job-649995a9-33d6-4161-8978-d4dc38b22ff5/0] OUT Exit status 137 (out of memory)
   2024-08-26T17:05:31.91-0500 [CELL/0] OUT Cell e49592cc-346d-4fd2-b553-bd659bffafef stopping instance 3d9df652-8d10-49c2-9abe-49cace1108bc
   2024-08-26T17:05:31.91-0500 [CELL/0] OUT Cell e49592cc-346d-4fd2-b553-bd659bffafef destroying container for instance 3d9df652-8d10-49c2-9abe-49cace1108bc
```

**Comment by jbrown-xentity** [comment]
Do we know if it's specifically in the compare section? If it makes it through the compare, maybe there is some deleting/freeing of memory we can do to make it more efficient...

**Comment by btylerburton** [comment]
```
  self.external_records_to_id_hash(
      download_file(self.url, ".json")["dataset"] <<<<<<<
  )
```

My guess is it's this line, and the 68MB NASA data.json is causing it to crash. 

I'm harvesting a smaller JSON source from DOJ right now and then will re-harvest that again. Then I plan to add some log statements to pinpoint that it's failing at the JSON extraction.

**Comment by btylerburton** [comment]
🎉 🌮 processing the external external records before we process internal records allows me to reharvest the NASA source...

**Comment by btylerburton** [comment]
😢 Test Harvesting DOI datajson fails with same OOM error....

Research reveals we can pass memory limit into task; leading me to believe there is a default mem limit (of 512k?) on every task.

https://cli.cloudfoundry.org/en-US/v6/run-task.html

😄 Testing `cf run-task` with a memory boost `-m 2G` allows DOI source to harvest successfully...

**Comment by jbrown-xentity** [comment]
In theory we could "right size" these jobs; ie track in the harvest source config something like a t-shirt size (S/M/L/XL), and use different memory allocations when starting up the task from the controller. But that's a later optimization...
