### ISSUE TITLE
Create Clear for Harvest2.0 Harvest source

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4787]
## User Story

In order to be able to reset/restart a harvest source, data.gov admins want a clear function/API route.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN the `/harvest/{id}/clear` API route is created \
  WHEN I call the harvest API at `/harvest/{id}/clear` \
  THEN the datasets are removed from CKAN \
  AND the dataset records/errors/jobs are removed from the harvest DB

## Background

Very helpful for testing, and occasionally useful for resetting a harvest source that has become corrupted or out of sync. Similar to CKAN clear functionality.  

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Should require authentication, but no security additions required.

## Sketch

Eventually the CKAN removal piece may become so cumbersome (ie take so long, longer than the restart time [15 minutes?]) that we'll want to implement that piece as a subtask. For this instance, just utilize the API normally.
Simply try to run a CKAN [dataset purge](https://docs.ckan.org/en/2.10/api/index.html#ckan.logic.action.delete.dataset_purge). Also run the DB delete/clear commands. Ideally if everything is synced correctly, you should be able to remove the harvest jobs and let everything flow to delete the other foreign objects, but might require config changes or workarounds.

**Comment by btylerburton** [comment]
moving back to H2.0 backlog as other tickets have taken precedence

**Comment by Jin-Sun-tts** [comment]
This ticket should only clear the` harvest_record `and `harvest_record_error` associated with the harvest_source_id, while retaining the harvest_job related to this harvest_source.

The harvest_source deletion will be addressed in https://github.com/GSA/data.gov/issues/4691

**Comment by Jin-Sun-tts** [comment]
Created the clear_harvest_source route and interface to streamline the cleanup of datasets in CKAN. 

Implemented with ckan remote API call bulk_update_delete.

To address time-out limitations from Cloud.gov and CKAN. Added multiple retry attempts to ensure the Solr cleanup completes successfully.

**Comment by Jin-Sun-tts** [comment]
Tested in the development environment:
Harvest speed: 2 seconds per dataset
Record clearing speed: 0.5 seconds per dataset

Additionally, a new ticket needs to be logged for implementing the ability to cancel a job while it is running.

**Comment by Jin-Sun-tts** [comment]
Added retry loop to handle time-out limitations from both cloud.gov and CKAN's Solr backend. By retrying the dataset deletion multiple times, it increases the likelihood that all datasets will eventually be cleared, even if some requests fail due to timeouts or incomplete operations.
