### ISSUE TITLE
Migrate content from federation.data.gov to https://resources.data.gov/resources/us-data-federation/

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4788]
## User Story

In order to reduce compliance and maintenance burden, datagov team wants to migrate content from federation.data.gov to resources.data.gov.

## Acceptance Criteria

- [ ] GIVEN there should be a record of work done by the US Data Federation
  AND the federation.data.gov site is not maintained
  WHEN a user would like to find information on the US Data Federation
  THEN the key content should be available on resources.data.gov

## Background

https://docs.google.com/document/d/1w17nvZ6M4XYFqjDEyao7bZwCUbuLmM7QaJotLWKLdsU/edit

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

none

## Sketch

- [ ] Create a page with the same template as https://resources.data.gov/resources/dcat-us/
- [ ]  left-hand navigation includes the following 4 labels, with the content to be transferred from the link in parentheses (all content to be reviewed & updated to reflect that the effort has now ended):

- Overview (https://federation.data.gov/) 
-About (https://federation.data.gov/about/)
-Framework (https://federation.data.gov/us-data-federation-framework/) 
ReVal tool (https://federation.data.gov/tools/)
-Also link to success story: https://18f.gsa.gov/2020/04/23/saving-time-and-improving-data-quality-for-the-national-school-lunch-breakfast-program/

**Comment by robert-bryson** [comment]
[PR](https://github.com/GSA/resources.data.gov/pull/724) and [draft page](https://cg-f5a56614-c88e-470c-9f06-ff5fe2d4c98a.sites.pages.cloud.gov/preview/gsa/resources.data.gov/feature/4788-migrate-federation/resources/us-data-federation/), @tdlowden
