### ISSUE TITLE
Redirect all url endpoints of federation.data.gov to resources.data.gov/resources/us-data-federation/

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4789]
## User Story

In order to prevent historical links from 404ing, datagov team wants to implement a redirect on all federation.data.gov pages

## Acceptance Criteria

- [ ] GIVEN the resources.data.gov/resources/us-data-federation page is created
  AND content has been migrated
  WHEN a visitor land on any federation.data.gov URL
  THEN the user should be redirected to the page on resources.data.gov

## Background

https://docs.google.com/document/d/1w17nvZ6M4XYFqjDEyao7bZwCUbuLmM7QaJotLWKLdsU/edit

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

Just need to make sure the redirect maintains HTTPS

## Sketch

- [ ] Redirect [the DNS](https://github.com/18F/dns/blob/main/terraform/data.gov.tf#L302-L308) to point to the [redirects app](https://github.com/GSA/datagov-website/blob/main/redirects/nginx.conf), and then redirect to the resources.data.gov new page with content.

**Comment by gujral-rei** [comment]
- need nginx update as well

**Comment by Bagesary** [comment]
New ticket needs to be created as per discussion with Tyler. Bags to followup with Robert.

**Comment by jbrown-xentity** [comment]
This is working as expected: federation.data.gov redirects to https://resources.data.gov/resources/us-data-federation/, as expected.
There is some cleanup in the other ticket, but this is working and can be closed.
