### ISSUE TITLE
uswds-compile reverted back to [4.0.2](https://github.com/uswds/uswds-compile/commit/74ddb4ca8ce5fec113a152265d31fb2450d33d65) recently

### ISSUE THREAD

**Issue by lilduvy** [GSA/data.gov#4794]
uswds-compile reverted back to [4.0.2](https://github.com/uswds/uswds-compile/commit/74ddb4ca8ce5fec113a152265d31fb2450d33d65) recently

_Originally posted by @rshewitt in https://github.com/GSA/data.gov/issues/4778#issuecomment-2148760368_

**Comment by btylerburton** [comment]
Issue for uswds-compile.
