### ISSUE TITLE
Add this repository to the GSA code inventory

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/data.gov#48]
*(I work in GSA IT, Office of the CTO. I am submitting this as part of our work to ensure GSA complies with the new Federal Source Code Policy.)*

GSA needs to create an inventory of all agency source code, whether open source or closed source. The inventory we create will appear on [Code.gov](https://code.gov/). The inventory will contain basic information about each source code repository, but will not include the source code itself. Please read the [implementation guide](https://gsa.github.io/GSAOpenSourcePolicy/guide/implementation/) and use it to **submit this repository to the inventory by December 5**.

Basically, please do one of the following, the details of which are described in the [implementation guide](https://gsa.github.io/GSAOpenSourcePolicy/guide/implementation/):

* Add a metadata file (`.codeinventory.yml` or `.codeinventory.json`) to this repository ([optionally, use this tool to generate a metadata file](https://gsa.github.io/codeinventory-metadata-generator/))
* Submit your metadata via a form (only do this if you cannot add a metadata file to this repository)

**Let me know if you would like me to open a PR with an example `.codeinventory.yml` file.**

Please let me know if you have any questions.

Thanks!

---

References:

* [GSA Open Source Implementation Guide](https://gsa.github.io/GSAOpenSourcePolicy/guide/implementation/)
* [GSA Open Source Policy](https://gsa.github.io/GSAOpenSourcePolicy/)
* [Federal Source Code Policy](https://sourcecode.cio.gov/)

**Comment by JJediny** [comment]
@jfredrickson5 we will add .code.yml to data.gov's main repository https://github.com/GSA/data.gov/issues/752
