### ISSUE TITLE
Configure Zendesk for public support platform

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4813]
## User Story

In order to better track feedback and efficiently reply to support tickets, datagov team wants to stand up Zendesk

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN the current system for replies to public feedback is cumbersome
  WHEN a member of the public emails us
  THEN a properly configured Zendesk group with macros, labels, and assignments will make it more efficient

## Background

This is work to get ZD ready as a main support platform for members of the public

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

None

## Sketch

- [x] Obtain Google Group email
- [x] Attach Google group email to Zendesk 
- [x] Configure group view settings
- [x] Create labels
- [x] Create macros for canned responses

**Comment by Bagesary** [comment]
Google group has been granted. Set up is ongoing.

**Comment by tdlowden** [comment]
Initial setup complete
