### ISSUE TITLE
Complete annual site self assessment

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4820]
As a requirement of TTS Digital Council and EDX team

https://docs.google.com/spreadsheets/d/1eEbQw-aS6UAfnCbhYP7oQq3SPTivdFDdJkjDKgfmrd0/edit?gid=1232597517#gid=1232597517

**Comment by tdlowden** [comment]
https://docs.google.com/spreadsheets/d/1eEbQw-aS6UAfnCbhYP7oQq3SPTivdFDdJkjDKgfmrd0/edit?gid=1912021007#gid=1912021007

**Comment by tdlowden** [comment]
Ready for review @hkdctol 

https://docs.google.com/spreadsheets/d/1eEbQw-aS6UAfnCbhYP7oQq3SPTivdFDdJkjDKgfmrd0/edit?gid=1232597517#gid=1232597517

**Comment by hkdctol** [comment]
@tdlowden I think spreadsheet is good to go--thanks

**Comment by tdlowden** [comment]
Submitted to Rachel Flagg
