### ISSUE TITLE
Apply hardening playbook to dev and production hosts

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#484]
hardening.yml should be applied to all hosts.

**Comment by adborden** [comment]
We've applied hardening to all hosts in both production and dev with a few stragglers.
catalog-harvester2p
catalog-web2d

**Comment by adborden** [comment]
I re-ran the hardening script on catalog-web2d.

I'm still waiting on the ticket for catalog-harvester2p to come back.

**Comment by hkdctol** [comment]
@adborden is that a ticket with BSP or GSA IT? Let me know if I can help expedite.

**Comment by adborden** [comment]
harvester2p is up and I ran the hardening playbook on it.
