### ISSUE TITLE
Complete first attempt at Product Worksheet

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4841]
https://docs.google.com/document/d/1VM4dnUU74O78C4tmzpLMCU8F7bCUwNEJAmTcUyvIw7w/edit#heading=h.uznhj24pqu6u

**Comment by tdlowden** [comment]
https://docs.google.com/document/d/1VM4dnUU74O78C4tmzpLMCU8F7bCUwNEJAmTcUyvIw7w/edit

**Comment by hkdctol** [comment]
I think we can consider this one done
