### ISSUE TITLE
Create process to generate unique URLs for datasets

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4849]
## User Story

In order to ensure any newly harvested datasets pass CKAN validation for unique titles, datagovteam wants to build a process to generate unique URLs for conflicting titles.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I am harvesting a source, which contains a dataset
  AND the title of that dataset conflicts with a dataset already on the CKAN instance
  WHEN the CKAN API returns a validation error of the type: `ValidationError({'name': ['That URL is already in use.'], '__type': 'Validation Error'})`
  THEN I want to add some extra random characters to the title to ensure the name is unique

- [ ] GIVEN I have added extra characters to the title of a dataset
WHEN I reharvest that dataset's source
THEN I want to ensure that the title remains the same.

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Define process for generating unique URLs for all datasets
- [ ] Ensure that process carries forward across multiple harvests

**Comment by jbrown-xentity** [comment]
The code to create the name in the harvester lives [here](https://github.com/GSA/datagov-harvester/blob/main/harvester/utils/ckan_utils.py#L119-L142)

**Comment by rshewitt** [comment]
> The code to create the name in the harvester lives [here](https://github.com/GSA/datagov-harvester/blob/main/harvester/utils/ckan_utils.py#L119-L142)

to be clear, that doesn't append text to the name to resolve the url issue it just formats the name in certain ways

**Comment by btylerburton** [comment]
We should be doing try/except check against our own DB. Moving this back to In Progress to accomplish that in a subsequent PR.
