### ISSUE TITLE
Add additional properties to CKAN metadata to define Flask DB Relationship

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4856]
## User Story

In order to allow for the correlation between a record in CKAN and a record in the flask db interface, datagovteam wants to add new properties to the CKAN metadata:

- record_id
  - the id of the record in the flask db
  - needed to display a link to the original metadata in the CKAN UI interface
- harvest_source_id
  - the id of the flask db harvest_source that this record corresponds to
  - needed to clear entries out of CKAN DB and Solr without clearing an organization's other datasets
- harvset_source_name
  - the human readable name of the flask db harvest_source
  - needed to display name of harvest source in CKAN UI

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I am harvesting a new harvest source
WHEN I am pushing a new dataset to CKAN via the REST API
THEN I want that to include the origin_record_id, origin_harvest_source_id, and origin_harvest_source_name as additional metadata properties

- [ ] GIVEN I have harvested a new dataset
WHEN I look at the metadata in CKAN I will see additional properties of origin_record_id, origin_harvest_source_id, origin_harvest_source_name that are not part of the original dataset's metadata.

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Add origin_record_id, origin_harvest_source_id and origin_harvest_source_name as extra metadata properties prior to positing the dataset to CKAN
- [ ] Confirm these properties show up on the dataset after harvest
- [ ] Confirm these properties persist on `package_update`

**Comment by btylerburton** [comment]
updated to include harvset_source_name

**Comment by FuhuXia** [comment]
This is closely related to https://github.com/GSA/data.gov/issues/4847.

**Comment by btylerburton** [comment]
Closing in favor of #4847
