### ISSUE TITLE
Support Non-Federal Data Harvesting

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#4870]
We need to enhance the current data harvesting system to support non-federal data sources. This involves updating the harvest_source table to include additional fields that differentiate between federal and non-federal data sources, or alternatively, using the existing schema_type field to manage this distinction.

## How to reproduce

When harvesting non-federal data sources, such as NYC Data.json, validation errors occur, preventing all records from being harvested.

## Expected behavior

The bureauCode field should not be validated when processing non-federal data.

## Actual behavior

validation error:  `<ValidationError: "'bureauCode' is a required property">`

## Sketch

- [ ]  Modify the harvest_source table to include a field indicating whether the source is federal or non-federal.
- [ ]  Update the harvester process to support the processing of non-federal data.

**Comment by jbrown-xentity** [comment]
We have a [non-federal schema](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/pod_schema/non-federal-v1.1/dataset-non-federal.json), but the JSON Schema version is super old. @rshewitt went through the process of upgrading the federal-v1.1 version and it is in the datagov-harvester [here](https://github.com/GSA/datagov-harvester/tree/main/schemas). I examined the differences between the federal and non-federal on the old version; they mostly consist of allowing REDACTED in the federal version, and some namespace convention changes that are mostly unnecessary.
I would propose going from the updated federal version, and making things not required using best judgement from the [DCAT-US spec documentation](https://resources.data.gov/resources/dcat-us/#dataset-fields). For example, while bureauCode is listed in the summary area  as being "required", in the [details](https://resources.data.gov/resources/dcat-us/#bureauCode), you'll see it is `Yes, for United States Federal Government agencies`. So for non-federal validation, this should be optional.

**Comment by rshewitt** [comment]
first pass it seems like `bureauCode` and `programCode` are the only ones which could be changed to optional. the latest federal version includes `keyword` and `modified` as required. based on the v1.1 documentation these seem reasonable to include in non-federal as required as well.
