### ISSUE TITLE
Limit the metrics section search terms download report to 50 rows

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4873]
## User Story

In order to prevent accidental PII exposure, datagovteam wants to limit the download report to the top 50 terms.

## Acceptance Criteria

- [ ] GIVEN a user clicks the download search terms report in the metrics section
  WHEN the file is opened
  THEN only 50 rows will populate

## Background

This is to remove most potential inclusions of people searching email addresses or SSNs with names in our search box

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

Accidental exposure of PII by showing the "long-tail" of search terms is something we'd like to avoid

## Sketch

- [ ] Put a row limit of 50 on the API call that populates the csv we store in s3

**Comment by btylerburton** [comment]
Done
