### ISSUE TITLE
Irrelevant Geoplatform Metadata link

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4879]
For dataset https://catalog.data.gov/dataset/test, geoplatform provide a metadata link to https://www.geoplatform.gov/metadata/6e23ae6d-314a-4fae-bdf4-f7b881c31b69, irrelevant to the dataset on the catalog.

This is more a bug on the geoplatform rather than on the catalog. geoplatform should not provide a link if the source is not from our catalog. So the geoplatform should improve their API endpoint and allow an additional parameter for dataset source, something like this:

https://api.geoplatform.gov/v3/public/lookups/data-gov/dataset?name=test&source=catalog.data.gov

with `&source=catalog.data.gov `at the end, we ensure we got result only relevant to catalog.

## How to reproduce

![image](https://github.com/user-attachments/assets/05d504b1-dc2c-4fa0-a01d-dd9f395208ef)

## Expected behavior

No Geoplatform Metadata link found.

## Actual behavior

Wrong Geoplatform Metadata link.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
Good find @FuhuXia ! @chris-macdermaid and the geoplatform team have been made aware and are looking into this; they've created a bug ticket on their end.

**Comment by Bagesary** [comment]
Team decided to icebox this bug until we hear from geoplatform team.

**Comment by btylerburton** [comment]
The API returns the same URL for these two different queries:

- https://api.geoplatform.gov/v3/public/lookups/data-gov/dataset?name=test-postsandy
- https://api.geoplatform.gov/v3/public/lookups/data-gov/dataset?name=test

**Comment by chris-macdermaid** [comment]
GeoPlatform has updated the lookups API. The OpenSearch datagov id field was of type text. We changed its type to keyword for an exact match. Let us know if you see any other issues.

**Comment by jbrown-xentity** [comment]
I agree from our test case this is resolved.
I think we can revert https://github.com/GSA/ckanext-datagovtheme/pull/189/files, bump the version, and then release it, and this feature should be back online! Moving this to No Status so we can discuss as a team.

**Comment by btylerburton** [comment]
This does appear to be fixed.

Currently @FuhuXia's test URL I don't see the Geoplatform link any longer: https://catalog.data.gov/dataset/test

But it shows up for valid datasets: https://catalog.data.gov/dataset/an-example-data-set-for-exploration-of-multiple-linear-regression

FWIW I think we never turned the feature off after turning it back on in April: https://github.com/GSA/ckanext-datagovtheme/blame/main/ckanext/datagovtheme/templates/package/read.html#L271
