### ISSUE TITLE
MDTranslator ISO19115-2 to DCATUS: identifier

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4882]
## User Story
In order to transform ISO19115-2 documents into DCATUS using mdtranslator, datagov wants to add processing for `identifier`

## Acceptance Criteria
- [x] GIVEN the DCATUS `identifier` field \
  AND how the DCATUS writer expects to find the data within the internal metadata object
  WHEN the associated ISO19115-2 reader ruby modules are created 
  THEN `identifier` should be transformed from ISO19115-2 to DCATUS

## Background
- related to [#4862](https://github.com/GSA/data.gov/issues/4862)
- We process 291017 ISO19115-2 datasets. We want all our datasets to be in DCATUS. 
- This reader is not intended to be feature complete according to the ISO19115-2 standard. All we're looking to read is as much as the DCATUS writer expects. 
- [ISO19115-3 development workflow](https://github.com/GSA/mdTranslator/tree/datagov?tab=readme-ov-file#feature-development)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

**Comment by rshewitt** [comment]
- "identifier" in citation is a `MD_Identifier_PropertyType` and is declared in [referencesystem](https://www.isotc211.org/2005/gmd/referenceSystem.xsd). copy link to highlight doesn't appear to work for this kind of document.
- for this ticket you'll need to create an `identification` module ( here's the equivalent module for the [writer](https://github.com/GSA/mdTranslator/blob/datagov/lib/adiwg/mdtranslator/writers/iso19115_2/classes/class_mdIdentifier.rb) ). the dcatus writer looks for a `namespace` value associated with the identifier but only a `RS_Identifier_Type` has a codespace/namespace property so you don't have to process it
