### ISSUE TITLE
MDTranslator ISO19115-2 to DCATUS: License

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#4883]
## User Story
In order to transform ISO19115-2 documents into DCATUS using mdtranslator, datagov wants to add processing for `license`

## Acceptance Criteria
- [ ] GIVEN the DCATUS `license` field \
  AND how the DCATUS writer expects to find the data within the internal metadata object
  WHEN the associated ISO19115-2 reader ruby modules are created 
  THEN `license` should be transformed from ISO19115-2 to DCATUS

## Background
- related to [#4862](https://github.com/GSA/data.gov/issues/4862)
- We process 291017 ISO19115-2 datasets. We want all our datasets to be in DCATUS. 
- This reader is not intended to be feature complete according to the ISO19115-2 standard. All we're looking to read is as much as the DCATUS writer expects. 
- [ISO19115-3 development workflow](https://github.com/GSA/mdTranslator/tree/datagov?tab=readme-ov-file#feature-development)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
- field mapping relationship ISO19115-2 -> MDJSON -> DCATUS
  - .//gmd:MD_DataIdentification//gmd:resourceConstraints//gmd:MD_Constraints//gmd:useLimitation
  - intObj[:metadata][:resourceInfo][:constraints][:reference][:title]
  - license
- add processing in resourceInfo to read keywords from gmd:MD_DataIdentification
- create a transformation test demonstrating how the value went from the ISO19115-2 document into the DCATUS json
- create a response object message test verifying when required elements are missing

**Comment by rshewitt** [comment]
iso19115-3 has 3 constraints: common, legal, and security. if these are present in -2 then you should probably create all 3. `reference` in the constraint is a citation in -3. dcatus only pulls the title from that reference/citation so there shouldn't need to be an update to the citation module because title is already processed

**Comment by Jin-Sun-tts** [comment]
In the current DCAT-US writer, the `license` is derived from `resourceInfo -> constraints -> reference -> title`. 
```
ISO19115-3 
<mri:resourceConstraints>
    <mco:MD_Constraints>
           <mco:reference>
               <cit:CI_Citation>
                  <cit:title>
```

However, in ISO19115-2, `MD_Constraints `under `resourceConstraints` does not include a `reference` element.
```
 <gmi:MI_Metadata
   <gmd:identificationInfo>
     <gmd:MD_DataIdentification>
       <gmd:resourceConstraints> 
          <gmd:MD_Constraints>
             <gmd:useLimitation>

```

need guidance on how to locate the corresponding `license` information in `ISO19115-2`.

**Comment by btylerburton** [comment]
Based on this statement from https://resources.data.gov/resources/podm-field-mapping/:

```
license | License | if applicable | no | default value for government data is ‘Public Domain’
```

and the default field for DCAT-US in the writer which is:

```
license = title || 'https://creativecommons.org/publicdomain/zero/1.0/'

```
https://github.com/GSA/mdTranslator/blob/datagov/lib/adiwg/mdtranslator/writers/dcat_us/sections/dcat_us_license.rb#L10

I believe our current ckanext-spatial transformer treats the rights and license fields interchangeably, and incorrectly.

In https://catalog.data.gov/dataset/office-of-coast-survey-wrecks-and-obstructions-database / https://catalog.data.gov/harvest/object/f5060a92-e297-4940-b8f3-41ed6eb39a34 the `<gmd:useLimitation>` should be mapped to rights and not license.

I'm closing this with the expectation that no further work is needed to make this spec compliant, though changes might be necessary to adapt it to our needs when we reach that step.

**Comment by btylerburton** [comment]
I'm going to write a test case for this even if we don't have any code changes and we will defer to the default from the writer.
