### ISSUE TITLE
MDTranslator ISO19115-2 to DCATUS: Language 

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#4888]
## User Story
In order to transform ISO19115-2 documents into DCATUS using mdtranslator, datagov wants to add processing for `Language `

## Acceptance Criteria
- [ ] GIVEN the DCATUS `Language ` field \
  AND how the DCATUS writer expects to find the data within the internal metadata object
  WHEN the associated ISO19115-2 reader ruby modules are created 
  THEN `Language ` should be transformed from ISO19115-2 to DCATUS

## Background
- related to [#4862](https://github.com/GSA/data.gov/issues/4862)
- We process 291017 ISO19115-2 datasets. We want all our datasets to be in DCATUS. 
- This reader is not intended to be feature complete according to the ISO19115-2 standard. All we're looking to read is as much as the DCATUS writer expects. 
- [ISO19115-3 development workflow](https://github.com/GSA/mdTranslator/tree/datagov?tab=readme-ov-file#feature-development)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
- field mapping relationship ISO19115-2 -> MDJSON -> DCATUS
  - gmi:MI_Metadata//gmd:locale//gmd:PT_Locale//gmd:languageCode//gmd:LanguageCode
  - intObj[:metadata][:metadataInfo][:defaultMetadataLocale][:languageCode] + [:otherMetadataLocales][:languageCode]
  - language
- add processing in resourceInfo to read keywords from gmi:MI_Metadata//gmd:locale
- create a transformation test demonstrating how the value went from the ISO19115-2 document into the DCATUS json
- create a response object message test verifying when required elements are missing

**Comment by Jin-Sun-tts** [comment]
dcatus writer looking for` [:metadata][:metadataInfo][:defaultMetadataLocale][:languageCode] `and optional `[:otherMetadataLocales][:languageCode]`

ISO19115-2 doesn't include default and other metadata locales:
```
<gmi:MI_Metadata
  <gmd:locale>
    <gmd:PT_Locale>
      <gmd:languageCode>
        <gmd:LanguageCode 
```

need suggestions on how to mapping this situation.

**Comment by btylerburton** [comment]
would setting a default in dcat-us writer be the way to go, @rshewitt?

**Comment by rshewitt** [comment]
@btylerburton iso19115-3 has 2 kinds of locales: `mdb:defaultLocale` and `mdb:otherLocale`. iso19115-2 appears to only have 1 type of locale: `gmd:locale`. one path forward is to use the first locale as the default and the remaining ones as others. this would bypass editing the dcat-us language module and instead be handled within `module_locale` of the iso19115-2 reader. frankly, i don't feel confident enough to run with that decision so we should bounce it off of chris

**Comment by FuhuXia** [comment]
looking at XML we have on catalog, it is predominately
```
<gmi:MI_Metadata>
    <gmd:language>
    <gco:CharacterString>eng</gco:CharacterString>
    </gmd:language>
```

**Comment by Jin-Sun-tts** [comment]
https://resources.data.gov/resources/podm-field-mapping/
//gmd:identificationInfo/gmd:MD_DataIdentification/**gmd:languageConvert** 
the value of this field based on the following mapping:
eng; USA - en-US
spa; USA - es-US
eng; CAN - en-CA
fre; CAN - fr-CA
spa; MEX - es-MX

```
<gmi:MI_Metadata>
      <gmd:language>
        <gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/php/code_list.php" 
          codeListValue="eng">eng</gmd:LanguageCode>
        </gmd:language>

```

```
<gmi:MI_Metadata>
      <gmd:language>
        <gco:CharacterString>eng; USA</gco:CharacterString>
      </gmd:language>
```

**Comment by btylerburton** [comment]
We need to put the language setter here: https://github.com/GSA/mdTranslator/blob/datagov/lib/adiwg/mdtranslator/readers/iso19115_2/modules/module_metadata_info.rb

Path it to `hMetadataInfo[:defaultMetadataLocale][:languageCode]` and call it a day.

**Comment by Jin-Sun-tts** [comment]
Based on discussion with Reid, for now we just process the locale information from following:
```
 <gmd:locale>
    <gmd:PT_Locale>
      <gmd:languageCode>
        <gmd:LanguageCode codeListValue="eng" codeSpace="123"/>
```

There could be multiple `gmd:locale`, we only set the first one to [:defaultMetadataLocale]
