### ISSUE TITLE
MDTranslator ISO19115-2 to DCATUS: distribution

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4894]
## User Story
In order to transform ISO19115-2 documents into DCATUS using mdtranslator, datagov wants to add processing for `distribution`

## Acceptance Criteria
- [ ] GIVEN the DCATUS `distribution` field \
  AND how the DCATUS writer expects to find the data within the internal metadata object
  WHEN the associated ISO19115-2 reader ruby modules are created 
  THEN `distribution` should be transformed from ISO19115-2 to DCATUS

## Background
- related to [#4862](https://github.com/GSA/data.gov/issues/4862)
- We process 291017 ISO19115-2 datasets. We want all our datasets to be in DCATUS. 
- This reader is not intended to be feature complete according to the ISO19115-2 standard. All we're looking to read is as much as the DCATUS writer expects. 
- [ISO19115-3 development workflow](https://github.com/GSA/mdTranslator/tree/datagov?tab=readme-ov-file#feature-development)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
- field mapping relationship ISO19115-2 -> MDJSON -> DCATUS
  - [ from multiple places. will add later ]
  - intObj[:metadata][:distributorInfo]
  - distribution
- create a transformation test demonstrating how the value went from the ISO19115-2 document into the DCATUS json
- create a response object message test verifying when required elements are missing

**Comment by rshewitt** [comment]
module flow:
   - distribution -> distributor -> transfer options -> online resources

we really only care about transfer options & online resources because that's what the dcatus writer uses

- module_transfer_option
   - mediaType
      - distribution format is a sibling to transfer options in MD_Distributor but is stored as a child of transfer options in mdjson
      - you'll need to get distribution formats seperately from transfer options then add distro format to the transfer option hash
   - module_online_resource
      - accessURL
         - read from `gmd:linkage//gmd:URL` stored in `:olResURI`. dcatus only care if the url ends with `.html`
      - downloadURL
         - read from `gmd:linkage//gmd:URL` stored in `:olResURI`. dcatus only cares if the url doesn't end with `.html`
      - title
         - read from `gmd:name//gco:CharacterString` stored in `:olResName`

**Comment by rshewitt** [comment]
what does an online resource look like within a `gmd:MD_DigitalTransferOptions` element?

```xml
<!-- gmd:MD_DigitalTransferOptions siblings... -->
<gmd:onLine>
  <gmd:CI_OnlineResource>
     <gmd:linkage>
        <gmd:URL>http://online.adiwg.org/1</gmd:URL>
     </gmd:linkage>
     <gmd:protocol>
        <gco:CharacterString>protocol</gco:CharacterString>
     </gmd:protocol>
     <gmd:applicationProfile>
        <gco:CharacterString>application profile</gco:CharacterString>
     </gmd:applicationProfile>
     <gmd:name>
        <gco:CharacterString>online resource name</gco:CharacterString>
     </gmd:name>
     <gmd:description>
        <gco:CharacterString>online resource description</gco:CharacterString>
     </gmd:description>
     <gmd:function>
        <gmd:CI_OnLineFunctionCode codeList="http://mdtranslator.adiwg.org/api/codelists?format=xml#CI_OnLineFunctionCode" codeListValue="online resource function" codeSpace="userCode"/>
     </gmd:function>
  </gmd:CI_OnlineResource>
</gmd:onLine>
<!-- gmd:MD_DigitalTransferOptions siblings... -->
```
