### ISSUE TITLE
Remove ec2-catalog roles

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#491]
These roles mostly set configuration files to hostnames base don ec2. This is silly because ansible supports inventory variables for that. In the meantime, the hosts for ckan are set to things like 'localhost' which causes ckan to be unavailable until the ec2-catalog runs (theres no database on localhost).

**Comment by nickumia-reisys** [comment]
Ansible no longer being used.
- https://github.com/GSA/data.gov/issues/3710
