### ISSUE TITLE
Deploying catalog/inventory app results in site broken-ness or downtime

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#492]
The order that we copy/move the code and rollback code means that files are unavailable or permissions aren't set correctly while apache is still serving the app. This results in random failures for users. Instead we should minimize the time we need to take the instance out of service and make sure to take the instance out of service during the critical bits.

"take the instance out of service" usually means removing them from the load balancer, but without API keys, this won't  be possible. The best we can do is stop apache which will cause the ELB to detect a health issue and kick out the instance. The ELB will detect when the instance is back up (we won't have control over that).

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
