### ISSUE TITLE
Write proposal to redirect strategy.data.gov

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4921]
## User Story

In order to decrease our compliance burden, datagovteam wants to propose putting relevant content from strategy.data.gov on a resources.data.gov page and redirect the strategy.data.gov site to that location.

## Acceptance Criteria

- [ ] GIVEN OMB has. stake in strategy.data.gov
  WHEN a proposal to redirect strategy.data.gov is approved by OMB
  THEN we can move forward with consolidation and redirect
## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

none

## Sketch

- [ ] Create proposal
- [ ] Get it approved by TTS stakeholders
- [ ] Get it approved by OMB stakeholders

**Comment by tdlowden** [comment]
Proposal at: https://docs.google.com/document/d/1iCnF1JB7ryouul9GIbm0OOZiu6mPtZH_PzeQq7w_E_M/edit

**Comment by hkdctol** [comment]
@tdlowden Will discuss this with our management and determine what other stakeholders within TTS we need to consult, if any, and then next step would be raising with OMB.
