### ISSUE TITLE
Merge MDTranslator work in datagov branch to main

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4923]
## User Story

In order to park our spec-compliant work, datagov team wants to merge the datagov branch into main for MDTRanslator. This will allow us to begin work on the sibling reader which will need changes to accomodate the divergent XML markup in catalog documents.

Depends upon: #4862 

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [x] Merge gsa/MDTranslator datagov branch into main
- [x] Copy reader work into sibling namespace
  - [x] `lib/adiwg/mdtranslator/readers/iso19115_2` -> `lib/adiwg/mdtranslator/readers/iso19115_2_datagov`
  - [x] `test/readers/iso19115_2` -> `test/readers/iso19115_2_datagov`
  - [x] `test/translator/tc_iso19115_2_to_dcatus.rb` -> `test/translator/tc_iso19115_2_datagov__to_dcatus.rb`
- [x] Add new namespaced tests to Rakefile

**Comment by Bagesary** [comment]
This ticket is the pre-requisite for #4924

**Comment by rshewitt** [comment]
master now has spec-compliant ( feature-incomplete ) iso19115-2 & -3 readers excluding our dcat-us writer changes. edits to that writer will come later.

**Comment by rshewitt** [comment]
@btylerburton related to our conversation yesterday. `keyword` is required in dcatus but optional in -2 ( at least where we're currently reading it from ). here's the element
```xml
<xs:element name="descriptiveKeywords" type="gmd:MD_Keywords_PropertyType" minOccurs="0" maxOccurs="unbounded"/>
```
this puts us in an interesting situation where we have to explain why something was rejected based on the destination schema and not the input source.

**Comment by btylerburton** [comment]
Thanks for doing this work @rshewitt. It will be crucial to our designing the requirements for what should pass validation or not.
