### ISSUE TITLE
catalog playbook should restart supervisor harvest services after upgrading ckan

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#494]
After running the playbooks on catalog-harvester, the supervisor services (gather, fetch, etc) still reported uptimes of hours, instead of showing they were restarted.

**Comment by nickumia-reisys** [comment]
Ansible no longer being used.
- https://github.com/GSA/data.gov/issues/3710

Harvesting restarts are still an issue, but that part is superseded by
- https://github.com/GSA/data.gov/issues/4187
