### ISSUE TITLE
Add tables for global file downloads and external clicks on /metrics

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4943]
## User Story

In order to understand the totality of downloads and link clicks on the site, agency users wants unfiltered file download and external link data.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN we don't have a way of attributing links to orgs on search results pages
  WHEN someone visits the main /metrics page happens 
  THEN tables for global downloads and external link clicks will be present
 AND have associated downloadable full files

## Background

The org-specific dataset pages do not account for link clicks directly from search results. This will help show the full picture

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

none

## Sketch

- [ ] Create API calls for global downloads and external links

- [ ] Add tables for downloads and external links to global /metrics page

   MOST_DOWNLOADED_DATASETS_GLOBAL: {
      title: "Most Downloaded Dataset Files",
      description: "Top 10 downloaded files across catalog.data.gov, including links on dataset pages and search results pages",

  MOST_CLICKED_OUTBOUND_LINKS_GLOBAL: {
      title: "Most Downloaded Dataset Files",
      description: "Top 10 external link clicks across catalog.data.gov, including links on dataset pages and search results pages",

- [ ] Include download links for the global data

**Comment by FuhuXia** [comment]
change can be previewed at the [staging site](https://federalist-2ac784db-2321-4734-8d02-933835d88304.sites.pages.cloud.gov/preview/gsa/datagov-11ty/two-global-reports/metrics/). 

![image](https://github.com/user-attachments/assets/c7f66813-4ad4-4d20-bfc5-d9400619a12d)
