### ISSUE TITLE
hardening playbook disables apache

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#495]
Hardening playbook disables [unnecessary services](https://github.com/GSA/ansible-os-ubuntu-14/blob/master/tasks/section2.yml#L56) but there is no way to configure that we need apache on some hosts. This is not a major problem, since running the role playbooks after hardening will re-enable the needed services.

It seems this may have been [supported](https://github.com/GSA/ansible-os-ubuntu-14/blob/master/defaults/main.yml#L27) at one point, but these variables don't appear in the task files.

**Comment by jbrown-xentity** [comment]
Ran into again today, simply restarted services manually after running the common playbook and then the reboot. Eventually ran full site deployment to correct problem moving forward.

**Comment by nickumia-reisys** [comment]
Ansible no longer being used.
- https://github.com/GSA/data.gov/issues/3710
