### ISSUE TITLE
Update lists on https://data.gov/open-gov/

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4958]
## User Story

In order to have current listings of international and US SLTT data catalogs, users want lists that have been revisited annually.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN datagov offers links to international and State/Local data catalogs on https://data.gov/open-gov/
  WHEN those lists are accessed
  THEN they will have been tested and updated

## Background

Annual review

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

none

## Sketch

- [ ] Test existing URLs to verify they resolve
- [ ] Update list with new links or additional links
- [ ] Publish new csvs on https://data.gov/open-gov/

**Comment by tdlowden** [comment]
[OpenGov Listings - INTL.csv](https://github.com/user-attachments/files/17804292/OpenGov.Listings.-.INTL.csv)
[OpenGov Listings - US.csv](https://github.com/user-attachments/files/17804293/OpenGov.Listings.-.US.csv)


New files attached. @btylerburton can you help us get these in S3? We could probably just swap the csvs in the same file location to avoid needing a PR to update the link on data.gov, yes?

**Comment by btylerburton** [comment]
Sure, I can take care of the uploads. Will let you know when that's complete.

**Comment by btylerburton** [comment]
@tdlowden @crysacarter can you confirm the S3 links are updated? Thanks.

**Comment by crysacarter** [comment]
I'm still seeing the 2023 links. @tdlowden ?

**Comment by tdlowden** [comment]
Yep, hang on. we just need to merge the new links. One sec.

**Comment by tdlowden** [comment]
@crysacarter PR is merged. New links are there now!
