### ISSUE TITLE
Update and harden Management VPC and Logging stack

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#496]
Apply hardening and updated vendored roles to management and logging stack

Management:
- [ ] web-proxy.yml
- [ ] efk-nginx.yml
  - [ ] verify nginx hash bucket config set to 128
- [ ] efk-stack.yml
- [ ] elastalert.yml
- [ ] elasticsearch.yml

**Comment by hkdctol** [comment]
Closing tickets related to old infrastructure.
