### ISSUE TITLE
Draft VoC quarterly update

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4968]
Background:

 I'm writing to request updates for the activities (such as training, outreach, webinars, newsletters, partner meetings, etc.) that you have engaged in on your program to improve customer satisfaction on your program in Q4 2024 (July 1, 2024 - September 30, 2024). These updates will be provided to the FAS CASE Office of Customer Care Voice of the Customer (VoC) program to be shared out in a quarterly VoC bulletin. Providing the updates is a way that FAS demonstrates that we are using the customer feedback and data that came out of the FY23 Customer Loyalty Survey to identify and drive any initiatives, and/or activities to improve the customer experience. 

As with the last time, the quarterly updates should include the following points:

Summary of initiatives - provide a brief overview of the activities that you are driving to improve customer satisfaction on your program.

Progress and Achievements - highlight any significant milestones or achievements reached since the last update.  Share any positive outcomes and success stories related to your program offerings.

Challenges and Solutions - identify any challenges encountered during the implementation of your initiatives.  Outline any strategies or solutions employed to overcome these challenges.

Upcoming Plans and Action Items - outline any upcoming projects or strategies aimed at further improving customer satisfaction in the next quarter.

Here are the TTS [updates](https://docs.google.com/document/u/0/d/1QJDMyItdOtryZugEbGit5STzrUEJ7trEK7v3ZGM2kUU/edit) that were provided to the Voice of the Customer program for Q3 2024.  Please feel free to update this document directly to include your program’s Q4 updates.  Alternatively, you may  provide your program’s updates in a separate document and I'll incorporate them into the submission to the VoC program office for TTS. I am asking for updates to be sent to me or updated in the document by CoB Friday, November 15, 2024.

The Q4 updates should be brief and highlight the activity(ies) that your program is implementing to improve customer satisfaction, how it drives customer engagement and/or satisfaction, and any challenges encountered in implementing these activities.

**Comment by tdlowden** [comment]
Draft here: https://docs.google.com/document/d/19vjtdN0VU_XL2dJKcmiJxVzPho5qUl8FTdnblHHb7_s/edit?tab=t.0

It's strange to try to write this for Q4 when we are halfway through FY25 Q1, but I think I captured most things. Please feel free to add/edit, @hkdctol

**Comment by hkdctol** [comment]
Made some edits @tdlowden
