### ISSUE TITLE
grub-mount sometimes hang when GRUB_DISABLE_OS_PROBER is not set

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#497]
@JJediny found that somtimes apt/dpkg will hang when updating things like the kernel which require the grub config to be regenerated. When GRUB_DISABLE_OS_PROBER is not set on ubuntu trusty on AWS, this will sometimes hang the apt/dpkg process. We've seen this on a handful of machines.

We should add `GRUB_DISABLE_OS_PROBER=true` to `/etc/default/grub` in the `software/ubuntu/common` role.

**Comment by JJediny** [comment]
The common role has not been applied to all existing host reopening until we confirm and reboot

**Comment by adborden** [comment]
Haven't seen this come up recently, so this looks like it's fixed now.
