### ISSUE TITLE
Catalog "Please try another search" in the wrong location

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4975]
When search yield no results on catalog, the text `Please try another search.` shows up in the wrong location.

## What is on Catalog:
![image](https://github.com/user-attachments/assets/e9713161-fe67-4c9a-8aaf-a0e15754ed0a)

## What is on DEMO CKAN:
![image](https://github.com/user-attachments/assets/beb082fe-e373-4640-8b15-8e24bf377ec1)

**Comment by Jin-Sun-tts** [comment]
Changed the location of the message:

![Image](https://github.com/user-attachments/assets/ff818500-a8a9-470a-a20a-4ee5c2190a4d)
