### ISSUE TITLE
Search Collection changed to Search Datasets on collection page

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4976]
On catalog, when you are on a collection page, the search box should have "Search Collection"  in the search box as placeholder text. But it changes to Search Datasets when search box is out of focus. 

![image](https://github.com/user-attachments/assets/335069ad-ad08-467c-b0c3-d0edd7eb3baf)

## How to reproduce

1. go to a collection page, such as [this page](https://catalog.data.gov/dataset/?collection_package_id=e8b6064e-d75c-4a54-a4b7-995b570d5c76). Notice it says **Search Collection**.
2. Click the search box, and click away.
3. The text changes to **Search Datasets**.
4. text color also changes.

## Expected behavior

It stays as **Search Collection**.

## Actual behavior

Text changes to **Search Datasets**. Font color also changes.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by rshewitt** [comment]
the color changes also affects "Search Datasets..."

**Comment by rshewitt** [comment]
https://github.com/user-attachments/assets/b146baf5-a2df-455a-a841-3865f7aaf13e
