### ISSUE TITLE
[research: 1 day] Review ckan cleanup jobs

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#499]
## User Story

In order to reduce uncertainty about whether we're maintaining our CKAN deployment well, the team wants to spend 1 day researching the cleanup scripts and maintenance available and identifying what we could/should enable.

## Acceptance Criteria

- [ ] We have a backlog of issues reflecting the improvements that we identified by doing the research.

## Background
@adborden said: 
> @jbrown-xentity  and I were just debugging an issue with redis and the harvesters and saw that there are old harvest objects and jobs in redis. We should ensure that these kinds of things get cleaned up in redis, solr, and the database. What processes are in place to regularly remove old data?

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Not for the research, though we may note security considerations for particular issues that span out of it.

## Sketch
- [ ] Pay attention to [solr sync issues](https://github.com/GSA/datagov-deploy/issues/1595)
- [ ] Review [ansible jobs that are commented out](https://docs.google.com/document/d/16lDiaz6ZEJ3jOlCAP2UcuRvG0MrnaEaYhkLwc3fY2hA/edit#) to determine if they're useful and should be enabled
- [ ] clean out revisions and old harvest jobs
- [ ] validate if solr is tracking harvest job information and ensure it's only tracking the most recent object
- [ ] ensure jobs are running regularly via cron

**Comment by jbrown-xentity** [comment]
Will want to test jobs on sandbox first, and see what looks to be able to be enabled...

**Comment by jbrown-xentity** [comment]
Using [google doc](https://docs.google.com/document/d/16lDiaz6ZEJ3jOlCAP2UcuRvG0MrnaEaYhkLwc3fY2hA/edit#) to track notes. Will eventually update readme or ticket where appropriate.

**Comment by jbrown-xentity** [comment]
Updated [Wiki Documentation](https://github.com/GSA/datagov-deploy/wiki/CKAN-commands) and cleaned up. Most jobs are not running regularly. Should do a deep dive into next steps for each job, something like `Add to automation or remove job`...
