### ISSUE TITLE
Add Page Title to download and outbound link tables

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4992]
## User Story

In order to understand which datasets link refer to, public users wants to see the name of the page the files are clicked from.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a user visits a metrics page for an org
  WHEN the outbound link and download file tables render
  THEN they should include a column for page title

## Background

On their own, it is difficult to decipher what a download file link means without clicking it ![Image](https://github.com/user-attachments/assets/0d615c11-3bdc-4cab-a03e-72eb508dd9a0)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch

- [ ] Add `page title` into the API calls that populate the outbound and download reports saved into S3
- [ ] Add `page URL` into the API calls that populate the outbound and download reports saved into S3
- [ ] Add `Page Title` as a column in the download files table
- [ ] Add `Page Title` as a column in the outbound link table
- [ ] Link `Page Title` text to page URL

**Comment by rshewitt** [comment]
@tdlowden is this what you're looking for in the UI?

![Image](https://github.com/user-attachments/assets/bee9e9fa-b558-40ec-b6e7-d856ef0ef7b1)

**Comment by rshewitt** [comment]
@tdlowden ran into an interesting situation with the "Most downloaded dataset files". these results are current so they're gonna be different than what's on prod now. 

![Image](https://github.com/user-attachments/assets/5eff39ed-68b6-4980-a69b-2edf7c5a9daf)

the same file was downloaded but on different pages. one is the [dataset page](https://catalog.data.gov/dataset/americorps-participant-demographics-data)  and the other is the [resource page](https://catalog.data.gov/dataset/americorps-participant-demographics-data/resource/e7222bd1-69c9-4725-ad4a-6769d30697e2).

**Comment by tdlowden** [comment]
@rshewitt Yep, I'm aware of this. But without a descriptive universal "File Name" we can capture across pages in a single row (in your example, the file name is `rows.csv`, which is useless), this is the expected outcome. It's the best we can currently do

**Comment by rshewitt** [comment]
i regenerated the reports for november so what's on s3 should be updated with my changes. 11ty pages on main/prod get rebuilt nightly so in the meantime here's the preview pages offers

<img width="1183" alt="Screenshot 2024-12-09 at 12 09 30 PM" src="https://github.com/user-attachments/assets/7cd03583-a991-4c58-a51b-37c2a7999a43">

**Comment by tdlowden** [comment]
2 thoughts @rshewitt 

1. Can you adjust the column header to `Page Title` instead of just `title`? I don't want people to think thats the file name.

2. Is there any way to make the page title column a bit wider, so that it can fit more of the page title in the row before expanding?

**Comment by rshewitt** [comment]
> 2 thoughts @rshewitt
> 
> 1. Can you adjust the column header to `Page Title` instead of just `title`? I don't want people to think thats the file name.
> 2. Is there any way to make the page title column a bit wider, so that it can fit more of the page title in the row before expanding?

1. yeah sure
2. yeah i'll look into it

**Comment by rshewitt** [comment]
i also noticed something odd about the outbound links. i'll look into it.

**Comment by tdlowden** [comment]
@rshewitt what did you find with outbound?

**Comment by Bagesary** [comment]
pairing and PR review in progress

**Comment by rshewitt** [comment]
- global and per-org are complete: https://data.gov/metrics/
- the download and outbounds table columns vary in width because of the underlying class used. would require some work to get the first and second rows fixed and align with each other.

**Comment by rshewitt** [comment]
fix download files page title hyperlink ( it's using the count )
