### ISSUE TITLE
catalog metrics data shows new result after action rerun 

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#5000]
Data displayed on page https://data.gov/metrics/ is collected on the 1st day of each month. When a new report is generated on the 3rd day, the data in the CSV is different from what is displayed on the page. It needs to wait till the next day for the displayed data gets corrected after an 11ty page rebuild overnight.

## How to reproduce

Run action https://github.com/GSA/data.gov/actions/workflows/build-metrics-report.yml on the 3rd day of a month.

## Expected behavior

Data displayed on page https://data.gov/metrics/  is consistent with downloaded CSVs.

## Actual behavior

Slightly different

## Sketch

It could be that Google Analytics requires an extra day after the end of the month to fully process and collect data from the previous month. If the data stabilizes by the 2nd/3rd day, we can adjust the cron job to run the report on the 2nd/3rd day instead of the 1st. However, if the data continues to fluctuate daily, we can add a unique string to each CSV file to ensure that the data displayed on the page matches the data in the downloaded CSV.

**Comment by btylerburton** [comment]
@tdlowden do we expect the latest reports to be timestamped 2024-12-31?

**Comment by tdlowden** [comment]
@btylerburton we do. and I see they are. Is something fishy happening?

**Comment by btylerburton** [comment]
nope, just wanted to confirm it wasn't supposed to be stamped 2024-01-01.
