### ISSUE TITLE
Change package name to conform to PyPi standards

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#5005]
## User Story

In order to ensure our project continues to be published to PyPi, datagovteam wants to update the naming format of our datagovtheme package.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN the notification below (in background)
  WHEN we make the appropriate changes and publish again to PyPI
  THEN the deprecation warning will no longer be sent

## Background

We received this deprecation warning from PyPI:

> This email is notifying you of an upcoming deprecation that we have determined may affect you as a result of your recent upload to 'ckanext-datagovtheme'.
> 
> In the future, PyPI will require all newly uploaded source distribution filenames to comply with PEP 625. Any source distributions already uploaded will remain in place as-is and do not need to be updated.
> 
> Specifically, your recent upload of 'ckanext-datagovtheme-0.2.37.tar.gz' is incompatible with PEP 625 because it does not contain the normalized project name 'ckanext_datagovtheme'.
> 
> In most cases, this can be resolved by upgrading the version of your build tooling to a later version that supports PEP 625 and produces compliant filenames.
> 
> If you have questions, you can email admin@pypi.org to communicate with the PyPI admin@pypi.org to communicate with the PyPI administrators.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by btylerburton** [comment]
Replacing deploy commands based on this rec: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary

**Comment by Jin-Sun-tts** [comment]
PR merged. Closed this issue.
