### ISSUE TITLE
Add https://resources.data.gov/resources/cdoc-case-study/ to "Skills development" section of the site

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#5012]
## User Story

In order to provide better discoverability, CDO Council wants https://resources.data.gov/resources/cdoc-case-study/ to be listed under "Skills development".

## Acceptance Criteria

- [ ] GIVEN a user is looking for the report on https://resources.data.gov/resources/cdoc-case-study/
  WHEN a user clicks in the "Skills development" section of resources.data.gov
  THEN an entry for "Federal CDO Data Skills Training Program Case Studies" will appear in the list

AND

- [ ] GIVEN a user is looking for the report on https://resources.data.gov/resources/cdoc-case-study/
  WHEN a user clicks in the "case studies" section of resources.data.gov
  THEN an entry for "Federal CDO Data Skills Training Program Case Studies" will appear in the list (which is currently true)
  

## Background

We received an email from DCOC that they wanted this entry moved from one section to the other, but being that it  fits in both categories, we should make it visible in both sections.

Email:

Good Morning Hyon,

Hope this message finds you well and dry on this rainy day.

Could you or your team help up with re-aligning the "[Federal CDO Data Skills Training Program Case Studies](https://resources.data.gov/resources/cdoc-case-study/)" report to  "Skills Development" instead of "Case Studies" on the platform?

Our users tend to look for the resource under skills and we believe the update would greatly improve searchability.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

None

## Sketch

- [ ] Add an entry for "Federal CDO Data Skills Training Program Case Studies" in "Skills development" section

**Comment by Jin-Sun-tts** [comment]
PR merged. Closed this issue.
