### ISSUE TITLE
Mobile view distorted with new language under search bar

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#5017]
The search layout is not ideal on mobile:

![Image](https://github.com/user-attachments/assets/230127c0-46b6-4f9a-8d10-34052d48516b)

## How to reproduce

1. visit catalog.data.gov on mobile

## Expected behavior

The extra search operators language spans the width of the screen

## Actual behavior

The extra search operators language spans 2/3 the width of the screen because it is interfered with by the search result order dropdown

**Comment by rshewitt** [comment]
can't replicate it via device toolbar on chrome even with responsive dimensions

**Comment by rshewitt** [comment]
web inspector for [iOS](https://developer.apple.com/documentation/safari-developer-tools/inspecting-ios)

**Comment by rshewitt** [comment]
@tdlowden 

mobile 

![Image](https://github.com/user-attachments/assets/9232a6e0-0dc2-4424-bd7a-e371f7bb2908)

desktop

https://github.com/user-attachments/assets/5170d074-57f5-401e-be02-e20193b7ad9f

**Comment by tdlowden** [comment]
Looks good. Thanks @rshewitt
