### ISSUE TITLE
Harvest source NRC (datajson) gets stuck in gather queue

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#508]
Harvest source `80f5799b-ffbd-4867-8ca5-c5d2b3c85760` gets stuck in gather queue. This is the only log line, then it hangs:
```
2018-11-21 22:12:13,583 DEBUG [ckanext.harvest.queue] Received harvest job id: cda19bd1-d967-4ccb-85a8-e42e7e74ba6e
```

**Comment by adborden** [comment]
I noticed when curl'ing their data.json, sometimes it would hang, but eventually it started coming through without an issue.

**Comment by hkdctol** [comment]
Closing old tickets
