### ISSUE TITLE
CloudWatch harvester false positive on CPU alert

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#513]
> View this alarm in the AWS Management Console:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#s=Alarms&alarm=DATAGOV-Production-CatalogHarvester1CPUAlarm-B7RUQYJYNM8H
>
> Alarm Details:
> - Name:                       DATAGOV-Production-CatalogHarvester1CPUAlarm-B7RUQYJYNM8H
> - Description:                CPU alarm for CatalogHarvester1
> - State Change:               INSUFFICIENT_DATA -> ALARM
> - Reason for State Change:    Threshold Crossed: 1 datapoint [99.575000000002 (30/11/18 16:28:00)] was greater than the threshold (90.0).
> - Timestamp:                  Friday 30 November, 2018 16:34:45 UTC

I took a look at harvester1p and this looks more like a false alarm. The harvesters should be running on high CPU based on their workload. Looks like Census kicked off the meta.geo.census.gov harvest which just finished, so the load is back to 0.

It looks like a 4 CPU system, so having 8 fetch workers + 1 gather might be too many processes. The load was  ~ 7.6 6.4 5.1, which is probably too much (I think for a 4CPU system you want an avg load of 5. We might want to:
1. Change this CPU alert to be over a duration instead of alarm on a single point or just remove it
2. Ensure there is an alert based on average load over some duration of time
3. Maybe reduce the number of workers

**Comment by adborden** [comment]
Another data point: load average: 5.60, 4.71, 2.80

**Comment by adborden** [comment]
I think we also want to open a ticket with BSP to remove this CloudWatch alert. We manage our own alerts in New Relic, which is much easier to tune (we have direct access, don't need to go through BSP).

**Comment by nickumia-reisys** [comment]
No more CloudWatch alerts for harvesting.  We have cloud.gov container monitoring/metrics for each app (including harvesters), so this is handled in a completely different way and no long relevant.
