### ISSUE TITLE
Test individual CKAN extensions

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#517]
For each code base, we will need to look at implementing the most recent/upstream version, and use any documentation for setup to add to Docker.

We will use the list documented here: https://github.com/GSA/datagov-deploy/wiki/Catalog-CKAN-2.8-upgrade

High level review of code differences, consider any improvements/additions to GSA version to get pushed upstream.

Validate specifically for the enabled extensions in current data.gov catalog production.ini file, but attempt all and note any errors.

If anything is broken or will require changes, create a new card.

**Comment by kimwdavidson** [comment]
reundant with forks epic #1343
