### ISSUE TITLE
php-fpm not logging errors

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#523]
I'm trying to debug an issue with max.gov and I can't find the errors generated by PHP. Nothing is logged to /var/log/php7.0-fpm.log. Only notices are logged to /var/log/upstart/php7.0-fpm.log

**Comment by adborden** [comment]
I think these errors are supposed to appear in the nginx error log.

**Comment by jbrown-xentity** [comment]
We no longer use php or max.gov, closing.
