### ISSUE TITLE
Full metadata link gathering the oldest original harvest metadata instead of newest

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#526]
This occurs sitewide, and is due to the additions of the geodatagov extension (https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/plugins.py#L407) to save old harvest id information. The fix is noted in the code in CKAN here: https://github.com/GSA/ckan/blob/datagov/ckan/lib/helpers.py#L1606

**Comment by adborden** [comment]
Duplicate of https://github.com/GSA/datagov-deploy/issues/524

**Comment by adborden** [comment]
Nm

**Comment by jbrown-xentity** [comment]
This is not something we're going to fix, closing.
