### ISSUE TITLE
Links in WordPress pages pointing to s3

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#529]
A number of links, such as the image on this page: https://www.data.gov/ecosystems/ecoinforma/ which were previously data.gov links, are now at links such as https://s3.amazonaws.com/bsp-ocsit-prod-east-appdata/datagov/wordpress/2014/01/EcoINFORMA-_conceptual_illustration.jpg

This is a temporary fix and we should have data.gov links.

**Comment by adborden** [comment]
As a temporary fix, we should update the broken links by updating them in SQL to the CNAME'd bucket. This will involved some NetScaler routing. @philipashlock has some additional details.

**Comment by nickumia-reisys** [comment]
This is an interesting ticket.  Technically this is still a problem, but the solution would be way different for our cloud.gov setup.  It may be possible to just add a DNS record in the 18f repo: https://github.com/18F/dns
