### ISSUE TITLE
Re-enable a small set of automatic harvesters, start with the CFO act datajson harvest sources.

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#531]

**Comment by philipashlock** [comment]
Also refer to the [previous state](https://github.com/GSA/datagov-deploy/issues/532#issuecomment-444233960) of harvest sources before they were all set to manual.

**Comment by hkdctol** [comment]
Set GSA and Treasury to daily on 12/17, GSA harvest ran and Treasury is still shown as "running."

**Comment by adborden** [comment]
@hkdctol I tried clearing out the Treasury job, but harvester1p is available. I opened a ticket with BSP.

**Comment by hkdctol** [comment]
Closing this as we have set harvest jobs back to automatic for CFO Act and other federal agencies.
