### ISSUE TITLE
Review list of all harvest sources and work with agency POCs to identify old ones and remove them

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#532]

**Comment by philipashlock** [comment]
We've used [this script](https://github.com/GSA/ckan-php-manager/blob/master/cli/harvest_stats_csv.php) in the past to generate a report of harvest sources

We recently updated and backed-up the state of all harvest sources with this [script](https://github.com/GSA/ckan-php-manager/blob/master/cli/update_harvest.php). 
- August backup of [all harvest sources](https://drive.google.com/open?id=1g2pm1fe0W-QDrrGzFMb8DFvd_KrrGlYg) (with state of automatic/manual)
- August backup of [automatic harvest sources](https://drive.google.com/open?id=1U9EwcSDFX27i09_svJmczZC-TM47GWKy)

**Comment by adborden** [comment]
This is ongoing, we have an introduction session for new agencies on Thursday.

**Comment by hkdctol** [comment]
Outreach to agencies already in Data.gov almost complete.

**Comment by hkdctol** [comment]
Outreach is complete, would recommend closing for now and then create new ticket when we know there's a list of harvesters we know to delete.
