### ISSUE TITLE
catalog-harvester2p becomes unavailable

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#541]
We've seen catalog-harvester2p become unavailable. I've been on that machine when it happens and I believe it's consuming too much memory and then stalling out. We should verify with BSP that this is the case and then look into remediations.

**Comment by adborden** [comment]
This definitely looks like a large job before memory is exhausted.
![screenshot from 2019-02-06 16-22-28](https://user-images.githubusercontent.com/509703/52382778-7ec04180-2a2b-11e9-8672-518d41b80308.png)

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
