### ISSUE TITLE
Free space on catalog replicas is low

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#542]
We keep seeing alerts and occasional spikes in low free disk space on the catalog replicas. We're growing a few gigabytes every few weeks at the moment.

https://drive.google.com/file/d/0B5EC5Q83gYbobEhaQ3ozelVFazNfak9NazNxRDFleXdPQ0ZB/view

**Comment by adborden** [comment]
I think we should look at upgrading the replicas the first week of January.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
