### ISSUE TITLE
dashboard-web playbook should fail if database connection settings are not specified

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#543]
I just ran the dashboard-web playbook in test without having a database setup and the playbook passed.

**Comment by mogul** [comment]
[The app itself will now fail if DB settings aren't specified.](https://github.com/GSA/project-open-data-dashboard/pull/219/commits/b0e1b9f52235d6d6a04b06cc45f74c1bd9e5b279) What's the right way to test for this during deployment on the Ansible side?

**Comment by adborden** [comment]
In ansible, you can comment out the variables of the .env template or you
can specify incorrect values on the command line...

ansibe-playbook ... -e db_password=foo

**Comment by mogul** [comment]
Tested working... The app throws a `500` and ansible shows:
![image](https://user-images.githubusercontent.com/47762/70747408-cadbb280-1cdc-11ea-902a-ce9f987b2694.png)

When you visit the app you see this:
![image](https://user-images.githubusercontent.com/47762/70747375-b4355b80-1cdc-11ea-92c5-47c55b8f4c01.png)

The [log message generated](https://github.com/GSA/project-open-data-dashboard/blob/2e376fbf3f3e3494da774335e3be0114fe02ee52/application/config/database.php#L104-L105) just before showing that result is specific about which DB param is missing.

**Comment by mogul** [comment]
This issue can be marked complete once https://github.com/GSA/datagov-deploy/pull/1207 is merged.
