### ISSUE TITLE
Decommision datagovsolrm1d

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#551]
This host is no longer used. Open a ticket with BSP to remove it.

**Comment by adborden** [comment]
10.183.0.141

**Comment by adborden** [comment]
@JJediny I can open the issue, just want to confirm with you that there is no reason to keep datagovsolrm1d around for anything.

**Comment by hkdctol** [comment]
Closing--if still relevant we will be decommissioning all FCS resources soon.
