### ISSUE TITLE
Install mod-http-headers-more-filter on nginx hosts

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#562]
We upgraded nginx using the nginx ppa. They moved the header-more-filter to a package, so it must be installed separately. It's already on some hosts but not all (not sure why). We should make sure to install it as part of our nginx role.

```
- apt: name=libnginx-mod-http-headers-more-filter state=present
```

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
