### ISSUE TITLE
filestore.data.gov/gsa/catalog/jsonl/index.html should be under version control or updated automatically

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#566]
If it's under version control, I can't find it. The jsonl-export job updated dataset.jsonl.gz, but the index page doesn't reflect the new size/date.

Side note, under the shutdown, this page is confusing. There's no message why catalog.data.gov redirects here so it looks more like an error or misconfiguration

**Comment by adborden** [comment]
Finally figured out how to update it for now:
![screenshot from 2019-01-09 13-42-26](https://user-images.githubusercontent.com/509703/50930315-926c8e00-1414-11e9-8a8b-910a7ad5b206.png)

I think under normal circumstances, this should be a landing page that describes the dataset, similar to the content described on [catalog.data.gov](https://catalog.data.gov/dataset/data-gov-ckan-api) ([cached version](https://webcache.googleusercontent.com/search?q=cache:mYpbbnnaFgYJ:https://catalog.data.gov/dataset/data-gov-ckan-api/resource/96bf923e-e7ce-45f7-ad1f-47eb34178e95+&cd=1&hl=en&ct=clnk&gl=us)).

> **Government-wide open data metadata bulk download**
> 
> This provides a bulk extract of all metadata stored in Data.gov for Federal datasets. The file is automatically generated monthly as an export from the CKAN API using the JSON Lines serialization format (jsonlines.org). This does not provide all metadata stored on Data.gov, only metadata for Federal datasets following the metadata guidelines described at http://www.digitalgov.gov/resources/how-to-get-your-open-data-on-data-gov/
>  The compressed file is approximately 2.3GB.

**Comment by philipashlock** [comment]
The version control for this file is meant to be managed at https://github.com/GSA/datagov-filestore-landing/blob/master/index.html

**Comment by adborden** [comment]
But what was filestore.data.gov/gsa/catalog/jsonl/index.html supposed to be before the shutdown? Before I updated it, /gsa/catalog/jsonl/index.html was more of a directory listing of the different versions of dataset.jsonl.gz, all out dated and incorrect.

**Comment by adborden** [comment]
Here's a  [cached version](https://webcache.googleusercontent.com/search?q=cache:7fc5zFUJO_MJ:https://filestore.data.gov/gsa/catalog/jsonl/+&cd=10&hl=en&ct=clnk&gl=us): 

![screenshot from 2019-01-11 12-18-42](https://user-images.githubusercontent.com/509703/51057647-12246500-159b-11e9-858d-981320d66a81.png)

**Comment by nickumia-reisys** [comment]
Given that it no longer exists, what was filestore used for in the past?  Are we using an S3 bucket to host things that we need to now?

**Comment by jbrown-xentity** [comment]
Undocumented static s3 resources to serve 5xx and 4xx error pages (if catalog service is down). Configured directly with cloudfront. This is not considered best practice, and with multiple ways to accomplish this (nginx server in front of catalog in current implementation), this will not be re-implemented.

**Comment by nickumia-reisys** [comment]
So this was superseded by,
- https://github.com/GSA/catalog.data.gov/pull/403/files#diff-6f7fcc8e11a2a2b1d2134f83b9a69f16ff1d42f32192f69b8d28f0ea7631594d
