### ISSUE TITLE
jsonl-export does not produce json

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#567]
We provide the entire [metadata catalog as JSONL](https://catalog.data.gov/dataset/data-gov-ckan-api/resource/96bf923e-e7ce-45f7-ad1f-47eb34178e95) produced by the jsonl-export job in [ckanext-geodatagov](https://github.com/GSA/ckanext-geodatagov). However, the JSONL produced is not valid because jsonl-export from ckanext-geodatagov [stringifies the object](https://github.com/GSA/ckanext-geodatagov/blob/f9ea5196bbb6b0336a574fdaa4bb3c5b3d2cf4b1/ckanext/geodatagov/commands.py#L1209) instead of JSON serializing it, so you end up with keys like `u'datetime'` and the data can't be parsed with JSON/JSONL libraries.

## How to reproduce
In your local development environment:

1. `paster --plugin=ckanext-geodatagov geodatagov jsonl-export --config=/etc/ckan/production.ini`
1. Inspect the dataset.jsonl.gz file created `zcat dataset.jsonl.gz | head -n1 | jq .`

## Expected behavior

File is properly formatted JSONL (JSON objects separated by newlines) and `jq` prints the first dataset.

## Actual behavior

File is not properly format, jq complains it cannot parse the input.

## To do
- wrap the output in json.dumps
- write tests

**Comment by adborden** [comment]
As a stop-gap, I want to make sure we have a good snapshot of the catalog.data.gov metadata catalog before we launch catalog-next.

**Comment by avdata99** [comment]
Related to #1848

**Comment by avdata99** [comment]
To QA in sandbox:
 - Open the terminal in catalog-next-web
 - run `sudo ckan --plugin=ckanext-geodatagov geodatagov jsonl-export`

**Comment by adborden** [comment]
@avdata99 the command is working but the output format is wrong, see my comment here https://github.com/GSA/ckanext-geodatagov/pull/160/files#r494515501

**Comment by CodeShtuff** [comment]
QA looks good. 

Steps/Results:
Exported json file:
`$ docker-compose exec ckan bash -c "paster --plugin=ckanext-geodatagov geodatagov jsonl-export"
... trimmed for brevity ...
2020-10-01 14:04:29 jsonl is being generated, 1 pages, total 9 datasets to go.
2020-10-01 14:04:29 doing page 1/1...
2020-10-01 14:04:29,983 INFO  [ckanext.geodatagov.plugins] NOT Added FQ to collection_package_id
Compressing ...
No AWS destination, saved at: /tmp/jsonl/jsonl-Ft75Ny.json, /tmp/jsonl/jsonl-3o3l03.json.gz
2020-10-01 14:04:29 Done.`

Verified file created and noted name:
`$ docker-compose exec ckan bash -c "ls -ltr /tmp/jsonl"
total 56
-rw-r--r--    1 root     root          2968 Sep 30 13:31 PyZ3950_parsetab.py
-rw-------    1 root     root         41905 Oct  1 14:04 jsonl-Ft75Ny.json
-rw-------    1 root     root          8019 Oct  1 14:04 jsonl-3o3l03.json.gz`

Verified content (viewed full output, sample head here to provide brevity):
`$ docker-compose exec ckan bash -c "zcat /tmp/jsonl/jsonl-3o3l03.json.gz" |head -n1 |jq . |head
[
  {
    "license_title": "other-license-specified",
    "maintainer": "HPI Help Desk",
    "relationships_as_object": [],
    "private": false,
    "maintainer_email": "hpihelpdesk@fhfa.gov",
    "num_tags": 9,
    "id": "cba19026-60d7-41cd-835e-f03c6d6c3325",
    "metadata_created": "2020-09-30T14:39:23.391176",`
