### ISSUE TITLE
Configure web instances to listen on HTTPS

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#570]
data.gov sites redirect HTTP -> HTTPS* but the load balancer talks to the hosts on HTTP. HTTPS would provide an extra layer of security within AWS.

This would involve a few steps because of BSP.
1. Configure apache/nginx to serve the site on both HTTP and HTTPS.
1. Open a ticket with BSP to update all the load balancers to talk to instances over HTTPS.
1. Configure HTTP to 301 redirect to HTTPS so its not possible to connect over HTTP.

This could be done for staging, then production.

_* I'm not exactly sure where this is happening, at CloudFront, load balancer or at NetScaler._

**Comment by adborden** [comment]
CRM and Dashboard were completed as part of [RITM0598393](https://gsa.service-now.com/sp/?id=form&table=sc_req_item&filter=&sys_id=de1c654adb64f7440e1d368d7c961919&v=).

**Comment by adborden** [comment]
No longer applies to component/static since we moved to Federalist.

**Comment by FuhuXia** [comment]
Will do a survey on following Netscaler/Load Balancer entries and request BSP to change protocol from all HTTP to HTTPS. This change also means currently used ip address in the URL need to be changed to hostnames.

Prod:
```
wp-bsp.data.gov 		(www.data.gov)
catalog-bsp.data.gov 		(catalog.data.gov)
admin-catalog-bsp.data.gov	(admin-catalog.data.gov)
catalog-next.data.gov
admin-catalog-next.data.gov
inventory-bsp.data.gov		(inventory.data.gov)
dashboard-bsp.data.gov		(labs.data.gov/dashboard/)
```
Staging:
```
wordpress-datagov.dev-ocsit.bsp.gsa.gov
catalog-datagov.dev-ocsit.bsp.gsa.gov
admin-catalog-datagov.dev-ocsit.bsp.gsa.gov
catalog-next-datagov.dev-ocsit.bsp.gsa.gov
admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov
inventory-datagov.dev-ocsit.bsp.gsa.gov
inventory-next-datagov.dev-ocsit.bsp.gsa.gov
dashboard-datagov.dev-ocsit.bsp.gsa.gov
```
