### ISSUE TITLE
Renew site certificates

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#574]
The `*.data.gov` certificate expires April 21, 2019. GSA offers external certificates. We should look into this as an option.

**Comment by hkdctol** [comment]
We will create Service Catalog request to request the external certs from GSA. For that we need the complete list of subdomains. Will send to @adborden

**Comment by adborden** [comment]
Service Now ticket submitted.

**Comment by adborden** [comment]
This got hung up related to DNSSEC policy. We're waiting on GSA cert team to clarify the requirements. In the meantime, we're looking for alternatives.

**Comment by adborden** [comment]
:tada: the certificate has been issued. Key and certificate are in [drive](https://drive.google.com/drive/folders/1vMCI5YXvVklSZTEohfnZke04upo8qdJc). I'll open a ticket with BSP to get these installed on NetScaler

@JJediny can you install these on the CDN?

**Comment by adborden** [comment]
Certificate and key have been installed on Cloud Front. Opened [RITM0601967](https://gsa.service-now.com/sp/?sys_id=c2c1afb4db307f080e1d368d7c961920&view=sp&id=ticket&table=sc_req_item) to install to NetScaler.

**Comment by adborden** [comment]
Verified that domains are using the new certificate with [this script](https://gist.github.com/adborden/f0dc1cfa0eb8912ec4def8322860377c). 

The following domains were not updated, but I believe they are no longer used or are manged by another team.
```
coop.smallbusiness.data.gov... fail
manage.data.gov... fail
origins-data-gov.data.gov... fail
origins-smallbusiness.data.gov... fail
smallbusiness.data.gov... fail
```

**Comment by adborden** [comment]
For reference, this is the content of the ticket for BSP. Just like any other BSP ticket, it should be a Generic Request:

> Short Title: Replace *.data.gov site certificate
>
> Key and certificate are available in Google Drive, please request access https://drive.google.com/drive/folders/1vMCI5YXvVklSZTEohfnZke04upo8qdJc
> 
> There are about ~80 domains to address.
