### ISSUE TITLE
Check firewall rules for labs.data.gov for Brasil

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#578]
Seeing Uptrends checks consistently fail for Brasil's checkpoints.
https://app.uptrends.com/Report/ProbeLog?probeGuids=0605ad53-7cf3-49e7-839b-4aabd7692cdd#

We should check with the firewall team if this is the case.

**Comment by adborden** [comment]
This might also be the case for sdg.data.gov

**Comment by adborden** [comment]
I'm seeing this affect all of our apps. The firewall team must have reverted the change to allow Brasil.

**Comment by hkdctol** [comment]
I think we can close this for now--as we should shortly be shifting away from using Uptrends.
