### ISSUE TITLE
Move test kitchen suites to molecule

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#581]
As part of the [Ubuntu bionic upgrade](https://github.com/GSA/datagov-deploy/issues/571), we're moving test kitchen suites to molecule where we can easily add bionic tests.

**Comment by adborden** [comment]
@sstevens21 is working on the CRM, Dashboard, and WordPress roles.

**Comment by adborden** [comment]
@sstevens21 is handing off the work. Latest commits will be pushed to https://github.com/sstevens21/datagov-deploy/tree/feature/move_apps_to_molecule

**Comment by adborden** [comment]
Still waiting on the latest commits.

**Comment by mogul** [comment]
Aaron's going to try to move this forward this sprint, particularly as the lack of automated testing for dashboard and Wordpress has been a hindrance.

**Comment by mogul** [comment]
Aaron's planning to break these roles out into their own repositories to reduce build times/dependencies.
