### ISSUE TITLE
Python 2.7 end-of-life January 1, 2020

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#591]
We need to double check our CKAN extensions and make sure they work with python 3. We should also standardize on a long-term-support version of python 3.

**Comment by nickumia-reisys** [comment]
We are already on Python 3.
- https://github.com/GSA/data.gov/issues/3401
- https://github.com/GSA/data.gov/issues/3388
- https://github.com/GSA/data.gov/issues/3374
