### ISSUE TITLE
Configure www.data.gov load balancers for backend on port 443

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#592]
We need to open a ticket with BSP to review the configuration. The WordPress nginx config expects to be responding on 443.

**Comment by JJediny** [comment]
cloudfront is HTTPS only if the issue remains after the cache purge we will need to address this at the load balancer

**Comment by adborden** [comment]
Thanks, I've updated the issue name. The load balancer in combination with our nginx config is what caused the outage.

**Comment by adborden** [comment]
BSP ticket is resolved.

**Comment by adborden** [comment]
Both production and staging load balancers are listening on 443 only.
