### ISSUE TITLE
Review catalog playbook and roles to identify tasks that should be the responsibility of catalog-app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#600]
When you run catalog-app, you get an app that behaves slightly different from production. This is because there are some tasks that happen in ansible for production, but won't happen in local development for catalog-app. Review the ansible roles and plays to identify what should be pulled out.

**Comment by adborden** [comment]
For example, we know that ckanext-datagovtheme looks different in local development than in production.

**Comment by nickumia-reisys** [comment]
No more Ansible.
- https://github.com/GSA/data.gov/issues/3710

Our current local development is as close to production as possible.  I don't have any hard links for this, but our docker setup does mirror >95% of cloud.gov ckan operations.
