### ISSUE TITLE
Remove deprecated Wordpress plugins

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#612]
These plugins are no longer supported, they no longer appear in the composer/wpackagist repos. We should find their functionality elsewhere and remove these.

- [ ] https://wordpress.org/plugins/custom-content-type-manager/
- [ ] https://wordpress.org/plugins/si-captcha-for-wordpress/
- [ ] phpoffice/phpexcel should be replaced with phpoffice/phpspreadsheet

**Comment by adborden** [comment]
As a work around, we are pulling these dependencies from their subversion archives.

**Comment by adborden** [comment]
FYI the subversion archives can be slow, and sometimes composer times out when checking them out:

```
  - Installing wpackagist-plugin/custom-content-type-manager (0.9.8.9):  Checking out tags/0.9.8.9

                                                                                                                                                              
  [RuntimeException]                                                                                                                                          
  Package could not be downloaded, The process "svn co --non-interactive  'https://plugins.svn.wordpress.org/custom-content-type-manager//tags/0.9.8.9' '/var/www/vendor/wpackagist-plugin/custom-content-type-manager'" exceeded the timeout of 300 seconds.
```

I've tried setting COMPOSER_PROCESS_TIMEOUT in some cases as a work around.

**Comment by hkdctol** [comment]
Closing as we've left Wordpress
