### ISSUE TITLE
software/ckan/native-login should move to catalog-app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#620]
[software/ckan/native-login role](https://github.com/GSA/datagov-deploy/blob/master/ansible/roles/software/ckan/native-login/tasks/main.yml) should be moved to config in catalog-app, allowing this config to be used based on an ansible variable at deploy time.

**Comment by nickumia-reisys** [comment]
No more Ansible.
- https://github.com/GSA/data.gov/issues/3710

I don't have any hard links for this one, but we have normal login enabled for local development and the option to enable Login.gov saml2auth login (for testing).  We have Login.gov saml2auth always on in cloud.gov.
