### ISSUE TITLE
software/ckan/saml2 should move to catalog-app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#621]
[software/ckan/saml2 role](https://github.com/GSA/datagov-deploy/blob/master/ansible/roles/software/ckan/saml2/tasks/main.yml) should move to catalog-app and configs should be deployed based on ansible variable at deploy time.

**Comment by nickumia-reisys** [comment]
Similar to 
- https://github.com/GSA/data.gov/issues/620#issuecomment-1416550657
- https://github.com/GSA/data.gov/issues/3710
