### ISSUE TITLE
Configure postfix root alias to datagov team email

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#626]
As a datagov operator, I want to receive notifications from the hosts so that I know if there are any errors (system, cron, etc) so that I can respond to them.

**Comment by adborden** [comment]
Setting an alias for root and configuring [smtp_generic_maps](http://www.postfix.org/ADDRESS_REWRITING_README.html#generic) would allow us to forward messages.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
