### ISSUE TITLE
audit logs are filling up the disk

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#634]
I've seen this on a handful of hosts in dev where /var/logs is almost full. It's because audit.log.123 files are being created without being cleaned up. The hardening script explicitly configures auditd to not remove files. I think we want logrotate to handle them to avoid wrestling with the hardening role.

**Comment by adborden** [comment]
See https://github.com/GSA/datagov-deploy/issues/949#issuecomment-531055829 for work around.

**Comment by adborden** [comment]
catalog-harvester1p hitting this.

**Comment by adborden** [comment]
inventory1d.dev-ocsit.bsp.gsa.gov too

**Comment by FuhuXia** [comment]
logrotate is not designed to handle files with different extensions, i.e. `audit.log.???`,  in this folder.  I think we should add a cronjob to clean files based on file timestamps.

**Comment by adborden** [comment]
auditd has it's own log rotation mechanism. I think we want to address it there. https://github.com/GSA/ansible-os-ubuntu-16/blob/a4f78639b7be2e7e20e8cc5c8d0e4d328861b3bb/tasks/section4.yml#L13

**Comment by nickumia-reisys** [comment]
No more FCS.
- https://github.com/GSA/data.gov/issues/3710

Logs are primarily tracked by Cloud.gov, (GSA ISE? whichever team handles central logging) and New Relic.
