### ISSUE TITLE
Monitoring for background jobs and processes

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#639]
These are things we should create alerts for in New Relic
- apache2 is up for apache hosts
- nginx is up for nginx hosts
- supervisor is up for all hosts
- webrick/jekyll/ruby is running on static-web
- when background jobs haven't run (I'm not sure the best way to detect this)

**Comment by adborden** [comment]
[Superlance](https://github.com/Supervisor/superlance/blob/master/docs/crashmail.rst) is a plugin for supervisor that includes an event listener that watches for unexpected exits on supervisor processes.

Systemd has [OnFailure](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#OnFailure=) directive that could be used to start another unit that sends a notification.

**Comment by hkdctol** [comment]
A ticket from old infrastructure

**Comment by nickumia-reisys** [comment]
Superseded by
- https://github.com/GSA/data.gov/issues/3710
