### ISSUE TITLE
Move static sites to Federalist

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#641]
Moving our static sites to Federalist removes the need to manage static-web.

- https://github.com/GSA/us-data-federation
- https://github.com/GSA/sdg-indicators-usa
- https://github.com/GSA/data-strategy

[Federalist launch checklist](https://federalist.18f.gov/documentation/launch-checklist/).
- [x] Add site in the Federalist app
- [x] Assert that site is building correctly and preview look correct
- [x] Check CI checks are passing
- [x] Schedule launch day/time with Federalist and GSA DNS
  - resources-staging.data.gov
  - strategy.data.gov
  - strategy-staging.data.gov
  - sdg.data.gov
  - sdg-staging.data.gov
  - federation.data.gov
  - federation-staging.data.gov
- [x] Enable fork builds in CI
- [x] Require CI checks to pass
- [x] Update workflow documentation
- [x] Update the custom site name in Federalist app
- [x] Remove jekyll role from datagov-deploy
- [x] Open ticket with BSP to decommission static-web
- [x] Clean up branches (staging, gh-pages, etc) in repos

**Comment by adborden** [comment]
Part of https://github.com/GSA/datagov-deploy/issues/571

**Comment by adborden** [comment]
Trying to schedule the switchover for the end of the week. I've submitted a ticket with the DNS team to reduce the TTL to 300 seconds.

**Comment by adborden** [comment]
Relevant PRs:
- [x] [federation](https://github.com/GSA/us-data-federation/pull/20)
- [x] [sdg](https://github.com/GSA/sdg-indicators-usa/pull/994)
- [x] [strategy](https://github.com/GSA/data-strategy/pull/52)

**Comment by adborden** [comment]
I removed the webhooks from all three repos.

**Comment by adborden** [comment]
These buckets should be removed from BSP, along with any CloudFront distributions
- bsp-ocsit-prod-east-data-site-sdg
- bsp-ocsit-prod-east-data-site-federation
- bsp-ocsit-prod-east-data-site-strategy
- bsp-ocsit-dev-east-data-site-sdg
- bsp-ocsit-dev-east-data-site-federation
- bsp-ocsit-dev-east-data-site-strategy

**Comment by adborden** [comment]
Ticket submitted to remove resources. DNS we will drop on our move to TTS DNS.

**Comment by FuhuXia** [comment]
DNS entries `federation-staging.data.gov` and `sdg-staging.data.gov` were removed today.

**Comment by FuhuXia** [comment]
`federation-staging.data.gov` and `sdg-staging.data.gov` are back live?

**Comment by mogul** [comment]
Closing as we've confirmed that the Federalist side has been disabled.
