### ISSUE TITLE
Investigate PyCSW export command

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#648]
Partners like FGDC need to harvest all the geospatal datasets on data.gov. They primarily use the CSW service for this task which can be slow. PyCSW offers an [export command](https://docs.pycsw.org/en/2.2.0/administration.html?highlight=exporting#exporting-the-repository) that could be used to create a bulk archive of all the CSW datasets. This might be more efficient than using the CSW service to scan over every record.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3182
