### ISSUE TITLE
Create separate ansible-vault keys per inventory

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#652]
- [ ] Each inventory should have it's own vault key.
- [ ] Templates exist so that it is straight forward how to create a new inventory.
- [ ] [Runbook](https://github.com/GSA/datagov-deploy/wiki/Keypair-Rotation) is updated so documentation explains step-by-step how to rotate keys.

**Comment by nickumia-reisys** [comment]
No more Ansible.
- https://github.com/GSA/data.gov/issues/3710

I'm not sure what "inventory" this issue is referring to, but I'm pretty sure there's no equivalent for current operations.
