### ISSUE TITLE
Create an ansible role to manage pki-validation tokens

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#656]
In order to create pki-validation tokens to verify we control domains, we need a role to create these tokens and configure nginx to serve these under `/.well-known/pki-validation`

**Comment by adborden** [comment]
This is needed for https://github.com/GSA/datagov-deploy/issues/574

**Comment by nickumia-reisys** [comment]
No more Ansible,
- https://github.com/GSA/data.gov/issues/3710

Our Domain validations are handled directly by cloud.gov or https://github.com/18F/dns.
