### ISSUE TITLE
Setup authentication (pref. MFA) to Kibana

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#66]
Right now Kibana is open. We need to setup some authentication and restrictions. This is what I was looking at a few days ago. @JJediny thoughts?
https://aws.amazon.com/blogs/security/how-to-control-access-to-your-amazon-elasticsearch-service-domain/

**Comment by dano-reisys** [comment]
basic auth should be working now @ manage.data.gov

**Comment by kvuppala** [comment]
👍

**Comment by kvuppala** [comment]
@JJediny @hkdctol 
Should we setup a MAX Data.gov Admin group, only members in that group can access the Kibana dashboard after successful authentication and authorization.  Otherwise, any user who has MAX login will be able to access the dashboard once this is rolled out.

**Comment by hkdctol** [comment]
This is the approach we discussed earlier, yes? Sounds good to me.

**Comment by kvuppala** [comment]
@hkdctol Yes, we will soon have the request sent to MAX team.

**Comment by hkdctol** [comment]
Closing old tickets if not pertinent to current data.gov status.
