### ISSUE TITLE
Develop hardening role for Ubuntu 18.04

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#667]
We need a hardening role for trusty and bionic.
https://github.com/GSA/ansible-os-ubuntu-16

**Comment by adborden** [comment]
@JJediny is this complete? I think we have hardening supported in the common role now.

**Comment by JJediny** [comment]
Yes the [GSA supported ansible hardening role](https://github.com/GSA/ansible-os-ubuntu-16/pulls) for 16/xenial has been successfully tested for 18/bionic and is now fully implemented in https://github.com/GSA/datagov-deploy-common
