### ISSUE TITLE
Re-enable resubmit_jobs in ckanext-harvest

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#671]
ckanext-harvest upstream has resubmit_jobs as part of harvest run. This requeues harvest tasks that have timed out. The upstream timeout is 3 minutes, which might be too short for us. I would be happy with a 60 minute timeout. We should update the timeout and re-enable resubmit_jobs.

**Comment by adborden** [comment]
This is also related to fixing the duplicates issue in ckanext-datajson. Having the ability to requeue tasks would simplify how we process parent and child datasets.

**Comment by jbrown-xentity** [comment]
No longer investing in CKAN harvester. closing.
