### ISSUE TITLE
Harden the CSW harvester (failed requests derail harvests)

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#672]
The CSW harvester keeps failing for NOAA. The gather stage has to fetch thousands of records and any 500 on their side will fail the job. We need to review the CSW, add some retry logic, and do some general hardening to so the harvest is more robust.

**Comment by mogul** [comment]
NOAA will be rescued from this state by the work in #1419, but we're leaving this issue open as there are likely other agencies affected and the problem still exists.

**Comment by jbrown-xentity** [comment]
No longer investing in the CKAN harvester, closing.
