### ISSUE TITLE
Intermittent DNS issues

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#677]
The dns.gsa.gov name servers are having intermittent issues. This manifests in Uptrends alerts as "DNS Lookup Error" and DNS delays or timeouts. Uptrends uses a 10 second timeout. This issue started 2/16/2019 and we see dozens of errors every day. This is not specific to data.gov domains.

This report shows all the monitors, not just data.gov properties and all the DNS errors the monitors encountered. It shows this is systemic with the GSA DNS name servers.
https://docs.google.com/spreadsheets/d/17VHnDdyrd1IQkIqJYZUQe56JExE4NPNMGl0wguV-zh8/edit#gid=122081050

![DNS errors per day](https://user-images.githubusercontent.com/509703/54944631-2b2d8880-4ef1-11e9-95d6-94b4c718d5ba.png)

**Comment by adborden** [comment]
Opened https://gsa.service-now.com/sp/?id=sc_request&table=sc_request&sys_id=ac515b9bdb50f7800e1d368d7c9619d3

**Comment by adborden** [comment]
We've met with the GSA DNS team. Their monitors ping the DNS servers directly, which skips any potential network issues or DNS propagation issues that we might be seeing from the Uptrends monitors. We've passed on information to them about IP addresses and resolver information. Waiting to here back from them.

**Comment by afeld** [comment]
Is this for external DNS, or internal? If it continues to be an issue, we can get data.gov delegated to [DNS that's in our control](https://github.com/18F/dns).

cc https://github.com/18F/dns/issues/351

**Comment by adborden** [comment]
It's external (although there is some internal DNS names I haven't looked into, yet). The plan is to move to the TTS DNS in that repo, however I'm not sure that will completely resolve the issue. My understanding is Route53 still does not support DNSSEC, so we would still have to have some records in GSA's DNS which might still make us prone to the intermittent failures.

**Comment by adborden** [comment]
Added https://github.com/GSA/datagov-deploy/issues/1001
