### ISSUE TITLE
USDA dataset not included in faceted view for publisher

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#680]
https://catalog.data.gov/dataset/season-and-interval-of-burning-and-cattle-exclusion-in-the-southern-blue-mountains-oregon--b4eda and
https://catalog.data.gov/dataset/season-and-interval-of-burning-and-cattle-exclusion-in-the-southern-blue-mountains-oregon--9c0a6
are included under USDA datasets, but if you look for them under U.S.Forest Service view:

https://catalog.data.gov/organization/4ae51f6c-467a-4f9d-b40a-2c52e83c326a?publisher=U.S.+Forest+Service

the two datasets do not appear, though they appear to have correct metadata for program/bureau codes

**Comment by adborden** [comment]
I took a quick look at this and noticed most of the data that is usually in `extras` is actually in `extras_rollup`. Not sure if this is relevant but wondering if some code is not finding the bureau/program code in `extras_rollup`

**Comment by JJediny** [comment]
this sounds related to what we were just seeing when we enabled harvester with `USmetadata` extension, that some of the harvested metadata wasn't being mapped to the USmetadata form fields (and had an added `{}` wrapping each of these):

```
Language:
Program code:
Unique id:
Bureau code:
Contact name:
Contact email:
```
