### ISSUE TITLE
inventory-web 500 OperationalError SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#682]
Sometimes we see 500s from Uptrends. Seems to be one of the hosts having a database issue:
```
[Fri Mar 29 00:21:20.728001 2019] [:error] [pid 27740:tid 140422794897152] [remote 10.176.16.106:29884] Error - <class 'sqlalchemy.exc.OperationalError'>: (O
perationalError) SSL SYSCALL error: EOF detected
[Fri Mar 29 00:21:20.728126 2019] [:error] [pid 27740:tid 140422794897152] [remote 10.176.16.106:29884]  'SELECT beaker_cache.data \\nFROM beaker_cache \\nWH
ERE beaker_cache.namespace = %(namespace_1)s' {'namespace_1': 'fc49500cb6d749879e85af8df10c22cd'}
```

I've seen this over the course of several hours. It's strange that the connection doesn't get re-established and recover. Rebooting or restarting apache should be a fine work-around.

**Comment by FuhuXia** [comment]
This happen again today. Did a survey and there were 8k of occurrences of this error in the past 3 days.  Every time it happens user will see a 500 error page. So we need to resolve it to have a stable inventory web app.

I think it has something to do with the size of table beaker_cache. Query shows this table has 2.8 million records dated all the way back to December of 2016.  If we can have a slim beaker_cache table, this issue should be resolved. According to [Beaker docs](https://readthedocs.org/projects/beaker/downloads/pdf/v1.6.2/), it is developer's responsibility to delete old entries. 

```
2.4.1 Removing Expired/Old Sessions
Beaker does not automatically delete expired or old cookies on any of its back-ends. 
This task is left up to the developer based on how sessions are being used, 
and on what back-end.

The database backend records the last accessed time as a column in the database
so a script could be run to delete session rows in the database that haven’t been
used in a long time.
```

**Comment by mogul** [comment]
We need to regularly run a query to prune entries older than a certain date. We should add an Ansible task that sets up a cronjob to do that on one of the hosts.

**Comment by mogul** [comment]
@FuhuXia is going through testing his PR for this on sandbox, staging, and then prod.

**Comment by adborden** [comment]
Is cleanup of beaker sessions supported in upstream CKAN? Seems like CKAN should be the one supporting this. A script/cron doesn't translate well to cloud.gov and ultimately this is the application's responsibility.

**Comment by FuhuXia** [comment]
No sign of this feature support from upstream CKAN.

**Comment by adborden** [comment]
Would you please file an issue with CKAN?

**Comment by mogul** [comment]
Just pending the PR being approved at this point.

**Comment by FuhuXia** [comment]
Issue filed at ckan upstream https://github.com/ckan/ckan/issues/5294.

**Comment by FuhuXia** [comment]
Upstream issue was closed. CKAN's solution is also using a daily cron job to run a query to delete rows in beaker_cache table.

After our PR deployed, we haven't see any more such 500 errors. We can consider this issue is resolved.

**Comment by FuhuXia** [comment]
This continues to be an issue. We resolved it in FCS environment but the fix was not ported over to cloud.gov.
inventory-db has 16,822,505 records in beaker_cache, catalog-db has 223,037,215.

**Comment by gujral-rei** [comment]
Recommend creating systematic process to clean up the records.

**Comment by FuhuXia** [comment]
It is not easy to clean the table with 260 million rows. We should automate it so that we don't have to go thru the the manual process any more.
