### ISSUE TITLE
ntp should be configured with AWS ntp servers

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#688]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html

chrony is already installed on some of the hosts because it's included in the [hardening role](http://github.com/GSA/ansible-os-ubuntu-14)

**Comment by adborden** [comment]
@JJediny not sure if there's any work to do here, GSA's role is already configuring NTP https://github.com/GSA/ansible-os-ubuntu-16/blob/c1fdfd599922232e9ec9c9a344af9c87e0ed67a5/defaults/main.yml#L77-L79

**Comment by JJediny** [comment]
@adborden should close this out agreed
