### ISSUE TITLE
 AC 3.4 Technical Evidence

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#69]
Provide a representative sample of accounts/processes for evidence that access enforcement mechanisms are operating as intended (i.e., access provided to users and roles are consistent with what is authorized for:

- [ ] PostgreSQL (verify user/group/role access controls)
- [ ] CKAN (verify user/group/role access controls)
- [ ] Kibana (verify user/group/role access controls)  
- [ ] ElasticSearch (verify user/group/role access controls)

**Comment by hkdctol** [comment]
Closing old issue from completed audit.
