### ISSUE TITLE
Technical Evidence - Artifacts

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#70]
- [ ] System Design Guides
- [ ] Standard Operating Procedures (SOPs)
- [x] System Administration Guides
- [ ] User Guides
- [ ] Baseline Configuration Guides
- [ ] Configuration Management Documents (Most recent change processed through the CCB. This evidence should be in the form of a formal request, analysis and security review, approval, testing, and implementation.).
- [ ] Documents detailing role matrices and/or admin user list
- [ ] Documents detailing Audit Review, Analysis, and Reporting (e.g. email, ServiceNow) and demonstrating that key personnel are engaged.
- [ ] Evidence, as applicable, of any incident support/incident ticket histories (from ServiceNow or similar internal or contractor system).

**Comment by AlexisCommarota** [comment]
"Documents detailing role matrices and/or admin user list" - this is part of the System Design Guide.

**Comment by segarnette** [comment]
CKAN Guides
Administration Guide (http://docs.ckan.org/en/ckan-1.7.4/)
User Guide (http://docs.ckan.org/en/latest/user-guide.html)
Maintainer’s Guide (http://docs.ckan.org/en/latest/maintaining/index.html)

**Comment by segarnette** [comment]
Ansible Documentation (http://docs.ansible.com/ansible/index.html)

**Comment by segarnette** [comment]
Kibana Documentation User Guide (https://www.elastic.co/guide/en/kibana/current/index.html)

**Comment by segarnette** [comment]
NGINX Administration Guides 
https://www.nginx.com/resources/admin-guide/

**Comment by segarnette** [comment]
Elasticsearch
Installation and Upgrade Guide [5.1] — other versions (https://www.elastic.co/guide/en/elastic-stack/current/index.html)
Elasticsearch Reference [5.1] — other versions (https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html)
Elasticsearch - The Definitive Guide [2.x] — other versions (https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html)
Elasticsearch Resiliency Status (https://www.elastic.co/guide/en/elasticsearch/resiliency/current/index.html)
Plugins and Integrations [5.1] — other versions (https://www.elastic.co/guide/en/elasticsearch/plugins/current/index.html)
Elasticsearch Clients (https://www.elastic.co/guide/en/elasticsearch/client/index.html)
Elasticsearch for Apache Hadoop and Spark [5.1] — other versions (https://www.elastic.co/guide/en/elasticsearch/hadoop/current/index.html)
Curator Index Management [4.2] — other versions (https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html)

**Comment by segarnette** [comment]
Capistrano
Installation (http://capistranorb.com/documentation/getting-started/installation/)
Configuration (http://capistranorb.com/documentation/getting-started/configuration/)
Preparing Your Application (http://capistranorb.com/documentation/getting-started/preparing-your-application/)
Authentication & Authorisation (http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/)

**Comment by segarnette** [comment]
Apache
https://httpd.apache.org/docs/

**Comment by segarnette** [comment]
Fluentd
Installation (http://docs.fluentd.org/v0.12/categories/installation)
Configuration File (http://docs.fluentd.org/articles/config-file)
Logging of Fluentd (http://docs.fluentd.org/articles/logging#)
Monitoring Fluentd (http://docs.fluentd.org/articles/monitoring)
Forwarding Data Over SSL (http://docs.fluentd.org/articles/forwarding-over-ssl)

**Comment by segarnette** [comment]
Redis
https://redis.io/documentation

**Comment by hkdctol** [comment]
Closing old issue from completed audit.
