### ISSUE TITLE
Upgrade ansible-lint to 4.x

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#701]
We're currently running ansible-lint 3.4.x. There are improved checks in 4.x but upgrading requires fixing or excluding some linting issues.

If necessary, add a `.ansible-lint` to exclude any files instead of specifying rules in `Makefile` on the command line.

**Comment by nickumia-reisys** [comment]
No more Ansible,
- https://github.com/GSA/data.gov/issues/3710
