### ISSUE TITLE
Accessing Login Page on Shibboleth

### ISSUE THREAD

**Issue by eric-asongwed** [GSA/data.gov#71]
We have installed and configured an IDP and a SP server.  However, we are not able to access the metdata.xml file from the idp server, which may be preventing us from accessing the login page.  We are close to getting this going, the inability to access the metadata.xml file has halted the process.

**Comment by neilhunt1** [comment]
@eric-asongwed closing this ticket as duplicate, I added your comment to #40 since that's the one we've been using to track it.
