### ISSUE TITLE
Ubuntu Bionic rollout for inventory-web host(s)

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#717]
## User Story
As an operator, I need new Ubuntu Bionic hosts provisioned in all of our environments so that I can continue receiving security updates automatically from Ubuntu.

Part of https://github.com/GSA/datagov-deploy/issues/571

Ubuntu 14.04 support ends [April 2019](https://www.ubuntu.com/about/release-cycle). We should move to Ubuntu 16.04 or 18.04. The latest 18.04 is preferred, but we should consider what kind of support exists for it.

## Details
Hosts are provisioned in these environments and play books are successfully applied.
1. [x] bionic sandbox
1. [x] staging
1. [ ] production

## Acceptance Criteria
- [ ] Bionic hosts are provisioned and operating correctly
- [x] Bionic hosts reporting to our monitoring systems
- [ ] Old Trusty hosts are decommissioned and removed from Ansible inventory

**Comment by adborden** [comment]
Waiting on staging hosts.

**Comment by adborden** [comment]
In staging, new hosts are on and operating correctly. I was not able to test datapusher, due to https://github.com/GSA/datagov-deploy/issues/748 but I believe this is a staging issue. Will continue to production.

**Comment by adborden** [comment]
Production hosts are rolled out and added to the load balancer but we're seeing Uptrends alerts, so apache2 is currently stopped.

**Comment by mogul** [comment]
This issue's blocked until we resolve the hang we're seeing.

**Comment by mogul** [comment]
@FuhuXia when you're back: Can we put some time on the calendar to work on this one?

**Comment by mogul** [comment]
https://github.com/gsa/datagov-deploy/issues/1068 is the specific problem to be resolved to unblock this.

**Comment by adborden** [comment]
@FuhuXia and I rolled bionic out to staging.

    $ ansible-playbook inventory.yml --limit inventory-web-v2 -e '{"datagov_in_service": true}'
    $ ansible-playbook inventory.yml --limit inventory-web-v1 -e '{"datagov_in_service": false}'

Hosts seem to be working correctly, but the service url https://inventory-datagov.dev-ocsit.bsp.gsa.gov is returning a 503. It looks like the bionic hosts were removed from the load balancer since they are responding with 200 locally. We'll check with BSP tomorrow.

**Comment by mogul** [comment]
Blocked on request pending with FCS/BSP

**Comment by adborden** [comment]
BSP resolved the issue with the load balancer and things are looking good. I'm going to continue with the rollout to production.

**Comment by adborden** [comment]
No, my understanding is that this is still blocked on https://github.com/GSA/datagov-deploy/issues/1375

**Comment by mogul** [comment]
Now that we're [removed the urgency to get off of 14.04](https://github.com/gsa/datagov-deploy/issues/571#issuecomment-648988887), we're planning to do the Bionic upgrade in the course of migrating to cloud.gov, rather than rolling our Ansible-managed hosts in FCS. So, closing this issue!
