### ISSUE TITLE
Ubuntu bionic rollout to catalog-web host(s)

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#719]
## User Story
As an operator, I need new Ubuntu Bionic hosts provisioned in all of our environments so that I can continue receiving security updates automatically from Ubuntu.

Part of https://github.com/GSA/datagov-deploy/issues/571

Ubuntu 14.04 support ends [April 2019](https://www.ubuntu.com/about/release-cycle). We should move to Ubuntu 16.04 or 18.04. The latest 18.04 is preferred, but we should consider what kind of support exists for it.

## Details
Hosts are provisioned in these environments and play books are successfully applied.
- [x] bionic sandbox
- [ ] staging
- [ ] production

## Acceptance Criteria
- [ ] Bionic hosts are provisioned and operating correctly
- [ ] Bionic hosts reporting to our monitoring systems
- [ ] Old Trusty hosts are decommissioned and removed from Ansible inventory

**Comment by adborden** [comment]
There's an issue with [M2Crypto](https://github.com/GSA/datagov-deploy/issues/758) a dependency for pysaml2/ckanext-saml2 that is blocking this upgrade.

**Comment by adborden** [comment]
Getting this error in staging and sandbox:

From the host `curl -v -L -k localhost`. In `/var/log/ckan/ckan.error.log`:
```
[Sat Sep 28 16:19:41.522516 2019] [wsgi:error] [pid 19193:tid 139843254347520] [client 10.0.102.139:41506] Truncated or oversized response headers received from daemon process 'ckan': /etc/ckan/apache.wsgi
```

I bumped up [WSGIDaemonProcess](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html#wsgidaemonprocess)'s header-buffer-size (to 32M) and response-buffer-size (to 64M) hoping to see more details about the response, but still get the same behavior.

**Comment by adborden** [comment]
The above error is caused by https://github.com/GSA/datagov-deploy/issues/1375. The work around is to downgrade to pycsopg2 2.7.x.

Currently, I'm able to deploy catalog-web successfully https://catalog.bionic.datagov.us/

**Comment by adborden** [comment]
I've also checked that pycsw is working https://catalog.bionic.datagov.us/csw

**Comment by adborden** [comment]
Looks like we're not the only ones running into mod-wsgi problems https://github.com/ckan/ckan/issues/5430

**Comment by mogul** [comment]
Now that we're [removed the urgency to get off of 14.04](https://github.com/gsa/datagov-deploy/issues/571#issuecomment-648988887), we're planning to do the Bionic upgrade in the course of migrating to cloud.gov, rather than rolling our Ansible-managed hosts in FCS. So, closing this issue!
