### ISSUE TITLE
Ubuntu Bionic rollout to catalog-harvester hosts

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#720]
## User Story
As an operator, I need new Ubuntu Bionic hosts provisioned in all of our environments so that I can continue receiving security updates automatically from Ubuntu.

Part of https://github.com/GSA/datagov-deploy/issues/571

Ubuntu 14.04 support ends [April 2019](https://www.ubuntu.com/about/release-cycle). We should move to Ubuntu 16.04 or 18.04. The latest 18.04 is preferred, but we should consider what kind of support exists for it.

## Details
Hosts are provisioned in these environments and play books are successfully applied.
1. [x] bionic sandbox
1. [ ] staging
1. [ ] production

## Acceptance Criteria
- [ ] Bionic hosts are provisioned and operating correctly
- [ ] Bionic hosts reporting to our monitoring systems
- [ ] Old Trusty hosts are decommissioned and removed from Ansible inventory

**Comment by adborden** [comment]
I've verified that the harvester succesfully harvests GSA's data.json.

**Comment by mogul** [comment]
Now that we're [removed the urgency to get off of 14.04](https://github.com/gsa/datagov-deploy/issues/571#issuecomment-648988887), we're planning to do the Bionic upgrade in the course of migrating to cloud.gov, rather than rolling our Ansible-managed hosts in FCS. So, closing this issue!
