### ISSUE TITLE
Retire old domains

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#722]
We have a [number of domains](https://github.com/GSA/datagov-deploy/blob/develop/ansible/bin/production-sans.txt) that are just redirects. We can retire these domain names at some point.

**Comment by FuhuXia** [comment]
There is another GSA site runs scans to collect metrics on items such as accessibility. Here is [the list of data.gov subdomains](https://docs.google.com/spreadsheets/d/1bp7VoDwna2yxcDoOzXri4LpGrC8cetROGnZL_1AsOCI) findings in the scan result.

**Comment by jbrown-xentity** [comment]
Looks like all the ones that have `This site can't be reached` are deprecated, looks like on purpose (to me at least).
The others have bad redirects, those are all defined in DNS: https://github.com/18F/dns/blob/main/terraform/data.gov.tf
@hkdctol maybe you can take a look and mark what should be removed, and what should be changed (from Fuhu's spreadsheet above)...
