### ISSUE TITLE
Idempotence tests failing for CKAN roles (Inventory)

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#728]
## User Story
As a sysadmin, I want to make sure a playbook can be rerun without reimplementing changes already made, known as `idempotence` in ansible.

## Details
--> Action: 'idempotence'
ERROR: Idempotence test failed because of the following tasks:
* [ckan-inventory-app-trusty] => inventory : Create rollback code
* [ckan-inventory-app-bionic] => inventory : Create rollback code
* [ckan-inventory-app-trusty] => inventory : Symlink current dir with rollback code
* [ckan-inventory-app-bionic] => inventory : Symlink current dir with rollback code
* [ckan-inventory-app-bionic] => inventory : get code
* [ckan-inventory-app-trusty] => inventory : get code
* [ckan-inventory-app-bionic] => inventory : get code
* [ckan-inventory-app-trusty] => inventory : get code
* [ckan-inventory-app-bionic] => inventory : get code
* [ckan-inventory-app-trusty] => inventory : get code
* [ckan-inventory-app-bionic] => inventory : get code
* [ckan-inventory-app-trusty] => inventory : get code
* [ckan-inventory-app-bionic] => inventory : get code
* [ckan-inventory-app-trusty] => inventory : get code
* [ckan-inventory-app-bionic] => inventory : get code
* [ckan-inventory-app-trusty] => inventory : get code
* [ckan-inventory-app-bionic] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : install requirements
* [ckan-inventory-app-bionic] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : install requirements
* [ckan-inventory-app-bionic] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : install requirements
* [ckan-inventory-app-bionic] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : install requirements
* [ckan-inventory-app-bionic] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : run setup
* [ckan-inventory-app-bionic] => inventory : run setup
* [ckan-inventory-app-trusty] => inventory : run setup
* [ckan-inventory-app-bionic] => inventory : run setup
* [ckan-inventory-app-trusty] => inventory : run setup
* [ckan-inventory-app-bionic] => inventory : run setup
* [ckan-inventory-app-trusty] => inventory : run setup
* [ckan-inventory-app-bionic] => inventory : run setup
* [ckan-inventory-app-trusty] => inventory : run setup
* [ckan-inventory-app-bionic] => inventory : run setup
* [ckan-inventory-app-trusty] => inventory : run setup
* [ckan-inventory-app-bionic] => inventory : run setup
* [ckan-inventory-app-trusty] => inventory : Remove old datapusher code
* [ckan-inventory-app-bionic] => inventory : Remove old datapusher code
* [ckan-inventory-app-bionic] => inventory : get code
* [ckan-inventory-app-trusty] => inventory : get code
* [ckan-inventory-app-bionic] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : run setup
* [ckan-inventory-app-bionic] => inventory : run setup
* [ckan-inventory-app-trusty] => inventory : fix "/usr/lib/datapusher" permissions
* [ckan-inventory-app-bionic] => inventory : fix "/usr/lib/datapusher" permissions
* [ckan-inventory-app-bionic] => inventory : Configure production.ini
* [ckan-inventory-app-trusty] => inventory : Configure production.ini
* [ckan-inventory-app-bionic] => inventory : get code
* [ckan-inventory-app-trusty] => inventory : get code
* [ckan-inventory-app-bionic] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : install requirements
* [ckan-inventory-app-trusty] => inventory : run setup
* [ckan-inventory-app-bionic] => inventory : run setup
* [ckan-inventory-app-bionic] => inventory : add s3filestore to production.ini plugins
* [ckan-inventory-app-trusty] => inventory : add s3filestore to production.ini plugins
* [ckan-inventory-app-bionic] => inventory : copy datajson export map
* [ckan-inventory-app-trusty] => inventory : copy datajson export map
* [ckan-inventory-app-bionic] => inventory : Datapusher json content-type temp fix (content-type: application/json does not work now)
* [ckan-inventory-app-trusty] => inventory : Datapusher json content-type temp fix (content-type: application/json does not work now)
* [ckan-inventory-app-trusty] => inventory : Datapusher https to http temp fix (local https is unreachable now)
* [ckan-inventory-app-bionic] => inventory : Datapusher https to http temp fix (local https is unreachable now)
* [ckan-inventory-app-trusty] => inventory : Remove compiled web.pyc
* [ckan-inventory-app-bionic] => inventory : Remove compiled web.pyc
* [ckan-inventory-app-trusty] => inventory : Symlink current dir with new code
* [ckan-inventory-app-bionic] => inventory : Symlink current dir with new code

## Acceptance Criteria
- [ ] fix tasks so they complete idempotence tests

## Definition of Done
same as acceptance

re https://github.com/GSA/datagov-deploy/pull/723

**Comment by nickumia-reisys** [comment]
No more Ansible,
- https://github.com/GSA/data.gov/issues/3710

Our current deployment has different issues related to concurrency, but not idempotence.  The SSB terraform sometimes has this issue (but it's more of the user did something wrong, it's not a system issue.)
