### ISSUE TITLE
Idempotence tests failing for CKAN roles (Catalog)

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#729]
## User Story
As a sysadmin, I want to make sure a playbook can be rerun without reimplementing changes already made, known as `idempotence` in ansible.

## Details
ERROR: Idempotence test failed because of the following tasks:
* [ckan-catalog-app-bionic] => ckan-app : Create rollback code
* [ckan-catalog-app-trusty] => ckan-app : Create rollback code
* [ckan-catalog-app-trusty] => ckan-app : Symlink current dir with rollback code
* [ckan-catalog-app-bionic] => ckan-app : Symlink current dir with rollback code
* [ckan-catalog-app-bionic] => ckan-app : Remove new code
* [ckan-catalog-app-trusty] => ckan-app : Remove new code
* [ckan-catalog-app-bionic] => ckan-app : Install CKAN app
* [ckan-catalog-app-trusty] => ckan-app : Install CKAN app
* [ckan-catalog-app-trusty] => ckan-app : Fix permissions on ckan install dir
* [ckan-catalog-app-bionic] => ckan-app : Fix permissions on ckan install dir
* [ckan-catalog-app-bionic] => ckan-app : Symlink current dir with new code
* [ckan-catalog-app-trusty] => ckan-app : Symlink current dir with new code

## Acceptance Criteria
- [ ] fix tasks so they complete idempotence tests

## Definition of Done
same as acceptance

Re https://github.com/GSA/datagov-deploy/pull/723

**Comment by nickumia-reisys** [comment]
No more Ansible,
- https://github.com/GSA/data.gov/issues/3710

Our current deployment has different issues related to concurrency, but not idempotence.  The SSB terraform sometimes has this issue (but it's more of the user did something wrong, it's not a system issue.)
