### ISSUE TITLE
Idempotence tests failing for CKAN roles (PyCSW)

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#731]
## User Story
As a sysadmin, I want to make sure a playbook can be rerun without reimplementing changes already made, known as `idempotence` in ansible.

## Details
ERROR: Idempotence test failed because of the following tasks:
* [pycsw-trusty] => pycsw-app : run setup build for pycsw
* [pycsw-bionic] => pycsw-app : run setup build for pycsw
* [pycsw-trusty] => pycsw-app : run setup install for pycsw
* [pycsw-bionic] => pycsw-app : run setup install for pycsw

## Acceptance Criteria
- [ ] fix tasks so they complete idempotence tests

## Definition of Done
same as acceptance

re https://github.com/GSA/datagov-deploy/pull/723

**Comment by adborden** [comment]
This is now an external role.
