### ISSUE TITLE
Create CloudFront distributions for apps

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#739]
## User Story
As a user, I want Data.gov applications to be cached via CDN so that requests are fast.

## Acceptance Criteria
- [ ] Something

## Definition of Done
>the single statement you make upfront to determine what you need to be able to prove, to close the issue.

**Comment by nickumia-reisys** [comment]
Completed during our migration to Cloud.gov:
- https://github.com/GSA/data.gov/issues/3555
- https://github.com/GSA/data.gov/issues/3554
- https://github.com/GSA/data.gov/issues/3547
