### ISSUE TITLE
Catalog sitemap cron job has not run since August 2018

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#740]
Should be able to just re-enable the cron job.

**Comment by philipashlock** [comment]
If I follow the history of this correctly it was originally set up with:
`#0 5 * * * root ckan --plugin=ckanext-geodatagov geodatagov sitemap-to-s3 >> /var/log/sitemap-to-s3.log 2>&1` 

And is now set up with supervisor using:
`#0 5 * * * root supervisorctl start ckan-sitemap`

Which is this:
```
[program:ckan-sitemap]
command=ckan --plugin=ckanext-geodatagov geodatagov sitemap-to-s3
stdout_logfile=/var/log/ckan/sitemap.log
redirect_stderr=true
autostart=false
autorestart=false
```

This generates multiple sitemap files and a sitemap index file in s3 at https://filestore.data.gov/gsa/catalog/sitemap/sitemap.xml 

Then it looks like we also need to add that URL back to the robots.txt file at http://catalog.data.gov/robots.txt per the [specification](https://developers.google.com/search/reference/robots_txt#sitemap)

**Comment by adborden** [comment]
This did not complete successfully in staging because [s3 is not configured correctly](https://github.com/GSA/datagov-deploy/issues/742).

In production, the job took about 2 hours and completed successfully.
