### ISSUE TITLE
Configure S3 for catalog staging

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#742]
## User Story
As a developer, I need staging setup with an s3 bucket so that I can test maintenance jobs in staging and have confidence they will work in production.

## Details
Production catalog has s3 buckets configured for various items. These buckets don't exist in staging.

## Acceptance Criteria
- [ ] S3 buckets are created in BSP
- [ ] S3 buckets and credentials are added to inventory vault

## Definition of Done
> I can run maintenance jobs in staging to completion providing test parity between production and staging.

**Comment by adborden** [comment]
This also has a side effect of filling up the `/` disk on catalog-harvester2d. We just had a disk alarm from New Relic. To resolve, run this from catalog-harvester2d:

    $ sudo rm -rf /tmp/s3sitemap/*

**Comment by adborden** [comment]
catalog-harvester2d alarming with no space left on `/`, again. Cleared.

**Comment by adborden** [comment]
catalog-harvester2d alarming with no space left on /, again. Cleared.

**Comment by jbrown-xentity** [comment]
catalog-harvester2d alarming with no space left on /, again. Mitigation performed.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710

P.S. catalog on cloud.gov has S3.
