### ISSUE TITLE
Automatically purge AWS resources in sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#744]
## User Story
As an operator, I want to automatically purge AWS resources in sandbox on a regular basis so that unused or abandoned resources are cleaned up and our AWS costs low.

## Details
@JJediny suggested https://github.com/servian/aws-auto-cleanup

## Acceptance Criteria
- [ ] automatic cleanup is scheduled for every 14 days (at the start of the sprint)

## Definition of Done
> Unused sandbox resources are removed automatically, reducing cost in our monthly AWS invoice.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
