### ISSUE TITLE
Ensure our embedded schema.org structured data is being indexed properly

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#745]
Making sure our embedded schema.org structured data is being indexed properly to power Google Datasets search and other uses.

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by jbrown-xentity** [comment]
This seems to be working as expected: https://datasetsearch.research.google.com/search?src=2&query=U.S.%20Hourly%20Precipitation%20Data&docid=L2cvMTF0eTd0eDNiNg%3D%3D, closing.
