### ISSUE TITLE
Add redirects from Project Open Data to new resources site

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#749]
## User Story
As a project open data user, I need pages at https://project-open-data.cio.gov to redirect to the new Data.gov Resources site so that my bookmarks and links still work.

## Details

_TODO: list out individual urls that need to redirect to special locations._

All urls not mentioned above should be redirected to the Resources home page.

## Acceptance Criteria
- [ ] _TODO_

## Definition of Done
> _TODO_

**Comment by adborden** [comment]
@philipashlock do you want to add some specifics here?

**Comment by hkdctol** [comment]
Closing this as it's been incorporated and completed in resources.data.gov work.
