### ISSUE TITLE
Catalog sitemap cron job is not running daily

### ISSUE THREAD

**Issue by philipashlock** [GSA/data.gov#766]
Based on the fixes that were made with #743 based on #740 the sitemap.xml files should be generated every morning at 5am (`0 5 * * * root supervisorctl start ckan-sitemap`) but they have not been updated for about two weeks. 

## How to reproduce

The lastmod dates in the current sitemap.xml are 2019-04-15 https://filestore.data.gov/gsa/catalog/sitemap/sitemap.xml

## Expected behavior

The lastmod dates in the sitemap.xml should update daily

**Comment by adborden** [comment]
Thanks for following up on this. I'll take a look at these issues.

--
Aaron D Borden
Human and hacker

**Comment by adborden** [comment]
The job is running, but getting a permission denied when writing to S3. This is the same host where the job was run manually, so I'm not sure what's going on here.

```
3544001 to 3544164 of 3544164 records done.
done with /tmp/s3sitemap/sitemap-71-GNrqRS.xml.
Traceback (most recent call last):
  File "/usr/bin/ckan", line 45, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan-new/src/ckanext-geodatagov/ckanext/geodatagov/commands.py", line 118, in command
    self.sitemap_to_s3()
  File "/usr/lib/ckan-new/src/ckanext-geodatagov/ckanext/geodatagov/commands.py", line 1097, in sitemap_to_s3
    bucket = get_s3_bucket(bucket_name)
  File "/usr/lib/ckan-new/src/ckanext-geodatagov/ckanext/geodatagov/commands.py", line 1326, in get_s3_bucket
    format(bucket_name))
Exception: Access to bucket bsp-ocsit-prod-east-data-site-filestore denied
```

@JJediny I'm not seeing any aws credentials in the inventory... are we using iam roles to push to s3?

**Comment by JJediny** [comment]
@adborden yes all AWS auth is handled by on-host IAM roles

**Comment by adborden** [comment]
OK, I found `/root/.aws/credentials`, so these are probably invalid and overriding the IAM role credentials. That would explain why the job works when run with sudo (ubuntu) but not via cron (root).

Glad that with the bionic upgrade we will get rid of these weird inconsistencies.

**Comment by adborden** [comment]
This looks like it's working correctly now.
```
$ curl -X HEAD https://filestore.data.gov/gsa/catalog/sitemap/sitemap.xml -v 2>&1 | grep -i last-modified
< Last-Modified: Mon, 06 May 2019 08:49:03 GMT
```
