### ISSUE TITLE
Catalog sitemap.xml loc URLs are incorrect

### ISSUE THREAD

**Issue by philipashlock** [GSA/data.gov#767]
The `loc` URLs are incorrect in the sitemap files, they're missing the `dataset` portion of the full URL.

## How to reproduce

Look at the sitemap.xml files. The first one is https://filestore.data.gov/gsa/catalog/sitemap/sitemap-1.xml

Which starts off as: 
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://catalog.data.gov/usgs-lidar-point-cloud-ky-nrcs-watersheds-2011-16-05284174-las-2016</loc>
        <lastmod>2016-09-14</lastmod>
    </url>
    <url>
        <loc>https://catalog.data.gov/usgs-lidar-point-cloud-va-sandy-2014-17sqb3835-las-2015</loc>
        <lastmod>2015-12-02</lastmod>
    </url>
```

## Expected behavior

The URLs are missing the `dataset` portion of the URL:

This:
`https://catalog.data.gov/usgs-lidar-point-cloud-ky-nrcs-watersheds-2011-16-05284174-las-2016` 

Should instead be:
`https://catalog.data.gov/dataset/usgs-lidar-point-cloud-ky-nrcs-watersheds-2011-16-05284174-las-2016`

**Comment by adborden** [comment]
This has been deployed to production and the sitemap appears fixed.
