### ISSUE TITLE
Test multi-branch approach

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#77]
Allow different branches, resources, and state to be maintained.

1. Ensure information sharing between stacks works properly
2. Ensure works with multiple branches
3. Simple to setup using Jenkins Multi-branch Pipeline projects

**Comment by robproper** [comment]
Completed, merged to master

**Comment by neilhunt1** [comment]
Rob, only thing here is that we have Jenkinsfile at the root of the repository. Since we would likely have multiple pipelines, we'll either need to separate some code out into different repos or figure out a different approach. It's a minor thing at this time, but worth noting here. Still keeping issue closed, overall it's in great shape with the tag/name branch convention you've setup.
