### ISSUE TITLE
Configure MySQL app databases in sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#779]
## User Story
As a developer, I want MySQL application databases configured in sandbox environments from the ansible playbooks so that I can fully test the MySQL-based applications in sandbox.

## Acceptance Criteria
- [ ] Playbooks create the application databases in RDS using the [datagov-deploy-mysql](https://github.com/GSA/datagov-deploy-mysql) role

## Definition of Done
> Developers can provision machines in sandbox with terraform, the provision them with the ansible playbooks in order to have a working test environment.

**Comment by nickumia-reisys** [comment]
No more FCS sandbox and ansible.
- https://github.com/GSA/data.gov/issues/3710
