### ISSUE TITLE
Demonstrate multiple stack layers

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#78]
Create two stacks, one with simple infrastructure such as VPC's, subnets, security groups; another with application-specific resources such as EC2 instances, S3 buckets, RDS, ElastiCache, etc.
This should demonstrate the ability to separate different resources within an application's spectrum and can support "separation of duties" (e.g. Sec owns security groups, dev team owns it's own databases, ops team owns common S3 buckets, etc.).

**Comment by robproper** [comment]
In progress, but need to share output from infrastructure to pilot stack (automatically)
