### ISSUE TITLE
Wordpress cache is too aggressive

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#782]
Updates to Wordpress take ~24 hours to appear on the website. This requires editors to ping the data.gov team to purge the cache when this should be a 100% self-serve service.

## How to reproduce

1. Update content on wordpress

## Expected behavior

Content is published immediately

## Actual behavior

Content is available from wp-bsp.data.gov but the cache is still serving stale content.

**Comment by hkdctol** [comment]
Closing as we've left wordpress
