### ISSUE TITLE
Should "How to get your open data on data.gov" live on data.gov?

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#783]
Should this content live on data.gov? Does it need to be updated for the recent Open Data and Geospatial laws?

https://digital.gov/resources/how-to-get-your-open-data-on-data-gov/

**Comment by adborden** [comment]
@hkdctol I believe this work was completed?

**Comment by hkdctol** [comment]
Yes, there was a separate ticket that was closed as well. Closing this one.
