### ISSUE TITLE
Trigger App/OS updates using Ansible

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#79]
Ensure that Ansible scripts can be executed on remote machines directly from Jenkins and propose secure method of doing so.
On Jenkins, what I need are

- Ansible EC2 inventory scripts (ec2.py, ec2.ini)
- Ansible itself
- Ansible environment variables
- Git
- Correct IAM role (power user-ish)

**Comment by robproper** [comment]
- Possible approaches for Ansible playbook orchestration:
    1. Use a terraform script with [terraform provisioners](https://www.terraform.io/docs/provisioners/index.html) to make the ansible playbook calls
    2. Use a bash script to make the ansible playbook calls

- Configuration of playbook orchestration script:
    1. Use output from a terraform stack to discover the hostname/ips of the servers to provision
    2. Use AWS CLI to discover hostname/ip of servers to provision

- Call playbook orchestration script from Jenkins pipeline. 
   A pipeline would group provisioning of servers of one system component (i.e. servers that would change together)

**Comment by neilhunt1** [comment]
I'll be working on this next week

**Comment by neilhunt1** [comment]
@JJediny Trying to get [built-in Ansible Jenkins plugin](https://github.com/jenkinsci/ansible-plugin#pipeline-support) to work in pipeline. Dynamic inventory is working fine outside of this, but it needs to be part of Jenkins pipeline. If the plugin doesn't work for some reason, we will need to take a different approach with raw ansible setup on Jenkins slaves as originally intended (I went down this path a bit already today, but it has its own challenges)

**Comment by JJediny** [comment]
See @10:00 https://skillsmatter.com/skillscasts/7630-terraform-to-build-infrastructure-in-aws

https://github.com/madetech/terransible-jenkins

Putting the ansible dynamic inventory script with encrypted token/key on the Jenkins master makes the host tags available to Jenkins slaves
