### ISSUE TITLE
Docker Compose based development environment for wordpress app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#792]
## User Story
As a developer, I need a Docker Compose based workflow to develop and test the wordpress application so that I can quickly and easily bump dependencies and fix security issues while being forward compatible with Docker.

## Acceptance Criteria
- [x] Docker Compose based workflow exists
- [ ] CI runs a simple check via Docker Compose

## Definition of Done
> I can use Docker Compose to bring up a development instance for local development.

**Comment by hkdctol** [comment]
Closing as we've left wordpress
