### ISSUE TITLE
Docker Compose based development environment for project open data dashboard app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#793]
## User Story
As a developer, I need a Docker Compose based workflow to develop and test the dashboard application so that I can quickly and easily bump dependencies and fix security issues while being forward compatible with Docker.

## Acceptance Criteria
- [x] Docker Compose based workflow exists
- [x] CI runs a simple check via Docker Compose

## Definition of Done
> I can use Docker Compose to bring up a development instance for local development.

**Comment by mogul** [comment]
@adborden [this is done now](https://github.com/GSA/project-open-data-dashboard#development), right?

**Comment by adborden** [comment]
:+1: acceptance criteria looks met.
