### ISSUE TITLE
Establish notification methods from Jenkins pipelines

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#80]
How and when will people be alerted? Will Jenkins have mail server access? Should we notify through other tools that are already in use? Would we want to use something like SES?

**Comment by robproper** [comment]
Embed notification into the Jenkins pipeline. This could use:
- Direct email
- AWS SNS
- A messaging platform, such as HipChat

The best approach does not embed individuals but uses a kind of grouping (SNS Topic, Email distribution list, specific HipChat room), such that users can be added or removed from notification without changing the Pipeline. Furthermore, SNS allows for unsubscribing from topics. Also, can send messages to email and/or text (SMS) and other messaging (HTTP/S, Lambda)
