### ISSUE TITLE
NOAA harvest issue

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#802]
NOAA CSW harvest fails. One issue is that it is fetching only 10 datasets at a time, hardcoded in ckanext-spatial.

## Repro steps

1. Kick off a harvest for NOAA

## Expected
Harvester completes successfully

## Actual
Harvester errors after fetching a few datasets in the fetch stage. _TODO: can we get a specific stack trace or error log?_

**Comment by adborden** [comment]
I implemented a change to ckanext-spatial that allows for the CSW page fetch size to be changed via CKAN config. The idea is that fetching only 10 at a time increases the chance of a network issue and is generally too small a batch size. Further work to make the requests more robust is needed.

**Comment by mogul** [comment]
We're obsoleting this issue by [migrating the harvest over to WAFs](https://github.com/GSA/datagov-deploy/issues/1419).
