### ISSUE TITLE
Move supervisor services to systemd

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#805]
## User Story

As an operator, I want all the supervisor jobs/services running as systemd jobs/services so that I get the features of systemd, including failure notifications and resource limits.

## Details

An advantage to moving to Ubuntu Bionic is that we get systemd. We should update the supervisor jobs to take advantage of this.

## Acceptance Criteria

- [ ] Supervisor jobs are move to systemd
- [ ] Where appropriate, job failures send a notification to datagovhelp@
- [ ] Supervisor is uninstalled from all hosts

## Definition of Done
> Data.gov jobs and services run under systemd just like OS level jobs and services.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
