### ISSUE TITLE
Trigger network infrastructure pipeline from Jenkins

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#82]
Address issues and demonstrate ability to setup infrastructure using Jenkins Pipeline and understand how it relates to Resources and Ansible pipelines.

**Comment by robproper** [comment]
Use outcome of #78 and #79 to have orchestrate creation of different stacks called from Jenkins. 

Stacks can be created in in a single pipeline or multiple pipelines. Multiple pipelines (likely) requires separate repositories for separate stacks (or else use a parameterized pipeline to enable naming the stack to create in the pipeline job (if using a single repository).
