### ISSUE TITLE
Items from self-assessment

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#823]
https://docs.google.com/spreadsheets/d/1MRYlKn5IctNIB42Oq-E7LmIkbdU3fNg4Fo8KP7o1AWQ/edit#gid=1062608910

**Comment by hkdctol** [comment]
Here is the link to the drive where to put the artifacts:

https://drive.google.com/drive/folders/1lwsx0VU2J5DvXjkPvWA5kguQH4-Bpjiv?usp=sharing

**Comment by adborden** [comment]
@jjediny opened some tickets with BSP for a few of the items.

Still need to check session timeouts in the PHP applications. Check the settings and link to the code.

**Comment by adborden** [comment]
Wanted to get all the evidence by Tuesday July 9th.
