### ISSUE TITLE
Delete and import VA datasets into Inventory

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#824]

**Comment by adborden** [comment]
The VA datasets have been archived https://drive.google.com/file/d/1-MFglC3_OpnndFZPD1SQ1PZ2RkKQlzT0/view

**Comment by hkdctol** [comment]
Looks like current data.json for VA was successfully imported into inventory, but the current listing in catalog.data.gov of their current source is wrong. Is the harvest working correctly?

**Comment by adborden** [comment]
I'll dig into this a bit. There are 3784 datasets in there data.json. Currently catalog is listing ~1600 datasets, and the harvest sources lists ~4k https://catalog.data.gov/harvest/about/va-json

I will dig into this a bit. One option is to clear the harvest source.

**Comment by JJediny** [comment]
This was the report after we switched the url to `https://www.data.va.gov/data.json`
```
Job: a1de79c9-f4bb-440e-bbcb-d27e433a999a
Started: June 3, 2019, 16:59 GMT — Finished: June 3, 2019, 17:14 GMT

503 added  27 updated  4 deleted
```

**Comment by hkdctol** [comment]
Yes, just noted that that harvest job ran after switching source, and there are new datasets in catalog from it: https://catalog.data.gov/dataset/gravesite-locations-of-veterans-and-beneficiaries-in-california-as-of-may-2019
just not sure about the numbers compared to https://www.data.va.gov/search/type/dataset

**Comment by JJediny** [comment]
I performed a complete clear/purge/re-harvest overnight. My guess is this is related to https://github.com/GSA/datagov-deploy/issues/601 - re the strength of the unique identifier checking in our fork of harvester/datajson ckan ext. We had the same issue with DOI when we switched metadata sources/endpoints. Half - ~1/4 were detected as matching an old dataset and updated/deleted, the other half - ~3/4 we're retained as was and neither updated/deleted. The purge/reharvest worked.

<img width="999" alt="Screen Shot 2019-07-02 at 9 34 41 AM" src="https://user-images.githubusercontent.com/6350035/60517298-6c31f780-9cad-11e9-8ef3-d5fa2c428a8f.png">

**Comment by adborden** [comment]
@JJediny let us know when the db_solr_sync job completes. I believe we are all set here, as the numbers are pretty close.

Total datasets in data.json matches what the [harvester reports](https://catalog.data.gov/harvest/va-json) (3784).
```
$ jq -r '.dataset | length' data.json
3784
```

Total datasets (sans collection members) match the count listed for [VA](https://catalog.data.gov/organization/ff9ae098-eccc-41d8-bfcd-5e8ed047db05?dataset_type=dataset) (1527)
```
$ jq -r '.dataset[].isPartOf' data.json | grep null | wc -l
    1513
```

**Comment by adborden** [comment]
Get the count of the datasets for VA including the collection members and explain why despite the number in the view looking incorrect, all datasets are available on data.gov.

**Comment by adborden** [comment]
We have an exact match.

Currently, the data.json file has **3793** datasets:
```
$ curl -L https://www.data.va.gov/data.json | jq '.dataset | length'
3793
```

Collection members:
```
$ curl 'https://catalog.data.gov/api/action/package_search?fq=organization:va-gov+collection_package_id:*+type:dataset' | jq '.result.count'
2266
```

Non-collection members:
```
$ curl -v 'https://catalog.data.gov/api/action/package_search?fq=organization:va-gov+type:dataset' | jq '.result.count'
1527
```

Total: **3793** = 2266 + 1527
