### ISSUE TITLE
Propose strategy for verifying stack compliance

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#83]
Consider automated testing for stack setup.

1. What do we want to test and why?
2. How do we integrate this within a pipeline?

Look at
https://github.com/stelligent/serverspec-aws-resources
http://docs.aws.amazon.com/cli/latest/reference/configservice/describe-compliance-by-resource.html

**Comment by robproper** [comment]
Other options to test state of resources are:

1. [AWS Config](http://docs.aws.amazon.com/cli/latest/reference/configservice/index.html)
2. [AWS-CLI](http://docs.aws.amazon.com/cli/latest/reference/index.html#cli-aws) using ec2, s3, etc. sub-commands.
