### ISSUE TITLE
Information architecture for resources.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#831]
## Details
Reviewing IA layout from Mike, adding a few additional resources that are missing.

Put out for review from partners.

## Acceptance Criteria
- [ ] Something

## Definition of Done
>the single statement you make upfront to determine what you need to be able to prove, to close the issue.

**Comment by adborden** [comment]
I think we can close this, I'm not sure there's any work to do here. I think the 10x folks will be working on this.

**Comment by hkdctol** [comment]
I think we can close this considering 10X work that's been done. They are awaiting go-ahead from OMB before launching a new version of resources.data.gov.
