### ISSUE TITLE
CKAN database gets out of sync with Solr

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#840]
I'm not familiar with the history of this issue, but we've developed `db_solr_sync` as a means to repair the situation. Historically, this has been the approach to dealing with this issue. I'm documenting this here so in hopes to understand the cause and determine if a fix is still necessary (maybe it's fixed in recent CKAN versions).

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by adborden** [comment]
Or, if you know the `name` of the dataset, you can update solr immediately:
```
ckan search-index rebuild networx-business-volume-fy2019-2nd-qtr
```

**Comment by adborden** [comment]
Recently saw this with the [ioos](https://catalog.data.gov/harvest/ioos) and [coris-fgdc-metadata](https://catalog.data.gov/harvest/coris-fgdc-metadata).

The dataset page loads, but package_show and harvest_source_show both result in a 500.
https://catalog.data.gov/api/3/action/harvest_source_show?name_or_id=coris-fgdc-metadata
https://catalog.data.gov/api/3/action/harvest_source_show?name_or_id=ioos

https://catalog.data.gov/api/3/action/package_show?name_or_id=coris-fgdc-metadata
https://catalog.data.gov/api/3/action/package_show?name_or_id=ioos

**Comment by chris-macdermaid** [comment]
Additionally the USGS Ortho Collection is out of sync.  Ortho shows 353,284 datasets in Solr and 0 in the database. 

https://admin-catalog.data.gov/harvest/usgs-high-resolution-orthoimagery-collection
![Screenshot from 2020-12-30 09-41-00](https://user-images.githubusercontent.com/64213093/103372604-a8efd200-4a8f-11eb-8fde-7468abecb3b2.png)

**Comment by nickumia-reisys** [comment]
We have a `db-solr-sync` script.  Still not sure of the origins, but this issue is fixed,
- https://github.com/GSA/data.gov/issues/3985
