### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by crysacarter** [GSA/data.gov#842]
There are links on the data.gov/climate landing page that are not accessible and broken. These were the hyperlinks for "Food Resilience", "Ecosystem Vulnerability", and "Human Health" within the first paragraph on that page.

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by adborden** [comment]
@crysacarter you should be able to login to [data.gov](https://www.data.gov/wp/wp-login.php) and edit this page. Ping me on slack if you need a hand.

**Comment by crysacarter** [comment]
correct links added - closed
