### ISSUE TITLE
Setup fluentd for all logs

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#86]
[system]
- [x] /var/log/auth.log
- [x] /var/log/syslog
- [x] /var/log/td-agent/td-agent.log

[catalog-web]
- [x] /var/log/apache2/ckan.error.log
- [x] /var/log/apache2/ckan.custom.log

[inventory-web]
- [x] /var/log/apache2/ckan.error.log
- [x] /var/log/apache2/ckan.custom.log
- [x] /var/log/apache2/datapusher.error.log
- [x] /var/log/apache2/datapusher.custom.log

[solr] 
- [x] /var/log/tomcat6/catalina.out

[crm-web]
- [x] /var/log/nginx/error.log
- [x] /var/log/nginx/access.log

[wordpress-web]
- [x] /var/log/nginx/error.log
- [x] /var/log/nginx/access.log
- [x] /var/log/wp-cron.log
 
[dashboard]
- [x] /var/log/nginx/error.log
- [x] /var/log/nginx/access.log
- [x] /var/log/dashboard-cron.log
- [x] /var/log/dashboard-cron-cfo.log

[jekyll-web]
- [x] /var/log/data-federation/jekyll-rebuilder.log
- [x] /var/log/sdg-indicators/jekyll-rebuilder.log
- [x] /var/log/jekyll-sdg-indicators.log
- [x] /var/log/jekyll-data-federation.log
- [x] /var/log/apache2/access.log
- [x] /var/log/apache2/error.log 

[catalog-harvester]
- [x] /var/log/supervisord.log
- [x] /var/log/harvester_run.log
- [x] /var/log/fetch-consumer.log
- [x] /var/log/gather-consumer.log
- [x] /var/log/tomcat6/catalina.out
- [x] /var/log/clean_deleted.log
- [x] /var/log/ckan_tracking.log
- [x] /var/log/ckan_report.log
- [x] /var/log/db_solr_sync.log
- [x] /var/log/harvest_job_cleanup.log
- [x] /var/log/ckan-combine-feeds.log
- [x] /var/log/ckan-export-csv.log
- [x] /var/log/ckan_qa.log
- [x] /var/log/qa-update.log
- [x] /var/log/pycsw_load.log
- [x] /var/log/pycsw_keywords.log
- [x] /var/log/pycsw_fts.log

**Comment by dano-reisys** [comment]
The format for `/var/log/dashboard-cron.log` source is set to `none`.
I am not entirely sure how to parse cron log.
@philipashlock @JJediny any insight on format of this log file?
We should be able to use multiline, but i need a better idea on what is being logged.
http://docs.fluentd.org/articles/in_tail#format-required

**Comment by dano-reisys** [comment]
@FuhuXia can you please move 
`/root/data-federation/jekyll-rebuilder.log`
`/root/sdg-indicators/jekyll-rebuilder.log`
to
`/var/log/data-federation/jekyll-rebuilder.log`
` /var/log/sdg-indicators/jekyll-rebuilder.log`
