### ISSUE TITLE
CKAN broken links report

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#861]

**Comment by adborden** [comment]
https://catalog.data.gov/report

**Comment by adborden** [comment]
Never seems to load, fails with a timeout.

**Comment by nickumia-reisys** [comment]
This technically has a similar issue on cloud.gov production.  But it does work, it just takes a pretty long time for CKAN to generate the report.  This is superseded by,
- https://github.com/GSA/data.gov/issues/4116

**Comment by nickumia-reisys** [comment]
Actually, it's more related to 
- https://github.com/GSA/data.gov/issues/3986
