### ISSUE TITLE
Setup Mgmt VPC with Bionic

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#864]
- [x] Provision new bionic jumpbox host
- [x] Remove trusty hosts
- [ ] Update Ansible mgmt inventory for common role variables
- [ ] Remove EFK related roles
- [ ] Apply site.yml to mgmt

**Comment by adborden** [comment]
BSP might be able to provide an Elasticsearch solution.

**Comment by adborden** [comment]
Created REQ0478801 to remove Trusty hosts.

**Comment by mogul** [comment]
We confirmed that mgmt now only contains the jumpbox host, which is already on Bionic.
