### ISSUE TITLE
Make the fgdc2iso service its own app

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#865]
## User Story
As a developer, I want fgdc2iso as its own application with releases so that as improvements and fixes are made, I can easily pull-in published releases to consume for app development and deployment. 

## Details
Buried in the [ckanext-geodata extension](https://github.com/GSA/ckanext-geodatagov/tree/master/conversiontool) is the fgdc2iso service that transforms the FGDC metadata format to ISO 19115-2. This service is essentially it's own application and should be deployed separately from its own repo.

## Acceptance Criteria
- [x] app lives in its own repo, maybe https://github.com/GSA/catalog-fgdc2iso
- [x] WAR files built from `main` are published automatically as releases in the GH repo (through GitHub Actions)
- [x] consumers are updated to pull a versioned release from GH (datagov-deploy, catalog-app, ...)

**Comment by mogul** [comment]
We're holding off on this one until the next occasion where we're updating the transformation file.

**Comment by chris-macdermaid** [comment]
Created issue [#2209](https://github.com/GSA/datagov-deploy/issues/2209) to handle "consumers are updated to pull a versioned release from GH (datagov-deploy, catalog-app, ...)" task in the ticket.

**Comment by chris-macdermaid** [comment]
The https://www.saxonica.com website has been down for a couple of days and is still down now. To build on a push to master, this web server needs to exist to get the saxon parser.

**Comment by chris-macdermaid** [comment]
The saxon web server is working again!
Cleaned up repo. Removed the translate app's files.
Added clean, all to makefile
Added github action to create a release on a push to master.
Added github secret for testing part of action
Updated README for catalog-fgdc2iso and catalog-app
