### ISSUE TITLE
[Research 1d] Explore how to handle metadata transforms in the ckanext-geodatagov extension

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#866]
## Details
The FGDC to ISO 19115-2 transform is handled by a Jython based Tomcat service ([catalog-fgdc2iso](https://github.com/GSA/catalog-fgdc2iso)) listening over local HTTP. The transform is done by XSLT 2.0 using a proprietary [Saxon Professional Edition](http://www.saxonica.com/products/PD9.9/PE.pdf) library and license.

## Acceptance Criteria
- [ ] Something

## Definition of Done
>the single statement you make upfront to determine what you need to be able to prove, to close the issue.

**Comment by adborden** [comment]
I haven't written the user story yet because I don't totally understand the user value here.

We're currently using the proprietary Java-based Saxon PE library to handle XSLT. If we were were to drop this dependency and go with an open source solution, we would be
- dropping the requirement for Tomcat and having a pure python solution
- removing a service that we have to deploy, support, and maintain

**Comment by adborden** [comment]
After a quick look into this, the existing XSLT is using XSLT 2.0. Saxon PE supports up to XSLT 3.0. [lxml](https://lxml.de/xpathxslt.html)/[libxslt](http://xmlsoft.org/XSLT/index.html) seems to only support 1.0, so lxml won't work here unless we can rewrite the XSLT in version 1.0 (or maybe it doesn't use any 2.0 features and is already 1.0 compatible)?

**Comment by adborden** [comment]
Moving to New for us to take another look in grooming cc @chris-macdermaid

**Comment by mogul** [comment]
The transform file we're relying on is using XSLT 2.0. It's not clear if it relies on any 2.0-specific features, or could be backported to XSLT 1.0. If it can be backported to XSLT 1.0, the set of XSLT options for Python opens up quite a lot. If not, then really the only game in town continues to be [libsaxon](https://www.saxonica.com/welcome/welcome.xml).

There is now a [Python3 binding for Saxon/C](https://www.saxonica.com/saxon-c/doc/html/saxonc.html), so we can drop the use of Java and Jython, instead embedding the transformation right into the fgdc2iso extension. The [license for Saxon-PE/C](https://www.saxonica.com/saxon-c/index.xml#license) sells for [~$83/instance/year](https://www.saxonica.com/shop/shop.html#!/Saxon-PE-Professional-Edition-ref-PE001/p/3667733/category=905991); presumably we need to buy licenses covering as many instances as we expect to be operating in production (and possibly staging). 

According to [our research on the path to Python3](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0): It's a large effort to get ckanext-geodatagov working with Python3. Furthermore, there are many other extensions in catalog.data.gov that would also have to be made to work with Python3 before we'd have a path to production for the Python3 binding. 

Another avenue: Figure out how to backport the Python3 binding (or at least the tiny subset that we'd use) to Python2. There is [precedent for doing that](http://matthewrocklin.com/blog/work/2018/11/28/python-2-and-cython). The Saxon/C documentation includes [instructions for compiling the Python3 binding](https://www.saxonica.com/saxon-c/documentation/index.html#!starting/installingpython), so there is an entrypoint to start from.

Here's [the code that calls fgdc2iso now](https://github.com/GSA/ckanext-geodatagov/blob/4dffc3626a13b85cd108fc40ca47a78cd016ea2d/ckanext/geodatagov/harvesters/base.py#L114), and [the Jython code that actually does the transform now](https://github.com/GSA/catalog-fgdc2iso/blob/df5c8e22fbaa22f52a7334481ee6bfb532c61d95/fgdc2iso/app.py#L41-L53). The only API we need from Saxon is instantiating an XSLT transform object, and then pointing it at the input and output file paths to do a transform. So if we can't port the whole binding rom Python3 to Python2 easily, we may get away with porting only a very small portion.

**Comment by mogul** [comment]
Saxon/C includes [CLI wrappers for invoking XSLT transformations](https://www.saxonica.com/saxon-c/documentation/index.html#!starting/running). 

We can skip all the drama and uncertainty around Python versions by just having the extension invoke the CLI binary at the appropriate time!

**Comment by mogul** [comment]
For simple XSL transforms, we don't need the additional features of the commercially-licensed versions of Saxon. [Saxon-HE can transform up through XSLT 3.0](https://www.saxonica.com/html/documentation/conformance/xslt30.html).  
> Saxon-HE implements the following features of the XSLT 3.0 specification

...

> Saxon (from release 9.8) acts as an XSLT 3.0 processor whether this is explicitly requested or not. Specifying version="1.0" or version="2.0" does not prevent the use of 3.0 features; rather it switches on "backwards compatibility mode" as defined in the XSLT 3.0 specification.

[Saxon-HE is MPL 2.0-licensed](https://www.saxonica.com/license/license.xml), so it runs without hassling over the presence of a license file.

We don't care about Saxon/C vs Saxon/Java if we don't embed the transformation in Python but rather call a CLI utility. [The Java version of Saxon can **also** be invoked from the command line](https://www.saxonica.com/html/documentation/using-xsl/commandline/), and without the hassle of building the command-line wrappers for Saxon/C. 

At this point I have high confidence that we can drop the fgdc2ido application and replace the HTTP request in the CKAN extension with an invocation of the CLI Saxon/Java version:
```bash
java net.sf.saxon.Transform -s:source -xsl:stylesheet -o:output
```

We can [install the java runtime](https://stackoverflow.com/a/49214154) using [the apt-buildpack](https://github.com/cloudfoundry/apt-buildpack), and also use it to [install Saxon-HE/Java from a PPA](https://launchpad.net/ubuntu/+source/libsaxon-java).

**Comment by mogul** [comment]
Follow up [issue for actually doing the work](https://github.com/GSA/datagov-deploy/issues/2917) created, marking this `Done` now.
