### ISSUE TITLE
As a Data.gov Employee I want an Onboarding/Offboarding guide and access to relevant Documents

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#867]
## User Story
As a new Data.gov team member, I want an Onboarding/Offboarding guide and access to relevant Documents so that I can get ramped up quickly and meet all required procedures for onboarding/offboarding.

## Acceptance Criteria
- [ ] [Onboarding/Offboarding Wiki](https://github.com/GSA/datagov-deploy/wiki/Onboarding-Offboarding)
  - [x] User/Accounts setup
  - [x] Geospatial introduction/context
  - [x] Project Open Data and Open Data Act history
  - [x] Ckan extensions and what happens where within CKAN general ie features/functionalities
  - [x] Who's who of agencies we interface with and their roles/responsibilities
  - [x] Access to https://github.com/gsa/datagov-incident-response https://github.com/gsa/datagov-account-management repo
  - [x] Review System Security Plan
  - [x] Current contact list for internal stakeholders/teams (e.g. Security-general/FCS-devops/Networking/DNS/Logging/Incident response/compliance/SaaS admin groups in slack or email)- who is familiar with the data.gov program.
  - [x] List of relevant slack channels and their purpose
  - [x] How to upload relevant documents shared during the course of employeement to the team's Google drive
  - [x] Basic guidelines on what should be moved and what need not be.

## Definition of Done
>wiki that cover this listed items ^ in atleast an outline -> link to function

**Comment by adborden** [comment]
@hkdctol do you want to give this a review? https://docs.google.com/document/d/1905dSQEfOuQaIs2_kPeAiYVdCwQfZ6DNwkxddkbriBU/edit#

**Comment by hkdctol** [comment]
@adborden made a few edits to google doc but looks good

**Comment by adborden** [comment]
Completed in https://github.com/GSA/datagov-deploy/pull/990
