### ISSUE TITLE
Migrate open-licenses page to resources.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#875]
## Details
https://docs.google.com/document/d/1CnGeDoaMZcFV0d42EA3ZD0QjnIsgWpVmhclFnI2AbrE/edit

https://project-open-data.cio.gov/open-licenses/ 
This is not currently on the resources page at all. Could go on https://resources.data.gov/tools/ under the Agency Data Inventories section.

## Acceptance Criteria
- [ ] Something

## Definition of Done
>the single statement you make upfront to determine what you need to be able to prove, to close the issue.

**Comment by hkdctol** [comment]
The substance will need updating, but for now it is migrating the content in the POD version of the open license page, to an Open Licenses page under resources.data.gov/tools

**Comment by crysacarter** [comment]
new file created migrated POD version to page within resources.data.gov/tools

**Comment by adborden** [comment]
Hey Crystal, thanks for this work! I'm going to re-open these issues and we'll close them once the PRs are merged, that way we know the work has been completely done, reviewed, and published.
