### ISSUE TITLE
Migrate open-standards page to resources.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#876]
## Details
https://docs.google.com/document/d/1CnGeDoaMZcFV0d42EA3ZD0QjnIsgWpVmhclFnI2AbrE/edit

https://project-open-data.cio.gov/open-standards/
Add to standards page under "Communities"

## Acceptance Criteria
- [ ] Something

## Definition of Done
>the single statement you make upfront to determine what you need to be able to prove, to close the issue.

**Comment by hkdctol** [comment]
It's not migrating the page but the standards listed and most
of the standards have already been included in resources.data.gov. The ones missing are:
https://www.ietf.org/
https://www.w3.org/
http://www.unece.org/cefact/about.html

They could be included under Communities in:
https://resources.data.gov/standards/

**Comment by hkdctol** [comment]
Note this is just moving the three standards that were left out originally and including them in resources.data.gov/standards

**Comment by crysacarter** [comment]
three standards that were left out have been added to file under communities.  Pull request created.
