### ISSUE TITLE
Migrate glossary from POD to resources.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#877]
## Details
https://docs.google.com/document/d/1CnGeDoaMZcFV0d42EA3ZD0QjnIsgWpVmhclFnI2AbrE/edit

3. https://project-open-data.cio.gov/glossary/
There is a link from https://resources.data.gov/tools/ for a Glossary, but the text is on this POD page, so needs to be transferred to resources page.

Many of them have a "sources" link which are mostly dead. Keep a list of the sources links, so we have a list that we can track down in the future.

## Acceptance Criteria
- [ ] Something

## Definition of Done
>the single statement you make upfront to determine what you need to be able to prove, to close the issue.

**Comment by hkdctol** [comment]
@crysacarter can you remind - you have the Sources with the links, correct? In which case it is simply migrating the definitions from POD page to a Glossary under resources.data.gov/tools

**Comment by crysacarter** [comment]
I started a document with the term, the linked source, and a notation on
whether that source needs replaced.

**Comment by crysacarter** [comment]
branch: 
https://github.com/GSA/resources.data.gov/tree/crysacarter-patch-5

content written - pull request glossary.md
