### ISSUE TITLE
Migrate Open Data Engagement Guidance from /press to resources.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#879]
## Details
https://docs.google.com/document/d/1CnGeDoaMZcFV0d42EA3ZD0QjnIsgWpVmhclFnI2AbrE/edit

Last part of [POD page](https://project-open-data.cio.gov/) should be moved to Resources -> Guidance -> Open Data Engagement Guidance as its own page.

starting with:
> ### Open Data Engagement Guidance

And ending with:

> ### Seek ways to maintain communication with members of the community
>
> Maintaining communication with the community that is created from an open data event has been among the most challenging aspects of agency public engagement in open data. In most cases, the communication post event is concentrated in the blog posts, media coverage, and social media activity immediately following the event. The events that have been most successful in continuing communication with the community result in some type of clearly identified post event activity, such as a new website focused on the open data issue that was the topic of the event. A dedicated website for sharing new content or communication within the community, however, can succeed only with dedicated resources for maintaining the website and taking responsibility for keeping it current and maintaining the level of community communication. In other cases, identifying a tangible goal at the beginning of the open data event such as a subsequent pilot project or other next steps with commitments from participants to contribute on a specific effort after the open data event can ensure that the interaction from the open data event continues.

## Acceptance Criteria
- [ ] Something

## Definition of Done
>the single statement you make upfront to determine what you need to be able to prove, to close the issue.

**Comment by hkdctol** [comment]
The task here is simply migrating the content re open data engagement in the last part of the POD main page. It could go under https://resources.data.gov/guidance/

**Comment by crysacarter** [comment]
file created resources/guideance/open-data-engagment-guidance.md, pull request created - crysacarter-patch-4 branch

**Comment by adborden** [comment]
Merged :+1:
