### ISSUE TITLE
Decommission CRM

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#880]
## Details
- Redirect CRM forms on www.data.gov to the "main" contact form which forwards to the datagov@ email alias.

## Acceptance Criteria
- [ ] Something

## Definition of Done
>the single statement you make upfront to determine what you need to be able to prove, to close the issue.

**Comment by hkdctol** [comment]
Right now three forms go to CRM

Reporting an issue: https://www.data.gov/issue/
Submit a data story: https://www.data.gov/story
Make a data request: https://www.data.gov/data-request/

We want these forms to redirect to
https://www.data.gov/contact#question

**Comment by adborden** [comment]
We've disabled the forms that feed into CRM, so no _new_ issues should be getting created. Still need to come up with a plan for how we need to shut this down.

**Comment by adborden** [comment]
Closing this, since the forms were redirected.

https://github.com/GSA/datagov-deploy/issues/1138 has the plan for decommission.
