### ISSUE TITLE
Load PyCSW from upstream ckanext-spatial

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#892]
## User Story
As a developer, I want to use the existing CKAN to PyCSW loading provided by ckanext-spatial so that I don't need to maintain a fork of PyCSW.

## Details
https://github.com/GSA/datagov-deploy/issues/608#issuecomment-468928933

## Acceptance Criteria
- [ ] CKAN to PyCSW load job is configured to use ckanext-spatial
- [ ] https://github.com/GSA/pycsw repo is archived

**Comment by nickumia-reisys** [comment]
No more pycsw,
- https://github.com/GSA/data.gov/issues/3182
