### ISSUE TITLE
Upgrade Ansible to 3.x

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#893]
## User Story
As an operator, I want to use a supported Ansible version so that I have access to the latest bug fixes and have less Ansible work-arounds to maintain

## Acceptance Criteria
- [ ] BSP environments are update
- [ ] CI environments in our Ansible roles are updated

**Comment by mogul** [comment]
We'll evaluate the timeline for 2.8 support ending in December and prioritize this issue depending on what we find.

**Comment by adborden** [comment]
Keeping an eye on https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html

**Comment by adborden** [comment]
Ansible-core 2.11 was released last week. which makes Ansible 2.8 no longer supported.

[Starting with 2.10](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html), Ansible has been split into two packages, ansible-core and ansible (community).

I think that means instead of upgrading to ansible 2.9, we should jump to ansible 3.0. ansible-core is more of a library while ansible provides all the functionality from 2.9. This should mean breaking changes only happen in major version bumps of Ansible which allows us to keep up to date on the latest Ansible version instead of staying back on the oldest supported Ansible version.

I'm going to update this ticket to jump to Ansible 3.x.
