### ISSUE TITLE
Migrate Proof Points from strategy.data.gov to resources.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#894]
## User Story
As a strategy.data.gov, owner I want the Proof Points from the Federal Data Strategy moved to resources.data.gov as case studies, so that a) we meet the requirements for resources.data.gov to have case studies and b) the proof points content lives in a more suitable place, separate from the Federal Data Strategy content.

## Details
Strategy team might be able to help with this, it might just be copy/pasting for the most part.

## Acceptance Criteria
- [ ] Each Proof Point is migrated as its own page
- [ ] Tags and tag pages are migrated
- [ ] Link to the tags page is added to the footer
- [ ] A section is created for Case Studies

**Comment by hkdctol** [comment]
In order of priority we have a bit more time on this one, would finish the POD migration ones first.

**Comment by mogul** [comment]
@hkdctol and @philipashlock we see [this Case Studies page](https://resources.data.gov/case-studies/)... Does that represent the outcome of this work or is there more to do?

**Comment by mogul** [comment]
@philipashlock says he's going to try to work on this soon; there's a stub in place that needs to be fleshed out.

**Comment by mogul** [comment]
@philipashlock can you give us any updates on how this is going?

**Comment by mogul** [comment]
Phil is working on this again and is hoping to finish it this week.

**Comment by mogul** [comment]
Phil's looking for help catching up to the current Jekyll layout, will likely look for a pair. The actual work isn't that involved once he's on top of that.

**Comment by philipashlock** [comment]
The initial work to migrate the content is in the `proof-points-migration` [branch](https://github.com/GSA/resources.data.gov/tree/proof-points-migration), waiting on some feedback to determine how much more work is needed before the first push live with the migrated content. 

Previews
- https://cg-f5a56614-c88e-470c-9f06-ff5fe2d4c98a.app.cloud.gov/preview/gsa/resources.data.gov/proof-points-migration/proof-points/
- https://cg-f5a56614-c88e-470c-9f06-ff5fe2d4c98a.app.cloud.gov/preview/gsa/resources.data.gov/proof-points-migration/proof-points/tags/

We can then remove content from strategy.data.gov and close out https://github.com/GSA/data-strategy/issues/183

**Comment by mogul** [comment]
Phil's making progress here and thinks remaining problems are mostly CSS; should complete soon.

**Comment by jbrown-xentity** [comment]
This is complete.
