### ISSUE TITLE
Address partition size and setup on EC2 instances

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#90]
We would like to increase the size of our log volumes to accommodate more logs locally on the machine. Today the volume sizes are fixed as part of the AMI. We need to address best strategy for how we can specify larger volumes (either manually through BSP tickets or automated through infrastructure as code).

**Comment by kvuppala** [comment]
On the new AMI with new hardening,  we need to optimize the log partition size

**Comment by dano-reisys** [comment]
there's an issue with the /var/log partition that has been created for the openstack hardened ami, figuring it out now.
