### ISSUE TITLE
Ansible smoke tests with uri module should use validate_certs=yes

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#900]
We use smoke tests in our playbooks to assert that web services are up and running using the [Ansible uri module](https://docs.ansible.com/ansible/latest/modules/uri_module.html). The module fails with:
```
Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
```

This is unexpected because the certificate is a GSA signed certificate installed to the well-known `/etc/ssl/certs/ca-certificates.crt` location.

## How to reproduce

1. `ansible -m uri -a 'url=https://crmweb1d.dev-ocsit.bsp.gsa.gov status_code=200' crmweb1d.dev-ocsit.bsp.gsa.gov`

## Expected behavior

Success, 200 status code.

## Actual behavior

SSL certificate verify failure.

**Comment by nickumia-reisys** [comment]
No more Ansible,
- https://github.com/GSA/data.gov/issues/3710

Our current smoke tests use `curl` which automatically fails if [certificates are expires (or otherwise bad)](https://stackoverflow.com/a/62115626).
