### ISSUE TITLE
Large number of 4xxs on catalog

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#904]
Almost every day we see alert emails from AWS CloudWatch that the number of 400s is above 20 within a one minute interval. The notifications are `awscloudfront-AWS-CloudFront-High-4xx-Error-Rate`.

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by adborden** [comment]
At one point, I think we thought these were related to Google and other search engines crawling the site and hitting deleted duplicates. There was also an issue at one point with harvest urls `/harvest/<guid>` returning a 400 for some reason. I thought the harvest URLs were fixed at some point.

**Comment by adborden** [comment]
I didn't realize before, but CloudFront is in the OPP account, so we can easily inspect and adjust the thresholds.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
