### ISSUE TITLE
PyCSW keywords jobs run multiple times by supervisor

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#909]
The pycsw keywords jobs are pretty quick. Supervisor sees this fast exiting and tries to run them again, but shouldn't.

## How to reproduce

1. ssh catalog-harvester2
1. sudo supervisorctl start pycsw-keywords-all
1. sudo supervisorctl status

## Expected behavior

Process exited successfully.

## Actual behavior

FATAL process exiting too quickly.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3182
