### ISSUE TITLE
Upgrade PHP applications to use PHP 7.3

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#919]
## User Story
As an operator, I want the PHP applications to run on PHP 7.3.x so that they have the latest security fixes and the longest supported lifetime.

## Details
https://www.php.net/supported-versions.php

This should include all the PHP applications:
- CRM
- Dashboard
- WordPress

## Acceptance Criteria
- [ ] Application development environments and tests are updated
- [ ] Deployment playbooks are updated

**Comment by adborden** [comment]
For this task, you'll want to first test the PHP changes locally in these repositories:

- [CRM](https://github.com/GSA/open311-simple-crm) ([with docker-compose PR](https://github.com/GSA/open311-simple-crm/pull/38))
- [Dashboard](https://github.com/GSA/project-open-data-dashboard) (@pburkholder added docker-compose already)
- [WordPress](https://github.com/GSA/datagov-wp-boilerplate) ([with docker-compose PR](https://github.com/GSA/datagov-wp-boilerplate/pull/25))

Then, we'll want to update the Ansible playbooks which will be applied to the BSP environment.
- [CRM roles](https://github.com/GSA/datagov-deploy/tree/develop/ansible/roles/software/crm)
- [Dashboard roles](https://github.com/GSA/datagov-deploy/tree/develop/ansible/roles/software/dashboard)
- [WordPress roles](https://github.com/GSA/datagov-deploy/tree/develop/ansible/roles/software/wordpress)

**Comment by adborden** [comment]
And it's probably to best to start with one of them (CRM) and take it all the way to production before moving on to the other apps.

**Comment by mogul** [comment]
I'm working on updating the dashboard role for the BSP environment and getting a little lost on how to test it. Let's meet early Monday to review, @adborden!

**Comment by mogul** [comment]
> And it's probably to best to start with one of them (CRM) and take it all the way to production before moving on to the other apps.

Per discussion today, it's easier to keep the common Ansible roles intact if we do them all at once, so I'm taking that path instead.

**Comment by adborden** [comment]
@mogul deployed this to production today.
