### ISSUE TITLE
Upgrade solr to latest LTS series

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#922]
## User Story
As an operator,  I want to use [LTS solr](https://solr.apache.org/downloads.html#about-versions-and-support) so that my solr cluster has a long runway for support and security updates.

## Details
Before getting too far into this, we should check that CKAN indeed supports 7.7.x. I've seem some anecdotal evidence that the most compatible version is 6.6.x.

## Acceptance Criteria
- [ ] datagov-deploy-solr supports 7.7
- [ ] datagov-deploy is updated to solr 7.7

**Comment by jbrown-xentity** [comment]
Current version is [8.6.3](https://github.com/apache/lucene-solr/releases/tag/releases%2Flucene-solr%2F8.6.3)

**Comment by adborden** [comment]
Yes, 8.x is current but we want an LTS release, not the latest.

At the moment, it looks like CKAN 2.9 is [not compatible with Solr 8](https://github.com/ckan/ckan/issues/5585) although the [support implementation has started](https://github.com/ckan/ckan/pull/5143).

**Comment by mogul** [comment]
We're still limited by CKAN only supporting through Solr 6.6.6 upstream.

**Comment by nickumia-reisys** [comment]
We have successfully [updated catalog](https://github.com/GSA/catalog.data.gov/pull/397) to use the latest LTS release of Solr.

There is an issue to finish updating inventory to use Solr 8 as well.  This issue has been superseded by https://github.com/GSA/datagov-deploy/issues/3697 for Inventory.

**Comment by hkdctol** [comment]
Closing this as we've updated Solr.
