### ISSUE TITLE
Catalog CKAN 2.8+ environment in sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#924]
## User Story
As an operator, I want a basic CKAN 2.8 environment in sandbox running catalog (and harvesters) so that I can identify a clear upgrade path with working software.

## Details

In the past, we tried to start with a development environment running all of our custom extensions and work toward 2.8. Instead, we should start with vanilla 2.8 and begin adding essential Data.gov functionality.

## Acceptance Criteria
- [ ] Terraform templates for ckan environment

**Comment by adborden** [comment]
Updated this issue to be about Catalog only, since Inventory has a new issue https://github.com/GSA/datagov-deploy/issues/1481

**Comment by kimwdavidson** [comment]
Work for DevSecOps team

**Comment by mogul** [comment]
Closing as a dupe of #1507
