### ISSUE TITLE
Update content on Open Government page

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#925]
https://www.data.gov/open-gov/ contains outdated content. It should reference the most recent laws and policy, including the Open Government Data Act. Links to {cities,counties,states}.data.gov should be updated or removed. Currently they're CNAME'd to www.data.gov

## How to reproduce

1. https://www.data.gov/open-gov/

## Expected behavior

Updated content

## Actual behavior

Outdated content and unhelpful links.

**Comment by crysacarter** [comment]
Am I creating a pull request for this or is it something I can directly edit since it is on wordpress? @hkdctol @adborden

**Comment by adborden** [comment]
Right, you can edit directly on WordPress.

**Comment by crysacarter** [comment]
Content updated and links to cities, counties, states removed.  There are links to CSV files of open data sites and list views.  How current are these listings?  Do we need to do any updating to them? @hkdctol

**Comment by crysacarter** [comment]
Full list csv and excel are updated.

List views will need to be done by returning tech person per @hkdctol
