### ISSUE TITLE
Keep log on hosts for ansible actions

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#931]
## User Story
As an operator, I want to keep a separate log on each host for any Ansible actions so that I can review and audit invocations of Ansible.

## Acceptance Criteria
- [ ] log is written to /var/log/ansible.log or similar
- [ ] log rotation is in place
- [ ] Ansible actions from jumpbox appear in the host log

**Comment by nickumia-reisys** [comment]
No more Ansible,
- https://github.com/GSA/data.gov/issues/3710

The same motivation does not exist for our current operations.
