### ISSUE TITLE
Host level http ping health check

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#938]
## User Story
As an operator, I want each host to have a health check service for HTTP based services so that I know when an individual host is having issues, even if over all, the service is still available across hosts.

## Details
Sometimes we see individual hosts in Inventory, Catalog, or Solr lose a connection or have some issue so the apps are no longer working. However, we don't always get an alert because other hosts are still available and serving requests.

## Acceptance Criteria
- [ ] Hosts have a configurable health check enabled
- [ ] Critical alerts go to datagovhelp@ or #datagov-alerts

**Comment by adborden** [comment]
Two options: 

1. New Relic Synthetics has some kind of "internal" version. I don't know if anyone at TTS is using this.
2. Shell script and cron to ping http, then report to an external service like OpsGenie

**Comment by adborden** [comment]
Geoplatform has also experienced this with CSW, where they will see intermittent 404s because a host is not behaving correctly.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
