### ISSUE TITLE
Improve alerting on Dashboard health

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#943]
## User Story
As an operator, I want to be alerted when Dashboard is in an unhealthy state so that I can proactively fix issues and respond as soon as possible.

## Details
Followup on issues discovered in https://github.com/GSA/datagov-deploy/issues/940

## Acceptance Criteria
- [ ] Logging is configured correctly so that errors go to a persistent log in /var/log (not the application directory which can be lost on deploy)
- [ ] Database errors appear in logs
- [ ] Database error triggers some notification in the UI, so it is obvious that things are not working correctly
- [ ] Index or status page exists for health check that returns a non-200 response when the Database or site is not working correctly
- [ ] Dashboard cron job logs to appropriate location

**Comment by adborden** [comment]
Removed references to CRM.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3502
