### ISSUE TITLE
not getting help requests sent through contact form 

### ISSUE THREAD

**Issue by crysacarter** [GSA/data.gov#944]
since the closure of the CRM, the number of help desk inquiries have slowed from about 30 a week to around 5.  Those were sent via email to datagov@gsa.gov
I had received another message on twitter about a user finding several broken links, so I sent a test through the contact form on the site. It did not go through. 
In the meantime, I'll advise him to email us, but I am concerned that users are submitting through the contact form and we are not getting those issues.

@hkdctol  @adborden 

Before closing:
- [ ] decide on next steps for addressing the [backlog](https://www.data.gov/wp/wp-admin/admin.php?page=flamingo_inbound&paged=1) of requests

## How to reproduce

1. https://www.data.gov/contact
1. Fill out contact form
1. Submit

## Expected behavior

Email notification comes through to datagov@

## Actual behavior

No email notification is received.

**Comment by adborden** [comment]
Thanks @crysacarter for looking into this. When you submit through the [Contact](https://www.data.gov/contact) form, do you get an error? Or is it that the form is successfully submitted but never received in the datagov@ inbox?

**Comment by adborden** [comment]
I can confirm that messages are getting sent with the wrong From address (wordpressweb1p.prod-ocsit.bsp.gsa.gov) and will likely be rejected due to the GSA DMARC policy.

**Comment by adborden** [comment]
This is still partially resolved. Email should be going through now.

The Flamingo plugin captured all the submissions to the Contact Us form, so the messages that weren't delivered are still available. https://www.data.gov/wp/wp-admin/admin.php?page=flamingo_inbound&paged=1

The last Contact Us message to datagov@ was back in January, so there's quite a few unanswered messages :( but at least they're not lost.

**Comment by adborden** [comment]
I think the next step here is to contact GSA Email/google groups to have them debug the datagov@ issue.

**Comment by adborden** [comment]
Tracking in INC2832086.

**Comment by adborden** [comment]
@hkdctol what do you want to do about the backlog of requests? https://www.data.gov/wp/wp-admin/admin.php?page=flamingo_inbound&paged=1

**Comment by adborden** [comment]
This seems to be why emails from wordpress are not going to datagov@ list. @hkdctol @crysacarter can either of you with admin rights check the banned list on datagov@ and datagovhelp@?

> Heard back from Google and they confirmed that no-reply@data.gov is on the banned list for the group. You can find it in the group settings under members -> all members and then the "banned" button near the top middle. If you click the checkbox next to the entry you can select "unban" at the top under Actions.

**Comment by crysacarter** [comment]
no-reply@data.gov has  been unbanned

**Comment by hkdctol** [comment]
@crysacarter 
I think this can be closed as the requests have been getting through, let us know if you think otherwise

**Comment by crysacarter** [comment]
resolved
