### ISSUE TITLE
Create page for the interagency Open Data Working Group on resources.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#947]
## User Story
As an agency data contact, I want a web page with information about the Open Data Working Group so that I can find when meetings are and tell others about it.

## Details
Information that would be useful to include.

- how to subscribe to the listserv
- meeting details (when, where, what, call-in details)
- calendar invite

## Acceptance Criteria
- [x] Information exists on a single page on resources.data.gov
- [x] Page is linked from _TBD_

**Comment by hkdctol** [comment]
This was completed in the last release for resources.data.gov
