### ISSUE TITLE
Bump PyCSW

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#963]
## User Story
As a CSW user, I want PyCSW on the latest stable version so that I have access to the latest bugfixes and features.

## Details
2.4.1 was published recently.

## Acceptance Criteria
- [ ] Branch exists in GSA/pycsw with our patches applied to 2.4.1
- [ ] Branch is deployed to all environments

**Comment by adborden** [comment]
[datagov/v2.4.1](https://github.com/GSA/pycsw/compare/2.4.1...GSA:datagov/v2.4.1) has been created.

**Comment by nickumia-reisys** [comment]
No more pycsw,
- https://github.com/GSA/data.gov/issues/3182
