### ISSUE TITLE
Update SSP for Jenkins

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#967]
## User Story
As an operator, I want usage of Jenkins documented in the System Security Plan so that I know how information flows in/out of Jenkins and how it should be configured.

## Details
Jenkins is mentioned briefly  in the SSP.

## Acceptance Criteria
- [x] Network and system diagrams updated
- [ ] ISSO & ISSM sign off

**Comment by FuhuXia** [comment]
Is there a link to the existing System Security Plan?

**Comment by adborden** [comment]
Let me know if you have trouble accessing. The doc is owned by our ISSO https://drive.google.com/file/d/110hUAi5gmJ5sGMkNMWefssQBOKhn2wLx/view

**Comment by FuhuXia** [comment]
No access. If granting access is a hassle, we can work on an offline copy, or, assign the story to whoever has access.

**Comment by hkdctol** [comment]
@FuhuXia I provided REI names to our ISSO Lynnette Jackson, so she should provide you access to the document. You can cc me in an email requesting.

**Comment by adborden** [comment]
Original diagrams are available in [drive](https://drive.google.com/open?id=0B2PJMJtPsLN6YUlWblBjUmk4dGc).

**Comment by kvuppala** [comment]
Updated the SSP with new system and network diagram.

**Comment by adborden** [comment]
Diagram available https://drive.google.com/open?id=1PXLeRvxAsHNztkJRvo-YGt07DpIIkw6H
