### ISSUE TITLE
Update JQuery to 3.4.1 on all applications

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#972]
https://cm-jira.usa.gov/browse/ACR-37

These applications are running old versions of JQuery. They should be updated to the latest (3.4.1).

- [x] https://github.com/GSA/data-strategy
- [x] https://github.com/GSA/us-data-federation
- [x] https://github.com/GSA/project-open-data-dashboard
- [x] https://github.com/GSA/open311-simple-crm
- [x] https://github.com/GSA/datagov-wp-boilerplate
- [x] https://github.com/GSA/catalog-app

## How to reproduce

1. Open URL in your browser
1. Right click, "view source"
1. Ctrl+f "jquery"

## Expected behavior

JQuery is an up to date version (3.4.1)

## Actual behavior

JQuery is an older version.

**Comment by mogul** [comment]
@adborden this all went to production already, right?

**Comment by adborden** [comment]
Probably not all of them. Catalog hasn't even gone to develop yet. I will try to move this forward today...

**Comment by adborden** [comment]
This has been deployed to production.
