### ISSUE TITLE
Update contact information for partner teams and support

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#974]
## User Story
As a Data.gov team member, I want a [contact list](https://docs.google.com/spreadsheets/d/1Z9Zpr1mpx-65i_fH2VTbVofPtidpLZs5cnkO0Jz53Vc/edit#gid=0) for anyone or any team so that I know who and how to contact someone for anything related to the operation of Data.gov.

## Details
Data.gov works with several other people/teams for the operation of Data.gov. BSP support, GSA DNS, GSA Networking and SecOps, etc.

## Acceptance Criteria
- [ ] [Contact information](https://docs.google.com/spreadsheets/d/1Z9Zpr1mpx-65i_fH2VTbVofPtidpLZs5cnkO0Jz53Vc/edit#gid=0) is updated

**Comment by hkdctol** [comment]
Added more information. We will keep as a google doc but this item can be considered completed/closed.

**Comment by hkdctol** [comment]
Going to mark as done for now.
