### ISSUE TITLE
Harvester sources cleanup

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#975]
## User Story
As a Data.gov Product Owner, I want all of our valid harvest sources to be scheduled automatically, so that all sources are harvested regularly and datasets are kept up to date.

## Details
When we halted sources and re-activated them, we didn't confirm with Agency POCs if the source was still valid.

Likely things are still set as manual that are not obsolete and should be made automatic.

## Acceptance Criteria

- [x] Confirm that deleting a harvest source will properly remove the datasets
- [x] Obsolete sources are removed
- [x] All valid sources are scheduled as automatic unless there is some documented exception

**Comment by hkdctol** [comment]
We recently completed a thorough review of harvest sources and organizations and deleted obsolete ones.
