### ISSUE TITLE
Content audit and review*

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#976]
## User Story
As a Data.gov product owner, I want all the content on any Data.gov component (WordPress, Resources.data.gov, Digital.gov, etc) to be reviewed, re-organized, and/or archived so that our users have high quality, up-to-date information.

- WordPress
- Content on Digital.gov
- resources.data.gov
- labs.data.gov tools and resources

**Comment by mogul** [comment]
@hkdctol and @crysacarter: This Epic is listed as `In Progress`. Can you confirm that you two are still working on this, or if there's no more work to do?

**Comment by hkdctol** [comment]
@crysacarter has done a first pass but I will take a look too after annual leave.

**Comment by hkdctol** [comment]
Second review of spreadsheet completed. Reached out to agencies that may have view on current topics on front page. Set up a few meetings for next week to discuss with agencies involved.

**Comment by hkdctol** [comment]
This epic has been entered into Github projects https://github.com/orgs/GSA/projects/11/views/4
