### ISSUE TITLE
Hiring action for Data.gov PMO

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#980]
## User Story
As Data.gov PMO, we want to fill a vacant FTE for the program.

## Details
Our hiring action has moved up in queue, so it is active. Editing this old ticket for long term staffing to one for current hiring action.

## Acceptance Criteria
- [x] Draft objectives for position description
- [x] Complete set of documents for hiring action in consultation with TTS Hiring
- [x] Post vacancy
- [x] Review applications 
- [x] Candidate interviews
- [x] Select candidate and forward to HR

**Comment by hkdctol** [comment]
Documents required by HR have been finalized. Awaiting posting.

**Comment by mogul** [comment]
Still waiting on HR posting the vacancy.

**Comment by hkdctol** [comment]
Going to mark as Done as the engineering bucket hire has closed and we have candidates moving forward in the HR process.
