### ISSUE TITLE
Create a document describing the Data.gov program mission and its responsibilities

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#981]
## User Story
As a Data.gov team member, I want a document describing the Data.gov mission, what its responsibilities are and how it ties into the law so that I can make better day-to-day decisions to support that mission and Data.gov stakeholders.

## Acceptance Criteria
- [ ] Document exists listing mission and responsibilities

**Comment by hkdctol** [comment]
Draft has been provided to PMO members for review and edit.

**Comment by hkdctol** [comment]
link to document https://docs.google.com/document/d/18a0f7bVXiFHaBotkGPR-ILn2YMoZmCzC361ZwMV_pxg/edit?usp=sharing

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data.gov/issues/4354
