### ISSUE TITLE
Document the history of Data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#983]
## User Story
As a Data.gov team member, I want to know the history of Data.gov in a simple timeline, so that I can better understand how Data.gov got to where it is today.

## Acceptance Criteria
- [x] Simple timeline or list of milestones
- [x] Events are linked to laws, articles, or artifacts where possible

**Comment by adborden** [comment]
I think I've seen a power point or something somewhere.

**Comment by adborden** [comment]
This was requested in https://github.com/GSA/datagov-deploy/issues/867

**Comment by adborden** [comment]
here's a start https://docs.google.com/document/d/1H3yx1LrSNtuR9AkPNMs1gfhbILXB2xFKC00kM2CS7P4/edit

**Comment by hkdctol** [comment]
Draft has been shared with Data.gov team https://docs.google.com/document/d/1H3yx1LrSNtuR9AkPNMs1gfhbILXB2xFKC00kM2CS7P4/edit?usp=sharing
