### ISSUE TITLE
Update Data.gov email list descriptions

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#985]
## User Story
As a Data.gov team member, I want the email list descriptions to reflect the list's purpose so that I understand exactly what the list is used for and who might use it to contact us.

## Details
https://groups.google.com/a/gsa.gov/forum/#!aboutgroup/datagov

> General public support list. Anyone can use this for reporting dataset issues, requesting datasets, and general Data.gov inquiries. We provide this list as a general contact for the public.

https://groups.google.com/a/gsa.gov/forum/#!aboutgroup/datagovhelp

> Technical support list. Agency POCs use this to get support. We provide this list for any technical contact e.g. TLS certificates or DNS registry contact.

https://groups.google.com/a/gsa.gov/forum/#!aboutgroup/inventory-help
> Inventory help desk for agency users.

## Acceptance Criteria
- [x] List descriptions are updated

**Comment by hkdctol** [comment]
Updated the descriptions in google group view so that new team members will see descriptions of each group.
