### ISSUE TITLE
Disable INSPIRE extension for PyCSW

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#986]
@kalxas [notified](https://github.com/GSA/datagov-deploy/issues/608#issuecomment-535402303) us that the INSPIRE extension is enabled but no service metadata is populated. Additionally, it only applies to EU countries and doesn't make sense to be enabled.

INSPIRE can be [disabled](http://docs.pycsw.org/en/2.4.0/profiles.html#inspire-extension) in the pycsw.cfg.

## How to reproduce

1. https://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities

## Expected behavior

inspire_ds:ExtendedCapabilities is not included.

## Actual behavior

inspire_ds:ExtendedCapabilities is included in the response.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3182
