### ISSUE TITLE
Migrate WordPress to a static site

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#992]
https://docs.google.com/document/d/1VS2qLb8d24Icz7KLJft23KbDQK9WxuBmFbXiIq2etA4/edit#

**Comment by adborden** [comment]
in doc form https://docs.google.com/document/d/1VS2qLb8d24Icz7KLJft23KbDQK9WxuBmFbXiIq2etA4/edit#heading=h.cui1qvtcapew

**Comment by mogul** [comment]
We're closing this one in favor of #1356
